### ISSUE TITLE
Use arrow_dataset in C++

### ISSUE THREAD

**Issue by swhzzh** [apache/arrow#10110]
How to use arrow_dataset in C++ project? I tried several names for find_package in CMakeLists.txt, such as 'ArrowDataset', 'Arrow_Dataset', 'Arrow_datset', 'Arrow-Dataset', 'Arrow-dataset', but it doesn't work..

I have installed libarrow-dataset-dev in my ubuntu20

**Comment by westonpace** [comment]
I'm not sure if this helps but for a very minimal CMakeLists I do the following (I use conda so most of my libraries are in my conda home directory, including libarrow.so & libarrow_dataset.so)...

```
include_directories(${CONDA_HOME}/include)
include_directories(${CONDA_HOME}/include/python3.7m)
include_directories(${CONDA_HOME}/lib64/python3.7/site-packages/numpy/core/include)
link_directories(${CONDA_HOME}/lib64)
link_directories(${CONDA_HOME}/lib)
add_executable(read_csv read_csv.cc)
target_link_libraries(read_csv arrow)
target_link_libraries(read_csv arrow_dataset)
```

**Comment by swhzzh** [comment]
It seems that I cannot use find_package to find arrow_dataset directly, I need to specify the cmake prefix path to find it...

**Comment by wesm** [comment]
Let's open a Jira issue about improving our documentation about how to use various Arrow C++ packages in downstream CMake projects?
