### ISSUE TITLE
pq.write_to_dataset does not work with Windows paths

### ISSUE THREAD

**Issue by pspeter** [apache/arrow#10120]
The logic to construct these paths does not consider Windows paths:

https://github.com/apache/arrow/blob/be258f2aa646f28f71108332e84f5e3adf1d2637/python/pyarrow/parquet.py#L1967-L1978

Line 1972 tries to create directory with a forward slash, which causes an `OSError: [WinError 123]` in Windows.

**Comment by emkornfield** [comment]
Hi @pspeter,
I think this code path will get deprecated soon, you might want to test with `use_legacy_dataset=False` (if the missing features aren't a blocked).  Either way this does sound like a bug so opening a [JIRA](https://arrow.apache.org/community/) issue is probably worthwhile.
