### ISSUE TITLE
Deleting the _SUCCESS file after executing pq.ParquetDataset

### ISSUE THREAD

**Issue by alibabadoufu** [apache/arrow#10149]
Hi, 

I noticed that when I run code

`df = pq.ParquetDataset(fpaths).read().to_pandas()`

It will delete the _SUCCESS file in my original fpaths. May I know if this happened to anyone here?

**Comment by jorisvandenbossche** [comment]
Reading a dataset shouldn't delete any files. So if that happens, that's certainly a bug. 
Would you be able to provide a reproducible script?

**Comment by jorisvandenbossche** [comment]
@alibabadoufu Can you still reproduce this?
