### ISSUE TITLE
is pyarrow 3.0.0 stable?

### ISSUE THREAD

**Issue by pingdink** [apache/arrow#10170]
Hi 

wondering about this..

Is version 3.0.0 from pip stable?

Thank you!
![Screen Shot 2021-04-26 at 3 22 33 PM](https://user-images.githubusercontent.com/9258889/116158281-3ab8c600-a6a3-11eb-92da-181d4eeb8e21.png)

**Comment by jorisvandenbossche** [comment]
To answer your general question: yes, pyarrow 3.0.0 is stable. There are however specific parts of the library that are more experimental, and here you posted a screenshot of Arrow Flight. This is indicating that Arrow Flight is still unstable, although I am a bit unsure about whether this is still up to date or can be removed by now.

**Comment by pramitchoudhary** [comment]
Also had issues installing it using python3.7 without using `conda`. Virtual env using `venv`.
No problem with `pyarrow==2.0.0` on `python3.7`
```
    CMake Error at /home/pramit/TextAttack-WebDemo/venv/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find Arrow (missing: ARROW_INCLUDE_DIR ARROW_LIB_DIR
      ARROW_FULL_SO_VERSION ARROW_SO_VERSION)
    Call Stack (most recent call first):
      /home/pramit/TextAttack-WebDemo/venv/lib/python3.7/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      cmake_modules/FindArrow.cmake:419 (find_package_handle_standard_args)
      cmake_modules/FindArrowPython.cmake:46 (find_package)
      CMakeLists.txt:214 (find_package)


    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-rj0gveil/pyarrow/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    error: command 'cmake' failed with exit status 1

    ----------------------------------------
Command "/home/pramit/TextAttack-WebDemo/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rj0gveil/pyarrow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wum9rr1f-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pramit/TextAttack-WebDemo/venv/include/site/python3.7/pyarrow" failed with error code 1 in /tmp/pip-build-rj0gveil/pyarrow/
```

**Comment by kszucs** [comment]
Seems like pip is trying to install from the source tarball rather than using a wheel instead. What platform are you trying to install pyarrow on?

**Comment by pramitchoudhary** [comment]
> Seems like pip is trying to install from the source tarball rather than using a wheel instead. What platform are you trying to install pyarrow on?

This was on Linux - `Ubuntu 18.0.4`

**Comment by kszucs** [comment]
Pip should install one of the manylinux wheels in that case. Perhaps you could try to update pip itself and try installing pyarrow again.

**Comment by jorisvandenbossche** [comment]
Going to close this issue. If you still have problems with installing (but first ensure to upgrade pip), don't hesitate to further reach out here or on the user mailing list
