### ISSUE TITLE
ParquetWriter.write_table() in-memory usage

### ISSUE THREAD

**Issue by ritesh-malav** [apache/arrow#10206]
I has had a small query regarding `ParquetWriter.write_table()` method. If I have one parquetwriter open and I am adding a apache arrow table to it of 1GB let's say over 10 iterations. In that case wold the entire final parquet be loaded in-memory like entire 10GB or it will just load one single table of 1 GB in memory and keep on appending to parquetWriter ?

**Comment by westonpace** [comment]
`ParquetWriter` should not hold onto the table after the `write_table` call so as long as you are not holding onto it elsewhere it should free up and be destroyed which means you will need around 1GB in memory and not 10GB.
