### ISSUE TITLE
C Data Interface: which one is the offsets buffer?

### ISSUE THREAD

**Issue by sa-** [apache/arrow#10235]
Hey,

I'm trying to implement the C Data Interface in Julia. A column of Strings looks like this in memory:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1297369/116938172-9dddc600-ac6a-11eb-964d-8cb8ba4aa4dd.png">

There are 3 buffers. Correct me if I'm wrong but the first buffer is always the validity bitmap.
How do I know which one is the offsets buffer and which one is the data buffer?

https://arrow.apache.org/docs/format/CDataInterface.html#c.ArrowArray.buffers this link doesn't specify which one comes first. And the [columnar format spec](https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-layout) only says that there is an offsets and a data buffer, but doesn't necessarily say offsets is the 2nd buffer and data is the 3rd

Thanks!

**Comment by jorisvandenbossche** [comment]
See this table: https://arrow.apache.org/docs/format/Columnar.html#buffer-listing-for-each-layout So for variable sized binary (or string), the 2nd buffer are offsets and 3rd buffer is the data

**Comment by sa-** [comment]
Thank you very much!
