### ISSUE TITLE
issue installing arrow in R Studio

### ISSUE THREAD

**Issue by marianoirace** [apache/arrow#10437]
Hi, I'm trying to install arrow in R Studio in Windows and I get the following error message. It seems related to a mismatch between the c++ library and the R version I'm using. I tried installing in R version 4.0.4 and 3.6.3 and get the same message. Any ideas how to deal with this?

* installing *source* package ‘arrow’ ..
*** package ‘arrow’ successfully unpacked and MD5 sums checked** using staged installation
*** Arrow C++ libraries found via pkg-config
**** Warning: library version mismatch
**** C++ is 0.15.1 but R is 4.0.1
**** If installation fails, upgrade the C++ library to match**** or retry with ARROW_USE_PKG_CONFIG=false
PKG_CFLAGS=-DNDEBUG -DARROW_R_WITH_ARROWPKG_LIBS= -larrow 
** libs
g++ -std=gnu++11 -I"/opt/R/4.0.4/lib/R/include" -DNDEBUG -DNDEBUG -DARROW_R_WITH_ARROW -I'/local/common/r_home/marirace/R/x86_64-pc-linux-gnu-library/4.0/cpp11/include' -I/usr/local/include -fpic -g -O2 -c array.cpp -o array.o
In file included from array.cpp:18:0:.
/arrow_types.h:35:10: fatal error: arrow/c/abi.h: No such file or directory 
#include <arrow/c/abi.h> 
^~~~~~~~~~~~~~~
compilation terminated./
opt/R/4.0.4/lib/R/etc/Makeconf:181: recipe for target 'array.o' failed
make: *** [array.o] Error 1
ERROR: compilation failed for package ‘arrow’
*removing ‘/local/common/r_home/marirace/R/x86_64-pc-linux-gnu-library/4.0/arrow’
Warning in install.packages : 
installation of package ‘arrow’ had non-zero exit status

**Comment by nealrichardson** [comment]
The error message suggests two options:

```
**** If installation fails, upgrade the C++ library to match**** or retry with ARROW_USE_PKG_CONFIG=false
```

BTW this looks like Linux, not Windows.

If either/both of those options do not work for you, please open a JIRA issue.

**Comment by realzhang** [comment]
> Sys.setenv(ARROW_USE_PKG_CONFIG="false")
> install.packages('arrow')
