### ISSUE TITLE
Official way of using parquet in modern cmake

### ISSUE THREAD

**Issue by ghamarian** [apache/arrow#10469]
What is the official way of adding the targets using modern cmake? The only thing that worked for me is the following but not sure if it is the best way. I installed arrow using brew on mac. Vcpkg unfortunately does not work at the moment.

```
set(Parquet_DIR /usr/local/lib/cmake/arrow)

find_package(Arrow CONFIG REQUIRED)
find_package(Parquet CONFIG REQUIRED)
target_link_libraries(database PRIVATE arrow_shared parquet_shared)
```

**Comment by bkietz** [comment]
@ghamarian could you please [open a JIRA](https://issues.apache.org/jira/secure/CreateIssue!default.jspa) describing what you're trying to accomplish?

**Comment by ghamarian** [comment]
Thanks, did that. I guess this issue can be closed.

**Comment by wesm** [comment]
See also https://issues.apache.org/jira/browse/ARROW-13021
