### ISSUE TITLE
Doc update ? For Reading and Writing the Apache Parquet Format

### ISSUE THREAD

**Issue by E-HO** [apache/arrow#10492]
Hi,

Cannot submit a bug since it's not especially a direct issue but it's more something not complete or up to date in the documentation and especially https://arrow.apache.org/docs/python/parquet.html#reading-a-parquet-file-from-azure-blob-storage .

Maybe it could be possible to add some improvements ?

- The chapter "Writing to Partitioned Datasets" still presents a "solution" with "hdfs.connect" but since it's mentioned as deprecated no more a good idea to mention it.
- The chapter "Reading a Parquet File from Azure Blob storage" is based on the package "azure.storage.blob" ... but an old one and the actual "azure-sdk-for-python" doesn't have any-more methods like get_blob_to_stream(). Possible to update this part with new blob storage possibilities, and also another mentioning the same concept with Delta Lake (similar principle but since there are differences ...)
- There is a chapter for "Reading from Partitioned Datasets", that's great ... but works only with a local storage and adding a Data Lake URL to a recursive folder don't work, missing the ability to read partitioned parquet files from Cloud

Thanks,

**Comment by jorisvandenbossche** [comment]
Good points, thanks for noting them!

> There is a chapter for "Reading from Partitioned Datasets", that's great ... but works only with a local storage and adding a Data Lake URL to a recursive folder don't work, missing the ability to read partitioned parquet files from Cloud

This last one I don't fully understand. Normally with passing a URI (eg for "s3://..." we certainly have tests) for a supported file system, or with passing a path and a filesystem object, reading a partitioned dataset form the cloud should work. Can you explain a bit more what doesn't work?

**Comment by E-HO** [comment]
Hi, Thanks for the quick intervention.

For the third I mean that it's obviously working with a local parquet file system including partition :
`local_source = "_FILE_SYSTEM_ON_LOCAL_DRIVE\PARTITION_Month=08\Day=01"
dataset = pq.ParquetDataset(local_source)
result = dataset.read()`

But with same the most basic approach with a Azure Data-Lake storage account it doesn't work : 
`dataset = pq.ParquetDataset("https://_ACCOUNT_.blob.core.windows.net/__CONTAINER__/PartitionMonth%3D01/Day%3D01?sp=_AZURE_SAS_KEY_URL__")
result = dataset.read()`

The error obtained is "raise OSError('Passed non-file path: {}'"

**Comment by westonpace** [comment]
> Cannot submit a bug since it's not especially a direct issue but it's more something not complete or up to date in the documentation
Please do create a JIRA issue.  Arrow uses JIRA to track all changes (bugs, doc change, CI improvements, new features) and so you don't have to worry about that.  These sound like valid concerns and a JIRA issue would be acceptable.

> There is a chapter for "Reading from Partitioned Datasets", that's great ... but works only with a local storage and adding a Data Lake URL to a recursive folder don't work, missing the ability to read partitioned parquet files from Cloud

That chapter is talking about the legacy datasets API (ParquetDataset).  You may be better served reading up on the new datasets API: https://arrow.apache.org/docs/python/dataset.html#dataset .  The new API will accept a URL as a path although it currently only has first-class support for S3 and HDFS.  To use Azure data lake directly you would need to create a filesystem for it as the datasets API needs to be able to list files, search for files, create files, etc.

That being said, you might be able to make something work by using the fsspec filesystem (https://arrow.apache.org/docs/python/filesystems.html#using-fsspec-compatible-filesystems) and https://github.com/dask/adlfs .

**Comment by jorisvandenbossche** [comment]
> The new API will accept a URL as a path although it currently only has first-class support for S3 and HDFS

Small correction: it will accept a URI, but not a URL (although wikipedia says that they are often used interchangeably). Meaning: we don't support reading from a http(s) URL, in contrast to typical pandas or R functions do for single files).
Also the old interface supports such URIs. 

There is an open issue to also support https/ftp urls: https://issues.apache.org/jira/browse/ARROW-7594

But @westonpace is correct: although we generally support cloud URIs, we only have built-in support for S3 and HDFS. But we accept fsspec-based filesystems as well, and so using the `adlfs` package for now is the way to go to read data from Azure.

I created https://issues.apache.org/jira/browse/ARROW-13034 for your first two bullet points.

**Comment by E-HO** [comment]
Nice. 

Sorry for the doc who is legacy, a bit hard to discover like that. A suggestion to add something more clear like a "deprecated flag, see the page XXX" ?

In the same time I was thinking to use "DataLakeServiceClient" Azure SDK to get the list of the parquet files in the subfolder in order to provide it as file list to recreate a "filesystem" but without being sure that will be possible. With dask/adlfs could be a possibility to test ... and maybe until a more direct integration of Azure can be a possibility !?

**Comment by jorisvandenbossche** [comment]
> With dask/adlfs could be a possibility to test

I think using `adlfs` is the best option at the moment to directly read files from Azure Blob Storage / Azure Data Lake with pyarrow.

I am updating the example in https://github.com/apache/arrow/pull/10548
