### ISSUE TITLE
Custom schema for Parquet files

### ISSUE THREAD

**Issue by Pand9** [apache/arrow#10543]
I want to use full capability of Parquet from Python. It seems I have to go through PyArrow, whch doesn't seem to expose extra schema options. I can't find any other API unfortunately. Is there some API to provide the raw parquet schema?
Specifically I want to set "delta binary packed encoding" for my column, but in general I'm interested in flexibility for the future use-cases.

**Comment by westonpace** [comment]
> It seems I have to go through PyArrow
Is there a reason for this?  There are non-arrow libraries available for parquet, even some in python, e.g. fastparquet.  Or is there some other reason you have to use pyarrow?

> Is there some API to provide the raw parquet schema?
Pyarrow has some bindings for reading the schema.  However, it seems like you are interested in writing the schema.  I do not believe anyone has added this today.

> Specifically I want to set "delta binary packed encoding" for my column, but in general I'm interested in flexibility for the future use-cases.

Pyarrow depends on a C++ parquet library that is included in the Arrow git repository but also sort of stands alone.  This C++ library does not have full support for "delta binary packed encoding" [ML discussion](https://lists.apache.org/thread.html/ra5a2f4ffc23aadf51508589bbb5510959ad420cc965b88dff6c815b1%40%3Cdev.arrow.apache.org%3E) although there is some implementation there.  The Java parquet library (parquet-mr) does have support but it doesn't allow you to force the encoding type [ML discussion](https://lists.apache.org/thread.html/r7235fb021487bde5361c915003c0a2d17e35178a00279f36562f2b43%40%3Cdev.parquet.apache.org%3E).

**Comment by Pand9** [comment]
Thanks, I wasn't aware it's so little supported. I'm using the rust one, which supports it and lets me set it explicitly.
I'm trying to send files between rust and python, both ways. Pyarrow seemed most active and maintained.
