### ISSUE TITLE
Quotation Marks around CMake Variable? 

### ISSUE THREAD

**Issue by bridgream** [apache/arrow#10555]
https://github.com/apache/arrow/blob/f1e3c2e557bb3622b203fb270bf0329f53f1e617/cpp/src/arrow/io/CMakeLists.txt#L33
Should this line be `if(NOT ("${ARROW_SIMD_LEVEL}" STREQUAL "NONE"))` where `${ARROW_SIMD_LEVEL}` be wrapped by quotation marks? Otherwise if `${ARROW_SIMD_LEVEL}` is empty (observed if processed with `ExternalProject_Add`), `STREQUAL` will compare `(` and `"NONE"`, leaving an unmatched right parenthesis.

**Comment by kou** [comment]
We use `SSE4_2` as the default `ARROW_SIMD_LEVEL`. Why does `ExternalProject_Add` set an empty string to it? Could you show the `ExternalProject_Add(...)` that reproduces the case?

**Comment by bridgream** [comment]
I wasn't able to reproduce the issue using the same code. The original code works in a loop test using the same code where I spotted the problem. Could be a cache issue.
