### ISSUE TITLE
ModuleNotFoundError: No module named 'pyarrow._orc'

### ISSUE THREAD

**Issue by laomagic** [apache/arrow#10699]
pip install pyarrow

pyarrow\orc.py
import pyarrow._orc as _orc
ModuleNotFoundError: No module named 'pyarrow._orc'

**Comment by westonpace** [comment]
The pip builds of 4.0.0 and 4.0.1 do not include orc.  You will need to install from `conda` or build from source.  Please also see: https://stackoverflow.com/questions/61382301/python-module-pyarrow-has-no-attribute-orc
