### ISSUE TITLE
[R] Trouble Installing Package on Windows with S3 support

### ISSUE THREAD

**Issue by JrmFRL** [apache/arrow#10764]
Hello, 

I am meeting troubles to install the R arrow package with the S3 support.
Shouldn't be yet any issues since I can read from the [vignette](https://arrow.apache.org/docs/r/articles/fs.html):
> In Windows and macOS binary packages, S3 support is included.  

However after installing arrow from the CRAN (`install.packages('arrow')`) as recommended, I do not have the S3 support available : 

> arrow::arrow_with_s3()
[1] FALSE
 
Still didn't work after I un- and re-installed last release.
I have not be able to find any way to fix it. Any idea ?
Thank you!

**Comment by thisisnic** [comment]
Hi @JrmFRL , sorry to hear you've been having problems with installing on Windows.  I don't suppose you'd mind popping over to our JIRA, where we manage these things, and I can help diagnose the issue there?  I've opened a ticket with details of your problem and have added a comment with the first step of working out what's going on: https://issues.apache.org/jira/browse/ARROW-13422

**Comment by JrmFRL** [comment]
Hi @thisisnic 
Switched to Jira, thanks!

**Comment by JrmFRL** [comment]
Solved. 
Reason : S3 support on Windows is only available for R >= 4.0
