### ISSUE TITLE
Capacity error: array cannot contain more than 2147483646 bytes, have 2147489180

### ISSUE THREAD

**Issue by lz19970205** [apache/arrow#10776]
When I tried to import data into ClickHouse, I encountered this error. My data is stored in the orc file.
I read the source code of ClickHouse and I noticed that it use this library to read orc file.
I also read the source code of Apache arrow and I thought it was because there was a very large string in the data? So I removed some columns and tried to import again. But I encountered this error again.

Because the data is related to the user's private information, so I can't provide it.
Does anyone know the possible reason? Or should I post this issue under ClickHouse project?

**Comment by westonpace** [comment]
List arrays and string arrays cannot have more than 2GB.  This is because they are represented as two arrays.  A values array and an offsets array.

```
        0  1  2  3  4  5  6  7  8  9  10 11 12 13       
Values: s  t  r  i  n  g  1  s  t  r  i  n  g  2
Offsets: 0, 7, 13
```

The offsets point to the beginning (and end) of each string.  Since the offsets array is int32 the maximum offset is 2GB and so the values array cannot have more than 2GB bytes of values.

Normally, when this limit is hit, a good workaround is to split your data into smaller record batches (you can still represent it as a single table) but it will depend on what you are trying to do.

**Comment by lz19970205** [comment]
> List arrays and string arrays cannot have more than 2GB. This is because they are represented as two arrays. A values array and an offsets array.
> 
> ```
>         0  1  2  3  4  5  6  7  8  9  10 11 12 13       
> Values: s  t  r  i  n  g  1  s  t  r  i  n  g  2
> Offsets: 0, 7, 14
> ```
> 
> The offsets point to the beginning (and end) of each string. Since the offsets array is int32 the maximum offset is 2GB and so the values array cannot have more than 2GB bytes of values.
> 
> Normally, when this limit is hit, a good workaround is to split your data into smaller record batches (you can still represent it as a single table) but it will depend on what you are trying to do.

Thanks for the reply!
So you mean there is a big array in my data?

**Comment by lz19970205** [comment]
> List arrays and string arrays cannot have more than 2GB. This is because they are represented as two arrays. A values array and an offsets array.
> 
> ```
>         0  1  2  3  4  5  6  7  8  9  10 11 12 13       
> Values: s  t  r  i  n  g  1  s  t  r  i  n  g  2
> Offsets: 0, 7, 14
> ```
> 
> The offsets point to the beginning (and end) of each string. Since the offsets array is int32 the maximum offset is 2GB and so the values array cannot have more than 2GB bytes of values.
> 
> Normally, when this limit is hit, a good workaround is to split your data into smaller record batches (you can still represent it as a single table) but it will depend on what you are trying to do.

I see. So you mean there is a huge array in my data?
But I have already converted all array types to string types and removed the big string I thought.
I verified the maximum length of all string columns in my data and I found that the maximum length is only 36000. This is far from reaching the 2GB limit.

I will split data into smaller piece and try again.

**Comment by westonpace** [comment]
The length we are talking about here is the total length (in bytes) of a column.  So, for example, if you have a column with 1 million strings and each string has 36,000 characters that would be a total length of 36 billion which would be too large.

**Comment by lz19970205** [comment]
In this case, this error may occur on any column and not just the string column, right?

**Comment by westonpace** [comment]
> So the library will convert the data of one column to an array and process it?
In Arrow a column is always an array.

>  In this case, this error may occur on any column and not just the string column, right?
For this particular error the column's data type would have to be string, variable sized list, or fixed size list I believe.

**Comment by lz19970205** [comment]
So what are the restrictions if the column type is int or other basic types (float, double...)?
If a column always contains an array to indicate the offset, I think it maybe cannot contain more than 2^31 - 1 elements?
In other words, the data cannot contain more than 2^31 -1 rows?

**Comment by westonpace** [comment]
Correct.  A single array (regardless of type) may not contain more than 2^31 - 1 elements.  String & List arrays cannot contain more than 2^31 - 1 bytes (these types are more restrictive).

In Arrow, this limitation is usually fixed by using multiple arrays in a single chunked array or multiple record batches in a single table.

**Comment by lz19970205** [comment]
Got it!
Thanks a lot!

**Comment by fingoldo** [comment]
> a good workaround is to split your data into smaller record batches (you can still represent it as a single table)

Hi, is it possible to specify these custom record batch sizes when saving a pandas dataframe into parquet? Most frustrating fact is that df gets saved without any warnings, but can't be read back due to this Capacity error.

**Comment by westonpace** [comment]
> Hi, is it possible to specify these custom record batch sizes when saving a pandas dataframe into parquet? Most frustrating fact is that df gets saved without any warnings, but can't be read back due to this Capacity error.

I believe the original question was about orc.  I would expect the parquet reader to automatically break the returned data into smaller batches in this case.  What operation are you running when you encounter this error?  Is it the same error as posted in the title?

**Comment by fingoldo** [comment]
> en I tried to import data into ClickHouse, I encountered this error. My data is stored in the orc file.
> I read the source code of ClickHouse and I noticed that it use this library to read orc file.
> I also read the source code of Apache arrow and I thought it was because there was a very large string in the data? So I removed som

Oh I'm sorry, indeed the topic starter was asking about orc format. In my case, I was dumping a pandas dataframe with 3M records and, among others, 2 pretty "wide" text fields to the parquet file using the default engine - pyarrow in the case of pandas. But the error message was exactly the same. Do you want me to create a reproducer?
