### ISSUE TITLE
How to read a boolean column in C++

### ISSUE THREAD

**Issue by romgrk-comparative** [apache/arrow#10788]
Hey, I was wondering what's the correct way to read a boolean value from an `arrow::Array`?

For `int64_t` types and `string` types we were able to figure out how to read them (example below), however for  boolean we're unsure how to read them correctly and how they're encoded. Is it individual bits in the whole `array->GetValues()` returned data?

```c++
// std::shared_ptr<arrow::Array> array;

// int64
const int64_t* view = array->GetValues<int64_t>(1,0);

// strings
const int32_t *offsets = array->GetValues<int32_t>(1, 0);
const char    *view  = array->GetValues<char>(2, 0);
```

It would also be nice to have that information available in the docs.

**Comment by lidavidm** [comment]
In all cases, you may prefer to downcast to the concrete Array subclass and use accessor methods. In this case that would be Int64Array, StringArray, and [BooleanArray](https://github.com/apache/arrow/blob/3f592a0a24432d3eee9f66081714e7cf4f9928f5/cpp/src/arrow/array/array_primitive.h#L76). BooleanArray has a Value() method that gets the value at a particular index, and of course all arrays have IsValid/IsNull methods.

Indeed, the encoding of a Boolean array is one boolean per bit. You can see this in the definition of `BooleanArray::Value` above. You'll have to take into account the offset as well in case the array is a slice. (Hence the zeroth value in an array lies at the `offset + 0`th bit.)

**Comment by romgrk-comparative** [comment]
Ok, thanks!
