### ISSUE TITLE
Getting an `std::istream` from an `arrow::io::InputStream`

### ISSUE THREAD

**Issue by pi-guy-in-the-sky** [apache/arrow#10844]
I'm currently working on a tool in C++ which needs to fetch data from an S3 bucket. Calling `arrow::fs::S3FileSystem::OpenInputStream` allows me to get an `arrow::io::InputStream` that can read from the file. However, an external library in my application needs to read from the file through an `std::istream`. Is there any way I can get an `std::istream` from an `arrow::io::InputStream`?

**Comment by westonpace** [comment]
No.  It also might be a bit tricky to build one effectively using just STL.  You could wrap the buffers in `stringstream` but that does a copy.  I think Boost has some [utilities](https://www.boost.org/doc/libs/1_73_0/libs/iostreams/doc/guide/generic_streams.html) which might help.  @pitrou Any ideas?

**Comment by pitrou** [comment]
No further idea. It seems the Boost page you linked to might help.

**Comment by pitrou** [comment]
We may also want to expose such a facility in Arrow, provided someone contributes it.
