### ISSUE TITLE
Null values in CSV file if values are quoted

### ISSUE THREAD

**Issue by anzej-curk** [apache/arrow#10892]
Hi team,

I have an example where I'm getting constantly errors. I have a regular CSV file with quoted values. The following example is reproducing my situation:

```python
import io
import pyarrow as pa
from pyarrow import csv

fp = io.BytesIO(b'"one","two","three"\n"1","2","3"\n"4","","6"')
fp.seek(0)
table = csv.read_csv(
        fp,
        convert_options=csv.ConvertOptions(
            column_types={
                'one': pa.int8(),
                'two': pa.int8(),
                'three': pa.int8(),
            },
	    strings_can_be_null=True,
            null_values=[""],
	    quoted_strings_can_be_null=True
        ))
```
With this approach, I'm getting an error
`pyarrow.lib.ArrowInvalid: In CSV column #1: CSV conversion error to int8: invalid value ''`
And I do not know how to list under `null_values` attribute strings that represent null values (I have tried with several values in `null_values` but without any luck). If CSV values are not quoted, then this is working completely fine, but if CSV values are quoted this approach is failing. Because I'm not a procedure of CSV files, I can not change CSV files.
Can you have any suggestions on how to solve this issue?

Thanks

**Comment by westonpace** [comment]
It appears quoted nulls are only allowed for string columns at the moment.  I agree this is not the behavior we want.  I have opened ARROW-13580 .

In the meantime a workaround may be to read the columns as string and then cast to int8.

```
table = csv.read_csv(
        fp,
        convert_options=csv.ConvertOptions(
	    strings_can_be_null=True,
            null_values=[""],
	    quoted_strings_can_be_null=True
        ))
new_columns = []
for column in table.columns:
    if column.type == pa.utf8():
        new_columns.append(pc.cast(column, pa.int8()))
    else:
        new_columns.append(column)
new_table = pa.Table.from_arrays(new_columns, names=table.column_names)
```

**Comment by anzej-curk** [comment]
Thanks for a quick reply. In meantime, I can use the solution that you have provided, just that this workaround can consume a little bit more memory (if the CSV files are really huge) compared to if the parser will deal with null values in process of parsing CSV files.

Thanks again and looking forward to using the end solution :).
