### ISSUE TITLE
Readback KeyValueMetadata from Field and Schema in pyarrow from file written in C++

### ISSUE THREAD

**Issue by dantrim** [apache/arrow#10935]
If I write a simple Parquet file using the script [simple-write-parquet.cpp](https://gist.github.com/dantrim/33f9f14d0b2d3ec45c022aa05f7a45ee), I expect to have a simple Parquet file with a single column `MyInt`. The script [simple-write-parquet.cpp](https://gist.github.com/dantrim/33f9f14d0b2d3ec45c022aa05f7a45ee) attempts to add `KeyValueMetadata` to the field `MyInt` with some dummy values. In the C++ code, if I do,
```c++
std::cout << field->ToString(true) << std::endl;
```
I see the expected return.
```
...
-- metadata --
foo: bar
bar: foo
```
and I expect that this metadata will be preserved in the output Parquet file.

However, when I attempt to read this file back using `pyarrow`, this field metadata key-value pair does not seem to exist:
```python
import pyarrow as pa
import pyarrow.parquet as pq

table = pq.read_table("test.parquet")
field = table.field("MyInt")
field.metadata # None!
```

Is there a way to retrieve from within `pyarrow` the `KeyValueMetadata` attached to both fields and schema (e.g. via the `WithMetadata` methods) from the C++ side writing out the Parquet files to disk?

Thanks!

**Comment by jorisvandenbossche** [comment]
When doing this in pure python, the field metadata gets preserved:

```python
import pyarrow as pa
import pyarrow.parquet as pq

f = pa.field("a", pa.int64(), metadata={'test': 'value'})
schema = pa.schema([f])
table = pa.table({'a': [1, 2, 3]}, schema=schema)

pq.write_table(table, "test_field_metadata.parquet")
table2 = pq.read_table("test_field_metadata.parquet")

# original table has the field metadata
>>> table.field('a').metadata
{b'test': b'value'}

# roundtripped table still has it
>>> table2.field('a').metadata
{b'test': b'value'}
```

So there is something that is done differently in your C++ example. I think this has to do with the saving of the Arrow schema in the Parquet FileMetaData or not. This is an option in the `ArrowWriterProperties`. In C++ it is set to False by default:

https://github.com/apache/arrow/blob/b220fea6900e964f8fab987e7dacd6ae38c15dca/cpp/src/parquet/properties.h#L661

but in Python we always enable it:

https://github.com/apache/arrow/blob/b220fea6900e964f8fab987e7dacd6ae38c15dca/python/pyarrow/_parquet.pyx#L1294-L1296

You can pass ArrowWriterProperties to the `parquet::arrow::WriteTable` function to enable store_schema in your example.

**Comment by dantrim** [comment]
Thanks @jorisvandenbossche! This was also [further clarified on SO](https://stackoverflow.com/questions/68778638/readback-keyvaluemetadata-from-field-and-schema-in-pyarrow-from-file-written-in).
