### ISSUE TITLE
Gandiva Using Problem

### ISSUE THREAD

**Issue by EdisonZiXing** [apache/arrow#11025]
Hello everyone , when i try to 
import pyarrow.gandiva
Error was raised as 'no module named gandiva'
Why i cant import'.pyx'?
python 3.8
Help me plz TAT

**Comment by westonpace** [comment]
That error message means that your version of pyarrow does not have gandiva support built in.  How did you install pyarrow?  The wheels available on pip (pypi) do not support gandiva.  The wheels available on conda do support gandiva.  Can you try installing with conda?  Or you can build a wheel from source following the instructions [here](https://arrow.apache.org/docs/developers/python.html).

**Comment by EdisonZiXing** [comment]
> That error message means that your version of pyarrow does not have gandiva support built in. How did you install pyarrow? The wheels available on pip (pypi) do not support gandiva. The wheels available on conda do support gandiva. Can you try installing with conda? Or you can build a wheel from source following the instructions [here](https://arrow.apache.org/docs/developers/python.html).

Thx bro，I uesd pip before.
conda install worked for me!
Appreciate!!!

**Comment by EdisonZiXing** [comment]
> That error message means that your version of pyarrow does not have gandiva support built in. How did you install pyarrow? The wheels available on pip (pypi) do not support gandiva. The wheels available on conda do support gandiva. Can you try installing with conda? Or you can build a wheel from source following the instructions [here](https://arrow.apache.org/docs/developers/python.html).

Here is another question I wanna consult about:
I'm trying to filter the dataframe with gandiva,and I uesd the Expression Tree with Python
But I can only get the index for the filtered data.How can I get the whole row?
Thanks a lot!!!
Looking forword to your reply,master!
