### ISSUE TITLE
Filter the dataframe with gandiva

### ISSUE THREAD

**Issue by EdisonZiXing** [apache/arrow#11034]
Here is another question I wanna consult about:
I'm trying to filter the dataframe with gandiva,and I uesd the Expression Tree with Python
But I can only get the index for the filtered data.How can I get the whole row?
Thanks a lot!!!
Looking forword to your reply,master!**

**Comment by emkornfield** [comment]
If you have indices from gandiva you could use [pyarrow.take](https://arrow.apache.org/docs/python/generated/pyarrow.compute.take.html) to collapse the filtered data.

**Comment by EdisonZiXing** [comment]
> If you have indices from gandiva you could use [pyarrow.take](https://arrow.apache.org/docs/python/generated/pyarrow.compute.take.html) to collapse the filtered data.

Thx for the reply bro! pyarrow.take() to get the data is a little bit slow for me.So I'm trying to find another method.I'm reading the source recently and found that gandiva can only get the indices back first, am I right?

**Comment by emkornfield** [comment]
I'm not sure.  You might try dev@  where there are more people familiar with that system.
