### ISSUE TITLE
ArrowFlight support for Julia

### ISSUE THREAD

**Issue by diegomestre2** [apache/arrow#11066]
HI,

I am considering ArrowFlight for our client-server protocol. However, I noticed that there is no support for Julia. Do you guys have any plans to provide that? If not, how difficult would it be to implement that ourselves?

Cheers,

Diego Tomé.

**Comment by emkornfield** [comment]
CC @quinnj 

I imagine a naive implementation would not be too hard assuming there is already a gRPC implementation available in Julia.  Both the C++ and Java implementations have made a lot of effort to avoid unnecessary memory copies which is slight more involved.

**Comment by quinnj** [comment]
Yes, I played around with using https://github.com/JuliaComputing/gRPCClient.jl to generate a gRPC client for arrow flight and got it minimally working; this was back before gRPCClient was officially "ready"/registered as a package though. Perhaps @tanmaykm can comment on whether he things gRPCClient.jl is "ready to use" or not yet. Then it should be pretty easy to get client support in Arrow.jl.

**Comment by tanmaykm** [comment]
Yes, gRPCClient.jl should be fairly stable now. Please file issues if you encounter any problems!
