### ISSUE TITLE
unsupported system page size

### ISSUE THREAD

**Issue by fatCatGm** [apache/arrow#11134]
enviroment：arm64 aarch64
python: anaconda2 python3.7

when i use this command（import pyarrow ） and i get a error（unsupported system page size）
How to solve this problem?
![image](https://user-images.githubusercontent.com/38717241/132932189-6b68ea07-0431-44bf-a9be-50c52a1f513d.png)

**Comment by emkornfield** [comment]
This is https://issues.apache.org/jira/browse/ARROW-13635

**Comment by fatCatGm** [comment]
thanks for your help,it really help me.
