### ISSUE TITLE
Multi_threads Or Using multi-cores of pyarrow

### ISSUE THREAD

**Issue by EdisonZiXing** [apache/arrow#11141]
Hello everyone，I'm trying to find the multi-cores way to process the data,but when I use **pyarrow.set_cpu_count** or **pyarrow.set_io_thread_count** to set a bigger int but the cost time basically no change. Is it caused by Python's GIL? How can I working out a parallel-working way ? Thx for replies!!!!!!

**Comment by westonpace** [comment]
I'm afraid you will need to explain in more detail what you are trying to do and what results you are expecting to get.  Some operations in Arrow-C++ (which pyarrow uses) will take advantage of multiple threads.  These operations are controlled by the functions you mentioned.  Mostly today this is in file parsing and decoding.  On the other hand, some functions are implemented completely in python (and thus subject to the GIL) and others are implemented in C++ and release the GIL but do not use multiple threads.

**Comment by EdisonZiXing** [comment]
> I'm afraid you will need to explain in more detail what you are trying to do and what results you are expecting to get. Some operations in Arrow-C++ (which pyarrow uses) will take advantage of multiple threads. These operations are controlled by the functions you mentioned. Mostly today this is in file parsing and decoding. On the other hand, some functions are implemented completely in python (and thus subject to the GIL) and others are implemented in C++ and release the GIL but do not use multiple threads.

Sorry master，I didn't clarify what I was trying to do.Here is the my problem: I'm trying to use gandiva to speed up the filter operations.But I dont know how to use multi-cpus to speed up gandiva. So I wanna find a way to acheive this goal. Looking for
