### ISSUE TITLE
Multi_threads Or Using multi-cores of pyarrow

### ISSUE THREAD

**Issue by EdisonZiXing** [apache/arrow#11151]
Sorry master，I didn't clarify what I was trying to do.Here is the my problem: I'm trying to use gandiva to speed up the filter operations.But I dont know how to use multi-cpus to speed up gandiva. So I wanna find a way to acheive this goal. 
Looking forward to your guide!!!

**Comment by emkornfield** [comment]
As noted on other question, writing dev@ for more visibility from engineers working on Gandiva would make sense.
