### ISSUE TITLE
Question: Can arrow be used to load a parquet file from an Azure blob store (abfs://) using Arrow cpp

### ISSUE THREAD

**Issue by oss-maker** [apache/arrow#11195]
I'm trying to read a parquet file from azure data lake storage gen 2 (abfss://) using the cpp sdk. 

If the above is not possible, if I am able to open a stream to the abfs storage, can this input stream be used as input to the parquet cpp reader?

**Comment by jorisvandenbossche** [comment]
The C++ filesystem implementation does not yet have support for Azure, so it's not possible to do this directly. 
There is an open issue about this: https://issues.apache.org/jira/browse/ARROW-2034

If you can open the file yourself and get a seekable stream, then probably yes: you can create a Parquet FileReader from a RandomAccessFile, see https://arrow.apache.org/docs/cpp/parquet.html#filereader
