### ISSUE TITLE
Gandiva Multi-cores Using and GPU Using Problem

### ISSUE THREAD

**Issue by EdisonZiXing** [apache/arrow#11278]
Hello everyone!Here are two questions for me right now:
Q1:How could gandiva use the multi-cores to execute the filter?
Q2: Could gandiva use GPU to accelerate the preformance?
THX for ur replies!!!

**Comment by westonpace** [comment]
You might try the dev@ or user@ mailing list.  It will have a wider audience and is more likely to get noticed by someone that is more knowledgeable with Gandiva.
