### ISSUE TITLE
Use java.time.LocalDateTime instead of org.joda.time.LocalDateTime

### ISSUE THREAD

**Issue by benmccann** [apache/arrow#1132]
It would be preferable to use the standard Java time API

**Comment by wesm** [comment]
Can you open a JIRA about this? Thanks

**Comment by icexelloss** [comment]
Hi,

Arrow project uses ASF Jira to track issues. Can you create a Jira there and provide some details?

**Comment by wesm** [comment]
@icexelloss note we enabled GitHub issues for the project to lower the barrier for users and potential contributors to interact with the project and ask questions, so no worries about opening an issue here, but development work indeed will get tracked in JIRA

**Comment by icexelloss** [comment]
Gotcha. Thanks!

**Comment by wesm** [comment]
Can someone open a JIRA? Thanks

**Comment by dgunning** [comment]
Created https://issues.apache.org/jira/browse/ARROW-2015
