### ISSUE TITLE
Binary wheels for Windows

### ISSUE THREAD

**Issue by ofek** [apache/arrow#1135]
Since we already use AppVeyor, could we use it to automate this?

**Comment by xhochy** [comment]
@ofek We already provide binary wheel for Windows on every release. What is missing here?

**Comment by wesm** [comment]
Indeed, there are wheels on https://pypi.python.org/pypi/pyarrow

**Comment by ofek** [comment]
@xhochy @wesm Sorry! The docs https://github.com/apache/arrow/tree/master/python#installing imply only Linux has binary wheels and Conda must be used otherwise. I'll submit a PR.
