### ISSUE TITLE
read_table/read_feather in chunks?

### ISSUE THREAD

**Issue by abekfenn** [apache/arrow#11469]
Hi,

Is it possible to read feather files in chunks? I've seen a lot of discussion on this and mentions of the API being opened for reading in chunks but don't see any documentation or evidence in the code to suggest that it is open.

I am aware that it is possible to write in chunks but would like to be able to read a feather file in chunks to enable multithreaded processing of large files using chunked processing with minimal memory.

Thank you!

**Comment by abekfenn** [comment]
That would be great, thank you @westonpace.. python

**Comment by westonpace** [comment]
So one of the points of confusion with the python implementation is that it refers to both `feather` and IPC files as separate things.  This is unfortunately a bit of legacy.  Feather v2 is the same thing as the Arrow IPC file format.  The "feather" calls in python are rather limited, as you have noticed, and you only have full table reads.  However, the IPC functionality is more extensive.

So to read a feather file in python in a streaming fashion you will use a `pyarrow.ipc.RecordBatchFileWriter`.  There is some documentation on this here: https://arrow.apache.org/docs/python/ipc.html#writing-and-reading-random-access-files

So, for example:

```
import pyarrow as pa
import pyarrow.ipc as ipc

table = pa.Table.from_pydict({'a': range(100)})

with ipc.RecordBatchFileWriter('test.arrow', table.schema) as writer:
    writer.write_table(table, max_chunksize=10)

with ipc.RecordBatchFileReader('test.arrow') as reader:
    for batch_index in range(reader.num_record_batches):
        batch = reader.get_batch(batch_index)
        print(f'Read in batch {batch_index} which had {batch.num_rows} rows')
```

The second thing to note, as you will see in the example, is that iterative reading is only supported if the file was written as multiple batches.  If your giant feather file was written as one giant record batch then you will be unable to read it in a streaming fashion using pyarrow today.
