### ISSUE TITLE
apache arrow c++: Ways to invalidate data

### ISSUE THREAD

**Issue by r0b3rt24** [apache/arrow#11491]
To whom this may concern,

I'm working on a research project where I need to delete several rows from an arrow array. Since the arrow does not support update/delete, I wonder if it's possible for me to invalidate data using the validity map?

(I have tried re-construct the table, but the performance was not satisfying).

Thank you for any help in advance!

**Comment by OscarTHZhang** [comment]
I came across this example: http://arrow.apache.org/docs/cpp/arrays.html#performance 
```c++
arrow::Int64Builder builder;
// Make place for 8 values in total
builder.Resize(8);
// Bulk append the given values (with a null in 4th place as indicated by the
// validity vector)
std::vector<bool> validity = {true, true, true, false, true, true, true, true};
std::vector<int64_t> values = {1, 2, 3, 0, 5, 6, 7, 8};
builder.AppendValues(values, validity);

std::shared_ptr<arrow::Array> array;
arrow::Status st = builder.Finish(&array);
```
In this code, you can construct the validity map while constructing a new `arrow::Array`.

I wonder if there is an API in Apache Arrow, or an ad-hoc solution, to change this validity map after the construction of `arrow::Array` so that this will invalidate some elements in this `arrow::Array`?

Thanks

**Comment by westonpace** [comment]
> I wonder if there is an API in Apache Arrow, or an ad-hoc solution, to change this validity map after the construction of arrow::Array so that this will invalidate some elements in this arrow::Array?

Yes...ish.  At this point you're probably venturing into more internal features so it may have gotchas down the road.

For example:

```
  std::cout << array->ToString() << std::endl;
  arrow::BitUtil::ClearBit(array->null_bitmap()->mutable_data(), 1);
  std::cout << array->ToString() << std::endl;
```

Some caveats:
 * `null_bitmap` is not going to take into account the array offset, if any, so you will need to adjust that into your calculation.
 * You will need to convert from "index to change" to byte/bit to change (e.g. divide by 8 then modulo 8)
 * Not all arrays have a validity bitmap (only dense union and sparse union do not at the moment)
 * The validity bitmap may be null (often when an array is constructed without any null values we do not create one)
 * The `Array` caches the `null_count` so if the null count changes then you would want to unset that cached value.  Unfortunately, I don't know any trick off the top of my head to do this.

**Comment by westonpace** [comment]
Ah, it seems you can do `array->data()->SetNullCount(new_null_count);` but you will be responsible for doing the math to compute the new null count.  If the null count is wrong then strange things may happen.

**Comment by westonpace** [comment]
> Thank you for your response! I'm particularly interested in the third option. Would you mind showing me some hint about how that is done?

Do you mean the compute functions?  Here is an example (sample output is based on @OscarTHZhang 's example):

```
  ARROW_ASSIGN_OR_RAISE(
      arrow::Datum filter_mask,
      arrow::compute::CallFunction("not_equal", {array, arrow::Datum(2)}));
  std::cout << filter_mask.make_array()->ToString() << std::endl;
  // [true, false, true, null, true, true, true, true]
  ARROW_ASSIGN_OR_RAISE(
      arrow::Datum filtered_array,
      arrow::compute::CallFunction("filter", {array, filter_mask}));
  std::cout << filtered_array.make_array()->ToString() << std::endl;
  // [1, 3, 5, 6, 7, 8]
  ARROW_ASSIGN_OR_RAISE(
      arrow::Datum null_replaced,
      arrow::compute::CallFunction(
          "if_else", {filter_mask, array,
                      arrow::Datum(arrow::MakeNullScalar(array->type()))}));
  std::cout << null_replaced.make_array()->ToString() << std::endl;
  // [1, null, 3, null, 5, 6, 7, 8]
```

> I saw there is a class in gandiva called selection_vector I wonder if that can do the same?

That seems likely but I don't know much about gandiva myself.  Perhaps someone else has a thought.

**Comment by emkornfield** [comment]
Resolving.  Any more in depth conversation should probably happen on the dev@ mailing list.
