### ISSUE TITLE
GPU Acceleration for Arrow

### ISSUE THREAD

**Issue by EdisonZiXing** [apache/arrow#11597]
Dear contributors:
    After I read the code for the Gandiva based on cpu,I thought that using llvm to accelerate the filter is a brilliation way. I also find another llvm tech called XLA which been used to accelerate Tensorflow with GPU computings.So I wonder if we consider to use XLA to accelerate Arrow Datatype? Or how could we use gpu when we based on the Arrow Datatype?
    Looking forwards to yours replies!

**Comment by emkornfield** [comment]
@EdisonZiXing 
This type of conversation is best had on the dev@ mailing list.  I think some companies have made efforts here but I don't know the current status.
