### ISSUE TITLE
Arrow flight server integrated with pure gRPC service

### ISSUE THREAD

**Issue by elignb** [apache/arrow#11657]
Hi,

I am using Arrow 6.0.0's flight and I also implemented my own gRPC service.
I followed the example given at:
https://github.com/apache/arrow/blob/master/cpp/examples/arrow/flight_grpc_example.cc
But I crash at runtime (segmentation fault).  
Does someone have an idea what may cause this?
Also, is there a way to have the server listening on a **single** port for both flight and the pure gRPC service?

Thank you!

**Comment by lidavidm** [comment]
The example demonstrates both servers running on a single port, can you clarify?

For the crash: likely this is a linking issue (gRPC and Protobuf cannot be linked multiple times). This would happen, for instance, if you dynamically link libarrow_flight.so but statically link libgrpc.a. If you could show a backtrace of the crash (via a debugger like GDB) and the commands used to compile and link the application, that would be a great help.

**Comment by elignb** [comment]
Thanks David!
In the example you can see there are 2 ports:
`std::cout << "Listening on ports " << FLAGS_port << " and " << extra_port << std::endl;`

Regarding the crash, indeed I link  the arrow flight dynamically and the gRPC statically. What is the best way to handle both pure gRPC usage and arrow flight usage in my project? regarding versions, libraries etc. ?

**Comment by lidavidm** [comment]
The example is adding a second port to demonstrate that you can customize the gRPC server. However, both services are available on both ports.

For this case, you should always link gRPC dynamically. That means both Arrow and your application need to be built against the gRPC shared libraries, *not* the static libraries. We should make this clearer somewhere…

**Comment by lidavidm** [comment]
We will document this more thoroughly in https://github.com/apache/arrow-cookbook/issues/106 and ARROW-14662.

**Comment by elignb** [comment]
So when I use the gRPC library it can be a completely different library than the one used for the arrow library? Because currently I use a system installed arrow (+flight) using apt, and gRPC I build from source and then install it to a location  (/usr/.local) and I see it installs only static libraries, and also the versions are different (1.35 vs. 1.41). I don't quite understand how I should link the libraries correctly

**Comment by lidavidm** [comment]
No, the gRPC version must be the same as well. Does the system installed arrow not link to a system gRPC? In that case, I believe this should also work: link both libarrow_flight and libgrpc statically, using the system versions. That is, either both must be linked dynamically, or both must be linked statically, but you cannot mix and match.

I would say, if you are building one of the components from source, you should probably build all of them from source.

There's likely an option in the gRPC build script to build the dynamic libraries. (Though again, if you go that path, you should build Arrow from source as well.) I apologize for the complications, but unfortunately this is what we're stuck with given all libraries involved (gRPC, Arrow, Protobuf) are rather complex and have many dependencies.

**Comment by elignb** [comment]
@lidavidm thank you very much!
Indeed after aligning versions and library types it works.

**Comment by lidavidm** [comment]
Great! Thanks for reporting back. I'll try to improve the documentation around this when I get a chance.
