### ISSUE TITLE
[JS] ReferenceError: TextDecoder is not defined - running tests with React Testing Library.

### ISSUE THREAD

**Issue by tielushko** [apache/arrow#11662]
Hello!

I am currently trying to use the React Testing library to run my unit/integrated tests, and there's a problem I've been noticing running any component/file that includes apache-arrow imports. 

I am currently using the es2015-cjs bundle due to some tree-shaking issues that's been happening with the library, but even when after the solution was introduced and I used es6 import statements, the TextDecoder error was still present. 

Here is the output from the terminal: 

ReferenceError: TextDecoder is not defined

![image](https://user-images.githubusercontent.com/46033508/141150775-064fddae-448d-4441-a6a6-375ded0e8fd5.png)

It appears that the issue is coming from here: https://github.com/apache/arrow/blob/master/js/src/util/utf8.ts

I would appreciate any guidance on this issue!

**Comment by sisco0** [comment]
What is your current _NodeJS_ version? https://nodejs.org/api/util.html#class-utiltextdecoder

**Comment by tielushko** [comment]
Hey @sisco0 !

Thanks for reaching out back to me. I was running version 14, but after research I decided to most recent LTS 16.13.0 in hopes it would resolve the issue, however the error was still present. Here's the environment I am running:

System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.0
    Yarn: Not Found
    npm: 7.13.0 
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.906.0), Chromium (95.0.1020.38)

**Comment by sisco0** [comment]
Hello @tielushko , did you have a chance to test the attached _Pull Request_ solution?

**Comment by tielushko** [comment]
I did test it as well @sisco0, but it seemed to still have the issue.

**Comment by stopyransky** [comment]
I can only confirm the issue. 
For me is present when trying to import Table: 
`import { Table } from 'apache-arrow';`

Shouldn't the utf8.ts use Node's `util` module?

```
const util = require('util');
const decoder = new util.TextEncoder();
```

instead of 
```
const decoder = new TextEncoder();
```

**Comment by tielushko** [comment]
@stopyransky I tried to use the normal package with ES6 imports as well, and it was breaking for me too. I use the es5 packaged one due to the issues the package had in the past with tree-shaking. Either way you import it, the Decoder issue is present.

**Comment by alippai** [comment]
It can be similar to this issue https://github.com/jsdom/jsdom/issues/2524

**Comment by tielushko** [comment]
The top answer here: 

https://stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test/57713960#57713960 

seemed to resolve my issues. I also added the TextDecoder from utils and ran the test with the environment specified. 

const Environment = require("jest-environment-jsdom");

```
/**
 * A custom environment to set the TextEncoder and TextDecoder
 */
module.exports = class CustomTestEnvironment extends Environment {
  async setup() {
    await super.setup();
    if (typeof this.global.TextEncoder === "undefined") {
      const { TextEncoder } = require("util");
      this.global.TextEncoder = TextEncoder;
    }

    if (typeof this.global.TextDecoder === "undefined") {
      const { TextDecoder } = require("util");
      this.global.TextDecoder = TextDecoder;
    }
  }
};
```
