### ISSUE TITLE
Compile/link w/ the Glib (C) C API

### ISSUE THREAD

**Issue by tomweber-sas** [apache/arrow#11672]
Hey, I hope this is the right forum for this; let me know if not. I've only been looking into this for a number of hours, so I may have missed something.
I'm trying to to use Arrow in a C system to transfer data between the C Process and other language processes (Python, but later R, ...).
I want to use the mmap for on the same system and other streaming (socket probably) when the processes are on separate systems.
I found the Apache Arrow GLib (C), and installed based upon  https://arrow.apache.org/install/  (CentOS 7 and Red Hat Enterprise Linux 7 instructions). From that I found that bits and pieces were installed in various locations: 
/usr/lib64/libarrow-glib.so
/usr/include/arrow
/usr/include/arrow-glib
I have no real idea of what all it put, where; that's just what I found so far.

That seemed fine as I've integrated other products which provide interface libraries (.so) and .h files. So, I tried to compile my stuff with the .so's and .h files, based upon some of the code in this example   /usr/share/arrow-glib/example/read-stream.c

First I was missing a lot of .h files. So, I ended up downloading the apache-arrow-6.0.0.tar.gz and copying some of the missing h files down (they weren't part of the package installs???). I had to find other h files on my system that didn't seem to be part of the arrow package. Currently, I've gotten past the compile errors for missing .h files (doesn't seem that all the required ones are part of either the install of Glib or the tar file).

Now I'm hitting link error for missing functions/... (I have libarrow.so.600.0.0, libarrow_dataset.so.600.0.0, libarrow-glib.so.600.0.0 and libref_array.so.1.2.1). No idea if there are others I don't have?

Am I confused as to how this is supposed to work? I haven't found much info about how this is supposed to work, so I'm assuming it's like the others I've integrated, where the .so's and h files (and a little API doc) were all that were needed. I'm unclear on how to get all of the pieces this needs for it to compile and link. Would have thought they would al be in the install.

Again, I wanted to just use the C API in the C process to interface w/ the Python version in a python process (other lang's later) to move data via this format via the mmap/streaming interfaces it says it supports. Is that something I'm supposed to be able to do with this? And how do I get the right set of .so's and .h files to do this? Or am I confused about what I can do w/ C?

Thanks a bunch!
Tom

**Comment by kou** [comment]
You can get compiler flags by `pkg-config --cflags --libs arrow-glib`. You can find `.h` and `.so` with the compiler flags.

**Comment by tomweber-sas** [comment]
Awesome, you rock; that got me the pieces I was missing! Is there any kind of manifest about what's installed, and where, by the commands in the install instructions (CentOS 7 and Red Hat Enterprise Linux 7)? Either way, now I can start trying to play with this tomorrow and see if I can actually do what I'm thinking. Getting in the debugger and seeing what I see will help a lot.
Thanks again for the quick help! I'll close this, since it's about getting it to compile and link, which it is now doing. :)
Thanks!
Tom

**Comment by kou** [comment]
You can use `rpm -ql arrow-glib-devel` for it.

**Comment by tomweber-sas** [comment]
awesome, thanks!
