### ISSUE TITLE
[Python] read csv: incorrect number of columns

### ISSUE THREAD

**Issue by tzipperle** [apache/arrow#11702]
Hello, 

is it possible to use in Python with pyarrow 6.0.0 the function to handle incorrect number columns as described below?

> If a row has an incorrect number of columns, now the row can be skipped instead of raising an error (ARROW-12673).

**Comment by jorisvandenbossche** [comment]
AFAIK this feature was only added to the C++ library, and not to the python bindings (pyarrow). So currently that's not possible from Python.

**Comment by tzipperle** [comment]
Okay thanks!
