### ISSUE TITLE
[JS] Where is the filter function?

### ISSUE THREAD

**Issue by renodesu** [apache/arrow#11746]
Where is the `filter()` functionality? I'm using version `6.0.1` of `apache-arrow`.

The two examples in the README ([here](https://observablehq.com/@theneuralbit/introduction-to-apache-arrow) and [here](https://observablehq.com/@lmeyerov/manipulating-flat-arrays-arrow-style)) both make use of the `sometable.filter(/**/)` functionality on a table.

Seems like it did exist on previous versions based on the example code? Why isn't such a core feature present on a library like this (and why was it seemingly removed)?
Based on the examples, it was present on versions `0.16` and `4.0.0`.

Simple reproduction would be:
```
import { Int8Vector, Table, Utf8Vector } from 'apache-arrow'

const arrowTable = Table.new(
  [
    Utf8Vector.from(['John', 'Mary']),
    Int8Vector.from([10, 20])
  ],
  ['name', 'age']
)

// @ts-ignore
arrowTable.filter() // "TypeError: arrowTable.filter is not a function"
```

**Comment by kszucs** [comment]
cc @domoritz

**Comment by domoritz** [comment]
The docs are outdated. We I lay have filter on data frames. A data frame extends table.
