### ISSUE TITLE
Trivial issue in python hypothesis strategies

### ISSUE THREAD

**Issue by notEvil** [apache/arrow#11744]
Hi,

https://github.com/apache/arrow/blob/463108dda72aafd60fd37b960226585dcf777c4a/python/pyarrow/tests/strategies.py#L108

should be `interval_types = st.sampled_from([` or `interval_types = st.just(`.

Thx!

**Comment by cyb70289** [comment]
Thanks for reporting the issue. Will you open a PR to fix it?

**Comment by cyb70289** [comment]
Closed by https://github.com/apache/arrow/pull/11880.
Thanks @notEvil for the report and fix.
