### ISSUE TITLE
Any work-around for integer overflow in applying R's write_parquet()?

### ISSUE THREAD

**Issue by zhi-guo** [apache/arrow#11782]
- The issue: Integer Overflow 
- R code: write_parquet(a_data.table, out_parquet_file)  
- R version: 4.1.2 (2021-11-01) - "Bird Hippie"
- Platform: x86_64_linux-gnu(64-bit)
- arrow version: 6.0.1.20211125

Error message: 
![image](https://user-images.githubusercontent.com/77978147/143671978-c1a24e9a-ba18-40f6-8b6e-28af5d6dffe4.png)

Possible cause: lines 205-216 of "parquet.R"

![image](https://user-images.githubusercontent.com/77978147/143672056-92e3551b-eb94-45db-9d06-1feed790dd5f.png)

Reason for possible cause: the data.table is so large that x$num_rows * x$num_columns > .Machine$integer.max

![image](https://user-images.githubusercontent.com/77978147/143672176-cfe5a396-3cc0-4b8f-a489-c46070835789.png)

Many thanks

**Comment by thisisnic** [comment]
Thanks for reporting this @zhi-guo!  I have opened a bug ticket on the project JIRA: https://issues.apache.org/jira/browse/ARROW-14894

In the short term, you can manually specify the `chunk_size` argument to `write_parquet()` to prevent this code from being run.  It governs how many rows of data are written to disk at once.  For a dataset with the rows/columns shown in your `cell_num` calculation above, around 2500000 is the value which would have been calculated.
