### ISSUE TITLE
Pre-Feature-request - Is there a reason why metadata isn't accessible between language implementations?

### ISSUE THREAD

**Issue by gowerc** [apache/arrow#11935]
Hi,

I was planning to make this into a feature request on the JIRA board but before I did I just wanted to check if there was a particular reason why this feature doesn't already exist (as it could just be my lack of knowledge of the parquet standard).

The current implementations of reading and writing parquet (at least the R and Python implementations) allow you to assign arbitrary metadata to your dataset which can written and read by the same language but cannot be read by other languages i.e. attributes set in R don't appear to be easily accessible via the python implementation and vice versa.  Is there a reason for this? Would it be viable to request that at least simple metadata (i.e. numerics and strings) have some way of being shared between the different implementations ?  

As an example of use we often assign longer variable labels to columns in order to give a description of what the column is for i.e.
`TRT01P` = `First planned treatment`. It would be great if we could attach this metadata within the parquest object in a way that other languages reading the object can also access it.

**Comment by jorisvandenbossche** [comment]
> attributes set in R don't appear to be easily accessible via the python implementation and vice versa.

Can you give a more concrete code example?

As far as I know for Python, metadata in the table schema's metadata is written to Parquet FileMetaData key_value_metadata, which should be a standard place to put this.

I am less familiar with the R side, but it seems this is similarly available in the R arrow table's metadata:

```python
# create a table with some top-level metadata
>>> table = pa.table({"a": [1, 2, 3], "b": [4, 5, 6]})
>>> table = table.replace_schema_metadata({"a": "long name"})
# in python this is exposed as a dict
>>> table.schema.metadata
{b'a': b'long name'}

>>> import pyarrow.parquet as pq
>>> pq.write_table(table, "test_metadata.parquet")
# this metadata is stored in the Parquet FileMetaData "key_value_metadata", in the python interface again exposed as a dict
>>> file_metadata = pq.read_metadata("test_metadata.parquet")
>>> file_metadata.metadata
{b'ARROW:schema': b'/////+gAAAAQAAAAAAAKAA4ABgAFAAgACgAAAAABBAAQAAAAAA....',
 b'a': b'long name'}
# and after reading also available
>>> pq.read_table("test_metadata.parquet").schema.metadata
{b'a': b'long name'}
```

Reading the same file from R:

```R
> table <- read_parquet("test_metadata.parquet", as_data_frame=F)
> table
Table
3 rows x 2 columns
$a <int64>
$b <int64>

See $metadata for additional Schema metadata
> table$metadata
$a
[1] "long name"
```

**Comment by gowerc** [comment]
I clearly had not looked deeply enough into the documentation apologies ! And thank you this solves my use case :)

**Comment by jorisvandenbossche** [comment]
It's also quite likely our documentation is not very clear about this

**Comment by gowerc** [comment]
Apologies one other question; is it possible to add metadata at the column level or is it restricted purely to the table level?  At least when I try this in R I can't see any `metadata` attribute for the columns

```
library(arrow)
i2 <- arrow_table(iris)
str(i2$Sepal.Length)
```

```
Classes 'ChunkedArray', 'ArrowDatum', 'ArrowObject', 'R6' <ChunkedArray>
  Inherits from: <ArrowDatum>
  Public:
    .:xp:.: externalptr
    as_vector: function () 
    cast: function (target_type, safe = TRUE, ...) 
    chunk: function (i) 
    chunks: active binding
    clone: function (deep = FALSE) 
    Equals: function (other, ...) 
    Filter: function (i, keep_na = TRUE) 
    initialize: function (xp) 
    invalidate: function () 
    length: function () 
    null_count: active binding
    num_chunks: active binding
    pointer: function () 
    print: function (...) 
    set_pointer: function (xp) 
    Slice: function (offset, length = NULL) 
    SortIndices: function (descending = FALSE) 
    Take: function (i) 
    ToString: function () 
    type: active binding
    type_id: function () 
    Validate: function () 
    View: function (type)
