### ISSUE TITLE
[Python] Unable to turn-off signal blocking for pyarrow flight RPC server

### ISSUE THREAD

**Issue by liuyu81** [apache/arrow#11932]
Greetings,

The [python-binding](https://arrow.apache.org/docs/python/api/flight.html) of Apache [Arrow Flight](https://arrow.apache.org/docs/format/Flight.html) RPC server blocks `SIGTERM` and `SIGINT` signals during long-running operations. And I have been unable to *unblock* these signals.

It seems like the [`enable_signal_handlers()`](https://github.com/apache/arrow/blob/master/python/pyarrow/error.pxi#L154) method from `pyarrow.lib` is there for the exact purpose of turning on/off signal blocking, but it does not work, at least not for the following sample code,

- server.py

```python
import signal
import threading
import time
from datetime import datetime

import pyarrow as pa
import pyarrow.flight as pf


class TickServer(pf.FlightServerBase):

    SCHEMA = pa.schema([
        ('time', pa.timestamp("us")),
    ])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.stopped = threading.Event()

    def _generate_ticks(self, context: pf.ServerCallContext):
        while not self.stopped.is_set() and not context.is_cancelled():
            yield pa.record_batch([
                pa.array([datetime.now(), ]),
            ], schema=TickServer.SCHEMA)
            time.sleep(1)

    def do_get(self, context: pf.ServerCallContext, ticket: pf.Ticket):
        key = ticket.ticket.decode('utf-8')
        if key == "tick":
            return pf.GeneratorStream(TickServer.SCHEMA, self._generate_ticks(context))
        raise pa.ArrowKeyError("Unknown ticket: {}".format(ticket))

    def shutdown(self):
        self.stopped.set()
        return super().shutdown()


if __name__ == "__main__":
    # NOTE: this doesn't work
    pa.enable_signal_handlers(False)

    with TickServer(location="grpc://127.0.0.1:8000") as server:

        def signal_handler(signum, frame):
            server.shutdown()
            print("interrupted")

        signal.signal(signal.SIGINT, signal_handler)
        server.serve()

```

- client.py

```python
import pyarrow as pa
import pyarrow.flight as pf

if __name__ == "__main__":
    try:
        client: pf.FlightClient = pf.connect(location="grpc://127.0.0.1:8000")
        client.wait_for_available()
        for batch in client.do_get(pf.Ticket("tick")):
            table = pa.Table.from_batches([batch.data])
            for record in table:
                print(record[0])
    except KeyboardInterrupt:
        print("interrupted")
```

The current behavior of `server.py` is that it can only be interrupted by `SIGINT` (i.e. Ctrl+C) when no client is active. I'd like to be able to interrupt `server.py` regardless of whether there are active clients not not.

My environment is Ubuntu 20.04 + python 3.8 + pyarrow 6.0.1.

**Comment by lidavidm** [comment]
Right, the signal masking is done unconditionally right now. I'll file a JIRA for tackling this issue and confirm that your expected use case works.

Just to make sure, are you able to interrupt the client as expected?

**Comment by lidavidm** [comment]
We are calling Shutdown when you interrupt the server, the issue is this: https://grpc.github.io/grpc/cpp/classgrpc_1_1_server_interface.html#a644772d11101318f1424e595dee73ccf

In other words, if there is an ongoing RPC, the gRPC implementation won't shutdown the server. This is an implementation decision of gRPC. I am not sure why is_cancelled seems not to be set, though. (Also note that your overridden shutdown() won't be called, so there is no value to the `threading.Event` except for when you call shutdown in Python.) However you will find that new clients can't connect, as expected.

If you interrupt the server, then interrupt the client, then the server will print `interrupted` and shut down as expected.

Also, if we don't set the signal handlers, gRPC C++ doesn't react to Ctrl-C at all, so you won't be able to interrupt the server even if there's no clients. So I think the main thing to fix here is to figure out why `ServerCallContext.is_cancelled` is not set when the server is shutdown - would that fix your issue?

**Comment by lupko** [comment]
I run into this problem as well. What happens in my case is FlightServerBase will install its own handlers for INT & TERM. Upon those signals, none of the previously installed handlers will be called (even if it seems the code intends to do so?); Flight RPC server shuts down on those signals.

Anyway, what seems like a workaround to me is to:

1. set both SIGTERM and SIGINT to SIG_IGN - this way pyarrow will not register its own signal handlers (https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/flight.cc#L181)
2. start the server in separate thread, once up, install your own handlers in the main thread
3. in your own handlers trigger shutdown explicitly; once shutdown is done blocking, the serve() will exit as well

Disclaimer: i'm a newbie in pyarrow/Flight so maybe this is not 100% correct and leads to problems down the line.

@lidavidm i'm curious, how about exposing the Serve() for applications that want/need to do their own signal processing and control the Flight RPC server lifecycle themselves? Seems like the underlying C++ impl has methods to do Serve() and ServeWithSignals() but python only exposes the latter.

Thanks

**Comment by lupko** [comment]
@lidavidm for me, the goal is to integrate Flight RPC server into a larger app, and manage the lifecycle of the server from there. 

e.g. when my app receives signal to stop, it handles the teardown and as part of it shuts down the Flight RPC server. That's why for me the approach of no signal handling done by PyArrow is preferred.

btw, is there any difference between shutdown done as part of PyArrow signal handling and the shutdown() that I can trigger myself?

**Comment by lidavidm** [comment]
Ok, disabling the default handler is doable, so long as it's understood that you still need a background thread. (Relatedly, note that the server is active as soon as it's created, even without calling Serve(). Serve() really just waits for shutdown. So you could just skip all that.)

There's no difference. The signal handler just calls shutdown() (at the C++ level, so bypassing any overridden Python method).

I tested the shutdown-with-deadline method in C++, for what it's worth, and it also does not cancel ongoing RPC handlers. I think by a careful reading of https://stackoverflow.com/questions/51196732/grpc-how-can-rpc-handlers-properly-detect-if-server-has-been-shutdown/51333217 and the linked gRPC method, this is expected; gRPC will only cancel handlers using the async API.

**Comment by lupko** [comment]
@lidavidm thanks a lot. now the thing with serve() that you mentioned. it seems to me that by not calling the serve I achieve exactly what I want: server is up, no signal handlers registered by PyArrow :)

**Comment by lidavidm** [comment]
Ok! We should better document this, perhaps.

**Comment by liuyu81** [comment]
@lidavidm thanks for the detailed explanation.

my application scenario is likewise to that of @lupko, where the server is part of a CLI application and its life-cycle is controlled by end users. The clients are remote services consuming live streams of data as they become available; the clients don't voluntarily cancel requests, except when the streams are closed from the source. It therefore seems like a natural design choice to capture user-initiated `SIGINT` from the app, and issue an immediate shutdown of the gRPC server. 

As suggested, I am now able to capture `SIGINT` by creating the gRPC server in a background thread and not invoking `serve()`, e.g.,

```python
# see the original post for the definition of `TickServer`

if __name__ == '__main__':
    server: Optional[TickServer] = None

    def create_server():
        global server
        with TickServer(location="grpc://127.0.0.1:8000") as server:
            server.stopped.wait()

    with ThreadPoolExecutor() as executor:
        try:
            fut = executor.submit(create_server)
            concurrent.futures.wait([fut])
        except KeyboardInterrupt:
            server.shutdown()
            print("interrupted")
```

**Comment by liuyu81** [comment]
Out of curiosity, I took a closer look at the implementation of pyarrow's flight server, and it seems like [`FlightStreamReader.read_all`](https://github.com/apache/arrow/blob/cf8d81d9fcbc43ce57b8a0d36c05f8b4273a5fa3/python/pyarrow/_flight.pyx#L904) is protected by [SignalStopHandler](https://github.com/apache/arrow/blob/cf8d81d9fcbc43ce57b8a0d36c05f8b4273a5fa3/python/pyarrow/error.pxi#L181) which calls into [the C++ code](https://github.com/apache/arrow/blob/2464b149b3d06c6c3e45136dad0f3956772ca487/cpp/src/arrow/util/cancel.h) and blocks custom signal handlers. But still, on the Python side, the signal-blocking behavior is controlled by the [`signal_handlers_enabled`](https://github.com/apache/arrow/blob/cf8d81d9fcbc43ce57b8a0d36c05f8b4273a5fa3/python/pyarrow/error.pxi#L151) global variable, and it can be toggled on / off with [`enable_signal_handlers()`](https://github.com/apache/arrow/blob/cf8d81d9fcbc43ce57b8a0d36c05f8b4273a5fa3/python/pyarrow/error.pxi#L154). Could anyone shed some light on why calling `enable_signal_handlers(False)` from the main thread doesn't prevent the signal-blocking behavior?

**Comment by lidavidm** [comment]
@liuyu81 I think the Python documentation on [signal](https://docs.python.org/3/library/signal.html) also applies to you. If you run the server on the main thread, and Flight does not register a signal handler, then it is impossible for your application to handle signals in Python.

The reason why `enable_signal_handlers` does not do anything is simply because it isn't accounted for. Would it be useful? I am arguing it is not useful for you. You must run the server on a different thread than the main thread. We could respect it regardless for consistency, but it will not achieve the behavior you want because you will simply be unable to handle signals at all.

**Comment by liuyu81** [comment]
Hi @lidavidm, I am perfectly fine with running the flight server in a background thread, and thank you for point that out. The follow up question on `enable_signal_handlers()` is, as I said, out of pure curiosity on how things works around the `SignalStopHandler` -- it does not mandate setting up a custom signal handler, nor running flight server in the main thread. It would be great, though, if we can have something resembling [`SetShutdownOnSignals`](https://github.com/apache/arrow/blob/c038e611e95978d0e8a28feb10b2cec54c1b50ed/cpp/src/arrow/flight/server.h#L186) on the python side.

On the update to `shutdown()` with cancellation of ongoing RPCs, that sounds wonderful as well. Would be perfect if that includes canceling streams (e.g. `GeneratorStream`s) as well.

**Comment by lidavidm** [comment]
See ARROW-15106, ARROW-15107, and ARROW-15108.
