### ISSUE TITLE
Question - Arrow Flight Support for C#

### ISSUE THREAD

**Issue by SebastianGau** [apache/arrow#11960]
Hi Guys,

at first thanks for the great work on flight! The idea is brilliant. Our data scientists are adopting flight more and more in their implementations. I am a backend developer in the data integration team and we work a lot with C#, and would also like to use flight more for data exchange between services due to obvious reasons. I just wondered why the flight implementation for C# is so far behind compared to the reference implementation in C++? Is it planned to bring them both to the same level, or even provide a C# binding to the C++ reference implementation?

Cheers, Sebastian

**Comment by lidavidm** [comment]
I think it's just a matter of someone stepping up to do the work, whether it's to improve the implementation or provide bindings. I see @eerhardt and @Ulimo were answering another Flight/C♯ related-question here, would one either of you be able to chime in?

What specific features are you missing in C♯? It seems there's not many [JIRAs](https://issues.apache.org/jira/browse/ARROW-10939?jql=project%20%3D%20ARROW%20AND%20component%20%3D%20%22C%23%22%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20Flight) for this, so it might help to know what would be useful.

**Comment by Ulimo** [comment]
Hi @SebastianGau as @lidavidm mentioned it would be great to know what features you are missing from the C# implementation.

As a reference we use the C# implementation in production at my company. I guess its more that no one has yet seen a requirement to implement the other features yet.

**Comment by eerhardt** [comment]
I'm going to close this issue for now, as I believe the questions have been answered. Please feel free to open a JIRA ticket for any missing features or issues you find in the C# implementation. We'd also gladly accept fixes as well 😀.
