### ISSUE TITLE
Parquet schema / data type for entire null object DataFrame columns

### ISSUE THREAD

**Issue by mishbahr** [apache/arrow#11967]
I'm writing some DataFrame to binary parquet format with one or more entire null object columns.

If I then load the parquet dataset with `use_legacy_dataset=False`

```python
parquet_dataset = pq.ParquetDataset(root_path, use_legacy_dataset=False, **kwargs)
type(parquet)
pyarrow.parquet._ParquetDatasetV2

```

It returns an `_ParquetDatasetV2` instance and when I check the schema.

```python
type(parquet_dataset.schema) 
pyarrow.lib.Schema
```

If I load the same file but with `use_legacy_dataset=True`

```python
parquet_dataset2 = pq.ParquetDataset(root_path, use_legacy_dataset=True, **kwargs)
```

The schema for the file is an instance of `ParquetSchema`

```python
type(parquet_dataset2.schema)
pyarrow._parquet.ParquetSchema
```

This is as I would expect and I'm aware that I can get the "arrow schema" like this.

```python
arrow_schema = parquet_dataset2.schema.to_arrow_schema()
type(arrow_schema)
pyarrow.lib.Schema
```

i.e same format as when I use `use_legacy_dataset=False`

For an instance of `ParquetSchema`, I can get details of any column. e.g

```python
parquet_dataset2.schema[13]

<ParquetColumnSchema>
  name: col13
  path: col13
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: INT96
  logical_type: None
  converted_type (legacy): NONE
```

Here the "physical_type" for this column is INT96.

```python
parquet.schema[13].physical_type
'INT32'
```

For an instance of `pyarrow.lib.Schema`, if I get the "data type" for the same column.

```python
parquet_dataset.schema.field("col13").type
DataType(null)
```

i.e with no information about what the "data type" is supposed to be.

This information is available in the Parquet file. But how do I access it?

Is there way to convert instance of `pyarrow.lib.Schema` -> `pyarrow._parquet.ParquetSchema`?

**Comment by mishbahr** [comment]
![screenshot-parquet-dataset](https://user-images.githubusercontent.com/1264089/146270547-2a24ec3b-7338-4372-b257-35ec63d01cdd.png)

I recreated the error with a simple test dataframe.

I think there is a bug on the  legacy datasets API.

Where is is getting the  `INT32` physical type from?

**Comment by westonpace** [comment]
Copying my question from the gist:

What is parquet_file.schema[0].logical_type? For me, if I do not specify a schema, it is Null (which is different than None). In your first snippet the logical type is None so I assume you are specifying the schema when writing.

Perhaps you have some files with Null logical type and some with None logical type? This could explain the behavior as the new datasets API infers the schema from a single file (picked more or less at random). So if it picked one of the null ones then you may end up with the behavior you are describing.

**Comment by mishbahr** [comment]
```python
parquet_file.schema[0]
```
```python
<ParquetColumnSchema>
  name: x
  path: x
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: INT32
  logical_type: Null
  converted_type (legacy): NONE
```
Just incase there is some issue with my  data source .

Now I'm using `df = pd.DataFrame(data={"x": [None, ]})` as input.

**Comment by westonpace** [comment]
This is a null array represented in parquet:
```
<ParquetColumnSchema>
  name: x
  path: x
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: INT32
  logical_type: Null
  converted_type (legacy): NONE
```

The original post was not a null array:
```
<ParquetColumnSchema>
  name: col13
  path: col13
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: INT96
  logical_type: None
  converted_type (legacy): NONE
```

In particular the `logical_type` is different between the two.  I'm not actually sure what data type it is (maybe timestamp)?  What is different between how the data is generated?  Do all of your files look like the latter (`logical_type: None`) or is it possible that some of your files look like the former?

**Comment by mishbahr** [comment]
Ignoring my initial code sample where I was using real parquet file as source.
This is fresh example using `df = pd.DataFrame(data={"col1": [None, ], "col2": ["foo1", ]})` as starting point.

Where does pyarrow get `INT32` as "physical_type" when the column completely empty (only null values) 

```python
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
```


```python
df = pd.DataFrame(data={"col1": [None, ], "col2": ["foo1", ]})
```


```python
table = pa.Table.from_pandas(df)
```


```python
pq.write_table(table, '/tmp/data.parquet')
```


```python
legacy_dataset = pq.ParquetDataset('/tmp/data.parquet', use_legacy_dataset=True)
```


```python
dataset = pq.ParquetDataset('/tmp/data.parquet', use_legacy_dataset=False)
```


```python
legacy_dataset.schema
```




    <pyarrow._parquet.ParquetSchema object at 0x7efc1dc51a40>
    required group field_id=-1 schema {
      optional int32 field_id=-1 col1 (Null);
      optional binary field_id=-1 col2 (String);
    }




```python
legacy_dataset.schema[0]
```




    <ParquetColumnSchema>
      name: col1
      path: col1
      max_definition_level: 1
      max_repetition_level: 0
      physical_type: INT32
      logical_type: Null
      converted_type (legacy): NONE




```python
dataset.schema[0].type
```




    DataType(null)

**Comment by jorisvandenbossche** [comment]
> Where does pyarrow get `INT32` as "physical_type" when the column completely empty (only null values)

For Parquet, you need to distinguish the "physical_type" and "logical_type" (as shown in the output of the `ParquetColumnSchema`, this is "INT32" vs "Null" for this column of all nulls). 

Parquet only has a limited set of physical types, see https://github.com/apache/parquet-format#types. And "Null" is not a physical type, but only a logical type. And a logical type always "annotates" some actual physical type. 

So when Arrow saves a "null" column (in Arrow this is an actual, proper type) to Parquet, it can use a "Null" logical type, but it still needs to choose some physical type for the column in the Parquet file. And by default, Arrow uses INT32 for the physical type. 

That explains where the "INT32" physical type is coming from. But in general, I think you don't need to care about this / you can ignore this. When reading the Parquet file to an Arrow table, we will correctly notice the "Null" logical type, and create a "null" column in the resulting Arrow table (basically ignoring the INT32 physical type of the Parquet field)

**Comment by mishbahr** [comment]
Ok. Thanks for the explanation. 
I think I am going to change my code the use the v2 dataset API (`use_legacy_dataset=False`)
And then throw an error when `field.type == pa.null()` and ask the user to cast dataframe column with specific type. 
e.g `df['x'] = df['x'].astype('string')`

**Comment by yan-hic** [comment]
> still needs to choose some physical type for the column in the Parquet file. And by default, Arrow uses INT32 for the physical type.
@jorisvandenbossche can that default be changed in `pyarrow` ? I want to use STRING instead.
The issue we are facing is that when saving a dataset, i.e. multiple parquet files, with one file having a column coincidentally with all nulls whereas other files have some strings for that column. The result is different schema across the dataset (INT32 or STRING), which when reading with bigquery (for instance), raises errors.

**Comment by jorisvandenbossche** [comment]
It's currently not possible to customize this as a user (and I am not sure it is worth adding a new option for this ..). 
If you want to use strings for all-null columns, you can also try to ensure your data have a proper string type when saving to parquet (this issue only happens if the data has the actual "null" arrow data type, not if your column contains all-null data but has some actual data type like "string"). 

Of course, it depends on your exact pipeline how easy it is to do (eg if you actually start with pandas data that gets converted to arrow while writing to parquet, you can currently only specify a _full_ schema, not just the data type for one column were you want to override the inference).

**Comment by yan-hic** [comment]
@jorisvandenbossche you are right on, `pandas` is the source, and before that sql (query). 

I could figure out how to retrieve `sqltypes` somewhere in `pandas` internals (or `sqlalchemy`) to map to the correct dtype for pa.null-type columns (I saw a long-time open issue on that) but for my use case, all such happen to be null-strings so the below just works fine:
```
schema = pa.Schema.from_pandas(df)
for i, col in enumerate(schema):
    if col.type == pa.null():
        schema = schema.set(i, pa.field(col.name, pa.string()))
table = pa.Table.from_pandas(df, schema=schema)
```
