### ISSUE TITLE
parquet-cpp RLE/delta encoding

### ISSUE THREAD

**Issue by robambalu** [apache/arrow#12046]
I'm trying to use the parquet RLE and delta binary encoding for some of my columns.  I dont want them to use dictionary encoding at all.  However, when I try to set my builder to disable dictionary / enable RLE or delta binary, I hit this exception:
"Selected encoding is not supported".

Looking in parquet/encoding.cpp MakeEncoder it looks like these encodings arent actually supported.  Am I going about this the wrong way, or am I bound to encode with dictionary or PLAIN?

**Comment by emkornfield** [comment]
This is correct they are not yet implemented yet in C++
