### ISSUE TITLE
How to read arrow files data in C#

### ISSUE THREAD

**Issue by neroarth94** [apache/arrow#12049]
I am trying to read the content of an arrow file but I was not able to find the functions to get the actual data from it. I am not able to find any useful example to read the data too. For example here.

The code example for writing and reading in C#:

```
// Write
var recordBatch = new Apache.Arrow.RecordBatch.Builder(memoryAllocator)
    .Append("Column A", false, col => col.Int32(array => array.AppendRange(Enumerable.Range(5, 15))))
    .Build();

using (var stream = File.OpenWrite(filePath))
using (var writer = new Apache.Arrow.Ipc.ArrowFileWriter(stream, recordBatch.Schema, true))
{
    await writer.WriteRecordBatchAsync(recordBatch);
    await writer.WriteEndAsync();
}

// Read
var reader = Apache.Arrow.Ipc.ArrowFileReader.FromFile(filePath);
var readBatch = await reader.ReadNextRecordBatchAsync();
var col = readBatch.Column(0);
```

By debugging the code, I can see the values in the col Values property but I have no way of accessing this information in the code.
![image](https://user-images.githubusercontent.com/59238910/147622497-4b858609-8506-4880-b83d-768ae504e69f.png)
Am I missing anything or is there a different approach to read the data?

**Comment by emkornfield** [comment]
CC @eerhardt

**Comment by edponce** [comment]
@neroarth94 There are several abstractions underlying the `Column` data structure. `var col` is a [`Column` which is represented by a `Field` and a `ChunkedArray`](https://github.com/apache/arrow/blob/master/csharp/src/Apache.Arrow/Column.cs#L27-L28). The `Data` getter gives you access to the [`ChunkedArray` which is a collection of `Arrays`](https://github.com/apache/arrow/blob/master/csharp/src/Apache.Arrow/ChunkedArray.cs#L28) that logically represent a single array of values. The `Array`s are the data structures that generally give you access to particular values. In your case, you have an [`Int32Array` which derives from `PrimitiveArray`](https://github.com/apache/arrow/blob/master/csharp/src/Apache.Arrow/Arrays/Int32Array.cs#L20) that contains the [`GetValue(index)`](https://github.com/apache/arrow/blob/master/csharp/src/Apache.Arrow/Arrays/PrimitiveArray.cs#L36) method for accessing a particular value.

IIUC, unfortunately, the C# `ChunkedArray` API does not has an indexing method similar to [the one in the C++ API](https://github.com/apache/arrow/blob/master/cpp/src/arrow/chunked_array.cc#L149), so you would need to convert global `ChunkedArray` indices to and pair of `Array` index and relative value index. 

For example, assuming the column consists of a single `ChunkedArray` you should be able to access the values as follows:
```c#
var col = readBatch.Column(0);
var value = col.Data.Array(0).GetValue(10);  // Value at index 10 is 15
```
Note: Most of the data structures contain `Slice(offset, length)` methods that allow you to get a copy of a subset of the values.

**Comment by neroarth94** [comment]
Hi @edponce thank you for the answer. The `col.Data.Array(0)` doesn't contain the `Array` property but I was able to read the data using the `Microsoft.Data.Analysis` library's data frame as suggested in this [SO](https://stackoverflow.com/questions/70501957/reading-file-with-apache-arrow-arrowfilereader-in-net/70568782#70568782)

**Comment by eerhardt** [comment]
```
var col = readBatch.Column(0);
```

Here `col` is an `IArrowArray`. In order to read the values from an array, you need to know which type of data is contained in the array. You can do `as` or `is` type checks for each type, or if you know the type, you can just cast. In your example above, it is an `Int32Array`, so casting to that you can now get the `.Values` property, which is a `ReadOnlySpan<int>` that you can loop through:

```C#
IArrowArray col = readBatch.Column(0);

Int32Array intArray = (Int32Array)col;
ReadOnlySpan<int> values = intArray.Values;

for (int i = 0; i < values.Length; i++)
{
    Console.WriteLine(values[i]);
}
```

**Comment by edponce** [comment]
@eerhardt Thanks for correcting me! I took a blind stab at it for the sakes of helping, but now I know.

**Comment by westonpace** [comment]
I'm sorry, I also did not realize C# had typed arrays (e.g. Int32Array).  For some reason I thought it was all the generic type-erased ones.  I'll fix up my SO answer.

**Comment by neroarth94** [comment]
Ok understood, thank you all for the answers
