### ISSUE TITLE
Feature request: lz4 and zstd compression support ?

### ISSUE THREAD

**Issue by bordingj** [apache/arrow#1209]
lz4 and zstd compression is currently not supported in arrow/python/pyarrow/_parquet.pyx, but seems to be supported in c++ https://arrow.apache.org/docs/cpp/structarrow_1_1_compression.html ?
It would be really nice to have these 2 standards in pyarrow.

**Comment by wesm** [comment]
This isn't necessarily a pyarrow problem -- the compressors used in Parquet are limited by the Parquet format itself. We (the Parquet team) just added these to the format specification https://github.com/apache/parquet-format/commit/84460c5a1e8aadf52a40dcf2aeb2fc875df4ac2a. So we can add them as soon as they are available in parquet-cpp

**Comment by bordingj** [comment]
aah I see. Nice!
