### ISSUE TITLE
A MemoryError occurred when reading Arrow streams

### ISSUE THREAD

**Issue by zhihuiwan** [apache/arrow#12121]
The hdfs file size is 160G, and the machine memory is 64G. 
pyarrow.NativeFile does not support readline and readlines methods, but I want to read the content by line, so I did the following test:

```python
>>> from pyarrow import fs
>>> path = 'hdfs://hadoop-cluster//wzh/test_160g'
>>> hdfs_client = fs.HadoopFileSystem.from_uri(path)
>>> buffer = hdfs_client.open_input_file(path)
>>> reader = io.TextIOWrapper(buffer=buffer, encoding="utf-8")
>>> reader.readlines(10)
```

The result is the following error：
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/io.pxi", line 376, in pyarrow.lib.NativeFile.read1
  File "pyarrow/io.pxi", line 323, in pyarrow.lib.NativeFile.read
MemoryError
```
Is there a good way to handle this?

**Comment by pitrou** [comment]
Sorry for the delay. We don't use Github issues but a [JIRA bug tracker](https://issues.apache.org/jira/projects/ARROW/), as noted in [the documentation](https://arrow.apache.org/community/).

In any case, this is probably the same underlying cause as https://issues.apache.org/jira/browse/ARROW-16272 . I'm therefore closing this issue.
