### ISSUE TITLE
hdfs3 autoconf

### ISSUE THREAD

**Issue by kpweiler** [apache/arrow#1213]
The hdf3 python library has a nice way of reading from $HADOOP_CONF_DIR like this:

hdfs = HDFileSystem(autoconf=True)

it would be nice have this functionality in the hdfs3 reader method. Or better yet, it would be nice to pass the HDFileSystem from hdf3 directly to PyArrow.

**Comment by wesm** [comment]
This is https://issues.apache.org/jira/browse/ARROW-448 -- I could use some help implementing and testing this. Would you like to write a patch? We also should be able to support `hdfs3.HDFileSystem` in pyarrow. Feel free to open a separate JIRA about that

**Comment by wesm** [comment]
Closing in favor of tracking on JIRA
