### ISSUE TITLE
Recasting elements in ListType

### ISSUE THREAD

**Issue by mbandrews** [apache/arrow#1214]
Are there are any plans to support the conversion of nested lists of doubles to ones of floats? For instance:
```
x = np.ones([640,480,3], dtype=np.float32)
a = pa.array(x.tolist())
a.type
# ListType(list<item: list<item: double>>)
```
and if I try to cast this to the corresponding float, via `a.cast(pa.list_(pa.list_(pa.float32())))`, I get the ff:
```
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
<ipython-input-26-36140d9d5f77> in <module>()
----> 1 a.cast(pa.list_(pa.list_(pa.float32())))

array.pxi in pyarrow.lib.Array.cast()

error.pxi in pyarrow.lib.check_status()

ArrowNotImplementedError: No cast implemented from list<item: list<item: double>> to list<item: list<item: float>>

```
The use case I have in mind is to iteratively write out multiple Tables or RecordBatches which contain multiples such elements (e.g. multiple stacked image arrays) and later feed them to a ML workflow. Double precision would be an unnecessary waste of space.

**Comment by wesm** [comment]
There's already a JIRA for this, could you follow it there? https://issues.apache.org/jira/browse/ARROW-1487. Patches welcome if you'd like to see it done sooner

**Comment by mbandrews** [comment]
Thanks for the info!
