### ISSUE TITLE
plan for updating conan package

### ISSUE THREAD

**Issue by Tudyx** [apache/arrow#12156]
Hello, the current *conan*  package for *arrow* is version `2.0.0`. Is there any plan for updating to a newer version?

**Comment by ianmcook** [comment]
Hi @Tudyx, the Apache Arrow core dev team does not maintain the [recipe](https://github.com/conan-io/conan-center-index/tree/master/recipes/arrow) for the [arrow Conan package](https://conan.io/center/arrow) and I am not aware of any plans or intentions to begin doing so. I believe the 2.0.0 version that's there now was unofficially contributed by a member of the broader Arrow community. If you would like to engage with the Arrow core dev team to suggest that we officially maintain this Conan package recipe, please open an Apache Arrow Jira or send an email to the Apache Arrow dev mailing list to make the case for this. Instructions at https://arrow.apache.org/docs/developers/contributing.html. Thanks!
