### ISSUE TITLE
How to write data with struct with pyarrow.parquet ?

### ISSUE THREAD

**Issue by dg3feiko** [apache/arrow#1217]
I want to convert a JSON data file to parquet format.

The only API to write data to parquet is `write_table()`. But I find no way to create a table with structs, either by `table.from_array()` or `table.from_pandas()`, but I always got errors. 

For example:
```python
data = [
   pa.array([1,2,3]),
   pa.array({"foo":"bar"}, {"foo":"bar"}, {"foo":"bar"})
]

TypeError: Argument 'type' has incorrect type (expected pyarrow.lib.DataType, got dict)
```
or 
```python
df = pd.read_json('[{"foo":{"foofoo":"bar"}}, {"foo":"barbar"}]')
table = pa.Table.from_pandas(df)

pyarrow.lib.ArrowInvalid: Error inferring Arrow type for Python object array. Got Python object of type dict but can only handle these types: string, bool, float, int, date, time, decimal, list, array
```

**Comment by wesm** [comment]
Hi, we do not yet support the syntax you are using for creating an array of structs. After adding missing square brackets:

```
In [2]: pa.array([{"foo":"bar"}, {"foo":"bar"}, {"foo":"bar"}])
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
<ipython-input-2-5383db65d4fd> in <module>()
----> 1 pa.array([{"foo":"bar"}, {"foo":"bar"}, {"foo":"bar"}])

/home/wesm/code/arrow/python/pyarrow/array.pxi in pyarrow.lib.array (/home/wesm/code/arrow/python/build/temp.linux-x86_64-3.5/lib.cxx:25024)()

/home/wesm/code/arrow/python/pyarrow/array.pxi in pyarrow.lib._sequence_to_array (/home/wesm/code/arrow/python/build/temp.linux-x86_64-3.5/lib.cxx:23628)()

/home/wesm/code/arrow/python/pyarrow/error.pxi in pyarrow.lib.check_status (/home/wesm/code/arrow/python/build/temp.linux-x86_64-3.5/lib.cxx:8242)()

ArrowNotImplementedError: /home/wesm/code/arrow/cpp/src/arrow/python/builtin_convert.cc:740 code: InferArrowTypeAndSize(obj, &size, &type)
/home/wesm/code/arrow/cpp/src/arrow/python/builtin_convert.cc:319 code: InferArrowType(obj, out_type)
/home/wesm/code/arrow/cpp/src/arrow/python/builtin_convert.cc:299 code: seq_visitor.Visit(obj)
/home/wesm/code/arrow/cpp/src/arrow/python/builtin_convert.cc:180 code: VisitElem(ref, level)
No type inference for dicts
```

I would like to support this, but implementing it is quite some work. Patches are welcome. I opened https://issues.apache.org/jira/browse/ARROW-1705 to track the feature request.

**Comment by wesm** [comment]
By the way, you can use `pa.StructArray.from_arrays` to create a struct:

```
In [3]: fields = [pa.array(['foo', 'foo', 'foo']), pa.array(['bar', 'bar', 'bar'])]

In [4]: arr = pa.StructArray.from_arrays(['key', 'value'], fields)

In [5]: arr
Out[5]: 
<pyarrow.lib.StructArray object at 0x7f874084b098>
[
  {'value': 'bar', 'key': 'foo'},
  {'value': 'bar', 'key': 'foo'},
  {'value': 'bar', 'key': 'foo'}
]
```

**Comment by dg3feiko** [comment]
Thank you for your correction and info, Wes.

I am not quite sure how to compose nested objects and arrays in pyarrow with some low level primitives, e.g. part of my json fields look like
```json
{"obj": {"foo":"bar"}, "arr": [ {"key":"value1"},{"key":"value2"} ] }
{"obj": {"foo":"bar2"}, "arr": [ {"key":"value3"},{"key":"value4"} ] }
{"obj": {"foo":"bar3"}, "arr": [ {"key":"value5"},{"key":"value6"} ] }
```
I understand it needs some works and in the future this may be natively supported by pyarrow. For the moment I'd just convert them as JSON strings or flatten them in a `obj_foo` name style.

Thank you all the same for the great job.

**Comment by wesm** [comment]
You need to unravel this data into its columnar representation. What's the effective schema here?

```
obj: struct<foo: string>
arr: list<item: struct<key: string>>
```

This data has 2 leaf nodes: `obj.foo` and `obj.arr.item.key`. So you need to "shred" the leaf data and assemble the Arrow arrays by following the columnar data model:

```
foo_data = pa.array(['bar', 'bar2', 'bar3'])
arr_data = pa.array(['value1', 'value2', 'value3', 'value4', 'value5', 'value6'])

obj = pa.StructArray.from_arrays(['foo'], [foo_data])

arr_offsets = pa.array([0, 2, 4, 6], type='int32')
arr = pa.ListArray.from_arrays(arr_offsets,
                               pa.StructArray.from_arrays(['key'], [arr_data]))
```

Now we have:

```python
In [17]: obj
Out[17]: 
<pyarrow.lib.StructArray object at 0x7f4ab64daa98>
[
  {'foo': 'bar'},
  {'foo': 'bar2'},
  {'foo': 'bar3'}
]

In [18]: arr
Out[18]: 
<pyarrow.lib.ListArray object at 0x7f4ab64e7a98>
[
  [{'key': 'value1'},
   {'key': 'value2'}],
  [{'key': 'value3'},
   {'key': 'value4'}],
  [{'key': 'value5'},
   {'key': 'value6'}]
]
```

Hope this helps

**Comment by aahaselgrove** [comment]
I don't believe the original answer in this issue was answered - is it possible to write structured data to Parquet? I tried the following:

````
data = pa.StructArray.from_arrays([pa.array([1])], ['a'])
table = pa.Table.from_pydict({'data': data})
pq.write_table(table, 'test.parquet')
````

and it gives the error: `pyarrow.lib.ArrowNotImplementedError: Level generation for Struct not supported yet`.

**Comment by emkornfield** [comment]
Not at the moment: https://issues.apache.org/jira/browse/ARROW-1644?filter=-1 is tracking the feature.

**Comment by RezaeiNasab** [comment]
As @wesm is mentioned above, I wrote the following code in python:

fields = [pa.array(['foo', 'foo', 'foo']), pa.array(['bar', 'bar', 'bar'])]
arr = pa.StructArray.from_arrays(['key', 'value'], fields)
print(arr)

and I get the following error:

expected bytes, pyarrow.lib.StringArray found

why?

**Comment by emkornfield** [comment]
you probably want `print(str(arr))`

**Comment by Balive13** [comment]
The error is related to "arr = pa.StructArray.from_arrays(['key', 'value'], fields)".

**Comment by emkornfield** [comment]
It looks like you have the args reversed: https://arrow.apache.org/docs/python/generated/pyarrow.StructArray.html#pyarrow.StructArray.from_arrays

**Comment by Balive13** [comment]
I reversed that args i.e., "arr = pa.StructArray.from_arrays(fields, ['key', 'value'])" and I got the below result:
```
-- is_valid: all not null
-- child 0 type: string
  [
    "foo",
    "foo",
    "foo"
  ]
-- child 1 type: string
  [
    "bar",
    "bar",
    "bar"
  ]```
