### ISSUE TITLE
[C++] Is building for Windows 32 Bit/x86 supported?

### ISSUE THREAD

**Issue by VisBeo** [apache/arrow#12258]
I'm new to the Apache Arrow project and want to make use of it to simply write Parquet files (which I was able to do when building for Win x64).
Using Arrow v6.0.1, I followed the instructions [here](https://github.com/apache/arrow/blob/master/docs/source/developers/cpp/building.rst) and [here](https://github.com/apache/arrow/blob/master/docs/source/developers/cpp/windows.rst). I changed the parameters from `x64` to `x86` or `Win32` respectively (_VsDevCmd.bat_ and the _CMAKE_ call). 

If I try to build the resulting VS solution as "Win32|Debug" in Visual Studio 2019, I get various errors related to "64 bit vs 32 bit incompatibilities". E. g. in bit_util.h "_Error C3861 '_BitScanReverse64': identifier not found	arrow_shared_" and others. 

**Although I couldn't find an explicit mention, I assumed that Arrow could be built "out of the box" to target Windows/x86 (Win32)?**

I found an older issue ([#5787](https://github.com/apache/arrow/issues/5787)) which asks a similar question. Is there any update since 2019 (unfortunately, I couldn't find the related Jira ticket)?
Are there any current efforts to be able to build 32 bit Window applications using the sources found (CMAKE lists, C++ source code) in the Arrow-cpp GitHub repository?

**Comment by pitrou** [comment]
There are no such efforts but we are willing to accept a PR to fix this issue if you'd like to. Could you perhaps start by opening an issue [on JIRA](https://arrow.apache.org/docs/developers/contributing.html#report-bugs-and-propose-features)?

**Comment by VisBeo** [comment]
@jmckenna 
In my use case it was sufficient to work with the 64-bit version. To be able to build the project also in 32-bit/x86 would have been necessary in my case only for the sake of completeness ("nice to have"). Therefore, I have unfortunately not been able to solve the issue conclusively.

**Comment by jmckenna** [comment]
Thanks @VisBeo
