### ISSUE TITLE
How to use delimiter with CSVWriter w/ write_options?

### ISSUE THREAD

**Issue by imranghori** [apache/arrow#12367]
Hi all, has anyone try to implement customer parsing options with CSV_writer? I am trying different combination if it could accept as kwargs. 

Any help would be highly appreciated.

Regards,
ighori.

**Comment by westonpace** [comment]
Which language are you working on?

Custom delimiters are not supported by the C++ CSV writer at the moment (which is what is used by the python and R implementation).  Can you open a JIRA ticket with your request.

**Comment by pitrou** [comment]
So the C++ CSV writer finally supports setting a custom delimiter (see #12426), so I'm going to close this issue. Sorry for the delay!
