### ISSUE TITLE
bind_rows functionality

### ISSUE THREAD

**Issue by flachboard** [apache/arrow#12371]
Hello,

Is there any way to bind rows of multiple open datasets before collecting into memory?

I've tried bind_rows, rbind, and union_all. Each function errors out.

Thanks!

**Comment by jonkeane** [comment]
Would you be able to provide a minimal example that shows what you're trying to do here?

**Comment by flachboard** [comment]
See below! Thanks!

df1 <- open_dataset(df1_path)
df2 <- open_dataset(df2_path)

df1 %>%
  select(var1, var2) %>%
  bind_rows(
    df2 %>%
      select(var1, var2)
  )

**Comment by wjones127** [comment]
You can union two (or more) datasets by passing a list of them to `open_dataset()`.

```
df1 <- open_dataset(df1_path)
df2 <- open_dataset(df2_path)

df <- open_dataset(list(df1, df2))
```

https://arrow.apache.org/docs/r/reference/open_dataset.html

**Comment by flachboard** [comment]
So if I do this, I get the following error...

df <- open_dataset(list(df1 %>% select(var1, var2), df2 %>% select(var1, var2)))

Error: x is not a character vector

My parquet files don't have all the same fields FYI.

**Comment by wjones127** [comment]
> Error: x is not a character vector

Unfortunately once you run `select` it returns a query and not a pure dataset, so it's no longer a valid input to `open_dataset()`.

We haven't implemented `union_all()` for queries yet; if we did I think it would look like this:

```r
df <- union_all(select(ds1, x), select(ds2, x))
# Currently, you'd have to materialize each side
df <- union_all(select(ds1, x) %>% collect(), select(ds2, x) %>% collect())
```

I think for now you'd have to either collect it in memory or if the data really is too large, process each part separately and then union together later.

Thanks for bringing up this use case; it's definitely something we want better support for. I'll create a Jira ticket to implement `union_all` for arrow queries.

**Comment by wjones127** [comment]
See https://issues.apache.org/jira/browse/ARROW-15622

**Comment by marciz** [comment]
Try
```
df <- open_dataset(c(df1_path, df2_path), unify_schemas = TRUE) %>%
select(var1, var2)
```

**Comment by flachboard** [comment]
Awesome! I got it working! For clarity if there's anyone else struggling with this, I normally just point to the folder when running the open_dataset function. To get this to work, I needed to point to the parquet file.

df <- open_dataset(c(df1.parquet, df2.parquet), unify_schemas = TRUE) %>%
select(var1, var2)

**Comment by jorisvandenbossche** [comment]
Assuming this issue has been answered (and a JIRA was opened to track some improvements), I am going to close this issue. But feel free to further respond or reopen the issue if that was a wrong assessment.
