### ISSUE TITLE
Error: Unable to read map<string, double> data type

### ISSUE THREAD

**Issue by rileyhun** [apache/arrow#12396]
We have some data stored in parquet file format generated from a `pyspark` pipeline and we are trying to read it in using `pyarrow`. Unfortunately, `pyarrow` is not able to interpret one of the stored data types. Would prefer being able to read in the data without relying on `pyspark`. I am using `pyarrow=7.0`

Example:

```
import s3fs
import pyarrow.parquet as pq

fs = s3fs.S3FileSystem()
bucket_uri = 's3://data/batch=1000doc/part=0'

dataset = pq.ParquetDataset(bucket_uri, filesystem=fs)
table = dataset.read()
table.to_pandas()
```

Error:

```
ArrowNotImplementedError: Not implemented type for Arrow list to pandas: map<string, double>
```

**Comment by rileyhun** [comment]
Hello @wjones127 - thanks so much for your response. 

Here is the data type for that column: `(MapType(map<int64, map<string, map<string, double>>>))`

**Comment by wjones127** [comment]
@rileyhun Does the following snippet fail for you? I'm see conversion of that schema go through fine in this example.

```python
import pyarrow as pa
import pandas as pd

data = [[('x', 1.0), ('y', 0.0)], [('a', 2.0), ('b', 45.0)]]
ty = pa.map_(pa.string(), pa.float64())
inner = pa.array(data, type=ty)
array = pa.MapArray.from_arrays([0,1], ['one', 'two'], inner)
array = pa.MapArray.from_arrays([0,1], [1], array)
table = pa.table({'col': array})
array.type
# MapType(map<int64, map<string, map<string, double>>>)
table.to_pandas()
#                                           col
# 0  [(1, [('one', [('x', 1.0), ('y', 0.0)])])]
```

**Comment by jorisvandenbossche** [comment]
@rileyhun can you also verify the pyarrow version that you are using (eg check `pyarrow.__version__` at runtime, to ensure you are actualy using the latest 7.0)

**Comment by rileyhun** [comment]
@jorisvandenbossche - sorry for the delay in my response. We found a workaround, so going to close the issue.

**Comment by rileyhun** [comment]
Thanks @wjones127 - I will try that example shortly. Thanks again for your assistance.
