### ISSUE TITLE
Pyarrow write dataset ignores delimiter 

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [apache/arrow#12413]
Hi Guys.
I tried to report this bug/possible bug with jira but I failed so writing here.
I have a dataset and when I am trying to write it as tsv or tab separated file pyarrow  anyway writes csv.
here is my code :
```python
ds.write_dataset(data=table, base_dir='adapter/tsv/',
                 basename_template='my-unique-name-{i}.tsv', 
                 format=ds.CsvFileFormat(parse_options=csv.ParseOptions(delimiter="\t")), 
                 partitioning=['month'],
                 existing_data_behavior='overwrite_or_ignore' )
```
here is what I am getting 
```csv 
"day","year"
26,1958
11,1912
26,1942
```
here is what I should get : 

```tsv
day     year
26      1958
11      1912
26      1942
```
IT feels like pyarrow ignoring format or delimiter
Thanks in advance

**Comment by lidavidm** [comment]
Unfortunately ParseOptions only applies to reading data; [WriteOptions](https://github.com/apache/arrow/blob/6b7c7a2702466f7c3c9c1f9dd41bc42458cff398/cpp/src/arrow/csv/options.h#L187) controls writing data. We don't currently support changing the delimiter when writing.

Please see https://issues.apache.org/jira/browse/ARROW-15672.

**Comment by HaykManukyanAvetiky** [comment]
ok thanks
