### ISSUE TITLE
Parquet Partition issues with Int64 Null

### ISSUE THREAD

**Issue by NarayanB** [apache/arrow#12416]
I'm not sure if no-one has observed this. There are multiple libraries libraries out there like pandas, vaex etc. They all can generate arrow table from their dataframe.  From there you can chose to code like pq.write_to_dataset(parquet_folder, partition_columns..). The issue is that for Int64, though the pyarrow schema is confirmed before write as 'int64', during write parquet with partition, it is converted as float64, if atleast there is one row with null value. This also messes up the data with inaccurate values. The latest pandas supports 'Int64', so I'm not sure if there is any specific parameter in kwargs that i need to pass. Using partition is very common and I tried with pyarrow versions 4,5,6 though I have to use 4.0.1. Please advise

**Comment by NarayanB** [comment]
This issue very close to 'https://issues.apache.org/jira/browse/ARROW-6114', but it affects Int64 a lot

**Comment by NarayanB** [comment]
Hi,
Thanks for the answer. In my case, i don't convert to pandas but i have the table whose schema is correct as int64 before i call pq.write_to_dataset(...). The issue is when i read it back using pq.read_table. I tried providing schema during pq.write_to_dataset but didnt work.

**Comment by wjones127** [comment]
> The issue is when i read it back using pq.read_table. I tried providing schema during pq.write_to_dataset but didnt work.

Could you provide a reproducible example where that did not work?

**Comment by jorisvandenbossche** [comment]
(small sidenote that the Int64 dtype from pandas should _in principle_ already be supported and work out of the box in pandas <-> arrow conversion (so for example you wouldn't need `type_mapper`), so yes, a reproducible code example to illustrate your issue would be useful)

**Comment by NarayanB** [comment]
I'm not using table.to_pandas() at all. Polars csv has method to convert df to table. I'm directly writing pq.write_to_dataset method on that table. I will prepare a simple example soon

**Comment by NarayanB** [comment]
import pandas as pd
import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds

def read_csv(csv_file):
     print("reading csv")
     csv = """pid1,pid2,intCol,strCol
     2010,10000,23455555508999,Peaceful
     2015,15000,7753285016841556620,Happy
     2020,25000,,World""".encode()

     good_df = (pl.read_csv(csv, dtypes={"intCol": pl.Utf8})
           .with_column(pl.col("intCol").str.replace("", "0").cast(pl.Int64))
           )
     bad_df = pl.read_csv(csv)
     df = good_df
     #df = bad_df
     print(df.head(10))
     table = df.to_arrow()
     print('Table Schema..\n',table.schema)
     return table

def save_table(table, location):
    pq.write_to_dataset(table, location, partition_cols=['pid1','pid2'])

def read_table(location):
    schema = pa.schema([ ('pid1', pa.int64()),
                         ('pid2', pa.int64())

    ])
    partition = ds.partitioning(schema=schema, flavor='hive')
    dataset = ds.dataset(location, partitioning=partition)
    table = dataset.to_table()
    print("Retrived table schema\n", table)
    df = pl.from_arrow(table)
    print(df.head(10))

table = read_csv(None)
save_table(table, '../data')
read_table('../data')

Please run this program twice once with df = good_df and next time df = bad_df. You will see the issue that the int64 value toggling between 7753285016841556620 vs 7753285016841556992. You will have to clear the partition data for each run

I think I issue is that for some very big int64 values having null in one field column creates the issue. There is no pandas involved here. I haven't seen the issue if the int64 field value is something like 10000 or 2500001 etc

**Comment by wjones127** [comment]
When I try to run this, here is my output for "bad_df" run:

```
reading csv
shape: (3, 4)
┌──────┬───────┬─────────────────────┬──────────┐
│ pid1 ┆ pid2  ┆ intCol              ┆ strCol   │
│ ---  ┆ ---   ┆ ---                 ┆ ---      │
│ i64  ┆ i64   ┆ i64                 ┆ str      │
╞══════╪═══════╪═════════════════════╪══════════╡
│ 2010 ┆ 10000 ┆ 23455555508999      ┆ Peaceful │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2015 ┆ 15000 ┆ 7753285016841556620 ┆ Happy    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2020 ┆ 25000 ┆ null                ┆ World    │
└──────┴───────┴─────────────────────┴──────────┘
Table Schema..
 pid1: int64
pid2: int64
intCol: int64
strCol: large_string
Retrived table schema
 pyarrow.Table
intCol: int64
strCol: large_string
pid1: int64
pid2: int64
shape: (3, 4)
┌─────────────────────┬──────────┬──────┬───────┐
│ intCol              ┆ strCol   ┆ pid1 ┆ pid2  │
│ ---                 ┆ ---      ┆ ---  ┆ ---   │
│ i64                 ┆ str      ┆ i64  ┆ i64   │
╞═════════════════════╪══════════╪══════╪═══════╡
│ 23455555508999      ┆ Peaceful ┆ 2010 ┆ 10000 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 7753285016841556992 ┆ Happy    ┆ 2015 ┆ 15000 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ null                ┆ World    ┆ 2020 ┆ 25000 │
└─────────────────────┴──────────┴──────┴───────┘
```

My versions:

```python
print(pa.__version__) # 4.0.0
print(pl.__version__) # 0.13.3
```

So I don't think I am seeing the same behavior as you are; the output looks good to me. Could you share what you are seeing and also exactly which versions of polars and pyarrow you are using?

**Comment by NarayanB** [comment]
There is issue with serialization/de-serialization right? the csv had int64 as 7753285016841556620. After reading from parquet partition it is 7753285016841556992

**Comment by NarayanB** [comment]
i'm using polars 0.12.6 and pyarrow 4.0.1

**Comment by wjones127** [comment]
> There is issue with serialization/de-serialization right? the csv had int64 as 7753285016841556620. After reading from parquet partition it is 7753285016841556992

Okay yeah I see that now. I was expecting the issue you were talking about earlier about converting to float64, but sounds like that's a different problem then, right?

**Comment by NarayanB** [comment]
I read in one forum that arrow or pandas convert int64 to float when there is null issue with Int64. That's why i included good_df to show the issue. if the int64 fields have no None/Nan then everything works fine

**Comment by wjones127** [comment]
Good new is this should be an easy fix: the newer datasets implementation doesn't have this issue, so you can pass in `use_legacy_dataset=False` (default is `True` for now). See the example below.

@jorisvandenbossche Is the legacy being deprecated and removed later? Or should we consider looking into fixing this?

```python
import pandas as pd
import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds
import tempfile

def read_csv(csv_file):
    print("reading csv")
    csv = """pid1,pid2,intCol,strCol
    2010,10000,23455555508999,Peaceful
    2015,15000,7753285016841556620,Happy
    2020,25000,,World""".encode()
    good_df = (pl
            .read_csv(csv, dtypes={"intCol": pl.Utf8})
           .with_column(pl.col("intCol").str.replace("", "0").cast(pl.Int64))
       )
    bad_df = pl.read_csv(csv)
    #df = good_df
    df = bad_df
    print(df.head(10))
    table = df.to_arrow()
    print('Table Schema..\n',table.schema)
    print(table['intCol'])
    return table

def save_table(table, location):
    pq.write_to_dataset(table, location, partition_cols=['pid1','pid2'], use_legacy_dataset=False)
    # Old deprecated datasets API
    # pq.write_to_dataset(table, location, partition_cols=['pid1','pid2'])

def read_table(location):
    schema = pa.schema([ ('pid1', pa.int64()), ('pid2', pa.int64())])
    partition = ds.partitioning(schema=schema, flavor='hive')
    dataset = ds.dataset(location, partitioning=partition)
    table = dataset.to_table()
    print(table['intCol'])
    print("Retrived table schema\n", table)
    df = pl.from_arrow(table)
    print(df.head(10))

ds_dir = tempfile.mkdtemp()

table = read_csv(None)
save_table(table, ds_dir)
read_table(ds_dir)
``` 

```
reading csv
shape: (3, 4)
┌──────┬───────┬─────────────────────┬──────────┐
│ pid1 ┆ pid2  ┆ intCol              ┆ strCol   │
│ ---  ┆ ---   ┆ ---                 ┆ ---      │
│ i64  ┆ i64   ┆ i64                 ┆ str      │
╞══════╪═══════╪═════════════════════╪══════════╡
│ 2010 ┆ 10000 ┆ 23455555508999      ┆ Peaceful │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2015 ┆ 15000 ┆ 7753285016841556620 ┆ Happy    │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ 2020 ┆ 25000 ┆ null                ┆ World    │
└──────┴───────┴─────────────────────┴──────────┘
Table Schema..
 pid1: int64
pid2: int64
intCol: int64
strCol: large_string
[
  [
    23455555508999,
    7753285016841556620,
    null
  ]
]
[
  [
    23455555508999
  ],
  [
    7753285016841556620
  ],
  [
    null
  ]
]
Retrived table schema
 pyarrow.Table
intCol: int64
strCol: large_string
pid1: int64
pid2: int64
shape: (3, 4)
┌─────────────────────┬──────────┬──────┬───────┐
│ intCol              ┆ strCol   ┆ pid1 ┆ pid2  │
│ ---                 ┆ ---      ┆ ---  ┆ ---   │
│ i64                 ┆ str      ┆ i64  ┆ i64   │
╞═════════════════════╪══════════╪══════╪═══════╡
│ 23455555508999      ┆ Peaceful ┆ 2010 ┆ 10000 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ 7753285016841556620 ┆ Happy    ┆ 2015 ┆ 15000 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ null                ┆ World    ┆ 2020 ┆ 25000 │
└─────────────────────┴──────────┴──────┴───────┘
```

**Comment by wjones127** [comment]
Here's a shorter reproduction of the issue, which also fails in 7.0.0:

```python
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.dataset as ds
import tempfile

table = pa.table({
    'x': pa.array([23455555508999, 7753285016841556620, None]),
    'y': pa.array(['a', 'b', 'c'])
})

ds_dir = tempfile.mkdtemp()
pq.write_to_dataset(table, ds_dir, partition_cols=['y'])

table_after = ds.dataset(ds_dir).to_table()
print(table['x'])
print(table_after['x'])
assert table['x'] == table_after['x']
```

Output:

```
[
  [
    23455555508999,
    7753285016841556620,
    null
  ]
]
[
  [
    23455555508999
  ],
  [
    7753285016841556992
  ],
  [
    null
  ]
]
```

**Comment by wjones127** [comment]
I created ARROW-15725 for this issue. Thanks @NarayanB for reporting this!

**Comment by NarayanB** [comment]
Thanks @wjones127. I will verify and let you know if any issues. Will it have impact on other existing (table) partitions wrt compatibility ?

**Comment by wjones127** [comment]
> Will it have impact on other existing (table) partitions wrt compatibility ?

The new datasets API is going to be compatible with most systems for partitioned data, including the legacy datasets in PyArrow.

The new datasets has generally better support, but there are a few extra pieces of information that the legacy datasets implementation exposes that's not in the new one yet. See ARROW-9720 for details.

**Comment by NarayanB** [comment]
Looks good after quick check on my side. Thanks for the quick response @wjones127

**Comment by NarayanB** [comment]
Hi @[wjones127],
I ran into issues with file_name getting overwritten like 1.parquet when i try to slice the table. Do i need to use my own file name ? Could you please suggest how ?

**Comment by wjones127** [comment]
@NarayanB The two parameters you want to look at are `basename_template`, which defines the filename, and `existing_data_behavior`, which controls how PyArrow responds to existing files. `existing_data_behavior` should be `"error"` by default, which should prevent overwrites. See: https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html#pyarrow.dataset.write_dataset

I'm not sure what you mean by "slice the table". How did that produce overwrites? Do you have code you can share?

**Comment by NarayanB** [comment]
@wjones127 -> the basename_template doesn't work if using legacy_dataset=False, while using the API pq.write_to_dataset. While checking the code, I see that it throws the exception. The other option is to use ds.write_dataset. I was able to get it working. Pyarrow table has the slice option which implies chunking. I would have expected pq.write_to_dataset returns the filename which would have allowed me to rename it. While using ds.write_dataset, I think the issue is gone with Int64 null partition issue. Not sure how though.

**Comment by wjones127** [comment]
> the basename_template doesn't work if using legacy_dataset=False, while using the API pq.write_to_dataset.

Sorry, that method is only available in `ds.write_dataset`. That's the API that's update more moving forward, so I recommend you switching to using that function.

> While using ds.write_dataset, I think the issue is gone with Int64 null partition issue. Not sure how though.

That's the new datasets API (equivalent to passing `use_legacy_datasets=False` to `pq.write_to_dataset`), so makes sense you wouldn't have that problem.

**Comment by NarayanB** [comment]
@wjones127 -> Thanks for the explanation
