### ISSUE TITLE
[Go] Proposal: simpler parquet.ReaderAtSeeker interface

### ISSUE THREAD

**Issue by tilinna** [apache/arrow#12428]
I didn't find any code from v8-master using the io.Reader interface of the `parquet.ReaderAtSeeker`. And the only usage for the io.Seeker was to find out the size of the file.

```go
type ReaderAtSeeker interface {
	io.ReaderAt
	io.ReadSeeker
}
```
Therefore, I propose the interface to be simplified (and possibly renamed) to:

```go
type SizedReaderAt interface {
	Size() int64
	io.ReaderAt
}
```

For example, io.SectionReader and bytes.Reader already implement this combination, so the changes should be minimal.

Also, when converting a client-provided ReaderAtSeeker (_SizedReaderAt_) into a io.SectionReader (in buffered reading mode), it would be a good idea to first test whether the instance is already implementing the SectionReader API too.

_Update:_ I realized the os.File doesn't implement the Size() int64, so an alternative for a simpler interface would be just to replace the io.ReadSeeker with an io.Seeker.

**Comment by zeroshade** [comment]
Not a bad idea at all. I can try to get to this when I have a chance, but feel free to file a PR and tag me on it if you'd like to give it a go yourself.

Sorry for the delay in response here, I was on vacation last week.
