### ISSUE TITLE
[Flight] If the flight server and client are just in different processes one same server, can we avoid the data copies in arrow flight?

### ISSUE THREAD

**Issue by hujianxin** [apache/arrow#12473]
Thank!

**Comment by lidavidm** [comment]
Flight is built on gRPC which would have to implement this optimization. gRPC C++ does not have this optimization. gRPC Java does have an "InProcessTransport" which you can set up with the flight-grpc module, but this will still go through some serialization/deserialization.

What is the use case?

**Comment by hujianxin** [comment]
@lidavidm Thanks for the reply.

1. I use the c++ version of arrow and grpc
2. My project (storage server) wants to provide a `Scan` interface for natively client to share an Arrow RecordBatch to this natively client.
3. I want to know that if the recordbatch sharing can be zero-copy

**Comment by lidavidm** [comment]
Interesting. We are working on a UCX (https://github.com/openucx/ucx) backend, which I believe has optimizations for intraprocess data transfer. I'll investigate this more thoroughly and get back to you.

In any case, I think it would be valuable to have a 'truly'/guaranteed zero-copy in process transport. The UCX work would also pave the path towards supporting that.

**Comment by lidavidm** [comment]
BTW: is this work open source in any way? It would be nice to see more examples of Flight being used. And/or depending on the details it would help plan out how to support this. (Is this something like [Plasma](https://arrow.apache.org/docs/python/plasma.html) for instance? Plasma maps shared memory into client processes for zero-copy data sharing.)

**Comment by hujianxin** [comment]
And thanks for the advice on UCS, I'll consider your suggestion carefully.

**Comment by hujianxin** [comment]
Our work maybe open source this year or next year, Thanks.

**Comment by hujianxin** [comment]
Our project is a kudu/hbase-like storage system, we need to provide a native client for calculate engine to accelerate the data reading for it. And the calculate engine is deployed on same machine with our storage server.

**Comment by hujianxin** [comment]
Do we have more examples besides `flight/integration_tests/test_integration_client.cc`，It's difficult to setup an demo flight serivce with custom service method for me 😄

**Comment by lidavidm** [comment]
Interesting! Would love to hear more once it's ready.

As for examples: yes, we are working on more for the Cookbook. See https://arrow.apache.org/cookbook/cpp/flight.html

I do want to provide an example of a Flight service with custom gRPC methods, if that's what you're asking about (just gotta find some time to work on it…) There's also https://github.com/apache/arrow/blob/master/cpp/examples/arrow/flight_grpc_example.cc for that use case. Hope this helps!

**Comment by lidavidm** [comment]
Filed https://issues.apache.org/jira/browse/ARROW-15756 to track benchmarking this case, to start with. 

I'll close this now, but if you have other questions, don't hesitate to reach out here, on JIRA, or on the mailing list at user@arrow.apache.org. Particularly if you have questions about how to accomplish things with Flight - we can add Cookbook recipes and/or documentation as appropriate, and knowing where people are confused helps us address this (documentation is sorely lacking as you have found).

**Comment by lidavidm** [comment]
Just FYI: the shared memory transport gets about 8GB/s. I can't get UCX's self-transport to work right now, that will need some additional digging. gRPC gets about 3.5GB/s on this machine over TCP loopback. (Of course, even if this is fast, it's still copying data which is undesirable for this particular case.)

**Comment by hujianxin** [comment]
Thansk for your kind reply and great information!

**Comment by hujianxin** [comment]
@lidavidm
