### ISSUE TITLE
[C#] Are the README file up-to-date?

### ISSUE THREAD

**Issue by rijukk** [apache/arrow#12498]
We are in the process of moving our C# in-memory data storage based on List<List<T>> to Arrow Table based data structure for faster data transfer between processes.  However we are not seeing much discussion or information about C# Arrow library.

I have few quetion on the [README](https://github.com/apache/arrow/blob/master/csharp/README.md) file on the Apache Arrow C# page. 

1.  **Implementation** section,  **Arrow 0.11 (specification)**
> 1. What is the current Arrow specification version?
> 2. How much feature missing in C# library in comparison with C++ or Python? 

2. **Not Implemented** section, Types -> **Table**. 
However C# library contains **Table**, upon the search I have noticed a PR [ARROW-4719](https://github.com/apache/arrow/pull/3806) discussing about ChunkedArray, Column and Table implementation on C#.

Whether the README file not up-to-date?
Is it safe to move ahead with C# Arrow Table?

@wesm @pgovind @eerhardt

**Comment by eerhardt** [comment]
@rijukk - yes there is some staleness on the C# README. You can find the most up-to-date support information in https://github.com/apache/arrow/blob/master/docs/source/status.rst.

> What is the current Arrow specification version?

C# has integration tests to ensure that basic read-write interop between the other languages works correctly. C# supports the 1.0 format version doc'd here: https://arrow.apache.org/docs/format/Columnar.html

> How much feature missing in C# library in comparison with C++ or Python?

See https://github.com/apache/arrow/blob/master/docs/source/status.rst for the full list.

> Is it safe to move ahead with C# Arrow Table?

It should be. Feel free to open JIRA issues for any missing functionality. Also feel free to submit fixes/features as well. They will be very welcome.
