### ISSUE TITLE
[python] Parallel parquet metadata resolution?

### ISSUE THREAD

**Issue by ericl** [apache/arrow#12501]
Hi all,

We're trying to improve the metadata resolution performance of pyarrow's ParquetDataset in Ray (https://github.com/ray-project/ray/issues/21274). Metadata resolution is a bottleneck when directories have 1000s of files in cloud storage.

Trying multiple threads or processes, both approaches seem to have issues:
- With threads: there is a mutex preventing concurrent metadata resolution of arrow::dataset::ParquetFileFragments.
- With processes: Serializing a ParquetFileFragment to send to another process triggers metadata resolution (again hitting the lock issue).

Is there a recommended way of achieving parallelism here?

**Comment by lidavidm** [comment]
Just to be clear, which mutex is the issue? `physical_schema_mutex_` in ParquetFileFragment is per-fragment

**Comment by lidavidm** [comment]
Or do you have something to reproduce this?

**Comment by lidavidm** [comment]
Oooooh, maybe we aren't releasing the GIL. Hold on…

**Comment by lidavidm** [comment]
D'oh. We'll have a patch up soon. Great catch :slightly_smiling_face:

**Comment by jorisvandenbossche** [comment]
It might not be the exact thing you need for Ray, but a related issue is that the actual "dataset discovery" (listing all files, etc) is currently single threaded, and that's something that might be possible to parallelize on Arrow's side: https://issues.apache.org/jira/browse/ARROW-8137

If we have the option to force to load the metadata already during dataset discovery (instead of later when accessed), that could also speed-up the serialization of the fragments (since all metadata will already be read at that point).

**Comment by lidavidm** [comment]
We could also perhaps not pickle the metadata if it isn't already present (and then the resolution could be spread across threads/processes/machines as desired by the application).

**Comment by clarkzinzow** [comment]
Our [current workaround](https://github.com/ray-project/ray/pull/22665/files#diff-52cb247b72f8fa8eeae58b8f430a56df8a486fcfd338edbcdf54d28d88bf539cR36-R48) is to register a custom pickle serializer that doesn't serialize the row group IDs and therefore doesn't trigger a metadata fetch. We don't yet create Parquet file fragments at the row group granularity so this _should_ work for us for now.

I'd be happy to contribute something akin to what @lidavidm mentioned upstream!

**Comment by lidavidm** [comment]
I think that makes sense to do. IMO pickling something shouldn't cause potentially expensive I/O, GIL or no GIL. 

I filed https://issues.apache.org/jira/browse/ARROW-15796 if you do wish to take a look at it.
