### ISSUE TITLE
Plasma store as a production kv store for arrays

### ISSUE THREAD

**Issue by patcollis34** [apache/arrow#12554]
Hey all, 
90% sure this isn't the place for this question, but couldn't find a gitter or slack to post for this project, possibly JIRA but I've never used that before. 
Wondering if the plasma datastore would/should be the recommended way to serve arrow(numpy arrays) in a distributed read-only environment(1 pod write, many pod read). In my first hack code I ran into ObjectID overwrite problems as well as the 20 bytes key limitation, which led me to think plasma wasn't fully suited for this workload. 
Current setup: syncing local LMDBs per pod with a master efs, but has a few problems(serialiazation times, unnecessary syncs, etc..). 
Any inputs or suggestions here is much appreciated
Also happy to delete this comment and move it to the proper forum

**Comment by westonpace** [comment]
Plasma, at the moment, is not currently maintained by anyone on this project.  The Ray project maintains a fork internally but (to the best of my knowledge) this isn't exposed as a standalone product.  For more background you can check [this dicussion](https://lists.apache.org/thread/8zd8j8l2w0xlwznzjnzd2s228v31ld61) and [this older discussion](https://lists.apache.org/list?dev@arrow.apache.org:lte=2y:plasma) from the mailing list.

This place is probably an ok spot to ask a question but if you want a better chance at input into "what would be a good way to serve arrays in a distributed read-only environment?" then the mailing list is your best bet.

**Comment by patcollis34** [comment]
great thank you for the info @westonpace

**Comment by liusitan** [comment]
for your use case, you may use [vineyard](https://github.com/v6d-io/v6d)
