### ISSUE TITLE
Support for automatic optimizations

### ISSUE THREAD

**Issue by mattgerg12** [apache/arrow#12568]
@nealrichardson Does arrow R query optimizer can automatically push down filters and projections based on the `dplyr` transformation queries that follows after the load using `open_dataset()`? I am aware that if we give the `partitioning =`option then it will only look the directories that are needed. But other than this are there any options to achieve the predicate and projection pushdown ?

Are there any plans to support this in future ? Or the recent integration with [duckDB](https://arrow.apache.org/docs/r/news/#2-duckdb-integration-6-0-0) is the solution Rarrow is leaning towards? But in this situation we are limited in using only duckDB verbs.

**Comment by nealrichardson** [comment]
There is no query optimizer per se, but yes, filter and projection are pushed down in the arrow query engine. duckdb also pushes predicates down to arrow when you use it to query an arrow dataset.

**Comment by mattgerg12** [comment]
Thanks @nealrichardson for replying. Sorry for the misunderstanding. Is this automatic filter and projection pushdown feature with `rarrow` and `dplyr` OR in general with `arrow` ? As I was thinking it's not from this [arrow article](https://arrow.apache.org/blog/2021/12/03/arrow-duckdb/) that says

_"For the comparison with Pandas, note that DuckDB runs in parallel, while pandas only support single-threaded execution. Besides that, one should note that we are comparing automatic optimizations. DuckDB’s query optimizer can automatically push down filters and projections. This automatic optimization is not supported in pandas, but it is possible for users to manually perform some of these predicate and filter pushdowns by manually specifying them them in the read_parquet() call."_

**Comment by westonpace** [comment]
This is not an answer exactly but I wanted to mention that there are a number of PRs & JIRAs in Arrow to actively adopt [Substrait](https://substrait.io/) which should open the door for users to plug in their own optimizer.  For example, if rarrow's dplyr bindings produced Substrait plans instead of arrow plans then you could do:

```
rarrow-dplyr -> substrait -> any optimizer you want (e.g. duckdb's optimizer, calcite, etc.) -> substrait -> arrow
```

Though that is perhaps a bit of an oversimplification as optimizers often would want information back from arrow as well (e.g. table statistics, cost estimates, etc.)

**Comment by nealrichardson** [comment]
The arrow C++ engine supports predicate pushdown. The R package wraps that and supports calling it with dplyr methods, which push down. The pandas comparison in the duckdb blog post you mention is using pandas, not arrow, to compute. It's only using arrow to read the parquet file into a pandas DataFrame.
