### ISSUE TITLE
Error while creating IpcFileFormat

### ISSUE THREAD

**Issue by vicky1999** [apache/arrow#12576]
I tried to read feather file and got the [documentation](https://arrow.apache.org/docs/dev/cpp/dataset.html).  when I tried it, I got an error

```
Undefined symbols for architecture arm64:
  "vtable for arrow::dataset::FileFormat", referenced from:
      arrow::dataset::FileFormat::FileFormat() in libfeather.a(featherparser.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for arrow::dataset::IpcFileFormat", referenced from:
      arrow::dataset::IpcFileFormat::IpcFileFormat() in libfeather.a(featherparser.cpp.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have debugged the code and found that the error occurs while creating IpcFileFormat.  
`auto format = std::make_shared<arrow::dataset::IpcFileFormat>();`

I am not sure if any library is missing.  Also, I am checking whether is it due to the reason, Some features of the core Arrow shared library can be switched off for improved build times if they are not required for your application.  because, in the [build](https://arrow.apache.org/docs/developers/cpp/building.html) documentation, -DARROW_IPC will be turned off.

**Comment by AlenkaF** [comment]
Hi @vicky1999, sorry for such a late reply.

`ARROW_IPC` is by default turned ON, see https://github.com/apache/arrow/blob/89c0214fa43f8d1bf2e19e3bae0fc3009df51e15/cpp/cmake_modules/DefineOptions.cmake#L351

Could you share the commands you use to build the Arrow C++ library, if the issue is still relevant?
