### ISSUE TITLE
Should an arrow IPC file written by the javascript arrow library be readable by the python arrow library?

### ISSUE THREAD

**Issue by dancoates** [apache/arrow#12606]
I came across this issue about a month ago where I couldn't read a arrow file created in js using the python library.

I created a issue in the JIRA thinking that this was a pretty major problem

https://issues.apache.org/jira/browse/ARROW-15642

but it doesn't seem like anyone has seen it yet.

So I'm wondering if I am misunderstanding the intentions of the arrow project? To me one of the major attractions is having a file format that allows data to be efficiently read, transformed, written, and then read again by another program or service. This isn't very useful if everything has to be written in the same language for this to work though?

**Comment by westonpace** [comment]
Your original understanding was correct.  Apologies that your ticket was overlooked.  Thanks for the ping :)
