### ISSUE TITLE
Binary release of version 7.0.0 missing for Centos 8

### ISSUE THREAD

**Issue by MartinMarciniszyn** [apache/arrow#12602]
Hi,

I was expecting to find the binary release of version 7.0.0 for Centos 8 on [JFrog](https://apache.jfrog.io/ui/native/arrow/centos/8/x86_64/Packages/). However, the latest rpm seems to be missing. Do I need to look elsewhere?

Thanks,

Martin

**Comment by westonpace** [comment]
@kou might have the best answer to this.

**Comment by kou** [comment]
CentOS 8 reached EOL on 2021-12: https://www.centos.org/centos-linux-eol/

We provide packages for AlmaLinux 8 instead: https://arrow.apache.org/install/

(We should remove "CentOS 8" from the page...)

**Comment by MartinMarciniszyn** [comment]
Thank you for the quick response, @kou.

Would you consider releasing binaries for [Centos Stream](https://blog.centos.org/2020/12/future-is-centos-stream/)?

**Comment by kou** [comment]
Could you open an issue on JIRA? https://issues.apache.org/jira/projects/ARROW/issues

**Comment by MartinMarciniszyn** [comment]
https://issues.apache.org/jira/browse/ARROW-15916
