### ISSUE TITLE
unable to install the apache arrow on debian 11

### ISSUE THREAD

**Issue by shettypriy** [apache/arrow#12686]
I am trying to install apache arrow on debian 11 by following the steps mentioned here https://arrow.apache.org/install/ , however, when trying to download the deb file using the command wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb it is not downloading the file and giving the Forbidden error. What has changed suddenly which is causing this issue?  Running apt-get update command on the server where the deb package was already installed  is giving the following error

Err:10 https://apache.jfrog.io/artifactory/arrow/debian bullseye InRelease                    
  403  Forbidden [IP: 13.32.43.79 443]
E: Failed to fetch https://apache.jfrog.io/artifactory/arrow/debian/dists/bullseye/InRelease  403  Forbidden [IP: 13.32.43.79 443]
E: The repository 'https://apache.jfrog.io/artifactory/arrow/debian bullseye InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Release links on the website https://arrow.apache.org/release/7.0.0.html is showing forbidden error

**Comment by pitrou** [comment]
This may be a transient issue, can you try again?

**Comment by kontrybutor** [comment]
Seems to be working again, thanks!

**Comment by shettypriy** [comment]
yes, it is working currently, thanks
