### ISSUE TITLE
[Python] replace_with_mask seg faults

### ISSUE THREAD

**Issue by lccnl** [apache/arrow#12761]
Hello,
there is currently an open issue in Jira, [ARROW-15928](https://issues.apache.org/jira/browse/ARROW-15928), reporting a seg faults with chunked arrays when the method `compute.replace_with_mask` is used.

Actually, for `pyarrow 7.0`, I believe the error extends to larger cases (while for `pyarrow 6.0.1` this does not happen): it turns out that whenever the mask has both True and False values, seg faults occurs.

The following minimal example should reproduce the error:
```
import pyarrow as pa
values=pa.array([0,1],pa.int64())
mask=pa.array([True,False],pa.bool_())
replace=pa.array([5],pa.int64())
pa.compute.replace_with_mask(values,mask,replace)
```

Thanks!

**Comment by lidavidm** [comment]
Thank you! I've crossposted this on GitHub, do you mind if we keep the discussion there?

**Comment by lccnl** [comment]
yes sure, can you keep this issue open though until it is solved? Thanks!

**Comment by jorisvandenbossche** [comment]
We use JIRA for tracking bugs, so are you OK with closing this issue? You can follow the JIRA issue if you want to be updated about when the bug gets fixed.

**Comment by lccnl** [comment]
ok then
