### ISSUE TITLE
[c++][substrait]Couldn't find a file named expression.pb

### ISSUE THREAD

**Issue by HaoChen-ch** [apache/arrow#12942]
https://github.com/apache/arrow/blob/master/cpp/src/arrow/engine/substrait/expression_internal.h  include a header "substrait/expression.pb.h" ,but I can find a protobuf file named expression.pb even in https://github.com/substrait-io/substrait/tree/main/proto/substrait or https://github.com/apache/arrow/tree/master/experimental/computeir  . Could you help me to get the expression.pb file

**Comment by westonpace** [comment]
It should be downloaded automatically as part of the build: https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1635-L1706

It's generated code from a .proto file which comes from the Substrait repository (an old version at the moment): https://github.com/substrait-io/substrait/blob/1210195692df721e05a9e9bd34fd7b9ae83dd35c/proto/substrait/expression.proto

**Comment by HaoChen-ch** [comment]
Thanks very much for the reply.

> It should be downloaded automatically as part of the build: https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1635-L1706
> 
> It's generated code from a .proto file which comes from the Substrait repository (an old version at the moment): https://github.com/substrait-io/substrait/blob/1210195692df721e05a9e9bd34fd7b9ae83dd35c/proto/substrait/expression.proto
> 
> The file in Substrait has since moved into algebra.proto

@westonpace  Thanks very much for the reply. I ran the arrow engine successfully with your help.And I plan to do some work with arrow,First I need to choose a IR to describe computation on Arrow data,I have read the email https://www.mail-archive.com/dev@arrow.apache.org/msg24388.html .And I am confused about which one to choose , substrait or Arrow Compute IR.Could you give me some advice?

**Comment by westonpace** [comment]
If you are referring to the flatbuffers-based serializer (`ir_consumer.h`/`ir_consumer.cc`) then I'm pretty sure this has been discontinued in favor of Substrait.

So you should use Substrait.

**Comment by westonpace** [comment]
However, Arrow does not yet have a fully compliant consumer of Substrait IR.  That is a work in-progress.  For example: https://issues.apache.org/jira/browse/ARROW-16036?jql=Project%20%3D%20ARROW%20and%20labels%20%3D%20substrait%20AND%20(status%20%3D%20Open%20OR%20status%20%3D%20%22In%20Progress%22)

**Comment by HaoChen-ch** [comment]
Thanks very much for the reply.I get it.
