### ISSUE TITLE
Index is not preserved when columns keyword is used in pq.read_table

### ISSUE THREAD

**Issue by swarnakumar** [apache/arrow#1302]
Create a pandas dataframe:

`df = pd.DataFrame({'a': [1,2,3], 'b': [3, 4, 5]}, index=list('abc'))`

Convert to arrow table:

`adf = pa.Table.from_pandas(df)`

Write to disk:
`pq.write_table(adf, 'example.parquet')`

Now read the file back:

```
In [53]: pq.read_table('example.parquet').to_pandas()
Out[53]:
   a  b
a  0  3
b  2  4
c  3  5
```

Index is preserved above.

But when columns keyword is used, the index vanishes (below):

```
In [54]: pq.read_table('example.parquet', columns=['a']).to_pandas()
Out[54]:
   a
0  0
1  2
2  3

```
```
In [55]: pq.read_table('example.parquet', columns=['a', 'b']).to_pandas()
Out[55]:
   a  b
0  0  3
1  2  4
2  3  5

```

## GitHub Issues for Apache Arrow

We support GitHub issues as a lightweight way to ask questions and engage with
the Arrow developer community. We use the Apache Software Foundation's JIRA
instance for maintaining a queue of development work and as the public record
for work on the project. So, feel free to delete this text and open an issue
here if you have a question or aren't sure whether something is a bug or
feature request. Any bugs, suggestions, or feature requests will eventually
need to end up in JIRA, either before or after completing a pull request.

See the Arrow JIRA project here: https://issues.apache.org/jira/browse/ARROW.

For more in-depth development discussions, please use the public mailing list
dev@arrow.apache.org (first subscribe by sending an e-mail to
dev-subscribe@arrow.apache.org).

**Comment by wesm** [comment]
@cpcloud is this a bug? My understanding is that using `pq.read_pandas` is the solution here

**Comment by wesm** [comment]
Confirmed that using `read_pandas` reads the additional index column, so the roundtrip works properly. 

```
In [13]: pq.read_pandas('example.parquet', columns=['a']).to_pandas()
Out[13]: 
   a
a  1
b  2
c  3
```

This is not documented in http://arrow.apache.org/docs/python/parquet.html so let's fix that

**Comment by wesm** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-2014 about improving the documentation
