### ISSUE TITLE
[Java] Arrow Java (8.0.0). How to allow reading parquet from S3

### ISSUE THREAD

**Issue by REASY** [apache/arrow#13110]
I'm trying to use Arrow Java (https://mvnrepository.com/artifact/org.apache.arrow/arrow-dataset/8.0.0) to read a parquet file from S3. It fails due to the native library being compiled without S3 support:
```
java.lang.RuntimeException: Got S3 URI but Arrow compiled without S3 support
at org.apache.arrow.dataset.file.JniWrapper.makeFileSystemDatasetFactory(Native Method)
at org.apache.arrow.dataset.file.FileSystemDatasetFactory.createNative(FileSystemDatasetFactory.java:35)
at org.apache.arrow.dataset.file.FileSystemDatasetFactory.<init>(FileSystemDatasetFactory.java:31)
```
The check happens in the Arrow C++ code https://github.com/apache/arrow/blob/d00caa947ea53774e0e6745c857bf622457081ad/cpp/src/arrow/filesystem/filesystem.cc#L724

Is there a java version that is bundled with libarrow_dataset with S3 support?

**Comment by raulcd** [comment]
@davisusanibar @kszucs my understanding is that we ship our own C++ lib with the jars. Is this not supported on Java or it was not compiled with S3 support?

**Comment by kou** [comment]
We need to add `-DARROW_S3=ON` to https://github.com/apache/arrow/blob/master/ci/scripts/java_jni_manylinux_build.sh and https://github.com/apache/arrow/blob/master/ci/scripts/java_jni_macos_build.sh to enable S3 support.

**Comment by REASY** [comment]
@raulcd @kou was able to get native library compiles with AWS SDK (draft https://github.com/apache/arrow/pull/13157). The size of libarrow_dataset_jni.so increased from 43.37 MBytes to 57.11 Mbytes so the final JAR also will be a bit bigger.

**Comment by kou** [comment]
Sure. Let's continue this at #13157. I close this.
