### ISSUE TITLE
Convert string time to timestamp.

### ISSUE THREAD

**Issue by Milad137** [apache/arrow#13111]
I have a csv file with datetime formatted as "%d/%m/%Y %I:%M %p". I can convert them to pandas datetime but when I use pyarrow's strptime I get the following error.
`ArrowInvalid: Failed to parse string: '9/03/2043 12:35 AM' as a scalar of type timestamp[s]`

Code to reproduce:
```
import pandas as pd
import pyarrow.compute as pc

# pd.__version__ == '1.3.4'
# pyarrow.__version__ == '8.0.0'

_ts = ["9/03/2043 12:35 AM"]
_format = "%d/%m/%Y %I:%M %p"

pd.to_datetime(_ts, format=_format)
pc.strptime(_ts, format= _format, unit='s')
```

**Comment by AlenkaF** [comment]
Unfortunately I wasn't able to reproduce locally:

```python
>>> import pyarrow
>>> import pandas as pd
>>> pyarrow.__version__
'8.0.0'
>>> pd.__version__
'1.4.2'

>>> import pyarrow.compute as pc
>>> _ts = ["9/03/2043 12:35 AM"]
>>> _format = "%d/%m/%Y %I:%M %p"

>>> pd.to_datetime(_ts, format=_format)
DatetimeIndex(['2043-03-09 00:35:00'], dtype='datetime64[ns]', freq=None)
>>> pc.strptime(_ts, format= _format, unit='s')
<pyarrow.lib.TimestampArray object at 0x7fcae0078e80>
[
  2043-03-09 00:35:00
]
```

**Comment by rok** [comment]
@Milad137 what OS are you on?

**Comment by Milad137** [comment]
> @Milad137 what OS are you on?

I'm on windows.

**Comment by rok** [comment]
@Milad137 Arrow is using [`arrow_strptime`](https://github.com/apache/arrow/blob/a713e7fa5dbd4997cfdac928cf868f38c31ac3d0/cpp/src/arrow/vendored/musl/strptime.c#L30) on windows and `strptime` on other systems. There might be a feature (available strptime flags) gap.
Could you please test a subset of flags and see if a particular one is missing for you? E.g.:
```
_ts = ["9/03/2043 12:35"]
_format = "%d/%m/%Y %I:%M"

_ts = ["9/03/2043"]
_format = "%d/%m/%Y"

_ts = ["12:35 AM"]
_format = "%I:%M %p"
```

**Comment by Milad137** [comment]
The first 2 are working fine, it's just the last one, when the "%p" tag gets added, it throughs an error.

```
>>> import pandas as pd
>>> import pyarrow.compute as pc

>>> # pd.__version__ == '1.3.4'
>>> # pyarrow.__version__ == '8.0.0'

>>> _ts = ["9/03/2043 12:35"]
>>> _format = "%d/%m/%Y %I:%M"
>>> print(pc.strptime(_ts, format= _format, unit='s'))
[
  2043-03-09 12:35:00
]

>>> _ts = ["9/03/2043"]
>>> _format = "%d/%m/%Y"
>>> print(pc.strptime(_ts, format= _format, unit='s'))
[
  2043-03-09 00:00:00
]

>>> _ts = ["12:35 AM"]
>>> _format = "%I:%M %p"
>>> print(pc.strptime(_ts, format= _format, unit='s'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\anaconda3\lib\site-packages\pyarrow\compute.py", line 250, in wrapper
    return func.call(args, options, memory_pool)
  File "pyarrow\_compute.pyx", line 341, in pyarrow._compute.Function.call
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Failed to parse string: '12:35 AM' as a scalar of type timestamp[s]
```

**Comment by jorisvandenbossche** [comment]
That seems a limitation of the vendored strptime implementation then. @rok do you want to open a JIRA for this?

**Comment by pitrou** [comment]
The vendored strptime implementation _does_ support `%p`, but we have to disable it on Windows because the behavior is locale-dependent and it's not easy to support there.

(of course, we may support it in a non-locale-dependent way, i.e. always use the same values as a "C" Unix locale)

**Comment by rok** [comment]
Sorry I lost sight on this one.
Opened [ARROW-16618](https://issues.apache.org/jira/browse/ARROW-16618). Similarly we have [ARROW-16443](https://issues.apache.org/jira/browse/ARROW-16443) reported from R.
Is there an easy way for users to change locale to "C" as a workaround @pitrou?

**Comment by RandomFractals** [comment]
I ran into the same issue while trying to convert string dates in Chicago crimes datatset.

What was the resolution of this ticket, or a workaround to convert date strings with AM/PM strings on Windows? I am on win10.

Data repo: https://github.com/RandomFractals/chicago-crimes

Error pic with more info:

![chi-crimes-pyarrow-strptime-error](https://user-images.githubusercontent.com/656833/197756369-067aa971-95e3-4130-978b-70704cbeec67.png)

**Comment by Milad137** [comment]
My workaround was to use VSCode dev container.

**Comment by rok** [comment]
Hey @RandomFractals! There was no work done on [ARROW-16618](https://issues.apache.org/jira/browse/ARROW-16618) as there wasn't much expressed interest. Right now @Milad137's workaround might be the best good idea.

**Comment by RandomFractals** [comment]
> My workaround was to use VSCode dev container.

not an option. seems like a very basic Python date conversion issue. I'll see if maybe Py 3.11 fixes that.

**Comment by RandomFractals** [comment]
also, @pitrou, if this is arrow `strptime` issue, could you please reopen this ticket?

I would like to to use pyarrow on Windows and this seems like very basic timestamp issue that is core to working with datasets with string timestamps.

**Comment by pitrou** [comment]
@RandomFractals Arrow uses a vendored copy of [musl's strptime](https://git.musl-libc.org/cgit/musl/tree/src/time/strptime.c), where we had to disable all format codes that use `langinfo`. So `%p` unfortunately won't work on Windows.

If you know of a more complete implementation of `strptime` that works on Windows, feel free to suggest it.

**Comment by RandomFractals** [comment]
@pitrou so, basically, this renders pyarrow useless for devs using Jupyter notebooks on windows with datasets that have string timestamps.

I don't have better suggestions. Sounds like an important internal issues for the core arrow dev team to look into and resolve. Thanks for your explanation of it.

**Comment by rok** [comment]
@RandomFractals Arrow is juggling several priorities. For instance we have several open [strptime issues](https://issues.apache.org/jira/browse/ARROW-15894).
However it's good to there's interest for this particular issue to be fixed so it can be prioritised when someone has time to work on in this space.

**Comment by davlee1972** [comment]
**Wouldn't it be cleaner to add a  locale parameter to strptime?**

pyarrow.compute.strptime(strings, /, format, unit, error_is_null=False, *, options=None, memory_pool=None)

**strftime does support a locale parameter to convert timestamps to string**

pyarrow.compute.strftime(timestamps, /, format='%Y-%m-%dT%H:%M:%S', **locale='C'**, *, options=None, memory_pool=None)[¶](https://arrow.apache.org/docs/python/generated/pyarrow.compute.strftime.html#pyarrow.compute.strftime)

**This would also need to be added to pyarrow.csv.ConvertOptions. The timestamp_parsers current is just a list of strptime format strings without any type of locale.**

https://arrow.apache.org/docs/python/generated/pyarrow.csv.ConvertOptions.html#pyarrow-csv-convertoptions

_timestamp_parsers_
A sequence of strptime()-compatible format strings, tried in order when attempting to infer or convert timestamp values (the special value ISO8601() can also be given). By default, a fast built-in ISO-8601 parser is used.

**Comment by davlee1972** [comment]
I got a temporary solution which modifies pyarrow.compute.strptime(), but I can't seem to figure out how to adjust a timestamp array by +/- number of hours.. tried using pyarrow.compute.add()

Here's the almost completed code..

```
import pyarrow.compute as pc

old_strpttime = pc.strptime

def new_strptime(*args, **kwargs):
    if 'format' in kwargs and '%p' in kwargs['format'] and '%I' in kwargs['format']:
        is_am = pc.count_substring(_ts, 'AM')
        kwargs['format'] = kwargs['format'].replace('%p','')
        strings = pc.replace_substring(pc.replace_substring(args[0], 'AM', ''), 'PM', '')
        new_timestamps = old_strpttime(strings, **kwargs)
        hour_adjustments = pc.case_when(pc.make_struct(
            pc.and_(is_am.cast("bool"), pc.equal(pc.hour(new_timestamps), 12)),
            pc.and_(pc.invert(is_am.cast("bool")), pc.equal(pc.hour(new_timestamps), 12)),
            is_am.cast("bool")
            ),
            -12,
            0,
            0,
            12
        )
        return {'original timestamps': args[0], 'without am|pm': new_timestamps, 'hours adjusted': hour_to adjust}
    else:
        return old_strpttime(*args, **kwargs)

pc.strptime = new_strptime
 
```

and the output with and without AM/PM hour additions..

```
>>> _ts = ["9/03/2023 00:35", "9/03/2023 12:35", "9/03/2023 6:35", "9/03/2023 18:35"]
>>> _format = "%d/%m/%Y %H:%M"
>>>
>>> pc.strptime(_ts, format= _format, unit='s')
<pyarrow.lib.TimestampArray object at 0x000001D0D0E48880>
[
  2023-03-09 00:35:00,
  2023-03-09 12:35:00,
  2023-03-09 06:35:00,
  2023-03-09 18:35:00
]
>>> _ts = ["9/03/2023 12:35 AM", "9/03/2023 12:35 PM", "9/03/2023 6:35 AM", "9/03/2023 6:35 PM"]
>>> _format = "%d/%m/%Y %I:%M %p"
>>>
>>> pc.strptime(_ts, format= _format, unit='s')
{'original timestamps': ['9/03/2023 12:35 AM', '9/03/2023 12:35 PM', '9/03/2023 6:35 AM', '9/03/2023 6:35 PM'], 'without am|pm': <pyarrow.lib.TimestampArray object at 0x000001D0D0E48D00>
[
  2023-03-09 12:35:00,
  2023-03-09 12:35:00,
  2023-03-09 06:35:00,
  2023-03-09 06:35:00
], 'hours to adjust': <pyarrow.lib.Int64Array object at 0x000001D0D0E48E20>
[
  -12,
  0,
  0,
  12
]}
```
