### ISSUE TITLE
How to use ARROW_CUDA

### ISSUE THREAD

**Issue by Adela0814** [apache/arrow#13145]
When I turn on the option `ARROW_CUDA`, I want to compile code with the line `#include <arrow/gpu/cuda_api.h>`. CUDA related headers are not currently installed. So I get the error message: `fatal error C1083: Cannot open include file: 'arrow/gpu/cuda_api.h': No such file or directory`. 

My question is whether `arrow `needs to install `CUDA` related header files, or what is the correct usage.

Please refer to https://github.com/microsoft/vcpkg/issues/24678

**Comment by Adela0814** [comment]
I found the installed header files, close this issue.

**Comment by kou** [comment]
Oh, sorry. I missed this.
