### ISSUE TITLE
write_batch vs write_table of ParquetWriter

### ISSUE THREAD

**Issue by kato1208** [apache/arrow#13142]
What is the difference between the two methods "write_table" and "write_batch" in ParquetWriter?
The following code is for comparing "write_table" and "write_batch", but they appear to work the same.
```
import pyarrow as pa
import pyarrow.parquet as pq

schema = pa.schema([
    pa.field('name', pa.string()),
    pa.field('id', pa.int32()),
    pa.field("points", pa.list_(pa.int32())),
])

records1 = [
    {
        "name": "Bob",
        "id": 323234,
        "points": [20, 12, 22],
    },
    {
        "name": "Alex",
        "id": 1234
    }
]

records2 = [
    {
        "name": "Niclas",
        "id": 123222,
        "points": [21, 32, 1],
    },
    {
        "name": "lena",
        "id": 12345
    }
]

writer = pq.ParquetWriter('test_table.parquet', schema=schema)

for records in [records1, records2]:
    table = pa.Table.from_pylist(records, schema=schema)
    writer.write_table(table)
writer.close()

print("show result for write_table")
print(pq.read_table("test_table.parquet").to_pandas())

writer = pq.ParquetWriter('test_batch.parquet', schema=schema)

for records in [records1, records2]:
    batch = pa.RecordBatch.from_pylist(records, schema=schema)
    writer.write_batch(batch)
writer.close()

print("show result for write_batch")
print(pq.read_table("test_batch.parquet").to_pandas())
```
```result
show result for write_table
     name      id        points
0     Bob  323234  [20, 12, 22]
1    Alex    1234          None
2  Niclas  123222   [21, 32, 1]
3    lena   12345          None
show result for write_batch
     name      id        points
0     Bob  323234  [20, 12, 22]
1    Alex    1234          None
2  Niclas  123222   [21, 32, 1]
3    lena   12345          None
```
I would like to split the data and write to the same parquet file to save memory, should I use "write_table" or "write_batch" ?
Also, what would be the best size after splitting?

I would appreciate your response.

**Comment by westonpace** [comment]
Use write_table if you have a table, use write_batch if you have a record batch.  They do the same thing.

Columns in a record batch are stored in contiguous buffers (e.g. an int32 array in a record batch will have one values buffer and one validity buffer).  Generally, when doing I/O, Arrow reads data one record batch at a time and you often can't read anything smaller than a record batch.  So if you store one giant record batch then you will need to read that entire giant record batch out all at once.

A table contains multiple record batches.

Both write_table and write_batch take an optional row_group_size which you can use to slice a large continuous in-memory object into pieces as you write it.  Arrow's record batch is roughly analogous to parquet's "row group".  Arrow's table is roughly analogous to an entire parquet file.

> I would like to split the data and write to the same parquet file to save memory, should I use "write_table" or "write_batch" ?
Also, what would be the best size after splitting?

I'm not really sure what you mean by this.  Are you trying to write the data so it can be read back out a piece at a time?

**Comment by kato1208** [comment]
Thank you for your ansewer.
I understood that in our case it is better to use record batch.

> I'm not really sure what you mean by this. Are you trying to write the data so it can be read back out a piece at a time?

I'm working on a parquet conversion of huge protobuf data using pyarrow.
We don't want to read the protobuf data all at once and store it in memory, so we want to read it little by little and convert it to parquet.
For example:
```
records = []
for record in protobuf_obj.read():
    records.append(record)
    if sys.getsizeof(records) > threshhold:
        batch = pa.RecordBatch.from_pylist(records, schema=schema)
        writer.write_batch(batch)
        records = []
```
I don't know how to determine this threshhold.
Or is this approach not appropriate?

**Comment by westonpace** [comment]
That model should be appropriate.  A general rule of thumb for `threshold` would be ~1 million rows but it can depend on a lot of things.  It's best to fiddle with later though once you've got enough data to run experiments and fine-tune.

**Comment by westonpace** [comment]
Actually, I thought threshold was a number of rows.  Since it is a number of bytes I'd maybe shoot for ~200 MiB.

**Comment by kato1208** [comment]
Are there any concerns about reducing the threshold such as ~20mb?
I want to save memory as much as possible.

**Comment by westonpace** [comment]
There would be two potential concerns at that point.

 1. Parquet has to store metadata for each row group.  This metadata has to be read and parsed.  If your row groups are too small you will have poor reading performance because a lot of time is spent handling metadata.
 2. It can depend on how many columns you have and if those columns are compressed but individual columns might start to get really small (e.g. 1mb) and you will end up having to issue a lot of non-contiguous reads to the disk.  If your disk is a "spinning disk" (e.g. HDD) then this can hurt your I/O bandwidth.

**Comment by westonpace** [comment]
Both of these just mean your performance will suffer.  If that is not a concern then you can go ahead and store the groups that small.

**Comment by kato1208** [comment]
I understand that it affects query perfomance.
Thank you for your prompt reply!!
I closed this issue.

**Comment by kato1208** [comment]
Are there any performance benchmarks by row group size?
I load the parquet files into Redshift and analyze them from Tableau.
I would like to know how much performance impact there is on Redshift query.

**Comment by pitrou** [comment]
> Are there any performance benchmarks by row group size?

Not really, because this depends entirely on the actual data and schema, and also on the machine that you're doing the reading from. Reasonable advice is to write micro-benchmarks with our actual (or simulated) data and decide what's best for you.

**Comment by pitrou** [comment]
Closing again, since the original issue has been answered.
