### ISSUE TITLE
Compute total number files written by write_table based on row_group_size

### ISSUE THREAD

**Issue by jaidisido** [apache/arrow#13197]
This is a question more than an issue so my understanding is that it's ok to open here rather than JIRA.

I am using the parquet [write_table](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html) method to write parquet objects to an S3 bucket.

I wish to know if there is a way to obtain the **number of files** that will be written in advance. I don't need the actual file names, just the total number of files written as a result of that api call. I know that the number is determined by the `row_group_size` parameter in the call, but cannot figure out how to convert that figure into a number of files written.

Cheers

**Comment by AlenkaF** [comment]
I can be mistaken but as far as I understand `pq.write_table` produces a single parquet file with multiple row groups if `row_group_size` is specified. You can calculate the number of row groups by `table.num_rows/row_group_size`.

To write in multiple parquet files you can use [`pq.write_to_dataset`](https://arrow.apache.org/docs/python/parquet.html#writing-to-partitioned-datasets). In this case the number of files will be defined by partitioning columns and their unique values.
