### ISSUE TITLE
[R] Can't binary install arrow 8.0.0 from RStudio Public Package Maneger

### ISSUE THREAD

**Issue by eitsupi** [apache/arrow#13211]
When we try to install arrow from `https://packagemanager.rstudio.com/cran/__linux__/focal/latest` on Ubuntu 20.04, it seems to perform a source install.
Since the other packages are binary installs, it is possible that there is something wrong with the arrow build on RSPM.
However, I did not know where to report it properly...

**Comment by eitsupi** [comment]
It appears that binary installation is possible with bionic.

https://packagemanager.rstudio.com/__api__/repos/1/binaries?distribution=focal&r_version=4.2&packages=arrow
https://packagemanager.rstudio.com/__api__/repos/1/binaries?distribution=bionic&r_version=4.2&packages=arrow

**Comment by nealrichardson** [comment]
@glin FYI, is this known? Let me know if I can help debug anything.

**Comment by glin** [comment]
@nealrichardson Looking into this now - I think the arrow 8.0.0 builds for Ubuntu 20 and 22 are timing out in our build system. We added a 1 hour timeout recently to deal with hanging builds for unrelated packages, and that's apparently too short. We'll try bumping the timeout and rebuilding arrow.

@eitsupi For future reference, you can also report any issues with the Public Package Manager site at RStudio Community under the `package-manager` tag: https://community.rstudio.com/c/r-admin/package-manager/21?tags=package-manager. We monitor that forum and usually respond pretty quickly. It's also linked under the "How to get help" section on the home page of https://packagemanager.rstudio.com if you ever need to find the link again.

**Comment by nealrichardson** [comment]
@glin you could try setting `LIBARROW_BINARY=true` in your build env, that will download a C++ binary we pre-build. Should speed things up significantly. https://arrow.apache.org/docs/r/articles/install.html#r-package-configuration

**Comment by glin** [comment]
arrow 8.0.0 binaries should now be available for both focal and jammy, and thanks for reporting this.

@nealrichardson Ooh, good to know about `LIBARROW_BINARY`, we might add that to our builds. For now, there don't seem to be prebuilt C++ libs for Ubuntu 22 yet, so we I think we would've needed to fix the build timeout anyway.

**Comment by nealrichardson** [comment]
> arrow 8.0.0 binaries should now be available for both focal and jammy, and thanks for reporting this.
> 
> 
> 
> @nealrichardson Ooh, good to know about `LIBARROW_BINARY`, we might add that to our builds. For now, there don't seem to be prebuilt C++ libs for Ubuntu 22 yet, so we I think we would've needed to fix the build timeout anyway.

There aren't, but the libraries built for ubuntu-18.04 should get pulled in and work for 22.04 (and if they don't, we'll add them)

**Comment by nealrichardson** [comment]
Done in https://github.com/ursa-labs/arrow-r-nightly/commit/bda16283a911d680c5a0481c39cebeb4379dc57d

**Comment by assignUser** [comment]
@glin If you had issues building arrow on ubuntu 22.04 even after the distro-map fix that problem should be solved now: https://issues.apache.org/jira/browse/ARROW-16678

**Comment by eitsupi** [comment]
> you could try setting `LIBARROW_BINARY=true` in your build env, that will download a C++ binary we pre-build. Should speed things up significantly. [arrow.apache.org/docs/r/articles/install.html#r-package-configuration](https://arrow.apache.org/docs/r/articles/install.html#r-package-configuration)

I am wondering if this setting is only available on amd64?
Since it appears to install the same binary on arm64, and in fact the build seems to fail on arm64.

**Comment by nealrichardson** [comment]
Good call, I've added that to ARROW-16752
