### ISSUE TITLE
[pyarrow] All code snippets crashed in the documentation

### ISSUE THREAD

**Issue by o3661606** [apache/arrow#1324]
All code snippets in the document cannot be shown, showing the below error instead:  
> ImportError: libarrow.so.0: cannot open shared object file: No such file or directory
 
Example: https://arrow.apache.org/docs/python/memory.html

**Comment by wesm** [comment]
Thanks. Looks like something went wrong when building the docs. One of us can fix

**Comment by xhochy** [comment]
I've recently updated the docs with the docker image, probably there is a problem in there with the `LD_LIBRARY_PATH`. I can investigate later

**Comment by wesm** [comment]
I created https://issues.apache.org/jira/browse/ARROW-1831

**Comment by xhochy** [comment]
Pushed fixed docs, should propagate in the next hours through the ASF's infrastructure.
