### ISSUE TITLE
First-class functions in substrait

### ISSUE THREAD

**Issue by donghekang** [apache/arrow#13268]
Hi all,

I am trying to execute an example Substrait plan in Arrow. The example plan is shown as the following. We define a filter operator to compare an attribute with one constant value 1. The operator uses the `gt` function defined in https://github.com/substrait-io/substrait/blob/main/extensions/functions_comparison.yaml. 

However, it looks like Arrow does not implement the first-class functions defined in Substrait. Arrow reports **Uri 'https://github.com/substrait-io/substrait/blob/main/extensions/functions_comparison.yaml' not found in registry** when I execute the plan. I use the Arrow release-8.0.0.

I am curious how to describe the `gt` funciton in the Substrait message that can be consumed by Arrow. Thanks in advance!

> {
>  "extensionUris": [
>   {
>    "extensionUriAnchor": 7,
>    "uri": "https://github.com/substrait-io/substrait/blob/main/extensions/functions_comparison.yaml"
>   }
>  ],
>  "extensions": [
>   {
>    "extensionFunction": {
>     "extensionUriReference": 7,
>     "functionAnchor": 42,
>     "name": "gt"
>    }
>   }
>  ],
>  "relations": [
>   {
>    "rel": {
>     "filter": {
>      "input": {
>       "read": {
>        "baseSchema": {
>         "names": [
>          "i",
>          "b"
>         ],
>         "struct": {
>          "types": [
>           {
>            "i64": {}
>           },
>           {
>            "bool": {}
>           }
>          ]
>         }
>        },
>        "localFiles": {
>         "items": [
>          {
>           "uriFile": "file:///home/daniel/20220512-arrow-substrait-example/example.parquet",
>           "format": "FILE_FORMAT_PARQUET"
>          }
>         ]
>        }
>       }
>      },
>      "condition": {
>       "scalarFunction": {
>        "functionReference": 42,
>        "args": [
>         {
>          "selection": {
>           "directReference": {
>            "structField": {}
>           },
>           "rootReference": {}
>          }
>         },
>         {
>          "literal": {
>           "i64": "1"
>          }
>         }
>        ],
>        "outputType": {
>         "bool": {
>          "nullability": "NULLABILITY_REQUIRED"
>         }
>        }
>       }
>      }
>     }
>    }
>   }
>  ]
> }

**Comment by westonpace** [comment]
Mapping of functions is not yet fully implemented.  There is some discussion on approach in [ARROW-15582](https://issues.apache.org/jira/browse/ARROW-15582) and [ARROW-15538](https://issues.apache.org/jira/browse/ARROW-15538) and these JIRAs are in progress (though no PR is yet available)
