### ISSUE TITLE
Best practices to use Arrow Flight Server

### ISSUE THREAD

**Issue by marsupialtail** [apache/arrow#13300]
I am trying to use the Arrow Flight Server (in Python) with multiple clients.

I have the Arrow Flight Server on one machine and multiple clients that could be on the same machine and different machines talking to it, and invoking methods such as list_flights and do_put, do_get. 

I notice that the list_flights method sometimes hangs on the client. (It returns an iterator, but trying to iterate on this iterator )

Can someone comment on the concurrency behaviors of the Arrow Flight Server? Is it a single threaded event loop implementation or does it use threading under the scenes?

**Comment by lidavidm** [comment]
It uses gRPC/C++ underneath which is based around event loop(s) serviced by multiple threads. 

Are you able to provide the server or client code? Note that list_flights is currently implemented synchronously in Python and will not return until all results are fetched, so it's not suitable for very large/streaming/infinite result streams.

**Comment by marsupialtail** [comment]
What happens when new things are added to self.flights when you are listing flights?

**Comment by marsupialtail** [comment]
Making a self contained example might be difficult. The code is in here: https://github.com/marsupialtail/quokka/tree/replace-redis. High level: I have a distributed actor system which pushes around Arrow tables. I initialize a FlightServer on each machine. Other actors might push data to servers on remote machines and fetch data from servers on local machine (which have been pushed remotely). There can be many such actors.

You can look at how I use the FlightServer in https://github.com/marsupialtail/quokka/blob/replace-redis/pyquokka/quokka_runtime.py#L420 and https://github.com/marsupialtail/quokka/blob/replace-redis/pyquokka/flight.py.
How I use the FlightClient is here: https://github.com/marsupialtail/quokka/blob/replace-redis/pyquokka/nodes.py#L604. Each actor constantly calls the get_batches function to try to get its latest batches in the local FlightServer.

The behavior is that for some actors this work fine but for others it hangs. In particular the observed behavior is that it gets stuck in the iterator. As in the actor seems to hang in the loop here: https://github.com/marsupialtail/quokka/blob/replace-redis/pyquokka/nodes.py#L604. I'm sorry if this is too much information -- I can try to produce a minimally reproducible example, but that might be kind of difficult. 

If you are interested in helping, you can also contact me directly at zihengw@stanford.edu or on the Substrait Slack.

**Comment by lidavidm** [comment]
Hmm, interesting. Do you happen to have a stack trace from when an actor hangs? That'll help narrow down what could be happening. 

Does it occur in a small setup/on localhost, or only with a truly distributed system? I can try and run the project if I can find some time.

You can also try running with gRPC debug flags to see what happens with the call - `env GRPC_VERBOSITY=info GRPC_TRACE=http` should do the trick; it'll print when headers arrive, when the call ends, etc. which can help narrow it down as well.

**Comment by marsupialtail** [comment]
Yeah unfortunately I don't have a stack trace. I will try running with debug flags.

Perhaps I am doing something flagrantly wrong in my server code: https://github.com/marsupialtail/quokka/blob/replace-redis/pyquokka/flight.py? I tried to place locks on the self.flights object which did not really receive the issue.

**Comment by lidavidm** [comment]
No, nothing seems to jump out at me there either.

**Comment by marsupialtail** [comment]
I think I got a stack trace:
    task_graph.run()
  File "/home/ziheng/quokka-dev/pyquokka/quokka_runtime.py", line 440, in run
    finished, unfinished = ray.wait(unfinished, timeout = 1)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/api.py", line 62, in wait
    return self.worker.wait(*args, **kwargs)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/worker.py", line 530, in wait
    resp = self._call_stub("WaitObject", req, metadata=self.metadata)
  File "/home/ziheng/.local/lib/python3.8/site-packages/ray/util/client/worker.py", line 298, in _call_stub
    return getattr(self.server, stub_name)(*args, **kwargs)
  File "/home/ziheng/.local/lib/python3.8/site-packages/grpc/_channel.py", line 944, in __call__
    state, call, = self._blocking(request, timeout, metadata, credentials,
  File "/home/ziheng/.local/lib/python3.8/site-packages/grpc/_channel.py", line 933, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 338, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 169, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 163, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 63, in grpc._cython.cygrpc._latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next

**Comment by marsupialtail** [comment]
Yeah I guess both Ray and Flight use gRPC and I should try to make sure they are the same version...
What do you mean by there is a gRPC "embedded into Flight"?

**Comment by lidavidm** [comment]
I suppose it's actually backwards. Flight uses gRPC, but:

`import pyarrow.flight` -> loads `libarrow_flight.so` -> loads `libgrpc++.so` -> loads `libgrpc.so`
but `import grpcio` -> loads `_cygrpc.so` -> this **statically** links gRPC

and so you have two versions of gRPC in the same process.

The key problem is that short of modifying the build scripts and building your own package, you cannot get grpcio to dynamically link to gRPC (last I checked).

**Comment by lidavidm** [comment]
So even if you make sure they are the same version, you can still run into issues.

**Comment by marsupialtail** [comment]
Yes. The solution, is to run the Arrow Flight Server in its own process apart from Ray to avoid this issue. 

Once I started doing that I haven't seen it fail yet.

**Comment by marsupialtail** [comment]
I think the Ray people might be interested in hearing about this interplay, I will link this issue on their side as well.

**Comment by lidavidm** [comment]
That happened in a proprietary system and it's been a few years, but yeah - the basics are as I've described above:

- Flight links a copy of gRPC
- grpcio statically links a copy of gRPC
- gRPC maintains global state

and hence, when you combine Flight and grpcio, you run the risk of these two copies of gRPC trampling on each other.
