### ISSUE TITLE
How to get c_glib debug compiled lib (can debug with src code)

### ISSUE THREAD

**Issue by chenbaggio** [apache/arrow#13349]
STOP! Are you reporting a bug, a possible bug, or requesting a
feature? If so, please report under the ARROW project on the ASF JIRA
server https://issues.apache.org/jira/browse/ARROW. This JIRA server
is free to use and open to the public, but you must create an account
if it is your first time.

See our contribution guidelines for more information:
http://arrow.apache.org/docs/developers/contributing.html

We have GitHub issues available as a way for new contributors and
passers-by who are unfamiliar with Apache Software Foundation projects
to ask questions and interact with the project. Do not be surprised if
the first response is to open a JIRA issue or to write an e-mail to
one of the public mailing lists:

* Development discussions: dev@arrow.apache.org (first subscribe by
  sending an e-mail to dev-subscribe@arrow.apache.org).
* User discussions: user@arrow.apache.org (first subscribe by
  sending an e-mail to user-subscribe@arrow.apache.org).

Thank you!

**Comment by chenbaggio** [comment]
I have tried many ways ,but them all do not work
include set meson buildtype c_args etc.

**Comment by kou** [comment]
`meson setup` uses debug build by default.
Could you show your command lines to build Apache Arrow GLib?

**Comment by chenbaggio** [comment]
I use canon python script to build

```
import os

from conans import ConanFile, CMake, tools, AutoToolsBuildEnvironment, Meson

dependencies = [
    "orc/1.7.0@hashdata/testing"
]


class GopherConan(ConanFile):
    name = "arrow"
    license = "Apache License Version 2"
    url = "https://code.hashdata.xyz/hashdata/Gopher"
    description = "A Vector Computing System"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake", "pkg_config"
    exports_sources = ["../*", "!.git/*", "!.ci/*", "!.gitlab-ci.yml", "!build/*", "!binary/*", "!vagrant/*",
                       "!.idea/*", "!cmake-build*/*"]
    revision_mode = "scm"

    def set_version(self):
        self.version = "2.0.0"

    def requirements(self):
        for dependency in dependencies:
            self.requires(dependency)

    def imports(self):
        self.copy("*.so", dst="thirdparty", src="lib")

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_folder="cpp", defs={
            "CONAN_DISABLE_CHECK_COMPILER": "ON",
            "ARROW_BUILD_STATIC": "OFF",
            "ARROW_PYTHON": "ON",
            "ARROW_GANDIVA": "ON",
            "ARROW_COMPUTE": "ON",
            "ARROW_CSV": "ON",
            "ARROW_PARQUET": "ON",
            "ARROW_DATASET": "ON",
            "ARROW_FILESYSTEM": "ON",
            "ARROW_BUILD_UTILITIES": "ON",
            "ARROW_JSON": "ON",
            "ARROW_ORC": "ON",
            "CMAKE_BUILD_TYPE": "debug"
        })
        cmake.build()
        cmake.install()

        with tools.environment_append(
                {
                    "LD_LIBRARY_PATH": [os.path.join(self.build_folder, "thirdparty")]
                }):
            meson = Meson(self)
            meson.configure(source_folder=os.path.join(self.source_folder, "c_glib"),
                pkg_config_paths=[os.path.join(self.package_folder, "lib/pkgconfig")]
                )
            meson.build()
            meson.install()

    def package(self):
        pass

    def package_info(self):
        self.cpp_info.includedirs = ['include']
        self.cpp_info.libdirs = ['lib']
        self.cpp_info.bindirs = ['bin']

```
but it always show buildtype is release, I have to add the line

```
os.system("meson /code/c_glib -Dcpp_args=\"-g -O0\" -Dcpp_std=\"c++11\" -Dc_args=\"-g -O0\" auto_features=disabled --optimization=g --buildtype=debug --debug  --reconfigure")

```
the buildtype can change into debug, but ninja call gcc,  the optimmizer argument is O3

**Comment by kou** [comment]
How about specifying `build_type='debug'` explicitly?

```python
meson = Meson(self, build_type='debug')
```

See also: https://docs.conan.io/en/latest/reference/build_helpers/meson.html#constructor
