### ISSUE TITLE
pyarrow parquet and datasets with metadata files

### ISSUE THREAD

**Issue by trent** [apache/arrow#1336]
pyarrow==0.7.1

I am working with a parquet dataset that has `_metadata` and `_common_metadata` files in the root directory as such:

```
data/
├── _common_metadata
├── _metadata
└── symbol=ABC
    ├── date=2017-10-30
    │   └── part.0.parquet
    └── date=2017-10-31
        └── part.0.parquet
```

and get the follow error trying to load this data via pyarrow:

```
ValueErrorTraceback (most recent call last)
<ipython-input-92-8b770500bffe> in <module>()
----> 1 dataset = pq.ParquetDataset('path/to/data/')
      2 table = d_dataset.read()

.../lib/python2.7/site-packages/pyarrow/parquet.pyc in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema)
    619 
    620         (self.pieces, self.partitions,
--> 621          self.metadata_path) = _make_manifest(path_or_paths, self.fs)
    622 
    623         if self.metadata_path is not None:

.../lib/python2.7/site-packages/pyarrow/parquet.pyc in _make_manifest(path_or_paths, fs, pathsep)
    763     if is_string(path_or_paths) and fs.isdir(path_or_paths):
    764         manifest = ParquetManifest(path_or_paths, filesystem=fs,
--> 765                                    pathsep=fs.pathsep)
    766         metadata_path = manifest.metadata_path
    767         pieces = manifest.pieces

.../lib/python2.7/site-packages/pyarrow/parquet.pyc in __init__(self, dirpath, filesystem, pathsep, partition_scheme)
    503         self.metadata_path = None
    504 
--> 505         self._visit_level(0, self.dirpath, [])
    506 
    507     def _visit_level(self, level, base_path, part_keys):

.../lib/python2.7/site-packages/pyarrow/parquet.pyc in _visit_level(self, level, base_path, part_keys)
    532         if len(files) > 0 and len(filtered_directories) > 0:
    533             raise ValueError('Found files in an intermediate '
--> 534                              'directory: {0}'.format(base_path))
    535         elif len(filtered_directories) > 0:
    536             self._visit_directories(level, filtered_directories, part_keys)

ValueError: Found files in an intermediate directory: path/to/data/
```

There appears to be some support for handling `_metadata` and `_common_metadata` files ([here](https://github.com/apache/arrow/blob/0e21f84c2fc26dba949a03ee7d7ebfade0a65b81/python/pyarrow/parquet.py#L517-L520)) while traversing the dataset directory structure , but it doesn't filter those files or consider them after traversing the tree and raise the exception [here](https://github.com/apache/arrow/blob/0e21f84c2fc26dba949a03ee7d7ebfade0a65b81/python/pyarrow/parquet.py#L532-L534).

Does (or rather "Should") pyarrow support datasets with this structure?

**Comment by wesm** [comment]
I think this was just fixed in https://github.com/apache/arrow/commit/eb7be48ef80fcecea11be29320b244df82f1cc06 but we should make sure

**Comment by trent** [comment]
Great! Happy to test, but I'm having issues building from source on RHEL. Do you release built conda or pip nightlies so I can just install the latest?

**Comment by wesm** [comment]
Yes, install the nightlies from https://anaconda.org/twosigma/pyarrow

**Comment by wesm** [comment]
`conda install pyarrow -c twosigma`

**Comment by trent** [comment]
I installed from twosigma and I get the following `ImportError`:

```
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/site-packages/pyarrow/__init__.py", line 32, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: lib/python2.7/site-packages/pyarrow/lib.so: undefined symbol: _ZTVN5arrow14Decimal128TypeE
```

**Comment by wesm** [comment]
Bad timing perhaps with some recent patches we've been merging, we will look into. cc @cpcloud

**Comment by trent** [comment]
@cpcloud and @wesm any update on this?  I am currently getting the error:

```
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/site-packages/pyarrow/__init__.py", line 32, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: lib/python2.7/site-packages/pyarrow/lib.so: undefined symbol: _ZTVN5arrow2io8WritableE
```

**Comment by wesm** [comment]
The nightlies are broken right now due to ARROW-1881. We should try to resolve this today

**Comment by wesm** [comment]
A fix for ARROW-1881, I would update the nightly build tomorrow and this error should hopefully go away

**Comment by wesm** [comment]
Closing. The nightly builds are not supported but we can try to help if you keep running into issues

**Comment by MosheVai** [comment]
@wesm I seem to run into the exact same problem is it fixed?

**Comment by wesm** [comment]
If you're hitting it with 1.0.0 please open a JIRA issue
