### ISSUE TITLE
R installation and Brotli error code

### ISSUE THREAD

**Issue by michaelccata** [apache/arrow#13372]
Hello, not sure if this the right place to post this question. I'm very much a noob here.

I'm not sure if it's operator error here or an actual bug.

I'm simply trying to install `arrow` to read a parquet file into `R` and following this [guide](https://arrow.apache.org/docs/r/articles/install.html). I think I'm following the right steps, but still getting an error.

<img width="757" alt="Screen Shot 2022-06-12 at 9 26 21 PM" src="https://user-images.githubusercontent.com/4422873/173264333-e7f2a5c6-7d46-4afb-9a0a-f28a9e6827e8.png">

**Comment by wjones127** [comment]
Unfortunately, those instructions are primarily aimed at Linux users. `install.packages()` for MacOS installs pre-compiled binaries, which looks like they don't include Brotli.

In theory, you should be able to run this instead:

```
arrow::install_arrow(minimal=FALSE)
```

(Though I found this doesn't work on my machine.)

**Comment by nealrichardson** [comment]
If that doesn't work, try setting the env vars `FORCE_BUNDLED_BUILD=true LIBARROW_MINIMAL=false` and then run `install.packages("arrow", type = "source")`. It looks like `arrow::install_arrow()` will set those for you if you're on a M1 mac but not on an Intel mac. 

Side note: we should turn on brotli and any other missing compression libs in the mac binaries.

**Comment by wjones127** [comment]
> Side note: we should turn on brotli and any other missing compression libs in the mac binaries.

Issue created: https://issues.apache.org/jira/browse/ARROW-16828

**Comment by michaelccata** [comment]
Maybe it's something with my local system and/or permissions to write in these directories?

**Comment by nealrichardson** [comment]
I don't think that's it, you should be able to write to /tmp. Something didn't go as expected with fetching `cmake`. If you have `brew` installed, you can `brew install cmake` and then retry and it will skip the step that failed.

**Comment by michaelccata** [comment]
@nealrichardson bingo, I'm on a new machine and hadn't downloaded XCode or Brew yet. I installed `brew` and pulled down `cmake` and then everything clicked. 

Thank so much for helping me troubleshoot this!

**Comment by edponce** [comment]
@nealrichardson This issue seems resolved so we should close it.
