### ISSUE TITLE
Is the Arrow::Table.merge function in a working state?

### ISSUE THREAD

**Issue by arjunsr1** [apache/arrow#13396]
I'm trying to use the merge function in table.rb (Line 358) and it's not giving me the functionality I am expecting. From what I interpreted, the function should take the table that is passed in as a parameter, and append the rows to the original table. However, I tried to use this function where the table that is calling the function had 53 rows, and the parameter table had 1 row, and the resulting table had only 1 row instead of what I assumed should be 54 rows. I also noticed the TODO comment above the method.

Is this function a work in progress?

**Comment by kou** [comment]
It's for merging "columns" not "rows".
You can use `Arrow::Table#concatenate(table1, ...)` for appending rows.

**Comment by arjunsr1** [comment]
I tried to do something like this:

`consolidated_table = Arrow::Table.concatenate(s3_existing_table, table)` and I got an error as follows:

`Caused by NoMethodError: undefined method `concatenate' for Arrow::Table:Class`

**Comment by arjunsr1** [comment]
I'm getting this error now:  `Caused by TypeError: no implicit conversion of Arrow::Table into Array`

**Comment by kou** [comment]
Ah, sorry. Could you try `s3_existing_table.concatenate([table])`?

**Comment by arjunsr1** [comment]
Hi @kou - it seems like `s3_existing_table.concatenate([table])` should work fine. However, I'm getting an error that says `Invalid schema at index 1 was different`. The steps I'm taking are as follows:

- Construct a table based on a CSV file (variable is called tempfile) using `table = Arrow::Table.load(tempfile.path)`
- Pull a parquet file from S3 into a temporary file location (A parquet file that was generated by previously calling `Arrow::Table.save()` on an arrow table of the same type).
- Call `s3_existing_table = Arrow::Table.load(_temporary_file_path_)`
- Finally, try to merge tables by doing `consolidated_table = s3_existing_table.concatenate([table])`

The only schema changes I can verify via diffchecker are as follows
`
History Completed Time: timestamp[ms]
History Created Time: timestamp[ms]
vs
History Completed Time: timestamp[s]
History Created Time: timestamp[s]
`
(Rest of the schema ommitted since there are no changes in the rest)
Apologies if this goes beyond the scope of what you know, but do you think there could be some schema change issue that occurs when saving arrow tables as parquet files?

**Comment by arjunsr1** [comment]
Hi @kou - through using my debugger and stepping through code, it seems that when I save an arrow table with schema fields
```
History Completed Time: timestamp[s]
History Created Time: timestamp[s]
```
to a tempfile, then use arrow::Table.load() to get the file data into an Arrow table, the type changes from s to ms. Is there any quick workaround to this issue?

**Comment by kou** [comment]
Apache Parquet doesn't support "seconds" as unit: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#timestamp
So "seconds" timestamp type is converted to "milliseconds" timestamp type when we write Apache Arrow data as Apache Parquet.

We can cast type by the following:

```ruby
s3_existing_table.merge(
  "History Completed Time" => Arrow::ChunkedArray.new(s3_existing_table["History Completed Time"].data.chunks.collect {|chunk| chunk.cast(Arrow::TimestampDataType.new(:second))},
  "History Created Time" => Arrow::ChunkedArray.new(s3_existing_table["History Created Time"].data.chunks.collect {|chunk| chunk.cast(Arrow::TimestampDataType.new(:second))}
)
```

But this it too inconvenient... I'll add convenient APIs to write something like the following:

```ruby
s3_existing_table.merge(
  "History Completed Time" => s3_existing_table["History Completed Time"].cast(unit: :second)),
  "History Created Time" => s3_existing_table["History Created Time"].cast(unit: :second)),
)
```

**Comment by kou** [comment]
With https://github.com/apache/arrow/pull/13418, we can write it as:

```ruby
s3_existing_table.merge(
  "History Completed Time" => s3_existing_table["History Completed Time"].cast({type: :timestamp, unit: :second}),
  "History Created Time" => s3_existing_table["History Created Time"].cast({type: :timestamp, unit: :second}),
)
```

**Comment by arjunsr1** [comment]
@kou - thanks so much for getting back to me and introducing this functionality. This will help a lot for our application! Is there a new gem version now that I must update? Has this change gone live?

**Comment by arjunsr1** [comment]
Hello @kou - revisiting the same problem, I now noticed that
