### ISSUE TITLE
There is no test case using the `2.0.0-compression` test file

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow#13391]
In the  issue: https://issues.apache.org/jira/browse/ARROW-8670
Java and c++ have implemented the compression for IPC format, but there is no test to read and write https://github.com/apache/arrow-testing/tree/master/data/arrow-ipc-stream/integration/2.0.0-compression files to verify the implemention.

**Comment by lidavidm** [comment]
They're tested by the integration suite, e.g. see the output of this run: https://github.com/apache/arrow/runs/6927219399?check_suite_focus=true#step:7:11104

**Comment by liukun4515** [comment]
> They're tested by the integration suite, e.g. see the output of this run: https://github.com/apache/arrow/runs/6927219399?check_suite_focus=true#step:7:11104

thank you and I will check them.

**Comment by lidavidm** [comment]
Given the Rust PR did you figure this out?

**Comment by liukun4515** [comment]
> Given the Rust PR did you figure this out?

I think we can close this issue, I figure out this.
