### ISSUE TITLE
Update Plasma Buffer failed

### ISSUE THREAD

**Issue by g302ge** [apache/arrow#13424]
When I have updated the arrow::plasma project to support some features in our business. I got this error in make process.

![image](https://user-images.githubusercontent.com/17953717/175256522-2ba72fcc-a5a7-4a64-b4ac-107086c5f999.png)

And the generating command from .fbs files is:

```
flatc --cpp --cpp-std c++11 --gen-object-api --scoped-enums common.fbs plasma.fbs
```

my flatc compiler is at version 2.0.6

thx for reply best wishes

**Comment by edponce** [comment]
Hi @g302ge, although I am not an arrow::plasma user, I have several observations:
* The [`VerifyField` function](https://github.com/apache/arrow/blob/8e43f23dcc6a9e630516228f110c48b64d13cec6/cpp/thirdparty/flatbuffers/include/flatbuffers/flatbuffers.h#L2490) expects only 2 arguments and your error message is showing that it being invoked with 3 arguments. 
* Browsing the Arrow codebase, there is no invocation passing 3 arguments to this function, so I assume that your `plasma_generated.h` is not supported.
* Also, `arrow::plasma` updates are mostly +2 years old, so it may be the case that this component is not fully stable.

**Comment by pitrou** [comment]
> When I have updated the arrow::plasma project to support some features in our business.

Can you explain what this means exactly?

Also, regardless, Plasma is currently unmaintained and will probably be deprecated at some point...

**Comment by g302ge** [comment]
> > When I have updated the arrow::plasma project to support some features in our business.
> 
> Can you explain what this means exactly?
> 
> Also, regardless, Plasma is currently unmaintained and will probably be deprecated at some point...

Sure, we have design a new data application, whose bottleneck is File I/O (some FXXK history reason). So these day we are trying do some hot patch to reduce the IO using big main memory to cache them. In our design every column in file could be regard as an object in Plasma, but we have to introduce some new feature designed for our situation. For example we use the `SHA1(file_path)` + `FileInfo.mtime()` as version + `Column Index` as an ObjectID, since we expand the origin ObjectID into 32bit. 

Sounds really tricky, but recent days the only road to reduce the IO is to build a new Database to replace File I/Os . LOL
