### ISSUE TITLE
Building C++ for M1 Macs

### ISSUE THREAD

**Issue by jayhomn-bitquill** [apache/arrow#13422]
Does arrow currently support cross building for M1 Macs? (Intel -> M1). For more context, we are currently also using a package manager called vcpkg with the associated arm64-osx triplet

**Comment by wjones127** [comment]
I'm not 100% sure about Intel -> M1, but we do use M1 -> Intel in our Python packaging (which builds C++ with vcpkg for dependencies): https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/github.osx.arm64.yml

**Comment by kou** [comment]
It seems that we can build binaries for M1 Mac by specifying `-target arm64-apple-macos11` to `clang++`: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

CMake has a feature for cross compiling: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html

We'll be able to build binaries for M1 Mac on Intel Mac with them.

**Comment by pitrou** [comment]
(of course, given the relative performance of Intel and Arm Macs, you'd better better off building on Arm anyway!)

**Comment by kou** [comment]
Can we close this?
