### ISSUE TITLE
when use setBytes(), ArrowBuf.nioBuffer() is empty,but writeBytes(byte[]) can work.

### ISSUE THREAD

**Issue by lfygh** [apache/arrow#13431]
what is the diff ArrowBuf#writeBytes(byte[]) vs ArrowBuf#setBytes(long, byte[]), if i use setBytes(), ArrowBuf.nioBuffer() is empty,but writeBytes(byte[]) can work. this is a bug or i miss sth?

```java
    ArrowBuf buffer = allocator.buffer(20);
    byte[] bytes = "hello".getBytes(StandardCharsets.UTF_8);
    buffer.setBytes( 0, bytes);  // writeBytes can work
    streamListener.onNext(PutResult.metadata(buffer));
    ===================================
    // org.apache.arrow.flight.PutResult#toProtocol  
    Flight.PutResult toProtocol() {
    if (applicationMetadata == null) {
      return Flight.PutResult.getDefaultInstance();
    }
   //applicationMetadata.nioBuffer() is empty
    return Flight.PutResult.newBuilder().setAppMetadata(ByteString.copyFrom(applicationMetadata.nioBuffer())).build();
  }
```

**Comment by lidavidm** [comment]
setBytes doesn't update writerIndex, but writeBytes does, and the length of the nioBuffer is defined as `writerIndex - readerIndex`. So if you use setBytes, the length of the buffer is still 0. The docstring could be clarified, but this sounds like intentional behavior to me.
