### ISSUE TITLE
[Python] iloc equivalent for selection by position and setting values?

### ISSUE THREAD

**Issue by zacqed** [apache/arrow#13505]
iloc equivalent for selection by position and setting values?
```
import pyarrow as pa
import pandas as pd
df = pd.DataFrame({'year': [2020, 2022, 2019, 2021],
                   'n_legs': [2, 4, 5, 100],
                   'animals': ["Flamingo", "Horse", "Brittle stars", None]})
table = pa.Table.from_pandas(df)

```
`df.loc[df["animals"].isnull(), "animals"] = "new_value" # how do we perform this in pyarrow?`

**Comment by rok** [comment]
There is a [discussion](https://lists.apache.org/thread/c1von4oj8g0tb93mggov2sv04x56o80r) going on the mailing list.
