### ISSUE TITLE
How to create an empty record batch per given schema?

### ISSUE THREAD

**Issue by dudutudou** [apache/arrow#13559]
In c++ version, do we have an easy method to create a record batch which has zero rows per given schema?

Thanks.

**Comment by wjones127** [comment]
`RecordBatch::MakeEmpty()? https://github.com/apache/arrow/blob/d404c9c6a0d6ce94f054596e667205995ef944d2/cpp/src/arrow/record_batch.h#L71

**Comment by dudutudou** [comment]
@wjones127 Thanks!
