### ISSUE TITLE
read_csv_arrow() does not support ".csv.gz"

### ISSUE THREAD

**Issue by PursuitOfDataScience** [apache/arrow#13695]
Hi, 

I tried to read some ".csv.gz" files by using `read_csv_arrow()` and it gave me such an error message "Error in url(file, open = "rb") : URL scheme unsupported by this method." However, I've never had such an issue by using `readr::read_csv()`. I am not sure if this is a bug or a feature that can be requested for the future releases. 

Thanks!

**Comment by nealrichardson** [comment]
This is probably [ARROW-16619](https://issues.apache.org/jira/browse/ARROW-16619); #13625 should resolve this and a few related issues.
