### ISSUE TITLE
[Python][Flight] pyarrow.flight.FlightServerBase use threading instead of multiprocessing?

### ISSUE THREAD

**Issue by tianjiqx** [apache/arrow#13745]
I tried to use arrow flight, but when testing the performance (`do_exchange`), I found that the cpu usage can only be around 100%, maybe it is the GIL problem of python multi-threading.

I didn't find anything about setting the thread pool for `FlightServerBase`, so it seems that if you want to improve performance, it seems that you can only use `multiprocessing.Pool` internally to handle the internal working logic.

Do you have any other suggestions? Thanks!

**Comment by tianjiqx** [comment]
I've searched for similar questions and maybe learned something, but anyone with more suggestions is welcome.
- [[Python] [Flight] How does concurrency in Arrow Flight work? Where in the source code can I find it?](https://www.mail-archive.com/search?l=user@arrow.apache.org&q=subject:%22Re%5C%3A+%5C%5BPython%5C%5D+%5C%5BFlight%5C%5D+How+does+concurrency+in+Arrow+Flight+work%5C%3F+Where+in+the+source+code+can+I+find+it%5C%3F%22&o=newest)
- #13300

**Comment by lidavidm** [comment]
Yes, if you have heavy internal processing, your only real choice is to use multiprocessing. Depending on what you want to do, you could also set the `SO_REUSEPORT` gRPC option and spawn many processes listening to the same port. 

There's no option to set the thread pool because 1) it's provided by gRPC and 2) it wouldn't help anyways, you're still limited by the GIL.

**Comment by tianjiqx** [comment]
@lidavidm  thank you for your reply. My program still have some IO. Considering the copy cost of multi-process communication, it may be better to start more FlightServer.

**Comment by lidavidm** [comment]
Yeah, it does make it hard to build a CPU-intensive service in Python.

Maybe the SO_REUSEPORT option can be an Arrow Cookbook recipe - is that a good solution here?

**Comment by tianjiqx** [comment]
Probably didn't understand how to use SO_REUSEPORT. Sometimes it is possible to bind to the same port, but the created clients always only connect to the same server.

```
@contextlib.contextmanager
def _init_grpc_port(grpc_port):
    """Initialize grpc port for multiprocessing."""
    # Reference code.
    # https://github.com/grpc/grpc/issues/17659

    socket = py_socket.socket(py_socket.AF_INET6, py_socket.SOCK_STREAM)
    # in fact, py_socket.SOL_SOCKET = 65535
    # print(py_socket.SOL_SOCKET)

    socket.setsockopt(py_socket.SOL_SOCKET, py_socket.SO_REUSEADDR, 1)
    if socket.getsockopt(py_socket.SOL_SOCKET, py_socket.SO_REUSEADDR) == 0:
        raise RuntimeError("Failed to set SO_REUSEADDR.")
    socket.setsockopt(py_socket.SOL_SOCKET, py_socket.SO_REUSEPORT, 1)
    if socket.getsockopt(py_socket.SOL_SOCKET, py_socket.SO_REUSEPORT) == 0:
        raise RuntimeError("Failed to set SO_REUSEPORT.")
    socket.bind(('', grpc_port))
    try:
        yield socket.getsockname()[1]
    finally:
        socket.close()

def main():
    with _init_grpc_port(5005) as port:
        pass

    for i in range(2):
        p = Process(target=server.start, args=(i, ))
        # if set time.sleep(1) then always throw "os_error":"Address already in use","syscall":"bind"
        p.start()
```

**Comment by lidavidm** [comment]
The option has to be passed through gRPC (the code above effectively does nothing). See [`generic_options`](https://arrow.apache.org/docs/python/generated/pyarrow.flight.FlightClient.html#pyarrow.flight.FlightClient) and the [gRPC documentation](https://grpc.github.io/grpc/python/glossary.html#term-channel_arguments)

I'll see about adding a code snippet in the cookbook
