### ISSUE TITLE
why pyarrow ipc so slow?

### ISSUE THREAD

**Issue by qiuyang163** [apache/arrow#13787]
I want to send a numpy from one process to another process,then I use python function
```
import numpy as np
import time
import ctypes

from multiprocessing import sharedctypes

data = np.ones([1, 1, 544, 192], dtype=np.float32)

capacity = 1000 * 1 * 544 * 192 * 10

buffer = sharedctypes.RawArray(ctypes.c_uint8, capacity + 1)
ndarray = np.ndarray((capacity,), dtype=np.uint8, buffer=buffer)

cur_offset = 0

t = time.time()
for i in range(1000):
    data = np.frombuffer(data, dtype=np.uint8)
    data_size = data.shape[0]
    ndarray[cur_offset:data_size + cur_offset] = data
    cur_offset += data_size
e = time.time()

print(e - t)
```

get time cost 0.09337258338928223s

then I use pyarrow

```
import numpy as np
import pyarrow as pa
import time
import os

data = np.ones((1, 1, 544, 992), dtype=np.float32)

tensor = pa.Tensor.from_numpy(data)

path = os.path.join(str("./"), 'pyarrow-tensor-ipc-roundtrip')
mmap = pa.create_memory_map(path, 5000000 * 1000)

s = time.time()
for i in range(1000):
    result = pa.ipc.write_tensor(tensor, mmap)
e = time.time()

print(e - s)

output_stream = pa.BufferOutputStream()

s = time.time()
for i in range(1000):
    result = pa.ipc.write_tensor(tensor, output_stream)
e = time.time()

print(e - s)
```

and get results: 1.8259341716766357s 3.7164011001586914s

why pyarrow ipc is so slow?Does it use share memory to communicate between different processes?

**Comment by qiuyang163** [comment]
Is there any python ipc function faster than multiprocessing. sharedctypes? tks

**Comment by drin** [comment]
in np.frombuffer did you mean to use something other than data? either buffer or ndarray?

I'm trying to understand the code first

**Comment by qiuyang163** [comment]
> in np.frombuffer did you mean to use something other than data? either buffer or ndarray?
> 
> I'm trying to understand the code first

No,I just try to copy a nd.array to shared memory.And it is very fast.But when I use pyarrow to do the same thing,I find it slower than use multiprocessing. sharedctypes

**Comment by pitrou** [comment]
If you are creating a disk-backed memory map then the OS needs to write out the data at some point. What happens if you locate your memory mapped file inside a tmpfs such as `/dev/shm`?

**Comment by qiuyang163** [comment]
> If you are creating a disk-backed memory map then the OS needs to write out the data at some point. What happens if you locate your memory mapped file inside a tmpfs such as `/dev/shm`?

I don't want to map a file to memory, It will cause some data synchronize.
Does pyarrow support communication inter-process(IPC) without mapping a file?Just like multiprocessing. sharedctypes only use sharing memory to do it.

**Comment by pitrou** [comment]
> Does pyarrow support communication inter-process(IPC) without mapping a file?Just like multiprocessing. sharedctypes only use sharing memory to do it.

sharedctypes uses mmap over `/dev/shm`...

**Comment by pitrou** [comment]
Regardless, yes, you can write to shared memory using PyArrow:
```python
>>> buffer = sharedctypes.RawArray(ctypes.c_uint8, capacity + 1)
>>> tensor = pa.Tensor.from_numpy(data)
>>> out = pa.FixedSizeBufferWriter(pa.py_buffer(buf))
>>> pa.ipc.write_tensor(tensor, out)
418112
```

**Comment by qiuyang163** [comment]
> > Does pyarrow support communication inter-process(IPC) without mapping a file?Just like multiprocessing. sharedctypes only use sharing memory to do it.
> 
> sharedctypes uses mmap over `/dev/shm`... See https://github.com/python/cpython/blob/f79547a429d5c90af83a0da821e082cba20d4712/Lib/multiprocessing/heap.py#L67-L75

Oh,I understand, you mean I can use code below to finish it
```
path = os.path.join('/dev/shm')
mmap = pa.create_memory_map(path, 5000000 * 1000)
```

**Comment by qiuyang163** [comment]
> Regardless, yes, you can write to shared memory using PyArrow:
> 
> ```python
> >>> buffer = sharedctypes.RawArray(ctypes.c_uint8, capacity + 1)
> >>> tensor = pa.Tensor.from_numpy(data)
> >>> out = pa.FixedSizeBufferWriter(pa.py_buffer(buf))
> >>> pa.ipc.write_tensor(tensor, out)
> 418112
> ```

Tks,I'll try it.

**Comment by cyb70289** [comment]
Looks the two cases are tested against different data size?
[1, 1, 544, **192**] vs. [1, 1, 544, **992**]

Besides, for the first test cast, I believe below line will realize all the physical pages.
`buffer = sharedctypes.RawArray(ctypes.c_uint8, capacity + 1)`
So the benchmarked code loop won't cause any page fault.

But for pyarrow case, below line only reserves pages without truly allocate anyone.
`mmap = pa.create_memory_map(path, 5000000 * 1000)`
So the benchmarked code loop will trigger tons of page faults.

I benchmarked the running time of the whole program, with same data size, and tempfile under 'dev/shm', pyarrow(0.459s) is faster than sharedctypes(0.947s).

**Comment by qiuyang163** [comment]
> Looks the two cases are tested against different data size? [1, 1, 544, **192**] vs. [1, 1, 544, **992**]
> 
> Besides, for the first test cast, I believe below line will realize all the physical pages. `buffer = sharedctypes.RawArray(ctypes.c_uint8, capacity + 1)` So the benchmarked code loop won't cause any page fault.
> 
> But for pyarrow case, below line only reserves pages without truly allocate anyone. `mmap = pa.create_memory_map(path, 5000000 * 1000)` So the benchmarked code loop will trigger tons of page faults.
> 
> I benchmarked the running time of the whole program, with same data size, and tempfile under 'dev/shm', pyarrow(0.459s) is faster than sharedctypes(0.947s).

could you share your test code？tks

**Comment by cyb70289** [comment]
```python
import numpy as np
import pyarrow as pa
import time
import os

data = np.ones((1, 1, 544, 192), dtype=np.float32)

tensor = pa.Tensor.from_numpy(data)

path = os.path.join(str("/dev/shm/"), 'pyarrow-tensor-ipc-roundtrip')
mmap = pa.create_memory_map(path, 5000000 * 1000)

s = time.time()
for i in range(1000):
    result = pa.ipc.write_tensor(tensor, mmap)
e = time.time()

print(e - s)

#output_stream = pa.BufferOutputStream()
#
#s = time.time()
#for i in range(1000):
#    result = pa.ipc.write_tensor(tensor, output_stream)
#e = time.time()
#
#print(e - s)
```

**Comment by qiuyang163** [comment]
> ```python
> import numpy as np
> import pyarrow as pa
> import time
> import os
> 
> data = np.ones((1, 1, 544, 192), dtype=np.float32)
> 
> tensor = pa.Tensor.from_numpy(data)
> 
> path = os.path.join(str("/dev/shm/"), 'pyarrow-tensor-ipc-roundtrip')
> mmap = pa.create_memory_map(path, 5000000 * 1000)
> 
> s = time.time()
> for i in range(1000):
>     result = pa.ipc.write_tensor(tensor, mmap)
> e = time.time()
> 
> print(e - s)
> 
> #output_stream = pa.BufferOutputStream()
> #
> #s = time.time()
> #for i in range(1000):
> #    result = pa.ipc.write_tensor(tensor, output_stream)
> #e = time.time()
> #
> #print(e - s)
> ```

sorry,I havent't understand.In your opinion, `mmap = pa.create_memory_map(path, 5000000 * 1000)` this line only reserves pages without truly allocate anyone and the code loop will cause some page fault. why pyarrow(0.459s) is faster than sharedctypes(0.947s)?

I modified my test code to the same data size
```
import numpy as np
import pyarrow as pa
import time
import os

data = np.ones((1, 1, 544, 192), dtype=np.float32)

tensor = pa.Tensor.from_numpy(data)

path = os.path.join(str("/dev/shm/"), 'pyarrow-tensor-ipc-roundtrip')
mmap = pa.create_memory_map(path, 5000000 * 1000)

s = time.time()
for i in range(1000):
    result = pa.ipc.write_tensor(tensor, mmap)
e = time.time()

print(e - s)
```

pyarrow :0.23s

```
import numpy as np
import time
import ctypes

from multiprocessing import sharedctypes

data = np.ones([1, 1, 544, 192], dtype=np.float32)
capacity = 1000 * 1 * 544 * 192 * 4
buffer = sharedctypes.RawArray(ctypes.c_uint8, capacity + 1)

ndarray = np.ndarray((capacity,), dtype=np.uint8, buffer=buffer)

cur_offset = 0

t = time.time()
for i in range(1000):
    data = np.frombuffer(data, dtype=np.uint8)
    data_size = data.shape[0]
    ndarray[cur_offset:data_size + cur_offset] = data
    cur_offset += data_size
e = time.time()

print(e - t)
```
sharedctypes cost 0.10s

**Comment by cyb70289** [comment]
We should compare the running time of the whole application, not only the loop.
Because something very heavy (major page fault) happens before the loop and is not counted in the first test. But it's counted in the second test.

**Comment by cyb70289** [comment]
`sharedctypes.RawValue` calls `memset` which realizes all the physical pages. 
https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/multiprocessing/sharedctypes.py#L50

**Comment by cyb70289** [comment]
I'm closing this issue.
Feel free to continue comment.
