### ISSUE TITLE
python calling c++ code with arrow

### ISSUE THREAD

**Issue by 50hz** [apache/arrow#1382]
thanks for making Arrow! If I understand correctly, it should be possible to use Arrow as the intermediate (zero-copy in-memory storage) format for python to call/communicate with a c++ function (instead of using e.g. JSON)? If this is the case, is there a chance we can have some example code? or any hint/direction? thanks

**Comment by wesm** [comment]
Hi, you want to use the IPC interfaces:

http://arrow.apache.org/docs/cpp/namespacearrow_1_1ipc.html

The stream writer writes a sequence of message encapsulating an Arrow schema and one or more record batches (tables) corresponding to that schema. The stream reader can parse those messages with zero-copy. The actual RPC mechanism (client/server) you would need to use some other tool, like gRPC or Thrift, to implement, but you could use Arrow as the on-wire format for data transport
