### ISSUE TITLE
Confusion about the Arrow Formats Categorization 

### ISSUE THREAD

**Issue by liusitan** [apache/arrow#13850]
I am looking at the 
https://arrow.apache.org/cookbook/py/io.html#memory-mapping-arrow-arrays-from-disk
Recently I am trying to implement arrow file format for memory_mapped read. However, I don't know which one to use.
Arrow arrays that have been written to disk in the **_Arrow IPC format_** can be memory mapped back directly from the disk.

with pa.memory_map('arraydata.arrow', 'r') as source:
    loaded_arrays = pa.ipc.open_file(source).read_all()
arr = loaded_arrays[0]
print(f"{arr[0]} .. {arr[-1]}")
0 .. 99

What does the Arrow IPC format refer to? 
Is the arrow ipc streaming format or the arrow ipc format, what's the difference? 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/20542539/184042849-2a8fc178-e4b4-4c1e-8f36-7dddc61bfddb.png">

By RecordBatchFileWriter, what kind of arrow format does it write to?
with pa.OSFile('penguin-dataset.arrow', 'wb') as sink:
    with pa.RecordBatchFileWriter(sink, table.schema) as writer:
        writer.write_table(table)

how about this one? what kind of arrow format does it write to?
with open(filename, 'wb') as sink:
    with pa.ipc.RecordBatchStreamWriter(sink, pdf.schema) as writer:
        data = writer.write(pdf)

**Comment by drin** [comment]
the IPC format refers to a memory format used by arrow. Most file writers will write the IPC file format, which is the IPC format but with slight adjustments for tuning for files and file systems. Most stream writers will write the IPC stream format.

**Comment by drin** [comment]
so RecordBatchFileWriter writes the IPC file format, and RecordBatchStreamWriter writes the IPC stream format.

**Comment by drin** [comment]
note that the first paragraph of the sections you highlighted in red describe the differences between the 2, but essentially the file format additionally writes a footer:

> What follows in the file is identical to the stream format. At the end of the file, we write a footer containing a redundant copy of the schema (which is a part of the streaming format) plus memory offsets and sizes for each of the data blocks in the file.

**Comment by drin** [comment]
@liusitan did my comments answer your questions? can we close this?

**Comment by liusitan** [comment]
oh yes I thought I closed it

Best,
Sitan Liu


________________________________

**Comment by drin** [comment]
thanks! I can't close it myself, so just close it when it's convenient

**Comment by liusitan** [comment]
thanks for answering, sorry for the bothering, it's you answer my question : >
