### ISSUE TITLE
[Java] JDBC parameter binder for List and Map vectors

### ISSUE THREAD

**Issue by igor-suhorukov** [apache/arrow#13895]
Typical real life Arrow datasets contain List/Map type vectors of primitive type. Looks logically implement default JDBC parameter binders for such vector type or implement some kind on binder code extensibility of core framework via MetaINF/ServiceLocator

Related tickets:
https://issues.apache.org/jira/browse/ARROW-17430
https://issues.apache.org/jira/browse/ARROW-17431

**Comment by lidavidm** [comment]
Thanks for the issues. Is there further discussion beyond the JIRA tickets? We generally try to keep discussions there.

**Comment by igor-suhorukov** [comment]
Resolved by :
https://github.com/apache/arrow/pull/13906
https://github.com/apache/arrow/pull/13941
