### ISSUE TITLE
Is it possible to provide a partial schema to pyarrow to_parquet(), and infer everything else?

### ISSUE THREAD

**Issue by hungcs** [apache/arrow#14025]
I know that one particular column will always be a list of floats, so I do:

```
import pyarrow as pa
schema = {"col1": pa.list_(int64())}
df.to_parquet(schema=schema)
```

however, it seems providing an explicit schema will make it so that all other columns are not included in the resulting parquet file. I would like to have it so that all the other column types are included and inferred.

I know there is a `pyarrow.from_pandas()`, but the df may be a dask dataframe

**Comment by AlenkaF** [comment]
The schema must include all the columns that are needed in the output.

For example if you have a Pandas dataframe
```python
>>> import pandas as pd
>>> df = pd.DataFrame(
...     {
...         "A": [1, 2, 3],
...         "B": ["a", "b", "c"],
...         "C": pd.date_range("2016-01-01", freq="d", periods=3),
...     },
...     index=pd.Index(range(3), name="idx"),
... )

>>> df
     A  B          C
idx                 
0    1  a 2016-01-01
1    2  b 2016-01-02
2    3  c 2016-01-03
```

And you define only two columns in the schema:

```python
import pyarrow as pa
>>> schema=pa.schema([
...     ('A', pa.int16()),
...     ('B', pa.string())
... ])
```

The ouput will include these two columns specified by the schema.

```python
>>> df.to_parquet('df.parquet.gzip', schema=schema)
>>> pd.read_parquet('df.parquet.gzip')
   A  B
0  1  a
1  2  b
2  3  c
```

You will have to **include all of them in the schema** if you do not want any of the columns to be lost.
If there are a large number of columns you can save the schema from pyarrrow table and then change the type for one column only:

```python
>>> table = pa.table(df)
>>> table
pyarrow.Table
A: int64
B: string
C: timestamp[ns]
----
A: [[1,2,3]]
B: [["a","b","c"]]
C: [[2016-01-01 00:00:00.000000000,2016-01-02 00:00:00.000000000,2016-01-03 00:00:00.000000000]]

>>> # Save the schema
>>> schema = table.schema
>>> schema
A: int64
B: string
C: timestamp[ns]
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": "idx", "start": 0, ' + 600

>>> # Change datatype and save into new schema
>>> schema_new = schema.set(0, pa.field('A', pa.int16()))
>>> schema_new
A: int16
B: string
C: timestamp[ns]
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": "idx", "start": 0, ' + 600

>>> # Create a parquet file qith all columns and changed type of one
>>> df.to_parquet('df.parquet.gzip', schema=schema_new)
>>> df_from_parquet = pd.read_parquet('df.parquet.gzip')
>>> df_from_parquet
   A  B          C
0  1  a 2016-01-01
1  2  b 2016-01-02
2  3  c 2016-01-03
>>> pa.table(df_from_parquet)
pyarrow.Table
A: int16
B: string
C: timestamp[ns]
----
A: [[1,2,3]]
B: [["a","b","c"]]
C: [[2016-01-01 00:00:00.000000000,2016-01-02 00:00:00.000000000,2016-01-03 00:00:00.000000000]]
```

If the structure of the dataframes do not change and you only need to do this once, I think that might help.

**Comment by hungcs** [comment]
thanks @AlenkaF! Do you know if there's a performance hit when calling `pa.table(df)` on a dask dataframe? Do all the rows need to be read for type inference? (This may be what `df.to_parquet()` does implicitly, in which case there we would be doing the same work anyways, but I'm not familiar enough with this path)

**Comment by AlenkaF** [comment]
Oh, what about `pa.Schema.from_pandas(df)`? 🤦‍♀️ 

```python
>>> import pyarrow as pa
>>> pa.Schema.from_pandas(df)
A: int64
B: string
C: timestamp[ns]
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": "idx", "start": 0, ' + 600
>>> 
```

**Comment by AlenkaF** [comment]
Or manually construct the schema like so:

```python
pa.schema([
    ('some_int', pa.int32()),
    ('some_string', pa.string())
])
```

For all the columns you need in the parquet file.

**Comment by AlenkaF** [comment]
I have created a JIRA issue for `parquet.write_table`/`parquet.ParquetWriter` to except a partial schema and infer everything else:
https://issues.apache.org/jira/browse/ARROW-18001
