### ISSUE TITLE
Method arrowPySparkSelfDestructEnabled([]) does not exist

### ISSUE THREAD

**Issue by bhaskarkvvsr** [apache/arrow#14037]
I am trying to convert a spark data frame to pandas data frame by enabling these two flags

```
'spark.sql.execution.arrow.pyspark.enabled'
'spark.sql.execution.arrow.pyspark.fallback.enabled'
```

But I'm getting this error while trying to do so.

```
File /opt/conda/envs/python385/lib/python3.8/site-packages/pyspark/sql/pandas/conversion.py:108, in PandasConversionMixin.toPandas(self)
    106 # Rename columns to avoid duplicated column names.
    107 tmp_column_names = ['col_{}'.format(i) for i in range(len(self.columns))]
--> 108 self_destruct = self.sql_ctx._conf.arrowPySparkSelfDestructEnabled()
    109 batches = self.toDF(*tmp_column_names)._collect_as_arrow(
    110     split_batches=self_destruct)
    111 if len(batches) > 0:

Py4JError: An error occurred while calling o1723.arrowPySparkSelfDestructEnabled. Trace:
py4j.Py4JException: Method arrowPySparkSelfDestructEnabled([]) does not exist
```

I have installed `pyarrow` through conda-forge

python version- 3.8.5
Pyspark version - 3.2.1
Pyarrow version - 8.0.0
OS details- 

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

**Comment by AlenkaF** [comment]
Hi @bhaskarkvvsr, sorry for a later reply.
I think this is an issue for [Apache Spark](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-40367?filter=allopenissues).

I see there was some response on https://stackoverflow.com/questions/73585222/error-while-using-arrow-library-to-convert-spark-dataframe-to-pandas-dataframe.

I am not sure what the flags enable, but this sql part of Apache Spark codebase is where the `arrowPySparkSelfDestructEnabled` method is defined:
https://github.com/apache/spark/blob/44573a26bafb487f0e0c854b141eebf9990b22c1/python/pyspark/sql/pandas/conversion.py#L127-L128.
