### ISSUE TITLE
parquet.dll : libcrypto-3-x64.dll missing module

### ISSUE THREAD

**Issue by davesworking** [apache/arrow#14068]
I am building Arrow with PARQUET_REQUIRE_ENCRYPTION=OFF set.

When I view parquet.dll in Dependencies Viewer, it shows PARQUET_REQUIRE_ENCRYPTION=OFF missing.

How can I build without a dependency on libcrypto?

Thanks!

**Comment by drin** [comment]
does your cmake log show that variable being correctly interpreted?

I just checked the CMakeLists.txt file and didn't see anything about MSVC that is special cased that would be relevant.

**Comment by drin** [comment]
that being said, I believe my parquet library also looks for libcrypto, so... maybe this flag doesn't help with that

**Comment by drin** [comment]
For reference:

```bash
otool -L /usr/local/arrow-dev/lib/libparquet.dylib
/usr/local/arrow-dev/lib/libparquet.dylib:
        /usr/local/arrow-dev/lib/libparquet.900.dylib (compatibility version 900.0.0, current version 900.0.0)
        ...
        /opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
        /opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
        ...
```

**Comment by drin** [comment]
sorry, I think I'm actually no help here, but maybe the context is helpful for someone who knows more :(

**Comment by davesworking** [comment]
I should mention that I am installing Arrow via vcpkg:

`.\vcpkg\vcpkg.exe install "arrow[core,csv,dataset,filesystem,json,parquet]" --triplet=%tripletName% --x-install-root=%installDir% --recurse`

I am turning off openssl and encryption manually in the port files:

```
sed -i "87i \       \ -DARROW_USE_OPENSSL=OFF" vcpkg\ports\arrow\portfile.cmake
sed -i "88i \       \ -DPARQUET_REQUIRE_ENCRYPTION=OFF" vcpkg\ports\arrow\portfile.cmake
```

here are the grep (findstr) results:

--- **cwd** ---
vcpkg\packages\arrow_x64-windows\share\arrow\ArrowOptions.cmake:set(PARQUET_REQUIRE_ENCRYPTION "OFF")
vcpkg\ports\arrow\portfile.cmake:        parquet     PARQUET_REQUIRE_ENCRYPTION
vcpkg\ports\arrow\portfile.cmake:        -DPARQUET_REQUIRE_ENCRYPTION=OFF

--- **installdir** ---
x64-windows\ports\arrow\portfile.cmake:        parquet     PARQUET_REQUIRE_ENCRYPTION
x64-windows\ports\arrow\portfile.cmake:        -DPARQUET_REQUIRE_ENCRYPTION=OFF
x64-windows\share\arrow\ArrowOptions.cmake:set(PARQUET_REQUIRE_ENCRYPTION "OFF")

**Comment by kou** [comment]
Could you attach the log when you install Apache Arrow via vcpkg? I want to see all outputs from CMake.

**Comment by davesworking** [comment]
I am sorry. I cannot reproduce this now. The second sed command, above, initially was missing the 'D' at the beginning and just read -PARQUET_REQUIRE_ENCRYPTION=OFF.

Possibly correcting that typo has fixed the issue.

**Comment by drin** [comment]
if that's the case, then when you get the chance can you close the issue?

**Comment by davesworking** [comment]
not reproducible
