### ISSUE TITLE
Reading every batch while being written to the server

### ISSUE THREAD

**Issue by iamsmkr** [apache/arrow#14089]
I was going through this [Flight Java Example](https://arrow.apache.org/cookbook/java/flight.html) and realized that reading starts only after all the batches are written. This seems problematic if we are writing a huge amount of data in batches. Ideally we would expect every batch being read as soon as they are written to the server.

What are the changes needed in the example code to achieve this, if that is even possible? Please suggest.

**Comment by lidavidm** [comment]
Hi @iamsmkr can you explain? That is not true, the server gets data as soon as the client writes it. The example shows read-after-write because it's from the client's perspective.

**Comment by iamsmkr** [comment]
@lidavidm Thanks for your reply. I have written a small working example (in Scala) for you to have a look [here](https://github.com/iamsmkr/arrow-flight-scala). 

In the `Main.scala`, I am writing and reading in separate threads. What I would expect is that all batches are read as soon as they are written. However, I could do this only after "completing all sends per batch" i.e., calling `listener.completed()` after every `listener.putNext()`, as shown below:
```scala
  Future(reader.readMessages(1))

  writer.addToBatch(0, "Shivam")
  writer.addToBatch(1, "Shyam")
  writer.addToBatch(2, "Srinivas")
  writer.sendBatch()
  writer.completeSend()

  Thread.sleep(1000)

  writer.addToBatch(0, "Neha")
  writer.addToBatch(1, "Naveen")
  writer.addToBatch(2, "Nisha")
  writer.sendBatch()
  writer.completeSend()
```

First read in the following version won't work!
```scala
//  Future(reader.readMessages(1))

  writer.addToBatch(0, "Shivam")
  writer.addToBatch(1, "Shyam")
  writer.addToBatch(2, "Srinivas")
  writer.sendBatch()
//  writer.completeSend()
  reader.readMessages()                 // THIS DOESN'T READ THE FIRST BATCH AS EXPECTED!
  println(s"reading A")
  Thread.sleep(5000)

  writer.addToBatch(0, "Neha")
  writer.addToBatch(1, "Naveen")
  writer.addToBatch(2, "Nisha")
  writer.sendBatch()
  writer.completeSend()
  reader.readMessages()
```

Hope I could explain it better this time. Please suggest what changes could be made to fix this. Thanks!

**Comment by lidavidm** [comment]
Well, yes of course: the server implementation isn't actually making the data available until the call finishes:

``` scala
  override def acceptPut(context: CallContext, flightStream: FlightStream, ackStream: StreamListener[PutResult]): Runnable = {
    val batches = new util.ArrayList[ArrowRecordBatch]()
    () => {
      var rows: Long = 0
      while (flightStream.next()) {
        val unloader = new VectorUnloader(flightStream.getRoot)
        val arb = unloader.getRecordBatch
        batches.add(arb)
        rows = rows + flightStream.getRoot.getRowCount
      }

      val dataset = ArrowFlightDataset(batches, flightStream.getSchema, rows)
      datasets.put(flightStream.getDescriptor, dataset)
      ackStream.onCompleted()
    }
  }
```
This buffers the data in memory and does not update the member variable `datasets` until the call completes. How would Flight be able make the data available to the `getStream` implementation for you? 

Flight is just a framework for building services, so if you want to be able to read data while writing, Flight will not get in your way of implementing that, but neither will it do that for you automatically. In this case, you'll have to update `datasets` as soon as the call starts, mutate the dataset as the call progresses, and have some way of coordinating between `acceptPut` and `getStream` so the latter knows when all data has been uploaded. And you'll want to handle the client disconnecting, etc.

**Comment by iamsmkr** [comment]
Thanks @lidavidm. This clarifies! But I do wonder what APIs to use to achieve this. Is there any example code that I could refer? Any help is much appreciated!

**Comment by lidavidm** [comment]
The APIs are not different. This is up to the application. You are synchronizing two threads, that is nothing specific to Arrow or Flight.

**Comment by lidavidm** [comment]
@iamsmkr do you have other questions here?

**Comment by iamsmkr** [comment]
Which file and line are you pointing at? @lidavidm

**Comment by lidavidm** [comment]
https://github.com/iamsmkr/arrow-flight-scala/blob/b7ecb25d4e4e772e47c3c6ee0485134580b428df/src/main/scala/com/iamsmkr/arrowflight/ArrowFlightProducer.scala#L19-L33

this just creates a new queue and overwrites the previous one on every iteration - why bother with the queue in the first place?

**Comment by iamsmkr** [comment]
@lidavidm I am not sure if I understand you. It is creating a new blocking queue only per file descriptor. See this -> https://github.com/iamsmkr/arrow-flight-scala/commit/06482900ebb4ae7fcfbf40be9f4a7dfb751c0cb0
The print statement is called only once per endpoint. If the endpoint is same new messages are added to the same blocking queue.

**Comment by lidavidm** [comment]
Ah…I can't deal with the lack of braces, I skipped that line entirely, makes sense
