### ISSUE TITLE
Possibility to write ORC by chunks (C++)

### ISSUE THREAD

**Issue by LouisClt** [apache/arrow#14211]
Hello,
I use Arrow as an intermediate format before writing Parquet or ORC.
However, in order to reduce the memory fottprint (as the tables can be quite big), I need to write both formats little by little.
For the parquet export, I manager to do so by using the "WriteColumnChunk" method.
However, for the ORC format, there is no such thing, the only method available is "Write(table)" which writes a whole table into the file. That forces me to allocate a whole Arrow table in memory beforehand, which I can't do.
So is there a plan to support this in the future ?

I looked at the code, and it seems to be pretty easy to make a method like that, since the "write" method already write little chunks internally.

**Comment by LouisClt** [comment]
Thanks, for your answer. I tried the approach you are suggesting, but I could not get it to work, it failed when I tried to reimport it afterwards. But maybe that was a mistake in my testing, so I will give it another try.

**Comment by wjones127** [comment]
It's also possible the API is misleading; I'm not super familiar with the implementation. It doesn't seem like the internal writer is actually re-used...

https://github.com/apache/arrow/blob/5256e434935f90f02023e6dfce3b5c1ed056a1c9/cpp/src/arrow/adapters/orc/adapter.cc#L733-L734

**Comment by LouisClt** [comment]
I re-tested it and indeed, the following import was not working. 
But it indeed gave me the idea to try to re-use the "writer_" rather than reallocating it everytime.

Doing so, it was finally working. I think I will do a PR for this.
