### ISSUE TITLE
Java deserialization

### ISSUE THREAD

**Issue by h928725721** [apache/arrow#14237]
I've just started learning Arrow.
In Python we can use 'import pyarrow 'as a tool for serialization and deserialization.
But in Java，How do we deserialize a binary?
![image](https://user-images.githubusercontent.com/35357788/192264755-a64f3eed-458f-428e-8cfc-d80893a4bcd8.png)
![image](https://user-images.githubusercontent.com/35357788/192264944-694e3cf6-c32d-42bc-a000-4016a964d7a6.png)

I try to use the above method，but the column values cannot be resolved
Please help me solve this problem, thank you

**Comment by h928725721** [comment]
![1664191732695](https://user-images.githubusercontent.com/35357788/192265593-2ca2cb48-43fc-4b54-a158-e2bdeec83458.png)
This is the data parsed in Python

**Comment by h928725721** [comment]
I used ARROW8.0
I can't provide an executable example because I'm using confidential data，so sorry

**Comment by lidavidm** [comment]
For ArrowStreamReader, you must call `loadNextBatch` to load the next chunk of data into the VectorSchemaRoot before using the root. I don't see that in your screenshot. You must do this in a loop, processing the chunk of data, until `loadNextBatch` returns `false`. See the API docs: https://arrow.apache.org/docs/java/reference/index.html

Also see this example: https://arrow.apache.org/cookbook/java/io.html#id4

**Comment by h928725721** [comment]
> For ArrowStreamReader, you must call `loadNextBatch` to load the next chunk of data into the VectorSchemaRoot before using the root. I don't see that in your screenshot. You must do this in a loop, processing the chunk of data, until `loadNextBatch` returns `false`. See the API docs: https://arrow.apache.org/docs/java/reference/index.html
> 
> Also see this example: https://arrow.apache.org/cookbook/java/io.html#id4

Thank you very much,You solved my problem
