### ISSUE TITLE
PostgreSQL via Flight SQL

### ISSUE THREAD

**Issue by konstantin-doncov** [apache/arrow#14284]
Is it possible to use Apache Arrow Flight SQL to directly access PostgreSQL from Java(how does JDBC do it)? If so, how?

**Comment by lidavidm** [comment]
No, Flight SQL is a wire protocol, which means the (Postgres) server, or some proxy, must implement it. It is not like JDBC where a client-side driver translates API calls into a server-specific protocol. (For that idea, see https://github.com/apache/arrow-adbc.)

For Postgres, either Postgres would need to implement Flight SQL, or a proxy must be implemented that translates Flight SQL to the Postgres wire protocol.

**Comment by lidavidm** [comment]
@konstantin-doncov do you have any other questions here?

**Comment by konstantin-doncov** [comment]
That's all, thanks!
