### ISSUE TITLE
Help with building from source

### ISSUE THREAD

**Issue by matteosantama** [apache/arrow#14291]
There's a simple change I would like to make to `pyarrow` but before I open a PR I want to test it locally. To do so, I need to build the library from source -- but I am really struggling with the compilation process. 

I tried following the instructions [here](https://github.com/apache/arrow/blob/master/docs/source/developers/python.rst), but kept running into problems at multiple stages. Likely, those instructions there are a bit stale. So I abandoned it in favor of the automatic build script [here](https://github.com/apache/arrow/blob/master/python/examples/minimal_build/build_venv.sh). With the script, the compilation process runs to completion but when I go to import the library I run into problems.

```python
>>> import pyarrow as pa
ImportError: dlopen(/Users/matteosantamaria/arrow/python/pyarrow/lib.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libarrow.1000.dylib'
  Referenced from: '/Users/matteosantamaria/arrow/python/pyarrow/lib.cpython-310-darwin.so'
  Reason: tried: '/Users/matteosantamaria/arrow/python/pyarrow/libarrow.1000.dylib' (no such file), '/Users/matteosantamaria/arrow/python/pyarrow/libarrow.1000.dylib' (no such file), '/usr/local/lib/libarrow.1000.dylib' (no such file), '/usr/lib/libarrow.1000.dylib' (no such file)
```

Does anyone know what this error is complaining about? If it helps, I am on macOS M1.

**Comment by wjones127** [comment]
Did you follow the instructions for Conda or for pip? If it was pip, you may have missed this step:

```bash
export ARROW_HOME=$(pwd)/dist
export LD_LIBRARY_PATH=$(pwd)/dist/lib:$LD_LIBRARY_PATH
```

**Comment by matteosantama** [comment]
It is for pip. The script sets those variables [here](https://github.com/apache/arrow/blob/master/python/examples/minimal_build/build_venv.sh#L29-L30)

**Comment by wjones127** [comment]
On Mac OS, you may also need to pass this flag to 

```
-DARROW_INSTALL_NAME_RPATH=OFF
```

When you run cmake:

```bash
cmake -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Debug \
        -DARROW_INSTALL_NAME_RPATH=OFF \
        -DARROW_DATASET=ON \
        -DARROW_WITH_BZ2=ON \
        -DARROW_WITH_ZLIB=ON \
        -DARROW_WITH_ZSTD=ON \
        -DARROW_WITH_LZ4=ON \
        -DARROW_WITH_SNAPPY=ON \
        -DARROW_WITH_BROTLI=ON \
        -DARROW_PARQUET=ON \
        -DPARQUET_REQUIRE_ENCRYPTION=ON \
        -DARROW_PYTHON=ON \
        -DARROW_BUILD_TESTS=ON \
        ..
```

**Comment by matteosantama** [comment]
Woohoo, that worked!
