### ISSUE TITLE
Cannot create ListArray of element type float32

### ISSUE THREAD

**Issue by buhrmann** [apache/arrow#1431]
To reproduce (in pyarrow v0.8.0):

```
import pyarrow as pa
l = [[1.2, 3.4], [9.0, 42.0]]
pa.array(l, type=pa.list_(pa.float32()))
```

Results in "ArrowNotImplementedError: value type not implemented". 

float64 works without problem.

**Comment by wesm** [comment]
I think this is https://issues.apache.org/jira/browse/ARROW-1345, same as #1430, but we should make sure

**Comment by wesm** [comment]
This is a different bug. I opened https://issues.apache.org/jira/browse/ARROW-2007
