### ISSUE TITLE
[C++][Python] Get size of RecordBatchWriter.close()?

### ISSUE THREAD

**Issue by varadal** [apache/arrow#14438]
Hello,
Is there a way to get the size of what is written when a writer is closed()?

**Comment by ljluestc** [comment]
In Apache Arrow, the RecordBatchWriter.close() method is responsible for finalizing the writing process and flushing any remaining data to the underlying storage or stream. However, the Arrow library itself does not provide a direct method to retrieve the size of the data that was written when the writer is closed.

**Comment by varadal** [comment]
That makes sense. Then is there a way to use MakeStreamWriter with a MemoryMappedFile sink?

**Comment by ljluestc** [comment]
```
#include <arrow/api.h>
#include <arrow/io/api.h>

using namespace arrow;

int main() {
  std::shared_ptr<io::MemoryMappedFile> mmap_file;
  ARROW_ASSIGN_OR_RAISE(mmap_file, io::MemoryMappedFile::Create("data.arrow", io::FileMode::WRITE));
  std::shared_ptr<io::FileOutputStream> output_stream = std::make_shared<io::FileOutputStream>(mmap_file);
  std::shared_ptr<ipc::RecordBatchWriter> writer;
  ARROW_ASSIGN_OR_RAISE(writer, ipc::MakeFileWriter(output_stream, schema));
  ARROW_RETURN_NOT_OK(writer->WriteRecordBatch(*record_batch));
  ARROW_RETURN_NOT_OK(writer->Close());
  int64_t written_size = mmap_file->GetSize();
  std::cout << "Written data size: " << written_size << std::endl;
  return 0;
}

```

**Comment by varadal** [comment]
FileOutputStream doesn't accept a MemoryMappedFile, but I was able to get my code to work with your help. Thanks so much!
