### ISSUE TITLE
Some datetimes come back from Pyarrow off by ~21 minutes

### ISSUE THREAD

**Issue by h5rdly** [apache/arrow#1446]
I'm randomizing datetimes to test our database, and while writing a test, found that some dates come back wrong. Here's a short reproduction snippet:

> import pyarrow as pa
> import pyarrow.parquet as pq
> import numpy as np
> from numpy.random import rand, randint, uniform, choice
> 
> dts = [np.datetime64('1913-11-02 13:49:19').tolist()]
> 
> dates = pa.array(dts)
> test_table = pa.Table.from_arrays([dates], ['dates'])
> pq.write_table(test_table, 'datetimes.parquet')  
> 
> arrow_table = pq.read_table('datetimes.parquet')
> table = arrow_table.to_pydict()

The datetime that comes back is off by 20-21 mins. Am I somehow misusing the library?

My specs : Ubuntu 14.04, Python 2.7.6, Pyarrow 0.7.x (This was at work,  I should've checked the version, apologize)

Thanks,
Eli

**Comment by alphalfalfa** [comment]
I did a quick try and did not observe mismatch. Of course, my environment setup is very different: Python 3.5.4 and Pyarrow 0.6.0. I will try again with the same versions later.  

>>> import pyarrow as pa
>>> import pyarrow.parquet as pq
>>> import numpy as np
>>> from numpy.random import rand, randint, uniform, choice
>>>
>>> dts = [np.datetime64('1913-11-02 13:49:19').tolist()]
>>>
>>> dates = pa.array(dts)
>>> test_table = pa.Table.from_arrays([dates], ['dates'])
>>> pq.write_table(test_table, 'datetimes.parquet')
>>>
>>> arrow_table = pq.read_table('datetimes.parquet')
>>> table = arrow_table.to_pydict()
>>> table
OrderedDict([('dates', [Timestamp('1913-11-02 13:49:19')])])

**Comment by wesm** [comment]
@h5rdly what is your system locale? This is likely a locale issue related to some of the POSIX time methods we're using internally

**Comment by h5rdly** [comment]
Sorry for the late response, it was in fact a locale issue. Thanks for the help!

**Comment by wesm** [comment]
If you can give any details that would help us reproduce (what was your system locale?), we should be able to resolve locale issues within the software rather than expecting users to deal with it
