### ISSUE TITLE
MIGRATION: Evaluate image and attachment handling

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14513]
ASF Jira issues may have attached content, including images displayed inline in comments. This issue is a marker to evaluate how that content may migrate, and whether additional work may be required. Issue attachments may simply be referenced in an added comment, indicating attachments exist and can be retrieved from the source issue. Missing inline images (if not handled by migration) may be a bit more challenging to handle usefully.

**Comment by toddfarmer** [comment]
By default, inline images render as broken image links in migrated content - see [this example](https://github.com/toddfarmer/test_import/issues/309):

![image](https://user-images.githubusercontent.com/3641430/201753006-fd77c0c3-a014-4bbe-8a90-ea89a42173b0.png)

**Comment by toddfarmer** [comment]
By adding some additional translation, it's possible to direct the inline image/attachment links in the migrated content back to the ASF Jira-hosted content.  See [this example](https://github.com/toddfarmer/test_import/issues/310).

Note that this points back to the original ASF Jira issue content, and the actual attachment has not been migrated to GitHub. This also means that if ASF Jira content is removed, inline content such as this will break.

**Comment by toddfarmer** [comment]
There are currently [516 Jira issues with attachments](https://issues.apache.org/jira/issues/?jql=project%20%3D%20ARROW%20AND%20attachments%20is%20not%20empty).

**Comment by toddfarmer** [comment]
It would be trivially easy to list the attachments with links to the content found in ASF Jira (not copying content into GitHub). Do we have strong feelings on needing to bring this referenced content over to GitHub itself, or can we allow migrated issues to point back to the content in ASF Jira? Because ASF Jira is world-readable, the content itself isn't restricted to registered Jira users. Any new attachments added would obviously end up in GitHub.

**Comment by toddfarmer** [comment]
Unless there are objections, I plan to:

1. Fix inline image links to point to the ASF Jira-hosted content from the source issue, without migrating/copying any content.
2. Add a list of issue attachments at time of migration to the issue description with links to the ASF Jira issue content (again, without copying any of that content to GitHub issues).

Both are demonstrated in this example issue:  https://github.com/toddfarmer/test_import/issues/313

**Comment by jorisvandenbossche** [comment]
Sounds good!
