### ISSUE TITLE
MIGRATION: Adjust GitHub issues template

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14512]
Users attempting to report issues via the Arrow GitHub project see the following options:

![image](https://user-images.githubusercontent.com/3641430/197903122-ee1dfa77-94d8-4f86-8995-1e81addedd75.png)

If issue tracking for the project is migrated to GitHub issues from ASF Jira, this will need to be adjusted [here](https://github.com/apache/arrow/tree/master/.github/ISSUE_TEMPLATE).

**Comment by jorisvandenbossche** [comment]
This is essentially a duplicate from https://issues.apache.org/jira/browse/ARROW-18364 and is resolved now?
