### ISSUE TITLE
MIGRATION: Define post-migration Jira updates

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14511]
If we migrate Jira content to GitHub issues, it probably makes sense to add a comment to the source Jira issue with a pointer to the migrated GitHub issue. This might also reference a document instructing users how to engage further after issue migration (e.g., manage their watched issues, assigned issues, stop working in Jira, etc.).

**Comment by toddfarmer** [comment]
It would be useful to identify a specific field in Jira we can leverage as a pointer to a migrated issue in GitHub. There is the "External Issue URL" field, which is [sparsely used today](https://issues.apache.org/jira/issues/?jql=project%20%3D%20ARROW%20AND%20%22External%20issue%20URL%22%20%20is%20not%20empty), and mostly seems to have been used at one time to point to related GitHub PRs that are otherwise tracked via other means (comments, etc.). If we prefer a different field, we will need to either select an existing unused field, or request Infra create such a field and possibly add it to our issue screens.

**Comment by westonpace** [comment]
+1 for External Issue URL, I'm pretty sure it's not being regularly used today and I don't think we want to make this more complex than needed.  I don't think the message needs to be too involved.

```
Arrow issues are now tracked on Github.  This issue has been migrated to https://github.com/apache/arrow/issues/xyz
```

**Comment by rok** [comment]
Comments pointing to migrated issues were added to all Jira issues, e.g. [ARROW-17832](https://issues.apache.org/jira/browse/ARROW-17832?focusedCommentId=17674920&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17674920).
