### ISSUE TITLE
[PyArrow] Issure reading file written with `flavor="spark"`

### ISSUE THREAD

**Issue by Heroico** [apache/arrow#1452]
Hi there!

I am using `pyarrow 0.8.0` on `python 3.5`, with pandas `0.21.1`. I wrote a file with `flavor="spark"`, and when I read it back and convert to pandas dataframe, I get an extra column with the index values. When I wrote it with the default flavor, there was no such column.

I tried adding some code to `parquet.py` on my end to handle this case but it felt quite ad-hoc. 

Is this expected?
What are my options? Just dropping the extra column whenever I read a parquet file?
Or converting the pandas dataframe to a plain record batch and write that?

Here is my example:

```[python]
#!/usr/bin/env python

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

df = pd.DataFrame({
'a': [-1, np.nan, 2.5, 4],
'b': [True, False, True, False],
'c': ['foo', 'bar', 'baz', "fiz"]})

t = pa.Table.from_pandas(df)
pq.write_table(t, "ex1.parquet")
pq.write_table(t, "ex2.parquet", flavor="spark")

t1 = pq.read_table("ex1.parquet")
t2 = pq.read_table("ex2.parquet")

print("t1\n")
print(t1.schema)
print(t1.to_pandas())

print("\nt2\n")
print(t2.to_pandas())
print(t2.schema)

print("\nversions\n")
print(pa.__version__)
print(pd.__version__)

f1 = pq.ParquetFile("ex1.parquet")
f2 = pq.ParquetFile("ex2.parquet")
```
And here is the part of the output concerned with the dataframes:
```
#t1, written with default flavor
     a      b    c
0 -1.0   True  foo
1  NaN  False  bar
2  2.5   True  baz
3  4.0  False  fiz

#t2, written with `flavor="spark"`
     a      b    c  __index_level_0__
0 -1.0   True  foo                  0
1  NaN  False  bar                  1
2  2.5   True  baz                  2
3  4.0  False  fiz                  3
```

**Comment by wesm** [comment]
Thanks for the bug report. I see what the issue is and I have opened https://issues.apache.org/jira/browse/ARROW-1961 about fixing. Patches welcome
