### ISSUE TITLE
MIGRATION: only migrate open issues?

### ISSUE THREAD

**Issue by nealrichardson** [apache/arrow#14546]
@assignUser said: "I think importing all issues regardless of status makes sense as there is no cost to us ( excl. migration script run time) and it has the benefits of keeping all previous discussion and knowledge in one place e.g. for new (and old but they might know to also check jira) contributors to look through prior to opening an issue or for the directional links between issues."

To argue the other side: whether or not there is no cost (I'm not sure I agree), I'm not sure there's any benefit, particularly given that we can keep the Jira issues where they are as read-only. They're only a click away on the old merged github PRs, and easily findable from the commit message prefixes. If we duplicate all of that in GitHub Issues, would we also go back and rewrite all of the past commit messages? If not, what's the point of duplicating the information in (closed) GitHub Issues?

**Comment by jorisvandenbossche** [comment]
> They're only a click away on the old merged github PRs, and easily findable from the commit message prefixes.

They are a click away for those cases indeed. But I quite often search through our (currently JIRA) issues, open and closed, to try to find back some old issue. 
If our issues start to be split between JIRA and GitHub over time, that means you would have to do this search in two places to have a complete search (and in addition for issues that are now open, you would get duplicated search results in both JIRA and GitHub, so you would have to look in JIRA for a subset of the issues that are not already contained in your github search)

**Comment by h-vetinari** [comment]
Comment from the peanut gallery: better to import everything, it makes searching the issue history so much easier (which is often a relevant source of information)

**Comment by assignUser** [comment]
Should we keep the existing issues? Restructure the open ones without a matching jira into the new format, delete closed issues?

**Comment by jorisvandenbossche** [comment]
I don't think there is any harm in keeping the closed issues? (deleting them would just remove that content, while it might have been useful user questions with answers) 

For the current issues, we could consider converting all of them into discussions, _if_ we would start using discussions for the user questions for which we currently pointed to the github issues.

**Comment by toddfarmer** [comment]
I'll voice my support for importing all ASF Jira issues, regardless of current state. I think retaining a single system to search for past work and decisions is important.
