### ISSUE TITLE
pyarrow wheel for python 3.11

### ISSUE THREAD

**Issue by david-engelmann** [apache/arrow#14572]
Add wheels for python 3.11

**Comment by assignUser** [comment]
Already on the way: https://github.com/apache/arrow/pull/14499

**Comment by david-engelmann** [comment]
@assignUser Incredible, it's just pending trouble shooting [AMD64 macOS 11 Python 3](https://github.com/apache/arrow/actions/runs/3364503539/jobs/5578929140#logs)

**Comment by raulcd** [comment]
hi @david-engelmann , the PR is currently only pending review, the CI failure you are pointing out is not related to the PR as it has failed on the default branch too. The PR adds CI jobs to be able to build Arrow wheels with Python 3.11 but it won't create or publish the wheels once merged. In the Apache Arrow project the process to generate and publish new wheels is tied with the releases. Once the PR is merged I will ask on the Apache Arrow mailing list how to proceed as we probably have to create a new minor release to generate the wheels for Python 3.11 but this will have to be voted / approved.
