### ISSUE TITLE
arrow 10.0.0 group_by  slice_max() 

### ISSUE THREAD

**Issue by cmonk28** [apache/arrow#14584]
Hello,

With the recent release to arrow 10.0.0 and implementation of slice_*() functions, will it also work in conjunction with a group_by()?

```
library(arrow)
library(dplyr)

df <- tibble(a = rep(letters, 2), b = 1:52, c = 52:1)
dfarrow <- arrow_table(df)
dfarrow %>% collect

df %>% group_by(a) %>% slice_max(b)
dfarrow %>% group_by(a)  %>% slice_max(b) %>% collect()
```

ie: the bottom two lines should return the same output.

Thanks!

**Comment by nealrichardson** [comment]
Alas, no. This and other differences in the implementation of features in Arrow are listed on https://arrow.apache.org/docs/r/reference/acero.html.
