### ISSUE TITLE
MIGRATION: Retain issue priority?

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14593]
The source ASF Jira system has a dedicated `Priority` field, for which there is no equivalent in GitHub issues. Should we use labels to retain this information as we migrate?  For example:

* `Priority: 1`
* `Priority: 2`

I personally prefer numeric priorities over strings such as `High` or `Urgent`, because it makes relative priority readily apparent without having to consult the list of possible values (and interpreting whether High or Urgent has higher priority). But I'm open to suggestions if other values are preferred.

**Comment by toddfarmer** [comment]
As a note, it is possible to [create custom fields in GitHub projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/best-practices-for-projects), which would allow explicit `Priority` field definition and tracking. That said, it seems it is not possible to directly query project custom fields for issue searching, except within the context of a specific project.

**Comment by toddfarmer** [comment]
[Example](https://github.com/toddfarmer/test_import/issues/44):

![image](https://user-images.githubusercontent.com/3641430/200137537-9ca65c92-ccf1-4e07-9b96-3d3ab7012899.png)

**Comment by jorisvandenbossche** [comment]
I think we mostly use "Priority: Blocker" for release management purposes, and somewhat "Priority: Critical" for prioritization of work. I am not sure we really use the other levels.

**Comment by raulcd** [comment]
I agree with @jorisvandenbossche here. The `Priority: Blocker` is really helpful for release management purposes and maybe another for work prioritization but the rest of the levels don't seem necessary in my opinion.

**Comment by jorisvandenbossche** [comment]
Short term, we can maybe "just" (assuming this is not too hard to set up) map the priority to labels? And then we can still later see if we want to keep all of them or only the blocker/critical ones?

**Comment by toddfarmer** [comment]
cc @rok to evaluate what needs done here.

**Comment by rok** [comment]
I like the idea of just bringing in the Jira priorities as labels. We would then have:
* Priority: Blocker
* Priority: Major
* Priority: Minor
* Priority: Trivial

**Comment by wjones127** [comment]
I'm skeptical those labels 4 labels are actually used. I'm personally only in favor of bringing over labels that are used in practice. Realistically, I think we only need two labels:

 * release-blocker: which tells us we cannot bump this issue to the next release milestone
 * critical-fix: which tells us we should prioritize fixing this over most other things. Defined as is in https://lists.apache.org/thread/s49bkj8ckgcjvjskhhz26xy1xscrswdp

I'm not familiar with any practice that involves Major/Minor/Trivial, and other commenters on this issue seem to be saying the same thing.

**Comment by rok** [comment]
I think these labels are used but not consistently so not sure if they are net good.

As for release-blocker - it could be skipped in favor of convention that everything within a milestone is a blocker for it.

**Comment by wjones127** [comment]
>  it could be skipped in favor of convention that everything within a milestone is a blocker for it.

Not sure about that. I think we often tag issues with the release to indicate that we would *like* to get that included, but not that it's absolutely necessary. It's helpful to have a tag that distinguishes what's nice to have and what's necessary. But maybe there's a better way to do that?

**Comment by rok** [comment]
Yeah, having an explicit label there will make it easier for the release work indeed. We would then migrate the following labels from Jira:
* Priority: Critical
* Priority: Blocker
* good-second-issue

**Comment by rok** [comment]
If there are no objections I'll create the last proposed labels when I start the migration sometime this week.

**Comment by raulcd** [comment]
@rok I have created the three labels as we are going to need the `Priority: Critical` in preparation for the release. I am going to start asking people to mark any release blocker with it on the mailing list and Zulip.

**Comment by rok** [comment]
I suppose this is resolved then.
