### ISSUE TITLE
read access violation this->raw_data_ in UnSafeAppend [Windows]

### ISSUE THREAD

**Issue by ssvenkatesh** [apache/arrow#1460]
## read access violation this->raw_data_  in UnSafeAppend

I tried using the build

Version: arrow-cpp-0.8.0-py35_vc14_2.tar
Visual Studio : 2017
Language : c++

And the sample code used:

	arrow::MemoryPool* pool = arrow::default_memory_pool();
	Int64Builder id_builder(pool);
	::arrow::Status s2 = id_builder.Init(10);

	::arrow::Status s3 = id_builder.Append(24);

error on append: 

>arrow::NumericBuilder<arrow::Int64Type>::UnsafeAppend(const __int64 val) Line 284	C++	Symbols loaded.
 arrow::NumericBuilder<arrow::Int64Type>::Append(const __int64 val) Line 274	C++	Symbols loaded.

  Is there anything else I have to initialze ?

**Comment by wesm** [comment]
Calling `Init` shouldn't be necessary, but the error is definitely odd.

**Comment by wesm** [comment]
Can someone please have a look and open an appropriate JIRA? This seems like the type of error that should show up in valgrind on Linux also

**Comment by ssvenkatesh** [comment]
The library binaries in the zip was in release mode while I was trying to run in Debug mode. Changing the configuration made it to work.

**Comment by wesm** [comment]
That would do it. Thanks for following up!
