### ISSUE TITLE
Arrow segfaults or leaks memory when working with Parquet files that have duplicate columns

### ISSUE THREAD

**Issue by ostrokach** [apache/arrow#1461]
I accidentally created a large number of Parquet files with two `__index_level_0__` columns (through a Spark SQL query).

PyArrow can read these files into tables, but it segfaults when converting the resulting tables to Pandas DataFrames or when saving the tables to Parquet files. 

```
# Duplicate columns cause segmentation faults
table = pq.read_table('/path/to/duplicate_column_file.parquet')
table.to_pandas()  # Segmentation fault
pq.write_table(table, '/some/output.parquet') # Segmentation fault
```

If I remove the duplicate column using `table.remove_column(...)` everything works without segfaults but there is a memory leak.

```
# After removing duplicate columns, everything works fine
table = pq.read_table('/path/to/duplicate_column_file.parquet')
table.remove_column(34)
table.to_pandas()  # OK
pq.write_table(table, '/some/output.parquet')  # OK
```

See the following repository for a concrete example of a segfault and a memory leak: https://gitlab.com/ostrokach/pyarrow_duplicate_column_errors.

---

Tested on conda versions `0.8.0-py36_0 conda-forge` and `0.8.0+25.nightly-py36_0 twosigma` with similar behaviour.

**Comment by ostrokach** [comment]
On second look, it seems the memory leak may not be caused by duplicate columns. I will investigate further tomorrow.

**Comment by wesm** [comment]
This will need to get converted into a JIRA for 0.9.0

**Comment by ostrokach** [comment]
I created two JIRA issues:
- https://issues.apache.org/jira/browse/ARROW-1973
- https://issues.apache.org/jira/browse/ARROW-1974

It appears that the memory leak occurs when calling `table.to_pandas()` for any Arrow table *with array columns*.

**Comment by wesm** [comment]
Thanks. Let's address these fixes on JIRA
