### ISSUE TITLE
pyarrow serialization takes more space

### ISSUE THREAD

**Issue by ppwwyyxx** [apache/arrow#1467]
```python
import pyarrow as pa
import msgpack
import pickle


def test_serialize(obj):
    print('-------------------------')
    print(len(pa.serialize(obj).to_buffer()))
    print(len(msgpack.dumps(obj)))
    print(len(pickle.dumps(obj)))


test_serialize(1)
test_serialize(list(range(1000)))
test_serialize(str(list(range(1000))))
```
Output:
```
-------------------------
524
1
5
-------------------------
13876
2619
2752
-------------------------
5428
4893
4900
```
Looks like it's very space-consuming for small primitive types? Is that intended or will there be improvements?

**Comment by wesm** [comment]
I can let @pcmoritz or @robertnishihara comment, but this isn't intended as a replacement for pickle or msgpack for very small objects, it's for serializing objects that contain relatively large pieces of data (like NumPy arrays, pandas DataFrames, etc.). We could probably make the representation a bit more compact

**Comment by robertnishihara** [comment]
You're right that it's pretty space inefficient for small objects. It's mostly optimized for large numerical data right now, but I suspect there's some room for improvement in the small object case.

**Comment by wesm** [comment]
Many of the internal buffers could be trimmed to 8-byte padding rather than 64-byte as I think it is now, would have to take a look

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2006. Patches welcome
