### ISSUE TITLE
[c++][parquet]bit-unpacking with AVX512_VBMI

### ISSUE THREAD

**Issue by yaqi-zhao** [apache/arrow#14672]
We do some optimization using AVX512_VBMI to accelerate bit-unpacking on Intel Icelake platform and get good performance. It's useful to acclearate parquet file reader. 
Do you think the work is valuable? If it's valuable, we prepare to submit PR to the Repo.

@kou  May I draw your attention to this question as you reviewed changes on bpacking just days ago.

Thank you!

**Comment by kou** [comment]
Yes.
#14674 is for this?

**Comment by yaqi-zhao** [comment]
> Yes. #14674 is for this?

Yes, #14674 is for this.

**Comment by kou** [comment]
Can we close this because we have ARROW-18362 for #14674?

**Comment by yaqi-zhao** [comment]
OK, i'll close it
