### ISSUE TITLE
TEST: Validating new issue templates.

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14692]
### Describe the usage question you have. Please include as many useful details as possible.

Creating this issue just to verify new issue template behavior for labeling.

### Component

Other

**Comment by toddfarmer** [comment]
It appears that since the `Type: usage` label is not established for this repo, it was not labeled as expected/hoped. This applies to all issue type labels driven by new issue templates, it seems. We need to get appropriate labels added ASAP.

**Comment by westonpace** [comment]
@toddfarmer This seems rather sparse.  Can we prompt them to provide the component (C++, Java, etc.)?

**Comment by toddfarmer** [comment]
@westonpace : The component is required and is represented as a drop-down in the issue template. Unfortunately, that doesn't automatically translate into labels, which also cannot be set manually by most users. There is further work to be done to populate labels based on the selected drop-down values (via GitHub actions).

**Comment by westonpace** [comment]
Ah, got it.  I see the component in the body of the message now.  Hmm, are we able to use the drop-down to adjust or suggest an issue title (e.g. [C++] Blah)?

**Comment by toddfarmer** [comment]
Unfortunately, any dynamic content based on form values requires GitHub actions. I've opened [ARROW-18377](https://issues.apache.org/jira/browse/ARROW-18377) to track the component aspect.
