### ISSUE TITLE
questions about cross-language streaming 

### ISSUE THREAD

**Issue by CodingCat** [apache/arrow#1469]
Hi, all

I am reading the doc at https://arrow.apache.org/docs/python/ipc.html

My question is, after the step of 

```python 
In [10]: buf = sink.get_result()
```

if I want to make a c++ framework read this buffer, what am I supposed to do ?

Is it the same approach applied to java-to-c++ communication?

Thanks in advance!

Best,

Nan

**Comment by wesm** [comment]
The `arrow::Buffer` that is wrapped by the Python object `buf` contains a complete Arrow stream as described in http://arrow.apache.org/docs/ipc.html. See the C++ API docs for reading streams, like `arrow::ipc::RecordBatchStreamReader`. Hope this helps
