### ISSUE TITLE
_plasma_store_entry_point in pyarrow/__init__.py

### ISSUE THREAD

**Issue by chevalierNoir** [apache/arrow#14693]
### Describe the bug, including details regarding any error messages, version, and platform.

NameError: name 'warnings' is not defined.

In [`_plasma_store_entry_point`](https://github.com/apache/arrow/blob/master/python/pyarrow/__init__.py#L355-L357) function, `warnings` should be changed to `_warnings`. 

### Component

Python

**Comment by AlenkaF** [comment]
True, thank you for reporting @chevalierNoir!
