### ISSUE TITLE
Upload version 10.0.1 on PyPI

### ISSUE THREAD

**Issue by petrpulc** [apache/arrow#14701]
### Describe the feature requested.

Could you please provide the version 10.0.1 with the updated SSL dependency to PyPI?

Thank you very much in advance.

### Component

Python

**Comment by raulcd** [comment]
Hi @petrpulc ,
Thanks for opening the issue. The 10.0.1 release is currently being voted / approved. Once this process is done and the release is official as a post-release tasks the pyarrow wheels will be uploaded to PyPI. You can follow this mail thread for the latest on the 10.0.1 release and the post-release tasks:
https://lists.apache.org/thread/rlkrj9lnfmwgn7kq8hvmzf06l5z6w30k

**Comment by kou** [comment]
Done.

**Comment by petrpulc** [comment]
Thank you very much for a swift solution ♥️
