### ISSUE TITLE
MIGRATION: Link to related pull requests

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14710]
See [this comment](https://github.com/apache/arrow/issues/14542#issuecomment-1319845797) - we should aim to retain links between PRs and migrated issues. This is most important for in-flight PRs, but may also be useful for PRs which have been closed.

**Comment by eitsupi** [comment]
It seems that GitHub issues migrated from JIRA have not been closed after the PRs referencing JIRA were merged.

**Comment by raulcd** [comment]
@eitsupi do you have an example? we just merged this PR that won't allow merging PRs referencing JIRA anymore and they will require updating the title to point to the corresponding GitHub issue. I have manually updated the only ticket I've seen that has been merged on the meantime but I might have missed others.

**Comment by raulcd** [comment]
And now with the link to the PR: https://github.com/apache/arrow/pull/33611

**Comment by eitsupi** [comment]
@raulcd Thanks, this one. #32694

**Comment by assignUser** [comment]
This is resolved/obsolete
