### ISSUE TITLE
MIGRATION: Retain good-first-issue labels

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14724]
As [suggested here](https://github.com/apache/arrow/issues/14542#issuecomment-1325684738), it would be useful to retain `good-first-issue` and `good-second-issue` labels when migrating issues from Jira to GitHub issues.

**Comment by rok** [comment]
"goog-first-issue" already exists and "good-second-issue" is being [discussed here](https://github.com/apache/arrow/issues/14593), so closing this.
