### ISSUE TITLE
pyarrow’s setup.py —cmake-extra-args needs shlex.split

### ISSUE THREAD

**Issue by leifwalsh** [apache/arrow#1474]
If not on windows, it doesn’t split the argument so passing multiple cmake arguments is broken. Can work around this for my use case by using environment variables instead of cmake -D args for now though. 

I’ll try to submit a PR soon, fix is pretty small.

**Comment by xhochy** [comment]
@leifwalsh I also run into this lately. The problem should be fixed in `setup.py` by 

```diff
 -            cmake_options.append('-DPYARROW_CXXFLAGS="{0}"'
 +            cmake_options.append('-DPYARROW_CXXFLAGS={0}'
```

No need to use `shlex.split`. The above code is part of https://github.com/apache/arrow/pull/1464/files but that probably won't be merged soon, so feel free to make a separate PR.

**Comment by leifwalsh** [comment]
Actually, I was talking about https://github.com/xhochy/arrow/blob/fcf46d9d947eb3a31c63be3e65118cd69cdd2976/python/setup.py#L177.  It assumes it's a single extra arg string, which the win32 branch does not (it uses `shlex.split` so you can pass multiple args through to cmake).  If you want to set, e.g. `-DCYTHON_EXECUTABLE` from outside setup.py, this seems to be the way, but if you want to pass multiple args, it doesn't.

**Comment by xhochy** [comment]
Ah, got it!

**Comment by wesm** [comment]
Can you open a JIRA?

**Comment by xhochy** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-2028 and will make a PR shortly.
