### ISSUE TITLE
[Python] Find and resolve unclosed socket ResourceWarnings

### ISSUE THREAD

**Issue by milesgranger** [apache/arrow#14760]
### Describe the enhancement requested

https://github.com/apache/arrow/pull/14729 Addresses test warnings, but there are seemingly harder-to-find `ResourceWarning`s for unclosed sockets:

> opt/conda/envs/arrow/lib/python3.7/site-packages/pyarrow/tests/parquet/test_dataset.py::test_read_partitioned_directory_s3fs_wrapper[False]
  /opt/conda/envs/arrow/lib/python3.7/site-packages/_pytest/fixtures.py:907: ResourceWarning: unclosed <socket.socket fd=256, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 37954), raddr=('127.0.0.1', 58351)>
    fixture_result = fixturefunc(**kwargs)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
  
  [Link to all warnings](https://github.com/apache/arrow/actions/runs/3568052561/jobs/5996480154#step:6:5754)

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
This is basically https://issues.apache.org/jira/browse/ARROW-17651?
