### ISSUE TITLE
Is it possible to write a parquet file with a bloom filter for a column 

### ISSUE THREAD

**Issue by reh183** [apache/arrow#14797]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi I looked all over for documentation and couldn't find any that suggested this was possible using pyarrow. is this possible? I am looking for something like this https://medium.com/@songkunjump/parquet-bloom-filter-with-spark-495a5f019c6c where specific columns can have a bloom filter associated with it and it's configurable. I know it's possible with the parquet format but I can't find any support within this library for that other than for ORC format. Thanks

### Component(s)

Parquet, Python

**Comment by mapleFU** [comment]
Hi reh, although `BloomFilter`'s code is introduced in Parquet, but currently, seems that there are no way to read / write parquet BloomFilter with C++ / pyarrow.

Maybe you can try parquet-mr or other tools for now

**Comment by reh183** [comment]
ok thanks @mapleFU I cannot use java for this project unfortunately.
