### ISSUE TITLE
[C++] CMake config files for Dataset are not copied to the install directory 

### ISSUE THREAD

**Issue by piotrwendykier** [apache/arrow#14801]
### Describe the bug, including details regarding any error messages, version, and platform.

I built Arrow 10.0.1 using:
```
vcpkg.exe install "arrow[core,csv,dataset,filesystem,json,parquet]" --triplet=x64-windows-static --x-install-root=%installDir% --recurse
```
I cannot link arrow_dataset.lib using documented CMake functions (find_package(ArrowDataset REQUIRED), target: ArrowDataset::arrow_dataset_static), because ArrowDatasetConfig.cmake and other configuration files for Dataset are not copied to the install directory. 
This issue was probably introduced in https://github.com/apache/arrow/pull/13892

### Component(s)

C++

**Comment by kou** [comment]
This is a problem of vcpkg's arrow port: https://github.com/microsoft/vcpkg/tree/master/ports/arrow

We need a change something like the following to install `ArrowDatasetConfig.cmake`:

```diff
diff --git a/ports/arrow/portfile.cmake b/ports/arrow/portfile.cmake
index 595049bfb..9f9249b99 100644
--- a/ports/arrow/portfile.cmake
+++ b/ports/arrow/portfile.cmake
@@ -72,6 +72,13 @@ if(EXISTS "${CURRENT_PACKAGES_DIR}/lib/arrow_static.lib")
     message(FATAL_ERROR "Installed lib file should be named 'arrow.lib' via patching the upstream build.")
 endif()
 
+if("dataset" IN_LIST FEATURES)
+    vcpkg_cmake_config_fixup(
+        PACKAGE_NAME arrowdataset
+        CONFIG_PATH lib/cmake/ArrowDataset
+        DO_NOT_DELETE_PARENT_CONFIG_PATH
+    )
+endif()
 if("parquet" IN_LIST FEATURES)
     vcpkg_cmake_config_fixup(
         PACKAGE_NAME parquet
```

Could you send a pull request to https://github.com/microsoft/vcpkg/ ?

**Comment by piotrwendykier** [comment]
You can close this as duplicate now.

**Comment by kou** [comment]
Thanks!
