### ISSUE TITLE
[Dev] Add created GitHub issues to issues@arrow.apache.org

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#14809]
### Describe the enhancement requested

There is an issues@arrow.apache.org mailing list: https://lists.apache.org/list.html?issues@arrow.apache.org
This list contains newly created issues.
At the moment new issues created on GitHub are not notified there, we should fix that.

### Component(s)

Developer Tools

**Comment by assignUser** [comment]
FYI there is also https://lists.apache.org/list.html?github@arrow.apache.org but that gets *everything*. I will add the open/close messages to issues@
