### ISSUE TITLE
[CI][Conda] Nightly CI jobs aren't maintained

### ISSUE THREAD

**Issue by kou** [apache/arrow#14828]
### Describe the bug, including details regarding any error messages, version, and platform.

Nightly CI jobs for Conda were fixed by @h-vetinari and @xhochy in GH-14102 but most nightly CI jobs are failing again this past month.

Can we maintain them? If we can't maintain them, can we remove them? Are they useful to maintain https://github.com/conda-forge/arrow-cpp-feedstock ?

http://crossbow.voltrondata.com/

Task Name | Since Last Successful Build | Last Successful Commit | Last Successful Build | First Failure | 9 Days Ago | 8 Days Ago | 7 Days Ago | 6 Days Ago | 5 Days Ago | 4 Days Ago | 3 Days Ago | 2 Days Ago | Most Recent Failure
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
conda-win-vs2019-py37-r40 | 78 days | 5e6da78 | pending | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-win-vs2019-py38 | 65 days | 60c9383 | pending | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py310-arm64 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py310-cpu | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py37-arm64 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py37-cpu-r40 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py37-cpu-r41 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py37-cuda | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py37-ppc64le | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py38-arm64 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py38-cpu | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py38-cuda | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py38-ppc64le | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py39-arm64 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py39-cpu | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py39-cuda | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py39-ppc64le | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-arm64-clang-py38 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-arm64-clang-py39 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-clang-py37-r40 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-clang-py37-r41 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-clang-py38 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-clang-py39 | 29 days | 8e3a1e1 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py310-cuda | 15 days | 501b799 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-linux-gcc-py310-ppc64le | 15 days | 501b799 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-arm64-clang-py310 | 15 days | 501b799 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail
conda-osx-clang-py310 | 15 days | 501b799 | pass | fail | fail | fail | fail | fail | fail | fail | fail | fail | fail

### Component(s)

Continuous Integration, Packaging

**Comment by h-vetinari** [comment]
I've been planning to update them as soon as https://github.com/conda-forge/arrow-cpp-feedstock/pull/875 is merged, but that PR took quite a while for various reasons (needs to cross-compile for aarch/ppc, which didn't work in conjunction with CUDA; there's a path to make this work but I'm not going to block the PR on that; also, bunch of tests failed and there were some segfaults, but I received essentially no response to many pings about what to do with them, so for now I'll ignore them).

After that update the CI should run fine IMO, and it should be easy to update after that as well. The test failures and segfaults I mentioned IMO make running things in CI here worthwhile, as another angle through which to stresstest the code (before the PR linked above, the conda-forge feedstock didn't run the test suite; now it does).

However I can't speak for the jobs that also include R. Haven't looked at those, so far only @xhochy did AFAIU.

**Comment by kou** [comment]
Thanks for sharing the current status.

Sorry for not replying to segfaults... I couldn't follow https://github.com/conda-forge/arrow-cpp-feedstock/pull/875 because it's too large for me.
If you find problems or have questions of Apache Arrow, how about creating an issue to apache/arrow for each problems/questions? It may bother you but it may be easier to resolve each problem/question.

**Comment by h-vetinari** [comment]
> If you find problems or have questions of Apache Arrow, how about creating an issue to apache/arrow for each problems/questions? It may bother you but it may be easier to resolve each problem/question.

It doesn't bother me at all. I didn't want to spam people with issues, and thought it would be easier to ask specific questions (e.g. about the LLVM usage), but if people prefer issues here that's not a problem for me.

**Comment by h-vetinari** [comment]
While preparing a PR, I just saw that https://github.com/apache/arrow/commit/a3ef64b9583c3a92fac73e74e9e03e5d22a6d8f6 broadly undid several necessary infrastructure changes in `tasks.yml` (looks like it might have been an inattentive merge conflict resolution that undid most of #1402's changes) - it's unsurprising that builds have been failing since, because they're pointing to non-existent configs.

CC @assignUser, please be more careful next time

**Comment by assignUser** [comment]
@h-vetinari Oh 😱 seems like I picked the wrong chunk and it slipped through the review. Sorry

**Comment by kou** [comment]
Oh, sorry. I missed these changes on merging...
