### ISSUE TITLE
MIGRATION: Update the documentation to include the new GitHub issue workflow

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#14822]
### Describe the enhancement requested

As we are moving towards GitHub issues for Arrow issue reports, the documentation needs to be updated so that the contributors have a place to look if they need the information about the workflow we are/will be having.

The issue will be divided into multiple subtasks (parts of the documentation) so that the review process will be easier:

- [x] https://github.com/apache/arrow/issues/14854
- [x] https://github.com/apache/arrow-site/issues/284
- [x] https://github.com/apache/arrow/issues/14885
- [x] https://github.com/apache/arrow/issues/14918
- [x] Version specific project docs warnings https://arrow.apache.org/docs/
  Tracked here: https://issues.apache.org/jira/browse/ARROW-18363
  https://github.com/apache/arrow-site/pull/275
  https://github.com/apache/arrow/pull/14839

### Component(s)

Documentation

**Comment by assignUser** [comment]
Anyone can now self-assign issues by commenting "take": https://github.com/apache/arrow/pull/14785
