### ISSUE TITLE
[Python] Import/usage of pyarrow results in 'Invalid machine command'

### ISSUE THREAD

**Issue by Qwertzi01** [apache/arrow#14835]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello and good morning, 

I get the error message 'Invalid machine command' if I try to use/import pyarrow v10 (also older versions).

* Operating system: Debian 11 (Bullseye)
* Kernel Version: `Linux 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`
* Python Version: 3.9.2

Console output after installing pyarrow with latest pip:
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Invalid machine command
```

Kernel log if I try to use Freqtrade which need pyarrow v10:

`Dec 3 17:01:08 server kernel: [617405.716600] traps: freqtrade[584823] trap invalid opcode ip:7f848859ae22 sp:7ffee55e2750 error:0 in libarrow.so.1000[7f84884a2000+189e000]`

If it helps, here the original issue regarding Freqtrade with Pyarrow: https://github.com/freqtrade/freqtrade/issues/7839

### Component(s)

Python

**Comment by Qwertzi01** [comment]
Ok, understood. What is the solution to use pyarrow
and libarrow.so without SSE4/POPCNT? 

A hardware upgrade because of a python module is not the goal.

**Comment by lidavidm** [comment]
If you build from source, you may be able to patch around anything required. https://arrow.apache.org/docs/dev/developers/guide/step_by_step/building.html#build-arrow-guide

**Comment by lidavidm** [comment]
Note that even if you can get Arrow itself to work, there may be dependencies that also require patching.

**Comment by lidavidm** [comment]
I'm going to close this, based on the previous issues. Patches would be welcome (feel free to reopen if so), but we don't have such an old machine in CI so there's no guarantees.
