### ISSUE TITLE
[Java] VectorValueComparator should skip the null test for NonNullable FieldTypes types

### ISSUE THREAD

**Issue by markjschreiber** [apache/arrow#14844]
### Describe the enhancement requested

I recently ran a profiler on a simple implementation of a sort and noticed that the VectorValueComparator spends quite a lot of time checking the values to be compared for `null` values. In this case I had already declared the `FieldType` to be `notNullable`. Unless I am misunderstanding something, the values cannot be `null` so the comparator is making unnecessary and expensive comparisons.

As a test I made a comparator that skips the null tests and runs ~12% faster as a result. Based on this I think the `VectorValueComparator` should skip the `nul`l test for NonNullable `FieldTypes`.

I'd be happy to contribute a change to do this if you think it would be reasonable.

### Component(s)

Java

**Comment by lidavidm** [comment]
IMO this would be reasonable. Additionally, I believe you can check for null or empty validity buffers and apply the optimization even if the type itself is not declared non-nullable. (At least, C++ doesn't allocate a validity buffer unless needed.)
