### ISSUE TITLE
[Docs] Color coding for warnings [Building documentation]

### ISSUE THREAD

**Issue by sayantikabanik** [apache/arrow#14840]
### Short description

While building the documentation, I noticed the warnings appearing on the console are color coded as `red` which I assumed as errors (was bit alarmed)

### Screenshot for reference 

<img width="1406" alt="Screenshot 2022-12-05 at 3 21 48 PM" src="https://user-images.githubusercontent.com/17350312/205615808-a5e5b757-f757-439b-9ef7-0c73693413d0.png">

### Expectation

Usually I have come across warnings as `yellow`/ `orangish` color printed on the console.
And errors highlighted or color coded as `red`.

### Component(s)

Documentation

**Comment by jorisvandenbossche** [comment]
This is behaviour of sphinx, not something we can control.

Ideally we should fix those warnings, though, so you also won't see any ..
