### ISSUE TITLE
pandas_compat. _reconstruct_block uses deprecated kwarg

### ISSUE THREAD

**Issue by jbrockmendel** [apache/arrow#1484]
https://github.com/apache/arrow/blob/234ff713dd9ecbcc2824d336b4e4f9d059a490dd/python/pyarrow/pandas_compat.py#L426

`pandas_compat. _reconstruct_block` calls `_int.make_block` with the kwarg `fastpath=True`.  We recently determined that `fastpath` is not actually _used_ anywhere within `make_block`, so are moving towards removing it (https://github.com/pandas-dev/pandas/pull/19265).  Ideally it would be removed downstream first so we don't cause any collateral damage.

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2003 about fixing this. A patch would be welcome
