### ISSUE TITLE
MIGRATION: Update project documentation to point to GitHub issues

### ISSUE THREAD

**Issue by toddfarmer** [apache/arrow#14861]
### Describe the enhancement requested

The Apache Arrow project documentation references Jira in number of places. These references should be updated to point to GitHub issues. Additionally, a best practices document should be started to establish emerging GitHub processes and policy.

### Component(s)

Documentation

**Comment by jorisvandenbossche** [comment]
@toddfarmer We already have https://github.com/apache/arrow/issues/14822, I think we can use that one as the general issue
