### ISSUE TITLE
[C++] Add `Append(std::optional<T>...)` convenience methods to builders

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#14863]
### Describe the enhancement requested

When you have a `std::optional` of the right value type, it would be convenient to append it directly to a concrete `ArrayBuilder` subclass instead of having to query whether it has a value:
```c++
template <typename V>
Status Append(const std::optional<V>& value) {
  return (value) ? Append(*value) : AppendNull();
}

template <typename V>
void UnsafeAppend(const std::optional<V>& value) {
  if (value) {
    UnsafeAppend(*value);
  } else {
    UnsafeAppendNull();
  }
}
```   

### Component(s)

C++

**Comment by yeshwantthota** [comment]
hey, I am new to open source, can I contribute to this issue?

**Comment by westonpace** [comment]
@yeshwantthota generally the answer would be yes but there appears to be a PR already for this issue (#24372) that is close to merging so I do not think this issue needs further help.

**Comment by pitrou** [comment]
@felipecrv Can you comment on this issue so that we can assign you?

**Comment by felipecrv** [comment]
take
