### ISSUE TITLE
[C++] arrow.pc should have -DARROW_STATIC for Windows static builds

### ISSUE THREAD

**Issue by lukester1975** [apache/arrow#14869]
### Describe the enhancement requested

Without, the generated pc file is insufficient (at least without "manually" defining ARROW_STATIC, which is unpleasant).

Quick hack fix: https://github.com/lukester1975/arrow/commit/2a8efd9c0bf69fe1b466e157bd69e83a757c926e

* Cflags.private is quite new (https://gitlab.freedesktop.org/pkg-config/pkg-config/-/merge_requests/13), so this approach might be unpalatable.
* pkgconfiglite is too old to include that (no commits since 2016??). It does quietly ignore the field, though.
* vcpkg does its own merging of Cflags.private into Cflags, so not an issue if pkg-config doesn't understand Cflags.private there (my case).
* Obviously this is applying to all platforms, not just Windows, but should do no harm...?

Seems like there should be some sort of fix here rather than asking vcpkg to patch it!

Regards

### Component(s)

C++

**Comment by kou** [comment]
Could you open a pull request with your approach?
pkgconf that is a drop-in replacement of pkg-config supports `Cflags.private`: http://pkgconf.org/features.html 
So we can use `Cflags.private` for it.

We also need similar change to all other `*.pc.in` too.

**Comment by lukester1975** [comment]
Sure, can do.

Are the other `pc.in`s required, though? They all `Requires: arrow` (directly or indirectly) so should inherit the flag from there.

**Comment by kou** [comment]
We have separated `_STATIC` macro for each modules. For example, we have `PARQUET_STATIC` for Parquet and `ARROW_DS_STATIC` for Arrow Dataset.
