### ISSUE TITLE
Best practices for handling larger than memory data

### ISSUE THREAD

**Issue by mattwarkentin** [apache/arrow#14880]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi,

I am wondering if someone from the Arrow team could offer some guidance on best practices for handling very large data in an optimal way (such as if partitioning is even the answer). The specific data is a TSV file that is 26Gb on disk and ~50Gb in-memory when read into R. The data frame is ~500K rows and ~14K columns. It is prohibitively slow/memory intensive to read the full data across each of several projects when, typically, only a small subset of the data (either subset of rows or columns) is relevant for any given project. 

However, the filtering conditions for which subset changes project to project, So I don't see an obvious column to use for grouping and partitioning. Does it ever make sense to randomly chunk/partition the data into smaller sets of 5000-10000 observations? My understanding was that much of the memory gain would occur if you chunked on a sensible variable (e.g., `year`) and then when you `filter()` a certain year, some of the data sets won't even be touched/loaded. Is there any way random chunking of observations offers any time/memory advantage?

Most commonly, most/all rows but only a very small set of columns are needed. I had hoped that something like the following would work, where `...` is just a small set of column names:
```r
ds <- arrow::open_dataset('data.tsv', format = 'tsv')
df <- ds |> dplyr::select(...) |> dplyr::collect()
```
But this is seemingly just as slow as loading the full table. I had thought only `...` columns would be read into memory so there would be a time savings. 

Anyway, any suggestions? Am I fundamentally misunderstanding how to handle larger-than-memory data with `arrow`?

### Component(s)

R

**Comment by pitrou** [comment]
I think you could try using Parquet rather than TSV (even as a single file). Parquet has much better access characteristics: you can freely load only a subset of the rows or columns.

**Comment by mattwarkentin** [comment]
So just save a copy of the file as parquet format and access using the approach shown in the above code?

**Comment by pitrou** [comment]
Using the same approach, yes, though I can't tell you how that would look like in R :-)
cc @thisisnic

**Comment by mattwarkentin** [comment]
Thanks. Do you have any comments on the question about random chunking of rows and whether that offers any benefit? Or does partitioning a dataset only offer benefits if the partitioning is based on a sensible column?

**Comment by assignUser** [comment]
@mattwarkentin yes! You will probably also be blown away by the new size on disk :D

**Comment by mattwarkentin** [comment]
Thanks for the advice. I will give it a shot.

**Comment by westonpace** [comment]
> Thanks. Do you have any comments on the question about random chunking of rows and whether that offers any benefit? Or does partitioning a dataset only offer benefits if the partitioning is based on a sensible column?

This will not modify the amount of memory used.

> But this is seemingly just as slow as loading the full table. I had thought only ... columns would be read into memory so there would be a time savings.

That should be the case.  I believe this was broken in r-arrow 9.  So if you are using version 9 you might try version 8 or 10.  We always read CSV data in blocks (usually 4MB) and we should drop the data you don't need after reading it in.  So even for CSV I would expect to see memory savings when using a select.  I'm afraid I don't know R enough to know why that didn't work.

That being said, parquet is always a good idea too :)

**Comment by mattwarkentin** [comment]
Thanks for your input.

I saved the file as a parquet and I am very impressed with the disk size. However, when I try to open this file as a dataset, I get the following error:
```r
ds <- open_dataset('data.parquet')
```
```
Error: IOError: Cannot list directory 'data.parquet'. Detail: [errno 20] Not a directory
```

**Comment by assignUser** [comment]
Yes. `open_dataset` expects a directory containing multiple files. For a single file `read_parquet` (see the [cookbook](https://arrow.apache.org/cookbook/r/reading-and-writing-data---single-files.html#write-a-parquet-file)) works.

Although looking at the [docs](https://arrow.apache.org/docs/r/reference/open_dataset.html) `open_dataset` should also work with a single file. @thisisnic any idea why this is? does it need a multi component file path to detect it as a single file or something like that?

**Comment by mattwarkentin** [comment]
I think I just had an outdated version of arrow on this machine. It seems to be working after an update. Thanks.
