### ISSUE TITLE
pyarrow 10.0.1 is missing libarrow_python.so

### ISSUE THREAD

**Issue by david-engelmann** [apache/arrow#14931]
### Describe the bug, including details regarding any error messages, version, and platform.

Builds with pyarrow as a dependency are not able to build with the most recent release of pyarrow.
The error states the following:
`.../libarrow_python.so needed by ..., missing and no know rule to make it`

If anyone knows how I can resolve this error so I can support pyarrow10, please let me know!

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Can you provide a bit more detail? Do you have a problem running pyarrow itself, or with another package depending on pyarrow? (assuming the second since I see your linked turbodbc PR) Is it when packaging another packge? How did you install pyarrow? etc

**Comment by david-engelmann** [comment]
I see that pyarrow is installed in the environment when I debug. pip list shows 

```
...
pyarrow            10.0.1
...
```
Unfortunately, this is for the turbodbc and the issue occurs during the Earthly CI flow which utilizes mamba to install pyarrow. The error occurs when trying to build turbodbc with the following command

` cmake -DBOOST_ROOT=\${CONDA_PREFIX} -DBUILD_COVERAGE=ON -DCMAKE_INSTALL_PREFIX=./dist  -DPYTHON_EXECUTABLE=\$(which python) -GNinja .. && ninja && cmake --build . --target install && cd dist && python setup.py sdist`

I'll include the relevant section of the build failed output below

```
 -- Found PkgConfig: /opt/conda/envs/turbodbc-dev/bin/pkg-config (found version "0.29.2")
              +build *failed* | -- Found /opt/conda/envs/turbodbc-dev/lib/libarrow.so in /opt/conda/envs/turbodbc-dev/lib
              +build *failed* | -- Found the Arrow core library: /opt/conda/envs/turbodbc-dev/lib/libarrow.so
              +build *failed* | -- Found the Arrow Python library: ARROW_PYTHON_LIB_PATH-NOTFOUND
              +build *failed* | -- Detecting unixODBC library
              +build *failed* | --   Found header files at: /opt/conda/envs/turbodbc-dev/include
              +build *failed* | --   Found library at: /opt/conda/envs/turbodbc-dev/lib/libodbc.so
              +build *failed* | CMake Warning (dev) at /opt/conda/envs/turbodbc-dev/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
              +build *failed* |   The package name passed to `find_package_handle_standard_args` (PkgConfig)
              +build *failed* |   does not match the name of the calling package (Arrow).  This can lead to
              +build *failed* |   problems in calling code that expects `find_package` result variables
              +build *failed* |   (e.g., `_FOUND`) to follow a certain pattern.
              +build *failed* | Call Stack (most recent call first):
              +build *failed* |   /opt/conda/envs/turbodbc-dev/share/cmake-3.25/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
              +build *failed* |   cmake_scripts/FindArrow.cmake:26 (include)
              +build *failed* |   cpp/turbodbc_arrow/CMakeLists.txt:12 (find_package)
              +build *failed* | This warning is for project developers.  Use -Wno-dev to suppress it.

              +build *failed* | -- Found /opt/conda/envs/turbodbc-dev/lib/libarrow.so in /opt/conda/envs/turbodbc-dev/lib
              +build *failed* | -- Found the Arrow core library: /opt/conda/envs/turbodbc-dev/lib/libarrow.so
              +build *failed* | -- Found the Arrow Python library: ARROW_PYTHON_LIB_PATH-NOTFOUND
              +build *failed* | -- Configuring done
```

**Comment by jorisvandenbossche** [comment]
@david-engelmann the way libarrow_python.so is package has changed in 10.0 (it is now part of the python package), so I assume that turbodbc will have to update their build scripts to follow that change.

**Comment by kou** [comment]
We need to use `pyarrow.get_include()`, `pyarrow.get_libraries()` and `pyarrow.get_library_dirs()` to find `libarrow_python`.
  
See also: https://arrow.apache.org/docs/python/integration/extending.html#c-api

**Comment by david-engelmann** [comment]
@kou I was able to find the ARROW_PYTHON_SHARED_LIB path but I can't find the ARROW_PYTHON_STATIC_LIB which is the libarrow_python.a.

**Comment by david-engelmann** [comment]
> We need to use `pyarrow.get_include()`, `pyarrow.get_libraries()` and `pyarrow.get_library_dirs()` to find `libarrow_python`.
> 
> See also: https://arrow.apache.org/docs/python/integration/extending.html#c-api

I added those to the setup.py file of turbodbc, you can [check it out here](https://github.com/blue-yonder/turbodbc/pull/369/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).

**Comment by kou** [comment]
I've commented on the pull request.
