### ISSUE TITLE
[Java] Remove Netty dependency from arrow-vector

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#14936]
### Describe the enhancement requested

#14913 removes a lot of uses of Netty from the core Arrow modules in favor of our own classes. If we could replace the remaining uses of Netty, we could drop the hard dependency on Netty entirely, so that it's only required if you use arrow-memory-netty or arrow-flight.

From https://github.com/apache/arrow/pull/14913#issuecomment-1348686193:
> `PlatformDependent` was used in `arrow-algorithm`, `arrow-jdbc`, `arrow-memory-netty`, `arrow-vector`. I've removed the usages in `arrow-algorithm`, `arrow-jdbc` and `arrow-vector`, and removed the dependency of `netty-common` in `arrow-algorithm` and `arrow-jdbc`. It would take a bit more job to remove dependency of `netty-common`  in `arrow-vector` as it is using some Netty collection utils llike `IntObjectMap`. Maybe do that in follow up.

### Component(s)

Java

**Comment by sudip-unb** [comment]
Interested to work on this issue.

**Comment by lidavidm** [comment]
@sudip-unb if you're interested, please feel free to file a PR; you can comment 'take' here to have the bot assign this issue to you as well

**Comment by jduo** [comment]
take

**Comment by jduo** [comment]
We probably don't want to re-implement IntObjectHashMap. Can we simply take the Netty implementation and add it to the Arrow project? It Netty has an Apache 2.0 license.

**Comment by lidavidm** [comment]
Vendoring is fine, yes (just update LICENSE to reflect that). Or we could possibly pull in Eclipse or Apache Commons equivalents if they exist.
