### ISSUE TITLE
[CI][Release] Source Release and Merge Script jobs are currently failing on GHA

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#14949]
### Describe the bug, including details regarding any error messages, version, and platform.

This has been raised on Zulip.
The jobs for `Source Release and Merge Script` are failing on several PRs and master. Example of failures:
- https://github.com/apache/arrow/actions/runs/3687535449
- https://github.com/apache/arrow/pull/14926
- https://github.com/apache/arrow/actions/runs/3693047779/jobs/6252584126

From what I understand the error seems to be around the following not being found (but I might be mistaken as the output is quite difficult to follow):
```
 -   :path=>"java/adapter/avro/pom.xml"},
-  {:hunks=>
-    [["-        <version>11.0.0-SNAPSHOT</version>",
-      "+        <version>12.0.0-SNAPSHOT</version>"]],
-   :path=>"java/adapter/jdbc/pom.xml"},
-  {:hunks=>
-    [["-        <version>11.0.0-SNAPSHOT</version>",
-      "+        <version>12.0.0-SNAPSHOT</version>"]],
-   :path=>"java/adapter/orc/pom.xml"},
-  {:hunks=>
-    [["-    <version>11.0.0-SNAPSHOT</version>",
-      "+    <version>12.0.0-SNAPSHOT</version>"]],
```
I can't find any change lately that might be the cause. The first commit on master that seems to fail due to this issue is unrelated: https://github.com/apache/arrow/commit/4647739e46fc1fffb5e89b28f3faee4500a8ef9e

### Component(s)

Continuous Integration

**Comment by raulcd** [comment]
I can't seem to reproduce locally:
```
(pyarrow-dev) ~/code/arrow  (master)  $ git pull upstream master
From github.com:apache/arrow
 * branch            master     -> FETCH_HEAD
Already up to date.
(pyarrow-dev) ~/code/arrow  (master)  $ ci/scripts/release_test.sh $(pwd)
+ arrow_dir=/home/raulcd/code/arrow
+ pushd /home/raulcd/code/arrow
~/code/arrow ~/code/arrow
+ dev/release/run-test.rb
Loaded suite release
Started
.........
Finished in 26.797402892 seconds.
---------------------------------------------------------------------------------------------------------------------------------------------------------------
9 tests, 9 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------------------------------------------------------------
0.34 tests/s, 0.34 assertions/s
+ popd
~/code/arrow
```

**Comment by raulcd** [comment]
I've checked and the GitHub runner seems to be exactly the same (no version updates) between a successful run:
https://github.com/apache/arrow/actions/runs/3692289538/jobs/6251037794
and a failure one:
https://github.com/apache/arrow/actions/runs/3693047779/jobs/6252584126

**Comment by raulcd** [comment]
@kou any idea what could be the issue?

**Comment by kou** [comment]
It seems that `mvn version:set` in `dev/release/utils-prepare.sh` doesn't update `java/adapter/*/pom.xml` but why...?

**Comment by kou** [comment]
I reran the succeeded build and it failed now: https://github.com/apache/arrow/actions/runs/3692289538/jobs/6264959209

It means that this is not related to our changes. It's related to CI environment.

**Comment by kou** [comment]
I think that https://github.com/mojohaus/versions/issues/848 is the problem.

**Comment by raulcd** [comment]
This seems to work now on my last PR the jobs were successful: https://github.com/apache/arrow/actions/runs/3706180881/jobs/6281060893
