### ISSUE TITLE
[C++][Parquet] Add benchmarks for DELTA_BINARY_PACKED

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#14951]
### Describe the enhancement requested

Now that we support the DELTA_BINARY_PACKED encoding for both reading and writing, we can add some benchmarks for it.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
Should it just follow `src/parquet/encoding_benchmark.cc`? I'd like to have a try.

**Comment by rok** [comment]
That seems like the right place @mapleFU. I think you can go ahead and open a PR! :)

**Comment by mapleFU** [comment]
By the way, should we generate the input using random? Seems that if we use a incremental number or fixed number, the data of `DELTA_BINARY_PACKED` should be well compressed and optimized, which is kind of unfair

**Comment by pitrou** [comment]
> By the way, should we generate the input using random? Seems that if we use a incremental number or fixed number, the data of `DELTA_BINARY_PACKED` should be well compressed and optimized, which is kind of unfair

Use random but with two different magnitudes (narrow or wide) such as to exercise both the easily compressible and poorly compressible cases.

**Comment by mapleFU** [comment]
By the way, I want to ask that what's the differences between `column_io_benchmark`, `column_reader_benchmark` and `encoding_benchmark`? And do we have some benchmark for `compress + encoding`? Because some encoding will not benifit a lot when encoding, but will greatly improve the performance or saving the space when compress and encoding, like byte_stream_split.

**Comment by pitrou** [comment]
> And do we have some benchmark for `compress + encoding`? Because some encoding will not benifit a lot when encoding, but will greatly improve the performance or saving the space when compress and encoding, like byte_stream_split.

I'm not convinced it's useful to add compression here. We're not writing the compression routines ourselves.

**Comment by mapleFU** [comment]
> I'm not convinced it's useful to add compression here. We're not writing the compression routines ourselves.

Yes, you're right. But I think if compression is not tested, maybe we will only have benchmark for partial of reading parquet. For example, some benchmark would be "the decoder is how much slower than PlainDecoder" when CPU prefetch works well.
