### ISSUE TITLE
[R] pkgdown built-in search doesn't work

### ISSUE THREAD

**Issue by eitsupi** [apache/arrow#14969]
### Describe the bug, including details regarding any error messages, version, and platform.

Built-in search does not seem working.

![image](https://user-images.githubusercontent.com/50911393/207886057-17172824-8517-4f45-8b25-fc0cc18ccff3.png)

### Component(s)

R, Website

**Comment by eitsupi** [comment]
If this cannot be fixed before the next release, it may be worth removing the search bar temporary.

**Comment by assignUser** [comment]
The search bar only shows up in the dev version, maybe we can make it work and activate it on the release version :D

**Comment by eitsupi** [comment]
According to my past experiments (#12541), I believe the search bar is not working because of https://github.com/apache/arrow/blob/3f31b327cd04e79e673b37ee684d438a72367483/r/pkgdown/extra.js.
The search bar may not work unless this file is modified.

**Comment by eitsupi** [comment]
Is there any need to disable this before the 11.0 release?
I believe that if nothing is done, a non-working search bar on the release version of the website.

**Comment by thisisnic** [comment]
Sorry @eitsupi, entirely missed your comments here.  This is something we should look into, and make a PR to the Arrow site to fix once it's done.  The CRAN release process has just started, so it may or may not be done in time for that.

**Comment by eitsupi** [comment]
Remarkably, I don't think this issue has been resolved yet.
Could you please reopen this issue?

**Comment by kou** [comment]
Ah, this issue focuses on search bar not version selector but #35103 focused on version selector, right?

**Comment by eitsupi** [comment]
Thank you for reopening this.

I too thought that #35103 would solve this, but in fact it didn't.
Is it because extera.js is still there?
https://github.com/apache/arrow/blob/c35a35d7c2e8699df6f90e8b9cc8ca1cfc5b7c88/r/pkgdown/extra.js

**Comment by kou** [comment]
Could you open a pull request to try the solution?

**Comment by eitsupi** [comment]
> Could you open a pull request to try the solution?

Sure.

I played around with it and it seemed to work correctly by deleting `extera.js`.
