### ISSUE TITLE
[Python] `write_dataset(table, format='orc')`: segfault

### ISSUE THREAD

**Issue by jgehrcke** [apache/arrow#14968]
I'm on CPython 3.10.8 on Linux on x86_64.

```
$ python
Python 3.10.8 (main, Nov 15 2022, 15:04:54) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> pyarrow.__version__
'10.0.1'
>>> import pyarrow.dataset
>>> t = pyarrow.table({"a": range(10)})
>>> pyarrow.dataset.write_dataset(t, format='orc', base_dir='/tmp')
Segmentation fault (core dumped)
```

If what I try to do shouldn't even work (e.g., if `write_dataset()` isn't supposed to be able to write ORC) then we probably want a nicer error message.

I tried searching existing GitHub issues for that, but didn't find anything applicable. Sorry if that's already tracked elsewhere.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Thanks for the report. It seems this is crashing when trying to create the file write options. For example in Python the following also segfaults:

```
import pyarrow.dataset
orc_format = pyarrow.dataset.OrcFileFormat()
orc_format.make_write_options()
```

Want to try to debug and fix this crash?

**Comment by jgehrcke** [comment]
> Want to try to debug and fix this crash?

Yes, I'd love to give this a shot!

**Comment by jgehrcke** [comment]
Understood the problem :).

Manual bisection has shown that this line is where things crash:

https://github.com/apache/arrow/blob/41b57d683ea73329af083540e6f67007bdd1d0c4/python/pyarrow/_dataset.pyx#L778

`sp.get()` above returns whatever `self.format.DefaultWriteOptions()` [here](https://github.com/apache/arrow/blob/41b57d683ea73329af083540e6f67007bdd1d0c4/python/pyarrow/_dataset.pyx#L890) returns.

And in case of the ORC file format that's 

```cpp 
std::shared_ptr<FileWriteOptions> OrcFileFormat::DefaultWriteOptions() {
  // TODO (https://issues.apache.org/jira/browse/ARROW-13796)
  return nullptr;
}
```

as defined in [cpp/src/arrow/dataset/file_orc.cc](https://github.com/apache/arrow/blob/41b57d683ea73329af083540e6f67007bdd1d0c4/cpp/src/arrow/dataset/file_orc.cc#L221).

Trying to invoke `type_name()` of `nullptr` explains the segfault.

Quote from JIRA ticket:

> https://github.com/apache/arrow/pull/10991 added basic support for ORC file format in the Datasets API, but didn't yet add support to write datasets to the ORC format.

https://arrow.apache.org/docs/python/dataset.html#dataset currently says:

> Currently, only Parquet, ORC, Feather / Arrow IPC, and CSV files are supported. 

That kind of suggests that ORC support is complete.

However, the [`write_dataset()` docs](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html#pyarrow.dataset.write_dataset) are explicit in the sense that ORC is _not_ documented as being supported:

>  Currently supported: “parquet”, “ipc”/”arrow”/”feather”, and “csv”.

**Comment by jgehrcke** [comment]
As a quick improvement: should we maybe raise a `NotImplementedError` or generally use some method to generate a user-friendly error message for the while being?

**Comment by westonpace** [comment]
> As a quick improvement: should we maybe raise a NotImplementedError or generally use some method to generate a user-friendly error message for the time being?

Yes please.  Perhaps we can test if `DefaultWriteOptions` returns `nullptr` to decide if a format supports writing (and document this in the `DefaultWriteOptions` comment docs).
