### ISSUE TITLE
[JS] Using tableFromIPC().toString() results in invalid stringified JSON when containing dates

### ISSUE THREAD

**Issue by arteconceito** [apache/arrow#14973]
For reference, let's use the following code sample where we have a single row table:
```javascript
const tableAsArray = tableFromIPC(someSource).toArray();

console.log(tableAsArray);
// [{ id: 'foo', name: 'bar', dob: Fri Dec 15 2000 12:00:00 GMT+0100 (Central European Standard Time) }]
```
Considering the `dob` property above is a date object, this should be the JSON string:
```javascript
const tableAsString = tableFromIPC(someSource).toString();

console.log(tableAsString);
// '[{"id":"foo","name":"bar","dob":"2000-12-15T11:00:00.000Z"}]'
```
Unfortunately, that's not what happens. Instead this is how the string looks like:
```javascript
const tableAsString = tableFromIPC(someSource).toString();

console.log(tableAsString);
// '[{"id":"foo","name":"bar","dob":Fri Dec 15 2000 12:00:00 GMT+0100 (Central European Standard Time)}]'
```
Note that not only the date has not been converted to JSON (`dateObject.toJSON()`) but also, it is an unquoted string. This is of course a problem as one cannot parse back this string to JSON as the parser will throw an exception.

### Component(s)

JavaScript

**Comment by arteconceito** [comment]
Hi @AlenkaF
As you can see above I've already created a PR #14984 to address this issue that I myself reported.
How can I have a maintainer on board to review it?

**Comment by AlenkaF** [comment]
Great @arteconceito, thank you for reporting and contributing!
I will look at the PR and request a review from a developer working on this part of the codebase.

**Comment by domoritz** [comment]
I don't think I agree that this is a bug. `toString` should return a human-readable representation for debugging more than a JSON-readable representation. That's what `toJSON` is for. We should make sure `toJSON` works correctly, though.

**Comment by arteconceito** [comment]
Following the current implementation, the `.toString()` methods actually behaves as the `.toJSON()` an that's why it to me classifies as a bug. In any case I do agree with you @domoritz, as I already wrote [here](https://github.com/apache/arrow/pull/14984#issuecomment-1363097976).

Question: should I refactor those `.toJSON()` methods to actually behave as expected (cc @trxcllnt)?
Actually if we do that, then those `.toString()` could use `.toJSON()` to generate the string output.

**Comment by domoritz** [comment]
I am not fully following the proposal. `toString` can produce strings that are not JSON and I think that's okay. This looks good to me actually

```js
const tableAsArray = tableFromIPC(someSource).toArray();

console.log(tableAsArray);
// [{ id: 'foo', name: 'bar', dob: Fri Dec 15 2000 12:00:00 GMT+0100 (Central European Standard Time) }]
```

But it would probably make sense to make it consistent with 

```js
const tableAsString = tableFromIPC(someSource).toString();

console.log(tableAsString);
// '[{"id":"foo","name":"bar","dob":Fri Dec 15 2000 12:00:00 GMT+0100 (Central European Standard Time)}]'
```

`toJSON` has the challenge that we use it to produce js objects rather than actual JSON strings (for performance reasons and we can consider alternatives). But we should expect `JSON.stringify(X.toJSON())` to work and if it doesn't I would consider that a bug.

**Comment by arteconceito** [comment]
Before the conversation goes into a different path other that the main point of why this issue was raised, let me add a bit of context to why I opened this issue as a bug.

As in the example I gave on [my OP above](https://github.com/apache/arrow/issues/14973#issue-1498642827), the output of `table.toString()` is too similar to a JSON string. Similar enough to induce one to take it as a "helper" method for getting the actual table as a serialised JSON string.

This is exactly what happened with two other devs on my team that authored the code I was assigned to fix. Once we started having dates on those tables, the app broke as I then figured why. It was exactly due to the fact that `.toString()` was used to get the table as JSON and because the `.toString()` method does not quote the date strings (as also mentioned in my original OP).

So, as per the [MDN's definition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString) of `Object.prototype.toString()`, the `.toString()` should not only be used to return a string representation but is also meant to be overridden for custom type conversion. Below is an example of a "native" string representation (yes, it's not that helpful),
```javascript
const arrayOfObjects = [{ name: 'John', dob: new Date() }, { name: 'Jane', dob: new Date() }];

console.log(arrayOfObjects);
// "[object Object],[object Object]"
```

Compared to this, the current `Table.toString()` implementation does a good job already and is actually following the "meant to be overridden for custom type conversion" part of the recommendation. I only meant to "adjust" it in a way that it would be backwards compatible, continue being human readable while also being JSON parseable as a nice addition.

Regarding the part where you write...
> `toJSON` has the challenge that we use it to produce js objects rather than actual JSON strings

... I get it that's how you intended it to be in the first place but it for sure, at least to me, makes one think it will return a JSON string, as its name suggests, and also because JSON on its most basic definition is a string. I know introducing changes here would be a breaking change but just in case, my suggestion would be `.valueOf()` following [MDN's definition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf) on `Object.prototype.valueOf()`.

Anyway... going back to the basics.
The current `Table.toString()` already returns a JSON parseable string, why not also support `Date()` values ?

**Comment by domoritz** [comment]
Thanks. I appreciate the deep dive. 

> The current `Table.toString()` already returns a JSON parseable string, why not also support `Date()` values ?

I think because we don't want `toString` to be relied on as serialization format. If we create the impression that it works, we will get subtle issues (as you encountered). Maybe we should remove the key quoting and use `'` instead of `"` so it looks like the first example from your OP.

**Comment by arteconceito** [comment]
Then this issue can be be closed and I will abandon de PR as well.
Thx anyway for discussing this 👍 .

**Comment by domoritz** [comment]
I think you brought up a good point how 

```
const tableAsString = tableFromIPC(someSource).toString();

console.log(tableAsString);
// '[{"id":"foo","name":"bar","dob":Fri Dec 15 2000 12:00:00 GMT+0100 (Central European Standard Time)}]'
```

should look more like

```
const tableAsArray = tableFromIPC(someSource).toArray();

console.log(tableAsArray);
// [{ id: 'foo', name: 'bar', dob: Fri Dec 15 2000 12:00:00 GMT+0100 (Central European Standard Time) }]
```

to avoid the confusion your team member ran into. What do you think about making that change?

**Comment by trxcllnt** [comment]
`toString()` and `toJSON()` are actually really subtle. JS will invoke an instance's `toString()` method when implicitly converting a type to a string representation, and will use `toJSON()` when running through `JSON.stringify()`.

I know `toJSON()` sounds like it should return a string, but according to [the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) `toJSON()` should return the value to be serialized, not a string:
> If the value has a `toJSON()` method, it's responsible to define what data will be serialized. Instead of the object being serialized, the value returned by the `toJSON()` method when called will be serialized.

For example:
```shell
# Implicitly converting an Array to a string:
> `${[new Date(), 5, {}, {foo:1, bar: 'baz'}]}`
'Thu Dec 22 2022 19:02:07 GMT-0800 (Pacific Standard Time),5,[object Object],[object Object]'

# Stringify'ing JSON
> JSON.stringify([new Date(), 5, {}, {foo:1, bar: 'baz'}])
'["2022-12-23T03:00:46.440Z",5,{},{"foo":1,"bar":"baz"}]'
```

We can override this via custom `toString()` and `toJSON()` implementations:
```shell
> `${[new Date(), 5, {}, {foo:1, bar: 'baz', __proto__: {toString() { return JSON.stringify(this); }}}]}`
'Thu Dec 22 2022 19:00:16 GMT-0800 (Pacific Standard Time),5,[object Object],{"foo":1,"bar":"baz"}'

> JSON.stringify([new Date(), 5, {}, {foo:1, bar: 'baz', __proto__: {toJSON() { return {foo: this.foo}; }}}])
'["2022-12-23T03:01:35.003Z",5,{},{"foo":1}]'
```

The implementations we provide in Arrow are intended to follow these semantics. If you want stringified JSON, why not add a `Table.toJSON()` method that returns an Array, then call `JSON.stringify(table.toJSON())`?

**Comment by arteconceito** [comment]
Thanks for the well supported clarification @trxcllnt.
In any case, for our use case we are all set. Using `JSON.stringify(table.toArray())` also works fine because then `JSON.stringify()`will use the `Vector.toJSON()` method for the serialisation.

**Comment by arteconceito** [comment]
Closing as this turns out not to a bug. Just wrong assumptions taken towards the `Table.toString()` method.
