### ISSUE TITLE
Broken Backwards compatibility around bytes_view

### ISSUE THREAD

**Issue by david-engelmann** [apache/arrow#14983]
### Describe the bug, including details regarding any error messages, version, and platform.

Here is the full command that failed with all the included directories

```
/opt/conda/envs/turbodbc-dev/bin/x86_64-conda-linux-gnu-c++ -Dturbodbc_arrow_support_EXPORTS -I/src/cpp/turbodbc_arrow/Library -I/src/cpp/turbodbc_arrow/../cpp_odbc/Library -I/src/cpp/turbodbc_arrow/../turbodbc/Library -isystem /opt/conda/envs/turbodbc-dev/include/python3.8 -isystem /opt/conda/envs/turbodbc-dev/lib/python3.8/site-packages/numpy/core/include -isystem /opt/conda/envs/turbodbc-dev/lib/python3.8/site-packages/pyarrow/include -isystem /src/pybind11/include -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/turbodbc-dev/include -Wall -Wextra -g -O0 -pedantic -fprofile-arcs -ftest-coverage -fPIC -fvisibility=hidden   -std=c++11 -MD -MT cpp/turbodbc_arrow/Library/CMakeFiles/turbodbc_arrow_support.dir/src/python_bindings.cpp.o -MF cpp/turbodbc_arrow/Library/CMakeFiles/turbodbc_arrow_support.dir/src/python_bindings.cpp.o.d -o cpp/turbodbc_arrow/Library/CMakeFiles/turbodbc_arrow_support.dir/src/python_bindings.cpp.o -c /src/cpp/turbodbc_arrow/Library/src/python_bindings.cpp
```

```
/opt/conda/envs/turbodbc-dev/include/arrow/util/bytes_view.h:26:25: error: 'basic_string_view' in namespace 'std' does not name a template type
using bytes_view = std::basic_string_view<uint8_t>;
```
It also states that this is only defined for C++17 and on. Currently, the turbodbc build with pyarrow10 version is failing because of this. The default build behavior of turbodbc uses the following commands `add_definitions("-std=c++11")` and `extra_compile_args.append("--std=c++11")`

I believe this is the final blocker for bumping turbodbc requirements to greater than 9.

### Component(s)

Python

**Comment by raulcd** [comment]
Arrow 10.0.0 bumped to C++ 17, see: https://github.com/apache/arrow/pull/13991
I think turbodbc will have to upgrade accordingly.

**Comment by david-engelmann** [comment]
I'm testing with C++17 now, the build is successful, test are currently running

**Comment by raulcd** [comment]
Also, in case you are interested I sent this email today to the dev mailing list around removing some integration tests around turbodbc because they have been commented for 8 months now: https://lists.apache.org/thread/nqbbrnsdf86j0lj4j1rhbyxgs5o33p5w 
Just sharing in case you want to answer as I haven't seen many other people working on turbodbc lately.

**Comment by david-engelmann** [comment]
Are you removing Arrow test around turbodbc nightly, or Turbodbc test around Arrow Nightly. The Turbodbc test around Arrow Nightly should working going forward. I was able to confirm bumping to C++17 was the only remaining issue

**Comment by raulcd** [comment]
There are two nightly jobs that have been commented for 8 months and would be cleaned up:
- Arrow master with turbodbc master
- Arrow master with latest tag of turbodbc (right now 4.5.5)

**Comment by david-engelmann** [comment]
I see no reason why Arrow would need to keep those test, specially if they've been commented out for 8 months with no issue. Turbodbc will keep the test with arrow nightly. [I'm going to close this issue out because the bump to c++17 resolved the issue](https://github.com/david-engelmann/turbodbc/actions/runs/3707120555/jobs/6283157374).
