### ISSUE TITLE
[Go] flightsql.SqlInfoSupportedUnions has incorrect value

### ISSUE THREAD

**Issue by mhilton** [apache/arrow#14995]
### Describe the bug, including details regarding any error messages, version, and platform.

The constant for [`flightsql.SqlInfoSupportedUnions`](https://github.com/apache/arrow/blob/master/go/arrow/flight/flightsql/types.go#L462) is taken from [`pb.SqlSupportedUnions_SQL_UNION`](https://github.com/apache/arrow/blob/master/go/arrow/flight/internal/flight/FlightSql.pb.go#L1242), which has the value 0. I believe this should be using [`pb.SqlInfo_SQL_SUPPORTED_UNIONS`](https://github.com/apache/arrow/blob/master/go/arrow/flight/internal/flight/FlightSql.pb.go#L373), which has the value 540.

### Component(s)

Go

**Comment by zeroshade** [comment]
@mhilton good catch! thanks! Incoming PR for this
