### ISSUE TITLE
[CI][Conda] conda-linux-aarch64-* are failing

### ISSUE THREAD

**Issue by kou** [apache/arrow#14993]
### Describe the bug, including details regarding any error messages, version, and platform.

https://lists.apache.org/thread/3rqsxwv9oxwwlqr8lfjr9kvpn835ot1g

For example: conda-linux-aarch64-cpu-py3:

https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=41199&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=442

```text
+++ mamba create -n sysroot_linux-aarch64 --yes --quiet sysroot_linux-aarch64
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
/opt/conda/bin/cross_compile_support.sh: line 18: RECIPE_ROOT: unbound variable
```

Cc: @h-vetinari 

### Component(s)

Packaging

**Comment by h-vetinari** [comment]
Should be fixed by #15014
