### ISSUE TITLE
BUG: plasma tests failing in conda builds on linux

### ISSUE THREAD

**Issue by h-vetinari** [apache/arrow#15015]
### Describe the bug, including details regarding any error messages, version, and platform.

#14832 switched on the test suite within the conda-builds, which itself synced with https://github.com/conda-forge/arrow-cpp-feedstock/pull/875

In the process of doing so, currently all tests starting with `test_plasma` in their name were skipped,
https://github.com/apache/arrow/blob/2c768a1767c0d7b33644910e0e96a949bc6f6f42/dev/tasks/conda-recipes/arrow-cpp/meta.yaml#L377-L379

This only fails on linux, not on osx (windows doesn't have plasma). Additionally, it seems that there are two binaries for `plasma-store-server` being [installed](https://github.com/conda-forge/arrow-cpp-feedstock/pull/875#issuecomment-1325951190), one in `$PREFIX/bin` and one in `$PREFIX/lib/python3.x/site-packages/pyarrow/`. I'm pretty sure this is a left-over from making `libarrow` python-independent?

To fix this, the line quoted above should be removed, and the conda-linux tests still pass. Ideally, there should only be one `plasma-store-server` binary being installed.

### Component(s)

C++ - Plasma

**Comment by kou** [comment]
> I'm pretty sure this is a left-over from making libarrow python-independent?

This is not related. `$PREFIX/lib/python3.x/site-packages/pyarrow/plasma-store-server` is for users who don't have system Apache Arrow C++. (For example, pyarrow wheel users.)

We can stop installing `$PREFIX/lib/python3.x/site-packages/pyarrow/plasma-store-server` by the following:

```diff
diff --git a/dev/tasks/conda-recipes/arrow-cpp/build-pyarrow.sh b/dev/tasks/conda-recipes/arrow-cpp/build-pyarrow.sh
old mode 100644
new mode 100755
index 692ffb7806..98c0fa9181
--- a/dev/tasks/conda-recipes/arrow-cpp/build-pyarrow.sh
+++ b/dev/tasks/conda-recipes/arrow-cpp/build-pyarrow.sh
@@ -9,6 +9,7 @@ export PARQUET_HOME=$PREFIX
 export SETUPTOOLS_SCM_PRETEND_VERSION=$PKG_VERSION
 export PYARROW_BUILD_TYPE=release
 export PYARROW_BUNDLE_ARROW_CPP_HEADERS=0
+export PYARROW_BUNDLE_PLASMA_EXECUTABLE=0
 export PYARROW_WITH_DATASET=1
 export PYARROW_WITH_FLIGHT=1
 export PYARROW_WITH_GANDIVA=1
```

See also:
* https://github.com/apache/arrow/blob/apache-arrow-10.0.1/python/setup.py#L202-L203
* https://github.com/apache/arrow/blob/apache-arrow-10.0.1/python/setup.py#L495-L501

**Comment by h-vetinari** [comment]
Since plasma got removed, I'm closing this issue.
