### ISSUE TITLE
[Python] [Docs] Change docstring for `decompressed_size` arg in pyarrow.decompress to reflect implementation

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#15043]
### Describe the bug, including details regarding any error messages, version, and platform.

The docstring for `decompressed_size` in `pyarrow.decompress` and the underlying `Codec.decompress` states:

> decompressed_size : int, default None
>     If not specified, will be computed if the codec is able to determine the uncompressed buffer size. 

However, you can see from the implementation that the behavior isn't possibly and that the argument is effectively required because we always raise when it's `None`:

https://github.com/apache/arrow/blob/4e9158d373df105f01ba9d6052cfb9ab7ecdcbeb/python/pyarrow/io.pxi#L2091-L2124

For example,

```python
import pyarrow as pa

pa.decompress(pa.compress(bytes('mydata','utf-8')))
```

Raises:

> ValueError: Must pass decompressed_size for <pyarrow.Codec name=lz4 compression_level=1> codec

I think the [original intent](https://github.com/apache/arrow/pull/1345) was to support detecting or estimating the size of the output buffer for codecs that support it (like Snappy) but, the last time [this was brought up](https://issues.apache.org/jira/browse/ARROW-3877), it was marked as low priority and remains unimplemented.

Should the argument be made required and the bit about "If not specified" be removed?

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Yes, I think we should certainly update the docs to match the current behaviour (which is indeed to always require the `decompressed_size`)
