### ISSUE TITLE
[R][CI] Arrow nightly binaries require aws sdk system dependency

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#15040]
### Describe the bug, including details regarding any error messages, version, and platform.

It seems that https://github.com/apache/arrow/pull/14235 introduced aws-sdk as a system dependency for the ubuntu libarrow binaries created by the R nightlies. @raulcd detected the issue while working on the cookbook: https://github.com/apache/arrow/pull/14235#issuecomment-1357539110 . 

We confirmed that it is loading the nighly binary and not building from source https://github.com/raulcd/arrow-cookbook/actions/runs/3733167177/jobs/6333699829#step:6:2572.  Changing the scripts and workflows to use bundled dependencies in any case should fix the issue.

### Component(s)

Continuous Integration, R

**Comment by kou** [comment]
It seems that we can fix this by removing `--static` from `pkg-config` command line.
I dug why we use `--static`. I suggested it...:  https://github.com/apache/arrow/pull/10404#issuecomment-871034191
(Oh, I didn't remember...)
I reconsider the `--static` approach.
