### ISSUE TITLE
[JS] Missing support for LargeUtf8 datatype

### ISSUE THREAD

**Issue by ddemaeyer** [apache/arrow#15060]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently there is no support for the large_string or largeutf8 datatype in the javascript libraries.

### Component(s)

JavaScript

**Comment by universalmind303** [comment]
+1 to this, https://github.com/pola-rs/nodejs-polars uses LargeUtf8 & is currently incompatible with arrow-js due to the lack of LarguUtf8

**Comment by kylebarron** [comment]
It would be nice to see this, though in [`arrow-js-ffi`](https://github.com/kylebarron/arrow-js-ffi) I currently have a workaround where I [downcast offsets](https://github.com/kylebarron/arrow-js-ffi/blob/951faaf34e126a3bcd0cfa5423862014d657d1fa/src/vector.ts#L251-L256) from Int64 to Int32 in the case of Large data types.

**Comment by domoritz** [comment]
Yes. Unfortunately we need to rewrite a bunch of the buffers to support arrays of larger than 32 bit value length since js arrays can't be that long. I'll need some time to get to this but it's on my queue.

**Comment by dvirtz** [comment]
When will this fix be released?

**Comment by domoritz** [comment]
Arrow releases are aligned with other packages every three months.

**Comment by kou** [comment]
FYI: [INFO] Preparation for Arrow 15.0.0 https://lists.apache.org/thread/4mwnwm3wkdkocj38fnwjt2rwzwcckwrp
