### ISSUE TITLE
[Python][CI] Dask nightly tests are failing due to fsspec bug

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#15064]
### Describe the bug, including details regarding any error messages, version, and platform.

Nightly crossbow tests against dask are failing because of https://github.com/fsspec/filesystem_spec/pull/1139  (eg https://github.com/ursacomputing/crossbow/actions/runs/3717553395/jobs/6305023522)

### Component(s)

Continuous Integration, Python

**Comment by jorisvandenbossche** [comment]
Keeping this open to remind myself to remove the skip once fsspec is released.

**Comment by raulcd** [comment]
@jorisvandenbossche should we close this and open a new issue? I am trying to close issues that are milestoned with 11.0.0 in preparation for the release.

**Comment by jorisvandenbossche** [comment]
Sorry for forgetting to reply here. Is the reason you wanted to have this issue closed for including it in the release notes? We could also just have removed the milestone here, or change it to 12.0.

**Comment by raulcd** [comment]
> We could also just have removed the milestone here, or change it to 12.0.

Yes, that would have worked too. I decided to create a new issue just to track the left over work and close this one, I hope that's ok.

**Comment by jorisvandenbossche** [comment]
Yes, that's certainly OK. I just generally try to avoid creating new issues if we can reuse an existing one (but that's very much a personal preference ;))
