### ISSUE TITLE
[Ruby] Add a method to return column names in Arrow::Table

### ISSUE THREAD

**Issue by heronshoes** [apache/arrow#15085]
#### Target method

Arrow::Table#keys or #names (tentative)

#### Proposed feature

Return an Array `columns(&name)`.

#### Impact of this request

It will be useful in enhancements of #join .

#### Reference of this request

I am testing this feature in RedAmber by refinements.

https://github.com/heronshoes/red_amber/blob/main/lib/red_amber/refinements.rb#L144-L146

### Component(s)

Ruby

**Comment by kou** [comment]
How about `Arrow::Table#column_names`?

**Comment by heronshoes** [comment]
I agree. 'Key' is the word for join or group, 'name' is ambiguous. Thanks.
I will try to implement `Arrow::Table#column_names`.
