### ISSUE TITLE
[C++] Could not decompress arrow stream sent from Java arrow SDK

### ISSUE THREAD

**Issue by lanmao-alibaba** [apache/arrow#15102]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi guys,
I am using arrow java sdk to send  lz4/zstd stream to a server which is running c++ arrow sdk, but the c++ arrow report a failure: "Negative buffer resize: -1"

After some investigation, I found that Java compress process is not compatible with C++.
In Java, the class AbstractCompressionCodec has one optimization, if the buffer size after compression is larger than the uncompressed buffer, AbstractCompressionCodec::compress() will attach the uncompressed buffer directly and mark the buffer size with "-1".
But in C++, reader.cc::DecompressBuffer() does not check buffer size with "-1". It allocates the buffer directly and so the error "Negative buffer resize: -1" is thrown.

### Component(s)

C++, Java

**Comment by pitrou** [comment]
cc @lidavidm @lwhite1

**Comment by lidavidm** [comment]
Java is following the spec here, I believe:

https://github.com/apache/arrow/blob/master/format/Message.fbs#L59-L65

**Comment by pitrou** [comment]
@benibus Would you like to take a look at this sometimes before the 11.0 release?

**Comment by benibus** [comment]
@pitrou Yeah, I'll check it out.

**Comment by raulcd** [comment]
I am going to remove the milestone in preparation for the release. Please if this is a blocker add the `Priority: Blocker` label.
