### ISSUE TITLE
Question: Can arrow be used to load a parquet file from an Azure blob store?

### ISSUE THREAD

**Issue by rjrussell77** [apache/arrow#1510]
I'm researching the functionality of opening a parquet file stored in an Azure blob store from a Jupyter notebook using a Python 3 kernel.

Specifically, I do **not** want a PySpark kernel.  I can already do that using the following code:
`salesData = spark.read.parquet("wasbs://product-abc-data@myproduct.blob.core.windows.net/part-r-....gz.parquet")`

The question is, can arrow be used to somehow connect to a blob store from pure python code:
`import pandas as pd`
`pd.read_parquet('wasbs://product-abc-data@myproduct.blob.core.windows.net/part-r-blah-gz.parquet'`
Results in:
`ArrowIOError                              Traceback (most recent call last)
...
...
...
ArrowIOError: Failed to open local file: wasbs://product-abc-data@myproduct.blob.core.windows.net/part-r-blah-gz.parquet , error: No such file or directory`

**Comment by xhochy** [comment]
You can use `storefact` for this: https://storefact.readthedocs.io/en/latest/readme.html

```python
from storefact import get_store

params = {
    'account_name': 'test',
    'account_key': 'XXXsome_azure_account_keyXXX',
    'container': 'my-azure-container',
}
store = get_store('azure', **params)

reader = pa.BufferReader(store.open(key))
table = pq.read_table(reader, columns=columns).to_pandas()
``` 

The nice thing is that you can either supply `columns=None` and it will read the whole file or `columns=['some col', ..]` and it will load only the parts of the Parquet file from Azure Storage Blob that are relevant for the specified columns.

**Comment by wesm** [comment]
I also opened https://issues.apache.org/jira/browse/ARROW-2034. It would be great to have performant native implementations for S3, GCS, and ABS

**Comment by rrussell39** [comment]
@wesm @xhochy Awesome!  Thanks so much for the input.  Can't wait to try it.

**Comment by rrussell39** [comment]
@xhocy - Ok thanks for the tip.  I'm part way there.
I've added a Container called, "test-container-2018-01-25" under BLOB SERVICE in the Azure portal.
I've uploaded a test parquet file to this container called, "userdata1.parquet".
I then use the following code:
`from storefact import get_store

import pyarrow as pa
import pyarrow.parquet as pq

params = {
    'account_name': 'account_name',
    'account_key': 'key-info-here',
    'container': 'test-container-2018-01-25',
}
store = get_store('azure', create_if_missing=False, **params)
key = 'userdata1.parquet'
reader = pa.BufferReader(store.open(key))
table = pq.read_table(reader, columns=columns).to_pandas()`

Result:
`TypeError                                 Traceback (most recent call last)
io.pxi in pyarrow.lib.frombuffer()

TypeError: memoryview: a bytes-like object is required, not 'IOInterface'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-cdad1a9cee1d> in <module>()
     11 store = get_store('azure', create_if_missing=False, **params)
     12 key = 'userdata1.parquet'
---> 13 reader = pa.BufferReader(store.open(key))
     14 table = pq.read_table(reader, columns=columns).to_pandas()

io.pxi in pyarrow.lib.BufferReader.__cinit__()

io.pxi in pyarrow.lib.frombuffer()

ValueError: Must pass object that implements buffer protocol`

My main question at this point is this: what is the proper value of the 'key' parameter above?  Other than that, how do things look?
Things I've tried:
I mangled my account_key to see if there was a different error and there was so I'm sure my credentials are working.
I also tried calling get_store() without create_if_missing=False and that resulted in an error explaining that 'test-container-2018-01-25' already exists which is puzzling.  Not sure why it was telling me that unless it were trying some write operation.  Thanks for any guidance.

Rob

**Comment by rrussell39** [comment]
Just for clarity this recommended code above:
`reader = pa.BufferReader(store.open(key))` throws an error related to the `the container already exists`
In particular `store.open()` is seemingly NOT a read-only operation

**Comment by xhochy** [comment]
@rrussell39 I can investigate further on Monday what the problem with `open` is. Meanwhile you should be able to use `store.get(key)`. This will retrieve the whole file at once. 

Are you using Python 2 or Python 3 (if so, which version?)?

**Comment by rrussell39** [comment]
@xhochy I'm using Python 3.6.2
I got this to work using pyarrow & azure.storage.blob
`> pip install azure-storage 0.36.0`
`> conda install pyarrow 0.8.0`
(I could not find a suitable version of azure-storage on any Conda channels that didn't conflict with another of my dependencies - rpy2)
`import pyarrow.parquet as pq
import io
from azure.storage.blob import BlockBlobService

account_name = '...'
account_key = '...'
container_name = 'test-container-2018-01-25'
parquet_file = 'MySample.parquet'
local_file = 'sales_data'

block_blob_service = BlockBlobService(account_name=account_name, account_key=account_key)
with io.open(local_file, 'wb') as file:
    block_blob_service.get_blob_to_stream(container_name=container_name, blob_name=parquet_file, stream=file)

pd = pq.read_table(source=local_file).to_pandas()
pd.head(10)
file.close`

**Comment by rrussell39** [comment]
Ok - this seems to solve the local file issue:
```
with tempfile.TemporaryFile() as fp:
    block_blob_service.get_blob_to_stream(container_name=container_name, blob_name=parquet_file, stream=fp)
    pd = pq.read_table(source=fp).to_pandas()
    pd.head(10)
fp.close
```

**Comment by wesm** [comment]
Any chance of submitting a PR to document this?

**Comment by rrussell39** [comment]
@wesm Sure - I'm happy to contribute.  Can you provide a few details on what that would look like?  e.g. which file to modify and/or anything else I should know?

**Comment by wesm** [comment]
I created a JIRA https://issues.apache.org/jira/browse/ARROW-2066. The documentation can be added to the parquet.rst Sphinx document in the documentation

**Comment by rrussell39** [comment]
Ok working on this now...

**Comment by geoffreysamper** [comment]
When you want to use the storefact example of @xhochy. You don't need the buffered reader because the store.open method return an IOInterface can be used by the pyarrow read_table method.

```
from storefact import get_store
import pyarrow as pa
import pyarrow.parquet as pq

params = {
    'account_name': 'test',
    'account_key': 'XXXsome_azure_account_keyXXX',
    'container': 'my-azure-container',
   'create_if_missing': False
}
store = get_store('azure', **params)

reader = store.open(key) 
table = pq.read_table(reader, columns=columns).to_pandas()
```

**Comment by kcyea** [comment]
Can we read a list of parquet files under subdirectory of a container in Azure blob storage? For example, under container "test_container", there are a list of files under subdirectory of "test.parquet/department=HR/date=2020-01-01/"?

Besides that, I had tested the performance on reading a parquet file of 298MB on Azure blob storage from my local machine, I am selecting 3 columns to return. It took about 2 minutes to return the result. Can this be improve to less than one minute?

from storefact import get_store
import pyarrow as pa
import pyarrow.parquet as pq

params = {
    'account_name': 'test',
    'account_key': 'XXXsome_azure_account_keyXXX',
    'container': 'my-azure-container',
   'create_if_missing': False
}
store = get_store('azure', **params)

reader = store.open(key) 
table = pq.read_table(reader, columns=columns).to_pandas()
print(table.head(10))
