### ISSUE TITLE
Add compute between comparison

### ISSUE THREAD

**Issue by RNKuhns** [apache/arrow#15105]
### Describe the enhancement requested

Between is a common comparison operation. It is currently possible to implement this in Arrow using a combination of greater_equal and less_equal comparisons and the “and” or “and_kleene” logical functions. But given that it is a relatively common comparison and the building blocks exist, it would be nice to be able to call the comparison directly. 

Also, although this may be supported by the compute UDF API, that seems like a lot of overhead for a common comparison.

### Component(s)

C++, Python, R

**Comment by kou** [comment]
Duplicated: https://issues.apache.org/jira/browse/ARROW-9843

**Comment by jorisvandenbossche** [comment]
Duplicate of #25881
