### ISSUE TITLE
[Python] Pandas to Pyarrow Data Type Conversion Error for mixed-type columns

### ISSUE THREAD

**Issue by atherkevin** [apache/arrow#15133]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello,

I'm running into an issue using the pandas to_feather() call with pyarrow. Pyarrow seems to ignore the data types in the dataframe, and instead tries to convert objects to it's own data type, but then fails on the conversion if the column has mixed data types. I'm running python 3.11.1, pandas 1.5.2, numpy 1.24.1, and pyarrow 10.0.1, and have reproduced in a docker image of python 3.11.1-slim and on mac M1. 

`df = pd.DataFrame(({
            'a': ['a', 'a', 'a', 'b', 'b', 'b', 'c'],
            'b': ['c', 'c', None, 'd', 'd', 'd', 'e'],
            'c': [1.5, 2.0, 3.5, 5.0, 8.0, 10.0, 'a string'],
            'd': [1, 2, 3, 1, 2, 3, 1],
            'a1': [1, 1, 1, 1, 1, 1, 1],  # junk columns to test return df
            'a2': [2, 2, 2, 2, 2, 2, 2],  # junk columns to test return df
        }))
        df.to_feather('file')`

Pandas handles this fine, and will say the dtype of column 'C' is either object or string. When attempting to save as a feather file, the following stack trace happens:

> Error
> Traceback (most recent call last):
>   File "/Users/kevin/PycharmProjects/analyzethatv1/tests/test_pyarrow_file_failure.py", line 16, in test_error_conversion
>     df.to_feather('file')
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pandas/core/frame.py", line 2794, in to_feather
>     to_feather(self, path, **kwargs)
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pandas/io/feather_format.py", line 93, in to_feather
>     feather.write_feather(df, handles.handle, **kwargs)
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/feather.py", line 164, in write_feather
>     table = Table.from_pandas(df, preserve_index=preserve_index)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pyarrow/table.pxi", line 3475, in pyarrow.lib.Table.from_pandas
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 611, in dataframe_to_arrays
>     arrays = [convert_column(c, f)
>              ^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 611, in <listcomp>
>     arrays = [convert_column(c, f)
>               ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
>     raise e
>   File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
>     result = pa.array(col, type=type_, from_pandas=True, safe=safe)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
>   File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
>   File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
> pyarrow.lib.ArrowInvalid: ("Could not convert 'a string' with type str: tried to convert to double", 'Conversion failed for column c with type object')

Questions- why would this not obey the pandas dtype? I can appreciate attempting the conversion, but if the conversion fails, why not maintain the pandas dtype for saving? Is there some option I'm missing?

### Component(s)

Python

**Comment by AlenkaF** [comment]
PyArrow doesn't support columns with mixed string and primitive dtypes and so it tries to convert to a double

https://arrow.apache.org/docs/format/Columnar.html#terminology
https://arrow.apache.org/docs/python/pandas.html#pandas-arrow-conversion
https://github.com/apache/arrow/blob/b1a48c78a318402daab1d0f974825373ef41b293/python/pyarrow/tests/test_pandas.py#L2717-L2732

What you could do is to convert pandas `df` to a `pyarrow.Table` adding a `Schema` specifying the object column to be a string dtype and then [pyarrow.feather.write_feather](https://arrow.apache.org/docs/python/generated/pyarrow.feather.write_feather.html#pyarrow.feather.write_feather) should work fine.

https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pandas
https://arrow.apache.org/docs/python/generated/pyarrow.Schema.html#pyarrow.Schema

**Comment by atherkevin** [comment]
Thank you! Appreciate the help!

**Comment by atherkevin** [comment]
Just for the sake of information sharing and reference, using pa.Table.from_pandas(df, schema) with a schema describing the desired column type in pyarrow will still result in conversion error for columns of mixed primitive types.

**Comment by AlenkaF** [comment]
What data type did you use for the mixed column in the schema? Can you share the code you used?

**Comment by atherkevin** [comment]
Reduced complexity to show the failure

`df = pd.DataFrame(({
            'a': ['a', 'a', 'a', 'b', 'b', 'b', 'c'],
            'b': [1, 2, None, 4, 5, 1, 0],
            'c': [1.5, 2.0, 3.5, 5.0, 8.0, 10.0, 'a string'],
        }))

        fields = [pa.field('a', pa.string()),
                  pa.field('b', pa.int64()),
                  pa.field('c', pa.string())
                  ]
        schema = pa.schema(fields)
        table = pa.Table.from_pandas(df, schema)`

Stack trace:

Error
Traceback (most recent call last):
  File "/Users/kevin/PycharmProjects/analyzethatv1/tests/test_pyarrow_file_failure.py", line 20, in test_error_conversion
    table = pa.Table.from_pandas(df, schema)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 3475, in pyarrow.lib.Table.from_pandas
  File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 611, in <listcomp>
    arrays = [convert_column(c, f)
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/Users/kevin/PycharmProjects/analyzethatv1/venv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'float' object", 'Conversion failed for column c with type object')

So it seems it is reading the schema, and attempting to convert it to string, but then throws an error when it hits a float? I've also tried variations of casting this in pandas before passing it into pyarrow to no avail.

**Comment by AlenkaF** [comment]
Oh sorry, didn't check myself to be sure.
Changing the type on the pandas side should work, like so:

```python
import pyarrow as pa
import pandas as pd

df = pd.DataFrame(({
    'a': ['a', 'a', 'a', 'b', 'b', 'b', 'c'],
    'b': [1, 2, None, 4, 5, 1, 0],
    'c': [1.5, 2.0, 3.5, 5.0, 8.0, 10.0, 'a string'],
}))
df['c'] = df['c'].astype('str') 

pa.Table.from_pandas(df)
# pyarrow.Table
# a: string
# b: double
# c: string
# ----
# a: [["a","a","a","b","b","b","c"]]
# b: [[1,2,null,4,5,1,0]]
# c: [["1.5","2.0","3.5","5.0","8.0","10.0","a string"]]

df.to_feather('file')
pd.read_feather('file')
#    a    b         c
# 0  a  1.0       1.5
# 1  a  2.0       2.0
# 2  a  NaN       3.5
# 3  b  4.0       5.0
# 4  b  5.0       8.0
# 5  b  1.0      10.0
# 6  c  0.0  a string
```
