### ISSUE TITLE
[C++][CI] ASAN error in streaming JSON reader tests

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#15137]
### Describe the bug, including details regarding any error messages, version, and platform.

Example: https://github.com/apache/arrow/actions/runs/3808683807/jobs/6479467470
[logs_412266.zip](https://github.com/apache/arrow/files/10326545/logs_412266.zip)

### Component(s)

C++

**Comment by pitrou** [comment]
cc @benibus

**Comment by benibus** [comment]
I saw this pop up once back when the threaded reader implementation was a lot more fragile. Figured it was fixed by the subsequent changes but I guess not...

I still haven't managed to reproduce this locally but I'll try to find out what's wrong.
