### ISSUE TITLE
[CI] arrow-compute: ExecPlanExecution.StressSourceOrderBy may failed

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#15141]
### Describe the bug, including details regarding any error messages, version, and platform.

1. https://github.com/apache/arrow/actions/runs/3812471160/jobs/6485697443
2. https://github.com/apache/arrow/actions/runs/3808810467/jobs/6479699758

Seems that the case may failed. And I didn't modify the case which could cause it failed.

### Component(s)

C++

**Comment by westonpace** [comment]
Thanks for the report.  I probably introduced this with #15104
