### ISSUE TITLE
[R] Failing to  write_feather an R data.frame with column of mixed lists and NA

### ISSUE THREAD

**Issue by OfekShilon** [apache/arrow#15154]
### Describe the bug, including details regarding any error messages, version, and platform.

This works:
```r
> df <- data.frame(a=1:4, b=I(list(1,1:2,1:3,1:4)))
> arrow::write_feather(x=df, sink = "~/tmp/t1")
```

While this fails:
```r
> df <- data.frame(a=1:4, b=I(list(1,1:2,1:3,NA)))
> arrow::write_feather(x=df, sink = "~/tmp/t2")
Error: Invalid: cannot convert
```

### Component(s)

R

**Comment by OfekShilon** [comment]
All-NA columns also work:
```r
df <- data.frame(a=1:4, b=NA)
arrow::write_feather(x=df, sink = "~/tmp/t3")
```
just mixed data/NA break.

**Comment by OfekShilon** [comment]
Turns out the problem is non-homogeneous classes in an AsIs column. NAs are just a private case.

```r
> df1 <- data.frame(a=I(list(1)))
> df2 <- data.frame(a=I(list("d")))
> df <- rbind(df1,df2)
> arrow::write_feather(df,"~/tmp/df")
Error: Invalid: cannot convert
```

**Comment by thisisnic** [comment]
I don't think this is something we can support; part of the process of writing a data.frame to a Feather file involves converting from R data.frame to Arrow Table, which also involves converting the types.  Given the purpose of the AsIs class is to prevent converting to another type, I don't see how/why we'd support this. Happy to consider other perspectives though.
