### ISSUE TITLE
[C++][Flight] Test failure in pyarrow flight tests

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#15175]
### Describe the bug, including details regarding any error messages, version, and platform.

The m1 wheel builds are failing due to a [flight test](https://github.com/ursacomputing/crossbow/actions/runs/3827996914/jobs/6513100983#step:11:438)
```
 _________________________ test_none_action_side_effect _________________________

    def test_none_action_side_effect():
        """Ensure that actions are executed even when we don't consume iterator.
    
        See https://issues.apache.org/jira/browse/ARROW-14255
        """
    
        with ActionNoneFlightServer() as server, \
                FlightClient(('localhost', server.port)) as client:
            client.do_action(flight.Action("append", b""))
            r = client.do_action(flight.Action("get_value", b""))
>           assert json.loads(next(r).body.to_pybytes()) == [True]
E           assert [] == [True]
E             Right contains one more item: True
E             Full diff:
E             - [True]
E             + []
```
It looks like it was introduced here https://github.com/apache/arrow/commit/985789165eb30cc575d67aa52469f802e5132e64 
cc @lidavidm

### Component(s)

C++, FlightRPC, Python

**Comment by lidavidm** [comment]
sigh, I guess the other fix isn't sufficient.

Either we have to remove this feature, and accept that DoAction cannot handle streaming results, or we have to remove the test, and document that you must consume the results of DoAction

**Comment by lidavidm** [comment]
Oh wait. @assignUser this build is old, it predates the fix for this. See https://github.com/apache/arrow/pull/15152

**Comment by assignUser** [comment]
Oh nice, sorry for the noise did not see that PR!
