### ISSUE TITLE
Add support for PEP519 - pathlib and similar objects

### ISSUE THREAD

**Issue by vmuriart** [apache/arrow#1522]
Currently `pyarrow` doesn't seem to support reading from `pathlib.Path` or similar objects. [PEP519]( https://www.python.org/dev/peps/pep-0519/) introduced `__fspath__` which could be used to transform any `Path` like object to a string. 

[Pandas](https://github.com/pandas-dev/pandas/blob/a9d8e04ab68f688f899b4164bfa1ac868c9c1c64/pandas/io/common.py#L120-L160) has a sample implementation, though I think a simpler implementation of it could be used. 

I can take a stab at writing the pull request (and opening the JIRA ticket), but wanted to check if there was a reason why this shouldn't be implemented.

## Example

```python
import pathlib

import pandas as pd

import pyarrow as pa
import pyarrow.parquet as pq

df = pd.DataFrame({
    'Foo': ['A', 'A', 'B', 'B', 'C'],
    'Bar': ['A1', 'A2', 'B2', 'D3', ''],
})

test_dir = pathlib.Path(__file__).parent / 'test'
test_dir.mkdir(parents=True, exist_ok=True)

table = pa.Table.from_pandas(df)

path = test_dir / 'file1.parquet'

# Doesn't work
pq.write_table(table, path)

# Works
pq.write_table(table, str(path))
```

**Comment by wesm** [comment]
No reason not to do this -- feel free to open a JIRA and have a go at it

**Comment by vmuriart** [comment]
Moved to Jira (https://issues.apache.org/jira/browse/ARROW-2046)

**Comment by vmuriart** [comment]
@wesm sorry I couldn't create the pull-request as I originally promised. My laptop died, and I haven't had the time to work on it at work.

**Comment by xhochy** [comment]
@vmuriart there is a PR for the support now open at: https://github.com/apache/arrow/pull/1675

**Comment by vmuriart** [comment]
@xhochy I had noticed that, thus why I wanted to apologize 😄 . It also looks much better than what I had in mind.
