### ISSUE TITLE
[Python] dictionary_encode support duration types

### ISSUE THREAD

**Issue by jbrockmendel** [apache/arrow#15226]
### Describe the enhancement requested

In troubleshooting pandas xfails, I'm finding a chunk of them trace back to trying to call dictionary_encode with duration types.  @jorisvandenbossche tells me this is straightforward to do by operating on the underyling integers.  Not obvious to me what a clean way to get those integers is (i.e. without going through .buffers)

### Component(s)

Python

**Comment by westonpace** [comment]
Casting from duration to `int64` should be a zero-copy operation:

```
>>> import pyarrow as pa
>>> import datetime
>>> arr = pa.array([datetime.timedelta(days=1), datetime.timedelta(hours=1)])
>>> arr
<pyarrow.lib.DurationArray object at 0x7f6efa8e60e0>
[
  86400000000,
  3600000000
]
>>> arr.cast(pa.int64())
<pyarrow.lib.Int64Array object at 0x7f6e6edc86a0>
[
  86400000000,
  3600000000
]
```

**Comment by jorisvandenbossche** [comment]
While that is indeed the way to get the int64 values, the relevant issue for Arrow is that this is actually easy to support and that you shouldn't need this (we just "forgot" to add duration type to the list of types to support in the hashing algorithms) -> https://github.com/apache/arrow/pull/33685

**Comment by jbrockmendel** [comment]
Awesome,  thanks for the quick turnaround!
