### ISSUE TITLE
[JS] Support loading from XHR

### ISSUE THREAD

**Issue by thatcort** [apache/arrow#15230]
### Describe the enhancement requested

It would be great to support loading a table from an XHR in addition to fetch request. Angular uses XHR under the hood, so integrating Arrow into an Angular app requires either duplicating app authentication for fetch or translating an XHR response into something `tableFromIPC()` understands.

### Component(s)

JavaScript

**Comment by domoritz** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response says that `XMLHttpRequest.response` already returns an `ArrayBuffer`. Can you provide a code snippet to show what you would like to work?

**Comment by thatcort** [comment]
Will `tableFromIPC()` work on an ArrayBuffer? Looking again I now see that RecordBatchReader can wrap an ArrayBuffer in an ByteStream. I'll have to give it a try :)
