### ISSUE TITLE
[CI][C++] arrow-compute `ExecPlanExecution.StressSourceGroupedSumStop` timeout

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#15243]
### Describe the bug, including details regarding any error messages, version, and platform.

Test is: https://github.com/apache/arrow/actions/runs/3862492798/jobs/6584098719

```
[ RUN      ] ExecPlanExecution.StressSourceGroupedSumStop
D:/a/arrow/arrow/cpp/src/arrow/compute/exec/plan_test.cc:849: Failure
Value of: _fut.Wait(::arrow::kDefaultAssertFinishesWaitSeconds)
  Actual: false
Expected: true
Google Test trace:
D:/a/arrow/arrow/cpp/src/arrow/compute/exec/plan_test.cc:824: single threaded
D:/a/arrow/arrow/cpp/src/arrow/compute/exec/plan_test.cc:821: slowed
D:/a/arrow/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:64: Plan was destroyed before finishing


99% tests passed, 1 tests failed out of 69
```

which cause this patch failed https://github.com/apache/arrow/pull/15241

### Component(s)

C++, Continuous Integration

**Comment by rok** [comment]
Looks like the test takes too long to run?

**Comment by mapleFU** [comment]
> Looks like the test takes too long to run?

Maybe just running to much time / a deadlock or other bug...I don't know :(

**Comment by westonpace** [comment]
`kDefaultAssertFinishesWaitSeconds` is generally long enough that even CI machines will finish by then.  So I think deadlock seems likely :(

**Comment by westonpace** [comment]
I've reproduced this.  It is a deadlock.  It appears that, in some cancel situations, GroupByNode is not properly marking it's finished future as complete.  I can probably spot fix this if we need to but it is fixed more categorically by #15253 (I'm attempting to reproduce on that branch and so far have not been able to so that is a good sign).  If it appears that #15253 is not going to merge before the release then I will fix this individually (feel free to ping me if it seems like I am forgetting).

**Comment by mapleFU** [comment]
Please go ahead, I just blocked by CI

By the way, I meet another timeout, but I don't understand why: https://github.com/apache/arrow/actions/runs/3886295191/jobs/6631229773

**Comment by westonpace** [comment]
I don't think #15253 will merge in time.  I am going to try and put in a more targeted fix today.

**Comment by mapleFU** [comment]
Hi westonpace, did you solve this issue?

**Comment by westonpace** [comment]
> Hi westonpace, did you solve this issue?

Thanks for the reminder, I had forgotten.

**Comment by westonpace** [comment]
@raulcd this should be included in the release.  I've marked it with the 11.0.0 milestone.  Is there anything more I need to do?

**Comment by raulcd** [comment]
no, that's fine, Thanks! The `archery release cherry-pick` script will pick it up. I am adding the `Priority: blocker` label, just as a reminder for me to double check once I run the `cherry-pick` command but adding the 11.0.0 milestone should be enough.
