### ISSUE TITLE
[R] Error when trying to save a data.frame with NULL column names

### ISSUE THREAD

**Issue by OfekShilon** [apache/arrow#15247]
### Describe the bug, including details regarding any error messages, version, and platform.

```r
df <- data.frame(a=1:3,b=4:6)
names(df) <- NULL
arrow::write_feather(x=df, sink="~/tmp/df")
# Error: Invalid input type, expected 'character' actual 'NULL'
```

### Component(s)

R

**Comment by thisisnic** [comment]
Thanks for reporting this @OfekShilon!

I had a look at our other file writing functions to have a look at behaviour, and this isn't just restricted to those.  Interestingly, `readr::write_csv()` has the same behaviour.

``` r
df <- data.frame(a=1:3,b=4:6)
names(df) <- NULL
arrow::write_feather(x=df, sink="~/tmp/df")
#> Error: Invalid input type, expected 'character' actual 'NULL'
arrow::write_csv_arrow(df, "tst.csv")
#> Error in `value[[3L]]()`:
#> ! x must be an object of class 'data.frame', 'RecordBatch', 'Dataset', 'Table', or 'RecordBatchReader' not 'data.frame'.

#> Backtrace:
#>     ▆
#>  1. └─arrow::write_csv_arrow(df, "tst.csv")
#>  2.   └─base::tryCatch(...)
#>  3.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  4.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  5.         └─value[[3L]](cond)
#>  6.           └─rlang::abort(...)
arrow::write_parquet(df, "tst.csv")
#> Error: Invalid input type, expected 'character' actual 'NULL'

readr::write_csv(df, "tst.csv")
#> Error: Invalid input type, expected 'character' actual 'NULL'
```

Can I ask a bit more about the use case here, and the circumstances in which it's desirable to have a `data.frame` with NULL column names?

**Comment by OfekShilon** [comment]
@thisisnic We didn't have a direct need for this behavior - it was part of some complex logic that deleted col names in one part, than saved/loaded and applied new names at a different part.  We did work around it, it's just another place where the migration from native robj serialization to arrow bit us and we thought we'd report.

**Comment by thisisnic** [comment]
OK, good to know.  In that case, I think a sensible solution will be adding some validation of input df names so that the error message supplied to the user is more informative.
