### ISSUE TITLE
[C++][Dataset] arrow::dataset::Partitioning::Default() can't be used for writing dataset

### ISSUE THREAD

**Issue by kou** [apache/arrow#15256]
### Describe the bug, including details regarding any error messages, version, and platform.

Because `arrow::dataset::DefaultPartitioning::Format()` isn't implemented:

https://github.com/apache/arrow/blob/2acc51a7d5304c3fc6a432f1c09946547ca91d74/cpp/src/arrow/dataset/partition.cc#L92-L95

It's required in `WriteBatch()`:

https://github.com/apache/arrow/blob/2acc51a7d5304c3fc6a432f1c09946547ca91d74/cpp/src/arrow/dataset/file_base.cc#L380-L381

Is it expected that we can't use `arrow::dataset::Partitioning::Default()` for writing dataset?
If it's expected, how about removing `arrow::dataset::Partitioning::Default()` because it's useless?
If it's not expected, how about implementing `arrow::dataset::DefaultPartitioning::Format()` like the following?

```diff
diff --git a/cpp/src/arrow/dataset/partition.cc b/cpp/src/arrow/dataset/partition.cc
index 46cdf9023c..13add35fb8 100644
--- a/cpp/src/arrow/dataset/partition.cc
+++ b/cpp/src/arrow/dataset/partition.cc
@@ -90,8 +90,7 @@ std::shared_ptr<Partitioning> Partitioning::Default() {
     }
 
     Result<PartitionPathFormat> Format(const compute::Expression& expr) const override {
-      return Status::NotImplemented("formatting paths from ", type_name(),
-                                    " Partitioning");
+      return PartitionPathFormat{"", ""};
     }
 
     Result<PartitionedBatches> Partition(
```

### Component(s)

C++

**Comment by westonpace** [comment]
https://issues.apache.org/jira/browse/ARROW-15409 is probably related.

**Comment by kou** [comment]
Thanks! I didn't notice it.

It seems that we want to use `arrow::dataset::Partitioning::Default()` for no partition write. (All data are written to the base directory.)

**Comment by westonpace** [comment]
> It seems that we want to use arrow::dataset::Partitioning::Default() for no partition write. (All data are written to the base directory.)

I agree.  Either `Partitioning::Default` means "no partitioning" or we get rid of `Partitioning::Default` and make partitioning optional anywhere it is specified.  I think your suggestions (`Partitioning::Default` means "all in one directory") is the easiest.
