### ISSUE TITLE
[GLib] Add support for MatchSubstringOptions

### ISSUE THREAD

**Issue by heronshoes** [apache/arrow#15285]
#### Target option

MatchSubstringOptions

#### Proposed feature

Add support for MatchSubstringOptions.

#### Impact of this request

It will be used in these functions:

- count_substring()
- count_substring_regex()
- ends_with()
- find_substring()
- find_substring_regex()
- match_like()
- match_substring()
- match_substring_regex()
- starts_with()

#### Reference of this request

https://arrow.apache.org/docs/cpp/compute.html#containment-tests

### Component(s)

GLib, Ruby

**Comment by kou** [comment]
@heronshoes Do you want to implement this? Or can I implement this?

**Comment by heronshoes** [comment]
@kou Sorry I have no skill other than Ruby...

**Comment by kou** [comment]
OK. I'll do it.

**Comment by heronshoes** [comment]
Thanks!
