### ISSUE TITLE
[Ruby] Return other than @table.raw_records when saving Table to csv

### ISSUE THREAD

**Issue by heronshoes** [apache/arrow#15289]
#### Target method

Arrow::Table#save

#### Proposed feature

Change return value of Table#save when saving to csv files.

Current code returns `@table.raw_records` (Array of row Arrays). When saving a very big Table, it takes long time to display a large Array with interactive execution such as irb or Jupyter.

When we save as 'arrow' or 'arrows', it simply returns 'true'.

Candidates of return value:

- true
- self
- size of Table

#### Impact of this request

It will improve the user experience of interactive execution. The return value of #save is rarely used.

#### Reference of this request

https://github.com/apache/arrow/blob/master/ruby/red-arrow/lib/arrow/table-saver.rb#L174-L176

### Component(s)

Ruby

**Comment by kou** [comment]
Let's use `self`.

**Comment by heronshoes** [comment]
OK. I will create PR. Thank you.
