### ISSUE TITLE
pyarrow: ModuleNotFoundError: No module named 'pyarrow.plasma'

### ISSUE THREAD

**Issue by Darkonaut** [apache/arrow#1531]
I tried to reproduce the example for plasma from here [https://arrow.apache.org/docs/python/plasma.html](https://arrow.apache.org/docs/python/plasma.html) but `import pyarrow.plasma as plasma` gives me `ModuleNotFoundError: No module named 'pyarrow.plasma'`.

Did the api change or what could be the problem here?

`pyarrow.__version__ # '0.8.0'`
Windows 7, Anaconda3, Python 3.6

**Comment by wesm** [comment]
Plasma is not yet supported on Windows

**Comment by Darkonaut** [comment]
Thanks for letting me know! 

It doesn't seem to get mentioned in the docs linked. Under... 

> **Using  Plasma with Huge Pages**

.... is a restriction ...

>On Linux it is possible to use the Plasma store with huge pages for increased throughput.

, implying everything written above is not restricted to Linux.

**Comment by pcmoritz** [comment]
This is as supposed to macOS where huge pages are not supported but plasma
is.

**Comment by wesm** [comment]
I created https://issues.apache.org/jira/browse/ARROW-2069
