### ISSUE TITLE
overwrite column in parquet file?

### ISSUE THREAD

**Issue by Darkonaut** [apache/arrow#1545]
Am I right there's no way to overwrite just a single column in a parquet file although it's possible to read only one column?  If compression is column-based, what's preventing a round trip like posted below appart from updating some metadata?

```python
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

d = {i: 0 for i in range(4)}
df = pd.DataFrame(d, index=[0])
"""
Out: 
   0  1  2  3
0  0  0  0  0
"""
table = pa.Table.from_pandas(df)
pq.write_table(table, 'example_parquet')
table_col2 = pq.read_table('example_parquet', columns=["2"])
df2_col2 = table_col2.to_pandas()
df2_col2.loc[0] = 3
table_col2 = pa.Table.from_pandas(df2_col2)
pq.write_table(table_col2, 'example_parquet', columns=["2"])
```

**Comment by xhochy** [comment]
Parquet files cannot be mutatated. The data in a file is encoded, compressed and chunked  thus if you would change a single value in a column, the size and chunking of the column changes.  As the column is located in the middle of the file, you would need to rewrite the whole file from this position on.. This is nearly as compute intensive as rewriting the whole file again. Depending on the encoding, you might even have to rewrite segments before your value in the file as the new value might not be part of the yet existing dictionary.
