### ISSUE TITLE
Unable to write structs with non-scalar fields to parquet.

### ISSUE THREAD

**Issue by ishaan** [apache/arrow#1546]
I asked this question in dev@ and slack, but realised that this is the more appropriate forum for the question, so my apologies for the duplication. I'm trying to write a parquet file using pyarrow, the schema I'm trying to write data for has struct columns with non-scalar fields. This is what I've done so far:

struct_struct = pa.struct([pa.field('field1', pa.struct([pa.field('field1', pa.int32())]))])
_struct_int = pa.StructArray.from_arrays(['field1'], [pa.array([1], type=pa.int32())])
_struct_struct = pa.StructArray.from_arrays(['field1'], [_struct_int])
In [55]: _struct_struct
Out[55]: 
<pyarrow.lib.StructArray object at 0x7f6a4d3b4d08>
[
  {'field1': {'field1': 1}}
]
pq.write_table(pa.Table.from_arrays([_struct_struct], ['struct_struct']), 'foo.parquet')
in pyarrow.lib.check_status (/arrow/python/build/temp.linux-x86_64-2.7/lib.cxx:8570)()
     83             raise ArrowKeyError(message)
     84         elif status.IsNotImplemented():
---> 85             raise ArrowNotImplementedError(message)
     86         elif status.IsTypeError():
     87             raise ArrowTypeError(message)

Looks like it's not yet supported, but I wanted to confirm that and ensure I'm not doing anything wrong. If yes then I can abandon the effort and wait till it gets supported.
On that note, is there a notion of whether this will be supported?

Thanks !

Ishaan

**Comment by wesm** [comment]
I will reply on the mailing list; have been swimming in the PR backlog the last couple of weeks. The short summary is that complete nested data read/write support is not yet implemented in parquet-cpp. We would appreciate some help with this.

Thanks!
