### ISSUE TITLE
[Java] Bring in java-unsafe-tools as utility library for Arrow

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#15531]
Originally here:

https://github.com/alexkasko/unsafe-tools 

SGA signed off and received by Secretary.

**Reporter**: [Jacques Nadeau](https://issues.apache.org/jira/browse/ARROW-114) / @jacques-n

<sub>**Note**: *This issue was originally created as [ARROW-114](https://issues.apache.org/jira/browse/ARROW-114). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by vibhatha** [comment]
Since Java latest releases are planning upon [deprecating](https://openjdk.org/jeps/8323072), it would be better to close this ticket now.

**Comment by felipecrv** [comment]
Thanks @vibhatha! I'm closing since bringing in a third-party library that depends on functionality deprecated since Java 9 (released in 2017 — one year after this issue was created) is not a good idea.
