### ISSUE TITLE
[Java] ListVector: splitAndTransfer should also setValueCount()

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#15579]
This results in getValueCount() to return 0 although splitAndTransfer() has been called previously. 

**Reporter**: [MinJi Kim](https://issues.apache.org/jira/browse/ARROW-235)

<sub>**Note**: *This issue was originally created as [ARROW-235](https://issues.apache.org/jira/browse/ARROW-235). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by danepitkin** [comment]
Fixed as part of https://issues.apache.org/jira/browse/ARROW-1474

See implementation here: https://github.com/apache/arrow/blob/37616a8da57e4d98c82e8213ba1999cff4354334/java/vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java#L544
