### ISSUE TITLE
[Java] ComplexWriterImpl.setValueCount() doesn't set the value count of its "root" container

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#15793]
The following code:
```Java
    MapVector vector = new MapVector(name, allocator, null);
    ComplexWriterImpl mapWriter = new ComplexWriterImpl("colMap", vector);
    BaseWriter.MapWriter mapWr = mapWriter.rootAsMap();
    // write into the map vector
    …
    mapWriter.setValueCount(5);
```

is expected to set the value count of _vector_ to 5, but it doesn't

**Reporter**: [Abdel Hakim Deneche](https://issues.apache.org/jira/browse/ARROW-329) / @adeneche

<sub>**Note**: *This issue was originally created as [ARROW-329](https://issues.apache.org/jira/browse/ARROW-329). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by danepitkin** [comment]
Fixed in https://github.com/apache/arrow/issues/36375

It contains tests for `setValueCount` functionality: https://github.com/apache/arrow/pull/36351/files#diff-d272bd6f29af178ded979919169629bff9dc6d558da6c876e8f5b8358da1fdbfR1615-R1618
