### ISSUE TITLE
Using schema with from_pandas

### ISSUE THREAD

**Issue by matthewgilbert** [apache/arrow#1589]
The behavior of `from_pandas` using a `schema` appears unintuitive to me. Unsure if this is a bug but would appreciate some clarification. 

The first issue is if you create a `Table` from a `DataFrame` of ints with a NaN value. Since pandas casts these to floats, when converted to a table the NaN is interpreted as an integer. This seems a bit perverse to me since a known limitation in pandas (the inability to have null valued integers data) is taking precedence over arrow's functionality to store these as an IntArray with nulls?

```python
import pyarrow as pa
import pandas as pd

df = pd.DataFrame({"a":[1, 2, pd.np.NaN]})
schema = pa.schema([pa.field("a", pa.int64(), nullable=True)])
table = pa.Table.from_pandas(df, schema=schema)
table[0]


<pyarrow.lib.Column object at 0x7f2151d19c90>
chunk 0: <pyarrow.lib.Int64Array object at 0x7f213bf356d8>
[
  1,
  2,
  -9223372036854775808
]
```

The second issue is with providing a schema with `nullable=False` but passing a `DataFrame` which in fact has nulls. This appears to just disregard the schema? I would expect an error here. Is this by design, and if so any elaboration on this would be much appreciated since the [schema section of the docs](https://arrow.apache.org/docs/python/data.html#custom-schema-and-field-metadata) is still being worked on.

```python
df = pd.DataFrame({"a":[1.2, 2.1, pd.np.NaN]})
schema = pa.schema([pa.field("a", pa.float64(), nullable=False)])
table = pa.Table.from_pandas(df, schema=schema)
table[0]
<pyarrow.lib.Column object at 0x7f213bf2fb70>
chunk 0: <pyarrow.lib.DoubleArray object at 0x7f213bf20ea8>
[
  1.2,
  2.1,
  NA
]
```

This also seems to happen with `from_arrays()`

```python
schema = pa.schema([pa.field("a", pa.float64(), nullable=False)])
pa.Table.from_arrays([pa.array([1, 2, None])], schema=schema)[0]
<pyarrow.lib.Column object at 0x7f213c1a1fc0>
chunk 0: <pyarrow.lib.Int64Array object at 0x7f213bf35bd8>
[
  1,
  2,
  NA
]
```

Any clarification would be much appreciated.

**Comment by wesm** [comment]
This look like two bugs to me. Can you open JIRAs for them? Thanks

**Comment by matthewgilbert** [comment]
Okay JIRAs created at [ARROW-2135](https://issues.apache.org/jira/browse/ARROW-2135) and [ARROW-2136](https://issues.apache.org/jira/browse/ARROW-2136)

**Comment by wesm** [comment]
thanks!
