### ISSUE TITLE
Importing parquet fails in debug mode

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#1612]
When I compile pyarrow and libparquet in debug mode, libparquet fails importing from pyarrow:
```
ImportError: /home/antoine/miniconda3/envs/pyarrow/bin/../lib/libparquet.so.1: undefined symbol: _ZN5boost16re_detail_10660012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE5matchEv
ERROR: could not load /home/antoine/arrow/python/pyarrow/tests/conftest.py
```

The unmangled symbol is:
```
boost::re_detail_106600::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match()
```

Is this a known issue? Things seem to work fine in release mode.

**Comment by wesm** [comment]
Are you compiling dependencies from source or using binaries from conda? May need to pass some extra compilation flags to disable gcc5 ABI https://github.com/apache/arrow/pull/1319

**Comment by pitrou** [comment]
I'm using boost-cpp from conda-forge.

**Comment by pitrou** [comment]
Also I have `CXX=clang++-4.0`.

**Comment by wesm** [comment]
OK, you'll have to set `-D_GLIBCXX_USE_CXX11_ABI=0` in all your CXXFLAGS to be able to use the conda-forge toolchain libraries since clang on Ubuntu 16.04 will use the system standard library (gcc >= 5).

**Comment by pitrou** [comment]
Hmm, now I'm getting:
```
ImportError: /home/antoine/miniconda3/envs/pyarrow/bin/../lib/libparquet.so.1: undefined symbol: _ZN5arrow2io16MemoryMappedFile4OpenERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_8FileMode4typeEPSt10shared_ptrIS1_E
```

I have:
```
export CC=clang-4.0
export CXX=clang++-4.0
export CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
export PYARROW_CXXFLAGS=$CXXFLAGS
```

**Comment by pitrou** [comment]
Ok, adding `-DCMAKE_CXX_FLAGS=$CXXFLAGS` to the cmake invocations seems to make it work!

**Comment by wesm** [comment]
This was addressed https://github.com/apache/arrow/blob/master/python/doc/source/development.rst#known-issues
