### ISSUE TITLE
Zero Copy Issue Pandas Dataframe 

### ISSUE THREAD

**Issue by alivcor** [apache/arrow#1649]
Hi guys,

Not sure if this is the right place to ask.  

I have been trying to share a pandas dataframe in multiple Jupyter notebooks using PyArrow via Plasma memory store

I closely followed the steps here :

https://arrow.apache.org/docs/python/plasma.html

But as soon as I do

<pre>
result = record_batch.to_pandas()
</pre>

The memory utilization goes up and it seems it is copying. I replaced 'read_next_batch()' with 'read_all()' so that it reads as a PyArrow table and I can use the 'zero_copy_only=True' parameter in 'to_pandas()' - but it still makes in memory copy. 

I went through Wes's blog at <a href="http://www.wesmckinney.com/blog/arrow-streamimg-columnar"> Streaming Columnar Data with Apache Arrow</a> but he uses 'pa.StreamReader()' which doesn't exist in PyArrow as far as I searched.

Am I missing something here? Can someone help?

Thanks!

**Comment by alivcor** [comment]
The goal is to share a pandas dataframe from one notebook to another through Plasma Memory Store, without having two copies of the dataframe in memory.

As @wesm has described in the post it should have been zero copy.

**Comment by wesm** [comment]
hi @alivcor if you want to do zero copy with pandas, you need to wait for Arrow 0.9.0 which has zero-copy pandas serialization built into the `pyarrow.serialize` and `pyarrow.deserialize` functions. This will need to be better documented to help users understand what operations will copy data and what will not.

Using `RecordBatch.to_pandas` will copy data in nearly all cases -- my understanding was that passing `zero_copy_only=True` would cause an exception to be raised if ZC is not possible. @xhochy  does that sound right?

**Comment by alivcor** [comment]
Thanks @wesm 

[RecordBatch.to_pandas()](https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatch.html#pyarrow.RecordBatch.to_pandas) currently doesn't support the `zero_copy_only=True` argument. It's only available when you're using PyArrow Tables.

So I'm assuming you're talking about the exception when using `zero_copy_only=True` argument with PyArrow Table. That isn't happening either. We've verified it on a number of datasets. Memory utilization goes up, and it doesn't throw an exception.

**Comment by wesm** [comment]
Can you show the schema for your dataset?

**Comment by wesm** [comment]
OK, I would not expect zero copy to be possible at all starting from a RecordBatch with the dataset you're describing -- this should raise an exception, though, so we should diagnose and create a bug report.

0.9.0 probably will be released within one month. You always have the option to build from source

**Comment by alivcor** [comment]
Thanks @wesm 

Is zero copy available in any other formats (spark, drill etc) as of now (0.8) ?

Also, are any pre-packaged dev builds for 0.9 available as of now ?

**Comment by wesm** [comment]
The Arrow columnar format itself always supports zero-copy, but zero-copy conversions to _other_ formats (like pandas) is only possible in some very limited cases.

In 0.9.0, we have invented an alternative zero-copy serialization scheme for pandas that does not use the columnar format. 

We are building some nightly Linux packages in the `twosigma` channel that you can try out on anaconda.org: https://anaconda.org/twosigma/pyarrow

**Comment by wesm** [comment]
Closing this issue. We welcome your feedback on the 0.9.0 release; if you run into problems let us know in case there are some things that can be fixed for 0.10
