### ISSUE TITLE
rust arrow bindings support

### ISSUE THREAD

**Issue by DrRibosome** [apache/arrow#1653]
I was wondering if there were any plans to build a rust package with bindings for the cpp code.

Im working on a large rust project that integrates with python. Currently getting data out of rust and into python is possible, but fairly tedious. Apache arrow seems perfect for this, but it's pretty difficult to find working bindings for it (the only project I found hasnt been touched in a year, it's documentation is sparse to non-existent, and it's build artifacts arent published on the central rust package site). It would be great if the apache arrow project maintained the low level bindings and let other library authors build on them.

**Comment by wesm** [comment]
hi @DrRibosome, this would be a great addition to the project. We don't have any contributors at the moment who need to build such bindings, but if you would like to start a Rust bindings subproject in the repo, please be our guest.

**Comment by jo8hua** [comment]
@DrRibosome would you be interested in doing this yourself? I also would be interested in developing this for a work project.

**Comment by wesm** [comment]
I created a Rust component on JIRA. Let's create some issues and continue the discussion there

**Comment by DrRibosome** [comment]
I gave it a shot, but rust's bindgen didnt generate code from the arrow cpp correctly and I stopped.

**Comment by wesm** [comment]
I speculate that the longer-term plan for Rust ought to be a native and idiomatic implementation, but it will be useful to have constructs for utilizing functionality from the C++ libraries

**Comment by DrRibosome** [comment]
yah, a rust native implementation seems like the best route

**Comment by jo8hua** [comment]
I agree, but lets take this over to the [JIRA](https://issues.apache.org/jira/browse/ARROW-2267).
