### ISSUE TITLE
non-statically linked compression libraries?

### ISSUE THREAD

**Issue by teh** [apache/arrow#1661]
Context: I'm trying to package pyarrow for NixOS.

Looking at [1] it looks like I should be able to set `-DLZ4_HOME=... -DLZ4_SHARED_LIB=...` but when trying I get `-- Could NOT find LZ4 (missing: LZ4_STATIC_LIB)`.

Before I learn more CMake: Am I using the correct invocation? If yes: is the lack of shared compression codec linking an omission or by design?

[1]
https://github.com/apache/arrow/blob/master/cpp/cmake_modules/FindLz4.cmake

**Comment by xhochy** [comment]
It is an omission. We should support both types of linking a library.

**Comment by wesm** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-2217. Patch for this would be welcome
