### ISSUE TITLE
[C++] arrow::internal::make_unique conflicts std::make_unique on MSVC

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#16704]
MSVC appears to implement c++20 ADL, which includes function templates with explicit template arguments (previously these were not looked up through ADL):

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/23604480/job/psvu16jasktacvy2#L2097

**Reporter**: [Ben Kietzman](https://issues.apache.org/jira/browse/ARROW-5121) / @bkietz

<sub>**Note**: *This issue was originally created as [ARROW-5121](https://issues.apache.org/jira/browse/ARROW-5121). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by bkietz** [comment]
Since we're at c++17 and can use std::make_unique, this issue is obsolete.
