### ISSUE TITLE
BinaryArrow Byte Limitation

### ISSUE THREAD

**Issue by chebee7i** [apache/arrow#1673]
I'm having some trouble converting a DataFrame into a table:
```
import numpy as np
import pandas as pd
import pyarrow as pa

x = list('1' * 2**31)
y = pd.DataFrame({'x': x})
t = pa.Table.from_pandas(y)
# ArrowInvalid: BinaryArrow cannot contain more than 2147483646 bytes, have 2147483647
```
This is for pyarrow 0.8.0. Should it be creating chunked arrays automatically for me? Ultimately, my goal is to write to parquet.

**Comment by chebee7i** [comment]
Will do. Is there a simple workaround for the time being?

**Comment by chebee7i** [comment]
[ARROW-2227](https://issues.apache.org/jira/browse/ARROW-2227)

**Comment by wesm** [comment]
Closing in favor of tracking on JIRA
