### ISSUE TITLE
PyArrow: Missing libhdfs.so in Cloudera CDH 5.12

### ISSUE THREAD

**Issue by pederpansen** [apache/arrow#1685]
Hi,

my Cloudera CDH 5.12.2 installation does not provide a dynamic `libhdfs.so`, just a static `libhdfs.a`:

```
ls $HADOOP_HOME/lib/native
libhadoop.a       libhadoop.so        libhadooputils.a  libnativetask.a   libnativetask.so.1.0.0  libsnappy.so.1
libhadooppipes.a  libhadoop.so.1.0.0  libhdfs.a         libnativetask.so  libsnappy.so            libsnappy.so.1.1.4
```

Will PyArrow work under these conditons?

**Comment by wesm** [comment]
how did you install the distro?

**Comment by pederpansen** [comment]
I guess the "normal way": Cloudera Manager + Parcels

**Comment by wesm** [comment]
`libhdfs.so` may be in a different parcel -- from the look of Cloudera's Debian repos, it's included in the `libhdfs0-dev` Debian package

http://archive.cloudera.com/cdh5/debian/jessie/amd64/cdh/pool/contrib/h/hadoop/

**Comment by pederpansen** [comment]
I'll have a look. I'm on CentOS though, that might be another reason?

**Comment by wesm** [comment]
I assume the yum packages are structured similarly

**Comment by wesm** [comment]
Closing this. Please ask Cloudera for support

**Comment by chuyqa** [comment]
Ran into the same issue on CDH 5.13, Adding my "fix" for others that might stubmle on this:

`/opt/cloudera/parcels/CDH/` is symlinked to the current parcel dir, which contains the necessary `libhdfs.so`:
```
/opt/cloudera/parcels/CDH ->  /opt/cloudera/parcels/CDH-<version>
/opt/cloudera/parcels/CDH-<version>/lib64/libhdfs.so -> /opt/cloudera/parcels/CDH-<version>/lib64/libhdfs.so.0.0.0
```

Relevant export necessary
```python
os.environ['ARROW_LIBHDFS_DIR']="/opt/cloudera/parcels/CDH/lib64"
import pyarrow as pa
...
```
