### ISSUE TITLE
Unnecessary default_serialization_context?

### ISSUE THREAD

**Issue by mitar** [apache/arrow#1690]
Looking at the code it seems [these lines](https://github.com/apache/arrow/blob/master/python/pyarrow/serialization.py#L182-L185) are not necessary anymore?

**Comment by wesm** [comment]
My understanding is that that function gives a "fresh" context.

**Comment by mitar** [comment]
OK, I think it is used only in tests, but OK. It is a bit confusing because there is also `_default_serialization_context`. Maybe this one could be renamed to `make_default_serialization_context` or something. Anyway, not a critical thing.
