### ISSUE TITLE
[Plasma] Plasma On YARN

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#17022]
YARN is widely used for resource manager. Currently Plasma server serves as an external service for memory sharing across different clients. It is not a managed service by YARN. The resource used by Plasma should also been managed. Additionally, Plasma service can also been managed by YARN

**Reporter**: [Ferdinand Xu](https://issues.apache.org/jira/browse/ARROW-7588)

<sub>**Note**: *This issue was originally created as [ARROW-7588](https://issues.apache.org/jira/browse/ARROW-7588). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
