### ISSUE TITLE
How to get the number of buffers in a Field without TypeLayout?

### ISSUE THREAD

**Issue by yongyanw** [apache/arrow#1703]
With the support of typeLayout in Field class, the number of buffers in vector is the size of typeLayout. But without the support of typeLayout in Field, how to get the number of buffers in vector? For VariableWidthType, the number of buffers is 3; for PrimitiveType(List), the number of buffers is 1; for FixedWidthType, the number of buffers is 2. Is there any method that can get the number of buffers? Or is there any method can tell the type is VariableWidthType, PrimitiveType, or FixedWidthType?

**Comment by wesm** [comment]
hi @yongyanw is this a Java question, or C++?

**Comment by yongyanw** [comment]
This is a Java question. Thanks @wesm

**Comment by jacques-n** [comment]
Best to use the Arrow mailing list for this, type of thing, not GitHub issues. This is by definition. You should be able to write a static method that goes from ArrowType => buffers.

Closing this so you can continue to ask questions on the mailing list.
