### ISSUE TITLE
Using Plasma with xnd

### ISSUE THREAD

**Issue by saulshanabrook** [apache/arrow#1706]
I am looking into using the Plasma store to back [xnd objects](https://xnd.readthedocs.io/en/latest/xnd/index.html). Xnd uses [ndtypes](https://github.com/plures/ndtypes) to describe the shape and layout of the data. Ideally, we would use Plasma to allocate some memory with some type and then write directly to that, so we don't have to copy the data.

Is it possible to get a pointer to the allocated memory buffer after creating a plasma object? Or when you are retrieving one?

**Comment by wesm** [comment]
hi @saulshanabrook could we discuss further on the Arrow mailing list? Ideally these questions should all be addressed by the Plasma Python docs (https://github.com/apache/arrow/blob/master/python/doc/source/plasma.rst) but a) there are probably some documentation gaps that we can enumerate and b) we can probably add some APIs to help more with integration with third party Python libraries that have C extensions. We have a C++ API for pyarrow, for example

**Comment by saulshanabrook** [comment]
@wesm Sure. I used the "Start a thread" option on https://lists.apache.org/list.html?dev@arrow.apache.org. It hasn't showed up yet, is it going through review or should I try resubmitting just via email?

**Comment by xhochy** [comment]
@saulshanabrook you need to be subscribed to this mailing list to post messages. Also it is probably better to just sent an email instead of using this interface (it may work but it is hard to debug for us).

**Comment by saulshanabrook** [comment]
@xhochy Thank you, that worked for me: https://lists.apache.org/thread.html/f840f9d0205ac5dde90353f0107f9d8bbca62314b001efd615d0abb2@%3Cdev.arrow.apache.org%3E
