### ISSUE TITLE
pyarrow: uint32 type written to parquet files as INT64

### ISSUE THREAD

**Issue by davechallis** [apache/arrow#1725]
I'm trying to write some `uint32` values from a `Table` in pyarrow to a parquet file.

I'd expect them to be written to parquet as physical type `INT32` and logical type `UINT_32`, however they're being written as physical type `INT64` instead.

Some example code I'm using:

```
import pyarrow as pa
import pyarrow.parquet as pq

ids = pa.array([1,2,3,4,5], type=pa.uint32())
batch = pa.RecordBatch.from_arrays([ids], ['id'])
table = pa.Table.from_batches([batch])
print('Table schema:')
print(table.schema)
print()

pq.write_table(table, 'pa.pq')
parquet_file = pq.ParquetFile('pa.pq')
print('Parquet schema:')
print(parquet_file.schema)
```

this outputs:

```
Table schema:
id: uint32

Parquet schema:
<pyarrow._parquet.ParquetSchema object at 0x1145ba788>
id: INT64
```

If I write `uint32` data using the `fastparquet` module instead, then read it using `pyarrow.parquet.ParquetFile`, then I get the datatype I'm expecting, and the schema looks as follows:

```
<pyarrow._parquet.ParquetSchema object at 0x118beb248>
id: INT32 UINT_32
```

**Comment by wesm** [comment]
The reason for this is that the UINT_32 logical types are a relatively new feature of the Parquet format which is not in wide use -- so writing this metadata by default could result in data loss or incorrect query results. 

fastparquet has taken a more liberal view towards interoperability with other Parquet consumers where we've been a lot more conservative. If you read the files that fastparquet is producing in Apache Impala, for example, the results may be incorrect. 

Pass `version='2.0'` and I believe you will get the UINT_32 logical type.

**Comment by davechallis** [comment]
Perfect, thank you, just tested and works correctly.
