### ISSUE TITLE
Codec options

### ISSUE THREAD

**Issue by llchan** [apache/arrow#1727]
It seems that there is currently no way to set compression options (e.g. compression level). I'm not sure what granularity is the most sensible (probably at least per-file if not per-column), but even if we can only get a global configuration per codec that would be better than hardcoded values.

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2290. There are probably some other contact points (e.g. when writing Parquet files) that will need to be added

**Comment by kyleabeauchamp** [comment]
I'd like to upvote this; I encountered a use case where I wanted to improve compression ratio at the cost of compute and was sad to not have access to this knob.

**Comment by kyleabeauchamp** [comment]
PS: this benchmark suggests that Brotli in particular could gain another 10% or so compression ratio by a higher compression level: https://quixdb.github.io/squash-benchmark/#ratio-vs-decompression

**Comment by wesm** [comment]
Can you comment on the JIRA?

**Comment by kyleabeauchamp** [comment]
Done
