### ISSUE TITLE
Using write_to_dataset for large dataset

### ISSUE THREAD

**Issue by playqdrew** [apache/arrow#1749]
## GitHub Issues for Apache Arrow

I have a large dataset I am trying to write out as partitioned parquet like:

pq.write_to_dataset(table, '/Users/drewoconnor/pyarrowtest/', partition_cols=['year', 'month', 'day'], use_dictionary=False,  compression='snappy', use_deprecated_int96_timestamps=False)

Memory usage skyrockets and the process is killed by the OS: Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by wesm** [comment]
This is not surprising. We are using `df.groupby` to split the partitioned dataset, which has known memory use and performance problems. Could you open a JIRA about this? Perhaps someone can contribute a more memory-efficient alternative to using `df.groupby`?

**Comment by wesm** [comment]
cc @jreback

**Comment by wesm** [comment]
I have opened https://issues.apache.org/jira/browse/ARROW-2628
