### ISSUE TITLE
NotImplementedError for write_to_dataset using pa.hdfs.HadoopFileSystem

### ISSUE THREAD

**Issue by dsimmie** [apache/arrow#1753]
I'm not sure if this is by design (if not I can create a JIRA issue for it) but `pq.write_to_dataset` does not work with HDFS filesystem currently because the `_isfilestore()` check raises a `NotImplementedError`. If this check is removed from code or set to `True` then the code works and saves/loads a partitioned dataset fine:

Example code:

```
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

hdfs_fs = pa.hdfs.connect(host=hdfs_name_node, port=hdfs_port, user=os.environ['USER'], kerb_ticket=kerb_ticket)
df = pd.DataFrame({'a': np.arange(10**7), 'b': np.arange(10**7) % 10, 'c': np.arange(10**7) % 5})
table = pa.Table.from_pandas(df)
root_dir = '/tmp/test_partitioned_dataset.parquet'
hdfs_fs.mkdir(root_dir)
partition_cols = ['b']
pq.write_to_dataset(table, root_dir, partition_cols, hdfs_fs)
# Raises a NotImplementedError
```

Workaround that shows functionality works if check is removed:
```
def ignore_check(): return True
hdfs_fs._isfilestore = ignore_check
pq.write_to_dataset(table, root_dir, partition_cols, hdfs_fs)
loaded_df = hdfs_fs.read_parquet(root_dir).to_pandas()
pd.util.testing.assert_frame_equal(df.drop(partition_cols, axis=1), loaded_df.drop(partition_cols, axis=1).sort_index())
```

Is this expected behaviour?

Pyarrow version: 0.8.0

**Comment by wesm** [comment]
I just fixed this in https://github.com/apache/arrow/commit/a4307587b48aa8bf23e69b05b52739058302543b. This will be in 0.9.0
