### ISSUE TITLE
pyarrow-- reading selected columns from multiindex parquet file

### ISSUE THREAD

**Issue by timothydmorton** [apache/arrow#1771]
I have written a multi-indexed pandas dataframe to parquet using pyarrow.  If I try to read selected columns back using `pandas.read_parquet`,  I am finding that I have to pass the requested column(s) as a string-ified tuple; i.e. `columns = ["('a1', 'a2', 'a')", "('a1', 'a2', 'b')"]`, whereas if I am accessing the same columns directly from pandas, I could do the following (normal tuples): `df[[('a1', 'a2', 'a'), ('a1', 'a2', 'b')]`.  Is this intended behavior, or is there some way that I can pass the actual tuples to `pandas.read_parquet`?  The traceback I get when I try passing the tuples is the following:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>()

~/.local/lib/python3.6/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    255 
    256     impl = get_engine(engine)
--> 257     return impl.read(path, columns=columns, **kwargs)

~/.local/lib/python3.6/site-packages/pandas/io/parquet.py in read(self, path, columns, **kwargs)
    128         kwargs['use_pandas_metadata'] = True
    129         return self.api.parquet.read_table(path, columns=columns,
--> 130                                            **kwargs).to_pandas()
    131 
    132     def _validate_write_lt_070(self, df):

~/.local/lib/python3.6/site-packages/pyarrow/table.pxi in pyarrow.lib.Table.to_pandas (/arrow/python/build/temp.linux-x86_64-3.6/lib.cxx:46331)()

~/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py in table_to_blockmanager(options, table, memory_pool, nthreads, categoricals)
    565     # if we're reconstructing the index
    566     if has_pandas_metadata:
--> 567         columns = _reconstruct_columns_from_metadata(columns, column_indexes)
    568 
    569     # ARROW-1751: flatten a single level column MultiIndex for pandas 0.21.0

~/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py in _reconstruct_columns_from_metadata(columns, column_indexes)
    597         (level, col_index.get('numpy_type', level.dtype))
    598         for level, col_index in zip_longest(
--> 599             levels, column_indexes, fillvalue={}
    600         )
    601     ]

~/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py in <listcomp>(.0)
    596     levels_dtypes = [
    597         (level, col_index.get('numpy_type', level.dtype))
--> 598         for level, col_index in zip_longest(
    599             levels, column_indexes, fillvalue={}
    600         )

AttributeError: 'dict' object has no attribute 'dtype'
```

**Comment by timothydmorton** [comment]
Looking at the source on master @cpcloud , it looks like the code dealing with multiindices might have been updated since my version?  I'm using version 0.8.0, which seems to be the most recent release available via pip (and I get errors trying to install master from source).

**Comment by wesm** [comment]
Could you try out 0.9.0 (or 0.9.0.post1) and create a JIRA with the bug report info above if it's still not working? Thank you!

**Comment by rladeira** [comment]
I found the same issue here, using pyarrow version '0.17.1'. I could not select columns from a multi index dataframe saved as a parquet file. Is there some way to accomplish this? Read just some columns from a multindex parquet file? Something like:

`pd.read_parquet('file.parquet', engine='pyarrow', columns=[('a', 'b')])`

**Comment by wesm** [comment]
Please direct questions to user@arrow.apache.org or dev@arrow.apache.org. Thank you
