### ISSUE TITLE
[Format] Define logical data type that represents a "packed C struct" composed from other fixed-size primitive types

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#17787]
This would embed data like

```Java

struct Point {
  double x;
  double y;
  double z;
};
```

Here the struct could be embedded in a `FixedSizeBinary` with width 24. This is similar to structured data types in NumPy and other libraries

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-1790) / @wesm
#### PRs and other links:
- [GitHub Pull Request #3785](https://github.com/apache/arrow/pull/3785)

<sub>**Note**: *This issue was originally created as [ARROW-1790](https://issues.apache.org/jira/browse/ARROW-1790). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by ianmcook** [comment]
Closed due to inactivity
