### ISSUE TITLE
Writing a table to a multiple Feather files

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#1789]
Is there a supported way to write a `Table` to multiple `feather` files? Or even one?

My current solution is to convert the table to batches and write each column

**Comment by dmadeka** [comment]
Would it be possible to do this multi-threaded?

**Comment by wesm** [comment]
Possibly, but it might be IO-bound depending on the dataset. Could you please open a JIRA describing the feature and desired API? Thanks

**Comment by dmadeka** [comment]
Done! https://issues.apache.org/jira/browse/ARROW-2358?jql=text%20~%20%22Feather%22
