### ISSUE TITLE
[C++] Filesystem implementation for Azure Blob Storage

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18014]
Subissues:

* GH-35903
* GH-36886
* GH-37511
* GH-38330
* GH-38333
* GH-38335
* GH-38597
* GH-38598
  * GH-39262
  * GH-39318
  * GH-39320
  * GH-39343
  * GH-39344
  * GH-39345
  * GH-39449
* GH-38699
* GH-38700
* GH-38701
* GH-38702
* GH-38703
* GH-40074
* GH-38704
* GH-38705
* GH-38758
* GH-38772
* GH-38999
* GH-39069
  * GH-41034
* GH-39119
* GH-39292
* GH-39297
* GH-40025
* GH-40026
* GH-40028
* GH-40035
* GH-40036
* GH-40037
* GH-40052
* GH-40057
* ...

----

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-2034) / @wesm
**Assignee**: [Shefali Singh](https://issues.apache.org/jira/browse/ARROW-2034)
#### Related issues:
- [[C++] Filesystem implementation for Azure Data Lake](https://github.com/apache/arrow/issues/25673) (is cloned by)
- [[R] Expose Azure Blob Storage filesystem](https://github.com/apache/arrow/issues/32123) (is depended upon by)
#### Original Issue Attachments:
- [azfs.cc](https://issues.apache.org/jira/secure/attachment/13050104/azfs.cc)
- [azfs.h](https://issues.apache.org/jira/secure/attachment/13050103/azfs.h)
#### PRs and other links:
- [GitHub Pull Request #12914](https://github.com/apache/arrow/pull/12914)

<sub>**Note**: *This issue was originally created as [ARROW-2034](https://issues.apache.org/jira/browse/ARROW-2034). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by av8or1** [comment]
We too are in need of this feature.  Any word as to whether it will be included in the version 11 release?  Seems like the deadline is kinda tight at this point.

**Comment by pitrou** [comment]
@h-vetinari Do you know if there's a conda-forge package for the Azure Blob Storage C++ library? I couldn't find one.

**Comment by h-vetinari** [comment]
> @h-vetinari Do you know if there's a conda-forge package for the Azure Blob Storage C++ library? I couldn't find one.

I'm not aware of any either, but I don't know. What would be the sources of that C++ lib? If it's open source we could bring it to conda-forge eventually of course.

**Comment by Tom-Newton** [comment]
I think we're ready to start implementing the filesystem itself. Looking at how [GCS was done](https://github.com/apache/arrow/commits/main?before=9b6be29f431705ce1f85cc218c66d4d03698f06b+35&branch=main&path%5B%5D=cpp&path%5B%5D=src&path%5B%5D=arrow&path%5B%5D=filesystem&path%5B%5D=gcsfs.cc&qualified_name=refs%2Fheads%2Fmain) the next part was an implementation of `arrow::io::InputStream` and `OpenInputStream`. 

However it looks like `arrow::io::RandomAccessFile` is a superset of `arrow::io::InputStream` so I'm think it makes sense to just implement `arrow::io::RandomAccessFile`. This is what https://github.com/apache/arrow/pull/12914 did. 

I would propose we move forward with implementing `arrow::io::RandomAccessFile`, `OpenInputStream` and `OpenInputFile` as in https://github.com/apache/arrow/pull/12914. One change I would suggest is to avoid depending on whether the storage account has hierarchical namespace enabled. Hierarchical namespace is important for listing and renames if you want to make them faster but for blob reads I don't think it should matter, and it adds complexity.

**Comment by kou** [comment]
It makes sense.
Could you open a new issue for it and work on it? @srilman may want to help this.

**Comment by Tom-Newton** [comment]
I have not started any of https://github.com/apache/arrow/issues/38330, https://github.com/apache/arrow/issues/38333 or https://github.com/apache/arrow/issues/38335 yet. I plan to start working on one of them relatively soon though.

**Comment by felipecrv** [comment]
> I have not started any of #38330, #38333 or #38335 yet. I plan to start working on one of them relatively soon though.

Thank you! If I start working on one of them I will assign the issue to myself to let you know I'm on it.

**Comment by mavam** [comment]
@Tom-Newton +1 from an outside user for this feature. Our users are actively asking for it. Happy to help testing.

**Comment by kou** [comment]
I've added subissue list in this description.

**Comment by av8or1** [comment]
Hi- I'm looking to contribute.  This would be my first foray into the process however, so could Tom or other recommend a fairly straightforward task?  I was considering [#38703](https://github.com/apache/arrow/issues/38703) ... would that be a good candidate?

**Comment by Tom-Newton** [comment]
> I was considering [#38703](https://github.com/apache/arrow/issues/38703) ... would that be a good candidate?

I think that would be a good one to start with. Things tend to get more complicated when they deal with directories. You can assign yourself by commenting "take" on the GitHub issue. 

It will be great to have more contributors working on this 🙂

**Comment by Tom-Newton** [comment]
Does anyone have any thoughts on starting python bindings for this soon? I know the filesystem is not fully implemented but a lot of it is and I think its enough to already be very useful. For example my usecase, actually only needs random access file reads and default credential auth. 

I would probably suggest adding one or 2 more auth methods so we know how the configuration is going to look then I think we could create the python bindings.

**Comment by nosterlu** [comment]
I can help out testing python bindings! Looking forward to testing to see how this improve read speeds compared vs adlfs and pyarrow.

I use Azure storage with either a token (created with adlfs and web authentication) or a connection string directly. So one of those two ways to connect would be neccessary for me to help testing.

Mostly I connect to a hive partitioned parquet dataset, but also towards individual files.

**Comment by kou** [comment]
Could you open a new issue for Python bindings and work on it?
We don't need to mark the new issue as a sub issue of this issue because it's a separated task. (This issue focuses on C++ implementation.)

**Comment by raulcd** [comment]
I am moving this umbrella issue to 16.0.0

**Comment by felipecrv** [comment]
> I am moving this umbrella issue to 16.0.0

That's fine. Thanks.

**Comment by av8or1** [comment]
kou/felipecrv - How close is this to being done?  I see a few green-colored items in the list above, but they seem to be completed already (at least the ones I looked at did).  Is there anything else we can work on?  Will this make it into version 16.0.0?  Thanks

**Comment by felipecrv** [comment]
@av8or1 most of it works now. `s3fs` doesn't even support `Move`. `AzureFileSystem` supports `Move` on accounts with HNS enabled. You don't have to wait for this issue to be closed to start using what's already merged and ready to be part of the 16.0.0 release.

**Comment by av8or1** [comment]
Hi felipe- Thanks.  Well, the company can't utilize any library that isn't an official release.  I suppose that I could begin writing the code that will utilize the ADLS stuff now, then when 16.0.0 is released (April?), I would be able to produce our product shortly thereafter.  What remains to be completed, by the way? Anything I could help with?  Thanks

**Comment by felipecrv** [comment]
@av8or1 as I said above: `Move` with Blobs API (not a critical feature at all, `s3fs` doesn't even support `Move`). Python bindings (PR is open), and URI parsing (PR is open). Are any of these a dealbreaker for you? Everything else will be available in 16.0.0.

**Comment by av8or1** [comment]
@felipecrv OK thank you.  Work has been busy.  Just now looking at this again.  It appears that @kou has completed the URI parsing business (#40028).  Thus I will prepare on my end to use the library when it is released.  Hopefully in April.  Thanks

**Comment by wirable23** [comment]
> Everything else will be available in 16.0.0.

@felipecrv do you know when 16.0.0 would be available?

**Comment by felipecrv** [comment]
> > Everything else will be available in 16.0.0.
> 
> @felipecrv do you know when 16.0.0 would be available?

In April. The time it takes for the release also depends on how smooth the packaging and publishing process goes.

**Comment by Tom-Newton** [comment]
I think ideally https://github.com/apache/arrow/issues/40036 would be taken care of before the 16.0.0 release. I don't have any real world performance numbers but I suspect write performance is currently a bit disappointing.

**Comment by raulcd** [comment]
Hi @Tom-Newton there's no planned release before 16.0.0
The feature freeze for 16.0.0 is planned for the 8th of April.

**Comment by felipecrv** [comment]
I opened a MINOR PR expanding some of the docstrings: #40838

**Comment by raulcd** [comment]
There are some subtasks still opened. @felipecrv should I tag this umbrella issue as 17.0.0?

**Comment by felipecrv** [comment]
> There are some subtasks still opened. @felipecrv should I tag this umbrella issue as 17.0.0?

`AzureFileSystem` is already usable and feature-complete even without these issues open. I'm in favor of closing (marking it as complete) making it part of the 16.0 release in the logs.

**Comment by kou** [comment]
Let's close this as complete.
We don't need an umbrella issue for `AzureFileSystem`. We can just use separated issues like other components.

**Comment by kou** [comment]
Note that the current `AzureFileSystem`'s `CopyFile()` doesn't work with Azure hierarchical namespace support. See also: #41095

Some other `AzureFileSystem` implementations for Azure hierarchical namespace support have some problems: #41034
I want to add the fix of this (#41068) to 16.0.0.
