### ISSUE TITLE
[C++][Plasma] More primitive operations on plasma store

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18024]
Hi Developers,

I found plasma store very useful – it's fast and simple to use. However, I think there are more operations that can make it a more general IPC/messaging tool and potentially helpful in more scenarios.

Conceptually, an object store can support the following "put" methods:
1. Evict when full
1. Wait for space when full, perhaps with a timeout (i.e. blocking)
1. Return failure when full (i.e. non-blocking)
   
   And the following "get" methods:
1. Wait for the object to appear (i.e. blocking)
1. Return failure when object doesn't exist (i.e. non-blocking)
1. Remove the object after get
   
   Some of the above features can be implemented with others. But some of them are primitives (e.g. return failure when full) that needs to be supported.
   
    
   
   My use case: I wanted to use plasma to send/recv large buffers between processes, i.e. build a message passing interface on top of shared memory. Plasma has made it quite easy (only have to send/recv the id) and efficient (faster than unix pipe). But "evict when full" is now the only available "put" method, so that could create many trouble if I want to ensure message delivery.

**Reporter**: [Yuxin Wu](https://issues.apache.org/jira/browse/ARROW-2045)

<sub>**Note**: *This issue was originally created as [ARROW-2045](https://issues.apache.org/jira/browse/ARROW-2045). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
