### ISSUE TITLE
pyarrow-0.9.0: OS X package missing from PyPi

### ISSUE THREAD

**Issue by pyykkis** [apache/arrow#1816]
Hi, it seems that the latest 0.9.0 release for OS X hasn't been published in PyPi. I hope OS X is still a supported platform?

https://pypi.python.org/pypi/pyarrow/0.9.0

Thanks in advance!

**Comment by kou** [comment]
We're working on it. Please wait for a while!
#1810

**Comment by wesm** [comment]
@pyykkis we would appreciate help with packaging -- this project is supported by volunteers

**Comment by pyykkis** [comment]
Thanks @kou, I didn't notice there was an existing issue as closed issues are not shown by default by github issue filter.

Thanks @wesm, I forked the repo and looked around a bit and stumbled up to
https://github.com/apache/arrow-dist/pull/25. Looks like @xhochy has pretty much all set. I'm happy to help if there's anything left to do.

**Comment by xhochy** [comment]
`pyarrow==0.9.0.post1` is now on PyPI
