### ISSUE TITLE
Supported Python versions

### ISSUE THREAD

**Issue by michaelmior** [apache/arrow#1834]
I don't see documented anywhere what versions of Python are supported by pyarrow. Am I missing this somewhere? If not, it would be great if this could be added.

**Comment by xhochy** [comment]
We support 2.7, 3.4, 3.5 and 3.6 but will drop support for 3.4 soon (mainly we will not include it anymore in our test matrix and won't upload binary releases for it, it may still work).

The Python package https://pypi.python.org/pypi/pyarrow declares the supported versions (see the setup.py).

**Comment by michaelmior** [comment]
Thanks! Even though it's listed in `setup.py` it would be great if this were mentioned in the documentation.
