### ISSUE TITLE
Cannot run spark-submit with arrow 0.9.0

### ISSUE THREAD

**Issue by ruixuel** [apache/arrow#1842]
Hi, I switch from arrow 0.8.0 to 0.9.0 and package the fat jar to run on spark-submit. Arrow 0.8.0 works well on spark-submit. however, arrow 0.9.0 does not work correctly. I get the following error:

Exception in thread "main" java.lang.IllegalAccessError: class org.apache.arrow.vector.complex.impl.SingleStructReaderImpl cannot access its superclass org.apache.arrow.vector.complex.impl.AbstractFieldReader

In addition, I can run my program with arrow 0.9.0 well through sbt run, but it does not work through spark-submit.

**Comment by xhochy** [comment]
cc @BryanCutler may provide some information on how to debug this better.

**Comment by BryanCutler** [comment]
Hi @ruixuel , Spark 2.3 was built with Arrow 0.8.0 and the 0.9.0 jars are not binary compatible.  Spark will have to be rebuilt for it to work, but it does require some code changes.  You can follow https://issues.apache.org/jira/browse/SPARK-23874 for the upgrade, which is planned to be done some time in the next couple weeks but won't be official until the next Spark release.

I'll close this as it deals with upgrading in Spark.
