### ISSUE TITLE
[C++][Dataset] Allow more aggresive implicit casts for literals

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18481]
After ARROW-8919, a literal in an Expression may cause unnecessary implicit casting of a column. For example `equal(field_ref("i8"), literal(1))` will cause column i8 to be promoted to the type of the literal (int32) for comparison. Since we have access to the literal value at bind time we could examine `1` and determine that it can safely be \*de\*moted to int8, which produces a semantically equivalent and more performant filter.

**Reporter**: [Ben Kietzman](https://issues.apache.org/jira/browse/ARROW-11402) / @bkietz
#### PRs and other links:
- [GitHub Pull Request #15180](https://github.com/apache/arrow/pull/15180)

<sub>**Note**: *This issue was originally created as [ARROW-11402](https://issues.apache.org/jira/browse/ARROW-11402). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by westonpace** [comment]
Issue resolved by pull request 15180
https://github.com/apache/arrow/pull/15180
