### ISSUE TITLE
[C++] Push down projection and selection to S3 Select

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18506]
Amazon S3 Select [1], an S3 feature generally available since April 2018 [2], can improve S3 read performance by allowing S3 clients to use a limited subset of SQL to specify projection and selection [3] on data in some formats [4]. It would be interesting to try using this in Arrow and to measure its effects on S3 read performance under various conditions.

[1] <https://aws.amazon.com/blogs/aws/s3-glacier-select/>

[2] <https://aws.amazon.com/about-aws/whats-new/2018/04/amazon-s3-select-is-now-generally-available/>

[3] <https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-glacier-select-sql-reference-select.html>

[4]<https://docs.aws.amazon.com/cli/latest/reference/s3api/select-object-content.html>

**Reporter**: [Ian Cook](https://issues.apache.org/jira/browse/ARROW-11558) / @ianmcook

<sub>**Note**: *This issue was originally created as [ARROW-11558](https://issues.apache.org/jira/browse/ARROW-11558). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by deepzliu** [comment]
hi, any progress on this issue？

**Comment by westonpace** [comment]
> hi, any progress on this issue？

No, as @ianmcook summarized:

> This combined with the limited set of object data file formats, encodings, and compression formats that S3 Select supports certainly makes the practical applications of S3 Select within Arrow fairly narrow

Given this, I don't think there has been much motivation to try it.

**Comment by Susmit07** [comment]
@asfimport did you guys implemented it, we had a similar use case,

but i see few downside, getting the response in json format then convert JSON data to an Arrow Table and yield as RecordBatch

in memory we need to convert

and if we have wildcard file patterns then we need to read the data per file and send back as arrow streams per file in a loop

Any other better way ?

**Comment by ianmcook** [comment]
This was not implemented, and [AWS announced earlier this year that they are closing access to S3 Select](https://www.infoworld.com/article/3484870/aws-closes-several-cloud-services-to-new-customers.html). Closing as not planned.
