### ISSUE TITLE
Problem when install javascript implementation

### ISSUE THREAD

**Issue by gabomgp** [apache/arrow#1856]
When installing on windows with npm, the implementation of arrow in javascript, using the command:

    npm install @apache-arrow/ts --save

the console output is showing:

	npm ERR! path E:\Source\Repos\CollaborativeValueNetworks\frontend\node_modules\@apache-arrow\ts\bin\arrow2csv.js
	npm ERR! code ENOENT
	npm ERR! errno -4058
	npm ERR! syscall chmod
	npm ERR! enoent ENOENT: no such file or directory, chmod 'E:\Source\Repos\CollaborativeValueNetworks\frontend\node_modules\@apache-arrow\ts\bin\arrow2csv.js'
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent

	npm ERR! A complete log of this run can be found in:
	npm ERR!     C:\Users\GrupoLogyca\AppData\Roaming\npm-cache\_logs\2018-04-08T08_34_17_054Z-debug.log

maybe, i have to use other package?

**Comment by gabomgp** [comment]
But, it woks ok if i use the command:

    npm install apache-arrow --save

maybe a problem with ts package?

**Comment by wesm** [comment]
@trxcllnt any ideas on this one?

**Comment by trxcllnt** [comment]
@wesm yeah, the TypeScript module's `package.json` was including a reference to a JS file that doesn't apply to the TS module. I fixed the issue with the build in the pending JS-writer PR.

**Comment by wesm** [comment]
Great, I will close this issue, then. @gabomgp keep an eye out for the next JS release; if you hit the issue again please open a JIRA. Thanks
