### ISSUE TITLE
arrow javascript implementation supports serialized dictionary of dataframes?

### ISSUE THREAD

**Issue by gabomgp** [apache/arrow#1870]
I'm serializing a dictionary with dataframes values in python. I want to read that in browser with javascript implementation, but i can't find the way, is it a way?

**Comment by gabomgp** [comment]
Thanks, i used json instead of arrow for serialization between frontend and backend due to bug in pandas that disallow work with  dataframe deserialized from arrow data. I think with pandas 0.23, the bug is fixed, but i'm not sure.

**Comment by domoritz** [comment]
I wanted to do the same. Here are the two related issues: https://github.com/apache/arrow/issues/2119 and https://github.com/apache/arrow/issues/2123
