### ISSUE TITLE
[JS]Is there a JS ArrowFlight implementation/example?

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18767]
Have requirements for building JavaScript data visualizer that connects to Dremio.  Would like to do it with ArrowFlight.  I see the Arrow JS project and have played with some of the cookbook code but don't see any ArrowFlight examples or implementations.   Am I missing something?  Any pointers would be appreciated.

**Reporter**: [John E. Conlon](https://issues.apache.org/jira/browse/ARROW-13515)

<sub>**Note**: *This issue was originally created as [ARROW-13515](https://issues.apache.org/jira/browse/ARROW-13515). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by zeodtr** [comment]
@asfimport In Node.js environment, there is a gRPC implementation (https://www.npmjs.com/package/@grpc/grpc-js). So, it is possible and it would be useful to support Arrow Flight in JavaScript (at least for Node.js).
