### ISSUE TITLE
[CI] Docker push is failing with authentication fail

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18785]
See https://github.com/apache/arrow/runs/3314893335?check_suite_focus=true, Integration, step Docker Push

**Reporter**: [Jorge Leitão](https://issues.apache.org/jira/browse/ARROW-13621) / @jorgecarleitao
#### Related issues:
- [Wrong dockerhub credentials](https://issues.apache.org/jira/browse/INFRA-21809) (is caused by)

<sub>**Note**: *This issue was originally created as [ARROW-13621](https://issues.apache.org/jira/browse/ARROW-13621). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Outdated
