### ISSUE TITLE
[Python] Enable direct interaction of GPU Objects in Python

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18788]
Plasma can now manage objects on the GPU, but in order to use this functionality in Python, there needs to be some way to represent these GPU objects in Python that allows computation on the GPU.

The easiest way to enable this is to rely on a third party library, such as Pytorch, which will allow us to use all of its existing functionality.

**Reporter**: [William Paul](https://issues.apache.org/jira/browse/ARROW-2512) / @Wapaul1
#### PRs and other links:
- [GitHub Pull Request #1948](https://github.com/apache/arrow/pull/1948)

<sub>**Note**: *This issue was originally created as [ARROW-2512](https://issues.apache.org/jira/browse/ARROW-2512). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
Plasma was removed on 12.0.0. This can be closed.
https://github.com/apache/arrow/issues/33243
