### ISSUE TITLE
pyarrow: Segfault with pyarrow.deserialize_pandas on OS X

### ISSUE THREAD

**Issue by travisbrady** [apache/arrow#1884]
I've encountered a segfault when trying to use Arrow as a dataframe serialization format over http between a requests-based client and a Sanic-based web server.
My end goal is to get this working between a Java-based client and a Python/Sanic-based server.

This repo: https://github.com/travisbrady/sanic-arrow has all code and output showing this behavior.

Python details:
```
$ python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
```

OS:
```
$ uname -a
Darwin Traviss-Air 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
```

**Comment by xhochy** [comment]
@travisbrady Can you open an issue on https://issues.apache.org/jira/projects/ARROW/summary as this looks a like a more complicated problem?

**Comment by travisbrady** [comment]
Ok, created an official Jira issue here: https://issues.apache.org/jira/browse/ARROW-2459
