### ISSUE TITLE
Extracting column names from parquet files

### ISSUE THREAD

**Issue by frytime32** [apache/arrow#1885]
Hi,

I am working with very large datasets and I have found parquet files and arrow to be excellent tools, so thank you!

However, I am having an issue extracting ONLY the column names from a parquet file. Right now, n order to figure out the column names, I have to read in the entire dataset into pandas and then extract the column names from there, which takes far too long (several seconds). Is there a way I can extract only the column names without having to read in the entire dataset?

**Comment by xhochy** [comment]
You can use the following snippet that will only read the footer of the Parquet (your underlying I/O source needs to support seeking).

```python
p = ParquetFile(filename_or_reader)
p.schema.names
```
