### ISSUE TITLE
[C++] [CI] macOS failures on githubactions runs

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#18874]
Starting recently, we are getting filures on macos with c++ https://github.com/apache/arrow/actions/runs/1307843484

```Java

DocumentRoot is /usr/local/var/www.
320

321
The default ports have been set in /usr/local/etc/httpd/httpd.conf to 8080 and in
322
/usr/local/etc/httpd/extra/httpd-ssl.conf to 8443 so that httpd can run without sudo.
323

324
To start httpd:
325
  brew services start httpd
326
Or, if you don't want/need a background service you can just run:
327
  /usr/local/opt/httpd/bin/httpd -D FOREGROUND
```

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-14225) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-14225](https://issues.apache.org/jira/browse/ARROW-14225). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing at outdated.
