### ISSUE TITLE
Integrating pyarrow with RabbitMQ pika python

### ISSUE THREAD

**Issue by alphinside** [apache/arrow#1902]
Hi, I'm trying to serialize a large numpy array using pyarrow and I'm trying this format for the producer side :
```
data = np.random.random((10, 60, 60, 3))
start = time.time()
data_dict = dict()
data_dict['data'] = data
data_dict['time'] = start

buf = pyarrow.serialize(data, context=context).to_buffer()

buf.to_pybytes()
```

However on the consumer side, I found this error when using this function to deserialize them 

```
data = pyarrow.deserialize(buf)
```

Error:
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or booleanarrays are valid indices
```

Can you help me? I didnt found any documentation about pyarrow to read from bytes

**Comment by pitrou** [comment]
What is the type of `data` on the consumer side? Both `pa.deserialize(buf)` and `pa.deserialize(buf.to_pybytes())` work here.

**Comment by wesm** [comment]
Closing as stale. @alphinside if you can provide instructions for us to reproduce this please create a JIRA so we can have a look
