### ISSUE TITLE
[JS] Benchmark script improvements

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#19146]
- We don't seem to be using `perf/config.js` anymore. Let's remove it and replace it with `perf/table_config.js`.
- Make target and module configurable.
- Make it possible to select benchmarks to run with a RegEx

**Reporter**: [Brian Hulette](https://issues.apache.org/jira/browse/ARROW-2762) / @TheNeuralBit

<sub>**Note**: *This issue was originally created as [ARROW-2762](https://issues.apache.org/jira/browse/ARROW-2762). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
We now only have `perf/comfig.ts`. I think this can be closed.
