### ISSUE TITLE
[Packaging] Add unit tests for crossbow

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#19231]
As this code grows we should start adding unit tests to make sure we can make changes safely.

**Reporter**: [Phillip Cloud](https://issues.apache.org/jira/browse/ARROW-2858) / @cpcloud

<sub>**Note**: *This issue was originally created as [ARROW-2858](https://issues.apache.org/jira/browse/ARROW-2858). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by cpcloud** [comment]
Given the age of this issue that I created, I'm closing it.
