### ISSUE TITLE
[Python] Pandas roundtrip doesn't preserve list of datetime objects

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#19770]
Adding the following to the pandas_example.py::dataframe_with_lists functionn:

```python

datetime_data = [
     [datetime(2015, 1, 5, 12, 0, 0), datetime(2020, 8, 22, 10, 5, 0)],
     [datetime(2024, 5, 5, 5, 49, 1), datetime(2015, 12, 24, 22, 10, 17)],
     [datetime(1996, 4, 30, 2, 38, 11)],
     None,
     [datetime(1987, 1, 27, 8, 21, 59)]
]

type = pa.timestamp('s'|'ms'|'us'|'ns')
```

breaks the tests cases, because the roundtrip doesn't preserve the object type.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-3448) / @kszucs
#### Related issues:
- [[Python] timestamp_as_object support for pa.Table.to_pandas in pyarrow](https://github.com/apache/arrow/issues/21818) (relates to)
#### PRs and other links:
- [GitHub Pull Request #10866](https://github.com/apache/arrow/pull/10866)

<sub>**Note**: *This issue was originally created as [ARROW-3448](https://issues.apache.org/jira/browse/ARROW-3448). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by AlenkaF** [comment]
I think this can be closed as the datetime object can now be preserved with the use of `timestamp_as_object=True`:

```python
import pyarrow as pa
pa.__version__
# '12.0.0.dev279+gb20734438'

import pandas as pd
from datetime import datetime

datetime_data = [
     [datetime(2015, 1, 5, 12, 0, 0), datetime(2020, 8, 22, 10, 5, 0)],
     [datetime(2024, 5, 5, 5, 49, 1), datetime(2015, 12, 24, 22, 10, 17)],
     [datetime(1996, 4, 30, 2, 38, 11)],
     None,
     [datetime(1987, 1, 27, 8, 21, 59)]
]

df = pd.DataFrame({'a': datetime_data})
table = pa.table(df)
table.to_pandas(timestamp_as_object=True).values
# array([[array([datetime.datetime(2015, 1, 5, 12, 0),
#                datetime.datetime(2020, 8, 22, 10, 5)], dtype=object)],
#        [array([datetime.datetime(2024, 5, 5, 5, 49, 1),
#                datetime.datetime(2015, 12, 24, 22, 10, 17)], dtype=object)],
#        [array([datetime.datetime(1996, 4, 30, 2, 38, 11)], dtype=object)],
#        [None],
#        [array([datetime.datetime(1987, 1, 27, 8, 21, 59)], dtype=object)]],
#       dtype=object)
```

There is still an issue where the list roundtrips to a numpy array of numpy arrays, but there are other issues tracking this (https://github.com/apache/arrow/issues/34574, https://github.com/apache/arrow/issues/20222) - we could think of supporting an option to preserve list dtype also. But this should come after the optimisation of `to_pylist` (https://github.com/apache/arrow/issues/28694)
