### ISSUE TITLE
Rust: Buffer with capacity

### ISSUE THREAD

**Issue by Kane-Sendgrid** [apache/arrow#1979]
@andygrove Is it possible to create empty Buffer with allocated data of given size, so we can allocate Buffer and then fill data?

**Comment by andygrove** [comment]
Yes, absolutely. You should create a builder using this method: https://github.com/apache/arrow/blob/master/rust/src/builder.rs#L40-L49

Then call `slice_mut` to get the buffer that you can write to.

Finally, call `finish` to get the `Buffer<T>`

**Comment by Kane-Sendgrid** [comment]
@andygrove Perfect, thanks!
