### ISSUE TITLE
Feature request: R-style NA values

### ISSUE THREAD

**Issue by st-pasha** [apache/arrow#1984]
In R, boolean/integer NA values are stored as the largest negative value representable by the corresponding C type (i.e. `INT_MIN`). Likewise, numeric NA values are represented as NaNs with a specific double payload value.  

I understand that Arrow already has a way to represent NAs generically, via a numpy-style bitmask marking the null values. And when passing the data between R and numpy, it is necessary to translate the data between these two representations. Thus, the "zero-copy data transfer" promise cannot possibly be fulfilled in this case. On the other hand it is possible to zero-copy transfer data between different numpy instances (eg. across processes, or by saving the data to a file), because the Arrow format implements numpy NA model natively.

What is currently not possible to do is to zero-copy transfer data across different R instances with Arrow: one instance has to serialize NAs into a bitmask, while the other has to re-apply the mask to the data.

A simple fix to address this issue is to introduce an optional boolean flag `r_nas` (or `embedded_nas`) on `Int`/`Bool`/`Time`/etc. types which would signal that NA values are stored in the data itself rather than as a separate mask. It would be a simple task for a consumer implementation to automatically recode the data into their preferred representation. Such change would be strictly beneficial for R users, while not imposing any cost on Python users.

**Comment by pitrou** [comment]
I think this needs further discussion (perhaps on the arrow-dev mailing-list?) since it has far-reaching implications -- the new format would have to be understood by any Arrow-consuming library.

**Comment by wesm** [comment]
Closing in favor of further discussion on mailing list and/or JIRA
