### ISSUE TITLE
[RUST] ListBuilder::with_capacity() should have separate capacities for data and offsets

### ISSUE THREAD

**Issue by Kane-Sendgrid** [apache/arrow#1987]
@andygrove I think `ListBuilder::with_capacity()` should accept 2 capacity arguments both for data and offsets. Because ListBuilder is variable element size, size of data will not match to capacity needed to store offsets e.g.:

```
ListBuilder<u8> which stores 1_000 slices of 10 bytes each.
If I want to allocate data for with_capacity for 10_000 bytes, that gonna allocate 10_000 offsets, whereas I need only 1_000 and vice versa.
```

**Comment by wesm** [comment]
@Kane-Sendgrid could you open a JIRA about this? Thank you

**Comment by wesm** [comment]
Closing as stale
