### ISSUE TITLE
[RUST] .len methods should return usize instead of i32

### ISSUE THREAD

**Issue by Kane-Sendgrid** [apache/arrow#1988]
@andygrove To be compatible with stdlib .len methods Buffer.len should return usize instead of i32?

**Comment by andygrove** [comment]
Yes, this is true. I used i32 because the spec said to, but apparently the spec is out of data on this point. I fixed this in this PR https://github.com/apache/arrow/pull/1971 which hasn't bee merged yet,

BTW, we use JIRA for issues. Here is the URL: https://github.com/apache/arrow/pull/1971

**Comment by Kane-Sendgrid** [comment]
Oh, sorry and thanks!
