### ISSUE TITLE
pyarrow 0.9.0 not cross-platform compatible on projects with pinned dependencies

### ISSUE THREAD

**Issue by danpalmer** [apache/arrow#1992]
We run a Python project with pinned dependencies for security and production-stability.

We recently added 0.9.0, and found that it broke on macOS development machines (as cython is not a declared dependency), but when upgrading to 0.9.0.post1, we found that our build broke because that is not available for Linux.

We can't use different versions on different OSes, and in fact don't want to specifically because this usually leads to instability of production builds.

For this reason, we are currently unable to use 0.9.0. Our suggested remediation is a 0.9.1 release for macOS and Linux with wheels. Note: we would advise against a 0.9.0.post2 release for this as it goes against our interpretation of [PEP440](https://www.python.org/dev/peps/pep-0440/#post-releases).

**Comment by danpalmer** [comment]
Ping on this. The package is currently broken for projects that pin dependencies (which is Python best practice, as well as being very common for repeatable builds and security purposes).

**Comment by xhochy** [comment]
We will fix this on the next release but it is quite a lot of work to make releases for Arrow due to its broad range of packages. If you want this fixed sooner, please help us to streamline the release process.

**Comment by xhochy** [comment]
To help us to get out a new release, it would be helpful when someone could assist in the review of https://github.com/apache/arrow/pull/1869 This PR gives us tooling to avoid such situations in the future again.

**Comment by danpalmer** [comment]
Hi, thanks for the update, but I think it would be best to leave the issue open so that the community can see when it is fixed, rather than when it is _triaged_. We'll be following this to see when we can start using arrow again.

**Comment by xhochy** [comment]
We only use Github issues for simple communication, for tracking everything is logged in https://issues.apache.org/jira/projects/ARROW

**Comment by danpalmer** [comment]
@xhochy cool. Could you add a link here to the issue in Jira so that people who want to track it can do there?

**Comment by xhochy** [comment]
Things to track in JIRA are:

- PR to get a better packaging infrastructure: https://issues.apache.org/jira/browse/ARROW-2430
- The upcoming release: https://issues.apache.org/jira/projects/ARROW/versions/12342562 (We will probably skip 0.9.1 and do a 0.10)

**Comment by jstray** [comment]
+1 for leaving it open until the next release.

**Comment by peterclearmetal** [comment]
In the meantime a workaround to support 0.9.0 in cross platform (mac + linux) environments is to use this in your requirements.txt:

```
# Use Pyarrow 0.9.0.post1 where available (mac-only hotfix) otherwise use 0.9.0.
pyarrow>=0.9.0,<=0.9.0.post1
```

Or on the command-line:
```
pip install "pyarrow>=0.9.0,<=0.9.0.post1"
```

**Comment by tekumara** [comment]
```
pipenv install "pyarrow>=0.9.0,<=0.9.0.post1"
```

errors with

```
An error occurred while installing futures==3.2.0! Will try again.
An error occurred while installing pyarrow==0.9.0.post1! Will try again.
```

On Linux. Works on Mac.

**Comment by wesm** [comment]
What is the error?

**Comment by notpeter** [comment]
You've provided no mention of Linux distribution, python version or other environmental details so I'm not sure how you expect someone to help you.

@tekumara We use the pip/requirements line I mentioned above on Mac and Linux without issue.
For example this works, so your issue is likely environment specific.
```
docker run -it ubuntu:xenial

apt-get update; apt-get install -y python3-dev python3-pip
pip3 install "pyarrow>=0.9.0,<=0.9.0.post1"
python3 -c "import pyarrow; print(pyarrow.__version__)"
```
Similarly Python2/pip2 worked fine. 

PS @peterclearmetal is my work GitHub. Sorry for the confusion.

**Comment by tekumara** [comment]
I was hoping your workaround for `pip` would work for `pipenv` but it uses `0.9.0.post1` regardless. Some more detail as requested:

```
# python 3.5.2
docker run -it ubuntu:xenial

apt-get update; apt-get install -y python3-dev python3-pip
cd /tmp
pip3 install pipenv
export LC_ALL=C.UTF-8;export LANG=C.UTF-8
pipenv install -v "pyarrow>=0.9.0,<=0.9.0.post1"

....
                          ROUND 1
Current constraints:
  pyarrow<=0.9.0.post1,>=0.9.0 (from -r /tmp/pipenv-awjcfzsn-requirements/pipenv-m19__3qv-constraints.txt (line 2))

Finding the best candidates:
  found candidate pyarrow==0.9.0.post1 (constraint was >=0.9.0,<=0.9.0.post1)

Finding secondary dependencies:
  pyarrow==0.9.0.post1 not in cache, need to check index
  pyarrow==0.9.0.post1; python_version != "3.2.*" and python_version >= "2.7" and python_version != "3.1.*" and python_version != "3.0.*" and python_version != "3.3.*" requires futures, numpy>=1.10, pyarrow==0.9.0.post1; python_version != "3.2.*" and python_version >= "2.7" and python_version != "3.1.*" and python_version != "3.0.*" and python_version != "3.3.*", six>=1.0.0

New dependencies found in this round:
  adding ['futures', '', '[]']
  adding ['numpy', '>=1.10', '[]']
  adding ['pyarrow', '==0.9.0.post1', '[]']
  adding ['six', '>=1.0.0', '[]']
....
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 308, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/root/.local/share/virtualenvs/tmp-XVr6zr33/lib/python3.5/site-packages/pip/_internal/index.py", line 543, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pyarrow==0.9.0.post1 (from -r /tmp/pipenv-ilifgedr-requirements/pipenv-esjq5xiw-requirement.txt (line 1))

An error occurred while installing pyarrow==0.9.0.post1! Will try again.
```

This has been discussed over here https://github.com/pypa/pipenv/issues/2490

**Comment by wesm** [comment]
So it sounds like pipenv is just buggy:

https://github.com/pypa/pipenv/issues/2490#issuecomment-401860216

"This is a restriction of our resolver at the moment, but we expect each package to at least have an sdist for each version. Please help suggest pyarrow to publish it."

We are working as quickly as we can to get the 0.10.0 release out. This will be resolved when that happens. You can help by getting involved with Arrow development
