### ISSUE TITLE
[Python] Implement arrow JSON writer

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20054]
Add support for JSON writer in python

the docs only state JSON reading is supported: <https://arrow.apache.org/docs/python/json.html> 

**Reporter**: [Rishabh Rana](https://issues.apache.org/jira/browse/ARROW-15230)
#### Related issues:
- [[C++] JSON table writer](https://github.com/apache/arrow/issues/21529) (requires)

<sub>**Note**: *This issue was originally created as [ARROW-15230](https://issues.apache.org/jira/browse/ARROW-15230). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Duplicate of #21529
