### ISSUE TITLE
[Dev] Ask INFRA to switch default branch to main

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20117]
**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-15695) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-15695](https://issues.apache.org/jira/browse/ARROW-15695). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Done: https://issues.apache.org/jira/browse/INFRA-24214
