### ISSUE TITLE
FileOutputStream doesnt respect append=True

### ISSUE THREAD

**Issue by robambalu** [apache/arrow#2018]
While testing out FileOutputStream for streaming tables I noticed that passing append=True is broken.
When passing true, it will correctly avoid truncating the file, but it fails to seek to the end of the file.  As a result, the first existing N bytes of a file will simply be overridden, rather than appending

**Comment by wesm** [comment]
Can you please open a JIRA and provide a minimal reproduction?

**Comment by pitrou** [comment]
You're right, the `append` flag was buggy, it was fixed in PR #1978 (JIRA issue is ARROW-2466).
