### ISSUE TITLE
[R] Fix excess "Handling string data with embedded nuls" warning in tests

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20191]
The R tests raise a warning
```java

══ Warnings ════════════════════════════════════════════════════════════════════════════════════════════════
1. Handling string data with embedded nuls (test-RecordBatch.R:547:3) - Stripping '\0' (nul) from character vector
```
That test is already has an expectation for the warning, so it is likely being raised repeatedly and the excess are not suppressed.

AC: Warning not arising in tests because it is handled in an appropriate manner

**Reporter**: [Edward Visel](https://issues.apache.org/jira/browse/ARROW-16188) / @alistaire47
#### Related issues:
- [[R] unique() and is.na() on a column of a tibble is much slower after writing to and reading from a parquet file](https://github.com/apache/arrow/issues/31935) (relates to)

<sub>**Note**: *This issue was originally created as [ARROW-16188](https://issues.apache.org/jira/browse/ARROW-16188). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
I don't recall seeing these issues on our CI recently, so I'm going to assume this is fixed - feel free to reopen if not.
