### ISSUE TITLE
[Parquet] Null count in list arrays incorrect?

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20208]
The minimal example below reproduces the point:

```python

import pyarrow as pa  # pyarrow==7
import pyarrow.parquet

path = "bla.parquet"
data = [[0, 1], None, [2, None, 3], [4, 5, 6], [], [7, 8, 9], None, [10]]

t = pa.table(
    [pa.array(data)],
    schema=pa.schema([pa.field("int64", pa.list_(pa.int64()), nullable=True)]),
)

pyarrow.parquet.write_table(t,path)

parquet_file = pyarrow.parquet.ParquetFile(path)
nulls = parquet_file.metadata.row_group(0).column(0).statistics.null_count
assert nulls == 1, nulls
```

the null count should be equal to 1 because the inner array only has one null value (right?)

**Reporter**: [Jorge Leitão](https://issues.apache.org/jira/browse/ARROW-16299) / @jorgecarleitao

<sub>**Note**: *This issue was originally created as [ARROW-16299](https://issues.apache.org/jira/browse/ARROW-16299). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by mapleFU** [comment]
I guess this is expected, because `nulls` doesn't represent null-value here. 

```
  /** Number of NULL values, in this data page.
      Number of non-null = num_values - num_nulls which is also the number of values in the data section **/
  2: required i32 num_nulls
```

In fact, it means `num-of-levels - num-of-values`
