### ISSUE TITLE
[Python] Remove the test usage of legacy dataset

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20233]
Currently the parquet tests cover both new and old dataset implementation. The usage of legacy dataset can be removed from the tests as the legacy ParquetDataset is being deprecated.

See https://github.com/apache/arrow/issues/31529.

**Reporter**: [Alenka Frim](https://issues.apache.org/jira/browse/ARROW-16481) / @AlenkaF
#### Related issues:
- [[Python] Deprecate the legacy ParquetDataset custom python-based implementation](https://github.com/apache/arrow/issues/31529) (requires)
#### PRs and other links:
- [GitHub Pull Request #14031](https://github.com/apache/arrow/pull/14031)

<sub>**Note**: *This issue was originally created as [ARROW-16481](https://issues.apache.org/jira/browse/ARROW-16481). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Closing this issue as this will just be part of removing the legacy implementation (https://github.com/apache/arrow/issues/31303)
