### ISSUE TITLE
[JS] Unable to open reader on .arrow file after fetch: Uncaught (in promise) Error: Expected to read 1329865020 metadata bytes, but only read 1123.

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20325]
I created a file in raw arrow format with the script given in the Py arrow cookbook here: <https://arrow.apache.org/cookbook/py/io.html#saving-arrow-arrays-to-disk>

 

In a Node.js application, this file can be read doing:

 
```java

const r = await RecordBatchReader.from(fs.createReadStream(filePath));                
await r.open();

for (let i = 0; i < r.numRecordBatches; i++) {
    const rb = await r.readRecordBatch(i); 
    if (rb !== null) {
        console.log(rb.numRows);
    }
} 
```
However this method loads the whole file in memory (is that a bug?), which is not scalable.

 

To solve this scalability issue, I try to load the data with fetch as described in the the [README.md\|#load-data-with-fetch]. Both:

 
```java

import { tableFromIPC } from "apache-arrow";

const table = await tableFromIPC(fetch(filePath));
console.table([...table]);
```
 and
```java

const r = await RecordBatchReader.from(await fetch(filePath));                
await r.open(); 
```
fail with error:

Uncaught (in promise) Error: Expected to read 1329865020 metadata bytes, but only read 1123.

 

**Reporter**: [Benoit Cantin](https://issues.apache.org/jira/browse/ARROW-17123)
#### PRs and other links:
- [GitHub Pull Request #13715](https://github.com/apache/arrow/pull/13715)

<sub>**Note**: *This issue was originally created as [ARROW-17123](https://issues.apache.org/jira/browse/ARROW-17123). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by ArcRiiad** [comment]
Any update regarding this issue?

**Comment by kou** [comment]
You should use Apache Arrow Streaming format https://arrow.apache.org/docs/dev/format/Columnar.html#ipc-streaming-format not Apache Arrow File format https://arrow.apache.org/docs/dev/format/Columnar.html#ipc-file-format for this use case.

See also https://arrow.apache.org/docs/dev/python/ipc.html#using-streams how to write data as Apache Arrow Streaming format.

**Comment by ArcRiiad** [comment]
Mb, don't mind my previous comment, the issue was on my side, the tableFromIPC works well 👍
