### ISSUE TITLE
[C++][Compute] Add residual predicate support to new (Swiss) hash join

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20339]
Only HashJoinBasicImpl supports residual predicates (non-equality joins). This functionality needs to be ported to SwissJoin as well.

**Reporter**: [Michal Nowakiewicz](https://issues.apache.org/jira/browse/ARROW-17202) / @michalursa
#### Related issues:
- [[C++] Query engine umbrella issue](https://github.com/apache/arrow/issues/28385) (is a child of)

<sub>**Note**: *This issue was originally created as [ARROW-17202](https://issues.apache.org/jira/browse/ARROW-17202). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by zanmato1984** [comment]
take
