### ISSUE TITLE
[C++] Kernel input type matcher for RLE

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20351]
Builds on top of ARROW-17261

**Reporter**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-17262) / @zagto
#### PRs and other links:
- [GitHub Pull Request #13971](https://github.com/apache/arrow/pull/13971)

<sub>**Note**: *This issue was originally created as [ARROW-17262](https://issues.apache.org/jira/browse/ARROW-17262). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by felipecrv** [comment]
take
