### ISSUE TITLE
[C++] Handling of array-only types using VisitTypeInline

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20350]
**Reporter**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-17258) / @zagto
#### PRs and other links:
- [GitHub Pull Request #13752](https://github.com/apache/arrow/pull/13752)

<sub>**Note**: *This issue was originally created as [ARROW-17258](https://issues.apache.org/jira/browse/ARROW-17258). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by felipecrv** [comment]
take
