### ISSUE TITLE
[Parquet] DELTA_BINARY_PACKED constraint on num_bits is too restrict?

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20374]
Consider the sequence of (int32) values

[863490391,-816295192,1613070492,-1166045478,1856530847]

This sequence can be encoded as a single block, single miniblock with a bit_width of 33.

However, we currently require [1] the bit_width of each miniblock to be smaller than the bitwidth of the type it encodes.

We could consider lifting this constraint, as, as shown in the example above, the values representation's `bit_width` can be smaller than the delta's representation's `bit_width`.

[1] https://github.com/apache/arrow/blob/a376968089d7310f4a88d054822fa1eaf96c46f5/cpp/src/parquet/encoding.cc#L2173

**Reporter**: [Jorge Leitão](https://issues.apache.org/jira/browse/ARROW-17465) / @jorgecarleitao
#### Original Issue Attachments:
- [test.parquet](https://issues.apache.org/jira/secure/attachment/13048293/test.parquet)

<sub>**Note**: *This issue was originally created as [ARROW-17465](https://issues.apache.org/jira/browse/ARROW-17465). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by mapleFU** [comment]
@etseidl After https://github.com/apache/arrow/pull/37940 this is applied, would we prevent from generating new 33/65 bits data? Though we can still read from legacy data.

**Comment by etseidl** [comment]
@mapleFU AFAIK the arrow writer does not produce 33/65 bit data either before or after #37940, and still cannot read the bitwidths larger than the physical type. This reminds me that I still would like to add some clarification to the specification around this issue.

**Comment by etseidl** [comment]
This issue should be closed given the changes to the Parquet specification in [PARQUET-2435](https://github.com/apache/parquet-format/pull/231).

cc @pitrou @mapleFU

**Comment by pitrou** [comment]
Thanks @etseidl ! Closing then.
