### ISSUE TITLE
[R] Add as_scalar()

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20396]
There's as_everything_else but not as_scalar. 

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-17607) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-17607](https://issues.apache.org/jira/browse/ARROW-17607). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by danepitkin** [comment]
Is there more info we can add to this issue? Add `as_scalar()` where?
