### ISSUE TITLE
Fail to write pd.TimedeltaIndex and np.timedelta64

### ISSUE THREAD

**Issue by xwang777** [apache/arrow#2041]
Hi, 

When I try to write a pd.DataFrame with pd.TimedeltaIndex or np.timedelta64 column, I got 

> ArrowNotImplementedError: Unsupported numpy type 22.

I see that there's a Jira **ARROW-835** that is about implementing parquet I/O of pd.TimedeltaIndex and np.timedelta64. However, there seems to be no update on that since Nov/17. Is there a chance that this'll be resolved any time soon? What's the show stopper?

Thanks

**Comment by xhochy** [comment]
@xwang777 The showstopper is like in most cases that someone needs to work on the issue. Arrow just like any other opensource projects relies upon the contribution by individuals. If this is a feature that is of great interest for you, I would recommend that you try to implement it. When you need help making your contribution, feel free to reach out on the mailing list or the Slack channel and we will try to support you.

**Comment by wesm** [comment]
I have opened a JIRA specifically for the Python/pandas conversions to and from Arrow intervals: https://issues.apache.org/jira/browse/ARROW-2625. 

However, first we must resolve the format discussion in ARROW-835. We would welcome your assistance. I will close this issue in the meantime and steer discussion to JIRA.
