### ISSUE TITLE
Pandas DataFrame to parquet file

### ISSUE THREAD

**Issue by mlozowski** [apache/arrow#2043]
Hi!
In Pandas DataFrame there is a problem that you can not have integer column with NaNs. If there are any NaNs the column will be float type. Is there a way to convert a DataFrame with integer column containing -1 values and when we convert it to parquet file with pyarrow replace -1 values with NaN?

**Comment by xhochy** [comment]
In the next release we will have an option that you can convert `integer_object_nulls` to convert integer columns with nulls to object columns: https://github.com/apache/arrow/blob/48eee79189ca287ed58f3ae7833eaea011cdf5f8/python/pyarrow/array.pxi#L578

This is probably different to what you want to achieve but the more general alternative. The `-1` solution cannot be generalized will thus not be an option for Arrow. What you could do is to create a copy of the Arrow array where you replace all `null` values with `-1`. To make this fast you could use either Cython or Numba.

**Comment by mlozowski** [comment]
OK,
the main question is: is it possible to store pyarrow table with column type int and containing null values in the int column? And does pyarrow itself allow conversion of such a table to a parquet file containing int column with nulls?

**Comment by mlozowski** [comment]
OK, 
I have it. If I have a pandas DataFrame column with float type and I want to convert it to int32 in parquet file I have to define proper schema.
```
import numpy as np
import pyarrow as pa
l = [
     {'a': np.int32('12'), 'z': np.int32('1'), 'b': np.float('12.3'), 'c': datetime.datetime.now(), 'd': np.unicode('12')},
     {'a': np.int32('13'), 'z': np.int32('2'), 'b': np.float('13.3'), 'c': datetime.datetime.now(), 'd': np.unicode('13')},
     {'a': None, 'z': None, 'b': np.nan, 'c': None, 'd': None},
     ]
df_test = pd.DataFrame(columns=['c', 'a', 'z', 'b', 'd'], data=l).astype(dtype={'c': 'datetime64[ns]'})
schema = pa.schema([pa.field('a', pa.int32(), nullable=True), pa.field('z', pa.int32(), nullable=True)])
table_test = pa.Table.from_pandas(df=df_test, schema=schema, preserve_index=False)
```
And then the table_test write as a parquet.
In that way we can have a parquet file with int column and nulls in it (even if the pandas DataFrame does not allow it).
