### ISSUE TITLE
[JS] Update status docs

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20447]
Arrow JS support nulls, sparse, and dense unions.

**Reporter**: [Dominik Moritz](https://issues.apache.org/jira/browse/ARROW-17979) / @domoritz
#### PRs and other links:
- [GitHub Pull Request #14365](https://github.com/apache/arrow/pull/14365)

<sub>**Note**: *This issue was originally created as [ARROW-17979](https://issues.apache.org/jira/browse/ARROW-17979). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kylebarron** [comment]
I think this issue can be closed given https://github.com/apache/arrow/pull/37108
