### ISSUE TITLE
[Swift] Swift implementation of Arrow

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20484]
Initial check-in for a swift implementation of Arrow. Based on my understanding of the spec and looking through the C++ and C# current implementations.  

**Reporter**: [Alva Bandy](https://issues.apache.org/jira/browse/ARROW-18234) / @abandy
**Assignee**: [Alva Bandy](https://issues.apache.org/jira/browse/ARROW-18234) / @abandy
#### PRs and other links:
- [GitHub Pull Request #14561](https://github.com/apache/arrow/pull/14561)

<sub>**Note**: *This issue was originally created as [ARROW-18234](https://issues.apache.org/jira/browse/ARROW-18234). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
@abandy Could you add a "take" comment to assign this to you like https://github.com/apache/arrow/issues/33989#issuecomment-1412726868 ?

**Comment by abandy** [comment]
take
