### ISSUE TITLE
[CI] Migrate jobs on Travis CI to dev/tasks/

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20496]
https://cwiki.apache.org/confluence/display/INFRA/Travis+Migrations

> On November 2nd, 2020, Travis-CI announced the end of unlimited support for open source projects.
> 
> Infra is therefore moving our CI offerings away from Travis-CI in order to keep our builds pipeline  cost-effective
> 
> Deadline: December 31st 2022
> 
> Infrastructure is moving ASF projects away from using Travis-CI at the end of 2022.

We need to migrate jobs in `.travis.yml` to `dev/tasks/`. `dev/tasks/` are triggered by Crossbow. And Crossbow used in apache/arrow ( https://github.com/ursacomputing/crossbow/ ) can still use Travis CI ( https://app.travis-ci.com/github/ursacomputing/crossbow ) because the Travis CI account is sponsored by Voltron Data not ASF.

**Reporter**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-18316) / @kou
#### PRs and other links:
- [GitHub Pull Request #14751](https://github.com/apache/arrow/pull/14751)

<sub>**Note**: *This issue was originally created as [ARROW-18316](https://issues.apache.org/jira/browse/ARROW-18316). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
We need to do this ASAP because the deadline (December 31st 2022) has passed.

**Comment by pitrou** [comment]
@assignUser

**Comment by pitrou** [comment]
Should we close this? I don't think we have any remaining jobs on Travis-CI. @raulcd

**Comment by raulcd** [comment]
yes, there has been some discussion lately in order to add power pc support here: https://github.com/apache/arrow/issues/43817
where it can be followed up.
