### ISSUE TITLE
Can't run PyArrow identity aggregation in PySpark 2.3.0 EMR 5.13

### ISSUE THREAD

**Issue by dfithian** [apache/arrow#2052]
Hi, I have filed an issue in the Arrow JIRA: https://issues.apache.org/jira/browse/ARROW-2590. I understand that this is probably something to do with the combined environment of all the components involved, but it does definitely seem weird to me that I can't run the identity aggregation in this environment.

**Comment by wesm** [comment]
Thank you for opening a JIRA. I'm closing this issue here so we can track the problem there
