### ISSUE TITLE
Dart Lang

### ISSUE THREAD

**Issue by gedw99** [apache/arrow#2066]
There is now a decent version of FLatBuffers for Dart.
The PR will go in son:
https://github.com/google/flatbuffers/pull/4676

This is pretty useful as there is a large amount of work being done with Dart.

**Comment by wesm** [comment]
That's cool, thank you for pointing out. Want to open a JIRA about bootstrapping an Arrow library for Dart?

**Comment by gedw99** [comment]
sure its good to get into the groove.
where is the Jira ?

**Comment by gedw99** [comment]
made one here. see what you think.

https://issues.apache.org/jira/browse/ARROW-2631
