### ISSUE TITLE
Deeply Nested Test Data

### ISSUE THREAD

**Issue by quartox** [apache/arrow#2067]
From discussion with @joshuastorck, some deeply nested real world data could be valuable for testing out edge cases. I have created a test data set with arbitrary column names and values that slightly modifies a real world schema.

Attached is the json and parquet versions of the data:

[nested.zip](https://github.com/apache/arrow/files/2018618/nested.zip)

**Comment by wesm** [comment]
What do you think about random schema and data generation? This will ensure that all the Parquet edge cases are hit:

* Length 0 things
* Null lists and null structs
* Nullable and non-nullable fields (nearly of our unit tests in Arrow use nullable fields, so this is a hole in our testing)

etc. We can write the data generator in Python which will make things easier. If a new edge case is encountered, we can improve the random data generator

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2624
