### ISSUE TITLE
pandas ArrowInvalid error message should include column name

### ISSUE THREAD

**Issue by louispotok** [apache/arrow#2072]
I'm trying to write a pandas dataframe to feather using its to_feather method. When a single column's conversion fails (`pandas_compat.convert_column`), the error message does not include the name of the column that failed. E.g. the message is something like:
`ArrowInvalid: Error converting from Python objects to String/UTF8: Got Python object of type int but can only handle these types: str, bytes.`

I think it would make debugging easier to add the column name to the error message. Thoughts?

**Comment by wesm** [comment]
This sounds like a nice improvement. Could you open an issue on JIRA (our feature/bug tracker)?

**Comment by louispotok** [comment]
Sure https://issues.apache.org/jira/browse/ARROW-2626
Should I close this issue as well?

**Comment by wesm** [comment]
Perfect, thanks. Yep, closing this
