### ISSUE TITLE
[Java] Arrow-to-JDBC

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20730]
ARROW-1780 reads a query from a JDBC data source and converts the ResultSet to an Arrow VectorSchemaRoot.  However, there is no built-in adapter for writing an Arrow VectorSchemaRoot back to the database.

ARROW-3966 adds JDBC field metadata:
- The Catalog Name
- The Table Name
- The Field Name
- The Field Type
  
  We can use this information to ask for the field information from the database via the [DatabaseMetaData](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html) object.  We can then create INSERT or UPDATE statements based on the [list of primary keys](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getPrimaryKeys(java.lang.String,%20java.lang.String,%20java.lang.String)) in the table:
- If the value in the VectorSchemaRoot corresponding to the primary key is NULL, insert that record into the database.
- If the value in the VectorSchemaRoot corresponding to the primary key is not NULL, update the existing record in the database.
  
  We can also perform the same data conversion in reverse based on the field types queried from the database.

**Reporter**: [Michael Pigott](https://issues.apache.org/jira/browse/ARROW-4144) / @mikepigott

<sub>**Note**: *This issue was originally created as [ARROW-4144](https://issues.apache.org/jira/browse/ARROW-4144). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by wgtmac** [comment]
I am looking for a similar feature and came across this issue. I know we have supported JDBC to Arrow but not in the inverse direction. Do we have any plan to support it? @lidavidm

**Comment by lidavidm** [comment]
https://github.com/apache/arrow-adbc/tree/main/java/driver/jdbc can do it but needs assistance generating the SQL

https://github.com/apache/arrow/blob/main/java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcParameterBinder.java requires you to set up the PreparedStatement and everything and solely automates the work of converting Arrow data to JDBC statement parameters

If one of those works, I think we should document the possibilities and close this issue

**Comment by wgtmac** [comment]
> https://github.com/apache/arrow-adbc/tree/main/java/driver/jdbc can do it but needs assistance generating the SQL
> 
> https://github.com/apache/arrow/blob/main/java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcParameterBinder.java requires you to set up the PreparedStatement and everything and solely automates the work of converting Arrow data to JDBC statement parameters
> 
> If one of those works, I think we should document the possibilities and close this issue

None of them work for my case. My goal is to wrap a set of `VectorSchemaRoot` into JDBC `ResultSet` in the read path.

**Comment by lidavidm** [comment]
Ah. Interesting. Sorry, I misunderstood.

There is stuff like that in the JDBC driver but not exposed for public use. What is the use case?

**Comment by wgtmac** [comment]
To provide standard JDBC access to a database or engine that speaks arrow vector natively.

**Comment by lidavidm** [comment]
Ok, cool. (So this is like an embeddable engine? I assume otherwise you could use Flight SQL.)

Your best bet is to copy or refactor the code that is part of the JDBC driver. There isn't a separate adapter for this but it would make sense to refactor things into arrow-jdbc if they are useful more widely.

**Comment by lidavidm** [comment]
This is also different from this original issue, since this issue was about writing Arrow data to a database via JDBC

**Comment by wgtmac** [comment]
Did you mean this? https://github.com/apache/arrow/blob/main/java/flight/flight-sql-jdbc-driver/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcVectorSchemaRootResultSet.java

**Comment by lidavidm** [comment]
Yes, code like that. (I suppose the Avatica dependency means we may not want to add it to arrow-jdbc, but it's already public - does it sort of work? We can talk about refactoring it if it meets your needs.)

**Comment by wgtmac** [comment]
Yes, it seems like what I am searching for. I need some time to read into it before a concrete conclusion. Thanks for your help!

**Comment by wgtmac** [comment]
@lidavidm Can we add a separate `flight-sql-jdbc-core` module?

The issue is that `flight-sql-jdbc-driver` has relocated a lot of classes including `VectorSchemaRoot`: https://github.com/apache/arrow/blob/main/java/flight/flight-sql-jdbc-driver/pom.xml#L193. This makes it difficult to directly develop other JDBC drivers based on it.

**Comment by lidavidm** [comment]
If the ResultSet implementation (and any other functionality?) can be cleanly separated out and is useful more broadly, then that sounds reasonable to me.

**Comment by wgtmac** [comment]
I will try it once I have some time.
