### ISSUE TITLE
Speeding up PySpark with Apache Arrow: Can't reproduce the example

### ISSUE THREAD

**Issue by olekscode** [apache/arrow#2074]
Hello!

I was trying to reproduce the example from this article: https://arrow.apache.org/blog/2017/07/26/spark-arrow/ but on my machine (macOS, Spark 2.2.1, Python 3.6.2) there is no improvement.

* I have installed Arrow following the instructions here: https://github.com/apache/arrow/blob/master/site/install.md
* Measured time for converting Spark DataFrame to pandas (A)
* Added this configuration: `spark.conf.set("spark.sql.execution.arrow.enabled", "true")`
* Measured time again (B)

And there is almost no improvement:
* A = 25 sec
* B = 24 sec

According to the article, on author's local machine it was
* A = 17.4 sec
* B = 40 ms

Am I doing something wrong? Is this functionality not supported by my version of Spark or Python?

**Comment by olekscode** [comment]
Thank you!

**Comment by sushmit86** [comment]
@wesm I am in a databricks environment and using Pyspark2.4.0 but still, the topandas is taking a lot of time. Any ideas on what can be causing the issue? Also, I am getting a warning like ```UserWarning: pyarrow.open_stream is deprecated, please use pyarrow.ipc.open_stream```

**Comment by wesm** [comment]
I do not know. Can you open an issue with Apache Spark?

**Comment by sushmit86** [comment]
@wesm Thanks will open
