### ISSUE TITLE
issue with installing pyarrow in alpine linux docker

### ISSUE THREAD

**Issue by jibybabu** [apache/arrow#2080]
Hi,
Though I am able to pyarrow using pip in mac and Amazon Linux,  pip install pyarrow in alpine docker  is failing . Here is the error messages. 

bash-4.3# pip install --no-cache pyarrow
Collecting pyarrow
  Downloading https://files.pythonhosted.org/packages/be/2d/11751c477e4e7f4bb07ac7584aafabe0d0608c170e4bff67246d695ebdbe/pyarrow-0.9.0.tar.gz (8.5MB)
    100% |████████████████████████████████| 8.5MB 62.9MB/s 
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python2.7/site-packages (from pyarrow)
Requirement already satisfied: six>=1.0.0 in /usr/local/lib/python2.7/site-packages (from pyarrow)
Requirement already satisfied: futures in /usr/local/lib/python2.7/site-packages (from pyarrow)
Installing collected packages: pyarrow
  Running setup.py install for pyarrow ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9_IrTM/pyarrow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-BqMhyM-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/orc.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/parquet.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/serialization.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/feather.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/compat.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/hdfs.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/types.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/__init__.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/pandas_compat.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/util.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/ipc.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/filesystem.py -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/formatting.py -> build/lib.linux-x86_64-2.7/pyarrow
    creating build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_convert_pandas.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_parquet.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_misc.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_schema.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_io.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/pandas_examples.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_table.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_convert_builtin.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_serialization.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_ipc.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_tensor.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/conftest.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_types.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_cython.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_plasma.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/__init__.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/deserialize_buffer.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/util.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_deprecations.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_array.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_scalars.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_hdfs.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    copying pyarrow/tests/test_feather.py -> build/lib.linux-x86_64-2.7/pyarrow/tests
    running egg_info
    writing requirements to pyarrow.egg-info/requires.txt
    writing pyarrow.egg-info/PKG-INFO
    writing top-level names to pyarrow.egg-info/top_level.txt
    writing dependency_links to pyarrow.egg-info/dependency_links.txt
    writing entry points to pyarrow.egg-info/entry_points.txt
    reading manifest file 'pyarrow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    writing manifest file 'pyarrow.egg-info/SOURCES.txt'
    copying pyarrow/__init__.pxd -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/_config.pyx -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/_orc.pxd -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/_orc.pyx -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/_parquet.pxd -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/_parquet.pyx -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/array.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/error.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/feather.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/io-hdfs.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/io.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/ipc.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/lib.pxd -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/lib.pyx -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/lib_api.h -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow.so.0 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow.so.0.0.0 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow_boost_filesystem.so.1.65.1 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow_boost_regex.so.1.65.1 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow_boost_system.so.1.65.1 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow_python.so.0 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libarrow_python.so.0.0.0 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libparquet.so.1 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libparquet.so.1.4.1 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libplasma.so.0 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/libplasma.so.0.0.0 -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/memory.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/plasma.pyx -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/plasma_store -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/public-api.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/scalar.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/serialization.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/table.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    copying pyarrow/types.pxi -> build/lib.linux-x86_64-2.7/pyarrow
    creating build/lib.linux-x86_64-2.7/pyarrow/include
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/allocator.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/api.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/array.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/buffer.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/builder.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/compare.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/memory_pool.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/pretty_print.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/record_batch.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/status.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/stl.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/table.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/table_builder.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/tensor.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/test-util.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/type.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/type_fwd.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/type_traits.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/visitor.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    copying pyarrow/include/arrow/visitor_inline.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/adapters
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/adapters/orc
    copying pyarrow/include/arrow/adapters/orc/adapter.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/adapters/orc
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute
    copying pyarrow/include/arrow/compute/api.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute
    copying pyarrow/include/arrow/compute/context.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute
    copying pyarrow/include/arrow/compute/kernel.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute/kernels
    copying pyarrow/include/arrow/compute/kernels/cast.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute/kernels
    copying pyarrow/include/arrow/compute/kernels/hash.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/compute/kernels
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/io
    copying pyarrow/include/arrow/io/api.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/io
    copying pyarrow/include/arrow/io/file.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/io
    copying pyarrow/include/arrow/io/hdfs.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/io
    copying pyarrow/include/arrow/io/interfaces.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/io
    copying pyarrow/include/arrow/io/memory.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/io
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/api.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/dictionary.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/feather.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/json.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/message.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/reader.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    copying pyarrow/include/arrow/ipc/writer.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/ipc
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/api.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/arrow_to_pandas.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/arrow_to_python.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/builtin_convert.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/common.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/config.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/helpers.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/init.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/io.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/numpy_convert.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/numpy_interop.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/numpy_to_arrow.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/platform.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/pyarrow.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/python_to_arrow.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    copying pyarrow/include/arrow/python/type_traits.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/python
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/bit-stream-utils.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/bit-util.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/bpacking.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compiler-util.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compression.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compression_brotli.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compression_lz4.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compression_snappy.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compression_zlib.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/compression_zstd.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/cpu-info.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/decimal.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/hash-util.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/hash.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/io-util.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/key_value_metadata.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/logging.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/macros.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/memory.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/optional.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/parallel.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/recursive_wrapper.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/rle-encoding.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/sse-util.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/stl.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/string.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/type_traits.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/variant.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/variant_cast.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/variant_io.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/variant_visitor.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    copying pyarrow/include/arrow/util/visibility.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util
    creating build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util/variant
    copying pyarrow/include/arrow/util/variant/optional.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util/variant
    copying pyarrow/include/arrow/util/variant/recursive_wrapper.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util/variant
    copying pyarrow/include/arrow/util/variant/variant_cast.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util/variant
    copying pyarrow/include/arrow/util/variant/variant_io.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util/variant
    copying pyarrow/include/arrow/util/variant/variant_visitor.h -> build/lib.linux-x86_64-2.7/pyarrow/include/arrow/util/variant
    creating build/lib.linux-x86_64-2.7/pyarrow/includes
    copying pyarrow/includes/__init__.pxd -> build/lib.linux-x86_64-2.7/pyarrow/includes
    copying pyarrow/includes/common.pxd -> build/lib.linux-x86_64-2.7/pyarrow/includes
    copying pyarrow/includes/libarrow.pxd -> build/lib.linux-x86_64-2.7/pyarrow/includes
    copying pyarrow/tests/pyarrow_cython_example.pyx -> build/lib.linux-x86_64-2.7/pyarrow/tests
    creating build/lib.linux-x86_64-2.7/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.all-named-index.parquet -> build/lib.linux-x86_64-2.7/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.column-metadata-handling.parquet -> build/lib.linux-x86_64-2.7/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.parquet -> build/lib.linux-x86_64-2.7/pyarrow/tests/data
    copying pyarrow/tests/data/v0.7.1.some-named-index.parquet -> build/lib.linux-x86_64-2.7/pyarrow/tests/data
    running build_ext
    creating build/temp.linux-x86_64-2.7
    -- Runnning cmake for pyarrow
    cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python  -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_BUNDLE_BOOST=OFF -DCMAKE_BUILD_TYPE=debug /tmp/pip-build-9_IrTM/pyarrow
    -- The C compiler identification is GNU 6.3.0
    -- The CXX compiler identification is GNU 6.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    INFOCompiler command: /usr/bin/c++
    INFOCompiler version: Using built-in specs.
    COLLECT_GCC=/usr/bin/c++
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/6.3.0/lto-wrapper
    Target: x86_64-alpine-linux-musl
    Configured with: /home/buildozer/aports/main/gcc/src/gcc-6.3.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 6.3.0' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-cloog-backend --enable-languages=c,c++,objc,java,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
    Thread model: posix
    gcc version 6.3.0 (Alpine 6.3.0)
    
    INFOCompiler id: GNU
    Selected compiler gcc 6.3.0
    -- Performing Test CXX_SUPPORTS_SSE3
    -- Performing Test CXX_SUPPORTS_SSE3 - Success
    -- Performing Test CXX_SUPPORTS_ALTIVEC
    -- Performing Test CXX_SUPPORTS_ALTIVEC - Failed
    Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
    -- Build Type: DEBUG
    -- Build output directory: /tmp/pip-build-9_IrTM/pyarrow/build/temp.linux-x86_64-2.7/debug/
    -- Found PythonInterp: /usr/local/bin/python (found version "2.7.13")
    -- Searching for Python libs in /usr/local/lib64;/usr/local/lib;/usr/local/lib/python2.7/config
    -- Looking for python2.7
    -- Found Python lib /usr/local/lib/libpython2.7.so
    -- Found PythonLibs: /usr/local/lib/libpython2.7.so
    -- Found NumPy: version "1.14.3" /usr/local/lib/python2.7/site-packages/numpy/core/include
    -- Searching for Python libs in /usr/local/lib64;/usr/local/lib;/usr/local/lib/python2.7/config
    -- Looking for python2.7
    -- Found Python lib /usr/local/lib/libpython2.7.so
    -- Found PkgConfig: /usr/bin/pkg-config (found version "1.3.7")
    -- Checking for module 'arrow'
    --   Package 'arrow', required by 'virtual:world', not found
    CMake Error at cmake_modules/FindArrow.cmake:130 (message):
      Could not find the Arrow library.  Looked for headers in , and for libs in
    Call Stack (most recent call first):
      CMakeLists.txt:197 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-9_IrTM/pyarrow/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-build-9_IrTM/pyarrow/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeError.log".
    error: command 'cmake' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9_IrTM/pyarrow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-BqMhyM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9_IrTM/pyarrow/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by wesm** [comment]
Did you build and install the Arrow C++ libraries first?

**Comment by jibybabu** [comment]
Hi Wes,
Thanks for the response. 
Unfortunately, I couldn't install the arrow C++ libraries
When I tried to install the dependencies inorder to install the Arrow C++ libraries , as mentioned in https://github.com/apache/arrow/blob/master/python/doc/source/development.rst, it was failing in the alpine.
```bash-4.3# apk add libjemalloc-dev libboost-dev \
>                        libboost-filesystem-dev \
>                        libboost-system-dev \
>                        libboost-regex-dev \
>                        flex \
>                        bison
WARNING: This apk-tools is OLD! Some packages might not function properly.
ERROR: unsatisfiable constraints:
  libboost-dev (missing):
    required by: world[libboost-dev]
  libboost-filesystem-dev (missing):
    required by: world[libboost-filesystem-dev]
  libboost-regex-dev (missing):
    required by: world[libboost-regex-dev]
  libboost-system-dev (missing):
    required by: world[libboost-system-dev]
  libjemalloc-dev (missing):
    required by: world[libjemalloc-dev]```

Thanks,
Jiby

**Comment by wesm** [comment]
Getting all of this to work on Alpine will be some work to get all the dependencies working. I opened https://issues.apache.org/jira/browse/ARROW-2637 about tracking this topic in general. Closing the GitHub issue in the meantime

**Comment by mbrobbel** [comment]
For version 0.10 of the C++ library this worked for me: https://github.com/mbrobbel/libarrow/blob/0.10.0/Dockerfile

However, for version 0.11 it failed because alpine's musl libc execinfo.h ( (https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/logging.cc#L21) does not provide backtrace.

Relevant:
https://github.com/nodejs/node-report/commit/4691393e57f48d3f418fd636a6e80fdf12e03151
https://github.com/PDAL/PDAL/issues/1904
http://www.nongnu.org/libunwind/
https://github.com/quinoacomputing/quinoa/commit/9ec3ae3cb2ea29593385a05cd613e30780382a71

**Comment by xhochy** [comment]
@mbrobbel This is the same as https://github.com/apache/arrow/issues/2818 thus I opened a JIRA at https://issues.apache.org/jira/browse/ARROW-3670

**Comment by mbrobbel** [comment]
> @mbrobbel This is the same as #2818 thus I opened a JIRA at https://issues.apache.org/jira/browse/ARROW-3670

Ah, missed that issue. Thanks.

**Comment by xhochy** [comment]
@mbrobbel Fixed in master now
