### ISSUE TITLE
[Release] Add script to test release verification script against master branch

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20866]
This should enable us to find problems with the verification script well before releases happen.

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-4292) / @wesm

<sub>**Note**: *This issue was originally created as [ARROW-4292](https://issues.apache.org/jira/browse/ARROW-4292). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Source release script is tested against PRs and main + verifications are run as nightlies.
