### ISSUE TITLE
[Benchmarking] Performance Benchmarking Dashboard

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20889]
This is parent task to serve as a starting point for all performance benchmarking dashboard related tasks.

Original discussion started here: <https://lists.apache.org/thread.html/278e573445c83bbd8ee66474b9356c5291a16f6b6eca11dbbe4b473a@%3Cdev.arrow.apache.org%3E>

 

 

**Reporter**: [Areg Melik-Adamyan](https://issues.apache.org/jira/browse/ARROW-4317) / @aregm
#### Related issues:
- [[Benchmarking] Support for on-demand and automated benchmarks](https://github.com/apache/arrow/issues/21560) (blocks)
- [[Benchmarking] Decide which benchmarks are part of regression checks](https://github.com/apache/arrow/issues/21653) (is blocked by)

<sub>**Note**: *This issue was originally created as [ARROW-4317](https://issues.apache.org/jira/browse/ARROW-4317). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We now have a continuous benchmarking Web UI at https://conbench.ursa.dev/
