### ISSUE TITLE
[Python] Improve ParquetManifest creation time for highly partitioned datasets

### ISSUE THREAD

**Issue by rgruener** [apache/arrow#2094]
When a parquet dataset is highly partitioned, the time to call the constructor for [ParquetManifest ](https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L588) takes a significant amount of time since it serially visits directories to find all parquet files. In a dataset with thousands of partition values this can take several minutes from a personal laptop.

A quick win to vastly improve this performance would be to use a ThreadPool to have calls to `_visit_level` happen concurrently to prevent wasting a ton of time waiting on I/O.

An even faster option could be to allow for optional indexing of dataset metadata in something like the `common_metadata`. This could contain all files in the manifest and their row_group information. This would also allow for [split_row_groups](https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L746) to be implemented efficiently without needing to open every parquet file in the dataset to retrieve the metadata which is quite time consuming for large datasets. The main problem with the indexing approach are it requires immutability of the dataset, which doesn't seem too unreasonable.

I can likely help with either of these approaches as I have already experimented with them.

**Comment by rgruener** [comment]
The second option sounds something akin to https://issues.apache.org/jira/browse/ARROW-1983 actually

**Comment by wesm** [comment]
This sounds like a good idea. Could you open a JIRA for this work (improving the performance of ParquetManifest and adding a benchmark)?

**Comment by rgruener** [comment]
sure https://issues.apache.org/jira/browse/ARROW-2656

**Comment by wesm** [comment]
Thank you
