### ISSUE TITLE
table.to_pandas just take first item of the array 

### ISSUE THREAD

**Issue by deter3** [apache/arrow#2098]
I am testing arrow as below ,  

`data=[pa.array([1]),pa.array(["tokyo", "like", "happy"]),pa.array(["derek"])]`
`batch = pa.RecordBatch.from_arrays(data, ['id', 'tags', 'name'])`
`data1=[pa.array([2]),pa.array(["xiamen", "food", "happy"]),pa.array(["rich"])]`
`batch2 = pa.RecordBatch.from_arrays(data1, ['id', 'tags', 'name'])`
`batches= [batch]+[batch2]`
`table = pa.Table.from_batches(batches)`
`table[1]`

here is the result of table[1] :

`<pyarrow.lib.Column object at 0x10b6d0ed0>
chunk 0: <pyarrow.lib.BinaryArray object at 0x10b6fa788>
[
  'tokyo',
  'like',
  'happy'
]
chunk 1: <pyarrow.lib.BinaryArray object at 0x10b6fa7e0>
[
  'xiamen',
  'food',
  'happy'
]`

but when I convert to pandas by using 

`d = table.to_pandas()`

d is showing as below ;

<img width="168" alt="25b6a0b4-9a67-4701-9685-5035c5d95a5d" src="https://user-images.githubusercontent.com/11637246/40872823-281700c6-6690-11e8-9f54-a820d8e8a787.png">

Am I doing anything wrong ?

**Comment by wesm** [comment]
Thanks for the bug report. I opened https://issues.apache.org/jira/browse/ARROW-2820; closing this issue to track progress fixing it on JIRA

**Comment by deter3** [comment]
I have seen value error "Arrays were not all the same length" when I am having different length array in pyarrow-0.10.0 . The problem is I will need to include all tags in a tweets into one array , the array length for tags is variable , finally , all tweets records with different length of tags arrays will form a table .   Is there any other way to do it ? Thanks .

**Comment by wesm** [comment]
@deter3 can you ask this question on the mailing list and provide an example? Thanks
