### ISSUE TITLE
Support for Parquet zstd compression

### ISSUE THREAD

**Issue by will133** [apache/arrow#2108]
It seems like zstd is not yet supported for the python parquet api (the check seems to not include ZSTD):

https://github.com/apache/arrow/blob/master/python/pyarrow/_parquet.pyx

```
cdef int check_compression_name(name) except -1:
    if name.upper() not in ['NONE', 'SNAPPY', 'GZIP', 'LZO', 'BROTLI', 'LZ4']:
        raise ArrowException("Unsupported compression: " + name)
    return 0
```

Is there any plan to support this?

Thanks.

**Comment by wesm** [comment]
Yes, could you please open a JIRA to track this feature? Thank you

**Comment by will133** [comment]
Thanks.  I've filed this as https://issues.apache.org/jira/browse/ARROW-2677.

**Comment by theinexorable** [comment]
this same piece of code brings me:

 File "pyarrow\_parquet.pyx", line 884, in pyarrow._parquet.check_compression_name

AttributeError: 'int' object has no attribute 'upper'
