### ISSUE TITLE
Uploading source files in PyPI repository

### ISSUE THREAD

**Issue by ajeis** [apache/arrow#2113]
Hello,

Currently the Pyarrow package in PyPI has only wheel files and not the source code, unlike some of the other open source projects. Some of the proprietary package manners require the source code be also uploaded to PyPI. Would it be possible for the maintainers to upload the source code as well to PyPI? 
Apologies if this is not the right place for this discussion.

**Comment by xhochy** [comment]
We have source tarballs uploaded: https://pypi.org/project/pyarrow/0.9.0/#files

The display is currently a bit weird as we had to upload a bugfix wheel for OSX. We will fix this with the upcoming 0.10.0.
