### ISSUE TITLE
[JS] add logging

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#21131]
As discussed in https://github.com/apache/arrow/pull/3634, the javascript library will need some logging infrastructure. The goals for this implementation are a lightweight logger that can be easily configured to not write to console. 

**Reporter**: [Dominik Moritz](https://issues.apache.org/jira/browse/ARROW-4588) / @domoritz

<sub>**Note**: *This issue was originally created as [ARROW-4588](https://issues.apache.org/jira/browse/ARROW-4588). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
Not sure why we need this right now. Closing.
