### ISSUE TITLE
Add __iter__ method to pyarrow.lib.NativeFile.

### ISSUE THREAD

**Issue by fredlorry** [apache/arrow#2114]
Hello,

Currently, NativeFile does not pass the check of pandas for being a "file-like" object because it does not have `__iter__` method. It can be easily added using code from native python `io` module as a reference. Another way would be to subclass `io.IOBase`.

The exact code of pandas check can be found [here](https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/inference.py#L158).

Code for `__iter__`  method and `io.IOBase` can be found [here](https://github.com/python/cpython/blob/master/Lib/_pyio.py#L479).

Thanks!

**Comment by wesm** [comment]
Thanks for pointing this out. Can you open a JIRA to track this bug/feature request?

**Comment by wesm** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-2816
