### ISSUE TITLE
[JS] Arrow 0.3.1 cannot compile with typescript 2.8.3 and ES6

### ISSUE THREAD

**Issue by ruixuel** [apache/arrow#2115]
Arrow version: 0.3.1
Typescript version: 2.8.3
tsconfig.json: 
{
    "compilerOptions": {
        "allowJs": true,
        "jsx": "react",
        "types": ["node"],
        "module": "commonjs",
        "lib": [
            "dom",
            "webworker",
            "ES6",
            "scripthost",
        ],
        "target": "ES6",
        "sourceMap": true,
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true
    },
    "include": [
        "./src/**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}

I am trying to use the latest arrow JS library (0.3.1) and compile it with typescript 2.8.3 and ES6, however I get these errors: 

    ERROR in [at-loader] ./node_modules/apache-arrow/type.d.ts:135:47
        TS2344: Type 'TArrayType' does not satisfy the constraint 'TypedArray'.
      Type 'IntArray' is not assignable to type 'TypedArray'.
        Type 'Uint8Array' is not assignable to type 'TypedArray'.
          Property 'includes' is missing in type 'Uint8Array'.

    ERROR in [at-loader] ./node_modules/apache-arrow/type.d.ts:170:47
        TS2344: Type 'TArrayType' does not satisfy the constraint 'TypedArray'.
      Type 'FloatArray' is not assignable to type 'TypedArray'.
        Type 'Uint16Array' is not assignable to type 'TypedArray'.
          Property 'includes' is missing in type 'Uint16Array'.

    ERROR in [at-loader] ./node_modules/apache-arrow/vector/list.d.ts:6:43
        TS2304: Cannot find name 'SharedArrayBuffer'.

I think these are new in ES2016 and ES2017. 
I import arrow as: import {Table} from "arrow-apache";
I notice that the arrow js supports ES5 and ES2015, so I also tried package: "apache-arrow/es2015-cjs", but it does not compile either.

I am wondering if there's any way that I can compile the arrow js latest version with ES6? 
Thank you!

**Comment by wesm** [comment]
I think you should be able to `npm install` from the `js/` directory of the git repo, similar to how we test release candidates https://github.com/apache/arrow/blob/master/dev/release/js-verify-release-candidate.sh#L93

Seems like this could be a bug, or something that's been fixed since the 0.3.1 release. Could you open a JIRA with this report? Thank you

**Comment by ruixuel** [comment]
Thank you for your response. I find that in arrow repo: js/tsconfig/tsconfig.base.json, "ESNext" is included in the lib for typescript compilation.  That's why "npm install" works in your branch. However, since SharedArrayBuffer is not supported in most browsers for now, we don't want to support ESNext for our application. So I just add "skipLibCheck": true in the tsconfig.json to skip all *.d.ts files in the node_modules when compiling. It works finally!

**Comment by wesm** [comment]
@trxcllnt @TheNeuralBit can you open a JIRA to track this issue?

**Comment by TheNeuralBit** [comment]
Ah thanks for tagging us @wesm. I think @trxcllnt ran into this (and fixed it) when he did an upgrade to 2.9. Maybe we should back port that fix and cut an 0.3.2 release, not sure how long it will be until we do 0.4

**Comment by wesm** [comment]
Cool. Since there's so much new stuff for 0.4 it'd be awesome to get that out sooner rather than later. Just let me know when you want to release
