### ISSUE TITLE
Create .arrow format

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#2119]
I'm working on a JavaScript application and would like to load my data via arrow. I got stuck at the point where I create a `.arrow` file (I don't want to use parquet or feather) as used in https://github.com/apache/arrow/tree/master/js. I have a python program to read the data into a pandas data frame but https://arrow.apache.org/docs/python/ipc.html didn't mention how to write such a file. Is there something missing in the docs?

**Comment by wesm** [comment]
This is described here http://arrow.apache.org/docs/python/ipc.html#writing-and-reading-random-access-files. This could probably be made a bit more discoverable from the documentation table of contents -- could you create a JIRA about making some improvements to the section headers?

**Comment by domoritz** [comment]
Ahh, I got confused because IPC of my appears in the title and never again. I'll create a ticket.

**Comment by domoritz** [comment]
https://issues.apache.org/jira/browse/ARROW-2684

**Comment by domoritz** [comment]
I think the answer is

```python
table = pa.Table.from_pandas(df)
with open('file.arrow', 'bw') as f:
    writer = pa.RecordBatchFileWriter(f, table.schema)
    writer.write(table)
    writer.close()
```

**Comment by wesm** [comment]
Yes, that looks right. I think you can pass the file name to `RecordBatchFileWriter` instead of opening the file yourself (the performance should even be better this way)

**Comment by RobinL** [comment]
For anyone seeing this in future, you can also get the schema from pandas as follows. (I've also followed Wes's suggestion of using RecordBatchFileWriter).

```
import pyarrow as pa
import pandas as pd 

df = pd.read_parquet('clean_nhs_data_latest.parquet')

table = pa.Table.from_pandas(df)
schema = pa.Schema.from_pandas(df)

sink = "myfile.arrow"

# Note new_file creates a RecordBatchFileWriter 
writer = pa.ipc.new_file(sink, schema)
writer.write(table)
writer.close()
```
