### ISSUE TITLE
Invalid Arrow Buffer

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#2123]
I'm trying to load an arrow file in my typescript application. I'm using https://github.com/parcel-bundler/parcel to bundle my app. 

```ts
import { Table } from "@apache-arrow/es2015-esm";

fetch(require("../data/flights-10k.arrow")).then(response => {
  response.blob().then(blob => {
    const table = Table.from([blob]);
    console.log(table.toString());
  });
});
```

I get the following error `Uncaught (in promise) Error: Invalid Arrow buffer`.

**Comment by domoritz** [comment]
Maybe I need to convert the blob to a buffer

```ts
fetch(require("../data/flights-10k.arrow")).then(response => {
  response.blob().then(blob => {
    let arrayBuffer;
    const fileReader = new FileReader();
    fileReader.onload = function() {
      arrayBuffer = this.result;
      const table = Table.from(arrayBuffer);

      console.log(table.toString());
    };
    fileReader.readAsArrayBuffer(blob);
  });
});
```

Now I get `Uncaught TypeError: Cannot read property 'fields' of undefined`.

**Comment by wesm** [comment]
cc @trxcllnt @TheNeuralBit. The version of the project on npm is slightly stale, do we need to do a 0.4.0 JS release soon? 

@domoritz in general we prefer to use either JIRA or the mailing list for these discussions, but we have GitHub issues available to capture information from users who aren't yet familiar with how the project works

**Comment by domoritz** [comment]
I can post on the mailing list or create JIRA tickets instead. My questions are probably very naive and I wasn't sure where the right place is to ask them. I'll close this issue and move it to JIRA.

**Comment by wesm** [comment]
No worries, thanks!

**Comment by domoritz** [comment]
https://issues.apache.org/jira/browse/ARROW-2686

**Comment by trxcllnt** [comment]
@domoritz you should use `response.arrayBuffer()`, and then wrap the ArrayBuffer in a Uint8Array like this:

```ts
import { Table } from "@apache-arrow/es2015-esm";

fetch(require("../data/flights-10k.arrow")).then(response => {
  response.arrayBuffer().then(buffer => {
    const table = Table.from(new Uint8Array(buffer));
    console.log(table.toString());
  });
});
```

**Comment by domoritz** [comment]
Oh, perfect. That works!
