### ISSUE TITLE
pyarrow 0.10.0 project tracking

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#2131]
Quick question -

Is there a task list/link for the `0.10.0` release? Is this the right place to ask questions like this?

**Comment by wesm** [comment]
hi @dmadeka, the release milestone is tracked on the ASF's JIRA https://issues.apache.org/jira/projects/ARROW?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page. 

We are unlikely to make the 0.10.0 release until the packaging automation work (see prior mailing list discussions, pull requests) is completed. It would be great if that happened by the end of this month

In general the best place to discuss releases is the dev@ mailing list
