### ISSUE TITLE
pyarrow fails to split large dataframe into tiny parquet files

### ISSUE THREAD

**Issue by randomgambit** [apache/arrow#2138]
Hello there, I am following up on a discussion with @xhochy .

It seems writing a large dataframe into a single `parquet` is no problem, whereas trying to split the writing into many different `parquet` files creates memory issues.

Please have a look here for a complete reprex.

https://stackoverflow.com/questions/50824943/how-to-efficiently-split-a-large-dataframe-into-many-parquet-files

Thanks!

**Comment by randomgambit** [comment]
related https://github.com/dask/dask/issues/3598#issuecomment-396970081

**Comment by rpanai** [comment]
This [asnwer](https://stackoverflow.com/a/50841152/4819376) should solve the problem. The dask solution is 2.5x faster but doesn't use `flavor='spark'`. I think it would be interesting to implement this feature on the dask side.

**Comment by rpanai** [comment]
Yes you are right about memory usage. In order to free some RAM you can add these three line between `pa.Table` and `pq.write`

```
import gc
del df
gc.collect()
```

**Comment by wesm** [comment]
I recall there being a JIRA open about performance and memory use of `write_to_dataset`; sometime will need to do some work on it to possibly improve memory use and performance. Can you open a JIRA with the reproducible example copy-pasted there? Thanks

**Comment by randomgambit** [comment]
@wesm done

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-2709
