### ISSUE TITLE
[Benchmarking] Support for on-demand and automated benchmarks

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#21560]
We want to be able to request for a benchmark comparison in a PR against master. This should be triggered via a github comment.

The automated benchmarks would track the master branch and be triggered either on each merge or nightly.

**Reporter**: [Francois Saint-Jacques](https://issues.apache.org/jira/browse/ARROW-5070) / @fsaintjacques
#### Related issues:
- [[C++] Implement benchmark comparison between two git revisions](https://github.com/apache/arrow/issues/21343) (is blocked by)
- [[Benchmarking] Performs a benchmark run with archery](https://github.com/apache/arrow/issues/21561) (is blocked by)
- [[Benchmarking] Add portable machine and benchmark context detection](https://github.com/apache/arrow/issues/21240) (is blocked by)
- [[C++] Whitelist benchmarks candidates for regression checks](https://github.com/apache/arrow/issues/21739) (is blocked by)
- [[Benchmarking] Performance Benchmarking Dashboard](https://github.com/apache/arrow/issues/20889) (is blocked by)

<sub>**Note**: *This issue was originally created as [ARROW-5070](https://issues.apache.org/jira/browse/ARROW-5070). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
The conbench machinery now allows us to do that, closing.
