### ISSUE TITLE
Installing the Python package without having Cython installed first

### ISSUE THREAD

**Issue by michaelnowotny** [apache/arrow#2163]
Dear arrow developers,

there is a small issue in that the pip install fails if Cython is not yet installed on the system. Here is the error message:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kj/w0rvnqw174709h_46v87mbf40000gp/T/pip-req-build-zylhd17x/setup.py", line 28, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'

This page documents a workaround to fix a similar issue with numpy:
https://forum.predix.io/questions/30529/python-setuppy-cant-import-module-even-though-that.html

Please let me know if you require further details!

Thank you,

Michael

## GitHub Issues for Apache Arrow

We support GitHub issues as a lightweight way to ask questions and engage with
the Arrow developer community. We use the Apache Software Foundation's JIRA
instance for maintaining a queue of development work and as the public record
for work on the project. So, feel free to delete this text and open an issue
here if you have a question or aren't sure whether something is a bug or
feature request. Any bugs, suggestions, or feature requests will eventually
need to end up in JIRA, either before or after completing a pull request.

See the Arrow JIRA project here: https://issues.apache.org/jira/browse/ARROW.

For more in-depth development discussions, please use the public mailing list
dev@arrow.apache.org (first subscribe by sending an e-mail to
dev-subscribe@arrow.apache.org).

**Comment by wesm** [comment]
Our source build presently requires both CMake and Cython. It would be a great deal of effort for us to fix this.

**Comment by allan-simon** [comment]
can it be added as a dependencies in your setup.py ?  (not a python expert) or can you at least state in your readme that cython and cmake is required ?

**Comment by xhochy** [comment]
This is already mentioned in the `setup_requires` section: https://github.com/apache/arrow/blob/c327af0d926c80855c6b1a07aa7dafc1ac1fc362/python/setup.py#L586
