### ISSUE TITLE
[js] Are there plans to support Parquet as a data format?

### ISSUE THREAD

**Issue by eode** [apache/arrow#2209]
Title pretty much says it all.   I'm using Javascript, and would like to be able to read/write (read, mainly) Parquet data.  I know it's not currently available, but is this a planned feature?

**Comment by wesm** [comment]
It's a good-sized project because of the dependency stack involved (Thrift, various compression libraries) and because Parquet itself is a somewhat complex file format. I opened https://issues.apache.org/jira/browse/ARROW-2786 so the feature can be tracked there

**Comment by eode** [comment]
Thanks.  There's some existing work under an MIT license or similar variant [here](https://github.com/ironSource/parquetjs).  It doesn't work for me, as it attempts to compile LZO, and it seems I don't have the right dev environment configured for that -- but it might be a useful start, or have some useful tidbits.

**Comment by wesm** [comment]
Ah, interesting. LZO isn't really used anymore (as soon as Snappy came around people largely stopped using it because of the *GPL licensing issues)

**Comment by ali-habibzadeh** [comment]
Was there progressed made on this?

**Comment by westonpace** [comment]
> Was there any progress made on this?

None yet.  The JIRA is still open and there is some discussion of alternatives (e.g. 3rd party parquet libraries, using the rust parquet implementation via wasm) but as far as I can glean from the mailing list there is no one working on a native JS parquet implementation within Apache Arrow.  There is ongoing JS work (I believe they even had a virtual meetup in February) being discussed on the mailing list so if this is something you are interested in working on I would recommend reaching out on the dev mailing list.

**Comment by eatonphil** [comment]
Others have reported that this library supports in-browser reading of Parquet files: https://github.com/kbajalc/parquets
