### ISSUE TITLE
Error inferring Arrow type for Python object array. Got Python object of type dict but can only handle these types: string, bool, float, int, date, time, decimal, list, array

### ISSUE THREAD

**Issue by rob-dempsey-esure** [apache/arrow#2219]
Hi

I am reading in a parquet file, processing using pandas and then writing it back to the same parquet file.  One column payload contains nested JSON records.  When trying to convert back to a parquet file I get the following

>>> panda_table2[['payload']]
                                             payload
0  {'data': {'document_id': None, 'document_type'...
1  {'data': {'document_id': None, 'document_type'...
2  {'data': {'document_id': None, 'document_type'...
3  {'data': {'document_id': None, 'document_type'...
4  {'data': {'document_id': None, 'document_type'...
5  {'data': {'document_id': None, 'document_type'...
6  {'data': {'document_id': None, 'document_type'...
7  {'data': {'document_id': None, 'document_type'...
8  {'data': {'document_id': None, 'document_type'...
>>> rob=panda_table2[['payload']]
>>> table_output = pa.Table.from_pandas(rob)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "table.pxi", line 926, in pyarrow.lib.Table.from_pandas
  File "C:\Users\rob\Anaconda3\lib\site-packages\pyarrow\pandas_compat.py", line 371, in dataframe_to_arrays
    convert_types)]
  File "C:\Users\rob\Anaconda3\lib\site-packages\pyarrow\pandas_compat.py", line 370, in <listcomp>
    for c, t in zip(columns_to_convert,
  File "C:\Users\rob\Anaconda3\lib\site-packages\pyarrow\pandas_compat.py", line 366, in convert_column
    return pa.array(col, from_pandas=True, type=ty)
  File "array.pxi", line 177, in pyarrow.lib.array
  File "error.pxi", line 77, in pyarrow.lib.check_status
  File "error.pxi", line 77, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Error inferring Arrow type for Python object array. Got Python object of type dict but can only handle these types: string, bool, float, int, date, time, decimal, list, array
>>> rob.dtypes
payload    object
dtype: object

I read through https://issues.apache.org/jira/browse/ARROW-1705 and thought this might be fixed in version 0.9? Or is this a different issue?

Thanks

Rob

**Comment by wesm** [comment]
hi Rob, can you open a JIRA for this and provide a reproducible example? https://stackoverflow.com/help/mcve

**Comment by rob-dempsey-esure** [comment]
Hi Wes

I hope that has all the details you need https://issues.apache.org/jira/browse/ARROW-2814

Rob

**Comment by wesm** [comment]
Thank you!

**Comment by parachutepy** [comment]
Hi, we are seeing this issue for time field. Is this a related issue?

File 'error.pxi', line 77, in pyarrow.lib.check_status~pyarrow.lib.ArrowInvalid: Error inferring Arrow type for Python object array. Got Python object of type **NaTType** but can only handle these types: string, bool, float, int, date, time, decimal, list, array~

**Comment by wesm** [comment]
No, this is something else. See https://issues.apache.org/jira/browse/ARROW-842
