### ISSUE TITLE
Java support for Feather

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#2240]
Is there a roadmap/guide on how the Java bindings could support Feather reading/writing? It would make spark pipelines output a pretty Python friendly file format --

**Comment by wesm** [comment]
It would be easier and a better idea to write the Arrow file format as it supports all Spark types (including nested types), chunked files, etc. Feather in its current form should be considered deprecated. Writing the Arrow file format from Java is already supported, so you would need to propose a patch to Spark to make this functionality available

**Comment by dmadeka** [comment]
Is the Arrow file format supported by R?

**Comment by wesm** [comment]
Not yet, hopefully by year end. I remain hopeful. See http://wesmckinney.com/blog/feather-arrow-future/

**Comment by dmadeka** [comment]
Is there an example of writing the arrow format from Python?

**Comment by wesm** [comment]
Sure, see http://arrow.apache.org/docs/python/ipc.html

**Comment by davips** [comment]
Is feather still not a good format for data interchange with other languages other then python and java?
