### ISSUE TITLE
Using struct in c++

### ISSUE THREAD

**Issue by dragan224** [apache/arrow#2241]
Hi,

Does anyone have a working example of using structs in arrow in c++? How would I write code that creates an arrow table using the following schema for example:

```
std::vector<std::shared_ptr<arrow::Field>> schema_vector = 
    {
        arrow::field("1", arrow::utf8()),
        arrow::field("2", arrow::struct_(
                            {arrow::field("test", arrow::utf8()),
                             arrow::field("test_2", arrow::utf8()}))
    };
```

I really tried to look all over the place and couldn't find it, so maybe consider updating the example in the repository with something more complex?

**Comment by wesm** [comment]
You'll want to build the child arrays using e.g. `arrow::StringBuilder` and then construct the StructArray directly, see e.g. some code we use in the unit tests: https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/test-common.h#L378
