### ISSUE TITLE
[Release] JAVA_HOME is inproperly set in the gen apidocs docker container

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#22416]
Maven and openjdk are installed by both the system package manager and conda, and JAVA_HOME is set to /opt/conda eventually.

So javadoc fails with: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-site) on project arrow-java-root: Error generating maven-javadoc-plugin:3.0.0-M1:aggregate: Unable to find javadoc command: The environment vari
able JAVA_HOME is not correctly set. -> [Help 1]

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-6010) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-6010](https://issues.apache.org/jira/browse/ARROW-6010). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
This container does not exist anymore, current doc job works.
