### ISSUE TITLE
[pyarrow] Should Table.from_pandas default to preserve_index=False?

### ISSUE THREAD

**Issue by danielcompton** [apache/arrow#2244]
I spent a bit of time tracking down why an `__index_level_0__` columns was being written to our Parquet files. Eventually we found that it was coming from the `from_pandas` method on Table. There is an optional parameter `preserve_index` which defaults to True. Setting it to False dropped the index on transfer and led to drastically smaller file sizes (4MB -> 1MB, 2M rows).

```python
table = pa.Table.from_pandas(df, preserve_index=False)
```

https://github.com/apache/arrow/blob/8c9890c3731688683024a14c12cdca34c2901077/python/pyarrow/table.pxi#L949-L950

Would it make sense to not preserve the index by default? In many cases (but maybe not all?) the index is not desired and bloats Parquet files. Presumably it would have a similar impact in-memory in the Arrow format.

**Comment by wesm** [comment]
It really depends on the user. We selected the defaults to faithfully store the data represented by the pandas DataFrame, so my view is that we should leave the default as is. This issue could probably be better highlighted in the Python documentation, though

We could possibly implement an optimization for the case of simple RangeIndex (similar to https://issues.apache.org/jira/browse/ARROW-1639) to reduce the storage footprint
