### ISSUE TITLE
Pandas Series of NaNs with dtype np.unicode_ converted to Null

### ISSUE THREAD

**Issue by jkulzick** [apache/arrow#2254]
When creating a PyArrow Array from a Pandas Series of dtype np.unicode_, the type will be null instead of string if all values in the Series are NaNs.

I'm unsure what the expected behavior is. I also found ARROW-1941, which seems related.

To reproduce in Arrow 0.9.0:
```
import pyarrow as pa
import pandas as pd
import numpy as np

# Series with all NaNs
null_array = pa.array(pd.Series([np.NaN, np.NaN], dtype=np.unicode_))
null_array.type

# Series with at least one string
string_array = pa.array(pd.Series([np.NaN, 'foo'], dtype=np.unicode_))
string_array.type
```

This results in the following output:
```
# null_array (incorrect; expected string)
DataType(null)

# string_array (correct)
DataType(string)
```

**Comment by xhochy** [comment]
This is the expected bahaviour as Pandas does not support `np.unicode_ as a dtype and converts it to `object` instead. With this conversion, any type information is lost and cannot be reretrieved by Arrow alter on.

```
>>> pd.Series([np.NaN, np.NaN], dtype=np.unicode_)
0    NaN
1    NaN
dtype: object
```

**Comment by jkulzick** [comment]
Makes sense. I did not think about the pandas type conversion. Thank you.
