### ISSUE TITLE
pyarrow latest parquet map column type isn't supported

### ISSUE THREAD

**Issue by den-rifiniti** [apache/arrow#2262]
Hello
When I trying read parquet file with  column of type `map`, `pyarrow.lib.ArrowNotImplementedError: lists with structs are not supported.` exception is throws.

Seems like this was fixed here https://github.com/apache/arrow/pull/1530, and only release is required?

**Comment by xhochy** [comment]
No, this would also require https://github.com/apache/parquet-cpp/pull/462

**Comment by wesm** [comment]
Assistance with this would be much appreciated. Unfortunately we haven't been able to get this done in time for 0.10, so it will have to be later this year

**Comment by wesm** [comment]
No It has not yet been implemented

**Comment by wesm** [comment]
@damache would anyone from IBM like to get involved with Parquet development? We could really use the help.

**Comment by sujayramaiah** [comment]
Most of the data files in our data lake has map columns. Not being able to read parquet files with map columns using pyarrow creates dependency on Spark. Is there a plan to support map columns?

**Comment by wesm** [comment]
Yes, but someone has to do the implementation work. See ARROW-1644 and related issues
