### ISSUE TITLE
[C++] vendor a half precision floating point library

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#22806]
Clang and GCC provide _Float16 and there are numerous polyfills which can emulate a 16 bit float for other platforms. This would fill a hole in the kernels and other code which don't currently support HALF_FLOAT.

**Reporter**: [Ben Kietzman](https://issues.apache.org/jira/browse/ARROW-6436) / @bkietz
**Watchers**: [Rok Mihevc](https://issues.apache.org/jira/browse/ARROW-6436) / @rok
#### Related issues:
- [[C++] Cast to/from halffloat not implemented](https://github.com/apache/arrow/issues/20213) (is depended upon by)

<sub>**Note**: *This issue was originally created as [ARROW-6436](https://issues.apache.org/jira/browse/ARROW-6436). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by rok** [comment]
I've looked at some libraries to see what is usually used:
* [TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/third_party/FP16/workspace.bzl) - uses FP16
* [Numpy](https://github.com/numpy/numpy/blob/7e86c2aadfc6dcee12274db698407275cede1b63/numpy/core/src/common/half.hpp#L2) seems to implement it's own arithmetic.
* [PyTorch](https://github.com/pytorch/pytorch/tree/be0b12ece576c86c5f059d15a64dcba0eb886ddd/third_party) - uses FP16
* [FP16](https://github.com/Maratyszcza/FP16/) - seems to be [composed](https://github.com/Maratyszcza/FP16/tree/master/third-party) mostly of [half](https://half.sourceforge.net/) and few functions taken from other places.

Half [seems pretty complete](https://half.sourceforge.net/namespacehalf__float.html) so I think it or [FP16](https://github.com/Maratyszcza/FP16) would make good candidates.

cc @pitrou @bkietz

**Comment by bkietz** [comment]
I think if available software implementations are unsatisfactory, it'd be preferable to write a very minimal version of our own and handle any operations by first converting to 32 bit float. This should be sufficient since we'd be able to use a native type most of the time. In that case, we'd only need to maintain:
- The cmake logic/flags necessary to enable native IEEE 754-2008 half precision floats when available
- The conversions `soft 16 bit float <=> 32 bit float`
  - Including bitwise equivalence to native 16 bit floats when available

**Comment by pitrou** [comment]
> I think if available software implementations are unsatisfactory, it'd be preferable to write a very minimal version of our own and handle any operations by first converting to 32 bit float.

If the HW-based conversions are available on all major CPUs (and compilers!), and they are fast enough, then I guess it's a sufficient approach.

**Comment by pitrou** [comment]
Some interesting details discussed here:
https://www.corsix.org/content/converting-fp32-to-fp16

**Comment by adamreeve** [comment]
#36036 added a new `arrow::util::Float16` class, with a comment saying the routines are "partially adapted from Numpy's C implementation".

So it looks like this can be closed?

**Comment by pitrou** [comment]
Thanks for the heads up @adamreeve . Yes, you're right, this can be closed now!
