### ISSUE TITLE
[js] can i deseralize a dictionary of dataframes in the js implementation?

### ISSUE THREAD

**Issue by gabomgp** [apache/arrow#2284]
Excelent project and i would like to use it, but i have a question about maturity/scope for the project...

The idea is to serialize a dictionary of pandas dataframes in python, send it to the browser and deserialize the dictionary, getting all tables and to work with the tables/dataframes. Is it a supported workflow just now? in the future?

**Comment by wesm** [comment]
You can send individual data frames but reading more complex collections isn't supported in JS yet. You could help by contributing to the respective libraries
