### ISSUE TITLE
[Firehose Partition]

### ISSUE THREAD

**Issue by IceS2** [apache/arrow#2286]
I was wondering if support for Firehose Partition was in the roadmap.
I actually tried to code it myself, but I couldnt build pyarrow locally with `pip install -e` .

**Comment by wesm** [comment]
Are you talking about AWS?

Installing with `pip install -e .` is not a supported method. See the documentation about building from source: https://github.com/apache/arrow/blob/master/python/doc/source/development.rst

**Comment by IceS2** [comment]
Hey, yes I'm talking about aws firehose. While hive partitions like year=2018/month=01/day=01 firehose partitions like 2018/01/01

**Comment by wesm** [comment]
This is being worked on in https://github.com/apache/parquet-cpp/pull/462

The Apache JIRA instance is https://issues.apache.org/jira. You'll need to open an account

**Comment by IceS2** [comment]
thanks for the help, created an issue. Not sure it's well made though.
https://issues.apache.org/jira/browse/ARROW-2882 
If changes need to be made, please let me know

**Comment by wesm** [comment]
Thank you
