### ISSUE TITLE
Using arrow to write parquet (ends up with an empty table)

### ISSUE THREAD

**Issue by dragan224** [apache/arrow#2287]
Hi all,

I have this piece of code which produces a valid parquet file (using an arrow table), however the contents of the file are empty.

Code: https://ideone.com/DJkKUF

When I run "parquet-tools cat test.parquet" and actually try to read the file, i get an empty output, shouldn't the file have 5 entries?

Edit: Furthermore when i run "parquet-tools schema test.parquet" the schema prints correctly:

message schema {
  optional group MyStruct {
    required binary str (UTF8);
  }
}

**Comment by wesm** [comment]
This is really a Parquet issue, can you open an issue with this information on the Apache Parquet JIRA?

**Comment by wesm** [comment]
FWIW, It looks like the non-nullable case might not be handled properly. Does it work if you make the string field nullable?

**Comment by dragan224** [comment]
Nope.

And I just notice that it throws this error: lemented: Level generation for Struct not supported yet. Sorry, didn't realize it before, but for some reason it still creates a file with a valid schema.

I'll go ask parquet folks. My guess is that they intended for structs to be written differently than what I'm doing there?

**Comment by wesm** [comment]
Thanks. It'll be the same people responding there but we'll see what's up
