### ISSUE TITLE
Compression not in Parquet filename extension

### ISSUE THREAD

**Issue by jkulzick** [apache/arrow#2310]
I noticed that Spark will write out Snappy compressed Parquet files as '.snappy.parquet'. However, in `pyarrow.parquet.write_to_table` for example [here](https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L1157), the file extension is always '.parquet' regardless of the `compression`. Is this the intended behavior?

**Comment by xhochy** [comment]
Yes this is intended behaviour. The compression is part of the format specification and applied on a per-column basis (see https://github.com/apache/parquet-format/blob/518e206c3e6586b76e8315d5f62a8666ed62fa90/src/main/thrift/parquet.thrift#L631) Normally all interfaces only support setting compression globally but there are users that actually use the low-level interface to apply the compression only to a select subset. Thus having the compression as part of the filename is a bit misleading.

Note that this is in total contrast to formats like JSON where compression is applied outside the actual format implementations.

**Comment by jkulzick** [comment]
Thank you for the detailed explanation!
