### ISSUE TITLE
[C++] Add/document configuration to build with WebAssembly

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23221]
Not something I plan to work on, but given that https://github.com/finos/perspective created a custom wasm build of Arrow, it would seem a good idea to have a standard way for wasm projects to use the Arrow C++ library

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-6894) / @wesm

<sub>**Note**: *This issue was originally created as [ARROW-6894](https://issues.apache.org/jira/browse/ARROW-6894). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by joemarshall** [comment]
It would definitely seem worth building for webassembly nowadays, or at least building pyarrow and the required dependencies given (a) webassembly is an officially supported platform in python 3.11 and (b) pandas supports arrow as a backend officially, which won't work on webassembly until there is a reliable arrow build.

The core of arrow builds fine in wasm, but several things make it a pain to build a working pyarrow. These are:

1) Threads don't work in many webassembly environments (including pyodide), and there's no simple way of just removing threading in arrow build right now (I think?)
2) Dependencies have to be built in arrow - this is okay for the set needed for pyarrow, but I never did manage to get them automatically downloading and building using the configuration in emscripten. I think some work is required on the download and build cmake calls to make sure they inherit all the emscripten flags etc. correctly.
3) I couldn't make the setup.py work correctly for pyarrow, which is probably a similar problem to how it interacts with the pyodide package build process.

**Comment by joemarshall** [comment]
This is pretty much the same as #34996 - in that it requires #35471 to work for it to be usable in most webassembly environments (i.e. browsers).
