### ISSUE TITLE
toPandas() speed on small dataframes with Arrow

### ISSUE THREAD

**Issue by dvanasseldonk** [apache/arrow#2328]
Is it normal to expect similar or worse speed of toPandas() on a dataframe of 100 rows and 5 columns after enabling Apache Arrow on Spark 2.3.0.

For
spark.conf.set("spark.sql.execution.arrow.enabled", "true")
toPandas() runs in ~600ms

and for
spark.conf.set("spark.sql.execution.arrow.enabled", "false")
toPandas() runs in ~200ms

code here:
---------------
import pandas
import time
from timeit import default_timer as timer
import pyspark
from pyspark.sql.functions import rand

global spark
spark = pyspark.sql.SparkSession.builder.appName("apache arrow test").getOrCreate()
print(spark.version)
from pyspark.conf import SparkConf
conf = SparkConf()

df = spark.range(100).toDF("id").withColumn("x", rand()).withColumn("y", rand()).withColumn("z", rand()).withColumn("a", rand()).withColumn("b", rand())
df.printSchema()
df.show(100, False)

spark.conf.set("spark.sql.execution.arrow.enabled", "true")

start = timer()
pdf = df.toPandas()
end = timer()
print(end - start)

**Comment by icexelloss** [comment]
Hi,

Seems like this is more appropriate for the Spark project, do you mind open a Jira ticket here?
https://issues.apache.org/jira/projects/SPARK/issues/SPARK-14220?filter=allopenissues
