### ISSUE TITLE
[C#] System.Memory  Span.CopyTo - Crashes on Net Framework 

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23350]
The following code crashes on 8 cores.
```java

        public async Task StringArrayBuilder_StressTest()
        {
            var wait = new List<Task>();            
            for (int i = 0; i < 30; ++i)
            {
                var data = Enumerable.Range(0, 1000).Select(x => $"Item {x + 1}").ToArray();                
                var t = Task.Run(() =>
                {
                    for (int j = 0; j < 10000000; ++j)
                    {
                        var builder = new StringArray.Builder();
                        builder.AppendRange(data);
                    }
                });                
                wait.Add(t);
            }            

            await Task.WhenAll(wait);
        } 
```
 

It does not happen with the primitive arrays.  (ie IntArrayBuilder)

I suspect it is due to the offset array / and all the copy / resizing going on

 

Update - it seems that the problem is in the underlying **ArrowBuffer.Builder<T>**
```java

         public async Task ValueBuffer_StressTest()
        {
            var wait = new List<Task>();            
            for (int i = 0; i < 30; ++i)
            {
                var data = Enumerable.Range(0, 1000).Select(x => $"Item {x + 1}").ToArray();                
                var t = Task.Run(() =>
                {
                    for (int j = 0; j < 10000000; ++j)
                    {
                        ArrowBuffer.Builder<byte> ValueBuffer = new ArrowBuffer.Builder<byte>();                        
                        foreach (var d in data)
                        {
                            ValueBuffer.Append(Encoding.UTF8.GetBytes(d));
                        }
                    }
                });                
                wait.Add(t);
            }            
            await Task.WhenAll(wait);
        }
```
 

Update 2:

This is due to a confirmed bug in System.Memory - The implications are that Span.CopyTo needs to be removed / replaced. 

This is method is used internally by ArrowBuffer so I can't work around this easily. 

Solutions
1. Change the code
   1. Remove it out right (including disable span in FlatBuffer)
   1. create a multi target nuget where the offending code has compile blocks #If (NETFRAMEWORK) - and disable span in FlatBuffers only for net framework build 
1. wait for a System.Memory fix?
   
    
   
   I suspect option 2 won't happen anytime soon.  
   
    

**Reporter**: [Anthony Abate](https://issues.apache.org/jira/browse/ARROW-7040) / @abbotware
#### PRs and other links:
- [GitHub Pull Request #6122](https://github.com/apache/arrow/pull/6122)

<sub>**Note**: *This issue was originally created as [ARROW-7040](https://issues.apache.org/jira/browse/ARROW-7040). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Fixed upstream https://github.com/apache/arrow/pull/6122#issuecomment-670770541
