### ISSUE TITLE
[Developer] Apply language tags automatically by GitHub Actions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23364]
Split from ARROW-6942.

**Reporter**: [Micah Kornfield](https://issues.apache.org/jira/browse/ARROW-7055) / @emkornfield

<sub>**Note**: *This issue was originally created as [ARROW-7055](https://issues.apache.org/jira/browse/ARROW-7055). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Implemented
