### ISSUE TITLE
[JS][CI][Archery] Move nodejs linting from js_build.sh to archery

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23430]
Currently all the linters are run by archery, except just a couple ones, like the [js linter](https://github.com/apache/arrow/blob/master/ci/scripts/js_build.sh#L29). We should add support for it into archery and run in the lint build.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-7126) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-7126](https://issues.apache.org/jira/browse/ARROW-7126). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kszucs** [comment]
It hasn't been a real problem in the last 4 years so I would say no :) 

Closing the issue.
