### ISSUE TITLE
[CI][Crossbow] Add extra testing groups for on-demand builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23488]
We should have an easy way to trigger an extra set of builds but not the full matrix that runs nightly. For example, we should have a python group that runs one conda osx build, one wheel build, etc., not across all versions. Most of the time when we have a nightly build failure on python packaging, we get 5 failures for the same error, so we should be able to detect these more cheaply.

We already have build groups in crossbow, so this means adding new groups.

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-7190) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-7190](https://issues.apache.org/jira/browse/ARROW-7190). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Implemented
