### ISSUE TITLE
[CI][Crossbow] Nightly build email should distinguish between new failures and still failing builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23489]
It would help with triaging the nightly build status if it were more readily visible which builds broke today vs. are still broken (and were triaged yesterday).

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-7191) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-7191](https://issues.apache.org/jira/browse/ARROW-7191). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
http://crossbow.voltrondata.com
