### ISSUE TITLE
[C++] Coerce Arrow half-precision float to float32

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23537]
When trying to save a Pandas DF using "to_parquet" when that DF has a column with a dtype of float16, I get the error: "pyarrow.lib.ArrowNotImplementedError: Unhandled type for Arrow to Parquet schema conversion: halffloat"

**Reporter**: [Naor Volkovich](https://issues.apache.org/jira/browse/ARROW-7242)

<sub>**Note**: *This issue was originally created as [ARROW-7242](https://issues.apache.org/jira/browse/ARROW-7242). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Parquet now has halffloats! Closed with https://github.com/apache/arrow/issues/37582
