### ISSUE TITLE
Floating point exception when running df.to_parquet(engine='pyarrow')

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow#2360]
Running `df.to_parquet(path, engine='pyarrow')` crashes Python and the shell tells me `floating point exception`. Sadly, I can't share the source data, so I'll give the dtypes and general schema with the hope that someone knows an area of code that's the likely culprit.

The DataFrame has 11761443 rows x 9 columns. Column dtypes are 
```
object
object
object
object
datetime64[ns]
datetime64[ns]
bool
bool
bool
```

The index is a MultiIndex with two levels, `object` and `uint16`. I'm guessing this isn't enough information, but it was worth a shot.

**Comment by wesm** [comment]
Can you open a JIRA for this, please? If you come up with a minimum viable repro that would be helpful

**Comment by kylebarron** [comment]
I'll try to find some time to search for a reproducible example.

**Comment by wesm** [comment]
@kylebarron any luck on this?

**Comment by kylebarron** [comment]
Sorry, I haven't spent any more time trying to reproduce it. If I come across it again, I'll try to reproduce it again.
