### ISSUE TITLE
What frameworks / libraries support arrow?

### ISSUE THREAD

**Issue by AnthonyJacob** [apache/arrow#2361]
Hi,

apart from the image on arrow website I could not find a comprehensive list of all framework and libraries where I can get a interoperability benefit by using arrow.

For example if I were about to display pandas dataframe in java, I can do it like this: pandas->pyarrow->plasma->java, so even though I will still have to convert pandas datframe to pyarrow table, the rest will be noop, which should be efficient enough, unless I am displaying tons of dataframes... 

Am I right? What other frameworks and libraries can I communicate this way?

**Comment by wesm** [comment]
Hi -- could you ask on the Arrow mailing list? Thanks
