### ISSUE TITLE
[JS] Implement list contains predicate

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23976]
As far as I can see there is no way to check if a list contains a specific element.

My code is as follows:

 
```java

var listChild = new arrow.Field('list[Utf8]', new arrow.Utf8())

var all = arrow.Table.new([
 arrow.DateVector.from(dates),
 arrow.Int32Vector.from(flumeseqs),
 arrow.Utf8Vector.from(keys),
 arrow.Vector.from({ values: authors, type: new arrow.Dictionary(new arrow.Utf8(), new arrow.Int32()) }),
 arrow.Int32Vector.from(sequences),
 arrow.Vector.from({ values: types, type: new arrow.Dictionary(new arrow.Utf8(), new arrow.Int32()) }),
 arrow.Vector.from({ values: links, type: new arrow.List(listChild) }),
 ], ["date", "flumeseq", "key", "author", "sequence", "type", "links"])
```
And I want to get all the items that has a specific element in the links section.

So something like:

 
```java

var q2 = Array.from(
all.filter(
 arrow.predicate.col('links').contains('%GcvjVk+NLsjOB5Vd+vceGXEOeYmHoRA6lgXVJzPuMxw=.sha256')))
```
 

 

**Reporter**: [Anders Rune Jensen](https://issues.apache.org/jira/browse/ARROW-7738)

<sub>**Note**: *This issue was originally created as [ARROW-7738](https://issues.apache.org/jira/browse/ARROW-7738). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
We removed predicate support. Please use something like arquero now.
