### ISSUE TITLE
[CI][Packaging] Add nightly test that pip-installs nightly wheels

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24081]
This would catch issues with wheels that we only encountered during release verification.

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-7853) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-7853](https://issues.apache.org/jira/browse/ARROW-7853). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Our wheel jobs now pip-install the generated wheels, closing as stale.
