### ISSUE TITLE
Reading native ARROW format

### ISSUE THREAD

**Issue by brightsparc** [apache/arrow#2409]
Is there a way to load a file stored in the native ARROW format (instead of PARQUET)
eg: https://unpkg.com/@jpmorganchase/perspective-examples@0.1.18/build/superstore.arrow

I'm able to use the following code to get the read the raw bytes.

```
buf = pa.OSFile('superstore.arrow', 'rb').read_buffer()
reader = pa.BufferReader(buf)
reader.read()

```
I have been able to verify that I can read a parquet formatted file.

```
df = pd.DataFrame({'one': [-1, np.nan, 2.5],
   'two': ['foo', 'bar', 'baz'],
   'three': [True, False, True]},
   index=list('abc'))
table = pa.Table.from_pandas(df)
pq.write_table(table, 'example.parquet')
# read back the file
buf = pa.OSFile('example.parquet', 'rb').read_buffer()
reader = pa.BufferReader(buf)
pq.read_table(reader)

```

Is there a way to load the native ARROW file with `pyarrow`?

**Comment by wesm** [comment]
See http://arrow.apache.org/docs/python/ipc.html#writing-and-reading-random-access-files

**Comment by brightsparc** [comment]
@wesm Thanks, not sure how I missed that but simple in the end:

```
df = pa.open_file('superstore.arrow').read_pandas()
df.info()
```
