### ISSUE TITLE
[Plasma] Add GCS as an external store for Plasma

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24246]
This will allow objects to be evicted to Google Cloud Storage when Plasma runs out of memory.

**Reporter**: [Clark Zinzow](https://issues.apache.org/jira/browse/ARROW-8031)
#### Related issues:
- [[C++] Add filesystem / IO implementation for Google Cloud Storage](https://github.com/apache/arrow/issues/17070) (is blocked by)
- [[Plasma] Add S3 as external store for Plasma](https://github.com/apache/arrow/issues/21035) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-8031](https://issues.apache.org/jira/browse/ARROW-8031). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
