### ISSUE TITLE
[C++][Packaging] Add OpenSSL / encryption support to C++ packages

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24253]
This is an umbrella issue for tackling encryption support in the various packaging targets (Linux deb/rpm, Homebrew, conda, etc.)

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-8038) / @wesm
#### Subtasks:
- [X] [[Packaging][deb][RPM] Enable Parquet encription](https://github.com/apache/arrow/issues/26670)

<sub>**Note**: *This issue was originally created as [ARROW-8038](https://issues.apache.org/jira/browse/ARROW-8038). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
I think this is done in pretty much all binary packages now. Closing.
