### ISSUE TITLE
[C++][Plasma] Fix memory size when using huge pages in plasma; other code cleanups

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24291]
In the original code, 'PlasmaAllocator::SetFootprintLimit' happens before dealing with huge pages, which could change the memory limit. Also I found other dirty code needed to be written in a better way.

**Reporter**: [Siyuan Zhuang](https://issues.apache.org/jira/browse/ARROW-8081) / @suquark
#### PRs and other links:
- [GitHub Pull Request #6587](https://github.com/apache/arrow/pull/6587)

<sub>**Note**: *This issue was originally created as [ARROW-8081](https://issues.apache.org/jira/browse/ARROW-8081). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
