### ISSUE TITLE
[C++] Port the toolchain build from Appveyor to Github Actions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24299]
**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-8089) / @kszucs
#### PRs and other links:
- [GitHub Pull Request #6592](https://github.com/apache/arrow/pull/6592)

<sub>**Note**: *This issue was originally created as [ARROW-8089](https://issues.apache.org/jira/browse/ARROW-8089). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
I have created https://github.com/apache/arrow/issues/24299 which is more up to date

**Comment by raulcd** [comment]
I meant: https://github.com/apache/arrow/issues/42137
