### ISSUE TITLE
[Dev] Set JIRA ticket's status to in progress once a pull request available

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24295]
It's hard to see which tickets are in progress. Github actions build can be triggered on pull request creation and edit where we can parse out the Jira ticket. Call to the jira API to update the ticket's state (possibly update the components field as well.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-8085) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-8085](https://issues.apache.org/jira/browse/ARROW-8085). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
No longer applicable due to migration to GitHub issues.
