### ISSUE TITLE
[C++][CI] Revisit the flaky S3 tests caused by recent minio 

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24340]
See change in https://github.com/apache/arrow/pull/6632/files#diff-01448dc0a0e3217fd1579b81a915d593R843

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-8134) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-8134](https://issues.apache.org/jira/browse/ARROW-8134). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
This was opened in 2020 and we're now testing with a Minio version from 2022, closing as outdated
