### ISSUE TITLE
[Python] Start plasma store with STDOUT, STDERR arguments

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24493]
It seems that STDOUT and STDERR are always None, and non-configurable:

<https://github.com/apache/arrow/blob/b789226ccb2124285792107c758bb3b40b3d082a/python/pyarrow/plasma.py#L119>

 

Would it be possible to add them to the API? I get many printouts, which normally I would stream to a dedicated log file or to /dev/null.

**Reporter**: [Tal Pritzker](https://issues.apache.org/jira/browse/ARROW-8302)

<sub>**Note**: *This issue was originally created as [ARROW-8302](https://issues.apache.org/jira/browse/ARROW-8302). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
