### ISSUE TITLE
[CI][C++][R] Build and run C++ tests on Rtools build

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24561]
Maybe this will better identify our unexplained segfaults

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-8377) / @nealrichardson
#### PRs and other links:
- [GitHub Pull Request #6879](https://github.com/apache/arrow/pull/6879)

<sub>**Note**: *This issue was originally created as [ARROW-8377](https://issues.apache.org/jira/browse/ARROW-8377). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
I'll close this as stale.
