### ISSUE TITLE
AttributeError: module 'pyarrow' has no attribute 'compat' upong importing pyarrow

### ISSUE THREAD

**Issue by lpatruno** [apache/arrow#2468]
Hi folks,

I just installed pyarrow with `pip`. Here is the output:

```
Collecting pyarrow
  Using cached https://files.pythonhosted.org/packages/c9/b8/076ebd968f3c6d4e9b6e5de696f0b19964a3d4b7dc020fd32db4e868ad74/pyarrow-0.10.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.0.0 in /opt/conda/lib/python3.6/site-packages (from pyarrow) (1.11.0)
Requirement already satisfied: numpy>=1.10 in /opt/conda/lib/python3.6/site-packages (from pyarrow) (1.13.3)
Installing collected packages: pyarrow
Successfully installed pyarrow-0.10.0
```

However when I try to import the package I get an errror:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-f1048abcb32d> in <module>()
----> 1 import pyarrow

/opt/conda/lib/python3.6/site-packages/pyarrow/__init__.py in <module>()
     48 
     49 
---> 50 import pyarrow.compat as compat
     51 
     52 

AttributeError: module 'pyarrow' has no attribute 'compat'
```

I tried uninstalling and reinstalling but it did not help. Any ideas?

**Comment by lpatruno** [comment]
Hmm. Installing with `conda install -c conda-forge pyarrow` fixes this issue. Let me know if you folks need any diagnostics to help debug.

**Comment by kszucs** [comment]
With `numpy=1.13.3`:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/961747/44598586-ca5f9580-a7d3-11e8-83fb-db713b996ec8.png">

**Comment by wesm** [comment]
You might have had two different versions of pyarrow installed (one with pip, another older one with conda)

**Comment by lpatruno** [comment]
Thanks @kszucs . I was able to replicate the issue.

If I install `pyarrow` with numpy version 1.13.1, I get the error.

If I uninstall numpy 1.13.1, install 1.15.1, and then install pyarrow (with `pip`) I can import pyarrow with error.

FYI @wesm ...

**Comment by wesm** [comment]
Is there an ABI conflict? AFAIK we are building wheels against NumPy 1.14

**Comment by xhochy** [comment]
We're actually building against 1.10 to support old NumPy version. I'll have a look at the docker output to see what's going wrong there.

**Comment by xhochy** [comment]
This is a problem introduced by installing tensorflow: https://travis-ci.org/apache/arrow/jobs/421710986#L9970

**Comment by xhochy** [comment]
Actual cause and JIRA: https://issues.apache.org/jira/browse/ARROW-3141

**Comment by Schmidtbit** [comment]
I am getting this same error with numpy 1.16.4 and pyarrow 0.11.0

**Comment by wesm** [comment]
pyarrow 0.11.0 is not supported, recommend that you upgrade

**Comment by mstewart141** [comment]
for future readers of this thread: the issue can also be caused by pytorch, in addition to tensorflow; presumably other DL libraries may also trigger it.

**Comment by a5creel** [comment]
I've been working on this problem for a week now and am still getting this error. Tried rearranging the import order, as well as uninstalling numpy and pyarrow. 

It worked on a previous machine and now fails on a new ec2 instance. 

numpy 1.21.6

pyarrow 9.0.0     

```

myPacker_df = dd.read_parquet('s3://XXX/YYY/summary_i/', engine = "pyarrow")  
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-9934e78b02e8> in <module>
----> 1 myPacker_df = dd.read_parquet('s3://yse-bioecon/meat_packers/summary_i/', engine = "pyarrow")

~/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, chunksize, **kwargs)
    208 
    209     if isinstance(engine, str):
--> 210         engine = get_engine(engine)
    211 
    212     if hasattr(path, "name"):

~/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in get_engine(engine)
    495     elif engine == "pyarrow" or engine == "arrow":
    496         pa = import_required("pyarrow", "`pyarrow` not installed")
--> 497         from .arrow import ArrowEngine
    498 
    499         if LooseVersion(pa.__version__) < "0.13.1":

~/anaconda3/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py in <module>
      7 import pyarrow as pa
      8 import pyarrow.parquet as pq
----> 9 from pyarrow.compat import guid
     10 from ....utils import natural_sort_key, getargspec
     11 from ..utils import _get_pyarrow_dtypes, _meta_from_dtypes

ModuleNotFoundError: No module named 'pyarrow.compat'
```

**Comment by a5creel** [comment]
For future readers: pyarrow compat was depreciated at some point, uninstalled pyarrow 9.0.0 and installed pyarrow 4.0.0 which fixed the problem.

**Comment by xhochy** [comment]
@a5creel A better fix is probably to upgrade your dask version to be compatible with newer `pyarrow`, not downgrading `pyarrow`.

**Comment by edwardmoradian** [comment]
Just in general, sometimes simply restarting the Kernel after install/upgrading/uninstalling packages have worked for me on issue like this one.
