### ISSUE TITLE
[Python] from pyarrow import parquet fails with AttributeError: type object 'pyarrow._parquet.Statistics' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24724]
I have tried versions 0.15.1, 0.16.0, 0.17.0. Same error on all. I've seen in other issues that co-installations of tensorflow and numpy might be causing issues. I have tensorflow==1.14.0 and numpy==1.16.4 (and many other libraries, but I've read that those tend to cause issues)

 

``

 
```java

from pyarrow import parquet
 
~/python/lib/python3.6/site-packages/pyarrow/parquet.py in <module>
 32 import pyarrow as pa
 33 import pyarrow.lib as lib
---> 34 import pyarrow._parquet as _parquet
 35 
 36 from pyarrow._parquet import (ParquetReader, Statistics, # noqa
~/python/lib/python3.6/site-packages/pyarrow/_parquet.pyx in init pyarrow._parquet()
 
AttributeError: type object 'pyarrow._parquet.Statistics' has no attribute '__reduce_cython__'
```
``

**Environment**: Python 3.8.4, GCC 4.8.4, Debian 8
**Reporter**: [Hal T](https://issues.apache.org/jira/browse/ARROW-8557)

<sub>**Note**: *This issue was originally created as [ARROW-8557](https://issues.apache.org/jira/browse/ARROW-8557). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Giving this is an old issue, going to close this. 

Hal T, if you still encountered this with more recent versions of pyarrow, please let us know!
