### ISSUE TITLE
[Python] pa.array() sometimes ignore "safe=False"

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24733]
Generally, `pa.array(data).cast(sometype, safe=...)` is equivalent to
`pa.array(data, sometype, safe=...)`. Consider the following:

```python

>>> pa.array([Decimal('12.34')]).cast(pa.int32(), safe=False)                                                                                                               
<pyarrow.lib.Int32Array object at 0x7efbbd1556e0>
[
  12
]
>>> pa.array([Decimal('12.34')], pa.int32(), safe=False)                                                                                                                    
<pyarrow.lib.Int32Array object at 0x7efbbd13dad0>
[
  12
]
```

However, that is not always the case:
```python

>>> pa.array([Decimal('1234')]).cast(pa.int8(), safe=False)                                                                                                                 
<pyarrow.lib.Int8Array object at 0x7efbbd18e4b0>
[
  -46
]
>>> pa.array([Decimal('1234')], pa.int8(), safe=False)                                                                                                                      
Traceback (most recent call last):
  ...
ArrowInvalid: Value 1234 too large to fit in C integer type
```

I don't think this is very important: first because you can call cast() directly, second because the results are unusable anyway.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-8567) / @pitrou
#### Related issues:
- [[Python] Table.from_pandas is doing unsafe cast for float array to int array](https://github.com/apache/arrow/issues/31857) (relates to)
#### PRs and other links:
- [GitHub Pull Request #13936](https://github.com/apache/arrow/pull/13936)

<sub>**Note**: *This issue was originally created as [ARROW-8567](https://issues.apache.org/jira/browse/ARROW-8567). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by AlenkaF** [comment]
We created an "umbrella" issue that includes all the issues opened and connected to the Python to array conversion following the codepath in `python_to_arrow.cc`. See: https://github.com/apache/arrow/issues/36202
