### ISSUE TITLE
[CI] Add descriptions to the docker-compose images

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24853]
Add docstring like descriptions to the docker-compose services.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-8697) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-8697](https://issues.apache.org/jira/browse/ARROW-8697). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@kszucs Should we keep this open?

**Comment by kszucs** [comment]
We can either mark it as "good-first-issue" or just simply close it, I don't have a strong preference.

**Comment by pitrou** [comment]
Ok, if it's not particularly useful we can just close.
