### ISSUE TITLE
[ARROW-3137] pyarrow 0.10 requires newer version of numpy than specified in requirements

### ISSUE THREAD

**Issue by jpcampb2** [apache/arrow#2490]
pyarrow 0.10 appears to have a binary incompatibility with numpy versions prior to the 1.14.x series, but its requirements file claims support for numpy>=1.10.0

If an older version of numpy is used, the following RuntimeError results: `RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb`

The following tox.ini file demonstrates the issue:
```
[tox]
envlist=py27-numpy{10,11,13,14,15}-pyarrow{9,10}

[testenv]
deps =
    numpy10: numpy>=1.10.0,<1.11
    numpy11: numpy>=1.11.0,<1.12
    numpy13: numpy>=1.13.0,<1.14
    numpy14: numpy>=1.14.0,<1.15
    numpy15: numpy>=1.15.0,<1.16
    pyarrow9: pyarrow==0.9.0
    pyarrow10: pyarrow==0.10.0
    pytest

commands =
    pytest
```

Using a simple test function like the following:

```
def test_import_pyarrow():
    import pyarrow
```

pyarrow 0.9 doesn't appear to have this issue. Was there a change in the setup process for pyarrow 0.10 that no longer uses Cython to build?

**Comment by wesm** [comment]
Can you open a JIRA please? Thank you

**Comment by jpcampb2** [comment]
Created https://issues.apache.org/jira/browse/ARROW-3137

**Comment by wesm** [comment]
Thanks
