### ISSUE TITLE
Querying files with 10,000s of columns and 100,000s of rows

### ISSUE THREAD

**Issue by srp33** [apache/arrow#2491]
We have some biological datasets with 10,000s of columns and 100,000s of rows. Currently, we are storing the data in Parquet files and using pyarrow+pandas to read and filter the data. Users specify queries to filter the rows. And they indicate which columns they want to select.

This works well in most cases. But sometimes our users want to select *all* columns (but only some of the rows). Currently, we read all the data into a pandas DataFrame and then filter the rows. This is memory intensive when all columns are selected because the full dataset needs to be read. We are looking for a way to filter the rows before pulling data for all the columns.

Could we do something like the following?

1. Read only the columns specified in the filtering criteria and identify row indices that match the filtering criteria.
2. Read the rows that match those row indices.

Perhaps (probably?) we are thinking about this all wrong. Or perhaps Parquet is the wrong tool for the job. If you have any pointers or tips, we would greatly appreciate them.

Thanks for your time!

**Comment by xhochy** [comment]
Parquet supports predicate pushdown on RowGroup and Page level. While page-level filtering is not yet available and will be a bit more complex to implement, you can already do basic RowGroup filtering using `pyarrow`. With `pyarrow.ParquetFile(…).metadata.row_group(…).column(…).{min,max}` you get the minimum and maximum of a RowGroup for a given column. When you compare your filters against these statistics, you should be able to only read a subset of the file using `read_rowgroup`.

This though depends on that you already have written your Parquet files with more than one RowGroup. You can achieve this by setting a `chunk_size` in `write_table` that matches to your problem. Normally `pyarrow` will only write Parquet files with a single RowGroup.

**Comment by srp33** [comment]
@xhochy Thanks for your response! Would it be unreasonable to create a separate RowGroup for each row of data in the parquet file? Instead of getting the min or max, could we use that to just grab all the data in that single row? Would that have significantly negative side effects?

**Comment by xhochy** [comment]
Yes, that would remove most of the benefits of a columnar file format. If you really want to filter exactly to one row (assuming that your rows are quite large). It would be better to use a row-wise format like Avro.
To use Parquet, you should at least have 100 rows per RowGroup and for effective use, this should be well above 10k rows per RowGroup.

**Comment by jskalant** [comment]
@srp33 Hey Stephen,

How did you resolve this?  I have a similar case from the market research industry.

I have a dataset with over 500,000 columns and over two million rows and we need to read and filter the data from disk for a group of columns at a time, or for all columns but only a handful of rows at the time.

Cheers,

JC

**Comment by srp33** [comment]
JC,

It's still a work in progress, but our preprint article here (https://www.biorxiv.org/content/10.1101/536979v1) describes our preliminary solution and links to some code on GitHub.

Enjoy!

**Comment by westonpace** [comment]
@tday you may want to open up a new issue.  You will also likely need to provide some more details about what your overall goal is.

**Comment by srp33** [comment]
@tday I did some benchmarks and did not find a way to get good performance. I have an alternative solution that works really well. I'm creating a Python package. It's not quite ready yet. I'm happy to let you know when it is, if there's a way to get in touch.
