### ISSUE TITLE
[C++][CI] Add a test job for iOS

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24951]
**Reporter**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-8806) / @kou

<sub>**Note**: *This issue was originally created as [ARROW-8806](https://issues.apache.org/jira/browse/ARROW-8806). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@kou Should we close this issue or keep it open?
