### ISSUE TITLE
[Release] Calculate the committer statistics from the master branch

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#24989]
Out current workflow for patch releases starts with cherry picking the selected patches from the master branch to a maint-\* branch which means that the original committer data gets lost.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-8850) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-8850](https://issues.apache.org/jira/browse/ARROW-8850). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Committee data is lost due to API merge anyway and needs to be extracted from commit message.
