### ISSUE TITLE
[C#] Update to .NET SDK 3.1

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25079]
We should update our tools to the latest .NET SDK - 3.1. This will enable new tooling features, such as the code style rules package that will enforce coding style:

<https://github.com/apache/arrow/pull/7246#issuecomment-634206767>

 

There are 3 places that I know of that need updating:

 

<https://github.com/apache/arrow/blob/master/.github/workflows/csharp.yml>

<https://github.com/apache/arrow/blob/f16f76ab7693ae085e82f4269a0a0bc23770bef9/.github/workflows/dev.yml#L132>

<https://github.com/apache/arrow/blob/f16f76ab7693ae085e82f4269a0a0bc23770bef9/dev/release/verify-release-candidate.sh#L327>

 

**Reporter**: [Eric Erhardt](https://issues.apache.org/jira/browse/ARROW-8953) / @eerhardt

<sub>**Note**: *This issue was originally created as [ARROW-8953](https://issues.apache.org/jira/browse/ARROW-8953). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by CurtHagenlocher** [comment]
Closing this as relatively obsolete; the currently-used SDK is 7.0.x.
