### ISSUE TITLE
[Python] Make NumPy an optional runtime dependency

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25118]
Since in the relatively near future, one will be able to do non-trivial analytical operations and query processing natively on Arrow data structures through pyarrow, it does not make sense to require users to always install NumPy when they install pyarrow. I propose to split the NumPy-depending parts of libarrow_python into a libarrow_numpy (which also must be bundled) and moving this part of the codebase into a separate Cython module.

This refactoring should be relatively painless though there may be a number of packaging details to chase up since this would introduce a new shared library to be installed in various packaging targets. 

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-8998) / @wesm
#### Related issues:
- [C++ project doesn't need to require Numpy with ARROW_PYTHON=ON because it only builds Python extension's support libraries](https://github.com/apache/arrow/issues/32150) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-8998](https://issues.apache.org/jira/browse/ARROW-8998). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
I am currently investigating this. I also found this ML thread from 2021: https://lists.apache.org/thread/gwrhwv4p55ccrgrqontpodkwzgzr88w1

**Comment by pitrou** [comment]
Issue resolved by pull request 41904
https://github.com/apache/arrow/pull/41904
