### ISSUE TITLE
Segmentation fault when reading a Parquet partitioned dataset to a Parquet file

### ISSUE THREAD

**Issue by yingw787** [apache/arrow#2511]
Steps to reproduce:

1. Create a partitioned dataset with the following code:

```python
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

df = pd.DataFrame({
    'one': [-1, 10, 2.5, 100, 1000, 1, 29.2],
    'two': [-1, 10, 2, 100, 1000, 1, 11],
    'three': [0, 0, 0, 0, 0, 0, 0]
})
table = pa.Table.from_pandas(df)
pq.write_to_dataset(table, root_path='/home/yingw787/misc/example_dataset', partition_cols=['one', 'two'])
```

2. Create a Parquet file from a PyArrow Table created from the partitioned Parquet dataset:

```python
import pyarrow.parquet as pq

table = pq.ParquetDataset('/path/to/dataset').read()
pq.write_table(table, '/path/to/example.parquet')
```

EXPECTED:
- Successful write

GOT:
- Segmentation fault

**Comment by yingw787** [comment]
I may be missing something critical of the Parquet format, so please let me know if I am, but it would also be nice if this error was caught before the C extension and a nicer message was printed out.

**Comment by yingw787** [comment]
Note: There may be a relationship to the 'category' dtype in pandas, as I just tried to generate a datashape from a pandas dataframe generated from this partitioned dataset and I got a TypeError as the partition keys have dtype 'category'.

**Comment by wesm** [comment]
@yingw787 can you open a JIRA issue, please? The software should not segfault

**Comment by yingw787** [comment]
@wesm will do. Closing bug on GitHub mirror.

**Comment by yingw787** [comment]
Issue referenced in ARROW-3208.
