### ISSUE TITLE
[JAVA] Supporting zero copy arrow-vector

### ISSUE THREAD

**Issue by zzhao0** [apache/arrow#2516]
Hello Team,

While arrow-format/flatbuffers does support zero copy, current arrow-vector java implementation is not. I was trying to hack zero copy for readonly scenarios, but saw two main blockers:

1. ArrowBuf is the only buffer implementation used exclusively across ArrowReader/ArrowRecordBatch/Vectors. It's final, which means there isn't a way for me to override its logic in order to wrap some existing buffer. It's absolutely necessary to use ArrowBuf for write scenarios, but for read, if I already have data in ByteBuffer or netty ByteBuf, I hope to avoid the copy that creates ArrowBuf out of them (I was pretty much referring to deserialization logic inside MessageSerializer).

2. As a result of #1 described above, the only layer which seems reusable is the arrow-format. Then I have to implement effectively a readonly copy of arrow-vector that references existing buffer. Put aside the effort doing that, it introduces a big gap to keep up with future changes/fixes made to arrow-vector.

Wondering if you guys have put any thoughts into such readonly scenarios. Any suggestion how I can approach this myself?

Thanks.

**Comment by icexelloss** [comment]
Hi,

Arrow java memory is always offheap memory that is allocated and managed by Arrow's memory allocator. In order to support any ByteBuffer or netty ByteBuf, it would change Arrow java's memory model. 

I would also suggest you to send this to dev@arrow as that's the official channel to discuss such issues,

**Comment by wesm** [comment]
Yes can you please repost on the dev mailing list so we can discuss there?

**Comment by zzhao0** [comment]
Thanks, just posted

**Comment by wesm** [comment]
I don't see the post?

**Comment by zzhao0** [comment]
posted to: dev@arrow.apache.org. Is that the right email?

**Comment by zzhao0** [comment]
Just subscribed and reposted. Did you see it now?

**Comment by wesm** [comment]
Yes, thank you
