### ISSUE TITLE
get_library_dirs on Windows gives the wrong directory

### ISSUE THREAD

**Issue by vmuriart** [apache/arrow#2517]
Python Version: Anaconda 3.6
PyArrow Version: 0.9.0 and 0.10.0
Installed by: conda

The function `pa.get_library_dirs()` points to the wrong directory

```python
import pyarrow as pa
print(pa.get_library_dirs())
```

returns: (the extra spaces are due to the bolding)

`['C:\\Anaconda\\lib\\site-packages\\pyarrow', 'C:\\Anaconda\\`**`lib`**`\\Library\\lib']` 

but it should be:

    ['C:\\Anaconda\\lib\\site-packages\\pyarrow', 'C:\\Anaconda\\Library\\lib']

Not sure if this is dependent on how `pyarrow` was installed on the system.

**Comment by vmuriart** [comment]
@wesm to answer your question on the [`TODO`](https://github.com/apache/arrow/blob/e0c07f4dfe4305aadfd7288403f6f3c6272a8369/python/pyarrow/__init__.py#L222-L223). I don't use `conda` to build my local Cpp extensions, so that section of code is useful for the cases in which the user uses `setuptools` directly to build.

**Comment by wesm** [comment]
Can you please open a JIRA issue

**Comment by vmuriart** [comment]
Just opened. https://issues.apache.org/jira/browse/ARROW-3183

On a side note, Should I just open issue directly on Jira? I usually post here before Jira in case its my own user-error.

**Comment by wesm** [comment]
Well, in this case the bug report was fairly clear, or at least more than 50%. If you aren't sure either here or the mailing list is OK

**Comment by vmuriart** [comment]
Should I go ahead and open a pull-request with the changes needed?

**Comment by wesm** [comment]
Be our guest
