### ISSUE TITLE
[CI] optimization debian package manager tweaks

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25179]
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog] at https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends

**Reporter**: [Pratik Raj](https://issues.apache.org/jira/browse/ARROW-9064) / @Rajpratik71
#### PRs and other links:
- [GitHub Pull Request #7374](https://github.com/apache/arrow/pull/7374)

<sub>**Note**: *This issue was originally created as [ARROW-9064](https://issues.apache.org/jira/browse/ARROW-9064). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We generally apply this suggestion quite comprehensively in our suite of CI configurations and Docker images, closing.
