### ISSUE TITLE
pip3.7 install pyarrow fails on ubuntu14.04

### ISSUE THREAD

**Issue by giapoce** [apache/arrow#2521]
## GitHub Issues for Apache Arrow

We support GitHub issues as a lightweight way to ask questions and engage with
the Arrow developer community. We use the Apache Software Foundation's JIRA
instance for maintaining a queue of development work and as the public record
for work on the project. So, feel free to delete this text and open an issue
here if you have a question or aren't sure whether something is a bug or
feature request. Any bugs, suggestions, or feature requests will eventually
need to end up in JIRA, either before or after completing a pull request.

See the Arrow JIRA project here: https://issues.apache.org/jira/browse/ARROW.

For more in-depth development discussions, please use the public mailing list
dev@arrow.apache.org (first subscribe by sending an e-mail to
dev-subscribe@arrow.apache.org).

**Comment by giapoce** [comment]
Attempt to install pyarrow library for python 3.7 fails on ubuntu 14.04 with error:

pip3.7 install pyarrow 


.........
[ 66%] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
    /tmp/pip-install-yxfa9q27/pyarrow/build/temp.linux-x86_64-3.7/lib.cpp:593:35: fatal error: arrow/python/platform.h: No such file or directory
     #include "arrow/python/platform.h"
                                       ^
    compilation terminated.
    make[2]: *** [CMakeFiles/lib.dir/lib.cpp.o] Error 1
    make[1]: *** [CMakeFiles/lib.dir/all] Error 2
    make: *** [all] Error 2
    error: command 'cmake' failed with exit status 2
    
    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-yxfa9q27/pyarrow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-n998s9f9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-yxfa9q27/pyarrow/

**Comment by wesm** [comment]
Did you install the C++ libraries first? We hope to make wheels for 3.7 available in the next release
