### ISSUE TITLE
Make Install: not declared in this scope

### ISSUE THREAD

**Issue by albertoRamon** [apache/arrow#2529]
Error: When execute _make install_

- Timezone.cc:748:7: error: 'uint' was not declared in this scope
- Timezone.cc:749:11: error: 'nameStart' was not declared in this scope
- Timezone.cc:756:59: error: 'nameStart' was not declared in this scope

**To Reproduce it:**
`
docker pull python:2.7.15-alpine3.8
docker run -it python:2.7.15-alpine3.8 /bin/sh
apk add  wget git
apk add  gcc musl-dev cmake make boost-dev g++
apk add  unixodbc-dev pybind11
apk add  mysql-client postgresql-client
pip install numpy cython
#pip install pandas  #Optional

git clone https://github.com/apache/arrow.git
cd arrow/cpp
mkdir build
cd build
cmake .. -DARROW_PYTHON=on -DARROW_ORC=on-DCMAKE_BUILD_TYPE=Release
make install  #ERROR
export ARROW_HOME=$PWD
make unittest

pip install pyarrow turbodbc
export LC_ALL="en_US.UTF-8"
`

**Comment by wesm** [comment]
Can you please open a JIRA issue? Thank you

**Comment by albertoRamon** [comment]
[ARROW-3202](https://issues.apache.org/jira/browse/ARROW-3202)

**Comment by wesm** [comment]
Thanks
