### ISSUE TITLE
Parquet-CCP on Debian Stretch

### ISSUE THREAD

**Issue by albertoRamon** [apache/arrow#2533]
There is a error on Debian Stretch when execute _make install_ :
- schema.cc:32:14: error: 'arrow::TypePtr' has not been declared
- schema.cc:32:14: error: 'arrow::TypePtr' has not been declared

You can test it easily change the first line from dockerfile [DockerfileRV.zip](https://github.com/apache/arrow/files/2364749/DockerfileRV.zip):

```
docker build -f DockerfileRV  -t arrow_rw2 .
docker run -it arrow_rw2 bash
```
NOTE: [credits of main idea](https://hub.docker.com/r/rvernica/apache-arrow/)

**Comment by wesm** [comment]
Please, JIRA

**Comment by wesm** [comment]
I think this isn't a bug because the parquet-cpp repo is deprecated. See ARROW-3075
