### ISSUE TITLE
[Python][C++] Date64 converted to Date32 on parquet

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25570]
Executing the example below, 

```python

import datetime
import pyarrow as pa
import pyarrow.parquet

data = [
    datetime.datetime(2000, 1, 1, 12, 34, 56, 123456), 
    datetime.datetime(2000, 1, 1)
]

data32 = pa.array(data, type='date32')
data64 = pa.array(data, type='date64')
table = pyarrow.Table.from_arrays([data32, data64], names=['a', 'b'])

pyarrow.parquet.write_table(table, 'a.parquet')

print(table)
print()
print(pyarrow.parquet.read_table('a.parquet'))
```

yields

```java

pyarrow.Table
a: date32[day]
b: date64[ms]

pyarrow.Table
a: date32[day]
b: date32[day]   <------- IMO it should be date64[ms]
```

indicating that pyarrow converted its date64[ms] schema to date32[day]. I used the rust crate to print parquet's metadata, and the value is indeed stored as i32, which suggests that this likely happens on the writer, not reader.

IMO this does not have any practical implication because they are both dates and a 32 bit date (in days) can hold more dates than a 64 bit date in milliseconds, but still constitutes an error as the roundtrip serialization does not yield the same schema.

A broader question I have is why data64 exists in the first place? I can't see any reason to store a **date** in milliseconds since EPOCH.

**Reporter**: [Jorge Leitão](https://issues.apache.org/jira/browse/ARROW-9502) / @jorgecarleitao

<sub>**Note**: *This issue was originally created as [ARROW-9502](https://issues.apache.org/jira/browse/ARROW-9502). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by mapleFU** [comment]
When go through the code, I found this problem:

```c++
    case ArrowTypeId::DATE32:
      type = ParquetType::INT32;
      logical_type = LogicalType::Date();
      break;
    case ArrowTypeId::DATE64:
      type = ParquetType::INT32;
      logical_type = LogicalType::Date();
      break;
```

in `parquet/arrow/schema.cc`. Is this by design? If it's by design, should we mark it in the doc?

@westonpace

**Comment by mapleFU** [comment]
oh, it's in the doc: https://arrow.apache.org/docs/cpp/parquet.html
@rok should we close this because it's already documented?

**Comment by rok** [comment]
@mapleFU since #13847 was closed and this is documented I'd say it's safe to.
