### ISSUE TITLE
[CI] Use https, verify signatures when communicating with msys2.org

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25637]
Follow up for: https://github.com/apache/arrow/pull/7840

Not sure it's necessary, but we could be using `https://repo.msys2.org` instead of `http://repo.msys2.org` and/or verifying the signature for the keyring pkg

**Reporter**: [Ben Kietzman](https://issues.apache.org/jira/browse/ARROW-9571) / @bkietz

<sub>**Note**: *This issue was originally created as [ARROW-9571](https://issues.apache.org/jira/browse/ARROW-9571). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@kou Do you think this deserves keeping open?

**Comment by kou** [comment]
We can close this because the code isn't used now:

https://github.com/apache/arrow/blob/d7bc3788ea2773399b7ef489438c725999bfa83d/ci/scripts/r_windows_build.sh#L28
