### ISSUE TITLE
[CI][C++][Java] Gandiva tests cause java-jars nightly to fail

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#25633]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/ursacomputing/crossbow/actions/runs/3881589871/jobs/6620764549#step:6:2862
```
The following tests FAILED:
	 30 - arrow-compute-scalar-test (Failed)
	 64 - gandiva-internals-test (Failed)
	 66 - gandiva-filter-test (Failed)
	 67 - gandiva-projector-test (Failed)
	 68 - gandiva-projector-build-validation-test (Failed)
	 69 - gandiva-if-expr-test (Failed)
	 70 - gandiva-literal-test (Failed)
	 71 - gandiva-boolean-expr-test (Failed)
	 72 - gandiva-binary-test (Failed)
	 73 - gandiva-date-time-test (Failed)
	 74 - gandiva-to-string-test (Failed)
	 75 - gandiva-utf8-test (Failed)
	 76 - gandiva-hash-test (Failed)
	 77 - gandiva-in-expr-test (Failed)
	 78 - gandiva-null-validity-test (Failed)
	 79 - gandiva-decimal-test (Failed)
	 80 - gandiva-decimal-single-test (Failed)
	 81 - gandiva-filter-project-test (Failed)
	 82 - gandiva-projector-test-static (Failed)
```

### Component(s)

C++ - Gandiva, Continuous Integration, Java

**Comment by assignUser** [comment]
I added the blocker label as this prevents production of the java jars

**Comment by felipecrv** [comment]
The log shows lots of linker errors that only happen in the macOS ARM build. I have an M1 Mac and could look at this tomorrow. It's late here and I haven't set up the Arrow build in the Mac yet.

**Comment by js8544** [comment]
The problem seems to be with the RE2 library. All tests cases that segfaulted uses the RE2 library to do regex matching, namely:
arrow-compute-scalar-test: TestBaseBinaryKernels/0.FindSubstringIgnoreCase
gandiva-internals-test: TestLikeHolder.TestMatchAny
gandiva-filter-test: TestFilter.TestLike
gandiva-utf8-test: TestUtf8.TestLike
gandiva-projector-test: TestProjector.TestRegexpExtract
gandiva-projector-test-static: TestProjector.TestRegexpExtract

**Comment by js8544** [comment]
This failure seemed to have begun from 2022-12-27: https://github.com/ursacomputing/crossbow/actions/runs/3786202064/jobs/6437491716

**Comment by felipecrv** [comment]
Unfortunately I'm unable to reproduce the issue on my M1 Mac. The gandiva tests run successfully on my machine.

**Comment by kou** [comment]
@assignUser Can we ssh to the self-hosted runner for https://github.com/ursacomputing/crossbow/actions/runs/3786202064/jobs/6436882897 to debug this?

**Comment by raulcd** [comment]
this is the last success build (26th of December) prior to the initial failure: https://github.com/ursacomputing/crossbow/actions/runs/3780146447/jobs/6425989756
In case any difference on the logs can help
