### ISSUE TITLE
[Python] Struct types are unhandled in AppendNdarrayItem when converting from a Python sequence to Arrow array in python_to_arrow.cc

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25672]
See https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/python_to_arrow.cc#L759

and mailing list discussion

https://lists.apache.org/thread.html/r0a42d315df94997b7a01488d8309a0ad8f3b63997b8b29fdfb23932e%40%3Cuser.arrow.apache.org%3E

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-9610) / @wesm

<sub>**Note**: *This issue was originally created as [ARROW-9610](https://issues.apache.org/jira/browse/ARROW-9610). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
We don't have an exact reproducer, but so this is something that failed in the past with a similar error (the list item is a numpy array instead of a list):

```
In [1]: pa.array([np.array([{'a': 1, 'b': 2}, {'a': 3, 'b': 4}], dtype=object)])
...
ArrowTypeError: Unknown list item type: struct<a: int64, b: int64>
```

And that now works:

```
In [1]: pa.array([np.array([{'a': 1, 'b': 2}, {'a': 3, 'b': 4}], dtype=object)])
Out[1]: 
<pyarrow.lib.ListArray object at 0x7fa6eccc3700>
[
  -- is_valid: all not null
  -- child 0 type: int64
    [
      1,
      3
    ]
  -- child 1 type: int64
    [
      2,
      4
    ]
]
In [2]: _.type
Out[2]: ListType(list<item: struct<a: int64, b: int64>>)
```

So closing this.
