### ISSUE TITLE
[Python] Performance difference between pc.multiply vs pd.multiply

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25684]
Wanted to report the performance difference observed between Pandas and Pyarrow.

 
```java

 import numpy as np
 import pandas as pd
 import pyarrow as pa
 import pyarrow.compute as pc
df = pd.DataFrame(np.random.randn(100000000))
 %timeit -n 5 -r 5 df.multiply(df)
table = pa.Table.from_pandas(df)
 %timeit -n 5 -r 5 pc.multiply(table[0],table[0])
```
Results:
```java

%timeit -n 5 -r 5 df.multiply(df)
 374 ms ± 15.9 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)``
```
 
```java

%timeit -n 5 -r 5 pc.multiply(table[0],table[0])
 698 ms ± 297 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)
```

**Environment**: Windows
Pyarrow 1.0.0
**Reporter**: [H G](https://issues.apache.org/jira/browse/ARROW-9623)

<sub>**Note**: *This issue was originally created as [ARROW-9623](https://issues.apache.org/jira/browse/ARROW-9623). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
With recent versions of both numpy and pyarrow (installed with conda-forge), I personally observe that pyarrow is faster than numpy on my laptop:

```
In [2]: %timeit -n 5 -r 5 df.multiply(df)
429 ms ± 21.1 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)

In [3]: %timeit -n 5 -r 5 pc.multiply(table[0],table[0])
273 ms ± 7.45 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)

In [4]: np.__version__
Out[4]: '1.24.3'

In [5]: pa.__version__
Out[5]: '12.0.0'
```

Anyway, given that there is nothing clearly actionable (apart from general performance improvements, which are welcome for all compute kernels), going to close this issue.
