### ISSUE TITLE
[C++][Parquet] Enable external material and rotation for encryption keys

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#25986]
Encryption key material keeps the information required to recover the keys by Parquet readers. Currently, only "internal storage mode" is supported, where the key material is stored inside Parquet file footers, and therefore can't be rotated (re-wrapped with refreshed master keys) in immutable files. The new mechanism in this Jira adds the advanced "external storage mode" for the key material, where the key material is stored in separate small files, that enable the key rotation. This mechanism will also implement the key rotation functionality.

**Reporter**: [Gidon Gershinsky](https://issues.apache.org/jira/browse/ARROW-9960) / @ggershinsky
#### Related issues:
- [[C++][Dataset][Parquet] Support parquet modular encryption in the new Dataset API](https://github.com/apache/arrow/issues/29238) (Dependency)
- [[C++][Parquet] Encryption key management tools](https://github.com/apache/arrow/issues/25405) (depends upon)
- [[Python][Parquet] Enable usage of external key material and rotation for encryption keys in PyArrow](https://github.com/apache/arrow/issues/31869) (is depended upon by)
#### PRs and other links:
- [GitHub Pull Request #10491](https://github.com/apache/arrow/pull/10491)
- [GitHub Pull Request #8286](https://github.com/apache/arrow/pull/8286)
- [Overall design of key management tools](https://docs.google.com/document/d/1bEu903840yb95k9q2X-BlsYKuXoygE4VnMDl9xz_zhk/edit?usp=sharing)

<sub>**Note**: *This issue was originally created as [ARROW-9960](https://issues.apache.org/jira/browse/ARROW-9960). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by wjones127** [comment]
@adamreeve is working on this.

**Comment by wjones127** [comment]
@adamreeve could you comment "take" on this issue? Once you do, this issue should be assigned to you and I can merge the PR. (Also I'm looking into improving this process.)

**Comment by adamreeve** [comment]
take
