### ISSUE TITLE
Ubuntu's libarrow-python-dev is still version 9 and cannot be installed

### ISSUE THREAD

**Issue by Sleemanmunk** [apache/arrow#25990]
### Describe the bug, including details regarding any error messages, version, and platform.

Ubuntu version 22.04 (jammy) cannot install libarrow python dev

# apt install libarrow-python-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libarrow-python-dev : Depends: libarrow-dev (= 9.0.0-1) but 10.0.1-1 is to be installed
E: Unable to correct problems, you have held broken packages.

# apt show libarrow-python-dev
Package: libarrow-python-dev
Version: 9.0.0-1
Priority: optional
Section: libdevel
Source: apache-arrow
Maintainer: Apache Arrow Developers <dev@arrow.apache.org>
Installed-Size: 3773 kB
Depends: libarrow-dev (= 9.0.0-1), libarrow-python900 (= 9.0.0-1)
Homepage: https://arrow.apache.org/
Download-Size: 454 kB
APT-Sources: https://apache.jfrog.io/artifactory/arrow/ubuntu jammy/main amd64 Packages
Description: Apache Arrow is a data processing library for analysis
 .
 This package provides C++ header files for Python support.

### Component(s)

Python

**Comment by kou** [comment]
libarrow-pythnon-dev wasn't provided since Apache Arrow 10.0.0.
Because Python related modules were moved to Apache Arrow Python (PyArrow) from Apache Arrow C++.
Could you use pyarrow instead of libarrow-python-dev?
See also: https://arrow.apache.org/docs/python/integration/extending.html

**Comment by kou** [comment]
You need to install PyArrow via `pip` or conda not `apt`:
* https://pypi.org/project/pyarrow/
* https://anaconda.org/conda-forge/pyarrow

**Comment by Sleemanmunk** [comment]
Are you saying that you don't plan to support ubuntu apt anymore?
