### ISSUE TITLE
pyarrow column cast not working

### ISSUE THREAD

**Issue by kavitajsheth** [apache/arrow#2627]
I want to cast pyarrow table column from decimal(38,4) to int64.

col.cast(pa.int64())

Error:
  File "pyarrow/table.pxi", line 443, in pyarrow.lib.Column.cast
  File "pyarrow/error.pxi", line 89, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: No cast implemented from decimal(38, 4) to int64

Python version : 3.6.5
Pyarrow version : 0.10.0

is it not implemented yet or I am not using it correctly? If not implemented yet, then any work around to cast columns?

**Comment by wesm** [comment]
Can you open a JIRA issue with this information, please?

**Comment by kavitajsheth** [comment]
Thanks for the reply, I opened Jira issue, https://issues.apache.org/jira/projects/ARROW/issues/ARROW-3329

**Comment by wesm** [comment]
Thanks
