### ISSUE TITLE
Merge tables

### ISSUE THREAD

**Issue by hugo-pires** [apache/arrow#2631]
Hello

Is it possible to MERGE Arrow (I am using PyArrow) tables, just like we do on Pandas?

Thank you

**Comment by TomScheffers** [comment]
Hi @hugo-pires, while we are waiting for the pyarrow package to mature, I made my own [package](https://github.com/TomScheffers/pyarrow_ops) to perform pandas like operations on the pyarrow.Table directly. Currently it supports (inner) join, groupby (iterables and aggregations), filters (using multiple predicates), drop_duplicates and head (for printing). Although it is not yet as extensive yet as pandas, performance actually very similar. Feel free to contact me if you need anything!

**Comment by hugo-pires** [comment]
Thank you
