### ISSUE TITLE
[CI][Gandiva] Travis osx nightly build is failing due to homebrew llvm upgrade

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26338]
**Reporter**: [Projjal Chanda](https://issues.apache.org/jira/browse/ARROW-10352) / @projjal

<sub>**Note**: *This issue was originally created as [ARROW-10352](https://issues.apache.org/jira/browse/ARROW-10352). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We have no Travis-CI builds anymore, closing as outdated.
