### ISSUE TITLE
[Python] Use of target_include_directories on imported targets requires cmake >= 3.11

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#26394]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/ursacomputing/crossbow/actions/runs/3829615557/jobs/6516509884#step:5:12900

Introduced by #15143

### Component(s)

Python

**Comment by assignUser** [comment]
@kou I would be in favour of bumping the required cmake version vs adding in a (likely ugly) workaround as 3.11 should be no problem for manylinux

**Comment by kou** [comment]
Sorry. I didn't notice it.
We can bump required CMake version to 3.16 since Apache Arrow 12.0.0 or 13.0.0 because Ubuntu 18.04 will reach EOL on 2023-04.
I'll add a workaround for 3.11 for now.

**Comment by assignUser** [comment]
Great, I am very much looking forward to 3.16, will allow us to use `FetchContent` and other goodies :D
