### ISSUE TITLE
[JS] npm packages depends on outdated flatbuffers-esm

### ISSUE THREAD

**Issue by tarekrached** [apache/arrow#2640]
Not sure what the root cause is here, or if this is even a real issue, but I figured I'd flag it...

It looks like the `apache-arrow` npm package (and the @apache-arrow/* packages) are pointing at an out of date fork of flatbuffers from @trxcllnt, which can be seen with:
```
npm view apache-arrow@0.3.1 dependencies.flatbuffers
```
which shows `github:trxcllnt/flatbuffers-esm` instead of `1.9.0`, which is what [js/package.json](https://github.com/apache/arrow/blob/master/js/package.json#L61) leads me to believe it should be.

The description of the [trxcllnt/flatbuffers-esm](https://github.com/trxcllnt/flatbuffers-esm) repo says:
> temporary repo to use in Arrow until https://github.com/google/flatbuffers/pull/4504 is merged

That PR was merged on Dec 1, 2017, so I think we're good to point back at mainline [flatbuffers](https://www.npmjs.com/package/flatbuffers).

Since the `package.json` in this repo doesn't match that on npm, I'm guessing this is a packaging / deployment issue.  Let me know if there's anything I can do to help resolve this.

**Comment by trxcllnt** [comment]
Yep, we've updated the dependency master and it will go out in the next release.

**Comment by tarekrached** [comment]
👍 fantastic - thanks for the update.
