### ISSUE TITLE
[CI] Continuous integration on Apple M1 architecture

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26612]
It would be nice if we had some confidence that our next major release runs on Apple Silicon. I am looking at hooking up an M1 Mac Mini to Buildkite so that we are able to run CI jobs on one. If anyone else would like to contribute a machine to the build cluster, please be our guest

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-10657) / @wesm
#### Subtasks:
- [x] [[CI][C++] Implement CI on Apple M1 for C++](https://github.com/apache/arrow/issues/31591)
- [X] [[CI][R] Implement CI on Apple M1 for R](https://github.com/apache/arrow/issues/31592)
#### Related issues:
- [[Python][Packaging] Wheel builds for Apple Silicon](https://github.com/apache/arrow/issues/26613) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-10657](https://issues.apache.org/jira/browse/ARROW-10657). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
Should we close this and maybe add a specific task to add M1 runners for PRs? @assignUser

**Comment by assignUser** [comment]
Yes, I think we can close #31591 too as we run the source verification on m1 and that builds C++ and the wheels build C++ and the r packages build C++ on m1...

I don't see self-hosted M1 as feasible for PRs as we can not make them ephemeral as of yet.
