### ISSUE TITLE
[Python] pip install --user fails to install lib

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26803]
Compiling and installing C++ library via:

```Java

cd ~/src/pyarrow/cpp
mkdir build
cd build
CC=clang-11 CXX=clang++-11 cmake -GNinja -DARROW_PYTHON=ON ..
ninja
sudo ninja install
```

Then installing python package as follows will claim to succeed, but actually fail to provide `pyarrow.lib` (`python3 -c 'import pyarrow.lib'` will fail)

```Java

cd ~/src/pyarrow/python
pip install --user .
```

**Reporter**: [Leonard Lausen](https://issues.apache.org/jira/browse/ARROW-10868) / @leezu

<sub>**Note**: *This issue was originally created as [ARROW-10868](https://issues.apache.org/jira/browse/ARROW-10868). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Given this is an older issue, and there was no further response, going to close this.
