### ISSUE TITLE
[C#][FlightRPC] incompatible with java client for empty record batches

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#26866]
An error has been found when one sends an empty record batch from C# server and tries to read it with the java client.

From investigation the java client requires the protobuf tags to be sent in the message even though it is empty. Java code can be seen here:

<https://github.com/apache/arrow/blob/master/java/flight/flight-core/src/main/java/org/apache/arrow/flight/ArrowMessage.java>

Line 257-301 (the error is that it wont accept a null body for a record batch)

Normal functionality of gRPC is to exclude the entire tag if an object is empty, example code from generated csharp:

if (DataBody.Length != 0)

{ output.WriteRawTag(194, 62); output.WriteBytes(DataBody); }

To fix this so the csharp version is compatible with the java client requires a non empty flight data body must be sent or at least the tag of the body.

**Reporter**: [Alexander](https://issues.apache.org/jira/browse/ARROW-10939) / @Ulimo
#### Related issues:
- [[C++][FlightRPC] Missing protobuf data_body should result in default value of empty bytes, not null](https://github.com/apache/arrow/issues/26883) (is related to)
- [[Java][FlightRPC] FlightData deserializer should accept missing fields](https://github.com/apache/arrow/issues/26885) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-10939](https://issues.apache.org/jira/browse/ARROW-10939). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by CurtHagenlocher** [comment]
Closing this issue as the problem seems to have been identified as being on the Java (and C++) sides.
