### ISSUE TITLE
[CI] apache-rat-plugin is not thread-safe warnings

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#27058]
We're getting these warnings in some nightly builds. I don't have the expertise: are they likely to be causing problems now? (or later?)
 
 

| |
|
|-|-|
|[WARNING] \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* 
<br>[WARNING] \* Your build is requesting parallel execution, but project \* 
<br>[WARNING] \* contains the following plugin(s) that have goals not marked \* 
<br>[WARNING] \* as @threadSafe to support parallel building. \* 
<br>[WARNING] \* While this /may/ work fine, please look for plugin updates \* 
<br>[WARNING] \* and/or request plugins be made thread-safe. \* 
<br>[WARNING] \* If reporting an issue, report it against the plugin in \* 
<br>[WARNING] \* question, not against maven-core \* 
<br>[WARNING] \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* 
<br>[WARNING] The following plugins are not marked @threadSafe in Arrow Flight GRPC: 
<br>[WARNING] org.apache.rat:apache-rat-plugin:0.13 
<br>[WARNING] org.apache.maven.plugins:maven-site-plugin:3.5.1 
<br>[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe. 
<br>[WARNING] \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*|
<br> |

**Reporter**: [Andrew Wieteska](https://issues.apache.org/jira/browse/ARROW-11148) / @arw2019
#### Original Issue Attachments:
- [6_Execute Docker Build.txt](https://issues.apache.org/jira/secure/attachment/13018252/6_Execute+Docker+Build.txt)

<sub>**Note**: *This issue was originally created as [ARROW-11148](https://issues.apache.org/jira/browse/ARROW-11148). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as stale.
