### ISSUE TITLE
[Feature Request] Table.nbytes attribute

### ISSUE THREAD

**Issue by dhirschfeld** [apache/arrow#2707]
As it says in the title, I think this would be a very handy attribute to have. You can get it by converting to pandas and using `DataFrame.nbytes` but this is wasteful of both time and memory so it would be good to have this information on the `pyarrow.Table` object itself.

Happy to move this to a JIRA if there's agreement this is a useful/desirable feature.

**Comment by dhirschfeld** [comment]
Suggest implementing via the [`__sizeof__`](https://docs.python.org/3/library/sys.html#sys.getsizeof) protocol.

**Comment by wesm** [comment]
Can you open a JIRA? We discuss feature requests there.

**Comment by dhirschfeld** [comment]
Discussion moved to https://issues.apache.org/jira/browse/ARROW-3444
