### ISSUE TITLE
Plasma packages for arm64

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#27273]
"Note that Plasma packages are available only for amd64. Because nvidia-cuda-toolkit package isn't available for arm64." https://issues.apache.org/jira/browse/ARROW-6715

Nvidia supports Cuda on ARM, so this should be possible in principle?

Please also clarify the relation with https://github.com/alibaba/libvineyard Do you intend to continue develop Plasma?

**Reporter**: [Leonard Lausen](https://issues.apache.org/jira/browse/ARROW-11380) / @leezu

<sub>**Note**: *This issue was originally created as [ARROW-11380](https://issues.apache.org/jira/browse/ARROW-11380). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
