### ISSUE TITLE
[Java] NullVector field name can't be set

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#27275]
Currently, the Java NullVector has a default Field name fixed to DATA_VECTOR_NAME, which is "$data$". This should be able to be changed by the user, probably by having an alternate constructor that accepts a name.

**Reporter**: [Bryan Cutler](https://issues.apache.org/jira/browse/ARROW-11382) / @BryanCutler

<sub>**Note**: *This issue was originally created as [ARROW-11382](https://issues.apache.org/jira/browse/ARROW-11382). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by danepitkin** [comment]
This is now already implemented, and subsequently verified in https://github.com/apache/arrow/pull/38973.
