### ISSUE TITLE
Spec array size int32 or int64?

### ISSUE THREAD

**Issue by wolfv** [apache/arrow#2733]
The spec mentions clearly that the array size and null count are signed int32_t (https://github.com/apache/arrow/blob/master/format/Layout.md#array-lengths)

However, it appears to have changed to int64_t in C++ implementation ( https://github.com/apache/arrow/blob/master/cpp/src/arrow/array.h#L171 )

So I was wondering wether the spec needs an update or if C++ just internally uses int64_t?

**Comment by wesm** [comment]
Hi -- best to discuss on JIRA. Yes, we permit 64-bit lengths. An implementation is valid if it does not, though. For best compatibility between languages, we recommend limiting lengths to 32 bits.

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-3473
