### ISSUE TITLE
Pyarrow -> pandas -> pyarrow null column Question

### ISSUE THREAD

**Issue by kavitajsheth** [apache/arrow#2782]
I am reading parquet files using pyarrow where one of String type column has all null values when I convert it into pandas and back to pyarrow table column type changed to an integer. I read output using Spark. I also supplied schema when converting pandas to table.

Question: How to write a column with type string and all null values? I want to keep datatype as a string and null values.

Thank you !!

**Comment by kavitajsheth** [comment]
Hi Wes, Thank you. Sorry for late reply. while creating a reproducible example, I realized that I am using  
 write_to_dataset and that method divide that table into subtable and writes it. when I passed schema there, its working fine. API documentation doesn't have this method. I will close this issue now. Thanks again for help.

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-3629 about adding this to the API listing

**Comment by kavitajsheth** [comment]
Thank you.

**Comment by anttttti** [comment]
This issue can still occur with subtables. If one subtable gets converted to "null", and another table of the same column gets a valid type, then appending to the same parquet file with ParquetWriter will throw:
"ValueError: Table schema does not match schema used to create file: " , with file/table mismatch with one showing null, the other showing a valid column type
