### ISSUE TITLE
[CI][C++] Add nightly job to test offline build

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#27919]
See discussion on https://github.com/apache/arrow/pull/9803

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-12095) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-12095](https://issues.apache.org/jira/browse/ARROW-12095). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Issue resolved by pull request 44721
https://github.com/apache/arrow/pull/44721
