### ISSUE TITLE
[Java][JNI][CI] Flaky builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28037]
The Java build seems to fail randomly in those CI builds.

See e.g. https://github.com/apache/arrow/runs/2271358495?check_suite_focus=true

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-12221) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-12221](https://issues.apache.org/jira/browse/ARROW-12221). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as stale.
