### ISSUE TITLE
Table schema does not match schema used to create file:

### ISSUE THREAD

**Issue by danielhaviv** [apache/arrow#2805]
I'm trying to write a large parquet file row group by group and avoid running out of memory.
When I'm writing closing the ParquetWriter I receive the following exception "Table schema does not match schema used to create file:".

My code:
`pq.read_metadata(f).schema.to_arrow_schema()
writer = pq.ParquetWriter('/tmp/example2.parquet', schema)
for i in range(parquet_file.num_row_groups):
                    print("Row group " + str(i))
                    df = parquet_file.read_row_group(i).to_pandas()
                    for column in attributes:
                        df = df[~df[column].isin(attributes[column])]
                        deleted_users += ','.join(attributes[column])
                    writer.write_table(pa.Table.from_pandas(df, preserve_index=False))
                writer.close()`

table metadata:
{
	pandas: {
		"index_columns": [],
		"column_indexes": [],
		"columns": [{
			"name": "archived",
			"field_name": "archived",
			"pandas_type": "bool",
			"numpy_type": "bool",
			"metadata": null
		}, {
			"name": "author",
			"field_name": "author",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "author_flair_css_class",
			"field_name": "author_flair_css_class",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "author_flair_text",
			"field_name": "author_flair_text",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "body",
			"field_name": "body",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "controversiality",
			"field_name": "controversiality",
			"pandas_type": "int64",
			"numpy_type": "int64",
			"metadata": null
		}, {
			"name": "created_utc",
			"field_name": "created_utc",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "distinguished",
			"field_name": "distinguished",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "downs",
			"field_name": "downs",
			"pandas_type": "int64",
			"numpy_type": "int64",
			"metadata": null
		}, {
			"name": "edited",
			"field_name": "edited",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "gilded",
			"field_name": "gilded",
			"pandas_type": "int64",
			"numpy_type": "int64",
			"metadata": null
		}, {
			"name": "id",
			"field_name": "id",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "link_id",
			"field_name": "link_id",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "name",
			"field_name": "name",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "parent_id",
			"field_name": "parent_id",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "retrieved_on",
			"field_name": "retrieved_on",
			"pandas_type": "int64",
			"numpy_type": "int64",
			"metadata": null
		}, {
			"name": "score",
			"field_name": "score",
			"pandas_type": "int64",
			"numpy_type": "int64",
			"metadata": null
		}, {
			"name": "score_hidden",
			"field_name": "score_hidden",
			"pandas_type": "bool",
			"numpy_type": "bool",
			"metadata": null
		}, {
			"name": "subreddit",
			"field_name": "subreddit",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "subreddit_id",
			"field_name": "subreddit_id",
			"pandas_type": "unicode",
			"numpy_type": "object",
			"metadata": null
		}, {
			"name": "ups",
			"field_name": "ups",
			"pandas_type": "int64",
			"numpy_type": "int64",
			"metadata": null
		}],
		"pandas_version": "0.23.4"
	}
	}

File metadata:
{
	"org.apache.spark.sql.parquet.row.metadata": {
		"type": "struct",
		"fields": [{
			"name": "archived",
			"type": "boolean",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "author",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "author_flair_css_class",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "author_flair_text",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "body",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "controversiality",
			"type": "long",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "created_utc",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "distinguished",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "downs",
			"type": "long",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "edited",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "gilded",
			"type": "long",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "id",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "link_id",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "name",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "parent_id",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "retrieved_on",
			"type": "long",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "score",
			"type": "long",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "score_hidden",
			"type": "boolean",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "subreddit",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "subreddit_id",
			"type": "string",
			"nullable": true,
			"metadata": {}
		}, {
			"name": "ups",
			"type": "long",
			"nullable": true,
			"metadata": {}
		}]
	}
}

**Comment by danielhaviv** [comment]
It's worth mentioning that the columns are identical, only the "metadata" part is different (pandas vs spark)

**Comment by danielhaviv** [comment]
Removed metadata from both schemas and it worked:
                schema = parquet_file.read_row_group(0).schema.remove_metadata()
                 tab = pa.Table.from_pandas(df, preserve_index=False).replace_schema_metadata()

**Comment by wesm** [comment]
I think something ought to be documented about this issue in the Sphinx documentation. What do you think?

**Comment by danielhaviv** [comment]
Created [ARROW-3585](https://issues.apache.org/jira/browse/ARROW-3585).
I'll attend to it by the beginning of next week.
