### ISSUE TITLE
Add abstract function for null information

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28145]
**Reporter**: [Fiona La](https://issues.apache.org/jira/browse/ARROW-12346) / @lafiona

<sub>**Note**: *This issue was originally created as [ARROW-12346](https://issues.apache.org/jira/browse/ARROW-12346). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

A public `Valid` property, which represents the null values in an Arrow array, was added to the `arrow.array.Array` classes in #35655.

Example:

```matlab

>> a = arrow.array(uint64([1, 2, 3]), Valid=[true, false, true])

a = 

[
  1,
  null,
  3
]

>> a.Valid

ans =

  3x1 logical array

   1
   0
   1
```
