### ISSUE TITLE
Add abstract function for display

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28143]
**Reporter**: [Fiona La](https://issues.apache.org/jira/browse/ARROW-12344) / @lafiona

<sub>**Note**: *This issue was originally created as [ARROW-12344](https://issues.apache.org/jira/browse/ARROW-12344). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

Each `arrow.*` class (e.g. `arrow.array.Array`) currently has a `toString` method on the underlying `Proxy` object that it wraps, which calls the `ToString` method of the corresponding Arrow C++ object (e.g. `arrow.type.Field` display calls `arrow::Field::ToString`). We use the string returned by the C++ `ToString` implementation for display in MATLAB.

We probably want to make more improvements to the MATLAB display of Arrow types in the future, but we can track those display improvements under new issues that are more specific.
