### ISSUE TITLE
[MATLAB] add support for converting MATLAB numeric arrays to arrow::NumericArrays 

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28148]
Create a C++ function that accepts a MALTAB uint64 array and converts it into a arrow::NumericArray<arrow::UInt64Type>.

**Reporter**: [Sarah Gilmore](https://issues.apache.org/jira/browse/ARROW-12349) / @sgilmore10

<sub>**Note**: *This issue was originally created as [ARROW-12349](https://issues.apache.org/jira/browse/ARROW-12349). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

This was essentially implemented in #35479, which added a templated `NumericArray` `Proxy` subclass for creating Arrow numeric array types from MATLAB numeric arrays.
