### ISSUE TITLE
[MATLAB] create a matlab2mex function

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28166]
Create a function that takes a native numeric MATLAB array and converts it into a form that can be manipulated in a C++ MEX function. Once the data is accessible inside a MEX function, it can be converted into the corresponding  arrow::NumericArray type.

**Reporter**: [Sarah Gilmore](https://issues.apache.org/jira/browse/ARROW-12368) / @sgilmore10

<sub>**Note**: *This issue was originally created as [ARROW-12368](https://issues.apache.org/jira/browse/ARROW-12368). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

This issue doesn't seem relevant anymore.

In the current code, each `Proxy` class that wraps a corresponding Arrow C++ type takes care of marshaling MATLAB types to a form that is usable by the C++ layer via a "`static` `make` method`.

Example: https://github.com/apache/arrow/blob/d330d1b36c87ea43bfd16e1bc43a4ff9876abb4b/matlab/src/cpp/arrow/matlab/tabular/proxy/schema.cc#L58).
