### ISSUE TITLE
[CI] [Python] ERROR: ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28208]
Building unity_0 fails.

This affects Python 3.6 and 3.7, see

- https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=3579&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=1509
- https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=3576&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=1383
  
  This task has failed 33 times across 209 pipeline runs in the last 14 days (https://dev.azure.com/ursacomputing/crossbow/_pipeline/analytics/stageawareoutcome?definitionId=1)

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12417) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12417](https://issues.apache.org/jira/browse/ARROW-12417). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as stale.
