### ISSUE TITLE
[Release] Add crossbow task to verify ARM64 wheels on travis

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28314]
Although we're going to ship ARM64 wheels with release 4.0 we have not verified them using the automatized crossbow tasks. We should cover those binaries as well.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-12553) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-12553](https://issues.apache.org/jira/browse/ARROW-12553). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
ARM64 wheels now use the same GHA workflows as x86 wheels, closing.
