### ISSUE TITLE
solve OS X dependencies in nightly builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28422]
affects azure-conda-osx-clang-py37-r40 and azure-conda-osx-clang-py36-r36

there is a dependencies problem (Unsatisfiable dependencies for platform osx-64: {'arrow-cpp=3.1.0.dev802'})

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12674) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12674](https://issues.apache.org/jira/browse/ARROW-12674). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as stale.
