### ISSUE TITLE
[CI] [Gandiva] Fix Gandiva DEB file for nightly builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28482]
see 
https://uploads.github.com/repos/ursacomputing/crossbow/releases/42751337/assets?name=libgandiva-glib-dev_3.1.0.dev825-1_amd64.deb

it returns
message	"Bad Content-Length: "
request_id	"ECD8:3A77:3A930D:6B1DA1:609AC020"

and therefore github-debian-buster-amd64 fails

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12740) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12740](https://issues.apache.org/jira/browse/ARROW-12740). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as stale.
