### ISSUE TITLE
[MATLAB] Create the LifetimeManager C++ class

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28496]
LifetimeManager is a singleton that each arrow.Array subclass will interact with to keep their corresponding C++ data structures alive.

**Reporter**: [Sarah Gilmore](https://issues.apache.org/jira/browse/ARROW-12754) / @sgilmore10

<sub>**Note**: *This issue was originally created as [ARROW-12754](https://issues.apache.org/jira/browse/ARROW-12754). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

Functionality that is related to what is described in this issue was implemented in `mathworks/libmexclass`, which is now being used under the hood by the MATLAB Interface.
