### ISSUE TITLE
[MATLAB] Create a templated ObjectMap for storing arrow C++ data structures with IDs

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28495]
In order to keep arrow C++ data structures alive for the duration of the wrapping MATLAB object (e.g. arrow.Array), we can store the arrow C++ data structure in a map indexed by a unique ID. 

**Reporter**: [Sarah Gilmore](https://issues.apache.org/jira/browse/ARROW-12753) / @sgilmore10

<sub>**Note**: *This issue was originally created as [ARROW-12753](https://issues.apache.org/jira/browse/ARROW-12753). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

Functionality that is related to what is described in this issue was implemented in `mathworks/libmexclass`, which is now being used under the hood by the MATLAB Interface.
