### ISSUE TITLE
[CI] Fix Arrow DEB file for nightly builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28507]
see
https://uploads.github.com/repos/ursacomputing/crossbow/releases/42659679/assets?name=libarrow-cuda-glib-dev_3.1.0.dev817-1_amd64.deb

it returns
message	"Bad Content-Length: "
request_id	"859A:54C7:F5761:17E15E:609C4214"

and therefore github-ubuntu-groovy-amd64 fails

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12766) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12766](https://issues.apache.org/jira/browse/ARROW-12766). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as stale.
