### ISSUE TITLE
[Plasma][C++][JAVA]Add Metrics API for clients to get share memory usage

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28511]
Implement an API for Plasma clients to get share memory usage

**Reporter**: [KunshangJi](https://issues.apache.org/jira/browse/ARROW-12770) / @jikunshang
#### PRs and other links:
- [GitHub Pull Request #10308](https://github.com/apache/arrow/pull/10308)

<sub>**Note**: *This issue was originally created as [ARROW-12770](https://issues.apache.org/jira/browse/ARROW-12770). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Plasma was removed: #33243
