### ISSUE TITLE
[CI] Fix CMake Error: Unknown argument -isystem

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28522]
this makes github-test-conda-python-3.7-turbodbc-latest and github-test-conda-python-3.7-turbodbc-master to fail

see https://github.com/ursacomputing/crossbow/runs/2573049296#step:7:3865

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12783) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12783](https://issues.apache.org/jira/browse/ARROW-12783). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
This looks outdated, closing
