### ISSUE TITLE
[CI] Scale dev version number for Azure Conda builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28521]
we need to automatically scale the XXX part in arrow-cpp=3.1.0.devXXX available dependency for azure-conda-osx-clang-py36-r36 and azure-conda-osx-clang-py37-r40, or it shall keep failing

see 
- https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=5114&view=logs&j=cf796865-97b7-5cd1-be8e-6e00ce4fd8cf&t=88ee2fb8-46fd-5c68-fde3-1c8d31ba2a5f&l=1156
- https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=5115&view=logs&j=cf796865-97b7-5cd1-be8e-6e00ce4fd8cf&t=88ee2fb8-46fd-5c68-fde3-1c8d31ba2a5f&l=1152

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12782) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12782](https://issues.apache.org/jira/browse/ARROW-12782). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
I'm closing this as obsolete for now.
