### ISSUE TITLE
[CI] Nightly builds can't upload gir1.2-gandiva-1.0_3.1.0.dev841-1_amd64.deb

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28523]
gir1.2-gandiva-1.0_3.1.0.dev841-1_amd64.deb returns a 403 error for github-ubuntu-focal-amd64

**Reporter**: [Mauricio 'Pachá' Vargas Sepúlveda](https://issues.apache.org/jira/browse/ARROW-12784) / @pachadotdev

<sub>**Note**: *This issue was originally created as [ARROW-12784](https://issues.apache.org/jira/browse/ARROW-12784). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as obsolete.
