### ISSUE TITLE
memory consumption question

### ISSUE THREAD

**Issue by kavitajsheth** [apache/arrow#2874]
I am trying to read partitioned dataset(many small-files) of size 1GB from s3 and convert it into pandas.(data size is just an example)

dataset = pyarrow.parquet.ParquetDataset([list-of-files],filesystem =fs).read()
df = dataset.to_pandas()

This takes a very long time and it consumes around 50 GB memory(using top command to check memory used) and sometimes fails with a memory error.

I also tried reading one file at a time and concat pandas dataframe but same memory usage.

is there benchmark for how much data pyarrow can read and convert to pandas? Is there a better way to read it? I also need to do transformations on pandas data frame after reading it.

Please let me know if this is not the right place to ask such questions.

**Comment by xhochy** [comment]
The size of your Parquet files is not the size that they will be later on in memory. As Parquet applies various forms of compression, the resulting pandas DataFrames can be upto 100x larger than the files on disk. In your case, you should read a single file from disk and then have a look at the memory usage of this file using `df.memory_usage(deep=True)`

**Comment by kavitajsheth** [comment]
Thank you for the reply. Are there ways to reduce data frame memory usage or data compression with pandas? is there a parameter in pyarrow read method or to_pandas method that will help with data compression or memory usage?

Thank you.

**Comment by xhochy** [comment]
@kavitajsheth There are several things you can do like using smaller integer types for columns where you don't int64 but an int16 is sufficient. But this can only be applied after the DataFrame was initially loaded.

**Comment by kavitajsheth** [comment]
Thank you, those are great suggestions. I will close this issue now.
