### ISSUE TITLE
[MATLAB] Migrate the MEX gateway function to use the C++ MATLAB Data Array (MDA) API, instead of C Matrix API

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28766]
The current MEX gateway function uses the [C Matrix API\|[https://www.mathworks.com/help/matlab/cc-mx-matrix-library.html?s_tid=CRUX_lftnav]]

We should update to use the latest C++ MATLAB Data Array API, to gain access to modern C++ features and memory management.

**Reporter**: [tahsin hassan](https://issues.apache.org/jira/browse/ARROW-13057) / @tahsinH

<sub>**Note**: *This issue was originally created as [ARROW-13057](https://issues.apache.org/jira/browse/ARROW-13057). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
Marking this as resolved.

The MATLAB Interface now uses [mathworks/libmexclass](https://github.com/mathworks/libmexclass) under the hood which is based on [C++ MEX](https://www.mathworks.com/help/matlab/matlab_external/c-mex-functions.html) and the [MATLAB Data API for C++](https://www.mathworks.com/help/matlab/matlab-data-array.html).

The MEX gateway function is now https://github.com/apache/arrow/blob/main/matlab/src/cpp/arrow/matlab/mex/gateway.cc.
