### ISSUE TITLE
[Plasma][Python] plasma.PlasmaClient do not disconnect when user tried to delete it

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28818]
```
import pyarrow.plasma as plasma
for _ in range(10000):
    c = plasma.connect("/tmp/plasma")
    del c
```
The above code turns out not to call c.disconnect() automatically, and will cause `Connection to IPC socket failed` error.

**Reporter**: [Yuxian Meng](https://issues.apache.org/jira/browse/ARROW-13115)

<sub>**Note**: *This issue was originally created as [ARROW-13115](https://issues.apache.org/jira/browse/ARROW-13115). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
