### ISSUE TITLE
pyarrow.schema example gives error

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow#2884]
The example provided in the docstring for [`pyarrow.schema`](https://arrow.apache.org/docs/python/generated/pyarrow.schema.html#pyarrow.schema) is:
```py
import pyarrow as pa
fields = [
    ('some_int', pa.int32()),
    ('some_string', pa.string()),
]
schema = pa.schema(fields)
```

Maybe this worked previously, but it appears to currently raise an error:
![image](https://user-images.githubusercontent.com/15164633/47800408-98ead500-dd02-11e8-8bbc-e9417980b6d9.png)

**Comment by xhochy** [comment]
@kylebarron Eventhough I don't whether we ever supported this, we should support it as it is a convenient way to construct schemas. Can you open an issue at https://issues.apache.org/jira/projects/ARROW ?

**Comment by kylebarron** [comment]
So sorry! I was in a virtual environment that hadn't upgraded to 0.11 yet.

Small note: it's helpful how Pandas' documentation has notes that say, i.e. "new in version 0.23.0". That might help prevent versioning mistakes like mine.

Thanks for all your work!
