### ISSUE TITLE
Plasma server hangs on Get requests containing duplicate object IDs

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#28852]
If a plasma client issues a Get request containing duplicate object IDs, and a timeout of -1, the server will hang.

The logic at the end of `PlasmaStore::ProcessGetRequest()` only returns a response when the number of satisfied requests match the number of **unique** objects to wait for.  The former is calculated using the number of requested object IDs, not the number of unique requested object IDs.

To reproduce:

 
```java

# start the plasma store first

from pyarrow import plasma
client = plasma.connect("/tmp/plasma")
oid = client.put("hello, world")
print(client.get([oid, oid], -1))print("done.")
```
 

**Environment**: tested on Linux/Python 3.8/pyarrow 4.0.1
**Reporter**: [Bruce Martin](https://issues.apache.org/jira/browse/ARROW-13152)

<sub>**Note**: *This issue was originally created as [ARROW-13152](https://issues.apache.org/jira/browse/ARROW-13152). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
