### ISSUE TITLE
[Documentation] docs/requirements.txt is out-of-sync with what CI builds use

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29028]
docs/requirements.txt pins Sphinx 2.4.4 but the CI pipelines use the latest versions of breathe/sphinx/etc.

**Reporter**: [David Li](https://issues.apache.org/jira/browse/ARROW-13354) / @lidavidm

<sub>**Note**: *This issue was originally created as [ARROW-13354](https://issues.apache.org/jira/browse/ARROW-13354). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by amoeba** [comment]
I think we can close this because this is no longer the case as of https://github.com/apache/arrow/commit/3f7f245e780067614880fd80cc73ec20d31c1c7b and the local developer setup is in sync with the setup in CI.
