### ISSUE TITLE
[Release] Distinguish between closed and in-progress/open jiras without a linked patch in the release curation report

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29084]
`archery release curate 5.0.0` reports a lot of issues as `JIRA issues in version 5.0.0 without a linked patch`

There are in-progress/open ticket which need to be postponed or closed before cutting the release candidate but these are not listed separately from closed issues without a patch.

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-13415) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-13415](https://issues.apache.org/jira/browse/ARROW-13415). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
This is obsolete now that we've migrated to GH issues, closing.
