### ISSUE TITLE
PlasmaStoreFull on empty store

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29090]
I am trying to run plasma on a shared linux-based HPC system.
I start the server with:
```java

plasma_store -m 500000000 -s $PERSONAL_DIR/plasma -d $PERSONAL_DIR/store
```
Then in a separate terminal in python I run:
```java

import os
import pyarrow.plasma as plasma
client = plasma.connect(os.environ["PERSONAL_DIR"] + "/plasma")
object_id = client.put("hello, world")
```
However I get:
```java

PlasmaStoreFull: object does not fit in the plasma store
```
although the plasma store is empty.

**Reporter**: [Max Levine](https://issues.apache.org/jira/browse/ARROW-13423)

<sub>**Note**: *This issue was originally created as [ARROW-13423](https://issues.apache.org/jira/browse/ARROW-13423). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
