### ISSUE TITLE
[C++][Dataset][Parquet] Support parquet modular encryption in the new Dataset API

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29238]
In order for the new Dataset API to fully support PME, the same writer properties that include file_encryption_properties shouldn’t be used for the whole dataset. file_encryption_properties should be per file, for example in order to support key rotation ARROW-9960 .
Design document: <https://docs.google.com/document/d/13EysCNC6-Nu9wnJ8YpdzmD-aMLn4i2KXUJTNqIihy7A/edit#>

**Reporter**: [Maya Anderson](https://issues.apache.org/jira/browse/ARROW-13593) / @andersonm-ibm

#### Related issues:

- https://github.com/apache/arrow/issues/25986 (Dependency)
- https://github.com/apache/arrow/issues/32564 (supercedes)
- https://github.com/apache/arrow/issues/31410 (is depended upon by)

#### PRs and other links:
- [Design document](https://docs.google.com/document/d/13EysCNC6-Nu9wnJ8YpdzmD-aMLn4i2KXUJTNqIihy7A/edit#)

<sub>**Note**: *This issue was originally created as [ARROW-13593](https://issues.apache.org/jira/browse/ARROW-13593). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
@tolleybot if you could answer here on this comment, I can assign the issue to you (some strange limitation of github that this is required .. ;))
