### ISSUE TITLE
[R] Objects Written to Feather Not Restored Exactly

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29298]
Rather simple - write the standard 'iris' dataset to feather, then read it back.

At first glance everything looks the same, but setting 'attrib.as.set = FALSE' to identical() will return FALSE.

Using Waldo to compare, you can see that the order of attributes is different on the restored object. "class" should be the second attribute after "names" but before "row.names".

This should be a simple fix to the 'read_feather' function to set the correct order of attributes.

—

iris <- iris
 arrow::write_feather(iris, file <- tempfile())
 iris2 <- arrow::read_feather(file)
 unlink(file)
 identical(iris, iris2)
 #> [1] TRUE
 identical(iris, iris2, attrib.as.set = FALSE)
 #> [1] FALSE
 waldo::compare(attributes(iris), attributes(iris2))
 #> `names(old)`: "names" "class" "row.names" 
 #> `names(new)`: "names" "row.names" "class"

**Environment**: R4.1.1, Ubuntu 20.04
**Reporter**: [Charlie Gao](https://issues.apache.org/jira/browse/ARROW-13661)

<sub>**Note**: *This issue was originally created as [ARROW-13661](https://issues.apache.org/jira/browse/ARROW-13661). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
Closing this as I don't think attribute order roundtrip fidelity is something we're likely to invest time in support unless it becomes a wider issue for other users. Happy to review a PR to fix this though if anyone wants to submit one.
