### ISSUE TITLE
ArrowNotImplementedError: list<item: uint8>

### ISSUE THREAD

**Issue by vlavorini** [apache/arrow#2945]
Hi, not sure if this is a bug or not.

I am trying to save a Pandas dataframe in feather format, and I get:

    ArrowNotImplementedError: list<item: uint8>

I see Feather accept `uint8` format, so probably this behavior should be due to the `list` content. I don't find any documnetation on this, so: Is this an expected issue?

cheers

**Comment by wesm** [comment]
Feather doesn't support nested types yet. This is documented in http://arrow.apache.org/docs/python/ipc.html#feather-format

As soon as the R bindings for Apache Arrow are shipping, we can look at building a Feather V2 which will include nested data support (using the Arrow IPC protocol)
