### ISSUE TITLE
[RUST] Unsafe methods not declared unsafe

### ISSUE THREAD

**Issue by blkerby** [apache/arrow#2948]
Hi, I'm somewhat new here but am interested in this project and related efforts to bring tools for data science and machine learning to Rust. 

I noticed some methods in [array.rs](https://github.com/apache/arrow/blob/1ef6c2644b654fa77c49cc20bb9d8fc66d3f0c4f/rust/src/array.rs) are unsafe but are not marked as such in their declaration:

PrimitiveArray<$native_ty>::value: https://github.com/apache/arrow/blob/1ef6c2644b654fa77c49cc20bb9d8fc66d3f0c4f/rust/src/array.rs#L162)
ListArray::value_offset_at: https://github.com/apache/arrow/blob/1ef6c2644b654fa77c49cc20bb9d8fc66d3f0c4f/rust/src/array.rs#L437
BinaryArray::value_offset_at: https://github.com/apache/arrow/blob/1ef6c2644b654fa77c49cc20bb9d8fc66d3f0c4f/rust/src/array.rs#L542

The surrounding comments make it clear that the lack of safety is intended, for performance reasons. In this case, I believe we should declare these methods as unsafe in order to accurately signal to the caller that it is their responsibility to use them safely, in accordance with Rust's mandate:

> Unsafe functions are functions that are not safe in all contexts and/or for all possible inputs. Such a function must be prefixed with the keyword unsafe ... (https://doc.rust-lang.org/stable/reference/unsafe-functions.html)

This would be a breaking change, since callers would then need to mark their own code unsafe in order to use these methods. Alternatively, we could add an `assert` to make the existing methods safe but then make available an additional, unchecked version (e.g., `value_unchecked`) declared as unsafe which callers can opt into for performance reasons.

I noticed a related method already contains an `assert` rendering it safe. 
PrimitiveArray<bool>::value:  https://github.com/apache/arrow/blob/1ef6c2644b654fa77c49cc20bb9d8fc66d3f0c4f/rust/src/array.rs#L315

I'm assuming it would probably be ideal to make the API uniform in this regard; i.e., for this group of methods either provide only unsafe versions in all cases, or provide both safe and unsafe versions in all cases. I tend to think it would be nice to have both a safe and an unsafe version. What are your thoughts?

**Comment by paddyhoran** [comment]
Hi @blkerby, I think you are correct.  The rust implementation is not as complete as some of the other implementations so there are a lot small things to refine.  We manage issues on JIRA, I created an issue for you [here](https://issues.apache.org/jira/browse/ARROW-3776).  We would love to have you join the effort :)

I too believe that Rust could be a fantastic tool in scientific computing, etc (Actuarial Modeling is my particular domain) if the lower level building blocks are in place (aka Apache Arrow).  We would love for you to join the community and contribute to the project!

Feel free to ping me on JIRA with any questions.

**Comment by blkerby** [comment]
Thanks for the welcome! I can take a closer look at this one and make a pull request. Then I'll hop on over to JIRA to continue the conversation.
