### ISSUE TITLE
[CI] Docker Push step authentication is failing

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29544]
It looks like many (all?) of our GitHub Actions docker push steps are failing at the Docker Push step with:

```Java

Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
Traceback (most recent call last):
  File "/home/runner/work/arrow/arrow/dev/archery/archery/docker/core.py", line 214, in _execute_docker
    result = Docker().run(*args, **kwargs)
  File "/home/runner/work/arrow/arrow/dev/archery/archery/utils/command.py", line 78, in run
    return subprocess.run(invocation, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'login', '-u', '***', '-p', '***']' returned non-zero exit status 1.
```

One example: https://github.com/apache/arrow/runs/3545331147?check_suite_focus=true#step:8:9

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-13934) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-13934](https://issues.apache.org/jira/browse/ARROW-13934). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as outdated
