### ISSUE TITLE
[C++] Make Windows S3FileSystem/Minio tests more reliable

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29563]
[Example log](https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/40696885/job/5t25hl7biwxdipe9)
```

[ RUN      ] TestS3FS.FileSystemFromUri
WARNING: maximum file descriptor limit 0 is too low for production servers. At least 4096 is recommended. Fix with "ulimit -n 4096"
C:/projects/arrow/cpp/src/arrow/filesystem/s3fs_test.cc(387): error: Failed
'OutcomeToStatus(client_->CreateBucket(req))' failed with IOError: AWS Error [code 130]: Your previous request to create the named bucket succeeded and you already own it.
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1523: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-s6295hb6/.minio.sys/tmp/3cb9aaa7-6716-4c53-a30e-c2348f122148': . Detail: [Windows error 145] The directory is not empty.
[  FAILED  ] TestS3FS.FileSystemFromUri (7172 ms)
[ RUN      ] TestS3FS.CustomRetryStrategy
WARNING: maximum file descriptor limit 0 is too low for production servers. At least 4096 is recommended. Fix with "ulimit -n 4096"
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1523: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-wm32qa0y/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.CustomRetryStrategy (814 ms)
[----------] 23 tests from TestS3FS (51710 ms total) 
```
The tests are quite slow, and it seems in part because the bucket is being recreated/deleted on every test; also because some things seem to be eventually consistent(?) so we aren't cleaning files up properly.

It would also be nice here if the error from CreateBucket contained the bucket name.

**Reporter**: [David Li](https://issues.apache.org/jira/browse/ARROW-13957) / @lidavidm
#### Related issues:
- [[CI] AppVeyor build occationally fails due to file permissions](https://github.com/apache/arrow/issues/30568) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-13957](https://issues.apache.org/jira/browse/ARROW-13957). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by bkietz** [comment]
This appears to still be happening: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/48073408#L3429

@pitrou do you still think generating different bucket names is a viable approach? If so I could try a quick patch

**Comment by pitrou** [comment]
I don't think different bucket names would have an impact, since each test already uses a different data dir for Minio.

**Comment by pitrou** [comment]
Note this issue is a bit obsolete as we revamped the way S3 tests are ran, so we should just close it and open new ones for any flakiness currently witnessed.
