### ISSUE TITLE
[C++] Vendor a span implementation

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29678]
std::span is a basic vocabulary type which won't be available to us until c++20. We should vendor an implementation similar to our util::optional

**Reporter**: [Ben Kietzman](https://issues.apache.org/jira/browse/ARROW-14083) / @bkietz

<sub>**Note**: *This issue was originally created as [ARROW-14083](https://issues.apache.org/jira/browse/ARROW-14083). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by bkietz** [comment]
A span polyfill was added in https://github.com/apache/arrow/pull/36334
