### ISSUE TITLE
[C++] interval comparison kernels

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29712]
Subtask for tracking interval comparison kernels

**Reporter**: [Phillip Cloud](https://issues.apache.org/jira/browse/ARROW-14122) / @cpcloud
**Watchers**: [Rok Mihevc](https://issues.apache.org/jira/browse/ARROW-14122) / @rok

<sub>**Note**: *This issue was originally created as [ARROW-14122](https://issues.apache.org/jira/browse/ARROW-14122). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by cpcloud** [comment]
This was an interesting discussion!

It seems like effort here has stalled, so I'm going to close it out.

If anyone would like to work on it, please reopen!
