### ISSUE TITLE
[C++] DayTimeIntervalType::DayMilliseconds comparison function seems incorrect

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29713]
The less than operator (`operator<`) implemented on `DayTimeIntervalType::DayMilliseconds` seems incorrect:

```cpp

    bool operator<(DayMilliseconds other) const {
      return this->days < other.days || this->milliseconds < other.milliseconds;
    }

```

With this implementation, an example (in pseudocode) such as 

```cpp

DayMilliseconds { days = 10, milliseconds = 999 } < DayMilliseconds { days = 9, milliseconds = 1000 }
```

would return `true` when it should return `false`.

**Reporter**: [Phillip Cloud](https://issues.apache.org/jira/browse/ARROW-14123) / @cpcloud
**Watchers**: [Rok Mihevc](https://issues.apache.org/jira/browse/ARROW-14123) / @rok

<sub>**Note**: *This issue was originally created as [ARROW-14123](https://issues.apache.org/jira/browse/ARROW-14123). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by cpcloud** [comment]
This issue is quite old. It's a bug, but it doesn't seem to be super urgent. I'm going to close it as stale. Anyone is welcome to work on it.
