### ISSUE TITLE
[C++][Docs][Parquet] Trouble installing on Cent OS 7

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29741]
Installing on Cent OS 7 is not well documented and can be problematic, in particular for debug builds. Create guidelines for this that could also be turned into nightly tests.

**Environment**: Cent OS 7
**Reporter**: [Benson Muite](https://issues.apache.org/jira/browse/ARROW-14152) / @bkmgit
#### Original Issue Attachments:
- [CentOS7-gcc4.8.5-CMakeCache.txt](https://issues.apache.org/jira/secure/attachment/13034289/CentOS7-gcc4.8.5-CMakeCache.txt)
- [CentOS7-gcc4.8.5-makelog.out](https://issues.apache.org/jira/secure/attachment/13034290/CentOS7-gcc4.8.5-makelog.out)

<sub>**Note**: *This issue was originally created as [ARROW-14152](https://issues.apache.org/jira/browse/ARROW-14152). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Outdated
