### ISSUE TITLE
[Dev] merge_arrow_pr.py script fails if head pointer can't be checked out

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29743]
```Java

Merge complete (local ref PR_TOOL_MERGE_PR_11241_MASTER). Push to apache? (y/n): y
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 32 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 1.98 KiB | 1.98 MiB/s, done.
Total 9 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
To github.com:apache/arrow.git
   e5dc9d411..689a0b696  PR_TOOL_MERGE_PR_11241_MASTER -> master
Restoring head pointer to 6254bf77
error: pathspec '6254bf77' did not match any file(s) known to git
Command failed: ['git', 'checkout', '6254bf77']
```

Why does the script need to do anything that mutates the state of the clone?

**Reporter**: [Phillip Cloud](https://issues.apache.org/jira/browse/ARROW-14154) / @cpcloud

<sub>**Note**: *This issue was originally created as [ARROW-14154](https://issues.apache.org/jira/browse/ARROW-14154). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by nealrichardson** [comment]
@kou @raulcd @assignUser is this still valid? We use the GH API now so this shouldn't be happening.

**Comment by raulcd** [comment]
You are correct, that should not happen anymore the `git checkout` command was removed when we moved to the GH API: https://github.com/apache/arrow/commit/01e4ad095a7649afc7a7316447bc5cc1fd9679a2
