### ISSUE TITLE
link error on ubuntu

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29773]
I used vcpkg to install arrow versions 4 and 5, trying to build my code that uses parquet fails by giving link errors of undefined reference.

The same code works on OSX but fails on ubuntu.

My cmake snippet is as follows:

 
```java

find_package(Arrow CONFIG REQUIRED)
get_filename_component(MY_SEARCH_DIR ${Arrow_CONFIG} DIRECTORY)
find_package(Parquet CONFIG REQUIRED PATHS ${MY_SEARCH_DIR})
find_package(Thrift CONFIG REQUIRED)
```
and the linking: 

 
```java

target_link_libraries(vision_obj PUBLIC .... thrift::thrift re2::re2 arrow_static parquet_static )
```
 

 I get a lot of errors

 

**Environment**: Ubuntu 18.04, gcc-9, and vcpkg installation of arrow
**Reporter**: [Amir Ghamarian](https://issues.apache.org/jira/browse/ARROW-14188)
#### Original Issue Attachments:
- [completerr.txt](https://issues.apache.org/jira/secure/attachment/13034474/completerr.txt)
- [linkerror.txt](https://issues.apache.org/jira/secure/attachment/13034446/linkerror.txt)

<sub>**Note**: *This issue was originally created as [ARROW-14188](https://issues.apache.org/jira/browse/ARROW-14188). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
The vcpkg port has had 6 new versions so it is unlikely that this issue still remains.
