### ISSUE TITLE
PlasmaClient::Contains should return false before the corresponding object is sealed

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29850]
According to the doc(<https://arrow.apache.org/docs/python/generated/pyarrow.plasma.PlasmaClient.html?highlight=contains#pyarrow.plasma.PlasmaClient.contains>), contains should return false before the corresponding object is sealed.

**Reporter**: [chimucong](https://issues.apache.org/jira/browse/ARROW-14273)
#### Related issues:
- [PlasmaClient::Contains should return false before the corresponding object is sealed](https://github.com/apache/arrow/issues/29849) (duplicates)
#### PRs and other links:
- [GitHub Pull Request #11226](https://github.com/apache/arrow/pull/11226)

<sub>**Note**: *This issue was originally created as [ARROW-14273](https://issues.apache.org/jira/browse/ARROW-14273). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
