### ISSUE TITLE
[C++] Sorting dictionary array not implemented

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29887]
From R, taking the stock `mtcars` dataset and giving it a dictionary type column:

```Java

mtcars %>% 
  mutate(cyl = as.factor(cyl)) %>% 
  Table$create() %>% 
  arrange(cyl) %>% 
  collect()

Error: Type error: Sorting not supported for type dictionary<values=string, indices=int8, ordered=0>
../src/arrow/compute/kernels/vector_array_sort.cc:427  VisitTypeInline(type, this)
../src/arrow/compute/kernels/vector_sort.cc:148  GetArraySorter(*physical_type_)
../src/arrow/compute/kernels/vector_sort.cc:1206  sorter.Sort()
../src/arrow/compute/api_vector.cc:259  CallFunction("sort_indices", {datum}, &options, ctx)
../src/arrow/compute/exec/order_by_impl.cc:53  SortIndices(table, options_, ctx_)
../src/arrow/compute/exec/sink_node.cc:292  impl_->DoFinish()
../src/arrow/compute/exec/exec_plan.cc:297  iterator_.Next()
../src/arrow/record_batch.cc:318  ReadNext(&batch)
../src/arrow/record_batch.cc:329  ReadAll(&batches)
```

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-14314) / @nealrichardson
**Assignee**: [Ariana Villegas](https://issues.apache.org/jira/browse/ARROW-14314) / @ArianaVillegas
#### PRs and other links:
- [GitHub Pull Request #13334](https://github.com/apache/arrow/pull/13334)

<sub>**Note**: *This issue was originally created as [ARROW-14314](https://issues.apache.org/jira/browse/ARROW-14314). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by coady** [comment]
This did not implemented sorting on dictionary chunked arrays, or in tables. Is that planned, or should I open a feature request?

**Comment by lorentzenchr** [comment]
With pyarrow version 14
```python
import pyarrow as pa

dict_array = pa.DictionaryArray.from_arrays([2, 0, 2, 1, 0], ["c", "a", "b"])
dict_array.dictionary_decode()  # ["b", "c", "b", "a", "c"]

dict_array.sort().dictionary_decode()  # ["a", "b", "b", "c", "c"]
```

So it is just the alpha numerical sort order, not the order as given by the dictionary. I find that a bit unfortunate and don't find any discussion of it.

**Comment by pitrou** [comment]
This is what most people would expect. What did you expect here?

**Comment by lorentzenchr** [comment]
As the dictionary is specified as `["c", "a", "b"]`, I would have expected to preserve that ordering resulting in a decoded array `["c", "c", "a", "b", "b"]`, or to have the option to do so.

With pandas ordered categoricals:
```python
import pandas as pd

s = pd.Series(pd.Categorical(["b", "c", "b", "a", "c"], categories=["c", "a", "b"], ordered=True))
s  # b c b a c

s.sort_values()  # c c a b b
```
Use case: Being able to specify the sort order can make plots or reported tables much easier to create.

**Comment by pitrou** [comment]
In this case, you could probably create a new column with just the dictionary indices and sort on that column.

**Comment by pitrou** [comment]
cc @jorisvandenbossche FYI ^^

**Comment by lorentzenchr** [comment]
> In this case, you could probably create a new column with just the dictionary indices and sort on that column.

That's what I'm actually doing in a package of mine (with polars as df). Being able to specify the order as a user would just be much more convenient and less code. That's all I'm saying.
