### ISSUE TITLE
[Python] Add support for the SSO credential provider

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29912]
Not sure about other languages
 see also: <https://github.com/boto/botocore/pull/2070>
```java

from pyarrow.fs import S3FileSystem 

bucket = 'some-bucket-with-read-access' 
key = 'some-existing-key' 

s3 = S3FileSystem() 
s3.open_input_file(f'{bucket}/{key}')
```
 
 results in

 
```java

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    s3.open_input_file(f'{bucket}/{key}')
  File "pyarrow/_fs.pyx", line 587, in pyarrow._fs.FileSystem.open_input_file
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When reading information for key 'some-existing-key' in bucket 'some-bucket-with-read-access': AWS Error [code 15]: No response body.
```
 

without sso creds supported - shouldn't it raise some kind of AccessDenied Exception?

 

 

**Reporter**: [Björn Boschman](https://issues.apache.org/jira/browse/ARROW-14342)
#### Related issues:
- [[R] AWS SSO for R package](https://github.com/apache/arrow/issues/33131) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-14342](https://issues.apache.org/jira/browse/ARROW-14342). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by AQX-Ben** [comment]
Any updates on this issue ? 

`geopandas` uses Pyarrow to read geo parquet.
It is not possible to use the workaround from @asfimport.

**Comment by westonpace** [comment]
AFAIK we are still on 1.8 of AWS SDK.  Someone will have to try bumping the AWS SDK version and see how it goes.  @wjones127 do you know if there is any plan to bump the AWS version?

**Comment by wjones127** [comment]
@AQX-Ben Why is it not possible to use the workaround? You should be able to pass the filesystem to `geopandas.read_parquet` or pass storage options with the key.

https://geopandas.org/en/stable/docs/reference/api/geopandas.read_parquet.html#geopandas.read_parquet

@westonpace not sure but I can look at bumping that for the next version, at least for Python.

**Comment by kou** [comment]
#33808 ?

**Comment by wjones127** [comment]
I just tested with the `main` branch. AWS SSO will work in the 12.0.0 release.
