### ISSUE TITLE
[R] Add Raspberry Pi CI build to nightlies

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30016]
Now that we support Raspberry Pi OS (<https://github.com/apache/arrow/pull/11506),> and it might be possible to set up a 32-bit ARM CI which reflects the Rasberry Pi (<https://github.com/apache/arrow/pull/11506#issuecomment-949897509)> , we could set up a nightly build for this.

**Reporter**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-14455) / @thisisnic

<sub>**Note**: *This issue was originally created as [ARROW-14455](https://issues.apache.org/jira/browse/ARROW-14455). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Is it useful to keep this open? @thisisnic @jonkeane @nealrichardson

**Comment by nealrichardson** [comment]
Probably not, if we've gone 3 years without anyone complaining that we're broken on this platform.
