### ISSUE TITLE
[JS][Release] Ensure can use nohup with the release script

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30032]
Node may have problems reading and writing files when called using nohup. Directly running 

```bash

env "TEST_DEFAULT=0" env "TEST_JS=1"  bash dev/release/verify-release-candidate.sh source 6.0.0 3
```

seems to work, but
```bash

nohup env "TEST_DEFAULT=0" env "TEST_JS=1"  bash dev/release/verify-release-candidate.sh source 6.0.0 3 > log.out &
```
may not work [1]. Either document that one can use 
```bash

(nohup env "TEST_DEFAULT=0" env "TEST_JS=1"  bash dev/release/verify-release-candidate.sh source 6.0.0 3 > log.out & )
```
or modify the javascript implementation so that it can run as a background process and still find files so that the error:
```bash

yarn run v1.22.17
$ /tmp/arrow-6.0.0.BDnN3/apache-arrow-6.0.0/js/node_modules/.bin/run-s
clean:all lint build
events.js:377
        throw er; // Unhandled 'error' event
        ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
      at internal/fs/streams.js:173:14
      at FSReqCallback.wrapper [as oncomplete] (fs.js:562:5) {
    errno: -9,
    code: 'EBADF',
    syscall: 'read'
}
error Command failed with exit code 1.
```
is not obtained.

[1] https://stackoverflow.com/questions/16604176/error-ebadf-bad-file-descriptor-when-running-node-using-nohup-of-forever

**Reporter**: [Benson Muite](https://issues.apache.org/jira/browse/ARROW-14473) / @bkmgit

<sub>**Note**: *This issue was originally created as [ARROW-14473](https://issues.apache.org/jira/browse/ARROW-14473). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
Closing since there hasn't been any activity and it's unclear whether this is still an issue. Please open a new one.
