### ISSUE TITLE
[Python] Add StructType attribute to access all its fields

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30058]
Currently when having a StructType, you can check the number of fields or get a specific field by index:

```Java

>>> struct_type = pa.struct([('a', pa.int64()), ('b', pa.float64())])
>>> struct_type.num_fields
2
>>> struct_type.get_field_index("a")
0
>>> struct_type[0]
pyarrow.Field<a: int64>
```

and so that means you can actually get all fields by iterating:

```Java

>>> list(struct_type)
[pyarrow.Field<a: int64>, pyarrow.Field<b: double>]
```

That's straightfoward code once you know this, but personally I don't find this very discoverable. 

I think it would be nice to have some additional convenience attributes, such as `.fields` returning a list of all fields and `.names` returning a list of the field names (currently you need `[f.name for f in struct_type]` for this).

**Reporter**: [Joris Van den Bossche](https://issues.apache.org/jira/browse/ARROW-14501) / @jorisvandenbossche

<sub>**Note**: *This issue was originally created as [ARROW-14501](https://issues.apache.org/jira/browse/ARROW-14501). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 43481
https://github.com/apache/arrow/pull/43481
