### ISSUE TITLE
Make RC releases as tagged releases

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30063]
When we make RC releases, we should also make a tagged release on NPM instead of a full release. http://npm.github.io/publishing-pkgs-docs/updating/using-tags.html

**Reporter**: [Dominik Moritz](https://issues.apache.org/jira/browse/ARROW-14507) / @domoritz

<sub>**Note**: *This issue was originally created as [ARROW-14507](https://issues.apache.org/jira/browse/ARROW-14507). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
Would be nice but no-one has the cycles for this right now.
