### ISSUE TITLE
Continuous releases of the JS library

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30064]
To help people test new features and detect bugs early, we should make regular releases of the JS package. This could be nightly or whenever we merge a pull request with a JS tag on it. I think the latter would be better since it would reduce the number of releases significantly. 

Releases should be tagged as canary. http://npm.github.io/publishing-pkgs-docs/updating/using-tags.html

**Reporter**: [Dominik Moritz](https://issues.apache.org/jira/browse/ARROW-14508) / @domoritz

<sub>**Note**: *This issue was originally created as [ARROW-14508](https://issues.apache.org/jira/browse/ARROW-14508). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
This would be nice but doesn't work easily with the apache release model.
