### ISSUE TITLE
[C++][CI] Fix GCS testbench for Debian 10

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30061]
cc @coryan
The GCS testbench is broken on Debian 10. ARROW-14491 removes it temporarily, but it should be fixed and added back. Initially it complained about pip availability, which could be solved by installing python3-setuptools and symlinking pip to pip3 in debian-10-cpp.dockerfile, however the run itself still fails.

**Reporter**: [Balazs Jeszenszky](https://issues.apache.org/jira/browse/ARROW-14504) / @jeszyb

<sub>**Note**: *This issue was originally created as [ARROW-14504](https://issues.apache.org/jira/browse/ARROW-14504). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
I close this because Debian GNU/Linux 10 reached EOL on 2022-09-10.
