### ISSUE TITLE
[R] [CI] Check without any of the suggested packages

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30098]
https://www.stats.ox.ac.uk/pub/bdr/noSuggests/README.txt

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-14544) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-14544](https://issues.apache.org/jira/browse/ARROW-14544). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@jonkeane Do you think this issue is worth keeping open?
