### ISSUE TITLE
[R] [CI] Confirm that our sanitizer jobs are as close to CRAN as possible

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30092]
Here are the setups:
https://www.stats.ox.ac.uk/pub/bdr/memtests/README.txt

We do each (gcc-\*SAN, clang-\*SAN, and valgrind) slightly differently, can (should?) we unify those? What upstream additions/changes might we want or need to do that?

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-14537) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-14537](https://issues.apache.org/jira/browse/ARROW-14537). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@jonkeane Do you think this issue is worth keeping open?
