### ISSUE TITLE
[R] [CI] rcnst checks

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30099]
https://raw.githubusercontent.com/kalibera/cran-checks/master/rcnst/README.txt

https://github.com/kalibera/cran-checks/tree/master/rcnst

This is similar to our current rchk check:

- task: https://github.com/apache/arrow/blob/24acebcb5325c2bd2210cbe80e179250b60df7b1/dev/tasks/tasks.yml#L1084-L1086
- crossbow yaml: https://github.com/apache/arrow/blob/master/dev/tasks/r/github.linux.rchk.yml
  
  We could probably add a new task to this / make it a matrix of rchk/rcnst

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-14545) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-14545](https://issues.apache.org/jira/browse/ARROW-14545). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@jonkeane Do you think this issue is worth keeping open?
