### ISSUE TITLE
[R] [CI] Check with a read only library

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30100]
https://raw.githubusercontent.com/kalibera/cran-checks/master/rlibro/README.txt

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-14546) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-14546](https://issues.apache.org/jira/browse/ARROW-14546). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@jonkeane Do you think this issue is worth keeping open?
