### ISSUE TITLE
[CI][Crossbow] Fetch a single crossbow branch instead of the full repo on Azure

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30135]
Since crossbow has a lot of references the checkout step can take a long time, see build https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=14952&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5bbb8710-d4c1-5a8b-fc80-a388730cf6ac

We should alter the azure crossbow template to explicitly check out the task's branch using 
` {{ task.branch ` }} jinja variable.

See azure documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checking-out-a-specific-ref

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-14587) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-14587](https://issues.apache.org/jira/browse/ARROW-14587). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@kszucs @assignUser Do you think this issue is still relevant?

**Comment by kszucs** [comment]
Are we still using azure jobs? This ticket is about sparing some build time, but if the builds are quick enough then we can close this.

**Comment by pitrou** [comment]
I think we have a couple of them, but not many, and there's an issue open to migrate the remaining ones to GHA: GH-37281
