### ISSUE TITLE
[R] Create an arrow-specific checklist for a CRAN release  

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30136]
This would adapt and implement the functionality of `usethis::use_release_issue()` for `arrow`'s specific context.

**Reporter**: [Dragoș Moldovan-Grünfeld](https://issues.apache.org/jira/browse/ARROW-14588) / @dragosmg

<sub>**Note**: *This issue was originally created as [ARROW-14588](https://issues.apache.org/jira/browse/ARROW-14588). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
We have this now, not as part of usethis but works imo.
