### ISSUE TITLE
[Python] Add sort_by method to Array, StructArray and ChunkedArray

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30198]
It would be convenient to be able to sort a `StructArray` on one of its columns. This can be done by combining multiple compute functions, but having a helper that does that for you would probably be better.

**Reporter**: [Alessandro Molina](https://issues.apache.org/jira/browse/ARROW-14656) / @amol-
**Assignee**: [Alessandro Molina](https://issues.apache.org/jira/browse/ARROW-14656) / @amol-
#### PRs and other links:
- [GitHub Pull Request #14369](https://github.com/apache/arrow/pull/14369)

<sub>**Note**: *This issue was originally created as [ARROW-14656](https://issues.apache.org/jira/browse/ARROW-14656). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Duplicate of #14778
