### ISSUE TITLE
[Ruby][CI] Test all supported Ruby versions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30227]
Add systematic testing for different supported ruby versions. 2.5, 2.6, 2.7 and 3.0

**Reporter**: [Benson Muite](https://issues.apache.org/jira/browse/ARROW-14687) / @bkmgit

<sub>**Note**: *This issue was originally created as [ARROW-14687](https://issues.apache.org/jira/browse/ARROW-14687). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@kou Do you think we should keep this issue open?

**Comment by kou** [comment]
We can close this.

I agree that testing all supported version in CI is better but it increases our CI time. We already have long CI time. So I don't want to increase it for now.

We can revisit this when we have less CI time. For example, if we split more components to separated repositories such as apache/arrow-go, we can decrease CI time.
