### ISSUE TITLE
Building with -DARROW_GANDIVA=ON fails to detect Re2

### ISSUE THREAD

**Issue by suvayu** [apache/arrow#3026]
**Version:** release tarball of 0.11.1

### Error
`cmake` doesn't seem to find Re2 on my system.  The `FindRE2.cmake` in the release tarball was looking in `/lib`, and `/include`, so I replaced it with the version on `master`.  But the problem persists:

    -- RE2_HOME:
    CMake Error at cmake_modules/FindRE2.cmake:87 (message):
      Could not find re2 (missing headers).  Looked in system search paths.)
    Call Stack (most recent call first):
      src/gandiva/CMakeLists.txt:23 (find_package)

### System
As you can see below, everything is where it should be.

    $ ls /usr/lib64/libre2.so* /usr/include/re2/
    /usr/lib64/libre2.so  /usr/lib64/libre2.so.0  /usr/lib64/libre2.so.0.0.0

    /usr/include/re2/:
    filtered_re2.h  re2.h  set.h  stringpiece.h  variadic_function.h

### CMake invocation
This is how I invoke cmake:

    $ echo $ARROW_HOME 
    /opt/data-an
    $ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
        -DARROW_PARQUET=on -DARROW_PLASMA=on -DARROW_GANDIVA=ON \
        -DARROW_PYTHON=on -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6m \
        -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m \
        -DPYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython3.6m.so ../

I have to add the python paths to compile with Python 3.

Any thoughts on how I can compile with Gandiva enabled?

**Comment by wesm** [comment]
Can you try from the master branch and open a JIRA issue if master does not work? Gandiva is not supported for end users in 0.11.x

**Comment by suvayu** [comment]
Okay thanks.

I tried with `master`, now cmake fails to detect llvm even before getting to Re2!

    -- Found LLVM 6.0.1
    -- Using LLVMConfig.cmake in: /usr/lib64/cmake/llvm
    CMake Error at /usr/lib64/cmake/llvm/LLVM-Config.cmake:175 (message):
      Target X86 is not in the set of libraries.
    Call Stack (most recent call first):
      cmake_modules/FindLLVM.cmake:31 (llvm_map_components_to_libnames)
      src/gandiva/CMakeLists.txt:25 (find_package)

Strange!  I'll file a Jira tomorrow.

**Comment by suvayu** [comment]
Jira: [ARROW-3874](https://issues.apache.org/jira/browse/ARROW-3874)
