### ISSUE TITLE
[Python] Import Error for pyarrow.flight in pyarrow 6.0.0 and 6.0.1

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30499]
**Description:**

Unable to import flight module in pyarrow in version 6.0.0 and 6.0.1.  Is there a different package I can install that provides the module? Or is this potentially an issue with me using apple silicon?

 

**Error:**

>>>import pyarrow.flight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/repo/pyarrow/flight.py", line 18, in <module>
    from pyarrow._flight import (  # noqa:F401
ModuleNotFoundError: No module named 'pyarrow._flight'

 

**How to replicate**

pip3.8 install pyarrow==6.0.1

python3.8 -c 'import pyarrow.flight'

 

**Python version:**

Python version: 3.8

 

**Environment**

MacBook Pro (Apple Silicon)

**Reporter**: [Eric Henry](https://issues.apache.org/jira/browse/ARROW-14978)

<sub>**Note**: *This issue was originally created as [ARROW-14978](https://issues.apache.org/jira/browse/ARROW-14978). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Given this is an older issue, and there was no further response, closing this.
