### ISSUE TITLE
[CI] Docker push fails on Travis-CI

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30541]
See for https://app.travis-ci.com/github/apache/arrow/jobs/551022779#L3226

```Java

Pushing ubuntu-cpp (apache/arrow-dev:arm64v8-ubuntu-20.04-cpp)...
The push refers to repository [docker.io/apache/arrow-dev]
ERROR: denied: requested access to the resource is denied
```

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-15023) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-15023](https://issues.apache.org/jira/browse/ARROW-15023). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We have no Travis-CI builds anymore, closing as outdated.
