### ISSUE TITLE
[CI] AppVeyor build occationally fails due to file permissions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30568]
See if can change folders to ensure AppVeyor does not fail with

Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\api-errors.go:2091:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:2116:cmd.toAPIError()
       2: cmd\object-handlers.go:1801:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
API: PutObject(bucket=bucket, object=somefile/)
Time: 04:55:01 GMT 12/10/2021
DeploymentID: 870cd1bb-55d6-48a6-8ab6-32cf13b2b1fb
RequestID: 16BF4BC5833F0EFC
RemoteHost: 127.0.0.1
Host: 127.0.0.1:2703
UserAgent: aws-sdk-cpp/1.9.162 Windows/10.0.14393.2430 AMD64 MSVC/1916
Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\fs-v1.go:1033:cmd.(\*FSObjects).putObject()
       3: cmd\fs-v1.go:1009:cmd.(\*FSObjects).PutObject()
       2: cmd\object-handlers.go:1799:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
API: PutObject(bucket=bucket, object=somefile/)
Time: 04:55:01 GMT 12/10/2021
DeploymentID: 870cd1bb-55d6-48a6-8ab6-32cf13b2b1fb
RequestID: 16BF4BC5833F0EFC
RemoteHost: 127.0.0.1
Host: 127.0.0.1:2703
UserAgent: aws-sdk-cpp/1.9.162 Windows/10.0.14393.2430 AMD64 MSVC/1916
Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\api-errors.go:2091:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:2116:cmd.toAPIError()
       2: cmd\object-handlers.go:1801:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
API: PutObject(bucket=bucket, object=somefile/)
Time: 04:55:01 GMT 12/10/2021
DeploymentID: 870cd1bb-55d6-48a6-8ab6-32cf13b2b1fb
RequestID: 16BF4BC58F58C5D4
RemoteHost: 127.0.0.1
Host: 127.0.0.1:2703
UserAgent: aws-sdk-cpp/1.9.162 Windows/10.0.14393.2430 AMD64 MSVC/1916
Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\fs-v1.go:1033:cmd.(\*FSObjects).putObject()
       3: cmd\fs-v1.go:1009:cmd.(\*FSObjects).PutObject()
       2: cmd\object-handlers.go:1799:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
API: PutObject(bucket=bucket, object=somefile/)
Time: 04:55:01 GMT 12/10/2021
DeploymentID: 870cd1bb-55d6-48a6-8ab6-32cf13b2b1fb
RequestID: 16BF4BC58F58C5D4
RemoteHost: 127.0.0.1
Host: 127.0.0.1:2703
UserAgent: aws-sdk-cpp/1.9.162 Windows/10.0.14393.2430 AMD64 MSVC/1916
Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\api-errors.go:2091:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:2116:cmd.toAPIError()
       2: cmd\object-handlers.go:1801:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
API: PutObject(bucket=bucket, object=somefile/)
Time: 04:55:01 GMT 12/10/2021
DeploymentID: 870cd1bb-55d6-48a6-8ab6-32cf13b2b1fb
RequestID: 16BF4BC59B722DC4
RemoteHost: 127.0.0.1
Host: 127.0.0.1:2703
UserAgent: aws-sdk-cpp/1.9.162 Windows/10.0.14393.2430 AMD64 MSVC/1916
Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\fs-v1.go:1033:cmd.(\*FSObjects).putObject()
       3: cmd\fs-v1.go:1009:cmd.(\*FSObjects).PutObject()
       2: cmd\object-handlers.go:1799:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
API: PutObject(bucket=bucket, object=somefile/)
Time: 04:55:01 GMT 12/10/2021
DeploymentID: 870cd1bb-55d6-48a6-8ab6-32cf13b2b1fb
RequestID: 16BF4BC59B722DC4
RemoteHost: 127.0.0.1
Host: 127.0.0.1:2703
UserAgent: aws-sdk-cpp/1.9.162 Windows/10.0.14393.2430 AMD64 MSVC/1916
Error: mkdir C:\Users\appveyor\AppData\Local\Temp\1\s3fs-test-069ymmze/bucket/somefile/: Cannot create a file when that file already exists. (\*fs.PathError)
       4: cmd\api-errors.go:2091:cmd.toAPIErrorCode()
       3: cmd\api-errors.go:2116:cmd.toAPIError()
       2: cmd\object-handlers.go:1801:cmd.objectAPIHandlers.PutObjectHandler()
       1: net\http\server.go:2047:http.HandlerFunc.ServeHTTP()
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-069ymmze/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.CreateDir (7253 ms)
[ RUN      ] TestS3FS.DeleteFile
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-bwf79qx5/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.DeleteFile (1056 ms)
[ RUN      ] TestS3FS.DeleteDir
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-ix37jn0g/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.DeleteDir (1145 ms)
[ RUN      ] TestS3FS.CopyFile
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-unfo7kzs/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.CopyFile (804 ms)
[ RUN      ] TestS3FS.Move
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-4bd3nohf/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.Move (796 ms)
[ RUN      ] TestS3FS.OpenInputStream
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-m9916r2z/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenInputStream (1085 ms)
[ RUN      ] TestS3FS.OpenInputStreamMetadata
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-q9fnthdy/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenInputStreamMetadata (743 ms)
[ RUN      ] TestS3FS.OpenInputFile
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-ddj9wenm/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenInputFile (1369 ms)
[ RUN      ] TestS3FS.OpenOutputStreamBackgroundWrites
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-wv3igly2/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamBackgroundWrites (2749 ms)
[ RUN      ] TestS3FS.OpenOutputStreamSyncWrites
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-tcehm6is/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamSyncWrites (2574 ms)
[ RUN      ] TestS3FS.OpenOutputStreamAbortBackgroundWrites
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-r6mj4jfw/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamAbortBackgroundWrites (1463 ms)
[ RUN      ] TestS3FS.OpenOutputStreamAbortSyncWrites
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-4vvi7d5x/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamAbortSyncWrites (774 ms)
[ RUN      ] TestS3FS.OpenOutputStreamDestructorBackgroundWrites
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-be1xup3m/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamDestructorBackgroundWrites (1215 ms)
[ RUN      ] TestS3FS.OpenOutputStreamDestructorSyncWrite
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-ugf443ll/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamDestructorSyncWrite (783 ms)
[ RUN      ] TestS3FS.OpenOutputStreamMetadata
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-zedvtmp9/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.OpenOutputStreamMetadata (988 ms)
[ RUN      ] TestS3FS.FileSystemFromUri
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-1frrdkwg/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.FileSystemFromUri (728 ms)
[ RUN      ] TestS3FS.CustomRetryStrategy
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-xdzm5ii1/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FS.CustomRetryStrategy (910 ms)
[----------] 23 tests from TestS3FS (39474 ms total)
[----------] 26 tests from TestS3FSGeneric
[ RUN      ] TestS3FSGeneric.Empty
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-nf1x5ce3/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FSGeneric.Empty (1562 ms)
[ RUN      ] TestS3FSGeneric.NormalizePath
C:/projects/arrow/cpp/src/arrow/util/io_util.cc:1552: When trying to delete temporary directory: IOError: Cannot delete directory entry 'C:/Users/appveyor/AppData/Local/Temp/1/s3fs-test-ytbbvxz2/.minio.sys': . Detail: [Windows error 145] The directory is not empty.
[       OK ] TestS3FSGeneric.NormalizePath (1389 ms)
[ RUN      ] TestS3FSGeneric.CreateDir
API: PutObject(bucket=s3fs-test-bucket, object=AB/def/)

**Reporter**: [Benson Muite](https://issues.apache.org/jira/browse/ARROW-15052) / @bkmgit
#### Related issues:
- [[C++] Make Windows S3FileSystem/Minio tests more reliable](https://github.com/apache/arrow/issues/29563) (relates to)
#### Original Issue Attachments:
- [log.txt](https://issues.apache.org/jira/secure/attachment/13037230/log.txt)

<sub>**Note**: *This issue was originally created as [ARROW-15052](https://issues.apache.org/jira/browse/ARROW-15052). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We haven't seen this in a long time, closing
