### ISSUE TITLE
getvalue() fails for pyarrow BufferOutputStream

### ISSUE THREAD

**Issue by mkm177** [apache/arrow#3058]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-5f2f926eb3b2> in <module>()
----> 1 buf = sink.getvalue()

AttributeError: 'pyarrow.lib.BufferOutputStream' object has no attribute 'getvalue'

Error above is encountered on
pyarrow 0.11.1
python 3.6.6

The documentation states this function is supported, but I am unable to call it to get values off a BufferOutputStream. 

Any suggestions for possible workarounds?

**Comment by wesm** [comment]
I did

```
conda create -n pyarrow-conda-test python=3.6 pyarrow
```

and

```
In [1]: import pyarrow as pa                                                                   

In [2]: pa.BufferOutputStream.getvalue?                                                        
Docstring:
BufferOutputStream.getvalue(self)

Finalize output stream and return result as pyarrow.Buffer.

Returns
-------
value : Buffer
Type:      method_descriptor
```

and

```
In [5]: f = pa.BufferOutputStream()                                                            

In [6]: f.write(b'foooooo')                                                                    
Out[6]: 7

In [7]: buf = f.getvalue()                                                                     

In [8]: buf                                                                                    
Out[8]: <pyarrow.lib.Buffer at 0x7f6a7c858308>

In [9]: buf.to_pybytes()                                                                       
Out[9]: b'foooooo'
```

Can you provide information to reproduce your issue? Please also remember to use JIRA for bug reports

**Comment by mkm177** [comment]
Thanks for the response. Noted...will use JIRA next time. 

I reproduced the exacts steps you have above and get the same error message:
`conda create -n pyarrow-conda-test python=3.6 pyarrow`
creates the new conda environment. 
Activate the new env.
Create a new jupyter python 3 notebook

```
import pyarrow as pa

pa.BufferOutputStream.getvalue?
Object `pa.BufferOutputStream.getvalue` not found.

pa.BufferOutputStream.getvalue()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-86516e90cc0c> in <module>()
----> 1 pa.BufferOutputStream.getvalue()

AttributeError: type object 'pyarrow.lib.BufferOutputStream' has no attribute 'getvalue'

```

Env details:
MacOS 10.13.6
conda v4.4.10
python v3.6.7
(pyarrow-conda-test) ******:anaconda3 ******$ conda list

Name                    Version                   Build  Channel
arrow-cpp                 0.11.1           py36hc2947fe_0  
blas                      1.0                         mkl  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.10.15               py36_0  
gflags                    2.2.2                h0a44026_0  
glog                      0.3.5                h0a44026_1  
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.1                      144  
libboost                  1.67.0               hebc422b_4  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libevent                  2.1.8                ha12b0ac_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
lz4-c                     1.8.1.2              h1de35cc_0  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py36hb8a8100_0  
mkl_random                1.0.1            py36h5d10147_1  
ncurses                   6.1                  h0a44026_1  
numpy                     1.15.4           py36h6a91979_0  
numpy-base                1.15.4           py36h8a80b8c_0  
openssl                   1.1.1a               h1de35cc_0  
pandas                    0.23.4           py36h6440ff4_0  
pip                       18.1                     py36_0  
pyarrow                   0.11.1           py36h0a44026_0  
python                    3.6.7                haf84260_0  
python-dateutil           2.7.5                    py36_0  
pytz                      2018.7                   py36_0  
readline                  7.0                  h1de35cc_5  
setuptools                40.6.2                   py36_0  
six                       1.11.0                   py36_1  
snappy                    1.1.7                he62c110_3  
sqlite                    3.25.3               ha441bb4_0  
thrift-cpp                0.11.0               hd79cdb6_3  
tk                        8.6.8                ha441bb4_0  
wheel                     0.32.3                   py36_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.3                h2a6be3a_0

**Comment by wesm** [comment]
You must have two versions of pyarrow installed. Probably an old one that you got using `pip` that's installed in your root environment

```
$ conda create -y -q -n pyarrow-conda-test-2 python=3.6 pyarrow -c defaults
$ conda activate pyarrow-conda-test-2
$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow as pa
>>> pa.BufferOutputStream
<class 'pyarrow.lib.BufferOutputStream'>
>>> pa.BufferOutputStream.getvalue
<method 'getvalue' of 'pyarrow.lib.BufferOutputStream' objects>
>>> pa
<module 'pyarrow' from '/home/wesm/miniconda/envs/pyarrow-conda-test-2/lib/python3.6/site-packages/pyarrow/__init__.py'>
```

Try printing the `pa` module itself to see the import path.

**Comment by mkm177** [comment]
I have only installed pyarrow in Conda environments. Never using pip. I followed the exacts steps you listed above and still have the same issue from the python prompt. 
The only difference I see comparing our environments is that my GCC is v4.2.1 and yours is v7.3.0. 

See below
```
*******:anaconda3 ******$ conda activate pyarrow-conda-test-2
(pyarrow-conda-test-2) *******:anaconda3 *******$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow as pa
>>> pa.BufferOutputStream
<class 'pyarrow.lib.BufferOutputStream'>
>>> pa.BufferOutputStream.getValue
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'pyarrow.lib.BufferOutputStream' has no attribute 'getValue'
>>> pa
<module 'pyarrow' from '/Users/mmadra/anaconda3/envs/pyarrow-conda-test-2/lib/python3.6/site-packages/pyarrow/__init__.py'>
>>> 
```

**Comment by wesm** [comment]
You have `getValue` there instead of `getvalue`

**Comment by mkm177** [comment]
Ahh shoot... sorry for the typo. 
This works from python prompt. 

I fired up jupyter notebook from inside this environment and still get the same error messages as before.

**Comment by wesm** [comment]
Is jupyter installed in that environment? You might be picking up pyarrow from a different env

**Comment by mkm177** [comment]
Yeah installing jupyter manually in the environment solved it. 
I also found a number of other versions of pyarrow oldest being version 0.9 on the box. How that version got installed is a mystery, since I have only being playing with arrow for a week, and have always used conda environments for installs.
