### ISSUE TITLE
[CI] test-conda-cpp-valgrind nightly build doesn't finish

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30839]
It seems that the build may be too heavy for Azure?

<https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=18575&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb>

 

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-15354) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-15354](https://issues.apache.org/jira/browse/ARROW-15354). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as outdated, the build works fine nowadays
