### ISSUE TITLE
[Python] `add_column` method missing in pyarrow.RecordBatch

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30915]
`add_column` method missing in `pyarrow.RecordBatch` object (It's available for `Table` though). I think it's a simple, yet important functionality :)

**Reporter**: [Niranda Perera](https://issues.apache.org/jira/browse/ARROW-15434) / @nirandaperera
#### Related issues:
- [[Python] Consolidate shared methods of RecordBatch and Table](https://github.com/apache/arrow/issues/30559) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-15434](https://issues.apache.org/jira/browse/ARROW-15434). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 39506
https://github.com/apache/arrow/pull/39506
