### ISSUE TITLE
parquet cpp - improve examples

### ISSUE THREAD

**Issue by rajeshwar-nu** [apache/arrow#3099]
It would be a great help to have examples of using parquet arrow high-level API for the following 2 cases

- Storing nested data types (storing nested data types is touted as major merit of parquet, so I think this case should be included as an example). Not sure if parquet arrow cpp supports this case as of yet
- Buffered or Batched writes to parquet file. Parquet is meant to be used for large amounts of data. The current examples store all of the data as in arrow data structures, before writing to parquet file. Would be great to include an example of batched writes, which is helpful in most use cases of parquet

**Comment by wesm** [comment]
Can you please open JIRA isuues to propose changes / additions?

**Comment by rajeshwar-nu** [comment]
Created https://issues.apache.org/jira/browse/ARROW-3949
