### ISSUE TITLE
[Release][CI] Add tests using Clang 12, Mac OS 11, Mac OS 12

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31003]
Clang 12 was released in 2021 and is used in Mac OS 12 which is available as an image for GitHub actions:
https://github.com/actions/virtual-environments/tree/main/images.CI/macos/azure-pipelines

Add Mac OS12 and Mac OS 11 to the CI workflows in:
https://github.com/apache/arrow/blob/master/.github/workflows/cpp.yml

**Reporter**: [Benson Muite](https://issues.apache.org/jira/browse/ARROW-15531) / @bkmgit

<sub>**Note**: *This issue was originally created as [ARROW-15531](https://issues.apache.org/jira/browse/ARROW-15531). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Closing as obsolete.
