### ISSUE TITLE
[Python] Cannot installed pyarrow==3.0.0 for macos monterey(12.2)

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31140]
There are currently no wheels available in pypi python3.6 or 3.8 for macos monterey(12.2). This means it's not possible to install versions 3.0.0 of arrow from pypi as the latest uploaded source release is 7.0.0

It would also be useful to upload source releases to pypi...

**Reporter**: [Gideon Dirgahayu](https://issues.apache.org/jira/browse/ARROW-15686)
#### Original Issue Attachments:
- [Screenshot 2022-02-15 at 14.10.14.png](https://issues.apache.org/jira/secure/attachment/13040018/Screenshot+2022-02-15+at+14.10.14.png)
- [WhatsApp Image 2022-02-15 at 14.08.12.jpeg](https://issues.apache.org/jira/secure/attachment/13040019/WhatsApp+Image+2022-02-15+at+14.08.12.jpeg)

<sub>**Note**: *This issue was originally created as [ARROW-15686](https://issues.apache.org/jira/browse/ARROW-15686). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Apologies for the lack of response. In the meantime, there are wheels available for the latest versions for macos 12+, so closing this issue.
