### ISSUE TITLE
How to create an array of timestamps in apache arrow?

### ISSUE THREAD

**Issue by bcc791** [apache/arrow#3118]
I am trying to save an array of timestamps in Apache arrow and subsequently save it to a parquet file. 
Following the apache arrow C++ examples,  first I was trying to create a timestamp builder:

`arrow::TimestampBuilder builder;`

However, I get this error:

`error: no matching function for call to ‘arrow::NumericBuilder<arrow::TimestampType>::NumericBuilder()’`

Note that I was able to successfully create array of other type (`int` and `float`, etc.) without any problems. What is the correct way to create an array of timestamp in arrow?

**Comment by wesm** [comment]
`TimestampBuilder` does not have a nullary constructor because `TimestampType` requires a unit parameter. Try

```
arrow::TimestampBuilder builder(type);
```

where `type` is a `shared_ptr<DataType>` produced by `arrow::timestamp`
