### ISSUE TITLE
[C++] Hash aggregate functions to return first and last value from a group.

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31183]
Follow-up to ARROW-13993, which implemented `hash_one` to select an arbitrary value, as the core engine lack support for ordering. I think `first` and `last` will still be in demand though, based on pandas and sql usage.

It could be done without core changes by using `min_max` on an array of indices. For that reason, maybe it would be better as `hash_\{first,last}_index`, suitable for use with `take`.

**Reporter**: [A. Coady](https://issues.apache.org/jira/browse/ARROW-15735) / @coady
**Assignee**: [Sanjiban Sengupta](https://issues.apache.org/jira/browse/ARROW-15735) / @sanjibansg
#### PRs and other links:
- [GitHub Pull Request #15159](https://github.com/apache/arrow/pull/15159)

<sub>**Note**: *This issue was originally created as [ARROW-15735](https://issues.apache.org/jira/browse/ARROW-15735). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by nealrichardson** [comment]
Done in #34912.
