### ISSUE TITLE
pyarrow.hdfs.connect fails silently

### ISSUE THREAD

**Issue by jimfulton** [apache/arrow#3123]
I'm trying to connect to HDFS using libhdfs and Kerberos.

I have JAVA_HOME and HADOOP_HOME set and `pyarrow.hdfs.connect` sets CLASSPATH correctly.

My connect call looks like: 

```
import pyarrow.hdfs
c = pyarrow.hdfs.connect(host='MYHOST', port=42424, user='ME', 
                         kerb_ticket="/tmp/krb5cc_498970")
```

This doesn't error but the resulting connection can't do anything.  They either error like this: 

```
ArrowIOError: HDFS list directory failed, errno: 255 (Unknown error 255)
```

Or swallow errors (e.g. `exists` returning `False`).

Note that `connect` errors if the host is wrong but doesn't error if the port, user, or kerb_ticket are wrong.  I have no idea how to debug this, because no useful errors.

Note that I *can* connect using the hdfs Python package. (Of course, that doesn't provide the API I need to read Parquet files.).

This is on Centos 7.

Any help would be appreciated greatly.

**Comment by jimfulton** [comment]
Certainly.

**Comment by saurabh02** [comment]
@jimfulton @wesm if I may ask, what was the resolution of this issue? I'm facing the exact same error intermittently, and I'm unable to pin-point the root cause :(

**Comment by nealrichardson** [comment]
See https://issues.apache.org/jira/browse/ARROW-3957 for the followup.

**Comment by saurabh02** [comment]
@nealrichardson thanks for the follow-up! Seems like the cause of the issue is an incorrect port? The default to `pa.hdfs.connect()` is `port=0`. What would be the correct port to use?

**Comment by saurabh02** [comment]
Turns out this was being cause by duplication of computation of "dask.get" tasks on Delayed objects, which was leading to multiple processes attempting to write to the same file.
