### ISSUE TITLE
Cannot run make install for C++ library

### ISSUE THREAD

**Issue by jeffwong-nflx** [apache/arrow#3140]
I am trying to run the R package for arrow, which requires building the cpp files from source. When I follow the instructions in the README, I get an error at the `make install` step.

My dev environment runs:
Ubuntu 16.04
gcc 5.4
cmake 3.5.1
zstd 1.3.2
```
git clone https://github.com/apache/arrow.git
cd arrow/cpp && mkdir release && cd release

# It is important to statically link to boost libraries
cmake .. -DCMAKE_BUILD_TYPE=Release -DARROW_BOOST_USE_SHARED:BOOL=Off
make install
```

Error:

```
CMake Error at /data/arrow/cpp/debug/zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure-RELEASE.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-DCMAKE_BUILD_TYPE=RELEASE' '-DCMAKE_INSTALL_PREFIX=/data/arrow/cpp/debug/zstd_ep-install' '-DCMAKE_INSTALL_LIBDIR=lib' '-DZSTD_BUILD_PROGRAMS=off' '-DZSTD_BUILD_SHARED=off' '-DZSTD_BUILD_STATIC=on' '-DZSTD_MULTITHREAD_SUPPORT=off' '-DCMAKE_CXX_FLAGS= -O3 -DNDEBUG -O3 -DNDEBUG -fPIC' '-DCMAKE_C_FLAGS= -O3 -DNDEBUG -O3 -DNDEBUG -fPIC' 'SOURCE_SUBDIR' 'build/cmake' '-GUnix Makefiles' '/data/arrow/cpp/debug/zstd_ep-prefix/src/zstd_ep'

  See also

    /data/arrow/cpp/debug/zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure-*.log


CMakeFiles/zstd_ep.dir/build.make:106: recipe for target 'zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure' failed
make[2]: *** [zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure] Error 1
CMakeFiles/Makefile2:707: recipe for target 'CMakeFiles/zstd_ep.dir/all' failed
make[1]: *** [CMakeFiles/zstd_ep.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by wesm** [comment]
Can you please show the configure log file as described in the error message

**Comment by jeffwong-nflx** [comment]
`cat /data/arrow/cpp/debug/zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure-out.log`

```CMake Error: The source directory "/data/arrow/cpp/debug/zstd_ep-prefix/src/zstd_ep" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by wesm** [comment]
What version of CMake do you have?

**Comment by jeffwong-nflx** [comment]
My dev environment runs:
Ubuntu 16.04
gcc 5.4
cmake 3.5.1
zstd 1.3.2

**Comment by wesm** [comment]
I renamed the issue since the problem isn't related to R. Please update to CMake >= 3.12 from PPA and see if the problem persists. We've unfortunately gotten a bit lazy about supporting older CMake versions (see https://issues.apache.org/jira/browse/ARROW-3449) and we run very new CMake in all of our CI systems

cc @kszucs @fsaintjacques @xhochy

**Comment by wesm** [comment]
According to https://askubuntu.com/questions/952429/is-there-are-good-ppa-for-cmake-backports/952929#952929 there is no good PPA for CMake but Kitware provides binaries for recent versions. You can also install CMake with conda or pip

**Comment by wesm** [comment]
I see the issue, it's the SOURCE_SUBDIR option

https://gitlab.kitware.com/cmake/cmake/merge_requests/63

I'm not sure how easy this one is to work around on older CMake but having the C++ library fail to build out of the box on Ubuntu 16.04 isn't too great

**Comment by jeffwong-nflx** [comment]
An old cmake was definitely part of the problem. Installing cmake 3.12 got me farther in the make

Now I am seeing this error when building the .so file for R

```
[ 61%] Linking CXX shared library ../../release/libarrow.so
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_system.a(error_code.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/x86_64-linux-gnu/libboost_system.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/arrow/CMakeFiles/arrow_shared.dir/build.make:203: recipe for target 'release/libarrow.so.12.0.0' failed
make[2]: *** [release/libarrow.so.12.0.0] Error 1
CMakeFiles/Makefile2:1319: recipe for target 'src/arrow/CMakeFiles/arrow_shared.dir/all' failed
make[1]: *** [src/arrow/CMakeFiles/arrow_shared.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Line 203 of `src/arrow/CMakeFiles/arrow_shared.dir/build.make` refers to

`@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/data/arrow/cpp/debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Linking CXX shared library ../../release/libarrow.so"`

It suggests recompiling with -fPIC, but I don't know where to put that flag

**Comment by wesm** [comment]
Boost from the Ubuntu package manager is not configured for static linking. Passing `ARROW_BOOST_USE_SHARED=ON` should make this work

@romainfrancois I think it's best to not provide any C++ build instructions in the R README as it may be hard to provide consistent information. On Linux distributions, `ARROW_BOOST_USE_SHARED=OFF` won't work in a lot of cases. We should consolidate C++ build instructions in a single place

**Comment by kou** [comment]
Umm. It's strange that zstd is built without `-DARROW_WITH_ZSTD=ON` because I disabled Zstandard by default for old CMake: https://github.com/apache/arrow/pull/2970

You can't use the system Boost with `-DARROW_BOOST_USE_SHARED=OFF`. If you need to use the option, you need to use `DARROW_BOOST_VENDORED=ON`. It builds Boost for Apache Arrow C++.

**Comment by wesm** [comment]
Ah thanks you are right @kou that ZSTD should be disabled by default for CMake < 3.7, that is strange

**Comment by jeffwong-nflx** [comment]
@wesm thank you, that did the trick

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DARROW_BOOST_USE_SHARED:BOOL=On
make install
```

For any other users trying out arrow, the solution to my build problem was

1) Upgrade cmake to at least 3.12

```
sudo apt remove cmake
cd $HOME
wget https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh

chmod +x cmake-3.12.0-Linux-x86_64.sh
./cmake-3.12.0-Linux-x86_64.sh
sudo ln -s cmake-3.12.0-Linux-x86_64/bin/* /usr/bin
```

2) Get libboost

```
apt-get update && apt-get install libboost-all-dev -y
```

3) Get arrow

```
git clone https://github.com/apache/arrow.git
cd arrow/cpp
mkdir debug
cd debug

cmake .. -DCMAKE_BUILD_TYPE=Release -DARROW_BOOST_USE_SHARED:BOOL=On
make install
```

**Comment by kou** [comment]
> t's strange that zstd is built without `-DARROW_WITH_ZSTD=ON`.

I got it.

`ARROW_WITH_ZSTD` is enabled forcedly when `ARROW_BUILD_TESTS` is `ON` or `ARROW_BUILD_BENCHMAKRS` is on. And `ARROW_BUILD_TESTS` is `ON` by default.

@wesm Can we disable building tests by default? If we enable building tests by default, users who use old CMake need to specify `-DARROW_BUILD_TESTS=OFF`.

**Comment by fsaintjacques** [comment]
Ok, I'll bump the priority of this one. I'll also pickup a UB16.04 image and try to compile from there.

**Comment by wesm** [comment]
See @kou comment -- there was a patch to restore CMake < 3.7 out of the box but there is a conflict with the build flags. Making Gandiva work on older CMake is not as high priority. 

It might make sense to disable the tests by default since we are having even more non-developer users lately

**Comment by wesm** [comment]
I also opened https://issues.apache.org/jira/browse/ARROW-3984 which will help with reports of this nature
