### ISSUE TITLE
[Website] Remove support for triggering GitHub Actions apache/arrow-site website deployment workflow when pushing to master

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31412]
This is a follow up to [ARROW-15694](https://issues.apache.org/jira/browse/ARROW-15694).

Once Apache Infra switches the default Git branch from master to main in apache/arrow-site, we should completely remove support for triggering the deploy.yml CI workflow on a push to master.

This should be straightforward and would involve removing master from the `.github/workflows/deploy.yml` push trigger condition.

**Reporter**: [Kevin Gurney](https://issues.apache.org/jira/browse/ARROW-15988) / @kevingurney

<sub>**Note**: *This issue was originally created as [ARROW-15988](https://issues.apache.org/jira/browse/ARROW-15988). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kevingurney** [comment]
take

**Comment by kevingurney** [comment]
I verified that the `apache/arrow-site` deployment workflows in `.github/workflows/deploy.yml` are already prepared to work with "main" or "master".

See [line 23](https://github.com/apache/arrow-site/blob/032d5d697b1acd7c458c56cfa9cd5b29362553d6/.github/workflows/deploy.yml#L23) and [line 51](https://github.com/apache/arrow-site/blob/032d5d697b1acd7c458c56cfa9cd5b29362553d6/.github/workflows/deploy.yml#L51).

Note that the Jira issue `ARROW-15988`, which is referred to in the comments on these lines, is now being tracked as #31412 (this issue) in GitHub Issues. However, this issue can't be addressed until the default branch has been renamed to "main". Therefore, I'll follow up with a PR to address this as soon as Apache INFRA has renamed the default branch of the `apache/arrow-site` repo to "main".

**Comment by jorisvandenbossche** [comment]
The master->main branch rename is now also done for the apache/arrow-site repo, so you can go forward with this

**Comment by kevingurney** [comment]
Thanks, @jorisvandenbossche. I'll proceed with the changes.

**Comment by kevingurney** [comment]
I don't think I have the permissions to change it, but I think this issue should be part of the `[Website]` component rather than the `[Dev]` component.

**Comment by kou** [comment]
Changed the component.
