### ISSUE TITLE
Reading partitioned datasets using RecordBatchFileReader into R

### ISSUE THREAD

**Issue by jeffwong-nflx** [apache/arrow#3143]
I have a parquet dataset (which originally came from Hive) stored locally in the directory `data/`. It has 4 files in it

```
data/foo1
data/foo2
data/foo3
data/foo4
```

Using pyarrow I can read them via

`pq.read_table("data/foo1").to_pandas()`

I am trying to read them into R using `read_table("data/foo1")`, but I receive this error. 

```
 Error in ipc___RecordBatchFileReader__Open(file) : 
  Invalid: Not an Arrow file 
```

From debugging, I've traced it to this line https://github.com/apache/arrow/blob/d54a154263e1dba5515ebe1a8423a676a01e3951/r/R/RecordBatchReader.R#L112, which then goes to this Rcpp code https://github.com/apache/arrow/blob/d54a154263e1dba5515ebe1a8423a676a01e3951/r/src/recordbatchreader.cpp#L85. It seems that this c++ function is expecting a single "[file like object](https://arrow.apache.org/docs/cpp/classarrow_1_1ipc_1_1_record_batch_file_reader.html#a7e6c66ca32d75bc8d4ee905982d9819e)"; I wonder if the failure is because my data is split into 4 pieces, and the end of the file interface is likely in foo4 

If I pass the whole directory using `read_table("data/")` I will get

```
Error in ipc___RecordBatchFileReader__Open(file) : 
  IOError: Error reading bytes from file: Is a directory 
```

 Is reading a partitioned dataset into R not yet implemented? 

If I write a single file from R, I can read it back in like this example

```
tbl <- tibble::tibble(
  int = 1:10, dbl = as.numeric(1:10),
  lgl = sample(c(TRUE, FALSE, NA), 10, replace = TRUE),
  chr = letters[1:10]
)
tab <- arrow::table(tbl)

tf <- local_tempfile()
write_arrow(tab, tf)
read_table(tf) %>% as.tibble
```

I cannot post the original dataset online, and I don't know what aspect of my data causes the code to break, so I don't quite know how to post a reproducible example. Tips on how to generate a partitioned dataset would be great

**Comment by jeffwong-nflx** [comment]
Will do, thanks

**Comment by wesm** [comment]
Bumping this thread -- I might have missed it but can you open an issue? Thanks!

**Comment by wesm** [comment]
cc @romainfrancois -- can you look into this?
