### ISSUE TITLE
[Packaging] Add support for Coan C/C++ package manager

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31501]
**Reporter**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-16089) / @kou
**Assignee**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-16089) / @kou
#### Subtasks:
- [X] [[CI][Packaging][Conan] Add a job to test minimum build](https://github.com/apache/arrow/issues/31626)
#### Related issues:
- [[CI][Conan] Merge upstream changes](https://github.com/apache/arrow/issues/32135) (relates to)
- [[C++] Add support for SnappyConfig.cmake](https://github.com/apache/arrow/issues/32312) (relates to)
- [[CI][Conan] Enable Brotli](https://github.com/apache/arrow/issues/32389) (relates to)
- [[CI][Conan] Enable JSON](https://github.com/apache/arrow/issues/32631) (relates to)
- [[CI][Conan] Enable utf8proc automatically](https://github.com/apache/arrow/issues/32533) (relates to)
- [[CI][Conan] Enable Flight](https://github.com/apache/arrow/issues/32534) (relates to)
- [[C++] Enable Arrow to share an application's jemalloc instance](https://github.com/apache/arrow/issues/32058) (is related to)
- [[C++][CMake] Use target instead of include_directories(SYSTEM) to add include path](https://github.com/apache/arrow/issues/20188) (is related to)
- [[C++] Use lz4::lz4 for lz4's CMake target name](https://github.com/apache/arrow/issues/31968) (is related to)
- [[C++] Drop support for bundled Thrift < 0.13](https://github.com/apache/arrow/issues/20271) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-16089](https://issues.apache.org/jira/browse/ARROW-16089). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Done.
