### ISSUE TITLE
[GLib] Intoroduce auto formatter

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31545]
**Reporter**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-16137) / @kou

<sub>**Note**: *This issue was originally created as [ARROW-16137](https://issues.apache.org/jira/browse/ARROW-16137). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Issue resolved by pull request 40451
https://github.com/apache/arrow/pull/40451
