### ISSUE TITLE
[Plasma] Remove unused interfaces for interacting with remote machine

### ISSUE THREAD

**Issue by zhijunfu** [apache/arrow#3154]
In legacy ray, interacting with remote plasma stores is done via plasma manager, which is part of ray, and plasma has a few interfaces to support it - namely Fetch() and Wait(). 
Currently the legacy ray code has already been removed, and the new raylet uses object manager to interface with remote machine, and these legacy plasma interfaces are no longer used. I think we could remove these legacy interfaces to cleanup code and avoid confusion.

Thoughts? @pcmoritz @robertnishihara

**Comment by pcmoritz** [comment]
Yes, if you are interested please go ahead and create a PR for this!

**Comment by robertnishihara** [comment]
I think this is a good idea. The `fetch` and `wait` APIs were never really used by other plasma users so they most likely are not the right abstractions.

**Comment by zhijunfu** [comment]
cool. I can take this:)

**Comment by pcmoritz** [comment]
Great, thanks! Can you create a JIRA here: https://issues.apache.org/jira/projects/ARROW?

**Comment by zhijunfu** [comment]
@pcmoritz sure.  https://issues.apache.org/jira/browse/ARROW-4015
