### ISSUE TITLE
[CI][Java][Flight] Test failure on s390x

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31617]
Seems to happen quite reliably on Travis-CI:
https://app.travis-ci.com/github/apache/arrow/builds/249511328

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-16218) / @pitrou
#### PRs and other links:
- [GitHub Pull Request #12913](https://github.com/apache/arrow/pull/12913)
- [GitHub Pull Request #13271](https://github.com/apache/arrow/pull/13271)

<sub>**Note**: *This issue was originally created as [ARROW-16218](https://issues.apache.org/jira/browse/ARROW-16218). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We have no s390x builds anymore, closing as outdated.
