### ISSUE TITLE
[C++] Read nested structs

### ISSUE THREAD

**Issue by zilder** [apache/arrow#3169]
Hi,

I've been trying to read `map <int32, int32>` from parquet file using `RowGroupReader::ReadTable` and got an error:
```
Currently only nesting with Lists is supported.
```
As I understand map is encoded as a list of structs of key-value pairs. Is there currently any way I can read this kind of data layout using `parquet-cpp`?

**Comment by wesm** [comment]
Not yet. The work will be done I would guess sometime next year https://issues.apache.org/jira/browse/ARROW-1644
