### ISSUE TITLE
red-arrow interface for FileOutputStream doesn't respect append=True

### ISSUE THREAD

**Issue by ismurray** [apache/arrow#3175]
It seems that the PR (#1978) that resolved Issue #2018 has not cascaded down through the existing ruby interface.

I've been experimenting with variations of the `write-file.rb` examples, but passing in the append flag as true  (`Arrow::FileOutputStream.open("/tmp/file.arrow", true)`) still results in overwriting the file, and trying the newer interface using truncate and append flags throws `ArgumentError: wrong number of arguments (3 for 2)`.

**Comment by wesm** [comment]
Can you open a JIRA issue for this? I am sure that @kou or @shiro615 will be glad to have a look

**Comment by wesm** [comment]
Thanks
