### ISSUE TITLE
[R] [CI] Upstream gcc12 build to rhub

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31768]
In ARROW-16325 we added a simple build to our crossbow that uses gcc 12 to confirm that building on it is ok. We did the quickest + easiest thing there, but the real solution is to send a PR to rhub that really mimics CRAN's behavior: CRAN runs GCC 12 in the debian-gcc-devel build only; the fedora devel build and debian release and patched are still using GCC 11: https://cran.r-project.org/web/checks/check_flavors.html. 

And then we should use that rhub image in our crossbow CI instead of using our bespoke install-gcc-version setup here.

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-16388) / @jonkeane

<sub>**Note**: *This issue was originally created as [ARROW-16388](https://issues.apache.org/jira/browse/ARROW-16388). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@jonkeane Is this issue still relevant or should it be closed?
