### ISSUE TITLE
[R] [CI] Clean up our snappy-sanitizer skipping behavior

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31766]
We have a number of locations where we skip parquet tests now that snappy is built by default + we use it by default when it is built.

One recent example of needing to do this is https://github.com/apache/arrow/pull/13014

However, skipping tests like this is a little bit of misdirection, since we aren't really skipping these because | when snappy is not available like the helper suggests, just using that helper to _also_ skip when we know we are in a sanitizer environment.

The ultimate answer to this, of course is to upstream the change https://github.com/google/snappy/pull/148 though that's been sitting open for a few months still.

In the meantime, what if we took out these skips and instead used uncompressed parquet for reading and writting in some builds? This way we could make sure that snappy was not running during sanitizer tests, but still have test coverage for these code paths in other runs where we don't need to worry about this sanitizer error in snappy.

https://github.com/apache/arrow/pull/13014#discussion_r859970907 proposed one way to do this in this one case, but we should do it more generally for the other skips that we have had to add.

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-16385) / @jonkeane
#### Related issues:
- [[C++] Upgrade snappy to unreleased version](https://github.com/apache/arrow/issues/32562) (relates to)

<sub>**Note**: *This issue was originally created as [ARROW-16385](https://issues.apache.org/jira/browse/ARROW-16385). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
The patch has been upstreamed and released, closing.
