### ISSUE TITLE
[Tools][Docs] Add instructions on how to collect the produced telemetry data

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31809]
With the ongoing efforts to produce telemetry data in the engine, it might be helpful to collect some notes from the landed PRs about how to collect the telemetry data using the otel-collector and Jaeger running in some containers with docker-compose.

The goal is to make it trivial with these notes to get started with the telemetry data produced by the engine.

**Reporter**: [Matthijs Brobbel](https://issues.apache.org/jira/browse/ARROW-16435) / @mbrobbel
**Assignee**: [Bryce Mecum](https://issues.apache.org/jira/browse/ARROW-16435) / @amoeba

<sub>**Note**: *This issue was originally created as [ARROW-16435](https://issues.apache.org/jira/browse/ARROW-16435). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by amoeba** [comment]
Hey @mbrobbel, I worked up a first draft in https://github.com/apache/arrow/pull/33873 and would love a review by you or others close to this work.
