### ISSUE TITLE
[R] Update read_csv_arrow and open_dataset parse_options, read_options, and convert_options to take lists

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31848]
From a discussion on a PR which documents the encoding argument (<https://github.com/apache/arrow/pull/13038)>

Currently if we want to specify Arrow-specific read options such as encoding, we'd have to do something like this:
```java

df <- read_csv_arrow(tf, read_options = CsvReadOptions$create(encoding = "utf8")) 
```
However, this uses a lower-level API that we don't want to include in the examples for end-users to see.

 

We should update the code inside `read_csv_arrow()` so that the user can specify `read_options` as a list which we then pass through to CsvReadOptions internally, so we could instead call the much more user-friendly code below:
```java

df <- read_csv_arrow(tf, read_options = list(encoding = "utf8")) 
```
We should then add an example of this to the function doc examples.

 

We also should do the same for parse_options and convert_options.

Similarly, we can do:

```r

open_dataset("data.csv", format = "csv", convert_options = CsvConvertOptions$create(null_values = "Not Range", strings_can_be_null = TRUE))%>% collect()
```

but it'd be great to be able to do:

```r

open_dataset("data.csv", format = "csv", convert_options = list(null_values = "Not Range", strings_can_be_null = TRUE))%>% collect()
```

**Reporter**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-16480) / @thisisnic
**Assignee**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-16480) / @thisisnic
#### PRs and other links:
- [GitHub Pull Request #15270](https://github.com/apache/arrow/pull/15270)

<sub>**Note**: *This issue was originally created as [ARROW-16480](https://issues.apache.org/jira/browse/ARROW-16480). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
Yep, should be closed by that PR, so all good to close.
