### ISSUE TITLE
[JS] support for LargeUtf8 type

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31889]
Does JS library support [LargeUtf8](https://github.com/apache/arrow/blob/a8479e9c252482438b6fc2bc0383ac5cf6a09d59/format/Schema.fbs#L165)?

I'm getting error trying to read arrow produced by rust lib:
`Unrecognized type: "LargeUtf8"`

**Reporter**: [Dmytro Sambor](https://issues.apache.org/jira/browse/ARROW-16528)

<sub>**Note**: *This issue was originally created as [ARROW-16528](https://issues.apache.org/jira/browse/ARROW-16528). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
Done in https://github.com/apache/arrow/pull/35780
