### ISSUE TITLE
[Python] Add linting to our cython files

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31905]
The new versions for flake8 do not support linting cython files. Based on [this github issue ](https://github.com/PyCQA/flake8/issues/1482)it was never supposed to be supported.

We updated pre-commit and removed configuration for flake8 linting on cython as part of this ticket: https://issues.apache.org/jira/browse/ARROW-16531

We should find a way of linting our cython files.

**Reporter**: [Raúl Cumplido](https://issues.apache.org/jira/browse/ARROW-16544) / @raulcd
**Assignee**: [Marco Gorelli](https://issues.apache.org/jira/browse/ARROW-16544) / @MarcoGorelli
#### PRs and other links:
- [GitHub Pull Request #14662](https://github.com/apache/arrow/pull/14662)

<sub>**Note**: *This issue was originally created as [ARROW-16544](https://issues.apache.org/jira/browse/ARROW-16544). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
@MarcoGorelli could you comment "take" on this issue so the bot assigns it to you? I can't do it as you have not interacted with this issue :)

**Comment by assignUser** [comment]
Issue resolved by pull request 14662
https://github.com/apache/arrow/pull/14662
