### ISSUE TITLE
[Python]  Multiindex levels order is not preserved after a from_pandas/to_pandas

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31937]
Hello,

Not sure if it's the good place to report this issue but here is what I saw when I tried to convert a multi indexed dataframe (columns) to Table and convert it back to pandas:

 
```python

import pandas as pd
import pyarrow

# pandas version '1.4.1'
# pyarrow version '8.0.0'

df = pd.DataFrame([[100,300, 400], [200,500, 600]], columns=['Toyota', 'Ford', 'Alfa'])
concatenated = pd.concat([df, df*2], axis=1, keys=['foo', 'bar'])
concatenated.columns.names = ['l1', 'l2']

table = pyarrow.Table.from_pandas(concatenated)
from_table_df = table.to_pandas()

from_table_df.columns.levels # == FrozenList([['bar', 'foo'], ['Alfa', 'Ford', 'Toyota']])
concatenated.columns.levels # == FrozenList([['foo', 'bar'], ['Toyota', 'Ford', 'Alfa']])


```
the order of columns levels is not preserved. 

 

**Reporter**: [Fabien Aulaire](https://issues.apache.org/jira/browse/ARROW-16580)

<sub>**Note**: *This issue was originally created as [ARROW-16580](https://issues.apache.org/jira/browse/ARROW-16580). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
> In theory, we could add more information about the MultiIndex levels in the pandas metadata, but I am not sure we should do that in this case (the levels can in principle be a large array, and we still need to serialize/deserialize it to some string format).

Given what I said above, I think we can currently consider this out of scope to preserve this order. And therefore closing this issue.
