### ISSUE TITLE
Can arrow support graph data structure by developing plugin?

### ISSUE THREAD

**Issue by theseusyang** [apache/arrow#3195]
Hi All,

Can arrow support graph data structure by developing plugin? like neo4j to store some graph datasets.

**Comment by trxcllnt** [comment]
Hi @theseusyang, we discussed this [on the mailing list](http://mail-archives.apache.org/mod_mbox/arrow-dev/201806.mbox/%3CCAJPUwMA-U34y6WgkfNNhLyarF5O%3DWXKVeDY7rw2yhycMcsEwXA%40mail.gmail.com%3E) briefly last summer, but I've been too busy to pick it back up again. I would also like to eventually see a native Graph Message type in Arrow, especially if we can align with [native format](https://github.com/trxcllnt/arrow/blob/78f6b6c6a5b9e4e7bf96f5bbc4dfed7528b1cca7/format/GraphSchema_Triples_Quads.fbs) supported by the [nvGraph/cudf](https://github.com/rapidsai/cudf) project.

**Comment by lmeyerov** [comment]
In addition, the neo4j folks have expressed interest here. For an intuition, I believe they have been also doing things like neo4j<>spark (graphx?), which makes this even more natural. 

There seems to be questions around physical data rep. There are different graph formats optimized for different uses: CSR, triples, property graphs, etc. One discussion was supporting several, and compute envs can provide optimized transforms between them. (Graphistry happens to use property tables and edge lists.)

**Comment by wesm** [comment]
Are there any JIRA issues about this?
