### ISSUE TITLE
[Format] Add RLE definitions to FlatBuffers

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32115]
**Reporter**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-16782) / @zagto
#### PRs and other links:
- [GitHub Pull Request #14176](https://github.com/apache/arrow/pull/14176)

<sub>**Note**: *This issue was originally created as [ARROW-16782](https://issues.apache.org/jira/browse/ARROW-16782). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
Closing this manually as https://github.com/apache/arrow/pull/14176 was merged with a JIRA reference.
