### ISSUE TITLE
[CI][Python] Sanitize macOS wheel build steps

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32144]
The wheel build task in `dev/tasks/python-wheels/github.osx.arm64.yml` uses a hodgepodge of random `arch` calls that currently work but do not have a rational justification.

Someone should take a deep look at these and rationalize them: normally, it should be enough to create each Python environment with the right architecture.

Also, do note that the self-hosted M1 runner actually runs in x86 mode by default, so it's necessary to issue `arch -arm64` to select ARM64 mode.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-16814) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-16814](https://issues.apache.org/jira/browse/ARROW-16814). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
This issue doesn't apply anymore, closing.
