### ISSUE TITLE
./bootstrap.sh fails on Windows when ARROW_BOOST_VENDORED flag is set

### ISSUE THREAD

**Issue by BACtaki** [apache/arrow#3216]
Need to add a check in arrow/cpp/cmake_modules/ThirdpartyToolchain.cmake to use .\bootstrap.bat (instead of ./bootstrap.sh) to be able to use vendored boost libs when compiling arrow on Windows. I would be more than happy to submit a patch with this fix.

**Comment by wesm** [comment]
There's an issue open about this, please feel free to submit a patch: https://issues.apache.org/jira/browse/ARROW-1324
