### ISSUE TITLE
[C++] Implement cumulative product, max, and min compute functions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32190]
Other libraries/languages (pandas, R, numpy) have cumprod, cummax and cummin functions that useful to add to Arrow, similar to the now existing cumulative sum function.

**Reporter**: [Jabari Booker](https://issues.apache.org/jira/browse/ARROW-16865) / @JabariBooker
#### Related issues:
- [[C++] Implement cumulative sum compute function](https://github.com/apache/arrow/issues/29183) (is related to)
#### PRs and other links:
- [GitHub Pull Request #13412](https://github.com/apache/arrow/pull/13412)

<sub>**Note**: *This issue was originally created as [ARROW-16865](https://issues.apache.org/jira/browse/ARROW-16865). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by frosk1** [comment]
Hey, is this coming?

**Comment by js8544** [comment]
Hi @frosk1 are you working on this? I plan to implement cumprod, cummax and cummin if no one else is working on it.

**Comment by frosk1** [comment]
Hey @js8544 no unfortunately I do not have time atm. Would be great if you can work on that one.

**Comment by js8544** [comment]
take

**Comment by js8544** [comment]
I noticed that the functions cumprod, cummin and cummax would require the same option as `CumulativeSumOptions` (min and max won't need to `check_overflow` but I plan to remove it in #35790). 

I want to avoid having four different option types with identical structure, so I intend to refactor `CumulativeSumOptions` to `CumulativeOptions` and reuse it for all cumulative functions.

The current definition is
```cpp
/// \brief Options for cumulative sum function
class ARROW_EXPORT CumulativeSumOptions : public FunctionOptions {
 public:
  explicit CumulativeSumOptions(double start = 0, bool skip_nulls = false,
                                bool check_overflow = false);
  explicit CumulativeSumOptions(std::shared_ptr<Scalar> start, bool skip_nulls = false,
                                bool check_overflow = false);
  static constexpr char const kTypeName[] = "CumulativeSumOptions";
  static CumulativeSumOptions Defaults() { return CumulativeSumOptions(); }

  /// Optional starting value for cumulative operation computation
  std::shared_ptr<Scalar> start;

  /// If true, nulls in the input are ignored and produce a corresponding null output.
  /// When false, the first null encountered is propagated through the remaining output.
  bool skip_nulls = false;

  /// When true, returns an Invalid Status when overflow is detected
  bool check_overflow = false;
};
```

I plan to do this:
```cpp
/// \brief Options for cumulative functions
class ARROW_EXPORT CumulativeOptions : public FunctionOptions {
  // ... (same as above)
};

using CumulativeSumOptions = CumulativeOptions; // for backward compatibility
```

I checked that with this change all compute tests still passed, both in cpp and python. But I want to make sure there are no better ways to solve this. Do you consider this as the best approach? cc @pitrou @westonpace

**Comment by pitrou** [comment]
@js8544 This seems like a good approach to me.

**Comment by westonpace** [comment]
I agree with this approach.  We have done something very similar with aggregate functions and `ScalarAggregateOptions`: https://github.com/apache/arrow/blob/8b2ab4d8200fdd414b85d531f1cef4b58a3ce351/cpp/src/arrow/compute/api_aggregate.h#L45-L59

**Comment by westonpace** [comment]
CC @icexelloss / @rtpsw / @ildipo may be interested in these functions when available.  They are classic window functions and so could be useful in the work that is being done to add window function support to Acero.

**Comment by js8544** [comment]
> CC @icexelloss / @rtpsw / @ildipo may be interested in these functions when available. They are classic window functions and so could be useful in the work that is being done to add window function support to Acero.

Regarding window functions. I also implemented a `pairwise_diff` function (https://github.com/apache/arrow/pull/35787) you guys may also want to take a look. `pairwise` functions would corresponds to `LAG`/`LEAD` window functions in SQL.

I also plan to implement a series of `rolling_*` functions that computes over a fixed length sliding window soon, which corresponds to the window option `ROWS BETWEEN n PRECEDING AND CURRENT ROW` in sql.
