### ISSUE TITLE
[C++] GcsFileSystem::Make should return Result

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32206]
For consistency with S3FileSystem and others. See discussion at https://github.com/apache/arrow/pull/13404#discussion_r901799543

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-16884) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-16884](https://issues.apache.org/jira/browse/ARROW-16884). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by trifleneurotic** [comment]
I am currently working on this _good-first-issue_ on my fork, although I know it is an older issue. If you have any additional information or context regarding this issue, please feel free to comment. Thank you!

**Comment by trifleneurotic** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 44503
https://github.com/apache/arrow/pull/44503
