### ISSUE TITLE
[C#] Add decompression support for Record Batches

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32240]
C# Implementation does not support reading batches written in other implementations of Arrow when the compression is specified in IPC Write options.

e.g. Reading this batch from pyarrow in C# will fail:

pyarrow.ipc.RecordStreamBatchWriter(sink, schema, options=pyarrow,ipcWriteOptions(compression="lz4"))

 

This is to support decompression (lz4 & zstd) in the C# implementation.

**Reporter**: [Rishabh Rana](https://issues.apache.org/jira/browse/ARROW-16921) / @rishabh-rana
#### Related issues:
- [[C#] Support compression in IPC format](https://github.com/apache/arrow/issues/32370) (is duplicated by)

<sub>**Note**: *This issue was originally created as [ARROW-16921](https://issues.apache.org/jira/browse/ARROW-16921). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by adamreeve** [comment]
I went ahead and tidied up my code and used the reflection approach suggested by @westonpace to implement a default compression provider. I've created a PR for this at #33603

I'm still not sure the reflection approach is the best way to go, it's pretty verbose and not very discoverable by users. I've included some comments in that PR about alternative approaches but maybe it's better to discuss them here rather than on the PR, so I'll copy them below:

> An alternative approach that could be considered instead of reflection is to use these extra dependencies as build time dependencies but not make them dependencies of the NuGet package. I tested this out in https://github.com/adamreeve/arrow/commit/4544afde6fef12337c7b188cc497da0bc1bf829d and it seems to work reasonably well too but required bumping the version of `System.Runtime.CompilerServices.Unsafe` under the `netstandard2.0` and `netcoreapp3.1` targets. This reduces all the reflection boilerplate but seems pretty hacky as now Apache.Arrow.dll depends on these extra dlls and we rely on the dotnet runtime behaviour of not trying to load them until they're used. So I think the reflection approach is better.
> 
> Another alternative would be to move decompression support into a separate NuGet package (eg.  `Apache.Arrow.Compression`) that depends on `Apache.Arrow` and has an implementation of `ICompressionProvider` that users can pass in to the `ArrowFileReader` constructor, or maybe has a way to register itself with the `Apache.Arrow` package so it only needs to be configured once. That would seem cleaner to me but I'm not sure how much work it would be to set up a whole new package.

PS. It wasn't very obvious that this issue had been migrated to GitHub, maybe comments should be added to open Jira issues to explain that comments are disabled and point to the migrated issue on GitHub?

**Comment by westonpace** [comment]
> Another alternative would be to move decompression support into a separate NuGet package (eg. Apache.Arrow.Compression) that depends on Apache.Arrow and has an implementation of ICompressionProvider that users can pass in to the ArrowFileReader constructor, or maybe has a way to register itself with the Apache.Arrow package so it only needs to be configured once. That would seem cleaner to me but I'm not sure how much work it would be to set up a whole new package.

This sounds like a good approach to me.  I think having a standard package that just picks some common compression libs is going to be sufficient for 80% of use cases.

**Comment by adamreeve** [comment]
Cool okay, @lidavidm mentioned on the PR that the Java library works that way too so I'll take a look at the API used there to see if I can make the dotnet API consistent with the way the Java API works, and pare the PR back to remove the reflection based implementation for now. It might make sense to add the new package in a separate PR.

**Comment by westonpace** [comment]
> It might make sense to add the new package in a separate PR.

That seems reasonable to me.
