### ISSUE TITLE
[R] Build linux binaries on older image (like manylinux2014)

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32292]
ARROW-16752 observed that even with newer compilers installed on centos 7, you can't use binaries built on ubuntu 18.04 because ubuntu 18.04 has glibc 2.27 but centos 7 only has 2.17. But if we built the binaries on centos 7 with devtoolset-7 or 8 or something, all features could compile and we'd work with older glibc. 

Things built against older glibc are guaranteed to work with newer versions, and you can't just upgrade glibc because it would break the system. So for maximum compatibility, build with the oldest glibc. This strategy is like how they python manylinux standards work (IIUC). 

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-16976) / @nealrichardson
#### Related issues:
- [[R][Packaging] Build binaries with devtoolset 8 on CentOS 7](https://github.com/apache/arrow/issues/32842) (is fixed by)

<sub>**Note**: *This issue was originally created as [ARROW-16976](https://issues.apache.org/jira/browse/ARROW-16976). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
I tried to use CentOS 7 binaries with Ubuntu 18.04 in https://github.com/apache/arrow/pull/34020#issuecomment-1416603703 but we can't do it:

https://github.com/ursacomputing/crossbow/actions/runs/4089420508/jobs/7052165676#step:12:265

```text
 Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/00LOCK-arrow/00new/arrow/libs/arrow.so':
  /usr/local/lib/R/site-library/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: _ZNK5arrow8DataType18ComputeFingerprintB5cxx11Ev
```

Because CentOS 7 + devtoolset doesn't use cxx11 ABI but Ubuntu 18.04 requires cxx11 ABI.

Can we close this?
