### ISSUE TITLE
[C++][Parquet][Python] Add Parquet ColumnIndex and OffsetIndex support

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32305]
As documented here: <https://github.com/apache/parquet-format/blob/master/PageIndex.md>

The parquet format supports indexing of pages within a column chunk. Beyond what is accomplished by rowgroup statistics, this can further accelerate scanning.

As far as I am able to tell, Arrow does not currently support these indices (I see no references to `{}offset_index_offset{`}, `{}column_index_offset{`}, etc). Are there plans to add support, either in C++ or pyarrow?

**Reporter**: [ogego](https://issues.apache.org/jira/browse/ARROW-16991)

<sub>**Note**: *This issue was originally created as [ARROW-16991](https://issues.apache.org/jira/browse/ARROW-16991). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by wjones127** [comment]
Closing this in favor of tracking in https://github.com/apache/arrow/issues/26168
