### ISSUE TITLE
[Format][C++] Support RLE in IPC format

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32338]
**Reporter**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-17027) / @zagto
#### PRs and other links:
- [GitHub Pull Request #14340](https://github.com/apache/arrow/pull/14340)

<sub>**Note**: *This issue was originally created as [ARROW-17027](https://issues.apache.org/jira/browse/ARROW-17027). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by felipecrv** [comment]
take
