### ISSUE TITLE
[Python] Feather test failing on s390x travis CI job

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32342]
See https://app.travis-ci.com/github/apache/arrow/jobs/576170885#L9607 for the failing test.

**Reporter**: [Phillip Cloud](https://issues.apache.org/jira/browse/ARROW-17031) / @cpcloud

<sub>**Note**: *This issue was originally created as [ARROW-17031](https://issues.apache.org/jira/browse/ARROW-17031). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by AlenkaF** [comment]
Closing this as it is an old failure on Travis CI therefore not relevant anymore.
