### ISSUE TITLE
[Docs] Enable dark mode on documentation site

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32451]
pydata-sphinx-theme adds dark mode in version 0.9.0. We will need to adapt our logo ([see docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html?highlight=dark#different-logos-for-light-and-dark-mode)). There are also some places in the docs where we may need to adjust additional CSS. See attached screenshot.

**Reporter**: [Will Jones](https://issues.apache.org/jira/browse/ARROW-17152) / @wjones127
#### Related issues:
- [[Docs] Pin pydata-sphinx-theme to 0.8 to avoid dark mode](https://github.com/apache/arrow/issues/32450) (relates to)
#### Original Issue Attachments:
- [Screen Shot 2022-07-20 at 3.10.51 PM.png](https://issues.apache.org/jira/secure/attachment/13047045/Screen+Shot+2022-07-20+at+3.10.51+PM.png)
- [Screen Shot 2022-07-20 at 3.12.18 PM.png](https://issues.apache.org/jira/secure/attachment/13047044/Screen+Shot+2022-07-20+at+3.12.18+PM.png)

<sub>**Note**: *This issue was originally created as [ARROW-17152](https://issues.apache.org/jira/browse/ARROW-17152). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by AlenkaF** [comment]
This issue will be fixed with https://github.com/apache/arrow/pull/36591 where the theme is being updated.
