### ISSUE TITLE
[C++] Extend hash-join unit tests to cover both empty and length=0 batches

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32514]
Follow-up to ARROW-15938 so that we can merge ARROW-15938 for the RC.  This just adds the unit test requested in the review.

**Reporter**: [Weston Pace](https://issues.apache.org/jira/browse/ARROW-17226) / @westonpace

<sub>**Note**: *This issue was originally created as [ARROW-17226](https://issues.apache.org/jira/browse/ARROW-17226). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
@westonpace is this still required or can be closed? As I can see the reference ticket was delivered already.

**Comment by westonpace** [comment]
I believe this can be closed.
