### ISSUE TITLE
[C++][Parquet] Add JSON canonical extension type

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32538]
As a BigQuery developer, I would like the Arrow libraries to support the JSON logical Type. This would enable us to use the JSON type in the Arrow format of our ReadAPI. This would also enable us to use the JSON type to export data from BigQuery to Parquet.

**Reporter**: [Pradeep Gollakota](https://issues.apache.org/jira/browse/ARROW-17255)
**Watchers**: [Rok Mihevc](https://issues.apache.org/jira/browse/ARROW-17255) / @rok
#### Related issues:
- [[C++] JSON kernels](https://github.com/apache/arrow/issues/32548) (is related to)
#### PRs and other links:
- [GitHub Pull Request #13901](https://github.com/apache/arrow/pull/13901)

<sub>**Note**: *This issue was originally created as [ARROW-17255](https://issues.apache.org/jira/browse/ARROW-17255). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Issue resolved by pull request 13901
https://github.com/apache/arrow/pull/13901
