### ISSUE TITLE
[C++] Add type ID, Type and Array classes for RLE

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32543]
Based on top of ARROW-17258

Mostly picking these parts from ARROW-16772 and ARROW-16781 to create an easier order to merge things

**Reporter**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-17261) / @zagto
#### PRs and other links:
- [GitHub Pull Request #13754](https://github.com/apache/arrow/pull/13754)

<sub>**Note**: *This issue was originally created as [ARROW-17261](https://issues.apache.org/jira/browse/ARROW-17261). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by felipecrv** [comment]
take
