### ISSUE TITLE
[C++] Upgrade snappy to unreleased version

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32562]
https://github.com/google/snappy/pull/148 was finally merged, so if we upgrade to the current HEAD, we will resolve the UBSan issues we've observed and can remove some test skips (in R at least). And I see https://github.com/google/snappy/commit/8dd58a519f79f0742d4c68fbccb2aed2ddb651e8 as well, which may let us remove the `ARROW_SNAPPY_OLD_BUILD_VERSION` workaround too.

We could wait for an official snappy release, but they seem infrequent. Last one was over a year ago and there have been 2 sanitizer fixes we've upstreamed since then.

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-17283) / @nealrichardson
#### Related issues:
- [[R] [CI] Clean up our snappy-sanitizer skipping behavior](https://github.com/apache/arrow/issues/31766) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-17283](https://issues.apache.org/jira/browse/ARROW-17283). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
the patch was released in 1.1.10
