### ISSUE TITLE
[C++] Simplify IPC writer for dense unions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32613]
In ARROW-10580 we fixed the Arrow C++ implementation so that dense union offsets are always (non-strictly) monotonic for a given child, as mandated by the spec.

The IPC writer implementation, however, still assumes that dense union offsets may be in any order:
https://github.com/apache/arrow/blob/5719576c611929dd790f7f8a1ae3169a8f96f7f1/cpp/src/arrow/ipc/writer.cc#L476-L485

This can probably be simplified, making it slightly less costly to emit a sliced union array.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-17339) / @pitrou
#### Related issues:
- [[C++] When Validating, ensure DenseUnionArray offsets are increasing](https://github.com/apache/arrow/issues/26543) (relates to)

<sub>**Note**: *This issue was originally created as [ARROW-17339](https://issues.apache.org/jira/browse/ARROW-17339). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by rtadepalli** [comment]
Hi, I'd like to work on this if it is still available. Thanks.
