### ISSUE TITLE
[R] `lubridate::as_datetime()` in dplyr query should be able to handle time in sub seconds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32694]
Since the current unit is fixed to "s", an error will occur if a time containing sub-seconds is given.
```r

"1970-01-01T00:00:59.123456789" |>
  arrow::arrow_table(x = _) |>
  dplyr::mutate(x = lubridate::as_datetime(x, tz = "UTC")) |>
  dplyr::collect()
#> Error in `dplyr::collect()`:
#> ! Invalid: Failed to parse string: '1970-01-01T00:00:59.123456789' as a scalar of type timestamp[s]
```
I thought that nanoseconds should be used, but it should be noted that POSIXct is currently supposed to be converted to microseconds, as shown in ARROW-17424.
 
 
 

 

**Reporter**: [SHIMA Tatsuya](https://issues.apache.org/jira/browse/ARROW-17425) / @eitsupi
**Assignee**: [SHIMA Tatsuya](https://issues.apache.org/jira/browse/ARROW-17425) / @eitsupi
#### Related issues:
- [[R] Convert a column as a sub-second timestamp from CSV file with the `T` col type option](https://github.com/apache/arrow/issues/31061) (relates to)
- [[R] Microsecond is not sufficient unit for POSIXct](https://github.com/apache/arrow/issues/32693) (relates to)
#### PRs and other links:
- [GitHub Pull Request #13890](https://github.com/apache/arrow/pull/13890)

<sub>**Note**: *This issue was originally created as [ARROW-17425](https://issues.apache.org/jira/browse/ARROW-17425). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
Thanks for pointing this out @eitsupi I am closing this manually as was merged in the interim of the migration! We have updated the merge scripts to avoid this in the future for happening.
