### ISSUE TITLE
[R] conda r-arrow Linux package has 

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32825]
I need to read parquet files in R using a conda environment. Works great on Windows, but on Linux, r-arrow comes without some core features. If this is expected, it would be great to flag it in the docs, at least for me, reading through <https://arrow.apache.org/docs/r/articles/install.html#method-1a---binary-r-package-containing-libarrow-binary-via-rspmconda> gives the impression that I need not worry about features (though pinning r-arrow to 8.0.1 gives a complete version lacking only lzo-support).

After creating an environment based on the attached specification:

`{}(test-r-arrow) x@x/test-r-arrow$ R{`}`{}R version 4.1.3 (2022-03-10) – "One Push-Up"{`}
`Copyright (C) 2022 The R Foundation for Statistical Computing`
`Platform: x86_64-conda-linux-gnu (64-bit)`

 

`R is free software and comes with ABSOLUTELY NO WARRANTY.`
`You are welcome to redistribute it under certain conditions.`
`{}Type 'license()' or 'licence()' for distribution details.{`}{\{  }}

 

`Natural language support but running in an English locale`

 

`R is a collaborative project with many contributors.`
`Type 'contributors()' for more information and`
`'citation()' on how to cite R or R packages in publications.`

 

`Type 'demo()' for some demos, 'help()' for on-line help, or`
`'help.start()' for an HTML browser interface to help.`
`Type 'q()' to quit R.`

 

`> library(arrow)`
`Some features are not enabled in this build of Arrow. Run `arrow_info()` for more information.`

`Attaching package: ‘arrow’`

`The following object is masked from ‘package:utils’:``    timestamp`

 

`> arrow_info()`
`Arrow package version: 9.0.0`

`Capabilities:`
`               `
`dataset   FALSE`
`substrait FALSE`
`parquet   FALSE`
`json      FALSE`
`s3        FALSE`
`gcs       FALSE`
`utf8proc   TRUE`
`re2        TRUE`
`snappy     TRUE`
`gzip       TRUE`
`brotli     TRUE`
`zstd       TRUE`
`lz4        TRUE`
`lz4_frame  TRUE`
`lzo       FALSE`
`bz2        TRUE`
`jemalloc   TRUE`
`mimalloc   TRUE`

`To reinstall with more optional capabilities enabled, see`
`   [https://arrow.apache.org/docs/r/articles/install.html]`

 

`Memory:`
`                  `
`Allocator jemalloc`
`Current    0 bytes`
`{}Max        0 bytes{`}`{}Runtime:{`}
`                        `
`SIMD Level          avx2`
`{}Detected SIMD Level avx2{`}`{}Build:{`}
`                                                             `
`C++ Library Version                                     9.0.0`
`C++ Compiler                                              GNU`
`C++ Compiler Version                                   10.4.0`
`Git ID               13127e16b858dda3b8299a1e435c3c0ba5934fdc`

 

Creating the same environment on Windows produces:

 

`> arrow_info()`
`Arrow package version: 9.0.0`

`Capabilities:`

`dataset    TRUE`
`substrait FALSE`
`parquet    TRUE`
`json       TRUE`
`s3         TRUE`
`gcs       FALSE`
`utf8proc   TRUE`
`re2        TRUE`
`snappy     TRUE`
`gzip       TRUE`
`brotli     TRUE`
`zstd       TRUE`
`lz4        TRUE`
`lz4_frame  TRUE`
`lzo       FALSE`
`bz2        TRUE`
`jemalloc  FALSE`
`mimalloc   TRUE`

`Arrow options():`

`arrow.use_threads FALSE`

`{}Memory:{`}`{}Allocator mimalloc{`}
`Current    0 bytes`
`Max        0 bytes`

`Runtime:`

`SIMD Level          avx2`
`Detected SIMD Level avx2`

`Build:`

`C++ Library Version          9.0.0`
`C++ Compiler                  MSVC`
`C++ Compiler Version 19.16.27048.0`

 

**Environment**: Ubuntu 20.04

conda                     4.13.0           py39hf3d152e_1    conda-forge

Environment created based on attached script:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
abseil-cpp                20211102.0           h27087fc_1    conda-forge
arrow-cpp                 9.0.0           py310h893e394_0_cpu    conda-forge
aws-c-cal                 0.5.11               h95a6274_0    conda-forge
aws-c-common              0.6.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
aws-c-io                  0.10.5               hfb6a706_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1013    conda-forge
curl                      7.83.1               h7bff187_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc_impl_linux-64         12.1.0              hea43390_16    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
gfortran_impl_linux-64    12.1.0              h1db8e46_16    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpc-cpp                  1.46.3               hbd84cd8_3    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gxx_impl_linux-64         12.1.0              hea43390_16    conda-forge
harfbuzz                  5.1.0                hf9f4e7c_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     12.1.0              h1ec3361_16    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libgoogle-cloud           1.40.2               hefc27d0_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_2    conda-forge
libpng                    1.6.37               h753d276_4    conda-forge
libprotobuf               3.20.1               h6239696_1    conda-forge
libsanitizer              12.1.0              ha89aaad_16    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-devel_linux-64  12.1.0              h1ec3361_16    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libthrift                 0.16.0               h519c5ea_1    conda-forge
libtiff                   4.4.0                h0e0dad5_3    conda-forge
libutf8proc               2.7.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.2          py310h53a5b5f_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
orc                       1.7.5                h6c59b99_0    conda-forge
pango                     1.50.9               hc4f8a73_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                hc3806b6_1    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
r-arrow                   9.0.0             r41h27087fc_0    conda-forge
r-assertthat              0.2.1             r41hc72bb7e_2    conda-forge
r-base                    4.1.3                ha8c3e7c_2    conda-forge
r-bit                     4.0.4             r41hcfec24a_0    conda-forge
r-bit64                   4.0.5             r41hcfec24a_0    conda-forge
r-cli                     3.3.0             r41h7525677_0    conda-forge
r-ellipsis                0.3.2             r41hcfec24a_0    conda-forge
r-glue                    1.6.2             r41h06615bd_0    conda-forge
r-magrittr                2.0.3             r41h06615bd_0    conda-forge
r-purrr                   0.3.4             r41hcfec24a_1    conda-forge
r-r6                      2.5.1             r41hc72bb7e_0    conda-forge
r-rlang                   1.0.4             r41h7525677_0    conda-forge
r-tidyselect              1.1.2             r41hc72bb7e_0    conda-forge
r-vctrs                   0.4.1             r41h7525677_0    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
s2n                       1.0.10               h9b69904_0    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

**Reporter**: [Hans-Martin von Gaudecker](https://issues.apache.org/jira/browse/ARROW-17576)
#### Original Issue Attachments:
- [environment.yml](https://issues.apache.org/jira/secure/attachment/13048795/environment.yml)

<sub>**Note**: *This issue was originally created as [ARROW-17576](https://issues.apache.org/jira/browse/ARROW-17576). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Probably an issue with the feedstock that was fixed upstream. The current version (which is still 10.0.1) has all the features:
```
Arrow package version: 10.0.1

Capabilities:
               
dataset    TRUE
substrait  TRUE
parquet    TRUE
json       TRUE
s3         TRUE
gcs        TRUE
utf8proc   TRUE
re2        TRUE
snappy     TRUE
gzip       TRUE
brotli     TRUE
zstd       TRUE
lz4        TRUE
lz4_frame  TRUE
lzo       FALSE
bz2        TRUE
jemalloc   TRUE
mimalloc   TRUE
```
