### ISSUE TITLE
[Python][Packaging] Move Windows wheel build to more recent Visual Studio

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32840]
We recently decided to remove support for Visual Studio 2017:
https://lists.apache.org/thread/rcqkx19gpfjlkyvrhxfsrckktrdrzm2p

The Docker image for building Windows wheels should then be updated, for example to Visual Studio 2019:
https://github.com/apache/arrow/blob/d3d6371e1e7627d0c5c289acb8eee38ab0cea533/ci/docker/python-wheel-windows-vs2017.dockerfile#L21-L23

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-17592) / @pitrou
**Assignee**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-17592) / @pitrou
#### PRs and other links:
- [GitHub Pull Request #14021](https://github.com/apache/arrow/pull/14021)

<sub>**Note**: *This issue was originally created as [ARROW-17592](https://issues.apache.org/jira/browse/ARROW-17592). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Done by #39622/#39621.
