### ISSUE TITLE
[C++][Java][FlightRPC] Get rid of FlightTestUtil.getStartedServer etc.

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32954]
Anything expecting to bind to a random port in CI is an antipattern and makes tests flaky. All tests should bind to port 0 and let the OS assign a port.

**Reporter**: [David Li](https://issues.apache.org/jira/browse/ARROW-17718) / @lidavidm

<sub>**Note**: *This issue was originally created as [ARROW-17718](https://issues.apache.org/jira/browse/ARROW-17718). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by lidavidm** [comment]
@rtadepalli weirdly enough, I think I can only assign you to this issue if you comment 'take' or otherwise comment here

**Comment by ramasai1** [comment]
take

**Comment by rtadepalli** [comment]
take

**Comment by rtadepalli** [comment]
@lidavidm could you please unassign @ramasai1. I accidentally used my other Github account..
