### ISSUE TITLE
[CI][C++] Enable Flight and Flight SQL on ubuntu cpp 18.04 builds

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32959]
Currently Dockerfiles for ubuntu 18.04 cpp builds don't have Flight and / or Flight SQL enabled. This ticket is to add support for it.

**Reporter**: [Raúl Cumplido](https://issues.apache.org/jira/browse/ARROW-17723) / @raulcd
#### Related issues:
- [[CI] Enable Flight and Flight SQL on ubuntu cpp 20.04 builds](https://github.com/apache/arrow/issues/32327) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-17723](https://issues.apache.org/jira/browse/ARROW-17723). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by lidavidm** [comment]
We dropped 18.04 support.
