### ISSUE TITLE
[CI][C++][Python] s390x builds time out

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32951]
The s390x builds currently time out on Travis-CI while compiling Arrow C++.
The s390x execution resources at Travis-CI are probably too weak for compiling Arrow...

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-17715) / @pitrou
**Assignee**: [Kazuaki Ishizaki](https://issues.apache.org/jira/browse/ARROW-17715) / @kiszk
#### PRs and other links:
- [GitHub Pull Request #14138](https://github.com/apache/arrow/pull/14138)
- [GitHub Pull Request #14169](https://github.com/apache/arrow/pull/14169)
- [GitHub Pull Request #15266](https://github.com/apache/arrow/pull/15266)

<sub>**Note**: *This issue was originally created as [ARROW-17715](https://issues.apache.org/jira/browse/ARROW-17715). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
There are no s390x builds anymore, closing as outdated
