### ISSUE TITLE
Writing StructArrays

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#3296]
Hi there,

Im trying to write a map type into parquet using a StructArray, but there doesnt seem to be an obvious way to do it. Im not sure what the roadmap is for writing nested structures into parquet - but Id love to help!

Dhruv

**Comment by wesm** [comment]
Let's discuss on the mailing list? 

Some related JIRAs

* https://issues.apache.org/jira/browse/ARROW-1644
* https://issues.apache.org/jira/browse/ARROW-1207
