### ISSUE TITLE
[R] DuckDB test is failing (again) with new duckdb release

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33033]
It looks like the fix that I thought would work in DuckDB did not, in fact fix the error! The previous ticket, ARROW-17643, just skipped the test until the new release of duckdb (which just happened).

**Reporter**: [Dewey Dunnington](https://issues.apache.org/jira/browse/ARROW-17809) / @paleolimbot
**Assignee**: [Dewey Dunnington](https://issues.apache.org/jira/browse/ARROW-17809) / @paleolimbot
#### PRs and other links:
- [GitHub Pull Request #14195](https://github.com/apache/arrow/pull/14195)
- [GitHub Pull Request #14209](https://github.com/apache/arrow/pull/14209)

<sub>**Note**: *This issue was originally created as [ARROW-17809](https://issues.apache.org/jira/browse/ARROW-17809). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
I'm gonna assume this was fixed a while ago in that linked PR; feel free to close if this is not correct
