### ISSUE TITLE
[R][CI] Remove ubuntu-18.04 from nixlibs & prebuilt binaries

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33091]
The new dts compiled centos-7 binaries ([ARROW-17594]) should be able to replace the ubuntu-18.04 binaries.

**Reporter**: [Jacob Wujciak](https://issues.apache.org/jira/browse/ARROW-17876) / @assignUser

<sub>**Note**: *This issue was originally created as [ARROW-17876](https://issues.apache.org/jira/browse/ARROW-17876). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
We can't use the `centos-7` binaries on Ubuntu 20.04 because the `centos-7` binaries uses OpenSSL 1.0 and Ubuntu 20.04 uses OpenSSL 1.1. OpenSSL 1.0 and 1.1 are incompatible.
See also: #34048
