### ISSUE TITLE
[R] Documentation for json_credentials is misleading

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33106]
For authenticating with GCS via a JSON credentials file, the documentation under ?FileSystem for GcsFileSystem$create() says:

 
- `{}json_credentials{`}: optional string for authentication. Point to a JSON credentials file downloaded from GCS.
  
   
  
  Additionally, the GCS Authentication section of Working with Cloud Storage (S3, GCS) in the file system vignette says:
  > or `{}json_credentials{`}, to reference a downloaded credentials file.
   
  
  Both of these seem to imply that json_credentials expects a path to a JSON credentials file downloaded from GCP. However, when a file path is provided you get an invalid argument error:
  
   
  ```java
  
  > bucket <- gs_bucket(bucket = 'pinned_data',json_credentials = json_path)
  > bucket$ls(recursive = TRUE)
  Error: Invalid: google::cloud::Status(INVALID_ARGUMENT: Permanent error in ListObjects: Invalid ServiceAccountCredentials,parsing failed on data loaded from memory). Detail: [errno 22] Invalid argument
  ```
   
  
  However, if you pass a string containing the raw JSON from the file itself, the above code snippet works and returns the names of the objects in the bucket.
  
  Both sections of the documentation should be clarified to explicitly say that the argument expects the actual JSON rather than a file path to the JSON file.

**Reporter**: [Joran Elias](https://issues.apache.org/jira/browse/ARROW-17894)

<sub>**Note**: *This issue was originally created as [ARROW-17894](https://issues.apache.org/jira/browse/ARROW-17894). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by amoeba** [comment]
take

**Comment by amoeba** [comment]
Hey @cboettig, I've written up a standalone issue for what you're seeing at https://github.com/apache/arrow/issues/34525 and think we can follow up there. 

Once https://github.com/apache/arrow/pull/34524 merges this issue can be closed.
