### ISSUE TITLE
[C++] Parquet support read page with crc32 checking

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33115]
Currently, C++'s Parquet support write page with checksum, but `ReadPage` doesn't have check any checksum. And I would like to fix it

I'd like to split this patch to different parts:
1. Implement the crc in DataPageV1, which requires a write crc config, counting crc in read mode, crc verification, migrate testing from parquet mr
1. Implement crc for DataPageV2
1. Implement crc for Dict

**Reporter**: [Xuwei Fu](https://issues.apache.org/jira/browse/ARROW-17904) / @mapleFU
**Assignee**: [Xuwei Fu](https://issues.apache.org/jira/browse/ARROW-17904) / @mapleFU
#### PRs and other links:
- [GitHub Pull Request #14351](https://github.com/apache/arrow/pull/14351)
- [GitHub Pull Request #29](https://github.com/apache/parquet-testing/pull/29)

<sub>**Note**: *This issue was originally created as [ARROW-17904](https://issues.apache.org/jira/browse/ARROW-17904). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by wjones127** [comment]
@mapleFU could you "take" this one too?

**Comment by mapleFU** [comment]
take
