### ISSUE TITLE
[Java] Java jars creation failed at "Build C++ libraries macOS" steps

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33136]
Java jars creation failed at `Build C++ libraries macOS`

Consider: 
- <https://github.com/ursacomputing/crossbow/actions/runs/3172796174/jobs/5168650287>
- <https://github.com/ursacomputing/crossbow/actions/runs/3142124901/jobs/5106467031>
  
  Errors message:
  ```java
  
  ld: warning: dylib (/usr/local/lib/libz3.dylib) was built for newer macOS version (11.0) than being linked (10.13)
  3744ld: warning: dylib (/usr/local/lib/libzstd.1.5.2.dylib) was built for newer macOS version (11.0) than being linked (10.13)
  3745ld: in /usr/local/opt/llvm/lib/libLLVMCore.a(Instructions.cpp.o), could not parse object file /usr/local/opt/llvm/lib/libLLVMCore.a(Instructions.cpp.o): 'Invalid value (Producer: 'LLVM15.0.0' Reader: 'LLVM APPLE_1_1300.0.29.30_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.30)' for architecture x86_64
  3746clang: error: linker command failed with exit code 1 (use -v to see invocation)
  3747ninja: build stopped: subcommand failed.
  3748Error: Process completed with exit code 1. 
  ```
  @raulcd   `[~jwozniak]`  

**Reporter**: [David Dali Susanibar Arce](https://issues.apache.org/jira/browse/ARROW-17928) / @davisusanibar

<sub>**Note**: *This issue was originally created as [ARROW-17928](https://issues.apache.org/jira/browse/ARROW-17928). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Done.
