### ISSUE TITLE
[CI] Travis-CI should not run on unrelated changes

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33135]
Travis-CI currently runs jobs for C++, Python and Java, but as we can see in https://github.com/apache/arrow/pull/14304, it gets run anyway for changes that don't touch those areas at all.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-17926) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-17926](https://issues.apache.org/jira/browse/ARROW-17926). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
We have no Travis-CI builds anymore, closing as outdated.
