### ISSUE TITLE
[Plasma][C++] plasma-store-server start with -h , occur bus error

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33204]
use plasma as a shared-memory ,

start with these args:

./plasma-store-server -m 1000000 -s /tmp/test -d /dev/shm -h

occurs bus error

/home/arrow/arrow/cpp/src/plasma/store.cc:1277: Allowing the Plasma store to use up to 0.001GB of memory.
/home/arrow/arrow/cpp/src/plasma/store.cc:1300: Starting object store with directory /dev/shm and huge page support enabled
/home/arrow/arrow/cpp/src/plasma/store.cc:1328:  hugepage enable , SetMallocGranularity.
/home/arrow/arrow/cpp/src/plasma/store.cc:1349: starting server listening on /tmp/test
/home/arrow/arrow/cpp/src/plasma/store.cc:1154: new PlasmaStore...
/home/arrow/arrow/cpp/src/plasma/store.cc:1163: Memalign...pointer
/home/arrow/arrow/cpp/src/plasma/plasma_allocator.cc:34: Memalign,alignment=64;bytes=997952
internal memalign
internal malloc req = 998056,nb = 997968,min_chunk_size = 32,chunk_overhead = 8
Bus error

 

env:

[root@02a40e9b75b6 release]# free
              total        used        free      shared  buff/cache   available
Mem:       12979512     6299224     1163552      369948     5516736     5990072
Swap:       4194304       16480     4177824
[root@02a40e9b75b6 release]# uname -a
Linux 02a40e9b75b6 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Environment**: [root@02a40e9b75b6 release]# free
              total        used        free      shared  buff/cache   available
Mem:       12979512     6299224     1163552      369948     5516736     5990072
Swap:       4194304       16480     4177824
[root@02a40e9b75b6 release]# uname -a
Linux 02a40e9b75b6 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**Reporter**: [xingwang li](https://issues.apache.org/jira/browse/ARROW-18000)

<sub>**Note**: *This issue was originally created as [ARROW-18000](https://issues.apache.org/jira/browse/ARROW-18000). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Plasma has been deprecated (https://github.com/apache/arrow/issues/33077) in Arrow 10.0 and subsequently removed in Arrow 12.0 (https://github.com/apache/arrow/issues/33243). Given Plasma is no longer an existing component, closing this issue.

For reference, see this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2
