### ISSUE TITLE
[Python] Add sort_by to RecordBatch

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33207]
**Reporter**: [Alessandro Molina](https://issues.apache.org/jira/browse/ARROW-18003) / @amol-

<sub>**Note**: *This issue was originally created as [ARROW-18003](https://issues.apache.org/jira/browse/ARROW-18003). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
`RecordBatch.sort_by` was in the meantime tackled in https://github.com/apache/arrow/pull/14781 (together with (Chunked)Array.sort), so we can close this issue.

**Comment by jorisvandenbossche** [comment]
Resolved by #14781
