### ISSUE TITLE
[Plasma] Remove Plasma

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33243]
Plasma was deprecated in ARROW-17860.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-18040) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-18040](https://issues.apache.org/jira/browse/ARROW-18040). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
I know there was this mailing list discussion around possible alternatives: https://lists.apache.org/thread/lk277x3b9gjol42sjg27bst2ggm5s0j2

**Comment by MoFHeka** [comment]
So there is no other option to replace plasma with same performance?

**Comment by xiandong79** [comment]
??? why remove

**Comment by kou** [comment]
Because it was not maintained. See also:
* https://github.com/apache/arrow/issues/33077
* https://lists.apache.org/thread/nw232k2lzmg9kcl8ts475m9ybl34j81p

**Comment by at15** [comment]
For anyone that jump to the issue because seeing Plasma from Ray's doc. Ray has plasma inside the project without standalone API https://discuss.ray.io/t/plasma-store-apis/5421/6 https://github.com/ray-project/ray/tree/master/src/ray/object_manager/plasma
