### ISSUE TITLE
[C++][CI] Reduce MinGW build times

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33242]
The MinGW C++ builds on CI currently build in release mode. This is probably because debug builds on Windows are complicated (you must get all the dependencies also compiled in debug mode, AFAIU).

However, we could probably disable optimizations, so as to reduce compilation times.
The compilation flags are currently as follows:
```Java

-- CMAKE_C_FLAGS:  -O2 -DNDEBUG -ftree-vectorize  -Wa,-mbig-obj -Wall -Wno-conversion -Wno-sign-conversion -Wunused-result -fno-semantic-interposition -mxsave -msse4.2 
-- CMAKE_CXX_FLAGS:  -Wno-noexcept-type  -fdiagnostics-color=always -O2 -DNDEBUG -ftree-vectorize  -Wa,-mbig-obj -Wall -Wno-conversion -Wno-sign-conversion -Wunused-result -fno-semantic-interposition -mxsave -msse4.2 
```

Perhaps we can pass `-O0`?

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-18039) / @pitrou
**Assignee**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-18039) / @kou

<sub>**Note**: *This issue was originally created as [ARROW-18039](https://issues.apache.org/jira/browse/ARROW-18039). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Nowadays the MINGW builds take around ~40 minutes when the cache is cold. I'll close this.
