### ISSUE TITLE
[C++] Utility method to ensure an array object meetings an alignment requirement

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33317]
This would look something like:

EnsureAligned(Buffer|Array|ChunkedArray|RecordBatch|Table, int minimum_alignment, MemoryPool\* memory_pool);

It would fail if MemoryPool's alignment < minimum_alignment
It would iterate through each buffer of the object, if the object is not aligned properly, it would reallocate and copy the buffer (using memory_pool)

It would return a new object where every buffer is guaranteed to meet the alignment requirements.

**Reporter**: [Weston Pace](https://issues.apache.org/jira/browse/ARROW-18119) / @westonpace
**Assignee**: [Sanjiban Sengupta](https://issues.apache.org/jira/browse/ARROW-18119) / @sanjibansg
#### PRs and other links:
- [GitHub Pull Request #14758](https://github.com/apache/arrow/pull/14758)

<sub>**Note**: *This issue was originally created as [ARROW-18119](https://issues.apache.org/jira/browse/ARROW-18119). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by rtpsw** [comment]
@westonpace, @sanjibansg: we are interested in this PR getting merged. cc @icexelloss.

**Comment by icexelloss** [comment]
Thanks @westonpace !
