### ISSUE TITLE
[Python] test_cython failing on macOS

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33344]
<https://github.com/apache/arrow/actions/runs/3315249930/jobs/5475594297#step:5:354>
```java

ImportError: dlopen(/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_cython_api0/pyarrow_cython_example.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libarrow_python.1000.dylib'
357  Referenced from: '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_cython_api0/pyarrow_cython_example.cpython-310-darwin.so'
358  Reason: tried: '/usr/local/lib/libarrow_python.1000.dylib' (no such file), '/usr/local/lib/libarrow_python.1000.dylib' (no such file), '/usr/local/lib/libarrow_python.1000.dylib' (no such file), '/usr/lib/libarrow_python.1000.dylib' (no such file) 
```

**Reporter**: [Alenka Frim](https://issues.apache.org/jira/browse/ARROW-18150) / @AlenkaF

<sub>**Note**: *This issue was originally created as [ARROW-18150](https://issues.apache.org/jira/browse/ARROW-18150). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by raulcd** [comment]
@AlenkaF @jorisvandenbossche this was fixed by: https://github.com/apache/arrow/pull/14643, right?

**Comment by AlenkaF** [comment]
Yes, correct.
