### ISSUE TITLE
[Python] DataFrame Interchange Protocol for pyarrow Table

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33346]
For the documentation and spec: <https://data-apis.org/dataframe-protocol/latest/index.html>
Blog post about it: <https://data-apis.org/blog/dataframe_protocol_rfc/>
 
Several DataFrame libraries now support this interchange protocol (pandas, modin, vaex, cudf).

**Reporter**: [Alenka Frim](https://issues.apache.org/jira/browse/ARROW-18152) / @AlenkaF
**Assignee**: [Alenka Frim](https://issues.apache.org/jira/browse/ARROW-18152) / @AlenkaF
#### PRs and other links:
- [GitHub Pull Request #14613](https://github.com/apache/arrow/pull/14613)
- [GitHub Pull Request #14804](https://github.com/apache/arrow/pull/14804)

<sub>**Note**: *This issue was originally created as [ARROW-18152](https://issues.apache.org/jira/browse/ARROW-18152). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 14804
https://github.com/apache/arrow/pull/14804
