### ISSUE TITLE
[Ruby] Tables can have buffers get GC'ed

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33354]
ven an Arrow::Table with several columns "X"

 
```ruby

# Rails console outputs
3.1.2 :107 > x.schema
 => 
#<Arrow::Schema:0x7ff2fbc426d8 ptr=0x55851587bc20 actual_values: int64
dates: date32[day]                             
expected_values: double>                       
3.1.2 :108 > x.schema
 => 
#<Arrow::Schema:0x7ff2fbbcda68 ptr=0x55851a541020 actual_values: int64
dates: date32[day]                             
expected_values: double>                       
3.1.2 :109 >  
```
Note that the object and pointer have both changed values.

But the far bigger issue is that repeated reads from it will cause different results:
```ruby

3.1.2 :097 > x[1][0]
 => Sun, 22 Aug 2021 
3.1.2 :098 > x[1][1]
 => nil 
3.1.2 :099 > x[1][0]
 => nil 
```

I have a lot of issues like this - when I have done these types of read operations, I get the original table with the data in the columns all shuffled around or deleted. 

I do ingest the data slightly oddly in the first place as it comes in over GRPC and I am using Arrow::Buffer to read it from the GRPC and then passing that into Arrow::Table.load. But I would not expect that once it was in Arrow::Table that I could do anything to permute it unintentionally.

 

 

**Environment**: Ruby 3.1.2
**Reporter**: [Noah Horton](https://issues.apache.org/jira/browse/ARROW-18161)
**Assignee**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-18161) / @kou
#### PRs and other links:
- [GitHub Pull Request #15217](https://github.com/apache/arrow/pull/15217)

<sub>**Note**: *This issue was originally created as [ARROW-18161](https://issues.apache.org/jira/browse/ARROW-18161). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by kou** [comment]
Fixed by #15217.
