### ISSUE TITLE
ArrowIOError on file not found

### ISSUE THREAD

**Issue by matthsims** [apache/arrow#3335]
Is there a reason `ArrowIOError` is raised instead of `FileNotFoundError`, when a file is not found? There's really no good reason to force users to import (potentially downstream) libraries to catch an error that has a built-in analog.

For example, using pandas & feather-format:
```python
import pandas as pd
try:
    pd.read_feather('does_not_exist.feather')
except FileNotFoundError:
    pass
```
```
>>> ArrowIOError: Failed to open local file: does_not_exist.feather , error: No such file or directory
```

**Comment by wesm** [comment]
Please open a JIRA issue if you would like to change something
