### ISSUE TITLE
[Python] Table.drop should support passing a single column

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33377]
```Java

----> 2 data = dataset.drop("Churn") 

/usr/local/lib/python3.7/dist-packages/pyarrow/table.pxi in pyarrow.lib.Table.drop()
    KeyError: "Column 'C' not found"
```

Also, for consistency, it would probably be good to have a `Table.drop_column` alias, as all the other methods are named `Table.add_column`, `Table.append_column` and `Table.set_column`

**Reporter**: [Alessandro Molina](https://issues.apache.org/jira/browse/ARROW-18189) / @amol-

<sub>**Note**: *This issue was originally created as [ARROW-18189](https://issues.apache.org/jira/browse/ARROW-18189). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by danepitkin** [comment]
Whoops, looks like I did not correctly link my PR to the original issue. My PR is here https://github.com/apache/arrow/pull/33810.
