### ISSUE TITLE
[CI] Substrait Integration Testing

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33439]
At the moment the Substrait consumer test suite is developed at <https://github.com/substrait-io/consumer-testing.> To evaluate the performance and functionality against Acero/Substrait development, an integration test suite is important.

**Reporter**: [Vibhatha Lakmal Abeykoon](https://issues.apache.org/jira/browse/ARROW-18258) / @vibhatha
**Assignee**: [Vibhatha Lakmal Abeykoon](https://issues.apache.org/jira/browse/ARROW-18258) / @vibhatha
#### PRs and other links:
- [GitHub Pull Request #14596](https://github.com/apache/arrow/pull/14596)

<sub>**Note**: *This issue was originally created as [ARROW-18258](https://issues.apache.org/jira/browse/ARROW-18258). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
@vibhatha please comment "take" on this PR so it gets assigned to you

**Comment by vibhatha** [comment]
> @vibhatha please comment "take" on this PR so it gets assigned to you

Sure, @assignUser. I will do it.

**Comment by vibhatha** [comment]
take
