### ISSUE TITLE
[C++] Add Acero test to ensure names in the root relation of Substrain plans are retained

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33434]
Currently, Acero retains the names in the root relation when it executes a Substrait plan but there isn't a unit test in place to prevent a future regression.

**Reporter**: [Bryce Mecum](https://issues.apache.org/jira/browse/ARROW-18252) / @amoeba

<sub>**Note**: *This issue was originally created as [ARROW-18252](https://issues.apache.org/jira/browse/ARROW-18252). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by westonpace** [comment]
And this regressed :)

I've added a test in #34406 which should provide regression for this.
