### ISSUE TITLE
[C++] Add `Grouper::Reset`

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33484]
Adding `Grouper::Reset` will enable it to be reused in segmented streaming. `See [this post](https://github.com/apache/arrow/pull/14352#discussion_r1016640969).

**Reporter**: [Yaron Gvili](https://issues.apache.org/jira/browse/ARROW-18311) / @rtpsw

<sub>**Note**: *This issue was originally created as [ARROW-18311](https://issues.apache.org/jira/browse/ARROW-18311). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Issue resolved by pull request 41352
https://github.com/apache/arrow/pull/41352
