### ISSUE TITLE
[Python][CI] Support ORC in Windows wheels

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33499]
Now we support building with ORC enabled on Windows (ARROW-17817), we could also add this to the Python wheel packages for Windows (vcpkg seems to have an orc port for Windows as well)

**Reporter**: [Joris Van den Bossche](https://issues.apache.org/jira/browse/ARROW-18329) / @jorisvandenbossche

<sub>**Note**: *This issue was originally created as [ARROW-18329](https://issues.apache.org/jira/browse/ARROW-18329). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Resolved by https://github.com/apache/arrow/pull/40609
