### ISSUE TITLE
[R] Implement new function open_dataset_csv with signature more closely matching read_csv_arrow

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33526]
In order to make the transition between using the different CSV reading functions as smoothly as possible we could introduce a version of open_dataset specifically for reading CSVs with a signature more closely matching that of read_csv_arrow - this would just pass the arguments through to open_dataset (in the ellipses), but would make it simpler to have a docs page showing these options explicitly and thus be clearer for users.

**Reporter**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-18358) / @thisisnic

<sub>**Note**: *This issue was originally created as [ARROW-18358](https://issues.apache.org/jira/browse/ARROW-18358). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
Issue resolved by pull request 33614
https://github.com/apache/arrow/pull/33614
