### ISSUE TITLE
[R] Handle as_data_frame argument if passed into open_dataset for CSVs

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33524]
Currently, if the argument `as_data_frame` is passed into `open_dataset()` with a CSV format dataset, the error message returned is:

```r

Error: The following option is supported in "read_delim_arrow" functions but not yet supported here: "as_data_frame"
```

Instead, we could silently ignore it if as_data_frame is set to `FALSE` and give a more helpful error if set to `TRUE` (i.e. direct user to call `as.data.frame()` or `collect()`).

Reasoning: it'd be great to get to a point where users can just swap their `read_csv_arrow()` syntax for `open_dataset()` and get helpful results.

**Reporter**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-18356) / @thisisnic

<sub>**Note**: *This issue was originally created as [ARROW-18356](https://issues.apache.org/jira/browse/ARROW-18356). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
Closing this issue as the it's more clear from the `open_csv_dataset()` docs why not to do this
