### ISSUE TITLE
[C++] Move select-k implementation into separate module

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33559]
The select-k kernel implementations are currently in `vector_sort.cc`, amongst other things.
To make the code more readable and faster to compiler, we should move them into their own file.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-18395) / @pitrou
**Assignee**: [Ben Harkins](https://issues.apache.org/jira/browse/ARROW-18395) / @benibus
#### PRs and other links:
- [GitHub Pull Request #14753](https://github.com/apache/arrow/pull/14753)

<sub>**Note**: *This issue was originally created as [ARROW-18395](https://issues.apache.org/jira/browse/ARROW-18395). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
Issue resolved by pull request 14753
https://github.com/apache/arrow/pull/14753

**Comment by pitrou** [comment]
(this issue should be assigned to @benibus but unfortunatly it doesn't seem possible to do so)

**Comment by benibus** [comment]
[dummy comment]
