### ISSUE TITLE
[C++][Parquet] Parquet page index read support

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33596]
Implement read support for parquet page index and expose it from the reader API.

**Reporter**: [Gang Wu](https://issues.apache.org/jira/browse/ARROW-18434) / @wgtmac
**Assignee**: [Gang Wu](https://issues.apache.org/jira/browse/ARROW-18434) / @wgtmac
#### PRs and other links:
- [GitHub Pull Request #14964](https://github.com/apache/arrow/pull/14964)

<sub>**Note**: *This issue was originally created as [ARROW-18434](https://issues.apache.org/jira/browse/ARROW-18434). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@wgtmac Can you add a comment so that we can assign you here?

**Comment by wgtmac** [comment]
> @wgtmac Can you add a comment so that we can assign you here?

Thanks @pitrou!
