### ISSUE TITLE
[Dev] merge_arrow_pr.sh can't detect correct milestone with many milestones

### ISSUE THREAD

**Issue by kou** [apache/arrow#33604]
### Describe the enhancement requested

GitHub REST API returns at most 30 milestones with https://api.github.com/repos/apache/arrow/milestones by default. If we have 30+ milestones (now, we have 57 milestones https://github.com/apache/arrow/milestones ), we need to increase the 30 limit or use pagination.

* Increase the 30 limit: https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28#using-query-parameters
* For pagination: https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28

If we don't collect recent milestones such as 11.0.0, we can't set 11.0.0 milestone to the issue.
 

### Component(s)

Developer Tools

**Comment by kou** [comment]
Or we may want to use the `sort` parameter to get only recent milestones: https://docs.github.com/en/rest/issues/milestones?apiVersion=2022-11-28#list-milestones

**Comment by rok** [comment]
Maximum results per page is 100 and currently we're at 54, so this should work:
```
milestone_url = "https://api.github.com/repos/apache/arrow/milestones"
milestone_map = requests.get(milestone_url, params={"state": "all", "per_page": 100},
                                 headers=GITHUB_CREDENTIALS).json()
```

**Comment by raulcd** [comment]
I don't think this is a problem. The API returns by default only opened milestones, at the moment only 2 are opened. All the other milestones were just temporary opened due to the migration and that's why there was that issue.

**Comment by kou** [comment]
I see.
