### ISSUE TITLE
[CI][Python][C++] Avoid compiling grpcio from source

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#33630]
### Describe the enhancement requested

This wastes CI time:
https://app.travis-ci.com/github/apache/arrow/jobs/593143816#L1806

### Component(s)

Continuous Integration

**Comment by pitrou** [comment]
@assignUser @raulcd

**Comment by kou** [comment]
https://pypi.org/project/grpcio/1.49.1/#files has `grpcio-1.49.1-cp38-cp38-manylinux_2_17_aarch64.whl`.
I don't know why it's not used...

**Comment by pitrou** [comment]
pip probably needs to be upgraded to recognize `manylinux_2_17`.

**Comment by assignUser** [comment]
It uses python3-pip from ubuntu 20.04 so probably? I will test it

**Comment by pitrou** [comment]
@assignUser Could you advance on this?

**Comment by pitrou** [comment]
This was fixed piecemeal by several PRs including https://github.com/apache/arrow/pull/43852
