### ISSUE TITLE
[c++] Does the dataset feature have a hard dependency on parquet? 

### ISSUE THREAD

**Issue by autoantwort** [apache/arrow#33657]
### Describe the usage question you have. Please include as many useful details as  possible.

C++: There is the option `ARROW_DATASET`. Does setting this to ON also require setting `ARROW_PARQUET` to ON?
Rationale: The file `arrow-dataset.pc` contains a hard dependency to `parquet`. 

PS: I am only a vcpkg maintainer and not an arrow user. 

### Component(s)

C++

**Comment by westonpace** [comment]
It should not.  They were designed to be separable.

**Comment by westonpace** [comment]
Though maybe there is some nuance.  If the datasets shared library is compiled with ARROW_PARQUET=ON then it will fail unless the parquet shared library is present.

If the datasets shared library is compiled with ARROW_PARQUET=OFF then it will not fail.

**Comment by kou** [comment]
It's a bug of `arrow-dataset.pc`.
#33665 fixes this.
