### ISSUE TITLE
[C++] Add custom codec make codec pluggable for IPC

### ISSUE THREAD

**Issue by marin-ma** [apache/arrow#33688]
### Describe the enhancement requested

For now, only LZ4 and zstd compression codec are valid in arrow IPC. We hope to add a custom codec to allow using user-defined codec, so that we can use other compression algorithms or methods to optimize data de/compression in real workloads.

### Component(s)

C++

**Comment by pitrou** [comment]
The compression codecs are part of the spec: https://github.com/apache/arrow/blob/c525b57295e5ab9cb9e2591342d0b01a357660a3/format/Message.fbs#L45-L53

 Using custom codecs would destroy interoperability, so I'm afraid this is totally out of question.

**Comment by pitrou** [comment]
In any case, if you want to discuss such as protocol addition, it should be done on the [development mailing-list](https://arrow.apache.org/community/).
