### ISSUE TITLE
[C++][CI] arrow-compute-plan-test timeouts on nightly job for ubuntu 18.04

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#33695]
### Describe the bug, including details regarding any error messages, version, and platform.

Since https://github.com/apache/arrow/pull/15183 was merged the nightly job for:
[test-ubuntu-18.04-cpp-static](https://github.com/ursacomputing/crossbow/actions/runs/3926041170/jobs/6711398044)
has been failing with a timeout on:
```
 Errors while running CTest
88/88 Test #36: arrow-compute-plan-test ...................***Timeout 300.00 sec
Running arrow-compute-plan-test, redirecting output into /build/cpp/build/test-logs/arrow-compute-plan-test.txt (attempt 1/1)


99% tests passed, 1 tests failed out of 88
```
It does not seem to cause issues on the verification scripts so I don't think it is a release blocker but we should investigate to fix the test or increase the timeout?

### Component(s)

C++, Continuous Integration

**Comment by raulcd** [comment]
cc @vibhatha

**Comment by westonpace** [comment]
Is this consistent?  It may be fixed by https://github.com/apache/arrow/pull/33700

**Comment by raulcd** [comment]
It has been failing consistently since the first failure for the last 3 nightlies based on: http://crossbow.voltrondata.com/

**Comment by raulcd** [comment]
it seems to be fixed by the PR mentioned above: https://github.com/apache/arrow/pull/33700
I've triggered the crossbow job manually from latest master (containing the fix) and has been successful: https://github.com/ursacomputing/crossbow/actions/runs/3931964628
I am closing the issue, will re-open if nightly jobs fail again but seems fixed.
