### ISSUE TITLE
[CI][Python] Nightlies pandas jobs with pandas nightly and upstream_devel are currently failing

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#33696]
### Describe the bug, including details regarding any error messages, version, and platform.

This jobs seems to have been failing for around 3 weeks now:
[test-conda-python-3.8-pandas-nightly](https://github.com/ursacomputing/crossbow/actions/runs/3926040360/jobs/6711396548)
[test-conda-python-3.9-pandas-upstream_devel](https://github.com/ursacomputing/crossbow/actions/runs/3926045111/jobs/6711405287)
There's a single error for pandas nightly but 5 errors for upstream_devel. Copying an example of error for the pandas nightly:
```
 =================================== FAILURES ===================================
________________________________ test_timestamp ________________________________

    @pytest.mark.pandas
    def test_timestamp():
        import pandas as pd
        arr = pd.date_range('2000-01-01 12:34:56', periods=10).values
    
        units = ['ns', 'us', 'ms', 's']
    
        for i, unit in enumerate(units):
            dtype = 'datetime64[{}]'.format(unit)
            arrow_arr = pa.Array.from_pandas(arr.astype(dtype))
            expected = pd.Timestamp('2000-01-01 12:34:56')
    
            assert arrow_arr[0].as_py() == expected
>           assert arrow_arr[0].value * 1000**i == expected.value
E           AssertionError: assert (946730096000000000 * (1000 ** 0)) == 946730096
E            +  where 946730096000000000 = <pyarrow.TimestampScalar: Timestamp('2000-01-01 12:34:56')>.value
E            +  and   946730096 = Timestamp('2000-01-01 12:34:56').value

opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/test_scalars.py:311: AssertionError
```

### Component(s)

Continuous Integration, Python

**Comment by jorisvandenbossche** [comment]
This is being discussed on the pandas side, and most likely this change will be reverted in pandas, so we don't have to do something release critical. 
(although it would still be good to fix the test to get the nightly build passing; I can look into that tomorrow)

**Comment by jorisvandenbossche** [comment]
This was indeed changed back on the pandas side.
