### ISSUE TITLE
python pyarrow.lib.ArrowNotImplementedError: lists with structs are not supported.

### ISSUE THREAD

**Issue by balaklava** [apache/arrow#3371]
Hello. I cannot read a parquet file on a local file system and I have the following error: pyarrow.lib.ArrowNotImplementedError: lists with structs are not supported. I use Ubuntu. It would be nice, if somebody could help with it.

**Comment by wesm** [comment]
This is https://issues.apache.org/jira/browse/ARROW-1644.
