### ISSUE TITLE
[Go] arrow library is not compatible with grpc < 1.45 due to use of reflection experimental interface

### ISSUE THREAD

**Issue by chrisirhc** [apache/arrow#33734]
### Describe the enhancement requested

When attempting to use arrow library in projects with grpc < 1.45, the reflection was added in v1.45.0 via https://github.com/grpc/grpc-go/commit/18564ff61d5505d955c7bd1adc28e4f1ed96300c . 

This is due to a single line that references an experimental interface in grpc.reflection package:
https://github.com/apache/arrow/blob/c8d6110a26c41966e539e9fa2f5cb8c31dc2f0fe/go/arrow/flight/server.go#L97-L99

The interface is defined as:
https://github.com/grpc/grpc-go/blob/4c776ec01572d55249df309251900554b46adb41/reflection/serverreflection.go#L69-L83

I propose to inline this interface so that the go arrow library can be used in projects with earlier versions of grpc which don't contain this experimental interface. This should maintain the reflection capabilities introduced in https://github.com/apache/arrow/commit/07e7009154dc64967543ccd6462841443a8586b7 but make go arrow library compatible with grpc < 1.45.

### Component(s)

Go

**Comment by assignUser** [comment]
cc @zeroshade

**Comment by zeroshade** [comment]
Issue resolved by pull request 33735
https://github.com/apache/arrow/pull/33735
