### ISSUE TITLE
[Ruby] Add Arrow::RecordBatch#each_raw_record

### ISSUE THREAD

**Issue by otegami** [apache/arrow#33749]
## Target method

Arrow::RecordBatch#raw_records

## Proposed feature

~~Add Arrow::RecordBatch#each_raw_record method which is an iterator of Arrow::RecordBatch#raw_records.~~
Add Arrow::RecordBatch#each_raw_record and Arrow::Table#each_raw_record to make Arrow::RecordBatch#raw_records be iterable.

## Impact of this request

It can iterate over huge datasets, such as those using the Apache Parquet format.

### Component(s)

Ruby

**Comment by kou** [comment]
`Arrow::Table#each_raw_record` is also needed.

**Comment by otegami** [comment]
Thank you for reviewing it. I've just fixed it.
