### ISSUE TITLE
 [GLib] Add chunk_size property to GArrowTableBatchReader

### ISSUE THREAD

**Issue by otegami** [apache/arrow#33750]
## Target
~~TableBatchReader's chunksize~~
the property of GArrowTableBatchReader 
- ref: https://github.com/apache/arrow/blob/master/cpp/src/arrow/table.h#L258

## Proposed feature
~~Add support for the option to set chunksize in TableBatchReader~~
Add chunk_size property to GArrowTableBatchReader

## Impact of this request

It allows the maximum number of records in each record batch to be specified

### Component(s)

GLib

**Comment by kou** [comment]
We need to add `chunk_size` property to `GArrowTableBatchReader`.

**Comment by otegami** [comment]
Thank you for reviewing it. I've just fixed it.
