### ISSUE TITLE
[Packaging][Conda] Ubuntu: libarrow conda package fails to install on ecryptfs

### ISSUE THREAD

**Issue by crusaderky** [apache/arrow#33752]
### Describe the bug, including details regarding any error messages, version, and platform.

Ubuntu 22.04.1 x86-64
conda 22.9.0 (defaults channel)

My home directory was created on top of ecryptfs by the Ubuntu installer:

> $ mount | grep home
> /home/.ecryptfs/crusaderky/.Private on /home/crusaderky type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=0ee7f63b0c91f840,ecryptfs_sig=c7f3e46a3b8390b1,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)

Trying to install libarrow with conda fails with `[Errno 36] File name too long`:
> $ conda create -n test libarrow                                                                                                                             
> InvalidArchiveError("Error with archive /home/crusaderky/miniconda3/pkgs/libarrow-10.0.1-h86614e7_4_cpu.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 36] File name too long: '/home/crusaderky/miniconda3/pkgs/libarrow-10.0.1-h86614e7_4_cpu/share/gdb/auto-load/home/conda/feedstock_root/build_artifacts/apache-arrow_1673819166020/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol'")

Out of the hundreds of other packages that I'm installing, libarrow seems to be the only problematic one.

### Workaround
Move the conda root dir to ext4:
```bash
$ sudo mkdir /home/$USER-nocrypt
$ sudo chown $USER:users /home/$USER-nocrypt
$ mv /home/$USER/miniconda3 /home/$USER-nocrypt/
$ ln -s /home/$USER-nocrypt/miniconda3 /home/$USER/miniconda3
$ conda create -n test libarrow
```

### Component(s)

Python

**Comment by kou** [comment]
It seems that this is a conda package problem. Could you report this to https://github.com/conda-forge/arrow-cpp-feedstock ?
