### ISSUE TITLE
[Python] pa.map_() ignores child field metadata

### ISSUE THREAD

**Issue by sfc-gh-zpeng** [apache/arrow#33763]
### Describe the bug, including details regarding any error messages, version, and platform.

A map type can be created with the key and the item fields. And custom KV metadata can be attached to those fields. However, when creating such a type using pyarrow.map_(), the field level metadata are not taken. For example:

```
map_type = pa.map_(
    pa.field("key", pa.string(), nullable=False, metadata={"abc": "1"}),
    pa.field("value", pa.int32(), metadata={"abc": "2"}))
```

`map_type.key_field.metadata` is None, but it's expected to be `{"abc": "1"}`.

I believe it's a bug in pyarrow. Specifically at this line: https://github.com/apache/arrow/blob/1d9366f19e4b9846b33cc0c7bd7941cb5f482d74/python/pyarrow/types.pxi#L2929

A new field is created and used but without the metadata of the input field.

Also see: https://colab.research.google.com/drive/1ixsRK02I0aItU9FlHQf14IArWwR5ugiA#scrollTo=mzkPfZ5h6Td6

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
> I believe it's a bug in pyarrow. Specifically at this line: .... A new field is created and used but without the metadata of the input field.

That line should only be run if what you passed is not yet a Field? (so we create a new field if you just pass a type). 

So it might be on the C++ side, but also not directly sure where since we just seem to be passing through the field, which should retain the metadata.

**Comment by jorisvandenbossche** [comment]
Actually, this seems to working fine for me with the latest pyarrow:

```
In [72]: map_type = pa.map_(
    ...:     pa.field("key", pa.string(), nullable=False, metadata={"abc": "1"}),
    ...:     pa.field("value", pa.int32(), metadata={"abc": "2"}))
    ...: 

In [73]: map_type
Out[73]: MapType(map<string, int32>)

In [74]: map_type.key_field
Out[74]: pyarrow.Field<key: string not null>

In [75]: map_type.key_field.metadata
Out[75]: {b'abc': b'1'}
```

@sfc-gh-zpeng what version of pyarrow are you using?

**Comment by sfc-gh-zpeng** [comment]
oops. I mis-read the code. Sorry.

I believe arrow 9.0 was the version where I found this behavior.
