### ISSUE TITLE
[Go] Exported ArrowArrayStream.get_next doesn't handle uninitialized ArrowArrays well

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#33767]
### Describe the bug, including details regarding any error messages, version, and platform.

`get_next` should set `ArrowArray.release` to `NULL` when there are no more records. However, the current implementation instead tries to _release_ the out-parameter. This is harmless when the out-parameter is 0-initialized (the implementation will skip the call) but otherwise it'll crash (after jumping to a random garbage address).

### Component(s)

Go

**Comment by lidavidm** [comment]
@pitrou I noticed this while using PyArrow to import an ArrowArrayStream exported from Go. PyArrow apparently passes in an uninitialized ArrowArray to Go, and Go was assuming it would be initialized. Should we say that producers should not assume inputs are initialized, or that consumers should (zero-)initialize parameters?

**Comment by pitrou** [comment]
The `out` parameter should be handled as an out-parameter, so it can't be expected to be initialized (to what?).

**Comment by lidavidm** [comment]
That's what I thought :)

(It was expecting it to be zero-initialized, because it would _call the release callback if present_.)
