### ISSUE TITLE
[C++] Arrow under s390x: statement has no effect [-Werror=unused-value]

### ISSUE THREAD

**Issue by aliakseimakarau** [apache/arrow#33787]
### Describe the usage question you have. Please include as many useful details as  possible.

Arrow is employed in CEPH software defined storage (https://github.com/ceph/ceph, https://github.com/ceph/ceph/blob/main/.gitmodules):
```
[submodule "src/arrow"]
	path = src/arrow
	url = https://github.com/apache/arrow.git
```
Building the whole system at s390x with the -Werror triggers the following: 
arrow/cpp/src/arrow/util/cpu_info.cc:155:3: error: statement has no effect [-Werror=unused-value] (347a88ff9d20e2a4061eec0b455b8ea1aa8335dc).

Should a "dummy" default element be inserted into the `flag_mappings[]` :
```
struct {
  std::string name;
  int64_t flag;
} flag_mappings[] = {
#if (defined(__i386) || defined(_M_IX86) || defined(__x86_64__) || defined(_M_X64))
    {"ssse3", CpuInfo::SSSE3},       {"sse4_1", CpuInfo::SSE4_1},
    {"sse4_2", CpuInfo::SSE4_2},     {"popcnt", CpuInfo::POPCNT},
    {"avx", CpuInfo::AVX},           {"avx2", CpuInfo::AVX2},
    {"avx512f", CpuInfo::AVX512F},   {"avx512cd", CpuInfo::AVX512CD},
    {"avx512vl", CpuInfo::AVX512VL}, {"avx512dq", CpuInfo::AVX512DQ},
    {"avx512bw", CpuInfo::AVX512BW}, {"bmi1", CpuInfo::BMI1},
    {"bmi2", CpuInfo::BMI2},
#endif
#if defined(__aarch64__)
    {"asimd", CpuInfo::ASIMD},
#endif
};
```
Should I create a PR?
Thank you!

### Component(s)

C++

**Comment by kou** [comment]
We can just return `0` on neither x86 nor arm. Can you create a pull request with this approach?

**Comment by aliakseimakarau** [comment]
Lets first approach with this one:
https://github.com/apache/arrow/pull/33803

**Comment by aliakseimakarau** [comment]
Dear Sutou, thank you very much for the hint! Here is an update: https://github.com/apache/arrow/pull/33828

**Comment by kou** [comment]
Issue resolved by pull request 33828
https://github.com/apache/arrow/pull/33828
