### ISSUE TITLE
[Release][C#] Release verification tasks fail with new version of C# 7.0.x

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#33783]
### Describe the bug, including details regarding any error messages, version, and platform.

dotnet 7.0.0 was released on November and we never added new tasks for it. https://dotnet.microsoft.com/en-us/download/dotnet/7.0
We currently only have verification jobs with 6.0.202. If I run verification locally with Ubuntu 22.04 with .NET 6.0.202 C# jobs are successful:
```
===========================
Build and test C# libraries
===========================
└ Ensuring that C# is installed...
└ Installed C# at  (.NET 6.0.202)
You can invoke the tool using the following command: sourcelink
Tool 'sourcelink' (version '3.1.1') was successfully installed.
/tmp/arrow-11.0.0.ReaWC/apache-arrow-11.0.0/csharp /tmp/arrow-11.0.0.ReaWC/apache-arrow-11.0.0 ~/code/arrow
  Determining projects to restore...
```

but it fails if I upgrade dotnet to `7.0.102`:
```
===========================
Build and test C# libraries
===========================
└ Ensuring that C# is installed...
└ Found C# at  (.NET 7.0.102)

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.102
...
dev/release/verify-release-candidate.sh: line 341: 129149 Segmentation fault      (core dumped) dotnet tool install --tool-path ${csharp_bin} sourcelink
Failed to verify release candidate. See /tmp/arrow-11.0.0.lNQyX for details.
```

### Component(s)

C#, Release

**Comment by raulcd** [comment]
I've found that if I install dotnet 7.0.102 via snap I get the above segmentation fault but if I install it via the Microsoft debian repositories:
```
$ wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb 
$ sudo dpkg -i packages-microsoft-prod.deb 
$ sudo apt update 
$ sudo apt install dotnet-sdk-7.0 
```
I get a failure around some tests only supporting .NET 6.0:
```
A total of 1 test files matched the specified pattern.
Testhost process for source(s) '/tmp/arrow-11.0.0.kFKaf/apache-arrow-11.0.0/csharp/artifacts/Apache.Arrow.Tests/Debug/net6.0/Apache.Arrow.Tests.dll' exited with error: You must install or update .NET to run this application.
App: /tmp/arrow-11.0.0.kFKaf/apache-arrow-11.0.0/csharp/artifacts/Apache.Arrow.Tests/Debug/net6.0/testhost.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/
The following frameworks were found:
  7.0.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.22.04-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
```
The segmentation fault seems to be a long standing issue of installing dotnet via snap, see:
https://github.com/dotnet/runtime/issues/67465 and https://github.com/dotnet/runtime/issues/51322#issuecomment-890306629

We seem to only support .NET 6.0, right?
https://github.com/apache/arrow/pull/12870/files
@kou @eerhardt @westonpace Are we expected to support the new .NET 7.0?

**Comment by westonpace** [comment]
The libraries are (should be) portable.  Executables (unit tests in this case) are not portable.

The .NET library projects are built to target .net standard and should be compatible with .NET 7.0

The .NET unit test projects are built to target .NET framework 6.0 (executable projects cannot target a standard) and so they require a .NET 6.0 runtime to execute.

I think we can upgrade the unit test projects to compile for both .NET framework 6.0 and 7.0 but that is not normally done.  Or we can install the .NET 6.0 runtime (you can install multiple SDKs / runtimes).  Or we can upgrade the unit tests to always require 7.0

**Comment by westonpace** [comment]
> I've found that if I install dotnet 7.0.102 via snap I get the above segmentation fault but if I install it via the Microsoft debian repositories:

I also experienced this.  I found that I get a segmentation fault running just about anything with `dotnet`.  I don't think it's related to us.  I think it's a flaw in the snap: https://github.com/dotnet/runtime/issues/67465

**Comment by westonpace** [comment]
> I think we can upgrade the unit test projects to compile for both .NET framework 6.0 and 7.0 but that is not normally done.

I take back what I said about "not normally done".  It appears this is the correct way to test: https://stackoverflow.com/questions/44477840/how-to-properly-unit-test-a-net-project-with-multiple-target-frameworks-given
