### ISSUE TITLE
[Release] Vote email number of issues is querying JIRA and producing a wrong number

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#33782]
### Describe the bug, including details regarding any error messages, version, and platform.

When generating the vote email for RC 0 on 11.0.0 I've realised that the vote email generated contains the following:
```
This is a release consisting of 274 resolved JIRA issues[1].
```
This number is extracted from:
```
jira_url="https://issues.apache.org/jira"
  jql="project%20%3D%20ARROW%20AND%20status%20in%20%28Resolved%2C%20Closed%29%20AND%20fixVersion%20%3D%20${version}"
  n_resolved_issues=$(curl "${jira_url}/rest/api/2/search/?jql=${jql}" | jq ".total")
```
This is wrong now, we should extract this from the GitHub milestone:
https://github.com/apache/arrow/milestone/1?closed=1
I've updated this manually for the current email vote but we should fix it on the `dev/release/02-source.sh` script.

### Component(s)

Release

**Comment by rok** [comment]
GraphQL API is another option:
```
curl -H 'Content-Type: application/json' -H "Authorization: bearer GITHUB_TOKEN" -X POST -d '{"query": "query {search(query: \"repo:apache/arrow is:issue is:closed milestone:11.0.0\", type: ISSUE) {issueCount}}"}' https://api.github.com/graphql | jq ".data.search.issueCount"
```
