### ISSUE TITLE
[Packaging] Drop support for Ubuntu 18.04

### ISSUE THREAD

**Issue by kou** [apache/arrow#33800]
### Describe the enhancement requested

Ubuntu 18.04 will reach End of Standard Support on 2023-04: https://wiki.ubuntu.com/Releases

> Version | Code name | Docs | Release | End of Standard Support | End of Life
> -- | -- | -- | -- | -- | --
> Ubuntu 18.04.6 LTS | Bionic Beaver | Changes | September 17.2021 | April 2023 | April 2028

We'll release 12.0.0 on 2023-04 so 12.0.0 doesn't need Ubuntu 18.04 support. We can drop support for Ubuntu 18.04 support now because the maintenance branch for 11.0.0 is already created.

FYI: We can require CMake 3.16 or later after we drop support for Ubuntu 18.04 because Ubuntu 20.04 ships CMake 3.16 and EPEL for CentOS 7 ships CMake 3.17.

### Component(s)

Packaging

**Comment by assignUser** [comment]
> We can require CMake 3.16 

:tada: :partying_face: :rocket:

**Comment by kou** [comment]
We need to keep Debian buster support: https://github.com/apache/arrow/pull/34020#issuecomment-1418064747

Debian buster ships CMake 3.13 but backport repository ships CMake 3.18: https://packages.debian.org/search?keywords=cmake

**Comment by dpsi** [comment]
Hi, the [install page](https://arrow.apache.org/install/) still lists as 18.04 as supported. The release notes for 12 also don't mention the dropping of support for bionic. You have to read through the entire change log to figure that out.

Sorry if this wasn't the appropriate place for docs issues.

**Comment by assignUser** [comment]
@dpsi thanks for the report, this should indeed be mentioned in the blog post
