### ISSUE TITLE
[Python] Double . in error message

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#33824]
### Describe the bug, including details regarding any error messages, version, and platform.

I am getting an error

```
pyarrow.lib.ArrowInvalid: Error creating dataset. Could not read schema from 'data/flights-200k.arrow': Could not open Parquet input source 'data/flights-200k.arrow': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.. Is this a 'parquet' file?
```

Note the double `..`.

### Component(s)

Python

**Comment by saltgen** [comment]
@domoritz Could you post a few steps in order to reproduce this issue?

**Comment by saltgen** [comment]
Hello @domoritz and @kou :wave: , I'll push a change to this one shortly
