### ISSUE TITLE
[Java][FlightRPC] FlightCallHeaders added to FlightClient::getStream aren't attached to call

### ISSUE THREAD

**Issue by mkristofik** [apache/arrow#33839]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm using the Java flight-core version 10.0.1 and grpc-core version 1.50.2.  I'm having trouble attaching headers to a GET call to a server.
```java
Ticket ticket = new Ticket(/* ... */);
CallHeaders headers = new FlightCallHeaders();
headers.insert("foo", "bar");
CallOption opt = new HeaderCallOption(headers);
try (FlightStream stream = client.getStream(ticket, opt)) {
    // ...
}
```
I have logs that show the headers added to `opt` are not making it to the server.  My best guess at why this happens is due to https://github.com/apache/arrow/blob/master/java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java#L309.  `FlightClient` is ignoring the new stub returned by gRPC which has the header-injection interceptor added, see https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/MetadataUtils.java#L55.

Am I doing something wrong here?

### Component(s)

FlightRPC, Java

**Comment by mkristofik** [comment]
Here's the workaround I'm using, which seems to do what I want thus far.  Could someone confirm whether this is a valid approach?
```java
private static class HeaderMiddleware implements FlightClientMiddleware {
    private final Map<String, String> headers;

    private HeaderMiddleware(Map<String, String> headers) {
        this.headers = headers;
    }

    @Override
    public void onBeforeSendingHeaders(CallHeaders outgoingHeaders) {
        for (Map.Entry<String, String> kv : headers.entrySet()) {
            outgoingHeaders.insert(kv.getKey(), kv.getValue());
        }
    }

    @Override public void onHeadersReceived(CallHeaders headers) { }
    @Override public void onCallCompleted(CallStatus status) { }

    static class Factory implements FlightClientMiddleware.Factory {
        Map<String, String> headers;

        Factory(Map<String, String> headers) {
            this.headers = headers;
        }

        @Override
        public FlightClientMiddleware onCallStarted(CallInfo info) {
            return new HeaderMiddleware(headers);
        }
    }
}
```
And then the construction of the client...
```java
BufferAllocator alloc = /* ... */
Location loc = /* ... */
Map<String, String> headers = /* ... */
FlightClient client = FlightClient.builder(alloc, loc)
    .intercept(new HeaderMiddleware.Factory(headers))
    .build();
```

**Comment by lidavidm** [comment]
Yes, the middleware is perfectly fine. The call option is meant just to make it easier to attach headers for a particular call.
