### ISSUE TITLE
[Python] ENH: Preserve tzinfo from datetime.time objects when contructing pa.array

### ISSUE THREAD

**Issue by mroeschke** [apache/arrow#33842]
### Describe the enhancement requested

```
In [45]: pa_array = pa.array([datetime.time(12, 0, tzinfo=datetime.timezone.utc)])

In [46]: pa_array
Out[46]:
<pyarrow.lib.Time64Array object at 0x7fb0c86045e0>
[
  12:00:00.000000
]

In [47]: pa_array.to_pylist()
Out[47]: [datetime.time(12, 0)]
```

It looks like the `tzinfo` information is currently discarded. It would be great if it were kept.

### Component(s)

Python

**Comment by AlenkaF** [comment]
The builtin `datetime.time` is converted to `time64` in Arrow (see https://arrow.apache.org/docs/python/pandas.html#time-types) and [pa.time64()](https://arrow.apache.org/docs/python/generated/pyarrow.time64.html) is not, as far as I understand, timezone aware.

The information about the timezone is stored in [pa.timestamp()](https://arrow.apache.org/docs/python/generated/pyarrow.timestamp.html) data type which works correctly:

```python
>>> dt = datetime.datetime(2023, 1, 24, 0, 12, 0, tzinfo=datetime.timezone.utc)
>>> pa.array([dt]).type
TimestampType(timestamp[us, tz=UTC])
>>> pa.array([dt]).to_pylist()
[datetime.datetime(2023, 1, 24, 0, 12, tzinfo=<UTC>)]
```

**Comment by mroeschke** [comment]
Right, this would be an enhancement request for the `time` types in Arrow to be timezone aware.

Context: In pandas I am working on supporting pyarrow backed data types in pandas working with datetime functionality. We have a `Series.dt.timetz` method that returns times + timezones of a time series, but to return this as a pyarrow backed data type the timezone information is lost.

**Comment by AlenkaF** [comment]
Well, that's a bigger change (a request for a change in the Arrow C++ format).
For this kind of changes a discussion should be opened on the [dev Mailing List](https://arrow.apache.org/community/).

Honestly, I am not sure the context you are mentioning is a good reason to change the format.

**Comment by jorisvandenbossche** [comment]
Since currently the Arrow format spec doesn't have timezone for the time type, I am going to close this as python issue. 

As Alenka mentioned, actually adding this to the spec would require a broader discussion.

**Comment by jorisvandenbossche** [comment]
> Context: In pandas I am working on supporting pyarrow backed data types in pandas working with datetime functionality. We have a `Series.dt.timetz` method that returns times + timezones of a time series, but to return this as a pyarrow backed data type the timezone information is lost.

@mroeschke if we want to preserve that functionality in pandas, I think we can probably implement that differently there? (eg let it return object dtype with datetime.time objects, as it does now for datetime64tz?)

**Comment by mroeschke** [comment]
Yeah that's probably the correct workaround in pandas

**Comment by jbrockmendel** [comment]
Just ran into this.  It's reasonable for arrow to not implement this, but I would expect the constructor to raise/warn instead of silently dropping tz info
