### ISSUE TITLE
R and -DARROW_TENSORFLOW=ON

### ISSUE THREAD

**Issue by cHYzZQo** [apache/arrow#3386]
I'm trying to build libarrow for use with both R and python. I'd like to enable -DARROW_TENSORFLOW when building but when I do that the R package won't build and gives errors about missing symbols. 

I'm guessing it's because the R package isn't setup to use the old GLIBCXX ABI that building with tensorflow requires. Is there a way to get it to build in this way?

**Comment by wesm** [comment]
The `ARROW_TENSORFLOW` option does not do anything special for R at the moment, but it does set some ABI flags which won't work in your platform: https://github.com/apache/arrow/blob/master/cpp/CMakeLists.txt#L507. 

Can you open a JIRA issue and describe what you are trying to do with R and TensorFlow and Arrow together?

**Comment by cHYzZQo** [comment]
I'm not trying to do anything with tensorflow from R specifically. What I am trying to do is build a libarrow that I can build both my python and my R packages against without losing the python / arrow / tensorflow integration.

**Comment by wesm** [comment]
I see. You'll have to propagate the compilation flags https://github.com/apache/arrow/blob/master/cpp/CMakeLists.txt#L508 when building the R package

**Comment by cHYzZQo** [comment]
Makes sense, opened #3409 to make this a config var for the R package
