### ISSUE TITLE
[Release] Java binaries are missing from artifactory

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#33878]
### Describe the bug, including details regarding any error messages, version, and platform.

When uploading binaries to [artifactory](https://apache.jfrog.io/ui/repos/tree/General/arrow) for release 11.0.0 I've realised we don't upload Java binaries to artifactory on releases:

![image](https://user-images.githubusercontent.com/639755/214811316-82aa3e20-6230-4c6b-a38a-81055f21caa9.png)

Should Java binaries be uploaded to artifactory? From my understanding all released packages should go to Artifactory + any other distribution channel.

### Component(s)

Release

**Comment by raulcd** [comment]
@kou shouldn't those artifacts be there?

**Comment by kou** [comment]
We don't use Artifactory for `.jar`s.
See "Publish Maven artifacts" in https://arrow.apache.org/docs/dev/developers/release.html#post-release-tasks for `.jar`s.

**Comment by raulcd** [comment]
ok, I thought we also should upload them to artifactory as we do with Python but I see the difference being jars are still uploaded them to apache.org when Python wheels would only be uploaded to PyPI if we would not upload them to artifactory.
I am closing this then. Thanks for clarifying.

**Comment by kou** [comment]
Yes. https://repository.apache.org/ is one of the official distribution channels: https://infra.apache.org/release-publishing.html#distribution
And  it supports distributing signature and checksums that are required for each artifact: https://infra.apache.org/release-distribution.html#sigs-and-sums
.e.g.:  https://repository.apache.org/content/repositories/staging/org/apache/arrow/arrow-memory/11.0.0/

So we can use https://repository.apache.org/ for `.jar`s.
