### ISSUE TITLE
[Go] cdata package leaks handles, difficulty debugging

### ISSUE THREAD

**Issue by zeroshade** [apache/arrow#33887]
### Describe the bug, including details regarding any error messages, version, and platform.

When the "misuse of cgo.Handle" issue was fixed for #33864, it looks like we forgot to call `free` on the malloc'd `uintptr_t` that gets used causing a memory leak which was caught by leak sanitizer when testing ADBC. 

Also, we should add `static` to the definitions of the methods in `go/arrow/cdata/arrow/helpers.h` so that they don't cause multiple definition errors if you build without optimizations for debugging.

### Component(s)

Go

**Comment by pitrou** [comment]
> Also, we should add `static` to the definitions of the methods in `go/arrow/cdata/arrow/helpers.h` so that they don't cause multiple definition errors if you build without optimizations for debugging.

Hmm, why would they? They are marked `inline` so having multiple identical definitions shouldn't be a problem...
