### ISSUE TITLE
Unable to run plasma_store on Windows OS

### ISSUE THREAD

**Issue by REASY** [apache/arrow#3391]
I'm trying to run `plasma_store`  on `Microsoft Windows [Version 10.0.17134.523] x64`, but it fails with next error:
```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Envs\py_arrow\Scripts\plasma_store.exe\__main__.py", line 9, in <module>
  File "c:\users\user\envs\py_arrow\lib\site-packages\pyarrow\__init__.py", line 167, in _plasma_store_entry_point
    _os.execv(plasma_store_executable, _sys.argv)
FileNotFoundError: [Errno 2] No such file or directory
```
[Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) shows that it looks for the files `C:\Users\User\Envs\py_arrow\Lib\site-packages\pyarrow\plasma_store_server.exe`, but can't find it (yes, I don't have that file on that path):
![image](https://user-images.githubusercontent.com/5107562/51089290-64cd6f00-179d-11e9-927e-c478c2cf21eb.png)

### My environment:
![image](https://user-images.githubusercontent.com/5107562/51089308-af4eeb80-179d-11e9-958b-58e3ab807961.png)

```
OS: Microsoft Windows [Version 10.0.17134.523] x64
Python 3.7.2
py_arrow: 0.11.1
```

**Comment by pcmoritz** [comment]
Hey Reasy,

Thanks for getting in touch! Plasma is unfortunately not supported in
Windows at the moment. Contributions are welcome in this direction, the
main challenges in porting it would be:

- Port the socket code for communication between processes to Windows
- Making sure the event loop works in Windows, we are using ae from redis
- Implement a way to ship the shared memory files between processes on
Windows (we use sendmsg/recvmsg from POSIX)

In the short term, running your application in the Windows subsystem for
Linux might work, there is a number of people who are running Ray this way
(which uses plasma for its data storage).

Best wishes,
Philipp.

**Comment by wesm** [comment]
I didn't find an issue about windows support for plasma so I opened

https://issues.apache.org/jira/browse/ARROW-4248

**Comment by mehrdadn** [comment]
I think @pcmoritz hit all the main points that I can remember... but it's been a while since I've looked at this; there might be other issues I'm unaware of or not remembering. This link may (or may not) be helpful: https://github.com/ray-project/ray/issues/631
