### ISSUE TITLE
[C++][CI] C++ / AMD64 Ubuntu 22.04 C++ ASAN UBSAN (pull_request) Cancelled after 75m

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#33920]
### Describe the bug, including details regarding any error messages, version, and platform.

**C++ / AMD64 Ubuntu 22.04 C++ ASAN UBSAN** frequently hits the timeout limit of 75 min. Does it make sense to increase the limit in the workflow file?

Examples:
https://github.com/apache/arrow/actions/runs/4035720668/jobs/6937808549
https://github.com/apache/arrow/actions/runs/4034613084/jobs/6935958187

Successful check also takes 1h 5m 4s on the current master:
https://github.com/apache/arrow/actions/runs/4038548251/jobs/6942621768

### Component(s)

Continuous Integration

**Comment by westonpace** [comment]
I agree that it is annoying.  It would be good to understand what is going on though.  The build takes 52 minutes which seems excessive. I suppose this is just because it is building with ASAN?  Is there some kind of ccache we can enable here to speed things up?

**Comment by kou** [comment]
If we disable Flight SQL, we can use system gRPC and ProtoBuf on Ubuntu 22.04.

Flight SQL requires ProtoBuf 3.15.0 or later: https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1653-L1654
ProtoBuf on Ubuntu 22.04 is 3.12.4: https://packages.ubuntu.com/search?keywords=libprotobuf-dev

**Comment by pitrou** [comment]
Then we can disable Flight SQL IMHO.

**Comment by wgtmac** [comment]
I remember the Github workflow can be triggered according to files affected by a PR. Is it a good idea to enable Flight SQL only when it files are changed?

**Comment by pitrou** [comment]
Not really, because Flight SQL can be affected by changes made elsewhere.

**Comment by pitrou** [comment]
cc @lidavidm

**Comment by lidavidm** [comment]
If we need to disable Flight SQL, then I think that's alright (we can re-enable when we bump the OS version)

**Comment by westonpace** [comment]
I took a stab at this.  Unfortunately, libprotobuf on Ubuntu only provides static libraries and doesn't contain any cmake files.  I think this means we would also need to create a `FindProtobuf.cmake` that checks if `ARROW_PROTOBUF_USE_SHARED` and, if so, then looks for the `.a` file.  Although we should maybe always be linking protobuf statically given how obnoxious it is about versioning.

Another option would be to build protobuf from source in the docker file (e.g. with `ci/scripts/install_protobuf.sh`). We could even install abseil in this way too for GCS support.

Or, an even easier option, if we disable flight, substrait, orc (already disabled), opentelemetry, and gandiva, then we remove the protobuf dependency.  This cuts the time of the job in half on my system (from 9min to ~4.5min).

Is there any preference for approach?

**Comment by kou** [comment]
> libprotobuf on Ubuntu only provides static libraries

Not correct (both of static libraries and shared libraries are provided):
* `liprotobuf23`: https://packages.ubuntu.com/jammy/amd64/libprotobuf23/filelist includes `libprotobuf.so.23*`
* `libprotobuf-dev`: https://packages.ubuntu.com/jammy/amd64/libprotobuf-dev/filelist includes `libprotobuf.{a,so}`

> doesn't contain any cmake files

Correct.

> I think this means we would also need to create a `FindProtobuf.cmake` that checks if `ARROW_PROTOBUF_USE_SHARED` and, if so, then looks for the `.a`

We already have `FindProtobufAlt.cmake` and it did that. :-)

The following patch will disable Flight SQL only in ASAN job:

```diff
diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
index 4959197fcd..523e6fec5d 100644
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -66,8 +66,11 @@ jobs:
           - ubuntu-cpp-sanitizer
         include:
           - image: conda-cpp
+            docker-run-options:
             title: AMD64 Conda C++
           - image: ubuntu-cpp-sanitizer
+            docker-run-options: >-
+              -e ARROW_FLIGHT_SQL=OFF
             title: AMD64 Ubuntu 22.04 C++ ASAN UBSAN
     env:
       UBUNTU: "22.04"
@@ -96,7 +99,7 @@ jobs:
         run: |
           sudo sysctl -w kernel.core_pattern="core.%e.%p"
           ulimit -c unlimited
-          archery docker run ${{ matrix.image }}
+          archery docker run ${{ matrix.docker-run-options }} ${{ matrix.image }}
       - name: Docker Push
         if: success() && github.event_name == 'push' && github.repository == 'apache/arrow'
         env:
```

**Comment by pitrou** [comment]
> The following patch will disable Flight SQL only in ASAN job:

Perhaps we should do such tweaks in `docker-compose.yml` instead? It would make it easier to reproduce jobs locally...

**Comment by westonpace** [comment]
> The following patch will disable Flight SQL only in ASAN job:

I think you need to disable flight in addition to flight SQL.  Also, we will need to add libprotobuf to the docker image (it is only installing libprotobuf-dev)

**Comment by kou** [comment]
> you need to disable flight in addition to flight SQL.

Ah, we should use `ARROW_FLIGHT_SQL` not `ARROW_WITH_GRPC` in https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1653-L1654 .

> we will need to add libprotobuf to the docker image (it is only installing libprotobuf-dev)

We don't need it because `libprotobuf` is installed automatically as a `libprotobuf-dev` dependency.

**Comment by kou** [comment]
> Perhaps we should do such tweaks in `docker-compose.yml` instead? It would make it easier to reproduce jobs locally...

OK. #34014 uses this approach.
