### ISSUE TITLE
[CI] CI run arrow-threading-utility-test failed on TestRunSynchronously.ContinueAfterExternal

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#33943]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/4051208773/jobs/6969300361

When running `arrow-threading-utility-test` under 
`C++ / AMD64 Windows MinGW MINGW64 C++` in my patch ( https://github.com/apache/arrow/pull/33942 ), the test failed in `arrow-threading-utility-test`. My patch only modify some unrelated logic.

### Component(s)

C++, Continuous Integration

**Comment by mapleFU** [comment]
@westonpace Mind take a look?

**Comment by westonpace** [comment]
> @westonpace Mind take a look?

I do not mind.  Please feel free to take a look.  My hunch is that this might be https://github.com/apache/arrow/issues/30272 but it would be good to verify.
