### ISSUE TITLE
[C++] Add Rank chunked array benchmarks

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#33957]
### Describe the enhancement requested

Once GH-32050 is in, it should be very easy to add benchmarks for Rank on chunked arrays.

### Component(s)

C++

Depends on:
- [x] GH-32050

**Comment by dinimar** [comment]
@pitrou I'm new at benchmarks in this project. Could you please explain which file should be changed and provide some examples of benchmarks?

**Comment by pitrou** [comment]
@dinimar The code is in https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/kernels/vector_sort_benchmark.cc . You'll find existing examples there and it should be pretty easy to build on them.

@benibus can also help in case you're stuck.

**Comment by benibus** [comment]
@dinimar That's correct - you shouldn't need additional tests (generally speaking).
