### ISSUE TITLE
[Python] DataFrame Interchange Protocol

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#33982]
### Describe the enhancement requested

This is an umbrella issue for all tasks connected to the Dataframe Interchange Protocol.
https://data-apis.org/dataframe-protocol/latest/index.html

- [x] https://github.com/apache/arrow/issues/33346
- [x] https://github.com/apache/arrow/issues/33926
- [x] https://github.com/apache/arrow/issues/33980
- [x] https://github.com/apache/arrow/issues/33984
- [x] Implement DataFrame Interchange Protocol Compliance Suite https://github.com/data-apis/dataframe-interchange-tests/pull/21

### Component(s)

Python

**Comment by stinodego** [comment]
I noticed that there is currently no support yet in the `from_dataframe` function for boolean columns with bitsize 1. Is there an issue for implementing this?

```python
import polars as pl
import pyarrow as pa
import pyarrow.interchange

df = pl.Series("a", [True, False], dtype=pl.Boolean).to_frame()
dfi = df.__dataframe__()
pa.interchange.from_dataframe(dfi)
# NotImplementedError: Conversion for (<DtypeKind.BOOL: 20>, 1, 'b', '=') is not yet supported.
```

**Comment by AlenkaF** [comment]
No, there is no issue - I think we missed it as we didn't have the use case then.
Will open a new issue to implement it, thanks!

**Comment by AlenkaF** [comment]
Closing this issue as all tasks are done.
