### ISSUE TITLE
[Docs] Expand text around mailing list tags in Apache Arrow Community Page

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#33989]
### Describe the enhancement requested

The user and dev mailing lists use a variety of tags to help create some order. These tags include:

- Language specific tags (e.g., C++)
- Component-specific tags (e.g., Flight)
- Discuss/RFC
- Vote/Result

The "Mailing lists" section of [Apache Arrow Community](https://arrow.apache.org/community/) only mentions using one or more tags such as [C++] or [Python] but could probably be more comprehensive and could be expanded to cover all categories above. In addition, tags like [Vote] are part of our formal process and we should let users (1) know that and (2) tell them how to contribute (e.g., by replying "+1 (non-binding").

This section should be expanded so we have something more comprehensive. 

### Component(s)

Documentation

**Comment by amoeba** [comment]
take

**Comment by abandy** [comment]
take

**Comment by kou** [comment]
@abandy Please comment on #20484 not here.

**Comment by abandy** [comment]
Ah, gotcha, wil do. Thanks!
