### ISSUE TITLE
Is a bit width of zero supported for Rle/Bp encoding of dictionary indices?

### ISSUE THREAD

**Issue by crboth** [apache/arrow#3400]
I'm designing a custom parquet decoder and some of the generated test data I'm working with is giving me trouble. 
The page data itself is:
`0200 0000 5801 0058`
aka Definition Section of 2 bytes, `5801`
followed by the RLE_DICTIONARY bit width of 0,
followed by a VLQ int encoding the RLE count, (0x58 => 44) but without any data following the VLQ

I was wondering if this was an explicitly supported edge case in which 0 is a valid bitwidth, and that the decoder should not expect any data following the RLE VLQ for this case.

It doesn't appear to be valid according to the [Encodings.MD](https://github.com/apache/parquet-format/blob/master/Encodings.md) but this was generated by, and correctly parsed by, two different off the shelf software implementations I'm using for reference.

**Comment by xhochy** [comment]
@crboth This question is better asked on the parquet mailing list dev@parquet.apache.org (subscribe first by mailing to dev-subscribe@parquet.apache.org).
