### ISSUE TITLE
[Python] Incorrect return type for FlightStreamReader.read_chunk()

### ISSUE THREAD

**Issue by ravjotbrar** [apache/arrow#34017]
### Describe the bug, including details regarding any error messages, version, and platform.

The documentation for using the FlightStreamReader to read_chunk currently states that this method returns a RecordBatch. The return type is actually FlightStreamChunk, which then contains an attribute called data that is of type RecordBatch. 

When trying to click "Edit this Page", I get a 404 error: https://github.com/apache/arrow/edit/master/docs/source/python/generated/pyarrow.flight.FlightStreamReader.rst

### Component(s)

Documentation, Python

**Comment by AkashS20** [comment]
Hi, I would like to contribute to this. I'm new to open source so if you could please guide me on what is to be done and what are the pre-requisites for the same, it will be of great help.

**Comment by nph** [comment]
@lidavidm @jjerphan FYI the [docs](https://arrow.apache.org/docs/python/generated/pyarrow.flight.FlightStreamReader.html#pyarrow.flight.FlightStreamReader.read_chunk) for `FlightStreamReader.read_chunk` are still wrong. They currently show that `read_chunk` returns `tuple[FlightStreamChunk, Buffer | None]`, however it returns only a `FlightStreamChunk` instance. The `FlightStreamChunk` class supports tuple [unpacking](https://github.com/apache/arrow/blob/db19a358cdf2b550b741fc7574dea38a6e32261b/python/pyarrow/_flight.pyx#L973) into a `tuple[RecordBatch, Buffer | None]`, which is presumably why the original docstring showed this as the return type.

Shall I open a new issue for this?

**Comment by jjerphan** [comment]
@nph: feel free to open a PR, yes!
