### ISSUE TITLE
[Docs] Version warning about viewing old docs doesn't work for versions >= 10

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#34023]
Currently, if viewing older docs (eg https://arrow.apache.org/docs/9.0/python/index.html), you get a warning about that you are not viewing the latest docs. However, now that the newest "old" docs (those that are stored in a version/ subdirectory) is 10.0, that doesn't seem to work for this version (eg https://arrow.apache.org/docs/10.0/python/index.html doesn't show the warning)

My first guess is that it's caused by a bump in number of characters in the major version number (7, 8, 9 etc -> 10), and that this if check no longer works as expected because of that:

https://github.com/apache/arrow/blob/177a0d4400e61f44dbd045ce05150bba28dd1d74/docs/source/_static/versionwarning.js#L104-L105

**Comment by AlenkaF** [comment]
I have created a PR to correct the current state of the documentation https://github.com/apache/arrow-site/pull/312

Note from that PR:

> Also, additional copying of the versionwarning.js file seems to happen with the release. Currently there are three versions of the same document:
> - docs/_static/versionwarning.js
> - docs/dev/_static/versionwarning.js
> - docs/10.0/_static/versionwarning.js
>
> Second and third should be redundant and are removed with this PR. I will create a separate issue on the apache/arrow repo to research and correct how the versionwarning.js file is being copied.

I plan to create a separate PR to correct the versionwarning.js file in the apache/arrow repo after the PR on apache/arrow-site is merged and the warnings are working well.

**Comment by AlenkaF** [comment]
The issue about multiple copies of `versionwarning.js` in `apache/arrow-site`: https://github.com/apache/arrow/issues/34160
