### ISSUE TITLE
[C++] Arrow IPC buffer compression forces the use of default_memory_pool

### ISSUE THREAD

**Issue by marin-ma** [apache/arrow#34025]
### Describe the bug, including details regarding any error messages, version, and platform.

In the CompressBuffer, it calls AllocateBuffer without passing the memory_pool argument https://github.com/apache/arrow/blob/177a0d4400e61f44dbd045ce05150bba28dd1d74/cpp/src/arrow/ipc/writer.cc#L183

Is there any special reason why it doesn't use the memory_pool in ipc write options? In our use case, we want to manage the memory allocation and avoid using the default memory pool.

### Component(s)

C++

**Comment by wjones127** [comment]
> Is there any special reason why it doesn't use the memory_pool in ipc write options?

This is a bug. There are some places where we may have forgotten to pass down the memory pool. I'm working right now on a PR that will allow us to assert in tests that all allocations happen on the provided memory pool.
