### ISSUE TITLE
[Java] BufferAllocator allocated memory always increase

### ISSUE THREAD

**Issue by engimatic** [apache/arrow#34021]
### Describe the usage question you have. Please include as many useful details as  possible.

When I use arrow flight like this,and call do_get method many times,allocator allocated memory always increase.How and when should I do?
```
try (BufferAllocator allocator = new RootAllocator()) {
            // Server
            try (final CookbookProducer producer = new CookbookProducer(allocator, location);
                 final FlightServer flightServer = FlightServer.builder(allocator, location, producer).build()) {
                try {
                    flightServer.start();
                    System.out.println("S1: Server (Location): Listening on port " + flightServer.getPort());
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        }
```

### Component(s)

Java

**Comment by lidavidm** [comment]
Have you looked at the documentation on debugging memory leaks? https://arrow.apache.org/docs/java/memory.html#debugging-memory-leaks-allocation

**Comment by engimatic** [comment]
> Have you looked at the documentation on debugging memory leaks? https://arrow.apache.org/docs/java/memory.html#debugging-memory-leaks-allocation

I didn't find where the error was. It is obvious that the error caused by netty and direct memory with the error message "failed to allocate of direct memory" .But when I use jvisualvm, the buffer pools memory used was  just 16Bytes.

**Comment by engimatic** [comment]
Whenever my client consumption is slow, The memory of server will continue to grow.

**Comment by lidavidm** [comment]
Ok, that is expected. gRPC enqueues messages and doesn't apply backpressure. You have to poll isReady to throttle the producer. (Note that due to a design flaw in gRPC, this will artificially limit your bandwidth on fast connections.)

If the memory doesn't go back down, that is not expected. (Though, it depends on how you are measuring; the Netty allocator may pool allocations instead of actually freeing them.)

**Comment by engimatic** [comment]
> Ok, that is expected. gRPC enqueues messages and doesn't apply backpressure. You have to poll isReady to throttle the producer. (Note that due to a design flaw in gRPC, this will artificially limit your bandwidth on fast connections.)
> 
> If the memory doesn't go back down, that is not expected. (Though, it depends on how you are measuring; the Netty allocator may pool allocations instead of actually freeing them.)

How to poll isReady to throttle the producer?

**Comment by lidavidm** [comment]
The implementation of methods like getStream should poll `listener.isReady`:

https://github.com/apache/arrow/blob/ef21008d4e253188092f3c54ad4f7e83aac8d79e/java/flight/flight-core/src/main/java/org/apache/arrow/flight/OutboundStreamListener.java#L30-L37

**Comment by engimatic** [comment]
> The implementation of methods like getStream should poll `listener.isReady`:
> 
> https://github.com/apache/arrow/blob/ef21008d4e253188092f3c54ad4f7e83aac8d79e/java/flight/flight-core/src/main/java/org/apache/arrow/flight/OutboundStreamListener.java#L30-L37

Thanks, when I use isReady method, I have already resolved this problem in doget.
But when I test this case in doaction, also encountered the same issue.So how do I throttle the producer in doaction method?

**Comment by lidavidm** [comment]
Hmm, it appears doAction is missing that. If you want to file a new issue, that could be addressed.

**Comment by engimatic** [comment]
use isReady
