### ISSUE TITLE
[Python][Docs] Fix docstring violations for Table.drop

### ISSUE THREAD

**Issue by Fokko** [apache/arrow#34037]
### Describe the bug, including details regarding any error messages, version, and platform.

I saw this in when updating some docstrings:
```
pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

Total number of docstring violations: 3
```

I think we should deprecate `drop` in favor of `drop_columns`.

### Component(s)

Python

**Comment by vibhatha** [comment]
Seems like the same bug is reported here https://github.com/apache/arrow/issues/34041 
It will be addressed in that issue.
