### ISSUE TITLE
[C++][FlightRPC] Make warning about do_action stream less noisy

### ISSUE THREAD

**Issue by marsupialtail** [apache/arrow#34047]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi @lidavidm pyarrow 11.0 is breaking my arrow flight related code. I think you have a good sense what the problem is: /arrow/cpp/src/arrow/status.cc:137: DoAction result was not fully consumed: Cancelled: Flight cancelled call, with message: CANCELLED. Detail: Cancelled

I seem to be fully consuming the DoAction results, e.g. here is my code:
```
for result in self.flight_client.do_action(action):
      assert result.body.to_pybytes().decode("utf-8") == "True"
```

Can you give some pointers on how to use Python to get results from do_action?

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
This is just a warning, it shouldn't break anything.

Otherwise: just try list(do_action(...))

On Sun, Feb 5, 2023, at 00:27, Ziheng Wang wrote:
> 
> 
> Describe the bug, including details regarding any error messages, version, and platform.
> 
> Hi @lidavidm <https://github.com/lidavidm> pyarrow 11.0 is breaking my arrow flight related code. I think you have a good sense what the problem is: /arrow/cpp/src/arrow/status.cc:137: DoAction result was not fully consumed: Cancelled: Flight cancelled call, with message: CANCELLED. Detail: Cancelled
> 
> I seem to be fully consuming the DoAction results, e.g. here is my code:
> 
> `for result in self.flight_client.do_action(action):
>       assert result.body.to_pybytes().decode("utf-8") == "True"
`

**Comment by marsupialtail** [comment]
Can I disable this warning?

**Comment by lidavidm** [comment]
Does `list(do_action(...))` work?

I think a PR to remove the warning or change it to DEBUG level would be reasonable, it's probably a bit aggressive as-is.

**Comment by marsupialtail** [comment]
OK doing list() seems to work. But I still think this shouldn't be the default :-)

**Comment by lidavidm** [comment]
It was basically a conflict between people who want this to be a proper iterator (in which case gRPC really wants you to drain the stream) and the original behavior which was to eagerly materialize the list.

@marsupialtail do you want to leave this open? We could change it to not warn by default, at least.
