### ISSUE TITLE
[Python] Inconsistent partition value encoding

### ISSUE THREAD

**Issue by vdytyniak-exos** [apache/arrow#34049]
### Describe the bug, including details regarding any error messages, version, and platform.

The following code produces different partition value in the path:
MacOs: data/hour=2020-01-01 01:00:00
Ubuntu: data/hour=2020-01-01%2001%3A00%3A00

```
import pyarrow as pa
import pyarrow.parquet as pq

table = pa.table(
    {
        'hour': ['2020-01-01 01:00:00'],
        'animal': ["Flamingo"],
    },
)

pq.write_to_dataset(table, root_path='data', partition_cols=['hour'])
```

In production code we use S3FileSystem and it leads to a problem when users use the same code to save the data, but it stores the data in a different place.

pyarrow: 11.0.0

### Component(s)

Python

**Comment by westonpace** [comment]
Can you confirm that both the mac and ubuntu systems are using pyarrow 11.0.0?  This was a change introduced between 10.0.0 and 11.0.0 but I wouldn't expect it to be os-specific.

**Comment by vdytyniak-exos** [comment]
Sorry, my bad. I thought I have upgraded on MacOS as well. Thanks.
