### ISSUE TITLE
[C++][Parquet] Write parquet page index

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#34053]
### Describe the enhancement requested

Parquet C++ reader has supported reading page index from file. Now it is time to implement the write logic.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
> Just curious, would page index optimization be added to the Arrow interface in the long term after the low level reader/writer are finished? I'd expect that also requires change the I/O unit from row group to page.

Sounds ok, but seems it requires high performance IO-merging and requires some benchmarks/testing

**Comment by XinyuZeng** [comment]
> > Just curious, would page index optimization be added to the Arrow interface in the long term after the low level reader/writer are finished? I'd expect that also requires change the I/O unit from row group to page.
> 
> Sounds ok, but seems it requires high performance IO-merging and requires some benchmarks/testing

There is already IO coalesce, but its range unit is ColumnChunk . https://github.com/apache/arrow/blob/39bad5442c6447bf07594b09e4b29118b3211460/cpp/src/arrow/io/caching.cc#L175

Perhaps it is not necessary to breakdown the IO to page, since Parquet-format states ColumnChunk is the IO unit.

**Comment by mapleFU** [comment]
> Perhaps it is not necessary to breakdown the IO to page, since Parquet-format states ColumnChunk is the IO unit.

Yes, although the standard says so, but we can use it. Currently parquet-cpp implemention use both Page-IO and Chunk-IO:

* arrow can use `ReadRangeCache` to serving chunk-level io, and, however, I don't think it provides an good performance. And currently,  it will read whole buffer, and caching them in a `::arrow::io::BufferReader`
* If no cache is used, an `ArrowInputStream` would be created directly on input, and `PageReader` will try do create read buffer page-by-page

Besides, I think currently the implemention of `ReadRangeCache` is naive. I'm not sure it will works well.

**Comment by wgtmac** [comment]
Page index is a pretty new concept in the history of parquet specs. In the old days when page index is unavailable, the I/O unit is always column chunk because we can only drop row groups based on the column statistics. Once page index is supported, finer-grained I/O unit is a must if we want to leverage page index to efficiently skip specific pages. @XinyuZeng
