### ISSUE TITLE
how to release GParquetArrowFileReader

### ISSUE THREAD

**Issue by quintin-lee** [apache/arrow#34064]
### Describe the usage question you have. Please include as many useful details as  possible.

Hello，

I am reading the documentation of https://arrow.apache.org/docs/c_glib/parquet-glib/. During the process, I found the question in the code below :
```
GParquetArrowFileReader *reader =
    gparquet_arrow_file_reader_new_path(filename, &error);
```
I am wondering how to release memory during the process, especially how to release the pointer of  ` reader`.

Best Regards

### Component(s)

C, GLib

**Comment by kou** [comment]
All Apache Arrow GLib objects can be released by `g_object_unref()` such as `g_object_unref(reader)`.

See also: https://docs.gtk.org/gobject/method.Object.unref.html

**Comment by quintin-lee** [comment]
> 

OK，Thank you.
