### ISSUE TITLE
[Go] pqarrow.NewSchemaManifest creates wrong schema field for array object fields

### ISSUE THREAD

**Issue by orianED** [apache/arrow#34101]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm using the arrow V11 package for reading parquet files.

Calling `pqarrow.NewFileReader` creates the schema manifest using `pqarrow.NewSchemaManifest`.
When dealing with objects array fields, the record readers create an array of primitives of the first field in the object. for example:
[[“a”:1, “b”:2},[“a”:3, “b”:4}] -> [1,3]

diving into the code I found this in `pqarrow/schema.go -> listToSchemaField`:
```Go
listGroup := listNode.(*schema.GroupNode)
if listGroup.NumFields() == 1 && (listGroup.Name() == "array" || strings.HasSuffix(listGroup.Name(), "_tuple")) {
	// list of primitive type
	if err := groupToStructField(listGroup, currentLevels, ctx, out, &out.Children[0]); err != nil {
		return err
	}
} else {
	if err := nodeToSchemaField(listGroup.Field(0), currentLevels, ctx, out, &out.Children[0]); err != nil {
		return err
	}
}
```

At this stage, the listGroup is the inner dictionary. Assuming the above example listGroup.NumFields() returns 2 and the schema node is converted to a primitive field taking the first field in the group (else clause).
It also seems like the `groupToStructField` function is more suitable for this case.

changing the condition solves the problem and the field is being read as expected.
```Go
listGroup := listNode.(*schema.GroupNode)
if listGroup.NumFields() != 1 && (listGroup.Name() == "array" || strings.HasSuffix(listGroup.Name(), "_tuple")) {
	if err := groupToStructField(listGroup, currentLevels, ctx, out, &out.Children[0]); err != nil {
		return err
	}
} else {
	// list of primitive type
	if err := nodeToSchemaField(listGroup.Field(0), currentLevels, ctx, out, &out.Children[0]); err != nil {
		return err
	}
}
```

Can you take a look and fix it? the current state is misleading as the user might think this is the real value

### Component(s)

Go, Parquet

**Comment by orianED** [comment]
@zeroshade currently I can't share such files due to restricted data.
this is the schema of the problematic field:
```  
optional group field_id=-1 answers (List) {
    repeated group field_id=-1 array {
      optional byte_array field_id=-1 type (String);
      optional byte_array field_id=-1 rdata (String);
      optional byte_array field_id=-1 class (String);
    }
  }
```
is it something you can work with? if not I'll try to create a sample file like this

**Comment by zeroshade** [comment]
Thanks @orianED I was able to track down the issue and filed a PR with the fix for it. The PR is linked here.
