### ISSUE TITLE
[C++] Upgrade zstd to v1.5.4

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#34113]
### Describe the enhancement requested

Zstd has release it's latest version, v1.5.4, which containing a lots of performance improvement under x86 and aarch64. The release note can be seen here: https://github.com/facebook/zstd/releases/tag/v1.5.4

Notice that arrow is using zstd v1.5.2, can we upgrade it to v1.5.4?

### Component(s)

C++

**Comment by mapleFU** [comment]
@kou @pitrou What do you think of this? If it's ok, I can help upgrade it

**Comment by kou** [comment]
Yes, please!
