### ISSUE TITLE
[C++] Minimal build failed in crossbow because of zstd v1.5.4 requires CMake v3.18

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#34148]
### Describe the bug, including details regarding any error messages, version, and platform.

After patch https://github.com/apache/arrow/pull/34114 is merged, crossbow CI was broken: https://github.com/ursacomputing/crossbow/actions/runs/4153851721/jobs/7185765610#step:3:1131

This is because zstd v1.5.4 introduce [CheckLinkerFlag](https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html), which is introduced in https://github.com/facebook/zstd/pull/3392 . And our crossbow CI install cmake 3.16, which didn't support it.

### Component(s)

C++, Developer Tools

**Comment by mapleFU** [comment]
@kou

**Comment by mapleFU** [comment]
Also an issue here: https://github.com/facebook/zstd/issues/3500

**Comment by kou** [comment]
We can require CMake 3.13 or 3.16 since 12.0.0 (see #33800 ) but it doesn't solve this.

Could you add a CMake version check like https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1539-L1542 ?

**Comment by mapleFU** [comment]
@kou https://github.com/apache/arrow/pull/34149/files

**Comment by kou** [comment]
@mapleFU Zstandard 1.5.5 will be released soon: https://github.com/facebook/zstd/pull/3585
It will include https://github.com/facebook/zstd/pull/3510 .
Could you try upgrading Zstandard again?

**Comment by mapleFU** [comment]
> facebook/zstd#3585

Sure, I'm subscribing it's release. Once it send a release, I'll send a patch for it
