### ISSUE TITLE
Unable to send email to mailing list.

### ISSUE THREAD

**Issue by Shaheer-Ahmd** [apache/arrow#34141]
### Describe the bug, including details regarding any error messages, version, and platform.

Sending an email to `dev@arrow.apache.org` gives the following error.
![image](https://user-images.githubusercontent.com/110221120/218259505-a8552f1a-32c7-450f-9a6e-87f9e58405d9.png)

### Component(s)

Other

**Comment by kou** [comment]
Could you show raw e-mail you sent?

**Comment by Shaheer-Ahmd** [comment]
> Could you show raw e-mail you sent?

![Screenshot_20230212-092817.png](https://user-images.githubusercontent.com/110221120/218293025-1e52cc95-0acd-4b31-aa13-d0c04bf6921a.png)

**Comment by kou** [comment]
Could you show the source of the e-mail not rendered one?

**Comment by Shaheer-Ahmd** [comment]
I am not sure if I understand what you mean by "source of the email". Could you kindly elaborate?

**Comment by kou** [comment]
It depends on your mail client. For example, Gmail case: https://support.google.com/mail/answer/29436

I want to see a text like the following:

```text
Subject: Getting Issues ...
From: ...
To: dev@arrow.apache.org
...

I am a beginner ...
```

**Comment by Shaheer-Ahmd** [comment]
> I want to see a text like the following:





```
Message Id:  <16361173-3F67-40DB-83CD-444BCCFE8B68@hxcore.ol>
Created at:  Sat, Feb 4, 2023 at 11:22 PM (Delivered after 14 seconds)
From:  Shaheer Ahmad <shaheerahmad57575@gmail.com>
To:   "dev@arrow.apache.org" <dev@arrow.apache.org>
Subject:  Getting Issues during build cpp libraries.

```

**Comment by Shaheer-Ahmd** [comment]
Return-Path: <shaheerahmad57575@gmail.com>
Received: from Shaheer ([2400:adc5:16b:2d00:958c:d38e:150a:664e])
        by smtp.gmail.com with ESMTPSA id k6-20020adfb346000000b0027cb20605e3sm4957551wrd.105.2023.02.04.10.23.02
        for <dev@arrow.apache.org>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 04 Feb 2023 10:23:03 -0800 (PST)
MIME-Version: 1.0
Date: Sat, 4 Feb 2023 23:22:49 +0500
From: Shaheer Ahmad <shaheerahmad57575@gmail.com>
Subject: Getting Issues during build cpp libraries.
Thread-Topic: Getting Issues during build cpp libraries.
Message-ID: <16361173-3F67-40DB-83CD-444BCCFE8B68@hxcore.ol>
To: "dev@arrow.apache.org" <dev@arrow.apache.org>
Content-Type: multipart/related; boundary="_86DB2D15-1A58-4761-BD5A-FA22049C1209_"

--_86DB2D15-1A58-4761-BD5A-FA22049C1209_
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="utf-8"

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40"><head><meta http-equiv=3DContent-Type content=
=3D"text/html; charset=3Dutf-8"><meta name=3DGenerator content=3D"Microsoft=
 Word 15 (filtered medium)"><style></style></head><body lang=3Den-PK link=3Dblue vlink=3D"#954F72" style=3D=
'word-wrap:break-word'><div class=3DWordSection1><p class=3DMsoNormal><span=
 lang=3DEN-US>I am a beginner in opensource contributions and I am followin=
g the guide to build the arrow=E2=80=99s source code. Following the steps, =
I installed the requirements by vcpkg, install cmake and ninja-debug to bui=
ld using a preset and finally when I passed the command =E2=80=9Ccmake =E2=
=80=93build .=E2=80=9D within =E2=80=9Carrow/cpp=E2=80=9D directory (as tol=
d in the guide), the following error arises.<o:p></o:p></span></p><p class=
=3DMsoNormal><img width=3D515 height=3D180 style=3D'width:5.3666in;height:1=
.875in' id=3D"Picture_x0020_3" src=3D"cid:image003.png@01D938EF.98CA1520"><=
/p><p class=3DMsoNormal>Any help would be appreciated!</p><p class=3DMsoNor=
mal><o:p>&nbsp;</o:p></p><p class=3DMsoNormal>Sent from <a href=3D"https://=
go.microsoft.com/fwlink/?LinkId=3D550986">Mail</a> for Windows</p><p class=
=3DMsoNormal><o:p>&nbsp;</o:p></p></div></body></html>
--_86DB2D15-1A58-4761-BD5A-FA22049C1209_
Content-Type: image/png; name="46CEB29392EE440D81FC4B31AAA31C1E.png"
Content-ID: <image003.png@01D938EF.98CA1520>
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="46CEB29392EE440D81FC4B31AAA31C1E.png"


--_86DB2D15-1A58-4761-BD5A-FA22049C1209_--

**Comment by kou** [comment]
Thanks.

Could you try disabling a HTML e-mail feature in your mail client?

**Comment by bkietz** [comment]
@Shaheer-Ahmd should we close this issue?

**Comment by kou** [comment]
Succeeded: https://lists.apache.org/thread/93kyn8dwx720hb97c6sorz1rj3m0gsvr
