### ISSUE TITLE
[C++][Parquet] ColumnWriter avoids splitting a record into different pages 

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#34142]
### Describe the enhancement requested

For now ColumnWriter determines page boundary solely based on the buffered page size. This can lead to a record being split into different pages. Although writing via arrow::Table or arrow::RecordBatch guarantee that a record will not span across pages, we should add a new writer properties to explicitly to avoid that in order to implement writing page index.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
Does split the row into different page breaks the standard?

Just curious, assume a huge `list<string>`, containing lots of data. Should it be stored in one page?

**Comment by wgtmac** [comment]
> Does split the row into different page breaks the standard?
> 
> Just curious, assume a huge `list<string>`, containing lots of data. Should it be stored in one page?

Only data page v1 allows a record to span more than one pages. However, data page v2 and offset index enforces that a record cannot be split into pages. Please check: https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L919

**Comment by mapleFU** [comment]
Seems true. It really impressed me... But I wonder whether there any implemention don't use row to split PAGE_V1?
