### ISSUE TITLE
[Docs][Release] Multiple copies/versions of versionwarning.js

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#34160]
### Describe the bug, including details regarding any error messages, version, and platform.

There are currently three versions of the `versionwarning.js` file in apache/arrow-site:

- docs/_static/versionwarning.js
- docs/dev/_static/versionwarning.js
- docs/10.0/_static/versionwarning.js

and the only one needed should be `docs/_static/versionwarning.js`:

- https://github.com/apache/arrow-site/blob/3d617f38ecc8522a6937715ea53eb26fe5f87066/docs/8.0/index.html#L4862
- https://github.com/apache/arrow-site/blob/3d617f38ecc8522a6937715ea53eb26fe5f87066/docs/developers/python.html#L5471

I think `docs/10.0/_static/versionwarning.js` is being copied with the release and should be removed in the process. The other one I am not sure about.

### Component(s)

Documentation

**Comment by jorisvandenbossche** [comment]
I am personally not sure if this is necessarily a problem. Yes, those files are not used and so _could_ be removed. But those files are also tiny compared to the full docs, and don't really do any harm of being there (except for bothering maintainers ;)).

We also repeat many other files for each version of the docs, and for example also the versions.json file is included in each version of the docs, while they all point to the main one in `/docs/_static` as well.

**Comment by AlenkaF** [comment]
Thanks, that is good to know!
I feel the strongest for the maintainers burden - not huge, but easy to get confused about it.

Am OK with closing this issue though 👍

**Comment by jorisvandenbossche** [comment]
Yes, but updating scripts to remove those files automatically (making this script a bit more complex) also has some maintenance cost (maybe not that big though).

**Comment by AlenkaF** [comment]
That is true!

**Comment by kou** [comment]
I close this.
