### ISSUE TITLE
[Python] Build instructions don't work

### ISSUE THREAD

**Issue by judahrand** [apache/arrow#34240]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm following the build instructions for Python but get the following error:

```
CMake Error at CMakeLists.txt:268 (find_package):
        By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Arrow", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "Arrow" with any of
        the following names:
      
          ArrowConfig.cmake
          arrow-config.cmake
      
        Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
        "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
        provides a separate development package or SDK, be sure it has been
        installed.
```

### Component(s)

Python

**Comment by judahrand** [comment]
The above error is from following these docs:
https://github.com/apache/arrow/blob/main/docs/source/developers/python.rst

**Comment by kou** [comment]
Could you show all command lines what you used and outputs of them?

FYI: https://arrow.apache.org/docs/dev/developers/python.html is the rendered version.

**Comment by jorisvandenbossche** [comment]
@judahrand seeing your PR, has this issue been resolved with https://github.com/apache/arrow/pull/34234#issuecomment-1436340748 ? Or do you still have another build issue?
