### ISSUE TITLE
[C++] Can't access parquet statistics on binary columns

### ISSUE THREAD

**Issue by zilder** [apache/arrow#3424]
Hi,

I'm trying to use per-column statistics (min/max values) to filter out row groups while reading parquet file. But I don't see statistics built for binary columns. I noticed that `ApplicationVersion::HasCorrectStatistics()` discards statistics that have sort order `UNSIGNED` and haven't been created by `parquet-cpp`. As I understand there used to be some issues in `parquet-mr` before. But do they still persist?

For example, I have parquet file created with `parquet-mr` version 1.10, it seems to have correct min/max values for binary columns. And `parquet-cpp` works fine for me if I remove this code from `HasCorrectStatistics()` func:

```
    if (SortOrder::SIGNED != sort_order && !max_equals_min) {
      return false;
    }
```

**Comment by sumerman** [comment]
AFAICT this was a year ago https://github.com/apache/parquet-mr/commit/c6764c4a0848abf1d581e22df8b33e28ee9f2ced

**Comment by wesm** [comment]
Can you please open a JIRA issue? @majetideepak worked on this so should be able to help

**Comment by sumerman** [comment]
Ok. Which one of the two? Arrow or Parquet?

**Comment by zilder** [comment]
Created an issue in Arrow project:
https://issues.apache.org/jira/browse/ARROW-4293

**Comment by wesm** [comment]
This should be in PARQUET. I'll move the issue

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/PARQUET-1494
