### ISSUE TITLE
[Docs][Dev] Update git links/branches from master to main for external projects

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#34257]
### Describe the enhancement requested

We have still use `master` as a branch in a lot of places for external dependencies like numpy that have already updated their default branch to main. We should update our code to.

### Component(s)

Developer Tools, Documentation

**Comment by R-JunmingChen** [comment]
Hi, could you please assign this issue to me, I am interested in arrow and would like to contribute to it.
