### ISSUE TITLE
[Python] Pyarrow throw illegal instruction immediately on import on some hardware platforms.

### ISSUE THREAD

**Issue by abcbarryn** [apache/arrow#34268]
### Describe the bug, including details regarding any error messages, version, and platform.

Every version of pyarrow I have tried so far from the latest version back to version 3.0.0 exits with an illegal instruction after installation as soon as I execute:
import pyarrow

### Component(s)

Python

**Comment by abcbarryn** [comment]
I was simply running pip install pyarrow, it appears to build and install fine on the affected systems, but that as soon as you try to import it, it throws an illegal instruction.
I went to the trrouble of installing Anaconda and ran: conda install pyarrow
I got the same result on this system:

(base) static1:~ # python
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Illegal instruction
(base) static1:~ #

**Comment by abcbarryn** [comment]
CPU info:
vendor_id : GenuineIntel
cpu family : 6
model : 15
model name : Intel(R) Xeon(R) CPU 5160 @ 3.00GHz
stepping : 6
microcode : 0xd2
cpu MHz : 3000.116
cache size : 4096 KB
4 CPUs with 2 cores each

Linux static1 3.16.7-48-desktop https://github.com/streamlit/streamlit/pull/1 SMP PREEMPT Wed Oct 26 18:09:22 UTC 2016 (8c027f6) x86_64 GNU/Linux

glibc-2.18-4.44.1.x86_64

gcc version 7.1.1 20170607 [gcc-7-branch revision 248970] (SUSE Linux)

**Comment by abcbarryn** [comment]
I have tried the following python versions: 3.9.4, 3.9.13, 3.9.16, and 3.11 with the same result.

**Comment by assignUser** [comment]
The pyarrow wheels are compiled assuming SSE4.2 is available. You CPU is quite old and does not support that instruction set. You will have to build pyarrow/libarrow yourself see the [docs](https://arrow.apache.org/docs/cpp/env_vars.html#envvar-ARROW_USER_SIMD_LEVEL) on how to control the SIMD level.

**Comment by abcbarryn** [comment]
System information
CPU
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU            5160  @ 3.00GHz
stepping	: 6
microcode	: 0xd2
cpu MHz		: 3000.116
cache size	: 4096 KB

Linux static1 3.16.7-48-desktop #1 SMP PREEMPT Wed Oct 26 18:09:22 UTC 2016 (8c027f6) x86_64 GNU/Linux

glibc-2.18-4.44.1

OpenSuSE Linux

**Comment by abcbarryn** [comment]
Pyarrow builds without any error with pip or conda, but then when running python and importing pyarrow, you get an immediate illegal instruction. I have tried this with python versions 3.9.4, 3.9.13, 3.9.16 and 3.11.

**Comment by abcbarryn** [comment]
Additionally, setting the environment variable failed to change the behavior as described in the ocumentation.

One can override the detection by setting this environment variable to a well-defined value. Supported values are:

NONE disables any runtime-selected SIMD optimization;

SSE4_2 enables any SSE2-based optimizations until SSE4.2 (included);

AVX enables any AVX-based optimizations and earlier;

AVX2 enables any AVX2-based optimizations and earlier;

AVX512 enables any AVX512-based optimizations and earlier.

**Comment by cyb70289** [comment]
The runtime detection and environment variables are to choose **explicit** SIMD optimization code, as this [example](https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/exec/bloom_filter_avx2.cc).

Arrow is built with compiler (gcc, clang) option `-msse4.2` on x86 by default. With this option on, compiler may generate SSE code for any `cpp` source file, not only the explicit SIMD code.

Looks we should improve the document to explain this "illegal instruction" issue. I did saw it some times.

cc @pitrou

**Comment by assignUser** [comment]
For completeness sake a follow up was opened: https://github.com/apache/arrow/issues/34277

**Comment by westonpace** [comment]
Here: https://github.com/apache/arrow/blob/apache-arrow-11.0.0/cpp/cmake_modules/SetupCxxFlags.cmake#L474

It's conditionally set based on `ARROW_SIMD_LEVEL` which defaults to `DEFAULT` which is interpreted [here](https://github.com/apache/arrow/blob/apache-arrow-11.0.0/cpp/cmake_modules/SetupCxxFlags.cmake#L102) as SSE4.2.

**Comment by westonpace** [comment]
So if you want a build without SIMD you will need to specify `-DARROW_SIMD_LEVEL=NONE` when invoking cmake.
