### ISSUE TITLE
[Java] JDBC Flight SQL driver calls prepare() twice

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#34284]
### Describe the bug, including details regarding any error messages, version, and platform.

[From user@](https://lists.apache.org/thread/9smgkz1x3wl27yl7nj55d8qdmlmhpgm2):

> I noticed that when I use ArrowFlightJdbcDriver to run a prepare statement
> query. It sends prepare query twice to the backend flight server.
> 
> The first query is triggered in ArrowFlightMetaImpl#prepare method: link:
> https://github.com/apache/arrow/blob/45918a90a6ca1cf3fd67c256a7d6a240249e555a/java/flight/flight-sql-jdbc-driver/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightMetaImpl.java#L134
> 
> 
> The second query is triggered
> in ArrowFlightJdbcFactory#newPreparedStatement: link
> https://github.com/apache/arrow/blob/45918a90a6ca1cf3fd67c256a7d6a240249e555a/java/flight/flight-sql-jdbc-driver/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightJdbcFactory.java#L84
> 
> Could you shed some light on this? Why it's called twice? Does backend
> flight server need skip the second duplicate query in such case?

### Component(s)

FlightRPC, Java

**Comment by rtadepalli** [comment]
take
