### ISSUE TITLE
[C++] CountRows() in ParquetFileFormat class is unreasonable

### ISSUE THREAD

**Issue by YoungRX** [apache/arrow#34313]
### Describe the bug, including details regarding any error messages, version, and platform.

Suppose there are 10 row groups and 1 column (name id) in a Parquet file. Each row group has 10000 data.
Data distribution is as follows:
> row_group_1: (1, 2, 3, ..., 10000); 
> row_group_2: (10001, 10002, 10003, ..., 20000); 
> ......
> row_group_10: (90001, 90002, 90003, ..., 100000).

Then I use `Future<util::optional<int64_t>> ParquetFileFormat::CountRows(const std::shared_ptr<FileFragment>& file, compute::Expression predicate, const std::shared_ptr<ScanOptions>& options)` to count the number of rows after predicate pushdown.
If I set id < 12345 in compute::Expression, `CountRows` returns `util::nullopt`.
If I set id < 20000 in compute::Expression, `CountRows` returns `util::nullopt`.
If I set id < 20001, `CountRows` returns `util::make_optional<int64_t>(20000)`.
I found that `ParquetFileFormat::CountRows` calls `ParquetFileFragment::TryCountRows`, and the code in `ParquetFileFragment::TryCountRows` is as follows:

```
      // Unless the row group is entirely included, bail out of fast path
      if (expressions[i] != compute::literal(true)) return util::nullopt;
```
It is unreasonable. I think id < 12345 actually scans two row groups, the correct result for `CountRows` should be 20000. I hope you can solve this problem, or you have a different view.
I'd like to ask a few more questions, and I hope you can answer them.

> 1. For Parquet's predicate pushdown, is the filter level row group or page?
> 2. If it's row group, would the filtering level of the page be more efficient?
> 3. If it's page, can `ParquetFileFormat::CountRows` accurately calculate the number of rows corresponding to the predicate expression?
> 4. And where is the key code about the above questions?

### Component(s)

C++

**Comment by westonpace** [comment]
> I think id < 12345 actually scans two row groups, the correct result for CountRows should be 20000

Shouldn't the correct result be 12344?

> For Parquet's predicate pushdown, is the filter level row group or page?

Row group level currently.  Page level would be ideal but has not been implemented yet.

> If it's row group, would the filtering level of the page be more efficient?

Yes, in most cases, and there is no reason we can't do both.

> If it's page, can ParquetFileFormat::CountRows accurately calculate the number of rows corresponding to the predicate expression?

Depends.  If the predicate affects multiple columns like `x < 10 && y > 0` then page indices can't fully answer the question.  If the predicate only touches one column like `x < 10` then we still probably have to do some in-memory filtering (e.g. a page might have min=0 and max=20).

> And where is the key code about the above questions?

There are three main spots.

First, the parquet-cpp library is a (mostly) standalone library for reading parquet files.  It doesn't really have access to arrow expressions or arrow compute.  Page indices would probably first be added at this level.

Second, the arrow parquet reader wraps parquet-cpp and interfaces it with the rest of the arrow code.  Any capability we add in parquet-cpp will need to be exposed through the arrow parquet reader.

Finally, the parquet file format translates format-agnostic filtered reads into actual commands into the arrow parquet reader.   Once the capability to do filtered reads has been added to the arrow parquet reader then the parquet file format will need to utilize this.

**Comment by YoungRX** [comment]
> I think id < 12345 actually scans two row groups, the correct result for CountRows should be 20000
> Shouldn't the correct result be 12344?

Yes, the end result of the scan should be 12344 rows. But as you said, the filter level for Parquet predicate pushdown is row group. For `id < 12345`, we actually scanned two row groups. `ParquetFileFormat::CountRows` calls `ParquetFileFragment::FilterRowGroups` to get the two row groups. These two row groups have 20000 rows, which is what `ParquetFileFormat::CountRows` should return.

Specifically, `ParquetFileFormat::CountRows` calculates the number of rows of data after predicate pushdown filtering.

Possible solutions for `ParquetFileFormat::CountRows` are as follows:

> Delete `if (expressions[i] != compute::literal(true)) return util::nullopt;` from `ParquetFileFragment::TryCountRows`.

And thanks for your answers.

**Comment by westonpace** [comment]
The various formats aren't typically used directly, but through the scanner here: https://github.com/apache/arrow/blob/apache-arrow-11.0.0/cpp/src/arrow/dataset/scanner.cc#L728

So the logic is basically:

If we can know the row count without scanning the file then return it.  Else, if we can't know the exact count, return nullopt and let the scanner figure out the exact count with in-memory filtering.

**Comment by YoungRX** [comment]
OK, I understand it. Thanks a lot.
And I just need to read a parquet file, do you suggest I use AsyncScanner class or ParquetFileFormat class to read?
