### ISSUE TITLE
[C++] Memory access out of bounds in arrow-1.0.0

### ISSUE THREAD

**Issue by luffy-zh** [apache/arrow#34329]
### Describe the bug, including details regarding any error messages, version, and platform.

Memory access is out of bounds at line array_nested.cc:78. There is no need to clear the bits of the final offset.

### Component(s)

C++

**Comment by westonpace** [comment]
This was fixed in https://github.com/apache/arrow/pull/9801

We may patch the current release but we don't typically backport fixes to older releases.

**Comment by kou** [comment]
Thanks for the report but I close this as duplicate of #27902.
