### ISSUE TITLE
[Go] CSV not handling all extensions

### ISSUE THREAD

**Issue by yevgenypats** [apache/arrow#34334]
### Describe the enhancement requested

Seems like CSV missing some types at the moment (including BinaryType and BinaryFixedLengthType) - https://github.com/apache/arrow/blob/main/go/arrow/csv/common.go#L217

Also, missing handling of ArrowExtensionTypes (similar to https://github.com/apache/arrow/issues/34330). 

Will be happy to contribute support for some of the missing types unless there are some restrictions on supporting those types in a csv?

### Component(s)

Go

**Comment by zeroshade** [comment]
@yevgenypats there's no restrictions on supporting those types in CSV, just needing to determine how we want to.

Extension types aren't too bad, you can just process them as their underlying storage type. The Binary and BinaryFixedLength types should probably assume base64 encoding of the data in the CSV and decode accordingly.

I'll gladly review a PR for you contributing those!

**Comment by yevgenypats** [comment]
Thanks @zeroshade . I'll take a stab at this one first, as seems it's easier then the parquet one.

**Comment by zeroshade** [comment]
It absolutely will be haha. Though the same advice for extension types goes here: if it's an extension type just process it as it if was the underlying storage type.

One thing you can try for binary types might be to also update the auto-detection to try base64 decoding the values before defaulting to just string types and if it can successfully base64 decode the data then assume it is binary (possibly, but not entirely necessary, i'm fine with binary not being supported in auto-detection).

Another future enhancement I wanted to eventually work on for CSVs was to try to sample more than just the first line for the auto-detection of types to allow for better handling. But obviously that doesn't need to be part of this at all

**Comment by yevgenypats** [comment]
One question I do have, is how to correctly handle list types which are not handled at all at the moment. should it be configurable or should we use something like `{` and `}` to mark that a field is a list in a csv?

**Comment by zeroshade** [comment]
That's definitely a good question. So in theory the only real use for putting `{` or `[` to mark the field would be for the auto detection (and that should be configurable), alternately a user could essentially pipe the records through a channel and then process a column if they know it's a list/json/whatever and expand that column themselves....

If you want to process a list type column via csv you'll have to essentially have every row parse that value as if it were its own one-line CSV basically.... and then convert each value to the correct type. I mean, it'd definitely be convenient for users if you want to implement that but I'd definitely say you should make a separate issue/PR for that from this. Maybe even gather feedback. I'll take a look at how the C++ library handles (or doesn't handle) list types for CSV

**Comment by yevgenypats** [comment]
Thanks! Maybe a noob question but how do I iterate correctly in the following section.

```
case *arrow.ListType
  arr := col.(*array.List)
  l := arr.Len() // this returns the length of the list of lists.
  for i := i < l; i ++ {
    // How do I get the first list entry (that also contains a list)?
    arr.ListValues() // this returns a flattened list which is not what I want
  }
```

**Comment by zeroshade** [comment]
for the first question:

```go
case *arrow.ListType:
    arr := col.(*array.List)
    listVals, offsets := arr.ListValues(), arr.Offsets()
    for i := 0; i < arr.Len(); i++ {
        // values for list index i are the values of listVals from
        // offsets[i] : offsets[i+1]
        list := array.NewSlice(listVals, int64(offsets[i]), int64(offsets[i+1]))
        defer list.Release()
        // list is now the slice of listVals containing only the values for the list at index i
        // do whatever you like with it
    }
```

For another example of iterating a list array, you can look at the docs: https://pkg.go.dev/github.com/apache/arrow/go/v11/arrow@v11.0.0#example-package-ListArray

> Also, another question - why not use the native ToString / String in the conversion here but rather re-implement a custom one in the writer - https://github.com/apache/arrow/blob/main/go/arrow/csv/writer.go#L100

For the most part: custom null values and other customizations which don't exist for the standard `String()` conversion but do exist for CSV writing. There's also the customization of bool formatting.

Secondly, the way that the CSV writer works requires creating a slice of `[][]string`, whereas the `String()` method on the array produces a Go-like output of the array similar to what you'd get if it were a slice. i.e.: [0 1 2 3 4 5] as opposed to "0,1,2,3,4,5" which means if we use the standard `String()` method on the array, we'd have to then re-parse/split the values to get the `[][]string` that the CSV writer needs. It was easier to have the CSV writer do its own conversion to string to avoid having to jump through those hoops and allow possible future changes to the string representation without risking breaking the CSV writer.

**Comment by yevgenypats** [comment]
Here is a first stab it, open for comments (still missing the reader part) https://github.com/apache/arrow/pull/34343

**Comment by zeroshade** [comment]
I added some comments to it

**Comment by yevgenypats** [comment]
Thank you ! 🙏  taking a look now.
