### ISSUE TITLE
[Java] BaseAllocator.DEBUG should be opt-in as HistoricalLog is immensely expensive and breaks profiling

### ISSUE THREAD

**Issue by adamkennedy** [apache/arrow#34338]
### Describe the bug, including details regarding any error messages, version, and platform.

BaseAllocator.DEBUG is currently enabled automatically any time assertions are enabled via -ea which is typically all test runs and JUnit usages in IDEs, including debugging and profiling based on JUnit tests.

The problem with this is that BaseAllocator.DEBUG causes ArrowBuf to maintain a HistoricalLog with 5 history entries. To achieve this, a highly expensive event containing a full stack trace must be created for each allocation event with the vast majority of them thrown away.

For example: In an application that generates many small (100kB) Arrow data frames, each consisting of around 50 vectors, profiling parts of the test suite related to Arrow generation shows that the creation the StackTrace instances needed for the rolling 5 entry HistoricalLog consume 85% of all program CPU and are responsible for 80% of all Java memory allocation. 

During the applications full Maven test run, which is not a debugging scenario but sees BaseAllocator.DEBUG turned on anyway due to -ea, the cost of HistoricalLog increases the total test run-time from 4 seconds (with arrow.memory.debug.allocator=false ) to 14 seconds, a substantial slow-down for no real value and a large cost when spread over every test and CI run.

Profiling also becomes challenging, because the cost of StackTrace spread out across the program pollutes and distorts profiling results and flame graphs become largely unusable.

These negative effects occur in every Arrow Java application by default, unless explicitly turned off.

I propose that the default of arrow.memory.debug.allocator be reversed to false by removing the automatic enabling of BaseAllocator.DEBUG on -ea. If this is not acceptable, then at minimum the maintenance of HistoricalLog should be separately and specifically disabled.

If discoverability is a dominating concern, then in debugging or diagnostic messages, in place of the information presented from HistoricalLog we could instead place a message saying that HistoricalLog is disabled and describing the system property needed to enable it.

### Component(s)

Java

**Comment by lidavidm** [comment]
Debug allocation tracking consuming nearly all of the actual CPU time is certainly not a great default. (It shouldn't happen in an 'application' since presumably those are run without -ea, but even so.)

Given that this information is tracked but not surfaced by default anyways, I think it'd be fine to stop tracking it by default. As long as we make sure it's clear how to enable it when desired (e.g. the default exception thrown could include a message about this).

**Comment by lwhite1** [comment]
I think this is a good change. The current setup can lead new users to the impression that Arrow Java is slow, when it's really just a matter of configuration.

**Comment by raulcd** [comment]
@lidavidm @lwhite1 this is marked as 12.0.0. Is there something to be done here? Is that blocker for the release?

**Comment by lidavidm** [comment]
It is not a blocker. I am not working on it, at least. I don't want this to slip either, though.

**Comment by davisusanibar** [comment]
> Hi team, I'm reviewing this issue.
> 
> These are the ways implemented to handling logging messages:
> 
> 1. There is an environment variable created to enable debug messages `-Darrow.memory.debug.allocator`
> 2. The fallback is that environment variable is not passed is to analyze if `-ea = enabled assertion` is declared
> 3. In some another cases there is handled by `LOGGER.isDebugEnabled()`
> 
> My proposal will be to migrate all of these to only to be handled by external Logger and Configure SLF4J to see these logs (e.g. via Logback/Apache Log4j). It mean all Arrow Java logger messages should be handled by only SLF4J logger scope definition (debug(), info(), warn(), error()).
> 
> 1. There is an environment variable created to enable debug messages `-Darrow.memory.debug.allocator` ==> Will be moved to `logger.debug(...)`
> 2. The fallback is that environment variable is not passed is to analyze if `-ea = enabled assertion` is declared ==> Will be deleted the logic to enable debug if `-ea` is passed
> 3. In some another cases there is handled by `LOGGER.isDebugEnabled()` ==> Will be working as it is now
> 4. Delete class `org.apache.arrow.memory.util.AssertionUtil`
> 
> Please @lidavidm let me know your comments to try to implement that.

Handling that by external logger configuration will be helpful because also the user could configure/filter classes needed to debug or not.

**Comment by lidavidm** [comment]
We should just go with the original suggestion:

> I propose that the default of arrow.memory.debug.allocator be reversed to false by removing the automatic enabling of BaseAllocator.DEBUG on -ea. 

Note that deferring to the logger doesn't help. It's the generation/tracking of the data to be logged that is the issue, not the log messages themselves.

**Comment by davisusanibar** [comment]
> We should just go with the original suggestion:
> 
> > I propose that the default of arrow.memory.debug.allocator be reversed to false by removing the automatic enabling of BaseAllocator.DEBUG on -ea.
> 
> Note that deferring to the logger doesn't help. It's the generation/tracking of the data to be logged that is the issue, not the log messages themselves.

I agree with that, the option (2) consider the proposal mention on the issue. My proposal is to migrate also `-Darrow.memory.debug.allocator` to `Logger scope` to our users could handle logger configuration using *.xml file (that offer more granularity) instead of use environment variable.

I am starting with remove logic for `-ea` on `BaseAllocator.DEBUG`, then let me know if more changes need to be added.

**Comment by lidavidm** [comment]
That would be a larger breaking change; it may make sense to allow both paths but depending on loggers can be iffy (e.g. you then have to make sure you initialize the logger and load the configuration before you touch any Arrow classes)
