### ISSUE TITLE
[C++] Allow the CSV reader to read zero columns

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#34346]
### Describe the enhancement requested

There are times we may want to scan a CSV file and just count the lines.

One example is when we want to count the # of rows in a dataset.
Another example is when we have a partitioned dataset and the only columns the user has requested are fulfilled by the partition data.

Today, when `ParseOptions::columns` is an empty list the CSV reader reads and parses all of the data.

This doesn't have to be done as an extension to the CSV reader.  It could be a specialized CSV reader that just counts the # of rows.  Note: this isn't as simple as counting the number of newlines in the file because the options may allow for quoted newlines to be in a CSV field.

### Component(s)

C++

**Comment by dinimar** [comment]
Hi @westonpace 
Couldn't find `columns` field in `ParseOptions` or in any other `struct` in `arrow\cpp\src\arrow\csv\options.h` file. 
Maybe you misspelled name of class or field? Please let me know, wanna work on this issue

**Comment by westonpace** [comment]
@dinimar Sorry, the field I was thinking of was `arrow::csv::ConvertOptions::include_columns`.  It will still need to be possible to ask for all columns (and this should still be the default).

One way to do this would be to change `include_columns` from `std::vector<std::string>` to `std::optional<std::vector<std::string>>` with the default being `std::nullopt` which should be interpreted as "read all columns".  However, this would be a backwards incompatible change.

Another way to do this would be to introduce a new field `bool allow_no_columns` which defaults to `false` with the semantics:
 * If `include_columns` is empty and `allow_no_columns` is false then read all columns
 * If `include_columns` is empty and `allow_no_columns` is true then don't read any columns
 * If `include_columns` is not empty then ignore `allow_no_columns`.
This is backwards compatible but more confusing and redundant.

A final option, for best performance, is to create an entirely different CSV reader implementation (e.g. similar to `StreamingReader` and `TableReader`) which simplifies parsing by only searching and counting newlines.

**Comment by dinimar** [comment]
As I see there is already a function that counts rows. Does this function do what you want?
https://github.com/apache/arrow/blob/9d0bce65a08e0507a816ca4ed3faa912b7956eca/cpp/src/arrow/csv/reader.h#L118-L122

**Comment by westonpace** [comment]
Yes, that should work.  I hadn't realized this was a special path already.  I thought it still decoded the data and then counted the number of rows.  However, it looks like this is actually doing the right thing.
