### ISSUE TITLE
[Python] Add support for string + string add_checked

### ISSUE THREAD

**Issue by rachtsingh** [apache/arrow#34353]
### Describe the enhancement requested

Please consider adding (vectorized) support for adding strings to strings:

```python
In [1]: df = pd.DataFrame({'a': ['b'], 'c': ['d']}).astype(dtype={'a': 'string[pyarrow]', 'c': 'string[pyarrow]'})
In [2]: df.a + df.c
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 df.a + df.c

...

File ~/.pyenv/versions/3.10.4/envs/prod/lib/python3.10/site-packages/pyarrow/compute.py:239, in _make_generic_wrapper.<locals>.wrapper(memory_pool, *args)
    237 if args and isinstance(args[0], Expression):
    238     return Expression._call(func_name, list(args))
--> 239 return func.call(args, None, memory_pool)

File ~/.pyenv/versions/3.10.4/envs/prod/lib/python3.10/site-packages/pyarrow/_compute.pyx:355, in pyarrow._compute.Function.call()

File ~/.pyenv/versions/3.10.4/envs/prod/lib/python3.10/site-packages/pyarrow/error.pxi:144, in pyarrow.lib.pyarrow_internal_check_status()

File ~/.pyenv/versions/3.10.4/envs/prod/lib/python3.10/site-packages/pyarrow/error.pxi:121, in pyarrow.lib.check_status()

ArrowNotImplementedError: Function 'add_checked' has no kernel matching input types (string, string)
...
```

There's support for this in Panda's normal `pd.StringDtype` (aka dtype = `string`), but not with Arrow storage format. We'd also appreciate support for adding constant strings as prefixes or suffixes, if that's not already automatic with implementation of the kernel.

I can take a look at implementing this if someone points me to the right file (it is a little hard for me to understand how to set up a development environment for Pandas+Arrow).

### Component(s)

Python

**Comment by westonpace** [comment]
I think you can perhaps achieve this with the `binary_join_element_wise` kernel using an empty separator (admittedly, not intuitive):

```python
import pyarrow as pa
import pyarrow.compute as pc

x = pa.array(['one', 'two', 'three'], pa.string())
y = pa.array(['1', '2', '3'], pa.string())

print(pc.binary_join_element_wise(x, y, '='))
print(pc.binary_join_element_wise(x, y, ''))

# [
#   "one=1",
#   "two=2",
#   "three=3"
# ]
# [
#   "one1",
#   "two2",
#   "three3"
# ]
```

It appears the current implementation is expecting the `add_checked` function to support strings but I think the decision in Arrow was that `add_checked` is an arithmetic operation and string concatenation is a different function entirely.  That shouldn't (to the best of my knowledge) prevent pandas from converting `string + string` to `binary_join_element_wise` however.

**Comment by westonpace** [comment]
Or, if you want to make the case that `add_checked` should support strings, you can certainly do this with an alias (I think we have one or two cases where we alias for backwards compatibility reasons).  But that might be more of a discussion for the ML around philosophy.

**Comment by rachtsingh** [comment]
Thank you for the quick response! That seems like it would solve it (and I can ping the pandas devs to get the correct function to be called with pd.Series.__add__ with string[pyarrow] dtype), but I think I must be converting data wrong because I'm getting what seems to be incorrect results:

```python
In [35]: df = pd.DataFrame({'a': ['b'], 'c': ['d']}).astype(dtype={'a': 'string[pyarrow]', 'c': 'string[pyarrow]'})
In [36]: pc.binary_join_element_wise(pa.array(df.a, pa.string()), pa.array(df.c, pa.string())).to_pandas()
Out[36]:
0    b
dtype: object
```

I think I should expect to see `bd` as the resulting output?

**Comment by rachtsingh** [comment]
Oh, I'm sorry, I totally missed what you said about an empty separator. That works:

```python
In [47]: pc.binary_join_element_wise(pa.StringArray.from_pandas(df.a), pa.StringArray.from_pandas(df.c), '')
Out[47]:
<pyarrow.lib.ChunkedArray object at 0x7efed1d06520>
[
  [
    "bd"
  ]
]
```

**Comment by rachtsingh** [comment]
Final comment: I figured out Pandas uses the right function if you call:

```python
df.a.str.cat(df.b, sep='')
```

which seems pretty similar in semantics to the above snippet. Thanks for all the help!
