### ISSUE TITLE
[Java] Java Integration Test Failures

### ISSUE THREAD

**Issue by tustvold** [apache/arrow#34367]
### Describe the bug, including details regarding any error messages, version, and platform.

We are seeing failures building Java within the archery integration test framework

https://github.com/apache/arrow-rs/actions/runs/4283526230/jobs/7459219738

```
Error:  /__w/arrow-rs/arrow-rs/java/flight/flight-core/src/test/java/org/apache/arrow/flight/client/CustomHeaderTest.java:[77,27] error: cannot find symbol
  symbol:   method getStartedServer((location)[...]ild())
  location: class FlightTestUtil
```

I've not dug deep into what is occurring here, but thought I would create a ticket in case this is a known issue / easy fix

### Component(s)

Java

**Comment by lidavidm** [comment]
Hmm, I just merged a PR around this

**Comment by lidavidm** [comment]
I wonder if there was a rebase or merge oops, I'll check now - sorry about this @tustvold

**Comment by lidavidm** [comment]
I put up #34368. I merged two PRs in quick succession but derped and didn't realize they impacted each other.
