### ISSUE TITLE
[C++] Investigate regressions caused by changing row group size from 64Mi to 1Mi.

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#34374]
### Describe the bug, including details regarding any error messages, version, and platform.

It appears that changing the default row group size from 64Mi rows to 1Mi rows had a [significant change](https://conbench.ursa.dev/compare/runs/4f4776c497624be189af3c17a5f627e8...cc0d3e5e476148ff8ad72af2a31fe8eb/) (15-25%) on write performance.

Some decrease in performance is expected and it may be that this is simply unavoidable, though we should (at least manually) verify that we do in fact get tangible benefits on reading.

However, it also seems odd that the performance would degrade this much.  It's probably worth at least a brief profiling effort to ensure that there isn't any low-hanging fruit that could be addressed to mitigate this performance degradation.

### Component(s)

C++

**Comment by westonpace** [comment]
If we can't fix the performance we should make sure to be clear in the release notes that this may happen and users can always get the old behavior by manually specifying the larger row group size.

**Comment by jorisvandenbossche** [comment]
Something else (while trying to compare specifying the different row group sizes), it seems specifying the row group size no longer works to get something else as the default.

Using released pyarrow 11:

```python
>>> pa.__version__
'11.0.0'
>>> import pyarrow.parquet as pq
# table of 9_980_000 (~10M) rows
>>> table = pq.read_table("nyc_taxi_sample.parquet").combine_chunks()
# default is still 64M -> 1 row group
>>> pq.write_table(table, "test_pa11_row_group_size_None.parquet")
>>> pq.read_metadata("test_pa11_row_group_size_None.parquet").num_row_groups
1
# specify the new default manually -> correctly get 10 row groups
>>> pq.write_table(table, "test_pa11_row_group_size_1M.parquet", row_group_size=1024*1024)
>>> pq.read_metadata("test_pa11_row_group_size_1M.parquet").num_row_groups
10
# specify old default
>>> pq.write_table(table, "test_pa11_row_group_size_64M.parquet", row_group_size=1024*1024*64)
>>> pq.read_metadata("test_pa11_row_group_size_64M.parquet").num_row_groups
1
```

While with latest main:

```
>>> pa.__version__
'12.0.0.dev171+gf9a1d198f.d20230301'
>>> import pyarrow.parquet as pq
>>> table = pq.read_table("nyc_taxi_sample.parquet").combine_chunks()
# default now gives 10 row groups
>>> pq.write_table(table, "test_pa12_row_group_size_None.parquet")
>>> pq.read_metadata("test_pa12_row_group_size_None.parquet").num_row_groups
10
# specifying old default of 64M -> still gives 10 and not 1 row group
>>> pq.write_table(table, "test_pa12_row_group_size_64M.parquet", row_group_size=1024*1024*64)
>>> pq.read_metadata("test_pa12_row_group_size_64M.parquet").num_row_groups
10
```

I don't see how this could have been caused by https://github.com/apache/arrow/pull/34281, but certainly something we should fix as well.

**Comment by jorisvandenbossche** [comment]
> I don't see how this could have been caused by #34281, but certainly something we should fix as well.

Ah, no it was caused by the PR, because it changed `DEFAULT_MAX_ROW_GROUP_LENGTH`, which doesn't set the _default_ `chunksize`, but actually caps the max chunk (row group) size regardless of the user-specified `chunk_size`.

It seems this constant is used both for setting this max upper cap, and as the default values for `chunk_size` in `WriteTable`. I assume we will have to distinguish those two meanings?

**Comment by westonpace** [comment]
Yes, I think you're right.  That is more critical.

**Comment by westonpace** [comment]
Did you already open a separate issue for this?

**Comment by jorisvandenbossche** [comment]
Opened https://github.com/apache/arrow/issues/34410

**Comment by westonpace** [comment]
It seems the regression is quite stable:

![image](https://user-images.githubusercontent.com/1696093/232133789-e7919732-ad39-4578-9e16-87b830f54e9b.png)

I did some extensive testing of my own today.  The results when I run locally match what we are seeing in the benchmark.  For example, going from 2 to 62 row groups adds two seconds to the write time of a simple file.  I'm guessing there is a real opportunity somewhere to improve the writer performance.

However, since users can always go back to the old behavior, I think the update to the default remains justified.

@jorisvandenbossche any opinions?  Or else I think we can close this.
