### ISSUE TITLE
[Python] arrow table: how to drop duplicates?

### ISSUE THREAD

**Issue by code1704** [apache/arrow#34376]
### Describe the usage question you have. Please include as many useful details as  possible.

In pandas DataFrame there's `pandas.DataFrame.drop_duplicates`.

With arrow table, how can I drop duplicates on given columns (and keep first)?

### Component(s)

Python

**Comment by AlenkaF** [comment]
I believe you are thinking about removing duplicated rows? There is already an issue open on this topic:
https://github.com/apache/arrow/issues/30950

**Comment by code1704** [comment]
> I believe you are thinking about removing duplicated rows? There is already an issue open on this topic: #30950

Yes, thanks.

**Comment by AlenkaF** [comment]
I will close this as a duplicate then.

**Comment by AlenkaF** [comment]
Duplicate of #30950
