### ISSUE TITLE
[C++] Run-end encoding and decoding: Add support for more types

### ISSUE THREAD

**Issue by felipecrv** [apache/arrow#34382]
### Describe the enhancement requested

#34195 introduces two functions `run_end_encode` and `run_end_decode` supporting with support for numeric, null, and bool types. More types can and should be supported.

TODO list:

 - [x] All `NumericTypes()`
 - [x] `bool()`
 - [x] `null()`
 - [x] Temporal, Interval, and Duration types
 - [x] Variable length types
 - [x] Fixed size binary types

### Component(s)

C++

**Comment by dinimar** [comment]
@felipecrv 
As I found out in code there're `add_kernel()` function calls related to types you mentioned
https://github.com/apache/arrow/blob/f9324b79bf4fc1ec7e97b32e3cce16e75ef0f5e3/cpp/src/arrow/compute/kernels/vector_run_end_encode.cc#L607-L612
https://github.com/apache/arrow/blob/f9324b79bf4fc1ec7e97b32e3cce16e75ef0f5e3/cpp/src/arrow/compute/kernels/vector_run_end_encode.cc#L631-L636

But simple adding `add_kernel()` function calls doesn't work. Tests start failing after that. Could you please explain how to add types for `run_end_encode` and `run_end_decode` properly?

About types. As I see, in theory, it's possible to add all types using `add_kernel` (at least, it's easy for functions with empty arguments) listed in:
https://github.com/apache/arrow/blob/f9324b79bf4fc1ec7e97b32e3cce16e75ef0f5e3/cpp/src/arrow/type_fwd.h#L456-L590

**Comment by felipecrv** [comment]
take
