### ISSUE TITLE
[Java] Arrow deserialization performance is so poor in Java

### ISSUE THREAD

**Issue by chenyuanxing** [apache/arrow#34393]
### Describe the usage question you have. Please include as many useful details as  possible.

We experimented with the same data and found that the performance of Arrow deserialization is only 1/3 of PB. Arrow cost 8s and PB just cost 3s. 

test data set：(A total of 1000 lines, each line is a 20*2000 two-dimensional table.)
272M    Arrow_data
496M    PB_data

During the implementation process, Arrow uses flatbuf to serialize and deserialize, which should be faster in theory. but it is not. 
```
Schema subSchema = MessageSerializer.deserializeSchema(new ReadChannel(Channels.newChannel(new ByteArrayInputStream(schemaBytes))));
ArrowRecordBatch subRecordBatch = MessageSerializer.deserializeRecordBatch(new ReadChannel(Channels.newChannel(new ByteArrayInputStream(dataBytes))), ArrowUtils.getAllocator());

VectorSchemaRoot subRoot = VectorSchemaRoot.create(subSchema, ArrowUtils.getAllocator());
VectorLoader subLoader = new VectorLoader(subRoot);
subLoader.load(subRecordBatch);
subRecordBatch.close();
```

I looked at the source code and found that The main time-consuming is divided into two parts:
one is :
![image](https://user-images.githubusercontent.com/16252583/222102013-ef9204fb-04bb-4c26-b7a7-7eb2a24edd58.png)
the other is：
 `org.apache.arrow.vector.VectorLoader#load`
  
Is there something wrong with my way of using it, or is the serialization performance of the java version of Arrow just poor?

### Component(s)

Java

**Comment by lidavidm** [comment]
Hi @chenyuanxing sorry we didn't get to this in time. Did you figure out why it was slow?

**Comment by chenyuanxing** [comment]
em. yes .It is because the debug mode of BaseAllocator is enabled by default. 
![image](https://user-images.githubusercontent.com/16252583/222311763-c915035d-fd13-40e9-8451-ad071e870977.png)

**Comment by lidavidm** [comment]
Okay. We are considering disabling it by default. Feel free to chime in on https://github.com/apache/arrow/issues/34338

**Comment by chenyuanxing** [comment]
by the way . Is there no filter function in java? @lidavidm

**Comment by chenyuanxing** [comment]
like the arrow::compute::Filter in C++.

**Comment by lidavidm** [comment]
The Java library doesn't really have compute utilities like that. @lwhite1 was there anything related to that in the Table work?

**Comment by lwhite1** [comment]
There's no support for filtering in Java until the substrait interface to Arrow C++ is completed. I suspect that will be in the next release or two.

**Comment by chenyuanxing** [comment]
okay.very thanks.
