### ISSUE TITLE
[Python] Regression on pq.ParquetWriter incorrectly handling source string

### ISSUE THREAD

**Issue by fj-sanchez** [apache/arrow#3444]
In the latest changes to filesystem.py some new functions have been added to check the source string when calling pq.ParquetWriter. With the current implementation some assumptions are done about the format of the string which means that if the string is provided following some of these patterns it will be automatically split/formatted and changed to something else.

To give you a specific example, if I provide a string like `directory/level1#level2.parquet` it will be written to disk as `directory/level1`. The behaviour has changed on 0.12.0 from 0.11.1 and nothing is stated in the documentation.

**Comment by wesm** [comment]
Can you open a JIRA issues? There were no unit tests for this, so we'll have to add some

**Comment by fj-sanchez** [comment]
Should it be created as bug, test or improvement?

**Comment by wesm** [comment]
Seems like a bug to me, so that is a fine category

**Comment by fj-sanchez** [comment]
Done
https://jira.apache.org/jira/browse/ARROW-4311
