### ISSUE TITLE
[Python] Support non-nanosecond units in method to_pandas_dtype for timestamp and duration types

### ISSUE THREAD

**Issue by lukemanley** [apache/arrow#34462]
### Describe the enhancement requested

Pyarrow `timestamp(unit).to_pandas_dtype()` and `duration(unit).to_pandas_dtype` are currently returning `dtype('<M8[ns]')` with nanosecond units regardless of the pyarrow units. Pandas has recently added support for non-nanosecond units so I believe pyarrow can now preserve the units here.

```
>>> import pyarrow as pa

>>> pa.timestamp("us").to_pandas_dtype()
dtype('<M8[ns]')

>>> pa.duration("ms").to_pandas_dtype()
dtype('<m8[ns]')
```

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Related: https://github.com/apache/arrow/issues/33321 (for the actual data conversions)

**Comment by AlenkaF** [comment]
This issue also came up after pandas implemented `__from_pyarrow__` support to `DatetimeTZDtype`. See:

- https://github.com/apache/arrow/issues/35235
- https://github.com/pandas-dev/pandas/issues/52782
