### ISSUE TITLE
R 'arrow' package installation issue (failed in multiple machines)

### ISSUE THREAD

**Issue by wangtaifr** [apache/arrow#34506]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello I was trying to install arrow on Rstudio (Mac and Linux), R (version 4.1.1) and got error like: Failed to download manifest for apache-arrow

Any solution?

```
> install.packages("arrow")
Installing package into ‘/Users/wangt52/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary   source needs_compilation
arrow 11.0.0.2 11.0.0.3              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package ‘arrow’

trying URL 'https://cloud.r-project.org/src/contrib/arrow_11.0.0.3.tar.gz'
Content type 'application/x-gzip' length 3921484 bytes (3.7 MB)
==================================================
downloaded 3.7 MB

* installing *source* package ‘arrow’ ...
files ‘tools/cpp/src/arrow/Testing/Temporary/CTestCostData.txt’, ‘tools/cpp/src/arrow/Testing/Temporary/LastTest.log’ are missing
** using staged installation
*** Downloading apache-arrow
Failed to download manifest for apache-arrow
------------------------- NOTE ---------------------------
There was an issue preparing the Arrow C++ libraries.
See https://arrow.apache.org/docs/r/articles/install.html
---------------------------------------------------------
ERROR: configuration failed for package ‘arrow’
* removing ‘/Users/wangt52/Library/R/x86_64/4.1/library/arrow’
* restoring previous ‘/Users/wangt52/Library/R/x86_64/4.1/library/arrow’
Warning in install.packages :
  installation of package ‘arrow’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/x0/jf68v2s96bl_226mz0g3vqn00000gp/T/RtmpeV0JRH/downloaded_packages’
```

### Component(s)

R

**Comment by assignUser** [comment]
Yes this is due to the version being just released
 Just install the existing binary version from cran instead of the source version.

**Comment by assignUser** [comment]
I checked that both binary and source version can be installed on macos successfully: https://github.com/assignUser/test-repo-a/actions/runs/4369142182/jobs/7642595874#step:3:118

You can use the prompt or the `type` arg to force binary install e.g `install.packages("arrow", type = "mac.binary")` on mac.

Feel free to reopen the issue if it still fails to install for you. In that case please set the envvars `NOT_CRAN` and `ARROW_R_DEV` to TRUE and try installing afterwards so we get an exhaustive log.

**Comment by wangtaifr** [comment]
Thanks for swift action! I was able to install with 'mac.binary' uneventfully. But I need to deploy my R shiny app onto a server which it requires compilation.

I turned on both options (NOT_CRAN) and (ARROW_R_DEV) turned to true. But the log I got was exactly the same as my above log. 

I am using a Macbook pro with Mac 12.6.1 (monterey) and R 4.1.1 and R 4.2.2, with an Intel-based chip (x86_64). I guess there is some broader issue because I trie the latest release and I the legacy version (10.0.0 or 9.0.0) (using devtools::install_version ("arrow", version="10.0.0") and they also came to me with the same error. I try to install through 'conda install -c conda-forge --strict-channel-priority r-arrow' and it just freeze along the installation. We have it tested on multiple macbook pro from different locations. 

Thanks for checking this

**Comment by assignUser** [comment]
The mac package uses homebrew/autobrew to install the cpp library usually. Is it possible that there is a firewall block or something preventing that?

**Comment by thisisnic** [comment]
From what you've said, it looks like setting the environment variables didn't quite work, as you should be getting a more detailed log after doing this.  Can you show us the code you ran to set the env vars and then install the package, and where they were run (i.e. interactive R session or terminal)?

**Comment by nealrichardson** [comment]
We expect this to be resolved now. Please reopen and provide additional details if you're still having trouble.
