### ISSUE TITLE
R 'arrow' package installation issue (failed in multiple machines)

### ISSUE THREAD

**Issue by wangtaifr** [apache/arrow#34517]
Thanks for swift action! I was able to install with 'mac.binary' uneventfully. But I need to deploy my R shiny app onto a server which it requires compilation.

I turned on both options (NOT_CRAN) and (ARROW_R_DEV) turned to true. But the log I got was exactly the same as my previous issue (See below)

I am using a Macbook pro with Mac 12.6.1 (monterey) and R 4.1.1 and R 4.2.2, with an Intel-based chip (x86_64). I guess there is some broader issue because I trie the latest release and I the legacy version (10.0.0 or 9.0.0) (using devtools::install_version ("arrow", version="10.0.0") and they also came to me with the same error. I try to install through 'conda install -c conda-forge --strict-channel-priority r-arrow' and it just freeze along the installation. We have it tested on multiple macbook pro from different locations. 

Thanks for checking this

_Originally posted by @wangtaifr in https://github.com/apache/arrow/issues/34506#issuecomment-1462297843_

**Comment by thisisnic** [comment]
Just closing this ticket, as it's the same issue as the one linked in the ticket; will respond there.
