### ISSUE TITLE
[C++] How to use predicate pushdown of binary and decimal types in arrow::parquet?

### ISSUE THREAD

**Issue by YoungRX** [apache/arrow#34515]
### Describe the usage question you have. Please include as many useful details as  possible.

I am using 8.0.0. When I set a predicate pushdown expression on some types, I get an error. 
These types include `timestamp`, `date32`, `fixed_size_binary`, `string`, `binary`. 

The error occurs in the following code:
```
// predicate_filter_expressions is std::vector<arrow::compute::Expression>
scanOptions->filter = 
        arrow::compute::and_(predicate_filter_expressions).Bind(*scanOptions->dataset_schema).ValueOrDie();
```

The error information about `date32` is as follows:

> 0xffff4c1b7218 "Function 'greater' has no kernel matching input types (array[date32[day]], scalar[int32])
> /shared/cx_obs_data/softwares/arrow/cpp/src/arrow/compute/exec/expression.cc:388  call.function->DispatchBest("...

The error information of other types is the same as the above. It seems that the related function is not implemented.

Do versions later than 8.0.0 support predicate pushdown of these types? 
Or do you have plans to add implementations of predicate pushdown of these types?

In addition, how to build `Expression literal` for the decimal128 type?
I use `arrow::compute::literal(arrow::Datum(std::forward<char*>(result)))` and it reports an error.
Alternatively, the decimal128 type does not implement predicate pushdown either.

### Component(s)

C++

**Comment by westonpace** [comment]
Can you share `predicate_filter_expressions`?  It sounds like you have a filter like `field_ref("timestamp_col") > 17` and you perhaps want something like `field_ref("timestamp_col") > literal(std::make_shared<TimestampScalar>(timestamp(), 17))`?

**Comment by YoungRX** [comment]
Yes. But I use `arrow::Datum(std::forward<int64_t>(timestamp_value));` as a literal.
The specific code is as follows:
```
    if (strcmp(opName, ">") == 0) {
        predicate_filter.push_back(arrow::compute::greater(
            arrow::compute::field_ref(colField->name()),
            arrow::compute::literal(arrow::Datum(std::forward<int64_t>(timestamp_value)))
        ));
```
According to the example you gave:
```
    if (strcmp(opName, ">") == 0) {
        predicate_filter.push_back(arrow::compute::greater(
            arrow::compute::field_ref("timestamp_col"),
            arrow::compute::literal(arrow::Datum(std::forward<int64_t>(17)))
        ));
```
Then, an error is reported when Bind() is used.

If I use `literal(std::make_shared<TimestampScalar>(timestamp(), 17))`, is the problem likely to be solved? What about the other types?

**Comment by YoungRX** [comment]
I see. Thanks a lot.
