### ISSUE TITLE
pyarrow crashes Python on import on AMD CPUs

### ISSUE THREAD

**Issue by Nemecsek** [apache/arrow#34527]
(It could be related to [issue #28041](https://github.com/apache/arrow/issues/28041))

`pyarrow 11.0.0` (and some previous versions) doesn't work on some AMD x86_64 CPUs such as AMD G-T40 and AMD GX-412TC.

`import pyarrow` crashes python with an error `Illegal instruction` (my free translation from `Ungültiger Maschinenbefehl` in German).
It is due to a **SSE feature** that is not available on the CPUs and is requested by `pyarrow` on import.

According to the [documentation](https://arrow.apache.org/docs/cpp/env_vars.html#cpp-env-vars) a possible solution is to set environment var `ARROW_USER_SIMD_LEVEL=NONE`. It looks like the initial check returns SSE is available for these AMD CPUs even if it is not:

>  **ARROW_USER_SIMD_LEVEL**
The SIMD optimization level to select. By default, Arrow C++ detects the capabilities of the current CPU at runtime and chooses the best execution paths based on that information. One can override the detection by setting this environment variable to a well-defined value. Supported values are:
> *  **NONE** disables any runtime-selected SIMD  
> *  **SSE4_2** enables any SSE2-based optimizations until SSE4.2 (
> *  **AVX** enables any AVX-based optimizations and earlier;
> *  **AVX2** enables any AVX2-based optimizations and earlier;
> * **AVX512** enables any AVX512-based optimizations and earlier.
> This environment variable only has an effect on x86 platforms.

[Here](https://arrow.apache.org/docs/python/env_vars.html) it is stated that 
 > Since PyArrow is based on Arrow C++, its behavior is also affected by the [Arrow C++ environment variables](https://arrow.apache.org/docs/cpp/env_vars.html#cpp-env-vars).

After a number of attempts, it doesn't work: `ARROW_USER_SIMD_LEVEL` is neglected, and the only solution looks like to be a lenghty recompilation of `pyarrow`.

Am I missing something?

### Component(s)

Python

**Comment by cyb70289** [comment]
You have to rebuild pyarrow with sse disabled. See https://github.com/apache/arrow/issues/34268 and https://github.com/apache/arrow/issues/34277.

@abcbarryn shared the build steps https://github.com/apache/arrow/issues/34277#issuecomment-1449455571

**Comment by Nemecsek** [comment]
@cyb70289, it is what I did as it was the only practical solution after hours of testing.
But why is the environment var `ARROW_USER_SIMD_LEVEL` not read?

**Comment by cyb70289** [comment]
I explained it at https://github.com/apache/arrow/issues/34268#issuecomment-1439359645

**Comment by Nemecsek** [comment]
@cyb70289 , thank you for your explanation.
It looks like I am not the only one who has fallen into this trap.

It is confusing for a non-expert like me (I want to install `streamlit`, that will then import `pyarrow` together with another ton of libraries) to find documentation that doesn't match the experience.
