### ISSUE TITLE
[Java] JDBC Flight SQL driver should follow Flight RPC spec

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#34532]
### Describe the bug, including details regarding any error messages, version, and platform.

The JDBC Flight SQL driver assumes that the endpoints are all the same as the main server connection, but this is wrong. It should connect to individual endpoints specified by GetFlightInfo.

#13900 tried to fix it but the original contributor isn't interested - this would be a starting point for future contributors

### Component(s)

FlightRPC, Java

**Comment by jduo** [comment]
take
