### ISSUE TITLE
[C++] Hive partitioning values contain newlines for large_string

### ISSUE THREAD

**Issue by johnseekins** [apache/arrow#34546]
### Describe the bug, including details regarding any error messages, version, and platform.

pyarrow: 11.0.0
python: 3.9

I've been trying to create (and then write) a dataset using pyarrow:

```
file_options = ds.ParquetFileFormat().make_write_options(compression="zstd")
partitions = ds.partitioning(
    schema=pyarrow.schema([
        ("partition1", pyarrow.large_string()),
        ("partition2", pyarrow.large_string()),
        ("3", pyarrow.large_string()),
    ])
dataset = ds.dataset(
    f"gs://{bucket}/path1/",
    partitioning=partitions,
)
table = dataset.scanner().to_table()
ds.write_dataset(
    table,
    f"gs://{bucket}/path1/",
    format="parquet",
    file_options=file_options,
    partitioning=partitions,
    schema=table.schema,
    existing_data_behavior="overwrite_or_ignore",
)
```

This code never seems to turn the partitions into the actual expected strings:

```
pyarrow.lib.ArrowInvalid: google::cloud::Status(INVALID_ARGUMENT: Permanent error CreateResumableUpload: Disallowed unicode characters present in object name 'path1/[
  "partition1_value"
]/[
  "partition2_value"
]/[
  "3_value"
]/part-0.par...' error_info={reason=invalid, domain=global, metadata={http_status_code=400}}). Detail: [errno 22] Invalid argument
```

Am I doing something wrong here? I _thought_ I was following the documentation...

### Component(s)

Parquet, Python

**Comment by wjones127** [comment]
Hi John, have you looked at the values in your `table`? Do any of them contain the value `[\n"partition1"\n]`?

I tried to reproduce this (just locally, not GCS yet), but was not able to (writing the dataset worked fine):

```python
import pyarrow as pa
import pyarrow.dataset as ds

table = pa.table(
    {
        "partition1": ["1", "2", "3", "4", "5"],
        "partition2": ["2001", "2002", "2003", "2004", "2004"],
        "3": ["1", "2", "3", "4", "5"],
        "val": list(range(5)),
    }
)
file_options = ds.ParquetFileFormat().make_write_options(compression="zstd")
partitions = ds.partitioning(
    schema=pa.schema(
        [
            ("partition1", pa.large_string()),
            ("partition2", pa.large_string()),
            ("3", pa.large_string()),
        ]
    )
)
ds.write_dataset(
    table,
    f"tables/test_parts",
    format="parquet",
    file_options=file_options,
    partitioning=partitions,
    schema=table.schema,
    existing_data_behavior="overwrite_or_ignore",
)
```

**Comment by johnseekins** [comment]
That was bad copy/paste on my part. The values do not match the column names. I've updated the original example to reflect that.

**Comment by johnseekins** [comment]
Interestingly, I _also_ can't reproduce this locally. So this seems to be purely a problem with uploading the dataset to GCS.

**Comment by wjones127** [comment]
Oh wait I'm actually seeing weird directories too. :confused:

```
$ exa  --tree test_parts
test_parts
├── [\n  "1"\n]
│  └── [\n  "2001"\n]
│     └── [\n  "1"\n]
│        └── part-0.parquet
├── [\n  "2"\n]
│  └── [\n  "2002"\n]
│     └── [\n  "2"\n]
│        └── part-0.parquet
├── [\n  "3"\n]
│  └── [\n  "2003"\n]
│     └── [\n  "3"\n]
│        └── part-0.parquet
├── [\n  "4"\n]
│  └── [\n  "2004"\n]
│     └── [\n  "4"\n]
│        └── part-0.parquet
└── [\n  "5"\n]
   └── [\n  "2004"\n]
      └── [\n  "5"\n]
         └── part-0.parquet
```

**Comment by johnseekins** [comment]
Interesting. If I'm honest, I'm not sure why the columns are `large_string`. I used polars a bit in writing the files, and it seems to be creating all columns as `large_string` instead of `string`.

**Comment by wjones127** [comment]
Polars only uses large_string instead of string to avoid the limitations of the 32-bit offsets in string. Basically string can't hold more than 2GB of string data per array, so to have larger string columns they must either be chunked or use large_string with 64-bit offsets. But we should support large strings better in datasets!

**Comment by johnseekins** [comment]
> Polars only uses large_string instead of string to avoid the limitations of the 32-bit offsets in string. Basically string can't hold more than 2GB of string data per array, so to have larger string columns they must either be chunked or use large_string with 64-bit offsets.

I had a feeling that would be the reason why. Thanks for that clarification.

While y'all work out what to do about `large_string`...is there another way around this problem?

**Comment by wjones127** [comment]
I think even if the arrays are `large_string`, you can still specify `string` in the partitioning. This seems to work:

```python
import pyarrow as pa
import pyarrow.dataset as ds

table = pa.table(
    {
        "partition1": pa.array(["1", "2", "3", "4", "5"], pa.large_string()),
        "partition2": pa.array(["2001", "2002", "2003", "2004", "2004"], pa.large_string()),
        "3": pa.array(["1", "2", "3", "4", "5"], pa.large_string()),
        "val": list(range(5)),
    }
)

file_options = ds.ParquetFileFormat().make_write_options(compression="zstd")
partitions = ds.partitioning(
    schema=pa.schema(
        [
            ("partition1", pa.string()),
            ("partition2", pa.string()),
            ("3", pa.string()),
        ]
    )
)

ds.write_dataset(
    table,
    f"tables/test_parts",
    format="parquet",
    file_options=file_options,
    partitioning=partitions,
    schema=table.schema,
    existing_data_behavior="overwrite_or_ignore",
)
```

**Comment by johnseekins** [comment]
That solved my problem. I'm genuinely not sure why I didn't try that sooner. Thanks @wjones127 !
