### ISSUE TITLE
[Packaging] need apache-arrow  9.0.0 version

### ISSUE THREAD

**Issue by yashwanth-bit** [apache/arrow#34545]
### Describe the usage question you have. Please include as many useful details as  possible.

We are using red-parquet (version 6.0.1) in our project. currently we are facing issue with package while deploying (GitHub Actions) in test environment. on October 25th 2022 we successfully implemented the deployment. but when we try to deploy the changes after 2 days, the deployment got failed because apache-apt-source got updated for ubuntu version.

Successfully implemented software: apache-arrow-apt-source-9.0.0 version

I need above to implement successfully.Could you please provided me link for download apache-arrow-apt-source-9.0.0 

### Component(s)

Packaging

**Comment by kou** [comment]
* How did you install Apache Arrow?
* What Ubuntu version are you using?

URL for Ubuntu 20.04: https://apache.jfrog.io/ui/native/arrow/ubuntu/pool/focal/main/a/apache-arrow-apt-source/

BTW, please don't set all components.

**Comment by kou** [comment]
See also: https://arrow.apache.org/install/

**Comment by yashwanth-bit** [comment]
I followed above link. but we facing same issue because our application contains red-parquet with version 6.0.1 and its mandatory to use red-parquet with version 6.0.1

**Comment by yashwanth-bit** [comment]
> * How did you install Apache Arrow?
> * What Ubuntu version are you using?
> 
> URL for Ubuntu 20.04: https://apache.jfrog.io/ui/native/arrow/ubuntu/pool/focal/main/a/apache-arrow-apt-source/
> 
> BTW, please don't set all components.

 I try to install apache-arrow-apt-source_9.0.0-1_all.deb file but I prompt me below error 

![image](https://user-images.githubusercontent.com/60813323/224932637-70cb0c29-e584-4913-acd6-ca18b40792a1.png)

**Comment by kou** [comment]
What Ubuntu version are you using?

**Comment by yashwanth-bit** [comment]
ubuntu version 20.04

**Comment by kou** [comment]
I confirmed that the following command lines work on clean Ubuntu 20.04 Docker image (`ubuntu:focal`):

```bash
apt update
apt install -y -V ca-certificates lsb-release wget
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
apt update
apt install -V \
    gir1.2-arrow-1.0=6.0.1-1 \
    gir1.2-parquet-1.0=6.0.1-1 \
    libarrow-dev=6.0.1-1 \
    libarrow-glib-dev=6.0.1-1 \
    libarrow-glib600=6.0.1-1 \
    libarrow600=6.0.1-1 \
    libparquet-dev=6.0.1-1 \
    libparquet-glib-dev=6.0.1-1 \
    libparquet-glib600=6.0.1-1 \
    libparquet600=6.0.1-1
```

BTW, 6.0.1 isn't maintained. I recommend that you upgrade your red-parquet to the latest version.

**Comment by yashwanth-bit** [comment]
Red-parquet with version 6.0.1-1 version is  mandatory for our application and our developer are not willing to change red-parquet version . so we need apache arrow apt source file with 9.0.0-1 file
