### ISSUE TITLE
[Python] Expose Run-End Encoded arrays in PyArrow

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#34568]
### Describe the bug, including details regarding any error messages, version, and platform.

The python bindings are setup to warn us if there is a compute function that does not have python bindings.  The fix should be pretty straightforward.  Look at https://github.com/apache/arrow/pull/34084/files for an example.

```
/home/pace/dev/arrow/python/pyarrow/compute.py:206: RuntimeWarning: Python binding for RunEndEncodeOptions not exposed
  warnings.warn("Python binding for {} not exposed"
```

### Component(s)

Python

**Comment by westonpace** [comment]
CC @felipecrv

**Comment by felipecrv** [comment]
take
