### ISSUE TITLE
[R] CMake was not found locally and download failed.

### ISSUE THREAD

**Issue by wang-tan** [apache/arrow#34573]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi, I want to install r-arrow in my conda environment with the R install command or install from a git checkout，but I keep failing with the error message "cmake was not found locally and download failed".  However, there is cmake in my conda environment and the version of cmake is 3.3.1 . I have no idea what's wrong.

### Component(s)

R

**Comment by wang-tan** [comment]
my operating system is centos 7. 
This is the error message when install arrow from a git checkout:
![image](https://user-images.githubusercontent.com/9820714/225331963-3162a9b7-997f-4fde-92d1-8282c49bf459.png)

This is the error message when using the R command:
![image](https://user-images.githubusercontent.com/9820714/225332924-2b3e4d5c-0c1b-426c-a4b0-3f9960653bb4.png)

This  is the message from conda install:
![image](https://user-images.githubusercontent.com/9820714/225333207-c1ade09b-8946-4b1d-877f-283d84feb70a.png)

**Comment by eitsupi** [comment]
> However, there is cmake in my conda environment and the version of cmake is 3.3.1 . I have no idea what's wrong.

It seems that it requires cmake 3.10 or later.

https://github.com/apache/arrow/blob/3df5ba8bc72e371cdf4f7ab95e6e7191716c61ab/r/tools/nixlibs.R#L468-L486

Can you install a newer version of cmake?

**Comment by assignUser** [comment]
On Centos 7 you have to install and activate devtoolset for arrow >= 10.0.0 as we have switched to C++17 and as @eitsupi  said cmake is also required to be >= 3.10. 

By setting `NOT_CRAN=TRUE` and `ARROW_R_DEV=TRUE` you should be able to use the prebuilt binary for centos (wyou will still need cmake and devtoolset to build the R package but you will not have to build the C++ library)

**Comment by wang-tan** [comment]
Hi, thank you for your reply! 
I have upgrated the cmake to version 3.26，and setting "Sys.setenv(NOT_CRAN=TRUE, ARROW_R_DEV=TRUE)"  in R before "install.packages("arrow")", but I get other error messages, like this 

![image](https://user-images.githubusercontent.com/9820714/225535843-a9021423-f864-42fe-a404-767b20ed3a06.png)

and

![image](https://user-images.githubusercontent.com/9820714/225535715-48b2f6b8-7515-4337-9f8a-c15c47762d4b.png)

**Comment by wang-tan** [comment]
According to the url (https://apache.jfrog.io/artifactory/arrow/r/11.0.0/libarrow/bin/centos-7/arrow-11.0.0.zip), I download the libarrow binaries and installed arrow again using command "Sys.setenv("ARROW_DOWNLOADED_BINARIES" = "/home/wtt/src/arrow-11.0.0.zip");
install.packages](https://rdrr.io/r/utils/install.packages.html)("arrow")"，but there was error message too

![image](https://user-images.githubusercontent.com/9820714/225547711-65fc6cb3-fd00-446d-93db-83e3af3f1c59.png)

**Comment by assignUser** [comment]
Hm, there might be an incompatability with the 11.0.0 binaries and the most recent cran release. Could you try this again with the 11.0.0 centos binary and `devtools::install_version("arrow", "11.0.0")`?

**Comment by pormr** [comment]
You might want to install **binary** packages from repositories like Rstudio's package manager. [[ref1](https://arrow.apache.org/docs/r/articles/install.html#install-release-version-easy-way), [ref2](https://packagemanager.rstudio.com/__docs__/admin/serving-binaries/#binary-user-agents)]
```R
options("download.file.method" = "wget",
        "download.file.extra" = sprintf("--header \"User-Agent: R (%s)\"", paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"])))
install.packages("arrow", repos = "https://packagemanager.rstudio.com/all/__linux__/<distrib>/latest")
```
You can check your linux distribution [here](https://packagemanager.rstudio.com/client/#/repos/2/packages/arrow:~:text=Own%20Python%20Packages-,DISTRIBUTION).

**Comment by thisisnic** [comment]
I'm closing this as there's been no interaction on this in ~ 6 months
