### ISSUE TITLE
[Go][Parquet] RLE problem with ''(blank)"

### ISSUE THREAD

**Issue by allinux** [apache/arrow#34603]
### Describe the bug, including details regarding any error messages, version, and platform.

There is a bug where `''` is loaded as `\x00` when `WithDictionaryDefault` of `parquet.WriterProperties` is set to `true` when all data in the column is `''`.
If processed as `false`, it is normally loaded as `''`.
It seems to occur during RLE processing, but need to check.

sample_parquet.zip contains src.parquet and dest.parquet files, `src.parquet` is a file with `''` and `dest.parquet` is a file reloaded with `WithDictionaryDefault` set to `true`.

- python code for check

```
In [1]: import pandas as pd
In [2]: src = pd.read_parquet('src.parquet')
In [3]: src
Out[3]: 
  reserved1
0          
1          
2          
3          
4          
5          

In [4]: src.iloc[0].to_dict()
Out[4]: {'reserved1': ''}

In [5]: dest = pd.read_parquet('dest.parquet')

In [6]: dest
Out[6]: 
  reserved1
0         
1         
2         
3         
4         
5         

In [7]: dest.iloc[0].to_dict()
Out[7]: {'reserved1': '\x00'}
```

[sample_parquet.zip](https://github.com/apache/arrow/files/11000320/sample_parquet.zip)

### Component(s)

Go

**Comment by zeroshade** [comment]
@allinux can you provide the code you are using to perform the writes?

**Comment by allinux** [comment]
@zeroshade 
Thanks for the commet.
Please see sample code below.
'''
package main

import (
	"context"
	"os"

	"github.com/apache/arrow/go/v12/arrow/memory"
	"github.com/apache/arrow/go/v12/parquet"
	"github.com/apache/arrow/go/v12/parquet/file"
	"github.com/apache/arrow/go/v12/parquet/pqarrow"
)

func main() {
	mem := memory.NewCheckedAllocator(memory.DefaultAllocator)

	src, _ := file.OpenParquetFile("src.parquet", false, file.WithReadProps(parquet.NewReaderProperties(mem)))
	defer src.Close()

	schema := src.MetaData().Schema

	arrowRdr, _ := pqarrow.NewFileReader(src, pqarrow.ArrowReadProperties{}, mem)

	arrowSchema, _ := pqarrow.FromParquet(schema, &pqarrow.ArrowReadProperties{}, src.MetaData().KeyValueMetadata())

	props := parquet.NewWriterProperties(
		parquet.WithDictionaryDefault(true), // \x00
	)

	dest, _ := os.OpenFile("dest.parquet", os.O_CREATE|os.O_APPEND|os.O_RDWR|os.O_TRUNC, 0644)
	arrowWriter, _ := pqarrow.NewFileWriter(arrowSchema, dest, props, pqarrow.DefaultWriterProps())
	defer arrowWriter.Close()
	
	arrowWriter.NewRowGroup()
	for i, numRowGroups := 0, src.NumRowGroups(); i < numRowGroups; i++ {
		rowGroupReader := arrowRdr.RowGroup(i)
		for i, numColumns := 0, schema.NumColumns(); i < numColumns; i++ {
			datas, _ := rowGroupReader.Column(i).Read(context.Background())
			if datas.Len() > 0 {
				for _, ar := range datas.Chunks() {
					arrowWriter.WriteColumnData(ar)
				}
			}
			datas.Release()
		}
	}
}
'''
