### ISSUE TITLE
How to Send ListOfStruct Data in Row Format in C# using Arrow

### ISSUE THREAD

**Issue by facetosea** [apache/arrow#34604]
### Describe the usage question you have. Please include as many useful details as  possible.

Specifically, I am wondering how to send ListOfStruct data in a format where each row of data is sent individually. The desired format is similar to the following:
`[
    {
        "records":[
            {
                "table_name":"t1",
                "t1":199999,
                "col1":"v11"
            },
            {
                "table_name":"t2",
                "t1":199999992,
                "col1":"v12"
            }
        ]
    }
]`

I came across the following function in the Arrow GitHub repository:
https://github.com/apache/arrow/blob/main/csharp/test/Apache.Arrow.Tests/StructArrayTests.cs#L89

However, the output generated by this function is still in columnar format. 
I should do? Or where can I find the answer?

### Component(s)

C#

**Comment by westonpace** [comment]
There is no way to do this today.  There has been discussion in the past of a "[packed struct](https://lists.apache.org/thread/6s5coljptgk3oc83f6qnds87fvydg86s)" but this has not been adopted and no implementation has been proposed.  Sometimes the [fixed size list ](https://arrow.apache.org/docs/format/Columnar.html#fixed-size-list-layout)type can be used but it is not exactly what you are looking for.

**Comment by facetosea** [comment]
> There is no way to do this today. There has been discussion in the past of a "[packed struct](https://lists.apache.org/thread/6s5coljptgk3oc83f6qnds87fvydg86s)" but this has not been adopted and no implementation has been proposed. Sometimes the [fixed size list ](https://arrow.apache.org/docs/format/Columnar.html#fixed-size-list-layout)type can be used but it is not exactly what you are looking for.

Thank you for your reply, it was very helpful. I'm glad to report that my issue has been resolved, and we ended up choosing Column Format data transmission.

I tried using the Schema definition below, it seems to have the effect of "packed struct", it doesn't look very elegant.

> recordType = new StructType(colField);
>       var recordsType2 = new StructType(new List<Field>() {
>             new Field("ITEM", recordType, true)
>     });
