### ISSUE TITLE
parquet build error 

### ISSUE THREAD

**Issue by assassin5615** [apache/arrow#3463]
Downloaded Arrow and followed the build instruction but got following error.

> No rule to make target `thrift_ep/src/thrift_ep-install/lib/libthriftd.a', needed by `src/parquet/parquet_types.cpp'.  Stop

it says that thrift has been downloaded and installed. but only bin directory is installed. library is not built.

> [  7%] Performing configure step for 'thrift_ep'
> -- thrift_ep configure command succeeded.  See also /home/ylei/development/third_party/parquet/arrow/arrow/cpp/debug/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-configure-*.log
> [  8%] Performing build step for 'thrift_ep'
> -- thrift_ep build command succeeded.  See also /home/ylei/development/third_party/parquet/arrow/arrow/cpp/debug/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-build-*.log
> [  9%] Performing install step for 'thrift_ep'
> -- thrift_ep install command succeeded.  See also /home/ylei/development/third_party/parquet/arrow/arrow/cpp/debug/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-install-*.log
> [ 10%] Completed 'thrift_ep'
> [ 10%] Built target thrift_ep

**Comment by wesm** [comment]
Can you open a JIRA issue and provide more complete description of your environment and how you invoked the build system?

**Comment by assassin5615** [comment]
ok, created a one at https://issues.apache.org/jira/browse/ARROW-4348
