### ISSUE TITLE
[C++] Prefer unsafe casting by default in Substrait

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#34644]
### Describe the enhancement requested

Substrait specifies a failure behavior (return null or error) for casting.  However, it does not specify what exactly constitutes a failure. When we added bindings for the cast expression we assumed that Substrait wanted a safe cast.  However, I have since learned that most existing engines (e.g. postgres, spark, etc.) will perform an unsafe cast by default and only consider a failure when casting is impossible (e.g. "foo" to integer).

I'd like to eventually see Substrait add support for specifying more precisely what kind of casting should occur.  In the meantime I think we should update the default to unsafe casting to match user expectation.

### Component(s)

C++

**Comment by jorisvandenbossche** [comment]
> However, I have since learned that most existing engines (e.g. postgres, spark, etc.) will perform an unsafe cast by default

For postgres, that is not what I see based on a quick test for integer overflow:

```
test_db=# SELECT CAST (10000000 AS smallint);
ERROR:  smallint out of range
```

**Comment by jorisvandenbossche** [comment]
On the other hand, float truncation is indeed done by postgres:

```
test_db=# SELECT CAST (1.5 AS integer);
 int4 
------
    2
(1 row)
```

(although it is interesting to see that the result is 2, while in arrow casting 1.5 to int64 with allow_float_truncate=True gives 1)

**Comment by westonpace** [comment]
It seems SQL server truncates so I think we'll need both behaviors.  Sounds like something else we will need to document more thoroughly in Substrait and will also need to be added to the list of dialect behaviors.  My original motivation was to allow float->int.  I'm pretty open to whatever default we want (e.g. allow float/decimal truncation but not integer truncation) but I believe @icexelloss wanted something more flexible than defaulting to "safe only".
