### ISSUE TITLE
how to select children of a struct with Scan

### ISSUE THREAD

**Issue by j0bekt01** [apache/arrow#34649]
### Describe the usage question you have. Please include as many useful details as  possible.

How do you scan nested structs in R? This is what I tried so far but to no avail: 
`PATH <- "s3 URI path"`
`df <- arrow::open_dataset(sources=PATH)`
`scan_builder <- df$NewScan()`
Neither of these works.
`scan_builder$Project(list(doc_id = Expression$field_ref("document.id")))`
`scan_builder$Project(list(doc_id = Expression$field_ref("document.id")))`

However, if I do:
`scan_builder$Project(list(doc_id = Expression$field_ref("document")))` works but I don't want the entire nested object imported into R. 

### Component(s)

R

**Comment by nealrichardson** [comment]
In the dev version of the package, you can use `$` to reference nested fields in a struct: see #19706

**Comment by j0bekt01** [comment]
Thank you, sir! Do you know when this will be GA?

**Comment by nealrichardson** [comment]
Next release is in April, not sure the exact date

**Comment by j0bekt01** [comment]
awesome! Thank you.
