### ISSUE TITLE
[CI][Python][Packaging] Some nightly wheels fail to upload to gemfury

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#34656]
### Describe the bug, including details regarding any error messages, version, and platform.

Some of our Windows wheel nightly packaging jobs:

[wheel-windows-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/4454512931/jobs/7823752484)
[wheel-windows-cp311-amd64](https://github.com/ursacomputing/crossbow/actions/runs/4454517460/jobs/7823761351)
[wheel-windows-cp38-amd64](https://github.com/ursacomputing/crossbow/actions/runs/4454510998/jobs/7823749043)
[wheel-windows-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/4454516668/jobs/7823759936)

Have been failing to upload to gemfury:
```
Run path=$(ls arrow/python/dist/*.whl)
  path=$(ls arrow/python/dist/*.whl)
  curl -F "package=@${path}" https://${CROSSBOW_GEMFURY_TOKEN}@push.fury.io/${CROSSBOW_GEMFURY_ORG}/
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    PYTHON: 3.8
    REPO: ghcr.io/ursacomputing/arrow
    ARCHERY_USE_DOCKER_CLI: 1
    pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.8.10\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.8.10\x64
    CROSSBOW_GEMFURY_TOKEN: ***
    CROSSBOW_GEMFURY_ORG: ***
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 20.4M    0     0    0 65535      0  1283k  0:00:16 --:--:--  0:00:16 1333k
curl: (55) Failed sending data to the peer
Error: Process completed with exit code 55.
```
This seem to be consistent only for those wheels for the last 4-5 days.

### Component(s)

Continuous Integration, Packaging, Python

**Comment by raulcd** [comment]
@kszucs @kou can I be added to the [arrow-nightlies](https://gemfury.com/arrow-nightlies) team on gemfury to investigate if is something about quotas or account related? My gemfury username is the same as my GitHub (raulcd)

**Comment by kou** [comment]
@kszucs Could you make me an owner of arrow-nightlies?
