### ISSUE TITLE
[Packaging][C++] gdb integration is not compatible with conda packaging

### ISSUE THREAD

**Issue by h-vetinari** [apache/arrow#34670]
### Describe the bug, including details regarding any error messages, version, and platform.

gdb apparently needs to reflect the path of a given library (for which we want to have gdb-support) in the path to that support artefact. Currently this is being done by using
https://github.com/apache/arrow/blob/1ba4425fab35d572132cb30eee6087a7dca89853/cpp/src/arrow/CMakeLists.txt#L674-L675

However, this is incompatible with the way that conda-forge works, where the packaging step needs to install the package in order to determine which files need to be packaged at all. The use of `CMAKE_INSTALL_FULL_LIBDIR` means that we'll be baking the path of that temporary build environment in the feedstock into the final artefact, which is both non-functional, and additionally leads to [problems](https://github.com/conda-forge/arrow-cpp-feedstock/issues/935) due to path length.

The core issue is that we do not know the path to the final environment in conda until we're actually in it. In order to support the gdb integration nevertheless, the current work-around is to use a [patch](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/recipe/patches/0001-don-t-bake-non-relocatable-CMAKE_INSTALL_FULL_LIBDIR.patch) and an [activation script](https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/recipe/activate.sh) (which will always execute upon entering/activating an environment).

@kou asked me in https://github.com/apache/arrow/pull/34652 to open an issue for this. It would be great if we could have a better way to support gdb also in conda-forge, but at the moment I don't see how that would work.

### Component(s)

Packaging

**Comment by h-vetinari** [comment]
That sounds reasonable. 👍

**Comment by kou** [comment]
Thanks for confirming this approach.
I've opened a pull request: #34672

**Comment by kou** [comment]
@h-vetinari I've merged #34672. Could you try it in #34652?

**Comment by wjones127** [comment]
Could this be related to this failure: https://github.com/ursacomputing/crossbow/actions/runs/4653277236/jobs/8234012192

**Comment by kou** [comment]
@github-actions crossbow submit test-conda-python-3.10

**Comment by kou** [comment]
@github-actions crossbow submit test-conda-python-3.10

**Comment by kou** [comment]
I think that this is not related.
https://github.com/apache/arrow/pull/34020/files#diff-89ec0f60ce64dbc83670ee53b2182c2817d2a282c7175f2e245414981ba68330R19 may be related.
Anyway, could you open a new issue for it?

**Comment by alex-sarafianos** [comment]
In what version was this fixed? I'm experiencing problems in the installation location of libarrow.so.1400.1.0-gdb.py (same with libarrow.so.1400.2.0-gdb.py) when using conda.

**Comment by h-vetinari** [comment]
Can you please raise an issue on the [feedstock](https://github.com/conda-forge/arrow-cpp-feedstock) for arrow, including the requested information?

We spent quite a bit of effort in conda-forge into getting gdb integration working (since v10/v11), so I'd like to know what's not working.
