### ISSUE TITLE
[Python] Expose Run-End Encoded arrays in PyArrow

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#34701]
The initial bindings for Run-End Encoded arrays (the array and type classes) landed in https://github.com/apache/arrow/pull/34570. Some follow-ups:

- [x] https://github.com/apache/arrow/pull/34570
- [x] https://github.com/apache/arrow/issues/34686
- [x] https://github.com/apache/arrow/issues/40273
- [x] https://github.com/apache/arrow/issues/40659

**Comment by felipecrv** [comment]
`RunEndEncoded` is one of the types listed here as "NotImplemented". No specific reason, just a matter of taking the time to write and test the implementation.

https://github.com/apache/arrow/blob/main/python/pyarrow/src/arrow/python/arrow_to_pandas.cc#L1348

The list of things to implement for a new format is huge and this is one of the things that I didn't have time to complete yet.

**Comment by AlenkaF** [comment]
Closing this issue as all subtasks are completed.
