### ISSUE TITLE
[MSVC] Arrow failed to run test with case "arrow-compute-scalar-cast-test (Failed)"

### ISSUE THREAD

**Issue by Zhaojun-Liu** [apache/arrow#34714]
Hi, recently, we update the commit of Arrow, and it failed to run test with case "arrow-compute-scalar-cast-test" on windows. Could you please help look this issue? Thanks.

**Repro steps:**
1. git clone https://github.com/apache/arrow F:\gitP\apache\arrow
2. git -C "F:\gitP\apache\arrow" submodule sync
3. git -C "F:\gitP\apache\arrow" submodule update --init --recursive
4. mkdir F:\gitP\apache\arrow\cpp\build_amd64 and cd F:\gitP\apache\arrow\cpp\build_amd64
5. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DARROW_BUILD_TESTS=ON -DBOOST_ROOT=F:\tools\boost_1_77_0\x64 .. 
6. msbuild /maxcpucount:1 /p:Platform=x64 /p:Configuration=Release arrow.sln /t:Rebuild
7. set ARROW_TEST_DATA=F:\gitP\apache\arrow\testing\data
8. ctest -C Release --output-on-failure 

The commit we used: f9324b7

**Expected Result:**
run test pass.

**Actual Result:**
The following tests FAILED:
	 17 - arrow-compute-scalar-cast-test (Failed)

Detailed log: 
[test.log.txt](https://github.com/apache/arrow/files/11057906/test.log.txt)

**Environment:**
OS: Windows server 2022
Visual Studio: VS2022 V17.5.1

### Component(s)

C++

**Comment by kou** [comment]
You need to download timzeone data to `~\Downloads` manually.
See also: https://github.com/apache/arrow/blob/main/ci/scripts/download_tz_database.sh

**Comment by Zhaojun-Liu** [comment]
> You need to download timzeone data to `~\Downloads` manually. See also: https://github.com/apache/arrow/blob/main/ci/scripts/download_tz_database.sh

Ok, thank you for the reply, I will have a try.

**Comment by Zhaojun-Liu** [comment]
> You need to download timzeone data to `~\Downloads` manually. See also: https://github.com/apache/arrow/blob/main/ci/scripts/download_tz_database.sh

It worked, thank you.
