### ISSUE TITLE
[Java] ZstdCompressionCodec uses hard-coding compression level which cannot be configurable

### ISSUE THREAD

**Issue by viirya** [apache/arrow#34749]
### Describe the enhancement requested

ArrowFileWriter/ArrowStreamWriter add compression support for 12.0.0-dev. But [ZstdCompressionCodec](https://github.com/apache/arrow/blob/196fbe5f5e0669b1f8bf71005c8a4c6a4e0fb2da/java/compression/src/main/java/org/apache/arrow/compression/ZstdCompressionCodec.java#L41) uses hard-coding compression level (level 3) which cannot be configurable. As ZSTD level affects compression speed and ratio, ideally we should make such parameter configurable to developers.

### Component(s)

Java

**Comment by lidavidm** [comment]
@davisusanibar you need to assign yourself here
