### ISSUE TITLE
[Python][CI] Add a test build using Cython 3

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#34756]
See https://github.com/apache/arrow/issues/34564. PR https://github.com/apache/arrow/pull/34726 fixed the warnings/errors when building pyarrow with current Cython 3 beta. 

To ensure this keeps working / pyarrow is compatible with the future Cython 3 release, we should add a CI build that uses Cython 3 pre-release (we can install the `--pre` wheel with pip in one of the builds).

**Comment by assignUser** [comment]
Does this have the same issues with dependencies as python pre-release versions? Or does this only rely on our own code?

**Comment by jorisvandenbossche** [comment]
No, cython is "just" a python package you install, and for which you in principle can install any version that you support when building (no other package in the environment should have a _runtime_  dependency on cython, it's only a build time dependency)

**Comment by westonpace** [comment]
Thanks for creating this.  It looks like 3.0.0b2 has released.  b1 was flawed but I think b2 has the fixes we need.

**Comment by assignUser** [comment]
@jorisvandenbossche is there any specific python job we should duplicate for this? I think it would make sense to add something like this to the nightlies and not the PR CI.

**Comment by jorisvandenbossche** [comment]
If we use the nightlies, maybe we can use one of the pandas/numpy dev builds (in "Integration Tests" section)

**Comment by raulcd** [comment]
As this is to add a new nightly build, should this be added prior to 12.0.0? I don't think it's a blocker.

**Comment by jorisvandenbossche** [comment]
No, certainly not a blocker

**Comment by jorisvandenbossche** [comment]
We enabled cython 3 in the meantime, so this can be closed.
