### ISSUE TITLE
[C++][Gandiva] Accept LLVM 16

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#34768]
Some builds started to pick up LLVM 16, while we currently only accept up to 15:

https://github.com/apache/arrow/blob/24ba1cf75c01040b279514ecc063975de272b766/cpp/CMakeLists.txt#L130-L132

Similar to https://github.com/apache/arrow/pull/14125 for LLVM 15.

For example, the nightly pandas crossbow build is failing because conda started to install LLVM 16 (eg https://github.com/ursacomputing/crossbow/actions/runs/4551997501/jobs/8026770676)

**Comment by js8544** [comment]
Thanks @jorisvandenbossche for bringing this up! I'll work on this soon.

**Comment by js8544** [comment]
take

**Comment by kou** [comment]
@js8544 Are you working on this? Can I work on this?

**Comment by js8544** [comment]
> @js8544 Are you working on this? Can I work on this?

Sorry I got caught by other stuff. Please work on this. Thanks!

**Comment by kou** [comment]
OK!
