### ISSUE TITLE
Bintray repository signature verification fails

### ISSUE THREAD

**Issue by mbrobbel** [apache/arrow#3476]
Installation of the packages using the Bintray repository (in a Ubuntu xenial container) as instructed [here](https://github.com/apache/arrow/blob/master/site/install.md#c-and-glib-c-packages-for-debian-gnulinux-ubuntu-and-centos) fails for me:

```
W: GPG error: https://dl.bintray.com/apache/arrow/ubuntu xenial Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 25BCCA5220D84079
E: The repository 'https://dl.bintray.com/apache/arrow/ubuntu xenial Release' is not signed.
```

**Comment by kszucs** [comment]
cc @kou

**Comment by kou** [comment]
Oh...
`signed-by` is available since APT 1.3: https://wiki.debian.org/DebianRepository/Format#Signed-By

Ubuntu 16.04 uses APT 1.2.24.

I'll consider how to fix it.

**Comment by kou** [comment]
@mbrobbel Could you open an issue for this case on JIRA? https://issues.apache.org/jira/projects/ARROW/issues

**Comment by mbrobbel** [comment]
> @mbrobbel Could you open an issue for this case on JIRA? https://issues.apache.org/jira/projects/ARROW/issues

https://issues.apache.org/jira/browse/ARROW-4368

**Comment by kou** [comment]
Thanks!

**Comment by cobbr2** [comment]
We're seeing this again this week:

**Comment by cobbr2** [comment]
My apologies. We get the keyring by directly downloading from `dl.bintray.com`, and they are now serving the ring using a redirect to Akamai. In our installation scripts, we needed to change from:

**Comment by wesm** [comment]
Where does this change need to be made, on https://github.com/apache/arrow-site/blob/master/install.md? Can you please open a JIRA issue? cc @kou

**Comment by cobbr2** [comment]
This was caused by not following links when downloading the gpg key files.
The instructions should use `curl - L` to reflect that Bintray now
redirects to Akamai.

**Comment by kou** [comment]
Created:

* https://issues.apache.org/jira/browse/ARROW-7565
* https://github.com/apache/arrow-site/pull/40

FYI: I'll update install process for Debian GNU/Linux and Ubuntu to use `apache-arrow-archive-keyring` package when we release 0.16.0.
