### ISSUE TITLE
[Ruby] Query a parquet file on S3 without downloading it (using byte ranges)

### ISSUE THREAD

**Issue by collimarco** [apache/arrow#34781]
### Describe the usage question you have. Please include as many useful details as  possible.

I am new to this project and I am looking at the Ruby gem in particular:

https://github.com/apache/arrow/tree/main/ruby

If you load **a large Parquet file stored in S3**:

```
require 'arrow-dataset'

s3_uri = URI('s3://bucket/public.parquet')
Arrow::Table.load(s3_uri)
```

Can you query it without downloading the entire file? Is it possible to download only the relevant parts using byte ranges? Or the above command will always download the entire file and it's the only available solution?

Thanks

### Component(s)

Ruby

**Comment by kou** [comment]
Sorry, I missed this.

We can't use byte ranges directly but we can use condition push down to reduce download size.

We doesn't provide DSL to build condition yet (#29928) but the following will work:

```ruby
require 'arrow-dataset'

s3_uri = URI('s3://bucket/public.parquet')
Arrow::Table.load(s3_uri, filter: [:equal, :column_name, 100]) # "column_name == 100"
```

See https://arrow.apache.org/docs/cpp/compute.html for available functions.

**Comment by collimarco** [comment]
@kou Thanks for the reply!

> We can't use byte ranges directly but we can use condition push down to reduce download size

Can you please clarify this? Aren't they the same thing? You are basically avoiding the download of the entire file and you read it partially (so I guess that the partial download uses byte ranges under the hood)

**Comment by kou** [comment]
If we use condition push down, we can reduce target data in `.parquet`. So we don't need to download entire data.

Could you explain your use case?

**Comment by kou** [comment]
Internal S3 filesystem implementation will use bytes range: https://github.com/apache/arrow/blob/main/cpp/src/arrow/filesystem/s3fs.cc#L1103-L1104
But do you really want to know about it?

**Comment by collimarco** [comment]
> So we don't need to download entire data.

Great. 

> Could you explain your use case?

I would like to store a large parquet file on S3 and search on it with some conditions without having to download it entirely.

**Comment by kou** [comment]
OK. Then you can use the condition push down.

**Comment by kou** [comment]
Ah, you need to use `URI` instead of `String` to use `filter:` (and `format: :parquet` is redundant when a file name has `.parquet` extension):

```text
table = Arrow::Table.load(URI('sample.parquet'), filter: [:equal, :status, 200])
puts table
```

**Comment by collimarco** [comment]
@kou Thanks for the reply. Your code gives me this error:

```
/Users/example/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/red-arrow-12.0.0/lib/arrow/table-loader.rb:61:in `load': Arrow::Table load source must be one of [uri_https, file, uri_http]: #<URI::Generic sample.parquet> (ArgumentError)
```

There is a `sample.parquet` in the local directory, just for testing. `filter` doesn't work for local files?

**Comment by kou** [comment]
Ah, sorry. I forgot to mention explicitly: You need to add `require "arrow-dataset"` to use `filter:`.

**Comment by collimarco** [comment]
@kou Thanks! It works!

The only downside is that in my benchmark on a 100M log file I don't see any performance gains.

Original Ruby program:

```
require 'arrow'
require 'parquet'

table = Arrow::Table.load('sample.parquet', format: :parquet)
puts table.slice { |slicer| slicer['status'] == 200 }
```

Improved Ruby program:

```
require 'arrow'
require 'parquet'
require 'arrow-dataset'

file = URI('sample.parquet')
table = Arrow::Table.load(file, filter: [:equal, :status, 200])
puts table
```

Measuring with the `time` command I get `~ 1.2s` for both versions.

**Comment by kou** [comment]
Could you try a Parquet file on S3 too?
