### ISSUE TITLE
[R] Trouble installing from source with conda

### ISSUE THREAD

**Issue by abalter** [apache/arrow#34783]
### Describe the bug, including details regarding any error messages, version, and platform.

I use conda for package management, actually micromamba. I have the most current version of r-arrow installed.

However, I'm finding some crashy behavior with large files: creating/loading datasets, queries, etc.

I noticed in an issue someone installed from source through R and that fixed the problem. I'm doing it as [here](https://github.com/apache/arrow/issues/34061#issuecomment-1430672649), but it is failing.

```r
> Sys.setenv("NOT_CRAN" = "true", "LIBARROW_BUILD" = FALSE, "ARROW_R_DEV" = TRUE)
> install.packages("arrow")
trying URL 'https://cran.rstudio.com/src/contrib/arrow_11.0.0.3.tar.gz'
Content type 'application/x-gzip' length 3921484 bytes (3.7 MB)
==================================================
downloaded 3.7 MB

* installing *source* package ‘arrow’ ...
** package ‘arrow’ successfully unpacked and MD5 sums checked
** using staged installation
**** pkg-config not installed, setting ARROW_DEPENDENCY_SOURCE=BUNDLED
*** Unable to find libcurl and openssl
*** Proceeding without libarrow (build not authorized)
------------------------- NOTE ---------------------------
There was an issue preparing the Arrow C++ libraries.
See https://arrow.apache.org/docs/r/articles/install.html
---------------------------------------------------------
ERROR: configuration failed for package ‘arrow’
* removing ‘/home/users/balter/micromamba/lib/R/library/arrow’
* restoring previous ‘/home/users/balter/micromamba/lib/R/library/arrow’
Warning in install.packages :
  installation of package ‘arrow’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpsZ0yFA/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
```

I also tried installing using [this file](https://github.com/apache/arrow/blob/main/r/R/install-arrow.R) as suggested [here](https://github.com/apache/arrow/issues/34061#issuecomment-1430813609)

But, R can't see that I have conda for some reason:

```r
> source("install-arrow.R")
> install_arrow(nightly=T)
sh: 1: conda: not found
Warning message:
In system("conda install -y -c arrow-nightlies -c conda-forge --strict-channel-priority r-arrow") :
  error in running command
> system('which conda', intern=T)
character(0)
attr(,"status")
[1] 1
Warning message:
In system("which conda", intern = T) :
  running command 'which conda' had status 1
> system('which micromamba', intern=T)
character(0)
attr(,"status")
[1] 1
Warning message:
In system("which micromamba", intern = T) :
  running command 'which micromamba' had status 1
> system('which R', intern=T)
[1] "/usr/local/bin/R"
```

```
(base) balter@exahead1:~$ which conda
alias conda='micromamba'
(base) balter@exahead1:~$ which R
~/micromamba/bin/R
```

### Component(s)

R

**Comment by assignUser** [comment]
Building from source fails because you explicitly forbid it: `Sys.setenv("NOT_CRAN" = "true", "LIBARROW_BUILD" = FALSE, "ARROW_R_DEV" = TRUE)`. Removing `"LIBARROW_BUILD" = FALSE` should get you further!

For the second issue it looks like `system` is not picking up the alias, you could try creating a conda symlink? (or manually run `conda install -y -c arrow-nightlies -c conda-forge --strict-channel-priority r-arrow`).

**Comment by abalter** [comment]
I'm afraid none of that was it. Neither removing `"LIBARROW_BUILD" = FALSE` or setting it to `TRUE` helped.

And the problem isn't with the alias. `micromamba` is the actual name of the executable, and as I showed above,

```r
> system('which micromamba', intern=T)
character(0)
attr(,"status")
[1] 1
Warning message:
In system("which micromamba", intern = T) :
  running command 'which micromamba' had status 1
```

I tried creating a symlink, and R still can't see it, even though I made sure to put the symlink in my path;

```r
> system('which conda', intern=T)
character(0)
attr(,"status")
[1] 1
Warning message:
In system("which conda", intern = T) :
  running command 'which conda' had status 1
> Sys.readlink("~/usr/bin/conda")
[1] "/home/users/balter/.local/bin/micromamba"
```

```
(base) balter@exahead1:~$ which conda
~/usr/bin/conda
(base) balter@exahead1:~$ ls -l usr/bin
total 20
-rw-rw-r-- 1 balter balter 2240 Feb 22 17:07 acc_rocker.sh
lrwxrwxrwx 1 balter balter   40 Mar 29 18:14 conda -> /home/users/balter/.local/bin/micromamba
-rw-rw-r-- 1 balter balter 2219 Feb 23 12:33 f
-rwxr-xr-x 1 balter balter 4399 Jan 17 11:27 qsbatch
-rw-rw-r-- 1 balter balter 2133 Feb 23 12:31 rocker_template
-rw-rw-r-- 1 balter balter   59 Feb 23 12:28 rsstunnel
-rwxr-xr-x 1 balter balter 2757 Feb 21 12:45 sinteract
-rw-rw-r-- 1 balter balter  794 Feb 23 12:33 slurm-21914665.out
-rwxr-xr-x 1 balter balter 3078 Feb 23 12:34 _startrss
```

**Comment by assignUser** [comment]
> I'm afraid none of that was it. Neither removing "LIBARROW_BUILD" = FALSE or setting it to TRUE helped.
And what was the result/error?

**Comment by abalter** [comment]
>And what was the result/error?
Just the same non-zero exit.

Actually, it still has `system("conda install -y -c arrow-nightlies -c conda-forge --strict-channel-priority r-arrow")` which won't work. 

The code should do this instead:

```
  conda <- isTRUE(grepl("conda", R.Version()$platform))

  if (conda) {
    conda_prefix = Sys.getenv("CONDA_PREFIX")
    if (nightly) {
      system(str_glue("{conda_prefix} install -y -c arrow-nightlies -c conda-forge --strict-channel-priority r-arrow"))
    } else {
      system("str_glue("{conda_prefix} install -y -c conda-forge --strict-channel-priority r-arrow"))
    }
  ```

**Comment by abalter** [comment]
I already have the nightly install from conda anyway. But I'm still having some crashy arrow stuff. So I wanted to try installing from source. That's what started all of this.

Seems like a bug that `install.packages('arrow')` give an error no matter what.

**Comment by ahcyip** [comment]
For everyone still having trouble with arrow installation and needing parquet functionality in the short term, try the nanoparquet package :)

**Comment by assignUser** [comment]
@ahcyip Could you stop commenting the same thing under several unrelated and stale issues? It's creating notification spam and is a bit rude tbh.
