### ISSUE TITLE
Provide wheels for Python 3.7 and ARM 32-bit

### ISSUE THREAD

**Issue by me21** [apache/arrow#34804]
### Describe the enhancement requested

I'm using Beaglebone Black single-board computer, which is ARM 32-bit, with Debian Buster and Python 3.7, and I need to install pyarrow to write Parquet files. Direct attempt to install with pip failed, and I went to search the Internet.
I'm going to try and repeat the solution that worked for https://github.com/apache/arrow/issues/33814, but I thought it would be nice to provide wheels for that architecture.
May I ask for help with building in this topic if I stumble across something?

### Component(s)

Parquet, Python

**Comment by assignUser** [comment]
As we are about to drop 3.7 support (#34788) we won't provide such wheels as part of the official releases. 

Please have a look at the development documentation on how to build libarrow+pyarrow from source: https://arrow.apache.org/docs/developers/python.html#building-on-linux-and-macos
