### ISSUE TITLE
[Packaging][Python] Use self-hosted arm64 runner instead of Travis CI for arm64 wheels

### ISSUE THREAD

**Issue by kou** [apache/arrow#34812]
### Describe the enhancement requested

We can use self-hosted arm64 runner in Crossbow jobs (thanks to Voltron Data!) by `runs-on: ["self-hosted", "Linux", "arm64"]`.
See also: #34717

There is only one Crossbow job that uses Travis CI. It's a job for wheels: https://github.com/apache/arrow/blob/fa4b17057570530bba913b92daeba186acb13cba/dev/tasks/tasks.yml#L460

We can use self-hosted arm64 runner for it. We can move away from Travis CI for Crossbow jobs.

Note that we still depend on Travis CI for apache/arrow CI jobs. See also: #20496

### Component(s)

Continuous Integration, Packaging, Python

**Comment by kou** [comment]
@eitsupi Are you interested in this?

**Comment by eitsupi** [comment]
> @eitsupi Are you interested in this?

Sure.
Can I try to work on adding `dev/tasks/python-wheels/github.linux.arm64.yml`?

**Comment by kou** [comment]
Yes.
We may be able to unify `dev/tasks/python-wheels/github.linux.*.yml` to `dev/tasks/python-wheels/github.linux.yml` like `dev/tasks/linux-packages/github.linux.yml`.
