### ISSUE TITLE
[R] Windows R build fails

### ISSUE THREAD

**Issue by icexelloss** [apache/arrow#34843]
### Describe the bug, including details regarding any error messages, version, and platform.

An issue with build R on windows is introduced by #34711:

https://github.com/apache/arrow/pull/34711#issuecomment-1492971506

### Component(s)

R

**Comment by assignUser** [comment]
The other [R errors](https://github.com/ursacomputing/crossbow/actions/runs/4583536440/jobs/8094447479) also seem related:

> ** testing if installed package can be loaded from temporary location
> Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/r/check/arrow.Rcheck/00LOCK-arrow/00new/arrow/libs/arrow.so':
>   dlopen(/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/r/check/arrow.Rcheck/00LOCK-arrow/00new/arrow/libs/arrow.so, 6): Symbol not found: __ZN5arrow5acero7MapNode13InputFinishedEPNS0_8ExecNodeEi
>   Referenced from: /Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/r/check/arrow.Rcheck/00LOCK-arrow/00new/arrow/libs/arrow.so
>   Expected in: flat namespace
