### ISSUE TITLE
Performance of explicit array comparison faster vs. Arrow compute

### ISSUE THREAD

**Issue by zfoobar** [apache/arrow#34845]
### Describe the usage question you have. Please include as many useful details as  possible.

I wrapped the compute_and_write_csv_example.cc code in some timestamps to measure explicit array comparison vs. the arrow::compute method - the output below suggests the explicit comparison is much faster. This may be a dumb question (apologies) - but is this expected? I am exploring Arrow as both an end-user for my AI consultancy and a contributor - I want to understand the performance benefits/use-cases. 

output:

```text
(pyarrow-dev) Zacharys-MacBook-Air:arrow_scratch zacharyfierstadt$ ./compute_and_write_csv_example 
Array explicitly compared
0.000183625 seconds
Arrays compared using a compute function
0.0404125 seconds
Table created
Writing CSV file
```

### Component(s)

Benchmarking, C++

**Comment by westonpace** [comment]
@assignUser 's point is a good one.  In addition, are you including the construction and resizing of the boolean builder as part of your benchmark?  This will be a part of the compute function execution (it needs to allocate a result array).

There's a good chance the compiler is able to optimize that comparison function pretty effectively.  It may be able to do a better job than the compute function since the size oft he arrays is known ahead of time.

Are you able to share your benchmark code?

**Comment by zfoobar** [comment]
he indeed made a good point. Here is my test code, eager to hear your thoughts:
https://gist.github.com/zfoobar/f61c25271f20d54ea72b065b8e3c6a4c

Here are some sample runs with order of magnitude increases in input size. You can see where the performance superiority of Arrow kicks in (marked in green below)

(pyarrow-dev) Zacharys-MacBook-Air:arrow_scratch zacharyfierstadt$ ./my_example 10000
Generating 10000 random values..
Array explicitly compared
Time: 0.216 ms
Arrays compared using a compute function
Time: 9.757 ms
Table created
Writing CSV file

(pyarrow-dev) Zacharys-MacBook-Air:arrow_scratch zacharyfierstadt$ ./my_example 100000
Generating 100000 random values..
Array explicitly compared
Time: 1.148 ms
Arrays compared using a compute function
Time: 13.329 ms
Table created
Writing CSV file

(pyarrow-dev) Zacharys-MacBook-Air:arrow_scratch zacharyfierstadt$ ./my_example 1000000
Generating 1000000 random values..
Array explicitly compared
Time: 12.184 ms
Arrays compared using a compute function
**Time: 9.332 ms**
Table created
Writing CSV file

(pyarrow-dev) Zacharys-MacBook-Air:arrow_scratch zacharyfierstadt$ ./my_example 10000000
Generating 10000000 random values..
Array explicitly compared
Time: 87.849 ms
Arrays compared using a compute function
**Time: 39.409 ms**
Table created
Writing CSV file
