### ISSUE TITLE
[CI][Java] Upload Java Nightly builds not working

### ISSUE THREAD

**Issue by aiguofer** [apache/arrow#34867]
### Describe the bug, including details regarding any error messages, version, and platform.

It looks like the last working snapshot was back in Feb 16: https://github.com/apache/arrow/actions/runs/4194721593/jobs/7273263353

Here's the latest run with the error: https://github.com/apache/arrow/actions/runs/4597587219

It looks like a bug with `checkout@v3` action while checking out `crossbow`. It seems like changing `fetch-depth` to `1` might fix it, but I don't quite understand why it's currently set to `0`.

### Component(s)

Continuous Integration

**Comment by kou** [comment]
Ah, we should have not changed the branch name of `ursacomputing/crossbow` to `main` from `master`: https://github.com/apache/arrow/pull/34218/files#diff-dd8c7b27f53652e57dbe01d7e9d18a386d2bf3d9fa54750ec5d716e367ad1019L59-R59

Could you open a pull request to revert the change?

**Comment by assignUser** [comment]
@kou we could also rename crossbow master to main ^^

**Comment by kou** [comment]
It's an option. :-)
Can we do it immediately?

**Comment by assignUser** [comment]
I can do it, I think we already have renamed everything/adjusted archery so it get's the default branch. It looks like the r nightly yml has the master ref hardcoded and should be updated but as github creates forwarding it should be fine. Agreed @kou?

**Comment by kou** [comment]
Agree!

**Comment by assignUser** [comment]
done https://github.com/ursacomputing/crossbow

**Comment by kou** [comment]
Thanks!
Let's see the next job result.

**Comment by aiguofer** [comment]
Thanks ya'll for looking into this! Looks like there's some progress... got past the error with crossbow but now getting another error: `KeyError: 'Branch not found: origin/nightly-packaging-2023-04-04-0'` in `Download Artifacts`

**Comment by kou** [comment]
Ah, we need to fix the `java-jars` job for this job...
At least we need to fix #34862.

Anyway, I think that we can close this. We should track the `java-jars` job failure.

**Comment by assignUser** [comment]
> Anyway, I think that we can close this. We should track the java-jars job failure.

Agreed.

**Comment by aiguofer** [comment]
Interesting, the latest run seems to have been successful (https://github.com/apache/arrow/actions/runs/4629714005), but I still don't see the latest jars in https://nightlies.apache.org/arrow/java/org/apache/arrow/. Any guesses why that might be?

**Comment by kou** [comment]
The upload job is passed but the download step is still failed: https://github.com/apache/arrow/actions/runs/4629714005/jobs/8190329629#step:7:25
Because the last `java-jars` job failed: https://lists.apache.org/thread/y1h2xxp4yn8w6mz82gmyn45tggydo477

The `java-jars` job will be succeeded because #34866 was merged.

**Comment by aiguofer** [comment]
Ahh interesting, so the nightly upload depends on jobs on 2 separate repos. Seems like a pretty complex build system but it totally makes sense with how many platforms and language packages need to be built!

Unfortunately even with that latest merged PR it's still failing on [Build C++ libraries macOS x86_64](https://github.com/ursacomputing/crossbow/actions/runs/4649637808/jobs/8228116680#logs)

Thanks for looking into this!

**Comment by kou** [comment]
Oh.

Could you open a new issue for this?

We can find an error message via raw error log (we can't find it on the linked page because log is too large):

```text
2023-04-09T08:58:43.6973290Z + archery linking check-dependencies --allow CoreFoundation --allow Security --allow libSystem --allow libarrow_cdata_jni --allow libarrow_dataset_jni --allow libarrow_orc_jni --allow libc++ --allow libcurl --allow libgandiva_jni --allow libncurses --allow libobjc --allow libz libarrow_cdata_jni.dylib libarrow_dataset_jni.dylib libarrow_orc_jni.dylib libgandiva_jni.dylib
2023-04-09T08:58:47.8367910Z Error: Unexpected shared dependency found in libgandiva_jni.dylib: `libzstd`
```

**Comment by aiguofer** [comment]
Yeah will do! thanks for finding the error.
