### ISSUE TITLE
[Python][CI] Nightly integration tests with latest dask are failing (test_null_partition_pyarrow)

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#34879]
See eg https://github.com/ursacomputing/crossbow/actions/runs/4580261850/jobs/8088832221

This tests was introduced in https://github.com/dask/dask/pull/10007 which was already released in dask 2023.3.2. It was also already fixed on the dask side in https://github.com/dask/dask/pull/10116/. But that change isn't yet released, so our "latest" build is failing while the "upstream_devel" is already green again. 

We could fix it by skipping the tests temporarily, or we could also just wait a few days until their next release.

**Comment by jorisvandenbossche** [comment]
(marking as 12.0.0 to ensure we verify our builds are indeed green again before the release)

**Comment by assignUser** [comment]
(adding blocker so we don't miss to check this :) )

**Comment by raulcd** [comment]
Dask 2023.4.0 was released on April 14th (https://pypi.org/project/dask/#history). Since then the latest nightly tests have been successful. I am closing the issue.
