### ISSUE TITLE
[C++] mean overflows if numeric sum is larger than int64 max

### ISSUE THREAD

**Issue by rohanjain101** [apache/arrow#34909]
### Describe the bug, including details regarding any error messages, version, and platform.

```
>>> arr = pa.array([-1303487490025821099, -8371390547526583103, -2572374159461887095], type=pa.int64())
>>> pa.compute.mean(arr)
<pyarrow.DoubleScalar: 2.0664972922317535e+18>
>>>
```

When using numpy:

```
>>> arr.to_numpy().mean()
-4.0824173990047636e+18
>>>
```

Seems like overflow case is not handled correctly when using arrow array.

### Component(s)

Python

**Comment by rohanjain101** [comment]
It seems like mean is calculated by taking sum divided by count, instead of doing it iteratively, which will not handle overflow case correctly.

**Comment by assignUser** [comment]
This is actually an issue with the underlying C++ compute function.

Here is a clear reprex:

```python
 import numpy as np; import pyarrow as pa
 pa.compute.mean(pa.array([np.iinfo(np.int64).max, 1]))
 <pyarrow.DoubleScalar: -4.611686018427388e+18>
```

**Comment by jorisvandenbossche** [comment]
Numpy will always perform the actual operation on floats, so if calculating the mean of integers, those are cast to float64 at the start. In addition, they also cast float16 to float32 for the intermediates, for the other float inputs, they keep the precision.

In addition to doing this with floats, to improve the precision of the operation, pandas also recently switched to use Kahan summation (https://en.wikipedia.org/wiki/Kahan_summation_algorithm). I think numpy uses pairwise summation instead (https://en.wikipedia.org/wiki/Pairwise_summation)
