### ISSUE TITLE
[Docs][R] Version selector reports that release version is dev

### ISSUE THREAD

**Issue by nealrichardson** [apache/arrow#34907]
### Describe the bug, including details regarding any error messages, version, and platform.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/2975928/230168254-b12643f3-d790-430c-8e5b-7930ce501a8c.png">

It shows as dev when you're on the release version (per the URL). When you select release version, it goes to the release version URL but updates to the dev element in the selector. You can't select the dev version from here--the only way to use the selector to get to the dev version is to select an old number version (which does work correctly), and then you can select "dev", which takes you to the dev URL.

cc @thisisnic 

### Component(s)

Documentation, R

**Comment by thisisnic** [comment]
Thanks for reporting this, I think it's part of another issue we've had trying to update arrow-site, which I hadn't realised hadn't been sorted, will take a look.
