### ISSUE TITLE
[R] `write_dataset` puts addtional things around dir name when write big tibble

### ISSUE THREAD

**Issue by qifei9** [apache/arrow#34910]
### Describe the bug, including details regarding any error messages, version, and platform.

I have a big tibble of >500,000,000 rows. I want to use `write_dataset` to write it out with partationing by the column "species" containing values of "mouse" and "zebrafish".

However, it forms wrong dir names of
```
[\n "mouse"\n]
[\n "zebrafish"\n]
```
instead of correct form of
```
mouse
zebrafish
```

If I randomly sample a small fraction of the tibble, like 30000 rows, `write_dataset` could form the correct dir names.

### Component(s)

R

**Comment by westonpace** [comment]
I'm not sure I follow.  Are the `[`, `\n`, and `"` characters part of the directory filename?

**Comment by qifei9** [comment]
> I'm not sure I follow. Are the `[`, `\n`, and `"` characters part of the newly created directory filenames?

Yes, they are. 

If I read the dataset back into R, and `collect()`, the values of the column "species" used for partationing changed from original `mouse` to wrong form `[\n "mouse"\n]`.

I tried to change the parameter `hive_style = TRUE`, but it did not help.

I tried to partationing with more than 1 level, and change the order of the levels, in some rare cases, the problem did not occur, but I have not get a clue of why.

**Comment by thisisnic** [comment]
Thanks for reporting this @qifei9.  Can you tell me a bit more about your data source, and where it's from?

And would you mind double-checking there haven't been any input errors by running something like:

```
library(arrow)
library(dplyr)

my_tibble %>%
  distinct(grouping_col) %>%
  collect()
```

substituting `my_tibble` and `grouping_col` for the relevant values in your dataset.

**Comment by qifei9** [comment]
> Thanks for reporting this @qifei9. Can you tell me a bit more about your data source, and where it's from?
> 
> And would you mind double-checking there haven't been any input errors by running something like:
> 
> ```
> library(arrow)
> library(dplyr)
> 
> my_tibble %>%
>   distinct(grouping_col) %>%
>   collect()
> ```
> 
> substituting `my_tibble` and `grouping_col` for the relevant values in your dataset.

many thanks. I am quite busy now. Will try this once I get time.

**Comment by thisisnic** [comment]
I'm closing this as there's been no interaction on this in ~ 6 months
