### ISSUE TITLE
[C++] Require CMake 3.16 or later

### ISSUE THREAD

**Issue by kou** [apache/arrow#34921]
### Describe the enhancement requested

We need to support Ubuntu 20.04 (CMake 3.16) or later, CentOS 7 (CMake 3.17) or later, and Debian GNU/Linux buster (CMake 3.13 but backports repository has CMake 3.18) or later.

So we can require CMake 3.16 or later.

### Component(s)

C++

**Comment by westonpace** [comment]
I agree.  Is there a change needed here or can this be closed now that https://github.com/apache/arrow/pull/34969 has merged?

**Comment by kou** [comment]
We can't close this yet because #34969 is just for an example project.

This issue is for `cpp/CMakeLists.txt` not an example project.

**Comment by kou** [comment]
Debian GNU/Linux buster reached EOL on 2022-09-10:

https://wiki.debian.org/DebianReleases

> Version | Code name | Release date | End of life date | EOL LTS | EOL ELTS
> -- | -- | -- | -- | -- | --
> 10 | Buster | 2019-07-06 | 2022-09-10 | 2024-06-30

**Comment by kou** [comment]
Oh... Amazon Linux 2 uses CMake 3.13.1...
