### ISSUE TITLE
[Python] Building pyarrow does not work with all Cython 0.29.* versions

### ISSUE THREAD

**Issue by joosthooz** [apache/arrow#34933]
### Describe the bug, including details regarding any error messages, version, and platform.

Building pyarrow results in errors when I use Cython 0.29.24, but succeeds when using the latest 0.29.34.
In `requirements-build.txt` the version is `cython>=0.29` so maybe that should be updated to a later version?

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Yes, we can probably be more exact in the minimum version requirement for cython in our build requirements (for example, I know pandas regularly updates that and has "Cython>=0.29.33" in their pyproject.toml build-system.requires.

We also have a check in setup.py to enforce a minimum version, which we should update as well (and keep in sync):

https://github.com/apache/arrow/blob/84e54308f1399df094b785083e6faf52275d10e9/python/setup.py#L43-L44

**Comment by jorisvandenbossche** [comment]
Testing a few versions, 0.29.31 seems to be the first one that doesn't have the above mentioned cythonization error. So we can maybe use that one as minimum version
