### ISSUE TITLE
[C++] Standardize aggregation column order

### ISSUE THREAD

**Issue by rtpsw** [apache/arrow#34930]
### Describe the enhancement requested

Change aggregation column order to segment-keys then keys then aggregates.

### Component(s)

C++

**Comment by rtpsw** [comment]
cc @westonpace @icexelloss

**Comment by icexelloss** [comment]
This is a dup of https://github.com/apache/arrow/issues/34908

I am in favor of using #34908 because it has a bit more explanation in it.

**Comment by westonpace** [comment]
Duplicate of #34908
