### ISSUE TITLE
[Go] tensor doesn't support access to Null bitmap data?

### ISSUE THREAD

**Issue by rcoreilly** [apache/arrow#3496]
It seems that the tensor interface does not provide access to the Null bitmap data in the underlying array.  The root cause appears to be that Data does not have the null bitmap data and associated IsNull / IsValid methods, and tensor only retains the Data and not the Array -- only the array has the actual null bitmap and associated methods.  So either keeping the array.Interface around or moving the null bitmap into Data would seem to be the necessary steps.

**Comment by wesm** [comment]
Can you please open a JIRA issue?
