### ISSUE TITLE
[CI][Packaging] wheel-clean referes nonexistent ./ci/scripts/gemfury_clean.rb

### ISSUE THREAD

**Issue by kou** [apache/arrow#34973]
### Describe the bug, including details regarding any error messages, version, and platform.

> It seems that we need to use `arrow/ci/scripts/gemfury_clean.rb`: https://github.com/ursacomputing/crossbow/actions/runs/4587784310/jobs/8101540480
>
> ```text
> ruby: No such file or directory -- ./ci/scripts/gemfury_clean.rb (LoadError)
> ```

_Originally posted by @kou in https://github.com/apache/arrow/pull/34705#discussion_r1155338349_

### Component(s)

Continuous Integration, Packaging

**Comment by raulcd** [comment]
Thanks @kou !
