### ISSUE TITLE
Allow building with GCC (i.e., without a requirement for LLVM)

### ISSUE THREAD

**Issue by barracuda156** [apache/arrow#34999]
### Describe the enhancement requested

Currently `arrow` requires LLVM. It is desirable to allow building with GCC too.

### Component(s)

C++

**Comment by wjones127** [comment]
Which parts are you trying to build? The only component that should require LLVM is Gandiva.

**Comment by barracuda156** [comment]
@wjones127 In actually works, thank you. I made a wrong conclusion from a) Macports requiring that and b) a few vague statements in Apache documentation.

What I could not figure out is how to force it to use external `jemalloc` – bundled one is broken for PPC. Had to disable it for now. But `arrow` itself indeed builds without LLVM.

**Comment by kou** [comment]
FYI: `-Djemalloc_SOURCE=SYSTEM` may help you.
