### ISSUE TITLE
How to use external jemalloc?

### ISSUE THREAD

**Issue by barracuda156** [apache/arrow#35020]
### Describe the usage question you have. Please include as many useful details as  possible.

Configure ignores passed arguments (setting it to use shared or explicitly passing jemalloc root) and tries to build the bundled `jemalloc`. Bundled one is broken either for PPC specifically or for builds with GCC.

How to make it work? Everything else works fine: it finds external rapidjson, zstd etc. Only jemalloc does not.

Build env: MacOS, MacPorts, gcc12, latest CMake.

### Component(s)

C++

**Comment by kou** [comment]
Could you try `-Djemalloc_SOURCE=SYSTEM`?

**Comment by barracuda156** [comment]
> Could you try `-Djemalloc_SOURCE=SYSTEM`?

@kou I will check that and let you know. Thank you.

**Comment by barracuda156** [comment]
@kou Awesome, that works.

**Comment by kou** [comment]
That's good to know. :-)
