### ISSUE TITLE
[R] Implement `names<-` for Schemas

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#35035]
### Describe the enhancement requested

We occasionally have requests relating to updating schemas and we could make them easier to work with.  We could implement the S3 method `names<-` for Schema object, to enable users to be able to do something like:

```
my_schema <- schema(x = int8(), y = string())
names(my_schema) <- c("y", "x")
```
The specific use-case I'm thinking about here is when a user wants to read a schema from a source, update it, and then re-use it to read/write.

### Component(s)

R

**Comment by nealrichardson** [comment]
There is a `Schema->WithNames()` method you could add bindings for: https://github.com/apache/arrow/blob/main/cpp/src/arrow/type.h#L2003

Note that the C++ function doesn't seem to preserve schema metadata: https://github.com/apache/arrow/blob/main/cpp/src/arrow/type.cc#L1741-L1754

So you will either need to modify the function there to forward the metadata, or handle it yourself. (And for `metadata$r`, you may want to update column names referenced in that to point to the new names, so it may just be something to handle on the R side anyway.)
