### ISSUE TITLE
[Python][CI] Tests on windows are running very slow

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#35078]
Appveyor is currently timing out (eg https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/46764558), and also the nightly crossbow wheel tests show very slow tests (eg [wheel-windows-cp310-amd64 latest logs](https://github.com/ursacomputing/crossbow/actions/runs/4676300747/jobs/8282436089)). 

Going back a bit in time, the same crossbow build from April 1 was fast: [logs](https://github.com/ursacomputing/crossbow/actions/runs/4582243569/jobs/8092338363) (tests take about 5 minutes)

**Comment by jorisvandenbossche** [comment]
The first slow crossbow build seems to be 3 days ago: https://github.com/ursacomputing/crossbow/actions/runs/4649634532/jobs/8228109815

**Comment by mapleFU** [comment]
"raw logs" url seems expired, or just I didn't have authority to visit it?

**Comment by westonpace** [comment]
Is it a timeout?  It's pretty consistent on `test_conversion`.  I assumed it was a segfault.

**Comment by westonpace** [comment]
> "raw logs" url seems expired, or just I didn't have authority to visit it?

@mapleFU 

Here's a more recent slow build: https://github.com/ursacomputing/crossbow/actions/runs/4676300747/jobs/8282436089

I usually go to Zulip to find nightly test status: https://ursalabs.zulipchat.com/#narrow/stream/181017-nightlies/topic/report/near/348751506

**Comment by jorisvandenbossche** [comment]
Comparing the last fast and first slow crossbow build, the only external change in the python test environment was an update of pytest from 7.2.2 to 7.3.0, and that might actually be the culprit: https://github.com/pytest-dev/pytest/issues/10896

**Comment by jorisvandenbossche** [comment]
Sorry, wasn't aware that the raw logs urls expire so quickly. Updated the top post with linking to the normal github actions pages, where you can manually click on "View raw logs"

**Comment by raulcd** [comment]
The new Pytest release fixes the issue. Appveyor is now passing and the wheel tests for Windows are back to ~10 minutes instead of 2hours :). I am closing the issue.
