### ISSUE TITLE
[Python] avoid using pandas internals

### ISSUE THREAD

**Issue by jbrockmendel** [apache/arrow#35081]
- [x] #38341
- [x] #38342

--- 

### Describe the bug, including details regarding any error messages, version, and platform.

ATM pyarrow passes a BlockManager to the pd.DataFrame constructor, but in doing so accesses pandas functions/classes that are not public and that some pandas maintainers (me) would like to ween arrow off of (xref https://github.com/pandas-dev/pandas/pull/52419).

@jorisvandenbossche tells me the current usage is performance motivated, particularly (but not exclusively?) the performance hit associated with pandas silently consolidating, which it no longer does in 2.0.

Let's see if we can find an alternative using pandas' public API.  Starting bid: is pd.DataFrame.from_arrays a viable alternative?

### Component(s)

Python

**Comment by graingert** [comment]
pandas raises a DeprecationWarning: Passing a BlockManager to DataFrame is deprecated and will raise in a future version. Use public APIs instead for this use now:

```python
import pyarrow.dataset
import fsspec

paths = [
    "https://github.com/Parquet/parquet-compatibility/raw/master/parquet-testdata/impala/1.1.1-NONE/nation.impala.parquet"
]
(
    pyarrow.dataset.dataset(paths, filesystem=fsspec.filesystem("http"))
    .schema.empty_table()
    .to_pandas()
)
```

**Comment by jorisvandenbossche** [comment]
@graingert yes, although you shouldn't see that as an end user, fixing that on the pandas side (-> https://github.com/pandas-dev/pandas/pull/52419#issuecomment-1770215326)

You will see the warning when enabling all warnings to show or error (like when running tests), so we have to switch to a different API in pyarrow.

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 40897
https://github.com/apache/arrow/pull/40897
