### ISSUE TITLE
[CI][Packaging] Pin vcpkg to release that includes OpenSSL linux-headers fix

### ISSUE THREAD

**Issue by sjperkins** [apache/arrow#35099]
### Describe the enhancement requested

Newer versions of vcpkg are required when building manylinux_2_28 arm64 platforms due to the following build issue with OpenSSL

- https://github.com/microsoft/vcpkg/issues/29674

since fixed in:

- https://github.com/microsoft/vcpkg/pull/29966

#34818 pins vcpkg to an untagged commit:  see https://github.com/apache/arrow/pull/34818#discussion_r1164203060, but it would be better to pin vcpkg to an official release tag.

### Component(s)

Continuous Integration, Packaging, Release

**Comment by kou** [comment]
@sjperkins It seems that a new version was released: https://github.com/microsoft/vcpkg/releases/tag/2023.04.15
Could you work on this?

**Comment by sjperkins** [comment]
> @sjperkins It seems that a new version was released: https://github.com/microsoft/vcpkg/releases/tag/2023.04.15 Could you work on this?

Opened #35430
