### ISSUE TITLE
[Go] parquet: what is the correct way write repeated fields? 

### ISSUE THREAD

**Issue by jayshrivastava** [apache/arrow#35119]
### Describe the usage question you have. Please include as many useful details as  possible.
👋🏽 I have the following schema (version 11.0.0)
```
Schema:
message schema {
  optional group a (LIST) {
    repeated boolean a-datum;
  }
  optional group b (LIST) {
    repeated boolean b-datum;
  }
}
```

I've been struggling to write data to a file. 

This code below should write two rows to the parquet file: [true,true] and [false, false]
```
colwriterA.WriteBatch([]bool{true, false}, []int16{3, 3}, []int16{0, 1})
colwriterB.WriteBatch([]bool{true, false}, []int16{3, 3}, []int16{0, 1})
```
From my understanding, a def level of < 2 means the list is an empty list. A def level of 2 indicates a null value in the list. A def level of 3 should represent a non-null value. 

For the rep levels, 0 should indicate the first element in the list and 1 should indicate another value in the list.

I'm getting this information from this comment: https://github.com/apache/arrow/blob/2ba66285c6c78b43acdccf114fcb61aad090fb93/go/parquet/file/level_conversion.go#L33-L73 The value of `LevelInfo` for these column writers is `{0 2 1 2}`.

When I try to read the file, I get this:
```
{"a": null, "b": null}
```

What am I doing wrong?

### Component(s)

Go, Parquet

**Comment by zeroshade** [comment]
The misunderstanding is coming from the fact that you're using an old way to specify a list schema. 

The schema you provided is:
```
Schema:
required group schema {
  optional group a (LIST) {
    repeated boolean a-datum;
  }
  optional group b (LIST) {
    repeated boolean b-datum;
  }
}
```

Note the usage of a 2-level format for describing the lists. From the Parquet Format spec, usage of this backwards-compatible format means that the elements are non-nullable:

```
// List<Integer> (nullable list, non-null elements)
optional group my_list (LIST) {
  repeated int32 element;
}
```

This means that the max definition level (describing whether data exists) is `2` not `3` like you assumed. If you try writing the values with a definition level of `2`, you should get the data you expect.

The *correct* way to specify a list would be as this:

```
repeated group field_id=-1 schema {
  optional group field_id=-1 a (List) {
    repeated group field_id=-1 list {
      optional boolean field_id=-1 element;
    }
  }
  optional group field_id=-1 b (List) {
    repeated group field_id=-1 list {
      optional boolean field_id=-1 element;
    }
  }
}
```

Note the 3-level format here. This enables specifying that the elements can be null and will result in a maximum definition level of `3` like you were expecting, where a `2` would indicate a null in the list.

Hope this helps!

**Comment by jayshrivastava** [comment]
That was very helpful. Thanks! 

Btw, I'm having some trouble inspecting the file with [parquet-mr on v1.13](https://formulae.brew.sh/formula/parquet-cli), but It looks like that's an issue with parquet-mr. I can inspect the file just fine on https://parquetreader.com/home or https://www.parquet-viewer.com/. This issue can be closed though.
[TestBasicDatums.zip](https://github.com/apache/arrow/files/11240782/TestBasicDatums.zip)
