### ISSUE TITLE
[C++] Need a nightly test that compiles AVX2

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#35116]
### Describe the enhancement requested

I use AVX2 locally and ran into a few regressions.  It seems we do not have a CI job that is testing AVX2.

### Component(s)

Continuous Integration

**Comment by assignUser** [comment]
Apparently gha runners use these [azure machine](https://learn.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series). All listed CPUs support at least AVX2 (not 512 though which has caused issues before...) so this should be no issue.
