### ISSUE TITLE
Is Parquet metadata readable using Java?

### ISSUE THREAD

**Issue by JerAguilon** [apache/arrow#35127]
### Describe the usage question you have. Please include as many useful details as  possible.

Parquet supports writing stats in the form of [metadata](https://parquet.apache.org/docs/file-format/metadata/).

I've read metadata in python/C++ arrow ([example](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_metadata.html)), but I was curious if there's  away to accomplish this using Java? Thanks.

### Component(s)

Java

**Comment by lidavidm** [comment]
In Java, the reference implementation of Apache Parquet is [parquet-mr](https://github.com/apache/parquet-mr/). Does this work for your needs? It cannot read Parquet data into Apache Arrow format but should more than suffice for reading metadata. (You can use the Arrow JNI libraries to read Parquet data into Arrow format.)
