### ISSUE TITLE
[Go] Fails to build on 32-bit platforms

### ISSUE THREAD

**Issue by srebhan** [apache/arrow#35133]
### Describe the bug, including details regarding any error messages, version, and platform.

The current code fails to build on 32-bit platforms (at least on armel, armhf, mips, mipsel, linux-386 and windows-386) with the following error

```text
github.com/apache/arrow/go/v12/arrow/array
/go/pkg/mod/github.com/apache/arrow/go/v12@v12.0.0-20230414125938-59fe4ce90e2f/arrow/array/dictionary.go:1564:22: math.MaxUint32 (untyped int constant 4294967295) overflows int
```

### Component(s)

Go

**Comment by raulcd** [comment]
@zeroshade should this bug fix be added to 12.0.0?
