### ISSUE TITLE
[CI][C++] Minimal examples fail to compile due to missing configuration for `arrow_bundled_dependencies` 

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#35179]
### Describe the bug, including details regarding any error messages, version, and platform.

The following jobs have been failing:
[example-cpp-minimal-build-static](https://github.com/ursacomputing/crossbow/actions/runs/4716182026/jobs/8363676360)
[example-cpp-minimal-build-static-system-dependency](https://github.com/ursacomputing/crossbow/actions/runs/4716184879/jobs/8363681455)
since https://github.com/apache/arrow/commit/b63463c62881d098e9e262e52ca2bd29a416e55d was merged.

I have reproduced locally with:
```
$ cd arrow/cpp/examples/minimal_build
$ docker-compose run --rm static
```
I've checked the docker container and the built CMake seems to suggest arrow_bundled_dependencies is not found correctly:

```
root@70c12a6c178d:/build/example# vim CMakeFiles/arrow-example.dir/build.make 
...
# External object files for target arrow-example
arrow__example_EXTERNAL_OBJECTS =

arrow-example: CMakeFiles/arrow-example.dir/example.cc.o
arrow-example: CMakeFiles/arrow-example.dir/build.make
arrow-example: /usr/local/lib/libarrow.a
arrow-example: Arrow::arrow_bundled_dependencies-NOTFOUND
arrow-example: CMakeFiles/arrow-example.dir/link.txt

```

### Component(s)

C++, Continuous Integration

**Comment by raulcd** [comment]
I've validated that reverting the change for `ArrowConfig.cmake.in` fix the issue.

**Comment by assignUser** [comment]
The problem is that the changes from #35109  expect `LOCATION_<CONFIGURATION>` to be set, which is not the case by default. This leads to empty vars and wrong locations.

This issue should have been found pre-merge by running crossbow jobs.
cc @kou

```
-- Arrow version: 12.0.0
-- Found the Arrow shared library: 
-- Found the Arrow import library: 
-- Found the Arrow static library: /usr/local/lib/libarrow.a
CMake Error at CMakeLists.txt:28 (message):
  LOCATION_RELEASE: lib dir: /usr/local/lib
```

**Comment by kou** [comment]
Oh, sorry...

**Comment by assignUser** [comment]
Seems to happen frequently as there is a warning specifically for this since 3.19 :D 
https://cmake.org/cmake/help/latest/policy/CMP0111.html
