### ISSUE TITLE
not able to install pyarrow using source 

### ISSUE THREAD

**Issue by Ganeshkumhar1** [apache/arrow#35195]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi I am trying to install pyarrow using pyarrow-11.0.0.tar.gz  file.
- untarred pyarrow-11.0.0.tar.gz  
- cd pyarrow-11.0.0
- i see setup.py file here then i run "python setup.py bdist_wheel" to build and create whl file.
- I am hitting below error while doing this 
```
CMake Error at CMakeLists.txt:268 (find_package):
  By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Arrow", but
  CMake did not find one.

  Could not find a package configuration file provided by "Arrow" with any of
  the following names:

    ArrowConfig.cmake
    arrow-config.cmake

  Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
  "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
  provides a separate development package or SDK, be sure it has been
  installed.
```

I checked whole dir and could not find FindArrow.cmake anywhere . can some one please help addressing this issue., Thanks 

### Component(s)

C++

**Comment by assignUser** [comment]
Hello, thanks for your report. PyArrow depends on the Arrow C++ library which needs to be installed on the system (and has to match the pyarrow version you want to build). Unless you want to work on pyarrow I would recommend using the precompiled wheels if available for your system.

The process of installing from source is described in detail here: https://arrow.apache.org/docs/developers/python.html#building-on-linux-and-macos

**Comment by Ganeshkumhar1** [comment]
Thanks for the reply. could you please suggest steps to build  Arrow C++ library on system and how to use them while building pyarrow.

**Comment by raulcd** [comment]
Hi @Ganeshkumhar1 ! In the page that @assignUser linked you can see how to install using conda and system / bundled dependencies:
https://arrow.apache.org/docs/developers/python.html#environment-setup-and-build
https://arrow.apache.org/docs/developers/python.html#using-system-and-bundled-dependencies
Is there any reason why you want to build Arrow C++ and pyarrow 11.0.0 yourself?
Arrow is built on several package managers and can be installed from those distributed ones: https://arrow.apache.org/install/
You can also install the precompiled wheels from PyPI.

**Comment by Ganeshkumhar1** [comment]
there is some security concern in using precompiled whl file, hence I was trying to build manually.
Anyways I was able to build it using above steps. 
thanks a ton @raulcd @assignUser !!!!
