### ISSUE TITLE
[Python] Windows wheel is built without GCS support

### ISSUE THREAD

**Issue by yan-hic** [apache/arrow#35193]
### Describe the bug, including details regarding any error messages, version, and platform.

Error using latest 11.0 on Windows. 
I suspect `pyarrow-11.0.0-cp311-cp311-win_amd64.whl` has no GCS support, and maybe others.

### Component(s)

Python

**Comment by raulcd** [comment]
When we originally added GCS support it was not enabled for Windows wheels. This is the original PR: https://github.com/apache/arrow/pull/12763
We don't enable `ARROW_GCS` when building Windows wheels as seen here: https://github.com/apache/arrow/blob/main/ci/scripts/python_wheel_windows_build.bat#L32-L50
See Unix wheel for reference: https://github.com/apache/arrow/blob/main/ci/scripts/python_wheel_unix_test.sh#L34

I have tried to find if there's an issue opened for it but I can't find anything. I am unsure if there's a reason for it as I am no expert on GCS but at the moment we don't build `ARROW_GCS` on Windows wheels.

**Comment by yan-hic** [comment]
Alright - we are using linux in prod containers and can use WSL for Py interpreter, however, it would be good to post a disclaimer in the doc about what's not included in the Windows wheels. Feel free to close.

**Comment by westonpace** [comment]
I'm not sure the rationale either but I don't think we should close this.  Let's leave it open to add support for GCS on Windows wheels.  We do build GCS for our windows C++ CI tests (appveyor) so I'm not sure why it was excluded from wheels.  It's possible it was just an oversight.
