### ISSUE TITLE
[Go] Add more frames to Checked Allocator memory leak output

### ISSUE THREAD

**Issue by hermanschaaf** [apache/arrow#35212]
### Describe the enhancement requested

The `CheckedAllocator` output right now provides a single line of context, roughly indicating which type was involved. This is fine for testing within Arrow itself, but in large applications this is often not enough to narrow down where a memory leak is coming from. It would be very helpful if the full call stack could be provided in the output.

It is technically possible to repeatedly run with different values of `ARROW_CHECKED_ALLOC_FRAMES` and `ARROW_CHECKED_REALLOC_FRAMES` but this is quite tedious.

### Component(s)

Go

**Comment by hermanschaaf** [comment]
I have an implementation of this (and it's been very useful) but not sure how we'd want the details to look. I might open a draft PR for feedback soon

**Comment by zeroshade** [comment]
Sounds good @hermanschaaf I'd be happy to look at it when you submit the draft PR. If it doesn't automatically add me to it just tag me on it.
