### ISSUE TITLE
ARROW-4418: [Plasma] Replace event loop with boost::asio for plasma store

### ISSUE THREAD

**Issue by zhijunfu** [apache/arrow#3523]
It would be nice to move plasma store from current event loop to boost::asio to modernize the code, and more importantly to benefit from the functionalities provided by asio, which I think also provides opportunities for performance improvement.

What would you think? @pcmoritz @robertnishihara

**Comment by xhochy** [comment]
@zhijunfu As there is already a JIRA issue for this, please discuss there.

**Comment by zhijunfu** [comment]
@xhochy thanks. Could you kind share the related issue number? 
I vaguely remembered there was a related one but I didn't find it in JIRA.

**Comment by pitrou** [comment]
Direct link to JIRA: https://issues.apache.org/jira/browse/ARROW-4418

**Comment by zhijunfu** [comment]
Ok I got your point, I thought it was someone else created another JIRA issue earlier.
