### ISSUE TITLE
[C++][Parquet] params about FileReaderImpl::ReadRowGroups

### ISSUE THREAD

**Issue by CaoZB** [apache/arrow#35236]
### Describe the usage question you have. Please include as many useful details as  possible.

Interface `::arrow::Status ReadRowGroups` in file src/parquet/arrow/reader.h(https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/reader.cc#L1219) has an input param named `const std::vector<int>& column_indices`, here are my questions:
1.I read the code and thought that column_indices should be leaf's column index, is that right? And If it is right, how can i get leaf's column index? I didn't find any interface about it.
2.(https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/reader.cc#L1254)line 1254 in file src/parquet/arrow/reader.cc,`RETURN_NOT_OK(ReadColumn(static_cast<int>(i), row_groups, reader.get(), &column));`, i think the first param `static_cast<int>(i)` should be index of `std::vector<SchemaField> schema_fields` in struct `SchemaManifest`(https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/schema.h#L115), am i right? If so, i believe current passed value is not as expected.

### Component(s)

C++

**Comment by mapleFU** [comment]
You can also tag the issue with "parquet".

1. Yes. It's Leaf's column index. You can get the column from `SchemaManifest`
2. Not. If there is not nested struct, they should be near. But if we have nested struct, `schema_fields` would be a tree, and column is flatten.

You can talk a look at comment below:

```
  /// To get the index for a particular leaf field, one can use
  /// manifest().schema_fields to get the top level fields, and then walk the
  /// tree to identify the relevant leaf fields and access its column_index.
  /// To get the total number of leaf fields, use FileMetadata.num_columns().
```

**Comment by mapleFU** [comment]
Does this solve your problem @CaoZB ?

**Comment by CaoZB** [comment]
Yes, thank you so much.
