### ISSUE TITLE
[Java][JNI] Build Java JNI ARM binaries for Linux

### ISSUE THREAD

**Issue by henrymai** [apache/arrow#35258]
### Describe the enhancement requested

Currently there are only macOS ARM binaries being built for Java JNI, it would be great to also build these for ARM Linux so that software using Java Arrow Dataset or Gandiva running on AWS Graviton instances will work.

One possible way to approach this is to leverage [docker buildx with qemu](https://docs.docker.com/build/building/multi-platform/) to transparently build ARM binaries, but I'm not familiar enough with Archery to know off the top of my head if that would be too difficult to do.

### Component(s)

Java

**Comment by kou** [comment]
We can use our self-hosted arm64 runner instead of QEMU on amd64.
See also: https://github.com/apache/arrow/pull/34717/files#diff-547c878449dfd53e135c65ea268797610d25c60f3049a0b7bb18ed12bc98a738R28

**Comment by henrymai** [comment]
I think this is resolved by:

https://github.com/apache/arrow/issues/35258

https://github.com/apache/arrow/pull/36487

So I'm closing this out.

Thanks @jonathanswenson
