### ISSUE TITLE
[C++] find_package(Arrow) may be failed without CMAKE_CXX_STANDARD project

### ISSUE THREAD

**Issue by kou** [apache/arrow#35252]
### Describe the bug, including details regarding any error messages, version, and platform.

`FindGTestAlt.cmake` uses `-DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}` to check whether found GoogleTest can be used with Apache Arrow C++.

`find_package(Arrow)` also uses `FindGTestAlt.cmake`. Apache Arrow C++ always sets `CMAKE_CXX_STANDARD`. So `-DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}` has no problem. But a project that uses `find_package(Arrow)` may not set `CMAKE_CXX_STANDARD`. In this case, `try_compile()` is failed with the following message:

```text
The CXX_STANDARD property on target "cmTC_ce38e" contained an invalid
  value: "".
```

* GoogleTest is used by `ArrowTesting` not `Arrow`. So we should put it to `ArrowTesting/`.
* `CMAKE_CXX_STANDARD` check is needed only when Apache Arrow C++ finds GoogleTest. It's not needed when `find_package(Arrow)` because suitable GoogleTest should be found by `find_package(GTestAlot)`. 

### Component(s)

C++

**Comment by kou** [comment]
@raulcd Sorry... One more blocker for 12.0.0...

**Comment by raulcd** [comment]
Thanks @kou 😢
Was there any specific job failure that reproduced the issue?

**Comment by kou** [comment]
@raulcd Merged!
