### ISSUE TITLE
[R] Allow users to adjust AWS S3 log level from R

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#35260]
### Describe the enhancement requested

The AWS SDK has built-in logging and the C++ Arrow S3 implementation provides a way to initialize S3 with a log level other than the default (Fatal). Setting the log level above the default of Fatal is useful for both users and developers who might want to understand what the AWS SDK is doing behind the scenes. My immediate use case is to measure the timing and number of HTTP requests `arrow::write_dataset` triggers for a workload I'm troubleshooting.

The Python bindings expose such an option as:

```python
import pyarrow
from pyarrow import fs

fs.initialize_s3(fs.S3LogLevel.Debug)
```

As far as I can tell, the R bindings don't expose anything similar. Would this be worth a PR? It could look something like:

```r
library(arrow)

arrow:::s3_init("Debug") # Output starts printing to the console
s3_bucket(....) # Prints lots of debug info to console
```

I'm not sure whether my example `s3_init` should be exported or not so I'm also curious for thoughts on that.

### Component(s)

R

**Comment by thisisnic** [comment]
Anything which makes debugging easier for people who are using the package is definitely worth a PR!  

> I'm not sure whether my example s3_init should be exported or not so I'm also curious for thoughts on that.

Sounds reasonable enough to me right now.

**Comment by amoeba** [comment]
Thanks @thisisnic! I'll get a PR in soon and give you a ping.

**Comment by amoeba** [comment]
Hey @thisisnic, I've sent off a PR in https://github.com/apache/arrow/pull/35398. Let me know what you think.

**Comment by amoeba** [comment]
Following from discussion in https://github.com/apache/arrow/issues/35575, I've filed https://github.com/apache/arrow/issues/36115 which would add an environment variable, `ARROW_S3_LOG_LEVEL` which might be an easier route to allow control of the S3 log level than this issue. If such an environment variable existed, I'm not we'd need the change described in this issue, depending on how https://github.com/apache/arrow/issues/36115 goes.

**Comment by thisisnic** [comment]
Thanks @amoeba.  I think that an environment variable is a great idea, and I appreciate you having the patience to continue to engage with this and enduring all of the "this solution doesn't feel quite right, but I don't have a good alternative to suggest to you" feedback that it took to get here!
