### ISSUE TITLE
[CI][GLib][Parquet] GParquetColumnChunkMetadata comparing failed

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#35266]
### Describe the bug, including details regarding any error messages, version, and platform.

```
===============================================================================
Failure: test: #==(TestParquetColumnChunkMetadata):
        @metadata == other_metadata
        |         |  |
        |         |  #<Parquet::ColumnChunkMetadata:0x7fec99845598 ptr=0x600000f6be20>
        |         false
        #<Parquet::ColumnChunkMetadata:0x7fec9984f638 ptr=0x600000eba320>
/Users/runner/work/arrow/arrow/c_glib/test/parquet/test-column-chunk-metadata.rb:50:in `block in <class:TestParquetColumnChunkMetadata>'
     47:   test("#==") do
     48:     reader = Parquet::ArrowFileReader.new(@file.path)
     49:     other_metadata = reader.metadata.get_row_group(0).get_column_chunk(0)
  => 50:     assert do
     51:       @metadata == other_metadata
     52:     end
     53:   end
===============================================================================
.......................O
===============================================================================
Omission: parquet::RowGroupMetaData::Equals() isn't stable. [test: #==(TestParquetRowGroupMetadata)]
/Users/runner/work/arrow/arrow/c_glib/test/parquet/test-row-group-metadata.rb:48:in `block in <class:TestParquetRowGroupMetadata>'
===============================================================================
```

Eg: 
1. https://github.com/apache/arrow/actions/runs/4763103224/jobs/8466124309?pr=35242
2. https://github.com/apache/arrow/actions/runs/4762190574/jobs/8464152443?pr=35262

### Component(s)

Continuous Integration, Parquet, Ruby

**Comment by kou** [comment]
It seems that this is happen since we merge #35229.

**Comment by kou** [comment]
It's not reproduced on my local M1 macOS...

**Comment by mapleFU** [comment]
@kou Thanks for fast fixing this. Sorry for making that failed, however, I'm not familiar with Ruby, I think I just change some comments in the code in https://github.com/apache/arrow/pull/35278 . If you find something wrong, please tell me, or print the difference of these two  metadatas.

**Comment by kou** [comment]
OK. Could you implement `parquet::ColumnChunkMetaData::ToString()`? Then we can dump metadata contents easily.

**Comment by mapleFU** [comment]
Okay, will add one today

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/pull/35281 add one naive implemention
