### ISSUE TITLE
[Go] Add arrow.Table.String()

### ISSUE THREAD

**Issue by kou** [apache/arrow#35296]
### Describe the enhancement requested

If we have it, we can print a `arrow.Table` easily.

FYI: C++ has `arrow::Table::ToString()`:  https://arrow.apache.org/docs/cpp/api/table.html#_CPPv4NK5arrow11RecordBatch8ToStringEv

See also https://github.com/apache/arrow/pull/35178#discussion_r1174584004 for a use case.

### Component(s)

Go

**Comment by vibhatha** [comment]
take
