### ISSUE TITLE
Arrow IPC format: question on length of record batches

### ISSUE THREAD

**Issue by amcnulty-fermat** [apache/arrow#35300]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi Arrow community,

I have a question about RecordBatch messages in the Arrow IPC format (both the streaming and random access/file variants). In a given stream of Arrow IPC messages will the length (which is to say the number of records, not the number of bytes) ever vary?

For example, is it possible in a given stream of Arrow IPC messages to receive a RecordBatch message containing 10 records, and then subsequently in the same stream, receive a RecordBatch message containing 20 records?

Thanks in advance.

### Component(s)

Format

**Comment by westonpace** [comment]
Yes.  I think the most common case is the end of a file.  For example, if a file has 1 million rows and, for whatever reason, the data producer decided to batch in groups of 300k then the last batch would have only 100k items in it.

However, I'm pretty sure producers are allowed to vary this however they feel like.  For example, if some kind of filtering is applied to a read then you might get a stream of different sized batches based on how many rows happened to meet the particular filter.
