### ISSUE TITLE
[Go] FlightSQL TestPreparedStatementNoSchema test is failing

### ISSUE THREAD

**Issue by hermanschaaf** [apache/arrow#35328]
### Describe the bug, including details regarding any error messages, version, and platform.

This test failure is occurring for Go 1.18 on branches with no FlightSQL-related changes:

```
--- FAIL: TestPreparedStatementNoSchema (0.01s)
    driver_test.go:741: 
        	Error Trace:	/arrow/go/arrow/flight/flightsql/driver/driver_test.go:741
        	Error:      	Error "EOF" does not contain "parameter schema: unexpected"
        	Test:       	TestPreparedStatementNoSchema
FAIL
FAIL	github.com/apache/arrow/go/v12/arrow/flight/flightsql/driver	1.125s
```

For example: https://github.com/apache/arrow/actions/runs/4792026546/jobs/8523088061#step:5:816

It seems to happen frequently; I'm not sure if it happens 100% of the time.

### Component(s)

Go

**Comment by zeroshade** [comment]
Yea, I've been trying to pin down the cause of it and have been unsuccessful so far. 

@srebhan can you take a look here as this was introduced with your changes for the driver?

**Comment by srebhan** [comment]
@zeroshade I cannot reproduce the issue with latest master. Tested with go 1.20 and go 1.18 with 100 tests in a row passing without issues.

**Comment by zeroshade** [comment]
We've been having issues reproducing this issue since it first showed up, but every so often I still see it happen in CI: for example here https://github.com/apache/arrow/actions/runs/5937796502/job/16109536613?pr=37304
