### ISSUE TITLE
[Java] JniLoader throws FileNotFoundException on Windows

### ISSUE THREAD

**Issue by lfkpoa** [apache/arrow#35341]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm trying to use arrow-c-data with Java on Windows but I always get a FileNotFoundException.
Debugging the code I found out that JniLoader uses File.separator to concatenate the arch folder with the library name, which on Windows it is a backslack.
But ClassLoader.getResourceAsStream always expects the path to use "/", so it does not find the resource.
If I call ClassLoader.getResourceAsStream with the forward slach it is able to find the resource.
I think this could be fixed by replacing File.separator with "/".

### Component(s)

Java

**Comment by kou** [comment]
Thanks for your report but I think that this is duplicated of #34293.
