### ISSUE TITLE
A question about org.apache.arrow.flight.FlightClient#FlightClient

### ISSUE THREAD

**Issue by lfygh** [apache/arrow#35349]
### Describe the usage question you have. Please include as many useful details as  possible.

1、why this construct function is not public?
```java
FlightClient(BufferAllocator incomingAllocator, ManagedChannel channel,
      List<FlightClientMiddleware.Factory> middleware)
```
2、Can I customize the ManagedChannel ？

### Component(s)

Java

**Comment by lidavidm** [comment]
See FlightGrpcUtils in flight-grpc

**Comment by lfygh** [comment]
> 

thank you
