### ISSUE TITLE
[Docs] reStructuredText link markup is broken

### ISSUE THREAD

**Issue by kou** [apache/arrow#35369]
### Describe the bug, including details regarding any error messages, version, and platform.

https://arrow.apache.org/docs/format/Glossary.html#term-record-batch

> record batch
>
> In the :ref:\`IPC format \<format-ipc\>\`: the primitive unit of data. A record batch consists of an ordered list of [buffers](https://arrow.apache.org/docs/format/Glossary.html#term-buffer) corresponding to a [schema](https://arrow.apache.org/docs/format/Glossary.html#term-schema).

":ref:\`IPC format \<format-ipc\>\`" should be linked to https://arrow.apache.org/docs/dev/format/Columnar.html#format-ipc .

### Component(s)

Documentation

**Comment by Aman2818** [comment]
Hello @kou 
I am a beginner in open source.
can you help me with  how can I proceed to solve this issue ?

**Comment by kou** [comment]
Welcome!
Could you read our general contribution documents carefully as the first step?
https://arrow.apache.org/docs/dev/developers/contributing.html

**Comment by kou** [comment]
In general, most open source projects provide "how to contribute" documentation.
A new contributor reads the documentation as the first step.

**Comment by Divyansh200102** [comment]
take

**Comment by Divyansh200102** [comment]
hi can you please tell me how do i procced with this issue? @kou
