### ISSUE TITLE
[C++] Fix Substrait schema names and for segmented aggregation

### ISSUE THREAD

**Issue by rtpsw** [apache/arrow#35363]
### Describe the bug

Arrow Substrait does not pass `segment_keys`, as it should, when creating the schema. In addition, Arrow Substrait accepts a plan where the number of names does not match the size of the output schema for the plan. Both of these need to be fixed.

### Component(s)

C++

**Comment by rtpsw** [comment]
@westonpace, I mislabeled this as an enhancement but it should be a bug fix and I can't change that myself.

**Comment by icexelloss** [comment]
I fixed the label
