### ISSUE TITLE
How to read an Arrow IPC with multiple record batches in C#

### ISSUE THREAD

**Issue by simonthum** [apache/arrow#35371]
### Describe the usage question you have. Please include as many useful details as  possible.

I have a large-ish file with hundreds of record batches. I can read them one by one successfully.

However, I would like to create a ML.net DataFrame, which I suppose means I shoud join the record batches into a single large one before. I tried this:

````
var rbBuilder = new RecordBatch.Builder(allocator);
            
using (var stream = File.OpenRead("p2_uc.arrow"))
using (var reader = new ArrowFileReader(stream, allocator))
          {
              RecordBatch recordBatch;
              while ((recordBatch = await reader.ReadNextRecordBatchAsync()) != null)
              {
                  rbBuilder.Append(recordBatch);
              }
          }
          
          var df = DataFrame.FromArrowRecordBatch(
              rbBuilder.Build());
````

However, I get an exception as the builder has far too many fields. I suppose RecordBatch.Builder.Append is not intended for that job.

I have not found any example on how to read a arrow IPC file as a DataFrame. Is that supported at all? If yes how?

Edit: I tried joining with DataFrame.Append(otherDf.Rows), but it threw at me and looked very inefficient.

### Component(s)

C#

**Comment by simonthum** [comment]
I went with a reflection based call to ArrowArrayConcatenator per column. It takes about 4 times as long as the record batch loading. I am still looking for an efficient method.

**Comment by westonpace** [comment]
`RecordBatch.Builder.Append(RecordBatch)` doesn't work how I think you are expecting.  Instead of combining the rows from the two batches (making a longer record batch) it combines the columns from the two batches (making a wider record batch).

There is no class that does the concatenating behavior you are describing today though it seems a reasonable enhancement request.

**Comment by simonthum** [comment]
Actually, the concatenation worked well with ArrowArrayConcatenator, but I consider it a workaround. If memory mapped access is to work as (I think is) intended, it should be possible to construct a DataFrame from a collection of RecordBatches. Or am I on the wrong track?

So it might be that MDA.DataFrame needs enhancement, not this library.

**Comment by CurtHagenlocher** [comment]
ArrowArrayConcatenator has now been made public, removing the need to call it via Reflection. The in-memory layout of a record batch collection is different than the in-memory layout of a single record batch, so any changes to make DataFrame work differently would need to happen on the DataFrame side.

**Comment by simonthum** [comment]
Hi, this is good to know but I actually looked for a more effective way to work with many record batches. is there some other ticket for that?
