### ISSUE TITLE
[Python] Casting Timestamp scalar does not preserve UTC Suffix

### ISSUE THREAD

**Issue by wirable23** [apache/arrow#35370]
### Describe the bug, including details regarding any error messages, version, and platform.

```
>>> ts = pd.Timestamp('2000-12-01 00:00:00+0000', tz='UTC')
>>> scal = pa.scalar(ts, type=pa.timestamp("ns", tz="UTC"))
>>> scal.cast(pa.string())
<pyarrow.StringScalar: '2000-12-01 00:00:00.000000000'>
>>>
```

No UTC "Z" suffix is present, but will be present when casting using arrays:

```
>>> dt_arr = pa.array([ts], type=pa.timestamp("ns", tz="UTC"))
>>> dt_arr.cast(pa.string())
<pyarrow.lib.StringArray object at 0x000002268498B340>
[
  "2000-12-01 00:00:00.000000000Z"
]
>>>
```

When using the Timestamp array cast, the UTC "Z" suffix is preserved, when using the scalar, it's not preserved.

### Component(s)

Python

**Comment by danepitkin** [comment]
Good catch! I can reproduce the bug. The scalar code path does not handle timezone info. The pyarrow scalar cast uses a different implementation (`arrow/cpp/src/arrow/util/time.h::ConvertTimestampValue()`) than the pyarrow array cast (`arrow/compute/kernels/scalar_cast_string.cc::TemporalToStringCastFunctor`). Ideally, all functionality should be migrated to the compute kernel implementation. That will be a pretty big change, so the quickest option is to patch the current code path to add support for timezones.

**Comment by danepitkin** [comment]
A somewhat related issue: https://github.com/apache/arrow/issues/35040

**Comment by danepitkin** [comment]
Fixed as part of https://github.com/apache/arrow/pull/35395
