### ISSUE TITLE
[C++] FilesystemFromUriOrPath and FileSystemFromUri should always remove trailing slash

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#35399]
### Describe the enhancement requested

This is a fairly minor change but it is something I encountered trying to simplify the implementation of these methods in #34420.  Currently, these methods may or may not remove the trailing slash from a path.  For example:

```
FileSystemFromUriOrPath("s3://foo/bar/", &out_path);
FileSystemFromUriOrPath("file:///foo/bar/", &out_path);
```

The former returns `foo/bar` and the latter returns `/foo/bar/`.  I think the change leading slash being different between the two is ok.  However, I think there is no reason to remove the trailing slash in one instance and not the other.

No work needs to be done here, I'm addressing this already in #34420 .  However, I wanted to open a new issue to ensure visibility in case someone was relying on the old behavior or knew of a reason that the old behavior existed.

### Component(s)

C++

**Comment by wjones127** [comment]
Not sure why that was the old behavior, but I remember there were inconsistencies with trailing slashes elsewhere in the API that I fixed in https://github.com/apache/arrow/pull/13577.

**Comment by westonpace** [comment]
I'm going to close this then.  #13577 is helpful.  Since the filesystems will reject the trailing slash anyways it seems good that PathFromUriOrPath shouldn't generate them.

I suppose it could be argued that PathFromUriOrPath should reject a trailing slash to match the filesystems API.  However, since things have merged, let's say if someone wants to make that change they can reopen.
