### ISSUE TITLE
[Website][Docs] Missing logo on Arrow docs page

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#35406]
### Describe the bug, including details regarding any error messages, version, and platform.

There seems to be a missing logo from the generated docs:
https://arrow.apache.org/docs/
![image](https://user-images.githubusercontent.com/639755/235890358-319e46eb-54ce-47d7-af3c-86fac1829117.png)
The logo is visible on other pages, like:
https://arrow.apache.org/docs/format/Versioning.html
![image](https://user-images.githubusercontent.com/639755/235890488-d52cf815-f23f-4961-9d23-5f0b82c6e02b.png)

### Component(s)

Documentation, Website

**Comment by raulcd** [comment]
@jorisvandenbossche , I've just seen you just opened something that might be related (sphinx 6). Should we close this one?

**Comment by jorisvandenbossche** [comment]
Let's wait a moment to see if the preview of https://github.com/apache/arrow/pull/35405 actually fixes it (I am not fully sure if the missing logo is also caused by the sphinx version)

**Comment by jorisvandenbossche** [comment]
This was actually caused by https://github.com/apache/arrow/pull/35194. Given that was needed to support sphinx 6.x (and I am pinning to 5 to fix the other issues), I will also temporarily revert that patch.

**Comment by jorisvandenbossche** [comment]
Actually not reverting, just fixing so it works for both sphinx 5 and 6
