### ISSUE TITLE
[Docs] DoubleArray and FloatingPointArray are missing from generated Python docs

### ISSUE THREAD

**Issue by spenczar** [apache/arrow#35413]
### Describe the bug, including details regarding any error messages, version, and platform.

https://arrow.apache.org/docs/python/api/arrays.html lists the concrete array types available in Pyarrow. But some are missing: https://github.com/apache/arrow/blob/205ceb99389d2d5060551ebcba17635185c74d9d/python/pyarrow/array.pxi#L1870-L1885 lists the float16/float32/float64 concrete array types, and they don't appear in the generated table, nor do their direct links (eg https://arrow.apache.org/docs/python/generated/pyarrow.DoubleArray.html) work. 

### Component(s)

Documentation, Python

**Comment by spenczar** [comment]
It appears to me that this is because those types are not in the big list of exported types in https://github.com/apache/arrow/blob/205ceb99389d2d5060551ebcba17635185c74d9d/python/pyarrow/__init__.py#L200C1-L202. Is that an oversight, or intentional?

**Comment by AlenkaF** [comment]
Thank you for reporting! I think this is not intentional.
In the PR you could add a comment to generate the preview of the docs: `@github-actions crossbow submit preview-docs`.
