### ISSUE TITLE
[JS] How to work around the error of 'Unrecognized type: "Duration" (18)'.

### ISSUE THREAD

**Issue by jpkli** [apache/arrow#35439]
### Describe the usage question you have. Please include as many useful details as  possible.

When using Apache Arrow in Javascript, `tableFromIPC` would throws the error of 'Unrecognized type: "Duration" (18)' if the input data had the Duration type. Is there any workaround before https://github.com/apache/arrow/issues/21815 is resolved? 

I tried to use `RecordBatchReader` to open an arrow file or stream that has the Duration type, and it also throws same error ( 'Unrecognized type: "Duration" (18)' ). 

This issue is really blocking the use of the Apache Arrow JavaScript library in production, any help or pointer would be very appreciated!

### Component(s)

JavaScript

**Comment by jpkli** [comment]
Hello maintainers for Arrow JS - @TheNeuralBit @trxcllnt @domoritz , any help for resolving this would be greatly appreicated!

**Comment by domoritz** [comment]
I don’t think there is a workaround other than not using the duration type until it’s implemented. We’d be open to a pull request to add support for the duration type, though.
