### ISSUE TITLE
[Docs] Function execution section missing from compute API reference

### ISSUE THREAD

**Issue by drin** [apache/arrow#35438]
### Describe the bug, including details regarding any error messages, version, and platform.

I see a doxygen warning, and an empty function execution section.

Missing section (or maybe just empty?):

    https://arrow.apache.org/docs/cpp/api/compute.html#function-execution

doxygen warning:
```
doxygengroup: Cannot find group “compute-functions-executor” in doxygen xml output for project “arrow_cpp” from directory: ../../cpp/apidoc/xml
```

The docs are for version `12.0.0`, but oddly enough I can't change the version of the docs (the dropdown doesn't do anything).

I haven't validated the bug or triaged, but wanted to at least file for now.

### Component(s)

Documentation, Website

**Comment by drin** [comment]
Also, not sure if relevant, but the `src` attribute for the logo is incorrect:
```html
<a class="navbar-brand" href="../../index.html">
  <img src="../../_static/../../_static/arrow.png" class="logo" alt="logo">
</a>
```

and I am seeing the following issues in the browser (firefox) console:
```
Uncaught ReferenceError: $ is not defined
    <anonymous> https://arrow.apache.org/docs/cpp/api/compute.html#function-execution:133
    <anonymous> https://arrow.apache.org/docs/cpp/api/compute.html#function-execution:151
    ...
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://arrow.apache.org/docs/_static/scripts/pydata-sphinx-theme.js?digest=1999514e3f237ded88cf:1
    n https://arrow.apache.org/docs/_static/scripts/pydata-sphinx-theme.js?digest=1999514e3f237ded88cf:1
    ...
Uncaught ReferenceError: $ is not defined
    <anonymous> https://arrow.apache.org/docs/_static/versionwarning.js:21
    <anonymous> https://arrow.apache.org/docs/_static/versionwarning.js:135
```

**Comment by AlenkaF** [comment]
Yeah, the first one is a bug or better a typo. The correct group for doxygen is [compute-function-executor](https://github.com/apache/arrow/blob/de6c3cd2b6048641251fac0c64b70c2cd166e0c9/cpp/src/arrow/compute/exec.h#L455) (without an "s"). It will be corrected in https://github.com/apache/arrow/pull/35486 (https://github.com/apache/arrow/pull/35486/commits/b973d8e8b70a9ebcd8058d4cc176e9899ec31d4f#diff-9f736d28913127c4be6a02ccd78ef2559880eb900ad25ca0c1bb8c53bd03462d)

As for the logo issue, I think it was solved in https://github.com/apache/arrow/pull/35405

**Comment by jorisvandenbossche** [comment]
@AlenkaF feel free to do a quick MINOR PR to already fix the typo (the more we can leave out of https://github.com/apache/arrow/pull/35486 the better, I think, given that's already a big diff and will still take some time to get merged)

**Comment by AlenkaF** [comment]
I am thinking of adding most of the formatting corrections from [this commit](https://github.com/apache/arrow/pull/35486/commits/b973d8e8b70a9ebcd8058d4cc176e9899ec31d4f) into one PR and link it to this issue. Would that be ok with everybody involved?

**Comment by jorisvandenbossche** [comment]
Yes, that would be good

**Comment by westonpace** [comment]
`compute-functions-executor` is changing in #35320 as well (just to make it more confusing).  I will address the feedback on #35320 today and try and get that through.

**Comment by AlenkaF** [comment]
Oh sorry, didn't realise that. Thank you for the info!
