### ISSUE TITLE
[Ruby] Can't install red-arrow on Debian GNU/Linux buster

### ISSUE THREAD

**Issue by ealders** [apache/arrow#35446]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently working on installing the red-arrow gem as part of our Ruby project that resides in a Docker container. I followed the directions for the latest Apache Arrow v12 release by attaching to the repository and was able to pull the precompiled binaries for libarrow-dev and libarrow-glib-dev. However, it seems the ruby gem is failing to install due to a versioning conflict. It is looking for v11 or higher libarrow-dev/libarrow-glib-dev binaries to compile against while the versions from the debian buster repo is showing a latest version of v8 of the precompiled arrow binaries. Is there a different repo that I should be adding to get the latest? Have the binaries not been updated in this repo for some reason? What is the best way to go about fixing this and getting the latest precompiled binaries for the ruby gems to work?

### Component(s)

C++, Release, Ruby

**Comment by kou** [comment]
We dropped support for Debian GNU/Linux buster.
Could you use Debian GNU/Linux bullseye instead? It's the current stable version.

**Comment by ealders** [comment]
Thanks for the info! Will update and give that a try.
