### ISSUE TITLE
What is the different between FileWriter#WriteTableAPI() and FileWriter#WriteRecordBatch()

### ISSUE THREAD

**Issue by JkSelf** [apache/arrow#35444]
### Describe the usage question you have. Please include as many useful details as  possible.

We are currently using arrow's parquet write API to write parquet files. It was found that different APIs will bring different performance data. We wrote a simple benchmark to read 1GB of tpcds `store_sales ` data [here](https://github.com/JkSelf/gluten/blob/1015756c07d326dc301d2b1824c8c40dc59b021b/cpp/velox/benchmarks/ParquetWriteBenchmark.cc#L220). Then use `FileWriter#WriteTableAPI()`, `FileWriter#WriteRecordBatch()` to write data respectively, and found the `FileWriter#WriteTable()` need **800s** and the `FileWriter#WriteRecordBatch()`  only need **4.9s** . The strange thing here is why the performance of WriteTableAPI is so poor.   I want to ask, is the way I use it wrong?

### Component(s)

C++, Parquet

**Comment by JkSelf** [comment]
@[lidavidm](https://github.com/lidavidm) Do you have any input?

**Comment by mapleFU** [comment]
I don't know if it's the real reason. But seems that `WriteTable` would force using non-buffered RowGroup Writer. Would you mind profile/benchmark these two method and tell us where cost more time? And maybe `src/parquet/arrow/reader_writer_benchmark.cc` helps?

**Comment by JkSelf** [comment]
@mapleFU
Thanks for your response. I profiled my benchmark and found that the problem here is that the [stream ](https://github.com/JkSelf/gluten/blob/1015756c07d326dc301d2b1824c8c40dc59b021b/cpp/velox/benchmarks/ParquetWriteBenchmark.cc#L208)I defined has been reallocating. It maybe my wrong usage cause the perf slow. I will update further with new findings. Thank for your help again.

**Comment by JkSelf** [comment]
The reason is that `DataBuffer ` defined in the stream is directly reallocated in `reverse()` method , and memcpy  must be called every time, resulting in performance degradation. And the perf can be 4s after changed the reallocated size to 2 times. I will closing this issue.  Thanks again @mapleFU.

**Comment by mapleFU** [comment]
These two api may have different buffered/non-buffered write path, maybe you can try to config them or avoid some thrink to fit if possible.

**Comment by JkSelf** [comment]
Can you elaborate on how to configure it?

**Comment by mapleFU** [comment]
@JkSelf 

```c++
  Status NewRowGroup(int64_t chunk_size) override {
    if (row_group_writer_ != nullptr) {
      PARQUET_CATCH_NOT_OK(row_group_writer_->Close());
    }
    PARQUET_CATCH_NOT_OK(row_group_writer_ = writer_->AppendRowGroup());
    return Status::OK();
  }
```

`parquet::arrow::FileWriterImpl::WriteTable` will call `NewRowGroup` for every chunk, which means it will first close previous RowGroup, then split input table to `chunk` by users row group size, and call `AppendRowGroup` to create non-buffered row-group writer for every chunk.

`parquet::arrow::FileWriterImpl::WriteRecordBatch` will close previous rowgroup if previous row-group is not a "buffered" row-group, and append `RecordBatch` to the buffered row-group.

And I'm working on buffered write table, may it helps.
