### ISSUE TITLE
[Website] Doc search never returns anything

### ISSUE THREAD

**Issue by spenczar** [apache/arrow#35456]
### Describe the bug, including details regarding any error messages, version, and platform.

Searching docs is currently broken. Search for "arrow" for example (https://arrow.apache.org/docs/search.html?q=arrow) results in:

> **Search Results**
> Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.

### Component(s)

Website

**Comment by jorisvandenbossche** [comment]
I suppose this is another symptom of the breakages of our docs with sphinx 6 (https://github.com/apache/arrow/issues/35403), eg also the dropdown is not working. 

We have to rebuild and upload the docs for the latest stable version, should be done in a few days: https://github.com/apache/arrow-site/pull/351#issuecomment-1533952206

**Comment by jorisvandenbossche** [comment]
This is working again, so closing this issue.
