### ISSUE TITLE
[CI][Packacking][Java] java-jar nightly builds fail with Connect Reset related to maven-shade-plugin 

### ISSUE THREAD

**Issue by sjperkins** [apache/arrow#35463]
### Describe the bug, including details regarding any error messages, version, and platform.

Following the discussion in https://github.com/apache/arrow/pull/35430#issuecomment-1536756434, the `java-jar` nightly builds have been failing since 2023-05-05:

- https://lists.apache.org/list.html?builds@arrow.apache.org
- 2023-05-04: https://github.com/ursacomputing/crossbow/actions/runs/4880720274/jobs/8715652875
- 2023-05-05: https://github.com/ursacomputing/crossbow/actions/runs/4891509316/jobs/8732835157

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade (default) on project arrow-vector:
Execution default of goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade failed:
Plugin org.apache.maven.plugins:maven-shade-plugin:3.1.1 or one of its dependencies could not be resolved:
Failed to collect dependencies at org.apache.maven.plugins:maven-shade-plugin:jar:3.1.1 -> org.ow2.asm:asm:jar:6.0:
Failed to read artifact descriptor for org.ow2.asm:asm:jar:6.0: The following artifacts could not be resolved:
org.ow2.asm:asm:pom:6.0 (absent):
Could not transfer artifact org.ow2.asm:asm:pom:6.0 from/to apache (https://repo.maven.apache.org/maven2/):
Connection reset -> [Help 1]
```

### Component(s)

Continuous Integration, Java, Packaging

**Comment by kou** [comment]
I close this because we don't see this problem recently.
