### ISSUE TITLE
pyarrow: parquet datatype mapping for pandas object column

### ISSUE THREAD

**Issue by Riezebos** [apache/arrow#3546]
## GitHub Issues for Apache Arrow
My question is a bit similar to https://github.com/apache/arrow/issues/2782, but I think the fix there doesn't apply here.

When writing a pandas df to parquet, it seems datatype mapping is inconsistent for columns with dtype `object`. Is this intended behavior? Is there a way to make mapping consistent with pandas dtype? Example below.

Using pyarrow 0.12. (Installed with `conda` in docker image `jupyter/scipy-notebook`)

When running the code at the bottom, `test.parquet` has the following schema:
`message schema {
  optional binary test (UTF8);
}`
`test2.parquet` has the following schema:
`message schema {
  optional int32 test;
}`

Code:
```python
import pandas as pd
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

df = pd.DataFrame(data={'test':['1',np.nan,np.nan,'2']})

pt = pa.Table.from_pandas(df, preserve_index=False)
pq.write_table(pt, 'test.parquet', version='2.0')

pt2 = pa.Table.from_pandas(df[1:3], preserve_index=False)
pq.write_table(pt2, 'test2.parquet', version='2.0')```

**Comment by wesm** [comment]
@Riezebos pandas does not have "real" schemas, so in the case of `pt2` it seems that pyarrow defaults to INT32 in the absence of a better guess (when there are all nulls). You can pass `pt.schema` when calling `Table.from_pandas` to ensure the same schema is used in both cases
