### ISSUE TITLE
[C++][Docs] Doxygen warning for JoinType and JoinKeyCmp

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#35474]
### Describe the bug, including details regarding any error messages, version, and platform.

When building the documentation there is a warning about the `JoinType` and `JoinKeyCmp` not being found:

```
/Users/alenkafrim/repos/arrow/docs/source/cpp/api/compute.rst:71: WARNING: doxygenenum: Cannot find enum "arrow::compute::JoinType" in doxygen xml output for project "arrow_cpp" from directory: ../../cpp/apidoc/xml
/Users/alenkafrim/repos/arrow/docs/source/cpp/api/compute.rst:73: WARNING: doxygenenum: Cannot find enum "arrow::compute::JoinKeyCmp" in doxygen xml output for project "arrow_cpp" from directory: ../../cpp/apidoc/xml
```

The warning is visible in the docs also: https://arrow.apache.org/docs/dev/cpp/api/compute.html#streaming-execution-operators.

### Component(s)

C++

**Comment by westonpace** [comment]
Ah, it should be `arrow::acero` now I believe.

**Comment by westonpace** [comment]
I believe this is fixed as part of https://github.com/apache/arrow/pull/35320

**Comment by AlenkaF** [comment]
Oh I see, thank you for the info! Will close this as it is visible from the CI builds on the mentioned PR that the warnings are fixed 👍
