### ISSUE TITLE
[MSVC] Arrow failed to build with MSVC under /std:c++latest mode due to error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function

### ISSUE THREAD

**Issue by Zhaojun-Liu** [apache/arrow#35501]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi all, 
Recently, we updated the commit of Arrow, and it failed to build with MSVC due to below error on Windows with option /std:c++latest:
`error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function ` 
Could you please help look this issue? Thanks.

**Repro steps:**
1. git clone https://github.com/apache/arrow F:\gitP\apache\arrow
2. git -C "F:\gitP\apache\arrow" submodule sync
3. git -C "F:\gitP\apache\arrow" submodule update --init --recursive
4. mkdir F:\gitP\apache\arrow\cpp\build_amd64 and cd F:\gitP\apache\arrow\cpp\build_amd64
5. set \_CL_= /std:c++latest
6. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DARROW_BUILD_TESTS=ON -DBOOST_ROOT=F:\tools\boost_1_77_0\x64 ..
7. msbuild /maxcpucount:1 /p:Platform=x64 /p:Configuration=Release arrow.sln /t:Rebuild

The commit we use: f9324b7

**Expected result:**
Build successfully.

**Actual result:**
`F:\gitP\apache\arrow\cpp\src\arrow/compute/function_internal.h(289,3): error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function [F:\gitP\apache\arrow\cpp\build_amd64\src\arrow\arrow_static.vcxproj]`

**Detailed log:**
[build.log](https://github.com/apache/arrow/files/11427952/build.log)

### Component(s)

C++

**Comment by westonpace** [comment]
@Zhaojun-Liu are you interested in contributing a PR?

**Comment by Zhaojun-Liu** [comment]
> @Zhaojun-Liu are you interested in contributing a PR?

In our test, I just try to change `nullptr` to be `""` at line https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/function_internal.h#L289, and it will build ok, but I'm not sure if this change will have other effects.

**Comment by kou** [comment]
Using `std::basic_string::basic_string("")` instead of `std::basic_string::basic_string(std::nullptr_t)` is a right approach.
Could you open a pull request with the approach?

**Comment by Zhaojun-Liu** [comment]
> Using `std::basic_string::basic_string("")` instead of `std::basic_string::basic_string(std::nullptr_t)` is a right approach. Could you open a pull request with the approach?

Ok, I have submitted the pull request.
