### ISSUE TITLE
[C++] Hashing array scalar with null bitmap and non-null 0s bitmap produces different hashes.

### ISSUE THREAD

**Issue by micah-white** [apache/arrow#35521]
### Describe the bug, including details regarding any error messages, version, and platform.

Null bitmaps in arrays are generally set to `nullptr` when the null count for the array is 0. However, there are cases where the null bitmap is set to a 0s buffer instead. Semantically, a 0s bitmap and a `nullptr` bitmap are the same thing. However, the hashing algorithm for array scalars will hash the null bitmap if it exists, and the resulting hash is not 0. This behavior can lead to two scalars with the same semantic value, but different internal values of the null bitmap, to hash to different values.

### Component(s)

C++

**Comment by jorisvandenbossche** [comment]
Related issue: https://github.com/apache/arrow/issues/35360 (not strictly related to the null bitmap, but just in general about that there are quite some things lacking about the ScalarHash implementation)
