### ISSUE TITLE
C# ArrowStreamReader fails on gRPC streamed ArrowTable serialized as .arrow IPC in-memory file (bytearray)

### ISSUE THREAD

**Issue by zarko-gvozdenovic** [apache/arrow#35564]
### Describe the bug, including details regarding any error messages, version, and platform.

C# same failure detected for nuget package versions 2.0.0/10.0.0/11.0.0/12.0.0/13.0.0
Exception:
Unexpectedly reached the end of the stream before a full buffer was read.

The same ArrowTable (i.e. .arrow IPC in-memory byte array) can be successfully loaded using ArrowFileReader, after if had been saved from the streamed bytes using File.WriteAllBytes.

### Component(s)

C#

**Comment by westonpace** [comment]
I believe this is expected behavior.  Those are two different formats.  If you serialize a table with the file format then you need to read it with the file format.

**Comment by zarko-gvozdenovic** [comment]
Thx for your correct reply, Weston.

Some context:
My Python gRPC service was serializing the PyArrow.Table using pyarrow.ipc.new_file (instead of new_stream).
My C# .Net6 gRPC client was trying to deserialize it using ArrowStreamReader(MemoryStream(<ReceivedByteArray>).ReadNextRecordBatch(Async).
