### ISSUE TITLE
[Java] NullVector returning an inconsistent hash for null values between vectors

### ISSUE THREAD

**Issue by jarohen** [apache/arrow#35588]
### Describe the bug, including details regarding any error messages, version, and platform.

It's currently [implemented](https://github.com/apache/arrow/blob/cd6e2a4d2b9373b942da18b4cc82cb41431764d9/java/vector/src/main/java/org/apache/arrow/vector/NullVector.java#L281) as `31 * valueCount`, which returns a different hashCode for null values from different-length `NullVector`s. Presumably this should be a constant value?

James

### Component(s)

Java

**Comment by lidavidm** [comment]
Huh. Yeah, it should be a constant.

**Comment by lidavidm** [comment]
A quick PR would be welcome, or @davisusanibar would you be able to take a look?

**Comment by jarohen** [comment]
Hey @lidavidm - yep, have raised a PR. Don't think I've got my environment set up completely in order to run the later module tests, but the vector module passed.

James

**Comment by lidavidm** [comment]
Issue resolved by pull request 35590
https://github.com/apache/arrow/pull/35590
