### ISSUE TITLE
[R] Confusing (NULL) results when using `[[` and `$` to try to extract columns from Datasets

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#35593]
### Describe the bug, including details regarding any error messages, version, and platform.

``` r
library(arrow)

# All good with Tables
mt_table <- arrow_table(mtcars)
# Yay
mt_table[["hp"]]
#> ChunkedArray
#> <double>
#> [
#>   [
#>     110,
#>     110,
#>     93,
#>     110,
#>     175,
#>     105,
#>     245,
#>     62,
#>     95,
#>     123,
#>     ...
#>     150,
#>     245,
#>     175,
#>     66,
#>     91,
#>     113,
#>     264,
#>     175,
#>     335,
#>     109
#>   ]
#> ]
# Hooray
mt_table$hp
#> ChunkedArray
#> <double>
#> [
#>   [
#>     110,
#>     110,
#>     93,
#>     110,
#>     175,
#>     105,
#>     245,
#>     62,
#>     95,
#>     123,
#>     ...
#>     150,
#>     245,
#>     175,
#>     66,
#>     91,
#>     113,
#>     264,
#>     175,
#>     335,
#>     109
#>   ]
#> ]

# Not so good with Datasets
tf <- tempfile()
dir.create(tf)
write_dataset(mtcars, tf)
mt_dataset <- open_dataset(tf)
# Nope
mt_dataset[["hp"]]
#> NULL
# More nope
mt_dataset$hp
#> NULL
```
It's also not helped that typing `mt_dataset$` and using tab completion then displays the different column names

### Component(s)

R

**Comment by thisisnic** [comment]
Do we just want to write bindings for `[[.Dataset` and `$.Dataset` which map to `filter()`?

**Comment by nealrichardson** [comment]
> Do we just want to write bindings for `[[.Dataset` and `$.Dataset` which map to `select.Dataset()`?

I don't think so: `[[` and `$` extract from an object, and we don't have the concept of a lazy ChunkedArray. `[.Dataset` would return a Dataset (well, arrow_dplyr_query)--and in fact it does, it is implemented. 

IMO it could either be implemented as `select |> compute` or `stop("[[ is not implemented for Datasets")`

**Comment by thisisnic** [comment]
I think this is a question of how we conceptualise the difference between Tables and Datasets.  I opened this ticket after writing content which takes the perspective that a Dataset is very similar to a Table, but the distinction is in-memory versus on-disk.  

If we think about a Table being analogous to a data frame and a Dataset being analogous to a DB connection, then the current behaviour as it is makes sense as it mirrors dbplyr.  

`select |> compute` is appealing as it does *something* and removes friction, and even if it's not necessarily the typical way of working with Dataset objects, it doesn't feel like adding additionally unnecessary ways of doing something.  I'm not entirely opposed to an error message with a suggestion, but I think here, letting it "just work" is preferable.

**Comment by thisisnic** [comment]
I'm going to close this for now; I'm not sure it's worth investing the time to do something to change the existing behaviour. If anyone wants to re-open this in future, feel free.
