### ISSUE TITLE
[R] unable to create struct in schema for open_dataset

### ISSUE THREAD

**Issue by rdavis120** [apache/arrow#35604]
### Describe the bug, including details regarding any error messages, version, and platform.

When reading a parquet file and trying to set the schema to use a struct, I only get NA values back.

```r
# write parquet 
arrow::write_dataset(iris, path = 'iris.parquet')

arrow::open_dataset("iris.parquet") |> dplyr::collect()
    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
1            5.1         3.5          1.4         0.2     setosa
2            4.9         3.0          1.4         0.2     setosa


arrow::open_dataset("iris.parquet", schema = schema(Species=string(),  
                                                    Sepal = struct(Sepal.Length = float64(), Sepal.Width = float64()),  
                                                    Petal = struct(Petal.Length = float64(), Petal.Width = float64()))) |>
  dplyr::collect()
   Species Sepal$Sepal.Length $Sepal.Width Petal$Petal.Length $Petal.Width
   <chr>                <dbl>        <dbl>              <dbl>        <dbl>
 1 setosa                  NA           NA                 NA           NA
 2 setosa                  NA           NA                 NA           NA
 3 setosa                  NA           NA                 NA           NA

> packageVersion('arrow')
[1] ‘12.0.0’
```

### Component(s)

R

**Comment by westonpace** [comment]
The schema in `open_dataset` is not a tool for introducing mutations on the columns.  It can be used to reduce the number of columns you load, or I believe you can include additional columns (to get null values), but you should not be changing the type of existing columns.

I think you will want to use dplyr's mutate and the `make_struct` function (I'm not sure what the R bindings look like for this function).

**Comment by rdavis120** [comment]
Ok thanks, I think this works.  

The reason to convert the columns to a struct was that since a udf can support up to three argument, we can get around this by converting a table with >3 columns to a struct, and then passing the struct as an argument to the udf, which is before the collect(). 

library(arrow)
#
arrow::register_scalar_function(
  "sum2",
  function(context, x) {
    rowSums(x, na.rm = T)
  },
  in_type = schema(x = struct(Sepal.Length = float64(), Sepal.Width = float64(), Petal.Length = float64(), Petal.Width = float64())),
  out_type = float64(),
  auto_convert = T
)
#
arrow::write_dataset(iris, path = "iris.parquet")
x <- arrow::open_dataset("iris.parquet")
x |>
  dplyr::mutate(x = data.frame(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width), .keep = "none") |>
  dplyr::mutate(sum2 = sum2(x), .keep = "none") |>
  dplyr::collect()
