### ISSUE TITLE
[R] R builds failing with error 'Invalid: Timestamps already have a timezone: 'UTC'. Cannot localize to 'UTC''

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#35633]
### Describe the bug, including details regarding any error messages, version, and platform.

Lots of R builds (e.g. [here](https://github.com/ursacomputing/crossbow/actions/runs/4997978281/jobs/8952919283#step:6:24161)) are failing with the following error:

```
Invalid: Timestamps already have a timezone: 'UTC'. Cannot localize to 'UTC'.
```

which comes from this line in the C++ library: https://github.com/apache/arrow/blob/b60bb968863f3e6d8bc08cae32b370ea64a3cc22/cpp/src/arrow/compute/kernels/scalar_temporal_unary.cc#L124

This happened since we updated the vendored version of the date library, so perhaps could be related to that?

### Component(s)

C++

**Comment by thisisnic** [comment]
This fails on the nightly builds, but I can't replicate this when locally, or when running it on PRs (see https://github.com/apache/arrow/pull/3561).

**Comment by jorisvandenbossche** [comment]
> This happened since we updated the vendored version of the date library, so perhaps could be related to that?

Was that done in a specific PR? (to understand what changed)

**Comment by jorisvandenbossche** [comment]
I see that this is https://github.com/apache/arrow/pull/35612. Now, that was actually passing on main, so it might also have been triggered by https://github.com/apache/arrow/pull/35449 (which is failing with this on main, and was actually also already failing on the PR ..)

**Comment by thisisnic** [comment]
Yep, it was in https://github.com/apache/arrow/pull/35612

**Comment by jorisvandenbossche** [comment]
My assumption is that the fix of https://github.com/apache/arrow/pull/35449 caused one of the test dates to become UTC, causing the failure. If that's the case, we will need to fix the test I think

**Comment by thisisnic** [comment]
You're right; it is failing on the CI on that PR, e.g. https://github.com/apache/arrow/actions/runs/4900485911/jobs/8751167526

**Comment by jorisvandenbossche** [comment]
Here:

https://github.com/apache/arrow/blob/99ef3aada1d1589604da8905f3c9100ff1c997e9/r/tests/testthat/test-dplyr-funcs-datetime.R#L292

This adds the format ``"%T%z"``, and that will now actually result in a tz-aware timestamp, while before it didn't parse the timezone correctly.
