### ISSUE TITLE
[C++] util/small_vector_test.cc reports a self-move warning with MinGW

### ISSUE THREAD

**Issue by kou** [apache/arrow#35651]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/5006155150/jobs/8971042580#step:7:1154

```text
D:/a/arrow/arrow/cpp/src/arrow/util/small_vector_test.cc:417:22: warning: moving 'moved_moved_ints' of type 'arrow::internal::TestSmallStaticVector<arrow::internal::VectorIntLikeParam<arrow::internal::StaticVectorTraits, arrow::MoveOnlyDataType> >::IntVectorType<5>' {aka 'arrow::internal::StaticVectorImpl<arrow::MoveOnlyDataType, 5, arrow::internal::StaticVectorStorage<arrow::MoveOnlyDataType, 5, true> >'} to itself [-Wself-move]
  417 |     moved_moved_ints = std::move(moved_moved_ints);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/a/arrow/arrow/cpp/src/arrow/util/small_vector_test.cc:417:22: note: remove 'std::move' call
```

### Component(s)

C++

**Comment by zhjwpku** [comment]
I got the same error on macos with gcc 13.1

/Users/zhjwpku/zhjwpku/arrow/cpp/src/arrow/util/small_vector_test.cc:418:22: error: moving 'moved_moved_ints' of type 'arrow::internal::TestSmallStaticVector<arrow::internal::VectorIntLikeParam<arrow::internal::SmallVectorTraits, arrow::MoveOnlyDataType> >::IntVectorType<5>' {aka 'arrow::internal::StaticVectorImpl<arrow::MoveOnlyDataType, 5, arrow::internal::SmallVectorStorage<arrow::MoveOnlyDataType, 5> >'} to itself [-Werror=self-move]
/Users/zhjwpku/zhjwpku/arrow/cpp/src/arrow/util/small_vector_test.cc:418:22: note: remove 'std::move' call

I checked the [GCC 13 Release note](https://gcc.gnu.org/gcc-13/changes.html), this is a newly added warning, I guess the warning with MinGW might be using
gcc 13 too.
