### ISSUE TITLE
`DeltaLengthByteArrayEncoder::Put` may reserve too much space

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#35665]
### Describe the bug, including details regarding any error messages, version, and platform.

`DeltaLengthByteArrayEncoder::Put` passes the total desired capacity (`encoded_size_`) to `BufferBuilder::Reserve`. However, `BufferBuilder::Reserve` expects the _additional_ desired capacity. This will therefore request much more memory than desired, and perhaps reallocate more often than expected.

https://github.com/apache/arrow/blob/3e4eaa917fa9b09a923d255adee520aa68a4e78c/cpp/src/parquet/encoding.cc#L2651-L2675

### Component(s)

C++

**Comment by pitrou** [comment]
@felipecrv Do you want to take a look at this?

Also @rok FYI.

**Comment by pitrou** [comment]
It would be a good idea to look for similar mistakes in other Parquet encoders/decoders.

**Comment by mapleFU** [comment]
Maybe I can take a look and fix them.

**Comment by pitrou** [comment]
@mapleFU Feel free to.

**Comment by rok** [comment]
Thanks for catching this @pitrou! I seem to have mixed up `Resize` and `Reserve`.

**Comment by mapleFU** [comment]
(Actually it's a bit misleading. C++ `std::vector<T>::reserve` interface works like rok does. But our arrow code use it as incremental...)
