### ISSUE TITLE
[Python] `test_total_bytes_allocated` failing on CI

### ISSUE THREAD

**Issue by h-vetinari** [apache/arrow#35728]
### Describe the bug, including details regarding any error messages, version, and platform.

In https://github.com/conda-forge/arrow-cpp-feedstock/pull/1053, I currently have a failing test `test_total_bytes_allocated` on arrow 12 (though not arrow 11 or before), but some commit between arrow 12 and current `main` seems to have fixed this[^1] - any ideas?

This is currently holding up all our migrations on the arrow-feedstock and is very high priority for us in conda-forge. Possible solutions:
* someone tells me that it's fine to skip that test
* we identify the relevant changes that regressed this from 11->12 and revert them (on the feedstock)
* we identify what fixed the issue between 12 & main and I backport those changes (on the feedstock)

[^1]: as confirmed in #35637

_Originally posted by @h-vetinari in https://github.com/apache/arrow/issues/35637#issuecomment-1552650935_
            

### Component(s)

Packaging

**Comment by assignUser** [comment]
@westonpace is it fine to skip that test or do you know if that fix was already added for 12.0.1?

**Comment by h-vetinari** [comment]
Thanks @assignUser for chiming in! Some more context. It did not appear for the last successful [build](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1042) of 12.0.0, then appeared for a [migration](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1053) (of simultaneously re2, aws-crt & google-cloud-cpp; because reasons...), but only on linux, and not for any of the older arrow versions (which received the same migrator PRs).

> Single test failure here, and only on linux. Normally I'd go with a skip, but this looks like it might be leaking memory? Any ideas? The test in question [has no](https://github.com/apache/arrow/blob/apache-arrow-12.0.0/python/pyarrow/tests/test_array.py#L40-L41) comments or documentation AFAICS.
> 
> ```
> =================================== FAILURES ===================================
> __________________________ test_total_bytes_allocated __________________________
> 
>     def test_total_bytes_allocated():
> >       assert pa.total_allocated_bytes() == 0
> E       assert 1216 == 0
> E        +  where 1216 = <built-in function total_allocated_bytes>()
> E        +    where <built-in function total_allocated_bytes> = pa.total_allocated_bytes
> ```
> 
> It's also interesting that this doesn't appear in any of the equivalent PRs to the maintenance branches, e.g. #1057.

However, I've now restarted https://github.com/conda-forge/arrow-cpp-feedstock/pull/1053, and although I have no idea why, the failure seems to have disappeared! 🥳 

I'm happy to close this issue (and apologise for the noise), unless people want to leave this open a bit longer to understand better what's happening with `test_total_bytes_allocated`. As I mentioned above, it's hard to tell for me (from lack of code comments/context) what this test is actually testing, under which conditions it may fail, and how serious that is if it happens.

**Comment by jorisvandenbossche** [comment]
I think the context for that test is that in theory this method should always return zero if there is no data allocated/held by Arrow. And we are careful to ensure that in the tests we only create arrow data _inside_ a test function (and for example not in the pytest.mark.parametrize values), to ensure that this assertion holds.

Now, why it would have temporarily failed, no idea.

**Comment by jorisvandenbossche** [comment]
This failure is not also happening on our own CI, for example the latest [wheel-manylinux-2014-cp310-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5241345438/jobs/9463315424) nightly build also has

```
 __________________________ test_total_bytes_allocated __________________________

    def test_total_bytes_allocated():
>       assert pa.total_allocated_bytes() == 0
E       assert 640 == 0
E        +  where 640 = <built-in function total_allocated_bytes>()
E        +    where <built-in function total_allocated_bytes> = pa.total_allocated_bytes
```

**Comment by pitrou** [comment]
Ok, perhaps we can simply execute this test in a subprocess to make it more reliable?
