### ISSUE TITLE
[FlightRPC][C++] Order of gRPC channel arguments is wrong

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#35725]
### Describe the bug, including details regarding any error messages, version, and platform.

```cpp
    // Allow setting generic gRPC options.
    for (const auto& arg : options.generic_options) {
      if (std::holds_alternative<int>(arg.second)) {
        default_args[arg.first] = std::get<int>(arg.second);
      } else if (std::holds_alternative<std::string>(arg.second)) {
        args.SetString(arg.first, std::get<std::string>(arg.second));
      }
      // Otherwise unimplemented
    }
    for (const auto& pair : default_args) {
      args.SetInt(pair.first, pair.second);
    }
```

We should set the defaults _before_ the user-supplied arguments.

### Component(s)

C++, FlightRPC

**Comment by chLynda** [comment]
Hello ,for my first contribution ,i would like work on your project .Can I?

**Comment by lidavidm** [comment]
@chLynda please feel free, you can look at https://arrow.apache.org/docs/dev/developers/contributing.html to get started.

**Comment by perhapsmaple** [comment]
@lidavidm The above code snippet seems to first processes user-supplied options within the loop, overwriting the default options and then sets the arguments. It looks correct in terms of ordering the setting of default arguments and user-supplied options to me. Maybe I'm missing something, if you could explain the desired change, I would be happy to help and contribute.

**Comment by lidavidm** [comment]
Hmm, right. I don't remember what the original problem was anymore so let's close it.
