### ISSUE TITLE
[Parquet][C++][Python] Bump the default format version from 2.4 -> 2.6

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#35746]
### Describe the enhancement requested

Parquet format version 2.6 introduces the NanoSecond time unit for Time and Timestamp logical types.

### Component(s)

Parquet

**Comment by mapleFU** [comment]
I found that our implemention already supports `Timestamp`:

```c++
/// \brief Allowed for physical type INT64.
class PARQUET_EXPORT TimestampLogicalType : public LogicalType {
 public:
  static std::shared_ptr<const LogicalType> Make(bool is_adjusted_to_utc,
                                                 LogicalType::TimeUnit::unit time_unit,
                                                 bool is_from_converted_type = false,
                                                 bool force_set_converted_type = false);
  bool is_adjusted_to_utc() const;
  LogicalType::TimeUnit::unit time_unit() const;

  /// \brief If true, will not set LogicalType in Thrift metadata
  bool is_from_converted_type() const;

  /// \brief If true, will set ConvertedType for micros and millis
  /// resolution in legacy ConvertedType Thrift metadata
  bool force_set_converted_type() const;

 private:
  TimestampLogicalType() = default;
};
```

And timeunit has `NANO`

```
  struct TimeUnit {
    enum unit { UNKNOWN = 0, MILLIS = 1, MICROS, NANOS };
  };
```

Do we already supports them?

/cc @wgtmac

**Comment by mapleFU** [comment]
Have you tried:

```
::parquet::WriterProperties::Builder()
                                            .version(ParquetVersion::PARQUET_2_6)
                                            ->build();
```

**Comment by jorisvandenbossche** [comment]
Yes, we indeed already support that version, but we _default_ to 2.4 at the moment. I edited the title that the issue is about changing the default version.

The default in C++:

https://github.com/apache/arrow/blob/6d2df074e624a6a4462a1539be8dadf19cf39df4/cpp/src/parquet/properties.h#L207-L221

And similarly in the Python bindings the default is also "2.4".

**Comment by wgtmac** [comment]
It seems that parquet-cpp has implemented features (e.g. modular encryption and BYTE_STREAM_SPLIT encoding) beyond version 2.6. We probably need to update supported versions and manage features based on the version.

https://github.com/apache/parquet-format/blob/master/CHANGES.md

**Comment by mapleFU** [comment]
> It seems that parquet-cpp has implemented features (e.g. modular encryption and BYTE_STREAM_SPLIT encoding) beyond version 2.6. We probably need to update supported versions and manage features based on the version.
> 
> https://github.com/apache/parquet-format/blob/master/CHANGES.md

We can open issue about this, I can take time to fix it.

**Comment by pitrou** [comment]
Ok, so parquet-mr implemented nanosecond precision timestamps in 2018: https://github.com/apache/parquet-mr/pull/519
while we did so in 2018 (basic support) and 2019 (Arrow roundtrip):
https://github.com/apache/arrow/pull/4185
https://github.com/apache/arrow/pull/4421

I think this makes it ok to bump the default to 2.6.
