### ISSUE TITLE
[Go] TimestampType zero value default to seconds unit instead of nanoseconds

### ISSUE THREAD

**Issue by ddl-gabrielhaim** [apache/arrow#35770]
### Bug

The godoc mentions the zero value of `arrow.TimestampType` should be nanosecond UTC  (see https://github.com/apache/arrow/blob/main/go/arrow/datatype_fixedwidth.go#L340) but the `arrow.TimeUnit` seems to default to seconds (https://github.com/apache/arrow/blob/main/go/arrow/datatype_fixedwidth.go#L327)

```golang
package main

import (
	"fmt"

	"github.com/apache/arrow/go/v13/arrow"
)

func main() {
	t1 := arrow.TimestampType{Unit: arrow.Nanosecond}
	t2 := arrow.TimestampType{}

	fmt.Printf("Timestamp Unit 3: %s\n", t1.Unit)
	fmt.Printf("Timestamp Unit default: %s\n", t2.Unit)
}
```

output:
```
Timestamp Unit 3: ns
Timestamp Unit default: s
```

### Component(s)

Go, Arrow v13

**Comment by zeroshade** [comment]
@ddl-gabrielhaim good catch. A bunch of the math and shortcuts are based on the fact that the enum value of `Seconds` is 0 (to make life easier), so we should probably update the documentation/comment to clarify that the zero value is Seconds not Nanoseconds. Would you be willing to create a PR for it?
