### ISSUE TITLE
Memory leak reading parquet files with pyarrow

### ISSUE THREAD

**Issue by DiegoRider** [apache/arrow#3580]
I have many ~200MB files in a directory on hdfs. I'm trying to read them one by one and pick only the rows of data I am interested in, to not overload the memory in my machine. However I realized the memory of the downloaded datasets was not being freed. here is a simplified version of my code that still causes the error : 

import pyarrow 

hdfs = pyarrow.hdfs.connect()
files = hdfs.ls(path)
subdfs = []
for filename in files:
    df = hdfs.read_parquet(filename).to_pandas()
    subdf = df[df.index < 100]
    subdfs.append(subdf)

The memory allocated by "df" isn't freed until "subdfs" doesn't exist anymore. This isn't a pandas issue because if I create a dataframe directly with pandas it the memory leak doesn't happen. 

## GitHub Issues for Apache Arrow

We support GitHub issues as a lightweight way to ask questions and engage with
the Arrow developer community. We use the Apache Software Foundation's JIRA
instance for maintaining a queue of development work and as the public record
for work on the project. So, feel free to delete this text and open an issue
here if you have a question or aren't sure whether something is a bug or
feature request. Any bugs, suggestions, or feature requests will eventually
need to end up in JIRA, either before or after completing a pull request.

See the Arrow JIRA project here: https://issues.apache.org/jira/browse/ARROW.

For more in-depth development discussions, please use the public mailing list
dev@arrow.apache.org (first subscribe by sending an e-mail to
dev-subscribe@arrow.apache.org).

**Comment by DiegoRider** [comment]
I am using pyarrow 0.11.1
and running my code in a jupyter notebook version 4.4.0

**Comment by wesm** [comment]
What about with pyarrow 0.12.0 (just released)? As discussed in http://arrow.apache.org/blog/2019/02/05/python-string-memory-0.12/, in pyarrow 0.11.1 and earlier, `to_pandas` can use an alarming amount of memory, so please try upgrading first.

Otherwise I would need a reproducible example to look at to be able to help you

**Comment by DiegoRider** [comment]
I'll try that, thanks. I did find a hack to fix it, by replacing 
subdfs.append(subdf) 
by  
subdfs.append(subdf * 1).
I'm not sure how to give you a reproducible example, just thought you might want to know about this leak.

**Comment by emkornfield** [comment]
I think this is probably working as intended,  I think pandas dataframes are created as "immutable" without a memory copy if possible.  I think the slice operation, is also zero-copy and Per  pandas documentation https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.copy.html doesn't copy the actual data if possible.
