### ISSUE TITLE
[Python] Investigate why extension type test fails with pandas 2.0.x

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#35839]
### Describe the bug, including details regarding any error messages, version, and platform.

For our release 12.0.x we are skipping extension type tests for pandas < 2.0, see:
* https://github.com/apache/arrow/issues/35821
* https://github.com/apache/arrow/issues/35321

This is issue should follow up on those to investigate the cause.

### Component(s)

Python

**Comment by raulcd** [comment]
cc @jorisvandenbossche

**Comment by raulcd** [comment]
We should check whether this is still happening

**Comment by jorisvandenbossche** [comment]
I think we can close this issue without any further action.

It has been fixed on the pandas side (https://github.com/pandas-dev/pandas/issues/54063, I think through https://github.com/pandas-dev/pandas/pull/54130), but only in pandas 2.1.x. That leaves this as a bug/regression on pandas 2.0.x, but given pandas itself will not do more releases for 2.0.x, we can leave it at this.
