### ISSUE TITLE
[C++] Acero will hang if StopProducing is called while backpressure is applied on the source node

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#35837]
### Describe the bug, including details regarding any error messages, version, and platform.

The source node creates an external task called `SourceNode::DatasetScan` which is managed outside the exec plan.  This task is actually an `arrow::Loop` call which is iterating the source async generator.  That loop can be paused and resumed to apply backpressure.

When StopProducing arrives the source node sets `stop_requested_=true`.  However, `stop_requested_` is not processed until the next iteration through the loop.  If the plan is paused then the loop is not iterating and nothing notices that `stop_requested_` changed and the external task never completes and the plan then never completes.

### Component(s)

C++

**Comment by rtpsw** [comment]
take
