### ISSUE TITLE
[R][Documentation] Improve text in top-level package README

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#35875]
### Describe the enhancement requested

As discussed on the 2023/06/01 Arrow R package development sync call, a reworking of the [top-level README](https://arrow.apache.org/docs/r/) might make it easier for potential users of the package to understand what they can do and more likely for them to become users. While the current content gives a good overview, there are some areas it could be improved:

1. Move the discussion of Apache Arrow itself lower down
2. Describe a smaller and denser list of features, some could be combined, some could be moved or removed. Maybe five or so
3. Link each feature to more detail about how to use that feature

The [sparklyr](https://spark.rstudio.com) package website was brought up as an example and I think it's a good one. It lists a denser feature set and links to internal documentation for each. Their [guides](https://spark.rstudio.com/guides/) section was also brought up because of how it organizes guides.

Please comment if you have any ideas or suggestions.

cc @thisisnic @stephhazlitt @fmichonneau 

### Component(s)

Documentation, R

**Comment by dgreiss** [comment]
Happy to help on this one if needed.
