### ISSUE TITLE
[Ruby][Question] Is it possible to limit memory (RAM) usage when reading very large Parquet files?

### ISSUE THREAD

**Issue by collimarco** [apache/arrow#36001]
### Describe the usage question you have. Please include as many useful details as  possible.

I have a line like this:

```ruby
table = Arrow::Table.load('data.parquet', format: :parquet)
```

The problem is that I wonder what happens if I use this command when the file size exceeds the RAM available. For example, that command may run on a Kubernetes pod that has a memory limit of 1GB, but the file can be 2GB.

1. Is there a way to tell Arrow to use at most 500MB-800MB of RAM?

2. Otherwise, is there a way to read and query the file piece by piece without loading it entirely on RAM?

### Component(s)

Ruby

**Comment by kou** [comment]
> 1. Is there a way to tell Arrow to use at most 500MB-800MB of RAM?

Unfortunately, we don't have it...

> 2. Otherwise, is there a way to read and query the file piece by piece without loading it entirely on RAM?

You can read data per row group:

```ruby
Arrow::FileInputStream.open("data.parquet") do |input|
  reader = Parquet::ArrowFileReader.new(input)
  reader.n_row_groups.times do |i|
    table = reader.read_row_group(i)
    # Process table
  end
end
```

**Comment by mapleFU** [comment]
Personally I suggest that you can try to use buffered row-group. With un-buffered io, all column-chunk in a row-group can be read. If it's buffered, each column will only read a `min(buffer-size, page-size)`

**Comment by kou** [comment]
Wow! I didn't know the feature. Could you tell me C++ API for the buffered row-group feature?

**Comment by mapleFU** [comment]
```c++
class PARQUET_EXPORT ReaderProperties {
 public:
  /// Buffered stream reading allows the user to control the memory usage of
  /// parquet readers. This ensure that all `RandomAccessFile::ReadAt` calls are
  /// wrapped in a buffered reader that uses a fix sized buffer (of size
  /// `buffer_size()`) instead of the full size of the ReadAt.
  ///
  /// The primary reason for this control knobs is for resource control and not
  /// performance.
  bool is_buffered_stream_enabled() const { return buffered_stream_enabled_; }
  /// Enable buffered stream reading.
  void enable_buffered_stream() { buffered_stream_enabled_ = true; }
  /// Disable buffered stream reading.
  void disable_buffered_stream() { buffered_stream_enabled_ = false; }
```

cc @kou

**Comment by collimarco** [comment]
@mapleFU Thanks for the additional suggestion. Is there any Ruby code that I can try? I can benchmark them to see which one performs best in our case

**Comment by mapleFU** [comment]
Sorry I'm not so familiar with Ruby code, you can ask kou for how to use it.

Personally, I guess if you're reading a local file, I guess buffer-io can provide similiar performance with less io.If you're using S3 or other, batch read without buffer-io might provide better performance, but consumes more memory, because they do less IO. But you can enlarge buffer I/O size to tradeoff.

**Comment by kou** [comment]
Thanks.

@collimarco We haven't implemented the bindings of `parquet::ReaderProperties` yet. Could you open a new issue to implement them? Then we can use the feature from Ruby.

**Comment by collimarco** [comment]
Ok, thanks, I have opened the separate issue.
