### ISSUE TITLE
[C++] Bundled OpenTelemetry build is broken

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#36013]
### Describe the bug, including details regarding any error messages, version, and platform.

OpenTelemetry and Protobuf have conflicting versions of Abseil, which is causing build errors

- https://github.com/apache/arrow/actions/runs/5222129024/jobs/9427236062?pr=35628#step:9:984
- https://github.com/apache/arrow/actions/runs/5201352712/jobs/9381376686#step:9:984

These issues have been encountered and addressed in the conda-forge feedstock for opentelemetry, see

- https://github.com/conda-forge/cpp-opentelemetry-sdk-feedstock/issues/29
- https://github.com/conda-forge/cpp-opentelemetry-sdk-feedstock/pull/48

Unfortunately, the fix requires a patch to OpenTelemetry so it's not as simple as [building `-D WITH_STL=ON`](https://github.com/apache/arrow/pull/35628/commits/74d6e263ee7bd2e1883287b9813a7e0f0c12aff8).

For now it should be sufficient to disable bundled OpenTelemetry and rely on conda-forge's patch.

@kou @lidavidm 

### Component(s)

C++

**Comment by kou** [comment]
https://github.com/open-telemetry/opentelemetry-cpp/pull/2163 may fix this.

This may not be happen when we use Protobuf < 3.22?
