### ISSUE TITLE
[Python] pyarrow read tsv file failed

### ISSUE THREAD

**Issue by jelech** [apache/arrow#36037]
### Describe the bug, including details regarding any error messages, version, and platform.

platform: macos
pyarrow version: 12.0.0

## tsv file
tsv file from [data](https://github.com/google-research-datasets/wit/blob/main/DATA.md). one of [sample file](https://storage.googleapis.com/gresearch/wit/wit_v1.train.all-1percent_sample.tsv.gz)

## code
```python
import pyarrow.csv as csv_pq
with open("f.tsv", "rb") as file:
        tsv_file = csv_pq.read_csv(file, parse_options=csv_pq.ParseOptions(delimiter="\t"))
```

## error:
```shell
  tsv_file = csv_pq.read_csv(file, parse_options=csv_pq.ParseOptions(delimiter="\t"))
  File "pyarrow/_csv.pyx", line 1235, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1244, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 17 columns, got 1: В декабре 2009 года, Ford объявили, что кастомная раскрас ...
```

and the error will change line, when you delete line2. It looks like the error is related to the read buffer pool?

### Component(s)

Python

**Comment by westonpace** [comment]
Those files have newlines in some of the values.  You need `ParseOptions(delimiter="\t", newlines_in_values=True)`

**Comment by jelech** [comment]
thanks
