### ISSUE TITLE
[Python] pyarrow.ListArray.flatten not returning Array type

### ISSUE THREAD

**Issue by XinyuZeng** [apache/arrow#36049]
### Describe the bug, including details regarding any error messages, version, and platform.

Per [doc](https://arrow.apache.org/docs/python/generated/pyarrow.ListArray.html#pyarrow.ListArray.flatten) says: 

pyarrow.ListArray.flatten returns: result [Array](https://arrow.apache.org/docs/python/generated/pyarrow.Array.html#pyarrow.Array)

However it returns a Python list. This behavior is different from [pyarrow.compute.list_flatten](https://arrow.apache.org/docs/python/generated/pyarrow.compute.list_flatten.html#pyarrow.compute.list_flatten).

Code:
```python
table = pq.read_table('hug_data/general-pmd.parquet')
col = table.column('image_embedding')
print(col.slice(0,2))
print(type(col))
print(type(col.flatten()))
print(type(pa.compute.list_flatten(col)))
```
Output:
```text
[
  [
    null,
    [
      [
        1.75,
        0.6015625,
        -0.72265625,
        -0.22949219,
        -0.484375,
        ...
        -3.1875,
        2.140625,
        0.05078125,
        -0.56640625,
        -0.0703125
      ],
      [
        -0.07421875,
        0.61328125,
        0.984375,
        -0.56640625,
        -0.609375,
        ...
        -1.5234375,
        -0.087890625,
        -1.3125,
        3.078125,
        -0.6875
      ],
      ...
      [
        -0.82421875,
        -1.4921875,
        -0.20507812,
        1.859375,
        0.080078125,
        ...
        -0.20507812,
        0.71875,
        -0.15234375,
        0.734375,
        1.15625
      ],
      [
        -0.859375,
        -1.1875,
        -0.37890625,
        1.8828125,
        0.00024414062,
        ...
        -0.41992188,
        1.0703125,
        -1.0546875,
        0.66796875,
        0.29296875
      ]
    ]
  ]
]
<class 'pyarrow.lib.ChunkedArray'>
<class 'list'>
<class 'pyarrow.lib.ChunkedArray'>
```

### Component(s)

C++, Python

**Comment by js8544** [comment]
Hi, `col` is of type ChunkedArray, not ListArray. So the code you pasted calls [flatten of ChunkedArray](https://arrow.apache.org/docs/python/generated/pyarrow.ChunkedArray.html#pyarrow.ChunkedArray.flatten), which returns a list of chunked arrays.

**Comment by XinyuZeng** [comment]
My bad, Thank you @js8544  !
