### ISSUE TITLE
[Python] Improve usability of pc.map_lookup / MapLookupOptions

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#36045]
Trying to use `pc.map_lookup` today, I noticed some minor usability issues that could be improved:

```
arr = pa.array([{'a': 'a1', 'b': 'b1'}, {'a': 'a2', 'b': 'b2'}, {'a': 'a1', 'b': 'b3'}], 
               type=pa.map_(pa.string(), pa.string()))
```

1\. Passing the key value as a python string instead of scalar errors:

```
# works fine
>>> pc.map_lookup(arr, pa.scalar("a"), "all")
<pyarrow.lib.ListArray object at 0x7f099d2fabc0>
[
  [
    "a1"
  ],
  [
    "a2"
  ],
  [
    "a1"
  ]
]

# gives confusing error
>>> pc.map_lookup(arr, "a", "all")
...
ArrowInvalid: map_lookup: query_key can't be empty.
```

If not passing a Scalar object, we should probably just pass the python value to `pa.scalar(..)` for convenience.

2\. Allow to specify the `occurence` keyword, given that this is not necessarily obvious, it's nice to be able to specify the named argument:

```
>>> pc.map_lookup(arr, pa.scalar("a"), occurence="first")
...
TypeError: __init__() takes exactly 3 positional arguments (2 given)
```

I suppose we need to give it a default value for this, though (to make our auto-generation work, or we can look into improving the autogeneration of the signature)

**Comment by jorisvandenbossche** [comment]
> Wondering if we can provide a better error message in that case, but that might just be a Python/cython behaviour of first checking the positional keywords before the named ones)

Yes, that's a cython issue -> https://github.com/cython/cython/issues/1281

**Comment by R-JunmingChen** [comment]
> 1. Passing the key value as a python string instead of scalar errors:
So, we should only handle the issue one. I can make a quick implementation for it

**Comment by R-JunmingChen** [comment]
take
