### ISSUE TITLE
[JS] Require Node.js 18 or later

### ISSUE THREAD

**Issue by kou** [apache/arrow#36055]
### Describe the enhancement requested

https://github.com/nodejs/release#release-schedule says that Node.js 16 will reach EOL on 2023-09-11.

Our JavaScript related CI jobs use Node.js 16:
* https://github.com/apache/arrow/blob/main/.github/workflows/js.yml
* #36025

Should we use Node.js 18 instead of 16?

@domoritz What do you think about this?

### Component(s)

JavaScript

**Comment by domoritz** [comment]
I already use newer node versions locally without issues so we should update the CI.

**Comment by kou** [comment]
@abetomo Do you want to work on this?

**Comment by abetomo** [comment]
take
