### ISSUE TITLE
Likely LICENSE.txt should be updated.

### ISSUE THREAD

**Issue by rip-nsk** [apache/arrow#3611]
Should https://github.com/apache/parquet-cpp/blob/master/LICENSE.txt be merged with it?

**Comment by xhochy** [comment]
Yes, we should add https://github.com/apache/parquet-cpp/blob/642da055adf009652689b20e68a198cffb857651/LICENSE.txt#L204-L276 to the top-level `LICENSE.txt`. Can you make a JIRA/PR for this?

**Comment by wesm** [comment]
Several entries in that file are no longer relevant (they weren't merged, or they're already reflected in the LICENSE)

**Comment by rip-nsk** [comment]
https://issues.apache.org/jira/browse/ARROW-4546

**Comment by fsaintjacques** [comment]
Resolved, I think the issue can be closed here.
