### ISSUE TITLE
[C++] Refactor dict_internal.h to use Result

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#36111]
### Describe the enhancement requested

`DictionaryTraits<>::GetDictionaryArrayData` still uses the `Status(out ptr)` pattern instead of returning `Result<Out>`, which is less readable.

### Component(s)

C++

**Comment by infdahai** [comment]
I'd like to task this task.

**Comment by bkietz** [comment]
If you write a PR, @mention me and I'll review

**Comment by chrisjordansquire** [comment]
@bkietz  - I made a PR for this issue at https://github.com/apache/arrow/pull/37754 . I'm unsure if I correctly interpreted the task. Feedback greatly appreciated.
