### ISSUE TITLE
[C#] Support schema and field metadata in the C Data Interface

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#36120]
### Describe the enhancement requested

.NET support for import and export of schemas over the C data interface was added in #33856, but metadata in fields and schemas is currently ignored.

I'm happy to take a look at this unless this is something @wjones127 or @CurtHagenlocher was already planning on doing?

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Ask and ye shall receive.

**Comment by wjones127** [comment]
I don't have plans do work on this, but happy to review a PR for it!

**Comment by adamreeve** [comment]
That was quick, thanks @CurtHagenlocher!
