### ISSUE TITLE
[C++] Installation on Raspberry Pi 4 fails

### ISSUE THREAD

**Issue by starsnpixel** [apache/arrow#36135]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi, I'm trying to install arrow on my Raspberry Pi 4. After running into some issues following the official guideline on https://arrow.apache.org/docs/developers/python.html#building-on-linux-and-macos at `make -j4`
So I tried `make clean && make` provided in #35470 which to some extend seemed to be helping in that case. However, I run into an error at 29 %, see [output.txt](https://github.com/apache/arrow/files/11776359/output.txt) for the full details. 

If I re-run `make -j4`, it's leads to the same error as depicted above (though it's a different one than the one I had before). I'm a bit lost as I followed the official instructions and still it doesn't work out for some reason.

Any help would be extremely welcome. 

### Component(s)

Python

**Comment by cyb70289** [comment]
Do you have xsimd package installed on your system? Maybe the version is too low? `make_sized_batch_t` is added in xsimd-8.1.

**Comment by kou** [comment]
`-Dxsimd_SOURCE=BUNDLED` will fix the build error when the problem is caused by old xsimd.

If it doesn't fix the problem, could you provide the `cmake ...` output too?

**Comment by starsnpixel** [comment]
Sorry, newbie here, was that correct?
```
cmake -Dxsimd_SOURCE=BUNDLED \
	-DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Debug \
        -DARROW_BUILD_TESTS=ON \
        -DARROW_COMPUTE=ON \
        -DARROW_CSV=ON \
        -DARROW_DATASET=ON \
        -DARROW_FILESYSTEM=ON \
        -DARROW_HDFS=ON \
        -DARROW_JSON=ON \
        -DARROW_PARQUET=ON \
        -DARROW_WITH_BROTLI=ON \
        -DARROW_WITH_BZ2=ON \
        -DARROW_WITH_LZ4=ON \
        -DARROW_WITH_SNAPPY=ON \
        -DARROW_WITH_ZLIB=ON \
        -DARROW_WITH_ZSTD=ON \
        -DPARQUET_REQUIRE_ENCRYPTION=ON \
        ..
```
Unfortunately, this doesn't work, output is here: 
[log.txt](https://github.com/apache/arrow/files/11780089/log.txt)

**Comment by kou** [comment]
Yes.

OpenSSL is missing. You need to install `libssl-dev`.

**Comment by starsnpixel** [comment]
Thank you, that helped indeed! As a combination of what you recommended here and in #35470, I now used 

```
cmake -Dxsimd_SOURCE=BUNDLED \
	-DARROW_CXXFLAGS=-march=native \
	-DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Debug \
        -DARROW_BUILD_TESTS=ON \
        -DARROW_COMPUTE=ON \
        -DARROW_CSV=ON \
        -DARROW_DATASET=ON \
        -DARROW_FILESYSTEM=ON \
        -DARROW_HDFS=ON \
        -DARROW_JSON=ON \
        -DARROW_PARQUET=ON \
        -DARROW_WITH_BROTLI=ON \
        -DARROW_WITH_BZ2=ON \
        -DARROW_WITH_LZ4=ON \
        -DARROW_WITH_SNAPPY=ON \
        -DARROW_WITH_ZLIB=ON \
        -DARROW_WITH_ZSTD=ON \
        -DPARQUET_REQUIRE_ENCRYPTION=ON \
        ..
```
and it worked smoothlessly. However, with `make -j4` I now run into the following issue:
[log_j4.txt](https://github.com/apache/arrow/files/11780900/log_j4.txt)

**Comment by cyb70289** [comment]
This is strange. What's your compiler? gcc-7.1?
A quick workaround is to skip xsimd code with `cmake -DARROW_SIMD_LEVEL=NONE`. It disables explicit simd (neon) optimizations.

**Comment by starsnpixel** [comment]
`gcc --version` says it's version 8.3.0.

Using `-DARROW_SIMD_LEVEL=NONE` instead of `-Dxsimd_SOURCE=BUNDLED` actually led to a reboot of Raspberry Pi in the first attemp (for some unknown reason) but I just re-run it again and it worked, I can't believe it! I have yet to try to use it but the remaining steps didn't lead to any fatal errors either, so I'm confident! Thank you so much!

**Comment by starsnpixel** [comment]
Unfortunately, I have to reopen this issue. I don't get it. I don't get any errors anymore until the end of the process destribed in https://arrow.apache.org/docs/developers/python.html#building-on-linux-and-macos, including the last paragraph 
```
pushd arrow/python
export PYARROW_WITH_PARQUET=1
export PYARROW_WITH_DATASET=1
export PYARROW_PARALLEL=4
python setup.py build_ext --inplace
popd
```

However, if I try to make us of it, I still get the error `Missing optional dependency 'pyarrow'.  Use pip or conda to install pyarrow` ...

**Comment by kou** [comment]
Could you show all log?

**Comment by starsnpixel** [comment]
Okay, I've rerun everything and the following file contains the complete log of all the commands listed on [the official website](https://arrow.apache.org/docs/developers/python.html#building-on-linux-and-macos) from `git clone https://github.com/apache/arrow.git` till `make install`:  
[log_all.txt](https://github.com/apache/arrow/files/11886840/log_all.txt)

Interestingly, for the very last command `python setup.py build_ext --inplace`, this time I receive the following error message: 
```
File "setup.py", line 251
    print(f"-- Skipping build. Temp build {build_temp} does "
                                                            ^
SyntaxError: invalid syntax
```
Line 251 & 252 in setup.py are
`print(f"-- Skipping build. Temp build {build_temp} does "
                          f"not match cached dir {cachedir}")`

Something else that I realized with a different module: My code did not recognize it after `pip install _module_` (although installation was successful) but after `pip3 install _module_` - do I need to change something about the pyarrow code as well?

**Comment by cyb70289** [comment]
What's your python version?

**Comment by starsnpixel** [comment]
I have both 2.7.16 and 3.7.3 on my system (preinstalled). I'm going to try to upgrade it and see if that helps. Thanks!

**Comment by cyb70289** [comment]
Looks the default is python2 ?
Suggest setup a virtualenv with python3.

**Comment by starsnpixel** [comment]
> Suggest setup a virtualenv with python3.
Doesn't the line `python3 -m venv pyarrow-dev` do exactly this? I upgraded to Python 3.11 but the line 251 issue still occurs.

**Comment by cyb70289** [comment]
TBH, I don't know what's happening.
Looks to me the only possiblility might cause line 251 syntax error is you are using python2.
