### ISSUE TITLE
[C++][Parquet] StreamReader::SkipRows() skips to wrong spot in files containing multiple row groups

### ISSUE THREAD

**Issue by KarateSnowMachine** [apache/arrow#36189]
### Describe the bug, including details regarding any error messages, version, and platform.

The issue arises due to a simple arithmetic error when calculating the offset from the current row group. As far as I can tell this affects all platforms and the bug has existed since the introduction of the StreamReader skip code in https://github.com/apache/arrow/commit/56adb6a7ecd5f189f03f4a73a6df1c9a2af1eeb0 

I will submit a PR with a unit test case and proposed fix shortly. 

### Component(s)

C++

**Comment by KarateSnowMachine** [comment]
OK, maybe I didn't read the contributing guidelines correctly but I wasn't successful in getting my PR to automatically reference this issue. It is here: https://github.com/apache/arrow/pull/36191

**Comment by wgtmac** [comment]
> OK, maybe I didn't read the contributing guidelines correctly but I wasn't successful in getting my PR to automatically reference this issue. It is here: #36191

The PR title has to be started with `GH-XXX` to link it to correct issue.

**Comment by KarateSnowMachine** [comment]
> > OK, maybe I didn't read the contributing guidelines correctly but I wasn't successful in getting my PR to automatically reference this issue. It is here: #36191
> 
> The PR title has to be started with `GH-XXX` to link it to correct issue.

Should I submit a patch for the contributing guide, which says the issue should be named ARROW-XXX or PARQUET-XXXX? 
https://github.com/apache/arrow/blob/main/.github/CONTRIBUTING.md?plain=1#L61

**Comment by wgtmac** [comment]
> > > OK, maybe I didn't read the contributing guidelines correctly but I wasn't successful in getting my PR to automatically reference this issue. It is here: #36191
> > 
> > 
> > The PR title has to be started with `GH-XXX` to link it to correct issue.
> 
> Should I submit a patch for the contributing guide, which says the issue should be named ARROW-XXX or PARQUET-XXXX? https://github.com/apache/arrow/blob/main/.github/CONTRIBUTING.md?plain=1#L61

Yes, that would be great!
