### ISSUE TITLE
[Python][CI] Update spark versions tested on our nightly tests

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#36199]
### Describe the enhancement requested

It does seem we are using some pretty old and deprecated spark versions on our CI nightly integration builds with spark.
As discussed on this PR comment discussion: https://github.com/apache/arrow/pull/36061#discussion_r1230266720

The following comments were added:

Do we still need Spark 3.1.2?

I think that Spark 3.1 reached EOL:

https://spark.apache.org/versioning-policy.html

>    Feature release branches will, generally, be maintained with bug fix releases for a period of 18 months.

And 3.1.1 was released on 2021-03-02:

https://spark.apache.org/news/index.html

>    [Spark 3.1.1 released](https://spark.apache.org/news/spark-3-1-1-released.html)
>    March 2, 2021

3.2 might reach EOL because 3.2.0 was released on 2021-10-13:

>    [Spark 3.2.0 released](https://spark.apache.org/news/spark-3-2-0-released.html)
>    October 13, 2021

### Component(s)

Continuous Integration, Python

**Comment by raulcd** [comment]
@kiszk do you know what are the versions we should be testing?

**Comment by kiszk** [comment]
You are right. [This](https://spark.apache.org/versioning-policy.html) (at the bottom) is the maintenance policy. For 18 months from the release. Based on the policy, the current active Sparks are 3.2.x, 3.3.x, and 3.4.x. 

Spark 3.2.x will be retired soon. 
> [Spark 3.2.0 released](https://spark.apache.org/news/spark-3-2-0-released.html)
> October 13, 2021

Spark 3.5 will be released after this summer
> August 2023 | Release candidates (RC), voting, etc. until final release passes

So, my suggestion is to test Spark 3.4.0.
