### ISSUE TITLE
PyArrow append row to an Array

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#3622]
Is it possible to append a row to an Array (of arbitrary type) in a zero copy fashion?

Im thinking something along the lines of:

```python
a = Array([[1,1],[2,2],[3,3]])
a.append([4,4])
print(a)
>>> pa.Array([[1,1],[2,2],[3,3],[4,4]])
```

**Comment by xhochy** [comment]
Append in a zero-copy fashion to an Array is not possible as Arrow Arrays are immutable. We have `ArrayBuilder` classes in Arrow that support constructing arrays on an element-wise basis. They are not yet exposed to Python though: https://issues.apache.org/jira/browse/ARROW-3917

In general, zero-copy extension with pure Python objects will never be possible. Arrow is a language-independent in-memory structure, thus we cannot store language specific objects in the arrays. This can be possible in some cases though for data structures like NumPy arrays that are only a thin wrapper around native structure like integer arrays.

**Comment by wesm** [comment]
@dmadeka the way we build datasets without copying is using chunked arrays

**Comment by dmadeka** [comment]
@wesm Is there an example of that? Im not sure which method in `ChunkedArray` I'd use
