### ISSUE TITLE
[Python] Refactor CumulativeSumOptions to a separate class for independent deprecation

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#36240]
### Describe the enhancement requested

CumulativeSumOptions are renamed to CumulativeOptions in https://github.com/apache/arrow/pull/36020 after the introduction of cumulative functions other than `cumulative_sum` which reuse those options. For backward compatibility, [an alias](https://github.com/apache/arrow/pull/36020/commits/c61d6cf2df5a7c83a8aa4cbf51ed01c5d18165b6#diff-3d08757408024228c4443730cc3536ab39c9436cd2e4cb63e5da34c69c18962fR37) was added so that the name CumulativeSumOptions is still usable. However [per discussion on that PR](https://github.com/apache/arrow/pull/36020#discussion_r1238433064) the old name should be deprecated, which requires an explicit separate class.

### Component(s)

Python

**Comment by R-JunmingChen** [comment]
Hi, I am not sure I am understand well. It seems that what we need to do is copy-paste `CumulativeOptions` and rename it to `CumulativeSumOptions`?

**Comment by R-JunmingChen** [comment]
take
