### ISSUE TITLE
[CI] docs-preview jobs failing with error "fatal error: can’t write PCH file: No space left on device"

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#36258]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm running the docs-preview CI job on a [PR I'm working on](https://github.com/apache/arrow/pull/36171/), but I'm repeatedly getting errors which refer to insufficient space, e.g. https://github.com/ursacomputing/crossbow/actions/runs/5347622626/jobs/9696366020#step:6:7646

### Component(s)

Continuous Integration

**Comment by kou** [comment]
Duplicated: #36200
