### ISSUE TITLE
[Docs][Format] DenseUnion example in documentation 

### ISSUE THREAD

**Issue by sdachen** [apache/arrow#36279]
### Describe the bug, including details regarding any error messages, version, and platform.

In the [documentation](https://arrow.apache.org/docs/format/Columnar.html), the DenseUnion example has 4 elements, 2 float, 1 null, and 1 integer. 

In the `types` buffer, the null element is indicated as a float. In the float child array, there are 3 elements, 1.2, null, and 3.4, but the `Length` property says 2. Should it be 3 instead given the value buffer contains 12 bytes?

* Length: 4, Null count: 0
* Types buffer:

  |Byte 0   | Byte 1      | Byte 2   | Byte 3   | Bytes 4-63  |
  |---------|-------------|----------|----------|-------------|
  | 0       | 0           | 0        | 1        | unspecified |

* Offset buffer:

  |Bytes 0-3 | Bytes 4-7   | Bytes 8-11 | Bytes 12-15 | Bytes 16-63 |
  |----------|-------------|------------|-------------|-------------|
  | 0        | 1           | 2          | 0           | unspecified |

* Children arrays:
  * Field-0 array (f: Float32):
    * Length: 2, Null count: 1
    * Validity bitmap buffer: 00000101

    * Value Buffer:

      | Bytes 0-11     | Bytes 12-63  |
      |----------------|-------------|
      | 1.2, null, 3.4 | unspecified |

  * Field-1 array (i: Int32):
    * Length: 1, Null count: 0
    * Validity bitmap buffer: Not required

    * Value Buffer:

      | Bytes 0-3 | Bytes 4-63  |
      |-----------|-------------|
      | 5         | unspecified |

### Component(s)

Documentation

**Comment by kou** [comment]
Good catch! Could you open a pull request for this?

**Comment by sdachen** [comment]
Looks like it's already fixed - just need to refresh the docs. https://github.com/apache/arrow/commit/fe48403651e51e241802fef05984efc37f10a4fc

**Comment by kou** [comment]
OK. Then I close this as duplicated of #35887.

We can see the rendered document of the main branch at https://arrow.apache.org/docs/dev/
e.g.: https://arrow.apache.org/docs/dev/format/Columnar.html#union-layout
