### ISSUE TITLE
UMD erroneously declares dependencies on “Arrow” package.

### ISSUE THREAD

**Issue by mbostock** [apache/arrow#3629]
It seems that the UMD file in 0.4.0 erroneously declares a dependency on the “Arrow” package:

https://cdn.jsdelivr.net/npm/apache-arrow@0.4.0/Arrow.es5.min.js

It seems to be coming from here:

https://github.com/apache/arrow/blob/af60c2e730236cfbbd207e1c0bd655bbb230bae1/js/gulp/closure-task.js#L111

**Comment by kou** [comment]
Could you open an issue on JIRA https://issues.apache.org/jira/browse/ARROW ?
