### ISSUE TITLE
[Python] Repr of Timestamp scalars error if they are outside range of stdlib datetime.datetime

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#36323]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently, the repr of the TimestampScalar (well, of scalars in general) essentially uses the repr of the Python object. For TimestampScalar, this thus fails if this conversion fails, such as for timestamps that are outside of the range of `datetime.datetime` ([1-9999]):

```
>>> res = pa.scalar("0000-01-01").cast(pa.timestamp("s"))
>>>type(res)
pyarrow.lib.TimestampScalar
>>> repr(res)
...
File ~/miniconda3/envs/dev39/lib/python3.9/site-packages/pyarrow/scalar.pxi:117, in pyarrow.lib.Scalar.__repr__()

File ~/miniconda3/envs/dev39/lib/python3.9/site-packages/pyarrow/scalar.pxi:521, in pyarrow.lib.TimestampScalar.as_py()

File ~/miniconda3/envs/dev39/lib/python3.9/site-packages/pyarrow/scalar.pxi:437, in pyarrow.lib._datetime_from_int()

OverflowError: date value out of range

>>> pc.strftime(res)
<pyarrow.StringScalar: '0000-01-01T00:00:00'>
```

Our generic Scalar `__repr__` implementation:

https://github.com/apache/arrow/blob/11b140a734a516e436adaddaeb35d23f30dcce44/python/pyarrow/scalar.pxi#L117-L120

I think for Timestamps we should just convert to a string repr ourselves (`strftime`, or our own pretty printer as is used for the Array repr)

### Component(s)

Python

**Comment by anjakefala** [comment]
You can write 'take' into a comment body to assign yourself =) https://github.com/apache/arrow/blob/e5de6a59f410a3255cc84138b44fc5802b627afc/.github/workflows/comment_bot.yml#L178

I will add this to the documentation: https://arrow.apache.org/docs/dev/developers/guide/step_by_step/finding_issues.html

**Comment by aboss123** [comment]
take

**Comment by raulcd** [comment]
@jorisvandenbossche should this be a blocker for 13.0.0 or can I move it to 14.0.0?
