### ISSUE TITLE
[C++][CI] Sporadic errors in `arrow-acero-asof-join-node-test`

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#36331]
### Describe the bug, including details regarding any error messages, version, and platform.

Various errors seem to occur intermittently on CI.

One example:
```
[ RUN      ] AsofJoinTest.BackpressureWithBatchesGen
/arrow/cpp/src/arrow/acero/asof_join_node_test.cc:1516: Failure
Value of: has_bp_been_applied()
  Actual: false
Expected: true
[  FAILED  ] AsofJoinTest.BackpressureWithBatchesGen (10693 ms)
```
from https://github.com/apache/arrow/actions/runs/5391899018/jobs/9789453616?pr=36215#step:6:3333

Another example:
[logs](https://gist.github.com/pitrou/d1814bde928d3b08fd29a923053a9ed0)
from https://github.com/apache/arrow/actions/runs/5376323460/jobs/9753323965#step:10:338 

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
@rtpsw @icexelloss

**Comment by icexelloss** [comment]
Thanks @pitrou - I noticed this the other day as well: https://github.com/apache/arrow/issues/36248

We can probably disable this test until we figure out how to make this more robust

**Comment by kou** [comment]
@rtpsw Could you add "take" only comment here to assign you to this issue?

**Comment by rtpsw** [comment]
take
