### ISSUE TITLE
[Ruby] Connecting to Arrow Ballista using Flight SQL from Ruby program (implement Red Arrow Flight SQL)

### ISSUE THREAD

**Issue by collimarco** [apache/arrow#36348]
### Describe the enhancement requested

The Apache Arrow Ballista project (https://github.com/apache/arrow-ballista) requires the Flight SQL protocol for communications. 

Basically you need the Flight SQL protocol if you want to send a SQL query from a Ruby program to an instance of Arrow Ballista (e.g. running in Docker or Kubernetes).

I see that you already started this project for Ruby:
https://github.com/apache/arrow/tree/main/ruby/red-arrow-flight-sql

However there isn't any example of usage and the project seems empty / incomplete.

How can you interact with Arrow Ballista from Ruby? 
Are there any plans to complete the `red-arrow-flight-sql` gem?

### Component(s)

Ruby

**Comment by kou** [comment]
The following code should work but there is a problem (#36369) for now:

```ruby
require "arrow-flight-sql"

call_options = ArrowFlight::CallOptions.new
client = ArrowFlight::Client.new("grpc://127.0.0.1:50050")
client.authenticate_basic("admin", "password", call_options)
sql_client = ArrowFlightSQL::Client.new(client)

info = sql_client.execute("SELECT 'hello'", call_options)
endpoint = info.endpoints.first
reader = sql_client.do_get(endpoint.ticket, call_options)
table = reader.read_all
p table
```

We should be able to use ADBC too:

```ruby
require "adbc"

options = {
  "driver" => "adbc_driver_flightsql",
  "uri" => "grpc://127.0.0.1:50050",
  "username" => "admin",
  "password" => "password",
}
ADBC::Database.open(**options) do |database|
  database.connect do |connection|
    connection.open_statement do |statement|
      table, _n_rows_affected = statement.query("SELECT 'hello'")
      p table
    end
  end
end
```

But it also doesn't work for now...

**Comment by kou** [comment]
This should work now.
