### ISSUE TITLE
[Python][CI] GCFS python tests fail due to updated version of google-cloud-cpp

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#36352]
### Describe the bug, including details regarding any error messages, version, and platform.

As discussed here:
https://github.com/apache/arrow/pull/36119#issuecomment-1611147978

*originally from @raulcd *
I am unsure if there's something else to be done but it seems the nightlies for:
* [test-debian-11-python-3](https://github.com/ursacomputing/crossbow/runs/14609701083)
* [test-fedora-35-python-3](https://github.com/ursacomputing/crossbow/runs/14608852519)

Failed with:
```
E   pyarrow.lib.ArrowInvalid: google::cloud::Status(INVALID_ARGUMENT: missing project id error_info={reason=INVALID_ARGUMENT, domain=gcloud-cpp, metadata={gcloud-cpp.source.function=CreateBucket, gcloud-cpp.source.line=402, gcloud-cpp.source.filename=/build/cpp/google_cloud_cpp_ep-install/include/google/cloud/storage/client.h, gcloud-cpp.version=v2.12.0}}). Detail: [errno 22] Invalid argument
```
Is there something else to be done? Should I create a new issue for those failures?

and 
*originally from @raulcd *
No worries, from my understanding we have to add the new `project_id` to our `GcsFileSystem` constructor:
https://github.com/apache/arrow/blob/main/python/pyarrow/_gcsfs.pyx#L83-L89
And adding that to the underlying `CGcsOptions`.
We migt have to update the `__reduce__` function on that file and update the tests on `python/pyarrow/tests/test_fs.py`:
https://github.com/apache/arrow/blob/main/python/pyarrow/tests/test_fs.py#L211
I'll create an issue

### Component(s)

Continuous Integration, Python

**Comment by kou** [comment]
Oh, sorry. I missed it.

**Comment by raulcd** [comment]
@kou does this change mean we should require a mandatory project_id when creating a `GcsFileSystem`?
