### ISSUE TITLE
[C++] Bundled GTest CI jobs seem to `#include`ing GTest headers from somewhere else

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#36379]
### Describe the bug, including details regarding any error messages, version, and platform.

In https://github.com/apache/arrow/pull/36334 I saw link errors in some CI jobs which build bundled GTest:

- [AMD64 manylinux2014 Java JNI](https://github.com/apache/arrow/actions/runs/5404201925/jobs/9818060319?pr=36334#step:6:2663)
- [AMD64 macOS 12 C++](https://github.com/apache/arrow/actions/runs/5404201927/jobs/9818061642?pr=36334#step:9:1282)

The symbol which is undefined is the internal [FormatMatcherDescription](https://github.com/google/googletest/blame/687c589949eaf8734484491a6882a7fc56aebc12/googlemock/include/gmock/gmock-matchers.h#L3875) function. That function is present in the bundled version of GTest (v1.11), but its signature [is different in that version](https://github.com/google/googletest/blob/release-1.11.0/googlemock/include/gmock/gmock-matchers.h#L3705).

This suggests that somehow although we're building GTest v1.11 the tests are `#include`ing headers from a more recent version of GTest and we just haven't noticed before now.

### Component(s)

C++

**Comment by lidavidm** [comment]
FWIW, that pipeline also installs GTest via Homebrew. We've seen similar issues before when we had both Conda-installed and bundled GTest in the same build (because we stuck the Conda include directory early on in the search path).

**Comment by bkietz** [comment]
The same link error occurs on the [manylinux JNI](https://github.com/apache/arrow/actions/runs/5404201925/jobs/9818060319?pr=36334#step:6:2663) job. I'll update the description with a more informative listing of the link errors

**Comment by bkietz** [comment]
The problem is actually more subtle: when the dependency's source is AUTO, ThirdpartyToolchain.cmake checks for a compatible system package. If the system package is not compatible, it will build a bundled version. https://github.com/apache/arrow/blob/ad7f6ef3a97be6a3eb6fe37d0df1b1634db057d2/cpp/cmake_modules/ThirdpartyToolchain.cmake#L287-L292

Building the bundled dependency adds its include directories... but it *appends them* so include directories which are already added have precedence. In this case the incompatible gtest headers from the conda environment are not being overridden by the bundled headers. It should be sufficient to use `target_include_directories()` with the `BEFORE` keyword to ensure that bundled projects' headers can override system headers

**Comment by bkietz** [comment]
I'm not sure how this interacts with https://github.com/apache/arrow/pull/37483 yet. Among other things bundled gtest is no longer built as an ExternalProject. I'll open a PR using target_include_directories+BEFORE for the dependencies which still are ExternalProjects

**Comment by bkietz** [comment]
Nevermind, FetchContent_MakeAvailable does produce an ExternalProject.
