### ISSUE TITLE
[JS] Setting value of row in table with strings truncates longer strings

### ISSUE THREAD

**Issue by csjh** [apache/arrow#36395]
### Describe the bug, including details regarding any error messages, version, and platform.

```js
const table = tableFromJSON([{ name: "Bill" }, { name: "Samantha" }]);
table.set(0, table.get(1));
// table.get(0).name is now "Sama"
```
On version 11.0.0, MacOS 13.14

I'm not 100% sure that this isn't the intended behaviour, but better safe than sorry. The behaviour I would expect is for `table.get(0)` to be identical to `table.get(1)`.

### Component(s)

JavaScript

**Comment by domoritz** [comment]
This is a bit surprising but also expected. The memory for the variable width strings is allocated in one block so writing different content in that memory with `set` will not work correctly. In general, Arrow data structures are optimized for reading and if you need to make changes, you are better off making a new data structure. Supporting write here would mean we need to move all the memory for the strings in the vector around. 

If you only have a limited number of strings, you can use a dictionary and then re-assigning a value should work. 

Closing as working as expected for now.
