### ISSUE TITLE
[C++][CI] test_gdb fails on nightly job test-cuda-python

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#36449]
### Describe the bug, including details regarding any error messages, version, and platform.

[test-cuda-python](https://github.com/ursacomputing/crossbow/actions/runs/5449601863/jobs/9913998035) fails on `test_gdb` for several tests. All errors seem to not be able to match the type, like:

```
     def check_stack_repr(gdb, expr, expected):
        """
        Check printing a stack-located value.
        """
        s = gdb.print_value(expr)
        if isinstance(expected, re.Pattern):
            assert expected.match(s), s
        else:
>           assert s == expected
E           AssertionError: assert '<incomplete type>' == 'arrow::null()'
E             - arrow::null()
E             + <incomplete type>
```

### Component(s)

Continuous Integration, Python

**Comment by raulcd** [comment]
@pitrou any idea who might be able to take a look at this one?

**Comment by pitrou** [comment]
Either @kou or me.

**Comment by kou** [comment]
Yes. I know how to solve this. This is related to #36230. We should not use `-g1` for jobs that run `test_gdb`. Sorry. I missed this case.

I'll open a pull request for this.
