### ISSUE TITLE
[CI][Python] NumPy deprecation warnings in test_cuda.py (test-cuda-python nightly build)

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#36455]
In the [test-cuda-python](https://github.com/ursacomputing/crossbow/actions/runs/5449601863/jobs/9913998035) nightly build, there are a whole set of identical warnings, like:

```
usr/local/lib/python3.8/dist-packages/pyarrow/tests/test_cuda.py::test_copy_from_to_host[1000]
  /usr/local/lib/python3.8/dist-packages/pyarrow/tests/test_cuda.py:359: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
  For the old behavior, usually:
      np.array(value).astype(dtype)`
  will give the desired result (the cast overflows).
    arr[:] = range(size)
```

cc @danepitkin 

(in addition, there are also test failures, but that is due to https://github.com/apache/arrow/issues/36449)

**Comment by raulcd** [comment]
This seems to be worked on here: https://github.com/apache/arrow/pull/36453#issuecomment-1620193210
