### ISSUE TITLE
[R] no applicable method for 'drop_na' applied to an object of class "arrow_dplyr_query"

### ISSUE THREAD

**Issue by kbzsl** [apache/arrow#36458]
### [R] Describe the usage question you have. Please include as many useful details as  possible.

The `tidyr::dropna()` function is not available in [Arrow `dplyr` queries](https://arrow.apache.org/docs/dev/r/reference/acero.html).

Can you recommend a workaround for the dropna? 
The goal is to run on the Arrow compute level, without loading the data in the memory.

Thank you.

### Component(s)

R

**Comment by eitsupi** [comment]
We can use `dplyr::filter` with `dplyr::across` for this use case.

``` r
df <- data.frame(a = 1:3, b = c("a", NA, "c"))

df |>
  arrow::as_arrow_table() |>
  dplyr::filter(dplyr::across(everything(), ~ !is.na(.))) |>
  dplyr::collect()
#>   a b
#> 1 1 a
#> 2 3 c
```

<sup>Created on 2023-07-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Note that this is why dbplyr does not implement drop_na either. tidyverse/dbplyr#999

Related issue tidyverse/tidyr#939

**Comment by kbzsl** [comment]
Thank you.

**Comment by eitsupi** [comment]
I'm wondering this can be closed.

**Comment by kbzsl** [comment]
> I'm wondering this can be closed.

I'm OK with that.
