### ISSUE TITLE
[Java] mavencentral jars do not ship with libarrow_cdata_jni binding for linux/aarch64

### ISSUE THREAD

**Issue by jonathanswenson** [apache/arrow#36469]
### Describe the bug, including details regarding any error messages, version, and platform.

Attempting to use the CData interface from java on linux/aarch64 fails with an exception on recent versions when using the maven central distributions: 

`java.lang.IllegalStateException: error loading native libraries: java.io.FileNotFoundException: aarch_64/libarrow_cdata_jni.so`

Works just fine on mac (m1). 

Appears the mavencentral distribution does not include the `.so` file for aarch64 (it does for x86). 

<img width="537" alt="image" src="https://github.com/apache/arrow/assets/2752979/15fae2c7-4ea9-4208-8a8d-54b4d1f71f8c">

Looks gandiva and dataset jars on mavencentral also do not have distributions with these.

### Component(s)

Java

**Comment by kou** [comment]
We need to build aarch64 binaries by https://github.com/apache/arrow/blob/947a446c51b685debaf1a19e7c5f91e8e0bd09e4/dev/tasks/java-jars/github.yml#L24-L50

We can use self-hosted aarch64 runner for it: https://github.com/apache/arrow/blob/947a446c51b685debaf1a19e7c5f91e8e0bd09e4/dev/tasks/linux-packages/github.linux.yml#L28

**Comment by jonathanswenson** [comment]
Took a stab at this here: https://github.com/apache/arrow/pull/36487. 

My main concern is pushing the Docker image for both aarch64 and x86, but I likely also do not fully understand the implications of everything I'm changing here.
