### ISSUE TITLE
Calling convention specifier incorrect for C#'s C data interface

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#36506]
### Describe the bug, including details regarding any error messages, version, and platform.

We specify the calling convention with:

```
internal delegate* unmanaged
#if !NET5_0_OR_GREATER
            [Stdcall]
#endif
            <CArrowArrayStream*, CArrowSchema*, int> get_schema;
```

Here is my understanding:

 * These functions are implemented in Arrow-C++  When we build Arrow-C++ we do not specify any calling convention (e.g. `/Gd, /Gr, /Gv, /Gz`) and therefore the default (`/Gd`) will be used which maps to `__cdecl`.
 * In the above, if we are < .NET 5.0 then it specifies `[Stdcall]`, which is wrong
 * In the above, if we are >= .NET 5.0 then it specifies the default, which will be `[Stdcall]` on Windows, which is wrong.

In practice, this doesn't affect us because this only matters on 32-bit machines

### Component(s)

C#

**Comment by westonpace** [comment]
CC @teo-tsirpanis @pitrou @CurtHagenlocher @eerhardt for second opinions.  I'm opening this issue so we can isolate this conversation (as it is not terribly important unless we know someone is using this kind of system) and proceed on the other PR (which has other, legitimate, fixes)

**Comment by teo-tsirpanis** [comment]
I can quickly change it to cdecl, before you merge the PR.
