### ISSUE TITLE
[C++][FlightRPC] Async Flight: GetFlightInfo implementation

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#36512]
### Describe the enhancement requested

This is a first step towards async Flight APIs. The first task will be to implement async GetFlightInfo (client-side) only, and work out the approach to client APIs. In follow-on tasks we will implement the rest of the metadata calls, then the data calls.

### Component(s)

C++, FlightRPC

**Comment by mdianjun** [comment]
Any plan to implement the rest APIs? @lidavidm

**Comment by lidavidm** [comment]
It's unlikely. I have not much time now and I would prefer to explore a situation that exposes the underlying gRPC APIs instead of trying to re-wrap them.
