### ISSUE TITLE
Installing on RHEL7 from source. 

### ISSUE THREAD

**Issue by BeamerIsHere** [apache/arrow#3654]
## GitHub Issues for Apache Arrow
Can Anyone help me with installing Arrow in RHEL7. From source or through repo. 

We support GitHub issues as a lightweight way to ask questions and engage with
the Arrow developer community. We use the Apache Software Foundation's JIRA
instance for maintaining a queue of development work and as the public record
for work on the project. So, feel free to delete this text and open an issue
here if you have a question or aren't sure whether something is a bug or
feature request. Any bugs, suggestions, or feature requests will eventually
need to end up in JIRA, either before or after completing a pull request.

See the Arrow JIRA project here: https://issues.apache.org/jira/browse/ARROW.

For more in-depth development discussions, please use the public mailing list
dev@arrow.apache.org (first subscribe by sending an e-mail to
dev-subscribe@arrow.apache.org).

**Comment by wesm** [comment]
Yes, follow the CentOS instructions on http://arrow.apache.org/install/. Please write on dev@arrow.apache.org if something doesn't work, or open a JIRA issue
