### ISSUE TITLE
[Java][CI] Set up Arrow Java support for JDK8 and JDK11+

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#36604]
### Describe the enhancement requested

Currently, Arrow Java is using JDK11 to compile the code, and it offers JDK8 support with [source/target 8](https://github.com/apache/arrow/blob/ea4f03ac166e3961b59f29f60dcd160fbed29894/java/pom.xml#L203-L207).

We will eventually need to compile with JDK11 and use source/target 11. The main challenge will be excluding clients that need to continue using JDK8.

The following are the options for moving to JDK11:

1. In order to continue offering support for JDK 8, cross-compile with JDK 11+ and package with release=8:
If we compile with --release=8, we will have trouble accessing sun.misc.Unsafe, which is not as exposed/public/documented (https://openjdk.org/jeps/247).

2. Discontinue support for JDK8.

3. **Set up Arrow Java flavors for JDK8 and JDK11+.**

-------

This enhancement consider the changes needed to implement the 3rd option mention above: **Set up Arrow Java flavors for JDK8 and JDK11+.**

1. New Arrow Java library should be offering support for JDK8 and JDK11+ throughout different maven artifacts (adding classifier support).

```
arrow-memory-core-15.0.0-SNAPSHOT.pom
arrow-memory-core-15.0.0-SNAPSHOT-tests.jar
arrow-memory-core-15.0.0-SNAPSHOT.jar
arrow-memory-core-15.0.0-SNAPSHOT-javadoc.jar
arrow-memory-core-15.0.0-SNAPSHOT-sources.jar
arrow-memory-core-15.0.0-SNAPSHOT-cyclonedx.json
arrow-memory-core-15.0.0-SNAPSHOT-cyclonedx.xml
arrow-memory-core-15.0.0-SNAPSHOT-jdk8tests.jar
arrow-memory-core-15.0.0-SNAPSHOT-jdk8.jar
```

2. New Arrow Java library should be offering default support for JDK11 (major version: 55) 

Java libraries by default will offer JDK11 support (major version: 55):
```
  <dependency>
    <groupId>org.apache.arrow</groupId>
    <artifactId>arrow-memory-core</artifactId>
    <version>15.0.0-SNAPSHOT</version>
  </dependency>
```
3. If the user need to use JDK8 as a mandatory, then they need to change from-to:

From:
```
  <dependency>
    <groupId>org.apache.arrow</groupId>
    <artifactId>arrow-memory-core</artifactId>
    <version>15.0.0-SNAPSHOT</version>
  </dependency>
```
To JDK8 (major version: 52):
```
<dependency>
  <groupId>org.apache.arrow</groupId>
  <artifactId>arrow-memory-core</artifactId>
  <version>15.0.0-SNAPSHOT</version>
  <classifier>jdk8</classifier>
</dependency>
```

### Component(s)

Continuous Integration, Developer Tools, Documentation, Java

**Comment by danepitkin** [comment]
Closing since we decided to consider deprecating Java 8 in the future.
