### ISSUE TITLE
[C++][Dev] ARROW_ACERO should be OFF by default in `ci/scripts/cpp_build.sh`

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#36610]
### Describe the bug, including details regarding any error messages, version, and platform.

As the title says. For some reason the CI C++ build script always enabled Acero by default...

(I also don't understand why it's enabled in the Ubuntu "minimal" builds)

### Component(s)

C++

**Comment by pitrou** [comment]
@kou

**Comment by kou** [comment]
It seems that the "minimal" means that "minimal" environment not "minimal" build.

**Comment by pitrou** [comment]
I see.
