### ISSUE TITLE
[JS] What is best practice for connecting to an arrow instance in javascript?

### ISSUE THREAD

**Issue by jay-bulk** [apache/arrow#36625]
### Describe the usage question you have. Please include as many useful details as  possible.

In the [javascript examples](https://github.com/apache/arrow/tree/main/js), it's mostly exhibited how one might connect if the arrow files are on fs or directly accessible. What is best practice for connecting to a remote arrow flight instance instance such as connecting a js app to use dremio?

### Component(s)

JavaScript

**Comment by domoritz** [comment]
Closing as there is no action item besides what we already have covered in other issues.

**Comment by jay-bulk** [comment]
I guess I should have been more specific. It would be nice to see a node library for this. I don't have the bandwidth to get that going and I'm not sure the community is asking for it (other than myself).

**Comment by domoritz** [comment]
You want an arrow flight server in node? That would be covered by https://github.com/apache/arrow/issues/17325

**Comment by jay-bulk** [comment]
I'm not disagreeing that this should be closed, mind you. I've abandoned direct use of arrow flight altogether. I use dremio (built on arrow flight) and instead of calling the arrow flight db directly the implementation goes through an ETL to a PostgresDB where I can use typescript without issue.
Thanks for following up. I'll follow up in the other thread if need be.
