### ISSUE TITLE
[Java] Upgrade Netty due to security vulnerability, please make a release package.

### ISSUE THREAD

**Issue by bi-kai** [apache/arrow#36639]
### Describe the bug, including details regarding any error messages, version, and platform.

PR has bean merged:
[Java] Upgrade Netty due to security vulnerability
https://github.com/apache/arrow/pull/36211

this issue leads to unavaliable, please make a release package.

@kou

### Component(s)

Java

**Comment by lidavidm** [comment]
As described on the PR, we are working on the next release already. The code freeze has passed and we are working on packaging.

**Comment by bi-kai** [comment]
> As described on the PR, we are working on the next release already. The code freeze has passed and we are working on packaging.

@lidavidm We need to release a software before july 17, which depends on arrow, do you have any idea of the time about the next version?

**Comment by kou** [comment]
We will release a new version after July 17 because we need at least 72 hours to verify RC.

See also: https://www.apache.org/legal/release-policy.html#release-approval
