### ISSUE TITLE
[R] Error with create_package_with_all_dependencies() on Windows

### ISSUE THREAD

**Issue by bpaull** [apache/arrow#36638]
### Describe the bug, including details regarding any error messages, version, and platform.

When using `create_package_with_all_dependencies()` On Windows 10 an error occur : 
**Error : '\U' not followed by heaxadecimal code in "C:\U"** 

This error come from `source(download_script)` line 38 and seem to be due to the path writen in the download script by `system2("bash", c(download_dependencies_sh,  download_dir), stdout = download_script, stderr = FALSE)`.
rewriting double backslash seem to solve the problem : 
`system2("bash", c(download_dependencies_sh, 
    gsub("\\", "/", download_dir, fixed = TRUE)), stdout = download_script, stderr = FALSE)`

### Component(s)

R

**Comment by thisisnic** [comment]
Thanks for reporting this @bpaull and for providing a solution as well.  As you've said, it looks like we need to be escaping the path properly on Windows.

**Comment by thisisnic** [comment]
Are you interested in submitting a PR @bpaull ? We always love to see new contributors to the project, and it sounds like this should be fairly straightforward for you to verify that your change has worked!
