### ISSUE TITLE
[R] Passing `NULL` through a function to `col_select` in `read_parquet()` results in no columns being returned 

### ISSUE THREAD

**Issue by Moohan** [apache/arrow#36658]
### Describe the bug, including details regarding any error messages, version, and platform.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp

path <- tempfile(fileext = ".parquet")

write_parquet(starwars, path)

custom_read <- function(path, col_select) {
   read_parquet(path, col_select = col_select)
}

custom_read(path, col_select = NULL)
#> Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
#> ℹ Please use `all_of()` or `any_of()` instead.
#>   # Was:
#>   data %>% select(col_select)
#> 
#>   # Now:
#>   data %>% select(all_of(col_select))
#> 
#> See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.
#> # A tibble: 87 × 0
```

<sup>Created on 2023-07-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Since the value of `col_select` is still `NULL` I would expect it to function as though I passed `NULL` (or nothing at all) directly `read_parquet(path, col_select = NULL)` (or `read_parquet(path)`).

### Component(s)

R

**Comment by thisisnic** [comment]
Hi @Moohan, my tidy eval brain is not fully fired up today, so I don't have a detailed explanation of why this works, but if I rewrite your function like this:

```
custom_read <- function(path, col_select) {
  read_parquet(path, col_select = !!col_select)
}

```

things work as expected. Does this solve the problem for you?

**Comment by thisisnic** [comment]
In effect, I think what is going on here is that you need to pass in the value of the `col_select` variable, rather than the variable itself.  The injection operator (`!!`) does this for you.  You can read more about it in the rlang docs: https://rlang.r-lib.org/reference/topic-inject.html#injecting-with-

**Comment by thisisnic** [comment]
I'm closing this ticket as it's not an Arrow bug, but happy to discuss further in this thread if any of that doesn't make sense!

**Comment by Moohan** [comment]
> Hi @Moohan, my tidy eval brain is not fully fired up today, so I don't have a detailed explanation of why this works, but if I rewrite your function like this:
> 
> ```
> custom_read <- function(path, col_select) {
>   read_parquet(path, col_select = !!col_select)
> }
> ```
> 
> things work as expected. Does this solve the problem for you?

Yep, that seems to fix things for me and is a much neater workaround than what I was currently using, which is basically this:
```R
if (is.null(col_select)) {
      read_parquet(path)
    } else {
      read_parquet(path, col_select = col_select)
    }
}
