### ISSUE TITLE
[C++] Use anonymous namespace in arrow/IPC/reader.cc

### ISSUE THREAD

**Issue by smahapatra1** [apache/arrow#36674]
### Describe the bug, including details regarding any error messages, version, and platform.

It is technically not a bug, but the following types and functions should be in in file scope:

IpcReadConext, BatchDataReadRequest, ArrayLoader,
DecompressBuffer(s), LoadRecordBatch*, GetCompression*,
ReadRecordBatchInternal,
GetInclusionMaskAndOutSchmea, UnpackSchemaMessage,
ReadDictionary, AsyncRecordBatchStreamReaderImpl,

### Component(s)

C++

**Comment by smahapatra1** [comment]
Please ignore- they are public functions

**Comment by westonpace** [comment]
I agree this would be a good idea.  Do you want to propose a PR?

**Comment by pegasas** [comment]
hi, @westonpace , @smahapatra1 , I am new here and would like to do this issue, would you like to assign  this to me?

**Comment by pegasas** [comment]
Hi， @westonpace , @smahapatra1 ,
I am new here and wants to contribute in arrow,
Would you please allow me to try this task?

**Comment by mfruttid** [comment]
I would like to contribute to this if that's fine

**Comment by smahapatra1** [comment]
Hi, I have no issues with you contributing. Thanks.
  
  
  
  
  
  
  

  
  
>

**Comment by pegasas** [comment]
Thanks, will raise PR for tracking

**Comment by pegasas** [comment]
Thanks @pitrou !
