### ISSUE TITLE
Please use the flatbuffers package

### ISSUE THREAD

**Issue by yurivict** [apache/arrow#3670]
see here: https://github.com/apache/arrow/blob/master/cpp/thirdparty/versions.txt#L56

```flatbuffers``` packages are available on all systems: https://repology.org/metapackage/flatbuffers/versions

**Comment by wesm** [comment]
Can you please open a JIRA issue and articulate your ask more precisely

**Comment by yurivict** [comment]
https://github.com/apache/arrow/issues/3668 should be sufficient.
