### ISSUE TITLE
[CI] Github bot fails to assign issue to PR creator

### ISSUE THREAD

**Issue by js8544** [apache/arrow#36711]
### Describe the bug, including details regarding any error messages, version, and platform.

The bot has been trying to assign me to the issue in PR #36667 multiple times, but failed to do so.

### Component(s)

Continuous Integration

**Comment by js8544** [comment]
I feel like it's a one-time bug because I don't see this in other PRs.

cc @raulcd

**Comment by js8544** [comment]
> I found that I cannot assign [GH-35942](https://github.com/apache/arrow/issues/35942) to you, maybe you didn't reply to that, or a bug in github, or just I'm not a committer...

Yeah I think only committers can do it. However the bot should have enough priviledge.

**Comment by raulcd** [comment]
@mapleFU has permissions to assign issues too. I cannot assign you the issue either, could be related to: https://github.com/apache/arrow/issues/34389
Can you comment on GH-35942 itself with just the word: `take`  and see if that assigns you the issue?

**Comment by js8544** [comment]
> @mapleFU has permissions to assign issues too. I cannot assign you the issue either, could be related to: #34389 Can you comment on [GH-35942](https://github.com/apache/arrow/issues/35942) itself with just the word: `take` and see if that assigns you the issue?

Aha, it works. #34389 should be the cause. Thanks!
