### ISSUE TITLE
cmake script assumes that double-conversion installs static libs, when it can install shared libs

### ISSUE THREAD

**Issue by yurivict** [apache/arrow#3672]
This line: https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L580

The ```double-conversion``` project can alternatively build shared libraries, when ```BUILD_SHARED_LIBS=ON``` is used.

You should only use libraries that ```double-conversion``` cmake script provides, which is in the ```double-conversion_LIBRARIES``` variable.

**Comment by wesm** [comment]
We use JIRA to manage project issues. Can you open an issue there?

**Comment by yurivict** [comment]
JIRA issue: https://issues.apache.org/jira/browse/ARROW-4608
