### ISSUE TITLE
[C++] Use custom url for s3 using AWS_ENDPOINT_URL

### ISSUE THREAD

**Issue by Kotwic4** [apache/arrow#36770]
### Describe the enhancement requested

AWS_ENDPOINT_URL is now supported by the AWS for custom url (for example localhost).
More info about it [docs](https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html) and [original github issue](https://github.com/aws/aws-cli/issues/1270). It was merged into botocore in [this pr](https://github.com/boto/botocore/pull/2973).

What I can do with boto:
```python
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "SECRET_KEY"
os.environ["AWS_ENDPOINT_URL"] = "http://localhost:9000"

session = boto3.session.Session()
s3_client = session.client(
    service_name="s3",
)
print(s3_client.list_buckets()["Buckets"])
```
What I have to do in pyarrow:
```python
import os
from pyarrow import fs

os.environ["AWS_ACCESS_KEY_ID"] = "ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "SECRET_KEY"
os.environ["AWS_ENDPOINT_URL"] = "http://localhost:9000"

s3 = fs.S3FileSystem(endpoint_override=os.environ["AWS_ENDPOINT_URL"])
print(s3.get_file_info(fs.FileSelector("", recursive=False)))
```

What I would like to do in pyarrow:
```python
import os
from pyarrow import fs

os.environ["AWS_ACCESS_KEY_ID"] = "ACCESS_KEY"
os.environ["AWS_SECRET_ACCESS_KEY"] = "SECRET_KEY"
os.environ["AWS_ENDPOINT_URL"] = "http://localhost:9000"

s3 = fs.S3FileSystem()
print(s3.get_file_info(fs.FileSelector("", recursive=False)))
```

This will allow me to use `s3://` instead of creating file system
```python
#current way
s3 = fs.S3FileSystem(endpoint_override=endpoint_url)
file = pq.ParquetFile('mybucket/my_file.parquet', filesystem=s3)

#possible future
file = pq.ParquetFile('s3://mybucket/my_file.parquet')
```

### Component(s)

Python

**Comment by westonpace** [comment]
Arrow uses AWS' C++ SDK.  From [this table](https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html) it appears that the C++ SDK does not yet support this feature:

![image](https://github.com/apache/arrow/assets/1696093/e860097d-135f-4995-9e05-9bed38f43858)

Perhaps the best place to advocate for this feature would be on the [AWS C++ SDK repo](https://github.com/aws/aws-sdk-cpp/issues).  If it is added there then we would pick up support for it automatically once we upgraded to the latest SDK version.

That being said, it should be possible for us to provide support for this, even if the SDK does not, in case someone wanted to create a PR.

**Comment by kou** [comment]
> That being said, it should be possible for us to provide support for this, even if the SDK does not, in case someone wanted to create a PR.

This may work:

```diff
diff --git a/cpp/src/arrow/filesystem/s3fs.cc b/cpp/src/arrow/filesystem/s3fs.cc
index c57fc7f29..b0c2d973e 100644
--- a/cpp/src/arrow/filesystem/s3fs.cc
+++ b/cpp/src/arrow/filesystem/s3fs.cc
@@ -339,6 +339,7 @@ Result<S3Options> S3Options::FromUri(const Uri& uri, std::string* out_path) {
   }
 
   bool region_set = false;
+  bool endpoint_override_set = false;
   for (const auto& kv : options_map) {
     if (kv.first == "region") {
       options.region = kv.second;
@@ -347,6 +348,7 @@ Result<S3Options> S3Options::FromUri(const Uri& uri, std::string* out_path) {
       options.scheme = kv.second;
     } else if (kv.first == "endpoint_override") {
       options.endpoint_override = kv.second;
+      endpoint_override_set = true;
     } else if (kv.first == "allow_bucket_creation") {
       ARROW_ASSIGN_OR_RAISE(options.allow_bucket_creation,
                             ::arrow::internal::ParseBoolean(kv.second));
@@ -357,6 +359,12 @@ Result<S3Options> S3Options::FromUri(const Uri& uri, std::string* out_path) {
       return Status::Invalid("Unexpected query parameter in S3 URI: '", kv.first, "'");
     }
   }
+  if (!endpoint_override_set) {
+    auto endpoint = std::getenv("AWS_ENDPOINT_URL");
+    if (!endpoint) {
+      options.endpoint_override = endpoint;
+    }
+  }
 
   if (!region_set && !bucket.empty() && options.endpoint_override.empty()) {
     // XXX Should we use a dedicated resolver with the given credentials?
```

BTW, the following will work with the current implementation:

```python
file = pq.ParquetFile(f's3://mybucket/my_file.parquet?endpoint_override={os.environ["AWS_ENDPOINT_URL"]}')
```

**Comment by Kotwic4** [comment]
I think it should just be in cpp sdk then. Raised an issue there

**Comment by kou** [comment]
@adbmal Could you add `take` only comment here to assign this issue to you?

**Comment by adbmal** [comment]
> @adbmal Could you add `take` only comment here to assign this issue to you?

yap

**Comment by adbmal** [comment]
take

**Comment by amoeba** [comment]
I think it would make sense to document this in https://arrow.apache.org/docs/cpp/env_vars.html. Happy to file an issue and submit a patch for that.

**Comment by kou** [comment]
It's a good idea! Please do it!

**Comment by adbmal** [comment]
> I think it would make sense to document this in https://arrow.apache.org/docs/cpp/env_vars.html. Happy to file an issue and submit a patch for that.

@kou I think it is a minor change, no need to file an issue, here is the PR, please review.
MINOR: [Docs] update document for AWS_ENDPOINT_URL environment variable #36826
