### ISSUE TITLE
Installing Arrow via Conan 2.0.9 fails due to "calling self.options in package_id() is forbidden"

### ISSUE THREAD

**Issue by stefan-novak-brt** [apache/arrow#36781]
### Describe the bug, including details regarding any error messages, version, and platform.

Attempting to install 

```
ERROR: arrow/12.0.0: Error in package_id() method, line 330
	self.info.options.with_gflags = self._with_gflags()
while calling '_with_gflags', line 212
	if required or self.options.with_gflags == "auto":
	ConanException: 'self.options' access in 'package_id()' method is forbidden
```

[Calling `self.options`](https://github.com/apache/arrow/blob/b9a647023de40a670ec8d9c32ff6e205debfaa8d/ci/conan/all/conanfile.py#L298) in [`package_id()`](https://github.com/apache/arrow/blob/b9a647023de40a670ec8d9c32ff6e205debfaa8d/ci/conan/all/conanfile.py#L605) is forbidden.

It appears that `self.options` is being called in a variety of `with_*()`methods within `package_id()`.

Is anyone familiar with another approach for computing the `package_id` without accessing options?

Thank you!

### Component(s)

C++, Packaging

**Comment by stefan-novak-brt** [comment]
@jaimesalvador also came across this issue: https://github.com/conan-io/conan/issues/13984#issuecomment-1567200992

**Comment by kou** [comment]
https://github.com/conan-io/conan-center-index/tree/master/recipes/arrow is the upstream. Let's go to conan-io/conan-center-index.

**Comment by stefan-novak-brt** [comment]
Ah, here's an existing upstream issue: https://github.com/conan-io/conan-center-index/issues/16953

Thanks for pointing me in the right direction. Cheers!
