### ISSUE TITLE
[Python] Unhandled type for Arrow to Parquet schema conversion: month_day_nano_interval

### ISSUE THREAD

**Issue by FoxHeather** [apache/arrow#36798]
### Describe the bug, including details regarding any error messages, version, and platform.

Perform Python code to generate a parquet data with interval type, using APACHE ARROW. 
Display error as below: 

> 
pyarrow.lib.ArrowNotImplementedError: 
 Unhandled type for Arrow to Parquet schema conversion: month_day_nano_interval
> 

import pyarrow as pa 
import pyarrow.parquet as pq 

# Define Schema
schema = pa.schema([
    ('itv', pa.month_day_nano_interval())
])

itv = pa.array([ (13,25,1000) ], type = pa.month_day_nano_interval())

# Generate Parquet data
batch = pa.RecordBatch.from_arrays(
    [itv],  schema = schema
)
table = pa.Table.from_batches([batch])

# Write Parquet file pqtpitvl.parquet
pq.write_table(table, 'pqtpitvl.parquet')

# display error 
    with ParquetWriter(
         ^^^^^^^^^^^^^^
  File "C:\Users\FoxHeather\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarrow\parquet\core.py", line 966, in __init__
    self.writer = _parquet.ParquetWriter(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_parquet.pyx", line 1748, in pyarrow._parquet.ParquetWriter.__cinit__
  File "pyarrow\error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Unhandled type for Arrow to Parquet schema conversion: month_day_nano_interval

### Component(s)

Python

**Comment by FoxHeather** [comment]
@emkornfield could you have a look this error?

**Comment by FoxHeather** [comment]
@westonpace do you have any idea for this?

**Comment by mapleFU** [comment]
Seems interval is not handled by `FieldToNode`:

```
Status FieldToNode(const std::string& name, const std::shared_ptr<Field>& field,
                   const WriterProperties& properties,
                   const ArrowWriterProperties& arrow_properties, NodePtr* out)
```

**Comment by FoxHeather** [comment]
This is whole error message 

    with ParquetWriter(
         ^^^^^^^^^^^^^^
  File "C:\Users\FoxHeather\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarrow\parquet\core.py", line 966, in __init__
    self.writer = _parquet.ParquetWriter(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_parquet.pyx", line 1748, in pyarrow._parquet.ParquetWriter.__cinit__
  File "pyarrow\error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: 
  Unhandled type for Arrow to Parquet schema conversion: month_day_nano_interval

@mapleFU

**Comment by mapleFU** [comment]
Pyarrow is just a wrapper, finally it would goes here: https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/schema.cc#L433-L438

**Comment by jorisvandenbossche** [comment]
Closing as duplicate of https://github.com/apache/arrow/issues/36799
