### ISSUE TITLE
[Docs] Link to GeoArrow from Canonical Extension Types docs

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#36790]
### Describe the enhancement requested

Work is ongoing in https://github.com/geoarrow/geoarrow on a family of proposed Arrow extension types for representing geospatial data. This work is happening in a separate repo (not directly in the Arrow monorepo via canonical extension types) because it is more practical for the geospatial data subcommunity of Arrow to reach consensus before engaging with the broader Arrow community. However it would be nice to add a note about GeoArrow in https://arrow.apache.org/docs/format/CanonicalExtensions.html with a link to to https://github.com/geoarrow/geoarrow.

### Component(s)

Documentation

**Comment by westonpace** [comment]
Hmm, but if it hasn't been voted on yet then we don't want to misconstrue it as "canonical".  Are you thinking of adding a "work in progress" or "under discussion" section?

**Comment by jorisvandenbossche** [comment]
Will already opened a similar issue some time ago, which has some discussion on this: https://github.com/apache/arrow/issues/35800. Let's move this there?

**Comment by ianmcook** [comment]
oops, I didn't see that other issue! Closing this in favor of #35800.
