### ISSUE TITLE
[C#] Using C API fails at runtime when targeting .NET 4.7.2

### ISSUE THREAD

**Issue by CurtHagenlocher** [apache/arrow#36812]
### Describe the bug, including details regarding any error messages, version, and platform.

The code fails with an error message along the lines of "Cannot marshal 'parameter #1': Pointers cannot reference marshaled structures. Use ByRef instead."

### Component(s)

C#

**Comment by kou** [comment]
Can we verify this case in our verification script?

**Comment by CurtHagenlocher** [comment]
I have a separate PR (https://github.com/apache/arrow/pull/36818) which enables testing under .NET 4.7.2 under Windows. (Unfortunately, I didn't figure out how to do this in time to add it to the previous PR.) Arguably, a better approach would be to build for 4.7.2 on every platform but enable the test only under Windows. Unfortunately, I didn't have the time to figure out how to modify the CI scripts to manage that; they currently seem to run all the tests that are built which means that they would try to run the 4.7.2 tests even on platforms where it's not supported.

**Comment by kou** [comment]
I see.
Thanks!
