### ISSUE TITLE
[C++] how to set use_virtual_addressing for pyarrow S3FileSystem 

### ISSUE THREAD

**Issue by windpiger** [apache/arrow#36827]
Currently pyarrow.fs.S3FileSystem init S3Client by using this logic to set use_virtual_addressing :
https://github.com/apache/arrow/blob/a2a3b9580d66cf40c5df8358f260fdaf5ccc301f/cpp/src/arrow/filesystem/s3fs.cc#L922
https://github.com/apache/arrow/blob/a2a3b9580d66cf40c5df8358f260fdaf5ccc301f/cpp/src/arrow/filesystem/s3fs.cc#L956

But If I want to set endpointOverride to "https://mytest.endpoint" which is not empty, `use_virtual_addressing` will be set to `false` because `use_virtual_addressing = options_.endpoint_override.empty();`

So How can I set `use_virtual_addressing` to `true` if I also want to set a non-empty value for endpointOverride?

Maybe we should de-couple these two configs and set them independently

### Component(s)

C++

**Comment by windpiger** [comment]
@pitrou could you pls help me to review this, thank you!

**Comment by pitrou** [comment]
@windpiger When writing this code, I thought that virtual adressing would be incompatible with a custom endpoint, but it turns out the two should work together (the bucket name would be prepended to the custom hostname: `http(s)://<bucket>.endpoint`).

**Comment by pitrou** [comment]
Would you like to submit a PR for this?

**Comment by pitrou** [comment]
Also cc @felipecrv if you want an entrypoint into the filesystem subsystem.

**Comment by windpiger** [comment]
> Would you like to submit a PR for this?

ok, it's my pleasure~
I have another question that how can I use docker-compose to build a distribution wheel on my MacOS?
`docker-compose python-wheel-manylinux-2014` ?

**Comment by pitrou** [comment]
> I have another question that how can I use docker-compose to build a distribution wheel on my MacOS?
> `docker-compose python-wheel-manylinux-2014` ? @pitrou

I have no idea. @raulcd Do you know?

**Comment by raulcd** [comment]
I have usually reproduced the python wheel generation on our CI with for example:
```
$ PYTHON=3.11 docker-compose build --no-cache --progress plain python-wheel-manylinux-2014
$ PYTHON=3.11 docker-compose run --rm python-wheel-manylinux-2014
```
You can also run our wheel tests (once generated) with:
```
$ docker-compose build --no-cache --progress plain python-wheel-manylinux-test-unittests
$ docker-compose run --rm python-wheel-manylinux-test-unittests
```
I haven't tested those right now but I have used them in the past.

**Comment by windpiger** [comment]
thank you, guys, I have done with `docker-compose python-wheel-manylinux-2014` @pitrou @raulcd

**Comment by mapleFU** [comment]
> thank you, guys, I have done with docker-compose python-wheel-manylinux-2014

@windpiger would you mind push to github and create a patch?

**Comment by pitrou** [comment]
This was done in #38858.

**Comment by MissiontoMars** [comment]
This PR only modifies the C++ layer, so when using the Python API, the "force_virtual_addressing" parameter cannot be passed. such as:

`
fs = pyarrow.fs.S3FileSystem(access_key='aaa', secret_key='bbb', endpoint_override='https://xxx', force_virtual_addressing=True)
`
@pitrou

**Comment by pitrou** [comment]
Yes, sorry. I should have added a separate issue to expose it in Python.
