### ISSUE TITLE
arrow::flight::FlightMessageReader batches order

### ISSUE THREAD

**Issue by Jokser** [apache/arrow#36841]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi everybody,

I have a clarifying question regarding batches order in arrow::flight::FlightMessageReader.
If a client sends batches to a server using one DoPut stream, does it guaranteed that the server will receive batches in the same order that the client sends it?
According to the documentation ArrowFlight uses gRPC stream for that case and gRPC documentation says that the message order is preserved, but I just want to be sure that ArrowFlight doesn't break anything.

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
We don't do anything with the order, so it should be the same.
