### ISSUE TITLE
[C++][Parquet] Use RLE for boolean type by default when parquet version is 2.x

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#36882]
### Describe the enhancement requested

As discussed in https://issues.apache.org/jira/browse/PARQUET-2222, it would be reasonable to switch the default to use RLE for boolean values if the parquet version is 2.x.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
Emm change default encoding is a bit weird in arrow system, because when encoding is not set, it will always use PLAIN.

It's lucky that is when `Dictionary` enabled and fallback to boolean, we don't need to considering it because currently we don't allow dict boolean

**Comment by wgtmac** [comment]
I agree it is tricky. I thought it would be easy to make the code change but actually it is more dirty than I think.

**Comment by pitrou** [comment]
Can you explain why it would be dirty?

**Comment by pitrou** [comment]
Ah, it's a pity it's inflexible like that.

But we could instead store a `std::optional<Encoding::type>` in WriterProperties (or `Encoding::UNKNOWN`, but that's less pretty). Then if the encoding hasn't been set to the user, the writer can choose its concrete value depending on the column type, and whether it's a v1 or v2 data page.

**Comment by wgtmac** [comment]
Yes, that's an option I have also considered. If you are good with `std::optional<Encoding::type>` approach, I can go ahead to implement it.

**Comment by pitrou** [comment]
Yes, I think that would allow for more flexibility in the future.

**Comment by mapleFU** [comment]
I've seen a piece in `arrow-rs`:

```rust
// ----------------------------------------------------------------------
// Encoding support for column writer.
// This mirrors parquet-mr default encodings for writes. See:
// https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/values/factory/DefaultV1ValuesWriterFactory.java
// https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/values/factory/DefaultV2ValuesWriterFactory.java

/// Trait to define default encoding for types, including whether or not the type
/// supports dictionary encoding.
trait EncodingWriteSupport {
    /// Returns true if dictionary is supported for column writer, false otherwise.
    fn has_dictionary_support(props: &WriterProperties) -> bool;
}

/// Returns encoding for a column when no other encoding is provided in writer properties.
fn fallback_encoding(kind: Type, props: &WriterProperties) -> Encoding {
    match (kind, props.writer_version()) {
        (Type::BOOLEAN, WriterVersion::PARQUET_2_0) => Encoding::RLE,
        (Type::INT32, WriterVersion::PARQUET_2_0) => Encoding::DELTA_BINARY_PACKED,
        (Type::INT64, WriterVersion::PARQUET_2_0) => Encoding::DELTA_BINARY_PACKED,
        (Type::BYTE_ARRAY, WriterVersion::PARQUET_2_0) => Encoding::DELTA_BYTE_ARRAY,
        (Type::FIXED_LEN_BYTE_ARRAY, WriterVersion::PARQUET_2_0) => {
            Encoding::DELTA_BYTE_ARRAY
        }
        _ => Encoding::PLAIN,
    }
}

/// Returns true if dictionary is supported for column writer, false otherwise.
fn has_dictionary_support(kind: Type, props: &WriterProperties) -> bool {
    match (kind, props.writer_version()) {
        // Booleans do not support dict encoding and should use a fallback encoding.
        (Type::BOOLEAN, _) => false,
        // Dictionary encoding was not enabled in PARQUET 1.0
        (Type::FIXED_LEN_BYTE_ARRAY, WriterVersion::PARQUET_1_0) => false,
        (Type::FIXED_LEN_BYTE_ARRAY, WriterVersion::PARQUET_2_0) => true,
        _ => true,
    }
}
```

Should we make all of these consistent?

**Comment by wgtmac** [comment]
That sounds good. Let me check.

**Comment by jorisvandenbossche** [comment]
> Rle is default enabled on Page V2, however, write page v2 is not recommended.

My understanding is that we also enabled it by default for DataPage V1 (we have a separate "parquet v2" which is enabled by default, and we decided to write RLE booleans based on that version, and not on DataPage V1 vs V2)

**Comment by wgtmac** [comment]
The parquet java implementation (namely parquet-mr) has mixed v2 features with data page v2. It means that user cannot use any v2 feature if data page version is not v2. However, I think the v2 implementation in parquet-mr is incomplete and not finalized. And the specs does not prohibit applying RLE to boolean values on data page v1.

**Comment by mapleFU** [comment]
@wgtmac I'm a bit confused that can we use RLE for Boolean on Data Page V1. I think we can decode this with arrow-rs impl, however I'm not sure parquet-mr can decode that, would you mind confirm that?

**Comment by wgtmac** [comment]
> @wgtmac I'm a bit confused that can we use RLE for Boolean on Data Page V1. I think we can decode this with arrow-rs impl, however I'm not sure parquet-mr can decode that, would you mind confirm that?

I have verified the code here: https://issues.apache.org/jira/browse/PARQUET-2222?focusedCommentId=17746755&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17746755

**Comment by mapleFU** [comment]
Ah, that's my fault, I think we can keep same as arrow-rs, since it's able to read this kind of data.

🤔It's also interesting that when dictionary is enabled, Boolean will also write RLE

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/pull/38070 I've added 'RLE' here, also mentioned that `use_dictionary` doesn't work for boolean type.

**Comment by jorisvandenbossche** [comment]
> I think we can keep same as arrow-rs

My understanding from previous comments in this (or related) threads was that arrow-rs actually let's it depend (by default) on the datapage v1 vs v2, and so doesn't generally write RLE for v1 datapages (unless you ask for it). 

So that's not the same behaviour as what we did here (and I don't know if that's good or bad, just pointing out so that we are clear)

**Comment by mapleFU** [comment]
@wgtmac should we also check DATA_PAGE version before when release 14.0.0? I think RLE boolean is great, but write it on DataPageV1 might raise some problem.

**Comment by wgtmac** [comment]
I am open to any option. If data page version is preferred, we can solely depend on it. Or should we revert this commit first if there is no consensus yet to unblock the release?

**Comment by mapleFU** [comment]
How about:

```diff
diff --git a/cpp/src/parquet/column_writer.cc b/cpp/src/parquet/column_writer.cc
index be1881d00..88829ef5d 100644
--- a/cpp/src/parquet/column_writer.cc
+++ b/cpp/src/parquet/column_writer.cc
@@ -2336,7 +2336,8 @@ std::shared_ptr<ColumnWriter> ColumnWriter::Make(ColumnChunkMetaDataBuilder* met
   Encoding::type encoding = properties->encoding(descr->path());
   if (encoding == Encoding::UNKNOWN) {
     encoding = (descr->physical_type() == Type::BOOLEAN &&
-                properties->version() != ParquetVersion::PARQUET_1_0)
+                properties->version() != ParquetVersion::PARQUET_1_0 &&
+                properties->data_page_version() == ParquetDataPageVersion::V2)
:
```

**Comment by wgtmac** [comment]
> How about:
> 
> ```diff
> diff --git a/cpp/src/parquet/column_writer.cc b/cpp/src/parquet/column_writer.cc
> index be1881d00..88829ef5d 100644
> --- a/cpp/src/parquet/column_writer.cc
> +++ b/cpp/src/parquet/column_writer.cc
> @@ -2336,7 +2336,8 @@ std::shared_ptr<ColumnWriter> ColumnWriter::Make(ColumnChunkMetaDataBuilder* met
>    Encoding::type encoding = properties->encoding(descr->path());
>    if (encoding == Encoding::UNKNOWN) {
>      encoding = (descr->physical_type() == Type::BOOLEAN &&
> -                properties->version() != ParquetVersion::PARQUET_1_0)
> +                properties->version() != ParquetVersion::PARQUET_1_0 &&
> +                properties->data_page_version() == ParquetDataPageVersion::V2)
> :
> ```

This is one option, but still differs from arrow-rs, right? It also requires some additional work in the unit test.

**Comment by mapleFU** [comment]
Yes, here I just think that:

1. Writing RLE on Boolean is only disabled in parquet-mr, self defined encoding will not be prevented
2. Default encoding for most using still stay at PLAIN.

(However, I also think that write RLE Boolean is ok)

**Comment by mapleFU** [comment]
I've draft a impl for only enable RLE when only data page and version is V2: https://github.com/apache/arrow/pull/38163

Feel free to merge or close it.

**Comment by jorisvandenbossche** [comment]
I personally don't have a strong opinion on what default is best (I also don't know how much benefit RLE has over PLAIN for booleans in practice)

We do have some other cases where we already use "version 2" features by default (in combination with DataPage V1), but that might be mostly logical types, and not yet encodings.

**Comment by jorisvandenbossche** [comment]
Sounds good!
