### ISSUE TITLE
Static Link Problem

### ISSUE THREAD

**Issue by jxh-cuit** [apache/arrow#36887]
### Describe the bug, including details regarding any error messages, version, and platform.

When I use this command to compiler flight_grpc_exampls.cc

```text
g++ flight_grpc_example.cc helloworld.grpc.pb.cc helloworld.pb.cc -o server -I/home/jxh/arrow/cpp/build/protobuf_ep-install/include/ -I/home/jxh/arrow/cpp/build/gflags_ep-prefix/src/gflags_ep/include/ -I/home/jxh/arrow/cpp/build/grpc_ep-install/include -I/home/jxh/arrow/cpp/ -std=c++17 -L/home/jxh/arrow/cpp/build/grpc_ep-install/lib/ -lgrpca -L/home/jxh/arrow/cpp/build/absl_ep-install/lib/ -labsl -L/home/jxh/openssl-3.0.0/ -lssl -lcrypto -L/home/jxh/arrow/cpp/build/debug/ -larrow_flight -larrow -L/home/jxh/arrow/cpp/build/re2_ep-install/lib/ -lre2 -L/home/jxh/arrow/cpp/build/protobuf_ep-install/lib/ -lprotobuf -lprotoc -L/home/jxh/arrow/cpp/build/gflags_ep-prefix/src/gflags_ep/lib/ -lgflags_debug -I./ -L/home/jxh/arrow/cpp/build/cares_ep-install/lib/ -lcares -L/home/jxh/arrow/cpp/build/zlib_ep/src/zlib_ep-install/lib/ -lz -I/home/jxh/arrow/cpp/build/absl_ep-install/include/ -L/home/jxh/arrow/cpp/build/debug/ -larrow_flight
```

I have statically linked libarrow_flight.a, but when I run this server I still got:

```text
./server -port 5000
./server: error while loading shared libraries: libarrow_flight.so.1300: cannot open shared object file: No such file or directory
```

Why this still happen?

### Component(s)

C++

**Comment by kou** [comment]
Why did you build `flight_grpc_example.cc` manually?
You can build it automatically by using `-DARROW_BUILD_EXAMPLES=ON -DARROW_FLIGHT=ON`.

**Comment by jxh-cuit** [comment]
@kou I don't think this is the key issue, no matter which way to build this examples, all of these ways should work well, even I can build it automatically, there must be some times I still need to do it manually, so I have to figure out what's wrong happend here. If you know anything about it, please let me know, so much thank:).

**Comment by jxh-cuit** [comment]
ok, finally I finish this work manunlly.
