### ISSUE TITLE
[C++] Pointless ellipsis in array repr

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#36933]
### Describe the enhancement requested

```python
>>> import pyarrow
>>> pyarrow.array([None] * 5, pyarrow.list_(pyarrow.int8()))
<pyarrow.lib.ListArray object at 0x7f495698eb60>
[
  null,
  null,
  ...
  null,
  null
]
>>> pyarrow.__version__
'12.0.1'
```

There's no point ellipsizing the middle of the list; there's only one element, so we may as well show it!

### Component(s)

Python

**Comment by raycursive** [comment]
I guess this is intended, see [Here](https://github.com/apache/arrow/blob/757e0d5cca1124139cd08512882debcb7b4d65d5/cpp/src/arrow/pretty_print_test.cc#L765), it is a part of the test case (tho I don't really understand)
Here's the [related issue](https://issues.apache.org/jira/browse/ARROW-14798) where the testcase was introduced

I was thinking would it be better to check if the `element size == 2*window + 1`, and if so just erase the ellipsis?

**Comment by felipecrv** [comment]
> I guess this is intended, see [Here](https://github.com/apache/arrow/blob/757e0d5cca1124139cd08512882debcb7b4d65d5/cpp/src/arrow/pretty_print_test.cc#L765), it is a part of the test case (tho I don't really understand)

Don't take the tests as fixed truth. ;-)
 
We're manufacturing a new desirable invariant now: don't show `...` in place of only 1 item — an ellipsis replaces 2 or more entries.

**Comment by raycursive** [comment]
> > I guess this is intended, see [Here](https://github.com/apache/arrow/blob/757e0d5cca1124139cd08512882debcb7b4d65d5/cpp/src/arrow/pretty_print_test.cc#L765), it is a part of the test case (tho I don't really understand)
> 
> Don't take the tests as fixed truth. ;-)
> 
> We're manufacturing a new desirable invariant now: don't show `...` in place of only 1 item — an ellipsis replaces 2 or more entries.

Thanks! After thinking of this I do consider that the current implementation doesn't behave as desired. 
The improvement has been introduced in #37168
