### ISSUE TITLE
[R] Arrow crashes session or read gets an arror (exceeded limit size)

### ISSUE THREAD

**Issue by xtimbeau** [apache/arrow#36940]
### Describe the bug, including details regarding any error messages, version, and platform.

Using Arrow from R, version 12.0.1.1, on linux, last versions of everything, I try to write a 500Mo file to a parquet. Either it is crashing or I do get an error when reading : OSError: `Couldn't deserialize thrift: TProtocolException: Exceeded size limit error`.
When saving my data (6 columns, 16M lines) as a dataset I do get a crash too. Hiving the data brings the same.
Memory consumption seems to increase neatly before the crash -- however several Go of RAM are available. 

```
R version 4.3.1 (2023-06-16) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 22.04.2 LTS  Matrix products: default BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3  LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C                [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         time zone: Etc/UTC tzcode source: system (glibc)  attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] here_1.0.1        sf_1.0-13         tmap_3.3-3        data.table_1.14.8  [5] glue_1.6.2        lubridate_1.9.2   forcats_1.0.0     stringr_1.5.0      [9] dplyr_1.1.2       purrr_1.0.1       readr_2.1.4       tidyr_1.3.0       [13] tibble_3.2.1      ggplot2_3.4.2     tidyverse_2.0.0   archive_1.1.5      loaded via a namespace (and not attached):  [1] tidyselect_1.2.0        viridisLite_0.4.2       arrow_10.0.1             [4] fastmap_1.1.1           leaflet_2.1.2           stringfish_0.15.8        [7] XML_3.99-0.14           digest_0.6.32           timechange_0.2.0        [10] lifecycle_1.0.3         ellipsis_0.3.2          ggspatial_1.1.8         [13] terra_1.7-39            magrittr_2.0.3          compiler_4.3.1          [16] rlang_1.1.1             tools_4.3.1             yaml_2.3.7              [19] utf8_1.2.3              htmlwidgets_1.6.2       bit_4.0.5               [22] sp_2.0-0                MetricsWeighted_1.0.2   classInt_0.4-9          [25] RColorBrewer_1.1-3      abind_1.4-5             KernSmooth_2.23-21      [28] withr_2.5.0             leafsync_0.1.0          grid_4.3.1              [31] fansi_1.0.4             e1071_1.7-13            leafem_0.2.0            [34] colorspace_2.1-0        scales_1.2.1            dichromat_2.0-0.1       [37] cli_3.6.1               crayon_1.5.2            ragg_1.2.5              [40] generics_0.1.3          RcppParallel_5.1.7      rstudioapi_0.14         [43] tzdb_0.4.0              tmaptools_3.1-1         DBI_1.1.3               [46] proxy_0.4-27            RApiSerialize_0.1.2     stars_0.6-1             [49] assertthat_0.2.1        parallel_4.3.1          s2_1.1.4                [52] base64enc_0.1-3         vctrs_0.6.3             jsonlite_1.8.7          [55] hms_1.1.3               bit64_4.0.5             systemfonts_1.0.4       [58] crosstalk_1.2.0         units_0.8-2             lwgeom_0.2-13           [61] leaflet.providers_1.9.0 codetools_0.2-19        stringi_1.7.12          [64] gtable_0.3.3            raster_3.6-20           munsell_0.5.0           [67] pillar_1.9.0            htmltools_0.5.5         R6_2.5.1                [70] textshaping_0.3.6       wk_0.7.3                rprojroot_2.0.3         [73] vroom_1.6.3             lattice_0.21-8          png_0.1-8               [76] qs_0.25.5               class_7.3-22            Rcpp_1.0.10             [79] fs_1.6.2                pkgconfig_2.0.3
``` 
<br class="Apple-interchange-newline">

### Component(s)

R

**Comment by mapleFU** [comment]
Can you get `parquet::ReaderProperties`? In C++, we have:

```
constexpr int32_t kDefaultThriftStringSizeLimit = 100 * 1000 * 1000;
// Structs in the thrift definition are relatively large (at least 300 bytes).
// This limits total memory to the same order of magnitude as
// kDefaultStringSizeLimit.
constexpr int32_t kDefaultThriftContainerSizeLimit = 1000 * 1000;
```

Would you mind enlarge the thrift container size limit? @xtimbeau

**Comment by xtimbeau** [comment]
Hi, I think I found the problem. The filse size was way too big. One of the column was a named vector (result from a predict, no special intention there). When saving as a parquet, it seems to do something big.

**Comment by mapleFU** [comment]
Parquet will store the file metadata as a thrift. If you have too many columns or too many row groups, the thrift object would be large.

By default, during reading, parquet reader will use 1MB as thrift container size limit, 100MB as thrift object size limit. I guess your file footer is too large.

You can solve this by:
1. During writing: Make file having less row-groups, or just make file smaller.
2. During reading: you can enlarge the thrift config

**Comment by xtimbeau** [comment]
Ok thanks, still not clear how to enlarge the thrift config in R

**Comment by mapleFU** [comment]
As I said, R seems doesn't allow to config ReaderProperty in this problem, I'll create an issue for that.

By the way, to confirm my infer, would you mind print the metadata (using Python https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_metadata.html , I don't familiar with R so I don't know how to do it)when reading a smaller file? I just want to confirm that it's the thrift filemetadata problem, so I guess I'd better get the size of metadata

**Comment by xtimbeau** [comment]
Here is what I get on a smaller file (1k lines)
```
>>> pq.read_metadata('trajets.parquet')
<pyarrow._parquet.FileMetaData object at 0x7fd8ce7276a0>
  created_by: parquet-cpp-arrow version 10.0.1
  num_columns: 10
  num_rows: 1000
  num_row_groups: 1
  format_version: 2.6
  serialized_size: 33835
```

**Comment by mapleFU** [comment]
Emm the file is too small, I guess the code below is where the exception thrown. Later you can read the metadata with larger container size or string size in python or c++ to confirm if the containersize is large enough

```c++
  template <class T>
  void DeserializeUnencryptedMessage(const uint8_t* buf, uint32_t* len,
                                     T* deserialized_msg) {
    // Deserialize msg bytes into c++ thrift msg using memory transport.
    auto tmem_transport = CreateReadOnlyMemoryBuffer(const_cast<uint8_t*>(buf), *len);
    apache::thrift::protocol::TCompactProtocolFactoryT<ThriftBuffer> tproto_factory;
    // Protect against CPU and memory bombs
    tproto_factory.setStringSizeLimit(string_size_limit_);
    tproto_factory.setContainerSizeLimit(container_size_limit_);
    auto tproto = tproto_factory.getProtocol(tmem_transport);
    try {
      deserialized_msg->read(tproto.get());
    } catch (std::exception& e) {
      std::stringstream ss;
      ss << "Couldn't deserialize thrift: " << e.what() << "\n";
      throw ParquetException(ss.str());
    }
    uint32_t bytes_left = tmem_transport->available_read();
    *len = *len - bytes_left;
  }
```

**Comment by mapleFU** [comment]
@thisisnic @paleolimbot would you mind expose `ReaderProperties` in parquet to R wrapper?

1. cpp reader properties: https://github.com/apache/arrow/blob/main/cpp/src/parquet/properties.h#L59
2. Python https://github.com/apache/arrow/blob/836aa1e5ccaa20fb5d3b4b7f44adc84642ff0e56/python/pyarrow/parquet/core.py#L271

**Comment by thisisnic** [comment]
I've exposed these options in #36990 which will most likely take a bit longer to get merged as the person I've pinged to review the PR is currently on holiday, but it should fix the problem @xtimbeau was having, as I've managed to recreate their error in the tests there.

Thanks for the heads up on how to solve this @mapleFU, you saved me a lot of time there! :)

**Comment by mapleFU** [comment]
Yeah, make metadata smaller will solve this issue. And we can also pass the properties.
@xtimbeau Can we close this issue or wait for https://github.com/apache/arrow/issues/36990 merged?

**Comment by thisisnic** [comment]
I'll close this for now, as we've now merged that other issue - @xtimbeau - if you use the dev version of Arrow, you should now be able to configure the limit. If you run in to any issues, let us know.
