### ISSUE TITLE
[Python] How to generate a parquet file with type ENUM and type UUID

### ISSUE THREAD

**Issue by FoxHeather** [apache/arrow#36968]
### Describe the usage question you have. Please include as many useful details as  possible.

The Apache Parquet Logic types includes 3 String Types: STRING, ENUM and UUID.
[https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#string-types ](url)

In the Data Types and Schemas, there is no ENUM and UUID. [https://arrow.apache.org/docs/python/api/datatypes.html#](url)  

Now, I want to generate a Parquet file that including type ENUM and type UUID. 
Who can support your ideas how to do it? 

### Component(s)

Python

**Comment by danepitkin** [comment]
Hi @FoxHeather,

UUID and Enum can be represented by using/extending the existing Arrow formats. For UUID, see this example of a User Defined Type[1]. For Enum, the dictionary encoded layout is probably the best representation.

[1] https://arrow.apache.org/docs/python/extending_types.html#defining-extension-types-user-defined-types
[2] https://arrow.apache.org/docs/format/Columnar.html#dictionary-encoded-layout

**Comment by FoxHeather** [comment]
Thank you @danepitkin 
I have created the python code to generate parquet file with reference [1] link.

**Comment by FoxHeather** [comment]
I have created the python code to generate enum parquet file with reference [2] link.
@danepitkin Thanks

**Comment by mapleFU** [comment]
Nice, can we close this issue @FoxHeather ?

**Comment by FoxHeather** [comment]
@mapleFU Please close this one.
