### ISSUE TITLE
can't filter parquet data when a column format has Chinese and English

### ISSUE THREAD

**Issue by loukey-lj** [apache/arrow#37006]
### Describe the bug, including details regarding any error messages, version, and platform.

1、parquet come from
use apache hive 2.1.1 : 
``
create table all_f_hive_sn2 stored as PARQUET as
select '22323' as f1, 'abc'  as f2, '在在在'  as f3, 'abc'   as f4, '22323'  as f5, 'abc'    as f6
union 
select '22323' as f1, 'abc'  as f2, '在在在'  as f3, '22323' as f4, '在在在' as f5, '在在在' as f6`
``

2、query by gluten with spark 3.2.1
 select * from all_f_hive_sn2  where f1= '22323' , result right；
 select * from all_f_hive_sn2  where f2= 'abc'    , result right；
 select * from all_f_hive_sn2  where f3= '在在在'    , result right；
 select * from all_f_hive_sn2  where f4= 'abc'    , result right；

 select * from all_f_hive_sn2  where f5= '22323'    , no result ；
 select * from all_f_hive_sn2  where f6= 'abc'       , no result ；

== Physical Plan == 
Output [6]: [f1#0, f2#1, f3#2, f4#3, f5#4, f6#5]
Batched: true
Location: InMemoryFileIndex [hdfs://1a41vla2748hadp:8020/user/hive/warehouse/all_f_hive_sn2]
PushedFilters: [IsNotNull(f5), EqualTo(f5,22323)]
ReadSchema: struct<f1:string,f2:string,f3:string,f4:string,f5:string,f6:string>

000000_0.zip is the parquet file stored in table all_f_hive_sn2 ;

3、Since gluten depends on arrow, can someone help build a PushedFilters query parquet using arrow? See if it's an arrow bug

[000000_0.zip](https://github.com/apache/arrow/files/12246604/000000_0.zip)

### Component(s)

Parquet

**Comment by mapleFU** [comment]
> Since gluten depends on arrow, can someone help build a PushedFilters query parquet using arrow? See if it's an arrow bug

Can you show how gluten filters data? Or provide the filter in compute? Maybe add some log in 

```c++
Result<std::vector<int>> ParquetFileFragment::FilterRowGroups(
    compute::Expression predicate) {
  std::vector<int> row_groups;
  ARROW_ASSIGN_OR_RAISE(auto expressions, TestRowGroups(std::move(predicate)));

  auto lock = physical_schema_mutex_.Lock();
  DCHECK(expressions.empty() || (expressions.size() == row_groups_->size()));
  for (size_t i = 0; i < expressions.size(); i++) {
    if (expressions[i].IsSatisfiable()) {
      row_groups.push_back(row_groups_->at(i));
    }
  }
  return row_groups;
}
```

help

**Comment by mapleFU** [comment]
After check with 

```
cp::Expression filter = cp::and_(cp::equal(cp::field_ref("f5"), cp::literal("22323")), cp::not_(cp::is_null(cp::field_ref("f5"))));
```

This can scan the table out. So I wonder the pushdown rule is wrong in Hudi. Please refer to https://github.com/oap-project/gluten/issues/2513 for encoding.

**Comment by mapleFU** [comment]
So can I close this issue?

**Comment by loukey-lj** [comment]
Thank you, can turn it off. Through
analysis, it seems that there is a problem with the calculation of the column's min/max values  when hive writes the file, which causes an error when velox reads the parquet through thrift.
But it’s okay to query in other languages ​​and frameworks. It may be that the way velox reads parquet is very close to the bottom layer, which leads to reading wrong statistics, while java /arrow does not.

**Comment by loukey-lj** [comment]
Thank you, can turn it off. Through
analysis, it seems that there is a problem with the calculation of the column's min/max values  when hive writes the file, which causes an error when velox reads the parquet through thrift.
But it’s okay to query in other languages ​​and frameworks. It may be that the way velox reads parquet is very close to the bottom layer, which leads to reading wrong statistics, while java /arrow does not.
