### ISSUE TITLE
[R] Documentation for `read_parquet()` et al needs updating

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#37019]
### Describe the bug, including details regarding any error messages, version, and platform.

#35173 results in the `read_*()` family of functions now always returning tibbles, but the docs still say `data.frame()` - we should also cherry-pick the fix for this into 13.0.0 and make sure it's reflected on the deployed Arrow site

### Component(s)

R

**Comment by assignUser** [comment]
I have added the breaking change label to #35173 and added the 13 milestone to make sure it get's added to the next rc 
cc @raulcd

**Comment by thisisnic** [comment]
Thanks very much @assignUser !
