### ISSUE TITLE
[Java] How to build the JNI jar to contain both x86 and arm libraries

### ISSUE THREAD

**Issue by zinking** [apache/arrow#37058]
### Describe the usage question you have. Please include as many useful details as  possible.

I've managed to build a arrow-dataset JAR that contains x86 artifacts using `archery docker run java-jni-manylinux-2014`
but when I look at the current build, the JAR actually contains both x86 and arm libraries,
how do I build such jars?

### Component(s)

Java

**Comment by zinking** [comment]
@kou  any suggestions?

**Comment by zinking** [comment]
using this built jar seems still problematic 

```
Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 2) (10.73.23.33 executor driver): java.lang.NoClassDefFoundError: org/apache/arrow/c/ArrowArray
	at org.apache.arrow.dataset.jni.NativeScanner$NativeReader.loadNextBatch(NativeScanner.java:146)
```

**Comment by kou** [comment]
One more information: We can build arm64 binaries on x86_64 by `ARCH=arm64v8 ARCH_ALIAS=aarch64 ARCH_SHORT=arm64 archery docker run java-jni-manylinux-2014`.

**Comment by zinking** [comment]
> ARCH=arm64v8 ARCH_ALIAS=aarch64 ARCH_SHORT=arm64 archery docker run java-jni-manylinux-2014

didn't seem to work properly 
```
 > [ 2/17] RUN yum install -y dnf:
0.117 exec /bin/sh: exec format error
```

[this question](https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error) suggests a cross compiling related error.

**Comment by kou** [comment]
Ah, you need QEMU but I don't know QEMU works on macOS...
