### ISSUE TITLE
Ds.dataset() incorrectly reads datetimes in partitioned parquet file

### ISSUE THREAD

**Issue by lmocsi** [apache/arrow#37070]
### Describe the bug, including details regarding any error messages, version, and platform.

```
import pyarrow.dataset as ds

mytab = ds.dataset("my_table_name", partitioning='hive').to_table()
print(mytab)

```
[my_table_name.zip](https://github.com/apache/arrow/files/12296584/my_table_name.zip)

The DATE_OF_BIRTH is one hour less in the printed results, than it is in reality.

The results are:
pyarrow.Table
USER_ID: double
TRX_CNT: double
DATE_OF_BIRTH: timestamp[ns]
CALENDAR_DATE: string
----
USER_ID: [[1000,1001,1002,1003],[1000,1001,1002,1005],[1000,1001,1003,1005,1008]]
TRX_CNT: [[434,11,3,555],[111,32,1,2],[434,21,44,111,222]]
DATE_OF_BIRTH: [[1998-12-01 23:00:00.000000000,2002-03-13 23:00:00.000000000,1975-08-31 23:00:00.000000000,1998-12-31 23:00:00.000000000],[1998-12-01 23:00:00.000000000,2002-03-13 23:00:00.000000000,1975-08-31 23:00:00.000000000,2004-06-06 22:00:00.000000000],[1998-12-01 23:00:00.000000000,2002-03-13 23:00:00.000000000,1998-12-31 23:00:00.000000000,2004-06-06 22:00:00.000000000,1988-02-27 23:00:00.000000000]]
CALENDAR_DATE: [["2023-08-01 00:00:00","2023-08-01 00:00:00","2023-08-01 00:00:00","2023-08-01 00:00:00"],["2023-08-02 00:00:00","2023-08-02 00:00:00","2023-08-02 00:00:00","2023-08-02 00:00:00"],["2023-08-03 00:00:00","2023-08-03 00:00:00","2023-08-03 00:00:00","2023-08-03 00:00:00","2023-08-03 00:00:00"]]

### Component(s)

Parquet, Python

**Comment by lmocsi** [comment]
version:
pyarrow==12.0.1

platform:
windows 11 / linux

**Comment by mapleFU** [comment]
Hi 

```json
{
  "Version": "1.0",
  "CreatedBy": "parquet-mr version 1.12.3 (build f8dced182c4c1fbdec6ccb3185537b5a01e6ed6b)",
  "TotalRows": "4",
  "Columns": [
     { "Id": "2", "Name": "DATE_OF_BIRTH", "PhysicalType": "INT96", "ConvertedType": "NONE", "LogicalType": {"Type": "None"} }
  ],
  "RowGroups": [
     {
       "Id": "0",  "TotalBytes": "222",  "TotalCompressedBytes": "206",  "Rows": "4",
       "ColumnChunks": [
          {"Id": "2", "Values": "4", "StatsSet": "False",
           "Compression": "SNAPPY", "Encodings": "PLAIN_DICTIONARY(DICT_PAGE) PLAIN_DICTIONARY", "UncompressedSize": "100", "CompressedSize": "92" }
        ]
     }
  ]
}
```

Seems that `DATE_OF_BIRTH` is an INT96. INT96 is for legacy timezone. Parquet-format has a "isAdjustToUtc", see: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#instant-semantics-timestamps-normalized-to-utc

When reading INT96, we will regard it as a timestamp with utc timezone. And during reading, "timestamp" time will regard it as yourself location. So:
1. dataset read utc
2. print in your timezone

So it will be different from your result

**Comment by mapleFU** [comment]
```python
>>> schema=pa.schema([("DATE_OF_BIRTH", pa.timestamp('ns', 'UTC-8'))])
>>> mytab = ds.dataset(".", partitioning=part, schema=schema).to_table()
>>> mytab
pyarrow.Table
DATE_OF_BIRTH: timestamp[ns, tz=UTC-8]
----
DATE_OF_BIRTH: [[1998-12-01 23:00:00.000000000,2002-03-13 23:00:00.000000000,1975-08-31 23:00:00.000000000,1998-12-31 23:00:00.000000000],[1998-12-01 23:00:00.000000000,2002-03-13 23:00:00.000000000,1975-08-31 23:00:00.000000000,2004-06-06 22:00:00.000000000],[1998-12-01 23:00:00.000000000,2002-03-13 23:00:00.000000000,1998-12-31 23:00:00.000000000,2004-06-06 22:00:00.000000000,1988-02-27 23:00:00.000000000]]
>>> schema=pa.schema([("CALENDAR_DATE", pa.timestamp('ns', 'UTC-10'))])
>>> mytab = ds.dataset(".", partitioning=part, schema=schema).to_table()
>>> mytab
pyarrow.Table
CALENDAR_DATE: timestamp[ns, tz=UTC-10]
----
CALENDAR_DATE: [[2023-08-01 00:00:00.000000000,2023-08-01 00:00:00.000000000,2023-08-01 00:00:00.000000000,2023-08-01 00:00:00.000000000],[2023-08-02 00:00:00.000000000,2023-08-02 00:00:00.000000000,2023-08-02 00:00:00.000000000,2023-08-02 00:00:00.000000000],[2023-08-03 00:00:00.000000000,2023-08-03 00:00:00.000000000,2023-08-03 00:00:00.000000000,2023-08-03 00:00:00.000000000,2023-08-03 00:00:00.000000000]]
>>> 

```

You can set the tz yourself here @lmocsi

**Comment by lmocsi** [comment]
> @lmocsi hi, would the advice here ( [#37070 (comment)](https://github.com/apache/arrow/issues/37070#issuecomment-1675252307) ) helps?

@mapleFU Unfortunately no. Specifying the schema does not change anything for me. :(

**Comment by lmocsi** [comment]
The data is created like this:
```python
import polars as pl

df = pl.DataFrame({'USER_ID': [1000,1001,1002,1003,1000,1001,1002,1005,1000,1001,1003,1005,1008],
'TRX_CNT': [434,11,3,555,111,32,1,2,434,21,44,111,222],
'DATE_OF_BIRTH': ['1998-12-02','2002-03-14','1975-09-01','2000-01-01','1998-12-02','2002-03-14','1975-09-01','2004-06-07','1998-12-02','2002-03-14','1999-01-01','2004-06-07','1988-02-28'],
'CALENDAR_DATE': ['2023-08-01','2023-08-01','2023-08-01','2023-08-01','2023-08-02','2023-08-02','2023-08-02','2023-08-02','2023-08-03','2023-08-03','2023-08-03','2023-08-03','2023-08-03']
}, schema={'USER_ID':pl.Int64,
           'TRX_CNT': pl.Int64,
           'DATE_OF_BIRTH': pl.Date,
           'CALENDAR_DATE': pl.Date
           })

df.write_parquet('my_table_name',partition_by=['CALENDAR_DATE'])
```

And polars reads it correctly:
```python
import polars as pl

df = pl.read_parquet('my_table_name',hive_partitioning=True)
print(df)
```

**Comment by lmocsi** [comment]
Since I no longer use pyarrow.dataset, I'm closing this issue.
