### ISSUE TITLE
[Java][JDBC-driver] Ignore username/password auth if they are empty and a `token` is provided

### ISSUE THREAD

**Issue by aiguofer** [apache/arrow#37073]
### Describe the enhancement requested

We've run into some issues with our service where users are using tools that always provide a username/password even if none are provided and a token is passed in as part of the connection params. This causes the driver to go through the Handshake flow using username/password which fails since we don't support that.

Ideally, tools should not attempt to use username/password if none are provided, but it's impossible to force tools to change their implementation. Instead, we could check if the username/password are empty and the `token` is provided in the connection parameters and choose `token` auth instead.

If this seems reasonable I'd be happy to put up a PR for it.

### Component(s)

Java

**Comment by lidavidm** [comment]
Makes sense to me!
