### ISSUE TITLE
[C++] cumulative_sum doesn't check for overflow

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#37089]
### Describe the bug, including details regarding any error messages, version, and platform.

```pycon
>>> pc.cumulative_sum(pa.array([250, 250], type=pa.uint8()))
<pyarrow.lib.UInt8Array object at 0x7f9a363744c0>
[
  250,
  244
]
```

### Component(s)

C++

**Comment by pitrou** [comment]
@js8544

**Comment by js8544** [comment]
There's a `cumulative_sum_checked` variant that checks for overflow.

**Comment by pitrou** [comment]
Hmm, I had missed it, sorry!
