### ISSUE TITLE
[MATLAB] Add utility which makes valid MATLAB `table` variable names from an arbitrary list of strings

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#37096]
### Describe the enhancement requested

To make it possible to safely convert Arrow `Schema` field names to corresponding MATLAB `table` variable names, it would be helpful to add a utility which can take an arbitrary list of strings and return a set of valid MATLAB `table` variable names, which are (1) unique, (2) non-empty, and (3) do not conflict with the "reserved" variable names "Properties", "VariableNames", "RowNames", and ":".

### Component(s)

MATLAB

**Comment by sgilmore10** [comment]
take
