### ISSUE TITLE
[C++] `arrow-compute-scalar-round-benchmark` fails with `Rounding to -5 digits is out of range for type int16`

### ISSUE THREAD

**Issue by jgehrcke** [apache/arrow#37106]
### Describe the bug, including details regarding any error messages, version, and platform.

In benchmarking pipelines we [see](https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/160) that `arrow-compute-scalar-round-benchmark` fails with code 6, emitting `Invalid: Rounding to -5 digits is out of range for type int16` on stderr. The first commit that produces this error was https://github.com/apache/arrow/commit/7c8f398f32ba5d2685093a010002f729a01a4242. It seems to be strongly related :).

### Component(s)

Archery, Benchmarking

**Comment by pitrou** [comment]
@js8544 Could you perhaps take a look?
