### ISSUE TITLE
[Python] Attach Python stacktrace to errors in `ConvertPyError`

### ISSUE THREAD

**Issue by alanhdu** [apache/arrow#37164]
### Describe the bug, including details regarding any error messages, version, and platform.

We have an internal application that is using the `arrow::RecordBatchReader` with a Python generator (but in C++). Right now, when the Python generator raises an error, the stack trace disappears (e.g. in our code base we just see:

```
Python exception: AssertionError
```

without the stack trace.

I am not super familiar with C++ or the code, but I *think* the problem can be traced to this function:

https://github.com/apache/arrow/blob/750670e8c7c8b7985323f7866e4aa09be4232169/python/pyarrow/src/arrow/python/common.cc#L144-L153

which calls into

https://github.com/apache/arrow/blob/750670e8c7c8b7985323f7866e4aa09be4232169/python/pyarrow/src/arrow/python/common.cc#L91-L96

where we *only* attach the exception type name and no other information. My C++ is not very good, but how hard would it be to actually attach the full Python stacktrace inside the message whenever we hit a Python exception?

### Component(s)

Python

**Comment by pitrou** [comment]
Yes, we could improve `PythonErrorDetail::ToString()` to include more information (the downside is that it would also be more noisy for the user, who might not be interested in a full traceback).

cc @danepitkin
