### ISSUE TITLE
[C++] Rewrite schema in RecordBatch.

### ISSUE THREAD

**Issue by Light-City** [apache/arrow#37170]
### Describe the enhancement requested

We have a scene. There is a plan in pg that looks like the following. For the Append node, there are two scans in parallel, and then there is a column of data, but the column names are different. If it is mapped to the arrow schema It is a different field. For the append node, we will get two batches. The first batch comes from the first scan, and the second batch comes from the second scan, but because the two columns are constructed based on the scan The schema is different, so the final schema of the two batches is different. When we construct the slot returned by the Append node, we use the schema of the first batch. When we put the data of the second batch into it, the verification fails due to inconsistent shcema. 

**Therefore, the problem is simplified to: For a node, If there are n child nodes, the schema of the following child nodes must be consistent. If not, the schema of n-1 child nodes must be the same as the first schema, so there is logic to rewrite the schema of the batch data.**

```
-> Vec Append
            -> Vec Seq Scan on public. tenk1
                  Output: tenk1.unique1
            -> Vec Seq Scan on public.tenk1 tenk1_1
                  Output: tenk1_1.fivethous
```

However, when reading the batch code, there is only the read-only interface `schema()`, so here we submit a pr to add and rewrite the schema interface, and only modify the columns with the same type. If they are not the same, an invalid modification will be returned.

### Component(s)

C++

**Comment by mapleFU** [comment]
What about using a `Project` node? Seems that Acero can unify the schema with the help of Union or Project?

**Comment by Light-City** [comment]
> What about using a `Project` node? Seems that Acero can unify the schema with the help of Union or Project?

I personally feel that it is too heavy, and I have to start an arrow plan again. From the perspective of batch, if I only want to modify the schema name, I still need to rewrite the schema interface

**Comment by mapleFU** [comment]
I guess `Project` will not always modify the data, though it will call an expression.

Another point is that `RecordBatch` seems tent to be immutable. Would the interface below be ok?

```c++
Result<std::shared_ptr<RecordBatch>> SetSchema(...);
```

**Comment by Light-City** [comment]
> I guess `Project` will not always modify the data, though it will call an expression.
> 
> Another point is that `RecordBatch` seems tent to be immutable. Would the interface below be ok?
> 
> ```c++
> Result<std::shared_ptr<RecordBatch>> SetSchema(...);
> ```

I agree, if RecordBatch is read-only from a design point of view, then it really needs to be designed as above,

**Comment by Light-City** [comment]
> ```c++
> SetSchema
> ```

schema_ is readonly, so we don't use SetSchema function to get batch schema.

```
 protected:
  RecordBatch(const std::shared_ptr<Schema>& schema, int64_t num_rows);

  std::shared_ptr<Schema> schema_;
  int64_t num_rows_;
```

**Comment by Light-City** [comment]
maybe RewriteSchema in recordbatch is a good idea
