### ISSUE TITLE
[JS] using apache arrow in pure js

### ISSUE THREAD

**Issue by yosiasz** [apache/arrow#37186]
Greetings,

I would like to use apache arrow in grafana to visualize some paquet files.

is this a valid js file I can point to in order to do my thing?

https://cdn.jsdelivr.net/npm/apache-arrow@12.0.1/Arrow.es2015.min.js

from here
https://www.jsdelivr.com/package/npm/apache-arrow

Thanks!

### Component(s)

JavaScript

**Comment by kou** [comment]
@domoritz Could you take a look at this?

**Comment by domoritz** [comment]
Arrow JS does not support Parquet right now but only arrow IPC.
