### ISSUE TITLE
[C++] Primitive concrete arrays could expose a span converter

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#37199]
### Describe the enhancement requested

Just like we have `PrimitiveArray::raw_values`, we could also have something that returns a `arrow::util::span` for easier consumption:
```c++
  const util::span<value_type> values_span() const {
    return util::span(raw_values(), static_cast<size_t>(length_));
  }
```

### Component(s)

C++

**Comment by pitrou** [comment]
@bkietz @felipecrv

**Comment by mapleFU** [comment]
@jsjtxietian would you like to add this?

**Comment by jsjtxietian** [comment]
Will do.

**Comment by chrisjordansquire** [comment]
@jsjtxietian  - Was this done / is this task still open?

**Comment by jsjtxietian** [comment]
@chrisjordansquire Hi this task is still open. I went to one month vacation rightly after I took the task. I will do this likely before October.

**Comment by felipecrv** [comment]
What about null values?

**Comment by pitrou** [comment]
They would not be exposed here. The semantics would be similar to `raw_values()`. Perhaps there's a use case, perhaps not...
