### ISSUE TITLE
[R] Arrow package install - R binary version mismatch

### ISSUE THREAD

**Issue by meztez** [apache/arrow#37208]
### Describe the bug, including details regarding any error messages, version, and platform.

Error that you might  see : `*** Unable to find libcurl and openssl`

For systems with multiple R versions installed (Posit Connect, Posit Workbench...).

Installing arrow could results in unexpected behavior.

Say you run `install.packages("arrow")` using `/opt/R/4.3.1/bin/R` but your system R version (`which R`) is `/opt/R/4.3.0/bin/R`.
Or maybe R executable is not on your path.

This script https://github.com/apache/arrow/blob/8c4941b879670ec9dc3608b77637f44fddf32178/r/tools/nixlibs.R#L200 will use the system's R instead of /opt/R/4.3.1/bin/R or R will not be found resulting in an error.

Would it be possible to locate the currently running R executable and use that instead?

```r
runner <- "`R CMD config CXX17` `R CMD config CPPFLAGS` `R CMD config CXX17FLAGS` `R CMD config CXX17STD` -E -xc++"
```

```r
r_exec <- paste(R.home(component = "bin"), "R CMD config", sep="/")
runner <- sprintf("`%s CXX17` `%s CPPFLAGS` `%s CXX17FLAGS` `%s CXX17STD` -E -xc++", r_exec, r_exec, r_exec, r_exec)
```

Thanks

### Component(s)

R

**Comment by thisisnic** [comment]
Thanks for reporting this @meztez, sounds like a reasonable suggestion to me!
