### ISSUE TITLE
[C++] BufferReader should zero-copy if and only if given a Buffer, not a pointer and length

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#37212]
### Describe the enhancement requested

BufferReader can be constructed from a pointer and length:

https://github.com/apache/arrow/blob/0e677d27ae8ed489f2fa6f5e95b0e498319a887e/cpp/src/arrow/io/memory.cc#L277-L279

In that case, it will happily hand you a Buffer backed by that pointer:

https://github.com/apache/arrow/blob/0e677d27ae8ed489f2fa6f5e95b0e498319a887e/cpp/src/arrow/io/memory.cc#L353

However, I don't think the APIs make it clear that this ties the lifetime of any data read from the reader to the lifetime of the input. It would be clearer if it would copy in this case, and require you to explicitly construct BufferReader from a Buffer if you want to enable zero-copy.

### Component(s)

C++

**Comment by lidavidm** [comment]
There's a second issue here: BufferReader has no constructor for `std::string`, but the implicit conversion from string to string_view means you can still construct a BufferReader that is implicitly going to blow up on you.

**Comment by wgtmac** [comment]
The ctor of Buffer has a comment implies that `the passed memory must be kept alive through some other means`.

```
  /// \brief Construct from buffer and size without copying memory
  ///
  /// \param[in] data a memory buffer
  /// \param[in] size buffer size
  ///
  /// \note The passed memory must be kept alive through some other means
  Buffer(const uint8_t* data, int64_t size)
```

Does it mean `BufferReader` should inherit the same implication? The buffer itself cannot tell if it is owned or not after construction. If we have that info on hand, could we handle zero-copy better?

**Comment by lidavidm** [comment]
There's more discussion on the PR itself, FWIW

**Comment by mikelui** [comment]
FWIW I think there'd be a lot of value in an "examples" PR that has conventions for doing common patterns (e.g. given I own this buffer/input stream/message stream, how do I pass that ownership to the Arrow RecordBatch/Table I create?)

**Comment by mapleFU** [comment]
> e.g. given I own this buffer/input stream/message stream, how do I pass that ownership to the Arrow RecordBatch/Table I create?

Personally, I think `BufferReader` should always build from `std::string` or `std::shared_ptr<Buffer>`. Other constructor is deprecated, and when using `std::shared_ptr<Buffer>`, user should gurantee the lifetime of output buffer.

**Comment by lidavidm** [comment]
@mikelui There's https://arrow.apache.org/cookbook/ / https://github.com/apache/arrow-cookbook ; more examples would always be welcome!
