### ISSUE TITLE
[MATLAB] Add C++ `ARROW_MATLAB_EXPORT` symbol export macro

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#37228]
### Describe the enhancement requested

Currently, the main shared library used by the MATLAB interface - `libarrowproxy` - does not explicitly export any symbols.

This hasn't been a major issue so far based on our usage of these symbols - except for in one case - which was being able to define a template specialization of the `static` `make` function for `NumericArray<T>` in a C++ source file. To work around this, we decided to `inline` these template specializations.

However, this isn't an ideal solution because these functions shouldn't need to be inlined (and, in fact, this could have undesirable performance implications).

In addition, to enable the ability to write C++ unit tests for code in the "`Proxy` layer", we would need to export symbols from `libarrowproxy`.

### Component(s)

MATLAB

**Comment by sgilmore10** [comment]
take
