### ISSUE TITLE
[Ruby] Arrow::Table#initialize's raw_records document is wrong

### ISSUE THREAD

**Issue by kou** [apache/arrow#37239]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/blob/9fea4eedf5ceb06943d6443d08b00bc2fd248226/ruby/red-arrow/lib/arrow/table.rb#L148-L149

It should explain `raw_records` not `arrays`.

### Component(s)

Ruby

**Comment by kou** [comment]
@heronshoes @otegami Are you interested in this?

**Comment by otegami** [comment]
@kou 
Thank you for bringing up this issue. I've addressed it in this pull request: https://github.com/apache/arrow/pull/37261.
Whenever you're available, could you please take a look?
