### ISSUE TITLE
[MATLAB] Create an abstract `arrow.type.TemporalType` class

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#37234]
### Describe the enhancement requested

To simplify the implementation of `Time32Type`, `Time64Type`, `Date32Type`, and `Date64Type`, it would be helpful to create an abstract `arrow.type.TemporalType` class that the date and time types can inherit from.

As a first step, we can modify the implementation of `TimestampType` to inherit from `TemporalType`.

This mimics the class inheritance hierarchy from the C++ libraries.

### Component(s)

MATLAB

**Comment by sgilmore10** [comment]
take
