### ISSUE TITLE
[Python] Remove support for pickle5

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#37244]
### Describe the enhancement requested

`pickle5` is a backport of pickle protocol 5 features from python 3.8.3 to python 3.5, 3.6, and 3.7.[1]

Now that python 3.7 is end-of-life and not supported in Arrow, we can remove all usage of it.

[1] https://pypi.org/project/pickle5/

### Component(s)

Python

**Comment by chrisjordansquire** [comment]
Pull request https://github.com/apache/arrow/pull/37644 was created for this issue.

**Comment by chrisjordansquire** [comment]
@danepitkin  Tagging so you're aware of the above PR. Review would be greatly appreciated.
