### ISSUE TITLE
[Python][Parquet] Parquet Support write and validate CRC

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#37242]
### Describe the enhancement requested

Now, C++ Parquet API already supports CRC in reading and write.

Though system like S3 will ensure the storage data works well. But some data storage like HDD or SSD might corrupt. And network might provide bad result. So having CRC would helps.

Now it's better to has crc in Python code.

### Component(s)

Parquet, Python

**Comment by frazar** [comment]
I'll take this!
