### ISSUE TITLE
[Ruby] Add explicit the "csv" gem dependency for Ruby 3.4 or later

### ISSUE THREAD

**Issue by kou** [apache/arrow#37259]
### Describe the enhancement requested

The "csv" gem is a default gem for now but it'll be just a bundled gem in Ruby 3.4.
If red-arrow doesn't have an explicit the "csv" gem dependency, `require "csv"` may be failed with Ruby 3.4 or later.

Ruby master reports the following warning when we require red-arrow:

```console
$ ruby -v -e 'require "red-arrow"'
ruby 3.3.0dev (2023-08-17T21:17:31Z master 5d48825d55) [x86_64-linux]
.../lib/arrow/csv-loader.rb:18: warning: csv which will be not part of the default gems since Ruby 3.4.0
```

### Component(s)

Ruby

**Comment by kou** [comment]
@heronshoes @otegami Are you interested in this?

**Comment by heronshoes** [comment]
@kou I want to work on this. Thanks.
Is this issue is for Ruby 3.3.0 or 3.4?

**Comment by kou** [comment]
Thanks!
It's for 3.4 not 3.3.

**Comment by heronshoes** [comment]
I understood. Thank you!
