### ISSUE TITLE
[Python] Occasional error when reading metadata for Parquet files on S3 (in parallel)

### ISSUE THREAD

**Issue by thvasilo** [apache/arrow#37260]
### Describe the bug, including details regarding any error messages, version, and platform.

We have a process that reads the metadata for multiple files using `joblib`'s `threading` backend. Occasionally we observe the following error:

```
Traceback (most recent call last):  
[rest of call stack]
in get_rows_for_parquet_file    nrows = pq.read_metadata(  File "/usr/local/lib/python3.9/site-packages/pyarrow/parquet/core.py", line 3481, 
in read_metadata    file_ctx = where = filesystem.open_input_file(where)  File "pyarrow/_fs.pyx", line 770, 
in pyarrow._fs.FileSystem.open_input_file  File "pyarrow/error.pxi", line 144, 
in pyarrow.lib.pyarrow_internal_check_status  File "pyarrow/error.pxi", line 115, 
in pyarrow.lib.check_status

OSError: When reading information for key 'path/to/my/file' in bucket 'my-bucket': AWS Error UNKNOWN (HTTP status 503) during HeadObject operation: No response body.
``` 

I've tried setting the number of retries to 10 when creating the S3Filesystem but we still occasionally get this error. I would expect such an error if the file did not exist, but that's not the case here, so I'm wondering if a different error (like `503 S3 Slow Down`) is being hidden by the system.

Any ideas what could be the root case for such an error and if it's possible to surface it?

### Component(s)

Python

**Comment by mapleFU** [comment]
> AWS Error UNKNOWN (HTTP status 503) during HeadObject operation: No response body.

Seems that an AWS HeadObject Error? You can try to config some envs ( like https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html ) and config logs for in arrow?

**Comment by thvasilo** [comment]
Hi @mapleFU , thanks for your response. Yes `HeadObject` is the name of the [operation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html) being made (usually to check if a file exists), but error code 503 would indicate a service busy/slow down error (in the list of [S3 error code list](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) these are the only cases we can get 503).

I would expect a `HeadObject` operation to only fail when the file does not exist, which is not the case here.

Instead of `Slow down` or busy, we're getting `Unknown` back, so I'm wondering if https://github.com/apache/arrow/blob/94bd0d27326e8f3bfc0f612fcf604617402888ec/python/pyarrow/error.pxi#L115 is somehow losing the original error message? Is there a way to get the full original response (if any exists) like a fully verbose mode for PyArrow?

**Comment by mapleFU** [comment]
@thvasilo I was busy in previous days, sorry for late reply.

> would expect a HeadObject operation to only fail when the file does not exist, which is not the case here.

When you start to implement the framework on network, there must be some network error. You can config some network retry strategy to specify the retry policies.

> AWS Error UNKNOWN (HTTP status 503) during HeadObject operation

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-503-service-unavailable.html

Seems this might means error or config error in S3 or your client. I think it's better to retry that.

**Comment by thvasilo** [comment]
Right. I'm going to close this as I think it's on likely on the S3 side rather than arrow, thanks for the help.

**Comment by mapleFU** [comment]
Right. And arrow has `:S3RetryStrategy`, it might help in this case.
