### ISSUE TITLE
[Java] Start adding JSpecify nullability/nullness annotations

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#37286]
### Describe the enhancement requested

We should add nullability/nullness annotations to help users of our APIs (and us as developers) get better IDE and static analysis feedback. The roadblock has been that the 'old' standard, under javax, isn't suitable for modular Java libraries. [JSpecify][jspecify] is intended to supersede it, and recently has declared themselves ready for early usage: https://github.com/jspecify/jspecify/wiki/adoption

We should annotate some core APIs and see how it works out.

[jspecify]: https://github.com/jspecify/jspecify/

### Component(s)

Java

**Comment by davisusanibar** [comment]
Hi @lidavidm Based on this current issue, do you see any problems with continuing to implement JSpecify [Version Compatibility with JDK8 ](https://github.com/jspecify/jspecify/wiki/version-compatibility#issues-with-java-8)?

Is it possible to wait for Arrow Java JDK8 deprecation before continuing with this enhancement?
