### ISSUE TITLE
[C++] There is a problem with clang-format regular matching.

### ISSUE THREAD

**Issue by Light-City** [apache/arrow#37299]
### Describe the bug, including details regarding any error messages, version, and platform.

On my mac system, the version information is

```
➜  ~ clang-format -version
Homebrew clang-format version 16.0.4
```

if we use `^clang-format`, we can't match.

```
find_clang_tool(clang-format CLANG_FORMAT_BIN
                "^clang-format version ${ARROW_CLANG_TOOLS_VERSION_ESCAPED}")
```

### Component(s)

C++

**Comment by mapleFU** [comment]
Isn't that matches[1] in find_clang_tool[2]?

[1] https://cmake.org/cmake/help/latest/command/if.html#matches
[2] https://github.com/apache/arrow/blob/main/cpp/cmake_modules/FindClangTools.cmake#L61C38-L61C59

**Comment by Light-City** [comment]
> https://github.com/apache/arrow/blob/main/cpp/cmake_modules/FindClangTools.cmake#L61C38-L61C59

I got

```
-- clang-tidy found at /usr/local/opt/llvm/bin/clang-tidy
-- clang-format found, but version did not match "^clang-format version 16"
-- clang-format 16 not found
```

**Comment by Light-City** [comment]
cmake version is

cmake version 3.18.2

**Comment by Light-City** [comment]
I think it is prefix Homebrew
