### ISSUE TITLE
[C++][Docs] cpp-tutorial-example fails building

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#37308]
### Describe the bug, including details regarding any error messages, version, and platform.

The `cpp-tutorial-example` Crossbow task fails building, as seen here:
https://github.com/ursacomputing/crossbow/actions/runs/5937066578

### Component(s)

C++, Documentation

**Comment by pitrou** [comment]
cc @kou @raulcd @ksuarez1423

**Comment by raulcd** [comment]
> Also this task doesn't seem to be run as part of the nightly builds, which is why we didn't notice it breaking.

We should probably rename it to `example-cpp-tutorial` so it's run as part of the nightly tests along with the rest of `example-*` tasks: https://github.com/apache/arrow/blob/main/dev/tasks/tasks.yml#L164
