### ISSUE TITLE
[Python][CI][Packaging] Enable ORC on Windows Appveyor CI and Windows wheels for pyarrow

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#37381]
### Describe the enhancement requested

As found on: https://github.com/apache/arrow/issues/36026#issuecomment-1691625160
It does seem we are not testing pyarrow with ORC enabled on Windows and we are not enabling it on our Windows  wheels.
We should enable it.

### Component(s)

Continuous Integration, Packaging, Python

**Comment by wgtmac** [comment]
Thanks for doing this! Let me know if a specific error or failure is caught on the ORC side.

**Comment by jorisvandenbossche** [comment]
Resolved by https://github.com/apache/arrow/pull/40609
