### ISSUE TITLE
[C++] Make public version of StreamDecoderImpl-like class

### ISSUE THREAD

**Issue by MrLolthe1st** [apache/arrow#37429]
### Describe the enhancement requested

It is useful to use `StreamDecoderImpl` outside `reader.cc`.
For example, someone produces stream of data like that:
```
<SCHEMA>
<RECORD BATCH 0>
...
<RECORD BATCH n - 1>
<EOS> (*)
<SCHEMA>
<DICTIONARY 0>
...
<DICTIONARY k - 1>
<RECORD BATCH 0>
...
<RECORD BATCH n - 1>
<EOS>
<SCHEMA>
<RECORD BATCH 0>
...
<RECORD BATCH n - 1>
<EOS>
```

StreamDecoder in that way will ignore all payload after (*). But in way where StreamDecoderImpl-like class is open to use, I can use OnMessageDecoded(..) method and delegate message decoding in outer scope and when EOS coming, reseting StreamDecoderImpl to new.

### Component(s)

C++

**Comment by kou** [comment]
How about adding `arrow::ipc::StreamDecoder::Reset()` instead of exporting `StreamDecoderImpl`?

**Comment by MrLolthe1st** [comment]
> How about adding `arrow::ipc::StreamDecoder::Reset()` instead of exporting `StreamDecoderImpl`?

It's just one approach. In addition to `arrow::ipc::StreamDecoder::Reset()` must be added `arrow::ipc::StreamDecoder::OnMessageDecoded(...)`, because ` arrow::ipc::StreamDecoder::Consume(...)` doesn't returns amount of readed bytes, so anyway hight-level control of messages must be provided to feed `StreamDecoder` messages one-by-one.
For example, I'm trying to feed `StreamDecoder` with payload looks like that:
```
<RECORD BATCH n - 1>
<EOS>
<SCHEMA>
<DICTIONARY 0>
```

In that way I'm must determine where message with schema is located (to feed resetted `StreamDecoder` with new messages, starting with schema message).

Another approach is to make `Consume()` return not just status, but amount of bytes readed before EOS.

**Comment by kou** [comment]
How about calling `arrow::ipc::StreamDecoder::Reset()` in a listener?

```cpp
class EndlessListener : public arrow::ipc::Listener {
 public:
  explicit EndlessListener() : arrow::ipc::Listener(), decoders_() {}

  arrow::Status OnEOS() override {
    for (auto decoder : decoders_) {
      ARROW_RETURN_NOT_OK(decoder->Reset());
    }
    return arrow::Status::OK();
  }

  void AddDecoder(arrow::ipc::StreamDecoder *decoder) {
    decoders_.push_back(decoder);
  }

 private:
  std::vector<arrow::ipc::StreamDecoder> decoders_;
};

auto listener = std::make_shared<EndlessListener>();
arrow::ipc::StreamDecoder decoder (listener);
listener->AddDecoder(*decoder);
decoder.Consume(...);
```

**Comment by MrLolthe1st** [comment]
That's awesome!

**Comment by MrLolthe1st** [comment]
@kou That's not all: after return from OnEOS() and from OnEOS() at StreamDecoder, we'll back in old MessageReader, but after Reset() call, we're destroyed it. And since old MessageReader hadn't been reseted, MessageReader still in EOS state and will ingore all payload after EOS message.
