### ISSUE TITLE
On ubuntu:bionic can not install libarrow-acero-dev via apt

### ISSUE THREAD

**Issue by jasinliu** [apache/arrow#37452]
### Describe the usage question you have. Please include as many useful details as  possible.

When I try to use apt install arrow on ubuntu:bionic docker following the instructions, I can install libarrow-dev, but I cann't install libarrow-acero-dev. Why missing it, and how to fix it?

Also, the version of arrow is 11.0.0, not the newest.

### Component(s)

C++

**Comment by assignUser** [comment]
In 11.0.0 acero was still part of the core lib so libarrow-acero-dev does not exists for it (see https://github.com/apache/arrow/issues/15280). I assume you looked at the latest install instructions? The doc page has a version selector you can use to select the docs matching the version you want to install :)
