### ISSUE TITLE
Hadoop classpath discovery broken in 0.12 when HADOOP_HOME is a symlink

### ISSUE THREAD

**Issue by keyaaron** [apache/arrow#3748]
CLASSPATH discovery was recently changed in https://github.com/apache/arrow/commit/d91185000945cec96abad41a230d05d3cdefff93 to resolve ARROW-2113 and ARROW-3768.

Specifically, the logic used to find all jars under HADOOP_HOME uses the find command directly https://github.com/apache/arrow/blob/d91185000945cec96abad41a230d05d3cdefff93/python/pyarrow/hdfs.py#L144
This will not work when HADOOP_HOME is a symlink, in which case '-L' needs to  be passed to the find command.

CLASSPATH can still be set explicitly, but this is a change in behavior as HADOOP_HOME symlinks worked without issue before.

**Comment by emkornfield** [comment]
Hi @keyaaron,
I opened a [JIRA-4802](https://issues.apache.org/jira/browse/ARROW-4802) to track this.  Would you be willing to submit a patch?

**Comment by chenfj068** [comment]
This issue has been resolved @emkornfield  we can close it.
