### ISSUE TITLE
[R][CI] Nightly CI jobs failing with Thrift error

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#37535]
### Describe the bug, including details regarding any error messages, version, and platform.

Multiple nightly CI jobs, including [test-r-depsource-system](https://github.com/ursacomputing/crossbow/actions/runs/6067632674/job/16459553232) and [test-r-dev-duckdb](https://github.com/ursacomputing/crossbow/actions/runs/6067630702/job/16459549219) are failing with a Thrift error:

e.g.
```
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/arrow/r/check/arrow.Rcheck/00LOCK-arrow/00new/arrow/libs/arrow.so':
  /arrow/r/check/arrow.Rcheck/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: _ZTIN6apache6thrift8protocol9TProtocolE
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/arrow/r/check/arrow.Rcheck/arrow’
```

Failing jobs: 

- test-r-depsource-system
- test-r-dev-duckdb
- test-r-gcc11
- test-r-gcc-12
- test-r-rhub-ubuntu-22.04

### Component(s)

R

**Comment by thisisnic** [comment]
I've submitted a crossbow build on one of the commits that may or may not be the cause: https://github.com/apache/arrow/pull/37399#issuecomment-1708261906

**Comment by thisisnic** [comment]
@kou Do you mind taking a look at this? I think it might be due to the changes in #37399 as the nightly builds started failing after this point

**Comment by kou** [comment]
Oh, sorry.
I'll take a look at this.

**Comment by kou** [comment]
Note that DuckDB's R bindings were moved recently: https://github.com/duckdb/duckdb/pull/8793
We need to update our CI code.

**Comment by thisisnic** [comment]
> Note that DuckDB's R bindings were moved recently: [duckdb/duckdb#8793](https://github.com/duckdb/duckdb/pull/8793) We need to update our CI code.

Thanks for highlighting this, I'll open an issue
