### ISSUE TITLE
to_pandas(date_as_object=False) returns different dtype in pyarrow 13.0.0

### ISSUE THREAD

**Issue by 0x26res** [apache/arrow#37545]
### Describe the bug, including details regarding any error messages, version, and platform.

With `pyarrow==12.0.0`:

```python
import pyarrow as pa
import datetime
import numpy as np

table = pa.table({"date": pa.array([datetime.date(2023, 1, 1)], type=pa.date32())})
assert table.to_pandas(date_as_object=False)["date"].dtype == np.dtype("<M8[ms]")
```

With `pyarrow==13.0.0` I get `np.dtype("<M8[ms]")`

In my opinion, since the default precision for timestamp in arrow is "ns" it should stay the same when converting dates (though obviously you lose range).

Alternatively would there be a way to use the `types_mapper` argument to specify the precision? I can't get it to work:
```
>>> assert table.to_pandas(types_mapper={pa.date32() : np.dtype("<M8[ns]")}.get)["date"].dtype
ValueError: This column does not support to be converted to a pandas ExtensionArray
```

Lastly, I can't figure out from the release note of 13.0.0 which change caused that regression.

### Component(s)

Python

**Comment by AlenkaF** [comment]
Yes, correct. This behaviour changed from `pyarrow` version `12.0.1` to `13.0.0`. Here is the PR that changed it: https://github.com/apache/arrow/pull/35656
From the PR:

> This PR adds support for the following Arrow -> Pandas conversions, which previously all defaulted to datetime64[ns] or datetime64[ns, <TZ>]:
> date32 -> datetime64[ms]
> date64 -> datetime64[ms]
> ...

Also mentioned in the PR description:

> Arrow-to-pandas default conversion behavior will change when users have pandas >= 2.0, but a legacy option is exposed to provide backwards compatibility.

So in your reprex you could do:

```python
>>> pa.__version__
'13.0.0'
>>> table.to_pandas(date_as_object=False, coerce_temporal_nanoseconds=True)["date"].dtype
dtype('<M8[ns]')
```

But note the comment: https://github.com/apache/arrow/blob/a526ba697d4e3f009731bebda6838b41899051e3/python/pyarrow/array.pxi#L782-L788

**Comment by 0x26res** [comment]
Thanks @AlenkaF, `coerce_temporal_nanoseconds` gives me `timestamp[ns]`. 

Also I've figure I was using types_mapper wrong, I should be doing:
```python
table.to_pandas(types_mapper={pa.date32(): pd.ArrowDtype(pa.timestamp('ns'))}.get)
```

I'll close the issue.
