### ISSUE TITLE
[Python] Compatibility with numpy 2.0 (removal of np.unicode_)

### ISSUE THREAD

**Issue by martinfleis** [apache/arrow#37574]
### Describe the bug, including details regarding any error messages, version, and platform.

Numpy has deprecated `np.unicode_` and removed it in an upcoming 2.0 release. Current nightly builds do not have `np.unicode_` which results in an incompatibility between pyarrow main and numpy main due to this mapping:

https://github.com/apache/arrow/blob/13f0cd8ee44833efbced05c8505de12f9f02f235/python/pyarrow/pandas_compat.py#L87-L102

and possibly would also fail on this one

https://github.com/apache/arrow/blob/13f0cd8ee44833efbced05c8505de12f9f02f235/python/pyarrow/pandas_compat.py#L1008-L1018

numpy now raises `AttributeError: `np.unicode_` was removed in the NumPy 2.0 release. Use `np.str_` instead.` See the [full traceback](https://github.com/geopandas/geopandas/actions/runs/6086861805/job/16514196822?pr=2996#step:5:4662) in the geopandas CI.

### Component(s)

Python

**Comment by AlenkaF** [comment]
Thank you for bringing this to our attention @martinfleis !

**Comment by graingert** [comment]
it looks like the nightly CI job is using  https://pypi.anaconda.org/scipy-wheels-nightly/simple as opposed to https://pypi.anaconda.org/scientific-python-nightly-wheels/simple per https://scientific-python.org/specs/spec-0004/ so didn't get the nightly update to numpy v2

https://github.com/apache/arrow/blob/dd8734dc8ff21e7f8463b239e800aeac0ddcb764/ci/scripts/install_pandas.sh#L31

**Comment by graingert** [comment]
There's a handful of other removals where pyarrow is impacted: np.sctypes and np.NaN
