### ISSUE TITLE
[MATLAB] Add `toMATLAB` method to `arrow.array.ChunkedArray` class

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#37597]
### Describe the enhancement requested

Currently, there is no way to easily convert an `arrow.array.ChunkedArray` into a corresponding MATLAB array, other than (1) manually iterating chunk by chunk, (2) calling `toMATLAB` on each chunk, and then (3) concatenating all of the converted chunks together into one contiguous MATLAB array.

It would be helpful to add a `toMATLAB` method to `arrow.array.ChunkedArray` that abstracts away all of these steps.

### Component(s)

MATLAB

**Comment by kevingurney** [comment]
Added label `good-second-issue`.

**Comment by sgilmore10** [comment]
take
