### ISSUE TITLE
[Python] How to not filter null values from a list

### ISSUE THREAD

**Issue by r-priyam** [apache/arrow#37625]
### Describe the usage question you have. Please include as many useful details as  possible.

I have a 2D array with dictionaries in it and I want to flatten the values of it using the first dictionary and _I do NOT want to drop NULLS_. For example the expected output:
```py
import pyarrow as pa
pa.array([[{'key': 1}], None, [{'key': 2}]]).flatten()

>>> [1, None, 2]
```
However, I am getting output as `[1, 2]` which I don't want. 

The end goal is to use `pa.compute.coalesce` on 2 lists. For example, If I have 3 arrays like this -

```py
import pyarrow as pa

one = pa.array([[{'key': 1}], None, None])
two = pa.array([None, 2, None])
three = pa.array([None, None, 3])

# The output should be:
>>> [1, 2, 3] # when using pa.compute.coalesce
```
But I am not able to achieve this since `.flatten` is removing the `null` values

### Component(s)

Parquet, Python

**Comment by js8544** [comment]
> I have a 2D array with dictionaries in it and I want to flatten the values of it using the first dictionary 

I don't see any dictionary in your example though. Am I missing something? The array you provided is of type `list<item: struct<key: int64>>`
```python
>>> print(pa.array([[{'key': 1}], None, [{'key': 2}]]).type)
list<item: struct<key: int64>>
```
If you want the flattened result to contain a `null` for null lists, you can map the `null` list to a list containing a single `null`
```python
>>> arr = pa.array([[1], None, [2]])
>>> arr = pa.compute.coalesce(arr, pa.scalar([None], type=pa.list_(pa.int64())))
>>> arr
list<item: struct<key: int64>>
[
  [
    1
  ],
  [
    null
  ],
  [
    2
  ]
]
>>> arr.flatten()
<pyarrow.lib.Int64Array object at 0xffff61b29300>
[
  1,
  null,
  2
]
```

Does this work for you?

**Comment by r-priyam** [comment]
Hi @js8544, Thank you for getting back.
>I don't see any dictionary in your example though. Am I missing something? The array you provided is of type list<item: struct<key: int64>>

Apologies, you're right, my bad.

When I do -
```py
>>> arr = pa.array([[{'key': 1}], None, None])
>>> pa.compute.coalesce(arr, pa.scalar([None], type=pa.list_(pa.struct([('key', pa.int64())])))).flatten()
<pyarrow.lib.StructArray object at 0x12f4a4b20>
-- is_valid:
  [
    true,
    false,
    false
  ]
-- child 0 type: int64
  [
    1,
    null,
    null
  ]
```
It gives me exactly what I want. But then when I do -
```py
>>> arr = pa.compute.coalesce(pa.array([[{'key': 1}], None, None]), pa.scalar([None], type=pa.list_(pa.struct([('key', pa.int64())])))).flatten()
>>> arr_two = pa.array([None, 2, None])
>>> arr_three = pa.array([None, None, 3])
>>> pa.compute.coalesce(arr, arr_two, arr_three)
# It throws
File "pyarrow/_compute.pyx", line 367, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Function 'coalesce' has no kernel matching input types (struct<key: int64>, int64, int64)
```
In last my aim is to get output in a list `[1, 2, 3]`. Any suggestions on this please?

**Comment by js8544** [comment]
I don't have my computer with me now, but I believe `pyarrow.compute.struct_field` will be helpful. You need to extract the key field from your struct array.

**Comment by r-priyam** [comment]
Thank you @js8544 - sorry, the doc for it seems to be a bit confusing, without having an example or anything it's really a trick for me to try it out. I can't find any relevance around it though for it.

**Comment by js8544** [comment]
```python
>>> arr
<pyarrow.lib.StructArray object at 0xffff63d20ac0>
-- is_valid:
  [
    true,
    false,
    true
  ]
-- child 0 type: int64
  [
    1,
    null,
    2
  ]
>>> pa.compute.struct_field(arr, ['key'])
<pyarrow.lib.Int64Array object at 0xffff61c4e980>
[
  1,
  null,
  2
]
```

**Comment by r-priyam** [comment]
Many thanks @js8544 - This works. Closing this issue 🙏🏼
