### ISSUE TITLE
[Python][Parquet] pyarrow.lib.ArrowInvalid: Expected to read 827474256 metadata bytes, but only read 6635

### ISSUE THREAD

**Issue by VARSHAJOSHY** [apache/arrow#37631]
### Describe the usage question you have. Please include as many useful details as  possible.

When I tried to use RecordBatchStreamReader for reading parquet stream, I am getting this error.
data = parquet byte stream
reader = pa.RecordBatchStreamReader(data)

len(data) is 6639

### Component(s)

Parquet

**Comment by kou** [comment]
You can't use `pyarrow.RecordBatchStreamReader()` for Parquet data.
You can use `pyarrow.parquet.read_table()`.
See https://arrow.apache.org/docs/python/parquet.html for details.
