### ISSUE TITLE
[pyarrow-0.11.1] ImportError 

### ISSUE THREAD

**Issue by lalessan** [apache/arrow#3763]
I installed pyarrow using conda-forge:

    conda install -q -y -c conda-forge pyarrow

    The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arrow-cpp-0.11.1           |   py27h3bd774a_0         6.1 MB  conda-forge
    blas-1.0                   |              mkl           6 KB  defaults
    boost-cpp-1.68.0           |    h11c811c_1000        20.5 MB  conda-forge
    bzip2-1.0.6                |    h14c3975_1002         415 KB  conda-forge
    intel-openmp-2019.1        |              144         885 KB  defaults
    mkl-2019.1                 |              144       204.6 MB  defaults
    mkl_fft-1.0.10             |   py27h14c3975_1         158 KB  conda-forge
    mkl_random-1.0.2           |   py27h637b7d7_2         331 KB  conda-forge
    numpy-1.15.4               |   py27h7e9f1db_0          47 KB  defaults
    numpy-base-1.15.4          |   py27hde5b4d6_0         4.2 MB  defaults
    parquet-cpp-1.5.1          |                3           3 KB  conda-forge
    pyarrow-0.11.1             |py27hbbcf98d_1002         1.9 MB  conda-forge
    scikit-learn-0.20.2        |   py27hd81dba3_0         5.7 MB  defaults
    scipy-1.2.1                |   py27h7c811a0_0        17.6 MB  defaults
    ------------------------------------------------------------
                                           Total:       262.5 MB

    The following NEW packages will be INSTALLED:

      arrow-cpp          conda-forge/linux-64::arrow-cpp-0.11.1-py27h3bd774a_0
      boost-cpp          conda-forge/linux-64::boost-cpp-1.68.0-h11c811c_1000
      bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
      intel-openmp       pkgs/main/linux-64::intel-openmp-2019.1-144
      mkl                pkgs/main/linux-64::mkl-2019.1-144
      mkl_fft            conda-forge/linux-64::mkl_fft-1.0.10-py27h14c3975_1
      mkl_random         conda-forge/linux-64::mkl_random-1.0.2-py27h637b7d7_2
      numpy-base         pkgs/main/linux-64::numpy-base-1.15.4-py27hde5b4d6_0
      parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-3
     pyarrow            conda-forge/linux-64::pyarrow-0.11.1-py27hbbcf98d_1002
 
The following packages will be SUPERSEDED by a higher-priority channel:

      blas                       conda-forge::blas-1.1-openblas --> pkgs/main::blas-1.0-mkl
      numpy              conda-forge::numpy-1.16.1-py27_blas_o~ --> pkgs/main::numpy-1.15.4-py27h7e9f1db_0
      scikit-learn       conda-forge::scikit-learn-0.20.2-py27~ --> pkgs/main::scikit-learn-0.20.2-py27hd81dba3_0
      scipy              conda-forge::scipy-1.2.1-py27_blas_op~ --> pkgs/main::scipy-1.2.1-py27h7c811a0_0

And I get this error on import: 

    >>> import pyarrow
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/mnt/opt/miniconda2/lib/python2.7/site-packages/pyarrow/__init__.py", line 54, in <module>
        from pyarrow.lib import cpu_count, set_cpu_count
    ImportError: /mnt/opt/miniconda2/lib/python2.7/site-packages/pyarrow/lib.so: undefined symbol: _ZNK5arrow11RecordBatch11column_nameB5cxx11Ei

Can you help me? Thanks!

**Comment by xhochy** [comment]
Please recreate your installation using either packages all from `defaults` or from `conda-forge`. Mixing both is not supported. Furthermore, you seem to get an old version of pyarrow. Does the problem still persist using `pyarrow==0.12.1`?

Please open an issue at https://issues.apache.org/jira/projects/ARROW if this still persists.
