### ISSUE TITLE
[C++] Enhance arrow::Datum::ToString

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#37643]
### Describe the enhancement requested

As document says, `::arrow::Datum::ToString` only prints the "type" of tagged enum:

```
  /// \brief Return a string representation of the kind of datum stored.
  std::string ToString() const;
```

Can we enhance it and try call `ToString` for `RecordBatch`, `Table`, ...etc?

### Component(s)

C++

**Comment by kou** [comment]
+1
