### ISSUE TITLE
[R] "object 'input' not found" in R Shiny apps when passed to function in filtering arrow object

### ISSUE THREAD

**Issue by giocomai** [apache/arrow#37645]
### Describe the bug, including details regarding any error messages, version, and platform.

The `input` object used in Shiny apps does not seem to be fully available to arrow when passed to a function which is used for filtering.

Here is a basic Shiny app that can be used to reproduce this issue:

```
library("shiny")
library("arrow")
ui <- fluidPage(
  
  titlePanel("Arrow issue"),
  
  sidebarLayout(
    sidebarPanel(
      textInput(inputId = "pattern",
                value = "Lotus Europa",
                label = "pattern")
    ),
    mainPanel(
      h3("Arrow with pattern passed to `filter(str_detect)`:"),
      tableOutput("arrow_table_detect"),
      h3("Arrow table with pattern passed to `filter():"),
      tableOutput("arrow_table"),
      h3("Plain table with pattern passed to `filter(str_detect)` :"),
      tableOutput("plain_table")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$arrow_table_detect <- renderTable({
    arrow_table(mtcars |> 
                  tibble::rownames_to_column(var = "name")) |> 
      dplyr::filter(stringr::str_detect(string = name,
                                        pattern = input$pattern)) |> 
      dplyr::collect()
  })
  
  output$arrow_table <- renderTable({
    arrow_table(mtcars |> 
                  tibble::rownames_to_column(var = "name")) |> 
      dplyr::filter(name == input$pattern) |> 
      dplyr::collect()
  })
  
  
  output$plain_table <- renderTable({
    mtcars |> 
      tibble::rownames_to_column(var = "name") |> 
      dplyr::filter(stringr::str_detect(string = name,
                                        pattern = input$pattern)) 
  })
  
}

shinyApp(ui = ui, server = server)

```

Screenshot of the result:
![Screenshot from 2023-09-11 00-55-27](https://github.com/apache/arrow/assets/11276752/45a0cd55-5b48-4204-be5e-7c939d39a580)

If input object is passed directly to `filter`, then it does work. If it is passed to e.g. `str_detect()` inside a `filter()`, then it throws the error: "object 'input' not found" 

Collecting the arrow object fixes the issue, but then we're not using arrow any more.

Bug found with the current arrow version 13.

### Component(s)

R

**Comment by thisisnic** [comment]
Thanks for reporting this @giocomai!  

I think this may be a bug, which is fixed in the dev version of arrow:  #36784

As a workaround for now, if you put the `!!` (bang bang) in front of `input$pattern`, it'll evaluate the content of `input$pattern` correctly, and return the expected result.  Let me know if this works for you!

**Comment by giocomai** [comment]
Thank you for troubleshooting this further.

- using `!!` (bang bang) prevents this issue on the current released version
- the issue is still present in the version that gets installed with `arrow::install_arrow(nightly = TRUE)` (at least on Fedora Linux, this seems to be still 13.0.0)
- but indeed, the issue is fixed with the version I get with `remotes::install_github("apache/arrow/r", build = FALSE)` (currently, `arrow-13.0.0.9000`)

I wrongly assumed this was a Shiny-specific issue, but indeed, it seems to be the very same issue you highlighted. Thanks again!

**Comment by thisisnic** [comment]
Thanks for that extra info there too! Our nightly builds are a bit behind because of an issue that should be fixed shortly, but I'm glad you got it working via installing from the main branch.
