### ISSUE TITLE
Connecting to HDFS through a proxy?

### ISSUE THREAD

**Issue by dclong** [apache/arrow#3765]
Does pyarrow support connecting to HDFS through a proxy?

**Comment by wesm** [comment]
It does if libhdfs does. Do you know?

**Comment by dclong** [comment]
I never used libhdfs before and I don't know whether it supports proxy. However, I do know that it's fairly easily to set proxy for JVM. libhdfs is implemented in C but the doc mentions JNI which makes me feel like that it's called via JVM. Do you know whether pyarrow invokes libhdfs via JVM?

**Comment by wesm** [comment]
Yes it does

**Comment by emkornfield** [comment]
Sounds like the conversation is over.  If this is still an issue please open a JIRA or contact dev@ mailing list.
