### ISSUE TITLE
[Python][Dataset] Unable to read dataset from cloud storage

### ISSUE THREAD

**Issue by swyatt7** [apache/arrow#37667]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi all, I am trying to read a hive partitioned parquet dataset from cloud storage and am running into some issues.

The dataset is partitioned with the structure:
```
/path/to/dataset/ ->
   metadata_file.json
   metadata_file.csv
   metadata_file.fits
   partition_var1=X/ -> 
      partition_var2=Y/ ->
         partition_var3=Z.parquet
```

Locally, loading this with `pyarrow.dataset.dataset(...)` gives zero issues. Once I uploaded it to our `abfs` storage container, and attempted to read it with that filesystem, I began receiving the error: 
```
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path '/path/to/dataset/metadata_file.json', which is outside base dir '/path/to/dataset/'
```

I've even tried loading it without the metadata files in the base dir, but then it descends into the partitions and begins complaining about the parquet files themselves being outside the base dir. 

Here is the code I am using to read in the files:

```python
import os
import fsspec
import pyarrow.dataset as pds

storage_options = {
      "account_key" : os.environ.get("ABFS_ACCOUNT_KEY"),
      "account_name" : os.environ.get("ABFS_ACCOUNT_NAME")
  }

file_system = fsspec.filesystem("abfs", **storage_options)
dataset_dir = "/path/to/dataset"
ignore_prefixes = [
    "metadata_file"
]

dataset = pds.dataset(
    dataset_dir,
    filesystem=file_system,
    partitioning="hive",
    exclude_invalid_files=True,
    format="parquet",
    ignore_prefixes=ignore_prefixes,
)
```

Any help would be appreciated. 

pyarrow version: 12.0.1
fsspec version: 2023.9.0

### Component(s)

Parquet, Python

**Comment by mapleFU** [comment]
@swyatt7 What kind of OS are you using?

```c++
bool IsAncestorOf(std::string_view ancestor, std::string_view descendant) {
  ancestor = RemoveTrailingSlash(ancestor);
  if (ancestor == "") {
    // everything is a descendant of the root directory
    return true;
  }

  descendant = RemoveTrailingSlash(descendant);
  if (!StartsWith(descendant, ancestor)) {
    // an ancestor path is a prefix of descendant paths
    return false;
  }

  descendant.remove_prefix(ancestor.size());

  if (descendant.empty()) {
    // "/hello" is an ancestor of "/hello"
    return true;
  }

  // "/hello/w" is not an ancestor of "/hello/world"
  return StartsWith(descendant, std::string{kSep});
}
```

I guess this function might related to specific-os?

**Comment by mapleFU** [comment]
I strongly suspect that when user is using windows, the path handling for dataset is incorrect 🤔

**Comment by swyatt7** [comment]
I'm not on Windows. I'm on mac OS which emulates a POSIX filesystem.

I've realized when you pass in a filesystem argument into any pyarrow api with a URI, you must strip the any leading `/`. So when doing this.

```python
dataset_dir = "/path/to/dataset/" #doesn't work

dataset_dir = "path/to/dataset/" #does work
```

I'm closing this issue.
