### ISSUE TITLE
[R] R package arm64 build fails due to missing brotlienc-static

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#37685]
### Describe the bug, including details regarding any error messages, version, and platform.

See r-binary-packages nightlies: https://github.com/ursacomputing/crossbow/actions/runs/6156959279/job/16707483446#step:13:7536

### Component(s)

R

**Comment by kou** [comment]
https://github.com/Homebrew/homebrew-core/pull/140964 and https://github.com/google/brotli/pull/655 will be related.

It seems that Brotli 1.1.0 doesn't support building both of shared libraries and static libraries. And Homebrew's brotli formula does nothing. So brotli formula 1.1.0 doesn't include static libraries of Brotli. And we hard-code `-lbrotlienc-static -lbrotlidec-static -lbrotlicommon-static`:
https://github.com/apache/arrow/blob/15a8ac3ce4e3ac31f9f361770ad4a38c69102aa1/r/tools/autobrew#L65

**Comment by assignUser** [comment]
Ah thanks for the investigation! As this builds the R package we can not link shared... but we are also getting rid of the autobrew path so I am not sure how much sense it makes to spend time on this?

**Comment by assignUser** [comment]
(we should be able to use bundled brotli no?)

**Comment by assignUser** [comment]
#37923 does not have this problem so I am closing this as not planned.
