### ISSUE TITLE
Arrow Flight SQL Python Server

### ISSUE THREAD

**Issue by marsupialtail** [apache/arrow#37700]
### Describe the enhancement requested

Is there Python bindings to implement a FlightSQL server?

@lidavidm 

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
There aren't.

**Comment by marsupialtail** [comment]
Plans to add one?

**Comment by lidavidm** [comment]
I'm not aware of anyone actively working on it, but contributions towards that are welcome.

**Comment by marsupialtail** [comment]
I will just use c++. Thank you
