### ISSUE TITLE
[Java] Using an Iterator/Iterable/Stream to provide objects to a Java Collection for testing assertions

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#37728]
### Describe the enhancement requested

Use an Iterator/Iterable/Stream to provide objects into a Java Collection and use it for standard assertions.

Improve this method of comparing values of Vector Value objects, for example:

```
        assertTrue(reader.getVectorSchemaRoot().getVector("id").toString().equals("[19, 1, 11]"));
        assertTrue(reader.getVectorSchemaRoot().getVector("name").toString()
            .equals("[value_19, value_1, value_11]"));
```

### Component(s)

Java

**Comment by lidavidm** [comment]
So to clarify, the idea is that we could build some wrapper/adapter over a Vector (or VectorSchemaRoot) to support iteration over it as Java objects, as a more convenient (if less performant) version of the Reader classes. Then you could easily turn that into a testing API.

**Comment by lidavidm** [comment]
Issue resolved by pull request 41895
https://github.com/apache/arrow/pull/41895
