### ISSUE TITLE
[Go] how to run parameterized queries?

### ISSUE THREAD

**Issue by RPAraujo** [apache/arrow#37737]
### Describe the usage question you have. Please include as many useful details as  possible.

Can't find examples, or documentation, about how to run parameterized queries.
Going through the code I can only find examples like this `"SELECT * FROM intTable WHERE keyName LIKE ?"` which only allows for one placeholder.

I need to be able to run queries like: `SELECT * FROM $1 WHERE ASSET_ID = $2 LIMIT 1`

Can someone point me in the right direction?

Thanks

### Component(s)

Go

**Comment by zeroshade** [comment]
Just to confirm, this is using the FlightSQL driver?

**Comment by RPAraujo** [comment]
Yes, I can show you my code:
```
func (svc *DpeService) ExecuteParameterizedQuery(query string, args []any) {
	config := flightsql.DriverConfig{
		Address: fmt.Sprintf("%s:%s", svc.Host, svc.Port),
		Token:   "",
		Timeout: 10 * time.Second,
		Params:  make(map[string]string),
	}
	db, err := sql.Open("flightsql", config.DSN())
	if err != nil {
		log.Fatalf("open failed: %v", err)
	}
	defer db.Close()

	stmt, err := db.Prepare(query)
	if err != nil {
		log.Fatalf("query failed: %s", err)
	}
	rows, err := stmt.Query(args...)
	if err != nil {
		log.Fatalf("query failed: %s", err)
	}
	defer rows.Close()

	columns, err := rows.Columns()
	if err != nil {
		log.Fatalf("getting columns failed: %s", err)
	}
	log.Println("columns:", columns)

	// Prepare the list of data-points according to the received row
	columnData := make([]interface{}, len(columns))
	columnDataPtr := make([]interface{}, len(columns))

	for i := range columnData {
		columnDataPtr[i] = &columnData[i]
	}

	idx := 0
	for rows.Next() {
		idx++
		if err := rows.Scan(columnDataPtr...); err != nil {
			log.Fatalf("scanning row %d failed: %s", idx, err)
		}
		for j := range columns {
			fmt.Printf("%.22v    ", columnData[j])
		}
		fmt.Println()
	}

	if err := rows.Err(); err != nil {
		log.Fatalf("iterating rows failed: %s", err)
	}

}
```

Trying to run the query:
```
func (svc *assetService) GetSensorsByAssetId(assetId string) {
	query := `SELECT * FROM $1 WHERE ASSET_ID = $2 LIMIT 1`

	args := []any{
		svc.assetType,
		id.String(),
	}
	svc.dpeSvc.ExecuteParameterizedQuery(query, args)
}
```

With this code I get the error:
`SQL error: ParserError(\"Expected identifier, found: $1\")`

**Comment by zeroshade** [comment]
Can you try using the ADBC sqldriver for flightsql (https://pkg.go.dev/github.com/apache/arrow-adbc/go/adbc/sqldriver/flightsql) and see if that works properly with the parameterized queries? 

@srebhan Would you mind looking into this as you contributed the FlightSQL driver here and have been working on it? Thanks!

**Comment by RPAraujo** [comment]
Changed to the ADBC driver:
```
db, err := sql.Open("flightsql", fmt.Sprintf("uri=grpc://%s:%s", svc.Host, svc.Port))
	if err != nil {
		log.Fatalf("open failed: %v", err)
	}
	defer db.Close()

	stmt, err := db.Prepare(query)
	if err != nil {
		log.Fatalf("query failed: %s", err)
	}
```

And I still got the same error:
`"msg":"query failed: Invalid Argument: SqlState: \u0000\u0000\u0000\u0000\u0000, msg: [FlightSQL] SQL error: ParserError(\"Expected identifier, found: $1\") (InvalidArgument; Prepare)"`

**Comment by zeroshade** [comment]
So this seems to be an issue with the FlightSQL server you're using then potentially. 

Parameterization doesn't happen on the client side, but rather the query is sent to the server, and then values are bound via other flightsql calls. The FlightSQL server you're connecting to has to support the `$1` syntax in order for this to work. Is the FlightSQL server you're connecting to something in-house / custom or can it be shared or pointed to?

**Comment by RPAraujo** [comment]
Was not aware of the parameterization happening on the server side.
I confirmed with our team that implemented our FlightSQL server and indeed, we still don't handle parameters in prepared statements.

Thanks for pointing me in the right direction
