### ISSUE TITLE
[Plasma] add support in plasma client interfaces to work with multiple objects

### ISSUE THREAD

**Issue by zhijunfu** [apache/arrow#3777]
Right now the `Delete()` interface in plasma client supports deleting multiple objects in a single shot, so that we can save IPCs (inter-processing communication) between plasma clients and plasma store, which can reduce client latency and also improve the actual throughput for plasma store.

I'm thinking about adding support for other interfaces to work with multiple objects. It seems straightforward for `Release()`, and probably we can also add support for `Create()` and `Seal()`. 

Thoughts?

@robertnishihara @pcmoritz

**Comment by emkornfield** [comment]
@zhijunfu The developer mailing list (dev@arrow.apache.org) might be a better place to discuss this.

**Comment by zhijunfu** [comment]
@emkornfield Thanks. I created an [JIRA here](https://issues.apache.org/jira/browse/ARROW-4711), which should automatically update dev@arrow.apache.org.

**Comment by emkornfield** [comment]
thanks, do you mind closing this issue?
