### ISSUE TITLE
Add option to read schema of a hive partitioned parquet file (in python)

### ISSUE THREAD

**Issue by lmocsi** [apache/arrow#37794]
### Describe the enhancement requested

```
import pyarrow.parquet as pq
sch = pq.read_schema(path+filename, memory_map=True, partitioning='hive')
```
Currently the above code throws an error of: read_schema() got an unexpected keyword argument 'partitioning'
Without that, it is unable to read the file.
Would be nice, if it worked.

### Component(s)

Parquet, Python

**Comment by AlenkaF** [comment]
Reading the documentation I think `pq.read_schema` is meant to read schema from a single Parquet file
https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_schema.html

But a dataset can be partitioned. If the data is written out to a partitioned directory and you want to inspect the schema, directory etc., this might help:
https://arrow.apache.org/docs/python/dataset.html#dataset-discovery
