### ISSUE TITLE
[R] Can't isntall package on Linux

### ISSUE THREAD

**Issue by MislavSag** [apache/arrow#37831]
### Describe the bug, including details regarding any error messages, version, and platform.

I can install arrow package on Windows, but on Linux it never finishes and during docker image build which contans arrow package, it returns timeout error.

The installation logs returns

* installing *source* package ‘arrow’ ...
 package ‘arrow’ successfully unpacked and MD5 sums checked
 using staged installation
*** Found local C++ source: 'tools/cpp'
*** Building libarrow from source
    For build options and troubleshooting, see the install guide:
    https://arrow.apache.org/docs/r/articles/install.html
**** cmake
**** arrow

and stops here.

I have found one solution:
```
options(
  HTTPUserAgent =
    sprintf(
      "R/%s R (%s)",
      getRversion(),
      paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"])
    )
)

install.packages("arrow", repos = "https://packagemanager.rstudio.com/all/__linux__/focal/latest")
```
But the problem is when I use arrrow inside other package, so I need different installation process for different OS.
See here: https://stackoverflow.com/questions/77157446/different-options-for-package-installations-on-linux-windows

Can I use some other version of arrow which build successfully on Linux?

### Component(s)

R

**Comment by thisisnic** [comment]
Hi @MislavSag, thanks for reporting this!  I'm not sure if the source build is hanging there; can you try again but with a couple of environment variables set via `Sys.setenv("NOT_CRAN" = TRUE, "ARROW_R_DEV" = TRUE)`?  This should speed up the build by getting binaries, and providing more output if anything does go wrong.

**Comment by thisisnic** [comment]
So, it'll have been setting `NOT_CRAN` which installed the binary instead of building from source. There's more information/context here about this: https://arrow.apache.org/docs/r/articles/install.html

There's no way of automating that choice, so the best thing I can think of would be to suggest your users set `NOT_CRAN` as well (or the RSPM method described in the article above). It's only necessary on Linux, as CRAN builds binaries for Windows and MacOS.

**Comment by thisisnic** [comment]
I'm closing this issue as it looks like it's mot a bug, but happy to continue discussing options here!
