### ISSUE TITLE
[Docs][Website] JS docs are missing

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#37858]
### Describe the bug, including details regarding any error messages, version, and platform.

The JS docs at https://arrow.apache.org/docs/js/index.html are not accessible probably because of some reorganization of the website. 

The docs for 12 are at https://arrow.apache.org/docs/12.0/js/index.html but https://arrow.apache.org/docs/13.0/js/index.html doesn't exist either. 

### Component(s)

Documentation

**Comment by kou** [comment]
Oh, @raulcd could you take a look at this?
`docs.tar.`gz in https://github.com/ursacomputing/crossbow/releases/tag/release-13.0.0-rc3-0-github-test-ubuntu-default-docs doesn't have JS docs.
https://github.com/ursacomputing/crossbow/releases/tag/nightly-tests-2023-09-25-0-github-test-ubuntu-22.04-docs doesn't have JS docs too.

The following log will be related:

https://github.com/ursacomputing/crossbow/actions/runs/6293332503/job/17083717573#step:7:12052

```text
+ '[' ON == ON ']'
++ git config --get remote.origin.url
+ '[' https://github.com/apache/arrow == https://github.com/apache/arrow.git ']'
++ git config --get remote.upstream.url
+ '[' '' == https://github.com/apache/arrow.git ']'
++ git config --get remote.apache.url
+ '[' '' == git@github.com:apache/arrow.git ']'
+ echo 'Failed to build docs because the remote is not set correctly. Please set the origin or upstream remote to https://github.com/apache/arrow.git or the apache remote to git@github.com:apache/arrow.git.'
+ exit 0
Failed to build docs because the remote is not set correctly. Please set the origin or upstream remote to https://github.com/apache/arrow.git or the apache remote to git@github.com:apache/arrow.git.
```

**Comment by raulcd** [comment]
I am trying to fix it on main if the issue is solved I'll try and generate the docs from the 13.0.0 branch and create a PR to the docs repo with the JS docs.
