### ISSUE TITLE
[C++] Would `arrow::ipc::ArrayLoader` get dangling pointer when `SkipField` used?

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#37851]
### Describe the enhancement requested

In `arrow::ipc::ArrayLoader`, `SkipField` will create a dummy `ArrayData`, and point `arrow::ipc::ArrayLoader::out_` into that. Would this causing dangling pointer? Or it's by design?

```c++
  Status Load(const Field* field, ArrayData* out) {
    if (max_recursion_depth_ <= 0) {
      return Status::Invalid("Max recursion depth reached");
    }

    field_ = field;
    out_ = out;
    out_->type = field_->type();
    return LoadType(*field_->type());
  }

  Status SkipField(const Field* field) {
    ArrayData dummy;
    skip_io_ = true;
    Status status = Load(field, &dummy);
    skip_io_ = false;
    return status;
  }
```

### Component(s)

C++

**Comment by mapleFU** [comment]
@kou Do we need to care about this? Or it's ok to ignore this because the code will gurantee it's safe in this case?

**Comment by kou** [comment]
I think that this is just not cared. I think that we can reset it to `nullptr` explicitly.

BTW, do you have any problem case by this?

**Comment by mapleFU** [comment]
No, I'm trying to use the ipc streaming format, and the lint tell me I should care about this. I've checkout the code and the code not touch this problem, but it's a bit risky actually..

**Comment by kou** [comment]
OK. Let's reset it.
Do we need to add null checks for `out_` too?
If so, does it have performance penalty?

**Comment by mapleFU** [comment]
> Do we need to add null checks for out_ too?

Maybe DCHECK is ok here?

**Comment by kou** [comment]
Let's use `DCHECK`!
