### ISSUE TITLE
[Java] OrcReader#close doesn't throw any checked exceptions

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#37864]
### Describe the enhancement requested

https://github.com/apache/arrow/blob/1ae243628611a43812747f3bc1505072a139b1c8/java/adapter/orc/src/main/java/org/apache/arrow/adapter/orc/OrcReader.java#L86-L89

No checked exception is actually thrown here. For people using the class directly, it clutters their code to have to handle such a generic exception (and it might overlap with/suppress things like IDEs filling in handlers for other checked exceptions that may actually happen), so it would be nice to just remove the `throws` clause.

### Component(s)

Java

**Comment by jduo** [comment]
take
