### ISSUE TITLE
[Java] Add typed child getter to StructVector

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#37863]
### Describe the enhancement requested

StructVector lets you use `getVectorById`/`getChild` to get the children, but you have to cast the result afterwards; it would be nice (if not absolutely necessary) to have an accessor that casts for you (and provides a nicer exception if it turns out the type was different, the field was missing, etc.)

### Component(s)

Java

**Comment by jduo** [comment]
take

**Comment by jduo** [comment]
AbstractContainer#getChild() has an overload that lets you specify the target FieldVector subtype.
I've added to NonNullableStructVector an overload for getVectorById() that lets you specify a target ValueVector subtype.
