### ISSUE TITLE
[Java][CI]: Enable support for JDK21

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#37914]
### Describe the enhancement requested

Enable last Java release JDK21 support

### Component(s)

Java

**Comment by danepitkin** [comment]
Hey @davisusanibar , is it okay if we close this issue in favor of https://github.com/apache/arrow/issues/36994?

**Comment by davisusanibar** [comment]
Hi @danepitkin sure, let me update the title of the PR related.

**Comment by danepitkin** [comment]
Thank you!
