### ISSUE TITLE
[C++] examples for self-defined compute function

### ISSUE THREAD

**Issue by litao3rd** [apache/arrow#37924]
### Describe the enhancement requested

Hello, everyone,

I'm currently using C++ Arrow to build a data pipeline, and I'm interested in defining specific usage functions for use as compute functions. Despite deep searching, I haven't been able to find any relevant examples or documentation. Could someone please provide me with a complete example or guidance on this?

I appreciate any responses. Thank you!

### Component(s)

C++, C++ - Gandiva, Documentation

**Comment by kou** [comment]
Sorry. We don't have a document that describes how to implement compute functions...
If you're interesting in Gandiva not compute functions https://arrow.apache.org/docs/cpp/compute.html , #37753 may help you.

**Comment by litao3rd** [comment]
Thank you for your response. The provided information is valuable to me. Hope it will be merged into the master branch soon.

**Comment by kou** [comment]
Can we close this?

**Comment by litao3rd** [comment]
yep i will close this issue.

**Comment by egolearner** [comment]
@litao3rd 
You can refer to this example https://github.com/apache/arrow/blob/221484804ffae19bf55d7198e5773d9e956b7b42/cpp/examples/arrow/udf_example.cc#L66-L89

A bit late though.
