### ISSUE TITLE
[Swift] Implement FFI support

### ISSUE THREAD

**Issue by sunchao** [apache/arrow#37938]
### Describe the enhancement requested

Since we already have basic implementations for Arrow buffer, array, data type etc, in Swift. It would be great if we can implement the [Arrow C Data Interface](https://arrow.apache.org/docs/format/CDataInterface.html) in Swift, so that Arrow arrays in other languages such as Rust, C++, can be easily imported into Swift and operated on.

### Component(s)

Swift

**Comment by sunchao** [comment]
cc @abandy @viirya

**Comment by viirya** [comment]
Yea, I think this is nice to have.

**Comment by abandy** [comment]
This would be great.  I will start looking into the C Data Interface and the Swift impl.

**Comment by abandy** [comment]
Please assign this task to me as I am starting on this work.

**Comment by viirya** [comment]
Thank you @abandy

**Comment by abandy** [comment]
Closed my PR due to taking to long to get feedback.  I opened the PR for the initial checkin in early December and it is still outstanding with comments slowly trickling in.  Removing myself from this issue so someone else can pick it up and hopefully get better support.

**Comment by kou** [comment]
Issue resolved by pull request 41342
https://github.com/apache/arrow/pull/41342
