### ISSUE TITLE
[C++] Add support for specifying custom Array element delimiter to `arrow::PrettyPrintOptions`

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#37978]
### Describe the enhancement requested

In order to make the [`arrow::PrettyPrint`](https://github.com/apache/arrow/blob/7667b81bffcb5b361fab6d61c42ce396d98cc6e1/cpp/src/arrow/pretty_print.h#L101) functionality for `arrow::Array` more flexible, it would be useful to be to specify a custom `Array` element delimiter other than `","`.

For example, the MATLAB interface wraps the Arrow C++ libraries and being able to specify a custom `Array` element delimiter, would make it possible to make the display of MATLAB `arrow.array.Array` objects more MATLAB-like.

In order to support custom `Array` element delimiters, we could add a new option to the [`arrow::PrettyPrintOptions`](https://github.com/apache/arrow/blob/7667b81bffcb5b361fab6d61c42ce396d98cc6e1/cpp/src/arrow/pretty_print.h#L35) struct named something like `array_element_delimiter` with type `std::string`.

Implementing this functionality would enable use cases like the ability to display an `arrow::Array` that normally displays as `[1,2,3]` to display as `[1 | 2 | 3]` by setting `array_element_delimiter = " | "`.

### Component(s)

C++

**Comment by rok** [comment]
This is related but stalled: #30951.

**Comment by kevingurney** [comment]
@rok  - thank you for sharing this! My apologies - I didn't see this issue before.

I just opened #37981 to add support for specifying a custom Array element delimiter. If I am not mistaken, it looks like https://github.com/apache/arrow/issues/30951 took the approach of trying to change the default delimiter to be `", "` instead of just `","`. My approach is slightly different in that it adds a new property to `arrow::PrettyPrintOptions` which allows clients to decide what they would like to use for the delimiter rather than trying to modify the default delimiter.

If it seems OK, I will proceed with #37978 and #37981 for now to see if the community feels comfortable with this approach. If these changes end up getting merged, then it may make sense to mark https://github.com/apache/arrow/issues/30951 as closed since it kind of feels like #37981 partially address it (although, admittedly, it isn't exactly the same, since it doesn't change the default display to include a space after the comma).

**Comment by rok** [comment]
@kevingurney Thank you for the extensive and thoughtful explanation of your proposal! :D
I think it's best you proceed with your proposal and indeed close out #30951 once your work is merged.
