### ISSUE TITLE
[JS] when creating a Table from Vectors, arrow always infers non-nullable Fields

### ISSUE THREAD

**Issue by zenazn** [apache/arrow#37983]
### Describe the bug, including details regarding any error messages, version, and platform.

The following javascript code against `apache-arrow` 13.x...
``` js
const arrow = require('apache-arrow');
console.log((new arrow.Table({x: arrow.vectorFromArray([1, 2, null, 4])})).schema.fields);
```

...inappropriately results in the following

``` js
[
  Field {
    name: 'x',
    type: Float64 [Float] { precision: 2 },
    nullable: false,
    metadata: Map(0) {}
  }
]
```

Note that the field is marked as non-nullable. This causes all sorts of fun downstream issues

### Component(s)

JavaScript

**Comment by zenazn** [comment]
Proposed fix in #37982

**Comment by domoritz** [comment]
Hmm, the vector is nullable so it seems like we should pass that to the table constructor. I don't think it's good to always make vectors nullable if we can avoid it.

**Comment by nstokoe** [comment]
Is there anyway to create a new table from a VectorsMap that allows you to force all the schema fields to be nullable? Right or a way to type a vector so that it allows nulls?

**Comment by nstokoe** [comment]
So this is a bug? Any eta on a fix. Or a workaround for how to create a new table from vectors that allows for nulls?

**Comment by calvinfo** [comment]
I hit this as well recently and took me too long to hunt it down. Would love to see a fix for it. The library I'm using (arquero) does indeed pass in the right values in nullable + nullcount as Arrow Data objects, but this constructor overwrites it in the schema.

**Comment by domoritz** [comment]
I fixed this differently and only made the schema nullable if there are nulls in the initial vector. 

To allow customization, I made #39255.

**Comment by domoritz** [comment]
We merged a fix for nullable. Let me know what you think. I also sent https://github.com/apache/arrow/pull/39256 to allow customization of the schema so you can make fields nullable even if there are no nulls in the vectors.

**Comment by zenazn** [comment]
Looks great—thanks @domoritz!
