### ISSUE TITLE
[C++] exception caused by dataset_writer.cc:587:  Check failed: (largest) != (nullptr)

### ISSUE THREAD

**Issue by pawelz188** [apache/arrow#38011]
### Describe the bug, including details regarding any error messages, version, and platform.

The exception is repeated every time and
can be triggered by e.g. modifying the example by modification of [CreateExampleParquetHivePartitionedDataset()](https://github.com/apache/arrow/blob/532ab464db39da0e6b03e4b046355e7bf499730a/cpp/examples/arrow/dataset_documentation_example.cc#L116C43-L116C43) example in `arrow/cpp/examples/arrow/dataset_documentation_example.cc` 
by setting the recording parameters:
```
  write_options.base_dir = base_path;
  write_options.partitioning = partitioning;
  write_options.basename_template = "part{i}.parquet";
+   write_options.max_open_files = 2;
+   write_options.max_rows_per_file = 2;
+   write_options.max_rows_per_group = 2;
  ARROW_RETURN_NOT_OK(ds::FileSystemDataset::Write(write_options, scanner));
  return base_path;
```
Output error message:
`vcpkg\buildtrees\arrow\src\e-arrow-13-0a65b46298.clean\cpp\src\arrow\dataset\dataset_writer.cc:587:  Check failed: (largest) != (nullptr)`

Exception is triggered by DCHECK_NE(largest, nullptr) in CloseLargestFile() procedure in dataset_writter.cc.

The exception call indicates a synchronization problem when arrow is closing files and a limit on the number of open files is reached.

### Component(s)

C++

**Comment by pawelz188** [comment]
My local commit with changes described above:
https://github.com/apache/arrow/commit/0829fd5a5ceee55ef02bc1b4b822884302463669
that triggered exception.

**Comment by kou** [comment]
Thanks for your report.
Do you want to work on this?

**Comment by mapleFU** [comment]
Seems this is because the writer would like to close a file, but all in-flight file has written zero rows...🤔

**Comment by pawelz188** [comment]
Please fix it, I am not yet expert in arrow. 
Now I'm trying to make a patch to fix the problem but I'm not sure of the impact on the overall code.

**Comment by mapleFU** [comment]
I'll submit a fixing. I'm in National Day so maybe slow to reply

**Comment by pawelz188** [comment]
This patch eliminates the problem of exception occurrence.
It seems that the files are handled correctly. 
Please confirm the impact of the patch on the dataset at overall.
[CloseLargestFile-nullptr-fix.patch](https://github.com/apache/arrow/files/12814016/CloseLargestFile-nullptr-fix.patch)

**Comment by pawelz188** [comment]
> I'll submit a fixing. I'm in National Day so maybe slow to reply

If You submit a fix I will test it within my scope.

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/pull/38030 I've submit a basic fixing here, will accept review and maybe working more after national holiday :-)
