### ISSUE TITLE
[Go][FlightSQL] Including some missing types on Rows.Next() method

### ISSUE THREAD

**Issue by miguelpragier** [apache/arrow#38017]
### Describe the enhancement requested

# Description

The following types are missing from the flight driver's internal converter
- Decimal128
- Decimal256
- Binary
- Date64
- DayTimeInterval

As well as their respective null values. <br><br>

👉  I'm writing a PATCH to include these types.

[The related code can be found here](https://github.com/apache/arrow/blob/02de3c1789460304e958936b78d60f824921c250/go/arrow/flight/flightsql/driver/utils.go#L60)

### Component(s)

Go

**Comment by lidavidm** [comment]
The ADBC sqldriver adapter already supports all of these except DayTimeInterval: https://github.com/apache/arrow-adbc/blob/468d50324ff4d30a0aa39d1c201a3c48ea2635a7/go/adbc/sqldriver/driver.go#L605

**Comment by miguelpragier** [comment]
Hi, @lidavidm , and thanks for pointing that out.
I see now that my issue's description wasn't that accurate, and I improved it a lot into the PR. Please, take a look, and let me know if it now make sense: https://github.com/apache/arrow/pull/38028

**Comment by zeroshade** [comment]
Issue resolved by pull request 38028
https://github.com/apache/arrow/pull/38028
