### ISSUE TITLE
[Python] CSV Generation of pyarrow table

### ISSUE THREAD

**Issue by VARSHAJOSHY** [apache/arrow#38035]
### Describe the usage question you have. Please include as many useful details as  possible.

I've been exploring the most efficient method for generating CSV files from Parquet data, and I've discovered that pyarrow.csv.write_csv offers the best performance in my tests. However, I've encountered a challenge because the PyArrow library in my environment is outdated and lacks support for the write_csv function. Is there any alternative solution to do this?

Thanks in advance!

### Component(s)

Parquet

**Comment by VARSHAJOSHY** [comment]
Hi,
Thanks for the reply. Our environment not supporting pyarrow.csv.write_csv. Its throwing error 'pyarrow.csv doesnt have attribute write_csv'. I tried a couple of other approaches to read a parquet file to csv stream.

1.pyarrow table -> pandas table -> to csv
2.pyarrow table to tobatch -> to csv
3.pyarrow table - iterchunks - tocsv
4.pyarrow table ->dask dataframe >csv

but these are not quite well while dealing with parquet file > 10 GB

**Comment by assignUser** [comment]
> Its throwing error 'pyarrow.csv doesnt have attribute write_csv'.

Which means you have pyarrow < 5. The only real advice I can give is to upgrade pyarrow. If there is no way for you to upgrade pyarrow due to other dependencies but have a more recent arrow R version you could try to use the arrow R package via rpy2 as discussed here: https://voltrondata.com/resources/data-transfer-between-python-and-r-with-rpy2-and-apache-arrow

**Comment by VARSHAJOSHY** [comment]
Hi,
I am trying for pyarrow upgrade. Could you please let me know the minimum python version is required for this.

**Comment by assignUser** [comment]
[5.0.0](https://arrow.apache.org/docs/5.0/python/generated/pyarrow.csv.write_csv.html?highlight=write_csv) but I would recommend upgrading  the newest version possible.

**Comment by VARSHAJOSHY** [comment]
Pls let me know the supported python version. mine is 3.7

**Comment by assignUser** [comment]
You can check pypi https://pypi.org/project/pyarrow/#history
pyarrow dropped support for 3.7 in the current version (13.0.0) so you need something <=12.0.1

**Comment by VARSHAJOSHY** [comment]
Thank you!. I am planning to upgrade pyarrow 5.0.0. which requires python >=3.6
Thanks for all ur responses. Before closing the ticket, can u pls let me know the least supported version of numpy by pyarrow>=5. I have numpy 1.12.1

**Comment by assignUser** [comment]
1.16.6 
https://github.com/apache/arrow/blob/apache-arrow-5.0.0/python/pyproject.toml#L21
