### ISSUE TITLE
[Java][CI][Java-Jars] C++ libraries for MacOS AARCH 64 and C++ libraries for Windows is failing

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#38048]
### Describe the bug, including details regarding any error messages, version, and platform.

There are errors on Java building C++ libraries dependencies (java-jars task at http://crossbow.voltrondata.com):

1. Error 1: C++ libraries for MacOS AARCH 64: https://github.com/ursacomputing/crossbow/actions/runs/6403529915/job/17382218168

Machine name: 'm1mini02'
Error: No such keg: /opt/homebrew/Cellar/aws-sdk-cpp
Error: No such keg: /opt/homebrew/Cellar/llvm

2. Error 2: C++ libraries for Windows: https://github.com/ursacomputing/crossbow/actions/runs/6403529915/job/17382219556

Machine name: Microsoft Windows Server 2019
Error: Exit code 0xc0000135

### Component(s)

Continuous Integration, Java

**Comment by kou** [comment]
Could you split this issue for macOS's one and Windows' one?
Let's fix them step by step.

**Comment by davisusanibar** [comment]
> 3\. https://github.com/ursacomputing/crossbow/actions/runs/6403529915/job/17382219556
> 
> Machine name: Microsoft Windows Server 2019 Error: Exit code 0xc0000135

Just divided into MacOS https://github.com/apache/arrow/issues/38076 and Windows https://github.com/apache/arrow/issues/38077 issues
