### ISSUE TITLE
[C++] Benchmark: Add benchmark for non-stream `Codec` Compression/Decompression

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#38042]
### Describe the enhancement requested

Currently, we will enable compression benchmark with `ARROW_WITH_BENCHMARKS_REFERENCE`

Note that it only has benchmark for compressor ( make by `Codec::MakeCompressor()` ) and decompressor ( make by `Codec::MakeDecompressor` ). However, Parquet uses `Codec` to encode and decode. So, I'd like to add benchmarks that use `Codec` directly.

### Component(s)

C++

**Comment by mapleFU** [comment]
@pitrou Is this ok to add benchmark like this? Since I'd like to do some experiments on zstd compression ( like using context to decompress, compress with larger buffer size etc)

**Comment by pitrou** [comment]
If that doesn't add too many benchmarks then yes.
