### ISSUE TITLE
[C++] Add new datatypes to the IPC fuzz seed corpus

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#38041]
### Describe the enhancement requested

Part of our seed corpus for IPC fuzzing is generated dynamically here, but it hasn't been updated for the newer datatypes and features:
https://github.com/apache/arrow/blob/f7530de9fe20f8a3731b465af07a79a56640fe79/cpp/src/arrow/ipc/generate_fuzz_corpus.cc#L68

We should add the newer datatypes (run-end encoding, list view, string view) and ideally also new IPC features such as optional buffer compression (perhaps generate both compressed and uncompressed files).

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
@felipecrv This may be interesting to you.

**Comment by pitrou** [comment]
Note that you can check your work by running this nightly build, or reproducing its steps locally:
https://github.com/ursacomputing/crossbow/actions/runs/6413041512/job/17411340300

For example you can see the dynamic generation occurring here:
https://github.com/ursacomputing/crossbow/actions/runs/6413041512/job/17411340300#step:6:832

**Comment by pitrou** [comment]
And there are docs here: https://arrow.apache.org/docs/dev/developers/cpp/fuzzing.html :-)

**Comment by pitrou** [comment]
@zeroshade Can we prioritize this for 0.15.0? This a rather small task and is important to ensure robustness of the newly added data type implementations.

**Comment by felipecrv** [comment]
I'm assigning myself. I will at least get this started.

**Comment by pitrou** [comment]
Ping @felipecrv :-)

**Comment by felipecrv** [comment]
> Ping @felipecrv :-)

With all the reviews and Flight/SQL/REST work, I don't have time to take another workstream :/

**Comment by pitrou** [comment]
Issue resolved by pull request 43621
https://github.com/apache/arrow/pull/43621
