### ISSUE TITLE
[Java][CI][Java-Jars][MacOS] C++ libraries for MacOS AARCH 64

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#38076]
### Describe the bug, including details regarding any error messages, version, and platform.

There are errors on Java building C++ libraries for MacOS AARCH 64.

C++ libraries for MacOS AARCH 64: https://github.com/ursacomputing/crossbow/actions/runs/6403529915/job/17382218168
Machine name: 'm1mini02'
Error: No such keg: /opt/homebrew/Cellar/aws-sdk-cpp
Error: No such keg: /opt/homebrew/Cellar/llvm

There are more evidences of the error on other days on java-jars task at http://crossbow.voltrondata.com/

### Component(s)

Continuous Integration, Java

**Comment by danepitkin** [comment]
Did these homebrew packages drop support for MacOS 10.13 by chance?

**Comment by danepitkin** [comment]
Yeah, ignore what I said above.

The most recent MacOS version that support Apple Silicon was Big Sur (MacOS 11). Maybe the github runner `m1mini02` is using this version and maybe support for was recently dropped in homebrew for it? I haven't been able to verify yet.

**Comment by danepitkin** [comment]
Confirmed, `aws-sdk-cpp` dropped Big Sur in Homebrew recently https://github.com/Homebrew/homebrew-core/commit/1b8427278b25ba9aad426e97940d0fef59502581

**Comment by danepitkin** [comment]
And the `m1mini02` is self-hosted https://github.com/apache/arrow/blob/main/dev/tasks/java-jars/github.yml#L82

**Comment by assignUser** [comment]
Thanks for investigating. We will need to upgrade those machines.

**Comment by davisusanibar** [comment]
MacOS now run 13.6 and it is worked as expected at https://github.com/ursacomputing/crossbow/actions/runs/6403529915/job/17563133582
