### ISSUE TITLE
[C++][Emscripten] Suppress shorten-64-to-32 warnings

### ISSUE THREAD

**Issue by kou** [apache/arrow#38090]
### Describe the enhancement requested

Emscripten's `size_t`/`ptrdiff_t` is 32bit:

https://emscripten.org/docs/compiling/Building-Projects.html#detecting-emscripten-in-preprocessor

> Emscripten is a 32-bit platform, so `size_t` is a 32-bit unsigned integer, `__POINTER_WIDTH__=32`, `__SIZEOF_LONG__=4` and `__LONG_MAX__` equals `2147483647L`.

We need explicit cast to use `int64_t` for `size_t` on the platform to suppress `shorten-64-to-32` warnings.

We need to change the following files for this. I'll open multiple pull requests for easy to review.

* [ ] cpp/src/arrow/acero/asof_join_node.cc
* [ ] cpp/src/arrow/acero/bloom_filter.cc
* [ ] cpp/src/arrow/acero/hash_join.cc
* [ ] cpp/src/arrow/acero/hash_join_dict.cc
* [ ] cpp/src/arrow/acero/hash_join_node.cc
* [ ] cpp/src/arrow/acero/swiss_join.cc
* [ ] cpp/src/arrow/acero/swiss_join_internal.h
* [ ] cpp/src/arrow/acero/tpch_node.cc
* [ ] cpp/src/arrow/adapters/orc/adapter.cc
* [ ] cpp/src/arrow/array/array_binary.h
* [ ] cpp/src/arrow/array/array_run_end.cc
* [ ] cpp/src/arrow/array/builder_adaptive.h
* [ ] cpp/src/arrow/array/builder_binary.h
* [ ] cpp/src/arrow/array/builder_primitive.cc
* [ ] cpp/src/arrow/array/data.cc
* [ ] cpp/src/arrow/array/dict_internal.h
* [ ] cpp/src/arrow/array/diff.cc
* [ ] cpp/src/arrow/array/util.cc
* [ ] cpp/src/arrow/buffer.cc
* [ ] cpp/src/arrow/c/bridge.cc
* [ ] cpp/src/arrow/chunk_resolver.h
* [ ] cpp/src/arrow/chunked_array.cc
* [ ] cpp/src/arrow/compare.cc
* [ ] cpp/src/arrow/compute/exec.h
* [ ] cpp/src/arrow/compute/kernel.cc
* [ ] cpp/src/arrow/compute/kernel.h
* [ ] cpp/src/arrow/compute/kernels/aggregate_mode.cc
* [ ] cpp/src/arrow/compute/kernels/aggregate_quantile.cc
* [ ] cpp/src/arrow/compute/kernels/aggregate_tdigest.cc
* [ ] cpp/src/arrow/compute/kernels/chunked_internal.h
* [ ] cpp/src/arrow/compute/kernels/codegen_internal.h
* [ ] cpp/src/arrow/compute/kernels/copy_data_internal.h
* [ ] cpp/src/arrow/compute/kernels/hash_aggregate.cc
* [ ] cpp/src/arrow/compute/kernels/ree_util_internal.h
* [ ] cpp/src/arrow/compute/kernels/row_encoder.cc
* [ ] cpp/src/arrow/compute/kernels/row_encoder_internal.h
* [ ] cpp/src/arrow/compute/kernels/scalar_cast_internal.cc
* [ ] cpp/src/arrow/compute/kernels/scalar_cast_string.cc
* [ ] cpp/src/arrow/compute/kernels/scalar_compare.cc
* [ ] cpp/src/arrow/compute/kernels/scalar_if_else.cc
* [ ] cpp/src/arrow/compute/kernels/scalar_set_lookup.cc
* [ ] cpp/src/arrow/compute/kernels/scalar_string_ascii.cc
* [ ] cpp/src/arrow/compute/kernels/scalar_string_internal.h
* [ ] cpp/src/arrow/compute/kernels/scalar_string_utf8.cc
* [ ] cpp/src/arrow/compute/kernels/util_internal.h
* [ ] cpp/src/arrow/compute/kernels/vector_select_k.cc
* [ ] cpp/src/arrow/compute/kernels/vector_selection_filter_internal.cc
* [ ] cpp/src/arrow/compute/kernels/vector_sort.cc
* [ ] cpp/src/arrow/compute/kernels/vector_sort_internal.h
* [ ] cpp/src/arrow/compute/key_hash.cc
* [ ] cpp/src/arrow/compute/key_map.cc
* [ ] cpp/src/arrow/compute/light_array.cc
* [ ] cpp/src/arrow/compute/row/compare_internal.cc
* [ ] cpp/src/arrow/compute/row/encode_internal.cc
* [ ] cpp/src/arrow/compute/row/grouper.cc
* [ ] cpp/src/arrow/compute/row/row_internal.cc
* [ ] cpp/src/arrow/compute/util.h
* [ ] cpp/src/arrow/dataset/dataset_internal.h
* [ ] cpp/src/arrow/dataset/partition.cc
* [ ] cpp/src/arrow/extension/fixed_shape_tensor.cc
* [ ] cpp/src/arrow/integration/json_internal.cc
* [ ] cpp/src/arrow/io/buffered.cc
* [ ] cpp/src/arrow/io/compressed.cc
* [ ] cpp/src/arrow/io/file.cc
* [ ] cpp/src/arrow/io/memory.cc
* [ ] cpp/src/arrow/io/stdio.cc
* [ ] cpp/src/arrow/ipc/message.cc
* [ ] cpp/src/arrow/ipc/metadata_internal.cc
* [ ] cpp/src/arrow/ipc/reader.cc
* [ ] cpp/src/arrow/ipc/test_common.cc
* [ ] cpp/src/arrow/json/chunked_builder.cc
* [ ] cpp/src/arrow/json/parser.cc
* [ ] cpp/src/arrow/scalar.cc
* [ ] cpp/src/arrow/sparse_tensor.cc
* [ ] cpp/src/arrow/tensor.h
* [ ] cpp/src/arrow/tensor/coo_converter.cc
* [ ] cpp/src/arrow/tensor/csf_converter.cc
* [ ] cpp/src/arrow/testing/builder.h
* [ ] cpp/src/arrow/testing/gtest_util.cc
* [ ] cpp/src/arrow/testing/random.cc
* [ ] cpp/src/arrow/testing/util.cc
* [ ] cpp/src/arrow/type.cc
* [ ] cpp/src/arrow/util/align_util.cc
* [ ] cpp/src/arrow/util/basic_decimal.cc
* [ ] cpp/src/arrow/util/bit_run_reader.h
* [ ] cpp/src/arrow/util/bit_util.cc
* [ ] cpp/src/arrow/util/bitmap.cc
* [ ] cpp/src/arrow/util/bitmap.h
* [ ] cpp/src/arrow/util/bitmap_ops.cc
* [ ] cpp/src/arrow/util/bitmap_reader.h
* [ ] cpp/src/arrow/util/bitmap_writer.h
* [ ] cpp/src/arrow/util/byte_stream_split.h
* [ ] cpp/src/arrow/util/future.cc
* [ ] cpp/src/arrow/util/hashing.h
* [ ] cpp/src/arrow/util/int_util.cc
* [ ] cpp/src/arrow/util/key_value_metadata.cc
* [ ] cpp/src/arrow/util/memory.cc
* [ ] cpp/src/arrow/util/sort.h
* [ ] cpp/src/arrow/util/spaced.h
* [ ] cpp/src/arrow/visit_data_inline.h
* [ ] cpp/src/parquet/arrow/reader.cc
* [ ] cpp/src/parquet/arrow/reader_internal.cc
* [ ] cpp/src/parquet/bloom_filter.cc
* [ ] cpp/src/parquet/column_reader.cc
* [ ] cpp/src/parquet/column_scanner.h
* [ ] cpp/src/parquet/column_writer.cc
* [ ] cpp/src/parquet/encoding.cc
* [ ] cpp/src/parquet/file_reader.cc
* [ ] cpp/src/parquet/metadata.cc
* [ ] cpp/src/parquet/statistics.cc

### Component(s)

C++

**Comment by kou** [comment]
Other discussions on ursalabs.zulipchat.com:

https://ursalabs.zulipchat.com/#narrow/stream/180245-dev/topic/C.2B.2B.20and.20Emscripten.20warnings

```text
Antoine
23:28

@kou You've opened lots of PRs to explicitly cast int64_t to size_t for Emscripten (where I assume pointers and sizes are 32 bits?). This will generally make the code less readable and more annoying to maintain. Can we simply disable that specific warning when the target is Emscripten?
  23:28

cc @Benjamin Kietzman @Felipe Carvalho for opinions.
```

```text
Benjamin Kietzman
23:44

I'd be in favor of disabling most of the integer conversion warnings. I'd prefer to use -fsanitize=implicit-signed-integer-truncation and similar checks, which would give us a chance to catch actual bugs instead of littering the code with boilerplate to explicitly silence such
```

```text
Antoine
23:48

On the opposite, I think that integer conversion warnings are normally useful. But if you're on a 32-bit build, casting a size to 32 bits should be obviously safe (how would you have got a 64-bit size in the first place? except if reading the size from untrusted data, that is).
  23:50

Sanitize checks would only be useful if the tests actually exercise sizes larger than 2GB, right? That's not the case usually, for good reason.
```

```text
kou
05:44

    where I assume pointers and sizes are 32 bits?

Yes.

    Can we simply disable that specific warning when the target is Emscripten?

Yes, we can.

I don't have a strong opinion how to suppress this warning (adding explicit casts or disabling this warning).
I share most warning reported cases for information:

    Use int64_t for std::vector::operator[]
    Use int64_t for std::vector::resize()
    Use int64_t for memset()
    Use int64_t for memcpy()
    Use int64_t for memcmp()
```

**Comment by raulcd** [comment]
@kou should I move this out of 14.0.0?

**Comment by kou** [comment]
Yes. Done.
(This is included in 14.0.0 because some of related PRs were merged. Our merge script sets 14.0.0 on merge.)

**Comment by felipecrv** [comment]
Would changing `BytesForBits` to return a size_t help minimize the need for casts? `BytesForBits` generates a memory size, so `size_t` is probably a more appropriate type to return. The annoying thing is that `size_t` is unsigned and `ssize_t` is not standardized.

**Comment by pitrou** [comment]
I really disagree with adding all those `static_cast`. They add no value to the code, but make it less readable and more annoying to maintain. We will also quickly run into new Emscripten warnings as soon as new code handling sizes and offsets is added to the codebase.

IMO, we should simply disable those warnings on Emscripten.

**Comment by felipecrv** [comment]
> I really disagree with adding all those `static_cast`. They add no value to the code, but make it less readable and more annoying to maintain. We will also quickly run into new Emscripten warnings as soon as new code handling sizes and offsets is added to the codebase.
> 
> IMO, we should simply disable those warnings on Emscripten.

I agree. It would be extremely brittle and it adds nothing to the compiled program as the downcasts happen automatically.

Getting the compiler to ensure the Arrow code is 32-bit safe would require widespread use of `size_t` and less casts from `int64_t` to `size_t` instead of more casts.

**Comment by kou** [comment]
We don't do this.
