### ISSUE TITLE
S3FileSystem support virtual hosted style endpoint 

### ISSUE THREAD

**Issue by chenk008** [apache/arrow#38135]
### Describe the enhancement requested

the Alibaba Cloud OSS is an AWS S3 compatible storage, but only support virtual hosted style to access.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access

https://github.com/aws/aws-sdk-java-v2/issues/2317#issuecomment-1304365612

https://boto3.amazonaws.com/v1/documentation/api/1.9.42/guide/s3.html

### Component(s)

Python

**Comment by pitrou** [comment]
Closed by #38858 (see #38844)
