### ISSUE TITLE
Remove the workaround for gcc.98282?

### ISSUE THREAD

**Issue by Chandlerooo** [apache/arrow#38152]
### Describe the enhancement requested

I notice a workaround for gcc.98282 in datum.h introduced by commit: https://github.com/apache/arrow/commit/482ac5fa763f48efca8f83560da51fff1084df49
https://github.com/apache/arrow/blob/main/cpp/src/arrow/datum.h#L59
This bug has been marked as fixed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98282. Shall it be removed?

### Component(s)

Other

**Comment by pitrou** [comment]
In which versions is it fixed? Unless affected gcc versions are not present anymore, we should probably keep the workaround.

**Comment by pitrou** [comment]
Also, the workaround is trivial and doesn't cost anything to maintain, so my vote is not to change anything here.
