### ISSUE TITLE
[Python] Function match_substring_regex has unexpected behavior

### ISSUE THREAD

**Issue by mschwedeler** [apache/arrow#38150]
### Describe the bug, including details regarding any error messages, version, and platform.

System details:
```
pyarrow: 13.0.0
platform: macOS-12.6.9-arm64-arm-64bit
python: 3.9.13
```

This is as expected:
```python
import re

print(re.findall(r'\bm\b', 'méxico'))
# []
```

This is unexpected:
```python
import pyarrow as pa

print(
    pa.compute.match_substring_regex(
        pa.array(
            [
                "méxico",
            ]
        ), pattern=r'\bm\b'
    )
)
# <pyarrow.lib.BooleanArray object at 0x4585c27c0>
# [
#  true
# ]
```

### Component(s)

Python

**Comment by llama90** [comment]
It seems like the issue may be due to the character 'é'. Is it necessary to use the character 'é'? When tested on sites like https://regexr.com/, the same results appear. 

méxico - true
mexico - false

**Comment by spenczar** [comment]
`\b` is the "ASCII word boundary" expression in RE2. `méxico` is not an ASCII string, it's Unicode, and `m` is indeed a complete ASCII subsequence in there.

https://github.com/google/re2/issues/433 suggests a workaround.

**Comment by mschwedeler** [comment]
Great, thanks both, that clarifies.
