### ISSUE TITLE
[CI][Release] Release integration builds should not run test suites

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#38159]
### Describe the enhancement requested

Title says it all. One reason the release-integration builds are so horribly long is that they build tests and run tests for _all_ implementations _in release mode_.

Release-integration tests should not build and run tests. They should only run the integration test suite. This would make them significantly faster and more reliable.

### Component(s)

Continuous Integration, Release

**Comment by assignUser** [comment]
Sounds like a good idea to make verification faster and less annoying 👍 Thanks!
