### ISSUE TITLE
[R] `open_dataset(format = "json")` not documented

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#38216]
### Describe the bug, including details regarding any error messages, version, and platform.

In the roxygen header for the `format` argument to `open_dataset()`, "json" isn't documented even though it is supported.

### Component(s)

R

**Comment by Divyansh200102** [comment]
i want to work on this ..please tell in which file do i need to make the documentation changes

**Comment by Divyansh200102** [comment]
i want to work on this  @thisisnic
