### ISSUE TITLE
[C++] [FlightSQL] When an error occurs during installation with the '-DARROW_FLIGHT_SQL=ON' option.

### ISSUE THREAD

**Issue by llama90** [apache/arrow#38210]
### Describe the bug, including details regarding any error messages, version, and platform.

As the title suggests, an error occurs during the `install` command when including the '-DARROW_FLIGHT_SQL=ON' option after rebasing to the most recent commit.

It seems to be related to the commit(92de9a3028fdfb76e0ca1e216845e09bf68ab4ac). In the code, it's being handled as `std::string app_metadata = "";` to set a default value. However, when I run the `install`, if I do not explicitly set the `""` value, the following error occurs.

```
/Users/lama/workspace/arrow-2/cpp/src/arrow/flight/integration_tests/test_integration.cc:560:80: error: missing field 'app_metadata' initializer [-Werror,-Wmissing-field-initializers]
        {std::to_string(statuses_.size()) + ": " + ticket}, {}, expiration_time});
```

Adding `" "` explicitly to `app_metadata` for all calls to the FlightEndpoint constructor resolves the issue, allowing the command to execute without errors.

The constructor is already written to substitute a default value. Is this approach correct?

### Environment

M1(`ARM`) Macbook

### Component(s)

C++

**Comment by kou** [comment]
Could you open a pull request that adds `""` as `app_metadata`?

I don't know why this isn't detected in our CI...
