### ISSUE TITLE
[Java] New getTransferPair which takes Field as parameter for Complex type vectors and BaseVariableWidthVector's

### ISSUE THREAD

**Issue by xxlaykxx** [apache/arrow#38246]
### Describe the enhancement requested

Introduce a new getTransferPair method which takes 'Field' as a parameter for Complex type vectors and BaseVariableWidthVector's. Same like it was done for [BaseFixedWidthVector](https://github.com/apache/arrow/issues/15187)
In some cases its useful to pass a 'Field' object directly and not create a new 'Field' every time.

### Component(s)

Java

**Comment by lidavidm** [comment]
Labeling as a breaking change since existing callsites may become ambiguous when recompiled
