### ISSUE TITLE
Build Errors: arrow_objlib.dir/ipc/json-internal.cc.o

### ISSUE THREAD

**Issue by giveitatry168** [apache/arrow#3825]
g++ (GCC) 6.3.1 
rapidjson-v1.1.0
arrow-apache-arrow-0.12.1

/scratch_area/apache/arrow-apache-arrow-0.12.1/cpp/src/arrow/ipc/json-internal.cc: In member function 'typename std::enable_if<arrow::IsSignedInt<T>::value, void>::type arrow::ipc::internal::json::ArrayWriter::WriteDataValues(const T&)':
/scratch_area/apache/arrow-apache-arrow-0.12.1/cpp/src/arrow/ipc/json-internal.cc:389:18: error: 'using RjWriter = class arrow::rapidjson::Writer<arrow::rapidjson::GenericStringBuffer<arrow::rapidjson::UTF8<> > > {aka class arrow::rapidjson::Writer<arrow::rapidjson::GenericStringBuffer<arrow::rapidjson::UTF8<> > >}' has no member named 'RawNumber'
         writer_->RawNumber(null_string, sizeof(null_string));
                  ^~~~~~~~~

**Comment by emkornfield** [comment]
Hi @giveitatry168,
You might be able to get better support on the [mailing list](dev@arrow.apache.org), giving more details about your environment (which OS are you running) and how how you are setting up the build environment (what args are you passing to cmake).

As a first guess, it might be that you are picking up an older version of rapidjson on your system.

**Comment by giveitatry168** [comment]
Thanks, @emkornfield !

It was build on RHEL 6 with ARROW_RAPIDJSON_URL=/scratch_area/.../cpp//thirdparty/rapidjson-v1.1.0.tar.gz. I've also verified the rapidjson package is present. Will also try the dev alias you suggested.
