### ISSUE TITLE
[R][Docs] Version list is not updated

### ISSUE THREAD

**Issue by eitsupi** [apache/arrow#38273]
### Describe the bug, including details regarding any error messages, version, and platform.

<https://arrow.apache.org/docs/r/versions.html> does not seem updated.

It shows:

> [12.0.1.9000 (dev)](https://arrow.apache.org/docs/dev/r/)
> [12.0.1.1 (release)](https://arrow.apache.org/docs/r/)
> [11.0.0.3](https://arrow.apache.org/docs/11.0/r/)
> [10.0.1](https://arrow.apache.org/docs/10.0/r/)
> [9.0.0](https://arrow.apache.org/docs/9.0/r/)
> [8.0.0](https://arrow.apache.org/docs/8.0/r/)
> [7.0.0](https://arrow.apache.org/docs/7.0/r/)
> [6.0.1](https://arrow.apache.org/docs/6.0/r/)
> [5.0.0](https://arrow.apache.org/docs/5.0/r/)
> [4.0.1](https://arrow.apache.org/docs/4.0/r/)
> [3.0.0](https://arrow.apache.org/docs/3.0/r/)
> [2.0.0](https://arrow.apache.org/docs/2.0/r/)
> [1.0.1](https://arrow.apache.org/docs/1.0/r/)

But the release version is 13.0.0 now.

### Component(s)

Documentation, R

**Comment by Divyansh200102** [comment]
i want to work on this @eitsupi

**Comment by eitsupi** [comment]
@Divyansh200102 Glad to hear that.

I think you can assign this issue for you via commenting "take" on this issue.

https://github.com/apache/arrow/blob/c5bce96ba626ad2558e10acddf8ef19ea06940e8/CONTRIBUTING.md?plain=1#L22-L28

**Comment by Divyansh200102** [comment]
take

**Comment by Divyansh200102** [comment]
in which file exactly do you want me to make the changes?? @eitsupi

**Comment by Divyansh200102** [comment]
take

**Comment by Divyansh200102** [comment]
i think the website you just mentioned  mentions the older version of the docs for the users. @eitsupi 

r\_pkgdown.yml:
  352    components:
  353:     older_versions: "[Older versions of these docs](https://arrow.apache.org/docs/r/versions.html)"
  354

**Comment by thisisnic** [comment]
Thanks for repoting this @eitsupi!

No need to do anything here, @Divyansh200102  - there is currently a PR open to fix this on the arrow-site repo: https://github.com/apache/arrow-site/pull/413

The version list is updated via a script which is run during the release; we should check if it ends up being run successfully or not during the release, and if not, look into that.
