### ISSUE TITLE
[Dev][CI] autotune failing to push to PR branches?

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#38315]
### Describe the bug, including details regarding any error messages, version, and platform.

I just [tried to autotune and generate docs](https://github.com/apache/arrow/pull/38258#issuecomment-1766777461), but that failed with:

```
Run r-lib/actions/pr-push@v2
Collecting information about PR #38258...
git push ***github.com/Divyansh200102/arrow.git -q HEAD:open_dataset(format-=-json-)-not-documented
remote: Permission to Divyansh200102/arrow.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Divyansh200102/arrow.git/': The requested URL returned error: 403
Error: The process 'git' failed with exit code 128
``` 

It looks like that PR has permissions for maintainers to push to it — so maybe this is an issue that our github bot user no longer has the correct scope? I also was able to push to this branch personally, so I suspect it's something wrong with the actions runner permissions scope.

cc @assignUser since you know lots about github (actions) permissions

### Component(s)

Continuous Integration, Developer Tools

**Comment by jonkeane** [comment]
I've also looked to see if the r-libs/actions/pr-push has been updated and it's still on v2 

https://github.com/r-lib/actions/issues/563#issuecomment-1129862860 might be related (though which permissions were at issue weren't described)

**Comment by assignUser** [comment]
Yeah this is probably due to a change to the default permission + this workflow being rarely used. I can have a look

**Comment by raulcd** [comment]
I am closing this as autotune was removed at:
- https://github.com/apache/arrow/pull/44649
