### ISSUE TITLE
[C++] Implement file writes for Azure filesystem

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#38333]
### Describe the enhancement requested

The same process as for https://github.com/apache/arrow/issues/37511 but for file writes this time. 

So probably we need an azure implementation of `io::OutputStream` then that can be used to implement the `OpenOutputStream` methods of the AzureFileSystem.

https://github.com/apache/arrow/pull/12914 implemented this so that is a good starting point. However I would suggest that we avoid differing logic based on whether the hierarchical namespace (ADLS gen2) is used. Without the convenient `Append` API that only works with hierarchical namespace we will need to upload new blocks then update the block list of the block blob, to implement the same functionality. This method should work regardless of hierarchical namespace, its testable with azurite and and performance should be no different compared to if we use the  `Append` API. 

**Related Issues:**
- https://github.com/apache/arrow/issues/18014 (is a child of)

### Component(s)

C++

**Comment by Tom-Newton** [comment]
take

**Comment by kou** [comment]
This implements `AzureFileSystem::OpenOuptutStream()`, right?
I'll create  new sub issues for the following APIs:
* `AzureFileSystem::CreateDir()`
* `AzureFileSystem::DeleteDir()`
* `AzureFileSystem::DeleteDirContents()`
* `AzureFileSystem::DeleteRootDirContents()`
* `AzureFileSystem::DeleteFile()`
* `AzureFileSystem::Move()`
* `AzureFileSystem::CopyFile()`

Do we need a sub issue for `AzureFileSystem::OpenAppendStream()`?

**Comment by kou** [comment]
Done: See the GH-18014 descriptions for each sub issue.

**Comment by Tom-Newton** [comment]
> Do we need a sub issue for `AzureFileSystem::OpenAppendStream()`?

I was planning to do it in this one. I think the only difference is that append stream doesn't truncate the file if it already exists.

**Comment by kou** [comment]
I see!
