### ISSUE TITLE
[Python] Cython Modules (Flight, Parquet, CUDA, etc) not building for 13.0.0 on Python 3.12 (on macOS 14.0.0 ARM64)

### ISSUE THREAD

**Issue by DylanLukes** [apache/arrow#38338]
⚠️ **UPDATE: This bug was much more severe than I thought. I'm leaving the original text here but please read further down. It appears that _none_ of the Python modules are being built.**

---

### Describe the bug, including details regarding any error messages, version, and platform.

I had been using Flight in `pyarrow` 12.0.1 without issue, but it seems to have been disabled (somehow) from the wheel build CI in 13.0.0. 

This presents a blocking issue for me as I cannot just revert to 12.0.1: it seems like the 12.0.1 metadata is inconsistent now so I can't reinstall it from PyPI (see end of this post for details).

**What's baffling is that looking through all of the places Flight support should be enabled... it appears to be.**

It does not appear that `ARROW_FLIGHT` is set to `OFF` in the CI task:

https://github.com/apache/arrow/blob/63840f297df681e710a0b1a822235eca54f1c2fb/dev/tasks/python-wheels/github.osx.arm64.yml#L25-L27

And moreover, the ` --x-feature=flight` flag is set.

https://github.com/apache/arrow/blob/63840f297df681e710a0b1a822235eca54f1c2fb/dev/tasks/python-wheels/github.osx.arm64.yml#L66-L74

I installed `apache-arrow` (13.0.0) itself from Homebrew, and inspecting the formula... [Flight support is enabled there too](https://github.com/Homebrew/homebrew-core/blob/f539ddeeb78e374d9021060e372d5a01cbf9433f/Formula/a/apache-arrow.rb#L50-L58).

Despite this, importing `pyarrow.flight` indicates that the installation was not built with support for it.

```sh
~ ❯ python
Python 3.12.0 (main, Oct 18 2023, 20:54:23) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow.flight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dylan/.asdf/installs/python/3.12.0/lib/python3.12/site-packages/pyarrow/flight.py", line 67, in <module>
    raise ImportError(
ImportError: The pyarrow installation is not built with support for 'flight' (No module named 'pyarrow._flight')
```

---

### System Details

**System**: MacBook Pro w/ M1 Max
**OS**: macOS Sonoma 14.0
**Python**: 3.12.0
**Arrow**: apache-arrow: stable 13.0.0 (bottled) from Homebrew, [formula here](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/a/apache-arrow.rb), `-DARROW_FLIGHT=ON` is _enabled_.

---

### Metadata Inconsistency w/ 12.0.1

I would just go back to 12.0.1 until this is resolved, but I cannot, here's the error I get:

```sh
~ ❯ pip install --upgrade pyarrow==12.0.1
Collecting pyarrow==12.0.1
  Using cached pyarrow-12.0.1.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested pyarrow==12.0.1 from https://files.pythonhosted.org/packages/c5/68/d3410e975bebbf5be00c1238d0418345d8ec5d88b7a6c102211a1c967edd/pyarrow-12.0.1.tar.gz, but installing version 12.0.0
Discarding https://files.pythonhosted.org/packages/c5/68/d3410e975bebbf5be00c1238d0418345d8ec5d88b7a6c102211a1c967edd/pyarrow-12.0.1.tar.gz (from https://pypi.org/simple/pyarrow/) (requires-python:>=3.7): Requested pyarrow==12.0.1 from https://files.pythonhosted.org/packages/c5/68/d3410e975bebbf5be00c1238d0418345d8ec5d88b7a6c102211a1c967edd/pyarrow-12.0.1.tar.gz has inconsistent version: expected '12.0.1', but metadata has '12.0.0'
ERROR: Could not find a version that satisfies the requirement pyarrow==12.0.1 (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.17.1, 1.0.0, 1.0.1, 2.0.0, 3.0.0, 4.0.0, 4.0.1, 5.0.0, 6.0.0, 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 10.0.1, 11.0.0, 12.0.0, 12.0.1, 13.0.0)
ERROR: No matching distribution found for pyarrow==12.0.1
```

I can't find any reference to `12.0.0` in the `tar.gz`, so this must be in reference to some metadata PyPI has elsewhere.

### Component(s)

FlightRPC, Python

**Comment by DylanLukes** [comment]
I purged both `apache-arrow` and `pyarrow` from Homebrew and Pip respectively, including all caches. 

Here are installation logs from each:

- [apache-arrow-install.log](https://github.com/apache/arrow/files/13038381/apache-arrow-install.log)
- [pyarrow-install.log](https://github.com/apache/arrow/files/13038382/pyarrow-install.log)

Of particular interest:

It looks like a bunch (all?) of the pyx modules are failing due to the build shared objects not being found. This pattern repeats for `_cuda`, `_flight`, `_dataset`, `_dataset_orc`, `_acero`, `_parquet`, ...

```log
...
1805-2023-10-18T22:41:23,605   Did not find /private/var/folders/00/br6_1tk56bn7k97pq6klyqz80000gn/T/pip-install-pxxvsaq9/pyarrow_713c0a18b5ae4d03b9368fc79ff32155/build/lib.macosx-14.0-arm64-cpython-312/pyarrow/_flight.cpython-312-darwin.so
1806:2023-10-18T22:41:23,605   Cython module _flight failure permitted
1807-2023-10-18T22:41:23,605   Did not find /private/var/folders/00/br6_1tk56bn7k97pq6klyqz80000gn/T/pip-install-pxxvsaq9/pyarrow_713c0a18b5ae4d03b9368fc79ff32155/build/lib.macosx-14.0-arm64-cpython-312/pyarrow/_dataset.cpython-312-darwin.so
1808-2023-10-18T22:41:23,605   Cython module _dataset failure permitted
...
```

Considering even Parquet doesn't work, this may be a bigger issue than I at first thought...

```sh
>>> import pyarrow.parquet
...
ImportError: The pyarrow installation is not built with support for the Parquet file format (No module named 'pyarrow._parquet')
```

**Comment by DylanLukes** [comment]
Aha. It looks like it's just not installing any of the extensions...

```sh
2023-10-18T22:40:12,332   -- Running cmake for PyArrow 2023-10-18T22:40:12,332
  cmake
-DCMAKE_INSTALL_PREFIX=/private/var/folders/00/br6_1tk56bn7k97pq6klyqz80000gn/T/pip-install-pxxvsaq9/pyarrow_713c0a18b5ae4d03b9368fc79ff32155/build/lib.macosx-14.0-arm64-cpython-312/pyarrow -DPYTHON_EXECUTABLE=/Users/dylan/.asdf/installs/python/3.12.0/bin/python3.12
-DPython3_EXECUTABLE=/Users/dylan/.asdf/installs/python/3.12.0/bin/python3.12 -DPYARROW_CXXFLAGS= -DPYARROW_BUILD_CUDA=off -DPYARROW_BUILD_SUBSTRAIT=off
-DPYARROW_BUILD_FLIGHT=off -DPYARROW_BUILD_GANDIVA=off -DPYARROW_BUILD_ACERO=off
-DPYARROW_BUILD_DATASET=off -DPYARROW_BUILD_ORC=off -DPYARROW_BUILD_PARQUET=off
-DPYARROW_BUILD_PARQUET_ENCRYPTION=off -DPYARROW_BUILD_GCS=off -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off
-DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_CYTHON_CPP=off -DPYARROW_GENERATE_COVERAGE=off
-DCMAKE_BUILD_TYPE=release
/private/var/folders/00/br6_1tk56bn7k97pq6klyqz80000gn/T/pip-install-pxxvsaq9/pyarrow_713c0a18b5ae4d03b9368fc79ff32155

```

**Comment by DylanLukes** [comment]
This doesn't appear to be specific to Python 3.12 either. I tried in a clean 3.11 venv (with caches purged) and got something even more fatal:

```sh
Python 3.11.0 (main, Oct 27 2022, 23:12:59) [Clang 14.0.0 (clang-1400.0.29.201)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow.flight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dylan/Downloads/pyarrow-13.0.0/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ModuleNotFoundError: No module named 'pyarrow.lib'
```

**Comment by DylanLukes** [comment]
Well, building from the tarball, I can enable `PYARROW_WITH_PARQUET=1` and `PYARROW_WITH_FLIGHT=1` and the build seems to go smoothly, but now _any_ attempted import of pyarrow results in the error above (`pyarrow.lib` not found).

☹️

**Comment by DylanLukes** [comment]
Ok, some reproduction steps. Starting from the `pyarrow-13.0.0.tar.gz`:

```sh 
~/Downloads/pyarrow-13.0.0 ❯  PYARROW_WITH_PARQUET=1 PYARROW_WITH_FLIGHT=1 python -m build
...
Successfully built pyarrow-13.0.0.tar.gz and pyarrow-13.0.0-cp312-cp312-macosx_14_0_arm64.whl
```

```sh
~/Downloads/pyarrow-13.0.0 ❯  python -m installer dist/pyarrow-13.0.0-cp312-cp312-macosx_14_0_arm64.whl
```

At this point, it doesn't work:

```sh
~/Downloads/pyarrow-13.0.0 ❯ python -c "import pyarrow"                                                                  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dylan/Downloads/pyarrow-13.0.0/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ModuleNotFoundError: No module named 'pyarrow.lib'
```

Now, I move into the `site-packages` directory and import locally:

```sh
.../lib/python3.12/site-packages ❯ python -c "import pyarrow; print(pyarrow.__version__)" 
13.0.0
```

It works! And now returning to an arbitrary directory, it also works.

```sh
~ ❯ python -c "import pyarrow; print(pyarrow.__version__)"
13.0.0
```

It seems like performing the import locally in `site-packages` "fixes" something. It doesn't seem like anything has been updated anywhere (e.g. in `__pycache__`) from the timestamps however. The timestamps all match the original installation time.

**Comment by jorisvandenbossche** [comment]
@DylanLukes can you clarify how you are exactly trying to install pyarrow? Is it using homebrew, a binary wheel with pip, or from source? That are three quite different methods, but your messages seems to be mentioning each of them at some point.

**Comment by jorisvandenbossche** [comment]
Also, the fact that the import initially doesn't work from the downloads folder after building the tar.gz:



> At this point, it doesn't work:
> 
> ```shell
> ~/Downloads/pyarrow-13.0.0 ❯ python -c "import pyarrow"                                                                  
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/dylan/Downloads/pyarrow-13.0.0/pyarrow/__init__.py", line 65, in <module>
>     import pyarrow.lib as _lib
> ModuleNotFoundError: No module named 'pyarrow.lib'
> ```

That is because it is trying to import the local directory with the name pyarrow,  and not the one installed in site-packages. You can see that the path in the error message ("/Users/dylan/Downloads/pyarrow-13.0.0/pyarrow/__init__.py"). That's an expected (but for sure confusing if not thinking about it) error when having a local file or directory with a clashing name. 

But so it seems that at least your local build and install is working.

**Comment by jorisvandenbossche** [comment]
And one other clarification: the reason that your install for Python 3.12 doesn't work out of the box is because we don't yet have wheels for Python 3.12 (the pyarrow 13.0 release happened 3 months ago, and Python 3.12 is just out for two weeks). So when there is no wheel available, it will try to install from the sdist. 

Python 3.12 wheels will be included for the upcoming 14.0 release (estimated arrival is in one or two weeks)

**Comment by DylanLukes** [comment]
> @DylanLukes can you clarify how you are exactly trying to install pyarrow? 

I was simply trying to `pip install pyarrow`. 

> Is it using homebrew, a binary wheel with pip, or from source?

I tried initially just via `pip` (already had `apache-arrow` installed via `brew` but reinstalled to update it to 13.0.0 as well. In the end, I had to build from source.

> Python 3.12 wheels will be included for the upcoming 14.0 release (estimated arrival is in one or two weeks)

Awesome, looking forward to that. For the time being at least I have it working after manually installing it from the source tarball. 

---

One question I have is generally why all of the Cython extensions appear to be disabled in the package `setup.py`. Am I correct in understanding this is just a default state and that these normally be then enabled (using the environment variables) in CI/CD tasks when wheels are built and published?

**Comment by DylanLukes** [comment]
I think what happened here is that switching to 3.12, I was no longer on the golden path of having a wheel (built by the CI/CD) with the extensions enabled. So, `pip` fell back to build manually, and by default, that's with all of the extension flags set to "off".

**Comment by jorisvandenbossche** [comment]
> I think what happened here is that switching to 3.12, I was no longer on the golden path of having a wheel (built by the CI/CD) with the extensions enabled. So, `pip` fell back to calling out to `setuptools` to build from the source dist, and by default, that's with all of the extension flags set to "off".

Yes, that sounds as a correct summary.

> One question I have is generally why all of the Cython extensions appear to be disabled in the package `setup.py`. Am I correct in understanding this is just a default state and that these normally be then enabled (using the environment variables) in CI/CD tasks when wheels are built and published?

Yes, essentially our build setup is by default a relative minimal build, with the assumption you have to enable the additional feature you want (the same is true when building Arrow C++ from source). 

Although in the case of pyarrow, when it's building against an Arrow C++ build that already made such choices, it might be nice to automatically infer whatever is supported by libarrow (if you build both from source that is certainly possible, not sure if that would also work when building agasint a brew-installed Arrow C++)

**Comment by DylanLukes** [comment]
> Although in the case of pyarrow, when it's building against an Arrow C++ build that already made such choices, it might be nice to automatically infer whatever is supported by libarrow (if you build both from source that is certainly possible, not sure if that would also work when building against a brew-installed Arrow C++)

Agreed. And it should be easy enough actually. The file `/opt/homebrew/Cellar/apache-arrow/13.0.0_8/lib/cmake/Arrow/ArrowOptions.cmake` contains the options used for Brew's build (which is from source):

```cmake
...
## Project component options:
### Build the Arrow Acero Engine Module
set(ARROW_ACERO "ON")
### Build Arrow commandline utilities
set(ARROW_BUILD_UTILITIES "OFF")
### Build all Arrow Compute kernels
set(ARROW_COMPUTE "ON")
### Build the Arrow CSV Parser Module
set(ARROW_CSV "ON")
### Build the Arrow CUDA extensions (requires CUDA toolkit)
set(ARROW_CUDA "OFF")
### Build the Arrow Dataset Modules
set(ARROW_DATASET "ON")
### Build the Arrow Filesystem Layer
set(ARROW_FILESYSTEM "ON")
### Build the Arrow Flight RPC System (requires GRPC, Protocol Buffers)
set(ARROW_FLIGHT "ON")
...
```

[ArrowOptions.cmake.txt](https://github.com/apache/arrow/files/13045993/ArrowOptions.cmake.txt)

**Comment by DylanLukes** [comment]
Closing this for now. Awaiting the 14.0.0 wheels :).
