### ISSUE TITLE
[C++] What's the difference between `arrow::internal::BitWriter` and `arrow::internal::FirstTimeBitWriter`

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#38355]
### Describe the usage question you have. Please include as many useful details as  possible.

I've find `arrow::internal::BitWriter` and `arrow::internal::FirstTimeBitWriter` in our repo. The `arrow::internal::FirstTimeBitWriter` has some descriptions:

```
  // Like BitmapWriter, but any bit values *following* the bits written
  // might be clobbered.  It is hence faster than BitmapWriter, and can
  // also avoid false positives with Valgrind.
```

But actually I didn't know what it actually means. When should I use `FirstTimeBitWriter` and when should I use `BitWriter`? Is there any materialize for this?

### Component(s)

C++

**Comment by felipecrv** [comment]
When writing to a bitmap, the CPU can't write only the bits requested, the smallest unit of write is the byte but an entire 64-bit word is more friendly to the micro arch. The way more granularity is achieved (semantically) is by reading the bitmap and crafting a word that contains the existing bits and the new bits (when the bits being written don't align to the 64-bit boundaries).

The `FirstTimeBitmapWriter` will not care about the bits on the tail of the word being written which allows it to write to the bitmap with less operations. It only needs to preserve the bits that antecede the bits being written, no need to read the bits that follow it on the bitmap memory into the word being written.

It's faster when you know your next iteration is going to be over-writing the following bits.

**Comment by mapleFU** [comment]
Get it, thanks @felipecrv !
