### ISSUE TITLE
Question re: change in multi-threaded read in ParquetDataset read() method

### ISSUE THREAD

**Issue by mathemakitten** [apache/arrow#3836]
Hi there! I've been using Pyarrow 0.9.0 but recently switched over to 0.12.1. I noticed that in 0.9.0 I could pass `nthreads=num_threads` to the `ParquetDataset.read` method, but in the newest version I can only pass `use_threads=True`. 

My question is now, how do I control how many threads are being simultaneously used to read data on a machine? When I pass `use_threads=True`, what is the default behaviour? I tried poking around the source code but the reasoning for the API change, as well as the now-expected-behaviour, isn't entirely obvious to me. Thanks!

**Comment by hatemhelal** [comment]
I had a look and that option ultimately finds its way [here](https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/thread-pool.cc#L268).  I think for many machines the value will be determined by `std::thread::hardware_concurrency'.

**Comment by mathemakitten** [comment]
Gotcha, alright. Thank you, that's helpful to know. Do you know if there is any other way to control the number of threads allocated, as in the previous versions of Pyarrow?

**Comment by hatemhelal** [comment]
I missed this option when I was looking yesterday:

https://arrow.apache.org/docs/python/api/misc.html#multi-threading

You should be able to query and modify the number of threads used to read a parquet file like:
```
>>> pyarrow.cpu_count()
8
>>> pyarrow.set_cpu_count(4)
```
As I understand it, the API change was motivated by making parquet file reading use the same parallel settings as other pyarrow APIs.

**Comment by mathemakitten** [comment]
Ah, I see! That's very insightful. Thank you very much for your help!
