### ISSUE TITLE
Find the right pyarrow version for my GLIBC version (AWS Lambda)

### ISSUE THREAD

**Issue by nk-fouque** [apache/arrow#38373]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi, I am using pyarrow as a dependency of another library in my project running on AWS Lambda. 
Sadly, when I try to run my lambda I get the error `lib64/libm.so.6: version 'GLIBC_2.27' not found (required by /mnt/efs/site-packages/pyarrow/libarrow.so.1300)",`
Indeed AWS Lambda documentation specifies [here](https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20230424.html) that the AmazonLinux 2 image only comes with glibc 2.26.
I am trying to figure out how much I have to downgrade pyarrow to find the right version that uses glibc 2.26 but I can't find any indications on the matter.
Help would be appreciated.

### Component(s)

Continuous Integration, Python

**Comment by raulcd** [comment]
Hi,
We did drop support for Amazon Linux 2 on 13.0.0, see: https://github.com/apache/arrow/issues/36241
12.0.0 was still supported. We added support for Amazon Linux 2023 on 13.0.0, see: https://github.com/apache/arrow/issues/36006

**Comment by nk-fouque** [comment]
Thanks, that version worked with no problem.

**Comment by meze-pomelo** [comment]
I get the same error. 
I fix it declaring the next versions

pyarrow == 12.0.1
boto3 == 1.26.76
botocore == 1.29.76 

Context: Amazon Linux 2, with python 3.8

**Comment by monkeyZhy** [comment]
But my system has GLIBC version 2.17, what version of pyarrow supports it?

**Comment by liuss-buaa** [comment]
> But my system has GLIBC version 2.17, what version of pyarrow supports it?

I get the same error. Have you fixed it?

**Comment by monkeyZhy** [comment]
> > But my system has GLIBC version 2.17, what version of pyarrow supports it?
> 
> I get the same error. Have you fixed it?

yes! I remember that you need to downgrade the version of pyarrow to 8.x. You can downgrade bit by bit and debug it.

**Comment by liuss-buaa** [comment]
> > > But my system has GLIBC version 2.17, what version of pyarrow supports it?
> > 
> > 
> > I get the same error. Have you fixed it?
> 
> yes! I remember that you need to downgrade the version of pyarrow to 8.x. You can downgrade bit by bit and debug it.

thank you very much！
