### ISSUE TITLE
[PyArrow] 3.8 Deprecation Notice

### ISSUE THREAD

**Issue by fluffy-samurai** [apache/arrow#3839]
In running pytest against a project that has PyArrow v0.12.1, I see:
```
.venv/lib/python3.7/site-packages/pyarrow/parquet.py:289: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    new_schema = pa.schema(sanitized_fields, metadata=schema.metadata)
```

This is occurring during:
```
import pyarrow.parquet as pq
table_read = pq.read_table('example.parquet')
```

I think it is associated with how this line calls the function:
https://github.com/apache/arrow/blob/1c1bfe8ffc01e877713ae3aeadcd32ea3e597398/python/pyarrow/parquet.py#L290

Does this justify an email to the dev mailing list & how can I help?

**Comment by emkornfield** [comment]
Hi @fluffy-samurai,
If you want to open a JIRA issue on https://issues.apache.org and submit a patch for this issue it would be helpful.  If you don't already have the right permissions on JIRA you can ask for help on the mailing list.

**Comment by wesm** [comment]
Anyone can open a JIRA issue AFAIK

**Comment by wesm** [comment]
Can you open a JIRA issue?

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-4934
