### ISSUE TITLE
[MATLAB] Implement a `TableTypeValidator` class that validates a MATLAB `cell` array contains only `table`s that share the same schema

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#38417]
### Describe the enhancement requested

Adding this `TableTypeValidator` class is a step towards implementing the `arrow.array.ListArray.fromMATLAB` method for creating `ListArray`s whose `ValueType` is a `StructArray`.

### Component(s)

MATLAB

**Comment by sgilmore10** [comment]
take
