### ISSUE TITLE
can't download snappy

### ISSUE THREAD

**Issue by assassin5615** [apache/arrow#3841]
I can build arrow without any problem on other boxes, but always encountered problem on one box that has Oracle Linux 6 installed while downloading snappy.

the error log says

```
CMake Error at snappy_ep-stamp/download-snappy_ep.cmake:21 (message):
  error: downloading
  'https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz'
  failed

    status_code: 35
    status_string: "SSL connect error"
    log:   Trying 13.250.177.223...

```
I tried `wget https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz` and got the "Unable to establish SSL connection" error. 

I am not sure if this is related to the fact that snappy is actually located on aws. as brotli can be downloaded fine from code.github.com on the same box.

**Comment by wesm** [comment]
I'm not sure what we can reasonably do about this. If you want to open a JIRA issue and suggest a remedy please go ahead

**Comment by fsaintjacques** [comment]
This wget works locally. @assassin5615 any success if you retry. I'd also suggest increasing verbosity of wget/curl.

**Comment by assassin5615** [comment]
@wesm  @fsaintjacques  still can't use wget to download snappy. I'll close this issue as it's not really related to arrow. it's more like a wget issue or SSH configuration issue. thanks for your efforts.
