### ISSUE TITLE
[C++] Real null count for DictionaryArray

### ISSUE THREAD

**Issue by R-JunmingChen** [apache/arrow#38457]
### Describe the enhancement requested

Currently, `DictionaryArray::null_count()` counts the number of nulls among the dict indices, but ignores nulls among dict values.  It will be useful that we can count the same of the null number as the DictionaryArray is decoded. That would also help #37100. The implementation could be a member function like `DictionaryArray::CountNullValues`.

### Component(s)

C++

**Comment by kou** [comment]
See also the related discussion: https://github.com/apache/arrow/pull/37100#discussion_r1364128140

We'll not change `DictionaryArray::null_count()` to keep  backward comatibility.
