### ISSUE TITLE
[FeatureRequest] Add strptime functionality to read_csv

### ISSUE THREAD

**Issue by dhirschfeld** [apache/arrow#3847]
I'd like to make use of the new `read_csv` function but it appears that the format of the dates I have isn't supported by `pyarrow`:

```python
In [14]: opts = pa.csv.ConvertOptions(column_types={'issue_date_utc': pa.timestamp('ns')})
    ...: table = pa.csv.read_csv(filename, convert_options=opts)
Traceback (most recent call last):

  File "<ipython-input-14-21df9371c43e>", line 2, in <module>
    table = pa.csv.read_csv(filename, convert_options=opts)

  File "pyarrow\_csv.pyx", line 397, in pyarrow._csv.read_csv

  File "pyarrow\error.pxi", line 81, in pyarrow.lib.check_status

ArrowInvalid: In column #0: CSV conversion error to timestamp[ns]: invalid value '2019-02-26 22:00'

In [15]: !head $filename
issue_date_utc,variable_name,station_name,station_id,value_date_utc,value
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 03:00,29.1
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 03:30,28.9
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 04:00,28.6
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 04:30,28.3
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 05:00,28.0
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 05:30,27.5
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 06:00,27.1
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 06:30,26.6
2019-02-26 22:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 07:00,26.1
```

Since you can't usually get the date-format of your source data changed it would be good to allow the user to specify a format string (similar to [`strptime`](https://docs.python.org/3/library/time.html#time.strftime)) which would then allow for conversions from that format rather than *just* ISO-8601.

I had a look on [JIRA](https://issues.apache.org/jira/browse/ARROW-4803?jql=project%20%3D%20ARROW%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20text%20~%20%22parse%20timestamp%22) but couldn't see any existing open issue so have opened this here. If there's no existing issue which captures this functionality I'm happy to move it over to JIRA.

**Comment by dhirschfeld** [comment]
If my date format were slightly different it looks like it would work:
```python
In [47]: csv = io.BytesIO(b'''issue_date_utc,variable_name,station_name,station_id,value_date_utc,value
    ...: 2019-02-26 22:00:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 03:00,29.1
    ...: ''')

In [48]: pa.csv.read_csv(csv, convert_options=opts)
Out[48]: 
pyarrow.Table
issue_date_utc: timestamp[ns]
variable_name: string
station_name: string
station_id: int64
value_date_utc: string
value: double
```

**Comment by dhirschfeld** [comment]
I looks like the `read_csv` closes the file-handle passed to it - is this the desired behaviour?
```python
In [49]: csv.seek(0)
Traceback (most recent call last):

  File "<ipython-input-50-0644e6e50712>", line 1, in <module>
    csv.seek(0)

ValueError: I/O operation on closed file.
```
It seems to me if you pass in a file-handle it should be the users responsibility to close it?

In comparison, `pandas` doesn't close the file-handle:
```python
In [55]: pd.read_csv(csv)
Out[55]: 
        issue_date_utc variable_name  ...    value_date_utc  value
0  2019-02-26 22:00:00   TEMPERATURE  ...  2019-02-27 03:00   29.1

[1 rows x 6 columns]

In [56]: csv.seek(0)
Out[56]: 0

In [57]: pd.read_csv(csv)
Out[57]: 
        issue_date_utc variable_name  ...    value_date_utc  value
0  2019-02-26 22:00:00   TEMPERATURE  ...  2019-02-27 03:00   29.1

[1 rows x 6 columns]
```

**Comment by dhirschfeld** [comment]
Also, it seems `pyarrow` doesn't support `io.StringIO`:
```python
In [59]: csv = io.StringIO('''issue_date_utc,variable_name,station_name,station_id,value_date_utc,value
    ...: 2019-02-26 22:00:00,TEMPERATURE,ARCHERFIELD,040211,2019-02-27 03:00,29.1
    ...: ''')

In [60]: pd.read_csv(csv)
Out[60]: 
        issue_date_utc variable_name  ...    value_date_utc  value
0  2019-02-26 22:00:00   TEMPERATURE  ...  2019-02-27 03:00   29.1

[1 rows x 6 columns]

In [61]: pa.csv.read_csv(csv)
Traceback (most recent call last):

  File "<ipython-input-61-d86447415aa3>", line 1, in <module>
    pa.csv.read_csv(csv)

SystemError: <built-in function read_csv> returned NULL without setting an error
```
It would be nice/convenient if it did.

**Comment by emkornfield** [comment]
I think all of these seem like valid issues (I'm not 100% sure on closing the file handle).  https://issues.apache.org/jira/browse/ARROW-3739 might have some overlap with the Timesamp converting.  Could you create separate JIRAs for each?

**Comment by wesm** [comment]
@dhirschfeld this isn't the right place for feature requests -- definitely use JIRA in the future for all of these. The strptime request is already in JIRA https://issues.apache.org/jira/browse/ARROW-3739

**Comment by dhirschfeld** [comment]
Noted! Thanks for the link - I'm following that issue now.

I'll open JIRAs for the remaining issues...

**Comment by dhirschfeld** [comment]
JIRAs opened:
* [`ARROW-4824`](https://issues.apache.org/jira/projects/ARROW/issues/ARROW-4824) `read_csv` should accept io.StringIO objects
* [`ARROW-4823`](https://issues.apache.org/jira/projects/ARROW/issues/ARROW-4823) `read_csv` shouldn't close file handles it doesn't own
