### ISSUE TITLE
[C++] Should we add a arrow::RecordBatchWriter and make it parent of arrow::ipc::RecordBatchWriter

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#38487]
### Describe the enhancement requested

I'm trying to use CSV writer. However, CSV writer returns a `arrow::ipc::RecordBatchWriter`, this is so weird :-(

Since `arrow::ipc::RecordBatchWriter` is already public. Can we add a arrow::RecordBatchWriter here?

### Component(s)

C++

**Comment by mapleFU** [comment]
@lidavidm Is this expected 🤔? Or how could we by pass this? Since it's a bit weird here..

**Comment by lidavidm** [comment]
Is it causing problems?

**Comment by mapleFU** [comment]
No, but create a csv writer should require a ipc interface looks weird.

It doesn't introduce any problem.

**Comment by mapleFU** [comment]
Okay, let me close it first
