### ISSUE TITLE
[python] Datetime type does not keep time information

### ISSUE THREAD

**Issue by haixuanTao** [apache/arrow#38488]
### Describe the bug, including details regarding any error messages, version, and platform.

I was reading arrow file from python and noticed that the time information in DateTime type is not kept.

## To reproduce

```python
import pyarrow as pa
from datetime import datetime
expected_value = datetime(2012, 1, 1, 1, 1, 1)
returned_value = pa.scalar(expected_value, type=pa.date64()).as_py()
assert returned_value  == expected_value, "original value is not kept intact"
```

## Version
pyarrow 0.13

### Component(s)

Python

**Comment by rok** [comment]
This is a gotcha I hit myself occasionally. While `date64` stores dates with millisecond precision it still stores them rounded to day, so your timestamp gets rounded (floored) to nearest midnight. A more natural choice of unit here would be pa.timestamp("ms").
See arrow's definition of `date64` below:
https://github.com/apache/arrow/blob/6e6fd0a30aebee6738bb4bb703344f0c866debea/format/Schema.fbs#L240-L253

**Comment by haixuanTao** [comment]
indeed. I skipped the last part about being divisible by 86400000 ms i.e. a day.

Thanks for the quick response!
