### ISSUE TITLE
[Go][Parquet] Trouble using the C++ reader to read a Parquet file written with the Go writer

### ISSUE THREAD

**Issue by tschaub** [apache/arrow#38503]
### Describe the bug, including details regarding any error messages, version, and platform.

**Version**: https://github.com/apache/arrow/commit/7ef517e31ec3
**OS**: macOS 13 arm64

I'm uncertain if this is user error, an issue with the Go packages, or an issue with the C++ reader.  I've put together a test that demonstrates the issue here: https://github.com/tschaub/parquet-issue-38503

I'm trying to use the `pqarrow` package to read an input Parquet file, transform some of the data, and write an output Parquet file.  In the [linked test case](https://github.com/tschaub/parquet-issue), there is no transformation step.  So the test uses a `pqarrow.FileReader`, gets a `pqarrow.RowGroupReader` for each row group, reads each column as an `arrow.Chunked`, and uses a `pqarrow.ArrowColumnWriter` to write out the same.

When I try to use the C++ `parquet-reader` to read in the output file, I see the following error:
```shell
# parquet-reader output.parquet > /dev/null
Parquet error: Malformed levels. min: 2 max: 2 out of range.  Max Level: 1
```

This same test passes for other Parquet files.  I originally encountered the problem with one of the [Overture Maps](https://github.com/OvertureMaps/data) Parquet files, and the linked test case is based on a subset of that data using only two columns and a single row.

**Summarizing**

| file | [C++ reader](https://github.com/apache/arrow/blob/main/cpp/tools/parquet/parquet_reader.cc) | [Go reader](https://github.com/apache/arrow/tree/main/go/parquet/cmd/parquet_reader) |
| --- | :---: | :---: |
| `input.parquet` | ✅ | ✅ |
| `output.parquet` | ❌ | ✅ |

### Component(s)

Go, Parquet

**Comment by mapleFU** [comment]
Sorry for late reply. Run case in https://github.com/tschaub/parquet-issue-38503 can generate the case?

**Comment by mapleFU** [comment]
```
# parquet-reader output.parquet > /dev/null
Parquet error: Malformed levels. min: 2 max: 2 out of range.  Max Level: 1
```

This is weird 😅 This means go generate level == 2 when max-level == 1. Let me checkout the reason.

**Comment by mapleFU** [comment]
Updated: I think C++ reader checks max-rep-level, and it's 1. (and def-max is 3). So it report the error.

**Comment by mapleFU** [comment]
After rethink the impl, I found it's the impl's problem rather than a bug.

```
	ctx := context.Background()
	numFields := len(arrowReader.Manifest.Fields)
	numRowGroups := fileReader.NumRowGroups()
	for rowGroupIndex := 0; rowGroupIndex < numRowGroups; rowGroupIndex += 1 {
		rowGroupReader := arrowReader.RowGroup(rowGroupIndex)
		rowGroupWriter := fileWriter.AppendRowGroup()
		for fieldNum := 0; fieldNum < numFields; fieldNum += 1 {
			arr, err := rowGroupReader.Column(fieldNum).Read(ctx)
			fmt.Println("Read field: ", fieldNum)
			if err != nil {
				return nil, err
			}
			colWriter, err := pqarrow.NewArrowColumnWriter(arr, 0, int64(arr.Len()), arrowReader.Manifest, rowGroupWriter, fieldNum)
			if err != nil {
				return nil, err
			}
			if err := colWriter.Write(ctx); err != nil {
				return nil, err
			}
		}
	}
	if err := fileWriter.Close(); err != nil {
		return nil, err
	}
```

```
colWriter, err := pqarrow.NewArrowColumnWriter(arr, 0, int64(arr.Len()), arrowReader.Manifest, rowGroupWriter, fieldNum)
```

The code above is abit dangerous, the real code should be:

```
	numRowGroups := fileReader.NumRowGroups()
	for rowGroupIndex := 0; rowGroupIndex < numRowGroups; rowGroupIndex += 1 {
		rowGroupReader := arrowReader.RowGroup(rowGroupIndex)
		rowGroupWriter := fileWriter.AppendRowGroup()
		colIdx := 0
		for fieldNum := 0; fieldNum < numFields; fieldNum += 1 {
			arr, err := rowGroupReader.Column(fieldNum).Read(ctx)
			fmt.Println("Read field: ", fieldNum)
			for _, v := range arr.Chunks() {
				fmt.Println("CHUNK:" , v)
			}
			if err != nil {
				return nil, err
			}
			colWriter, err := pqarrow.NewArrowColumnWriter(arr, 0, int64(arr.Len()), arrowReader.Manifest, rowGroupWriter, colIdx)
			if err != nil {
				return nil, err
			}
			if err := colWriter.Write(ctx); err != nil {
				return nil, err
			}
			colIdx += colWriter.LeafCount()
		}
	}
```

`colWriter.LeafCount()` cannot be get now, maybe we need using other way.

**Comment by mapleFU** [comment]
And currently, the generated file is a bad file here...
