### ISSUE TITLE
Python docs for use_compliant_nested_typebool on ParquetWriter states default is both True and False.

### ISSUE THREAD

**Issue by kitsunde** [apache/arrow#38510]
Title and description is conflicts: https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html#pyarrow-parquet-parquetwriter

> use_compliant_nested_type[bool](https://docs.python.org/3/library/stdtypes.html#bltin-boolean-values), **default True**
> 
> Whether to write compliant Parquet nested type (lists) as defined [here](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#nested-types), **defaults to False**. [..]

### Component(s)

Python

**Comment by mapleFU** [comment]
This is fixed in https://github.com/apache/arrow/pull/38471

And default is True now.
