### ISSUE TITLE
[Python] S3FileSystem equals None causes bus error

### ISSUE THREAD

**Issue by matthewdeng** [apache/arrow#38535]
### Describe the bug, including details regarding any error messages, version, and platform.

**Version:** `pyarrow==13.0.0`

**Repro script:**
```python
import pyarrow.fs

fs = pyarrow.fs.S3FileSystem()
fs != None
```

**Output:**
```
[1]    77091 bus error  python
```

I can do `fs is not None` as a workaround for now.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
@matthewdeng Thanks for the report! Can confirm this also happens on the main branch. 

I think there is a `not None` missing in the signature here:

https://github.com/apache/arrow/blob/4aa9f604dfdab4c4b524a5b18c7976adb10c9b41/python/pyarrow/_fs.pyx#L508
