### ISSUE TITLE
0.11.1 python source not on pypi?

### ISSUE THREAD

**Issue by ryan-williams** [apache/arrow#3855]
Python source tar.gz's present on pypi.org:
- [x] [0.12.1](https://pypi.org/project/pyarrow/0.12.1/#files)
- [x] [0.12.0](https://pypi.org/project/pyarrow/0.12.0/#files)
- [x] [0.11.1](https://pypi.org/project/pyarrow/0.11.1/#files)
- [x] [0.11.0](https://pypi.org/project/pyarrow/0.11.0/#files)

Is this intentional?

0.11.1 being missing is [causing problems](https://issues.apache.org/jira/browse/BEAM-6765) in Beam / tensorflow/transform contexts

**Comment by xhochy** [comment]
@ryan-williams We can upload the sources for 0.11.1 to PyPI but this won't fix your problems as for compiling pyarrow from source, you need the Apache Arrow C++ binaries pre-installed.

But as far as I understand data flow, `pyarrow==0.11.1` should already be preinstalled on the workers: https://cloud.google.com/dataflow/docs/concepts/sdk-worker-dependencies

**Comment by xhochy** [comment]
@kou @kszucs Generating the source tarball would probably be just done by running the `manylinux1` docker of that release locally? Or is there a better way to do this?

**Comment by ryan-williams** [comment]
@xhochy thanks for the quick response!

I think both of your points are correct, but also that having the pyarrow sources on pypi is the simplest way to have things work as intended everywhere (including here; I assume the missing pyarrow sources are an oversight and worth correcting on their own, or at least figuring out why they're only being released sometimes?).

Beam/Dataflow don't have a way to say "stage these libraries on the workers, but skip certain transitive-deps that happen to already be on the workers **and** which will fail to resolve due to missing source artifacts". Maybe one or both halves of that are worth adding hooks for over there, but it's a bit convoluted vs the default behavior of "it's ok if some things get redundantly staged".

Anyway, those aren't really arrow concerns ofc, but I figured it was worthwhile to understand why pyarrow sources are sometimes missing, at least.

**Comment by kou** [comment]
@xhochy I'm not sure but the following command lines will work:

https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide#ReleaseManagementGuide-pipPackages

```shell
git checkout apache-arrow-0.11.1
python setup.py sdist upload
git checkout apache-arrow-0.12.0
python setup.py sdist upload
```

**Comment by wesm** [comment]
Maintaining source installs from PyPI has not been a priority for us. Does someone want to push the tarballs? We might want to embolden the sdist step in the RM notes for furture releases

**Comment by kou** [comment]
I want pyarrow source package to build pyarrow with system deb/rpm Arrow C++ packages too.
So I'll upload pyarrow source packages for 0.11.1 and 0.12.0 when someone confirms that the `sdist upload` approach is correct.

**Comment by xhochy** [comment]
@kou Yes, the approach is correct. We should be more careful with this in future releases. I still dream of having a self-contained wheel one day.

**Comment by xhochy** [comment]
@kou Wait. Please only use `python setup.py sdist` and then upload using `twine`.

**Comment by xhochy** [comment]
@kou I've uploaded sources for `0.12.0` but was unable to pull the `apache-arrow-0.11.1` tag from github.

**Comment by kou** [comment]
@xhochy Thanks for confirming this! I've upload 0.11.1 from `apache-arrow-0.11.1` and update https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide#ReleaseManagementGuide-pipPackages .
