### ISSUE TITLE
[C++] Missing FindArrow.cmake in the recent versions

### ISSUE THREAD

**Issue by kabicm** [apache/arrow#38583]
### Describe the usage question you have. Please include as many useful details as  possible.

It seems `FindArrow.cmake` file is removed from releases after 9.0.0. When using the newer Arrow versions (14.0.0), I am getting the following cmake error:
```
Could not find a package configuration file named "FindArrow.cmake"
  provided by package "Arrow".

  Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
  "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
  provides a separate development package or SDK, be sure it has been
  installed.
  ```
With versions prior to 9.0.0, this is not a problem, since they are shipped with FindArrow.cmake. Should I simply use the FindArrow.cmake from version 9.0.0 with version 14.0.0?

### Component(s)

C++

**Comment by kou** [comment]
We provide `ArrowConfig.cmake` instead of `FindArrow.cmake`.
`find_package(Arrow)` uses `ArrowConfig.cmake` not `FindArrow.cmake` without configuration. See also: https://cmake.org/cmake/help/latest/command/find_package.html
How do you require `FindArrow.cmake`?

**Comment by kabicm** [comment]
Thanks Sutou for the response! I wasn't aware that ArrowConfig.cmake was present instead.

Now I am using the following to find Arrow:
```
message(STATUS "Arrow installed here: " ${ARROW_ROOT}/install)
if (EXISTS "${ARROW_ROOT}/install/lib")
    set(ARROW_LIBRARY_DIR "${ARROW_ROOT}/install/lib")
elseif (EXISTS "${ARROW_ROOT}/install/lib64")
    set(ARROW_LIBRARY_DIR "${ARROW_ROOT}/install/lib64")
else ()
    message(ERROR "Unable to find Arrow lib directory in ${ARROW_ROOT}/install")
endif ()
set(ARROW_INCLUDE_DIR "${ARROW_ROOT}/install/include")
message(STATUS "Arrow libs dir: " ${ARROW_LIBRARY_DIR})
message(STATUS "Arrow include dir: " ${ARROW_INCLUDE_DIR})

# add a path to ArrowConfig.cmake to CMAKE_PREFIX_PATH
list(APPEND CMAKE_PREFIX_PATH "${ARROW_LIBRARY_DIR}/cmake/Arrow")
list(APPEND CMAKE_PREFIX_PATH "${ARROW_LIBRARY_DIR}/cmake/ArrowTesting")

find_package(Arrow REQUIRED)
find_package(ArrowTesting REQUIRED)
```

Is it the proper way to include it in a cmake project?


Thank you for your help!

**Comment by kou** [comment]
This will work:

```cmake
message(STATUS "Arrow installed here: " ${ARROW_ROOT}/install)
# add a path to lib*/cmake/*/Arrow{,Testing}Config.cmake to CMAKE_PREFIX_PATH
list(PREPEND CMAKE_PREFIX_PATH "${ARROW_ROOT}/install")
find_package(Arrow REQUIRED)
find_package(ArrowTesting REQUIRED)
```

**Comment by kabicm** [comment]
Great, thanks a lot Sutou, it works now!
