### ISSUE TITLE
[Docs] The main logo changes with the browser's vertical size.

### ISSUE THREAD

**Issue by llama90** [apache/arrow#38645]
### Describe the bug, including details regarding any error messages, version, and platform.

As the title suggests, the main logo changes with the browser's vertical size. It sometimes grows large enough to be a hindrance while navigating the document.

<details><summary>small</summary>

![image](https://github.com/apache/arrow/assets/6668548/d98324e1-1634-4bcc-be18-17ee567bd0d0)

</details>

<details><summary>middle</summary>

![image](https://github.com/apache/arrow/assets/6668548/64f2409f-5249-44b0-9d70-c5e724358941)

</details>

<details><summary>big</summary>

![image](https://github.com/apache/arrow/assets/6668548/3964b173-cbc0-45c8-ba71-b417f4a261b7)

</details>

### Component(s)

Documentation

**Comment by jorisvandenbossche** [comment]
Hmm, that's not suppose to happen. Which browser are you using? (I can't reproduce this on Firefox on Linux)

cc @AlenkaF

**Comment by llama90** [comment]
I use the M1 Macbook, with Chrome (version: 118.0.5993.117). This seems to depend on the environment. Safari is fine...

<details><summray>safari</summary>

<img width="1311" alt="image" src="https://github.com/apache/arrow/assets/6668548/ee305ca8-324f-4d69-9e09-326bf59819e3">

</details>

**Comment by AlenkaF** [comment]
I needed to do a hard refresh in Chrome (shift+reload) - could you try that?
