### ISSUE TITLE
[Java][CI] Java Jars failing on MacOS

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#38653]
### Describe the bug, including details regarding any error messages, version, and platform.

According to crossbow,

First failure: https://github.com/ursacomputing/crossbow/actions/runs/6795651621/job/18475552909

Last successful commit: https://github.com/apache/arrow/compare/25c18d8cd6a299f3bb6b72966f2dca357db26399...e62ec62e40b04b0bfce76d58369845d3aa96a419

We're seeing a lot of version mismatches in the logs.

aarch64 example:
```
In file included from /Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/cpp-build/cpp/src/gandiva/CMakeFiles/gandiva-internals-test.dir/Unity/unity_2_cxx.cxx:22:
/Users/voltrondata/github-actions-runner/_work/crossbow/crossbow/arrow/cpp/src/gandiva/tests/test_util.cc:35:18: error: 'string' is unavailable: introduced in macOS 10.15
  return ir_file.string();
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__filesystem/path.h:852:39: note: 'string' has been explicitly marked unavailable here
  _LIBCPP_HIDE_FROM_ABI _VSTD::string string() const { return __pn_; }
                                      ^
```

x86_64 example:
```
In file included from /Users/runner/work/crossbow/crossbow/arrow/cpp-build/cpp/src/gandiva/CMakeFiles/gandiva-internals-test.dir/Unity/unity_2_cxx.cxx:22:
/Users/runner/work/crossbow/crossbow/arrow/cpp/src/gandiva/tests/test_util.cc:35:18: error: 'string' is unavailable: introduced in macOS 10.15
return ir_file.string();
                  ^

/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:1266:43: note: 'string' has been explicitly marked unavailable here
   _LIBCPP_INLINE_VISIBILITY _VSTD::string string() const { return __pn_; }
                                           ^
```

### Component(s)

Continuous Integration, Java

**Comment by kou** [comment]
Oh.
@niyue could you take a look at this?

**Comment by niyue** [comment]
Sure. I took a brief look and the CI seems to complain `std::filesystem::path` cannot be used on macOS 14.0 aarch64, but this env is also what I use locally and I don't find such issue. I will take a closer look today.

**Comment by niyue** [comment]
I submitted a PR trying to address this issue: https://github.com/apache/arrow/pull/38677

But it requires raising the minimum macOS deployment target from 10.14 to 10.15, and you can check out the PR for more details.
