### ISSUE TITLE
[C++] Arrow 13.0.0, python ADBC connection flight server got authentication error

### ISSUE THREAD

**Issue by xinyiZzz** [apache/arrow#38666]
### Describe the usage question you have. Please include as many useful details as  possible.

I got an error when using Python ADBC to connect to the flight server implemented in C++.
```
conn = flight_sql.connect(uri="grpc://127.0.0.1:xxx", db_kwargs={
            adbc_driver_manager.DatabaseOptions.USERNAME.value: "root",
            adbc_driver_manager.DatabaseOptions.PASSWORD.value: "",
        })
cursor = conn.cursor()
start_time = datetime.now()
cursor.execute(sql)
arrow_data = cursor.fetchallarrow()

> adbc_driver_manager.OperationalError: IO: [FlightSQL] connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:9080: connectex: no connection could be made because the target machine actively refused it." (Unavailable; AuthenticateBasicToken)
```

I implemented flight server in C++ like this:
```
_header_middleware = std::make_shared<NoOpHeaderAuthServerMiddlewareFactory>();
_bearer_middleware = std::make_shared<NoOpBearerAuthServerMiddlewareFactory>();
flight_options.auth_handler = std::make_unique<arrow::flight::NoOpAuthHandler>();
flight_options.middleware.push_back({"header-auth-server", _header_middleware});
flight_options.middleware.push_back({"bearer-auth-server", _bearer_middleware});
```

I'm looking for help, thanks!

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
> no connection could be made because the target machine actively refused it

Are you absolutely sure that the port is correct and that the C++ server is fully active and listening?

**Comment by xinyiZzz** [comment]
> Are you absolutely sure that the port is correct and that the C++ server is fully active and listening?

Thx for your reply, port is correct and flight server is normally active. 

I used the above python statement to connect successfully on Centos and MacOS, but failed to connect on Windows, adbc_driver_manager Version 0.7

I will verify it on another machine and comment again.

**Comment by xinyiZzz** [comment]
```
OperationalError                          Traceback (most recent call last)
Cell In[3], line 9
      6 sql = "select * from hdf5 limit 1000000;"
      7 my_uri = "grpc://xxxx:10478"
----> 9 conn = flight_sql.connect(uri=my_uri, db_kwargs={
     10             adbc_driver_manager.DatabaseOptions.USERNAME.value: "root",
     11             adbc_driver_manager.DatabaseOptions.PASSWORD.value: "",
     12         })
     13 cursor = conn.cursor()
     14 start_time = datetime.now()

File ~\anaconda\Lib\site-packages\adbc_driver_flightsql\dbapi.py:120, in connect(uri, db_kwargs, conn_kwargs, **kwargs)
    118 try:
    119     db = adbc_driver_flightsql.connect(uri, db_kwargs=db_kwargs)
--> 120     conn = adbc_driver_manager.AdbcConnection(db, **(conn_kwargs or {}))
    121     return adbc_driver_manager.dbapi.Connection(db, conn, **kwargs)
    122 except Exception:

File ~\anaconda\Lib\site-packages\adbc_driver_manager\_lib.pyx:617, in adbc_driver_manager._lib.AdbcConnection.__init__()

File ~\anaconda\Lib\site-packages\adbc_driver_manager\_lib.pyx:227, in adbc_driver_manager._lib.check_error()

OperationalError: IO: [FlightSQL] connection error: desc = "transport: Error while dialing: dial tcp xxxx:10478: connectex: An established connection was aborted by the software in your host machine." (Unavailable; AuthenticateBasicToken)
```
On the same LAN, I still get error on Windows. not problem on MacOS. The code is the Python above.
@lidavidm  Ask for advice, Is there any special way to use ADBC on Windows?

adbc_driver_manager version 0.8
adbc_driver_flightsql version 0.8

**Comment by lidavidm** [comment]
Is there any Windows Firewall popup or similar? You appear to just be getting generic Windows errors. Are you able to telnet to the server port, or hit it with cURL?

**Comment by lidavidm** [comment]
`https://github.com/tinode/chat/issues/183` / `https://github.com/go-sql-driver/mysql/issues/657` have the same symptoms (Golang, Windows, error message) but different context (it appears to be a long-lived connection); it may still be worth investigating, though.

**Comment by xinyiZzz** [comment]
@lidavidm thank you for the reports, I tried telnet flight server port and it worked, I will research this more.

**Comment by xinyiZzz** [comment]
Completely turned off Windows Defender Firewall and the problem disappeared. Thanks again.
