### ISSUE TITLE
[Python][Docs] Time32Type "unit" docs are outdated

### ISSUE THREAD

**Issue by Tishj** [apache/arrow#38683]
### Describe the bug, including details regarding any error messages, version, and platform.

<https://arrow.apache.org/docs/python/generated/pyarrow.Time32Type.html>

This claims that these are valid options for `unit`:
> The time unit (‘s’, ‘ms’, ‘us’ or ‘ns’).

Using help on the `pyarrow.time32` method shows that only `s` and `ms` are valid options.

### Component(s)

Documentation, Python

**Comment by rok** [comment]
Agreed. That is not documented correctly.

**Comment by ShaiviAgarwal2** [comment]
Based on the information you provided, it seems that there is a discrepancy between the documentation and the actual implementation of the **pyarrow.time32 method**. The documentation claims that the valid options for the time unit are `'s', 'ms', 'us', or 'ns'`, while the help command shows that only `'s' and 'ms'` are valid options. This could potentially cause confusion for developers trying to use this library. 

Can you please provide more information about the error messages and version you are using?

> ### Describe the bug, including details regarding any error messages, version, and platform.
> https://arrow.apache.org/docs/python/generated/pyarrow.Time32Type.html
> 
> This claims that these are valid options for `unit`:
> 
> > The time unit (‘s’, ‘ms’, ‘us’ or ‘ns’).
> 
> Using help on the `pyarrow.time32` method shows that only `s` and `ms` are valid options.
> 
> ### Component(s)
> Documentation, Python

Based on the information you provided, it seems that there is a discrepancy between the documentation and the actual implementation of the **pyarrow.time32** method. The documentation claims that the valid options for the time unit are '`s', 'ms', 'us', or 'ns'`, while the help command shows that only `'s' and 'ms'` are valid options. This could potentially cause confusion for developers trying to use this library.

 Can you please provide more information about the error messages and version you are using?
