### ISSUE TITLE
[C#] Implement ICollection<T?> on scalar arrays

### ISSUE THREAD

**Issue by voidstar69** [apache/arrow#38692]
### Describe the enhancement requested

Issue split off from issue #38348.

### Describe the enhancement requested
If Arrow arrays of scalar type T were to implement ICollection<T?>, it would optimize their use with LINQ (pre-.NET 9), allowing for e.g. fast conversion to lists via the extension method ToList().

This change would to some extent supersede and/or resolve https://github.com/apache/arrow/issues/23892, https://github.com/apache/arrow/issues/35199 and https://github.com/apache/arrow/issues/37359.

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41539
https://github.com/apache/arrow/pull/41539
