### ISSUE TITLE
`FutureWarning` while using `pyarrow` in `awswrangler`

### ISSUE THREAD

**Issue by chanana** [apache/arrow#38690]
### Describe the bug, including details regarding any error messages, version, and platform.

getting a `FutureWarning` while using `awswrangler`. [They are pointing to](https://github.com/aws/aws-sdk-pandas/issues/2510#issuecomment-1791218812) `pyarrow` as a problem.

```python
.../.venv/lib/python3.9/site-packages/awswrangler/_distributed.py:105: FutureWarning: promote has been superseded by mode='default'.
  return cls.dispatch_func(func)(*args, **kw)
```

[current fix](https://github.com/aws/aws-sdk-pandas/issues/2510#issue-1974556671) seems to be to pinning to `pyarrow==13.0.0`

This doesn't prevent me from getting my data so wasn't sure if it was a bug or not!

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
> [They are pointing to](https://github.com/aws/aws-sdk-pandas/issues/2510#issuecomment-1791218812) `pyarrow` as a problem.

Well, I will point back to them ;) 
Of course the warning is coming from pyarrow, but it's exactly to warn users of pyarrow (in this case awswrangler) that they are using a feature of pyarrow that will change. If you want to get rid of the warning, it's the code in awswrangler that has to change. 
(will comment further on the issue on their side)
