### ISSUE TITLE
[C++] Conflict between `arrow::compute::MemAllocation::PREALLOCATE` and system header `vnode.h` preprocessor define

### ISSUE THREAD

**Issue by cholmcc** [apache/arrow#38709]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi, 

On MacOSX the system header [`vnode.h`](https://opensource.apple.com/source/xnu/xnu-6153.41.3/bsd/sys/vnode.h.auto.html) defines the symbol `PREALLOCATE` as a preprocessor define.   This causes a compilation error with `#include <arrow/compute/kernel.h>` where this name (`PREALLOCATE`) is used as an identifier , if `sys/vnode.h` and `arrow/compute/kernel.h` are both (possibly indirectly) included into the same compilation unit. 

Perhaps the `PREALLOCATE` symbol should be `#undef` in `arrow/compute/kernel.h` in case it is defined as preprocessor macro - e.g., 

```
    #if defined(__APPLE__) and defined(PREALLOCATE)
    # undef PREALLOCATE 
    #endif  
```
Yours,
_Christian_

### Component(s)

C++

**Comment by kou** [comment]
Could you open a pull request with the approach?

Or we can use `kPreallocate` name because our coding style uses the convention: https://google.github.io/styleguide/cppguide.html#Enumerator_Names
But it breaks backward compatibility and our many existing source codes don't follow the convention...

**Comment by cholmcc** [comment]
Hi, 

I think I would suggest to use the `kPreallocate` approach, as it is much less likely to cause conflicts.   However, I would worry a little about backward compatibility with existing client code. 

I made a [PR](https://github.com/apache/arrow/compare/main...cholmcc:arrow:patch-2).  If you choose the `kPreallocate` route, then just kill the PR. 

Yours,
_Christian_

**Comment by kou** [comment]
Let's choose `undef` approach for now.

It seems that a PR isn't made yet. Could you ensure opening a PR with the change?
