### ISSUE TITLE
[C++][FS][Azure] Implement `Move()`

### ISSUE THREAD

**Issue by kou** [apache/arrow#38704]
### Describe the enhancement requested

It's not implemented yet.

This is a child of GH-18014.

### Component(s)

C++

**Comment by Tom-Newton** [comment]
This is a potential complication with move. Azure blob storage does support efficient server side only moves.... but only if using SAS token authentication for the source. Alternatively everything will need to be downloaded and re-uploaded, but that should work with any authentication.

**Comment by nosterlu** [comment]
Maybe copy and then delete? That is at least how I have solved it previously with adlfs and Azure 😅

**Comment by Tom-Newton** [comment]
I don't think I was thinking very carefully when I posted that comment. 

I think move is efficiently supported with hierarchical namespace. E.g. using https://github.com/Azure/azure-sdk-for-cpp/blob/4a32d7266cfac8bfc0eb87feb56011361a36f43c/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_file_system_client.hpp#L239

What I was thinking of was the copy blob by URI which has to use SAS token auth. But if we're only copying within one storage account we don't need to use that https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id#authorization. So I do think there is any problem 🙂

**Comment by felipecrv** [comment]
@kou if you haven't started to work on this one I'm happy to take it.

**Comment by kou** [comment]
I haven't. Please do it!

**Comment by av8or1** [comment]
felipecrv - Did you begin work on this one?

**Comment by felipecrv** [comment]
> felipecrv - Did you begin work on this one?

Yes. I'm very close to sending a PR.
