### ISSUE TITLE
Is there a way to turn off RLE encoding for float columns in parquet (using `write_table()`)?

### ISSUE THREAD

**Issue by alippai** [apache/arrow#38722]
### Describe the usage question you have. Please include as many useful details as  possible.

When writing the file with pyarrow 13.0.0 (column not included in dictionary encoded columns) and observing with the duckdb  `parquet_metadata()` I see that the DOUBLE type column `encodings` information shows `RLE` next to the `PLAIN`.

Is this a pyarrow missing feature or a duckdb bug?

### Component(s)

Parquet

**Comment by alippai** [comment]
A small example:

```python
import pyarrow as pa
import pyarrow.parquet as pq
import duckdb

print(pa.__version__) #13.0.0
print(duckdb.__version__) #0.9.2
t = pa.Table.from_pydict({"a": [1.0]})
pq.write_table(t, '/tmp/out.parquet', version='2.6', data_page_version='2.0', use_dictionary=[])
duckdb.sql("select encodings from parquet_metadata('/tmp/out.parquet')").df() #RLE, PLAIN
```

**Comment by alippai** [comment]
Making the field not nullable doesn't change the output

**Comment by alippai** [comment]
parquet-mr looks good?
```
Row group 0:  count: 1  76.00 B records  start: 4  total(compressed): 76 B total(uncompressed):74 B
--------------------------------------------------------------------------------
   type      encodings count     avg size   nulls   min / max
a  DOUBLE    S   _     1         76.00 B    0       "1.0" / "1.0"```

**Comment by mapleFU** [comment]
Aha, @alippai . Parquet-format has an encoding in the file, it will do:
1. mark `RLE` if rep-def level using rle (for nullable type )
2. Since this not using dictionary, so dict is unrelated

You can also refer to the test in this patch: https://github.com/apache/arrow/pull/35758

[1] https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L777

**Comment by alippai** [comment]
Ok, I see the data and pages look good. Only the metadata describes that the column _might_ have RLE (it doesn't have it).
```
    // And for now, we always add RLE even if there are no levels at all,
    // while parquet-mr is more fine-grained.
```

**Comment by alippai** [comment]
Thanks @mapleFU!

**Comment by mapleFU** [comment]
> Only the metadata describes that the column might have RLE (it doesn't have it).

**Comment by mapleFU** [comment]
> Only the metadata describes that the column might have RLE (it doesn't have it).

If the data is nullable, it will containing Def level, def level is usally encoded by RLE :-)
