### ISSUE TITLE
[Python][Geopandas][AWS] Missing optional dependency 'pyarrow.parquet' after updating to v14.0.1

### ISSUE THREAD

**Issue by gbarrospfrmwk** [apache/arrow#38749]
### Describe the usage question you have. Please include as many useful details as  possible.

**Issue:** After updating pyarrow from v12.0.1 to v14.0.1 the import error is thrown when I try to use the geopandas `read_parquet` function

**Error** `ImportError: Missing optional dependency 'pyarrow.parquet'. pyarrow is required for Parquet support.  "`

**Env:** AWS Python Lambda 3.10

This error occurs only in the AWS Lambda environment, locally the project runs fine, and I already updated every possible library, checking the version with `poetry show -o `

**pyproject.toml**
```
[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.29.1"
geopandas = "^0.14.1"
pyarrow = "^14.0.1"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.23"
requests = "^2.31.0"
tox = "^4.11.3"
tenacity = "^8.2.3"
memoization = "^0.4.0"
pydantic = "^2.5.1"
urllib3 = "1.26.18"
certifi = "2023.7.22"
tomlkit = "^0.12.3"
virtualenv = "^20.24.6"
pandas = "^2.1.3"
```

### Component(s)

Parquet, Python

**Comment by jorisvandenbossche** [comment]
@gbarrospfrmwk what do you get if you import it directly? (`import pyarrow.parquet as pq`) Does that give an error message?

**Comment by gbarrospfrmwk** [comment]
@jorisvandenbossche this import is made within the geopandas lib, `geopandas.io.arrow _read_parquet()` so I can't import it directly. I downloaded the lambda zip to check if the lib is correctly installed and it is, but this line in `_read_parquet()` function throws the error `parquet = import_optional_dependency("pyarrow.parquet", extra="pyarrow is required for Parquet support.")`

**Comment by jorisvandenbossche** [comment]
Yes, I know the import is coming from geopandas. But the problem is that geopandas hides the original error message. Maybe something is wrong with the pyarrow 14.0.1 package or your install. And in that case the direct error message from importing pyarrow.parquet might provide some useful indication.

**Comment by gbarrospfrmwk** [comment]
I think I found out, I did import it directly and got the error `/lib64/libm.so.6: version GLIBC_2.27 not found (required by /tmp/sls-py-req/pyarrow/libarrow.so.1400)`. After some research I saw that the python lambda uses Amazon Linux 2 which has `glibc 2.26` but the lib expects the version `2.27`, so I have to change my lambda to use Amazon Linux 2023 with `glibc 2.34` if it's not really compatible. As a workaround, I installed the `pyarrow_hotfix` to keep using the pyarrow 12.0.1 but with the security issue solved.

**Comment by jorisvandenbossche** [comment]
That's strange. We do have binary wheels for both a minimum of glibc 2.17 and for 2.28 (see https://pypi.org/project/pyarrow/#files). So I would expect that pip installs the correct one based on your system (and so in this case would pick the "...manylinux_2_17_x86_64.manylinux2014_x86_64.whl" wheel). 

Do you have access to the install logs so you can see what pip exactly installed?

**Comment by gbarrospfrmwk** [comment]
The thing is that I install the libraries in CircleCI pipeline using an `ubuntu 22.04.1 LTS` image, which has `glibc 2.35`, then I export them into a Zip file, so the issue is that my pipeline environment is different from my lambda environment. So it ends up picking the wheel that works for the pipe env but not for my lambda. I tried to remove all wheels from the `poetry.lock` file leaving only the `*manylinux_2_17_x86_64.manylinux2014_x86_64.whl` but the error is still occurring.

**Comment by jorisvandenbossche** [comment]
Potentially related issue: https://github.com/apache/arrow/issues/38373

**Comment by gbarrospfrmwk** [comment]
Thank you for your suggestions, I'm closing this issue
