### ISSUE TITLE
[Java] jdbc:arrow-flight-sql how to execute query without using `PreparedStatement`

### ISSUE THREAD

**Issue by xinyiZzz** [apache/arrow#38742]
### Describe the usage question you have. Please include as many useful details as  possible.

I use the following code to connect to flight sql server to execute query, which will call the server's `createPreparedStatement` method, but unfortunately I unimplemented `createPreparedStatement`.

How to call server's `getFlightInfoStatement` to execute query? I didn't find the implementation in `FlightSqlClient.java`.

```
Connection conn = null;
Statement stmt = null;
Class.forName("org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver");
try {
    conn = DriverManager.getConnection("jdbc:arrow-flight-sql://xx:xx?useServerPrepStmts=false&cachePrepStmts=true&useSSL=false&useEncryption=false", "root", "");

    String sql = "select * from clickbench.hits limit 50";
    stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery(sql);
    int rowNum = rs.getRow();
    System.out.println(rowNum);
    rs.close();
    stmt.close();
    conn.close();
} catch (SQLException e) {
    throw new RuntimeException(e);
}
```
I'm looking for help, thanks!

### Component(s)

FlightRPC, Java

**Comment by jduo** [comment]
FlightSqlClient has execute() overloads that take in a query text and return a FlightInfo.

The JDBC driver internally always prepares and executes a query, even if you use Statement#execute(). This can be changed to support using the direct-execution RPC.

**Comment by xinyiZzz** [comment]
> FlightSqlClient has execute() overloads that take in a query text and return a FlightInfo.
> 
> The JDBC driver internally always prepares and executes a query, even if you use Statement#execute(). This can be changed to support using the direct-execution RPC.

That explains it, thanks for your reply.

I will implement a series of methods of `PreparedStatement`.
