### ISSUE TITLE
[C++][FS][Azure] Should `GetFileInfo()` against a directory always return true without hierarchical namespace support?

### ISSUE THREAD

**Issue by kou** [apache/arrow#38772]
### Describe the enhancement requested

Because `CreateDir()` without hierarchical namespace support does nothing and returns `arrow::Status::OK()`.

See also the discussion: https://github.com/apache/arrow/pull/38708#discussion_r1397948435

### Component(s)

C++

**Comment by felipecrv** [comment]
I thought a bit more about this idea and realized always returning `OK()` on "directory exists?" queries would contradict the post-condition of `DeleteDir()` – after `DeleteDir()` the caller expects `DirectoryExists()` to return `false`.

I think our approach of doing nothing on `CreateDir` has to be reconsidered. `s3fs.cc` creates an empty object with a path ending in `/` to indicate a directory was created:

```cpp
  Status CreateEmptyDir(const std::string& bucket, const std::string& key) {
    DCHECK(!key.empty());
    return CreateEmptyObject(bucket, key + kSep);
  }
```

**Comment by Tom-Newton** [comment]
Yeah, I saw the "directory markers" thing on the S3 filesystem. Does anyone know if that is an arrow thing or more common pattern with S3? Personally I assumed that was a common pattern in S3 and I'm not aware of the same pattern existing in Azure. 

My only concern with this approach would be when listing blobs. We could handle it in the arrow filesystem but if anybody tries to list with a different blob storage client they might get a confusing result.

**Comment by Tom-Newton** [comment]
It looks like the arrow GCS filesystem also creates directory markers in the same way as S3 https://github.com/apache/arrow/blob/c1b12ca1c331960d7cb4d23980120e4d50fd78b2/cpp/src/arrow/filesystem/gcsfs.cc#L407. The azure fsspec filesystem, though does a noop for create directory https://github.com/fsspec/adlfs/blob/092685f102c5cd215550d10e8347e5bce0e2b93d/adlfs/spec.py#L1060C6-L1060C6

If we chose to create directory markers it would probably be good to add some metadata to the blob to indicate that it's actually a directory. I believe hierarchical namespace accounts add `hdi_isfolder` but looking at the fsspec implementation it checks for several metadata fields https://github.com/fsspec/adlfs/blob/092685f102c5cd215550d10e8347e5bce0e2b93d/adlfs/spec.py#L851.

**Comment by felipecrv** [comment]
> Personally I assumed that was a common pattern in S3 and I'm not aware of the same pattern existing in Azure.

We're trying to impose filesystem semantics on top of a blob store and filesystem semantics require that after a `CreateDir` and `DeleteDir` you get directory exists and directory doesn't exist outcomes.

> The azure fsspec filesystem though, does a noop for create directory https://github.com/fsspec/adlfs/blob/092685f102c5cd215550d10e8347e5bce0e2b93d/adlfs/spec.py#L1060C6-L1060C6

This might not be very relevant here because the goal of the Arrow Filesystem API is to provide an uniform interface on top of regular filesystems and blob storage systems. It's pretty clear that the Azure fsspec is violating filesystem semantics of directory management in this case.

**Comment by Tom-Newton** [comment]
I think I'm in agreement. If we want to be rigorous we need to add directory markers in `CreateDir`. 

I think the current implementation of `GetFileInfo` will already return that a directory is present but probably we should make sure to add a test case for empty directory with just a directory marker. 

Probably I should also have added checks for metadata indicating a blob is a directory marker on `ObjectInputFile::Init` and `ObjectAppendStream::Init`.

**Comment by kou** [comment]
@felipecrv @Tom-Newton Do either of you want to work on this?

**Comment by Tom-Newton** [comment]
> @felipecrv @Tom-Newton Do either of you want to work on this?

I might be able to do it in about a week

**Comment by felipecrv** [comment]
> @felipecrv @Tom-Newton Do either of you want to work on this?

I will take this one.
