### ISSUE TITLE
[R] cmake download doesn't work on macOS

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#38811]
### Describe the bug, including details regarding any error messages, version, and platform.

When downloading from https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-macos-universal.tar.gz in nixlibs.R, this will result in a `CMake.app` being located on the path, we need to add on to the path `CMake.app/Contents/bin/` instead of just `bin`

### Component(s)

R

**Comment by assignUser** [comment]
I came across this as well #38777 but you have already pinpointed the issue so I am closing the other one :)
