### ISSUE TITLE
Applying arrow::compute::Expression on arrow::Table

### ISSUE THREAD

**Issue by kabicm** [apache/arrow#38838]
### Describe the usage question you have. Please include as many useful details as  possible.

As part of implementing a project operator, I am having a vector of expressions that should be applied to an `arrow::Table` object.

I see that `arrow::compute::Expression` can be applied to an `ExecBatch` object by invoking `arrow::compute::ExecuteScalarExpression` function. However, seems that this function only works on ExecBatch.

How can I apply an expression on a table? Moreover, how can I apply a vector of expression on a table?

### Component(s)

C++

**Comment by js8544** [comment]
There is a `MakeExecBatch` function right before `ExecuteScalarExpression` that takes a `Datum`, and `Datum` can be constructed from a `Table`.

**Comment by kabicm** [comment]
Great, thanks Jin!
