### ISSUE TITLE
[Docs] Wrong about the struct hiding valid children values in the example

### ISSUE THREAD

**Issue by stfdxv** [apache/arrow#38883]
### Describe the bug, including details regarding any error messages, version, and platform.

Valid children values are not hidden by the struct's validity bitmap in the example, but the [abstract](https://arrow.apache.org/docs/format/Columnar.html#struct-validity) says they are.
Struct's validity bitmap: 00001011
Field-0's validity bitmap: 00001001
Field-1's validity bitmap: 00001011

### Component(s)

Website

**Comment by stfdxv** [comment]
For example
Struct's validity bitmap: 00001011
Field-0's validity bitmap: 00001101
Field-1's validity bitmap: 00001111

If field-0 or field-1 had valid values at index 2 (hence validity bit 1 at index 2), these values would be hidden indeed by the struct's validity bit 0 at index 2.

**Comment by kou** [comment]
Ah, do you focus on the part?

> This is illustrated in the example above, the child arrays have valid entries for the null struct but they are “hidden” by the struct array’s validity bitmap. However, when treated independently, corresponding entries of the children array will be non-null.

I see. Could you open a pull request to fix the example validity bitmaps?

**Comment by stfdxv** [comment]
I'll do it.
