### ISSUE TITLE
[C++] GCC complains about redundant move

### ISSUE THREAD

**Issue by MrJia1997** [apache/arrow#38889]
### Describe the bug, including details regarding any error messages, version, and platform.

OS: Ubuntu 22.04
GCC: 11.4.0

GCC complains about redundant move when `-Wall`, `-Wextra`, and `-Werror` are enabled, on the following line for example. Does anybody have the same issue?
https://github.com/apache/arrow/blob/eb5de184a7e5d02f98526332ace54250417bd232/cpp/src/arrow/array/builder_base.h#L334

### Component(s)

C++

**Comment by kou** [comment]
Could you show full build log?

**Comment by MrJia1997** [comment]
Sorry, it turns out there's a problem on our build setup. Closed the issue. Thank you for your quick response!
