### ISSUE TITLE
[C++] [Parquet] Move EstimatedBufferedValueBytes from TypedColumnWriter to ColumnWriter

### ISSUE THREAD

**Issue by Hattonuri** [apache/arrow#38887]
### Describe the enhancement requested

Now, i can't easily use this method on array of columns and i need to cast these columns on hot path to calculate estimated total size. This method does not use DType of TypedColumnWriter so can be easily moved to its parent

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
I'll finish it today

**Comment by mapleFU** [comment]
take
