### ISSUE TITLE
[Java] Remove Contrib/Experimental from Flight SQL

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#39037]
### Describe the enhancement requested

Remove the `(Contrib/Experimental)` mention in Java Flight SQL modules which also show up in Maven Central website, as those modules have been part of the project for a while now.

### Component(s)

Java

**Comment by jbonofre** [comment]
Thanks, I gonna take a look.

**Comment by jbonofre** [comment]
I guess documentation should be updated as well. For instance https://arrow.apache.org/docs/format/FlightSql.html still mention experimental.
I can do a pass if you want 😄

**Comment by jbonofre** [comment]
@lidavidm cool ! Thanks ! I'm tackling it 😄
