### ISSUE TITLE
FutureWarning about is_sparse with Pandas>=2.1

### ISSUE THREAD

**Issue by batterseapower** [apache/arrow#39093]
### Describe the bug, including details regarding any error messages, version, and platform.

`pandas_compat.py` calls `pd.is_sparse`:
https://github.com/apache/arrow/blob/1cc1f4c752895301371ee59d315ebffe74224c66/python/pyarrow/pandas_compat.py#L374

With Pandas 2.1, this API is deprecated, so any attempt to e.g. use `DataFrame.to_parquet` prints this warning:

```
pyarrow/pandas_compat.py:373: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
```

A similar bug was flagged in #35329 but the corresponding PR #35366 only removed one use of the function. `pandas_compat.py` is still an issue.

(Link to the pandas issue: https://github.com/pandas-dev/pandas/issues/52899 where this is also being discussed.)

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
The `is_sparse` call in pandas_compat.py that you reference is actually a function that is defined in pyarrow itself:

https://github.com/apache/arrow/blob/1cc1f4c752895301371ee59d315ebffe74224c66/python/pyarrow/pandas-shim.pxi#L204-L208

and this is exactly the place that https://github.com/apache/arrow/pull/35366 has updated to no longer use pandas' `is_sparse` but `isinstance(.., pd.SparseDtype)` 

If you are still seeing this warning, I _assume_ you are using an older version of pyarrow (<12). Would that be the case?

**Comment by batterseapower** [comment]
Ah, I think you're right. Sorry for the noise!

(I saw that this `is_sparse` call hadn't been touched for 4 years and just assumed it had been missed, particularly given that the Pandas ticket is still open.)
