### ISSUE TITLE
Reading arrow files client-side

### ISSUE THREAD

**Issue by tdiprima** [apache/arrow#39114]
### Describe the usage question you have. Please include as many useful details as  possible.

When running the example in the `js` folder [read_file.html](https://github.com/apache/arrow/blob/main/js/examples/read_file.html), it says: `Arrow.Table.from is not a function`.  Please advise - what is the correct way to read an arrow file in a browser?

### Component(s)

JavaScript

**Comment by kylebarron** [comment]
You can use `tableFromIPC`

**Comment by tdiprima** [comment]
Hi Kyle,

I'm assuming you mean something like this...

```html
<script src="../targets/es2015/umd/Arrow.js"></script>
<script type="module">
import { tableFromIPC } from "apache-arrow";
const table = await tableFromIPC(fetch("hello_world.arrow"));
console.table([...table]);
</script>
```

But the console error says: The specifier “apache-arrow” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.

I'm guessing I'm either using the wrong JavaScript file, or the `import` is wrong.  Any ideas?

Thanks again.  I really appreciate your help.

**Comment by tdiprima** [comment]
Hi Kyle,

I used `tableFromIPC` instead of `Arrow.Table.from`, but it said, "tableFromIPC is not defined".  Am I supposed to import it as a module?  Any ideas?

Thanks again.  I really appreciate your help.

**Comment by kylebarron** [comment]
It's a top-level function: https://arrow.apache.org/docs/js/functions/Arrow_dom.tableFromIPC.html

**Comment by tdiprima** [comment]
You're right.  Thanks!
