### ISSUE TITLE
[Integration][Flight][Java] Flight Java server occasionally fails starting

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39113]
### Describe the bug, including details regarding any error messages, version, and platform.

We occasionally get an error starting the Flight Java server in Integration CI tests:
https://github.com/apache/arrow/actions/runs/7108228773/job/19351128300#step:8:21755

I don't know if the warning below is related:
```
################# FAILURES #################
FAILED TEST: decimal Java producing,  Java consuming
<class 'RuntimeError'>: Flight-Java server did not start properly, stdout:
Warning: [0.002s][warning][perf,memops] Cannot use file /tmp/hsperfdata_root/55221 because it is locked by another process (errno = 11)


stderr:


```

(also happens on [arrow-rs](https://github.com/apache/arrow-rs/actions/runs/7099107054/job/19322459447#step:10:14465) CI)

### Component(s)

FlightRPC, Integration, Java

**Comment by lidavidm** [comment]
You can just disable it: https://stackoverflow.com/questions/76327/how-can-i-prevent-java-from-creating-hsperfdata-files
