### ISSUE TITLE
[Python] pa.array doesn't check for byte-swapped list-arrays

### ISSUE THREAD

**Issue by hombit** [apache/arrow#39129]
### Describe the bug, including details regarding any error messages, version, and platform.

`pyarrow` doesn't support byte-swapped arrays, but it doesn't check it for list-arrays. So this code would fail with an assertion error, because the scalar equals 256 instead of 1:

```python
import numpy as np
import pyarrow as pa

# Big-endian byte order
np_a = np.array([1], dtype='>u2')
# Build a list array, supposed to be [[1]]
pa_a = pa.array([np_a])
scalar = pa_a[0][0]
# The scalar is 256 here, not 1
assert scalar.as_py() == 1, f'{scalar} != 1'
```

I believe that an expected behavior  is to fail with `ArrowNotImplementedError: Byte-swapped arrays not supported`, just like this code would do:

```python
import numpy as np
import pyarrow as pa

# Big-endian byte order
np_a = np.array([1], dtype='>u2')
pa_a = pa.array(np_a)
```

### Environment
- Linux 4.18.0 x86_64
- Python 3.9.13
- Pyarrow 14.0.1

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
@hombit thanks for the report! That indeed seems it should raise a similar error in the list case.

For the primitive array path, we have this check at

https://github.com/apache/arrow/blob/087fc8f5d31b377916711e98024048b76eae06e8/python/pyarrow/src/arrow/python/numpy_to_arrow.cc#L435-L439

And so for the ListConverter, we will need something similar here:

https://github.com/apache/arrow/blob/087fc8f5d31b377916711e98024048b76eae06e8/python/pyarrow/src/arrow/python/python_to_arrow.cc#L847-L852

**Comment by soumyadsanyal** [comment]
take

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 41549
https://github.com/apache/arrow/pull/41549
