### ISSUE TITLE
[R] arrow R package: support for stringr::str_replace_all() incomplete 

### ISSUE THREAD

**Issue by abfleishman** [apache/arrow#39191]
### Describe the bug, including details regarding any error messages, version, and platform.

The [arrow R package claims to support the `stringr::str_replace_all()` function](https://arrow.apache.org/docs/dev/r/reference/acero.html#stringr), however, it does not support using a vector of pattern/replacements as [the function says it should.](https://stringr.tidyverse.org/reference/str_replace.html)
```r
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(stringr)
dat<-data.frame(common_name=c("Cobalt-rumped Parrotlet", 
                              "Striped Woodcreeper", 
                              "Allard's Ground Cricket",
                              "Southern Double-collared Sunbird"))
dat_arrow<-arrow_table(dat)

# if working with a normal data.frame the following code works
dat_df<-dat %>% 
    mutate(common_name_clean = str_replace_all(common_name, c(" |-"="_", "'" = "")))

dat_df
#>                        common_name                common_name_clean
#> 1          Cobalt-rumped Parrotlet          Cobalt_rumped_Parrotlet
#> 2              Striped Woodcreeper              Striped_Woodcreeper
#> 3          Allard's Ground Cricket           Allards_Ground_Cricket
#> 4 Southern Double-collared Sunbird Southern_Double_collared_Sunbird

#but if working with an arrow data.frame it says I have to collect first
dat_arrow<-dat_arrow%>% 
    mutate(common_name_clean = str_replace_all(common_name, c(" |-"="_", "'" = "")))
#> Warning: Expression str_replace_all(common_name, c(` |-` = "_", `'` = "")) not
#> supported in Arrow; pulling data into R
Created on 2023-12-11 with reprex v2.0.2
```

### Component(s)

R

**Comment by thisisnic** [comment]
Thanks for reporting this @abfleishman!  Well-spotted; I think the problem here is that we can only support a single value and not a vector of values, so we should be checking the length of our inputs and providing an error if their lengths are >1. Are you interested in submitting a PR to fix this?

**Comment by abfleishman** [comment]
@thisisnic While this sounds simple, after a quick search of the code I am not sure where the error message would be added.  
Persumidly somewhere near [here](https://github.com/apache/arrow/blob/d2209582a0ef81c93342183cab3c12d69e79c5be/r/R/dplyr-funcs-string.R#L352C17-L352C17)? I am pretty unclear how these functions work.

The error message could look something like:

```r
if( length(pattern) !=1 || length(replacement) != 1){
    stop("Arrow does not support vectors of length > 1 for the pattern argument for `stringr::str_replace_all` ")
}
```

**Comment by thisisnic** [comment]
You got it, yeah!  

That `arrow_r_string_replace_function()` is a generic function which can be used for all of `sub/gsub/str_replace/str_replace_all`, so if you changed the error message to something more generic like `` `pattern` must be length 1 ``, then it'd cover multiple cases.

The codebase can be a bit tricky to work through manually, but what I usually do in cases like this is find similar unit tests, then write a unit test for the thing I want to change (in this case it would be attempting to pass in a vector with `replacement` having length > 1), and then just see if my change makes the new test pass without making other existing tests fail.  

If you open a PR, it'll be easier to walk you through any other changes on there :)
