### ISSUE TITLE
[C++][Python] Generating Parquet with Pandas

### ISSUE THREAD

**Issue by NKMatha** [apache/arrow#39205]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi team,

Am trying to save a csv to parquet using Pandas, but some times am facing issues like type conversations where a column is object but most the values are numeric. If one value in that column is alphanumeric then its causing issue like` ("Could not convert 'A5000' with type str: tried to convert to double", 'Conversion failed for column REFERENCE_KEY3 with type object')`.

But explicitly i defining individual column types before saving to parquet and REFERENCE_KEY3 is a object. Please help for this scenario.

**sample script:**
```
merged_df = merged_df.astype({col: typ_conv[oracle_type] for col, oracle_type in m.items()})
merged_df['REFERENCE_KEY3'].dtype   # dtype('O')
merged_df.to_parquet('sample.parquet', index=False)
```

**Info**:
Name: pandas
Version: 1.1.5
Name: pyarrow
Version: 6.0.1

### Component(s)

Parquet, Python

**Comment by mapleFU** [comment]
> but most the values are numeric

Seems in 'A5000', the type of input data is not the same? Parquet only store the data with same type in a Parquet file

**Comment by NKMatha** [comment]
Hi @mapleFU thanks for your quick response. So do you mean that column should have same data types?
But we're defining column type right, will it not consider it as string?

**Comment by mapleFU** [comment]
> But we're defining column type right, will it not consider it as string?

Hmmm I think it's defined as a "double" rather than string during writing to file, I'm not so familiar with pandas, would you mind provide a simplest reproduce way(maybe with some self-generated data?)

**Comment by NKMatha** [comment]
This is how my data look like
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/NANDAK~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/NANDAK~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Col1 | Col2 | Col3 | Col4
-- | -- | -- | --
1 | aed | 2019-05-10T08:31:41.000+00:00 |  
2 | wef | 2019-05-10T08:31:41.000+00:00 |  
3 | aed | 2019-05-10T08:31:41.000+00:00 |  
4 | wef | 2019-05-10T08:31:41.000+00:00 | 92
5 | aed | 2019-05-10T08:31:41.000+00:00 | 115
6 | wef | 2019-05-10T08:31:41.000+00:00 | 138
7 | aed | 2019-05-10T08:31:41.000+00:00 |  
8 | wef | 2019-05-10T08:31:41.000+00:00 | A184
9 | aed | 2019-05-10T08:31:41.000+00:00 | 207
10 | wef | 2019-05-10T08:31:41.000+00:00 | 230
11 | aed | 2019-05-10T08:31:41.000+00:00 |  
12 | wef | 2019-05-10T08:31:41.000+00:00 |  
13 | aed | 2019-05-10T08:31:41.000+00:00 | 299
14 | wef | 2019-05-10T08:31:41.000+00:00 | 322



</body>

</html>
so the REFERENCE_KEY3 column is like Col4, value at row 8 it's causing issue for me while saving as parquet and the column type is defined as object(string) in pandas.

**Comment by NKMatha** [comment]
Hey got resolved by changing pandas dtypes to String instead of Object and is working now.
Thanks @mapleFU for your quick response.
