### ISSUE TITLE
[Format][FlightRPC][Docs] Stabilize Flight SQL

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#39204]
### Describe the enhancement requested

See https://lists.apache.org/thread/qoshg8mln3t2ovr90o1yklz4yrpv503h

### Component(s)

FlightRPC, Format

**Comment by jbonofre** [comment]
I'm doing a pass, thanks !

**Comment by jduo** [comment]
Hi, I can start a PR for this.

**Comment by jbonofre** [comment]
I plan to start it next week.

**Comment by kou** [comment]
Issue resolved by pull request 41657
https://github.com/apache/arrow/pull/41657
