### ISSUE TITLE
[Release] Add retry mechanism in case of failure downloading RC binaries

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#39212]
### Describe the enhancement requested

While verifying the release 14.0.2 we have had some issues with artifactory resetting the connection due to SSL connection errors.
Even though I am not sure of the exact issue we could add a retry mechanism on the `download_rc_binaries.py` in case of OpenSSL connection errors as curl does not retry on those cases and it just fails.

After several retries of the jobs (6 and 3) it has successfully download all binaries:
https://github.com/ursacomputing/crossbow/actions/runs/7187567951/job/19594848965
https://github.com/ursacomputing/crossbow/actions/runs/7187567863

I opened an issue to INFRA to investigate if there's something going on with Artifactory: https://issues.apache.org/jira/browse/INFRA-25274 there are more details on the failures there.

### Component(s)

Release

**Comment by lidavidm** [comment]
Also see https://github.com/apache/arrow/issues/38442
