### ISSUE TITLE
[Python] Extend `RecordBatch.filter` to take an `Expression` in addition to a boolean mask `Array`

### ISSUE THREAD

**Issue by nph** [apache/arrow#39220]
### Describe the enhancement requested

Currently RecordBatches can only be filtered using a boolean mask `Array`, unlike Tables which can be filtered using either a mask or an `Expression`. It would be useful to allow `RecordBatch.filter` to also accept an `Expression` to make it consistent with `Table.filter`.

See also discussion [here](https://github.com/apache/arrow/issues/38770#issuecomment-1854247691)

### Component(s)

Python

**Comment by Fokko** [comment]
Looks like this is supported in Rust as well: https://arrow.apache.org/rust/arrow_select/filter/fn.filter_record_batch.html

**Comment by wjones127** [comment]
Issue resolved by pull request 43043
https://github.com/apache/arrow/pull/43043
