### ISSUE TITLE
[JS] Consider removing getByteLength

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#39259]
### Describe the enhancement requested

It's not clear to me why someone would want to get the byte length of an element. We also don't test this feature well so I'd rather remove it. 

### Component(s)

JavaScript

**Comment by bmschmidt** [comment]
Agreed this is an unusual feature. Curious if @trxcllnt knows the intent. I found one use of this searching github non-exhaustively, I think an old duckdb-wasm version. https://github.com/shaunstoltz/duckdb-wasm/blob/f37775b6a6525b51fce1115a7dc24601450ce768/packages/react-duckdb-table/src/simple_scan_provider.tsx#L157
