### ISSUE TITLE
[JS] TypeScript types don't work with Node ESM

### ISSUE THREAD

**Issue by andrew0** [apache/arrow#39289]
### Describe the bug, including details regarding any error messages, version, and platform.

The `apache-arrow` package has an `exports` field that points to an ESM build for Node.js imports, which works at runtime, but I get an error from TypeScript saying that it can't find the types for ESM projects:

<img width="590" alt="image" src="https://github.com/apache/arrow/assets/739172/564e69cb-c379-4a61-8f41-5bf0c1f42344">

https://stackblitz.com/edit/stackblitz-starters-7u3tyj?file=src%2Findex.ts

If I modify the `exports` field to this:

```
  "exports": {
    ".": {
      "node": {
        "types": "./Arrow.node.d.ts",
        "import": "./Arrow.node.mjs",
        "require": "./Arrow.node.js"
      },
      "types": "./Arrow.dom.d.ts",
      "import": "./Arrow.dom.mjs",
      "require": "./Arrow.dom.js"
    },
    "./*": {
      "import": "./*.mjs",
      "require": "./*.js"
    }
  }
```

then TypeScript is able to find the types correctly. I can also work around it by depending on `@apache-arrow/esnext-esm` directly.

### Component(s)

JavaScript

**Comment by ixxie** [comment]
Running into this as well.

**Comment by domoritz** [comment]
Can you try https://github.com/apache/arrow/pull/39475?
