### ISSUE TITLE
[C++][FS][Azure] Azure CLI authentation

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#39344]
### Describe the enhancement requested

Child of https://github.com/apache/arrow/issues/38598

Add support for Azure CLI auth. Should work on any system where you have run `az login`. 

https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/src/azure_cli_credential.cpp

### Component(s)

C++

**Comment by kou** [comment]
Can we close this?

**Comment by felipecrv** [comment]
> Can we close this?

What you think @Tom-Newton? Is there value in explicitly requesting CLI authentication instead of getting it from default behavior?

**Comment by Tom-Newton** [comment]
I wouldn't close it. Probably this provides quite a small benefit, but a benefit nonetheless and I think it's very easy for us to implement this. 

There have been lots of times I've wanted to use some tool, only to find Azure Auth options are lacking, so I'm keen to be comprehensive here.

**Comment by Tom-Newton** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 41976
https://github.com/apache/arrow/pull/41976
