### ISSUE TITLE
[C++][FS][Azure] Environment credential authentication

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#39345]
### Describe the enhancement requested

Child of https://github.com/apache/arrow/issues/38598

Environment credential is the same as [client secret](https://github.com/apache/arrow/issues/39343) except it extracts the important values from standard environment variables instead of just arguments in the code.  

https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/src/environment_credential.cpp

### Component(s)

C++

**Comment by felipecrv** [comment]
Note: even though there isn't a way to explicitly configure `AzureOptions` to get credentials from the environment, the `AzureOptions::ConfigureDefaultCredential()` will cause the Azure SDK to probe the environment for credentials and build the appropriate auth token.

**Comment by kou** [comment]
It means that we don't need to implement this feature because we already implemented the feature as `AzureOptions::ConfigureDefaultCredential()`, right?

**Comment by Tom-Newton** [comment]
I think really we should implement this. The default credential is often useful but it doesn't give you control in a case where you environment has Auth configured in more than one way.

**Comment by kou** [comment]
Issue resolved by pull request 41715
https://github.com/apache/arrow/pull/41715
