### ISSUE TITLE
[CI] MinGW MINGW32 C++ is failing due to missing uriparser

### ISSUE THREAD

**Issue by js8544** [apache/arrow#39359]
### Describe the bug, including details regarding any error messages, version, and platform.

E.g. https://github.com/apache/arrow/actions/runs/7306006597/job/19910237045
I think it's due to https://github.com/msys2/MINGW-packages/pull/19517. This PR seems to remove 32-bit builds for uriparser.

### Component(s)

Continuous Integration

**Comment by kou** [comment]
https://github.com/msys2/MINGW-packages/commit/f68162d5827fce41e7c2d4eb65cab6fcd8b9dd60
It seems that MSYS2 wants to drop support 32bit build. 
Let's remove the job from our CI.
