### ISSUE TITLE
[CI] Update upload-artifact and download-artifact versions to v4

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#39350]
### Describe the enhancement requested

Dependabot opened this PR: https://github.com/apache/arrow/pull/39284#event-11279329073

We have to update also the upload-artifact action to v4.

We should try to update all of them and be consistent.

### Component(s)

Continuous Integration

**Comment by kou** [comment]
`.github/workflows/` are done by #43952.

We need to do the same thing for `dev/tasks/`.

**Comment by kou** [comment]
Done by #44086.
