### ISSUE TITLE
[C++] How to ensure the usage of SIMD acceleration?

### ISSUE THREAD

**Issue by RemHero** [apache/arrow#39365]
### How to correctly use SIMD optimization in Arrow for better expression computation?

I read the user docs, and use the API in the "compute function" and have implemented an expression `(u1.d1.s1*u1.d2.s4+u1.d2.s4/u1.d1.s1)/u1.d1.s1*u1.d2.s4`. I found that using Arrow didn't make it faster. I made sure that `arrow::GetRuntimeInfo().detected_simd_level = AVX2`, and also modified the environment variable `ARROW_SIMD_LEVEL` and other parameters to `AVX2`. I wrote the same row-based expression that had much faster computation speed than using Arrow. I don't know how to correctly use Arrow's computation interface. 
Here is my code.
```c
// size of  columnInt  and columnDouble  is 10485760
    std::shared_ptr<arrow::Array> columnInt = record_batch->column(1);
    std::shared_ptr<arrow::Array> columnDouble = record_batch->column(3);
    arrow::Datum multiply_datum, divide_datum, add_datum, divide_datum1, multiply_datum1;

    ARROW_ASSIGN_OR_RAISE(multiply_datum,
                          arrow::compute::Multiply(columnInt, columnDouble));
    ARROW_ASSIGN_OR_RAISE(divide_datum,
                          arrow::compute::Divide(columnDouble, columnInt));
    ARROW_ASSIGN_OR_RAISE(add_datum,
                          arrow::compute::Add(multiply_datum, divide_datum));
    ARROW_ASSIGN_OR_RAISE(divide_datum1,
                          arrow::compute::Divide(add_datum, columnInt));
    ARROW_ASSIGN_OR_RAISE(multiply_datum1,
                          arrow::compute::Multiply(divide_datum1, columnDouble));
```
I'm confident that the compiler is using AVX2 and SSE instruction sets. I examined the assembly code of my own row-based expression logic and found instructions such as `vmovdqa` and `vaddsd`.
**I would like to know how to correctly use Arrow for expression computation to improve its execution efficiency？If there are any relevant reference documents available？**
Thank you very much! 
Merry Christmas!

### Component(s)

C++

**Comment by RemHero** [comment]
I also modified the environment variable `ARROW_SIMD_LEVEL `and other parameters to `AVX2`.

**Comment by mapleFU** [comment]
Have you enabling this: https://arrow.apache.org/docs/cpp/env_vars.html#envvar-ARROW_USER_SIMD_LEVEL ?

**Comment by RemHero** [comment]
Thank you very much for your suggestions! I conducted some further experiments based on your advice and found that the `batchSize` has a significant impact on the computation of expressions. 

Additionally, I implemented the computation using `arrow::compute::Expression`. However, the performance still falls short compared to the row-based implementation. Regarding the 'memory-boundary' you mentioned, I understand that my calculation process involves a lot of memory allocation and copying due to storing intermediate results. To address this, I tested only a multiplication operation, eliminating unnecessary intermediate result copies, and the results showed that the performance difference between the two approaches was not significant. 

Base on this, I'm not certain whether the arrow-based Function computation utilizes SIMD optimization? It might require further investigation through disassembly. Going forward, I plan to continue experimenting with the `Array-wise ('vector') functions `mentioned in the official documentation and follow your advice to hand-code the computation expressions above arrow-columanr. 

I have referred to the documentation you provided, and I may also try setting the appropriate SIMD optimization level during compilation.
There might be a result within the next couple of days. @mapleFU

**Comment by mapleFU** [comment]
Yeah, batchSize would be help, usally we hope batches can be staying in L1 cache. And larger batch size can have smaller cost.

If the computation is complex and has many operators (like group by. ... etc), writing a self generated call is complex, but workload like `(u1.d1.s1*u1.d2.s4+u1.d2.s4/u1.d1.s1)/u1.d1.s1*u1.d2.s4` might benifits from less memory allocation and fast computation, so it depend on your workload

**Comment by RemHero** [comment]
I forgot to close this issue, thank you very much for your advice. At present, arrow is used as the structure of column-oriented storage in my project, and simd is used to improve the calculation efficiency of related operators. @mapleFU
