### ISSUE TITLE
[C++] Thirdparty: Bump zlib to 1.3

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#39390]
### Describe the enhancement requested

zlib 1.3 is released, which containing some bugfix: https://github.com/madler/zlib/releases/tag/v1.3

We're currently default using zlib 1.2.13, so maybe we can bump it

### Component(s)

C++

**Comment by pitrou** [comment]
Thanks for doing this @mapleFU . Generally we should try to upgrade third-party versions before a release (perhaps also in vcpkg? @kou @assignUser ). Besides general improvements, there may also be important bug fixes or even security fixes.
