### ISSUE TITLE
[GLib] Broken Link in README Content

### ISSUE THREAD

**Issue by llama90** [apache/arrow#39416]
### Describe the bug, including details regarding any error messages, version, and platform.

I've noticed that there is a broken link in the README.

https://github.com/apache/arrow/blob/4543f5d8394e221681c362f4e7c8a7268823b2cd/c_glib/README.md?plain=1#L104

<img width="779" alt="image" src="https://github.com/apache/arrow/assets/6668548/daba534f-c7e7-4c68-841a-31879f5a5c18">

I believe this is a MINOR issue, so I searched for the appropriate link to replace the broken one. However, I'm not sure which link is the most suitable, so I'm raising this as an issue.

* https://www.gtk.org/docs/
* https://docs.gtk.org/
* something else?

### Component(s)

Documentation

**Comment by kou** [comment]
Good catch!
We should use https://gitlab.gnome.org/GNOME/gtk-doc .

BTW, we should migrate our documentation tool to gi-docgen https://gitlab.gnome.org/GNOME/gi-docgen .

**Comment by kou** [comment]
@Divyansh200102 Could you write a "take" only comment here to assign this issue to you?

**Comment by Divyansh200102** [comment]
take
