### ISSUE TITLE
[CI][R] test-r-rhub-debian-gcc-devel-lto-latest fails not being able to install Arrow

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#39424]
### Describe the bug, including details regarding any error messages, version, and platform.

The following job:
* [test-r-rhub-debian-gcc-devel-lto-latest](https://github.com/ursacomputing/crossbow/runs/20079233322)

is currently failing on the nightlies with:

```
* checking whether package ‘arrow’ can be installed ... [279s/266s] ERROR
Installation failed.
See ‘/arrow/r/check/arrow.Rcheck/00install.out’ for details.
```

### Component(s)

Continuous Integration, R

**Comment by assignUser** [comment]
Ah sorry I missed this: #39523
