### ISSUE TITLE
[C++][FS] Use default Azure credentials implicitly and support anonymous credentials explictly

### ISSUE THREAD

**Issue by felipecrv** [apache/arrow#39449]
### Describe the enhancement requested

As the next release is coming with a lot of the Azure FS implemented, I would like to propose a change to how `AzureOptions` works:

 - Use default credentials without any explicit `AzureOptions::Configure-` call
 - Support anonymous credentials (can only access public containers) instead of returning an error (but require an explicit call to `ConfigureAnonymousCredential()`.

### Component(s)

C++

**Comment by Tom-Newton** [comment]
I was going to make this ticket by I forgot. Thanks :+1:
