### ISSUE TITLE
[JS] make @swc/helpers dev dependency or make ts-node a dependency

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#39476]
### Describe the enhancement requested

@swc/helpers is only used with ts-node so it should be the same I think.

This was introduced in https://github.com/apache/arrow/pull/38500. 

### Component(s)

JavaScript

**Comment by domoritz** [comment]
@trxcllnt thoughts?

**Comment by trxcllnt** [comment]
The [`ts-node` docs about swc](https://www.npmjs.com/package/ts-node#swc-1) says we need it if we're using `"importHelpers": true` in our tsconfig:
> SWC uses @swc/helpers instead of tslib. If you have enabled importHelpers, you must also install @swc/helpers.
