### ISSUE TITLE
Roadmap of Arrow.

### ISSUE THREAD

**Issue by daadaada** [apache/arrow#3947]
Hi all,

Where can I find the roadmap of the Arrow project?

I may contribute to this project but I don't want to re-implement components you are working on, and I don't want to go in the wrong direction. 

Specifically, do you have the plan to support groupby, join etc. in the future?  Maybe I can help I guess.

**Comment by wesm** [comment]
Hi @daadaada let's discuss on the mailing list dev@arrow.apache.org?

We do intend to implement an in-memory query engine. There is already DataFusion for Rust and we will be doing such work in C++ (for Python, R, etc. also). For example: I have written a document indicating some of the development areas that I and my team intend to work on in the project:

https://docs.google.com/document/d/12dWBniKW2JQ-5djE3SPjyQXVquCAEmLXVlb1dnhLhQ0/edit
