### ISSUE TITLE
[C++][Parquet]: Page sizes are not always validated before truncating to int32

### ISSUE THREAD

**Issue by emkornfield** [apache/arrow#39527]
### Describe the bug, including details regarding any error messages, version, and platform.

This can lead to writing corrupt data if the pages passed in are too large (for instance LargeString arrow columns that get sliced but still exceed 2GB).

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
Just ask is this problem happens during read or write?

**Comment by emkornfield** [comment]
I don't have an end-to-end repro as it requires very large data if I traced the code, but I believe the current code can silently write corrupt files if the uncompressed or compressed size for a page exceed 2GB.  I think reading such files should trigger exceptions.
