### ISSUE TITLE
[Python] Compatibility with NumPy 2.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#39532]
NumPy 2.0 is coming soon, and we should ensure pyarrow is fully compatible to ensure a smooth transition of our users. Overview issue on numpy's side: https://github.com/numpy/numpy/issues/24300

We already test with nightly numpy (eg https://github.com/ursacomputing/crossbow/actions/runs/7454906275/job/20283098411), and currently this build is working fine.  
There is one warning about the usage of `numpy.core.numerictypes` that we should still solve.

Further, we need to check if we are all OK on the packaging side: do we need to pin numpy<2 for now in our upcoming release? What do we need to update in our wheel building? (stop using oldest-supported-numpy?)

- [x] #39533
- [x] #39537
- [x] #39555
  - [x] Ensure we can build pyarrow against numpy 2.0 nightly (update pyproject.toml to allow this), and test this by building our nightly wheels with numpy nightly
  - [x] https://github.com/apache/arrow/issues/39536
  - [x] #39848
- [x] #41098
- [x] https://github.com/apache/arrow/issues/40376

cc @raulcd

**Comment by jorisvandenbossche** [comment]
Some other observations / relevant bits from the linked issues:

* Since numpy 1.25, we don't need `oldest-supported-numpy` anymore (https://numpy.org/devdocs/release/1.25.0-notes.html#compiling-against-the-numpy-c-api-is-now-backwards-compatible-by-default and https://github.com/scipy/oldest-supported-numpy#deprecation-notice-for-numpy-20), so for newer Python versions (where the minimum supported version of numpy is <=1.25), we can start compiling with the latest numpy

* At the moment, pip install pyarrow in an environment with numpy 2.0, the import of pyarrow fails. So at a minimum, we should add a `numpy<2.0` pin in the release branch

* If we want wheels that support both numpy 1.x and 2.0 at runtime, we need to build our wheels with numpy 2.0 (https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice). The recommendation is to start doing that (and then a numpy<2.0 pin in the released version is no longer needed) once numpy 2.0rc1 is out. This is targeted for around 1 Feb 2024, but other projects already started building their wheels with numpy 2.0.dev, as far as I understand (eg https://github.com/scikit-learn/scikit-learn/pull/27735, or that is only for the nightly wheels?)

**Comment by raulcd** [comment]
@jorisvandenbossche is there something else to do on this one or are we ready for the release on this?

**Comment by jorisvandenbossche** [comment]
I think all sub-tasks are done, and this can be closed now
