### ISSUE TITLE
[C++] How to specific external jemalloc?

### ISSUE THREAD

**Issue by zclllyybb** [apache/arrow#39544]
### Describe the usage question you have. Please include as many useful details as  possible.

I want to use my specific jemalloc lib to build arrow. What should I do besides change `Djemalloc_SOURCE=BUNDLED` to `Djemalloc_SOURCE=SYSTEM`? how to specific the lib's path?

### Component(s)

C++

**Comment by kou** [comment]
`Djemalloc_ROOT=/opt/jemalloc` will work.

**Comment by zclllyybb** [comment]
> `Djemalloc_ROOT=/opt/jemalloc` will work.

yes it works. thank you
