### ISSUE TITLE
[Java] splitAndTransfer on empty ListVector should not throw IOB

### ISSUE THREAD

**Issue by FiV0** [apache/arrow#39554]
The following throws with `java.lang.IndexOutOfBoundsException: index: 0, length: 4 (expected: range(0, 0))`
```java
package org.apache.arrow.vector;

import org.apache.arrow.memory.RootAllocator;
import org.apache.arrow.vector.complex.ListVector;
import org.apache.arrow.vector.util.TransferPair;
import org.junit.jupiter.api.Test;

import static org.junit.Assert.assertEquals;


public class ListVectorIOBTest {

    @Test
    void shouldNotThrow()  {
        RootAllocator allocator = new RootAllocator();
        ListVector listVector = ListVector.empty("foo", allocator);

        TransferPair transferPair = listVector.getTransferPair(allocator);
        transferPair.splitAndTransfer(0,0);
        assertEquals(null, transferPair.getTo());

    }

}
```
Tested against the `14.0.2`  tag.

I think the test condition here https://github.com/apache/arrow/blob/e7ab540ed9901d19ebde81f43e8417562ef8a334/java/memory/memory-core/src/main/java/org/apache/arrow/memory/ArrowBuf.java#L316 is not correct for `index = 0` and `capacity = 0`.

### Component(s)

Java

**Comment by jarohen** [comment]
@FiV0 this might be a dupe of #30866?

**Comment by FiV0** [comment]
@jarohen yes true.
