### ISSUE TITLE
[Docs][R] Mention installing from r-universe binaries in readme

### ISSUE THREAD

**Issue by jeroen** [apache/arrow#39638]
### Describe the enhancement requested

As discussed with @thisisnic:

We could mention somewhere in the README or docs that precompiled binaries of the dev version of the R package can be installed directly from r-universe:

```r
install.packages('arrow', repos = c('https://apache.r-universe.dev', 'https://cloud.r-project.org'))
```

The arrow R package on https://apache.r-universe.dev/arrow is updated approximately every hour from the git main. Binaries of the R package are built for macos (x86_64+arm64), windows, and ubuntu:latest. So users on MacOS or Windows can test a nightly build of the R package without to setup the development environment, and build things from source.

### Component(s)

R

**Comment by thisisnic** [comment]
Issue resolved by pull request 44033
https://github.com/apache/arrow/pull/44033
