### ISSUE TITLE
[C++][Gandiva] Benchmarks should present a items/s or bytes/s metric

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39669]
### Describe the enhancement requested

We should scan through these benchmarks and look for those that only a present an iteration time.

### Component(s)

Benchmarking, C++, C++ - Gandiva

**Comment by pitrou** [comment]
cc @js8544

**Comment by js8544** [comment]
Will take a look!

**Comment by kou** [comment]
Issue resolved by pull request 40435
https://github.com/apache/arrow/pull/40435

**Comment by llama90** [comment]
take
