### ISSUE TITLE
[C++][Parquet] Benchmarks should present a items/s or bytes/s metric

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39668]
### Describe the enhancement requested

We should scan through these benchmarks and look for those that only a present an iteration time.

### Component(s)

Benchmarking, C++, Parquet

**Comment by pitrou** [comment]
cc @mapleFU

**Comment by mapleFU** [comment]
take

**Comment by mapleFU** [comment]
Parquet has benchmarks below:

```
parquet-bloom-filter-benchmark
parquet-arrow-reader-writer-benchmark
parquet-column-reader-benchmark
parquet-page-index-benchmark
parquet-level-conversion-benchmark
parquet-encoding-benchmark
parquet-column-io-benchmark
```

Seems all benchmark has at least one of items/s or bytes/s metric

**Comment by pitrou** [comment]
Thanks for going over this. If it's desirable to add more benchmark metadata still, feel free to post a PR, otherwise this issue should be closed.

**Comment by mapleFU** [comment]
Let me first close this
