### ISSUE TITLE
[Swift] Date32 & Date64 failing to create in Arrow Reader

### ISSUE THREAD

**Issue by lukedg97** [apache/arrow#39709]
### Describe the bug, including details regarding any error messages, version, and platform.

Attempting to send Date32 columns over ArrowFlight to swift. 

At
https://github.com/apache/arrow/blob/55afcf0450aa2b611e78335bdbfd77e55ae3bc9f/swift/Arrow/Sources/Arrow/ArrowReaderHelper.swift#L67
and 
https://github.com/apache/arrow/blob/55afcf0450aa2b611e78335bdbfd77e55ae3bc9f/swift/Arrow/Sources/Arrow/ArrowReaderHelper.swift#L72

the objects are being initialized with `ArrowType.ArrowString` when they should be `ArrowType.ArrowDate32` and `ArrowType.ArrowDate64`

Also, its seems that in most other arrow places the primary date dataType is Timestamp and I was wondering if that might be implemented in arrow for swift soon?

### Component(s)

Swift

**Comment by abandy** [comment]
@lukedg97 I think this issue was resolved with PR: https://github.com/apache/arrow/pull/39721 and can be closed.  Please let me know if you think this is still an issue.
