### ISSUE TITLE
[Java] Enable code review and formatting code through Spotless Maven plugin

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#39712]
### Describe the enhancement requested

As Java code increases, it will become increasingly important to implement code formatter best practices. As a result, we will be able to use [spotless](https://github.com/diffplug/spotless) to:

- Reviewing code: Spotless can be used to identify issues related to format.
- Formatting code: Spotless can be used to automatically fix common formatting mistakes, such as spaces, newlines, and unnecessary imports.

This enhancement will propose replacing `maven-checkstyle-plugin` with `spotless-maven-plugin`, which is currently used by Java.

### Component(s)

Java

**Comment by lidavidm** [comment]
What format does Spotless use? google-java-format has the advantage of IDE plugins that help with formatting, too

**Comment by davisusanibar** [comment]
> What format does Spotless use? google-java-format has the advantage of IDE plugins that help with formatting, too

We are starting using `google-java-format` as you could see at https://github.com/davisusanibar/arrow/blob/97e68f5e66d890c34dde89d0727fbc294a82b869/java/pom.xml#L693. Also `palantir-java-format` is also [available](https://github.com/diffplug/spotless/tree/main/plugin-maven#eclipse-jdt:~:text=Java%20(google%2Djava%2Dformat%2C%20eclipse%20jdt%2C%20prettier%2C%20palantir%2Djava%2Dformat%2C%20formatAnnotations%2C%20cleanthat)).

**Comment by vibhatha** [comment]
Closing in favor of the structured issue: https://github.com/apache/arrow/issues/40757
