### ISSUE TITLE
[Python] PyArrow throws ArrowTypeError constructing array with explicit Interval object/type

### ISSUE THREAD

**Issue by WillAyd** [apache/arrow#39728]
### Describe the bug, including details regarding any error messages, version, and platform.

```
>>> import pyarrow as pa
>>> pa.array(pa.MonthDayNano((1, 15, 30)), type=pa.month_day_nano_interval())  # fails
*** pyarrow.lib.ArrowTypeError: No temporal attributes found on object.
>>> pa.array(pa.MonthDayNano((1, 15, 30)))
<pyarrow.lib.Int64Array object at 0x7865e9bd14e0>
[
  1,
  15,
  30
]
```

At least on pyarrow 14.0.1

### Component(s)

Python

**Comment by AlenkaF** [comment]
I suggest you use square brackets like so:

```python
>>> pa.array([pa.MonthDayNano((1, 15, 30))])
<pyarrow.lib.MonthDayNanoIntervalArray object at 0x124d84f40>
[
  1M15d30ns
]
>>> pa.array([pa.MonthDayNano((1, 15, 30))], type=pa.month_day_nano_interval())
<pyarrow.lib.MonthDayNanoIntervalArray object at 0x124d850c0>
[
  1M15d30ns
]
```

**Comment by WillAyd** [comment]
Ah that makes sense. Thanks a ton @AlenkaF  - let's chalk this one up to user error

**Comment by jorisvandenbossche** [comment]
FWIW, passing a _scalar_ value also doesn't work for other types, for example:

```
In [21]: pa.array(1, pa.int64())
...
TypeError: 'int' object is not iterable

```

The only reason it passed silently here is because the `pa.MonthDayNano` is a namedtuple, and thus considered as an iterable .. (we could provide better error messages, though)

**Comment by AlenkaF** [comment]
Agree with better error message!
