### ISSUE TITLE
[Go] Is there no way to serialize schema and data separately in the implementation of arrow go?

### ISSUE THREAD

**Issue by chenyuanxing** [apache/arrow#39730]
When we use java or c++, we can easily serialize schema and data separately with ipc method, the code example is as follows:
`auto schema_res = arrow::ipc::SerializeSchema(*schema, pool);`
`auto buffer_res = arrow::ipc::SerializeRecordBatch(*record, write_options);`

But in go we don't find a way to serialize schema and data separately. 

We need to serialize schema and data separately as per other languages, is there any way to do that?

### Component(s)

Go

**Comment by mapleFU** [comment]
Do you mean: https://github.com/apache/arrow/blob/main/go/arrow/flight/record_batch_writer.go#L107 ?

**Comment by chenyuanxing** [comment]
but only SerializeSchema was found in the flight, no SerializeRecordBatch ... (by the way. We were looking in the IPC packet before, so we didn't find it. 😂)

**Comment by mapleFU** [comment]
( I think they're same...)

**Comment by chenyuanxing** [comment]
Do you mean both are using the SerializeSchema method, just mem param one puts in null and one puts in actual data?

**Comment by mapleFU** [comment]
Emm I think they're both uses ipc module, however `SerializeSchema/DeserializeSchema` wraps the underlying logic

**Comment by chenyuanxing** [comment]
that is right . it use the ipc module to implement the logic. but we didnot know how to just serialize RecordBatch data like the interface (SerializeRecordBatch) existed in java and c++ .

**Comment by mapleFU** [comment]
🤔arrow-ipc rely on serialization RecordBatch, so there must be something usable, but actually I'm not familiar with it's interface, maybe there is existing method, or maybe we need to make some interface public

**Comment by zeroshade** [comment]
Hey all, @mapleFU is correct in that currently there is only the `SerializeSchema` / `DeserializeSchema` methods in the Go impl, and there isn't a function that *just* creates the RecordBatch IPC message currently in Go. 

@chenyuanxing What's the use case you're operating with that you need that currently? It honestly shouldn't be difficult to create though.

**Comment by chenyuanxing** [comment]
We need to transfer Arrow objects between systems, we have been using java and c++ systems, so the format has always been schema IPC message + recordBatch IPC message, now we have a go system, and we find that we can't pass Arrow objects in the same format (separate format for schema and data)

**Comment by zeroshade** [comment]
If you use the IPC writer, that's what it does. It writes the schema IPC message first and then record batch IPC messages. You could use a `bytes.Buffer` as the sink to write to and that'll give you the schema IPC message + recordBatch IPC message one after the other.

In theory you shouldn't necessarily need an explicit function to write the record batch message. But it also shouldn't be difficult to add either. Do you wanna take a stab at it?

**Comment by chenyuanxing** [comment]
Ok, got it, we'll try to  Bypassing this the logic in other ways .  Thanks for your replies.

**Comment by zeroshade** [comment]
@chenyuanxing If your application structure still requires manual and separate serialization of the record batch and schema, it's likely a pretty trivial change to add functions for it. So just let us know.

**Comment by chenyuanxing** [comment]
okay.  thx very much .

**Comment by rekby** [comment]
> @chenyuanxing If your application structure still requires manual and separate serialization of the record batch and schema, it's likely a pretty trivial change to add functions for it. So just let us know.

It needs the function for use Bulk Upsert into YDB from go sdk. Alternative: manual cut end of stream marker, then cur scheme from serialized data. Or extend server api https://github.com/ydb-platform/ydb/issues/11790

It is difficult to find and understand the way.

Can you add the function for serialize data withou schema or I will create the PR?

**Comment by zeroshade** [comment]
@rekby If you have something working already, then go ahead and create the PR on the apache/arrow-go repository and I'll happily review. Otherwise, I'll put something together and get a PR up later this week.
