### ISSUE TITLE
[Java] Bump org.codehaus.mojo:exec-maven-plugin from 1.6.0 to 3.1.1

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#39734]
### Describe the enhancement requested

There is an existing effort from a dependabot PR to upgrade the maven version https://github.com/apache/arrow/pull/39202, but this requires more work to do that upgrade. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 39696
https://github.com/apache/arrow/pull/39696
