### ISSUE TITLE
[Java] Remove Static imports for Utf8 Usage

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#39752]
### Describe the enhancement requested

With the errorprone warning fixes, a decision was made to minimize the static imports. And a few more classes which does the UTF8 import in static mode was found in `FlightSqlExample`, `JsonFileReader` `ArrowFlightJdbcVarCharVectorAccessor`. 
It would be good to fix these. 

### Component(s)

Java

**Comment by vibhatha** [comment]
I will continue to work on these improvements following up reviews in https://github.com/apache/arrow/pull/39529

**Comment by vibhatha** [comment]
> I will continue to work on these improvements following up reviews in #39529

I have missed this unfortunately. Creating a smaller PR to fix this.

**Comment by lidavidm** [comment]
Issue resolved by pull request 40683
https://github.com/apache/arrow/pull/40683
