### ISSUE TITLE
[Python] Expose force_virtual_addressing in PyArrow

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39779]
### Describe the enhancement requested

In #36827 we added the `force_virtual_addressing` option to the S3 implementation in Arrow C++. It should now be exposed to Python users.

### Component(s)

Python

**Comment by pitrou** [comment]
cc @AlenkaF @jorisvandenbossche

**Comment by yo1956** [comment]
@pitrou 
I'm interested in working on this issue. Would that be okay?
It seems that making changes to _s3fs.pyx would be the way to go.

**Comment by yo1956** [comment]
@pitrou 
I've created a PR. If you find any mistakes or anything missing, please let me know. Thank you.
