### ISSUE TITLE
Python: Check for `max_chunksize > 0` in `Table.to_batches()`

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow#39788]
### Describe the bug, including details regarding any error messages, version, and platform.

`Table.to_batches` should check for `max_chunksize > 0` and raise an exception if not true. This is hard to debug because it creates an infinite loop where Jupyter just hangs.

```py
import pyarrow as pa
table = pa.table({'a': [1, 2, 3, 4]})
table.to_batches(max_chunksize=0)
# hangs forever
```

It also led to OOM.
<img width="614" alt="image" src="https://github.com/apache/arrow/assets/15164633/cb971403-b020-4927-b227-3bdce0770304">

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Good catch! Did a quick fix in https://github.com/apache/arrow/pull/39796
