### ISSUE TITLE
[C++][GPU] Add C Device Data Interface tests with CUDA

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39786]
### Describe the enhancement requested

CUDA-enabled builds should test exporting and importing GPU-backed arrays.

### Component(s)

C++, GPU

**Comment by pitrou** [comment]
cc @zeroshade

**Comment by jorisvandenbossche** [comment]
I only added a test for export/import of an Array, and not for RecordBatch. Of course those share most of the implementation, but so the tests could certainly still be expanded.
