### ISSUE TITLE
[C++] ExportDeviceArray for C device interface uses CPU memory address for buffers

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#39782]
The Array exporter currently uses `buffer->data()`, which is documented as "The buffer has to be a CPU buffer (`is_cpu()` is true). Otherwise, an assertion may be thrown or a null pointer may be returned.". 
In practice, we indeed return null for non-CPU data. There is only a debug check that asserts the device.

**Comment by zeroshade** [comment]
The proper fix would be to switch to `buffer->address()` should be hopefully trivial
