### ISSUE TITLE
[C++] Optimize Take and Filter on fixed-size list of primitives

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39798]
### Describe the enhancement requested

Currently, calling the Take and Filter functions on a fixed-size list of primitive types will use the following algorithm:
1. generate an array of child indices into the values array (for example, taking indices [1, 2] on a `fixed_size_list<T, 3>` array will generate child indices [3, 4, 5, 6, 7, 8])
2. call Take on the values array and the child indices

But, when the fixed-size list's value type is a fixed-width primitive type such as numbers or even fixed-size binary (example : a fixed-shape tensor), then we could simply Take or Filter directly on the values array, using the appropriate byte width. For example, filtering a `fixed_size_list<int32, 3>` can use the same algorithm as filtering a `fixed_size_binary<12>`. This should be much faster.

### Component(s)

C++

**Comment by pitrou** [comment]
cc @felipecrv @js8544 @rok

**Comment by rok** [comment]
That seems like a worth-while optimization. Can we reuse fixed-size binary codepath?

**Comment by pitrou** [comment]
Yes, that would be the idea. (related: https://github.com/apache/arrow/pull/39795)

**Comment by felipecrv** [comment]
A generic "gather" primitive could take the base indices and length of each contiguous run and then dispatch (based on template-params) the appropriate buffer writes for the type.

**Comment by pitrou** [comment]
> A generic "gather" primitive could take the base indices and length of each contiguous run and then dispatch (based on template-params) the appropriate buffer writes for the type.

That's a separate avenue, though.

**Comment by felipecrv** [comment]
I got this working locally for `Take`

**Comment by felipecrv** [comment]
A change to `FizedSizeListBuilder` that makes it more likely that the optmization proposed here is possible in more cases and simpler and more effective -> https://github.com/apache/arrow/pull/41189

**Comment by felipecrv** [comment]
Issue resolved by pull request 41297
https://github.com/apache/arrow/pull/41297

**Comment by felipecrv** [comment]
My PR wasn't a full fix for this issue, but it introduced `util/fixed_width_internal.h/cc` with the functions that help checking, pre-allocating, and writing to these generalized fixed-width types. I have more PRs coming improving Take and created #41510 which is about bringing all these improvements to `Filter`.
