### ISSUE TITLE
[Python] numpy-1.19.3 was collected despite numpy-1.26.3 being installed and in site packages 

### ISSUE THREAD

**Issue by tol-va** [apache/arrow#39821]
### Describe the usage question you have. Please include as many useful details as  possible.

I am installing/building PyArrow in Cygwin to satisfy a future requirement for Pandas 3.0. 

PyArrow version 15.0.0 installation documentation states any version of NumPy 1.16.6 or higher should satisfy the requirement. 

Why is an older version of NumPy being collected and built as a dependency of PyArrow?
```
 pip3 install pyarrow --dry-run --verbose
Using pip 23.3.2 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Collecting pyarrow
  Using cached pyarrow-15.0.0.tar.gz (1.1 MB)
  Running command pip subprocess to install build dependencies
  Collecting cython>=0.29.31
    Using cached Cython-3.0.8-py2.py3-none-any.whl.metadata (3.2 kB)
  Collecting oldest-supported-numpy>=0.14
    Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl.metadata (9.8 kB)
  Collecting setuptools_scm<8.0.0
    Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
  Collecting setuptools>=40.1.0
    Using cached setuptools-69.0.3-py3-none-any.whl.metadata (6.3 kB)
  Collecting wheel
    Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
  Collecting numpy==1.19.3 (from oldest-supported-numpy>=0.14)
    Using cached numpy-1.19.3.zip (7.3 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting packaging>=20.0 (from setuptools_scm<8.0.0)
    Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
  Collecting typing-extensions (from setuptools_scm<8.0.0)
    Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
  Collecting tomli>=1.0.0 (from setuptools_scm<8.0.0)
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Using cached Cython-3.0.8-py2.py3-none-any.whl (1.2 MB)
  Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl (4.9 kB)
  Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
  Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
  Building wheels for collected packages: numpy
    Building wheel for numpy (pyproject.toml): started
```

### Component(s)

Python

**Comment by AlenkaF** [comment]
If I am seeing correctly NumPy version `1.19.3` is being collected? That is in line with the documentation you have mentioned

> Required dependency
> - NumPy 1.16.6 or higher.

https://arrow.apache.org/docs/python/install.html#dependencies

**Comment by jorisvandenbossche** [comment]
> Why is an older version of NumPy being collected and built as a dependency of PyArrow?

This version of numpy is only collected for the isolated build environment (and so is not necessarily the version of numpy that will be installed in the actual user environment you are installing pyarrow in). You can see in the logs above that this numpy is collected because `oldest-supported-numpy`. That is the pyarrow build dependency, and ensures that we _build_ against an older version of numpy, such that it is compatible at runtime with any newer version of numpy (the numpy C ABI works that way).

(now, sidenote, starting with the next release of pyarrow, we will actually start building with the latest version of numpy, see https://github.com/apache/arrow/pull/39557)

**Comment by jorisvandenbossche** [comment]
Closing this issue, as I don't think there is anything actionable left (see my previous comment explaining why the observed behaviour is expected)
