### ISSUE TITLE
[Python][Packaging] Remove nightly numpy wheels from the wheel build requirements

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#39848]
https://github.com/apache/arrow/pull/39557 updated the wheel building scripts to install numpy nightly wheels (to have wheels compatible at runtime with numpy nightly). Once there is a stable numpy 2.0 release out (and at the latest before doing the 16.0 release), we should remove that again to ensure we don't build our release wheels with an unstable numpy version.

**Comment by rgommers** [comment]
This can be done now I believe, the `numpy>=1.25; python_version>='3.9'` requirement can be changed to `numpy>=2.0.0rc1; python_version>='3.9'`

**Comment by raulcd** [comment]
@jorisvandenbossche should this be done for 16.0.0?

**Comment by jorisvandenbossche** [comment]
Yes (although I assume that in practice we won't have problems because of building with nightly _generally_, but that's not a stable thing, so numpy can always accidentally have a bad nightly at some point)

I started working on this yesterday (together with the last item of the numpy 2.0 compat list in https://github.com/apache/arrow/issues/39532), was mostly offline last week.

**Comment by jorisvandenbossche** [comment]
Opened a PR at https://github.com/apache/arrow/pull/41097

**Comment by raulcd** [comment]
Issue resolved by pull request 41097
https://github.com/apache/arrow/pull/41097
