### ISSUE TITLE
[C++] Add functionality to MemoryManager for copying a slice of a buffer

### ISSUE THREAD

**Issue by zeroshade** [apache/arrow#39858]
### Describe the enhancement requested

Currently `MemoryManager` objects define functionality to Copy or View entire buffers. Occasionally there is the need to only copy a single value or slice from a buffer (see https://github.com/apache/arrow/pull/39770#discussion_r1470135438). It's overkill to do a bunch of whole `Buffer` operations and manually slicing just to copy 4 or 8 bytes.

Instead we can add new methods to the `MemoryManager` interface such as `CopyBufferSlice` etc.

### Component(s)

C++

**Comment by alanstoate** [comment]
take

**Comment by pitrou** [comment]
Issue resolved by pull request 41477
https://github.com/apache/arrow/pull/41477
