### ISSUE TITLE
[C++] DataType::ToString should optionally show metadata

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#39864]
### Describe the enhancement requested

A DataType doesn't directly carry metadata, but if it is a nested DataType, some of its child fields might carry metadata.

Therefore, similar to Schema::ToString, DataType::ToString should take an optional `show_metadata` argument.

### Component(s)

C++

**Comment by Cerdore** [comment]
I'm interested in working on this issue!

**Comment by Cerdore** [comment]
We should add an optional argument "show_metadata" to the ToString method of DataType and other DataType derived class. And we also need to add  `show_metadata` to  TypeHolder::ToString() , right?

Additionally, the Schema::ToString method already has an optional "show_metadata" argument.

**Comment by pitrou** [comment]
>     1. We should add an optional argument "show_metadata" to the ToString method of DataType and other DataType derived class. And we also need to add  `show_metadata` to  TypeHolder::ToString() , right?

Yes!

>     2. Default value of `show_metadata` should always be false in derived class. Because virtual functions are dynamically bound, but default parameter values are statically bound.

I suppose so, yes. In any case, we want the API to be consistent, this makes life easier for users.
