### ISSUE TITLE
[Go][Parquet] Inaccurate RowGroupTotalCompressedBytes/RowGroupTotalBytesWritten with go parquet file writer

### ISSUE THREAD

**Issue by matthewmcnew** [apache/arrow#39870]
### Describe the bug, including details regarding any error messages, version, and platform.

There does not appear to be an accurate way to identify or estimate the size of the current row group with `pqarrow.FileWriter`. 

`RowGroupTotalCompressedBytes()`provides the total bytes from [created data pages](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L334) but, when the [dictionary page size limit is reached ](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer_types.gen.go.tmpl#L240-L242) the buffered data pages are flushed and the [total size is reset to "0"](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L400). This means the RowGroupTotalCompressedBytes will only provide the size of pages created after the dictionary page size was reached. Ideally the size the TotalCompressedBytes size should include all created data pages. 

`RowGroupTotalBytesWritten()` will provide the total bytes of DataPages when [they are written](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L461) but, not if the the page is buffered due to the [dictionary page still being created](https://github.com/apache/arrow/blob/main/go/parquet/file/column_writer.go#L330). This causes the `RowGroupTotalBytesWritten` to inaccurately provide a "0" bytes estimate until the dictionary page size limit is reached.

Perhaps related to: https://github.com/apache/arrow/issues/39789. 

### Component(s)

Go

**Comment by zeroshade** [comment]
Thanks for tracking down the cause! It's likely related if not directly the cause of the issue you linked. 

Is this something you think you'd be willing to contribute a PR for? I don't have the bandwidth immediately, so it'll take me a week or so to dig into this. But I can definitely review any PRs

**Comment by mapleFU** [comment]
About totalBytesWritten, I've summarize similiar interface in C++:
https://github.com/apache/arrow/pull/33897#issuecomment-1440131022

Don't know if there're better solutions

**Comment by zeroshade** [comment]
@matthewmcnew Did https://github.com/apache/arrow/pull/39922 fix this issue? or is it still exhibiting this problem?

**Comment by zeroshade** [comment]
@matthewmcnew That makes sense to me

**Comment by matthewmcnew** [comment]
@zeroshade https://github.com/apache/arrow/pull/40105 should be ready for review now.
