### ISSUE TITLE
[C#] Restore support for .NET 4.6.2

### ISSUE THREAD

**Issue by CurtHagenlocher** [apache/arrow#39916]
### Describe the bug, including details regarding any error messages, version, and platform.

.NET 4.6.2 is still in support but removing the netstandard1.3 target caused the latest version of Arrow not to support it. Consider adding back explicit support for 4.6.2.

### Component(s)

C#

**Comment by raulcd** [comment]
@CurtHagenlocher this is labeled as `backport-candidate` should I add it to a possible 15.0.1 patch release?

**Comment by CurtHagenlocher** [comment]
@raulcd Yes, please; I've updated the milestone.
