### ISSUE TITLE
[Python][FS][Azure] Minimal python bindings for `AzureFilesystem`

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#39968]
### Describe the enhancement requested

Child issue of: https://github.com/apache/arrow/issues/39317

Blocked by: https://github.com/apache/arrow/issues/39352

Create minimal pybindings such that the Azure filesystem is useable. Probably this will have no configuration options exposed and will always just use default credential auth. 

I think it makes sense to circle back later to fill out all the configuration options that exist and may be added to `AzureFilesystem`

### Component(s)

Python

**Comment by Tom-Newton** [comment]
I want to enable the python side tests for Azure but there are a couple of failures. 
1. Move operations are not supported yet. https://github.com/apache/arrow/pull/39904 looks like its almost done I believe this will implement file and directory moves for hierarchical namespace accounts but not for flat namespace. These tests run against azurite, which is flat namespace so https://github.com/apache/arrow/pull/39904 actually won't solve this. We should at least add support for file moves to get parity with S3 and GCS.
2. Currently we can't read metadata set by the user, only system metadata generated by azure. This is explained here https://github.com/Tom-Newton/arrow/blob/8d6b96d7269a57317068cbaa59d2ff80d65be1a7/cpp/src/arrow/filesystem/azurefs.cc#L334-L346

I'm hoping its ok to skip these for Azure initially. I can create Github issues to get these ironed out.

**Comment by felipecrv** [comment]
I plan to add `::Move()` for flat-namespace accounts as well. I started with HNS because it's easier, but I hope the one based on Blobs will be helped by the infrastructure I've built for Move on HNS accounts. I won't have to write SO MANY tests, but I will have to fix all the issues they catch.
