### ISSUE TITLE
[C++][FS][Azure] Include user set metadata in `ObjectInputFile::ReadMetadata`

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#40026]
### Describe the enhancement requested

Child of https://github.com/apache/arrow/issues/18014

The current implementation only returns system metadata on the blobs not user set metadata. That means the `AzureFileSystem` can't round trip the metadata. 

As part of this task `TEST_F(TestAzuriteFileSystem, WriteMetadata)` should probably be updated so that it uses `AzureFileSystem` to assert that metadata is being written correctly. Currently this tests uses the Azure APIs to fetch the metadata to make this assertion. 

### Component(s)

C++

**Comment by Tom-Newton** [comment]
Assuming https://github.com/apache/arrow/pull/40021 is completed first, then this ticket should include enabling the python side tests for move. I will add TODO(GH-40026) comments where relevant.

**Comment by kou** [comment]
Issue resolved by pull request 40671
https://github.com/apache/arrow/pull/40671
