### ISSUE TITLE
[C++][FS][Azure] Optimise `ObjectAppendStream::DoAppend` in the case of many small appends

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#40036]
### Describe the enhancement requested

Optimisation to https://github.com/apache/arrow/issues/38333
Child of https://github.com/apache/arrow/issues/18014

Currently `ObjectAppendStream::DoAppend` calls `block_blob_client_->StageBlock` synchronously meaning that the call to `ObjectAppendStream::DoAppend` blocks until the data has been successfully written to blob storage. This is very in-efficient for large numbers of small writes. 

This performance problem is actually quite obvious just in small tests against azurite. The [`UploadLines`](https://github.com/apache/arrow/blob/d9891918a42c74002533ed5c06c42b7d0d070820/cpp/src/arrow/filesystem/azurefs_test.cc#L529-L535) function used to create test data uses `std::accumulate` and writes the data in one call for performance reasons.  

With accumulate
```
[ RUN      ] TestAzuriteFileSystem.OpenInputFileMixedReadVsReadAt
[       OK ] TestAzuriteFileSystem.OpenInputFileMixedReadVsReadAt (1350 ms)
```

without accumulate (4096 separate calls to `ObjectAppendStream::DoAppend`).
```
[ RUN      ] TestAzuriteFileSystem.OpenInputFileMixedReadVsReadAt
[       OK ] TestAzuriteFileSystem.OpenInputFileMixedReadVsReadAt (25124 ms)
```
And this is when testing against `azurite` on localhost so against real blob storage where the latency is going to be much higher the problem will be exacerbated.  

By comparison the GCS filesystem is able to handle [the later approach](https://github.com/apache/arrow/blob/d9891918a42c74002533ed5c06c42b7d0d070820/cpp/src/arrow/filesystem/gcsfs_test.cc#L1282-L1286) without performance issues. 

Some options to optimise:
1. Call `block_blob_client_->StageBlock` asynchronously and await all the futures in `ObjectAppendStream::Flush`.
2. Buffer small writes in memory and make fewer larger calls to `block_blob_client_->StageBlock`.
3. Buffer small writes in memory and make batched calls to `block_blob_client_->StageBlock`.

### Component(s)

C++

**Comment by pitrou** [comment]
You should **definitely** buffer small writes in memory. The S3 filesystem [does that](https://github.com/apache/arrow/blob/91bf1c9c170c1917ad47bb0dbb38aa5c9fbbbfb2/cpp/src/arrow/filesystem/s3fs.cc#L1545-L1592).

You should also optionally allow async writes, as [in S3](https://github.com/apache/arrow/blob/91bf1c9c170c1917ad47bb0dbb38aa5c9fbbbfb2/cpp/src/arrow/filesystem/s3fs.h#L155-L156), and have `Flush` ensure all writes have finished.

**Comment by OliLay** [comment]
Is there anybody working on this issue? It's kind of a blocking issues as it makes writing to Azure Blob quite slow.

**Comment by pitrou** [comment]
@OliLay Does using a [`BufferedOutputStream`](https://github.com/apache/arrow/blob/524a463207fdb799b2cd784b7ef95052165882ec/cpp/src/arrow/io/buffered.h#L38) fix the problem for you?

Though I agree this should probably be handled transparently inside the Azure FS implementation. @felipecrv

**Comment by OliLay** [comment]
Thanks, I haven't tried that so far, but I guess this won't fully solve the problem as writing on the stream would still block once the buffer size is exceeded as we call write on the underlying Azure output stream. So I agree that probably a non-blocking write mode + internal buffering (as it is implemented for S3) would be the best approach.

**Comment by pitrou** [comment]
Agreed!

**Comment by OliLay** [comment]
I opened a PR which addresses this issue: https://github.com/apache/arrow/pull/43096

**Comment by pitrou** [comment]
Issue resolved by pull request 43096
https://github.com/apache/arrow/pull/43096
