### ISSUE TITLE
[C++][Python] Basic conversion of RecordBatch to Arrow Tensor - add option to cast NULL to NaN

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#40061]
### Describe the enhancement requested

This issue is a part of https://github.com/apache/arrow/issues/40058 adds option to cast `NULL` to `NaN` mimicking the cast from [ConvertIntegerWithNulls](https://github.com/apache/arrow/blob/c67d0260d4e96472b5cbdff66ca67ead2b9abe4c/python/pyarrow/src/arrow/python/arrow_to_pandas.cc#L550).

### Component(s)

C++, Python

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 40803
https://github.com/apache/arrow/pull/40803
