### ISSUE TITLE
[C++] Possible data race in accessing scalars

### ISSUE THREAD

**Issue by mpimenov** [apache/arrow#40069]
### Describe the bug, including details regarding any error messages, version, and platform.

I use an ```arrow::compute::literal``` in my parquet reading pipeline and get ThreadSanitizer reports about this code:
https://github.com/apache/arrow/blob/c23a097965b5c626cbc91b229c76a6c13d36b4e8/cpp/src/arrow/array/data.cc#L288-L290

If I am reading it right, this results in issuing write instructions during what would seem to be read-only accesses, and this indeed looks racy.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Can you show your stack trace?

**Comment by mpimenov** [comment]
Arrow is built from commit 3c655df6d459f50cc9734b4f4da31c84ece6c030
[tsan-40069.txt](https://github.com/apache/arrow/files/14283806/tsan-40069.txt)

**Comment by pitrou** [comment]
Thank you. It looks like calling `ArraySpan::FillFromScalar` from several threads is legitimate when the same scalar is used as input for different computations. Given that this is probably always writing the same value, it would probably be enough to use relaxed atomic stores.

@bkietz

**Comment by pitrou** [comment]
@bkietz Would you be able to take a look at this?

**Comment by pitrou** [comment]
@zanmato1984 I'm not sure about the answer to the rest of your question, but for the record Arrow C++ doesn't promise any ABI stability. We do try to maintain API compatibility (with the occasional deprecation or signature change), but people are expected to recompile when switching from one version of Arrow C++ to another.

**Comment by zanmato1984** [comment]
> > However, the interpretation of the scratch space is type-dependent, i.e., some types treat it as two 32-byte space and others treat it as two 64-byte space.
> 
> But all threads accessing the scratch space should interpret it as the same type, right?
> 

Right. The question here is that the scratch space is defined in a generic place, i.e., `ArraySpanFillFromScalarScratchSpace` (base class of all "scratched" scalars) and we couldn't know how it is going to be interpreted at runtime, despite whether all threads interpret it as the same type or not.

> > extra atomic flags + spinning (keeping scratch space itself unchanged - as plane memory)
> 
> Please let's avoid home-grown synchronization like this. Either we can use atomic accesses without spinning, or we should use a lock.

Yeah, of course. I was thinking about using mutex too.

**Comment by pitrou** [comment]
> Right. The question here is that the scratch space is defined in a generic place, i.e., `ArraySpanFillFromScalarScratchSpace` (base class of all "scratched" scalars) and we couldn't know how it is going to be interpreted at runtime, despite whether all threads interpret it as the same type or not.

It would be incorrect for different threads to interpret it differently, even with a lock.

**Comment by zanmato1984** [comment]
> > Right. The question here is that the scratch space is defined in a generic place, i.e., `ArraySpanFillFromScalarScratchSpace` (base class of all "scratched" scalars) and we couldn't know how it is going to be interpreted at runtime, despite whether all threads interpret it as the same type or not.
> 
> 
> 
> It would be incorrect for different threads to interpret it differently, even with a lock.

You are right about this too.

I think here are two things:
1. Is the scratch being interpreted identically by different threads?
2. If 1 is yes, is it a race?

For 1, if the answer is no, then it should fall into some sort of undefined behavior area. That will be a user code problem that is using scalar the wrong way. It is not essential whether this is a race, or how the synchronization is implemented. And hopefully, and fortunately, I think current compute and Acero components are using scalar the "right way". So we don't really need to worry about it. 

For 2, this is what we are really talking about. Aren't we :)

**Comment by pitrou** [comment]
Right, so I think we can simply use atomic stores here.
In debug mode, we can perhaps be a bit more sophisticated and check that we don't write two different values, but that's optional IMHO.

**Comment by zanmato1984** [comment]
> Right, so I think we can simply use atomic stores here. In debug mode, we can perhaps be a bit more sophisticated and check that we don't write two different values, but that's optional IMHO.

Are you suggesting something like this?
https://github.com/apache/arrow/pull/40237/files#diff-1d848527e898cd9da6a41bdbd68cab5d5826986128851220d20d1fdac9752d8bR289-R292

**Comment by pitrou** [comment]
Yes, roughly.

**Comment by bkietz** [comment]
Issue resolved by pull request 40237
https://github.com/apache/arrow/pull/40237
