### ISSUE TITLE
[C++][FlightRPC] Running multi-node flight benchmarks with ucx transport

### ISSUE THREAD

**Issue by ysfess22** [apache/arrow#40072]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi, I'm facing the ucx error below when running flight benchmarks with ucx: 

This is what I did: 

Server side: 
`./release/arrow-flight-perf-server -server_host server_addr -server_port 49731 -transport ucx`

Client side (different machine):
`./release/arrow-flight-benchmark -server_host server_addr -server_port 49731 -transport ucx`

Output: 

Server side:
```
wireup.c:410  UCX  ERROR   ep 0x7f9fa2ee1000: no remote ep address for lane[1]->remote_lane[1]
[1707859837.486667] [server_addr:2262746:0]       wireup_cm.c:1263 UCX  WARN  server ep 0x7f9fa2ee1000 failed to connect to remote address on device eno1, tl_bitmap 0x1 0x0, status Destination is unreachable
[server][peer=client_addr:56522] Failed to create endpoint: IOError: ucp_ep_create: UCX error -6: UCS_ERR_UNREACHABLE Destination is unreachable. Detail: Destination is unreachable

```

Client side:
```
Testing method: DoGet
Failed with error: << IOError: ucp_request_check_status: UCX error -23: UCS_ERR_REJECTED Operation rejected by remote peer. Detail: Operation rejected by remote peer
[1707858431.412244] [client_addr:3821527:0]           flush.c:26   UCX  ERROR req 0x55d0180c81c0: error during flush: Endpoint timeout, flush comp 0x55d0180c8260 count reduced to 1
[1707858431.412251] [client_addr:3821527:0]           flush.c:26   UCX  ERROR req 0x55d0180c81c0: error during flush: Endpoint timeout, flush comp 0x55d0180c8260 count reduced to 0
```

The error occurs when when the ucp endpoint is made on the server side: 
https://github.com/apache/arrow/blob/0dbbd43ca9133912d1809394727784560cc5e797/cpp/src/arrow/flight/transport/ucx/ucx_server.cc#L503 

Please note that this benchmark works fine with gRPC. Any suggestion on what went wrong here? Thank you. 

### Component(s)

Benchmarking, C++, FlightRPC

**Comment by kou** [comment]
@cyb70289 Could you take a look at this?

**Comment by cyb70289** [comment]
Does it work if run client and server on same host, i.e., server_host = 127.0.0.1.

Are the client and server in same subnet and can directly talk to each other? E.g., without NAT.

**Comment by ysfess22** [comment]
@kou @cyb70289 Thanks for the prompt reply. Yes, the benchmarks works fine in the same host. The client and server are not on the same subnet but pinging from one side to the other works fine. So I think the client and server can talk to each other.

**Comment by cyb70289** [comment]
From below ucx issue, looks ucx expects all parties on same subnet.
https://github.com/openucx/ucx/issues/9526#issuecomment-1868287759
