### ISSUE TITLE
[C++][FS][Azure] Implement `DeleteFile()` for flat-namespace storage accounts

### ISSUE THREAD

**Issue by felipecrv** [apache/arrow#40074]
### Describe the enhancement requested

`AzureFileSystem::DeleteFile` is implemented for storage accounts with Hierarchical Namespace Support enabled (GH-38703), but not for storage accounts that can use only the Blobs API and represent directories with empty directory marker blobs.

This is a child of GH-18014.

### Component(s)

C++

**Comment by av8or1** [comment]
felipecrv - Have you begun work on this one?

**Comment by felipecrv** [comment]
@av8or1 yes, it was closed after the merge of #40075. I added you as co-author in the commit BTW.

**Comment by av8or1** [comment]
Apologies, I didn't include the link!  This is the one I was referring to, the move in the flat-namespace storage accounts:
[40025](https://github.com/apache/arrow/issues/40025)
