### ISSUE TITLE
[C++] Import/Export ArrowDeviceArrayStream

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#40078]
### Describe the enhancement requested

https://github.com/apache/arrow/pull/34972 added the definition of `ArrowDeviceArrayStream` to the C Device Data interface, but the initial PR for the device interface in C++ only added support for `ArrowDeviceArray` (https://github.com/apache/arrow/issues/36488 / https://github.com/apache/arrow/pull/36489).

cc @zeroshade 

### Component(s)

C++

**Comment by jorisvandenbossche** [comment]
@zeroshade are there plans to add this to the C++ library? We have added `ArrowDeviceArrayStream` to the Arrow spec, but AFAIU there is no implementation of it anywhere?

**Comment by zeroshade** [comment]
There are definitely plans to do so, It's on my list of things. I'll try to bump up the priority

**Comment by zeroshade** [comment]
Issue resolved by pull request 40807
https://github.com/apache/arrow/pull/40807
