### ISSUE TITLE
[CI] Move M1 self-hosted runners to newly available GitHub M1 runners

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#40077]
### Describe the enhancement requested

GitHub added availability of macOS ARM (M1) runners a couple of weeks ago for Open Source projects:
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

It would be good to migrate our self-hosted M1 runners to ephemeral GitHub runners.

### Component(s)

Continuous Integration

**Comment by kou** [comment]
Issue resolved by pull request 40437
https://github.com/apache/arrow/pull/40437
