### ISSUE TITLE
[C++][Parquet] Remove AVX512 variants of BYTE_STREAM_SPLIT encoding

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#40095]
### Describe the enhancement requested

According to previous observations, it seems the AVX512 accelerations of BYTE_STREAM_SPLIT perform equal or worse then their AVX2 counterparts.

Besides, the SSE2 and AVX2 accelerations, already performing at 5-10 GB/s or more, are amply fast enough.

We could therefore simply remove the AVX512 accelerations.

### Component(s)

Benchmarking, C++, Parquet

**Comment by pitrou** [comment]
@cyb70289 @wgtmac @mapleFU @felipecrv Opinions on this?

**Comment by felipecrv** [comment]
> According to previous observations, it seems the AVX512 accelerations of BYTE_STREAM_SPLIT perform equal or worse then their AVX2 counterparts.

Isn't that due to the effects of down-clocking when the CPU is executing too many AVX-512 instructions? It might be better in the future or to users that have a way to avoid that down-clocking.

**Comment by pitrou** [comment]
I don't think all CPUs have down-clocking, do they? But regardless, if it doesn't provide a significant benefit, it doesn't make much sense to keep those codepaths, IMHO.

**Comment by mapleFU** [comment]
I think BYTE_STREAM_SPLIT encoding/decoding might be memory-bound operations. We can remove the AVX512 impl first. If anyone wants to improve or requires AVX512, we can also revert it back...
