### ISSUE TITLE
R package fails to install on OSX

### ISSUE THREAD

**Issue by jpryda** [apache/arrow#4010]
I'm getting an error installing the R package on OSX (R version 3.5.2).  

Following a successful homebrew install of apache arrow, on running `devtools::install_github("apache/arrow/r")` within RStudio the compilation + installation all but completes successfully:

```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/arrow/libs/arrow.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/arrow/libs/arrow.so, 6): Symbol not found: __ZN5boost11basic_regexIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9do_assignEPKcS7_j
  Referenced from: /usr/local/opt/apache-arrow/lib/libparquet.12.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/opt/apache-arrow/lib/libparquet.12.dylib
Error: loading failed
```

**Comment by fsaintjacques** [comment]
Could you open a ticket at https://jira.apache.org/jira/projects/ARROW/issues/ARROW-4997?filter=allopenissues 

We'll follow the discussion there. Meanwhile, you can check if boost is installed with brew.

**Comment by jpryda** [comment]
Will do.  

`boost 1.69.0 is already installed and up-to-date`
