### ISSUE TITLE
[C++][Parquet] Separate encoders and decoder

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#40154]
### Describe the enhancement requested

Currently, encoders and decoders are defined in a single file `encoding.cc`, which is quite large.

Given that their infrastructure is separate, it would probably make maintenance easier to split them into two C++ source files (for example `encoder.cc` and `decoder.cc`). We can add corresponding `.h` files, and also keep `encoding.h` for compatibility.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Thoughts @felipecrv @mapleFU @wgtmac ?

**Comment by mapleFU** [comment]
I just check that there're few common constant used in `encoding.cc`, so maybe spliting them is not hard.

But I'm not sure about this. Current code is also ok to me

**Comment by felipecrv** [comment]
> split them into two C++ source files

I'm in favor, but it will be 3 files (or .h/.cc pairs) because there has to be one for the shared funcitonality. One risk of the split is exposing the bits that are now fully private in `encoding.cc`.

**Comment by wgtmac** [comment]
Perhaps we can add a `encoding_internal.h` file to hold those private but common stuff?

**Comment by pitrou** [comment]
> Perhaps we can add a `encoding_internal.h` file to hold those private but common stuff?

We can, though I doubt there's much shared functionality.

**Comment by changkhothuychung** [comment]
Hi, I am new to apache arrow and I would like to take this issue. Can this one be assigned to me?

**Comment by mapleFU** [comment]
You can type "take" to take the issue, and create a pull request named "GH-40154: [C++][Parquet] ..." when you finished @changkhothuychung

**Comment by kou** [comment]
Assigned!
