### ISSUE TITLE
[Go][FlightRPC] Implement session management

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#40155]
### Describe the enhancement requested

The session management primitives from https://github.com/apache/arrow/issues/34865 aren't yet supported in Go.

### Component(s)

FlightRPC, Go

**Comment by joellubi** [comment]
I can work on this

**Comment by lidavidm** [comment]
Thanks!

FWIW, if you comment just "take" on an issue, a bot should assign it to you

**Comment by joellubi** [comment]
I've just opened a PR for this: #40284

**Comment by zeroshade** [comment]
Issue resolved by pull request 40284
https://github.com/apache/arrow/pull/40284
