### ISSUE TITLE
Adding links to main documentation page to flip between API doc versions? 

### ISSUE THREAD

**Issue by mathemakitten** [apache/arrow#4016]
Hi! Would it possible to add the API docs for previous PyArrow versions as a drop-down link in the sidebar of this page? https://arrow.apache.org/docs/python/api.html

I find myself working in multiple environments with PyArrow versions ranging from 0.8.0 to 0.12+, and since the core Python API has changed quite a bit version-to-version, I have a hard time finding what I need sometimes. Or is there an existing way to easily flip between documentation versions? I might be missing it. Thanks!

**Comment by fsaintjacques** [comment]
Hello @mathemakitten, this seems like a legit request. I don't think we have versioned doc yet. The documentation system changed quite a bit lately.

I can suggest you to clone arrow repository, checkout the proper tag and read from there (you can try building the doc with docker-compose, but this also changed and markdown is readable).

Meanwhile could you open a ticket at https://jira.apache.org/jira/projects/ARROW/issues/ARROW-4997?filter=allopenissues about supporting versioned documentation?

**Comment by mathemakitten** [comment]
Excellent, I will do both of those things! Thank you for the thorough response, @fsaintjacques. Much appreciated.
