### ISSUE TITLE
[CI][Packaging] Homebrew CPP job has been failing for some days

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#40184]
### Describe the bug, including details regarding any error messages, version, and platform.

The [homebrew-cpp](https://github.com/ursacomputing/crossbow/actions/runs/7986115835/job/21805858631) job has been failing for some days with the following output:
```
 /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/Cellar/apache-arrow/HEAD-29a0581_3/lib/libarrow.a(ios.mm.o) has no symbols
...
 /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/Cellar/apache-arrow/HEAD-29a0581_3/lib/libarrow_acero.a(swiss_join_avx2.cc.o) has no symbols
...
ln -s ../../Cellar/apache-arrow/HEAD-29a0581_3/lib/pkgconfig/arrow.pc arrow.pc
ln -s ../../Cellar/apache-arrow/HEAD-29a0581_3/lib/pkgconfig/gandiva.pc gandiva.pc
ln -s ../../Cellar/apache-arrow/HEAD-29a0581_3/lib/pkgconfig/parquet.pc parquet.pc
==> Summary
🍺  /usr/local/Cellar/apache-arrow/HEAD-29a0581_3: 589 files, 126.8MB, built in 9 minutes 42 seconds
Error: Process completed with exit code 1.
```
I couldn't find the error and I am not sure if the above logs say anything.

This is also failing on the maint-15.0.1 branch.

### Component(s)

Continuous Integration, Packaging

**Comment by raulcd** [comment]
@kou any idea what is the issue? I can't seem to find what is happening

**Comment by kou** [comment]
Hmm. The "no symbols" log exists on success build too. e.g.: https://zulip.clear-code.com/#narrow/stream/6-.E3.82.AF.E3.83.AA.E3.82.A2.E3.82.B3.E3.83.BC.E3.83.89/topic/.E6.96.B0.E5.85.A5.E7.A4.BE.E5.93.A1/near/291673
So it may not be related.

We may need to add some debug logs... I may be able to work on this in a few days...

**Comment by pitrou** [comment]
Should this issue be closed now?

**Comment by raulcd** [comment]
This has been running successfully since March 23rd 2024:
[Successful build email for 23rd March](https://lists.apache.org/thread/kl3cbqg0q3xcz88rnwqtgmcqrh54hvtw)
[Failing build email for 22nd March](https://lists.apache.org/thread/vjt59mdcchvqrjjw2cmmwyf33m5pqy8x)
We can close this as this is not happening anymore.
