### ISSUE TITLE
[R][CI] Add (or restore) devel clang nightlies (with libc++)

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#40212]
### Describe the enhancement requested

There are a number of CRAN extra tests that use a pre release version of clang (and also links to libc++). And we don't currently have good coverage of this in our CI. I thought we used to so I will try and find that in the git history or add it new.

### Component(s)

Continuous Integration, R

**Comment by kou** [comment]
Issue resolved by pull request 40244
https://github.com/apache/arrow/pull/40244
