### ISSUE TITLE
Adding some projects to "Powered By Arrow" page

### ISSUE THREAD

**Issue by SebastianoMeneghin** [apache/arrow#40235]
### Describe the enhancement requested

I think that some projects should be added to the Powered By page.
One of them, with which I am working right now, is called [DeltaRS](https://github.com/delta-io/delta-rs), which is a Rust library that allows to write to DeltaLake using Python. In this case, Arrow can be used as table-over-the-network format.

Thanks

### Component(s)

Documentation, Website

**Comment by kou** [comment]
Could you open a PR to https://github.com/apache/arrow-site ?

**Comment by SebastianoMeneghin** [comment]
> Could you open a PR to https://github.com/apache/arrow-site ?

Just done!
Thanks for forwarding me there.
