### ISSUE TITLE
[C++][Python] glog 0.7 fix breaks downstream packages

### ISSUE THREAD

**Issue by bnavigator** [apache/arrow#40274]
### Describe the bug, including details regarding any error messages, version, and platform.

After applying #40230 to the cpp library and building with glog 0.7. Anything building with ArrowConfig.cmake now fails. For example a pyarrow  wheel build:

```
[   31s]   CMake Error at CMakeLists.txt:268 (find_package):
[   31s]     Found package configuration file:
[   31s] 
[   31s]       /usr/lib64/cmake/Arrow/ArrowConfig.cmake
[   31s] 
[   31s]     but it set Arrow_FOUND to FALSE so package "Arrow" is considered to be NOT
[   31s]     FOUND.  Reason given by package:
[   31s] 
[   31s]     Arrow could not be found because dependency GLOG could not be found.
[   31s] 
[   31s] 
[   31s] 
[   31s]   -- Configuring incomplete, errors occurred!
```

This was not the case before.

The build fails because ArrowConfig.cmake requires but cannot find uppercase GLOG.

_Originally posted by @bnavigator in https://github.com/apache/arrow/issues/40230#issuecomment-1968870506_
        

### Component(s)
C++, Python

**Comment by bnavigator** [comment]
Full build logs: 
* [apache-arrow-build.txt](https://github.com/apache/arrow/files/14434377/apache-arrow-build.txt)
* Resulting ArrowConfig.cmake:  [ArrowConfig.cmake](https://github.com/apache/arrow/files/14434398/ArrowConfig.cmake.txt)
* [pyarrowfail.txt](https://github.com/apache/arrow/files/14434359/pyarrowfail.txt)

**Comment by kou** [comment]
Issue resolved by pull request 40275
https://github.com/apache/arrow/pull/40275
