### ISSUE TITLE
[C++]  An implicit buffer-overflow in decimal_benchmark

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#40276]
### Describe the bug, including details regarding any error messages, version, and platform.

An implicit buffer-overflow bug in blow codes:
```c
  for (int x = 0; x < kValueSize; x++) {
    v.emplace_back(100 + x, 100 + x);
  }

  for (auto _ : state) {
    BasicDecimal128 result;
    for (int x = 0; x < 100; x++) { // should be kValueSize
      result += v[x];
    }
    benchmark::DoNotOptimize(result);
  }
```

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 40277
https://github.com/apache/arrow/pull/40277
