### ISSUE TITLE
[C++] A wrong total_bytes to generate StringType's test data in vector_hash_benchmark

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#40306]
### Describe the bug, including details regarding any error messages, version, and platform.

A  wrong total_bytes to generate StringType's test data in vector_hash_benchmark.
https://github.com/apache/arrow/blob/30e6d72242e376baa598b2e8f1d9b80d800a974c/cpp/src/arrow/compute/kernels/vector_hash_benchmark.cc#L128

It may cause the implicit buffer-overflow and inaccurate benchmark.

### Component(s)

C++

**Comment by bkietz** [comment]
Issue resolved by pull request 40307
https://github.com/apache/arrow/pull/40307
