### ISSUE TITLE
[Python] Don't initiate the ScalarMemoTable when it isn't needed

### ISSUE THREAD

**Issue by anjakefala** [apache/arrow#40316]
### Describe the bug, including details regarding any error messages, version, and platform.

This is the use-case for why this is important: https://github.com/apache/arrow/issues/40301

The memo table is only used if [`deduplicate_objects=True`](https://github.com/apache/arrow/blob/a6e577d031d20a1a7d3dd01536b9a77db5d1bff8/python/pyarrow/src/arrow/python/arrow_to_pandas.cc#L635), but [it gets instantiated regardless](https://github.com/apache/arrow/blob/a6e577d031d20a1a7d3dd01536b9a77db5d1bff8/python/pyarrow/src/arrow/python/arrow_to_pandas.cc#L609). 

### Component(s)

Python

**Comment by pitrou** [comment]
Issue resolved by pull request 40565
https://github.com/apache/arrow/pull/40565
