### ISSUE TITLE
[C++] Enable Array creation from Scalar

### ISSUE THREAD

**Issue by vyasr** [apache/arrow#40318]
### Describe the enhancement requested

Currently creating an ArrowArray from a Scalar requires going through the Builder interface. While this is fine as a general solution, a common special case is the creation of an Array from a single Scalar (possibly copying that Scalar N times). Abstracting out the handling of different types could be helpful for this case. If there is interest in this feature, [there is code that I wrote for this task in cudf](https://github.com/rapidsai/cudf/blob/branch-24.04/cpp/src/interop/from_arrow.cu#L511) that could easily be extracted into arrow C++ (we're likely to remove that functionality from libcudf).

Concretely, this would be something like an API with the signature:
```
arrow::Array from_scalar(arrow::Scalar const& input, size_type N=1)
````

Apologies if there is such a function somewhere in the C++ and I missed it.

### Component(s)

C++

**Comment by kou** [comment]
It seems that we have `arrow::MakeArrayFromScalar()`:
https://github.com/apache/arrow/blob/640667664abbdb9ddf38d32781715cc783a69885/cpp/src/arrow/array/util.h#L49-L55

Could you take a look at it?

**Comment by vyasr** [comment]
That looks exactly like what I was envisioning. I've tested it and it works just as I'd expect. I can't find that function anywhere in [the C++ documentation](https://arrow.apache.org/docs/search.html?q=MakeArrayFromScalar), though. Could we add it somewhere/ Perhaps to a factories section on the Arrays page similar to [the one that exists for Scalars](https://arrow.apache.org/docs/cpp/api/scalar.html#factory-functions)?

**Comment by kou** [comment]
It makes sense. Could you work on this?

**Comment by vyasr** [comment]
@kou yup! I opened #40373 for this.

**Comment by pitrou** [comment]
Issue resolved by pull request 40373
https://github.com/apache/arrow/pull/40373
