### ISSUE TITLE
[C++][Parquet] Allow use of FileDecryptionProperties after CryptoFactory is destroyed

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#40328]
### Describe the enhancement requested

The `CryptoFactory::GetFileDecryptionProperties` method has this comment:
https://github.com/apache/arrow/blob/5ce6ff434c1e7daaa2d7f134349f3ce4c22683da/cpp/src/parquet/encryption/crypto_factory.h#L116-L119

I've recently been working on adding bindings to the Parquet key management tools API to ParquetSharp, a .NET Parquet library that wraps the Arrow C++ Parquet library: https://github.com/G-Research/ParquetSharp/pull/426

I couldn't find a good way to keep the CryptoFactory alive as long as the FileDecryptionProperties are alive, so this means that users of the .NET library have to be aware of this requirement to avoid getting a native error from the C++ library that can't be caught as a .NET exception.

Ideally for our use case, the FileDecryptionProperties could remain alive independent of the CryptoFactory. It seems to me like this would also be better for other uses of the C++ API, by making the API simpler and more robust.

I will make a PR with a proposed change to fix this.

### Component(s)

C++, Parquet

**Comment by adamreeve** [comment]
take

**Comment by pitrou** [comment]
Issue resolved by pull request 40329
https://github.com/apache/arrow/pull/40329
