### ISSUE TITLE
[Java] JDBC Flight SQL driver not connect  to individual endpoints specified by GetFlightInfo

### ISSUE THREAD

**Issue by xinyiZzz** [apache/arrow#40336]
### Describe the bug, including details regarding any error messages, version, and platform.

FlightEndpoint returned by GetFlightInfoPreparedStatement is another flight server, but JDBC Flight SQL driver still fetch results from main flight server connection.

version: 15.0.0 release and 15.0.0 nightlies 2024.2.20

https://github.com/apache/arrow/issues/38785, In fact I found this problem in arrow 14.0.1, It was solved using 15.0.0 nightlies at that time, but today I tried again and found problem occurred again.

https://github.com/apache/arrow/pull/38521 This PR seems to actually solve this problem.

### Component(s)

FlightRPC

**Comment by lidavidm** [comment]
Hmm, there were definitely other changes but looking at the core it should definitely be using all locations:

https://github.com/apache/arrow/blob/2b194ad222f4dc8ecf2eb73539ab8cab5b1fc5e7/java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/client/ArrowFlightSqlClientHandler.java#L111-L177

**Comment by xinyiZzz** [comment]
> Hmm, there were definitely other changes but looking at the core it should definitely be using all locations:

Thanks for your reply, i will debug this part of the code

**Comment by xinyiZzz** [comment]
I upgrade to arrow 15.0.2 and redeploy environment, no problem anymore. not sure it’s related to version or environment.

close issue, thanks for reply.
