### ISSUE TITLE
[C++][Gandiva] An error during the build process for gandiva

### ISSUE THREAD

**Issue by llama90** [apache/arrow#40334]
### Describe the bug, including details regarding any error messages, version, and platform.

After pulling the latest code and enabling the options to build Gandiva (`-DARROW_GANDIVA=ON`), I encounter the following error while performing the build.

I am using an M1 MacBook.

I also tried after running the command `brew update && brew bundle --file=cpp/Brewfile`.

```bash
In file included from /Users/lama/workspace/arrow-new/cpp/src/gandiva/encrypt_utils_test.cc:18:
/Users/lama/workspace/arrow-new/cpp/src/gandiva/encrypt_utils.h:20:10: fatal error: 'openssl/aes.h' file not found
#include <openssl/aes.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

### Component(s)

C++ - Gandiva

**Comment by kou** [comment]
Could you try this?

```diff
diff --git a/cpp/src/gandiva/CMakeLists.txt b/cpp/src/gandiva/CMakeLists.txt
index 0f28b0da82..3e63f88c3d 100644
--- a/cpp/src/gandiva/CMakeLists.txt
+++ b/cpp/src/gandiva/CMakeLists.txt
@@ -269,7 +269,8 @@ add_gandiva_test(internals-test
                  interval_holder_test.cc
                  tests/test_util.cc
                  EXTRA_LINK_LIBS
-                 re2::re2)
+                 re2::re2
+                 ${GANDIVA_OPENSSL_LIBS})
 
 add_subdirectory(precompiled)
 add_subdirectory(tests)
```

**Comment by llama90** [comment]
Thank you for your response :)

Oh... Your suggestion is working well.

May I create a PR?

**Comment by kou** [comment]
Yes, please!

**Comment by kou** [comment]
Issue resolved by pull request 40338
https://github.com/apache/arrow/pull/40338
