### ISSUE TITLE
[C++] Move LocalFileSystem to a separate module

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#40342]
### Describe the enhancement requested

https://github.com/apache/arrow/issues/38309 adds the capability to build FileSystems separately. Apply this to LocalFileSystem

### Component(s)

C++

**Comment by bkietz** [comment]
Issue resolved by pull request 40356
https://github.com/apache/arrow/pull/40356

**Comment by raulcd** [comment]
Shouldn't this be 17.0.0? For some of our downstream packages we might require some changes (like conda)
