### ISSUE TITLE
[C++] Add benchmark for ToTensor conversions

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#40357]
### Describe the enhancement requested

We should add benchmarks to be sure not to cause regressions while working on additional implementations of `RecordBatch::ToTensor` and `Table::ToTensor`.

The first step is to create a benchmark file with a basic benchmark for a simple uniform case of `RecordBatch` to `Tensor` conversion (all fields same type, no missing values). With follow-up features being added we should also add more cases to this benchmark file.

### Component(s)

C++

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 40358
https://github.com/apache/arrow/pull/40358
