### ISSUE TITLE
object_store 0.9.1 breaks Azure Storage Emulator Config

### ISSUE THREAD

**Issue by aersam** [apache/arrow#40362]
### Describe the bug, including details regarding any error messages, version, and platform.

delta-rs is using this config to connect to Azure Storage Emulator:

```python
dict(
        AZURE_STORAGE_ACCOUNT_NAME="devstoreaccount1",
        AZURE_STORAGE_ACCOUNT_KEY="Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==",
        AZURE_STORAGE_CONTAINER_NAME="deltars",
        AZURE_STORAGE_USE_EMULATOR="true",
        AZURE_STORAGE_USE_HTTP="true",
    )
```

this is passed via python, but it basically just sets the configs in object_store.

In 0.9.1, this started to cause an authentication error:

```
E       OSError: Generic MicrosoftAzure error: Client error with status 403 Forbidden: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
E       <Error>
E         <Code>AuthorizationFailure</Code>
E         <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.
E       RequestId:44a1c5ff-8a6b-491a-a890-e07d0d823e87
E       Time:2024-03-05T11:31:55.140Z</Message>
E       </Error>
```

 Can you check this?

Since there was a check in Azure Authentication in object_store 0.9.1, is there some different config required? I was assuming a bug since it's only a minor version increase and the config looks good

### Component(s)

Other

**Comment by kou** [comment]
Could you report this to https://github.com/apache/arrow-rs/ ?
This is not the upstream of object_store.

**Comment by aersam** [comment]
Ah sorry, ported it here: https://github.com/apache/arrow-rs/issues/5475
