### ISSUE TITLE
[C++][Acero] Do acero hashJoin support input left_keys or right_keys as expressions

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#40380]
## Request like below
PostgreSQL like below:
```sql
postgres=# explain verbose select * from a,b where (a.c1+1)=b.c1;
                               QUERY PLAN
-------------------------------------------------------------------------
 Hash Join  (cost=55.90..1477.27 rows=23052 width=20)
   Output: a.c1, a.c2, a.c3, b.c1, b.c2
   Hash Cond: (b.c1 = (a.c1 + 1))
   ->  Seq Scan on public.b  (cost=0.00..32.60 rows=2260 width=8)
         Output: b.c1, b.c2
   ->  Hash  (cost=30.40..30.40 rows=2040 width=12)
         Output: a.c1, a.c2, a.c3
         ->  Seq Scan on public.a  (cost=0.00..30.40 rows=2040 width=12)
               Output: a.c1, a.c2, a.c3
```

For this kind of situation, the hash-key will become an expression rather than a field_ref.

For this situation, we need do project for the hash-key first when we select the hash-key-batch before we do build/probe.

But for now, seems we're not supporting this in basic_join and swiss_join implementation?

### Component(s)

C++

**Comment by zanmato1984** [comment]
Normally this projection can be done by inserting a `Projection` node between `TableScan` and `HashJoin` nodes during the planning phase. So it is not necessary for a hash join algorithm to implement that itself.

**Comment by ZhangHuiGui** [comment]
Yes, you're right. We could implement the plan by add a projection before hashjoin.
Thanks ~
