### ISSUE TITLE
[Python] Python build was broken by Cython 3.0.9

### ISSUE THREAD

**Issue by vyasr** [apache/arrow#40386]
### Describe the bug, including details regarding any error messages, version, and platform.

The [Cython 3.0.9 release yesterday (3/5/24)](https://cython.readthedocs.io/en/latest/src/changes.html#id2) added a warning [when a Cython function is marked noexcept while returning a Python object](https://github.com/cython/cython/pull/5999). This appears to have broken builds of pyarrow (see recent runs on #40373). I glanced at pyarrow's setup.py and it wasn't immediately obvious clear where/if pyarrow is setting [warnings as errors for Cython](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#Cython.Compiler.Options.warning_errors), but I assume it is doing so if it's breaking the build.

### Component(s)

Python

**Comment by austin3dickey** [comment]
Note that this is causing all benchmarking builds to fail as well (causing messages like https://github.com/apache/arrow/pull/40367#issuecomment-1980301946)

**Comment by kou** [comment]
Duplicated of #40375.

**Comment by jorisvandenbossche** [comment]
Closed by #40387

**Comment by jorisvandenbossche** [comment]
> I glanced at pyarrow's setup.py and it wasn't immediately obvious clear where/if pyarrow is setting [warnings as errors for Cython](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#Cython.Compiler.Options.warning_errors), but I assume it is doing so if it's breaking the build.

Small follow-up, we indeed do that here:

https://github.com/apache/arrow/blob/49cdb0fe4e98fda19031c864a18e6156c6edbf3c/python/CMakeLists.txt#L722-L723

(I was wondering myself as well ;))

And thanks for the PR!

**Comment by vyasr** [comment]
Aha I didn't realize it was building with CMake using a custom setuptools command setup.

My follow-up was going to be if you'd considered using scikit-build, but it looks like there's already discussion of that in #36411!
