### ISSUE TITLE
[C++] Add support for mold

### ISSUE THREAD

**Issue by kou** [apache/arrow#40394]
### Describe the enhancement requested

https://github.com/rui314/mold

It's a faster linker. It will reduce build time.

### Component(s)

C++

**Comment by assignUser** [comment]
Issue resolved by pull request 40397
https://github.com/apache/arrow/pull/40397

**Comment by amoeba** [comment]
Hi @kou, @assignUser: It seems like we should document this in the developer docs. Any reason not to?

**Comment by kou** [comment]
You're right.
We should document this and LLD's one.
We just forgot them...
Could you open an issue for them?

**Comment by amoeba** [comment]
Yep, will do.

**Comment by amoeba** [comment]
Done, see https://github.com/apache/arrow/issues/41408.
