### ISSUE TITLE
[C++] Missing protobuf link dependency for libarrow.a

### ISSUE THREAD

**Issue by tobim** [apache/arrow#40398]
### Describe the bug, including details regarding any error messages, version, and platform.

If `libarrow` is built with a system protobuf and either opentelemetry or ORC is enabled, `Protobuf` must be resolved in `find_package(Arrow)` so CMake can generate a link command line for targets depending on libarrow. This is currently not the case.

### Component(s)

C++

**Comment by kou** [comment]
Is this happen on main too?

**Comment by tobim** [comment]
The problem exists on 15.0.0, I haven't checked main. Were there relevant changes since then?

**Comment by kou** [comment]
I'm not sure. Could you try main?

**Comment by tobim** [comment]
I tried on 1c9a3122c603e2766a793766a11ff4c706efb2aa, still affected.

**Comment by kou** [comment]
OK. Thanks for trying this!
