### ISSUE TITLE
[GLib] Add missing compute function options classes

### ISSUE THREAD

**Issue by stenlarsson** [apache/arrow#40402]
### Describe the enhancement requested

In most cases the options to compute functions are optional, but there are cases where they are required. The following compute functions are not possible to use in Ruby because the required options classes are missing from the GLib bindings:

* `split_pattern`: `SplitPatternOptions`
* `strftime`: `StrftimeOptions` (technically not required)
* `strptime`: `StrptimeOptions`
* `struct_field`: `StructFieldOptions`

There are probably more functions that cannot be used, but this is a start.

### Component(s)

GLib

**Comment by kou** [comment]
Issue resolved by pull request 40403
https://github.com/apache/arrow/pull/40403
