### ISSUE TITLE
[Python] Error installing PyArrow with the recent release of 15.0.1

### ISSUE THREAD

**Issue by liangyun123** [apache/arrow#40409]
### Describe the bug, including details regarding any error messages, version, and platform.

When installing for the latest version of PyArrow using poetry with Python configured to latest 3.11 version, poetry attempts to install PyArrow v15.0.1. Checking the released distributions for PyArrow v15.0.1, the released built distributions are only for Python 3.10 macosx. As a result, Poetry errors because it's unable to locate the built distributions for PyArrow v15.0.1 for Python 3.11. While looking through the release, the source distribution was also not published. 

Attaching the pyproject.toml used for testing:
```
[tool.poetry]
name = "testing"
version = "1.0.0.dev"
description = "Description of package"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11.4"
pyarrow = "^15.0.1"

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
```

### Component(s)

Python

**Comment by joshasharpe** [comment]
> We had an issue with the size limit on PyPI when submitting wheels a couple hours ago. [pypi/support#3717](https://github.com/pypi/support/issues/3717) I am going to publish them again now that the size limit has been increased.

Do you have an estimated timeline? If it takes too long, is it worth it and feasible to push 15.0.2 as a revert to 15.0.0?  Since this is a patch it will likely break a lot of builds in the meantime that aren't pinned to that level. I'm not familiar enough with the pip publishing process to know the timeline or difficulties of either of these.

**Comment by raulcd** [comment]
All wheels have been uploaded now to 15.0.1.
