### ISSUE TITLE
[C++][FlightRPC] Add missing expiration_time arguments

### ISSUE THREAD

**Issue by llama90** [apache/arrow#40422]
### Describe the bug, including details regarding any error messages, version, and platform.

It seems that a similar error occurred as before. 

- #38210 

```bash
~/workspace/arrow/cpp/src/arrow/flight/integration_tests/test_integration.cc:2090:57: error: missing field 'expiration_time' initializer [-Werror,-Wmissing-field-initializers]
    auto endpoint = FlightEndpoint{{"reuse"}, {location}};
```

Adding `std::nullopt` as `expiration_time` and `""` as `app_metadata` for all calls to the `FlightEndpoint` constructor resolves the issue.

This can be detected when `-DARROW_BUILD_BENCHMARKS=ON`. I use m1 macbook.

### Component(s)

FlightRPC

**Comment by llama90** [comment]
@kou What do you think about this? As was the case before, it seems that because it occurred during benchmarking, it could not be discovered during CI.

**Comment by kou** [comment]
Could you open a PR that adds them?

We should add a nightly CI job (`test-ubuntu-22.04-cpp-benchmark` or something) that uses `-DARROW_BUILD_BENCHMARKS=ON` but doesn't run benchmark.

**Comment by llama90** [comment]
Aha! I got it. I will create PR.

**Comment by lidavidm** [comment]
Issue resolved by pull request 40425
https://github.com/apache/arrow/pull/40425
