### ISSUE TITLE
[CI][Debian] Use Debian 12 because Debian 11 will reach EOL on 2024-07

### ISSUE THREAD

**Issue by kou** [apache/arrow#40454]
### Describe the enhancement requested

https://wiki.debian.org/DebianReleases

| Version | Code name | Release date | End of life data |
|--------|--------|--------|--------|
| 11 | Bullseye | 2021-08-14 | ~2024-07 |

### Component(s)

Continuous Integration

**Comment by raulcd** [comment]
Issue resolved by pull request 40455
https://github.com/apache/arrow/pull/40455
