### ISSUE TITLE
[C#] Create simple example of C# HTTP GET Arrow client

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40480]
### Describe the enhancement requested

Contribute a C# .NET client example to the [set of minimal HTTP GET examples in the `arrow-experiments` repo](https://github.com/apache/arrow-experiments/tree/main/http/get_simple).

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Addressed via apache/arrow-experiments/#25
