### ISSUE TITLE
[Python][CI] Skip failing test_dateutil_tzinfo_to_string

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#40485]
### Describe the bug, including details regarding any error messages, version, and platform.

We should skip `test_dateutil_tzinfo_to_string` that started failing with the new release of python-dateutil in order to enable new minor Arrow release.

Connected to: https://github.com/apache/arrow/issues/40337

### Component(s)

Continuous Integration, Python

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 40486
https://github.com/apache/arrow/pull/40486
