### ISSUE TITLE
[C#] Create simple example of C# HTTP GET Arrow server

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40481]
### Describe the enhancement requested

Contribute a C# .NET server example to the [set of minimal HTTP GET examples in the `arrow-experiments` repo](https://github.com/apache/arrow-experiments/tree/main/http/get_simple).

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Addressed via #https://github.com/apache/arrow-experiments/pull/25
