### ISSUE TITLE
Request to update arrow library version in Vcpkg 

### ISSUE THREAD

**Issue by AndrewTsao** [apache/arrow#4048]
Apache arrow latest release is 0.12.*, Arrow release version in Vcpkg repo (https://github.com/Microsoft/vcpkg) is  0.11.1, request updates it. build it on windows is difficult. thank you.

**Comment by kou** [comment]
Could you open a pull request to https://github.com/Microsoft/vcpkg ?
Or could you find a volunteer in dev@arrow.apache.org mailing list?
http://mail-archives.apache.org/mod_mbox/arrow-dev/
