### ISSUE TITLE
[Go] Add support for protobuf messages

### ISSUE THREAD

**Issue by kp-tom-sc** [apache/arrow#40494]
### Describe the enhancement requested

**Context**

My team recieve protobuf messages from a kafka topic, we want to deserialise them and write them to S3 as parquet.

At the moment the suggested way is to convert them via JSON i.e. https://github.com/apache/arrow/issues/37807

I would like more support for protobuf features such as any, or one of.

### Component(s)

Go

**Comment by zeroshade** [comment]
Issue resolved by pull request 40496
https://github.com/apache/arrow/pull/40496
