### ISSUE TITLE
[C++] lddtree reports "security problem" when run on Arrow libraries

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#40503]
### Describe the bug, including details regarding any error messages, version, and platform.

On a freshly compiled Arrow C++ in debug mode, I get the following warning when running `lddtree` on `libarrow.so` and any other of our libraries:
```console
$ lddtree /build/build-test/debug/libarrow.so
libarrow.so => /build/build-test/debug/libarrow.so (interpreter => none)
scanelf: rpath_security_checks(): Security problem NULL DT_RPATH in /build/build-test/debug/libarrow.so
[ repeated a number of times ]
```

I'm not sure there's an actual problem here, but it would be worth investigating.

### Component(s)

C++

**Comment by pitrou** [comment]
@kou @xhochy @felipecrv Does this warning ring a bell?

**Comment by pitrou** [comment]
Only in the `build` folder. So it may be a red herring indeed.

**Comment by xhochy** [comment]
I remember that (at least on OSX) we explicitly didn't set a RPATH there so that the unit tests work and load the correct (local) libraries.

**Comment by pitrou** [comment]
I see. Well, I'll leave this open a day or two in case other people want to chime in, otherwise I'll close as not-a-bug. Thank you :-)

**Comment by kou** [comment]
I agree with xhochy.

**Comment by pitrou** [comment]
Ok, I'll close. Thanks all!
