### ISSUE TITLE
[Python] when pyArrow S3FileSystem support  force_virtual_addressing in new release

### ISSUE THREAD

**Issue by kadisi** [apache/arrow#40506]
### Describe the usage question you have. Please include as many useful details as  possible.

I found that the latest pyarrow code already supports the force_virtual_addressing parameter  but not in releae 1.15.2. 

from  @yo1956  pr：  https://github.com/apache/arrow/pull/39819

and we test it is ok for other S3 compatible storage.

May I ask in which Release this feature will be released and when? We urgently need this feature to access Alibaba Cloud oss object storage, and do not want to recompile the pyarrow package.

the Alibaba Cloud OSS is an AWS S3 compatible storage： only support virtual hosted style to access.

if we use pyarrow S3FileSystem to access Alibaba Cloud oss , we need  force_virtual_addressing parameter.

@chenk008  https://github.com/apache/arrow/issues/38135

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
It will be released in the next major release, which will be 16.0 (targetted for second half of April). 
(you can also see the milestone on the closed issue https://github.com/apache/arrow/issues/39779)

If you want to test it earlier, you can try to use the nightly packages: https://arrow.apache.org/docs/dev/developers/python.html#installing-nightly-packages

**Comment by kadisi** [comment]
> It will be released in the next major release, which will be 16.0 (targetted for second half of April). (you can also see the milestone on the closed issue #39779)
> 
> If you want to test it earlier, you can try to use the nightly packages: https://arrow.apache.org/docs/dev/developers/python.html#installing-nightly-packages

@jorisvandenbossche  ok， thank you. i have tested it.
