### ISSUE TITLE
[C++][ORC] Upgrade ORC to 2.0.0

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#40507]
### Describe the enhancement requested

Use ORC to 2.0.0
- https://orc.apache.org/news/2024/03/08/ORC-2.0.0/

### Component(s)

C++, Java

**Comment by raulcd** [comment]
This might allow us to enable on Windows for pyarrow solving the segmentation fault: https://github.com/apache/arrow/pull/37382

**Comment by wgtmac** [comment]
@raulcd TBH, I don't think so. I managed to build it on Windows and will try to reproduce that issue later. It will take some time as I'm not that familiar with python and conda.

**Comment by pitrou** [comment]
Issue resolved by pull request 40508
https://github.com/apache/arrow/pull/40508
