### ISSUE TITLE
[Java] Bump org.apache.maven dependencies from 3.3.9 to 3.8.7

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40515]
### Describe the enhancement requested

Bump `/java/maven/module-info-compiler-maven-plugin/pom.xml` to a higher version to address vulnerabilities identified in https://deps.dev/maven/org.apache.maven%3Amaven-core/3.3.9.

### Component(s)

Java

**Comment by kou** [comment]
Issue resolved by pull request 40514
https://github.com/apache/arrow/pull/40514
