### ISSUE TITLE
[CI] Replace additional self-hosted runners from crossbow 

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#40536]
### Describe the enhancement requested

We missed https://github.com/apache/arrow/blob/4fe364efa4be98b35964509e0e3d57a421a48039/dev/tasks/tasks.yml#L1001 in #40077 and the 10.13 runner can also be replaced with gha macos-11 (12 once that is removed) as cran no longer uses 10.13 builders.

### Component(s)

Continuous Integration

**Comment by raulcd** [comment]
Issue resolved by pull request 40537
https://github.com/apache/arrow/pull/40537
