### ISSUE TITLE
[Docs][Python] Document pyarrow.dataset.JsonFileFormat

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#40575]
See https://stackoverflow.com/questions/78130263/correct-way-to-specify-json-block-size-for-pyarrow-dataset:

> It appears that at the time of this writing JsonFileFormat is simply missing from the documentation for pyarrow.dataset. The documentation has CsvFileFormat, IpcFileFormat, ParquetFileFormat and OrcFileFormat but not JsonFileFormat.

**Comment by kou** [comment]
@arunppsg Could you write "take" only comment here to assign you to this issue?

**Comment by kou** [comment]
Issue resolved by pull request 40585
https://github.com/apache/arrow/pull/40585
