### ISSUE TITLE
[Python] Create Python examples of HTTP GET Arrow client/server supporting multipart/mixed response

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40598]
### Describe the enhancement requested

Contribute Python client and server examples to the [HTTP GET multipart examples in the `arrow-experiments` repo](https://github.com/apache/arrow-experiments/tree/main/http/get_multipart). This should demonstrate a server/client pair that sends/receives a multipart response (`Content-Type: multipart/mixed`) containing JSON data (`Content-Type: application/json`) and Arrow IPC stream data (`Content-Type: application/vnd.apache.arrow.stream`).

### Component(s)

Python

**Comment by ianmcook** [comment]
A challenge with this approach is that the part delimiter must not occur in the data, as described here: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

So to support all possible sequences of bytes that might occur in Arrow IPC stream data, the server would need to be able to dynamically choose a viable delimiter sequence by checking that it is not contained in the IPC stream bytes to be sent in the response.

On the other hand, maybe it's sufficient for the server to simply use a part delimiter that is highly unlikely to occur in the IPC stream bytes.

**Comment by ianmcook** [comment]
Using an dynamically generated, unpredictable, max-allowed-length (70-character) alphanumeric delimiter generated by a cryptographic hash function is perhaps the best way to reduce the risk that the delimiter exists in the IPC stream bytes. Discussion welcome here.

**Comment by felipecrv** [comment]
> cryptographic hash function

Close. But that is still a deterministic generation process. A CSPRNG will do.

**Comment by felipecrv** [comment]
https://github.com/apache/arrow-experiments/pull/33
