### ISSUE TITLE
[Python] Create Python examples of HTTP GET Arrow client and server using HTTP compression

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40601]
### Describe the enhancement requested

Create simple Python-based HTTP client and server examples like the ones in [`arrow-experiments/http/get_simple` ](https://github.com/apache/arrow-experiments/tree/main/http/get_simple)  or [`arrow-experiments/http/get_range` ](https://github.com/apache/arrow-experiments/tree/main/http/get_range) but using HTTP compression.

For example, the client sends a request with header `Accept-Encoding: gzip, deflate, br, zstd` and the server sends a response with header `Content-Encoding: gzip` and with the response body gzip-compressed which the HTTP client library automatically decompresses.

### Component(s)

Python

**Comment by felipecrv** [comment]
watching

**Comment by ianmcook** [comment]
@felipecrv I suggested using Python here for simplicity, but it could be in some other language if needed

**Comment by ianmcook** [comment]
@felipecrv let's please make sure we test HTTP compression using the zstd codec. That way we will have a same-codec comparison between HTTP compression and Arrow IPC buffer compression.

(Besides zstd, the only other codec that IPC buffer compression supports is lz4. But lz4 is rarely or never supported for HTTP compression. So zstd is our only choice for same-codec comparisons.)

**Comment by felipecrv** [comment]
I'm doing all of them actually. Server can acts according to the `Accept-Encoding` header and negotiate the chosen compression. But I will put a recommendation for `zstd` for sure.

**Comment by felipecrv** [comment]
https://github.com/apache/arrow-experiments/pull/35
