### ISSUE TITLE
[C++] Rename `Function::is_impure()` to `is_pure()`

### ISSUE THREAD

**Issue by felipecrv** [apache/arrow#40607]
### Describe the enhancement requested

Remove the property negation from the function name so that reasoning about the boolean value is easier.

"is_impure = false" vs "is_pure = true"
"is_impure" vs "!is_pure"

### Component(s)

C++

**Comment by felipecrv** [comment]
Issue resolved by pull request 40608
https://github.com/apache/arrow/pull/40608

**Comment by amoeba** [comment]
Hi @felipecrv, this looks like a breaking change to me. What do you think?

**Comment by mapleFU** [comment]
@amoeba This is not a breaking change since is_pure is also new added

**Comment by mapleFU** [comment]
I found this is marked as "breaking change" in release note, but it's not required, lol: https://arrow.apache.org/blog/2024/04/20/16.0.0-release/

**Comment by felipecrv** [comment]
It could be breaking for people programming against what is available on the `main` because I flipped the meaning of a boolean parameter. Perhaps it's one of those cases where it's better to safe than sorry.

**Comment by amoeba** [comment]
Thanks for catching my mistake @mapleFU! I didn't catch that the change was against unreleased code and I should have caught that before commenting here.

I put up a PR to remove it from the blog post: https://github.com/apache/arrow-site/pull/511.

**Comment by amoeba** [comment]
https://github.com/apache/arrow-site/pull/511 has been merged so this is no longer marked as breaking in the release blog post.
