### ISSUE TITLE
[Python] ORC Reader aborts when timezone file is missing

### ISSUE THREAD

**Issue by WillAyd** [apache/arrow#40633]
### Describe the bug, including details regarding any error messages, version, and platform.

This is an upstream report of https://github.com/pandas-dev/pandas/issues/56292

I noticed when running the pandas test suite I was getting this error:

```
pandas/tests/io/test_orc.py::test_orc_reader_basic terminate called after throwing an instance of 'orc::TimezoneError'
  what():  Can't open /usr/share/zoneinfo/US/Pacific
Fatal Python error: Aborted

Current thread 0x00007eff1a912780 (most recent call first):
```

The workaround is to create that timezone file:

```
$ sudo mkdir -p /usr/share/zoneinfo/US
$ sudo ln -s /usr/share/zoneinfo/America/Los_Angeles /usr/share/zoneinfo/US/Pacific
```

Although I think the error should be handled more gracefully than via abort

### Component(s)

Python

**Comment by kou** [comment]
@wgtmac will improve this.
See also:
* https://github.com/apache/arrow/issues/36026#issuecomment-2006087340 and related discussions
* https://github.com/apache/orc/pull/1587

**Comment by wgtmac** [comment]
This seems to be related to the installed version of tz database on the test machine. I checked my laptop and the path `/usr/share/zoneinfo/US/Pacific` exists. Could you verify the version by checking `/usr/share/doc/tzdata/version` file? @WillAyd

**Comment by WillAyd** [comment]
That file does not exist for me. This is running popOS 22.04

**Comment by kou** [comment]
Could you try installing the `tzdata-legacy` package?

**Comment by WillAyd** [comment]
I don't see that package for 22.04 - I think first appeared in 23.04?

**Comment by kou** [comment]
Oh, sorry. Could you install `tzdata`?

**Comment by WillAyd** [comment]
It is already installed - `tzdata is already the newest version (2024a-0ubuntu0.22.04).`

**Comment by kou** [comment]
Hmm. `tzdata` must install `/usr/share/zoneinfo/US/Pacific`: https://packages.ubuntu.com/jammy/all/tzdata/filelist

**Comment by WillAyd** [comment]
Ah OK - interesting indeed. That must have been deleted off of my system somehow, but I do see that in a recovery OS.

Happy to close this issue if we want to chalk it up to an unsupported system configuration

**Comment by aureliobarbosa** [comment]
> Could you try installing the `tzdata-legacy` package?

I also observed pyarrow breaking while processing ORC files, due to inexistent IANA keys. Those were observed on running the pandas test suit locally, but just trying to read some pre-existent ORC files completely broke python and ipython. My setup includes Ubuntu Mantic, Python 3.11 and `tzdata` version 2024.1.

At least in my case, installing `tzdata-legacy` system wide was enough to get ride of those errors.

**Comment by rhshadrach** [comment]
I've been debugging this issue and independently found the same solution - installing `tzdata-legacy`. Just stashing my error message here in case it is helpful for others.

> pyarrow.lib.ArrowInvalid: Cannot locate timezone 'US/Eastern': US/Eastern not found in timezone database

**Comment by kou** [comment]
Issue resolved by pull request 45051
https://github.com/apache/arrow/pull/45051
