### ISSUE TITLE
[CI][Release][Java] verify-rc-source-java-linux-almalinux-8-amd64 failed with old Maven

### ISSUE THREAD

**Issue by kou** [apache/arrow#40649]
### Describe the bug, including details regarding any error messages, version, and platform.

#39696 updated required Maven version to 3.6.3 or later but verify-rc-source-java-linux-almalinux-8-amd64 still uses Maven 3.5.4. So `org.apache.maven.plugins:maven-shade-plugin:3.5.2:shade` reports an error:

https://github.com/ursacomputing/crossbow/actions/runs/8326821831/job/22783243688#step:6:76985

```text
 Error:  Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.5.2:shade (default) on project arrow-vector: The plugin org.apache.maven.plugins:maven-shade-plugin:3.5.2 requires Maven version 3.6.3 -> [Help 1]
 ```

### Component(s)

Continuous Integration, Java

**Comment by vibhatha** [comment]
@kou 

```bash
=============================
Build and test Java libraries
=============================
/arrow/java /arrow /
/arrow/dev/release/verify-release-candidate.sh: line 614: mvn: command not found
Failed to verify release candidate. See /tmp/arrow-HEAD.FB64e for details.
```

**Comment by kou** [comment]
#40514 will fix this too.

**Comment by vibhatha** [comment]
@kou should we verify this on the main explicitly?

**Comment by kou** [comment]
What does "this" mean? The error in the description is happening on the main.

**Comment by vibhatha** [comment]
Oh what I meant was verify if the failed CI job is passing on the main explicitly?
