### ISSUE TITLE
estimate for release to conda-forge containing "ARROW-4642: [R] change f to file in read_parquet_file()"?

### ISSUE THREAD

**Issue by cmorgan** [apache/arrow#4065]
Hi, 
When do you estimate a release to conda forge containing "ARROW-4642: [R] change f to file in read_parquet_file()"?
Thanks

**Comment by wesm** [comment]
hi @cmorgan I recommend opening an issue on https://github.com/conda-forge/r-arrow-feedstock about this. I suspect the maintainers will update the package after the 0.13 release goes out
