### ISSUE TITLE
[C#] Invalid magic at offset

### ISSUE THREAD

**Issue by piyushdubey** [apache/arrow#40655]
### Describe the usage question you have. Please include as many useful details as  possible.

I am using the Arrow File Reader to read an arrow file and getting the below error. 

`System.IO.InvalidDataException: 'Invalid magic at offset <6>'`

My use case is pretty straightforward

```
using Apache.Arrow.Ipc;
using Microsoft.Data.Analysis;
using System.Reflection;

public class Program
{
    public static void Main(string[] args)
    {
        var filePath = "file.arrow";

        try
        {
            using (var arrowFileReader = ArrowFileReader.FromFile(filePath))
            {
                var arrowRecordBatch = arrowFileReader.ReadNextRecordBatch();
                var arrowRecord = DataFrame.FromArrowRecordBatch(arrowRecordBatch);
            }
        }
        catch (Exception ex) 
        { 
            Console.Write(ex.Message);
        }
    }
}
```

The arrow is thrown at line `var arrowRecordBatch = arrowFileReader.ReadNextRecordBatch();`

The table has three columns of type -> `Date, Decimal, Timestamp`

Thoughts?

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
The implication of the error message is that the first six bytes of the file are something other than "ARROW1".

**Comment by lidavidm** [comment]
How was the file written?

It's quite possible this is an [Arrow stream](https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format) (which doesn't have the magic) and not an [Arrow file](https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format).

**Comment by piyushdubey** [comment]
File was creating using code similar to below--

- First created a list of columns
- Created a RecordBatch
- Wrote this to a Stream.

```
IList<Column> column = DummyMethodToCreateColumnList();

RecordBatch recordBatch = ArrowConverter.Convert(columnList);
var writer = new ArrowStreamWriter(responseStream, recordBatch.Schema, leaveOpen: true);
await writer.WriteRecordBatchAsync(recordBatch, cancellationToken);
await writer.WriteEndAsync(cancellationToken);

responseStream.Position = 0;
```

**Comment by piyushdubey** [comment]
> How was the file written?
> 
> It's quite possible this is an [Arrow stream](https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format) (which doesn't have the magic) and not an [Arrow file](https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format).

That's what I suspect. 

I reading Parquet File from a Delta Table containing a single column of type Decimal. Transformed Parquet column to a generic column which I pass to  the record batch

The Writer doesn't throw any exception but the reader does.

**Comment by CurtHagenlocher** [comment]
ArrowStreamWriter goes with ArrowStreamReader. ArrowFileWriter goes with ArrowFileReader.

**Comment by piyushdubey** [comment]
> ArrowStreamWriter goes with ArrowStreamReader. ArrowFileWriter goes with ArrowFileReader.

Sorry, didn't get you? My understanding about streams is that I can read any stream written using ArrowStreamWriter using an ArrowStreamReader?

In my flow - I am reading an ArrowSteam with ArrowStreamReader which was created with ArrowStreamWriter.

**Comment by CurtHagenlocher** [comment]
> > ArrowStreamWriter goes with ArrowStreamReader. ArrowFileWriter goes with ArrowFileReader.
> 
> Sorry, didn't get you? My understanding about streams is that I can read any stream written using ArrowStreamWriter using an ArrowStreamReader?
> 
> In my flow - I am reading an ArrowSteam with ArrowStreamReader which was created with ArrowStreamWriter.

In the code you posted, you're reading the stream with ArrowFileReader instead of ArrowStreamReader.

**Comment by piyushdubey** [comment]
It doesn't work with ArrowFileReader either. Updated the example above - `ArrowFileReader.FromFile(filePath)`

I guess it boils down to the way file was written.

**Comment by piyushdubey** [comment]
This is how I am creating columns - #40657

**Comment by CurtHagenlocher** [comment]
The original code snippet you posted in this thread is using ArrowFileReader while the second code snippet is using ArrowStreamWriter. The error message you got is consistent with this difference. If the data was created with ArrowStreamWriter, it should be read with ArrowStreamReader.

If you're having trouble making some code work, it would be helpful to supply an entire chunk of compiler-ready code which demonstrates the problem -- perhaps as a Gist that's linked to from this issue.  The individual bits of code both here and in the other issue are incomplete and not sufficient to understand what might be going wrong.

**Comment by CurtHagenlocher** [comment]
@piyushdubey, based on offline conversation I'm going to mark this as closed. Feel free to reopen if you still have a question or problem.
