### ISSUE TITLE
[C++][FS][Azure] Add support for reading user defined metadata

### ISSUE THREAD

**Issue by kou** [apache/arrow#40670]
### Describe the enhancement requested

We've implemented `ReadMetadata()` by #38330.
It uses properties not user defined metadata. But our generic test has a test that writes/reads user defined metadata: https://github.com/apache/arrow/blob/bb9f229d8e8ac6b42e03b93d597f5f93e1b6bb42/cpp/src/arrow/filesystem/test_util.cc#L911-L927

### Component(s)

C++

**Comment by Tom-Newton** [comment]
I think this duplicates  https://github.com/apache/arrow/issues/40026

**Comment by kou** [comment]
Oh, sorry.
