### ISSUE TITLE
[Java] JDK 22 Support

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#40680]
### Describe the enhancement requested

Verify JDK 22 and enable it in CI jobs.

### Component(s)

Java

**Comment by danepitkin** [comment]
We need to wait for the Eclipse Temurin 22 release and then for the maven/temurin docker release before we can add to CI.

**Comment by vibhatha** [comment]
I can take a look at this.

**Comment by danepitkin** [comment]
Here is the link to the maven docker registry: https://hub.docker.com/_/maven

It will probably take a week or two before the container is available.

**Comment by vibhatha** [comment]
take

**Comment by danepitkin** [comment]
For tracking purposes https://github.com/adoptium/temurin/issues/35

**Comment by danepitkin** [comment]
Hey @vibhatha , I went ahead and created the PR!

**Comment by lidavidm** [comment]
Issue resolved by pull request 41038
https://github.com/apache/arrow/pull/41038

**Comment by vibhatha** [comment]
> Hey @vibhatha , I went ahead and created the PR!

Thanks Dane, it could have taken me a little longer. Apologies I couldn't review this PR before it got merged. I reviewed it later, looks good to me.
