### ISSUE TITLE
[CI][Python] python-sdist job fails with pytest not found

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#40706]
### Describe the bug, including details regarding any error messages, version, and platform.

[python-sdist](https://github.com/ursacomputing/crossbow/actions/runs/8355876590/job/22871821900) is failing with:
```
 + pytest -r s --pyargs pyarrow
/arrow/ci/scripts/python_sdist_test.sh: line 60: pytest: command not found
```
This is probably due to virtualenv not active.

### Component(s)

Continuous Integration, Python

**Comment by kou** [comment]
Issue resolved by pull request 40707
https://github.com/apache/arrow/pull/40707
