### ISSUE TITLE
[Docs][Format] Update ADBC spec version to 1.1.0 in Arrow spec docs

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#40713]
### Describe the enhancement requested

The ADBC pages in the Arrow specifications docs need to be updated to refer to ADBC spec version 1.1.0:
https://github.com/apache/arrow/blob/main/docs/source/format/ADBC.rst
https://github.com/apache/arrow/tree/main/docs/source/format/ADBC

The content on these pages could also be pared down somewhat and replaced with links to ADBC docs pages such as https://arrow.apache.org/adbc/current/format/specification.html

### Component(s)

Documentation

**Comment by ianmcook** [comment]
@lidavidm is this something you can do, or nominate someone to do? Thanks

**Comment by lidavidm** [comment]
Issue resolved by pull request 44313
https://github.com/apache/arrow/pull/44313
