### ISSUE TITLE
[CI][Java][Integration] Integration verification jobs are failing due to libarrow_cdata_jni.so not found

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#40716]
### Describe the bug, including details regarding any error messages, version, and platform.

Verification integration jobs have been failing for a long time:
[verify-rc-source-integration-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8326820551/job/22783238495)
[verify-rc-source-integration-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8326821549/job/22783241848)
[verify-rc-source-integration-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8326821294/job/22783240707)
[verify-rc-source-integration-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8326822265/job/22783288184)
[verify-rc-source-integration-macos-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8326821150/job/22783239900)
[verify-rc-source-integration-macos-conda-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8326820569/job/22783238615)

It seems that they have been failing since the 19th of January. The commits between the last success and the first failure are: https://github.com/apache/arrow/compare/55afcf0450aa2b611e78335bdbfd77e55ae3bc9f...05b8f366e17ee6f21df4746bb6a65be399dfb68d
I suspect https://github.com/apache/arrow/issues/39001 is the culprit.

Based on the logs:
```
 [ERROR]   StreamTest.getNextError:192 ? IllegalState error loading native libraries: java.io.FileNotFoundException: arrow_cdata_jni/x86_64/libarrow_cdata_jni.so
[ERROR]   StreamTest.getSchemaError:213 ? IllegalState error loading native libraries: java.io.FileNotFoundException: arrow_cdata_jni/x86_64/libarrow_cdata_jni.so
[ERROR]   StreamTest.roundtripDictionary:169->roundtrip:228 ? IllegalState error loading native libraries: java.io.FileNotFoundException: arrow_cdata_jni/x86_64/libarrow_cdata_jni.so
[ERROR]   StreamTest.roundtripStrings:131->roundtrip:257->roundtrip:228 ? IllegalState error loading native libraries: java.io.FileNotFoundException: arrow_cdata_jni/x86_64/libarrow_cdata_jni.so
[ERROR]   StreamTest.testRoundtripInts:94->roundtrip:257->roundtrip:228 ? IllegalState error loading native libraries: java.io.FileNotFoundException: arrow_cdata_jni/x86_64/libarrow_cdata_jni.so
```

### Component(s)

Continuous Integration, Integration, Java

**Comment by raulcd** [comment]
cc @jduo @danepitkin

**Comment by jduo** [comment]
Yes it looks related to changing the location of JNI libraries. JNI libraries now need to be in <library_name>/<arch>/<lib name>.<extension>

**Comment by danepitkin** [comment]
The verification scripts are mostly passing on main and fully passing in an open PR https://github.com/apache/arrow/pull/40514. Are the verification script tests here failing in a different environment?

**Comment by raulcd** [comment]
Those are on main and those are verify integration not verify java. I think the verify java are good.

**Comment by danepitkin** [comment]
Thank you for the clarification!

**Comment by kou** [comment]
Issue resolved by pull request 40724
https://github.com/apache/arrow/pull/40724
