### ISSUE TITLE
Can't use `array.RecordBuilder,NewRecord` when one of the fields has `arrow.NullType`

### ISSUE THREAD

**Issue by candiduslynx** [apache/arrow#40719]
### Describe the bug, including details regarding any error messages, version, and platform.

If we use `new(arrow.NullType)` as data type for one of the fields in the record, the `array.RecordBuilder,NewRecord` fails while validatiing the schema.

Workaround: use `arrow.Null` variable.

Proper fix:
```go
var(
   Null = new(NullType)
)
```
in the code.

cc: @zeroshade 

### Component(s)

Go

**Comment by candiduslynx** [comment]
@zeroshade could you update the following lines?
https://github.com/apache/arrow/blob/1ab25b8424cde6afaadad27d0e62d802dc8ba6f0/go/arrow/datatype_null.go#L31-L32

**Comment by zeroshade** [comment]
I wonder if the better solution would be to fix `TypeEqual` so that it recognizes `new(NullType)` as equal to `arrow.Null`. 

Either way, would you be willing to file a PR with your suggestion @candiduslynx?

**Comment by candiduslynx** [comment]
Hi @zeroshade!

> I wonder if the better solution would be to fix `TypeEqual` so that it recognizes `new(NullType)` as equal to `arrow.Null`.

No, this won't actually be a good fix, as the `new(arrow.NullType)` is a valid `arrow.DataType` & it should be perfectly valid to use in the code.

> Either way, would you be willing to file a PR with your suggestion @candiduslynx?

I don't currently have a fork, so it will require me to do some extra steps.
Instead, I'd be very much keen on reviewing the easy fix, if you'd like me to.

**Comment by zeroshade** [comment]
> No, this won't actually be a good fix, as the new(arrow.NullType) is a valid arrow.DataType & it should be perfectly valid to use in the code.

The only reason I can tell that it was being seen as invalid is due to the comparison in `TypeEqual`. I'll try to find some time today or tomorrow to poke at this

**Comment by candiduslynx** [comment]
take

**Comment by candiduslynx** [comment]
@zeroshade : https://github.com/apache/arrow/pull/40802

**Comment by zeroshade** [comment]
Issue resolved by pull request 40802
https://github.com/apache/arrow/pull/40802
