### ISSUE TITLE
[Gandiva] 'ilike' function does not work

### ISSUE THREAD

**Issue by lriggs** [apache/arrow#40727]
### Describe the bug, including details regarding any error messages, version, and platform.

When you attempt to use the 'ilike' function in Gandiva you get an error:
function holder not registered for function ilike

It seems some refactoring missed adding ilike to the function holder registry. This is a regression from Arrow 14.

A simple way to see the error is to add another test case in cpp/src/gandiva/tests/utf8_test.cc for ilike (by copying the existing 'like' test).

### Component(s)

C++, C++ - Gandiva

**Comment by kou** [comment]
Oh, #38632 removed the `ilike` entry accidentally...

**Comment by kou** [comment]
Issue resolved by pull request 40728
https://github.com/apache/arrow/pull/40728
