### ISSUE TITLE
[Python] pandas compat: clean-up code in columns Index reconstruction in Table.to_pandas

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#40720]
The `pandas_compat.py` has over the years grown quite complex and a lot of pandas compatibility code, which probably can be simplified nowadays because of not supporting old pandas and Python versions anymore.

One aspect that I noticed while working on `to_pandas` was the complexity in the reconstruction of the `.columns` Index object of the resulting DataFrame. Right now that always goes through a MultiIndex (even for simple column names), which has quite some overhead of the simple case.

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 40721
https://github.com/apache/arrow/pull/40721

**Comment by corneliusroemer** [comment]
I tried to find out _what_ the supported versions of pandas/python are, but couldn't find anything. It would be great if you could point me somewhere @jorisvandenbossche.

I noticed that Pyarrow 16.1.0 seems not to be usable with pandas 1.5.3 anymore, for example (it was I think until 16 dropped). I'm getting `AttributeError: module 'pyarrow' has no attribute '__version__'` from pandas.
