### ISSUE TITLE
Dealing with no header rows when importing CSV

### ISSUE THREAD

**Issue by somethingp** [apache/arrow#4072]
So when I want to read in a csv with no header names, I can't set the parser options to header_rows=0. It throws an error, and has no way to pass in the header names within the options. It also doesn't just default to using index rows. In the code it looks like these options have been left as a "TODO." [(arrow/cpp/src/arrow/csv/reader.cc Line 139)](https://github.com/apache/arrow/blob/ce9c6e3914274dcaf7806159ea5373e0cb632727/cpp/src/arrow/csv/reader.cc)

Is there a work around to this problem (other than adding header rows to all my files). Is this already an issue on JIRA that's being dealt with? Please help!

**Comment by emkornfield** [comment]
Hi @somethingp https://issues.apache.org/jira/browse/ARROW-4912 covers this but I don't think there is anyone actively working on it (if you have time and inclination, maybe you could submit a PR?)

**Comment by emkornfield** [comment]
Going to close this for now, as I don't believe there is a workaround.

**Comment by Blake-Foust** [comment]
The only workaround I know, is 
`arrow::csv::ReadOptions::autogenerate_column_names = true;`
