### ISSUE TITLE
[Packaging] `apache.jfrog.io/artifactory/arrow/ubuntu`  likely down?

### ISSUE THREAD

**Issue by shayonj** [apache/arrow#40744]
### Describe the bug, including details regarding any error messages, version, and platform.

Seeing a bunch of these in our CI

```
Err:6 https://apache.jfrog.io/artifactory/arrow/ubuntu focal InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:8 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Reading package lists...
E: Failed to fetch https://apache.jfrog.io/artifactory/arrow/ubuntu/dists/focal/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://apache.jfrog.io/artifactory/arrow/ubuntu focal InRelease' is not signed.
```

Looks like issue as the one here (https://github.com/apache/arrow/issues/34680#issuecomment-1479045108), same time last year (~March 22 2023)

### Component(s)

Other

**Comment by assignUser** [comment]
Hey, yeah it's the same issue sadly. I have already contacted ASF INFRA and they are in contact with jfrog to get this up again asap.

**Comment by shayonj** [comment]
Thank you! Appreciate it

**Comment by xlukem** [comment]
apache.jfrog.io available again, issue can be closed

**Comment by kou** [comment]
@assignUser Based on the sidebar information at https://apache.jfrog.io/ui/packages, it seems that our free trial days has been extended by 365 days  :

![image](https://github.com/apache/arrow/assets/27350/d0bf0008-d48e-4914-a23d-eeeb78c97077)

So this may happen next year. Could you ask INFRA to make sure this doesn't happen again?

**Comment by andersk** [comment]
Has there been any progress on making sure this doesn’t happen again every March? The Artifactory page still indicates that the free trial will expire on March 22, 2025.

**Comment by kou** [comment]
@assignUser Could you ask INFRA to this?

**Comment by assignUser** [comment]
I am working on it already :) but no news to share yet.

**Comment by kou** [comment]
Thanks!
Please share updates here when any progress is happen.

**Comment by andersk** [comment]
I haven’t seen any movement on this issue, and apache.jfrog.io is still showing that the trial will expire on March 22, 2025, so here’s a reminder that that’s 30 days from today.

**Comment by amoeba** [comment]
Thanks @andersk. cc @assignUser

**Comment by assignUser** [comment]
Thanks I'm aware and pinged infra about it in December, there is an active [issue](https://issues.apache.org/jira/browse/INFRA-26324).
