### ISSUE TITLE
[Java] Enable Spotless Plugin

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40757]
### Describe the enhancement requested

Enabling [Spotless](https://github.com/diffplug/spotless) plugin for Arrow Java is an important step towards code quality. 
There was an existing effort: https://github.com/apache/arrow/pull/39713, but the PR is too large to be evaluated and a better approach would be to enable it module by module and it requires some evaluation. 

As discussed in a [previous PR](https://github.com/apache/arrow/pull/39713#issuecomment-1916829045), this task will be divided per module. 

- [x] https://github.com/apache/arrow/issues/40819
- [x] https://github.com/apache/arrow/issues/40820
- [x] https://github.com/apache/arrow/issues/40821
- [x] https://github.com/apache/arrow/issues/40822
- [x] https://github.com/apache/arrow/issues/40823
- [x] https://github.com/apache/arrow/issues/40824
- [x] https://github.com/apache/arrow/issues/40825
- [x] https://github.com/apache/arrow/issues/40826
- [x] https://github.com/apache/arrow/issues/40827
- [x] https://github.com/apache/arrow/issues/40828
- [x] https://github.com/apache/arrow/issues/40829
- [x] https://github.com/apache/arrow/issues/40830
- [x] https://github.com/apache/arrow/issues/40831
- [x] https://github.com/apache/arrow/issues/40832
- [x] https://github.com/apache/arrow/issues/41929

### Component(s)

Java

**Comment by vibhatha** [comment]
cc @laurentgo we have listed this change per module so that we can review things quite easily.

**Comment by vibhatha** [comment]
@laurentgo I am planning to do till format module, would you like to contribute the other ones?

**Comment by laurentgo** [comment]
Yes, will do

**Comment by vibhatha** [comment]
Thank you, appreciate it.

**Comment by laurentgo** [comment]
Create #42121 for the cleanup task

**Comment by vibhatha** [comment]
Thanks @laurentgo , would you like to proceed?

**Comment by laurentgo** [comment]
Yes, will do

**Comment by laurentgo** [comment]
@vibhatha is there anything left?

**Comment by vibhatha** [comment]
I think now we are good. Probably we need to check the usability down the road and improve as needed. 

Thanks a lot for pushing this to the finish line.
