### ISSUE TITLE
[C++] CMake error for ninja-debug preset

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#40751]
### Describe the bug, including details regarding any error messages, version, and platform.

I'm building arrow cpp using CMake preset `ninja-debug`, with system provided protobuf:
`cmake ../arrow/cpp --preset=ninja-debug`

And got error message:
```
CMake Error at cmake_modules/ThirdpartyToolchain.cmake:1823 (message):
  ARROW_WITH_PROTOBUF must be propagated in the build tooling installation.
  Please extend the mappings of ARROW_PROTOBUF_ARROW_CMAKE_PACKAGE_NAME and
  ARROW_PROTOBUF_ARROW_PC_PACKAGE_NAME for newly introduced dependencies on
  protobuf.
Call Stack (most recent call first):
  CMakeLists.txt:543 (include)
```

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 40753
https://github.com/apache/arrow/pull/40753
