### ISSUE TITLE
[Java] Cannot create StructVector with dense-union child

### ISSUE THREAD

**Issue by jarohen** [apache/arrow#40773]
### Describe the bug, including details regarding any error messages, version, and platform.

I cannot create a StructVector with a dense-union child - it fails with the following stack trace:

```
java.lang.UnsupportedOperationException: Unknown type: DENSEUNION
	at org.apache.arrow.vector.complex.impl.NullableStructWriter.<init>(NullableStructWriter.java:258)
	at org.apache.arrow.vector.complex.StructVector.<init>(StructVector.java:69)
	at xtdb.vector.StructVectorWriterTest.struct with DUV child(StructVectorWriterTest.kt:101)
```

Test code is essentially:

```java
Field child = new Field("child", FieldType.notNullable(new ArrowType.Union(UnionMode.Dense, null)), emptyList());
Field struct = new Field("foo", FieldType.notNullable(ArrowType.Struct.INSTANCE), List.of(child));

try(RootAllocator allocator = new RootAllocator();
   StructVector structVec = new StructVector(struct, allocator, null)) {
            
   System.out.println("working!");
}
```

I suspect it's a case of adding `DENSEUNION` to the `switch` in the `NullableStructWriter` constructor, with a similar implementation to the sparse `UNION`?

Cheers,

James

### Component(s)

Java

**Comment by danepitkin** [comment]
Hey @jarohen , thanks for catching this. Would you be interested in contributing the fix to arrow? It should make it in the next release if we get it merged within the next two weeks.

**Comment by jarohen** [comment]
Hey @danepitkin - np, PR attached :slightly_smiling_face:

**Comment by danepitkin** [comment]
Thank you!! That was fast 😁 It's very much appreciated

**Comment by lidavidm** [comment]
Issue resolved by pull request 40809
https://github.com/apache/arrow/pull/40809
