### ISSUE TITLE
Artifactory repositories unavailable

### ISSUE THREAD

**Issue by adampinky85** [apache/arrow#40770]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi Team,

The Apache Arrow jfrog artifactory repository does not appear to be available currently. 

I've tried to access them from Ubuntu, Amazon Linux 2, and Amazon Linux 2023 without success. Retrieving the Ubuntu / Debian package with wget returns javascript code with the message _"MyJFrog doesn't work properly without JavaScript enabled. Please enable it to continue"._

https://arrow.apache.org/install/

```
curl https://apache.jfrog.io/artifactory/arrow/ubuntu/apache-arrow-apt-source-latest-jammy.deb
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### Component(s)

C++

**Comment by eyenx** [comment]
![](https://imgs.search.brave.com/O9VOkGjEuI__IcrVhZTZ4puN17URMoF9-Y7EBqBpcFo/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YTEudGVub3IuY29t/L20vN3VKWEVIczdP/dVVBQUFBZC9kaW5u/ZXItZm9yLXNhbWUu/Z2lm.gif) 

https://github.com/apache/arrow/issues/34680

**Comment by digoal** [comment]
`dpkg-deb: error: './apache-arrow-apt-source-latest-bullseye.deb' is not a Debian format archive`

**Comment by yannickgloster** [comment]
Reported on Friday here: #40744

Still not fixed unfortunately

**Comment by assignUser** [comment]
It's back, sorry for the inconvenience we are looking at alternatives to avoid such disruptions in the future.

**Comment by adampinky85** [comment]
Great thanks all!
