### ISSUE TITLE
[Packaging] Boost fallback URLs fail at sha256 verification

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#40782]
### Describe the bug, including details regarding any error messages, version, and platform.

CMake will configure 3 URLs for Boost:

https://github.com/apache/arrow/blob/3095344d68af3e4353c9ce098d73fe6768bcb626/cpp/cmake_modules/ThirdpartyToolchain.cmake#L606-L615

The first URL is a trimmed version of boost that is custom made by arrow. The following two URLs point to the original boost library with a different download size and sha256 hash. If a fallback URL is used, it will fail here:

https://github.com/apache/arrow/blob/ab6a5fd610cbd10cbded6ef0f235ad54b9273496/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1125

The CMake function `externalproject_add` does not allow for multiple hashes to be configured, so we should either add a second call to `externalproject_add` when falling back or delete the fallback URLs.

### Component(s)

Packaging

**Comment by kou** [comment]
Can we close this as a duplicated issue of #40756?

**Comment by danepitkin** [comment]
Yes, thanks @kou . It's a dupe of https://github.com/apache/arrow/issues/40756.
