### ISSUE TITLE
[Doc][Format] Implementation status page should list canonical extension types

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#40799]
### Describe the enhancement requested

Canonical extension types should be listed as a new subsection at the end of the https://arrow.apache.org/docs/dev/status.html#data-types section.

### Component(s)

Documentation, Format

**Comment by pitrou** [comment]
cc @rok @jorisvandenbossche

**Comment by rok** [comment]
Issue resolved by pull request 41053
https://github.com/apache/arrow/pull/41053
