### ISSUE TITLE
[R] Error: This build of the arrow package does not support Datasets

### ISSUE THREAD

**Issue by thomasstockton** [apache/arrow#40804]
### Describe the bug, including details regarding any error messages, version, and platform.

Under MacOS Sonoma 14.4

R
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid  

Package: arrow
Title: Integration to 'Apache' 'Arrow'
Version: 15.0.1

I get 
Error: This build of the arrow package does not support Datasets
on
`> arrow::open_dataset("./hive",format="csv")
`
This worked fine on 14.0.2.1

Thanks

Tom

### Component(s)

R

**Comment by assignUser** [comment]
This is a known issue please see https://github.com/apache/arrow/issues/40667#issuecomment-2007942987 for details and workarounds. Sorry for the inconvenience.
