### ISSUE TITLE
Coercing column types in schemas

### ISSUE THREAD

**Issue by dmadeka** [apache/arrow#4080]
When Im reading a collection of files (say `read_csv` into tables) and then concatenating them - is there a way for me to specify that double and int types can be merged. Currently, pyarrow throws an error on `concat_tables` saying the schemas dont match -- so I coerce each one to pandas, merge it back and then convert the dataframe back to a table

**Comment by wesm** [comment]
There isn't currently. You can write down the schema you want and use `table.cast(schema, safe=False)` for each table to do things in Arrow-land instead of converting to pandas. If you'd like to propose some improvements to the API for this use case please do open a JIRA issue
