### ISSUE TITLE
[C++] Thirdparty: Do we need bump zstd to 1.5.6?

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#40814]
### Describe the enhancement requested

https://github.com/facebook/zstd/releases/tag/v1.5.6

Zstd releases 1.5.6 . It doesn't include lots of performance improvement. So I wonder should we upgrade it?

### Component(s)

C++

**Comment by mapleFU** [comment]
cc @kou @pitrou @felipecrv

**Comment by kou** [comment]
In general, yes. Incremental upgrades are easier than one big upgrade.

**Comment by pitrou** [comment]
@ericsun2 Can you open a new issue for that and categorize it for the Go component? Thank you!

**Comment by kou** [comment]
Issue resolved by pull request 40837
https://github.com/apache/arrow/pull/40837
