### ISSUE TITLE
[Java] Adding Spotless to BOM module

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40821]
### Describe the enhancement requested

The main issue discussing the inclusion of Spotless plugin is discussed [here](https://github.com/apache/arrow/issues/40757). 

### Component(s)

Java

**Comment by laurentgo** [comment]
There's no code for this one and pom.xml has already being taken care of, so this one may be closed I guess?

**Comment by vibhatha** [comment]
Yeah let's do that. Initially this was also left with pom work. But we had a separate PR for that.
