### ISSUE TITLE
[Java] Adding Spotless to Format module

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40826]
### Describe the enhancement requested

The main issue discussing the inclusion of Spotless plugin is discussed [here](https://github.com/apache/arrow/issues/40757). 

### Component(s)

Java

**Comment by vibhatha** [comment]
Since this content is autogenerated we don't need to format this either. 
But in a follow up PR, we should add a config to disable running the formatter in this module. So keeping this until we make a final PR to clean things up.

**Comment by laurentgo** [comment]
This content may have been autogenerated but it is not the case anymore (it also doesn't have the `@Generated` annotation). I'm not sure we need to carve an exception except if we would want to diff with a new version of the generated code in the future? (but seems unlikely)

**Comment by laurentgo** [comment]
This was addressed by #43019. Maybe this issue can be closed?
