### ISSUE TITLE
COBOL bindings

### ISSUE THREAD

**Issue by max-sixty** [apache/arrow#4084]
We'd like to move our AI pipelines written in COBOL to use Arrow - are there plans to add COBOL bindings?

There a recent resurgence in COBOL's use, particularly around sophisticated statistical techniques. [Here's](https://medium.com/@oceankidbilly/python-vs-r-vs-cobol-which-is-best-for-data-science-7b2979c6a000) an article showing its primacy over both python and R.

Thanks for everyone's contributions, every day of the year!

**Comment by emkornfield** [comment]
I think the priorities at this point are ALGOL and Basic, but maybe you
could contribute a patch?

**Comment by andygrove** [comment]
I think this discussion is very timely. Thanks for raising it.
