### ISSUE TITLE
[Docs][C++][Python] Add initial documentation for RecordBatch::Tensor conversion

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#40841]
### Describe the enhancement requested

The work on the conversion from `Table`/`RecordBatch` to `Tensor` is progressing and we have to make sure to add information to the documentation. This should be an initial work to find a good place in the documentation with the basic information. Additional examples and features (row-major) can be documented later.

### Component(s)

Documentation

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 40842
https://github.com/apache/arrow/pull/40842
