### ISSUE TITLE
[Java] Incomplete shading of the Arrow FlightSQL JDBC driver

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#40878]
### Describe the bug, including details regarding any error messages, version, and platform.

The Arrow FlightSQL JDBC driver is not shaded properly and may cause conflicts with other dependencies:
* the pom.xml file published on Maven Central declares several runtime dependencies although the driver is supposed to be self contained
* some of the dependencies are not relocated properly and may conflict with other packages

Currently the driver contains the following non-relocated files:
* proto source files
* javax annotations
* bytebuddy classes
* codegen source files

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 40879
https://github.com/apache/arrow/pull/40879
