### ISSUE TITLE
[JS] Dates should be stored in TimestampMillisecond

### ISSUE THREAD

**Issue by domoritz** [apache/arrow#40891]
### Describe the bug, including details regarding any error messages, version, and platform.

See https://github.com/duckdb/duckdb-wasm/issues/1231

### Component(s)

JavaScript

**Comment by amoeba** [comment]
Hi @domoritz, would you consider this change a breaking change under [our definition](https://arrow.apache.org/docs/developers/reviewing.html#labelling)?

**Comment by domoritz** [comment]
Yes-ish. The default behavior of how `Date`s are handled changes but I'd argue the previous behavior was wrong as it lost precision.
