### ISSUE TITLE
[Java][FlightSQL] JDBC Driver does not shade slf4j-api

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#40907]
### Describe the bug, including details regarding any error messages, version, and platform.

The Arrow FlightSQL JDBC driver does not shade slf4j-api. Arrow uses Slf4j 2.x api which is backward compatible from an API point of view with Slf4j 1.x (the opposite is not true) but the backend discovery mechanism is different.

When the driver is used within an application using Slf4j 1.x, it may cause the application logging backend to stop working. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 40908
https://github.com/apache/arrow/pull/40908
