### ISSUE TITLE
[C#] Add support for boolean columns

### ISSUE THREAD

**Issue by johnnyg** [apache/arrow#40928]
### Describe the enhancement requested

Currently the C# library can't decode boolean columns; it would be great if it could to put it on par with the other language bindings.

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Can you clarify what you mean by this? There is a BooleanArray and there are tests which validate that it interoperates with other implementations.

**Comment by johnnyg** [comment]
Hi @CurtHagenlocher I was getting an exception when trying to read arrow data where one of the columns is an array of bools. I didn't see booleans listed anywhere on the C# readme so figured it must have been not implemented however if it is meant to be supported then perhaps it's a bug instead. I'll see if I can create a simple test to reproduce for you.

**Comment by johnnyg** [comment]
Actually it looks like this may be a bug in the [MS DataFrame library](https://www.nuget.org/packages/Microsoft.Data.Analysis/) we are using to read the values, e.g.
```csharp
public void DataFrameDecodeBooleans()
{
    BooleanArray boolArray = new BooleanArray.Builder().AppendNull().Append(false).Append(true).Build();
    Field boolField = new Field("col", BooleanType.Default, true);
    Schema schema = new Schema(new[] { boolField }, null);
    RecordBatch batch = new RecordBatch(schema, new IArrowArray[] { boolArray }, boolArray.Length);
    DataFrame df = DataFrame.FromArrowRecordBatch(batch);
    DataFrameColumn boolCol = df["col"];
    Assert.Equal(boolArray.Length, boolCol.Length);
    for (int row = 0; row < boolArray.Length; row++)
    {
        Assert.Equal(boolArray.GetValue(row), boolCol[row]);
    }
}
```
fails.
I'll double check that our actual data looks correct when using the direct methods and not via the Dataframe and report back.

**Comment by CurtHagenlocher** [comment]
Yes I can see that library is broken. It assumes that an Arrow bool is 1 byte long when it's actually one bit long.

**Comment by johnnyg** [comment]
Yeah that does seem broken. Have verified that our data is being read correctly in C# without that library.
I'll close this issue however it would be good to update the README to explicitly mention that you support boolean arrays.
