### ISSUE TITLE
[Python] pyarrow data type error cause lot of dependent project crash

### ISSUE THREAD

**Issue by guocity** [apache/arrow#40926]
### Describe the bug, including details regarding any error messages, version, and platform.

several project depends on pyarrow crash on type conversation

- Data Wrangler
- Polars

df = pl.DataFrame(pd)

ArrowInvalid: Could not convert '230' with type str: tried to convert to double

### Component(s)

Python

**Comment by AlenkaF** [comment]
Could you share a concrete reproducible example so we can see where the issue might be?

**Comment by guocity** [comment]
I have this dataset, when the string is mixed with float datatype, pandas will read as mixed datatype but not pyarrow,
therefore it breaks Data wrangler, and ability convert pd to polars, or export as parquet 
https://drive.google.com/file/d/1uxKSIqZ7IUEQ1Qp_LgB2qSAZDQEKteJl/view?usp=sharing

**Comment by AlenkaF** [comment]
Yes, Arrow array (or column) has one data type by [definition](https://arrow.apache.org/docs/dev/format/Columnar.html#terminology). Defining the column (with mixed float and string) as a string should solve the problem?

**Comment by guocity** [comment]
thanks,

**Comment by AlenkaF** [comment]
In case you have any follow-up questions, do not hesitate to re-open the issue.
