### ISSUE TITLE
[Java] Implement a strategy to return variable width buffer count for StringView in TypeLayout

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40935]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340),  we are only returning a value considering the inline Strings and discard long Strings. This functionality needs to be improved with corresponding test cases. 

### Component(s)

Java

**Comment by vibhatha** [comment]
## Usage of `TypeLayout.getTypeBufferCount`

1. `VectorUnloader` → `appendNodes` : used to validate the field buffer size against the defined size in the layout
2. `ValidateVectorBufferVisitor` → `validateVectorComon` → (this method is used to validate most vector types. Where it uses the field`s buffer size against the layouts defined buffer count. 
3. `StructVectorLoader` → `loadBuffers` used to get the number of buffers to give the initial capacity to the list
4. `StructVectorUnloader` → `appendNodes` : used to validate the field buffer size against the defined size in the layout
5. `VectorLoader` → `loadBuffers` : used to get the number of buffers to give the initial capacity to the list
6. `ValidateVectorBufferVisitor` → `validateVectorCommon` : used to validate the field buffer size against the defined size in the layout

The value set for the visitor here is a fixed value (number of buffers), but for StringView, the number of buffers are 2 + K and we can determine the value of K only by getting the `vector.dataBuffers.size()` which is not accessible in the visitor here. 

I can think of three ways of solving this. 

### Method 1

Check whether the number of buffers are `2 <=` such that setting the `getTypeBufferCount` to 2 and do the validation. And in each scenario where we do the validation. 

And when a list is formulated by iterating through buffers, we could do it until the iterator gives null and populate the list only if the type is `Utf8View` or `BinaryView`. 

### Method 2

We state validation is not supported, but update the list until iterator gives null. 

### Method 3

We write a special case for StringView such that we get `FieldVector` and cast it to `BaseVariableWidthViewVector` and get the `dataBuffers` and get the size. And then we can do the validation and initialize the list capacity.

**Comment by vibhatha** [comment]
cc @lidavidm

**Comment by lidavidm** [comment]
Either:
- deprecate TypeLayout and replace it with a version that also requires the vector/RecordBatch instance
- update uses of TypeLayout depending on the individual context, since we need to handle variadicBufferCounts now anyways

**Comment by vibhatha** [comment]
> deprecate TypeLayout and replace it with a version that also requires the vector/RecordBatch instance

I feel like this would be better for the longer term.

**Comment by vibhatha** [comment]
Closed by a unified task https://github.com/apache/arrow/pull/41732
