### ISSUE TITLE
[Java] Implement a function to retrieve reference buffers in StringView 

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40930]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340), `public ArrowBuf[] getBuffers(boolean clear)` function only returns the `offset, validity and value` buffers. But for recreating views entirely and support related features it would be better to introduce additional function or improve the existing function to return the view buffers. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41796
https://github.com/apache/arrow/pull/41796
