### ISSUE TITLE
[Java] Implement Holder-based functions in `ViewVarBinaryVector`

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40936]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340),  holders are not supported. The `NullableViewVarBinaryHolder` and `ViewVarBinaryHolder` must be implemented. 

### Component(s)

Java

**Comment by ViggoC** [comment]
@lidavidm This issue can be closed too.

**Comment by vibhatha** [comment]
Issue resolved by https://github.com/apache/arrow/pull/44187
