### ISSUE TITLE
[Java] Enhance the `copyFrom*` functionality in StringView

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40933]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340), doesn't support a fully copy functionality including the view buffers, it only supports the inline views. This functionality needs to be extended to support views. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41752
https://github.com/apache/arrow/pull/41752
