### ISSUE TITLE
[Java] Implement Holder-based functions for `ViewVarCharVector` 

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40937]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340),  holders are not supported. The `NullableViewVarCharHolder` and `ViewVarCharHolder` must be implemented. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 44187
https://github.com/apache/arrow/pull/44187
