### ISSUE TITLE
[Java] Implement `RangeEqualsVisitor` for StringView 

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40943]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340), the `RangeEqualsVisitor` functionality is not included. This must be implemented as a follow up PR. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41636
https://github.com/apache/arrow/pull/41636
