### ISSUE TITLE
[Java] Implement `TypeEqualsVisitor` for StringView

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40944]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340), the `TypeEqualsVisitor` functionality is not included. This must be implemented as a follow up PR. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41606
https://github.com/apache/arrow/pull/41606
