### ISSUE TITLE
[Java] Implement C Data Interface for StringView

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#40942]
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340), C Data interface has not been supported. It must be included in a follow up PR. 

### Component(s)

Java

**Comment by urvishdesai** [comment]
Hi, @vibhatha I have been following this PR. Is this task on C ABI support being worked upon currently?

**Comment by vibhatha** [comment]
@urvishdesai yes, this one is planned to be done sooner.

**Comment by vibhatha** [comment]
@urvishdesai 

I will be picking up this task earlier next week. But if you're interested in working, please go ahead I can help out with reviews.

**Comment by vibhatha** [comment]
@urvishdesai I started looking into the implementation details. It requires some other helper components. I am going to start working on those components. Once I complete that I will update the status here.

**Comment by urvishdesai** [comment]
@vibhatha Thanks a lot! I think you could work on this faster but I can help with the reviews. Let me know if it will take longer or more work. If so, I can help out!

**Comment by vibhatha** [comment]
That sounds like a plan @urvishdesai 
I will update here.

**Comment by lidavidm** [comment]
Issue resolved by pull request 41967
https://github.com/apache/arrow/pull/41967
