### ISSUE TITLE
[Java][FlightSQL] Cleanup flightsql jdbc driver dependencies

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#40952]
### Describe the bug, including details regarding any error messages, version, and platform.

The module `flight-sql-jdbc-driver` declares explicitly multiple dependencies which would be transitively captured if the module would only depend on `flight-sql-driver-core`. This can cause the module to declare dependencies which are not used anymore, or use a different version compared to what was declared in other modules. Indeed, the driver includes `joda` dependency which is not used in the rest of the code anymore.

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 40953
https://github.com/apache/arrow/pull/40953
