### ISSUE TITLE
[C++][Gandiva] Function "LIKE" does not always work correctly when the string contains \n.

### ISSUE THREAD

**Issue by xxlaykxx** [apache/arrow#40968]
### Describe the enhancement requested

Gandiva function "LIKE" does not always work correctly when the string contains \n.
String value:
```text
[function_name: "Space1.protect"
args: "passenger_count"
column_name: "passenger_count"
]
```
Pattern **'%Space1%'** or **'%Space1.%'** - not match.
Need to set **set_dot_nl(true);** to RE2::Options to handle this case.

### Component(s)

C++ - Gandiva

**Comment by kou** [comment]
Issue resolved by pull request 40970
https://github.com/apache/arrow/pull/40970
