### ISSUE TITLE
[Packaging] Outdated Debian keyring

### ISSUE THREAD

**Issue by tseeker** [apache/arrow#40967]
### Describe the bug, including details regarding any error messages, version, and platform.

The Debian GPG keyring found at https://apache.jfrog.io/artifactory/arrow/debian/apache-arrow-keyring.gpg is outdated. Using it results in updates failing with `NO_PUBKEY 9CBA4EF977CA20B8`.

### Component(s)

Packaging

**Comment by kou** [comment]
Could you use `apache-arrow-apt-source-latest-*.deb` at https://apache.jfrog.io/ui/native/arrow/debian/ instead?
It's described in https://arrow.apache.org/install/ ?

**Comment by tseeker** [comment]
Thank you for your reply.

I _could_ use the `-source-` package, in the sense that I could take the package, extract it manually, and use the keyring that's inside. Per policy, however, the contents of `/etc/apt/sources.list` and `/etc/apt/sources.list.d` are enforced on the system I'm installing this on, so half the point of the `-source-` package is lost on me, which is why I didn't use it.

**Comment by kou** [comment]
You can use https://downloads.apache.org/arrow/KEYS instead.

```bash
curl https://downloads.apache.org/arrow/KEYS | gpg --no-default-keyring --keyring /tmp/apache-arrow-apt-source.gpg --import -
```

**Comment by tseeker** [comment]
Thank you!

I see now that on the install page they are mentioned in the "Source" section, which is why I didn't pay attention to them.
