### ISSUE TITLE
[C++] supports UnsafeAppend{Values|Nulls} in ::arrow::BooleanBuilder 

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#40978]
### Describe the enhancement requested

Currently, we only support:
1. `UnsafeAppend{Value|Null}` for single value
2. `Append{Values|Nulls}` for multiple value

We can support UnsafeAppend{Values|Nulls} in ::arrow::BooleanBuilder 

### Component(s)

C++

**Comment by pitrou** [comment]
This will be necessary to avoid reserving too much in GH-40876.

**Comment by mapleFU** [comment]
benchmark shows it doesn't improve a lot, close as not planned first
