### ISSUE TITLE
Seek page in column chunk of Parquet

### ISSUE THREAD

**Issue by Luosuu** [apache/arrow#40981]
### Describe the usage question you have. Please include as many useful details as  possible.

Hi,

With [PageIndex](https://github.com/apache/parquet-format/blob/master/PageIndex.md), I think it should be possible to seek page within a column chunk when reading Parquet?

If so, how should I do this? (I think PyArrow does not support it yet, but if this is possible with other languages it is also fine.)
If not supported yet, what would be the appropriate way to implement page seeking (no matter with/without `PageIndex`).

Thank you very much for your attention to this!

### Component(s)

Parquet

**Comment by mapleFU** [comment]
Hmmm currently "page index" can locate to the position of a page. But this is not enough for direct read the rows in the page. Maybe arrow-rs or Impala supports that.

**Comment by Luosuu** [comment]
@mapleFU Thank you for reply!

I checked `arrow-rs` and it seems that it can read one page by `get_bytes` method of `ChunkReader` trait:

```rust
impl ChunkReader for File {
    type T = BufReader<File>;

    fn get_read(&self, start: u64) -> Result<Self::T> {
        let mut reader = self.try_clone()?;
        reader.seek(SeekFrom::Start(start))?;
        Ok(BufReader::new(self.try_clone()?))
    }

    fn get_bytes(&self, start: u64, length: usize) -> Result<Bytes> {
        let mut buffer = Vec::with_capacity(length);
        let mut reader = self.try_clone()?;
        reader.seek(SeekFrom::Start(start))?;
        let read = reader.take(length as _).read_to_end(&mut buffer)?;

        if read != length {
            return Err(eof_err!(
                "Expected to read {} bytes, read only {}",
                length,
                read
            ));
        }
        Ok(buffer.into())
    }
}
```


in my understanding, if we have the position of a page (and also the length too), can we directly decode that page?
Just like this `get_bytes` method which takes a start and length then it seek from the start with length.

**Comment by mapleFU** [comment]
Sure, we can, however thats the simplest case
1. Pages in different columns might not "aligned", for example, column1 may split page with 5000rows, column2 split with 3000 rows. Different row stride making it a bit tricky to resemble the data
2. Considering the nested take, page might be leaf page which is just a child structure

https://docs.google.com/document/d/1SeVcYudu6uD9rb9zRAnlLGgdauutaNZlAaS0gVzjkgM/edit we proposed an api for this but code is not finished yet. arrow-rs might have it implemented

**Comment by Luosuu** [comment]
Thanks so much for providing such helpful materials and I think I understand this better now.

The first point seems okay if I only care about a specific column (in this case I think I don't need to resemble the entire row structure since I don't care about other columns).

For the second point, if I understand correctly, you are mentioning https://arrow.apache.org/blog/2022/10/08/arrow-parquet-encoding-part-2/

so for this Parquet schema:

```
message schema {
  optional int32 a;
  required group b {
    optional int32 b1;
    required int32 b2;
  }
  optional group c {
    required int32 c1;
  }
  optional group d {
    required int32 d1;
    optional int32 d2;
  }
}
```

"a", "b", "c", and "d" are stored in different pages. Do I understand this right?
Thank you very much again.

**Comment by mapleFU** [comment]
> "a", "b", "c", and "d" are stored in different pages

Yes, and row would not cross page if page index enabled.

**Comment by Luosuu** [comment]
I see. If I understand correctly, you mean when page index enabled, 
for example:

```json
{              # <-- First record
  "a": 1,      # <-- the top level fields are a, b, c, and d
  "b": {       # <-- b is always provided (not nullable)
    "b1": 1,   # <-- b1 and b2 are "nested" fields of "b"
    "b2": 3    # <-- b2 is always provided (not nullable)
   },
  "d": {
   "d1":  1    # <-- d1 is a "nested" field of "d"
  }
}
```

when we have page index enabled: they are stored in one page;
when we do NOT have page index: "a", "b", "c", and "d" are stored in different pages.

Thank you so much again. I am trying my best to understand now.

**Comment by mapleFU** [comment]
Aha, no. Whether we have page index: "a", "b", "c", and "d" are stored in different pages. There are three levels:
* File ( a whole parquet file with same schema containing zero or multiple rowgroups)
* RowGroup: some "rows" with schema in file.
* Column Chunk: a "leaf" column in one row-group. Each Column Chunk. In your json there're 4 column chunks
* Page: some values in Column Chunk. It should have specific column. When Page Index is not enabled and the record is nested, some legacy file might have "cross page row", e.g.: "list: [[1, 1, 1], [1]]" stores "[1, 1" and "1]" in different page. But when page index enabled, it would not.

**Comment by Luosuu** [comment]
Thank you so much. I think I understand now. I will look into `arrow-rs` for my usage then.
