### ISSUE TITLE
[R] incompatibility with M2 and M3 processors in macOS

### ISSUE THREAD

**Issue by rafapereirabr** [apache/arrow#40991]
### Describe the bug, including details regarding any error messages, version, and platform.

It seems there is some incompatibility between the current version of the {arrow} package in R and the M2 and M3 processors in macOS. Two colleagues who have laptops with those processors have found the following ERROR when trying to run the code below:

```
data("mtcars")
head(mtcars)

arrow::write_parquet(mtcars, 'mtcars.parquet')

df <- arrow::read_parquet('mtcars.parquet', as_data_frame = F)
head(df)
```
> Error in parquet__WriterProperties_Builder_create() : 
  Cannot call parquet__WriterProperties_Builder_create(). See https://arrow.apache.org/docs/r/articles/install.html for help installing Arrow C++ libraries

observation 1. This error does not occur in macOS or pcs with Intel processors.
observation 2. I develop the [{censobr}](https://ipeagit.github.io/censobr/) package, which imports {arrow}, and I also noticed that the package passes all CMD Checks in all operational systems, except in macOS. See the [latest cmd chek here](https://github.com/ipeaGIT/censobr/actions/runs/8461114442).

### Component(s)

R

**Comment by pachecotaina** [comment]
I was one of the colleagues experimenting trouble with M3.

thank you so much @amoeba, the new version from r-universe installs fine for me!!

**Comment by emprestige** [comment]
I was having a similar issue and could not resolve it until coming across this thread and installing from r-universe! Thank you so much!!

**Comment by amoeba** [comment]
I'm going to leave this open for visibility until #40667 (and the underlying issue) is resolved. Thanks for confirming the workarounds all.

**Comment by rafapereirabr** [comment]
Great. Thanks for all the work on {arrow} and for the quick support here!

**Comment by jonkeane** [comment]
Issue resolved by pull request 41019
https://github.com/apache/arrow/pull/41019
