### ISSUE TITLE
[C++][Parquet] Supports DecodeArrow with nulls in RleBooleanDecoder

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#40994]
### Describe the enhancement requested

RleBooleanDecoder currently don't supports DecodeArrow, so here as a subtask of https://github.com/apache/arrow/issues/39227 we need supports it.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 40995
https://github.com/apache/arrow/pull/40995
