### ISSUE TITLE
[C++] Lost are_cols_in_encoding_order condition in NullUpdateColumnToRowImp_avx2

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#40997]
### Describe the bug, including details regarding any error messages, version, and platform.

Recently, we find that the compare internal's avx2 function `NullUpdateColumnToRowImp_avx2` lost the `are_cols_in_encoding_order` check when get `null_bit_id`. It may cause grouper's compare result wrong(are_cols_in_encoding_order = true in grouper).

avx2:
https://github.com/apache/arrow/blob/36ed0328b43ca39533e58a889f8e091d1f1ca7dc/cpp/src/arrow/compute/row/compare_internal_avx2.cc#L47

non-avx2:
https://github.com/apache/arrow/blob/36ed0328b43ca39533e58a889f8e091d1f1ca7dc/cpp/src/arrow/compute/row/compare_internal.cc#L53-L54

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 40998
https://github.com/apache/arrow/pull/40998
