### ISSUE TITLE
[CI][Release] Verification jobs are failing due to curl failure

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#41007]
### Describe the bug, including details regarding any error messages, version, and platform.

Almost all verification jobs have failed with:

```
 Verifying official Arrow release candidate 1{VERIFY_VERSION}-rc1{VERIFY_RC}
/tmp/arrow-1{VERIFY_VERSION}.3Hi7b /
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: key 97D7E8647AE7E47B: 2 signatures not checked due to missing keys
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 97D7E8647AE7E47B: public key "Julien Le Dem <julien@ledem.net>" imported
gpg: key 02DABFDF1679D194: public key "Julien Le Dem <julien@ledem.net>" imported
gpg: key 29D94E228CAAD602: public key "Uwe L. Korn <uwe@apache.org>" imported
gpg: key F105883A1735623D: public key "William Wesley McKinney (CODE SIGNING KEY) <wesm@apache.org>" imported
gpg: key 91D18FCF079F8007: 38 signatures not checked due to missing keys
gpg: key 91D18FCF079F8007: public key "Kouhei Sutou <kou@cozmixng.org>" imported
gpg: key 9F453D0CC3E4F6BA: public key "Charles Phillip Cloud <cpcloud@gmail.com>" imported
gpg: key 769BDC2129C2658C: public key "keybase.io/pitrou <pitrou@keybase.io>" imported
gpg: key 25BCCA5220D84079: public key "Krisztian Szucs (apache) <szucs.krisztian@gmail.com>" imported
gpg: key 755E743692EA1D85: public key "Micah Kornfield (Apache Arrow Code Signing Key) <emkornfield@gmail.com>" imported
gpg: key 0801999AF78748E8: public key "Jorge C. Leitao <jorgecarleitao@gmail.com>" imported
gpg: key 45127976E1E825D4: public key "Andrew A Lamb (https://github.com/alamb) <andrew@nerdnetworks.org>" imported
gpg: key CA1AB41406F9DBAD: public key "Qingping Hou (CODE SIGNING KEY) <houqp@apache.org>" imported
gpg: key 000488D7717D3FB2: public key "Neville Dipale <nevime@apache.org>" imported
gpg: key 0B8A854E87467E2C: public key "Andy Grove <agrove@apache.org>" imported
gpg: key 9CBA4EF977CA20B8: public key "David Li (CODE SIGNING KEY) <lidavidm@apache.org>" imported
gpg: key 03F0D5EA3790810C: public key "Raphael Jaen Taylor-Davies <r.taylordavies@googlemail.com>" imported
gpg: key 275C532289DD0F4A: public key "Ra�l Cumplido Dom�nguez (CODE SIGNING KEY) <raulcd@apache.org>" imported
gpg: key E05F29F0CD2679CC: public key "Ben Baumgold (CODE SIGNING KEY) <ben@baumgold.com>" imported
gpg: Total number processed: 18
gpg:               imported: 18
gpg: no ultimately trusted keys found
curl: (22) The requested URL returned error: 404 Not Found
```

[verify-rc-source-cpp-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960508/job/23392662415)
[verify-rc-source-cpp-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960732/job/23392663533)
[verify-rc-source-cpp-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538961031/job/23392665065)
[verify-rc-source-cpp-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960752/job/23392663386)
[verify-rc-source-csharp-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538959994/job/23392660464)
[verify-rc-source-csharp-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960954/job/23392664968)
[verify-rc-source-csharp-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960900/job/23392664379)
[verify-rc-source-csharp-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960439/job/23392662182)
[verify-rc-source-go-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960922/job/23392664438)
[verify-rc-source-go-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960445/job/23392662212)
[verify-rc-source-go-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960198/job/23392661382)
[verify-rc-source-go-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960175/job/23392661083)
[verify-rc-source-integration-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960277/job/23392661825)
[verify-rc-source-integration-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960929/job/23392664754)
[verify-rc-source-integration-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960396/job/23392661817)
[verify-rc-source-integration-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538961018/job/23392665164)
[verify-rc-source-java-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960767/job/23392663633)
[verify-rc-source-java-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960920/job/23392664454)
[verify-rc-source-java-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960212/job/23392661397)
[verify-rc-source-java-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538959996/job/23392660460)
[verify-rc-source-js-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960139/job/23392660975)
[verify-rc-source-js-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960598/job/23392662681)
[verify-rc-source-js-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960098/job/23392660917)
[verify-rc-source-js-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960145/job/23392660963)
[verify-rc-source-python-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960797/job/23392664059)
[verify-rc-source-python-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960742/job/23392663312)
[verify-rc-source-python-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960648/job/23392662826)
[verify-rc-source-python-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960830/job/23392664108)
[verify-rc-source-ruby-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960699/job/23392663269)
[verify-rc-source-ruby-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960680/job/23392663143)
[verify-rc-source-ruby-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960546/job/23392662498)
[verify-rc-source-ruby-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/8538960298/job/23392661796)

### Component(s)

Continuous Integration, Release

**Comment by kou** [comment]
It seems that `${VERIFY_VERSION}` and `${VERIFY_RC}` aren't expanded as we expect.
It may be related to #40949 .

**Comment by kou** [comment]
Issue resolved by pull request 41026
https://github.com/apache/arrow/pull/41026
