### ISSUE TITLE
[Doc] "Show source" links don't work

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#41013]
### Describe the bug, including details regarding any error messages, version, and platform.

On https://arrow.apache.org/docs/format/Integration.html, the "show source" link on the right leads me to a 404.

### Component(s)

Documentation

**Comment by AlenkaF** [comment]
There is already an issue about this that will land in 16.0.0: https://github.com/apache/arrow/issues/39291

**Comment by pitrou** [comment]
Ah, cool, thank you!
