### ISSUE TITLE
[C++] Add a benchmark for grouper for preventing performance regression

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#41035]
### Describe the enhancement requested

Enhancement comes from the https://github.com/apache/arrow/pull/40998#issuecomment-2039204161.

We find  it's a big performance improvement for grouper to resort columns  in rowtable:
https://github.com/apache/arrow/blob/83359d6958273be534f376f40976196c14675c8b/cpp/src/arrow/compute/row/row_internal.cc#L87-L88

In order to prevent performance regression, we should add a benchmark for grouper.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 41036
https://github.com/apache/arrow/pull/41036
