### ISSUE TITLE
pyarrow.parquet.read_table raises non-file path error when given a windows path to a directory

### ISSUE THREAD

**Issue by IlyaOrson** [apache/arrow#4104]
I think this might be a small bug with the read_table interface when used to load a directory full of parquets in Windows. It works just fine if I use directly a ParquetDataset object to read the table represented by the directory, or if I use `read_table` in a linux terminal.

Apparently the problem comes from the `_make_manifest()` method in `parquet.py`, I think around line ~1045. Either `_is_path_like()` or the FileSystem method `isdir()`  fail to recognize the path as a valid directory (I tested with a raw Windows path and a `pathlib.WindowsPath` object).

I hope this helps a little.

P.D. Thank you for your effort developing this package!

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by IlyaOrson** [comment]
Sure, I'll close this one for the [JIRA issue](https://issues.apache.org/jira/browse/ARROW-5122).
