### ISSUE TITLE
[C++] ListArray's Flatten function should support recursive flattening of nested lists

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#41055]
### Describe the enhancement requested

The function `FlattenListArray` seems only support flat the list array like `list(int32)`, 
https://github.com/apache/arrow/blob/6aa33210ecd9773f18ceb775306b79de132b6c6f/cpp/src/arrow/array/array_nested.cc#L240-L254

Users need to flatten nested list-arrays( list(list(int32)) ), and then the upper layer needs to implement recursive flatten, which seems inconvenient for them. 

@felipecrv  do you think we should implement this internally(and also for ListViewArray)?

### Component(s)

C++

**Comment by felipecrv** [comment]
> Users need to flatten nested list-arrays( list(list(int32)) ), and then the upper layer needs to implement recursive flatten, which seems inconvenient for them.

Right. But we can't change the behavior of existing `Flatten` to go recursive, but we can add a version that works recursively (and is not naively doing successive concatenations). And yes, it would treat all of `(Large)?List(View)?` as logical lists that need to be flattened until a non-list-like type is reached.

**Comment by felipecrv** [comment]
And we shouldn't forget `fixed_size_list` either. It's logically a list as well.
