### ISSUE TITLE
[Ruby] Arrow Flight Client do_put?

### ISSUE THREAD

**Issue by datbth** [apache/arrow#41056]
### Describe the enhancement requested

Hi, may I ask if there is a plan to implement the `do_put` method (and other missing Flight RPC methods) for Ruby Arrow Flight Client yet?

I checked GLib https://github.com/apache/arrow/blob/apache-arrow-16.0.0.dev/c_glib/arrow-flight-glib/client.h and saw that there is no binding yet.

### Component(s)

GLib, Ruby

**Comment by kou** [comment]
Let's implement it!

**Comment by datbth** [comment]
Would you need an extra hand on this?

**Comment by kou** [comment]
If you're interesting in this, you can try this.
#10836 may help you.

**Comment by kou** [comment]
Issue resolved by pull request 43813
https://github.com/apache/arrow/pull/43813
