### ISSUE TITLE
Exception has occurred: ImportError DLL load failed while importing lib: Die angegebene Prozedur wurde nicht gefunden.

### ISSUE THREAD

**Issue by julian-belina** [apache/arrow#41063]
### Describe the bug, including details regarding any error messages, version, and platform.

Hello,

I get the following Error when trying to import pyarrow with the following command:

`import pyarrow.lib as _lib`

> Exception has occurred: ImportError
> DLL load failed while importing lib: Die angegebene Prozedur wurde nicht gefunden.
>   File "C:\Programming\ethos_penalps\test_pyarrow.py", line 1, in <module>
>     import pyarrow.lib as _lib
> ImportError: DLL load failed while importing lib: Die angegebene Prozedur wurde nicht gefunden.

I have installed pyarrow with the following command into a clean environment from conda forge on Windows 11:

`mamba install pyarrow=10.0.1 python=3.10  `

This is my environment:

> aws-c-auth                0.7.15               ha04060b_0    conda-forge
> aws-c-cal                 0.6.9                hd33547d_3    conda-forge
> aws-c-common              0.9.12               hcfcfb64_0    conda-forge
> aws-c-compression         0.2.17               hd33547d_8    conda-forge
> aws-c-event-stream        0.4.1                hf127292_5    conda-forge
> aws-c-http                0.8.0                h0cc4be6_5    conda-forge
> aws-c-io                  0.14.3               hf372335_1    conda-forge
> aws-c-mqtt                0.10.1               h189e261_3    conda-forge
> aws-c-s3                  0.5.0                h582d114_2    conda-forge
> aws-c-sdkutils            0.1.14               hd33547d_0    conda-forge
> aws-checksums             0.1.17               hd33547d_7    conda-forge
> aws-crt-cpp               0.26.1               he292853_9    conda-forge
> aws-sdk-cpp               1.11.210            hf72cfbd_11    conda-forge
> bzip2                     1.0.8                hcfcfb64_5    conda-forge
> c-ares                    1.28.1               hcfcfb64_0    conda-forge
> ca-certificates           2024.2.2             h56e8100_0    conda-forge
> intel-openmp              2024.1.0           h57928b3_964    conda-forge
> krb5                      1.21.2               heb0366b_0    conda-forge
> libabseil                 20230802.1      cxx17_h63175ca_0    conda-forge
> libarrow                  10.0.1          h1138768_57_cpu    conda-forge
> libblas                   3.9.0              22_win64_mkl    conda-forge
> libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
> libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
> libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
> libcblas                  3.9.0              22_win64_mkl    conda-forge
> libcrc32c                 1.1.2                h0e60522_0    conda-forge
> libcurl                   8.7.1                hd5e4a3a_0    conda-forge
> libevent                  2.1.12               h3671451_1    conda-forge
> libffi                    3.4.2                h8ffe710_5    conda-forge
> libgoogle-cloud           2.12.0               h39f2fc6_4    conda-forge
> libgrpc                   1.59.3               h5bbd4a7_0    conda-forge
> libhwloc                  2.9.3           default_haede6df_1009    conda-forge
> libiconv                  1.17                 hcfcfb64_2    conda-forge
> liblapack                 3.9.0              22_win64_mkl    conda-forge
> libprotobuf               4.24.4               hb8276f3_0    conda-forge
> libre2-11                 2023.09.01           h8c5ae5e_1    conda-forge
> libsqlite                 3.45.2               hcfcfb64_0    conda-forge
> libssh2                   1.11.0               h7dfc565_0    conda-forge
> libthrift                 0.19.0               ha2b3283_1    conda-forge
> libutf8proc               2.8.0                h82a8f57_0    conda-forge
> libxml2                   2.12.6               hc3477c8_1    conda-forge
> libzlib                   1.2.13               hcfcfb64_5    conda-forge
> lz4-c                     1.9.4                hcfcfb64_0    conda-forge
> mkl                       2024.1.0           h66d3029_692    conda-forge
> numpy                     1.26.4          py310hf667824_0    conda-forge
> openssl                   3.2.1                hcfcfb64_1    conda-forge
> orc                       1.9.2                hf0b6bd4_0    conda-forge
> pip                       24.0               pyhd8ed1ab_0    conda-forge
> pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
> pyarrow                   10.0.1          py310hd0bb7c2_57_cpu    conda-forge
> python                    3.10.14         h4de0772_0_cpython    conda-forge
> python_abi                3.10                    4_cp310    conda-forge
> re2                       2023.09.01           hd3b24a8_1    conda-forge
> setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
> snappy                    1.2.0                hfb803bf_0    conda-forge
> tbb                       2021.11.0            h91493d7_1    conda-forge
> tk                        8.6.13               h5226925_1    conda-forge
> tzdata                    2024a                h0c530f3_0    conda-forge
> ucrt                      10.0.22621.0         h57928b3_0    conda-forge
> vc                        14.3                hcf57466_18    conda-forge
> vc14_runtime              14.38.33130         h82b7239_18    conda-forge
> vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
> wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
> xz                        5.2.6                h8d14728_0    conda-forge
> zstd                      1.5.5                h12be248_0    conda-forge

conda info

>      active environment : test_pyarrow
>     active env location : C:\Users\Julian\mambaforge\envs\test_pyarrow
>             shell level : 3
>        user config file : C:\Users\Julian\.condarc
>  populated config files : C:\Users\Julian\mambaforge\.condarc
>           conda version : 23.11.0
>     conda-build version : not installed
>          python version : 3.10.13.final.0
>                  solver : libmamba (default)
>        virtual packages : __archspec=1=x86_64
>                           __conda=23.11.0=0
>                           __win=0=0
>        base environment : C:\Users\Julian\mambaforge  (writable)
>       conda av data dir : C:\Users\Julian\mambaforge\etc\conda
>   conda av metadata url : None
>            channel URLs : https://conda.anaconda.org/conda-forge/win-64
>                           https://conda.anaconda.org/conda-forge/noarch
>           package cache : C:\Users\Julian\mambaforge\pkgs
>                           C:\Users\Julian\.conda\pkgs
>                           C:\Users\Julian\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Users\Julian\mambaforge\envs
>                           C:\Users\Julian\.conda\envs
>                           C:\Users\Julian\AppData\Local\conda\conda\envs
>                platform : win-64
>              user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Windows/10 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6
>           administrator : False
>              netrc file : None
>            offline mode : False

### Component(s)

Python

**Comment by xshirax** [comment]
I also have issue with importing pyarrow 
I occurs for me in pyarrow 12, 13, 14

File "/homes/name/.conda/envs/clipmap_pyarrow_12/lib/python3.10/site-packages/clipmap/clipmap.py", line 1, in <module>
    import pyarrow as pa
  File "/homes/name/.conda/envs/clipmap_pyarrow_12/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /homes/name/.conda/envs/clipmap_pyarrow_12/lib/python3.10/site-packages/pyarrow/../../.././liborc.so: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm

**Comment by m-rossi** [comment]
Downgrading snappy fixes the `ImportError` for me for now: `conda install "snappy<1.2"`, see the related issue in the feedstock: https://github.com/conda-forge/snappy-feedstock/issues/35

**Comment by julian-belina** [comment]
snappy 1.2 has been marked as broken. Can someone confirm that its no longer installable and it fixes the issue?

**Comment by m-rossi** [comment]
> snappy 1.2 has been marked as broken. Can someone confirm that its no longer installable and fixes the issue?

Yes, fixes it for me. snappy 1.2 is no longer installed when installing pyarrow with conda.

**Comment by julian-belina** [comment]
Thank you my pipelines work again.
