### ISSUE TITLE
Building from source failed

### ISSUE THREAD

**Issue by yunqu** [apache/arrow#4106]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04 (Arm64 architecture)
Ray installed from (source or binary): source
Arrow version: apache-arrow-0.12.1
Python version: 3.6.7
Exact command to reproduce: detailed below

I followed steps [here](https://arrow.apache.org/docs/developers/python.html#build-and-test) but `make` after `cmake` failed miserably.

Steps:
```
git clone https://github.com/apache/arrow/
cd arrow
git checkout -b apache-arrow-0.12.1 tags/apache-arrow-0.12.1
cd cpp
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
	  -DCMAKE_INSTALL_LIBDIR=lib \
          -DARROW_PYTHON=ON \
          -DARROW_PLASMA=ON \
          -DARROW_BUILD_TESTS=ON \
	  -DPYTHON_EXECUTABLE=/usr/bin/python3 \
           ..
make -j8
```

The error message is a long log while the first few lines are:
```
CMake Error at gflags_ep-stamp/gflags_ep-download-DEBUG.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/opt/builds/arrow/cpp/build/gflags_ep-prefix/src/gflags_ep-stamp/gflags_ep-download-DEBUG-impl.cmake'

  See also

    /opt/builds/arrow/cpp/build/gflags_ep-prefix/src/gflags_ep-stamp/gflags_ep-download-*.log


CMakeFiles/gflags_ep.dir/build.make:90: recipe for target 'gflags_ep-prefix/src/gflags_ep-stamp/gflags_ep-download' failed
make[2]: *** [gflags_ep-prefix/src/gflags_ep-stamp/gflags_ep-download] Error 1
CMakeFiles/Makefile2:422: recipe for target 'CMakeFiles/gflags_ep.dir/all' failed
make[1]: *** [CMakeFiles/gflags_ep.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at flatbuffers_ep-stamp/flatbuffers_ep-download-DEBUG.cmake:49 (message):
  Command failed: 1
```

Not sure if I am doing something wrong here?

**Comment by yunqu** [comment]
This seems like a `cmake` problem. The error log has complaints like "https disabled or not supported by libcurl", while I actually have it supported nicely and tested successfully. 

The default version that comes with Ubuntu 18.04 works. I had to downgrade its version. Now it is happy.

**Comment by AllenCX** [comment]
Hi yunqu, 

Did you find a way to solve it?

Thanks

**Comment by yunqu** [comment]
As far as I can remember, I just downgraded the cmake version to the default version that comes with ubuntu 18.04. Then it worked.
