### ISSUE TITLE
[C++] Finish up HalfFloatType cast changes. 

### ISSUE THREAD

**Issue by ClifHouck** [apache/arrow#41089]
### Describe the enhancement requested

There were a few issues brought up on https://github.com/apache/arrow/pull/40067 post-merge. This issue is solely to track finishing those tasks. Mainly adding a couple of tests and removing an unnecessary change to another test.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 41084
https://github.com/apache/arrow/pull/41084
