### ISSUE TITLE
[C++] `S3FileSystem(role_arn)` raises `SIGABRT` on shutdown

### ISSUE THREAD

**Issue by matthewdeng** [apache/arrow#41087]
### Describe the bug, including details regarding any error messages, version, and platform.

# Summary

Constructing an `S3FileSystem` with `role_arn` set will cause a `SIGABRT` to be raised at the end of the script. 

This impacts workflows that depend on the exit code.

# Repro

**PyArrow Version:** 15.0.2 (Happens starting in 13.0.0, does not happen in 12.0.1)

**`repro.py`:**
```python
import pyarrow.fs
filesystem = pyarrow.fs.S3FileSystem(role_arn="...")
```

**Output:**
```
$ python repro.py 
Fatal error condition occurred in /opt/vcpkg/buildtrees/aws-c-common/src/v0.8.9-fed0b55d0f.clean/source/allocator.c:209: allocator != ((void *)0)
Exiting Application
No call stack information available
Aborted

$ echo $?
134
```

### Component(s)

C, Python

**Comment by pcmoritz** [comment]
@pitrou Do you have any idea what the cause for this could be and how we can fix it?

**Comment by kou** [comment]
Could you try this?

```python
import pyarrow.fs
filesystem = pyarrow.fs.S3FileSystem(role_arn="...")
del filesystem
pyarrow.fs.ensure_s3_finalized()
```

**Comment by matthewdeng** [comment]
Thanks @kou! I forgot to mention that deleting the `filesystem` _does_ resolve the issue:

**Explicitly:**
```python
import pyarrow.fs
filesystem = pyarrow.fs.S3FileSystem(role_arn="...")
del filesystem
```

**Implicitly:**
```python
import pyarrow.fs

def main():
    filesystem = pyarrow.fs.S3FileSystem(role_arn="...")

main()
```

Separately, I also just tried this with `pyarrow==16.0.0` which was recently released, and it seems like the issue no longer surfaces. Let me do some more extensive validation, if I'm no longer able to reproduce the issue in this version I can close this issue.

**Comment by matthewdeng** [comment]
Verified that it's working for us now, marking as resolved! Thanks!
