### ISSUE TITLE
cannot hold very large DataFrame

### ISSUE THREAD

**Issue by fayeshine** [apache/arrow#4109]
I have a DataFrame which size should be about 6000000*1000, this error happens

```
Traceback (most recent call last):

  File "<ipython-input-9-6ad29a9635f6>", line 1, in <module>
    object_id = client.put(data)

  File "pyarrow/_plasma.pyx", line 496, in pyarrow._plasma.PlasmaClient.put

  File "pyarrow/serialization.pxi", line 355, in pyarrow.lib.serialize

  File "pyarrow/error.pxi", line 93, in pyarrow.lib.check_status

ArrowCapacityError: BinaryArray cannot contain more than 2147483646 bytes, have 2539867406
```

**Comment by bkietz** [comment]
Thanks for reporting this. Could you please [open a JIRA issue](https://issues.apache.org/jira/secure/CreateIssue!default.jspa)?

**Comment by wesm** [comment]
Also, please provide a reproducible example of the issue if you can

**Comment by fsaintjacques** [comment]
2G is plasma server default maximum allocation pool.

**Comment by fayeshine** [comment]
> 2G is plasma server default maximum allocation pool.

@fsaintjacques how to set plasma server maximum allocation pool

**Comment by emkornfield** [comment]
@fayeshine  https://arrow.apache.org/docs/python/plasma.html provides a command line with parameters have you tried that?

**Comment by fayeshine** [comment]
@emkornfield thanks, I have already set to 100GB, but this bug still happen

**Comment by emkornfield** [comment]
Hi fayeshine, actually looking at the error, I think the issue might be that you are creating a binary  value that has more then 2^31-1 bytes in it.  This is not currently supported in the existing layout for strings/list/variable width types(https://arrow.apache.org/docs/memory_layout.html).  There is a discussion on the mailing list about supporting larger types.

**Comment by emkornfield** [comment]
@fayeshine see explanation above, if that doesn't explain it, please file a [bug](https://issues.apache.org/jira/secure/Dashboard.jspa)

**Comment by fayeshine** [comment]
@emkornfield when will we support larger types?

**Comment by emkornfield** [comment]
Hard to say, it will probably take a week or two to come to consensus on the [mailing list](http://mail-archives.apache.org/mod_mbox/arrow-dev/).   If we agree to support the larger types someone needs to contribute patches, the only type currently being worked on is lists.  If you have interest and time it might be easy to replicate the work on large list type  to other types.
