### ISSUE TITLE
[Python] Adapt to changes in the `copy` keyword for numpy 2.0+ compatibility

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#41098]
We need to adapt for changes in numpy 2.0 as decribed at https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword and future changes to pass copy=True (https://github.com/numpy/numpy/issues/26208).

It seems we don't have usages of `np.array(.., copy=False)` in our code base, so we only have to tackle the item about the `copy` keyword in the `__array__` method.

**Comment by pitrou** [comment]
Issue resolved by pull request 41071
https://github.com/apache/arrow/pull/41071
