### ISSUE TITLE
[Packaging][Release] Create unique git tags for release candidates (e.g. `apache-arrow-{MAJOR}.{MINOR}.{PATCH}-rc{RC_NUM}`)

### ISSUE THREAD

**Issue by sgilmore10** [apache/arrow#41102]
### Describe the enhancement requested

As per @kou's [suggestion](https://github.com/apache/arrow/pull/40956#discussion_r1556447060) in #40956, we should create unique git tags (e.g. `apache-arrow-{MAJOR}.{MINOR}.{VERSION}-rc{RC_NUM}`) instead re-using the same git tag (`apache-arrow-{MAJOR}.{MINOR}.{VERSION}`) for each release candidate. The official release candidate tag (`apache-arrow-{MAJOR}.{MINOR}.{VERSION}`) should be created **only** after a release candidate is voted on and accepted. This "official" release tag should point to the same object in the git database as the accepted release candidate tag. 

The new release workflow could look like the following:

> 1. Create a apache-arrow-X.Y.Z-rc0 tag for X.Y.Z RC0 
> 2. (Found a problem for X.Y.Z RC0)
> 3. Create a apache-arrow-X.Y.Z-rc1 tag for X.Y.Z RC1
> 4. Vote
> 5. Passed
> 6. Create a apache-arrow-X.Y.Z tag from apache-arrow-X.Y.Z-rc1 ike apache/arrow-adbc and apache/arrow-flight-sql-postgresql do

See @kou's [comment](https://github.com/apache/arrow/pull/40956#discussion_r1556447060) for more details.

### Component(s)

Packaging, Release

**Comment by sgilmore10** [comment]
take

**Comment by kou** [comment]
@raulcd What do you think about this workflow change?

**Comment by raulcd** [comment]
I am happy with it. We might want to add the deletion of old RC tags once we create the tag that has passed the vote.

**Comment by kou** [comment]
I think that we don't need to delete old RC tags. Because there is no limit on the total size of a release: https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

**Comment by sgilmore10** [comment]
Issue resolved by pull request 41131
https://github.com/apache/arrow/pull/41131
