### ISSUE TITLE
[C#] Dense union arrays return incorrect results for IsValid and IsNull

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41137]
### Describe the bug, including details regarding any error messages, version, and platform.

`IsValid` and `IsNull` are implemented in the base `UnionArray` class, which doesn't account for the  value offsets.

I encountered this when looking at how to test null count calculation for union arrays (#41136)

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41138
https://github.com/apache/arrow/pull/41138
