### ISSUE TITLE
[C#] NullCount should be recomputed on-demand for sliced arrays

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41136]
### Describe the enhancement requested

This is a prerequisite for writing sliced arrays in the IPC format (#40517), as the IPC format doesn't seem to allow for the `null_count` field to be unset or negative.

Currently, when slicing an array, the null count is set to -1 (`RecalculateNullCount`) to indicate that the null count is no longer valid.

### Component(s)

C#

**Comment by adamreeve** [comment]
take

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41144
https://github.com/apache/arrow/pull/41144

**Comment by raulcd** [comment]
I am moving this to 16.1.0 to be able to cleanly cherry-pick this: https://github.com/apache/arrow/commit/a6cdcd051a8df1501c3c2530c421ba9f4a8957fd
