### ISSUE TITLE
[Benchmarking] Build benchmarks in benchmarks.env

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#41133]
### Describe the bug, including details regarding any error messages, version, and platform.

Previously, we were relying on archery to build C++ microbenchmarks during Conbench runs. That doubled the build time and ignored all the environment variables set in this file. Along with https://github.com/voltrondata-labs/benchmarks/pull/159, this change will remove the duplicated build.

Originally reported by @austin3dickey in #40925 

### Component(s)

Benchmarking

**Comment by assignUser** [comment]
Issue resolved by pull request 40925
https://github.com/apache/arrow/pull/40925

**Comment by austin3dickey** [comment]
Take

**Comment by raulcd** [comment]
adding to 16.1.0 in order to be able to run C++ benchmarks for comparison with 15.0.2
