### ISSUE TITLE
[Java] Format pom.xml files using Apache Maven pom.xml 2008 convention

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#41173]
### Describe the enhancement requested

`pom.xml` files used by the project seems to follow direct conventions regarding indentation or section ordering which makes harder to push changes to those files.

One of the most used convention for `pom.xml` files is the one used by [Apache Maven itself](https://maven.apache.org/developers/conventions/code.html#generic-code-style-and-convention).

There are a couple of plugins which do support this convention but spotless seems to be one of the most common options, especially if the project decides to also use for Java code formatting.

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41174
https://github.com/apache/arrow/pull/41174
