### ISSUE TITLE
[Python] Memory leak for repeated `StructArray` creation

### ISSUE THREAD

**Issue by rjzamora** [apache/arrow#41172]
### Describe the bug, including details regarding any error messages, version, and platform.

Memory grows continuously when a simple `StructArray` is overwritten repeatedly:

```python
import pyarrow as pa

while True:
    arr = pa.array([{"test": {str(i): "test" * 100000 for i in range(50)}}])
```

### Component(s)

Python

**Comment by galipremsagar** [comment]
I noticed `pa.StructArray.from_arrays` doesn't seem to be having this leak.

**Comment by wence-** [comment]
Duplicate of https://github.com/apache/arrow/issues/37989, fixed in https://github.com/apache/arrow/pull/40412
