### ISSUE TITLE
[C++][Parquet][Doc] Denote PARQUET:field_id in parquet.rst

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#41186]
### Describe the enhancement requested

Denote the mapping for field_id ( see https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/writer.cc#L536 and https://github.com/apache/arrow/blob/ec2d7cbfb426854ccb57be1d2abd9e2f88b268b9/cpp/src/parquet/arrow/schema.cc#L245 ) schema in parquet doc ( https://github.com/apache/arrow/blob/main/docs/source/python/parquet.rst )

### Component(s)

C++, Documentation, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 41187
https://github.com/apache/arrow/pull/41187
