### ISSUE TITLE
[C#] Accessing values of a decimal array doesn't account for the array offset

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41199]
### Describe the bug, including details regarding any error messages, version, and platform.

`Decimal128Array.GetValue`, `GetString` and `GetSqlDecimal` account for the array offset in the null check but not when getting the actual value.

`Decimal256Array.GetValue`, `GetString` and `TryGetSqlDecimal` have the same issue.

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41200
https://github.com/apache/arrow/pull/41200
