### ISSUE TITLE
[C++] ASOF join and sortedmerge join don't work in single threaded mode

### ISSUE THREAD

**Issue by joemarshall** [apache/arrow#41190]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently, if ARROW_ENABLE_THREADING is not set, asof join and sortedmergejoin are not implemented. This is because the current implementation uses std::thread internally, and I tried not to mess with any class internal code while creating the single threaded mode.

This could do with fixing, as I'm mid porting python to add single threaded support, and otherwise a load of tests will break.

### Component(s)

C++

**Comment by westonpace** [comment]
Issue resolved by pull request 41125
https://github.com/apache/arrow/pull/41125
