### ISSUE TITLE
[C#] Union array concatenation is incorrect

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41198]
### Describe the bug, including details regarding any error messages, version, and platform.

The `ArrayDataConcatenator` does not currently handle union arrays correctly. It concatenates type and offset buffers without accounting for array lengths, and the way it calculates the `baseOffset` in `ConcatenateUnionOffsetBuffer` has an off-by-one error and doesn't account for offsets being different per type.

I've made union array comparison more thorough in #41197, which caused the array concatenation tests to start failing, so I've temporarily skipped testing of union array concatenation in that PR.

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41226
https://github.com/apache/arrow/pull/41226
