### ISSUE TITLE
[Java][FlightSQL] Implement stateless prepared statements

### ISSUE THREAD

**Issue by stevelorddremio** [apache/arrow#41262]
### Describe the enhancement requested

Use Case
Expand the languages implementing stateless prepared statements to include Java.

Background
Stateless prepared statements enhancement proposal was approved on March 24, 2024.
https://github.com/apache/arrow/issues/37720

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41237
https://github.com/apache/arrow/pull/41237
