### ISSUE TITLE
[Dev] merge_arrow_pr.py uses 16.1.0 as the default fix version

### ISSUE THREAD

**Issue by kou** [apache/arrow#41282]
### Describe the bug, including details regarding any error messages, version, and platform.

Can we use 17.0.0 as the default fix version?

### Component(s)

Developer Tools

**Comment by jorisvandenbossche** [comment]
Did we change that? I saw 17.0.0 when merging a PR? (at least a few days ago, didn't yet merge anything yesterday or today)

**Comment by kou** [comment]
I saw this today.
The 16.1.0 milestone may be created yesterday or today. It may be related.

**Comment by raulcd** [comment]
Yes, the 16.1.0 milestone was created afterwards.

**Comment by raulcd** [comment]
Issue resolved by pull request 41305
https://github.com/apache/arrow/pull/41305
