### ISSUE TITLE
[Release][Java] Maven version detection in verification script may not work

### ISSUE THREAD

**Issue by kou** [apache/arrow#41280]
### Describe the bug, including details regarding any error messages, version, and platform.

Maven may use escape sequence for `mvn -v`. So `$(mvn -v | head -n 1 | awk '{print $3}')` may have a escape sequence.

Here is an example case of this:

```console
$ x="$(mvn -v | head -n 1 | awk '{print $3}')" ruby -e 'p ENV["x"]'
"3.8.7\e[m"
```

### Component(s)

Java

**Comment by assignUser** [comment]
Issue resolved by pull request 41281
https://github.com/apache/arrow/pull/41281
