### ISSUE TITLE
[Python] Read-only pd.DataFrame after reading

### ISSUE THREAD

**Issue by Zillibub** [apache/arrow#4128]
## Can't change columns after reading DataFrame from pyarrow

The behavior of pandas dataframe is changing after reading it from pyarrow. It become unwritable and the writable flag cannot be changed. I am not sure if this is a proper behavior for pandas.

Example: 
`df = pd.DataFrame(np.random.randn(100, 4), columns=list('ABCD'))`
Writing and reading: 
```
context = pa.default_serialization_context()
buf = context.serialize(df).to_buffer()
with pa.output_stream('test.pa') as stream:
    stream.write(buf)

with pa.input_stream('test.pa') as stream:
    df2 = context.deserialize(stream.read())
```
After reading Dataframe setting new values  to created columns raises exception: 
`df2.loc[:, ['A']] = df['A']`
ValueError: assignment destination is read-only

Flags in values: 
```
df2.values.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```
So, after reading dataframe the values are becoming unwritable and I can't change it. 

Two ways to avoid it: 
`df2 = df2.copy()`
or
```
df2.loc[:, ['A']] = None
df2.loc[:, ['A']] = df['A']
```
But I am not sure this is a good practice.

**Comment by pitrou** [comment]
Yes, Arrow is based around the idea of immutable data. It allows easy sharing of data between multiple threads or even process (if using shared memory / memory-mapped files). However, it means that modifying data requires allocating a new memory area.

Replacing the column with a new column is a reasonable solution, as you've found out.
