### ISSUE TITLE
[Python] SEGFAULT when casting a slice of a fixed with binary array to binary

### ISSUE THREAD

**Issue by judahrand** [apache/arrow#41306]
### Describe the bug, including details regarding any error messages, version, and platform.

```python
import pyarrow

arr = pyarrow.array(
    [b'a',b'b',b'c'],
   pyarrow.binary(1),
)
arr.slice(1).cast(pyarrow.binary())
```
```
Job 1, 'python' terminated by signal SIGSEGV (Address boundary error)
```

Running on an M1 Mac with `pyarrow==15.0.2`.
### Component(s)

C++, Python

**Comment by llama90** [comment]
take

**Comment by westonpace** [comment]
Issue resolved by pull request 41452
https://github.com/apache/arrow/pull/41452
