### ISSUE TITLE
[C#][Integration] Integration tests failing due to C# failing to write binary arrays with empty offsets

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41302]
### Describe the bug, including details regarding any error messages, version, and platform.

The changes in #41230 broke the integration tests. See https://github.com/apache/arrow/pull/41264#issuecomment-2065465259 for more context

### Component(s)

C#, Integration

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41303
https://github.com/apache/arrow/pull/41303
