### ISSUE TITLE
[Java] Update Maven modules to use latest Apache Parent (31) and plugins

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#41307]
### Describe the enhancement requested

Apache Java Arrow root project depends on [Apache Parent](https://github.com/apache/maven-apache-parent/blob/apache-18/pom.xml) [18](https://github.com/apache/maven-apache-parent) as its default configuration which is fairly odd nowadays. Some modules do not even use Apache Parent at all.

To keep the build stack clean, up-to-date and pave the way to support newer java versions for example, modules should be updated and cleaned up to use Apache Parent 31[^1], recent plugins, and remove unnecessary version/configuration when already defined in the parent modules.

[^1]: Apache Parent 32 has just been released but use `--release` by default which does not work well with Arrow use of `sun.misc.Unsafe`

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41309
https://github.com/apache/arrow/pull/41309

**Comment by kiszk** [comment]
@github-actions crossbow submit test-conda-python-3.10-spark-v3.5.0

**Comment by kiszk** [comment]
@github-actions  crossbow submit test-conda-python-3.10-spark-v3.5.0
