### ISSUE TITLE
[CI][Python] Add a job on ARM64 macOS

### ISSUE THREAD

**Issue by llama90** [apache/arrow#41314]
### Describe the enhancement requested

We need a new job in the Python environment. 

I'm not sure, but these errors seem to happen because of the environment, and it will be important in the future.

- https://github.com/apache/arrow/issues/41312

### Component(s)

Continuous Integration, Python

**Comment by kou** [comment]
Issue resolved by pull request 41313
https://github.com/apache/arrow/pull/41313
