### ISSUE TITLE
[C++][Gandiva] Cache size can be negative number

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#41329]
### Describe the bug, including details regarding any error messages, version, and platform.

I think the original purpose of the following check is to set gandiva cache size to the predefined default value (`5000`) for invalid/zero/negative numbers:
https://github.com/apache/arrow/blob/25bb627519f17835cb0b6ff95588f2de0cbaf7ad/cpp/src/gandiva/cache.cc#L29-L42

However it will fail checking if the value is negative because it is using unsigned type `size_t` to do the `<= 0` check.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 41330
https://github.com/apache/arrow/pull/41330
