### ISSUE TITLE
[C#][Flight] Add support for non-Kestrel Flight server

### ISSUE THREAD

**Issue by qed-** [apache/arrow#41347]
### Describe the enhancement requested

Due to class protection levels it is not currently possible to implement a flight server outside of AspNet.Core.

i.e. to start a flight server as a non-Kestrel GRPC server the following code can't be used due to protection level of the protocol and FlightServerImplementation classes.
```
using Apache.Arrow.Flight.Protocol;
using Apache.Arrow.Flight.Server.Internal;

var flightServer = new FlightServerImpl();
var server = new Server
{
    Services = {  FlightService.BindService(new FlightServerImplementation(flightServer)) },
    Ports =  { new ServerPort("0.0.0.0", 5001, ServerCredentials.Insecure) }   }
};
server.Start();
```

### Component(s)

C#, FlightRPC

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 41348
https://github.com/apache/arrow/pull/41348

**Comment by CurtHagenlocher** [comment]
@qed-, I should probably have looked at the build output more closely. Do you actually need .NET 4.6.2 support or is .NET 4.7.2 okay? The reason I ask is that there's at least one dependency here which requires netstandard2.0, and the situation with net462 and netstandard2.0 is a bit messy to say the least. If you don't specifically need 462 then targeting 472 probably makes more sense.

**Comment by qed-** [comment]
Hi @CurtHagenlocher , .net 4.7.2 is fine. I'll create a new PR to update it.
