### ISSUE TITLE
[C++][CMake] ARROW_NO_DEPRECATED_API is unused

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#41343]
### Describe the bug, including details regarding any error messages, version, and platform.

When I was reading the CMake code, I found that ARROW_NO_DEPRECATED_API is not used in the source code. Am I missing something?

### Component(s)

C++

**Comment by wgtmac** [comment]
cc @kou @pitrou

**Comment by kou** [comment]
GH-13288 removed the last `#ifndef ARROW_NO_DEPRECATED_API`.
It seems that we can remove the CMake variable.

We can use `ARROW_DEPRECATED()` and `-Werror=deprecated-declarations` instead.

**Comment by wgtmac** [comment]
OK, let me remove this.

**Comment by wgtmac** [comment]
Issue resolved by pull request 41345
https://github.com/apache/arrow/pull/41345
