### ISSUE TITLE
[C++][CMake][Windows] Don't use .dll suffix for system libraries such as ws2_32

### ISSUE THREAD

**Issue by kou** [apache/arrow#41340]
### Describe the bug, including details regarding any error messages, version, and platform.

We should use import library (`.lib`) no DLL (`.dll`) to link with system libraries. So `target_link_libraries(... ws2_32.dll)` is wrong. (But it seems that it works with MSVC...)

We should use `target_link_libraries(... ws2_32.lib)` (use `.lib`) or `target_link_libraries(... ws2_32)` (no extension).

See also: https://cmake.org/cmake/help/latest/command/target_link_libraries.html#command:target_link_libraries

> A plain library name: The generated link line will ask the linker to search for the library (e.g. `foo` becomes `-lfoo` or `foo.lib`).

See also: https://github.com/microsoft/vcpkg/pull/38295/files#r1574568441

### Component(s)

C++

**Comment by dg0yt** [comment]
> So `target_link_libraries(... ws2_32.dll)` isn't wrong. (But it seems that it works with MSVC...)

This isn't true: https://github.com/microsoft/vcpkg/issues/38305 is the original issue from vcpkg users.
The key problem is that the `ws2_32.dll` is published to the link interface for static library linkage. You won't notice until you consume the CMake config.

**Comment by kou** [comment]
Ah, sorry. The "isn't" is a typo... It should be "it".

**Comment by kou** [comment]
Issue resolved by pull request 41341
https://github.com/apache/arrow/pull/41341
