### ISSUE TITLE
[C#] use SqlDecimal.WriteTdsValue for .NET 7+ to avoid allocating a byte[] array

### ISSUE THREAD

**Issue by nmishturak-gl** [apache/arrow#41349]
### Describe the enhancement requested

In .NET 7+ there is an option to use [SqlDecimal.WriteTdsValue](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqldecimal.writetdsvalue?view=net-8.0#system-data-sqltypes-sqldecimal-writetdsvalue(system-span((system-uint32)))) to avoid allocating a `byte[]`

https://github.com/apache/arrow/blob/68eeef52aa78743a69844914ec984bed053bcfff/csharp/src/Apache.Arrow/DecimalUtility.cs#L434-L436

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 42150
https://github.com/apache/arrow/pull/42150
