### ISSUE TITLE
[Release][Docs] Update post release documentation task to remove the warnings banner for stable version

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#41356]
### Describe the bug, including details regarding any error messages, version, and platform.

When the stable version of the docs is generated, the warnings banner is still visible and should be removed.

Similar to: https://github.com/apache/arrow/pull/39762

### Component(s)

Documentation, Release

**Comment by raulcd** [comment]
Temporal fix for 16.0.0: https://github.com/apache/arrow-site/pull/503

**Comment by kou** [comment]
Issue resolved by pull request 41377
https://github.com/apache/arrow/pull/41377
