### ISSUE TITLE
[C++][Parquet] Optimize TypedRecordReader::DelimitRecords for nested type

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#41361]
### Describe the enhancement requested

When read nested type( for example, `list<list<int>>` ) , from the flamegraph, the bottlenect is `DelimitRecords`. It scan the rep-levels and def-levels, and return the number of records/non-null-values to user.

![1eeab6336e834b7d210071e9a8c2525e](https://github.com/apache/arrow/assets/24351052/81588c99-5515-4846-bc8d-9cd8eb631ed1)

The bottleneck of this is branching checking, we can optimize this.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 41362
https://github.com/apache/arrow/pull/41362
