### ISSUE TITLE
[CI][MATLAB] MATLAB macOS CI workflow fails because of `macos-latest` change to `macos-14`

### ISSUE THREAD

**Issue by kou** [apache/arrow#41370]
### Describe the bug, including details regarding any error messages, version, and platform.

`macos-latest` is now `macos-14` not `macos-12`.

In https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/ it is mentioned that the transition to `macos-14` was planned for April-June 2024).

See also: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Example:

https://github.com/apache/arrow/actions/runs/8819911040/job/24212270905?pr=41359#step:9:28

```text
CMake Error at /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
-- Configuring incomplete, errors occurred!
  Could NOT find Matlab (missing: Matlab_MEX_LIBRARY Matlab_MX_LIBRARY)
  (found version "9.14.0.2489007")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/FindMatlab.cmake:2029 (find_package_handle_standard_args)
  CMakeLists.txt:135 (find_package)
```

### Component(s)

Continuous Integration, MATLAB

**Comment by kevingurney** [comment]
Thanks for reporting this @kou!

This may be due to the fact that we are currently using MATLAB R2023a in the GitHub Actions workflow, and R2023a is not officially supported on `macos-14`.

See the Platform Roadmap here for more information on version compatibility:

https://www.mathworks.com/support/requirements/platform-road-map.html

We can try updating the version of MATLAB used in the GitHub Actions workflow to R2024a. Hopefully that will resolve the issue.

**Comment by kevingurney** [comment]
After some more investigation, we realized that there are a few issues that need to be addressed in `mathworks/libmexclass` before we can start using R2024a.

So, we think it makes the most sense to just pin this CI workflow back to use `macos-12` for the time being.

We will prioritize addressing the `libmexclass` issues as soon as we can.

**Comment by kevingurney** [comment]
I've created  #41385 to capture the work of moving to R2024a.

**Comment by kevingurney** [comment]
Issue resolved by pull request 41384
https://github.com/apache/arrow/pull/41384
