### ISSUE TITLE
[CI][Release] macOS job is failed because of mascos-latest change

### ISSUE THREAD

**Issue by kou** [apache/arrow#41371]
### Describe the bug, including details regarding any error messages, version, and platform.

`macos-latest` is `macos-14` not `macos-12`.

See also: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Example:

https://github.com/apache/arrow/actions/runs/8819910983/job/24212269544?pr=41359#step:4:18

```text
Error: The current runner (macos--arm64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
In such a case, you should install Ruby in the $RUNNER_TOOL_CACHE yourself, for example using https://github.com/rbenv/ruby-build
You can take inspiration from this workflow for more details: https://github.com/ruby/ruby-builder/blob/master/.github/workflows/build.yml
$ ruby-build 2.7.8 /Users/runner/hostedtoolcache/Ruby/2.7.8/arm64
Once that completes successfully, mark it as complete with:
$ touch /Users/runner/hostedtoolcache/Ruby/2.7.8/arm64.complete
It is your responsibility to ensure installing Ruby like that is not done in parallel.
```

### Component(s)

Continuous Integration, Release

**Comment by raulcd** [comment]
Issue resolved by pull request 41379
https://github.com/apache/arrow/pull/41379
