### ISSUE TITLE
[CI][MATLAB][Packaging] Add support for MATLAB `R2024a` in CI and crossbow packaging workflows

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#41385]
### Describe the enhancement requested

MATLAB R2024a is the latest available version of MATLAB as of April 2024.

We are currently building against MATLAB R2023a in CI and for the crossbow packaging workflow.

We should update the version of MATLAB we support to the latest available version.

We previously created an issue to use R2023b (#37809). However, R2024a has become publicly available since then.

We may want to consider building and packaging against multiple versions of MATLAB in parallel, rather than just the latest. This would require some more thought on how many releases back to support over time, however.

### Component(s)

Continuous Integration, MATLAB, Packaging

**Comment by sgilmore10** [comment]
Issue resolved by pull request 41504
https://github.com/apache/arrow/pull/41504
