### ISSUE TITLE
[Ruby] Cannot get gem installed on Ubuntu 20 with arrow 14,15 and/or 16

### ISSUE THREAD

**Issue by andresbarcenas** [apache/arrow#41396]
### Describe the bug, including details regarding any error messages, version, and platform.

here is the error message on Ubuntu 20 (focal)

```text
checking for arrow version (>= 15.0.0)... yes (16.0.0)
checking for arrow-glib version (>= 15.0.2)... yes (16.0.0)
creating Makefile

current directory: /home/deployer/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/red-arrow-15.0.2/ext/arrow
make "DESTDIR=" clean

current directory: /home/deployer/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/red-arrow-15.0.2/ext/arrow
make "DESTDIR="
compiling arrow.cpp
In file included from /usr/include/arrow/result.h:28,
                 from /usr/include/arrow/device.h:26,
                 from /usr/include/arrow/buffer.h:29,
                 from /usr/include/arrow/array/data.h:27,
                 from /usr/include/arrow/array/array_base.h:26,
                 from /usr/include/arrow/array.h:41,
                 from /usr/include/arrow/api.h:22,
                 from red-arrow.hpp:22,
                 from arrow.cpp:20:
/usr/include/arrow/util/aligned_storage.h:39:22: error: ‘constexpr const T* arrow::internal::AlignedStorage<T>::get() const’ cannot be overloaded with ‘constexpr T* arrow::internal::AlignedStorage<T>::get() const’
   39 |   constexpr const T* get() const noexcept {
      |                      ^~~
/usr/include/arrow/util/aligned_storage.h:35:16: note: previous declaration ‘constexpr T* arrow::internal::AlignedStorage<T>::get() const’
   35 |   constexpr T* get() noexcept {
      |                ^~~
In file included from /usr/include/arrow/device.h:26,
                 from /usr/include/arrow/buffer.h:29,
                 from /usr/include/arrow/array/data.h:27,
                 from /usr/include/arrow/array/array_base.h:26,
```

Is there any specific documentation/instructions to get this gem installed on Ubuntu 20. I was able to do it on CentOS7 with devtoolset-8

### Component(s)

Ruby

**Comment by kou** [comment]
@raulcd https://github.com/msys2/MINGW-packages/pull/20692 isn't merged yet but I'll release 16.0.0 gems. Because there is a problem with Apache Arrow C++ 16.0.0 and Red Arrow 15.0.x combination on other platforms. Releasing 16.0.0 gems break `gem install red-arrow` on Windows but it'll be fixed by https://github.com/msys2/MINGW-packages/pull/20692 is merged.

**Comment by kou** [comment]
I've released 16.0.0 gems.

@andresbarcenas Could you try again?

**Comment by raulcd** [comment]
Thanks @kou , sounds good to me. I'll try to fix the MINGW packages PR tomorrow but I'm slightly busy might have to do it on Monday.

**Comment by kou** [comment]
Thanks! No problem!

**Comment by Hronom** [comment]
Not works

**Comment by kou** [comment]
Ah, `re2.pc` on Ubuntu 20.04 and Debian bullseye have `-std=c++11`. I assumed that `re2.pc` on all supported platforms don't have `-std=c++11` in #39932.

Could you use Ubuntu 22.04 or `ruby:*-bookworm` instead?
Or could you run `sudo sed -i -e 's/-std=c++11//g' /usr/lib/x86_64-linux-gnu/pkgconfig/re2.pc` before `gem install red-arrow` as workaround?

**Comment by kou** [comment]
FYI: `sudo sed -i -e 's/-std=c++11//g' /usr/lib/x86_64-linux-gnu/pkgconfig/re2.pc` is safe because `g++` on Ubuntu 20.04 and Debian bullseye use C++14 as the default C++ standard.

**Comment by Hronom** [comment]
@kou thank you we cannot use `bookworm` as it will require update of Ruby. We currently use `3.0.6-slim-bullseye`.

Strange issue, because previously it was working on the same version, but now it stopped. Is there was some update?

**Comment by andresbarcenas** [comment]
> I've released 16.0.0 gems.
> 
> @andresbarcenas Could you try again?

I was able to do a simple 'gem install red-arrow -v 16' but I had to run the `sudo sed -i -e 's/-std=c++11//g' /usr/lib/x86_64-linux-gnu/pkgconfig/re2.pc` command as you mentioned. 

`deployer@sternvmutildev01-vm:~/apps/stern/current$ gem install red-arrow -v 16
Building native extensions. This could take a while...
Successfully installed red-arrow-16.0.0
Parsing documentation for red-arrow-16.0.0
Installing ri documentation for red-arrow-16.0.0
Done installing documentation for red-arrow after 1 seconds
1 gem installed`

Thank you for such a fast update and releasing 16.0.0. gems

**Comment by kou** [comment]
Yes. We need the `sed` on Ubuntu 20.04 too.

**Comment by kou** [comment]
> Is there was some update?

#39932 as I mentioned.

FYI: Debian GNU/Linux bullseye will reach EOL on 2024-07: https://wiki.debian.org/DebianReleases

So you need to update your image sooner or later.

**Comment by kou** [comment]
I didn't have a plan for it because Ubuntu 20.04 will reach EOL soon but let's do it.

**Comment by kou** [comment]
Issue resolved by pull request 43721
https://github.com/apache/arrow/pull/43721

**Comment by datbth** [comment]
That is really great. Thank you!
