### ISSUE TITLE
[CI][R]: Update our backwards compatibility CI any other R 4.4 cleanups

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#41402]
### Describe the enhancement requested

I noticed some of our CI jobs like our backwards compatibility check haven't been updated for a number of versions — bumping those. I will also ensure we have R 4.4 in the right places.

### Component(s)

Continuous Integration, R

**Comment by assignUser** [comment]
This now also contains a minimum version bump and related changes and I think it would make sense to add it too 16.1, so I am adding this as a blocker.

**Comment by jonkeane** [comment]
Issue resolved by pull request 41403
https://github.com/apache/arrow/pull/41403
