### ISSUE TITLE
[MATLAB] Bump `libmexclass` version to commit `ca3cea6`

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#41400]
### Describe the enhancement requested

This is a follow up to #41370.

@sgilmore10 and I recently resolved multiple issues related to `mathworks/libmexclass` not supporting ARM-based macOS builds (i.e. builds on `macos-14`).:

* https://github.com/mathworks/libmexclass/issues/76
* https://github.com/mathworks/libmexclass/issues/77

We should bump the version of `mathworks/libmexclass` used by the MATLAB interface to the latest available commit ([`ca3cea6`](https://github.com/mathworks/libmexclass/commit/ca3cea6bf1ba5e9d86210bd207d643493e8d45f6) as of now) in order to enable building the MATLAB interface to Arrow on `macos-14` (which is ARM-based).

### Component(s)

MATLAB

**Comment by sgilmore10** [comment]
Issue resolved by pull request 41436
https://github.com/apache/arrow/pull/41436
