### ISSUE TITLE
[Release][Docs][GLib] Use Sphinx based GLib front page

### ISSUE THREAD

**Issue by kou** [apache/arrow#41405]
### Describe the enhancement requested

GH-40441 migrated GLib front page from apache/arrow-site to Sphinx but our release script still uses apache/arrow-site's one.

### Component(s)

Documentation, GLib, Release

**Comment by kou** [comment]
The GLib front page: https://arrow.apache.org/docs/c_glib/

**Comment by kou** [comment]
Issue resolved by pull request 41406
https://github.com/apache/arrow/pull/41406

**Comment by kiszk** [comment]
@github-actions crossbow submit test-conda-python-3.10-spark-v3.5.0

**Comment by kou** [comment]
@github-actions crossbow submit test-conda-python-3.10-spark-v3.5.0
