### ISSUE TITLE
[C++]  Support [Large]ListView and Map types for if_else, case_when, and coalesce

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#41418]
### Describe the bug, including details regarding any error messages, version, and platform.

Recently, when i looked into the case_when and related kernel functions' implementation(for solving other problems), i find we've forgotten to add some nested types like `list_view`, `large_list_view`, `map` into related functions which already supported these types.

### Component(s)

C++

**Comment by felipecrv** [comment]
Issue resolved by pull request 41419
https://github.com/apache/arrow/pull/41419
