### ISSUE TITLE
[C++][Gandiva] Function ascii_utf8 result is different on x86_64 and Aarch_64

### ISSUE THREAD

**Issue by DenisTarasyuk** [apache/arrow#41433]
### Describe the bug, including details regarding any error messages, version, and platform.

On x86 platform ascii_utf8 function returns negative values for ascii codes >127, on Arm this function returns positive values. This issues is caused by usage of const char* input parameter which is by default signed char on x86 and unsigned char on Arm.

### Component(s)

C++ - Gandiva

**Comment by kou** [comment]
Issue resolved by pull request 41434
https://github.com/apache/arrow/pull/41434
