### ISSUE TITLE
[R] Uninformative error message 

### ISSUE THREAD

**Issue by JosiahParry** [apache/arrow#41447]
### Describe the enhancement requested

There is a very uninformative error message that occurs when using `arrow::open_dataset()` It says

>  This build of the arrow package does not support Datasets

There is no information about how to build the package such that it does support datasets. Additionally, searching around the package source i found the command `arrow_info()` which lists a number of capabilities—just about all of them off. It would be nice if the package told you how to get these capabilities 

### Component(s)

R

**Comment by assignUser** [comment]
Hi @JosiahParry , thanks for the report and sorry for the inconvenience.

The latest binary build of the arrow R package (15.0.1) on CRAN has an issue just on macOS where it's missing most of its features, including Parquet. See https://github.com/apache/arrow/issues/40667 and https://github.com/apache/arrow/pull/41019 which added the more informative message you are looking for :)

Your options right now are:

- Wait for 16.1.0 which will be released in the next few weeks
- Install arrow from source `install.packages("arrow", type = "source")`
- Install arrow from https://apache.r-universe.dev/arrow. Those binaries all have the regular set of features enabled.

I am going to close this message as your actual issue (the error message) is resolved. Feel free to post here if you need further help getting arrow to run :)
