### ISSUE TITLE
[Python][Packaging] In python3.10, report GCC_7.0.0 not found

### ISSUE THREAD

**Issue by ZhengLChang** [apache/arrow#41454]
### Describe the bug, including details regarding any error messages, version, and platform.

<img width="767" alt="image" src="https://github.com/apache/arrow/assets/11661954/87a67521-1eaf-4665-972b-3befb9a12a6f">

### Component(s)

Python

**Comment by raulcd** [comment]
Could you share which version of pyarrow are you using and how did you install, please?

**Comment by ZhengLChang** [comment]
> Could you share which version of pyarrow are you using and how did you install, please?

The version is pyarrow-16.0.0.

**Comment by ZhengLChang** [comment]
> Could you share which version of pyarrow are you using and how did you install, please?

BTW, I try to compile pyarrow to use in other docker。But, I get a error like next. Package comman is `python setup.py build_ext --build-type=Release --bundle-arrow-cpp bdist_wheel`.

![image](https://github.com/apache/arrow/assets/11661954/c4594f94-0efa-468e-bf75-0a3e635690bd)

**Comment by raulcd** [comment]
Can you share a minimal Dockerfile to reproduce? I see you are using redhat with GCC 7 but is hard to tell how you are building Arrow CPP, installing dependencies, etcetera to reproduce.
Is this happening only with Arrow 16.0.0 or was happening before? We did release Arrow 16.0.0 a couple weeks ago and I want to discard any issues there. Thanks

**Comment by ZhengLChang** [comment]
> Can you share a minimal Dockerfile to reproduce? I see you are using redhat with GCC 7 but is hard to tell how you are building Arrow CPP, installing dependencies, etcetera to reproduce. Is this happening only with Arrow 16.0.0 or was happening before? We did release Arrow 16.0.0 a couple weeks ago and I want to discard any issues there. Thanks

Thank you for your attention. I understand now. It seems the error was due to an incorrect version of GLIBC in your Docker image.
