### ISSUE TITLE
[Python] StructArray.sort() errors with default arguments

### ISSUE THREAD

**Issue by a-reich** [apache/arrow#41464]
### Describe the bug, including details regarding any error messages, version, and platform.

[StructArray's sort method](https://arrow.apache.org/docs/python/generated/pyarrow.StructArray.html#pyarrow.StructArray.sort) is documented to have the parameter `by: str or None, default None`, however a simple example that leaves the argument as None raises:

```
arr = pa.array([{'x': 1, 'y': True}, {'x': 3.4, 'y': False}])
arr.sort()
####### exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 3971, in pyarrow.lib.StructArray.sort
  File "/home/asaf/.local/lib/python3.12/site-packages/pyarrow/compute.py", line 263, in wrapper
    return func.call(args, options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 385, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Invalid sort key column: No match for FieldRef.Name() in x: double
y: bool
```
I am running pyarrow 16.0.0, Python 3.12, on Windows WSL. 

I *think* the cause is a simple mistake in this line? https://github.com/apache/arrow/blob/b609de374c7c00e1537eb8092e1ff2db718d2b61/python/pyarrow/array.pxi#L3973

I can send a basic PR with that fix and a test soon. But I'm not sure if I'll be able to build & test locally. Thanks!

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
@a-reich Thanks for the report, a PR is certainly welcome!

**Comment by raulcd** [comment]
As per how to build and test, If you add a test that reproduces the issue it can be tested on CI.

**Comment by a-reich** [comment]
take

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 41495
https://github.com/apache/arrow/pull/41495
