### ISSUE TITLE
[C++] Clean up Assorted Warnings to get a clean nanoarrow build

### ISSUE THREAD

**Issue by WillAyd** [apache/arrow#41478]
### Describe the bug, including details regarding any error messages, version, and platform.

There are still a few outstanding build warnings when trying to compile nanoarrow against Arrow, mostly around unused parameters and redundant moves

https://github.com/apache/arrow-nanoarrow/actions/runs/8912697432/job/24476664226?pr=448#step:7:144

### Component(s)

C++

**Comment by bkietz** [comment]
Issue resolved by pull request 41487
https://github.com/apache/arrow/pull/41487
