### ISSUE TITLE
[Python] _Py_IsFinalizing will be removed in Python 3.13

### ISSUE THREAD

**Issue by tacaswell** [apache/arrow#41475]
### Describe the bug, including details regarding any error messages, version, and platform.

`_Py_IsFinalizing` was removed in https://github.com/python/cpython/pull/106400 and replaced with a public version in https://github.com/python/cpython/pull/108032 .

This function is used 5 places in `udf.cc` for example: https://github.com/apache/arrow/blob/0ef7351986ee8b967e210d0f9c7a9c8e4d4038fd/python/pyarrow/src/arrow/python/udf.cc#L49-L53 which prevents building on Python 3.13.

Presumably this will need to be version gated on the version of CPython, but I am not sure how you prefer to do that in arrow.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Thanks for the heads up! (cc @pitrou)

> Presumably this will need to be version gated on the version of CPython, but I am not sure how you prefer to do that in arrow.

I assume we can use an `#if` / `#else` directive with one of the version macros that CPython exposes (https://docs.python.org/3/c-api/apiabiversion.html). 
From a quick look it seems we actually don't yet have any version specific code for CPython.

**Comment by tacaswell** [comment]
https://github.com/cython/cython/blob/a6d810b970c21948c7fcdeec2cf28769e716e4a9/Cython/Utility/ModuleSetupCode.c#L671-L703 is an example of how cython does it internally (which is the project where I have seen this done the most at the c level).

**Comment by raulcd** [comment]
Issue resolved by pull request 42034
https://github.com/apache/arrow/pull/42034
