### ISSUE TITLE
[Java] Performance uberjar is empty

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#41471]
### Describe the bug, including details regarding any error messages, version, and platform.

Performance uberjar `benchmarks.jar` is actually mostly empty and does not allow to run benchmark tests from commandline in an easy way.

The main issue is that JMH benchmarks are under `src/test/java` instead of `src/main/java` and `maven-shade-plugin` only consider main classes/jars.

There's a secondary issue regarding to JMH annotations which are not processed because top-level parent project defines its own annotations processors.

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41473
https://github.com/apache/arrow/pull/41473
