### ISSUE TITLE
[C++] Spurious duplicate registration of file:// factory

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#41470]
### Describe the bug, including details regarding any error messages, version, and platform.

As observed in https://github.com/apache/arrow/pull/41309 , some macos builds are [emitting key error](https://github.com/ursacomputing/crossbow/actions/runs/8871324532/job/24354134578#step:6:11011) due to duplicate registration of file:// factories. This should be fixable by reusing deduplication logic already in place for merging registries.

### Component(s)

C++

**Comment by lidavidm** [comment]
Issue resolved by pull request 41466
https://github.com/apache/arrow/pull/41466
