### ISSUE TITLE
[CI][C++] RapidJSON related build failure on AppVeyor

### ISSUE THREAD

**Issue by kou** [apache/arrow#41509]
### Describe the bug, including details regarding any error messages, version, and platform.

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/49736306#L1461

```text
FAILED: src/arrow/CMakeFiles/arrow_integration_shared.dir/Unity/unity_0_cxx.cxx.obj 
C:\Miniconda38-x64\envs\arrow\Library\bin\ccache.exe C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DARROW_EXPORTING -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DPROTOBUF_USE_DLLS -DUSE_IMPORT_EXPORT -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -IC:\projects\arrow\cpp\build\src -IC:\projects\arrow\cpp\src -IC:\projects\arrow\cpp\src\generated -external:IC:\Miniconda38-x64\envs\arrow\Library\include\rapidjson -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING  /EHsc /wd5105 /bigobj /utf-8 /W3 /wd4800 /wd4996 /wd4065  /WX /MP /MD /Od /UNDEBUG -std:c++17 -MD /showIncludes /Fosrc\arrow\CMakeFiles\arrow_integration_shared.dir\Unity\unity_0_cxx.cxx.obj /Fdsrc\arrow\CMakeFiles\arrow_integration_shared.dir\ /FS -c C:\projects\arrow\cpp\build\src\arrow\CMakeFiles\arrow_integration_shared.dir\Unity\unity_0_cxx.cxx
C:\projects\arrow\cpp\src\arrow/integration/json_internal.h(26): fatal error C1083: Cannot open include file: 'rapidjson/document.h': No such file or directory
[37/451] Building CXX object src\arrow\CMakeFiles\arrow_csv_shared.dir\Unity\unity_0_cxx.cxx.obj
ninja: build stopped: subcommand failed.
```

### Component(s)

C++, Continuous Integration

**Comment by kou** [comment]
This was triggered by the recent conda-forge update: https://github.com/conda-forge/rapidjson-feedstock/pull/7

It uses unreleased RapidJSON but unreleased RapidJSON has a CMake related problem: https://github.com/Tencent/rapidjson/issues/2192

**Comment by kou** [comment]
If the conda-forge's rapidjson package applies https://github.com/Tencent/rapidjson/pull/2193 as a workaround ( https://github.com/conda-forge/rapidjson-feedstock/issues/8 ), our CI will be fixed eventually.
If it's not applied, we should pin the conda-forge's rapidjson package.

**Comment by felipecrv** [comment]
> If it's not applied, we should pin the conda-forge's rapidjson package.

Is that hard to do?

**Comment by kou** [comment]
No.

**Comment by xhochy** [comment]
I'll update the conda-forge package with the patch

**Comment by kou** [comment]
Thanks.
I've re-run the AppVeyor job and confirmed that this problem has been fixed.
