### ISSUE TITLE
[Python] pandas roundtrip failing with decimal in column index

### ISSUE THREAD

**Issue by jrversteegh** [apache/arrow#41502]
### Describe the bug, including details regarding any error messages, version, and platform.

```
pd.DataFrame({Decimal(88): [88]}).to_parquet("test.parquet")
pd.read_parquet("test.parquet")

```
will fail with `TypeError: data type 'decimal' not understood`

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Resolved by https://github.com/apache/arrow/pull/41503
