### ISSUE TITLE
[C++][Compute] Redundant logic for ArrayData as ExecResults in ExecScalarCaseWhen

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#41529]
### Describe the bug, including details regarding any error messages, version, and platform.

This logic below branch will never be executed with current kernels:
https://github.com/apache/arrow/blob/c8cf61c569886ff18c88e29c447a98ab6dedbd92/cpp/src/arrow/compute/kernels/scalar_if_else.cc#L1487

The only way go into the `ArrayData`'s branch is input type is not `fixed_width`:
https://github.com/apache/arrow/blob/32885c91a1c94f1c8530815f4d4b8fc068859de8/cpp/src/arrow/compute/kernels/scalar_if_else.cc#L2691-L2695.

The non-fixed-width's type has their own `CaseWhenFunctor` like: 
```c
struct CaseWhenFunctor<DictionaryType> {...}
struct CaseWhenFunctor<Type, enable_if_union<Type>> {...}
struct CaseWhenFunctor<FixedSizeListType> {...}
struct CaseWhenFunctor<StructType>{...}
struct CaseWhenFunctor<MapType>{...}
struct CaseWhenFunctor<Type, enable_if_var_size_list<Type>> {...}
struct CaseWhenFunctor<Type, enable_if_base_binary<Type>> {...}
```

### Component(s)

C++

**Comment by felipecrv** [comment]
Issue resolved by pull request 41380
https://github.com/apache/arrow/pull/41380
