### ISSUE TITLE
[CI][Dev] Remove unnecessay requirement for six on merge script

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#41527]
We should remove the `six` dependency from the merge script and from the installation on the dev workflow.

_Originally posted by @jorisvandenbossche in https://github.com/apache/arrow/pull/41041#discussion_r1586125055_

### Component(s)

Continuous Integration, Developer Tools

**Comment by kou** [comment]
Issue resolved by pull request 43087
https://github.com/apache/arrow/pull/43087

**Comment by kou** [comment]
@llama90 Could you write "take" only comment here?
