### ISSUE TITLE
[Go] Importing a C array with 0 length leaks memory

### ISSUE THREAD

**Issue by zeroshade** [apache/arrow#41534]
### Describe the bug, including details regarding any error messages, version, and platform.

In the Go `cdata` package, importing an array of length 0 ends up leaking the memory for the internal `ArrowArray` that we allocate to hold the source and tie it to the buffers. This was found by an ASAN run of an ADBC test.

### Component(s)

Go

**Comment by lidavidm** [comment]
Issue resolved by pull request 41535
https://github.com/apache/arrow/pull/41535
