### ISSUE TITLE
[C++] Thirdparty: Bump xsimd to 13.0.0

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#41547]
### Describe the enhancement requested

Arrow now uses xsimd 9.0.1, currently, some conversion for batch is now support in neon, see: https://github.com/apache/arrow/pull/40335#issuecomment-1983609146 . So we can upgrading it.

The xsimd currently released 13.0.0, see: https://github.com/xtensor-stack/xsimd/issues/1015

For conan, seems community is updating it: https://github.com/conan-io/conan-center-index/pull/23859 . Maybe we can wait for a while

### Component(s)

C++

**Comment by wgtmac** [comment]
If there isn't any API break, we don't have to wait for conan upstream.

**Comment by kou** [comment]
Issue resolved by pull request 41548
https://github.com/apache/arrow/pull/41548
