### ISSUE TITLE
[C++][Parquet] Encoding: DeltaLengthByteArrayEncoder don't have right stats when Put with Array

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#41545]
### Describe the enhancement requested

`DeltaLengthByteArrayEncoder` works well, however, when put with arrow-array, the statistics would be wrong. Because `EstimatedDataEncodedSize()` [1] uses `encoded_size_`, but it's only incremented in `Put/PutSpaced` [2], but not handled in Array put [3]. This makes statistics wrong, which makes a page grows larger than INT32_MAX [4]

Luckily, this doesn't affect the result of encoding, just makes the statistics smaller than expected.

[1] https://github.com/apache/arrow/blob/main/cpp/src/parquet/encoding.cc#L2749
[2] https://github.com/apache/arrow/blob/main/cpp/src/parquet/encoding.cc#L2814
[3] https://github.com/apache/arrow/blob/main/cpp/src/parquet/encoding.cc#L2763-L2775
[4] https://github.com/apache/arrow/blob/d10ebf055a393c94a693097db1dca08ff86745bd/cpp/src/parquet/column_writer.cc#L1561-L1563

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 41546
https://github.com/apache/arrow/pull/41546

**Comment by alamb** [comment]
BTW thank you @mapleFU  for pushing the open parquet C++ implementation along ❤️

**Comment by mapleFU** [comment]
Thanks! I'm a Parquet C++ user and benifit from it's code so I've duty to backport bugfix and optimizations, and thanks the help with community I can use it in a better way
