### ISSUE TITLE
[Go] Time zone info not preserved on parquet roundtrip

### ISSUE THREAD

**Issue by candiduslynx** [apache/arrow#41557]
### Describe the bug, including details regarding any error messages, version, and platform.

I think that https://github.com/apache/arrow/pull/39467 may have introduced the following bug:
1. Create a record with `arrow.FixedTypes.Timestamp_us` column & some values (note that this column has `"UTC"` zone set)
2. Write a file
3. Read the file & record from it

The resulting column would have empty time zone.

### Component(s)

Go

**Comment by zeroshade** [comment]
I'll take a look at this tomorrow

**Comment by zeroshade** [comment]
@candiduslynx Can you provide me with some explicit sample code that shows this issue?

When testing this against `main` on the Arrow repo I'm unable to replicate the issue you're seeing, see below:

```go
func TestReadWriteTimestamp() {
  mem := memory.DefaultAllocator
  fld := arrow.Field{Name: "ts", Type: array.FixedWidthTypes.Timestamp_us}
  sc := arrow.NewSchema([]arrow.Field{fld}, nil)
  bldr := array.NewRecordBuilder(mem, sc)
  defer bldr.Release()

  tsbuilder := bldr.Field(0).(*array.TimestampBuilder)
  tsbuilder.AppendValues([]arrow.Timestamp{123450000, 567890000}, nil)

  rec := bldr.NewRecord()
  defer rec.Release()

  tbl := array.NewTableFromRecords(sc, []arrow.Record{rec})
  defer tbl.Release()
  // tbl schema column 1 has "UTC" for timezone!

  var buf bytes.Buffer
  err := pqarrow.WriteTable(tbl, &buf, tbl.NumRows(),
      parquet.NewWriterProperties(parquet.WithAllocator(mem)),
            pqarrow.DefaultWriterProps()))
  if err != nil {
      panic(err)
  }

  rdr := bytes.NewReader(buf.Bytes())
  out, err := pqarrow.ReadTable(context.Background(), rdr,
       parquet.NewReaderProperties(mem), pqarrow.ArrowReadProperties{}, mem)
  if err != nil {
      panic(err)
  }
  defer out.Release()

  fmt.Println(out)
}
```

I get the output:

```shell
schema:
  fields: 1
    - ts: type=timestamp[us, tz=UTC]
    metadata: ["PARQUET:field_id": "-1"]
ts: [[123450000 567890000]]
```

Note that it still has the UTC for the timezone in the table that I read out from the file. What version of arrow/parquet are you using? Are you writing/reading the table differently than in my example above?

**Comment by candiduslynx** [comment]
@zeroshade I think I misdirected the issue, we have an issue with DuckDB reading when the data from them is returned with stripped `UTC` timezone.
Closing as incorrect
