### ISSUE TITLE
[C++][Python] Support reading/writing key-value metadata from/to ColumnChunkMetaData

### ISSUE THREAD

**Issue by clee704** [apache/arrow#41579]
### Describe the enhancement requested

According to the standard, ColumnMetaData can have key_value_metadata which is a list of KeyValue.

https://parquet.apache.org/docs/file-format/metadata/

![image](https://github.com/apache/arrow/assets/220039/bdf99564-b83e-4690-a3be-f3e522fb929b)

### Component(s)

C++

**Comment by mapleFU** [comment]
Issue resolved by pull request 41580
https://github.com/apache/arrow/pull/41580
