### ISSUE TITLE
[Docs] Duplicate contents

### ISSUE THREAD

**Issue by llama90** [apache/arrow#41587]
### Describe the bug, including details regarding any error messages, version, and platform.

Duplicate content was found.

I did not find all the content, but there is duplicate content in the document as follows:

- [API Reference](https://arrow.apache.org/docs/python/api.html)
  - Compute Functions
    - `pyarrow.compute.CountOptions` <img width="1638" alt="image" src="https://github.com/apache/arrow/assets/6668548/5caee36d-1c2d-4077-a6dd-90c92b04ece5">
    - `pyarrow.compute.ScalarAggregateOptions` <img width="305" alt="image" src="https://github.com/apache/arrow/assets/6668548/705e5314-9abb-4558-86b0-50b663dcbe53">
    - `pyarrow.compute.TDigestOptions` <img width="306" alt="image" src="https://github.com/apache/arrow/assets/6668548/7a7417af-0270-433e-9edb-561e5b9a2897">

### Component(s)

Documentation

**Comment by AlenkaF** [comment]
Issue resolved by pull request 41588
https://github.com/apache/arrow/pull/41588
