### ISSUE TITLE
[Java] Improve `BaseRepeatedValueVector` function on `isEmpty` and `isNull` operations

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#41590]
### Describe the enhancement requested

Referring to `ListVector` base class `BaseRepeatedValueVector` at https://github.com/apache/arrow/blob/main/java/vector/src/main/java/org/apache/arrow/vector/complex/BaseRepeatedValueVector.java#L358-L367, the `isEmpty` and `isNull` returns a default value which is rather misleading. Since the sub-class contains the functionality, it would be better to make it abstract or throw as discussed [here](https://github.com/apache/arrow/pull/41285#discussion_r1593798045).

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41601
https://github.com/apache/arrow/pull/41601
