### ISSUE TITLE
[Go] Can't read `date64` value from CSV while write is supported

### ISSUE THREAD

**Issue by candiduslynx** [apache/arrow#41594]
### Describe the bug, including details regarding any error messages, version, and platform.

on `v16` can write `date64` column, but can't read it

### Component(s)

Go

**Comment by candiduslynx** [comment]
take

**Comment by davlee1972** [comment]
Can add this one to the list.. 
https://github.com/apache/arrow/issues/41488

**Comment by zeroshade** [comment]
Issue resolved by pull request 41595
https://github.com/apache/arrow/pull/41595
