### ISSUE TITLE
Enable updating Parquet key-value metadata of opened ParquetWriter before closing

### ISSUE THREAD

**Issue by kylebarron** [apache/arrow#41608]
### Describe the enhancement requested

In pyarrow, it would be great to have the ability to update Parquet key-value metadata of an existing `ParquetWriter` instance before closing the file. For example:

```py
import pyarrow.parquet as pq

with pq.ParquetWriter("output.parquet", schema) as writer:
    writer.write_batch(...)
    writer.add_key_value_metadata({b"hello": "world"})
```

This is akin to the arrow-rs [`ArrowWriter::append_key_value_metadata`](https://docs.rs/parquet/latest/parquet/arrow/arrow_writer/struct.ArrowWriter.html#method.append_key_value_metadata), which lets you mutate an existing writer to add key-value metadata before writing the final metadata.

My use case for this is in writing to [GeoParquet](https://geoparquet.org/) efficiently. Part of the GeoParquet metadata (stored as Parquet key-value metadata) includes an optional bounding box of all geometries in the file. But many applications might need a pass over the dataset to infer the bounding box of the data. If this key-value metadata can only be defined when _opening_ the `ParquetWriter`, then streaming applications (such as converting other file formats to GeoParquet) might need _two_ passes over the data: one to infer the bounding box and construct the schema to pass to the `ParquetWriter` constructor, and other to actually write the batches.
### Component(s)

Python

**Comment by mapleFU** [comment]
C++ has this API, but this might not integrated to Python SDK. Would you like to support this?

**Comment by kylebarron** [comment]
That would be great. I don't know C++ myself so I can't help out. But I may be able to test a branch if necessary

**Comment by mapleFU** [comment]
I would finish it in this week

**Comment by mapleFU** [comment]
Issue resolved by pull request 41633
https://github.com/apache/arrow/pull/41633

**Comment by mapleFU** [comment]
Sorry for delay, this would be in 17.0.0
