### ISSUE TITLE
[Docs][CI] Enable more sphinx-lint rules for documentation

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#41611]
### Describe the enhancement requested

The work in https://github.com/apache/arrow/issues/39990 enabled sphinx-lint as a pre-commit hook but enabled just two rules so as to start off simple:

- trailing-whitespace
- missing-final-newline

sphinx-lint offers a total of 22 rules and some of these are clearly useful as, at least at the time of writing, they catch meaningful meaningful problems in our documentation sources.

We should consider the full ruleset and enabling as many as we think offer good value.

### Component(s)

Continuous Integration, Documentation

**Comment by amoeba** [comment]
The current docs violates just six of the 22 sphinx-lint rules. Of these, most are useful and catch real issues. For each, I've noted which I think we should and shouldn't enable:

- dangling-hyphen
  - No. This is meant to catch hyphens breaking up long words for hard wrapping but we use dangling hyphens for some anchors and our use looks legit.
- missing-space-after-literal
  - Yes. This caught a bug in https://arrow.apache.org/docs/java/algorithm.html and will help us catch future issues.
- horizontal-tab
  - Yes. This seems like a good catch since tabs don't get treated correctly in HTML anyway and it makes it hard to know whether the source will render correctly.
- missing-final-newline
  - Yes. A bit nitpicky but it makes things more regular which should avoid noise in diffs.
- missing-underscore-after-hyperlink
  - Yes. Caught a broken link in https://arrow.apache.org/docs/format/Integration.html.
- trailing-whitespace
  - Yes. Again a bit nitpicky but it makes the docs more regular which avoids diff noise.
- unbalanced-inline-literals-delimiters
  - Yes. This catches real issues where authors forget to close their literals.

I think we could get away with just disabling `dangling-hyphen` and enabling all other checks. I'll still go through the other checks to make sure we don't enable something we don't want but, since we don't violate most of the rules, we can disable any we find that don't add value in the future. I'll update here once I do that.

**Comment by AlenkaF** [comment]
Thank you for working on this @amoeba and adding a thorough summary. Agree with what is added till now 👍

**Comment by amoeba** [comment]
Thanks @AlenkaF. I marked the PR as ready for review and I tagged you for review in addition to @jorisvandenbossche since he saw the last PR.

**Comment by AlenkaF** [comment]
Issue resolved by pull request 41612
https://github.com/apache/arrow/pull/41612
