### ISSUE TITLE
[Docs][C++] Is arrow::dataset namespace still experimental?

### ISSUE THREAD

**Issue by rouault** [apache/arrow#41623]
### Describe the enhancement requested

https://arrow.apache.org/docs/cpp/dataset.html has this warning "The arrow::dataset namespace is experimental, and a stable API is not yet guaranteed." . This was added 3 years ago per https://github.com/apache/arrow/commit/6f2e05d7e2bdd8f58adb96251bd07d744973e2c0
The GDAL Parquet driver has been using (part of) this API for 2 years now, and I don't recall any backward incompatible change in what we used, so it seems to me that this is fairly stable, and the warning could probably be dropped

### Component(s)

C++, Documentation

**Comment by jorisvandenbossche** [comment]
I would assume the warning can indeed be dropped (at least in general, there might still be some individual newer APIs that could be marked as experimental). 

cc @westonpace

**Comment by westonpace** [comment]
+1, this API is no longer experimental

**Comment by llama90** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 43148
https://github.com/apache/arrow/pull/43148
