### ISSUE TITLE
[Benchmarking] Out-of-source python build breaks benchmarks

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#41630]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/pull/41455 broke some benchmark as they use source=build dir. The changes lead to the 'build dir' being removed, which of course also removes the source files.

### Component(s)

Benchmarking

**Comment by assignUser** [comment]
cc @kou

**Comment by kou** [comment]
Oh, sorry. Can we show a failed build log?

**Comment by assignUser** [comment]
Issue resolved by pull request 41631
https://github.com/apache/arrow/pull/41631

**Comment by assignUser** [comment]
You could probably see the issue from the change I made but the important part from the log was this:
```
rm -rf .../arrow/python
cp -aL .../arrow/python .../arrow/python
cp: cannot stat '.../arrow/python': No such file or directory
```
