### ISSUE TITLE
[Go][Parquet] Expand BYTE_STREAM_SPLIT to support FIXED_LEN_BYTE_ARRAY, INT32 and INT64

### ISSUE THREAD

**Issue by benibus** [apache/arrow#41640]
### Describe the enhancement requested

Implement the format addition described in https://issues.apache.org/jira/browse/PARQUET-2414. An equivalent C++ implementation has already been done in https://github.com/apache/arrow/pull/40094.

### Component(s)

Go, Parquet

**Comment by zeroshade** [comment]
Issue resolved by pull request 43066
https://github.com/apache/arrow/pull/43066
