### ISSUE TITLE
[JS] When I install any apache-arrow version beyond 14 it throws error

### ISSUE THREAD

**Issue by pradeep22248** [apache/arrow#41649]
### Describe the bug, including details regarding any error messages, version, and platform.

it gives the error  npm ERR! path C:\hcc\hcc_interactive_map\web-ui\node_modules\apache-arrow\bin\arrow2csv.cjs

### Component(s)

Other

**Comment by raulcd** [comment]
Could you share more details? What is the version of npm used? Can you share slightly more details on how are you installing and more context on the logs? What happens if you install Arrow 13?

**Comment by trxcllnt** [comment]
Fixed in #43342
