### ISSUE TITLE
[CI][Python] Windows wheel builds build both static and shared libraries of Arrow C++

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#41652]
### Describe the enhancement requested

I might be misinterpreting this, but it [seems](https://github.com/ursacomputing/crossbow/actions/runs/9076259014/job/24938574537#step:7:787) that Windows wheel builds currently build both static and shared libraries of Arrow C++, therefore compiling everything twice:
```
[...]
  unity_1_cxx.cxx
  unity_0_cxx.cxx
  key_hash_internal_avx2.cc
  key_map_internal_avx2.cc
  compare_internal_avx2.cc
  encode_internal_avx2.cc
  util_avx2.cc
  aggregate_basic_avx2.cc
  aggregate_basic_avx512.cc
  arrow_compute_shared.vcxproj -> C:\arrow-build\src\arrow\arrow_compute_shared.dir\Release\arrow_compute_shared.lib
[...]
  unity_1_cxx.cxx
  unity_0_cxx.cxx
  key_hash_internal_avx2.cc
  key_map_internal_avx2.cc
  compare_internal_avx2.cc
  encode_internal_avx2.cc
  util_avx2.cc
  aggregate_basic_avx2.cc
  aggregate_basic_avx512.cc
  arrow_compute_static.vcxproj -> C:\arrow-build\src\arrow\arrow_compute_static.dir\Release\arrow_compute_static.lib
```

This is despite `ARROW_BUILD_STATIC` being disabled:
```
--   ARROW_BUILD_STATIC=OFF [default=ON]
--       Build static libraries
--   ARROW_BUILD_SHARED=ON [default=ON]
--       Build shared libraries
```

### Component(s)

Continuous Integration, Packaging, Python

**Comment by pitrou** [comment]
@kou @raulcd Thoughts?

**Comment by kou** [comment]
Oh, sorry. It's my fault. I should have add `ARROW_BUILD_SHARED`/`ARROW_BUILD_STATIC` to `arrow_add_object_library()` in #39824.

**Comment by kou** [comment]
Issue resolved by pull request 41658
https://github.com/apache/arrow/pull/41658
