### ISSUE TITLE
[MATLAB] Add new `arrow.c.Array` MATLAB class which wraps a C Data Interface format `ArrowArray` C struct 

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#41653]
### Describe the enhancement requested

Now that the MATLAB interface has support for `arrow.tabular.RecordBatch` and `arrow.array.Array`, we should add support for the [C Data Interface](https://arrow.apache.org/docs/format/CDataInterface.html) format.

The C Data Interface is based around two C struct definitions: (1) `ArrowArray` and (2) `ArrowSchema`.

We should start by adding a new MATLAB class (e.g. `arrow.c.Array`) which wraps the underlying `ArrowArray` C struct.

Later, we can add another new MATLAB class (e.g. `arrow.c.Schema`) which wraps the `ArrowSchema` C struct.

Once we have added these two MATLAB classes, we can then add import and export functionality to share the Arrow memory between multiple language runtimes running in the same process.

This would help enable workflows like sharing Arrow data between the MATLAB Interface to Arrow and `pyarrow` running within the MATLAB process via the [MATLAB interface to Python](https://www.mathworks.com/help/matlab/call-python-libraries.html)).

### Component(s)

MATLAB

**Comment by sgilmore10** [comment]
Issue resolved by pull request 41655
https://github.com/apache/arrow/pull/41655
