### ISSUE TITLE
[Java] Update Unit Tests to use `org.junit.jupiter.api` 

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#41680]
### Describe the enhancement requested

At the moment, test cases are using an older API version of Junit, and this should be upgraded to use the latest API. 
It would be best if we can do this module per module by creating an issue per module and list it here.

- [x] https://github.com/apache/arrow/issues/42002
- [x] https://github.com/apache/arrow/issues/42025
- [x] https://github.com/apache/arrow/issues/42030
- [x] c
- [x] https://github.com/apache/arrow/issues/42042
- [x] https://github.com/apache/arrow/issues/42045
- [x] https://github.com/apache/arrow/issues/42162
- [x] https://github.com/apache/arrow/issues/42164
- [x] https://github.com/apache/arrow/issues/42165
- [x] performance
- [x] https://github.com/apache/arrow/issues/42092
- [x] https://github.com/apache/arrow/issues/42193

### Component(s)

Java

**Comment by llama90** [comment]
@vibhatha I have verified the `c` module using only JUnit 5. Please cross-check when you have free time. Thank you.

**Comment by vibhatha** [comment]
> @vibhatha I have verified the `c` module using only JUnit 5. Please cross-check when you have free time. Thank you.
> 
> 
> 
> 

@llama90 thank you for checking this one. I will verify. I will update tomorrow. Really appreciate your support on this upgrade.

**Comment by vibhatha** [comment]
@llama90 You are correct, we don't need to work on `c` module. It is already in JUNIT5. Thanks for verifying this.

**Comment by llama90** [comment]
@vibhatha I think I will start after merging the spotless changes for each module to avoid conflicts.

**Comment by vibhatha** [comment]
@llama90 that's good idea.

**Comment by vibhatha** [comment]
@llama90 Done! Thanks for looking into this.

**Comment by llama90** [comment]
@vibhatha I attached the remaining issues for updating the contents.

- https://github.com/apache/arrow/issues/42045
- https://github.com/apache/arrow/issues/42162
- https://github.com/apache/arrow/issues/42164
- https://github.com/apache/arrow/issues/42165

**Comment by llama90** [comment]
No problem! Have a nice day.

**Comment by lidavidm** [comment]
@vibhatha after this is done, we also need to remove all JUnit 4 dependencies and preferably exclude them so we don't accidentally re-take a dependency on JUnit 4

**Comment by vibhatha** [comment]
@lidavidm I will work on that. Definitely.

**Comment by vibhatha** [comment]
@lidavidm issue created: https://github.com/apache/arrow/issues/42193

**Comment by llama90** [comment]
Finally, we've completed this issue. Thank you for your effort, @lidavidm and @vibhatha.

It was interesting and helped me learn a lot. If there are any other issues I can help solve, please let me know. I'm not yet familiar with the entire codebase in Java, but I'm getting the hang of it. 

Thank you!

**Comment by lidavidm** [comment]
@llama90 thank you for finishing this off! 

@vibhatha we can close now right?

**Comment by vibhatha** [comment]
Yes @lidavidm we can. 

Thanks a lot @llama90 for pushing this till the end. 🙏
