### ISSUE TITLE
[GLib] Separate version macros for each GLib library

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41681]
### Describe the enhancement requested

In order to support building the GLib libraries with MSVC and correctly applying dllimport and dllexport attributes depending on whether a library is being compiled or consumed, we should have separate `*_AVAILALBLE_IN_*` and `*_DEPRECATED_IN_*` macros for each GLib library.

See discussion at https://github.com/apache/arrow/pull/41599#discussion_r1596170268

### Component(s)

GLib

**Comment by kou** [comment]
Issue resolved by pull request 41721
https://github.com/apache/arrow/pull/41721
