### ISSUE TITLE
[Go][Parquet] BufferedPageWriter reallocates memory during cleanup, causing a leak

### ISSUE THREAD

**Issue by joellubi** [apache/arrow#41697]
### Describe the bug, including details regarding any error messages, version, and platform.

On `bufferedPageWriter.Close()` the `BufferWriter.Finish()` method is called but not `BufferWriter.Release()`. The doc for `Finish` states that the caller must still release the buffer.

Blocking: https://github.com/apache/arrow-adbc/pull/1866

### Component(s)

Go, Parquet

**Comment by jhump** [comment]
@joellubi, @zeroshade, this appears to have been fixed in #41698, right? Is this issue still open because the fix isn't yet released? I see that PR was merged after the last release (v16.1.0). Any chance of a v16.1.1 soon that would contain this fix?

**Comment by joellubi** [comment]
Hi @jhump. You should be able to update your Go dependency to the latest commit of `v17` to get a "preview" of all the latest changes, including this one ([example](https://github.com/apache/arrow-adbc/pull/1866/commits/c02ec846e14253262b031ce43310f7be44d8c366)). This may work for your needs.

Otherwise `v17` should officially release relatively soon, likely sometime in July ([ref](https://lists.apache.org/thread/hob7ozny5f49mgc5hpxz9qlyytp8w38v)).

I would consider this issue closed now. I've added it to the 17.0.0 milestone and closed it to reflect its current state.

**Comment by jhump** [comment]
Thanks, @joellubi!
