### ISSUE TITLE
[R] Windows: R4.4: Parquet File is not released (Windows 1224 error) After Reading it via Rserve

### ISSUE THREAD

**Issue by hidekoji** [apache/arrow#41714]
### Describe the bug, including details regarding any error messages, version, and platform.

Platform: Windows (Microsoft Windows 11 Home) version: 10.0.22621
arrow: 15.0.1
R: 4.4.0

```r
 "R version 4.4.0 (2024-04-24 ucrt)",
        "Platform: x86_64-w64-mingw32/x64",
        "Running under: Windows 8 x64 (build 9200)",
        "",
        "Matrix products: default",
        "",
        "",
        "locale:",
        "[1] LC_COLLATE=Japanese_Japan.utf8      LC_CTYPE=English_United States.utf8",
        "[3] LC_MONETARY=Japanese_Japan.utf8     LC_NUMERIC=C                       ",
        "[5] LC_TIME=Japanese_Japan.utf8        ",
        "",
        "time zone: America/Los_Angeles",
        "tzcode source: internal",
        "",
        "attached base packages:",
        "[1] stats     graphics  grDevices utils     datasets  methods   base     ",
        "",
        "other attached packages:",
        " [1] stringi_1.8.4      jsonlite_1.8.8     vroom_1.6.5        rmarkdown_2.26    ",
        " [5] knitr_1.46         crayon_1.5.2       exploratory_10.0.3 zipangu_0.3.2     ",
        " [9] bit64_4.0.5        bit_4.0.5          tibble_3.2.1       dplyr_1.1.4       ",
        "[13] RcppRoll_0.3.0     forcats_1.0.0      cpp11_0.4.7        readr_2.1.5       ",
        "[17] stringr_1.5.1      tidyr_1.3.1        hms_1.1.3          lubridate_1.9.3   ",
        "[21] janitor_2.2.0     ",
        "",
```

1. Read a parquet file from one Rserve session (In the below screenshot the one "Project Main Window")

![image](https://github.com/apache/arrow/assets/230637/6d5339fc-768b-4f3b-9cad-1e1428c52bde)

2. After reading a parquet file, It still keeps the resource and it does not release it. So accessing the parquet file from other Rserve process causes `Windows error 1224 The requested operation cannot be performed on a file  with a user-mapped section open` If I tried it with arrow 13.0.0.1, this issue did not happen. 

### Component(s)

Parquet, R

**Comment by assignUser** [comment]
Hey thanks for the report. Could you create a reprex as I am not familiar with Rserve.

**Comment by hidekoji** [comment]
Ok, I noticed that you do not need RServe and can reproduce it as follows:

1. On your Windows, open 2 Command Prompts and start R on each Command Prompt.
2. In the first Command Prompt try following:

``` r
arrow::write_parquet(mtcars, "~/test.parquet"); 
df <- arrow::read_parquet("~/test.parquet")
```

<sup>Created on 2024-05-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

3. In the second Command Prompt, try this

``` r
> arrow::write_parquet(mtcars,"~/test.parquet")
Error: IOError: Failed to open local file 'C:/Users/hidek/test.parquet'. Detail: [Windows error 1224] <
U+8981><U+6C42><U+3055><U+308C><U+305F><U+64CD><U+4F5C><U+306F><U+30E6><U+30FC><U+30B6><U+30FC> <U+30DE
><U+30C3><U+30D7> <U+30BB><U+30AF><U+30B7><U+30E7><U+30F3><U+3067><U+958B><U+3044><U+305F><U+30D5><U+30
A1><U+30A4><U+30EB><U+3067><U+306F><U+5B9F><U+884C><U+3067><U+304D><U+307E><U+305B><U+3093><U+3002>
>

```

<sup>Created on 2024-05-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by assignUser** [comment]
Ah thanks that makes it clearer. I think the default value of TRUE for [mmap](https://arrow.apache.org/docs/r/reference/read_parquet.html) is to blame
>mmap:   Use TRUE to use memory mapping where possible

Could you try setting that to `FALSE`?

**Comment by hidekoji** [comment]
Thanks, setting the `mmap=FALSE` fixed the issue as you suggested.

**Comment by assignUser** [comment]
Cool, I am closing the issue as completed. Feel free to comment/reopen if needed!
