### ISSUE TITLE
[C++] ARROW_FORCE_INLINE is incorrectly defined for MSVC builds

### ISSUE THREAD

**Issue by felipecrv** [apache/arrow#41711]
### Describe the bug, including details regarding any error messages, version, and platform.

I made a mistake in #40372 and defined `ARROW_FORCE_INLINE` as `__declspec(forceinline)` instead of `__forceinline` (the correct way) for MSVC.

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 41712
https://github.com/apache/arrow/pull/41712
