### ISSUE TITLE
[C++][Acero] An useless parameter for QueryContext::Init called in hash_join_benchmark

### ISSUE THREAD

**Issue by ZhangHuiGui** [apache/arrow#41720]
### Describe the bug, including details regarding any error messages, version, and platform.

My local compilation parameters will include the compilation of some basic benchmarks (with `ARROW_BUILD_OPENMP_BENCHMARKS=ON`). I discovered this compilation problem today. It seems that https://github.com/apache/arrow/issues/41334 of QueryContext::Init is not synchronized to hash_join_benchmark.cc, and CI has not found this problem. .
```shell
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DARROW_DATASET=ON -DARROW_COMPUTE=ON \
 -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=ON -DARROW_MIMALLOC=ON -DARROW_ORC=OFF \
 -DARROW_PARQUET=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DARROW_BUILD_EXAMPLES=ON \
 -DARROW_TESTING=ON -DARROW_BUILD_TESTS=ON -DARROW_CSV=ON -DARROW_BUILD_BENCHMARKS=ON \
 -DARROW_FLIGHT=ON -DARROW_WITH_RE2=OFF -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON \
-DARROW_WITH_BROTLI=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZSTD=ON -DARROW_WITH_BZ2=ON \
-DARROW_BUILD_OPENMP_BENCHMARKS=ON -DARROW_BUILD_DETAILED_BENCHMARKS=ON \
-DARROW_USE_ASAN=OFF -DARROW_RUNTIME_SIMD_LEVEL=SSE4_2 -DARROW_GANDIVA=OFF \
-DARROW_LLVM_USE_SHARED=OFF -DARROW_TEST_LINKAGE=shared -DARROW_BUILD_SHARED=ON \
-DARROW_S3=ON ..
```

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 41716
https://github.com/apache/arrow/pull/41716
