### ISSUE TITLE
[Java] Adding `variadicBufferCounts` to `RecordBatch`

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#41730]
### Describe the enhancement requested

The main integration effort including tests has been documented https://github.com/apache/arrow/issues/41729.  
As the first step introducing the `variadicBufferCounts` must be completed including some tests to evaluate it with view vectors. 

### Goals

1. Adding `variadicBufferCounts` to `ArrowRecordBatch` Java interface. 
2. Updating the classes which uses the `ArrowRecordBatch` interface to include the `variadicBufferCounts` attribute. The interfaces are `StructVectorLoader`, `StructVectorUnloader`, `VectorLoader`, `VectorUnloader` and corresponding test cases. 
3. `TypeLayout.getTypeBufferCount` and `TypeLayout.getTypeLayout` must be also updated to include the `FieldVector` usage and use IPC metadata from `ArrowRecordBatch` to obtain the accurate number of buffers. This steps proposes a new API which considers the vector as an input to the said methods. Thus we are adding a depcreation warning to the older API. This is required as we have to support variable width views with the new specification. 

### Non Goals

1. Note that the usage of `TypeLayout` function is in some other components like `JsonFileReader` and `JsonFileWriter`. So to get an accurate representation of buffers require concrete work on those two components. I propose to conduct that work separately.  

2. Also the `ValidateVectorBufferVisitor` needs to update to the updated new API, but it also requires some concrete work in updating corresponding test cases. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41732
https://github.com/apache/arrow/pull/41732
