### ISSUE TITLE
[CI] GitHub bot cannot run Java CIs 

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#41735]
### Describe the bug, including details regarding any error messages, version, and platform.

In a recent [PR](https://github.com/apache/arrow/pull/41718) it was observed that the following bot command is not working

```bash
@github-actions crossbow submit -g java
```

```bash
module 'pygit2' has no attribute 'GIT_OBJ_COMMIT'
The Archery job run can be found at: https://github.com/apache/arrow/actions/runs/9151003846
```

### Component(s)

Continuous Integration

**Comment by kou** [comment]
Issue resolved by pull request 41739
https://github.com/apache/arrow/pull/41739
