### ISSUE TITLE
[GLib] Allow getting a RecordBatchReader from a Dataset or Dataset Scanner

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41749]
### Describe the enhancement requested

In order to allow efficient processing of large datasets, it should be possible to read a dataset or a scanner using a RecordBatchReader rather than using the `to_table` method.

### Component(s)

GLib

**Comment by kou** [comment]
Issue resolved by pull request 41750
https://github.com/apache/arrow/pull/41750
