### ISSUE TITLE
[Python][Parquet] Documentation to parquet.write_table should be updated for new byte_stream_split encoding options

### ISSUE THREAD

**Issue by etseidl** [apache/arrow#41748]
### Describe the enhancement requested

The docstring for `parquet.write_table` still says BYTE_STREAM_SPLIT encoding is valid only for floating-point data. This should be updated now that other fixed length types are supported.

### Component(s)

Parquet, Python

**Comment by ianmcook** [comment]
cc @pitrou

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 41759
https://github.com/apache/arrow/pull/41759
