### ISSUE TITLE
[Python] Segfault when reading a RecordBatchReader constructed from an Arrow Table

### ISSUE THREAD

**Issue by Mytherin** [apache/arrow#41758]
### Describe the bug, including details regarding any error messages, version, and platform.

The following code snippet crashes for me when running PyArrow 16.1 in Python 3.12:

```py
import pyarrow as pa

print(pa.__version__)
# 16.1.0

tbl = pa.Table.from_pydict({"x": [11, 12], "y": ["c", "d"]})
t = pa.RecordBatchReader(tbl.to_batches())

print(t.read_all())
# zsh: segmentation fault  python3
```

### Component(s)

Python

**Comment by Mytherin** [comment]
Thanks! That does indeed work.

**Comment by jorisvandenbossche** [comment]
Thanks for the report! 
Almost all our classes define an `__init__` that raise an error, pointing to the correct constructor to use (like `RecordBatchReader.from_batches` in this case). But for some reason that is missing for RecordBatchReader ..

**Comment by jorisvandenbossche** [comment]
Opened a PR to add a more informative error message -> https://github.com/apache/arrow/pull/41773

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 41773
https://github.com/apache/arrow/pull/41773
