### ISSUE TITLE
[C++] take into account orc's capabilities for finding tzdb

### ISSUE THREAD

**Issue by h-vetinari** [apache/arrow#41755]
### Describe the enhancement requested

As one of the follow-ups to #36026, https://github.com/apache/orc/pull/1882 got merged into orc 2.0.1, which will use conda(-forge)'s `tzdata` also on windows, even if the `TZDIR` environment variable is not being set (inserting that variable into all user environments would have been very intrusive).

Based on this new functionality, I've successfully added orc-on-python support to arrow v13-v15, but some of the _other_ checks introduced in the context of #36026 now fail in https://github.com/conda-forge/pyarrow-feedstock/pull/122, because they haven't yet been taught to allow the case that orc>=2.0.1 now handles.

### Component(s)

C++, Packaging, Python

**Comment by kou** [comment]
Issue resolved by pull request 41767
https://github.com/apache/arrow/pull/41767
