### ISSUE TITLE
[C++] Make git-dependent preprocessor definitions internal

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#41783]
### Describe the enhancement requested

The `ARROW_GIT_ID` and `ARROW_GIT_DESCRIPTION` preprocessor variables are currently exposed in `arrow/util/config.h`, and included from `arrow/config.h`. This means that any file indirectly including these headers will have to be recompiled if the git information changes - something which happens quite frequently during development.

Using ccache with properly tuned configuration can work around the issue, but does not fully remove overhead. It also requires users to think about the best ccache configuration.

By making those two variable privates, we should fix the problem entirely.

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 41781
https://github.com/apache/arrow/pull/41781
