### ISSUE TITLE
[Packaging][RPM] Mismatch between package version and library version in naming

### ISSUE THREAD

**Issue by daeden** [apache/arrow#41784]
### Describe the bug, including details regarding any error messages, version, and platform.

**Version**: 16.1.0

**Platform**: Red Hat Enterprise Linux release 9.4 (Plow)

**Summary**: The version number in the library name does not match the version of the package that is installed. This causes load time issues where we fail to find library dependencies even when version mismatch is only on minor version change, which should backwards compatible.

**Steps to Reproduce**:
1. Install the package for version 16.1.0
2. List the installed libraries (`ls /lib64/libarrow.so*`)

**Expected Result**: The libraries should be labeled with the correct version number (16.1.0) with symlinks for major version and non versioned.

For example, I would expect to find:

```
$ ls  /lib64/libarrow.so*
/lib64/libarrow.so@  /lib64/libarrow.so.16@  /lib64/libarrow.so.16.1.0*
```

**Actual Result**: The libraries are labeled with an incorrect version number (1601.0.0)

```
$ ls  /lib64/libarrow.so*
/lib64/libarrow.so@  /lib64/libarrow.so.1601@  /lib64/libarrow.so.1601.0.0*
```

### Component(s)

Packaging

**Comment by kou** [comment]
We should use `libarrow1601-libs` and so on not `libarrow16-libs` for 16.1.X.
Related: #41679

**Comment by kou** [comment]
Issue resolved by pull request 41838
https://github.com/apache/arrow/pull/41838
