### ISSUE TITLE
[Java] fmpp-maven-plugin generates files directly under target/generated-sources

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#41787]
### Describe the bug, including details regarding any error messages, version, and platform.

`fmpp-plugin-maven` is used in `arrow-vector` module to generate source files before the compilation phase.  Those files are generated directly under `target/generated-sources` where they conflict with the `target/generated-sources/annotations` directory created by `javac`. Per convention each plugin generates files under its own directory to prevent risks of conflicts.

Although it doesn't cause a direct issue with the build, it may also confuse some IDEs (Eclipse and VSCode notably) which are detecting overlapping source directories

### Component(s)

Java

**Comment by lidavidm** [comment]
This also tends to confuse IntelliJ which expects a subdirectory, and so it doesn't see the generated sources -> IDE complains about undefined symbols

**Comment by lidavidm** [comment]
Issue resolved by pull request 41788
https://github.com/apache/arrow/pull/41788
