### ISSUE TITLE
[Java] Use immutables value-annotations instead of value artifact

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#41789]
### Describe the enhancement requested

As annotation processors are configured directly within `maven-compiler-plugin` instead of being discovered through the dependencies, there's no need to use `org.immutables:value` dependency which contains both annotation and the annotation processor, vs `org.immutables:value-annotations` which only contains the annotations

Similarly `org.checkerframework:checker-qual` is only needed (vs `org.checkerframework:checker`) and scope can be limited to `provided`

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41790
https://github.com/apache/arrow/pull/41790
