### ISSUE TITLE
[CI][Conda] The CondaEnvironment@1 (Conda environment) task has been deprecated since February 13, 2019 and will soon be retired

### ISSUE THREAD

**Issue by kou** [apache/arrow#41791]
### Describe the bug, including details regarding any error messages, version, and platform.

conda-linux-aarch64-cpu-py3:

https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=64087&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=cf5ca333-5432-59fc-78af-35cb2d46743b&l=161

```text
##[error]The CondaEnvironment@1 (Conda environment) task has been deprecated since February 13, 2019 and will soon be retired. Use the Conda CLI ('conda') directly from a bash/pwsh/script task. Please visit https://aka.ms/azdo-deprecated-tasks to learn more about deprecated tasks.
```

`CondaEnvironment` is used here: https://github.com/apache/arrow/blob/9185d7dad773ed8768f90fb63ad3ef7e7a92f108/dev/tasks/conda-recipes/azure.linux.yml#L49-L53

### Component(s)

Continuous Integration, Packaging

**Comment by amoeba** [comment]
I started tinkering with this in https://github.com/apache/arrow/pull/41883 though I'm not sure I've quite got it yet.

**Comment by amoeba** [comment]
Issue resolved by pull request 41883
https://github.com/apache/arrow/pull/41883
