### ISSUE TITLE
[Java] Transition from gradle-enterprise-maven-extension to develocity-maven-extension

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#41799]
### Describe the enhancement requested

Update `com.gradle:gradle-enterprise-maven-extension` artifact. Note that the artifact has been relocated to `com.gradle:develocity-maven-extension` and that there are several steps to go over to complete the migration which are described at https://docs.gradle.com/develocity/maven-extension/legacy/#develocity_migration

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 41800
https://github.com/apache/arrow/pull/41800
