### ISSUE TITLE
[GLib][CI] Use vcpkg for C++ dependencies when building GLib libraries with MSVC

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41806]
### Describe the enhancement requested

This is a follow up to #41134 and should hopefully allow building more of the GLib libraries with MSVC. 

Context: https://github.com/apache/arrow/pull/41599#discussion_r1596163069 and https://github.com/apache/arrow/pull/41599#issuecomment-2126145170

### Component(s)

Continuous Integration, GLib

**Comment by kou** [comment]
Issue resolved by pull request 41839
https://github.com/apache/arrow/pull/41839
