### ISSUE TITLE
[C++][Parquet] Unify normalize dictionary encoding handling

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#41818]
### Describe the enhancement requested

This is mentioned here: https://github.com/apache/arrow/pull/40957#discussion_r1562703901

There're some points:

1. https://github.com/apache/arrow/blob/main/cpp/src/parquet/encoding.cc#L444-L445 . encoding is not passed in Encoder
2. But shit, it's RLE in decoder 😅: https://github.com/apache/arrow/blob/main/cpp/src/parquet/encoding.cc#L1607 it will be detect and normalized in other place, like: 
3. https://github.com/apache/arrow/blob/main/cpp/src/parquet/column_reader.cc#L876

We'd better unifying them

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 41819
https://github.com/apache/arrow/pull/41819
