### ISSUE TITLE
[Java] Undefined symbol error when compile arrow java with ARROW_S3=OFF

### ISSUE THREAD

**Issue by PHILO-HE** [apache/arrow#41836]
### Describe the bug, including details regarding any error messages, version, and platform.

We encountered the below undefined symbol error at runtime with arrow java built with ARROW_S3=OFF.
```
undefined symbol: _ZN5arrow2fs17EnsureS3FinalizedEv
```

### Component(s)

Java

**Comment by raulcd** [comment]
Thanks for reporting the issue. Could you share what version of Arrow are you building from?

**Comment by PHILO-HE** [comment]
> Thanks for reporting the issue. Could you share what version of Arrow are you building from?

@raulcd, I found this issue in 15.0.0. Seems the issue still exists in main branch. I have created one PR: https://github.com/apache/arrow/pull/41837

**Comment by kou** [comment]
Issue resolved by pull request 41837
https://github.com/apache/arrow/pull/41837
