### ISSUE TITLE
[PyArrow] null values not found when reading CSV

### ISSUE THREAD

**Issue by sburns** [apache/arrow#4184]
👋, I'm having trouble getting `pyarrow.csv.read_csv` to parse null values:

```python
>>> from pyarrow import csv
>>> convert_options = csv.ConvertOptions(column_types=arrow_types)
>>> parse_options = csv.ParseOptions(escape_char='\\')
>>> table = csv.read_csv(fn, convert_options=convert_options, parse_options=parse_options)
>>> col = table.column('PATIENT_DOB')
>>> col.null_count
0
>>> 'NULL' in col.unique()
True
>>> col.to_pandas().value_counts()['NULL']
38546
```

But have no problem if I read the CSV w/ pandas and convert to a `Table`...

```python 
>>> import pandas as pd
>>> df = pd.read_csv(fn, dtype=pd_types, escapechar='\\')
>>> df.PATIENT_DOB.isna().sum()
38546
>>> table = pyarrow.Table.from_pandas(df)
>>> table.column('PATIENT_DOB').null_count
38546
```

I've tried passing various arguments to `ConvertOptions(...,null_values=)` but from my reading of https://github.com/apache/arrow/blob/f7ef65e5fc367f1f5649dfcea0754e413fcca394/cpp/src/arrow/csv/options.cc#L28-L30

it seems like literal `'NULL'` strings should be converted to NaN? I've tried various combinations of `read_csv` with/without ParseOptions, with/without ConvertOptions (including and not including column_types), etc.

Ultimately I'm looking to convert these CSV to parquet; ideally I can go csv -> table -> parquet but it seems like csv -> dataframe -> table -> parquet is my only option?

**Comment by wesm** [comment]
Can you please open a JIRA issue with a minimal reproduction? Thanks

**Comment by sburns** [comment]
Here you go, https://issues.apache.org/jira/browse/ARROW-5195

**Comment by wesm** [comment]
Thanks
