### ISSUE TITLE
[C++] Thread deadlock in ObjectOutputStream

### ISSUE THREAD

**Issue by icexelloss** [apache/arrow#41862]
### Describe the bug, including details regarding any error messages, version, and platform.

I am seeing a deadlock when destructing an ObjectOutputStream. I have attached the stack trace.

I did some debugging and found that the issue seems to be that the mutex in question is already held by this thread (I checked the __owner field in the pthread_mutex_t which points to the hanging thread)

Unfortunately the stack trace doesn’t show exactly which mutex it is trying to lock. I wonder if someone more familiar with the IO code has some ideas what might be the issue and where to dig deeper?

[arrow_object_output_stream_stacktrace.txt](https://github.com/apache/arrow/files/15469090/arrow_object_output_stream_stacktrace.txt)

Edit:
I am using Arrow 15.0.0

### Component(s)

C++

**Comment by pitrou** [comment]
Copying the temptative diagnosis I initially [posted](https://lists.apache.org/thread/d5gymtc6kj0d102k37xck8yywsyvpn7y) on the dev ML:

It seems the problem lies here:
https://github.com/apache/arrow/blob/9f5899019d23b2b1eae2fedb9f6be8827885d843/cpp/src/arrow/filesystem/s3fs.cc#L1858

The Future is marked finished with the ObjectOutputStream's mutex taken, 
and the Future's callback then triggers a chain of event which leads to 
calling the ObjectOutputStream destructor, which in turn tries to take 
the lock.

**Comment by pitrou** [comment]
@icexelloss If I submit a PR trying to fix this, will it be possible for you to validate it with your use case?

**Comment by icexelloss** [comment]
@pitrou I am curious how did you find the `HandleUploadOutcome` method? I couldn't find it in the stacktrace.

**Comment by pitrou** [comment]
It's frame 68 in the stacktrace :-)

**Comment by pitrou** [comment]
Ok, I have not one but two potential fixes, it would be nice if you could try each of them independently: https://github.com/apache/arrow/pull/41875 , https://github.com/apache/arrow/pull/41876

**Comment by icexelloss** [comment]
Thanks @pitrou! I will test both out in the next couple of days!

**Comment by icexelloss** [comment]
FYI I am testing https://github.com/apache/arrow/pull/41875 Today, I will let it run through out the day because the it doesn't always happen.

**Comment by icexelloss** [comment]
https://github.com/apache/arrow/pull/41875 doesn't seem to work and with similar stacktrace :( 

I am rerunning it to double check

**Comment by icexelloss** [comment]
I am testing https://github.com/apache/arrow/pull/41876 Today

**Comment by pitrou** [comment]
> #41875 doesn't seem to work and with similar stacktrace :(

Could you post the new stacktrace somewhere?

**Comment by icexelloss** [comment]
> > #41875 doesn't seem to work and with similar stacktrace :(
> 
> Could you post the new stacktrace somewhere?

Yep, let me do that.

**Comment by icexelloss** [comment]
[gdb-dataset-path-41875.txt](https://github.com/user-attachments/files/15536641/gdb-dataset-path-41875.txt)

Here is the stacktrace after I applied the https://github.com/apache/arrow/pull/41875 patch

**Comment by pitrou** [comment]
> [](https://github.com/user-attachments/files/15536641/gdb-dataset-path-41875.txt)
> 
> Here is the stacktrace after I applied the #41875 patch

Did you apply it to an old version of Arrow? I cannot find anything in recent versions that corresponds to this traceback line:
```
#21 ~<lambda> (this=0x5b98d96d4578, __in_chrg=<optimized out>) at /tmp/build/ts/arrow/dataset/c/src/arrow/dataset/dataset_writer.cc:363
```

It would be nice if you could test the PR itself.

**Comment by pitrou** [comment]
That said, I agree the stack trace is very similar (except for the `unique_ptr` being replaced by a `shared_ptr` in the patch you applied).

**Comment by icexelloss** [comment]
> > Here is the stacktrace after I applied the #41875 patch
> 
> Did you apply it to an old version of Arrow? I cannot find anything in recent versions that corresponds to this traceback line:
> 
> ```
> #21 ~<lambda> (this=0x5b98d96d4578, __in_chrg=<optimized out>) at /tmp/build/ts/arrow/dataset/c/src/arrow/dataset/dataset_writer.cc:363
> ```
> 
> It would be nice if you could test the PR itself.

This is on Arrow 15. The line numbers are slightly off but this is the line that stack #21 is referring to:

https://github.com/apache/arrow/blob/apache-arrow-15.0.0/cpp/src/arrow/dataset/dataset_writer.cc#L346

**Comment by pitrou** [comment]
Ok, thanks. That explains why the "fix" doesn't work then :-)

**Comment by icexelloss** [comment]
> Ok, thanks. That explains why the "fix" doesn't work then :-)

Sorry I am slightly confused. The "fix" doesn't work because I am using Arrow 15 and the fix only works on newer Arrow version?

**Comment by pitrou** [comment]
No, I mean the traceback better explains why the fix doesn't work. It probably wouldn't work on latest Arrow either (though you can still try if that's easy for you).

**Comment by icexelloss** [comment]
I see. Trying #41876 then.

**Comment by icexelloss** [comment]
@pitrou I ran tests with #41876 for two days and didn't see a deadlock. So I think #41876 fixes the issue that I was seeing.

**Comment by pitrou** [comment]
Cool, thanks!

**Comment by pitrou** [comment]
Issue resolved by pull request 41876
https://github.com/apache/arrow/pull/41876

**Comment by icexelloss** [comment]
Thank you! @pitrou
