### ISSUE TITLE
[DISCUSS] Seattle Arrow Meetup (August 2024)

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#41881]
### Describe the enhancement requested

I would like to offer to organize a face to face meetup for the Arrow community.

### Proposed dates:

Date: Tuesday, August 13th 2024
Venue: Somewhere near Hyatt Regency Seattle (the venue for post::conf).  There is a WeWork nearby that has a 20-person conference room and there are also many nearby hotels that likely have meeting spaces as well.

A number of Arrow contributors will be in town for [posit::conf](https://posit.co/conference/).  I live nearby and I know there are several other Arrow contributors in the Seattle area as well.  I think it would be fun and useful to get together.

It is important to note that we will not "decide" anything at the meeting, and will of course follow the same process as we do for other consensus lead decisions, including publicly posting all materials, and providing a video link/recordings for anyone who would like to attend but can not travel.

### Goals:

* Build & grow the community
* Discuss common goals and challenges

### Potential agenda items

* What are people doing with Arrow?  How can it grow?
* What challenges do people see with Arrow adoption?
* Are there things we can do to better evangelize Arrow?
* What integrations are arrow-adjacent projects are people most excited about?
* How can we help implementations that need more attention?

I'd like to use this issue to discuss the potential dates, further agenda items and goals, and early logistics / interest.

### Component(s)

Other

**Comment by CurtHagenlocher** [comment]
DuckCon happens to be in Seattle on Thursday August 15th from 1:30PM to 6:30PM (perhaps also to align with posit, as Hannes is speaking there).

And sadly for me, I'm away on the 11th.

**Comment by emkornfield** [comment]
I'd be more likely to be able to make the 11th (still not 100% sure though)

**Comment by ianmcook** [comment]
Sounds like a great idea. I can't make it unfortunately but I hope y'all make it happen!

**Comment by jonkeane** [comment]
This sounds like a wonderful idea, and I would very much like to attend

**Comment by thisisnic** [comment]
Love this idea! Can't make it as I'm busy on 11th in the day, and travelling on 15th, though if it ends up being 11th and folks are still around in the evening afterwards, I'd love to meet up!

**Comment by amoeba** [comment]
This is a fantastic idea. I'll be at posit::conf and, by August, I'll be living Seattle full-time so, in addition to attending, I can help with venue scouting or expediting. I can even lend a projector if need be.

**Comment by westonpace** [comment]
Looks like something of a split between the 11th and the 15th.  Given the duckdb meetup is on the 15th I think I'd recommend the 11th.

I'll leave this open for another week and then next week pick a date and move forward (that should give us about 2 months to plan).

> I'll be living Seattle full-time so, in addition to attending, I can help with venue scouting or expediting. I can even lend a projector if need be.

Awesome!

**Comment by nealrichardson** [comment]
I can see if posit::conf can provide space etc. for this if that would help, though if we do the 11th I'm not sure what will be possible since the conference won't have started yet, so they may not have space to give yet.

I can't see a full schedule posted but I'm guessing there will be time after 5pm or so on the 13th and 14th, after the last sessions--theoretically, if we could get a room at the conference around then on either of those days, would that work? Apologies to drop in late after y'all have been discussing other dates.

**Comment by lukekim** [comment]
@westonpace @nealrichardson if we do 11th, Spice AI can also help and we could organize space at Startup Hall at the University of Washington. The only issue, it's a little north of the city. Alternatively, if you go with a WeWork, we can help contribute.

**Comment by nealrichardson** [comment]
Ok. I can get us a room at posit::conf. Two options: Tuesday between 5:30 - 7:30pm, or Wednesday between 5:15 - 6:45pm. At the same time Wednesday is a (open to the public) PyLadies/RLadies mixer. I could see some advantage to having them the same time, so people could stop in at either, but also I wouldn't want people to feel like they had to choose, or that we were an alternative to that event. So on that basis, I might prefer Tuesday, assuming everyone would be available either day. 

Maybe we can vote with the emoji on this? 👍 for Tuesday, 🎉 for Wednesday, and 👎 for neither? If you can do both days, vote twice.

**Comment by westonpace** [comment]
Thanks @lukekim and @nealrichardson !  I like Tuesday because then people won't have to extend their travel plans so I think we should tentatively plan for Tuesday (it seems to have most votes so far on Neal's poll).

I've started a [Google Doc](https://docs.google.com/document/d/12YNqkgMBhU72VFv6s4sqUbQ2qOCUjAlc8bY72hjd5hM/edit?usp=sharing) we can use for planning the details.

At the moment we need more ideas for food and more ideas for things to talk about / do.  I'm chasing down whether or not we have to go through the process in https://www.apache.org/foundation/marks/events with the goal of getting a new announcement on the ML (with final date) sometime next week (we may technically need a PMC vote or at least lazy consensus that the event is approved).

**Comment by jonkeane** [comment]
I'm helping Neal and we've got the request in for a room on Tuesday. All looks good though I won't know exactly which room until closer in. I cannot wait to see some of y'all in parson

**Comment by westonpace** [comment]
I've sent out an invite to the dev/user list with the Tuesday time & date.  I've created a second document that is not for planning purposes but contains information for attendees: https://docs.google.com/document/d/1OL4PJ6sJeiDOEXWEFE1pgyCt84DFQtD61F4uaILQDsY/edit

I still need help figuring out food & agenda.  I've asked for RSVP's and presentations.

**Comment by westonpace** [comment]
> At the moment we need more ideas for food and more ideas for things to talk about / do. I'm chasing down whether or not we have to go through the process in https://www.apache.org/foundation/marks/events with the goal of getting a new announcement on the ML (with final date) sometime next week (we may technically need a PMC vote or at least lazy consensus that the event is approved).

I sent a message to the `private@` mailing list and the conclusion was that this is not "an event run by a third party" but rather "an event run by the community itself" and so we're probably ok.

**Comment by amoeba** [comment]
My notes for the meetup can be found at https://docs.google.com/document/d/1g0_oiEE0GPQP24LAP3Z8pGSoWnw6C3bsr5If8K7c_Xw.
