### ISSUE TITLE
[C++] Add arrow::ArrayStatistics

### ISSUE THREAD

**Issue by kou** [apache/arrow#41909]
### Describe the enhancement requested

An Arrow array doesn't have statistics but Arrow array source such as Parquet column may have statistics.
We can get the source statistics via source reader such as `parquet::ColumnChunkMetaData::statistics()` (`parquet::ParquetFileReader::metadata()->RowGroup(X)->ColumnChunk(Y)->statistics()`) but can't get read Arrow array (e.g. `parquet::arrow::FileReader::ReadColumn()`).

How about adding `arrow::ArrayStatistics` or something and attaching source statistics to `arrow::Array`?

### Component(s)

C++

**Comment by llama90** [comment]
I think this is a great idea. 

Adding `arrow::ArrayStatistics` and connecting source statistics to `arrow::Array` will help users get and use statistics directly from Arrow arrays. 

This can make Arrow easier to use, especially for people working with data sources like Parquet that have statistics.

**Comment by kou** [comment]
The mailing list discussion: https://lists.apache.org/thread/kcpyq9npnh346pw90ljwbg0wxq6hwxxh

**Comment by kou** [comment]
Issue resolved by pull request 43273
https://github.com/apache/arrow/pull/43273
