### ISSUE TITLE
[Java] Variadic Buffer Counts Incorrect

### ISSUE THREAD

**Issue by tustvold** [apache/arrow#41902]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/pull/41732 added an implementation of variadic buffer counts that appears to be incorrect and is failing the integration tests.

See https://github.com/apache/arrow-rs/issues/5815

I would appreciate if this could be fixed, or the relevant PR reverted as it is causing issues validating code changes to the IPC implementation in arrow-rs, and we hope to cut the next release early next week

### Component(s)

Java

**Comment by lidavidm** [comment]
CC @vibhatha

**Comment by vibhatha** [comment]
@tustvold I will work on a fix.

**Comment by vibhatha** [comment]
@tustvold I created a draft PR, is there a way to validate this before merging?

**Comment by tustvold** [comment]
I'm afraid I don't really know, I'm not familiar with how the integration tests are hooked up in this repository

**Comment by lidavidm** [comment]
Issue resolved by pull request 41930
https://github.com/apache/arrow/pull/41930
