### ISSUE TITLE
[Python] Add support for Emscripten Python (Pyodide)

### ISSUE THREAD

**Issue by joemarshall** [apache/arrow#41910]
### Describe the enhancement requested

Now that arrow c++ lib builds for emscripten, the next step is to get pyarrow building for pyodide. 

This is a tracking issue for that work.

### Component(s)

Python

**Comment by ianmcook** [comment]
@raulcd @kou I tagged this as a blocker because it looks like it is ready to merge and many people have expressed a strong wish for this to be included in 17.0.0

**Comment by kou** [comment]
Issue resolved by pull request 37822
https://github.com/apache/arrow/pull/37822
