### ISSUE TITLE
[Java] Adding POM License formatting for all modules

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#41929]
### Describe the enhancement requested

Currently the spotless support is being integrated per module as documented [here](https://github.com/apache/arrow/issues/40757). In the this [discussion](https://github.com/apache/arrow/pull/41825#discussion_r1620569426), it was decided to add the POM license formatting at once to all modules. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 42049
https://github.com/apache/arrow/pull/42049
