### ISSUE TITLE
[CI][C++][Python] Update minio version

### ISSUE THREAD

**Issue by h-vetinari** [apache/arrow#41922]
### Describe the enhancement requested

Arrow is using a pretty old version of minio:
https://github.com/apache/arrow/blob/0d9d699250ad98cdcc5c99735e1379b1e79bc195/ci/scripts/install_minio.sh#L65-L67

which hides issues like #37692. It would be good to update minio in CI here and fix any eventual fallout.

### Component(s)

Continuous Integration, Packaging

**Comment by pitrou** [comment]
Issue resolved by pull request 44225
https://github.com/apache/arrow/pull/44225

**Comment by h-vetinari** [comment]
Thanks for fixing this!

**Comment by pitrou** [comment]
Well, this had to be done at some point :-)
