### ISSUE TITLE
[C++] Compute: `all_scalar` is wrong when `ExecBatch` contains `chunked_array`

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#41923]
### Describe the enhancement requested

ExecBatch says it's a `array` or `scalar` for execution:

```
/// \brief A unit of work for kernel execution. It contains a collection of
/// Array and Scalar values and an optional SelectionVector indicating that
/// there is an unmaterialized filter that either must be materialized, or (if
/// the kernel supports it) pushed down into the kernel implementation.
///
/// ExecBatch is semantically similar to RecordBatch in that in a SQL context
/// it represents a collection of records, but constant "columns" are
/// represented by Scalar values rather than having to be converted into arrays
/// with repeated values.
///
/// TODO: Datum uses arrow/util/variant.h which may be a bit heavier-weight
/// than is desirable for this class. Microbenchmarks would help determine for
/// sure. See ARROW-8928.

/// \addtogroup acero-internals
/// @{

struct ARROW_EXPORT ExecBatch {
```

However, some code implicit shows that it might contains chunked array, see:

```
  Datum WrapResults(const std::vector<Datum>& inputs,
                    const std::vector<Datum>& outputs) override {
    // If execution yielded multiple chunks (because large arrays were split
    // based on the ExecContext parameters, then the result is a ChunkedArray
    if (HaveChunkedArray(inputs) || outputs.size() > 1) {
      return ToChunkedArray(outputs, output_type_);
    } else {
      // Outputs have just one element
      return outputs[0];
    }
  }
```

And:

```
ExecBatch ExecBatch::Slice(int64_t offset, int64_t length) const {
  ExecBatch out = *this;
  for (auto& value : out.values) {
    if (value.is_scalar()) {
      // keep value as is
    } else if (value.is_array()) {
      value = value.array()->Slice(offset, length);
    } else if (value.is_chunked_array()) {
      value = value.chunked_array()->Slice(offset, length);
    } else {
      ARROW_DCHECK(false);
    }
  }
  out.length = std::min(length, this->length - offset);
  return out;
}
```

If the input contains chunked array, the problem might happens here:

```
  bool all_scalar = true;
  for (size_t i = 0; i < arguments.size(); ++i) {
    ARROW_ASSIGN_OR_RAISE(
        arguments[i], ExecuteScalarExpression(call->arguments[i], input, exec_context));
    if (arguments[i].is_array()) {
      all_scalar = false;
    }
  }

  int64_t input_length;
  if (!arguments.empty() && all_scalar) {
    // all inputs are scalar, so use a 1-long batch to avoid
    // computing input.length equivalent outputs
    input_length = 1;
  } else {
    input_length = input.length;
  }
```

The `arguments[i].is_array()` flag should be `is_scalar()` if non-array element could be in here.

### Component(s)

C++

**Comment by mapleFU** [comment]
I've draft correspond repro and test here: https://github.com/apache/arrow/pull/41925

would you mind take a look? I'm not so familiar with compute so I don't know would this happens @felipecrv @bkietz @ZhangHuiGui

**Comment by ZhangHuiGui** [comment]
> However, some code implicit shows that it might contains chunked array, see:

In the expression system, ChunkedArray can be processed normally as input, and for some kernel functions, chunked array will be returned as output.

If the input type is chunked array, chunked array is returned in `ExecuteScalarExpression` as follows:
1. `NullHandling::COMPUTED_NO_PREALLOCATE` is registered when `AddKernel` is added
2. The output type of kernel function is `nested-type` or `dictionary-type`
3. The first two cases are not satisfied, but `can_write_into_slices = false` is set.

`ExecuteScalarExpression`'s processing logic for chunked array is as follows:
1. ExecBatch mainly saves `vector<Datum>`, and Datum can be chunked-array type.
2. Chunked array is processed in the kernel of ExecuteScalarExpression. The processing logic is mainly in [1]. There are three processing scenarios:
 1). If `preallocating_all_buffers_ = false`, that is, we do not enable preallocation (`NullHandling::COMPUTED_NO_PREALLOCATE` or nested-types or dictionary-type), the chunks in chunked-array will be processed one by one and returned as chunked-array. [2]
 2). If `preallocate_contiguous_ = true`, it means that the output type of this kernel function supports preallocation (non-nested types), the chunks in chunked-array will be processed one by one through span_iterator_, and an array will be concatenated and returned. [3]
3). If `preallocate_contiguous_ = false`, the processing logic is the same as `1)`, and chunked-array will be returned. [4]

[1] https://github.com/apache/arrow/blob/0d9d699250ad98cdcc5c99735e1379b1e79bc195/cpp/src/arrow/compute/exec.cc#L424C1-L439C6

[2] https://github.com/apache/arrow/blob/0d9d699250ad98cdcc5c99735e1379b1e79bc195/cpp/src/arrow/compute/exec.cc#L907C1-L927C6

[3] https://github.com/apache/arrow/blob/0d9d699250ad98cdcc5c99735e1379b1e79bc195/cpp/src/arrow/compute/exec.cc#L856C1-L861C8

[4] https://github.com/apache/arrow/blob/0d9d699250ad98cdcc5c99735e1379b1e79bc195/cpp/src/arrow/compute/exec.cc#L869C1-L874C9

**Comment by mapleFU** [comment]
Issue resolved by pull request 41925
https://github.com/apache/arrow/pull/41925
