### ISSUE TITLE
[Java] Add support for catalog as a JDBC query parameter

### ISSUE THREAD

**Issue by stevelorddremio** [apache/arrow#41947]
### Describe the enhancement requested

The proposal is to add "catalog" to the list of JDCB connection string parameters supported, then to pass this to the Flight Server as a DoAction session option.

Example:
jdbc:arrow-flight-sql://mydomain.com:443/catalog=\<value\>[& \<properties\>]

An alternative proposal would be to add this to the URI path. However, it might be wise to avoid the use of the URI path which has been proposed for at least one other use:
https://github.com/apache/arrow/issues/34829

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 42035
https://github.com/apache/arrow/pull/42035
