### ISSUE TITLE
[C++] Follow up of adding null_bitmap to MapArray::FromArrays

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#41955]
### Describe the enhancement requested

There have been some new comments regarding the work done in https://github.com/apache/arrow/pull/41757. This issue tracks the new suggestions so that they are included in the code.

See: https://github.com/apache/arrow/pull/41757#pullrequestreview-2094287563

### Component(s)

C++

**Comment by felipecrv** [comment]
Issue resolved by pull request 41956
https://github.com/apache/arrow/pull/41956
