### ISSUE TITLE
[R] macOS binaries on CRAN are not feature complete

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#41952]
```
Arrow package version: 16.1.0

Capabilities:

acero      TRUE
dataset    TRUE
substrait FALSE
parquet    TRUE
json       TRUE
s3        FALSE
gcs       FALSE
utf8proc   TRUE
re2        TRUE
snappy     TRUE
gzip      FALSE
brotli    FALSE
zstd      FALSE
lz4        TRUE
lz4_frame  TRUE
lzo       FALSE
bz2       FALSE
jemalloc  FALSE
mimalloc   TRUE
```
edit: I think this is only possible if `LIBARROW_MINIMAL` is unset when  `build_arrow_static.sh` is run? Which just is the case if the var is not set as we check for it but only actively set it if `not_cran`. Not sure why it wouldn't also show like this on the mac builder?

_Originally posted by @assignUser in https://github.com/apache/arrow/issues/41647#issuecomment-2132575287_

**Comment by jonkeane** [comment]
Issue resolved by pull request 42210
https://github.com/apache/arrow/pull/42210
