### ISSUE TITLE
[Java] ErrorProne Enhancements with @FormatMethod and @FormatString

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#41951]
### Describe the enhancement requested

ErrorProne warnings have been common to functions with a similar signature as follows.

```java
private void hist(String noteFormat, Object... args) {
  if (historicalLog != null) {
    historicalLog.recordEvent(noteFormat, args);
  }
}
```

And they must be updated as follows.

```java
@FormatMethod
private void hist(@FormatString String noteFormat, Object... args) {
  if (historicalLog != null) {
    historicalLog.recordEvent(noteFormat, args);
  }
}
```

At the moment, this would be suppressed based on the discussion [here](https://github.com/apache/arrow/pull/39777#discussion_r1624545389). But this must be resolved once we support JDK11+. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43376
https://github.com/apache/arrow/pull/43376
