### ISSUE TITLE
[Java] Update Unit Tests for Vector Module

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42002]
### Describe the enhancement requested

This is a sub-issue of the issue below.

- #41680

The unit tests should use the `org.junit.jupiter.api` package. This issue deals with the `vector` module.

### Component(s)

Java

**Comment by vibhatha** [comment]
@llama90 would you like to contribute a PR?

**Comment by llama90** [comment]
Yes, I would. I have a plan to follow these steps:

1. Replace `org.junit` with `org.junit.jupiter.api`.
2. Update `no suitable method found for assertEquals (string, xxx, yyy)` to `(xxx, yyy, string)` because in JUnit 5, the "message field" has changed.
3. Update `Assertions.assertXXX` to `assertXXX` using static imports.
     - I believe using static imports will make the code base clearer.
4. Update annotations such as `@Before`, `@BeforeClass`, `@After`, `@AfterClass`, etc., to their JUnit 5 equivalents.
5. ...
99. In the final step, replace `junit-vintage-engine` with `junit-jupiter-engine` to prevent using JUnit 4 statements.
    - Maybe, it should be changed after all JUnit 4 statements are removed.

Additionally, I will review documentation like [Migrating from JUnit 4 to JUnit 5](https://www.baeldung.com/junit-5-migration).

Let me know if you have any suggestions or additional steps.

**Comment by vibhatha** [comment]
Sounds like a plan! Looking forward to it.

**Comment by lidavidm** [comment]
Issue resolved by pull request 42019
https://github.com/apache/arrow/pull/42019
