### ISSUE TITLE
[CI][Python][C++] Windows wheel are failing with `Could NOT find utf8proc (missing: utf8proc_LIB) (found suitable version   "2.7.0", minimum required is "2.2.0")`

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#42017]
### Describe the bug, including details regarding any error messages, version, and platform.

Windows wheels jobs:
[wheel-windows-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9397680175/job/25881396489)
[wheel-windows-cp311-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9397680146/job/25881396446)
[wheel-windows-cp312-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9397679272/job/25881391790)
[wheel-windows-cp38-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9397679370/job/25881392547)
[wheel-windows-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9397679255/job/25881391571)
Are failing with:
```
 CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find utf8proc (missing: utf8proc_LIB) (found suitable version
  "2.7.0", minimum required is "2.2.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/Findutf8proc.cmake:107 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  cmake_modules/ThirdpartyToolchain.cmake:310 (find_package)
  cmake_modules/ThirdpartyToolchain.cmake:2822 (resolve_dependency)
  CMakeLists.txt:536 (include)


-- Configuring incomplete, errors occurred!
See also "C:/arrow-build/CMakeFiles/CMakeOutput.log".
See also "C:/arrow-build/CMakeFiles/CMakeError.log".
```
It started failing since https://github.com/apache/arrow/issues/41806 was merged which seems to be the culprit

### Component(s)

C++, Continuous Integration, Python

**Comment by kou** [comment]
Hmm. Our cached Docker image for wheel on Windows may have old utf8proc build...? I'll try.

**Comment by raulcd** [comment]
Issue resolved by pull request 42022
https://github.com/apache/arrow/pull/42022
