### ISSUE TITLE
[Java] Update Unit Tests for Algorithm Module

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42025]
### Describe the enhancement requested

This is a sub-issue of the issue below.

- #41680

The unit tests should use the `org.junit.jupiter.api` package. This issue deals with the `algorithm` module.

### Component(s)

Java

**Comment by llama90** [comment]
@vibhatha I’ll handle this issue the same way as PR #42019.

**Comment by vibhatha** [comment]
Great. Looking forward to it.

**Comment by lidavidm** [comment]
Issue resolved by pull request 42029
https://github.com/apache/arrow/pull/42029
