### ISSUE TITLE
[C++] Add `bool` operator support to `arrow::Result`

### ISSUE THREAD

**Issue by anjakefala** [apache/arrow#42036]
### Describe the enhancement requested

When the `Result<T>` class was introduced, it was decided that adding `bool` operator support [was out of scope](https://github.com/apache/arrow/pull/4501#discussion_r293686808), with the recommendation that users use `ARROW_ASSIGN_OR_RAISE` instead. 

If we could figure out how to add it, without breaking existing test cases, it would be a useful feature.

### Component(s)

C++

**Comment by Kelvinyu1117** [comment]
> ### Describe the enhancement requested
> When the `Result<T>` class was introduced, it was decided that adding `bool` operator support [was out of scope](https://github.com/apache/arrow/pull/4501#discussion_r293686808), with the recommendation that users use `ARROW_ASSIGN_OR_RAISE` instead.
> 
> If we could figure out how to add it, without breaking existing test cases, it would be a useful feature.
> 
> ### Component(s)
> C++

**Comment by pitrou** [comment]
There seems to be consensus on https://github.com/apache/arrow/pull/42094 that this is not desirable, so I'm closing this issue.
