### ISSUE TITLE
[Docs][Go] Broken Link in README Content

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42039]
### Describe the bug, including details regarding any error messages, version, and platform.

I've noticed that there is a broken link in the README.

https://github.com/apache/arrow/blob/601be7687ba89f711b876397746b5f49503c0871/go/README.md?plain=1#L51

<img width="701" alt="image" src="https://github.com/apache/arrow/assets/6668548/95412caa-9d62-4898-a98e-39f5cf2e292d">

It seems that the link has changed since version 0.4.0.

- https://arrow.apache.org/adbc/0.4.0/driver/go/flight_sql.html#client-options
- https://arrow.apache.org/adbc/0.5.0/driver/flight_sql.html#client-options

### Component(s)

Documentation, Go

**Comment by kou** [comment]
Issue resolved by pull request 42040
https://github.com/apache/arrow/pull/42040
