### ISSUE TITLE
[Swift] Decoding of nullable types value when nil is found

### ISSUE THREAD

**Issue by abandy** [apache/arrow#42041]
### Describe the bug, including details regarding any error messages, version, and platform.

When a nullable type is being decoded (String?, Int8?, Int32?...) the doDecode check will always return nil as nullable type is not convertible to a non null type (Int8? != Int8). 

Adding IsNull methods to the decoder class to resolve this issue. 

### Component(s)

Swift

**Comment by kou** [comment]
Issue resolved by pull request 42043
https://github.com/apache/arrow/pull/42043
