### ISSUE TITLE
[Java] Update Unit Tests for Flight Module

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42045]
### Describe the enhancement requested

This is a sub-issue of the issue below.

- #41680

The unit tests should use the `org.junit.jupiter.api` package. This issue deals with the `flight` module.

### Component(s)

Java

**Comment by llama90** [comment]
Issue resolved by pull request 42158 
#42158

**Comment by lidavidm** [comment]
Issue resolved by pull request 42158
https://github.com/apache/arrow/pull/42158
