### ISSUE TITLE
[Python] pyarrow.lib.ArrowIOError: Could not connect to socket Plasma

### ISSUE THREAD

**Issue by Raghava-NR** [apache/arrow#4206]
Hi,
I have implemented a piece of code to store pandas df into plasma store.
Works like a charm in my local env. But in my dev env, I am able to connect to store via python shell and put and get objects from store. But I am not able to connect to it via API call.
When I am trying to connect to store in an API it throws me 
pyarrow.lib.ArrowIOError: Could not connect to socket 
error.
Thought it might be permission issue and gave all permissions to socket but still no luck.

On server I am starting the plasma store with the cmd 
plasma_store -m 1000000000 -s /tmp/plasma
using supervisor

My server env::
OS : Ubuntu 18.04
Lang : Python 3.6
Framework : Django 1.11
webserver : apache2
pyarrow version : 0.13

Thanks in advance.

**Comment by wesm** [comment]
Can you please send an email to the mailing list (dev@arrow.apache.org) or open a JIRA issue (if you think it's a bug)?
