### ISSUE TITLE
[Python][Flight] Expose FlightInfo & FlightEndpoint attributes to python

### ISSUE THREAD

**Issue by janosik47** [apache/arrow#42095]
### Describe the enhancement requested

Both `FlightInfo` and `FilghtEndpoint` C++ classes contains attributes which are not exposed to pyarrow

`FlightEndpoint`:
 * `std::optional<Timestamp> expiration_time;`
 * `std::string app_metadata;`

`FlightInfo`:
 * `bool ordered;`
 * `std::string app_metadata;`

### Component(s)

FlightRPC, Python

**Comment by lidavidm** [comment]
Duplicate of #36954 I believe

**Comment by lidavidm** [comment]
Can we add it to that ticket?

**Comment by janosik47** [comment]
I guess so, I am fine with adding metadata into the other ticket and close this one as duplicate

**Comment by lidavidm** [comment]
Updated the other ticket

Duplicate of https://github.com/apache/arrow/issues/36954
