### ISSUE TITLE
[Python][Docs] Where's the changelog?

### ISSUE THREAD

**Issue by j-carson** [apache/arrow#42091]
### Describe the bug, including details regarding any error messages, version, and platform.

The only changelog I can find is https://github.com/apache/arrow/blob/main/CHANGELOG.md which hasn't been updated since 2021

Where can I find the changelog for pyarrow?

### Component(s)

Python

**Comment by assignUser** [comment]
Each release has a blog post with a summary of the changelog for each component with a link to the full list of resolved issues as well, e.g. the 16.0.0 release: https://arrow.apache.org/blog/2024/04/20/16.0.0-release/

**Comment by jorisvandenbossche** [comment]
Some related issues to the changelog file not being updated:

- https://github.com/apache/arrow/issues/15000
- https://github.com/apache/arrow/issues/30928
- https://github.com/apache/arrow/issues/18757

(will close two of them in favor of one)

Separately from the CHANGELOG.md file and the release blogposts, it might be useful to have a page in the Python docs that links to those sources (I agree that a first place to look for this for pyarrow will typically be the docs)

**Comment by j-carson** [comment]
Thank you!
