### ISSUE TITLE
[Java] Update Unit Tests for Tools Module 

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42092]
### Describe the enhancement requested

This is a sub-issue of the issue below.

- #41680

The unit tests should use the `org.junit.jupiter.api` package. This issue deals with the `tools` module.

I will process the modules where the task has been completed first.

- #40831

### Component(s)

Java

**Comment by vibhatha** [comment]
@llama90 spotless changes have been merged for the Tools module.

**Comment by llama90** [comment]
Yes, that's why I'm planning to proceed with this first!

**Comment by lidavidm** [comment]
Issue resolved by pull request 42093
https://github.com/apache/arrow/pull/42093
