### ISSUE TITLE
[Java] Enhance the FileRoundtrip about Creating File

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42101]
### Describe the enhancement requested

When changing from JUnit 4 to JUnit 5, we encountered an error in the `FileRoundtrip` due to a non-existing output file.

The input directory and file are mandatory, but the output directory and file might not exist. We need to enhance this logic to create the output directory and file if they do not exist.

### Component(s)

Java

**Comment by llama90** [comment]
@vibhatha I would like to know what you think about this!

**Comment by vibhatha** [comment]
@llama90 I will take a look.

**Comment by lidavidm** [comment]
Issue resolved by pull request 42115
https://github.com/apache/arrow/pull/42115
