### ISSUE TITLE
[C++][Parquet] Add tool to extract parquet footers

### ISSUE THREAD

**Issue by alkis** [apache/arrow#42102]
### Describe the enhancement requested

Add a tool that can extract footer metadata from a parquet file along with scrubbing of potentially private data. This can help collecting footers from the field and drive the design of new metadata encoding/representation with real world data.

Background: [Parquet Metadata evolution](https://docs.google.com/document/d/1PQpY418LkIDHMFYCY8ne_G-CFpThK15LLpzWYbc7rFU/edit)

### Component(s)

Benchmarking

**Comment by pitrou** [comment]
Issue resolved by pull request 42174
https://github.com/apache/arrow/pull/42174
