### ISSUE TITLE
[Swift] Add convenience methods for loading builders and validating if building is available for type

### ISSUE THREAD

**Issue by abandy** [apache/arrow#42124]
### Describe the enhancement requested

Now that all builders implement ArrowArrayHolderBuilder, it would be nice if there was a method that I could call to instantiate a builder for a type (Int32, Int32?, String...) and also if there was a method to check if a builder can be built for that type.

### Component(s)

Swift

**Comment by kou** [comment]
Issue resolved by pull request 42195
https://github.com/apache/arrow/pull/42195
