### ISSUE TITLE
[Packaging][CentOS] Migrate CentOS 7 and CentOS Stream 8 packaging jobs to use vault.centos.org

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#42128]
### Describe the enhancement requested

https://github.com/apache/arrow/pull/41395 and https://github.com/apache/arrow/issues/41401 discuss dropping support for Centos 7 and Centos Stream 8 (respectively) as they have both gone EOL. Continuing to support each platform was discussed and @kou mentioned that we may be able to keep each packaging job working by migrating to vault.centos.org. This would allow us to continue testing packaging on these two platforms and keep them in the support matrix.

We should update these two Dockerfiles to pull packages from vault.centos.org and evaluate whether this will work for our needs:

- [x] https://github.com/apache/arrow/blob/main/dev/tasks/linux-packages/apache-arrow/yum/centos-7/Dockerfile
- [x] https://github.com/apache/arrow/blob/main/dev/tasks/linux-packages/apache-arrow/yum/centos-8-stream/Dockerfile

### Component(s)

Packaging

**Comment by amoeba** [comment]
I initially tried updating just the AppStream repo definition as mentioned in https://github.com/apache/arrow/issues/41401#issuecomment-2156194716 but it looks like all repo definitions need updating because a `yum update` gives me:

```
CentOS Stream 8 - BaseOS                                                        81  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

After updating all the repos to point to vault.centos.org, update works:

```
find /etc/yum.repos.d/ -type f -iname *repo | xargs sed -i 's/mirrorlist/#mirrorlist/'
find /etc/yum.repos.d/ -type f -iname *repo | xargs sed -i 's/#baseurl/baseurl/'
find /etc/yum.repos.d/ -type f -iname *repo | xargs sed -i 's/mirror.centos.org/vault.centos.org/'
```

However, when I try to install all the packages we need for the job, I find we're missing some:

```
Error: Unable to find a match: ccache json-devel re2-devel rapidjson-devel thrift-devel
```

I'm looking into that now.

**Comment by kou** [comment]
Yes. We need to update all CentOS based repositories.

FYI: We can use one `sed` for it:

```bash
sed -i \
  -e 's/.../.../g` \
  -e 's/.../.../g` \
  ... \
  /etc/yum.repos.d/*.repo
```

> However, when I try to install all the packages we need for the job, I find we're missing some:
> 
> ```
> Error: Unable to find a match: ccache json-devel re2-devel rapidjson-devel thrift-devel
> ```

I think EPEL provides them. So we may need some adjustments for EPEL too.

**Comment by amoeba** [comment]
> FYI: We can use one sed for it:

Nice, thanks.

> I think EPEL provides them. So we may need some adjustments for EPEL too.

Good pointer, thanks.

**Comment by amoeba** [comment]
That was the trick, thanks @kou. Both images now build locally for me with the changes in https://github.com/apache/arrow/pull/42129. Can you have a look?

**Comment by kou** [comment]
Issue resolved by pull request 42129
https://github.com/apache/arrow/pull/42129
