### ISSUE TITLE
[R] Can not install the r package arrow in centos7.9

### ISSUE THREAD

**Issue by honghh2018** [apache/arrow#42120]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi developer,
    It get weird when install the  r package in centos7.9  with R 4.3.2
    This issue was lying below:
     ** testing if installed package can be loaded from temporary location
libgcc_s.so.1 must be installed for pthread_cancel to work
sh: line 1: 74477 Aborted                 (core dumped) R_TESTS= '/share/apps/R/R-4.3.2/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmpimbwiS/file1151c7c0d5bd8'
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/apps/R/R-4.3.2/lib64/R/library/00LOCK-arrow/00new/arrow/libs/arrow.so':
  /share/apps/R/R-4.3.2/lib64/R/library/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: __libc_single_threaded
  
  my gcc version was 9.3.0
  and i try to install the arrow with source code 
  build parameter lying below:
  cmake .. -DCMAKE_C_COMPILER=/usr/local/gcc-9.3.0/bin/gcc \
    -DCMAKE_CXX_COMPILER=/usr/local/gcc-9.3.0/bin/g++ \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_INSTALL_PREFIX=/share/apps/biosoft/arrow-latest \
    -DARROW_PARQUET=ON \
    -DARROW_PYTHON=ON \
    -DARROW_BOOST_USE_SHARED=ON \
    -DARROW_BUILD_TESTS=OFF \
    -DARROW_ACERO=ON \
    -DARROW_DATASET=ON \
    -DARROW_JSON=ON

# 编译并安装
make -j 20
make install

the ressioninfo
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /share/apps/R/R-4.3.2/lib64/R/lib/libRblas.so 
LAPACK: /share/apps/R/R-4.3.2/lib64/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2 tools_4.3.2   

Any advices would be appreciated
best,
hanhuihong

  
  
  

### Component(s)

C, R

**Comment by assignUser** [comment]
Arrow needs to be build with devtoolset on centos 7 but we have precompiled binaries for that. You can use them like this: `FORCE_BUNDLED_BUILD=true LIBARROW_BINARY=true ARROW_R_DEV=true Rscript -e 'install.packages("arrow")'`

**Comment by assignUser** [comment]
Alternativly you can also use r-universe: `install.packages("arrow", repos = c("https://apache.r-universe.dev", "https://cloud.r-project.org"))`

**Comment by honghh2018** [comment]
Thanks the urgent reply, 
     I try to install the install.packages("arrow", repos = c("https://apache.r-universe.dev", "https://cloud.r-project.org"))
     Nnfortunately, it still getting error:
     libgcc_s.so.1 must be installed for pthread_cancel to work
sh: line 1: 157608 Aborted                 (core dumped) R_TESTS= '/share/apps/R/R-4.3.2/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/RtmplDgKGj/file256f757bfaf8b'
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/apps/R/R-4.3.2/lib64/R/library/00LOCK-arrow/00new/arrow/libs/arrow.so':
  /share/apps/R/R-4.3.2/lib64/R/library/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: __libc_single_threaded
Error: loading failed
   It very confused for this condition
I try the another way to  build the   ARROW for this your advices
   FORCE_BUNDLED_BUILD=true LIBARROW_BINARY=true ARROW_R_DEV=true Rscript -e 'install.packages("arrow")'
Best,
hanhuihong,

**Comment by assignUser** [comment]
Hm I thought the r-universe binaries are built with out devtoolset binaries but maybe they are not. In that case my earlier advice should work.  But I will also note that Centos 7 has reached end of life, so I would recommend upgrading if possible.

**Comment by honghh2018** [comment]
Yes, the life of Centos 7 was come to an end,  i want to upgrade to new version, but this machine deploy server for many year, it not easy to change the basic server structure. but it a well advices for this.
I try the first advice ,it still get error:
  It very confuse for the  error tip:  libgcc_s.so.1 must be installed for pthread_cancel to work
  FORCE_BUNDLED_BUILD=true LIBARROW_BINARY=true ARROW_R_DEV=true Rscript -e 'install.packages("arrow", repos="https://mirrors.tuna.tsinghua.edu.cn/CRAN/")'
  the error lying below:
  ** testing if installed package can be loaded from temporary location
libgcc_s.so.1 must be installed for pthread_cancel to work
sh: line 1: 168913 Aborted                 (core dumped) R_TESTS= '/share/apps/R/R-4.1.2-4/lib64/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/Rtmp6Mfuwx/file27ec03de44523'
Error: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/apps/R/R-4.1.2-4/lib64/R/library/00LOCK-arrow/00new/arrow/libs/arrow.so':
  /share/apps/R/R-4.1.2-4/lib64/R/library/00LOCK-arrow/00new/arrow/libs/arrow.so: undefined symbol: __libc_single_threaded
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/share/apps/R/R-4.1.2-4/lib64/R/library/arrow’
* restoring previous ‘/share/apps/R/R-4.1.2-4/lib64/R/library/arrow’

The downloaded source packages are in
	‘/tmp/Rtmp3dBZYq/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("arrow", repos = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/") :
  installation of package ‘arrow’ had non-zero exit status

I wonder that the build process was run successfully,but the loading package was error with 
libgcc_s.so.1 must be installed for pthread_cancel to work

**Comment by honghh2018** [comment]
I take a try to re-build the gcc 9.3.0 and try again, hope can help ,
Best

**Comment by assignUser** [comment]
Why are you not using devtool set? https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/9/html-single/user_guide/index

**Comment by honghh2018** [comment]
Thanks the advices, i would try to use the devtool set,   i hope this would help.
Best,
      This package build can not  compatible with low version environment that block the use for this great tools, hope the simple use for this great package for large data analysis sector,
Best,

**Comment by honghh2018** [comment]
the devtoolset still getting error, i check myself for this issue directly to libgcc.so   ,  so  i reinstall gcc 9.3.0,
then it work for me

**Comment by assignUser** [comment]
Closing as it was a local env issue :)
