### ISSUE TITLE
[Java] Cleanup spotless and checkstyle configuration

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#42121]
### Describe the enhancement requested

Once [all modules have been configured with spotless](https://github.com/apache/arrow/issues/40757), the global spotless configuration should be changed to enable java formatting on all files and the individual configurations should be removed so that any new module would follow the new code style standard.

Checkstyle global configuration should also be changed to use the new configuration which does not conflict with spotless

Finally (nice to have) it may be good to add all the reformatting commits to a `.git-blame-ignore-revs` file so that `git blame` view on [Github would ignore those commits](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) since the changes are mostly automatic and cosmetic.

### Component(s)

Java

**Comment by vibhatha** [comment]
@laurentgo I was planning to do it in https://github.com/apache/arrow/issues/40826 as we don't need formatting for auto generated content in the `format` module. But if you prefer, you could choose that issue and finalize it or you could use this.

**Comment by lidavidm** [comment]
Issue resolved by pull request 43019
https://github.com/apache/arrow/pull/43019
