### ISSUE TITLE
[GLib] Cannot build gir files with MSVC

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#42130]
### Describe the bug, including details regarding any error messages, version, and platform.

Trying to build gir and typelib files fails when using MSVC with linker errors related to the generated enum methods:
```
Arrow-1.0.obj : error LNK2001: unresolved external symbol garrow_compression_type_get_type
```

### Component(s)

GLib

**Comment by adamreeve** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 42131
https://github.com/apache/arrow/pull/42131
