### ISSUE TITLE
[CI] Update job names that still refer to macOS 11 when they are using macos-latest

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#42136]
### Describe the bug, including details regarding any error messages, version, and platform.

We have several jobs that say we are running on macOS 11 AMD 64 but they are using macos-latest meaning they run on macOS 14 on ARM 64. Examples, go.yml, java.yml and js.yml:
https://github.com/apache/arrow/blob/main/.github/workflows/go.yml#L309
https://github.com/apache/arrow/blob/main/.github/workflows/go.yml#L367
https://github.com/apache/arrow/blob/main/.github/workflows/java.yml#L108
https://github.com/apache/arrow/blob/main/.github/workflows/js.yml#L84

We should validate we are still running jobs on AMD64

### Component(s)

Continuous Integration

**Comment by llama90** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 42175
https://github.com/apache/arrow/pull/42175
