### ISSUE TITLE
[Parquet] parquet-cpp Jira to GitHub issue migration

### ISSUE THREAD

**Issue by rok** [apache/arrow#42142]
### Describe the enhancement requested

This issue is to track parquet-cpp issue migration as [discussed](https://lists.apache.org/thread/zklp0lwcbcsdzgxoxy6wqjwrvt6y4s9p) and [voted](https://lists.apache.org/thread/w6r0fwj42wvpm5yflwxhtm2ss3z2hrl3) on Parquet and Arrow mailing lists.

As of this writing we have a preview repo with [migrated issues](https://github.com/rok/test-parquet-cpp/issues) to be able to review and discuss the upcoming migration. Please post any observed issues in the comments here.

### Component(s)

Developer Tools

**Comment by rok** [comment]
@jorisvandenbossche noted that https://github.com/rok/test-parquet-cpp/issues/759 had "ASF GitHub Bot:" comments that should have been filtered out. In the original migration of Arrow tickets we filtered them out and we should continue the practice here.

**Comment by raulcd** [comment]
Thanks @rok for the awesome work here!

**Comment by pitrou** [comment]
@rok This can be closed now, right? (also thanks for doing this!)

**Comment by rok** [comment]
Oh, yeah! :)
