### ISSUE TITLE
Run End Encoding not working with 16.1.0

### ISSUE THREAD

**Issue by Tunneller** [apache/arrow#42159]
### Describe the bug, including details regarding any error messages, version, and platform.

In Github launch for run-end encoding, the author cites that the following should not fail:

    import pyarrow as pa
    import pyarrow.compute as pc
    arr = pc.run_end_encode([1, 1, 2, 3, 3, 3, 6])
    arr.to_numpy()

With PyArrow 16.1.0 I get 

    pyarrow.lib.ArrowInvalid: Need to dencode a RunEndEncodedArray, but only zero-copy conversions allowed

This with python 3.10 and numpy 1.23.5

Once run-end encoding is supported, will I be able to apply encoding to the output of Bigquery,  something like q.to_arrow(compression=run-end-encoding).to_pandas()  ?

### Component(s)

Archery, Python

**Comment by rok** [comment]
Thanks for reporting this @Tunneller.
Run-end encoding should work if you try: `arr.to_numpy(zero_copy_only=False)`. Implication being that if your original array was chunked data will be copied when creating the new numpy array.

I'm not familiar with the bigquery interface. Could you provide more information about what `q` is?

**Comment by Tunneller** [comment]
Yes, that does work, thanks. 

If query is an SQL string and bq_client is a BigQuery client (that has had credentials, etc, sorted) then:

    job_query = bq_client.query(query)
    q = job_query.result() 

creates a temporary table on BigQuery which has got the results of the SQL call. The table is in column structure, largely similar to an Arrow file, I guess. The recommended way to get it off BigQuery is  py = q.to_arrow(). Followed by py.to_pandas() to be available for local analysis. Because BQ is column oriented, it internally takes advantage of encoding along the columns. And now Arrow files have run-end encoding that supports to_pandas().

So what is missing from the chain is to pass encoded columns in BQ to encoded columns in Arrow without inflation in between. Passing data from BigQuery to Arrow is a bottleneck at the moment.

**Comment by rok** [comment]
@Tunneller I'm not familiar with BigQuery internals. I'm guessing that BigQuery client returns Arrow so there shouldn't be need to change anything on BigQuery client->Arrow boundary. Arrow->numpy boundary will most likely always incur a copy.
Perhaps if you can use pandas with Arrow backend you can avoid numpy altogether.

**Comment by rok** [comment]
cc @emkornfield

**Comment by emkornfield** [comment]
> So what is missing from the chain is to pass encoded columns in BQ to encoded columns in Arrow without inflation in between. Passing data from BigQuery to Arrow is a bottleneck at the moment.

There can be many points that are a bottleneck here.  It probably makes sense to open an issue against the [BigQuery python libraries](https://github.com/googleapis/python-bigquery) with more details on the bottleneck to discuss it there.

CC @kmjung

**Comment by emkornfield** [comment]
I'm going to close this issue as it seems the remaining issues belong to BigQuery which I don't think this is a good forum for.
