### ISSUE TITLE
pyarrow 0.13.0 linux package size

### ISSUE THREAD

**Issue by kjschiroo** [apache/arrow#4216]
I noticed that the size of the `pyarrow` linux package size went up pretty significantly for `python3` in `pyarrow == 0.13.0` compared to the previous versions. In `0.13.0` the linux wheel is 48.5 MB while in `0.12.1` it was at 12.4 MB. This is a bit surprising since it looks like the size for `python2` stayed pretty near the same. 

This presents some challenges for some size limited use cases. In our specific case we're trying to make the latest version work against AWS Lambda's size limit of ~250 MB uncompressed, of which once inflated the latest version of `pyarrow` takes up 169M.

Are there any options for getting a slim build?

**Comment by wesm** [comment]
See https://issues.apache.org/jira/browse/ARROW-5082

In https://github.com/apache/arrow/blob/master/python/manylinux1/build_arrow.sh try disabling Gandiva, Plasma, or other components that you do not require. We'd be happy to discuss further on the dev@arrow.apache.org mailing list

**Comment by Ta-m** [comment]
> See https://issues.apache.org/jira/browse/ARROW-5082
> 
> In https://github.com/apache/arrow/blob/master/python/manylinux1/build_arrow.sh try disabling Gandiva, Plasma, or other components that you do not require. We'd be happy to discuss further on the [dev@arrow.apache.org](mailto:dev@arrow.apache.org) mailing list

Hi, I did saw the link. But I m still not getting how to reduce the size of the package. Ive installed it on windows and it is just 60MB in size. But as I have to use it on a lambda in aws, I need to install it using Ubuntu. And when I do it I get a package 190mb size.
It s impossible for me to use it this way.

**Comment by Sir-HC** [comment]
Same here, I think a solution has to do with building it with some disable options, but I'm dumb and don't know exactly how to do that

**Comment by thanuj11** [comment]
@wesm Hi, is there any option to disable Gandiva when installing pyarrow. I am trying to use it in lambda the package size is huge. I tried removing the gandiva files from the package but it gives corrupt footer error.

**Comment by wesm** [comment]
Let's discuss on the mailing list

**Comment by riad-c1** [comment]
> > See https://issues.apache.org/jira/browse/ARROW-5082
> > In https://github.com/apache/arrow/blob/master/python/manylinux1/build_arrow.sh try disabling Gandiva, Plasma, or other components that you do not require. We'd be happy to discuss further on the [dev@arrow.apache.org](mailto:dev@arrow.apache.org) mailing list
> 
> Hi, I did saw the link. But I m still not getting how to reduce the size of the package. Ive installed it on windows and it is just 60MB in size. But as I have to use it on a lambda in aws, I need to install it using Ubuntu. And when I do it I get a package 190mb size.
> It s impossible for me to use it this way.

Hi, just wondering how would I go about installing this with aws lambda size limitation?

**Comment by wesm** [comment]
See this e-mail thread https://lists.apache.org/thread.html/72cea3523312984d0c1d957e5fb42d224b9a415af7f1805d580c7cb0%40%3Cdev.arrow.apache.org%3E
