### ISSUE TITLE
[Python][Parquet] Pyarrow store decimal as integer

### ISSUE THREAD

**Issue by bkief** [apache/arrow#42168]
### Describe the enhancement requested

Expose the ParquetWriter property `store_decimal_as_integer` to pyarrow. This will allow storing fixed-point decimals as integers in the parquet format and take advantage of more efficient storage codecs.

### Component(s)

Parquet, Python

**Comment by raulcd** [comment]
Adding 17.0.0 to keep this in the radar before the code freeze to try and add it.

**Comment by mapleFU** [comment]
Issue resolved by pull request 42169
https://github.com/apache/arrow/pull/42169
