### ISSUE TITLE
[Python][CI] Sphinx and numpydoc test failure due to numpy 2.0.0 release

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#42170]
### Describe the bug, including details regarding any error messages, version, and platform.

Numpy 2.0.0 changed how float16 values are represented, which is causing the "AMD64 Conda Python 3.9 Sphinx & Numpydoc" tests to start failing with:
```
________________________ [doctest] pyarrow.lib.float16 _________________________
4183 
4184     >>> arr = np.array([1.5, np.nan], dtype=np.float16)
4185     >>> a = pa.array(arr, type=pa.float16())
4186     >>> a
4187     <pyarrow.lib.HalfFloatArray object at ...>
4188     [
4189       15872,
4190       32256
4191     ]
4192     >>> a.to_pylist()
Expected:
    [1.5, nan]
Got:
    [np.float16(1.5), np.float16(nan)]
```

(see https://github.com/adamreeve/arrow/actions/runs/9540117455/job/26291400384 for full build logs from my fork)

### Component(s)

Continuous Integration, Python

**Comment by danepitkin** [comment]
Issue resolved by pull request 42172
https://github.com/apache/arrow/pull/42172
