### ISSUE TITLE
[Java] Remove JUnit 4 Dependencies after JUnit 5 upgrade

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#42193]
### Describe the enhancement requested

As discussed [here](https://github.com/apache/arrow/issues/41680) once the unit test upgrade is completed to JUnit5, remove JUnit 4 dependencies. 

### Component(s)

Java

**Comment by llama90** [comment]
We can proceed after merging the Flight Module PR. If it's okay with you, can I take this?

**Comment by vibhatha** [comment]
No worries, please go ahead.

**Comment by vibhatha** [comment]
Closed by https://github.com/apache/arrow/pull/42206

**Comment by lidavidm** [comment]
Issue resolved by pull request 42206
https://github.com/apache/arrow/pull/42206

**Comment by lidavidm** [comment]
Sorry, I always forget the merge script has two parts...

**Comment by vibhatha** [comment]
Oh, sorry I am not aware of. I thought it is manual, did my manual closing messed things up.
