### ISSUE TITLE
[CI][Java] Need to Increase Timeout or Reduce CI Time for JNI

### ISSUE THREAD

**Issue by llama90** [apache/arrow#42209]
### Describe the enhancement requested

When I processed the JUnit 5 tasks, I noticed that the CIs for JNI are almost always failing. The timeout for JNI CIs is set to 90 minutes, but most workflows fail due to timeout. 

Even though the timeout is extended to 240 minutes, the workflows still fail. 

- https://github.com/apache/arrow/pull/42171

Shouldn't we consider increasing the timeout or reducing the CI workload for JNI?

- [Java JNI workflows](https://github.com/llama90/arrow/actions/workflows/java_jni.yml?page=2&query=is%3Afailure++)

### Component(s)

Continuous Integration, Java

**Comment by kou** [comment]
Could you rebase on main to use the cached Docker images at  https://hub.docker.com/repository/docker/apache/arrow-dev/tags?page=&page_size=&ordering=&name=java-jni ?

**Comment by llama90** [comment]
@kou Awesome! Thank you.

I have one question: Is the cached Docker image changed with each new commit to the main branch?

**Comment by vibhatha** [comment]
Did we close this because?

**Comment by llama90** [comment]
After rebasing the main branch to the feature([ARROW-42193](https://github.com/llama90/arrow/tree/ARROW-42193)) branch, the workflow for JNI was finished successfully. So, I think the Docker image was the only issue. Am I misunderstanding something?

- https://github.com/apache/arrow/actions/runs/9588420186/job/26440405550?pr=42206

**Comment by kou** [comment]
> Is the cached Docker image changed with each new commit to the main branch?

Partially, yes. It's changed only when new commit has changes related to the Docker image.

**Comment by llama90** [comment]
Aha, I did think it was strange that the workflow related to JNI took over an hour. Thank you for your answer!
