### ISSUE TITLE
[CI][Swift] Make a Package.swift file specific for CI build to ensure warnings are handles as errors

### ISSUE THREAD

**Issue by abandy** [apache/arrow#42213]
### Describe the bug, including details regarding any error messages, version, and platform.

An option for handling warnings as errors was added for Issue #42087.  This has caused an error for clients using these Swift Packages due to a change in XCode 15.3 (as explained by Luke Gardner in an email).  

### Component(s)

Swift

**Comment by abandy** [comment]
take

**Comment by lukedg97** [comment]
@abandy just an fyi that I can currently work around this issue by downgrading to an older version of the arrow repo. It does seem to be a specific piece of Xcode oddness, I have not found a way to disable the behavior from Xcode. Looking forward to the full fix!

**Comment by abandy** [comment]
Hi Luke,

Thanks for letting me know.  Glad to hear you have a work around!

I think we might have a "fix" until a better solution is found 🙂.  The PR is (https://github.com/apache/arrow/pull/42214), please take a look and comment when/if you get a chance..  I would add you as a reviewer but I do not have the auth.
[https://opengraph.githubassets.com/95aa2ca119e13c1c34929fcb3bbd6e844d1caf8249a5dff808200ee166840ad8/apache/arrow/pull/42214]<https://github.com/apache/arrow/pull/42214>
GH-42213: [Swift] Add CI specific Package files for building with warnings as errors by abandy · Pull Request #42214 · apache/arrow<https://github.com/apache/arrow/pull/42214>
Rationale for this change Downstream clients are getting a conflicting options error when building with the "-warnings-as-errors" swift option. What changes are included in this PR? This PR creates...
github.com

Thank you,
Alva Bandy

________________________________

**Comment by lukedg97** [comment]
I can confirm that I fail to build on `main` with the error: `Conflicting options '-warnings-as-errors' and '-suppress-warnings'`

and with the only change being checking out with the command `gh pr checkout 42214` i am able to build with no errors

For those who may find this conversation later make sure to right-click on the package in xcode and select the option "Update Package" to make sure that Xcode picks up the change.

**Comment by kou** [comment]
Issue resolved by pull request 42214
https://github.com/apache/arrow/pull/42214
