### ISSUE TITLE
[R]: `vctrs` custom class errors on roundtrip

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#42220]
### Describe the bug, including details regarding any error messages, version, and platform.

I think that this is fallout from #41969 but when making some examples for how to make a custom vctrs class I ran into an error on round trip `Error in '[<-':` `! Can't convert 'value' <list> to <special>.`.

``` r
library(arrow, quietly = TRUE, warn.conflicts = FALSE)
#> Warning: package 'arrow' was built under R version 4.4.1
```

``` r
library(vctrs, quietly = TRUE, warn.conflicts = FALSE)

special <- function(n = integer()) {
  new_rcrd(
    fields = list(special = n),
    class = "special"
  )
}

frac_df <- data.frame(
  total = c(2, 2, 7, 9)
)

frac_df$special = special(frac_df$total)

as_arrow_table(frac_df)
#> Error in `[<-`:
#> ! Can't convert `value` <list> to <special>.
```

<sup>Created on 2024-06-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup> 

### Component(s)

R

**Comment by nealrichardson** [comment]
This is in the `VctrsExtensionType` code path, which as it turns out serializes a `vec_ptype` and not just a list of attributes. So that will need to be handled differently.

**Comment by thisisnic** [comment]
Issue resolved by pull request 42226
https://github.com/apache/arrow/pull/42226
