### ISSUE TITLE
[JS] Build warning due to missing arrow2csv.cjs file in bin

### ISSUE THREAD

**Issue by didymental** [apache/arrow#42229]
### Describe the bug, including details regarding any error messages, version, and platform.

In the build in npm for package `apache-arrow`, there is this warning:
```
Failed to create bin at {path}/node_modules/.bin/arrow2csv. ENOENT: no such file or directory, open {path}/node_modules/.pnpm/apache-arrow@16.1.0/node_modules/apache-arrow/bin/arrow2csv.cjs
```

The bins are declared like this:
```
curl https://registry.npmjs.org/apache-arrow/16.1.0 | jq '.bin'
{
  "arrow2csv": "bin/arrow2csv.cjs"
}
```
But the `.tgz` file doesn't contain the `.cjs` file in `bin`.
> Reference: https://registry.npmjs.org/apache-arrow/-/apache-arrow-16.1.0.tgz
- It only contains `.js` and `.mjs` files. 

This results in the warning.

### Component(s)

Continuous Integration, JavaScript, Packaging

**Comment by mrb1090** [comment]
Are you sure this was closed?  Just tried to install via NPM and throwing the same error.

**Comment by trxcllnt** [comment]
The fix should be in the next Arrow release.
