### ISSUE TITLE
[Swift] Ensure map behavior is the same between all data types

### ISSUE THREAD

**Issue by abandy** [apache/arrow#42245]
### Describe the enhancement requested

Currently we are decoding a map into an array which means that each key/value pair is placed in its own map.  This is not the desired behavior.  A RecordBatch that is decoded into a map needs to put all the key/value pairs into the same map.

### Component(s)

Swift

**Comment by abandy** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 42246
https://github.com/apache/arrow/pull/42246
