### ISSUE TITLE
[Rust] README invalid link

### ISSUE THREAD

**Issue by hagsteel** [apache/arrow#4234]
In the README at https://github.com/apache/arrow/tree/master/rust/parquet the crate documentation goes to https://docs.rs/crate/parquet/0.14.0-SNAPSHOT which does not exist.

(Changing it to https://docs.rs/crate/parquet/0.13.0 works)

**Comment by kou** [comment]
master is for developers.
Could you use tag such as [apache-arrow-0.13.0](https://github.com/apache/arrow/tree/apache-arrow-0.13.0/rust/parquet) instead? It's for users.
