### ISSUE TITLE
Pyarrow Parquet Pagesize question

### ISSUE THREAD

**Issue by EvenOldridge** [apache/arrow#4237]
I'm trying to figure out how to specify page size in the parquet writer but I'm only seeing the option for chunk_size / row_group_size which I believe is block size.  How do you set page size?  I saw a reference to it being set as a default 1MB in a previous issue, but can't find any other references to change it.

**Comment by wesm** [comment]
see https://issues.apache.org/jira/browse/ARROW-2057. Let's discuss there
