### ISSUE TITLE
[C++][Parquet] Incorporate DELTA_BINARY_PACKED value encoder into library and add unit tests

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42394]
There is some code for this currently found in `examples/decode_benchmark.cc`

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wesm) / @wesm
#### Related issues:
- [[C++][Parquet] Add DELTA_BYTE_ARRAY encoder to Parquet writer](https://issues.apache.org/jira/browse/ARROW-17619) (blocks)
- [[C++] Improve performance of unpack64](https://issues.apache.org/jira/browse/ARROW-13677) (causes)
- [[C++][Parquet] Support for DeltaBitPackDecoder to read DELTA_BINARY_PACKED value and add unit tests](https://issues.apache.org/jira/browse/ARROW-13206) (is related to)
#### PRs and other links:
- [GitHub Pull Request #10627](https://github.com/apache/arrow/pull/10627)
- [GitHub Pull Request #19](https://github.com/apache/parquet-testing/pull/19)

<sub>**Note**: *This issue was originally created as [PARQUET-490](https://issues.apache.org/jira/browse/PARQUET-490). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Antoine Pitrou](https://issues.apache.org/jira/browse/PARQUET-490?#comment-17401733) / @pitrou:
Issue resolved by pull request 10627
<https://github.com/apache/arrow/pull/10627>

**Comment by asfimport** [comment]
[Brian Kiefer](https://issues.apache.org/jira/browse/PARQUET-490?#comment-17483771):
@pitrou - Is this issue really resolved since only the decoder has been implemented but not the encoder?

**Comment by asfimport** [comment]
[Antoine Pitrou](https://issues.apache.org/jira/browse/PARQUET-490?#comment-17484609) / @pitrou:
`[~Bkief]` Hmm, sorry. I went a bit overboard when closing this issue, as title mentions encoding not decoding.

**Comment by rok** [comment]
Issue resolved by pull request 14191
https://github.com/apache/arrow/pull/14191
