### ISSUE TITLE
ARROW_GANDIVA_JAVA flag missing in instructions

### ISSUE THREAD

**Issue by daslu** [apache/arrow#4248]
Thanks for this beautiful project!

The build instructions
https://github.com/apache/arrow/blob/master/docs/source/developers/cpp.rst#optional-components
seem to be missing the new `-DARROW_GANDIVA_JAVA=ON` (in addition to `DARROW_GANDIVA=ON`).

See https://github.com/apache/arrow/pull/2817 for background.

**Comment by emkornfield** [comment]
@daslu could you file a [JIRA](https://issues.apache.org/) issue on this?  Would you have time to contribute a patch?

**Comment by daslu** [comment]
@emkornfield sure, thanks.

**Comment by wesm** [comment]
@daslu can you post a link to the JIRA issue?

**Comment by daslu** [comment]
Hi, tomorrow finally I'll be able to create a ticket and a pull request, and post the links here.

**Comment by daslu** [comment]
Jira issue: https://issues.apache.org/jira/browse/ARROW-5373

Pull request: https://github.com/apache/arrow/pull/4345

Thanks

**Comment by emkornfield** [comment]
Thank you.
