### ISSUE TITLE
snappy compression seems not to work

### ISSUE THREAD

**Issue by asafcombo** [apache/arrow#4254]
# Description
I'm using `pq.write_table(arrow_table,'pyarrow_test', compression='snappy')`.

I'm validating the compression with `python-snappy`, but I get that the compression is not valid.

# system
1.  run on aws `ec2`
2. os:  `Amazon Linux AMI 2018.03`
3. deleted the snappy distribution that comes pre installed.
4. installed `snappy-devel-1.1.0-3.el7.x86_64.rpm` and `snappy-1.1.0-3.el7.x86_64.rpm`
5. installed `python-snappy`

# Code
```python
import pandas
import pyarrow
import pyarrow.parquet as pq
import snappy

data2 = [{'a':3, 'b':'c'}]*5000
df2 = pandas.DataFrame(data2)
df2.to_parquet('test2', engine='pyarrow', compression='snappy')
arrow_table = pyarrow.Table.from_pandas(df2)

pq.write_table(arrow_table,'pyarrow_test', compression='snappy')
data = open('pyarrow_test', 'r').read()
print(snappy.isValidCompressed(data))

>>>False
```

I also ran
`hadoop fs -text file:///pyarrow_test> check`

and got

```
19/05/05 15:36:50 INFO lzo.GPLNativeCodeLoader: Loaded native gpl library
19/05/05 15:36:50 INFO lzo.LzoCodec: Successfully loaded & initialized native-lzo library [hadoop-lzo rev 4096a4894918d48bbe2e12497617628401f3a88e]

```

Didn't find anything to point me in the right direction yet. please advise

**Comment by wesm** [comment]
@asafcombo Snappy compression is performed at the level of data pages in the Parquet format, not at the level of the whole file. Take a look at the Parquet specification for more details about this https://github.com/apache/parquet-format -- we can also point you to the relevant code paths in parquet-cpp
