### ISSUE TITLE
Can't read data from parquet file in C++ library

### ISSUE THREAD

**Issue by worker24h** [apache/arrow#4256]
Specified the second param parquet::ReaderProperties When I used parquet::ParquetFileReader::Open, it can't work. 
The following code：
```cpp
parquet::ReaderProperties _properties;
_properties = parquet::ReaderProperties(); 
_properties.enable_buffered_stream();  // used  buffer stream
parquet_reader = parquet::ParquetFileReader::Open(_parquet, _properties);
...
int32_t value;
parquet::Int32Reader* int32_reader =
static_cast<parquet::Int32Reader*>(column_reader.get());
int32_reader->Skip(_current_line_of_group);// skip lines of processed.
rows_read = int32_reader->ReadBatch(1, nullptr, nullptr, &value, &values_read);   
```
The interface **Skip**  throw exception：
```text
Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.
```

**Comment by worker24h** [comment]
I fixed the issued. 
cpp/src/parquet/util/memory.cc: 273
if (*num_bytes > (buffer_size_ - buffer_offset_))
to 
if (*num_bytes >= (buffer_size_ - buffer_offset_))

**Comment by kou** [comment]
Could you open a JIRA issue at https://issues.apache.org/jira/browse/ARROW and submit a pull request?
See also: https://arrow.apache.org/docs/developers/contributing.html#how-to-contribute-patches

**Comment by fsaintjacques** [comment]
This issue can be closed.
