### ISSUE TITLE
[Javascript] Possible bug in countBy

### ISSUE THREAD

**Issue by yngve-sk** [apache/arrow#4261]
The ```countBy``` function is not returning correct histograms, as it seems to select the wrong array type for the indexing.

The following line in countBy seems to be causing the problems:

 ```const countByteLength = Math.ceil(Math.log(vector.dictionary.length) / Math.log(256));```

For example, if the dictionary length is 3, yet the indices length is 1 million, the result of this expression will be 1, which will lead to a Uint8Array being used, again resulting in overflows.

Codepen example
https://codepen.io/Yngve92/pen/mYdWrr

If I switch the expression to: ```const countByteLength = Math.ceil(Math.log(vector.length) / Math.log(256));``` it seems to be working all right, but I am not sure if this is correct...

Best regards and thank you

**Comment by kou** [comment]
Could you open a JIRA issue at https://issues.apache.org/jira/browse/ARROW ?
See also: https://arrow.apache.org/docs/developers/contributing.html#github-issues

**Comment by yngve-sk** [comment]
Done: https://issues.apache.org/jira/browse/ARROW-5274
Submitted a PR with the fix.

**Comment by kou** [comment]
Thanks!
