### ISSUE TITLE
[C++][Parquet] Add index pages to the format to support efficient page skipping to parquet-cpp

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42849]
The scope of the Jira is to take advantage of indexes added as part of PARQUET-922

It is easier to implement this if we create sub-tasks

**Reporter**: [Renato Javier Marroquín Mogrovejo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renato2099) / @renato2099
**Assignee**: Gang Wu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wgtmac) / @wgtmac
#### Subtasks:
- [X] [Add Index support in the read path](https://issues.apache.org/jira/browse/PARQUET-1848)
- [X] [Add index support in the write path](https://issues.apache.org/jira/browse/PARQUET-1849)
#### Related issues:
- [[C++] Add support Parquet with Page Index](https://issues.apache.org/jira/browse/ARROW-10158) (duplicates)
#### PRs and other links:
- [GitHub Pull Request #6807](https://github.com/apache/arrow/pull/6807)

<sub>**Note**: *This issue was originally created as [PARQUET-1404](https://issues.apache.org/jira/browse/PARQUET-1404). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1404?#comment-17090617) / @wesm:
Do you want to keep the discussion in one place, i.e. on the mailing list?

**Comment by asfimport** [comment]
[Gang Wu](https://issues.apache.org/jira/browse/PARQUET-1404?#comment-17641967) / @wgtmac:
Hi @majetideepak, I am working on [ARROW-10158](https://issues.apache.org/jira/browse/ARROW-10158) now, so I have changed the assignee to myself.

Also cc [~shangx@uber.com]

**Comment by asfimport** [comment]
[Arun Balajiee Lekshmi Narayanan](https://issues.apache.org/jira/browse/PARQUET-1404?#comment-17641974):
Would you mind reviewing my changes with regards to issues before
proceeding?

**Comment by asfimport** [comment]
[Gang Wu](https://issues.apache.org/jira/browse/PARQUET-1404?#comment-17641983) / @wgtmac:
Hi `[~encodedgeek]`, I will definitely go through your change as well as the review comments.

FYI, I have discussed the initiative with some maintainers of Apache Arrow. The code is running in production already so it is good time to contribute back to the community.

**Comment by asfimport** [comment]
[Arun Balajiee Lekshmi Narayanan](https://issues.apache.org/jira/browse/PARQUET-1404?#comment-17642037):
Interested to collaborate with you!

**Comment by asfimport** [comment]
[Gang Wu](https://issues.apache.org/jira/browse/PARQUET-1404?#comment-17845717) / @wgtmac:
Page index has been implemented in the parquet-cpp already. Close this.

**Comment by cpaulik** [comment]
[this page](https://github.com/apache/arrow/blob/ac6d7e812d2bad25ee72be2cf3b7cdeea01aaa88/docs/source/cpp/parquet.rst?plain=1#L603-L604) still claims that `Column Index` and `Offset Index` are not used during reading. Looking at https://github.com/apache/arrow/pull/6807/files as a layman it seems they are used. 

Does the documentation need an update or am I reading the MR wrongly?

**Comment by cpaulik** [comment]
Just found [this issue](https://github.com/apache/arrow/issues/26168) so it seems the docs are correct and it's indeed not used when reading - but lower level API support is present.
