### ISSUE TITLE
0.13 FAILED to build with option -DARROW_NO_DEFAULT_MEMORY_POOL

### ISSUE THREAD

**Issue by whjiang** [apache/arrow#4289]
I tried to upgrade Apache Arrow to 0.13. But, when building Apache Arrow 0.13 with option `-DARROW_NO_DEFAULT_MEMORY_POOL`, I got a lot of failures. 

It seems 0.13 assuming default memory pool always available.

**Comment by whjiang** [comment]
My cmake command is:
```
make .. -DCMAKE_BUILD_TYPE=Release -DARROW_BUILD_TESTS=off -DARROW_USE_GLOG=off -DARROW_WITH_LZ4=off -DARROW_WITH_ZSTD=off -DARROW_WITH_SNAPPY=off  -DARROW_WITH_BROTLI=off -DARROW_WITH_ZLIB=off -DARROW_JEMALLOC=off -DARROW_CXXFLAGS=-DARROW_NO_DEFAULT_MEMORY_POOL
```

**Comment by wesm** [comment]
Thanks for reporting; apparently we aren't testing that configuration. Can you please open a JIRA issue?

**Comment by whjiang** [comment]
> Thanks for reporting; apparently we aren't testing that configuration. Can you please open a JIRA issue?

ARROW-5300 is created.

**Comment by wesm** [comment]
Thanks
