### ISSUE TITLE
Consider string interning (pooling) as option for columns

### ISSUE THREAD

**Issue by ericjster** [apache/arrow#4290]
For datasets having many rows but few distinct string column values, string interning could save time and space, at an extra cost of bookkeeping and complexity of code and storage. There are several places to consider: format and interface. 
Format changes would obviously introduce version dependencies for clients. Compression essentially does string interning on disk so it might be that it offers no CPU or disk savings (did not implement and test).
An interface implementation might help languages that allocate strings, by reducing allocation and GC costs, and memory usage.

**Comment by emkornfield** [comment]
Thanks for the suggestion.  Could you describe how this is different then [dictionary arrays](https://arrow.apache.org/docs/python/data.html#dictionary-arrays) ?

**Comment by wesm** [comment]
Indeed, @ericjster what you are describing sounds equivalent to dictionary encoding, which we have already
