### ISSUE TITLE
pyarrow.hdfs.ls and pyarrow.hdfs.walk caused Segmentation fault when the path 

### ISSUE THREAD

**Issue by JackYangzg** [apache/arrow#4291]
I Using pyarrow to communicate with hdfs through libhdfs3.so。
all Interfaces except ls and walk is all ok。
when I using ls to list files of a dir, if the file number > 1, the program will core dumped(Segmentation fault)。

I using C to call libhdfs3.so is fine.

system：suse12-sp2  or ubuntu16.04
hadoop: 2.7.6
pyarrow: 0.13.0
libhdfs3.so: latest in github

**Comment by wesm** [comment]
We don't support libhdfs3 version 2.3 that's currently available on conda-forge. I am not sure we want to continue supporting libhdfs3 at all because it is not maintained. You can try downgrading to `libhdfs3=2.2.31` in the meantime

**Comment by wesm** [comment]
Related issue https://issues.apache.org/jira/browse/ARROW-1445
