### ISSUE TITLE
C++17 build error

### ISSUE THREAD

**Issue by zhouyan** [apache/arrow#4294]
There are a few places in the source code that is not C++17 standard compliant when built under that standard, for example so far I am able to identify the following

```
      fields[i] = field(field_names[i].to_string(), field_values->type(),
                        field_builders_[i].nullable, Kind::Tag(field_builders_[i].kind));
```
which can be found in `cpp/src/arrow/json/parser.cc` around line 369

C++17 string_view does not have a `to_string` method which is causing compile errors when built against C++17. It is necessary to built it under C++17 if the user want to make use of C++17 in their own code because otherwise there would be ABI  issues.

More on the ABI problem, it could be avoided if all use of `util::string_view` is implemented in header and delegate the pointer version of the overloads to source file, instead of the other way around, which seems to be way done at the moment. For instance the for following segments of code in the DictionaryBuilder

```

  /// \brief Append a scalar value
  Status Append(const Scalar& value);

  /// \brief Append a fixed-width string (only for FixedSizeBinaryType)
  template <typename T1 = T>
  Status Append(typename std::enable_if<std::is_base_of<FixedSizeBinaryType, T1>::value,
                                        const uint8_t*>::type value) {
    return Append(util::string_view(reinterpret_cast<const char*>(value), byte_width_));
  }

  /// \brief Append a fixed-width string (only for FixedSizeBinaryType)
  template <typename T1 = T>
  Status Append(typename std::enable_if<std::is_base_of<FixedSizeBinaryType, T1>::value,
                                        const char*>::type value) {
    return Append(util::string_view(value, byte_width_));
  }
```

The problem of this style of implementation is that the built library is tied to a specific string_view ABI. So it requires that the same flags and ABI being chosen during both the time that the library is built and the time library headers included in user code. Which is usually the most desirable but not always possible (for example, user use a pre-built binary from package manger which is built against C++11 instead of C++17).  I understand there are configure macros to avoid this issue but in my experience it is better to avoid the ABI troubles all together to begin with.

**Comment by wesm** [comment]
Hi can you please open a JIRA issue? PRs welcome. Note we have a PR pending that affects the DictionaryBuilder code path so you may want to wait for that to go in

**Comment by pitrou** [comment]
Also @bkietz

**Comment by wesm** [comment]
@zhouyan would you mind opening a JIRA issue?

**Comment by bkietz** [comment]
https://issues.apache.org/jira/browse/ARROW-5404?filter=-1

**Comment by wesm** [comment]
Thanks!
