### ISSUE TITLE
Schema append does not work

### ISSUE THREAD

**Issue by K377U** [apache/arrow#4296]
Im trying to use [Schema API](https://arrow.apache.org/docs/python/generated/pyarrow.Schema.html#pyarrow.Schema).

Schema append does not work. 

```
import unittest
import pyarrow as pa

class TestSchema(unittest.TestCase):

    def test_schema_append(self):
        schema = pa.schema(
            [
                ('name', pa.string()),
            ]
        )
        schema.append(
            pa.field('age', pa.int64())
        )
        self.assertEqual(
            schema,
            pa.schema(
                [
                    ('name', pa.string()),
                    ('age', pa.int64())
                ]
            )
        )
```

Result:
```
E       AssertionError: name: string != name: string
E       age: int64
```

**Comment by K377U** [comment]
Ah, ok. Now I got it. Append returns schema. Naming was confusing but API documentation actually said that it returns it implying the given data structure was not modified.

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-5309 about improving the docstrings about this
