### ISSUE TITLE
[Rust] [Parquet] - How to flat map a RowIter ?

### ISSUE THREAD

**Issue by FabioBatSilva** [apache/arrow#4301]
Hi..

I have I iterator of parquet files/paths
and I'm trying to flatten it in order to get a iterator with all the rows in all files.

```rust
use parquet::file::reader::SerializedFileReader;
use parquet::record::reader::RowIter;
use std::path::Path;
use std::fs::File;

fn main() {
    let path1 = Path::new("path-to/1.snappy.parquet");
    let path2 = Path::new("path-to/2.snappy.parquet");
    let vec = vec![path1, path2];
    let it = vec.iter()
        .map(|p| {
            File::open(p).unwrap()
        })
        .map(|f| {
            SerializedFileReader::new(f).unwrap()
        })
        .flat_map(|reader| -> RowIter {
            RowIter::from_file(None, &reader).unwrap()
//|             |                        |
//|             |                        `reader` is borrowed here
//|             returns a value referencing data owned by the current function
        })
    ;

    for r in it {
        println!("{}", r);
    }
}
```

I think the prob is that to create a `RowIter` I need to borrow the `FileReader`.
And some how I need to keep both the reader and the row inter alive..

I tried creating wrapper iterator to hold both.
But that creates a struct member referencing other members.
which as far as i can tell is not quite possible in rust..

```rust
pub struct ParquetRowIterator<'a> {
    reader: SerializedFileReader<File>,
    iter: RowIter<'a>,
}

// ...
.flat_map(|reader| -> ParquetRowIterator {
    ParquetRowIterator::new(
        RowIter::from_file(None, &reader).unwrap(),
                                // ------- `reader` is borrowed here
        reader
    )
//  ^ returns a value referencing data owned by the current function
})
// ...
```

I know i could create all `SerializedFileReader` first and then flat map each row iter..
But that is not quite possible depending on how many parquet files i have.. 

What would be the recommend way to Flat map a RowIter ?

**Comment by nevi-me** [comment]
Hey @FabioBatSilva, may you please close this as you've opened a JIRA ticket and a PR, thanks btw.

**Comment by FabioBatSilva** [comment]
👍
