### ISSUE TITLE
[Java] Simplify `flight.properties` generation

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#43020]
### Describe the enhancement requested

`properties/flight.properties` file is a generated file which dumps all maven properties into the file (although only 4 of them are actually used by code) which is put under `src/main/resources` which violates the assumption that only permanent files are stored under `src` and generated files should be under `target`. It also means that the file is not cleaned when invoking `mvn clean`

The same thing could be done by storing `flight.properties` template under `src/main/resources` and ask them to interpolate its content when copying it over `target/classes`. The file would also be smaller

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43028
https://github.com/apache/arrow/pull/43028
