### ISSUE TITLE
feather write/load changes dataframe

### ISSUE THREAD

**Issue by lepmik** [apache/arrow#4302]
![image](https://user-images.githubusercontent.com/3418096/57631448-ccef5e80-759f-11e9-8022-b143cfbd8990.png)

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by jorisvandenbossche** [comment]
I suppose the reason is because your DataFrame will have integer column names, and writing/reading to/from parquet converted those to string column names.

Not sure if feather is supposed to restore that (with parquet we store pandas metadata, which we don't with feather I think)

**Comment by wesm** [comment]
That's right, so this may fall into the "won't fix" category
