### ISSUE TITLE
S3 support not enabled for r-universe builds on MacOS

### ISSUE THREAD

**Issue by grantmcdermott** [apache/arrow#43030]
### Describe the bug, including details regarding any error messages, version, and platform.

Got surprised by this today, especially since the `r-universe` installation has typically been the recommended approach for fixing missing feature support on MacOS in the past (c.f. https://github.com/apache/arrow/issues/40667#issuecomment-2007942987).

```r
> install.packages("arrow", repos = c("https://apache.r-universe.dev"))
Installing package into ‘/Users/gmcd/Library/R/x86_64/4.4/library’
(as ‘lib’ is unspecified)
trying URL 'https://apache.r-universe.dev/bin/macosx/big-sur-x86_64/contrib/4.4/arrow_16.1.0.tgz'
Content type 'application/x-gzip' length 13275496 bytes (12.7 MB)
==================================================
downloaded 12.7 MB


The downloaded binary packages are in
        /var/folders/30/w8mpd9p96gs0s0f4y0bhts880000gr/T//RtmpC5faej/downloaded_packages
> arrow::arrow_with_s3()
[1] FALSE
```

Possibly related to https://github.com/apache/arrow/issues/41952 and https://github.com/apache/arrow/pull/42210

P.S. There's no mention of r-universe anywhere on the r-arrow [website](https://arrow.apache.org/docs/r/index.html). Should it be added to the README as an alternative installation option?

### Component(s)

R

**Comment by grantmcdermott** [comment]
The nightlies R binary is also missing S3 support AFAICT.

```r
> install.packages("arrow", repos = c(arrow = "https://nightlies.apache.org/arrow/r", getOption("repos")))
Installing package into ‘/Users/gmcd/Library/R/x86_64/4.4/library’
(as ‘lib’ is unspecified)
trying URL 'https://nightlies.apache.org/arrow/r/bin/macosx/big-sur-x86_64/contrib/4.4/arrow_16.1.0.100000382.tgz'
Content type 'application/x-gzip' length 17398273 bytes (16.6 MB)
==================================================
downloaded 16.6 MB


The downloaded binary packages are in
        /var/folders/30/w8mpd9p96gs0s0f4y0bhts880000gr/T//RtmpC5faej/downloaded_packages
> arrow::arrow_with_s3()
[1] FALSE
> 
```

**Comment by assignUser** [comment]
Thanks for the report!
#42210 was just merged which should fix the issues both on CRAN (17.0.0 is planned for next week) and for the nightlies which didn't have a successful build since then due to a network issue.  

Sorry for the inconvenience. If you need the functionality _now_ then [ppp](https://packagemanager.posit.co/client/#/repos/cran/packages/overview?search=arrow) should have fully featured binaries or you can set `NOT_CRAN=true LIBARROW_MINIMAL=false LIBARROW_BINARY=false` and install from source.

**Comment by grantmcdermott** [comment]
> If you need the functionality now then [ppp](https://packagemanager.posit.co/client/#/repos/cran/packages/overview?search=arrow) should have fully featured binaries

Thanks. Confirmed workaround for the moment is to downgrade/grab the 15.0.1 binary from PPM:

```r
install.packages("arrow", repos = "https://packagemanager.posit.co/cran/2024-04-01")
```

Feel free to close once 17.0.0 hits CRAN.

**Comment by eitsupi** [comment]
Does the build of version 17 on CRAN continue to fail?

**Comment by grantmcdermott** [comment]
> Does the build of version 17 on CRAN continue to fail?

Looks like the CRAN binaries still haven't been built for x86_64 (Intel-based) Macs yet... which is unfortunately what I'm still using atm.

(I can confirm that the r-universe release is working again, though and supports s3 access again.)

**Comment by grantmcdermott** [comment]
Confirmed working again.
