### ISSUE TITLE
[R] So-called non-API entry points

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#43044]
### Describe the enhancement requested

There has been some churn on the so-called non-api entry points that CRAN is checking. Some of these come from `cpp11` directly and those are ok (as of now, at least, it seems — but that could change arbitrarily!). But others just popped up recently and are from our code.

The ones from `cpp11` that we can (mostly) ignore (for now): `SETLENGTH`, `SET_GROWABLE_BIT`, `SET_TRUELENGTH`

The new ones are: `LEVELS` and `Rf_findVarInFrame3`

https://github.com/apache/arrow/blob/e635cc23f2f39055ff463730bf1e328af791f85c/r/src/arrow_cpp11.h#L47-L48

https://github.com/apache/arrow/blob/e635cc23f2f39055ff463730bf1e328af791f85c/r/src/arrow_cpp11.h#L397

The second one has a similar call `Rf_findVarInFrame` that might be useable (and doesn't seem to complain) in that same file. Not sure about the `LEVELS`.

### Component(s)

R

**Comment by nealrichardson** [comment]
`LEVELS` looks like something Romain pulled in when we switched to cpp11 (https://github.com/apache/arrow/commit/55defbf7a14896dc1a166f04f62f576179b4a1d5#diff-ef920fdae5124d20b341b9710adf8a33367cd2d24e08510913419ead9c8bb40fR86). I wonder if there's a proper cpp11 way to handle some of this string typing now.

**Comment by jonkeane** [comment]
Ok, I've got `Rf_findVarInFrame3` fixed in  https://github.com/apache/arrow/compare/main...jonkeane:non_api?expand=1

I haven't found a clean cpp11 replacement for `LEVELS` yet

**Comment by jonkeane** [comment]
Also ROFL, "added in R 4.5.0", from WRE

> IS_ASCII
> Use charIsASCII, added in R 4.5.0.
> 
> IS_UTF8
> Use charIsUTF8, added in R 4.5.0, or avoid completely.

Thought https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Querying-CHARSXP-encoding-1 looks promising

**Comment by jonkeane** [comment]
Issue resolved by pull request 43173
https://github.com/apache/arrow/pull/43173
