### ISSUE TITLE
[CI][C++][Python][Gandiva] Some gandiva tests fail at verify-rc-source-python-linux-almalinux-8-amd64 with Symbols not found: [ llvm_orc_registerEHFrameSectionWrapper ]

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43059]
### Describe the bug, including details regarding any error messages, version, and platform.

Several gandiva tests are failing on [verify-rc-source-python-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9662756314/job/26653333731) with the following error:
```
 pyarrow/tests/test_gandiva.py:359: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyarrow/gandiva.pyx:672: in pyarrow.gandiva.make_filter
    cpdef make_filter(Schema schema, Condition condition,
pyarrow/gandiva.pyx:700: in pyarrow.gandiva.make_filter
    check_status(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   raise convert_status(status)
E   pyarrow.lib.ArrowException: CodeGenError in Gandiva: Could not create LLJIT instance: Symbols not found: [ llvm_orc_registerEHFrameSectionWrapper ]

pyarrow/error.pxi:91: ArrowException
```

### Component(s)

C++ - Gandiva, Continuous Integration, Python

**Comment by raulcd** [comment]
@pitrou any idea what the issue might be here?

**Comment by pitrou** [comment]
No idea. Could be a linking issue, or perhaps two different versions of LLVM are present? @kou

**Comment by kou** [comment]
Ah, this is https://github.com/apache/arrow/issues/39695 .

Workaround: https://github.com/apache/arrow/issues/39695#issuecomment-1912186637
Or use older LLVM.

**Comment by raulcd** [comment]
Should we pin `llvm` here? https://github.com/apache/arrow/blob/main/dev/release/setup-rhel-rebuilds.sh#L40
It seems the [docker build](https://github.com/ursacomputing/crossbow/actions/runs/9286396581/job/25553012058#step:6:1797)  is using:
```
#9 44.02  llvm-devel                                x86_64  17.0.6-2.module_el8.10.0+3757+fc27b834            appstream   4.1 M
#9 44.02  llvm-toolset                              x86_64  17.0.6-2.module_el8.10.0+3757+fc27b834            appstream    22 k
```
And [last success was](https://github.com/ursacomputing/crossbow/actions/runs/9269608801/job/25500772253#step:6:686):
```
/usr/lib64/cmake/llvm/LLVMConfig.cmake, version: 16.0.6
```

**Comment by kou** [comment]
I think that it's the easiest workaround.

**Comment by raulcd** [comment]
> I think that it's the easiest workaround.

The older version doesn't seem to be available anymore:
```
+ dnf --showduplicates list llvm-devel
AlmaLinux 8 - BaseOS                            3.4 MB/s | 4.0 MB     00:01    
AlmaLinux 8 - AppStream                         5.1 MB/s |  11 MB     00:02    
AlmaLinux 8 - Extras                             15 kB/s |  21 kB     00:01    
Available Packages
llvm-devel.i686          17.0.6-2.module_el8.10.0+3757+fc27b834        appstream
llvm-devel.x86_64        17.0.6-2.module_el8.10.0+3757+fc27b834        appstream
```

**Comment by kou** [comment]
Issue resolved by pull request 43093
https://github.com/apache/arrow/pull/43093

**Comment by danepitkin** [comment]
FYI this is affecting Gandiva for Java JNI as well. https://github.com/apache/arrow/issues/43769
