### ISSUE TITLE
[C][Python] Vendor pythoncapi-compat instead of adjusting changes manually

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43069]
### Describe the enhancement requested

This issue is an enhancement follow up from this comment: https://github.com/apache/arrow/pull/42034#issuecomment-2158594109

Based on the discussion:
Vendoring it should be trivial: there is [a single .h file](https://github.com/python/pythoncapi-compat/blob/main/pythoncapi_compat.h).

### Component(s)

C++, Python

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 43767
https://github.com/apache/arrow/pull/43767
