### ISSUE TITLE
[C++][Parquet] Reading corrupted encrypted Parquet files can cause a segfault

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#43070]
### Describe the bug, including details regarding any error messages, version, and platform.

We experienced a segfault reading an encrypted Parquet file and traced this down to `EVP_DecryptUpdate` being called [here](https://github.com/apache/arrow/blob/7dd1d34074af176d9e861a360e135ae57b21cf96/cpp/src/parquet/encryption/encryption_internal.cc#L489) with a negative value for the last parameter, which is the ciphertext length.

By debugging the problem I found that the length was being read from the file as zero, which became negative after subtracting `length_buffer_length_`, `kNonceLength` and `kGcmTagLength`.

This file was written with PyArrow but we suspect it may have become corrupted somehow. I would expect that this should result in a catchable exception rather than a segfault though.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Wow, this is horrid. Thanks for noticing this @adamreeve .

**Comment by mapleFU** [comment]
Issue resolved by pull request 43071
https://github.com/apache/arrow/pull/43071
