### ISSUE TITLE
[CI][Dev] Add shell script linter

### ISSUE THREAD

**Issue by kou** [apache/arrow#43080]
### Describe the enhancement requested

Candidate:
* ShellCheck
  * https://github.com/koalaman/shellcheck
  * https://github.com/koalaman/shellcheck-precommit

### Component(s)

Continuous Integration, Developer Tools

**Comment by pitrou** [comment]
This sounds like a good to me. I'm very bad at writing shell scripts and I would appreciate this.

**Comment by kou** [comment]
I've introduced shellcheck and shfmt to apache/arrow-go by https://github.com/apache/arrow-go/commit/d486377db4f25b0c38a2a16715c6c7d6d36745b8#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9 .
I'll do the same thing to apache/arrow after we completed the apache/arrow-go migration.

**Comment by pitrou** [comment]
I still think this would be a good idea. Also cc @assignUser

**Comment by assignUser** [comment]
Issue resolved by pull request 44724
https://github.com/apache/arrow/pull/44724

**Comment by pitrou** [comment]
Thanks, now I suppose we should go and fix all problematic scripts in the codebase?

**Comment by kou** [comment]
Yes. Let's track it in #44748.
