### ISSUE TITLE
[C++][FS][Azure] Implement `PathFromUri` support

### ISSUE THREAD

**Issue by OliLay** [apache/arrow#43097]
### Describe the enhancement requested

Other filesystems, such as e.g. S3, implement the virtual `PathFromUri` method. For the respective S3 implementation, see [here](https://github.com/apache/arrow/blob/edfa343eeca008513f0300924380e1b187cc976b/cpp/src/arrow/filesystem/s3fs.cc#L2814).
For the Azure file system, this method is currently not implemented while it certainly should be to comply with the file system API.

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 43098
https://github.com/apache/arrow/pull/43098
