### ISSUE TITLE
[CI][Packaging] Could not resolve host: mirrorlist.centos.org; Unknown error on wheel almalinux 2014 jobs

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43119]
### Describe the bug, including details regarding any error messages, version, and platform.

- [wheel-manylinux-2014-cp310-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9757628994/job/26930414925)
- [wheel-manylinux-2014-cp311-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9757626763/job/26930405465)
- [wheel-manylinux-2014-cp312-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9757627605/job/26930408341)
- [wheel-manylinux-2014-cp38-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9757626580/job/26930404986)
- [wheel-manylinux-2014-cp39-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9757629135/job/26930415150)

Are failing with the following error:
```
#7 [ 2/17] RUN yum install -y dnf
#7 0.412 Loaded plugins: fastestmirror, ovl
#7 0.683 Determining fastest mirrors
#7 0.696 Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=aarch64&repo=os&infra=container error was
#7 0.696 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
#7 0.698 
#7 0.698 
#7 0.698  One of the configured repositories failed (Unknown),
#7 0.698  and yum doesn't have enough cached data to continue. At this point the only
#7 0.698  safe thing yum can do is fail. There are a few ways to work "fix" this:
#7 0.698 
#7 0.698      1. Contact the upstream for the repository and get them to fix the problem.
#7 0.698 
#7 0.698      2. Reconfigure the baseurl/etc. for the repository, to point to a working
#7 0.698         upstream. This is most often useful if you are using a newer
#7 0.698         distribution release than is supported by the repository (and the
#7 0.698         packages for the previous distribution release still work).
#7 0.698 
#7 0.698      3. Run the command with the repository temporarily disabled
#7 0.698             yum --disablerepo=<repoid> ...
#7 0.698 
#7 0.698      4. Disable the repository permanently, so yum won't use it by default. Yum
#7 0.698         will then just ignore the repository until you permanently enable it
#7 0.698         again or use --enablerepo for temporary usage:
#7 0.698 
#7 0.698             yum-config-manager --disable <repoid>
#7 0.698         or
#7 0.698             subscription-manager repos --disable=<repoid>
#7 0.698 
#7 0.698      5. Configure the failing repository to be skipped, if it is unavailable.
#7 0.698         Note that yum will try to contact the repo. when it runs most commands,
#7 0.698         so will have to try and fail each time (and thus. yum will be be much
#7 0.698         slower). If it is a very temporary problem though, this is often a nice
#7 0.698         compromise:
#7 0.698 
#7 0.698             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
#7 0.698 
```

I am trying to understand if this has to do with the CentOS 7 EOL.

### Component(s)

Continuous Integration, Packaging

**Comment by raulcd** [comment]
FYI @ianmcook @amoeba @kou this is currently a blocker for the release

**Comment by raulcd** [comment]
The `r-binary-packages` and `java-jars` jobs on the maintenance branch are also failing with the same error, see all the jobs here:
https://github.com/apache/arrow/pull/43113#issuecomment-2202655512

**Comment by bkief** [comment]
CentOS 7 EOL'd on June 30 and they took down `mirrorlist.centos.org` with it

There is a nice solution here:
https://serverfault.com/a/1161847

**Comment by kou** [comment]
I've split the centos-7-amd64 job to #43122.

**Comment by raulcd** [comment]
Issue resolved by pull request 43121
https://github.com/apache/arrow/pull/43121
