### ISSUE TITLE
[C++][Compute] Row table is consuming more memory than expected

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#43129]
### Describe the enhancement requested

When I was investigating #43116 , found that row table consumed more memory than expected. For example, the questioning test case in #41336 encodes data a little more than 2GB, but the actual buffer takes 8GB, which is expected to be 4GB (with the growing strategy being double the current size).

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 43125
https://github.com/apache/arrow/pull/43125
