### ISSUE TITLE
[C++][ArrowFlight] Crash due to UCS thread mode 

### ISSUE THREAD

**Issue by amirgon** [apache/arrow#43130]
### Describe the bug, including details regarding any error messages, version, and platform.

ArrowFlight UCX transport sets `UCS_THREAD_MODE_SERIALIZED` mode:

https://github.com/apache/arrow/blob/fd6bf5a532245ae80908d52b90d5462f9b2f9882/cpp/src/arrow/flight/transport/ucx/ucx_client.cc#L100

This can cause UCX to crash (mpool corruption).
This happens when buffer is deallocated on a different thread. In such case two threads access UCX memory pool simultaneously.   
To fix that, need to change thread mode to `UCS_THREAD_MODE_MULTI`.

See discussion on UCX forum: https://github.com/openucx/ucx/discussions/9987

Opened a PR: https://github.com/apache/arrow/pull/43120

### Component(s)

C++, FlightRPC

**Comment by lidavidm** [comment]
Issue resolved by pull request 43120
https://github.com/apache/arrow/pull/43120
