### ISSUE TITLE
[C++][Parquet] Refactor Encryptor API to use arrow::util::span instead of raw pointers

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#43142]
### Describe the enhancement requested

This change was made to the Decryptor API in #43071, we should do the same for the Encryptor API for consistency and to make the code more maintainable.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 43195
https://github.com/apache/arrow/pull/43195
