### ISSUE TITLE
[C++][Parquet] Replace use of int with int32_t in the Parquet encryption APIs

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#43141]
### Describe the enhancement requested

For better portability we should prefer using int32_t over int. See this comment for context: https://github.com/apache/arrow/pull/43071/files#r1664346920

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 43413
https://github.com/apache/arrow/pull/43413
