### ISSUE TITLE
[Docs] Correction needed in pyarrow.compute.microsecond

### ISSUE THREAD

**Issue by Aloqeely** [apache/arrow#43150]
### Describe the bug, including details regarding any error messages, version, and platform.

The doc says "**Millisecond** returns number of microseconds since the last full millisecond" 
But, the method name is microsecond not millisecond, seems to be copied over from `pyarrow.compute.millisecond`

https://arrow.apache.org/docs/dev/python/generated/pyarrow.compute.microsecond.html

### Component(s)

Documentation

**Comment by rok** [comment]
Thanks for reporting this @Aloqeely ! We should fix this. Would you like to open a PR?

**Comment by Aloqeely** [comment]
Alright.

**Comment by rok** [comment]
Issue resolved by pull request 43151
https://github.com/apache/arrow/pull/43151
