### ISSUE TITLE
[CI][Packaging] `dev/release/utils-create-release-tarball.sh` should not include the release candidate number in the name of the tarball's top-level directory.     

### ISSUE THREAD

**Issue by sgilmore10** [apache/arrow#43199]
### Describe the bug, including details regarding any error messages, version, and platform.

`dev/release/util-create-release-tarball.sh` should not include the release candidate number in the name of the tarball's top-level directory. If the release candidate number is included, the binaries and the release verification tasks fail because the tarball entries have an unexpected folder hierarchy. See https://github.com/apache/arrow/pull/43188#issuecomment-2215002552. 

### Component(s)

Continuous Integration, Packaging, Release

**Comment by raulcd** [comment]
Issue resolved by pull request 43200
https://github.com/apache/arrow/pull/43200
