### ISSUE TITLE
[C++] Are `ARROW_DCHECK*` and `DCHECK*` interchangeable?

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#43209]
### Describe the usage question you have. Please include as many useful details as  possible.

Been developing arrow C++ for a while and I've always been wondering if the `ARROW_DCHECK*` family and the `DCHECK*` family are interchangeable. It seems like to be the case from the following straight forward definition:
https://github.com/apache/arrow/blob/5e451d85d7269d3fb9c7eaab06caece5718c40e5/cpp/src/arrow/util/logging.h#L141-L148

Or is there any subtle convention around them?

### Component(s)

C++

**Comment by zeroshade** [comment]
The general convention is that when you are utilizing this from *outside* of internal Arrow code, you should use `ARROW_DCHECK_*` to indicate where the macro is coming from. This is the same convention for the `RETURN_NOT_OK` vs `ARROW_RETURN_NOT_OK` family of functions. 

At least that's my understanding.

**Comment by zanmato1984** [comment]
> The general convention is that when you are utilizing this from _outside_ of internal Arrow code, you should use `ARROW_DCHECK_*` to indicate where the macro is coming from. This is the same convention for the `RETURN_NOT_OK` vs `ARROW_RETURN_NOT_OK` family of functions.
> 
> At least that's my understanding.

Thanks @zeroshade , that makes much sense. If this is the case, then we should probably put some comments around these macros as a tiny coding guideline.

Let's wait for a while to see if others have any further comments.

**Comment by pitrou** [comment]
Issue resolved by pull request 43248
https://github.com/apache/arrow/pull/43248
