### ISSUE TITLE
parquet cpp version

### ISSUE THREAD

**Issue by rip-nsk** [apache/arrow#4320]
Likely cpp/src/parquet/.parquetcppversion should be updated (to 1.10.1 ?)

**Comment by wesm** [comment]
parquet-cpp hasn't had a release since 1.5.0, so the next release would probably be 1.6.0. I've been too busy to set up the release scripts for a Parquet-only C++ release and no one has been asking for it, so it hasn't gotten done yet since the monorepo merge

1.10.1 is the Java version number
