### ISSUE TITLE
[Java] Remove flight-core extra shaded jars

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#43217]
### Describe the bug, including details regarding any error messages, version, and platform.

Following discussion at https://github.com/apache/arrow/pull/43139#discussion_r1664949913, removing extra shaded jars generated by `flight-core` module as they are not JPMS compatible 

### Component(s)

Java

**Comment by danepitkin** [comment]
Issue resolved by pull request 43224
https://github.com/apache/arrow/pull/43224
