### ISSUE TITLE
[Java] Update Maven project details

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#43229]
### Describe the enhancement requested

Follow up of the [conversation](https://github.com/apache/arrow/pull/43191#discussion_r1669373262) at #43191

Information generated and published to Apache Maven repository/Maven Central is either missing or incorrect:
* Modules under `maven/` and `bom/` directories do not have project url, mailing list, scm and issue management links
* Children modules have incorrect project and scm urls as Maven appends by default the name of the name of the artifact to the url from the parent module
* `${project.scm.tag}` hasn't been updated and is still `apache-arrow-2.0.0`

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43231
https://github.com/apache/arrow/pull/43231
