### ISSUE TITLE
[C++][Parquet] AesEncryptor::Make should return smart pointer, not a raw pointer

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43221]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently, `AesEncryptor::Make` returns a raw `AesEncryptor*` and relies on the caller to explicit call `delete` when done with the instance. This is unsafe, since if an exception is thrown while using the encryptor, it won't be deallocated; not only this is a memory leak, but it might (?) also be a security problem if the corresponding OpenSSL cipher object keeps confidential data around.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
FTR @adamreeve @mapleFU

**Comment by mapleFU** [comment]
Besides, should we remove legacy method or deprecate it first?

**Comment by pitrou** [comment]
It's an internal API, so we can remove whatever we want :-)

**Comment by pitrou** [comment]
Issue resolved by pull request 43222
https://github.com/apache/arrow/pull/43222
