### ISSUE TITLE
[C++][Parquet] remove useless template parameter of `DeltaLengthByteArrayEncoder`

### ISSUE THREAD

**Issue by IndifferentArea** [apache/arrow#43249]
### Describe the enhancement requested

https://github.com/apache/arrow/blob/03726178494c8978bf48b9bab15ed9676e7c9196/cpp/src/parquet/encoding.cc#L2735-L2737

It seems that the template parameter `DType` is never used. In addition, [only `ByteArray` could be encoded with `DeltaLengthByteArrayEncoder`](https://parquet.apache.org/docs/file-format/data-pages/encodings/#delta-length-byte-array-delta_length_byte_array--6). So maybe it can be removed.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
Issue resolved by pull request 43250
https://github.com/apache/arrow/pull/43250
