### ISSUE TITLE
[C#] Add LargeBinary, LargeString and LargeList array types

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#43266]
### Describe the enhancement requested

This is a subtask of https://github.com/apache/arrow/issues/34736

These arrays will not be able to support value buffers > 2 GB until #23776 is addressed, but there's some value in supporting these types anyway, to simplify integration with other Arrow implementations.

See https://github.com/apache/arrow/issues/34736#issuecomment-2227511168 for some more context.

### Component(s)

C#

**Comment by adamreeve** [comment]
take

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 43269
https://github.com/apache/arrow/pull/43269
