### ISSUE TITLE
[Release] post-01-tag.sh is missing input variables on the script

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43270]
### Describe the bug, including details regarding any error messages, version, and platform.

When executing the script I got:
```
$ dev/release/post-01-tag.sh 17.0.0 2
fatal: Failed to resolve 'apache-arrow--rc^{}' as a valid ref.
```

This is because version and rc are never correctly used on the script.

### Component(s)

Release

**Comment by kou** [comment]
Issue resolved by pull request 43271
https://github.com/apache/arrow/pull/43271
