### ISSUE TITLE
[Release][Docs] 17.0.0 docs where not uploaded to artifactory

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43282]
### Summary:

https://github.com/apache/arrow/blob/main/dev/release/binary-task.rb#L1898 is missing to update the new debian-docs task.

### Investigation:
When trying to publish the generated docs for 17.0.0, the job failed with:
```
~/code/arrow-site/docs_new ~/code/arrow-site ~/code/arrow
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

```

The docs are not present at: https://apache.jfrog.io/ui/native/arrow/docs/
but are also not present on the rc(s): https://apache.jfrog.io/ui/native/arrow/docs-rc/

`test-debian-12-docs` task finished on the RC branch: https://github.com/ursacomputing/crossbow/actions/runs/9888517780/job/27312627492#step:15:27

Docs seem to be present if I test locally:
```
$    archery crossbow \
    --queue-remote https://github.com/ursacomputing/crossbow.git \
    status \                                                  
    --task-filter 'test-debian-12-docs' \
    --no-fetch \                         
    --validate \
    release-17.0.0-rc2-0
[  state] Task / Branch                                               Artifacts
-------------------------------------------------------------------------------
[SUCCESS] test-debian-12-docs                                    uploaded 1 / 1
 └ https://github.com/ursacomputing/crossbow/actions/runs/9888517780/job/27312627492
                                                          docs.tar.gz [     OK]

```
And the crossbow release: https://github.com/ursacomputing/crossbow/releases/tag/release-17.0.0-rc2-0-github-test-debian-12-docs

I've tested downloading them locally:
```
$ dev/release/04-binary-download.sh 17.0.0 2 -f test-debian-12-docs
Downloading release-17.0.0-rc2-0's artifacts.
Destination directory is /home/raulcd/code/arrow/packages/release-17.0.0-rc2-0

[  state] Task / Branch                                               Artifacts
-------------------------------------------------------------------------------
[SUCCESS] test-debian-12-docs                                    uploaded 1 / 1
 └ https://github.com/ursacomputing/crossbow/actions/runs/9888517780/job/27312627492
                                                          docs.tar.gz [     OK]
```
And they are downloaded:
```
$ ls -lrt packages/release-17.0.0-rc2-0/test-debian-12-docs/docs.tar.gz 
-rw-rw-r-- 1 raulcd raulcd 51884344 jul 16 16:35 packages/release-17.0.0-rc2-0/test-debian-12-docs/docs.tar.gz

```
It seems the binary task wasn't updated here:
https://github.com/apache/arrow/blob/main/dev/release/binary-task.rb#L1898

### Component(s)

Documentation, Release

**Comment by raulcd** [comment]
@kou how do you think we should procede with the docs for 17.0.0? Apart from updating the `binary-task.rb` for following releases

**Comment by TrungKhoaLe** [comment]
@raulcd just wanted to ask. Is this related to the issue that the pyarrow==17.0.0 cannot be found by poetry?

**Comment by raulcd** [comment]
> @raulcd just wanted to ask. Is this related to the issue that the pyarrow==17.0.0 cannot be found by poetry?

It shouldn't, is there an open issue for your issue? What version of Python are you using there is a known issue when uploading some wheels to PyPI due to quota being exceeded and that one could be the case if you are using Python 3.8 or 3.9. I just sent an email to the ML explaining it: https://lists.apache.org/thread/mnzdpwzhctx6yrjl16zn8hl7pcxxt575

**Comment by TrungKhoaLe** [comment]
I am using Python 3.9.18.  I think somebody else just opened an issue for that [here](https://github.com/apache/arrow/issues/43289).

**Comment by kou** [comment]
Issue resolved by pull request 43283
https://github.com/apache/arrow/pull/43283

**Comment by kou** [comment]
We can upload it manually for 17.0.0.
I'll do it.

**Comment by kou** [comment]
Uploaded it to https://apache.jfrog.io/ui/native/arrow/docs/17.0.0/ .
Could you try `dev/release/post-10-docs.sh`?

**Comment by raulcd** [comment]
> Could you try `dev/release/post-10-docs.sh`?

Thanks @kou `dev/release/post-10-docs.sh` execution was successful now: https://github.com/apache/arrow-site/pull/536
