### ISSUE TITLE
[Java] When can I use the latest 17.0.0 version in my pom?

### ISSUE THREAD

**Issue by GuChangyang** [apache/arrow#43290]
### Describe the usage question you have. Please include as many useful details as  possible.

The arrow 17.0.0 is released today and I updated my arrow to the latest 17.0.0 in my pom.xml, but still can not find the latest version (I can use the second-latest 16.1.0), when can I use the latest 17.0.0? thank you

### Component(s)

Java

**Comment by laurentgo** [comment]
Maybe it's a mirror synchronization thing but it seems the artifacts are available on Maven Central: https://repo1.maven.org/maven2/org/apache/arrow/arrow-bom/17.0.0/

**Comment by danepitkin** [comment]
Closing since Arrow 17 has been released for a few weeks. Please re-open if you are still seeing issues.
