### ISSUE TITLE
[Java][Docs] Install document has a broken markup part

### ISSUE THREAD

**Issue by kou** [apache/arrow#43293]
### Describe the bug, including details regarding any error messages, version, and platform.

https://arrow.apache.org/docs/dev/java/install.html#java-compatibility

>  Finally, if you are using arrow-dataset, you’ll also need to report that JDK internals need to be exposed. Modifying the command above for arrow-memory: .. code-block:: shell
>
> > \# Directly on the command line $ java –add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED -jar … # Indirectly via environment variables $ env _JAVA_OPTIONS=”–add-opens=java.base/java.nio=org.apache.arrow.dataset,org.apache.arrow.memory.core,ALL-UNNAMED” java -jar …

`code-block` isn't processed.

### Component(s)

Documentation, Java

**Comment by kou** [comment]
Ah, it seems that this was already fixed on main: https://arrow.apache.org/docs/dev/java/install.html

**Comment by kou** [comment]
Ah, no. The `code-block` part is still broken.

**Comment by llama90** [comment]
take

**Comment by kou** [comment]
Issue resolved by pull request 43295
https://github.com/apache/arrow/pull/43295
