### ISSUE TITLE
[Java] `SchemaChangeRuntimeException` in transferred empty FixedSizeListVector

### ISSUE THREAD

**Issue by jarohen** [apache/arrow#43320]
### Describe the bug, including details regarding any error messages, version, and platform.

Yep, it's a bit obscure, this one :sweat_smile: 

Arrow 17.0.0

Steps:
1. Create a FixedSizeListVector (FSLV), it initialises with a ZeroVector for its elements.
2. Add it to a dense-union through DUV.addVector
3. That method transfers the empty FSLV through DUV.addVector but, in doing so, it creates a NullVector in the new vector rather than a ZeroVector.
4. Trying to set the element vector using FSLV.addOrGetVector throws SchemaChangeRuntimeException, because it explicitly checks for ZeroVector.

Will submit a test case and a fix shortly in a PR :slightly_smiling_face: 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43321
https://github.com/apache/arrow/pull/43321
