### ISSUE TITLE
[Docs][Format] Link to Intel performance guide broken

### ISSUE THREAD

**Issue by XinyuZeng** [apache/arrow#43346]
### Describe the bug, including details regarding any error messages, version, and platform.

In [the Buffer Alignment and Padding section](https://github.com/apache/arrow/blob/main/docs/source/format/Columnar.rst#buffer-alignment-and-padding) of the spec, link to "Intel performance guide" and "SIMD" is no longer available. It would be good to update them to the latest links.

### Component(s)

Documentation

**Comment by bkmgit** [comment]
Probably further changes to hte documentation are needed.    There are now AVX256 and AVX512 instructions on AMD64 architectures, and ARM has SVE instructions. Byte boundary alignment is useful for all of these, but best choices might be architecture specific.

**Comment by kou** [comment]
Issue resolved by pull request 43347
https://github.com/apache/arrow/pull/43347
