### ISSUE TITLE
[Go] ReadRowGroups panics with canceled context

### ISSUE THREAD

**Issue by sebdotv** [apache/arrow#43359]
### Describe the bug, including details regarding any error messages, version, and platform.

- Create a canceled `Context`
- Call `ReadTable`: `ReadRowGroups` might panic when trying to read first column length because it was not initialized
- Furthermore, `releaseColumns` might also panic for the same reason

### Component(s)

Go

**Comment by joellubi** [comment]
Issue resolved by pull request 43360
https://github.com/apache/arrow/pull/43360
