### ISSUE TITLE
[R] Some lints in the R code base

### ISSUE THREAD

**Issue by etiennebacher** [apache/arrow#43357]
### Describe the bug, including details regarding any error messages, version, and platform.

The codebase in R uses some inefficient patterns (e.g. `any(is.na())` instead of `anyNA()`) or patterns for which an easier-to-read alternative exists (e.g. `expect_equal(names(x), c("a", "b"))` instead of `expect_named(x, c("a", "b"))`).

Fixing those lints doesn't have any visible effect for the user but makes the code more maintainable.

### Component(s)

R

**Comment by thisisnic** [comment]
Issue resolved by pull request 43338
https://github.com/apache/arrow/pull/43338
