### ISSUE TITLE
[CI] Upgrade macOS to a supported version

### ISSUE THREAD

**Issue by llama90** [apache/arrow#43386]
### Describe the enhancement requested

According to [issue](https://github.com/apache/arrow/issues/43377), the current macOS (`MACOSX_DEPLOYMENT_TARGET`) version is no longer supported and should be upgraded to a supported version.

- reference: https://endoflife.date/macos https://github.com/apache/arrow/blob/a88f0cd0368f81f1b9243d443cd571d09242c5b1/dev/tasks/verify-rc/github.macos.yml#L24-L25

- [code search result](https://github.com/search?q=repo%3Aapache%2Farrow%20MACOSX_DEPLOYMENT_TARGET&type=code)

### Component(s)

Continuous Integration

**Comment by raulcd** [comment]
I did start some work here: https://github.com/apache/arrow/pull/43137
due to: https://github.com/apache/arrow/issues/41696
but I have to come back to it

**Comment by llama90** [comment]
> I did start some work here: #43137 due to: #41696 but I have to come back to it

Oh! It looks like there is already a related issue. This issue appears to be a duplicate, so I will close it.

Thank you for your attention.
