### ISSUE TITLE
[Python] Mappings that implement `__arrow_c_schema__` never have their method invoked

### ISSUE THREAD

**Issue by cpcloud** [apache/arrow#43388]
### Describe the bug, including details regarding any error messages, version, and platform.

The implementation of `pyarrow.schema` doesn't allow objects that are `Mapping`s to take advantage of `__arrow_c_schema__` because `Mapping` is checked before `__arrow_c_schema__` is checked.

This seems like a bug considering that custom schema objects naturally fit into the `Mapping` concept.

Would it make sense to swap the order here and first check for `__arrow_c_schema__` and **then** check whether an object is a mapping?

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Good point, thanks for the issue! 
I don't think there was a specific reason for this order in the code (added in https://github.com/apache/arrow/pull/37797, cc @wjones127). Will do a PR to switch the order.

**Comment by jorisvandenbossche** [comment]
-> https://github.com/apache/arrow/pull/43486

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 43486
https://github.com/apache/arrow/pull/43486
