### ISSUE TITLE
[Python] Expose methods to get the device and memory_manager on the pyarrow.cuda.Context class

### ISSUE THREAD

**Issue by anjakefala** [apache/arrow#43391]
### Describe the enhancement requested

Right now you can't yet create a CUDA MemoryManager. An existing approach is to create a dummy buffer and then use that to access its memory manager to get that object

```
    _, buf = make_random_buffer(size=10, target='device')
    mm_cuda = buf.memory_manager
```

One way is to add attributes to the existing Context class to get the device and memory manager.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 43392
https://github.com/apache/arrow/pull/43392
