### ISSUE TITLE
The Go flightsql driver doesn't handle scanning LargeString or LargeBinary types

### ISSUE THREAD

**Issue by phillipleblanc** [apache/arrow#43403]
### Describe the bug, including details regarding any error messages, version, and platform.

The Go flightsql database driver currently does not handle scanning string or byte values where the Arrow type is LargeString or LargeBinary.

This code will fail with `type *array.LargeString: not supported` today

```go
db, err := sql.Open("flightsql", "flightsql://some_endpoint")
if err != nil {
	panic(err)
}
defer db.Close()
row := db.QueryRow("SELECT string_value FROM table LIMIT 1")

log.Println("Reading row")
var string_value string
if err := rows.Scan(&string_value); err != nil {
  // If `string_value` is a LargeString type, this will error
}
```

### Component(s)

Go

**Comment by zeroshade** [comment]
Can you try the ADBC FlightSQL driver instead? It should hopefully work correctly with large string and large binary. If not then we can address it

**Comment by phillipleblanc** [comment]
> Can you try the ADBC FlightSQL driver instead? It should hopefully work correctly with large string and large binary. If not then we can address it

Ok, I'll try that

**Comment by phillipleblanc** [comment]
I haven't had a chance to test this on ADBC yet, but if its still a problem will open a different issue for that.
