### ISSUE TITLE
[CI] Add wheels and java-jars to vcpkg group tasks

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43418]
### Describe the enhancement requested

As suggested here: https://github.com/apache/arrow/pull/42171#issuecomment-2172095401

We could add the java-jars and wheels to the vcpkg group on our tasks

### Component(s)

Continuous Integration

**Comment by assignUser** [comment]
Issue resolved by pull request 43419
https://github.com/apache/arrow/pull/43419
