### ISSUE TITLE
[Java] Upgrade JNI version

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#43425]
### Describe the enhancement requested

With Java 11 as the new min supported version, the JNI version can be updated to `JNI_VERSION_10`. See https://docs.oracle.com/en/java/javase/21/docs/specs/jni/functions.html#version-information for version matrix.

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43424
https://github.com/apache/arrow/pull/43424
