### ISSUE TITLE
[Java] Do not publish protobuf based on filename

### ISSUE THREAD

**Issue by danepitkin** [apache/arrow#43437]
### Describe the enhancement requested

After migrating to Java 11, we see this warning:

```
[WARNING] * Required filename-based automodules detected: [protobuf-java-3.25.1.jar, protobuf-java-util-3.25.1.jar]. Please don't publish this project to a public artifact repository! *
```

We should upgrade to a version of protobuf that includes the `Automatic-Module-Name`, which prevents downstream projects from experiencing dependency version conflicts.

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43436
https://github.com/apache/arrow/pull/43436
