### ISSUE TITLE
[Packaging][C++] Fail to build bundled ORC with the official LZ4 CMake package on Debian GNU/Linux trixie

### ISSUE THREAD

**Issue by kou** [apache/arrow#43467]
### Describe the bug, including details regarding any error messages, version, and platform.

Recently, Debian GNU/Linux trixie provides LZ4 CMake package based on the official CMake build system.

Our LZ4 detection code doesn't work with it:

https://github.com/ursacomputing/crossbow/actions/runs/10130290903/job/28011414872#step:8:3691

```text
-- Building Apache ORC from source
CMake Error at cmake_modules/ThirdpartyToolchain.cmake:4512 (get_target_property):
  get_target_property() called with non-existent target "LZ4::lz4".
Call Stack (most recent call first):
  cmake_modules/ThirdpartyToolchain.cmake:208 (build_orc)
  cmake_modules/ThirdpartyToolchain.cmake:304 (build_dependency)
  cmake_modules/ThirdpartyToolchain.cmake:4698 (resolve_dependency)
  CMakeLists.txt:544 (include)
```

Because `LZ4::lz4` isn't provided with LZ4 1.9.4. It's available since 1.10.0.

### Component(s)

C++, Packaging

**Comment by assignUser** [comment]
Issue resolved by pull request 43468
https://github.com/apache/arrow/pull/43468
