### ISSUE TITLE
Restrict direct access to `sun.misc.Unsafe`

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#43479]
### Describe the enhancement requested

`sun.misc.Unsafe` is a Java internal class only accessible to classes loaded of the boot classloader, unless one uses reflection to bypass this restriction.

`org.apache.arrow.memory.util.MemoryUtil` makes it available as a public field to any java classes which is kind of opening a pandora box. As a first step towards switching from `sun.misc.Unsafe` to safer memory access methods (which may become a requirement at some point as discussed in [JEP 471](https://openjdk.org/jeps/471) ), remove direct access to `sun.misc.Unsafe` instance.

### Component(s)

Java

**Comment by danepitkin** [comment]
Issue resolved by pull request 43480
https://github.com/apache/arrow/pull/43480
