### ISSUE TITLE
[CI] Crossbow report shouldn't include jobs that aren't configured / run recently

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#43499]
### Describe the enhancement requested

In #43451 we turned off a bunch of jobs that were constantly red, but I was surprised to see that they are still [showing up on the crossbow nightly report](http://crossbow.voltrondata.com) would it be possible to update that report so that jobs that haven't been run in the last 2-3 days aren't in the list of builds to show up?

For example for `conda-win-x64-cuda-py3` the last run was three days ago, but it's still listed in the table + looks like it ran with the most recent group and failed.

cc @boshek  

### Component(s)

Continuous Integration

**Comment by boshek** [comment]
Yep I can help with this.
