### ISSUE TITLE
[C++][Compute] Consider widening the row offset of the row table to 64-bit

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#43495]
### Describe the enhancement requested

We’ve seen several reports about the hash join not working for large inputs (e.g., #34474, #37655, and #36995). The reason turns out to be that the row table (the hash table for the hash join) uses `uint32_t` to represent the row offset within the row data buffer, effectively preventing the row data from exceeding 4GB.

What makes things worse is that, when this limitation is exceeded, users can barely workaround it by regular methods like "splitting the input into smaller batches," which works for many other issues. Because the row table accumulates all the input data, smaller batches do not change the overall data size.

There are also some other aspects:
1. 32-bit row offset also makes the row table implementation error-prone. For example, #35087, #42188, and #43226 are fixes to address or detect certain edge cases related to the row offset. Even for the fixed-length code path, which doesn’t deal with the offset buffer at all and thus is supposed to be less problematic, there are obvious offset overflow issues like [1] and [2] (these issues are currently unreported but observed in my local experiments).
2. We are going to support large-offset data types for the row table eventually, as requested in #31622.

Therefore, we should consider widening the row offset of the row table to 64-bit.

[1] https://github.com/apache/arrow/blob/187197c369058f7d1377c1b161c469a9e4542caf/cpp/src/arrow/compute/row/compare_internal.cc#L108
[2] https://github.com/apache/arrow/blob/187197c369058f7d1377c1b161c469a9e4542caf/cpp/src/arrow/compute/row/compare_internal_avx2.cc#L243-L244

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 43389
https://github.com/apache/arrow/pull/43389
