### ISSUE TITLE
[Java] Fix TestFragmentScanOptions test result does not match

### ISSUE THREAD

**Issue by jinchengchenghh** [apache/arrow#43506]
### Describe the bug, including details regarding any error messages, version, and platform.

Some typo causes dataset tests not run in CI, so this test failed but pass CI
```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestFragmentScanOptions.testCsvConvertOptions:80 expected: <[Id: Int(32, true), Name: Utf8, Language: Utf8]> but was: <[Id;Name;Language: Utf8]>
Error:    TestFragmentScanOptions.testCsvConvertOptionsDelimiterNotSet:123 expected: <[Id: Int(32, true), Name: Utf8, Language: Utf8]> but was: <[Id;Name;Language: Utf8]>
Error:    TestFragmentScanOptions.testCsvConvertOptionsNoOption:159 
Expected: iterable containing ["1;Juno;Java\n2;Peter;Python\n3;Celin;C++"]
     but: item 0: was <1;Juno;Java>
[INFO] 
Error:  Tests run: 40, Failures: 3, Errors: 0, Skipped: 0
```
### Component(s)

Java

**Comment by vibhatha** [comment]
@jinchengchenghh let's add the failure and stacktrace in the description section.

**Comment by vibhatha** [comment]
Also, please add  [Java] Fix TestFragmentScanOptions test result does not match

**Comment by jinchengchenghh** [comment]
Fixed in https://github.com/apache/arrow/pull/43503

**Comment by vibhatha** [comment]
@jinchengchenghh in my latest PR (rebased), I am getting this, https://github.com/apache/arrow/actions/runs/10344923592/job/28631183503?pr=43637#step:7:59380

**Comment by jinchengchenghh** [comment]
I pushed my fix to this branch as you say https://github.com/apache/arrow/pull/43503, but it is missed in the merged commits...

I will pull a new request to solve

**Comment by jinchengchenghh** [comment]
Do you have a backup for my fix? I cannot find it now, sad. @vibhatha

**Comment by vibhatha** [comment]
Oh, wait, I cannot see that diff in the merged PR, what happened to that?

**Comment by jinchengchenghh** [comment]
Lucky thing, I find it in another folder. I have create a PR.

**Comment by lidavidm** [comment]
Issue resolved by pull request 43639
https://github.com/apache/arrow/pull/43639
