### ISSUE TITLE
[C++] Use ViewOrCopyTo instead of CopyTo when pretty printing non-CPU data

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#43507]
As a follow-up on https://github.com/apache/arrow/issues/41664 (PR https://github.com/apache/arrow/pull/42010), which ensured to copy data to the CPU when trying to pretty print it. 

But, the PR was using `CopyTo` when the data was not using a CPU device allocation type, i.e.:

```cpp
    if (array.device_type() != DeviceAllocationType::kCPU) {
      ARROW_ASSIGN_OR_RAISE(auto array_cpu, array.CopyTo(default_cpu_memory_manager()));
      ...
```

But this should better use `ViewOrCopyTo`, in case the data can be viewed as CPU data without a copy.

**Comment by kou** [comment]
Issue resolved by pull request 43508
https://github.com/apache/arrow/pull/43508
