### ISSUE TITLE
[Java] Fix Java JNI / AMD64 manylinux2014 Java JNI test not test dataset module

### ISSUE THREAD

**Issue by jinchengchenghh** [apache/arrow#43502]
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/pull/41646#issuecomment-2259855172

### Component(s)

Java

**Comment by danepitkin** [comment]
Issue resolved by pull request 43503
https://github.com/apache/arrow/pull/43503
