### ISSUE TITLE
Pyarrow hdfs3 ls command results in seg fault

### ISSUE THREAD

**Issue by pranav-kohli** [apache/arrow#4350]
I am using pyarrow to connect to hdfs client on my mac.
However the ls command results in seg fault

```
import pyarrow as pa
from hdfs3 import HDFileSystem
try:
    pyhdfs = pa.hdfs.connect(host='localhost', port=8020, driver='libhdfs3')
    pyhdfs.ls('/')   # doesnt work
    hdfs = HDFileSystem(host='localhost', port=8020)
    hdfs.ls('/')
except:
    if pyhdfs:
        pyhdfs.close()
    if hdfs:
     hdfs.disconnect()
    
```

pyarrow==0.13.0
hdfs3==0.3.0

**Comment by wesm** [comment]
We don't support the latest version of libhdfs3 on conda-forge yet. It's unclear whether continuing to support this library is worthwhile because it is not maintained by a very large community

https://issues.apache.org/jira/browse/ARROW-1465
