### ISSUE TITLE
[R] Add link to ?acero from ?list_compute_functions

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#43509]
### Describe the enhancement requested

As shown [here](https://forum.posit.co/t/arrow-filtering-an-arrow-table-between-a-range-of-dates/189685), users may end up in `list_compute_functions()` docs when they actually would find the docs that come up calling `?acero` more helpful.  Let's update the former to add a link to the latter.

### Component(s)

R

**Comment by amoeba** [comment]
Issue resolved by pull request 44210
https://github.com/apache/arrow/pull/44210
