### ISSUE TITLE
[Python][Packaging] Support Python 3.13 and upload wheels

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#43519]
Python 3.13 is currently in a prerelease status (a first release candidate was released today: https://discuss.python.org/t/python-3-13-0-release-candidate-1-released/59703) and is expected to have a final release in October this year (https://devguide.python.org/versions).

We should ensure we are fully ready to support Python 3.13 for the PyArrow 18 release that will happen around the same time (or potentially even sooner if we would have a 17.0.x bug fix release).

https://github.com/apache/arrow/pull/42034 already fixed a build issue with Python 3.13, and on the short term I think we should try to have 1) a CI build using Python 3.13 to ensure this keeps working, and 2) set up a wheel build so we can upload nightly wheels for Python 3.13 for downstream testing.

(equivalent PR for Python 3.12: https://github.com/apache/arrow/pull/37901)

---

- [x] Start building nightly wheels for Python 3.13: https://github.com/apache/arrow/pull/43539
- [x] Also add py 3.13 conda build once that is supported in conda-forge (https://github.com/apache/arrow/blob/712cfe6d84bd344cfe57a1e4c791f8a4d052c76d/dev/tasks/tasks.yml#L1200-L1201)
- [x] Update `requirements-wheel-build.txt` and `requirements-wheel-test.txt` to install released versions
- [ ] Update the places where we currently use "3.13-rc" or "rc1" or "3.13.0-rc1" (dev/tasks/python-wheels/github.linux.yml, ci/scripts/install_python.sh, the windows docker files)
- [x] Enable GCS testing once google-testbench (grpcio) can be installed (update `install_gcs_testbench.sh`) (or address [GH-38183](https://github.com/apache/arrow/issues/38183) and install testbench with independent python version)
  - This has been resolved by https://github.com/apache/arrow/pull/43852 and https://github.com/apache/arrow/pull/43884

**Comment by raulcd** [comment]
I was planning, if necessary, to delay the feature freeze for 18.0.0 for a week to have Python 3.13 wheels.

**Comment by jorisvandenbossche** [comment]
We can actually make wheels right now (and we should ideally produce nightly wheels well before the scheduled release of 18.0), because Python 3.13 is ABI stable now, and wheels built with the current Python 3.13 will work with the final 3.13 releases. 

(so there is certainly no need to delay 18.0.0 AFAIK)

**Comment by jorisvandenbossche** [comment]
Follow-ups after  https://github.com/apache/arrow/pull/43539: 

- Also add py 3.13 conda build once that is supported in conda-forge (https://github.com/apache/arrow/blob/712cfe6d84bd344cfe57a1e4c791f8a4d052c76d/dev/tasks/tasks.yml#L1200-L1201)
- Update `requirements-wheel-build.txt` and `requirements-wheel-test.txt` to install released versions
- Update the places where we currently use "3.13-rc" or "rc1" or "3.13.0-rc1" (dev/tasks/python-wheels/github.linux.yml, ci/scripts/install_python.sh, the windows docker files)
- Enable GCS testing once google-testbench (grpcio) can be installed (update `install_gcs_testbench.sh`)

**Comment by jarrodmillman** [comment]
Python 3.13 is scheduled for Monday (10/7). Would it be possible to make a 18.0.0b0 or 18.0.0rc0 release on PyPI in the near future? I know you have wheels on https://anaconda.org/scientific-python-nightly-wheels/pyarrow/files, but having a pre-release on PyPI would make it easier for projects that aren't aware of the "nightly" wheels.

**Comment by wizard86pz** [comment]
I've installed today the v3.13 of Python, and it's affected by this pyarrow issue.
Should I wait for a new release of python 3.13 to have the fix?

**Comment by bgupta** [comment]
3.13.0 is GA. Issue still persists.

**Comment by pitrou** [comment]
According to https://discuss.python.org/t/launch-day-availability-of-python-3-13-in-conda-forge/67124/1, 3.13 is now available in conda-forge.

**Comment by raulcd** [comment]
The only missing task if to update to the final released version of Python (we are just waiting for chocolatey or to migrate out of chocolatey).
I am closing this as done as I am close to create the first RC for 18.0.0.
Feel free to open a subtask for:
- Update the places where we currently use "3.13-rc" or "rc1" or "3.13.0-rc1" (dev/tasks/python-wheels/github.linux.yml, ci/scripts/install_python.sh, the windows docker files)

**Comment by bersbersbers** [comment]
> we are just waiting for chocolatey or to migrate out of chocolatey

Wow - I was not aware it takes chocolatey more than a week to update the latest stable Python version. Considering that there are packages whose 3.13 support depends on arrow's, maybe you want to consider scoop in the future, which updated a week ago: https://github.com/ScoopInstaller/Main/commit/ec70b275c5a66cfd7316fe5645ab3b04a8350dd6

**Comment by pllim** [comment]
Given this issue is closed, where should I subscribe to make sure I am aware when pyarrow that is compatible is Python 3.13 is actually released? Thanks!

**Comment by edgarrmondragon** [comment]
> Given this issue is closed, where should I subscribe to make sure I am aware when pyarrow that is compatible is Python 3.13 is actually released? Thanks!

@pllim you can subscribe to the PyPI feed: https://pypi.org/rss/project/pyarrow/releases.xml

**Comment by raulcd** [comment]
Wheels for Python 3.13 have been uploaded to PyPI

**Comment by Mrunal1396** [comment]
Hi completely new here,  I faced the same issue while doing pip install taipy. I also tried manually installing cmake but it still did not work. Is this issue still open. Because I have recently downloaded Python version 3.13.1 and the same issue popped up. Also to fix the issue should I downgrade to 3.13.0 or 3.12.0. Thanks in advance.

**Comment by raulcd** [comment]
@Mrunal1396 wheels are provided for 3.13 (that covers 3.13.0 and 3.13.1) for several architectures and operating systems, see the build distributions here: https://pypi.org/project/pyarrow/#files
In  your case you are probably downloading the source distribution and building locally. Could you share a little bit more details about your environment (operating system, architecture) and some logs when you try to `pip install pyarrow`?

**Comment by Mrunal1396** [comment]
@raulcd sir I am trying to pip install taipy which is using pyarrow version=17.0.0 which seems incompatible with python version 13.1 here is the error screenshot [`![IMG_20241212_015006544_HDR.jpg](https://github.com/user-attachments/assets/fc653c73-16b2-4430-a90a-9e182a0f6f34)

**Comment by raulcd** [comment]
oh, yes, we don't have wheels for Python 3.13 for pyarrow 17.0.0. You'll have to use pyarrow 18.0.0 or 18.1.0 for Python 3.13 or build pyarrow yourself.

**Comment by Mrunal1396** [comment]
I unfortunately don't know how to build. I am trying now to see if downgrading python works
