### ISSUE TITLE
[Python] Deprecate passing build flags to setup.py (e.g. `setup.py --with-parquet`)

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#43514]
As mentioned in https://github.com/apache/arrow/pull/41494#issuecomment-2092829903 (while refactoring how to specify to the pyarrow build which components to build, i.e. to let it follow the Arrow C++ components by default), we do have a "feature" that you can specify which components to build directly to setup.py, like `python setup.py build_ext --with-parquet`. 

This is currently not used in our own codebase, and is also not documented anymore, but we did document it in the past.

In general calling setup.py directly is not recommended (although for development installs, it is still useful), furthermore there are alternatives to those flags (relying on Arrow C++ or setting an environment variable), and this would go away anyhow in case we would move away from setuptools at some point. 
So I think it is better to deprecate those options.

**Comment by raulcd** [comment]
Issue resolved by pull request 43515
https://github.com/apache/arrow/pull/43515
