### ISSUE TITLE
[C++] Support the SSE-C(server-side encryption with customer-provided keys) for the AWS s3 filesystem read and write

### ISSUE THREAD

**Issue by ripplehang** [apache/arrow#43535]
### Describe the enhancement requested

According to https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html#specifying-s3-c-encryption
The AWS S3 bucket has already support the SSE-C, is it possible for the arrow c++ to provide the API to support read/write data with SSE-C  for the aws s3 filesystem. 
Thanks

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 43601
https://github.com/apache/arrow/pull/43601
