### ISSUE TITLE
[Python] Remove usage of deprecated pkg_resources in setup.py

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#43532]
See https://setuptools.pypa.io/en/latest/pkg_resources.html

We currently use this to get the numpy include directories:

https://github.com/apache/arrow/blob/8068554a5d18129121f824978c7ee4a9c430640b/python/setup.py#L109

The general deprecation of `pkg_resources` points to use `importlib` instead (https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), but for this specific usage I think we just should use `numpy.get_include()` (https://numpy.org/devdocs/reference/generated/numpy.get_include.html)

**Comment by pitrou** [comment]
Issue resolved by pull request 43602
https://github.com/apache/arrow/pull/43602

**Comment by pitrou** [comment]
@tlm365 Can you post a comment here? This will allow assigning the issue to you.

**Comment by tlm365** [comment]
take
