### ISSUE TITLE
[R] Compilation from source ignores user compilation flags

### ISSUE THREAD

**Issue by david-cortes** [apache/arrow#43546]
### Describe the bug, including details regarding any error messages, version, and platform.

Installing the R package for `arrow` using `install.packages` without a previous system `libarrow` installation will make it compile the core library on-the-fly, but compilation of said library ignores whatever compilation flags a user sets up for their R setup.

As an example, in a linux system, if I create a file `~/.R/Makevars` like this:
```
MAKEFLAGS += -j$(nproc)
```

R packages compiled from source will be compiled in parallel using the number of threads in the system as returned by `nproc`, but installation of the core libarrow during `install.packages` will not add such flag and will thus compile single-threaded.

Same for other flags used in `Makevars`, like `CXXFLAGS`.

### Component(s)

R

**Comment by assignUser** [comment]
Setting `NOT_CRAN=true` will use nproc for the build, CRAN is very particular about core usage so it's limited on purpose. This will also opt in to use of the precompiled binaries if you have openssl and libcurl installed.

You can also set MAKEFLAGS as an envvar which will be picked up by the libarrow build.

**Comment by david-cortes** [comment]
> Setting `NOT_CRAN=true` will use nproc for the build

It was just an example. Same happens for other types of build flags, like compiler, preprocessor and linker flags which a user might also want to customize.

> You can also set MAKEFLAGS as an envvar which will be picked up by the libarrow build.

Yes, I guess one can set standard env. vars for the build system if needed, but the issue is: R packages are meant to follow the R configuration when compiling rather than following standard env. variables like `CC` and such. Other R packages do not require setting up flags in special ways.

**Comment by assignUser** [comment]
> but the issue is: R packages are meant to follow the R configuration when compiling

It does, for the R package part. Using R makevars for the libarrow build would just cause issues.

> Yes, I guess one can set standard env. vars for the build system if needed

 As you said yourself you can influence the flags for the bundled build. The bundled build and pre-compiled binaries are a convenience feature only, we could also just add libarrow as a system dependency (e.g. like GDAL for geospatial packages).  We have spent a lot of time and effort to make it easy to install the package, even for users without experience with compiling complex C++ projects.  

If you want to compile libarrow in a special way to suit your needs you can either use the env. vars or you can build it locally and build the R package against that version with no problem, the easiest way to do this is to have libarrow in your pkg-config path. See also https://arrow.apache.org/docs/r/articles/developers/install_details.html#finding-libarrow-on-the-system
