### ISSUE TITLE
[Go] Protobuf to parquet doesn't support excluded fields

### ISSUE THREAD

**Issue by kp-tom-sc** [apache/arrow#43554]
### Describe the bug, including details regarding any error messages, version, and platform.

The go code for converting protobuf to parquet doesn't currently handle excluded fields.

Error like:
```
panic: type mismatch: cannot convert list to message
```

### Component(s)

Go

**Comment by joellubi** [comment]
Thanks for opening this @kp-tom-sc and for submitting a fix. I'll have some time tomorrow to review the PR.

**Comment by joellubi** [comment]
Issue resolved by pull request 43555
https://github.com/apache/arrow/pull/43555
