### ISSUE TITLE
[CI][Dev][Docs] Consider updating all references to "docker-compose" with "docker compose"

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#43570]
### Describe the enhancement requested

Arrow's CI and documentation reference `docker-compose` in many places which is the old V1 way of calling into Docker Compose, see https://docs.docker.com/compose/migrate/ for more background on `docker-compose` vs `docker compose`. It should be safe to update all references to `docker-compose` to use the current `docker compose`.

Note: What prompted this issue is that CI just started failing due to the GitHub Actions runners not being able to find `docker-compose`. See [1](https://github.com/ursacomputing/crossbow/actions/runs/10249219792/job/28352140688), [2](https://github.com/ursacomputing/crossbow/actions/runs/10249219397/job/28352137772). This was caused by GHA runner image release [20240804](https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240804.1) finally removing `docker-compose`. 

There's already a [minor PR updating CI](https://github.com/apache/arrow/pull/43566) and it would be good to follow up with a PR updating references everywhere else as I think (1) most developer systems should have V2 now and (2) V1 may slowly get phased out of package managers.

### Component(s)

Continuous Integration, Developer Tools

**Comment by amoeba** [comment]
I'm looking at this today. We might be able to deprecate `ARCHERY_USE_DOCKER_CLI` and the related stuff in archery like `using_docker_cli`.

**Comment by kou** [comment]
Issue resolved by pull request 43575
https://github.com/apache/arrow/pull/43575
