### ISSUE TITLE
[Java] `getBuffers` method needs correction on `clear` flag usage

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#43577]
### Describe the bug, including details regarding any error messages, version, and platform.

The `getBuffers` method uses a boolean flag to determine the buffer clear requirement. This field is not fully utilized in a few interfaces. This must be fixed. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43583
https://github.com/apache/arrow/pull/43583
