### ISSUE TITLE
[Python] AttributeError: module 'pyarrow.compute' has no attribute 'equal'

### ISSUE THREAD

**Issue by zeroRains** [apache/arrow#43580]
### Describe the usage question you have. Please include as many useful details as  possible.

I try to compile the arrow in c++ and python  from source code (v16.1.0).  Follow are my compile command

```shell
cd cpp
cmake -DARROW_CSV=ON -DARROW_JSON=ON -DARROW_FILESYSTEM=ON  ..
make -j32 && make install

cd ../python
PYARROW_WITH_COMPUTE=1 PYARROW_PARALLEL=32 PYARROW_WITH_CSV=1 PYARROW_WITH_JSON=1 PYARROW_WITH_FILESYSTEM=1 python setup.py build_ext --bundle-arrow-cpp bdist_wheel
cd dist
pip install  pyarrow-16.1.0-cp39-cp39-linux_x86_64.whl
```
  
The error is follow: 

>>> import pyarrow as pa
>>> arr = pa.array([1,2,3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/array.pxi", line 260, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 55, in pyarrow.lib._is_array_like
  File "pyarrow/pandas-shim.pxi", line 124, in pyarrow.lib._PandasAPIShim._have_pandas_internal
  File "pyarrow/pandas-shim.pxi", line 103, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 106, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 50, in pyarrow.lib._PandasAPIShim._import_pandas
  File "/root/miniconda3/envs/duckdb/lib/python3.9/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/root/miniconda3/envs/duckdb/lib/python3.9/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/root/miniconda3/envs/duckdb/lib/python3.9/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/root/miniconda3/envs/duckdb/lib/python3.9/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/root/miniconda3/envs/duckdb/lib/python3.9/site-packages/pandas/core/arrays/arrow/array.py", line 84, in <module>
    "eq": pc.equal,
AttributeError: module 'pyarrow.compute' has no attribute 'equal'

How to solve it?

### Component(s)

C++, Python

**Comment by raulcd** [comment]
If you want to use compute you have to build Arrow C++ with Compute too:
`-DARROW_COMPUTE=ON`

**Comment by jorisvandenbossche** [comment]
This looks like a confusing error message, though. The `pyarrow.compute` module is one of the cython submodules that are always built regardless of options (so `PYARROW_WITH_COMPUTE=1` is not doing anything, at the moment).

But then I suppose which functions are available in the submodule, that then depends on the C++ build options?

**Comment by zeroRains** [comment]
> If you want to use compute you have to build Arrow C++ with Compute too: `-DARROW_COMPUTE=ON`

Should I run a script to prepare the environment? I get a error in utf8proc lib although I have used `apt install libutf8proc-dev`.

```shell
(base) root@1f99389a8751:~/workspace/origin/utf8proc# apt install libutf8proc-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libutf8proc2
The following NEW packages will be installed:
  libutf8proc-dev libutf8proc2
0 upgraded, 2 newly installed, 0 to remove and 29 not upgraded.
Need to get 103 kB of archives.
After this operation, 693 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 libutf8proc2 amd64 2.5.0-1 [50.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 libutf8proc-dev amd64 2.5.0-1 [52.6 kB]
Fetched 103 kB in 2s (52.5 kB/s)         
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libutf8proc2:amd64.
(Reading database ... 23982 files and directories currently installed.)
Preparing to unpack .../libutf8proc2_2.5.0-1_amd64.deb ...
Unpacking libutf8proc2:amd64 (2.5.0-1) ...
Selecting previously unselected package libutf8proc-dev:amd64.
Preparing to unpack .../libutf8proc-dev_2.5.0-1_amd64.deb ...
Unpacking libutf8proc-dev:amd64 (2.5.0-1) ...
Setting up libutf8proc2:amd64 (2.5.0-1) ...
Setting up libutf8proc-dev:amd64 (2.5.0-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-opencl.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-nvvm.so.4 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libcuda.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-cfg.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-pkcs11.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-gpucomp.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libcudadebugger.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libcudadebugger.so.1 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-ml.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-nvvm.so.550.54.14 is empty, not checked.
/sbin/ldconfig.real: File /lib/x86_64-linux-gnu/libnvidia-allocator.so.550.54.14 is empty, not checked.
```

compile command: `cmake -DARROW_CSV=ON -DARROW_JSON=ON -DARROW_FILESYSTEM=ON -DARROW_COMPUTE=ON ..`

error:

```shell
CMake Error at /root/workspace/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find utf8proc: Found unsuitable version "", but required is at
  least "2.2.0" (found utf8proc_LIB-NOTFOUND)
Call Stack (most recent call first):
  /root/workspace/cmake-3.18.0-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:456 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/Findutf8proc.cmake:107 (find_package_handle_standard_args)
  cmake_modules/ThirdpartyToolchain.cmake:310 (find_package)
  cmake_modules/ThirdpartyToolchain.cmake:2816 (resolve_dependency)
  CMakeLists.txt:543 (include)
```

**Comment by zeroRains** [comment]
> This looks like a confusing error message, though. The `pyarrow.compute` module is one of the cython submodules that are always built regardless of options (so `PYARROW_WITH_COMPUTE=1` is not doing anything, at the moment).
> 
> But then I suppose which functions are available in the submodule, that then depends on the C++ build options? We should look if we can improve the error messaging here.

Do you mean I should add `-DARROW_COMPUTE=ON` flag when I compile the arrow in c++.

**Comment by raulcd** [comment]
Do you have something like a Dockerfile where we could reproduce? I am not entirely sure why your cmake is unable to find `utf8proc`, from what I can see on the logs you are using Ubuntu focal (20.04), and from what I can see on our CI jobs installing `libutf8proc-dev` should be enough for that, see: https://github.com/apache/arrow/blob/main/ci/docker/ubuntu-20.04-cpp.dockerfile#L101

**Comment by zeroRains** [comment]
> Do you have something like a Dockerfile where we could reproduce? I am not entirely sure why your cmake is unable to find `utf8proc`, from what I can see on the logs you are using Ubuntu focal (20.04), and from what I can see on our CI jobs installing `libutf8proc-dev` should be enough for that, see: https://github.com/apache/arrow/blob/main/ci/docker/ubuntu-20.04-cpp.dockerfile#L101

Thanks for your help, I haved solved it.
