### ISSUE TITLE
[Archery] "archery docker" should preferable call `docker compose`, not `docker-compose`

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43608]
### Describe the enhancement requested

The separate `docker-compose` utility has become legacy and it is usually preferrable to use the newer `docker compose` subcommand.

We should update Archery to prefer `docker compose`.

### Component(s)

Archery, Continuous Integration

**Comment by kou** [comment]
Issue resolved by pull request 43586
https://github.com/apache/arrow/pull/43586
