### ISSUE TITLE
[C++] Build fail with Clang 19-rc2 "arithmetic on a pointer to an incomplete type"

### ISSUE THREAD

**Issue by vient** [apache/arrow#43603]
### Describe the bug, including details regarding any error messages, version, and platform.

Compiling Arrow 15.0.0 with Clang 19 results in `error: arithmetic on a pointer to an incomplete type 'FileInfo'` in `FileSystemDatasetFactory` class.
Can't test latest Arrow right now.

A complementary issue to https://github.com/llvm/llvm-project/issues/102293, more info there.

### Component(s)

C++

**Comment by vient** [comment]
Tested with 17.0.0, same issue

**Comment by pitrou** [comment]
Can you please post the full error trace? Otherwise it's not possible to understand what happens here.

**Comment by vient** [comment]
Issue fixed on Clang side, forgot about this one.
