### ISSUE TITLE
[Java] LargeListViewVector RangeEqualVisitor and TypeEqualVisitor integration

### ISSUE THREAD

**Issue by vibhatha** [apache/arrow#43638]
### Describe the enhancement requested

`LargeListViewVector` requires the `RangeEqualVisitor` and `TypeEqualVisitor` to be integrated into the C Data interface. 

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43642
https://github.com/apache/arrow/pull/43642
