### ISSUE TITLE
parquet to pandas date type convention question

### ISSUE THREAD

**Issue by mfcabrera** [apache/arrow#4363]
I am not sure if this is a bug or an specification change. My technical knowledge of Parquet and Arrow is not the best but I am happy to provide more info if any. 

I have a parque file with dates in one column. Using Pyarrow version 0.11.1 when I deserialized that into Pandas DataFrame (via pd.read_parquet) I get a type but when I use version 0.13.x I get a different type. I am aware this might be an specification change but I want to double check. 

With the v 0.11.1 I get

```
In [5]: df.Week.dtype
Out[5]: dtype('<M8[ns]')
```
Numpy type datetime64. This allows me to do string based slicing right away without further convertion. 

i.e. :  `df["Week"] > "2018"`

with 0.13 I get an object (`dtype('O')`) with `datetime.date` objects inside (as per the specification) , which will fail if I want to any time of slicing above.  I have to transform it beforehand (` df["Week"] =  pd.to_datetime(df["Week"])`) 

So the question is why not straight away convert to numpy types and avoid the conversion afterwards? 

pyarrow==0.13.0
Python 3.6.8 (Anaconda)

**Comment by mfcabrera** [comment]
I noticed that this has to do with ARROW-3910 #3272 and I think I now understand why it was done. Still for one-way users (not interested in the roundtrip) this might be annoying but adding an extra line might not be the worst thing to do.

**Comment by wesm** [comment]
Would you like to contribute something to the documentation, or open a JIRA about improving the documentation?

cc @jorisvandenbossche @nealrichardson

**Comment by mfcabrera** [comment]
@wesm I added a bit of documentation on the pandas integration doc. I hope that's enough/relevant.
