### ISSUE TITLE
[Java] Reconcile header size limit in flight server with flight client 

### ISSUE THREAD

**Issue by PANKAJ9768** [apache/arrow#43667]
### Describe the bug, including details regarding any error messages, version, and platform.

Flight server side header acceptance limit is 2kb whereas client can send header size upto Integer.MAX_VALUE resulting in request failure .
In flight client builder we can set header size limit but this is missing in flight server builder.
Also default size at client side is set to Integer.MAX_VALUE  which allows client to send bigger payload in header but server side request is getting failed and no option to modify default size 
Client side config :
https://github.com/apache/arrow/blob/main/java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java#L777C1-L778C1
https://github.com/apache/arrow/blob/main/java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightClient.java#L805

Server side :
https://github.com/apache/arrow/blob/main/java/flight/flight-core/src/main/java/org/apache/arrow/flight/FlightServer.java#L224

### Component(s)

FlightRPC, Java

**Comment by lidavidm** [comment]
I would recommend just configuring the underlying gRPC server directly instead of relying on Flight defaults (which are mostly fairly arbitrary).

**Comment by PANKAJ9768** [comment]
Yeah, We can do that , But still if we can keep Flight default values in sync in both client and server side then it would be convenient

**Comment by lidavidm** [comment]
Agreed. A PR would be welcome.

**Comment by PANKAJ9768** [comment]
> Agreed. A PR would be welcome.

Yup, Will raise it soon

**Comment by lidavidm** [comment]
Issue resolved by pull request 43697
https://github.com/apache/arrow/pull/43697
