### ISSUE TITLE
R/C++ bindings documentation missing (Error 404)

### ISSUE THREAD

**Issue by ajinkya-k** [apache/arrow#43665]
### Describe the bug, including details regarding any error messages, version, and platform.

The `R` documentation references an article about writing bindings with the URL: [https://arrow.apache.org/docs/r/articles/developers/bindings.html](https://arrow.apache.org/docs/r/articles/developers/bindings.html). 
However, this URL gives a 404 error when I try to visit it. Has this moved somewhere else? 

For instance the above URL is referenced here: [https://arrow.apache.org/docs/developers/guide/resources.html#id1](https://arrow.apache.org/docs/developers/guide/resources.html#id1).

### Component(s)

R

**Comment by ajinkya-k** [comment]
Hello! I would still be interested in reading how R/C++ bindings work. Has this been documented elsewhere?

**Comment by amoeba** [comment]
Hi @ajinkya-k, the arrow R package uses [cpp11](https://cpp11.r-lib.org/) for its C++ bindings so you might have a look at their documentation.
