### ISSUE TITLE
[Dev] Allow passing `--progress=plain` to archery docker build

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#43669]
I was debugging one of our docker-compose based CI build, and building and running the docker image locally with `archery docker build xxx`. 

As the documentation (https://arrow.apache.org/docs/dev/developers/continuous_integration/docker.html) mentions, you can specify `--no-cache` to `archery docker run/build` (which passes that to `docker compose build`, but while debugging, I found that additionally it would have been helpful to be able to pass `--progress=plain` through.

**Comment by jorisvandenbossche** [comment]
(cc @assignUser @raulcd to check whether this makes sense, or if there are better ways to see verbose output and printing from the build stage)

**Comment by assignUser** [comment]
Sounds sensible :+1:

**Comment by raulcd** [comment]
Probably not well documented but from my understanding `archery --debug docker build xxx` should pass `--progress=plain` to the command:
```
DEBUG:archery:Executing `['docker', 'compose', '--file=/home/raulcd/code/arrow/docker-compose.yml', 'build', '--build-arg', 'BUILDKIT_INLINE_CACHE=1', '--progress=plain', 'conda']`

```

**Comment by raulcd** [comment]
ok, this was added not long ago (https://github.com/apache/arrow/pull/40129), we should probably document it.

**Comment by jorisvandenbossche** [comment]
That indeed seems to be what I wanted!

**Comment by jorisvandenbossche** [comment]
I will look into adding that to the dev docs. 

But the CLI help, it is actually kind of documented in the top-level one:

```
$ archery -h
Usage: archery [OPTIONS] COMMAND [ARGS]...

  Apache Arrow developer utilities.

  See sub-commands help with `archery <cmd> --help`.

Options:
  --debug      Increase logging with debugging output.
  ...
```

assuming those options listed are available for all subcommands.

But when you are looking at the specific options for docker build, that doesn't show up, so it is easy to miss:

```
$ archery docker build --help
Usage: archery docker build [OPTIONS] IMAGE

  Execute docker-compose builds.

Options:
  --force-pull / --no-pull        Whether to force pull the image and its
                                  ancestor images
  --use-cache / --no-cache        Whether to use cache when building the image
                                  and its ancestor images
  --use-leaf-cache / --no-leaf-cache
                                  Whether to use cache when building only the
                                  (leaf) image passed as the argument. To
                                  disable caching for both the image and its
                                  ancestors use --no-cache option.
  -h, --help                      Show this message and exit.
```

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 43935
https://github.com/apache/arrow/pull/43935
