### ISSUE TITLE
Changes suggested not working Error: NotImplemented: Support for codec 'zstd' not built

### ISSUE THREAD

**Issue by kyralindley** [apache/arrow#43676]
### Describe the usage question you have. Please include as many useful details as  possible.

I'm trying to follow the  visiumhd_analysis_vignette.Rmd.
While trying to run '''object <- Load10X_Spatial(data.dir = data_dir, bin.size = c(8,16))'''
I'm getting the following error 

Error: NotImplemented: Support for codec 'zstd' not built
In order to read this file, you will need to reinstall arrow with additional features enabled.
Set one of these environment variables before installing:

 * Sys.setenv(LIBARROW_MINIMAL = "false") (for all optional features, including 'zstd')
 * Sys.setenv(ARROW_WITH_ZSTD = "ON") (for just 'zstd')

See https://arrow.apache.org/docs/r/articles/install.html for details

Even when i follow the instrucutions and try and use the Sys.setenv and install the package, its still giving me the same error. How do i overcome this?

### Component(s)

R

**Comment by assignUser** [comment]
Which OS are you on? I assume MacOS which means you get binaries by default and will need to add `type="source"` when installing arrow.

**Comment by kyralindley** [comment]
> Which OS are you on? I assume MacOS which means you get binaries by default and will need to add `type="source"` when installing arrow.

I am on a macos,  Should it take a long time to download from source? I have tried that and the package wont install from, it just freezes at this point

> install.packages("arrow", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/arrow_16.1.0.tar.gz'
Content type 'application/x-gzip' length 4439675 bytes (4.2 MB)
==================================================
downloaded 4.2 MB

* installing *source* package ‘arrow’ ...
** package ‘arrow’ successfully unpacked and MD5 sums checked
** using staged installation
*** pkg-config not found.
*** Found local C++ source: 'tools/cpp'
*** Building libarrow from source
    For build options and troubleshooting, see the install guide:
    https://arrow.apache.org/docs/r/articles/install.html
**** cmake 3.26.4
**** pkg-config not installed, setting ARROW_DEPENDENCY_SOURCE=BUNDLED
****  S3/GCS  support  requires version >= 1.0.2 of openssl-devel (rpm), libssl-dev (deb), or openssl (brew) ; building with  ARROW_S3=OFF and ARROW_GCS=OFF 
**** arrow

**Comment by kyralindley** [comment]
> Which OS are you on? I assume MacOS which means you get binaries by default and will need to add `type="source"` when installing arrow.

I've tried that and im still getting the same errors 
> installing from source 
installing to /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/00LOCK-arrow/00new/arrow/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (arrow)

The downloaded source packages are in
	‘/private/var/folders/zh/2vp0syx15h1bpjmnr_jfn1j5y0bfr3/T/RtmpNVwsps/downloaded_packages’
> data_dir <- file.path("filepath")
> object <- Load10X_Spatial(data.dir = data_dir, bin.size = c(8,16))
Error: NotImplemented: Support for codec 'zstd' not built
In order to read this file, you will need to reinstall arrow with additional features enabled.
Set one of these environment variables before installing:

 * Sys.setenv(LIBARROW_MINIMAL = "false") (for all optional features, including 'zstd')
 * Sys.setenv(ARROW_WITH_ZSTD = "ON") (for just 'zstd')

See https://arrow.apache.org/docs/r/articles/install.html for details

**Comment by kyralindley** [comment]
AHH!! I think its working, thank you very much
