### ISSUE TITLE
[C#] Schema should be optional on FlightInfo

### ISSUE THREAD

**Issue by ndglover** [apache/arrow#43672]
### Describe the enhancement requested

Similar to [37553](https://github.com/apache/arrow/issues/37553)

The idea being that the Schema is not a required field for FlightInfo.  The Schema can be sent as part of the messages in the subsequent request.

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 43673
https://github.com/apache/arrow/pull/43673

**Comment by CurtHagenlocher** [comment]
> Is it possible to have a release candidate for this fix?

There's no existing process by which prereleases get published to nuget.org, so if you need something before the final 18.0.0 release you'd need to build it yourself from source.

**Comment by ndglover** [comment]
@CurtHagenlocher do you have a date for the 18.0.0 release?

**Comment by CurtHagenlocher** [comment]
Code freeze is at the end of September and the release will be sometime during October. We can't really predict a date because it depends in part on how the testing goes.

**Comment by ndglover** [comment]
Is there a reason not to have release candidates before that final release? It would seem to make sense from a stability perspective and also from an end user perspective. Waiting at worse case and entire quarter seems sub-optimal and each person then needs to fork the repo and manage builds etc

Happy to make a contribution if that's a good idea but not sure what would be involved.
