### ISSUE TITLE
[plasma] pin objects in plasma store

### ISSUE THREAD

**Issue by zhijunfu** [apache/arrow#4368]
Sometimes we want to "pin" an object in plasma store - we don't want this object to be deleted  even though there's nobody that's currently referencing it. In this case, we can specify a flag when creating the object so that it won't be deleted by LRU cache when its refcnt drops to 0, and can only be deleted by an explicit `Delete()` call. 

Would this make sense to you? @pcmoritz @robertnishihara

**Comment by guoyuhong** [comment]
This is good feature, especially when there is a long-chain dependency. Currently, we found that an actor FO problem. The actor creation task depends on a plasma object put by user. After the the actor running for a long time, the object will be deleted by plasma LRU. Then, an Actor FO happens, the creation task cannot find the object put by user, so the FO is hanging forever.

**Comment by wesm** [comment]
Can you please open a JIRA issue for this feature?

**Comment by zhijunfu** [comment]
@wesm  done, thanks. [ARROW-5402](https://issues.apache.org/jira/browse/ARROW-5402)

**Comment by wesm** [comment]
Thanks
