### ISSUE TITLE
[C++][Parquet][CI] Seed corpus should also use bad data files

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43703]
### Describe the enhancement requested

Currently our Parquet fuzzing seed corpus consists entirely of testing data files, see here:
https://github.com/apache/arrow/blob/ab432b1362208696e60824b45a5599a4e91e6301/cpp/build-support/fuzzing/generate_corpuses.sh#L57-L58

We should also add files from the `bad_data` directory in the testing repository.

### Component(s)

C++, Continuous Integration, Parquet

**Comment by pitrou** [comment]
@mapleFU Would you like to take a look?

**Comment by mapleFU** [comment]
I'd like adding this tonight when I back home

**Comment by pitrou** [comment]
Issue resolved by pull request 43708
https://github.com/apache/arrow/pull/43708
