### ISSUE TITLE
[Python][CI] Build failure with Cython 2

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43707]
### Describe the bug, including details regarding any error messages, version, and platform.

These failures have appeared recently on the `test-conda-python-3.10-cython2` Crossbow job:
https://github.com/ursacomputing/crossbow/actions/runs/10396692805/job/28791169422#step:7:3604
```
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      """

      cdef:
          c_string c_type_name = tobytes(type_name)
          c_string c_vendor_name = tobytes(vendor_name)
          shared_ptr[CDataType] c_type = make_shared[COpaqueType](
                                                                ^
  ------------------------------------------------------------

  pyarrow/types.pxi:5331:63: Cannot assign type 'shared_ptr[COpaqueType]' to 'shared_ptr[CDataType]'
```

### Component(s)

Continuous Integration, Python

**Comment by pitrou** [comment]
cc @lidavidm @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
FWIW, I think we should also consider simply raising the minimum cython version to something >= 3

**Comment by jorisvandenbossche** [comment]
Issue resolved by pull request 43765
https://github.com/apache/arrow/pull/43765
