### ISSUE TITLE
[Java][FlightSQL] FlightSqlUtils.FLIGHT_SQL_ACTIONS is missing ActionTypes

### ISSUE THREAD

**Issue by devinrsmith** [apache/arrow#43717]
### Describe the bug, including details regarding any error messages, version, and platform.

FlightSqlUtils.FLIGHT_SQL_ACTIONS is missing ActionTypes

### Component(s)

Java

**Comment by devinrsmith** [comment]
take

**Comment by lidavidm** [comment]
Issue resolved by pull request 43718
https://github.com/apache/arrow/pull/43718
