### ISSUE TITLE
[Go] Make Flight SQL clients/servers symmetric

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#43764]
### Describe the enhancement requested

We are trying to make a Flight SQL proxy but it is rather frustrating because methods aren't 1:1 between client/server. In particular for prepared statements we have to somehow fake a prepared statement object, and it isn't immediately clear what state is actually necessary; it would be nice if we could directly expose the actual RPC methods for this use case.

### Component(s)

Go

**Comment by zeroshade** [comment]
Can you give me an example specifically about what you mean? Because to my memory the RPC methods *are* exposed directly for the client and server in Go?

**Comment by lidavidm** [comment]
They appear to not be exposed for prepared statements; either we need a way to clearly serialize a PreparedStatement to/from just a handle, or the ability to call the underlying prepared statement methods

**Comment by zeroshade** [comment]
Issue resolved by pull request 43781
https://github.com/apache/arrow/pull/43781
