### ISSUE TITLE
span_range returns unexpected result (missing days) when using frame month

### ISSUE THREAD

**Issue by Iwerzhon** [apache/arrow#43778]
### Describe the bug, including details regarding any error messages, version, and platform.

Sometimes (based on the start_date/end_date value), some days are missing when splitting a range of dates using `span_range` with `frame=month`

Doc: https://arrow.readthedocs.io/en/latest/api-guide.html#arrow.arrow.Arrow.span_range

Reproduction
```
import arrow
start_date = arrow.get("2023-01-31T00:00:00+02:00")
end_date = arrow.get("2024-08-20T16:08:09.538605+02:00")
[
    [start.isoformat(), end.isoformat()]
    for start, end in arrow.Arrow.span_range("month", start_date.datetime, end_date.datetime, exact=True)
]
```

We go from `2023-03-27T23:59:59` to `2023-03-31T00:00:00+02:00`, missing 3 days (2nd to 3rd value)
We go from `2024-07-29T23:59:59` to `2024-07-31T00:00:00+02:00`, missing 1 day (last value)

Note : 
- this issue may not occur with different dates
- this issue does not occur when using `frame=months` instead of `frame=month`
- this issue does not occur when not specifying `exact=True`

I am unsure of the difference between `month` and `months`, but I don't think this is the expected behavior?

### Component(s)

Python

**Comment by buaazhwb** [comment]
You report the issue to a wrong repo. 
The repo you use is https://github.com/arrow-py/arrow
