### ISSUE TITLE
[C++] Register the new Opaque extension type by default

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#43787]
The Opaque extension type implementation for C++ (plus python bindings) was added in https://github.com/apache/arrow/pull/43458, but it was not registered by default, which we should do for canonical extension types (see https://github.com/apache/arrow/pull/43458#issuecomment-2302551404)

**Comment by rok** [comment]
Issue resolved by pull request 43788
https://github.com/apache/arrow/pull/43788
