### ISSUE TITLE
[Go][Parquet] Is LZ4 being supported in arrow parquet?

### ISSUE THREAD

**Issue by yangg-splunk** [apache/arrow#43783]
### Describe the usage question you have. Please include as many useful details as  possible.

From here it seems still unsupported in the lib's latest version: https://pkg.go.dev/github.com/apache/arrow/go/v17@v17.0.0/parquet/compress

### Component(s)

Go

**Comment by joellubi** [comment]
Hi @yangg-splunk. I've done some digging and found that a newer [LZ4_RAW](https://github.com/apache/parquet-format/blob/master/Compression.md#lz4_raw) codec has been added to the parquet spec to address the ambiguity around the (now deprecated) LZ4 codec. More details about the ambiguiity of the deprecated codec can be found in the mailing list thread linked in the code comment for LZ4.

I opened #43790 to track the addition of LZ4_RAW for Go.

Would this solve your problem?

**Comment by yangg-splunk** [comment]
Yes, this is what I am looking for.
So it will be the lz4_raw, not lz4 block (or hadoop-lz4)?

**Comment by joellubi** [comment]
Yes it will be LZ4_RAW, which actually is the block format (see link to parquet-format docs above). This should be unambiguous when reading/writing with other implementations supporting LZ4_RAW, but notably will not be compatible with files that may have been written with hadoop-lz4.

**Comment by yangg-splunk** [comment]
Thanks for correcting the terms I have been misusing. Feel free to close this request if it's going to be tracked by https://github.com/apache/arrow/issues/43790.

**Comment by joellubi** [comment]
@yangg-splunk #43835 has been merged which adds the LZ4_RAW codec implementation. Please let me know if this works for you when you have a chance to test it.

**Comment by yangg-splunk** [comment]
Thanks, nothing needed for now. I will monitor when this commit gets published in new version. Looks like v18 for now.
