### ISSUE TITLE
CSV reader doesn't remove BOM

### ISSUE THREAD

**Issue by Ingvar-Y** [apache/arrow#4382]
If a csv file starts with a byte-order mark, csv reader doesn't strip it and instead adds `\ufeff` to the first column name.

I found it out while trying to set `pyarrow.csv.ConvertOptions` when reader silently ignored the settings for the first column. As a couple of follow-up ideas, maybe a warning should be raised when `column_types` dictionary contains keys not matching column names, and maybe `column_types` dictionary should also accept integers matching column numbers as keys (which would be useful even after implemetation of [ARROW-4912](https://issues.apache.org/jira/browse/ARROW-4912)).

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by Ingvar-Y** [comment]
Done.
