### ISSUE TITLE
[Integration][Go] IPC files do not embed a valid IPC stream

### ISSUE THREAD

**Issue by bkietz** [apache/arrow#43837]
### Describe the bug, including details regarding any error messages, version, and platform.

The format guarantees that each IPC file [embeds a valid IPC stream](https://github.com/apache/arrow/blob/bde6ac57ad943f5938506359de1b13fb85b4f8ea/docs/source/format/Columnar.rst) in order to allow readers to ignore the Footer, skip the file's leading magic, and reuse a stream reader.

https://github.com/apache/arrow/pull/43834 adds validation of the embedded IPC stream and files written by Go fail. When writing IPC files Go seems to omit the stream's EOS so that a stream-only reader will [attempt to read the Footer as a Message](https://github.com/apache/arrow/actions/runs/10565413633/job/29269867382?pr=43834#step:9:27158).

### Component(s)

Go, Integration

**Comment by joellubi** [comment]
Issue resolved by pull request 43890
https://github.com/apache/arrow/pull/43890
