### ISSUE TITLE
[CI] Add cuda group on tasks.yml in order to be able to trigger cuda jobs

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43840]
### Describe the enhancement requested

We are currently upgrading the cuda images for our self-hosted runners on crossbow.
It would be good to be able to run the cuda jobs with:
`@github-actions crossbow submit -g cuda`

### Component(s)

Continuous Integration

**Comment by pitrou** [comment]
Issue resolved by pull request 43841
https://github.com/apache/arrow/pull/43841
