### ISSUE TITLE
PyArrow UnionType Reporting as NotImplemented

### ISSUE THREAD

**Issue by nishkakar** [apache/arrow#43857]
### Describe the bug, including details regarding any error messages, version, and platform.

Here's the repro on Version 16  with Python 3.10 (also repros on Version 11 FWIW). It seems according to the docs that this behavior should be supported, but maybe I'm missing something here. Appreciate the help!

```
import pyarrow as pa

lst = [
    {"payload": {"executed": {'finger': 'middle', 'type': 'tap'}}},
    {"payload": {"executed": "left"}}
]

# Also fails with pa.sparse_union
executed_union = pa.dense_union([
    pa.field("struct", pa.struct([("finger", pa.string()), ("type", pa.string())])),
    pa.field("string", pa.string())
])

schema = pa.schema([
    ("payload", executed_union)
])

map_type = pa.map_(pa.string(), executed_union)

# BOTH OF THESE FAIL WITH: "ArrowNotImplementedError:dense_union"
pa.Table.from_pylist(lst, schema=schema)
pa.array(lst, map_type)
```

### Component(s)

Python

**Comment by assignUser** [comment]
Thanks for the report,  as the error shows a number of utilities are not yet implemented for union types in pyarrow.
This is a known issue see #31211 I will close this as duplicate.

**Comment by nishkakar** [comment]
@assignUser Thanks for the quick response. After doing a quick search, I think the core issue seems to be described in #19157. I've left a comment there.

**Comment by nishkakar** [comment]
@assignUser Can we re-open this issue or perhaps get a report back on whether it's going to be worked on as part of https://github.com/apache/arrow/issues/19157? This is proving to be a sizable blocker for us.

**Comment by assignUser** [comment]
@nishkakar I don't know of anyone actively working on this, sorry. If this is a feature that you are interested in, contributing it yourself is likely the quickest way to get it in. We have a contribution guide here: https://arrow.apache.org/docs/developers/index.html#developers
