### ISSUE TITLE
[Go] Error was not handled

### ISSUE THREAD

**Issue by bigsheeper** [apache/arrow#43860]
### Describe the bug, including details regarding any error messages, version, and platform.

The error thrown during the [ReadRecords](https://github.com/apache/arrow/blob/6b268f62a8a172249ef35f093009c740c32e1f36/go/parquet/file/record_reader.go#L569) process was not handled or returned correctly.
1. `HasNext` returns false because of an error, then the `for` loop broke:
<img src="https://github.com/user-attachments/assets/6b00a550-0c5b-4318-b971-a96958257700" width=65% height=65%>

2. But the error isn't being returned:
<img src="https://github.com/user-attachments/assets/b7840958-503f-4f67-bea1-333f487bbce1" width=65% height=65%>

### Component(s)

Go

**Comment by zeroshade** [comment]
Issue resolved by pull request 43861
https://github.com/apache/arrow/pull/43861
