### ISSUE TITLE
[Go] Remove go/

### ISSUE THREAD

**Issue by kou** [apache/arrow#43879]
### Describe the enhancement requested

Blockers:
* #43872
* #43873
* #43874
* #43875
* #43876
* #43878

### Component(s)

Go

**Comment by raulcd** [comment]
@kou now that the `arrow-go` repository is "ready" for development there, I plan to start working on these tasks to prepare the repo for 18.0.0 so we don't release go. Let me know if you think there's something that has to be done before.

**Comment by kou** [comment]
+1

**Comment by raulcd** [comment]
Issue resolved by pull request 44293
https://github.com/apache/arrow/pull/44293
