### ISSUE TITLE
[Go][Release] Remove Go related codes from our release scripts

### ISSUE THREAD

**Issue by kou** [apache/arrow#43878]
### Describe the enhancement requested

Our release scripts: https://github.com/apache/arrow/tree/main/dev/release

We also need to update our release document: https://github.com/apache/arrow/blob/main/docs/source/developers/release.rst

### Component(s)

Go, Release

**Comment by raulcd** [comment]
Issue resolved by pull request 44172
https://github.com/apache/arrow/pull/44172
