### ISSUE TITLE
[Ruby] Cannot work with zero-value Decimals

### ISSUE THREAD

**Issue by datbth** [apache/arrow#43877]
## Description
![image](https://github.com/user-attachments/assets/e8d74e5e-ce88-43c0-b6cb-d61c392536ce)

```ruby
schema = Arrow::Schema.new([Arrow::Field.new('x', {type: :decimal128,precision: 38,scale:9})])
table = Arrow::Table.new(schema, [[BigDecimal(0)]])
puts table[0][0].class
```
![image](https://github.com/user-attachments/assets/62f1d6b3-b6c3-403e-a6fa-3bc26371d4dd)

(In my actual use case, I'm working with data coming from Flight RPC.  
But as far as I see, the Ruby Flight client also [ingests decimal data using the string representation](https://github.com/apache/arrow/blob/main/ruby/red-arrow/ext/arrow/converters.hpp#L289))

Not sure if we can do something here or do we have to wait for a patch from Ruby BigDecimal?  
I have also filed an issue on Ruby BigDecimal: https://github.com/ruby/bigdecimal/issues/301

## Additional details
* Ruby: 2.7.4p191 [x86_64-linux]
* Platform: Ubuntu 24.04
* `red-arrow`: 17.0.0
* `bigdecimal`: 3.1.7

### Component(s)

Ruby

**Comment by kou** [comment]
Issue resolved by pull request 43882
https://github.com/apache/arrow/pull/43882
