### ISSUE TITLE
[R] format_aggregation() should print options too

### ISSUE THREAD

**Issue by nealrichardson** [apache/arrow#43894]
### Describe the enhancement requested

We rely on C++ ToString methods for printing Arrow Expressions, which include functions, arguments, and options. But when we print `arrow_dplyr_query` objects with aggregations, we don't have Expressions at that time. The print method we use is

```
format_aggregation <- function(x) {
  paste0(x$fun, "(", paste(map(x$data, ~ .$ToString()), collapse = ","), ")")
}
```

So it shows the function and the arguments, but not any options. We either need to construct Expressions and print them, or map option names to C++ options and include them in format_aggregation.

### Component(s)

R

**Comment by thisisnic** [comment]
Issue resolved by pull request 43896
https://github.com/apache/arrow/pull/43896
