### ISSUE TITLE
[CI][Python] python_test_emscripten fails with missing PARQUET_TEST_DATA environment variable

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43905]
### Describe the bug, including details regarding any error messages, version, and platform.

The [test-conda-python-emscripten](https://github.com/ursacomputing/crossbow/actions/runs/10658679057/job/29540120827) is failing with the following error:
```

    @pytest.fixture(scope='module')
    def parquet_test_datadir():
        result = os.environ.get('PARQUET_TEST_DATA')
        if not result:
>           raise RuntimeError('Please point the PARQUET_TEST_DATA environment '
                               'variable to the test data directory')
E           RuntimeError: Please point the PARQUET_TEST_DATA environment variable to the test data directory
```
This has been failing since this check was introduced in: https://github.com/apache/arrow/pull/41580

### Component(s)

Continuous Integration, Python

**Comment by kou** [comment]
We already have an issue for this: https://github.com/apache/arrow/issues/43868
