### ISSUE TITLE
[C#] Use "asf" organization in NuGet

### ISSUE THREAD

**Issue by kou** [apache/arrow#43930]
### Describe the enhancement requested

https://www.nuget.org/profiles/asf

We don't use the organization feature in NuGet now. Some PMC members are owner of https://www.nuget.org/packages/Apache.Arrow and so on.

The next step: Read the following information and know how to do:
* The mail on `users@infra.apache.org`: https://lists.apache.org/thread/hpq8kn57nnkbl0jryw5s4gsg65v94nvn
* https://issues.apache.org/jira/browse/INFRA-25617

### Component(s)

C#, Release

**Comment by kou** [comment]
@raulcd We may do this in the next.

@lidavidm https://www.nuget.org/packages/Apache.Arrow.Adbc/ may do this.

**Comment by lidavidm** [comment]
Hmm, it seems I cannot log in and see that mail. 

It seems we should (1) transfer the packages to the new ASF organization and (2) request to be added as collaborators on that organization?

**Comment by kou** [comment]
Oh, can you access to https://issues.apache.org/jira/browse/INFRA-25617 with your ASF account?

(I haven't read all texts in the issue yet... Sorry...)

**Comment by lidavidm** [comment]
Yes, I can read the JIRA! (Just that the login for lists.apache.org does not work for me...after login it still says I am logged out.) That's where I saw the news about the new 'asf' org.

**Comment by raulcd** [comment]
I can't read the email either. Do you require to be an ASF member to do so?
As per moving the nuget packages to the asf org, sounds good to me. I will ask on slack if I can get added to the asf org, from my understanding we can transfer the packages to the org.

**Comment by lidavidm** [comment]
CC @CurtHagenlocher for visibility

**Comment by raulcd** [comment]
As discussed with Infra, I've created https://issues.apache.org/jira/browse/INFRA-26091 to track it.

**Comment by kou** [comment]
Thanks!

**Comment by raulcd** [comment]
`asf` is now an owner of the `Apache.Arrow` packages, I am going to also give them ownership of the `Apache.Arrow.Adbc` ones, is that ok @lidavidm ?
https://www.nuget.org/profiles/asf

**Comment by lidavidm** [comment]
@raulcd sounds good to me, thanks!

**Comment by raulcd** [comment]
I've requested `asf` to get ownership of the remaining adbc packages. I'll close the issue once it's accepted. I don't think we have to do anything else as the published packages already appear as part of the `asf` ones.

**Comment by kou** [comment]
Can we close this?

**Comment by raulcd** [comment]
I'm fine with closing it but infra hasn't yet approved the transfer for the adbc packages. I will ping them again

**Comment by raulcd** [comment]
The remaining packages have been transfered

**Comment by kou** [comment]
Thanks!
