### ISSUE TITLE
Docker warnings about docker-compose version and PYTHON_IMAGE_TAG default value

### ISSUE THREAD

**Issue by lysnikolaou** [apache/arrow#43933]
### Describe the bug, including details regarding any error messages, version, and platform.

Running `docker-compose` locally with any of the services in the `docker-compose.yml` file results in the following warnings.

```bash
WARN[0000] The "PYTHON_IMAGE_TAG" variable is not set. Defaulting to a blank string.
WARN[0000] The "PYTHON_IMAGE_TAG" variable is not set. Defaulting to a blank string.
WARN[0000] The "PYTHON_IMAGE_TAG" variable is not set. Defaulting to a blank string.
WARN[0000] The "PYTHON_IMAGE_TAG" variable is not set. Defaulting to a blank string.
WARN[0000] /Users/lysnikolaou/repos/python/arrow/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```

They're easy to get rid of, so a PR is probably worth it.

### Component(s)

Continuous Integration

**Comment by raulcd** [comment]
Issue resolved by pull request 43934
https://github.com/apache/arrow/pull/43934
