### ISSUE TITLE
[CI] Bump artifact action on GitHub Actions

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43952]
### Describe the bug, including details regarding any error messages, version, and platform.

It seems v3 of the artifact actions is deprecated and will soon be removed:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

### Component(s)

Continuous Integration

**Comment by pitrou** [comment]
cc @kou @assignUser

**Comment by assignUser** [comment]
#43940

**Comment by kou** [comment]
Related: #39350

**Comment by kou** [comment]
Issue resolved by pull request 43940
https://github.com/apache/arrow/pull/43940
