### ISSUE TITLE
[Java] Check for nullabilities when comparing StructVector

### ISSUE THREAD

**Issue by hellishfire** [apache/arrow#43966]
### Describe the bug, including details regarding any error messages, version, and platform.

Currently RangeEqualsVisitor doesn't consider the nullabilities of StructVector, thus it may incorrectly reports true when two StructVector have same underlying field vectors but differ in struct nullabilities.

### Component(s)

Java

**Comment by vibhatha** [comment]
@hellishfire thanks for reporting this, would it be possible to provide a reproducible test case or an example?

**Comment by hellishfire** [comment]
> @hellishfire thanks for reporting this, would it be possible to provide a reproducible test case or an example?

I'll submit a fix along with simple tests shortly.

**Comment by vibhatha** [comment]
Wonderful, thanks.

**Comment by lidavidm** [comment]
Issue resolved by pull request 43968
https://github.com/apache/arrow/pull/43968
