### ISSUE TITLE
[CI][C++][Dev] Add cpplint to pre-commit

### ISSUE THREAD

**Issue by kou** [apache/arrow#43979]
### Describe the enhancement requested

We have a copy of cpplint at https://github.com/apache/arrow/blob/main/cpp/build-support/cpplint.py and use it from Archery now. pre-commit doesn't use cpplint yet.

### Component(s)

C++, Continuous Integration, Developer Tools

**Comment by raulcd** [comment]
Issue resolved by pull request 43982
https://github.com/apache/arrow/pull/43982
