### ISSUE TITLE
[Format] Is Buffer lengths buffer REQUIRED in C data format of BinaryView

### ISSUE THREAD

**Issue by robert3005** [apache/arrow#43989]
### Describe the bug, including details regarding any error messages, version, and platform.

C Data interface section on [BinaryView](https://arrow.apache.org/docs/format/CDataInterface.html#binary-view-arrays) mentions that this array type requires an additional buffer to be produced when sending the array. However, it doesn't mention whether that addtional array always has to be present even if there's no data buffers. This could happen for example if your array only contains short strings.

For reference the implementation assumes there are at least 3 buffers which I assume is view, nulls and buffer lengths https://github.com/apache/arrow/blob/089ad788976041444887a9a9c3b8f6973467e22a/cpp/src/arrow/c/bridge.cc#L1741
 
### Component(s)

Format

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/commit/94fc124288a0b925c26ea3800ec380020abe9e42

I think it's mentioned in the `docs/source/format/CDataInterface.rst`?

**Comment by robert3005** [comment]
Ok, so the correct interpretation of the docs I had linked https://arrow.apache.org/docs/format/CDataInterface.html#binary-view-arrays is that there MUST be a length buffer even if there are no data buffers?

**Comment by mapleFU** [comment]
cc @pitrou @bkietz @felipecrv

**Comment by bkietz** [comment]
When I wrote it, it was my intent that the lengths buffer always be present even if there were no data buffers. In that case, there would be exactly three buffers: validity, views, and lengths. However if there are no data buffers the lengths buffer would be empty, present only to give the array correct layout.

**Comment by robert3005** [comment]
When I started looking it made sense that it must be present. Thanks, I might make a small docs pr but this answers my question
