### ISSUE TITLE
[C++] Can't find_package

### ISSUE THREAD

**Issue by kv-gits** [apache/arrow#43998]
### Describe the usage question you have. Please include as many useful details as  possible.

Built static bundle and try link to project.
```
list(PREPEND CMAKE_PREFIX_PATH "${PROJPATH}/libs/arrow/cpp/build/src")
find_package(Arrow REQUIRED)
```

Got error

```
CMake Error at libs/arrow/cpp/build/src/arrow/ArrowConfig.cmake:125 (include):
  include could not find requested file:

.../arrow/cpp/build/src/arrow/ArrowTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:68 (find_package)

CMake Error at libs/arrow/cpp/build/src/arrow/ArrowConfig.cmake:192 (get_target_property):
  get_target_property() called with non-existent target
  "Arrow::arrow_static".
Call Stack (most recent call first):
  libs/arrow/cpp/build/src/arrow/ArrowConfig.cmake:226 (arrow_keep_backward_compatibility)
  CMakeLists.txt:68 (find_package)
```

File ArrowTargets.cmake is created in separate "export" directory and not available to include in ArrowConfig

### Component(s)

C++

**Comment by kou** [comment]
Could you use "installed" directory not "build" directory?

**Comment by kv-gits** [comment]
Installed directory was not created. Only "build". My build instructs are. Arrrow version 17.0.0

```
cmake .. --preset ninja-release-minimal  -DARROW_PARQUET=ON -DARROW_BUILD_STATIC="ON" -DARROW_BUILD_SHARED="OFF"  -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_DEPENDENCY_USE_SHARED=OFF
cmake --build .
```

**Comment by kou** [comment]
You need to install (`cmake --install .`) to use `find_package()`.

BTW, could you share the document URI you referred?

**Comment by kv-gits** [comment]
Yes, I found it. Thanks!
In docs https://arrow.apache.org/docs/developers/cpp/building.html
there is some info, but little unclear

**Comment by kou** [comment]
Ah, you're right. The document misses install command line.

**Comment by kou** [comment]
Issue resolved by pull request 44000
https://github.com/apache/arrow/pull/44000
