### ISSUE TITLE
[C++][Parquet] Fix schema conversion from two-level encoding nested list

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#43994]
### Describe the bug, including details regarding any error messages, version, and platform.

I have seen an issue when reading a Parquet file created by Hudi. There is a nesting list as below:
```
  optional group a (LIST) {
    repeated group array (LIST) {
      repeated int32 array;
    }
  }
```

The C++ parquet reader infers its schema as `array<struct<array:array<int>>>`. The root cause is here: https://github.com/apache/arrow/blob/12dddfc737ea23c43646f79769e0f9e12204a429/cpp/src/parquet/arrow/schema.cc#L657-L663

I think we need to regard them as a nesting two-level list, meaning that the correct interpretation is `array<array<int>>`.

### Component(s)

C++, Parquet

**Comment by mapleFU** [comment]
`array<array<int>>`?
