### ISSUE TITLE
[Java] Mark new allocated ArrowSchema as released

### ISSUE THREAD

**Issue by viirya** [apache/arrow#43996]
### Describe the enhancement requested

Currently a newly allocated `ArrowArray` will be marked as released, but `ArrowSchema` is not. 

We have been bitten by this in https://github.com/apache/datafusion-comet/pull/905 when a `ArrowSchema` passed from JVM to native is dropped that invokes uninitiated value in the release slot which causes SIGSEGV.

It is safer to mark newly allocated `ArrowSchema` as released following `ArrowArray`.

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 43997
https://github.com/apache/arrow/pull/43997
