### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by jason-gao** [apache/arrow#44015]
### Describe the bug, including details regarding any error messages, version, and platform.

python3.12
mac:intel 11.7.10 (20G1427)
streamlit run xx.py
error:Segmentation fault: 11

pyarrow==17.0.0

### Component(s)

Python

**Comment by raulcd** [comment]
Sorry, I edited my comment on your original post, there is a known issue for macOS 11 with pyarrow >16.1.0 (also 17.0.0). We bumped the macOS deployment target to macOS 12 for pyarrow 18.0.0, see the original issue for more context: https://github.com/apache/arrow/issues/41696

**Comment by raulcd** [comment]
Closing as duplicate
