### ISSUE TITLE
[Python] Fix threading bugs under the free-threaded version related to borrowed references and Pandas initialization

### ISSUE THREAD

**Issue by lysnikolaou** [apache/arrow#44046]
### Describe the bug, including details regarding any error messages, version, and platform.

Sub-issue of https://github.com/apache/arrow/issues/43536.

There's two threading related bugs under the free-threaded build:
- One is related to borrowed references using `PySequence_Fast_GET_ITEM`, which I'd missed in #43540.
- The other is related to `pandas` initialization using multiple threads.

### Component(s)

Python

**Comment by pitrou** [comment]
Issue resolved by pull request 44047
https://github.com/apache/arrow/pull/44047
