### ISSUE TITLE
[C++][Compute] Row segmenter inefficiency

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#44052]
### Describe the enhancement requested

The third item in #34475 :
> Improve performance of grouping inside the segmenter (see [this discussion](https://github.com/apache/arrow/pull/34311/files#r1129570181))

Currently the algorithm has O(n^2) complexity, which is inefficient.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 44053
https://github.com/apache/arrow/pull/44053
