### ISSUE TITLE
[Java] Request to support Run-End Encoded Layout in Java C Data interface

### ISSUE THREAD

**Issue by whutjs** [apache/arrow#44065]
### Describe the enhancement requested

In version 17.0, Java C Data interface still doesn't not support Run-End Encoded Layout. Giving a Run-End Encoded Layout, the [Fortmat class](https://github.com/apache/arrow/blob/main/java/c/src/main/java/org/apache/arrow/c/Format.java) will throw an exception with message "**Format +r is not supported**".

### Component(s)

Java

**Comment by danepitkin** [comment]
RunEndEncoded Vectors are not yet implemented in Arrow Java. There's a PR in progress to add it: https://github.com/apache/arrow/pull/43888

**Comment by lidavidm** [comment]
Issue resolved by pull request 44241
https://github.com/apache/arrow/pull/44241
