### ISSUE TITLE
[Dev][Archery][Integration] Reduce needless test matrix

### ISSUE THREAD

**Issue by kou** [apache/arrow#44062]
### Describe the enhancement requested

Archery generates product of all testers: https://github.com/apache/arrow/blob/8556001e6a8b4c7f35d4e18c28704d7811005904/dev/archery/archery/integration/runner.py#L88-L90

If we enable C++, Java and Rust, we use the following patterns:

| Producer | Consumer |
|--------|--------|
| C++ | C++ |
| C++ | Java |
| C++ | Rust | 
| Java | C++ |
| Java | Java |
| Java | Rust | 
| Rust | C++ |
| Rust | Java |
| Rust | Rust | 

In apache/arrow, the following patterns are redundant because they should be done in apache/arrow-rs:

| Producer | Consumer |
|--------|--------|
| Rust | Rust | 

In apache/arror-rs, the following patterns are redundant because they should be done in apache/arrow:

| Producer | Consumer |
|--------|--------|
| C++ | C++ |
| C++ | Java |
| Java | C++ |
| Java | Java |

Can we remove redundant patterns?

### Component(s)

Developer Tools, Integration

**Comment by kou** [comment]
@alamb @tustvold @paleolimbot  @zeroshade @pitrou What do you think about this?

**Comment by pitrou** [comment]
No opinion from me. I suppose it will make the test a bit shorter, but not by much since it's still `O(n**2)` where `n` is the number of implementations.

**Comment by alamb** [comment]
Seems like a good idea to me. Thanks @kou

**Comment by zeroshade** [comment]
Also seems like a good idea to me too, thanks @kou

**Comment by kou** [comment]
Thanks for sharing your opinions.
I'll implement this.

**Comment by alamb** [comment]
> In apache/arror-rs, the following patterns are redundant because they should be done in apache/arrow:

Can you give me some hint about how to reduce the test matrix in arrow-rs to remove the redundancies?

Here is how the job is run

https://github.com/apache/arrow-rs/blob/889a90436ffd69e94975049b047c413c53b2dfe3/.github/workflows/integration.yml#L56-L67

**Comment by kou** [comment]
Yes. The following change is needed with the current #44099 implementation:

```diff
diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
index 41edc1bb19..dcaf03c44a 100644
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -64,6 +64,7 @@ jobs:
       ARROW_INTEGRATION_GO: ON
       ARROW_INTEGRATION_JAVA: ON
       ARROW_INTEGRATION_JS: ON
+      ARROW_INTEGRATION_TARGET_LANGUAGES: "rust"
       ARCHERY_INTEGRATION_WITH_NANOARROW: "1"
       # https://github.com/apache/arrow/pull/38403/files#r1371281630
       ARCHERY_INTEGRATION_WITH_RUST: "1"
```

But this may be changed.

I'll open a PR in apache/arrow-rs after I complete this. Please wait for a while.

**Comment by alamb** [comment]
Thank you @kou

**Comment by kou** [comment]
Issue resolved by pull request 44099
https://github.com/apache/arrow/pull/44099

**Comment by kou** [comment]
https://github.com/apache/arrow-rs/issues/6406
