### ISSUE TITLE
[Python] Add Python wrapper for JsonExtensionType

### ISSUE THREAD

**Issue by rok** [apache/arrow#44066]
### Describe the enhancement requested

We [added JsonExtensionType](https://github.com/apache/arrow/pull/13901) and we should make it usable from Python.

### Component(s)

Python

**Comment by raulcd** [comment]
should this be a release blocker? @jorisvandenbossche @rok

**Comment by rok** [comment]
It's a nice to have for me, as it matches duckdb adding it. https://github.com/duckdb/duckdb/pull/13446

**Comment by raulcd** [comment]
I am really close to create RC0. I don't think we should block the release for this. I'll move this to 19.0.0 once I create RC0

**Comment by rok** [comment]
Please go ahead.

**Comment by pitrou** [comment]
Issue resolved by pull request 44070
https://github.com/apache/arrow/pull/44070
