### ISSUE TITLE
[R] cannot collect multiple times after passing to_arrow() and collect()

### ISSUE THREAD

**Issue by abduazizR** [apache/arrow#44069]
### Describe the bug, including details regarding any error messages, version, and platform.

I am using the arrow package in arrow and I am facing an issue when I try to collect data

Here is a reproducible example

``` r
library(duckdb)
#> Warning: package 'duckdb' was built under R version 4.4.1
#> Loading required package: DBI
library(arrow)
#> Warning: package 'arrow' was built under R version 4.4.1
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(tidyverse)

# Example
x <- iris |> to_duckdb() |> to_arrow()

# Collect first time (success)
x |> collect()
#> # A tibble: 150 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9          1.7         0.4 setosa 
#>  7          4.6         3.4          1.4         0.3 setosa 
#>  8          5           3.4          1.5         0.2 setosa 
#>  9          4.4         2.9          1.4         0.2 setosa 
#> 10          4.9         3.1          1.5         0.1 setosa 
#> # ℹ 140 more rows


# Collct second time => empty tibble
x |> collect()
#> # A tibble: 0 × 5
#> # ℹ 5 variables: Sepal.Length <dbl>, Sepal.Width <dbl>, Petal.Length <dbl>,
#> #   Petal.Width <dbl>, Species <chr>
```

<sup>Created on 2024-09-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### Component(s)

R

**Comment by amoeba** [comment]
Hello @abduazizR, thanks for filing an issue. Some implementation details are leaking here and I can see how this is a bit confusing. Your `to_arrow()` call is creating what we call a RecordBatchReader which can only be consumed once and your call to `collect()` consumes it.

You have two workarounds here,

```r
# 1. Convert to an arrow Table first
x <- iris |>
  to_duckdb() |>
  to_arrow() |>
  as_arrow_table()
x |> collect() # can be called repeatedly

# 2. or call to_arrow() every time you need to collect
x <- iris |> to_duckdb()
x |>
  to_arrow() |>
  collect() # can be called repeatedly
```

Converting to a Table (option 1) comes with the downside that it materializes the entire Table in memory but this might work fine for your use case.

In theory we could probably do some trick to make your original code work like resetting the RecordBatchReader on repeated calls to collect/compute but, at the very least, documenting this in `to_arrow()` would be good. I can file an PR for the latter. @nealrichardson do you have an opinion on leaving things as-is or implementing a fix here?

**Comment by nealrichardson** [comment]
Yeah it would be nice if it were reusable. If we could get the schema of the resulting table from duckdb without evaluating the full duckdb query, we could defer the RecordBatchReader construction until the arrow query evaluates (in `collect()`). `to_arrow()` would just construct the `arrow_dplyr_query` around the duckdb connection.

**Comment by thisisnic** [comment]
Issue resolved by pull request 44094
https://github.com/apache/arrow/pull/44094
