### ISSUE TITLE
[C++][Parquet] Remove deprecated APIs

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44079]
### Describe the enhancement requested

A bunch of Parquet C++ have been deprecated in past years. We should remove them.

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 44080
https://github.com/apache/arrow/pull/44080

**Comment by h-vetinari** [comment]
FWIW, a number of projects in conda-forge seem to be running into failures caused by these removals. Not sure how visible the warnings were, but just FYI:
- https://github.com/conda-forge/river-ingester-feedstock/pull/30
- https://github.com/conda-forge/tip-feedstock/pull/34
