### ISSUE TITLE
[CI] Remove deprecated job for macOS 11

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44076]
### Describe the bug, including details regarding any error messages, version, and platform.

There is a verify-rc-binaries job for macOS 11 that is now deprecated. It should be removed.

https://github.com/ursacomputing/crossbow/actions/runs/10794272900/job/29938245079

### Component(s)

Continuous Integration

**Comment by assignUser** [comment]
Resolved by PR #44077
