### ISSUE TITLE
[Java] Fix BaseVariableWidthViewVector

### ISSUE THREAD

**Issue by ViggoC** [apache/arrow#44088]
### Describe the bug, including details regarding any error messages, version, and platform.

Fix some bug in BaseVariableWidthViewVector
1. Fix handleSafe(), `while (index >= getValueCapacity())` may goes into a dead loop until the validityBufferSize is overflow when dataLength == 0, 
2. Fix copyFrom() and copyFromSafe(), the logic is wrong if `fromIndex != thisIndex` or the initialCapacity of the source and target vector is different.

### Component(s)

Java

**Comment by vibhatha** [comment]
Right, let me take look at the PR.

**Comment by lidavidm** [comment]
Issue resolved by pull request 44078
https://github.com/apache/arrow/pull/44078
