### ISSUE TITLE
[R] Add Rocky and opensuse to the allowlist for libarrow binaries

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#44114]
### Describe the enhancement requested

We already have [a few distros where we allow the download of binaries of libarrow by default](https://github.com/apache/arrow/blob/990cdf7dca8ba74d1c3b9a7b14898011a1142356/r/tools/nixlibs.R#L220-L229) should we add `rocky` and `opensuse-leap` to these? 

This came up when talking to the Posit Package Manager team which run those and they were a little surprised that these don't download binaries, but ubuntu does. I don't believe these flavors of linux are checked by CRAN, so we should be ok to add them.

### Component(s)

R

**Comment by nealrichardson** [comment]
Yep, seems safe to just do.
