### ISSUE TITLE
[R] Don't use the new pipe yet

### ISSUE THREAD

**Issue by jonkeane** [apache/arrow#44122]
### Describe the bug, including details regarding any error messages, version, and platform.

The R versions we support include 4.0 so we can't _quite yet_ switch to the new pipe. 

Caught with the test-r-versions nightly job: https://github.com/ursacomputing/crossbow/actions/runs/10866689696/job/30154574098

### Component(s)

R

**Comment by assignUser** [comment]
Do we support 4.0 still? I thought last 4 versions, which would mean 4.1 is our minimum, no?

**Comment by assignUser** [comment]
Ah checked https://www.tidyverse.org/blog/2019/04/r-version-support/

It's current + 4 so 4.0 is still in :+1:

**Comment by jonkeane** [comment]
Issue resolved by pull request 44123
https://github.com/apache/arrow/pull/44123
