### ISSUE TITLE
[Python] OSError: Expected to be able to read 1013159856 bytes for message body, got 513144496

### ISSUE THREAD

**Issue by lasuomela** [apache/arrow#44146]
Hi,

I'm using Huggingface Datasets to read data from disk, which internally utilizes PyArrow. Reading data, I intermittently run into the following type of error:

```
  pa_table = opened_stream.read_all()
  File "pyarrow/ipc.pxi", line 762, in pyarrow.lib.RecordBatchReader.read_all
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
OSError: Expected to be able to read 1013159856 bytes for message body, got 513144496
```

Any ideas about what typically produces this kind of errors with PyArrow, or any debugging tips?

Context:

Huggingface Datasets reads the data with an approach equivalent to:

```
    import pyarrow as pa
    filename = 'some_path.arrow'
    memory_mapped_stream = pa.memory_map(filename)
    opened_stream = pa.ipc.open_stream(memory_mapped_stream)
    pa_table = opened_stream.read_all()
```

I access the same data concurrently from 4 processes. I assume the problem isn't in the data itself, because at a later time I can read the piece of data where the error occurs without any problem. Furthermore, this error only occurs on one of the computers I'm using. Could this be caused by some 'system' related thing? For example, the maximum number of simultaneously memory mapped files is limited in `/proc/sys/vm/max_map_count`.

Pyarrow version: Tried 15.0, 17.0
Platform: Red Hat Enterprise Linux release 8.10

### Component(s)

Python

**Comment by aditya-malte** [comment]
Hi,
How did you fix this?

**Comment by lasuomela** [comment]
Hi,
It was actually just a case of data corruption that occurred during file copy using `shutil.copytree`. I switched to rsync and got no more problems. So likely it's a case of corrupted data, as to my understanding the error means that the actual file size read is different from the file size at file creation.

Hope this helps.
-Lauri
