### ISSUE TITLE
[Packaging] Remove unnecessary references to Ubuntu bionic

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44149]
### Describe the enhancement requested

We did [drop support for Ubuntu bionic (18.04) more than a year ago](https://github.com/apache/arrow/issues/33800) but I've found some references on the code:
https://github.com/apache/arrow/blob/main/dev/release/setup-ubuntu.sh#L28

We should remove it.

### Component(s)

Packaging

**Comment by assignUser** [comment]
Issue resolved by pull request 44150
https://github.com/apache/arrow/pull/44150
