### ISSUE TITLE
[C++][Acero] More tests for row segmenter

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#44167]
### Describe the enhancement requested

Current tests are not covering fixed size binary and dictionary types:
https://github.com/apache/arrow/blob/a6f736c962adddd0f7078a10338fe8f1445c583b/cpp/src/arrow/acero/hash_aggregate_test.cc#L835-L888

which are clearly in the supported type list:
https://github.com/apache/arrow/blob/a6f736c962adddd0f7078a10338fe8f1445c583b/cpp/src/arrow/compute/row/grouper.cc#L475

(Both fixed size binary and dictionary are "fixed width".)

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 44166
https://github.com/apache/arrow/pull/44166
