### ISSUE TITLE
[CI][Python] Some verification tasks on Ubuntu 20.04 fail because we have dropped support for Python 3.8

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44173]
### Describe the bug, including details regarding any error messages, version, and platform.

Since we merge the drop python 3.8 PR: 
- https://github.com/apache/arrow/issues/43518 

There has been some verification jobs on Ubuntu 20.04 that have started failing:
- [verify-rc-source-integration-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10922528785/job/30317040315)
- [verify-rc-source-python-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10922529193/job/30317042367)

Ubuntu's 20.04 Python version is 3.8 and we do not support it. We should not test pyarrow verification on Ubuntu 20.04.

### Component(s)

Continuous Integration, Python

**Comment by pitrou** [comment]
Do we care about running release verification on such an old Ubuntu LTS? @kou
