### ISSUE TITLE
[GLib][Ruby][Flight] allow setting CallOption timeout

### ISSUE THREAD

**Issue by datbth** [apache/arrow#44178]
### Describe the enhancement requested

Currently, it's not possible to set the `timeout` option of `FlightCallOptions` via Ruby `ArrowFlight::CallOptions`.  
Can you expose a method for setting it in flight glib and ruby?

Thank you.

### Component(s)

GLib, Ruby

**Comment by kou** [comment]
Issue resolved by pull request 44181
https://github.com/apache/arrow/pull/44181
