### ISSUE TITLE
[Python] install  pyarrow wrong

### ISSUE THREAD

**Issue by xiaoHaoWeb** [apache/arrow#44189]
### Describe the usage question you have. Please include as many useful details as  possible.

CMake Error at CMakeLists.txt:266 (find_package):
        By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Arrow", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "Arrow" with any of
        the following names:
      
          ArrowConfig.cmake
          arrow-config.cmake
      
        Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
        "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      error: command '/usr/bin/cmake' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyarrow)
Failed to build pyarrow

### Component(s)

Python

**Comment by pitrou** [comment]
@xiaoHaoWeb Can you please explain how you got your traceback? What platform you are using, which Python version, which command you ran, etc.

**Comment by xiaoHaoWeb** [comment]
my platform is docker Alpine,python 3.11，run pip install pyarrow

**Comment by xiaoHaoWeb** [comment]
@pitrou

**Comment by pitrou** [comment]
Thanks. So this is similar to #39846 : we do not provide musllinux wheels for now, so you have to build and install Arrow C++ before being able to build and install PyArrow.
