### ISSUE TITLE
[C++][Parquet] Rename parquet Endianess -> Endianness

### ISSUE THREAD

**Issue by mapleFU** [apache/arrow#44186]
### Describe the enhancement requested

Typo in column_writer.cc, Endianess -> Endianness

### Component(s)

C++, Parquet

**Comment by pitrou** [comment]
Issue resolved by pull request 40856
https://github.com/apache/arrow/pull/40856

**Comment by pitrou** [comment]
@RoboSchmied Can you comment here so that we assign this issue to you?

**Comment by RoboSchmied** [comment]
> @RoboSchmied Can you comment here so that we assign this issue to you?

sure.
