### ISSUE TITLE
[CI][macOS] Drop support for macOS 12 (Monterey)

### ISSUE THREAD

**Issue by kou** [apache/arrow#44206]
### Describe the enhancement requested

Because Homebrew dropped support for macOS 12 (Monterey): https://github.com/Homebrew/brew/pull/18314

NOTE: Recently, `macos-12` jobs are failing. It may be related to this.

### Component(s)

Continuous Integration

**Comment by pitrou** [comment]
Issue resolved by pull request 44212
https://github.com/apache/arrow/pull/44212
