### ISSUE TITLE
[Python] uwsgi fails installing on macOS arm64 benchmarking machine

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44218]
### Describe the bug, including details regarding any error messages, version, and platform.

See https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/5994#01921fbc-0a5c-438c-928a-761d1a14e06d/34-652

We could simply avoid installing uwsgi on macOS. It's probably enough to exercise the uwsgi-specific test on Linux.

### Component(s)

Benchmarking, Python

**Comment by pitrou** [comment]
@jorisvandenbossche What do you think?

**Comment by pitrou** [comment]
We could try to set the `UWSGI_PYTHON_NOLIB` environment variable instead:
https://github.com/unbit/uwsgi/blob/b738f550fd74ebf77cc966708d26e4f64ce2a7a3/plugins/python/uwsgiplugin.py#L45

**Comment by pitrou** [comment]
Issue resolved by pull request 44221
https://github.com/apache/arrow/pull/44221

**Comment by jorisvandenbossche** [comment]
I think the current solution to only test it on linux is also perfectly fine, but just wondering about what was going on:  the `uwsgi` package has no wheels (and so the source install was failing), but from https://flask.palletsprojects.com/en/3.0.x/deploying/uwsgi/, it points to https://pypi.org/project/pyuwsgi/, which does have wheels.

I am not very familiar with those tools and packages, but if that package provides the same underlying tool, switching to that might actually be useful for linux as well to avoid compiling it from source on CI.

**Comment by pitrou** [comment]
Uh, I had no idea `pyuwsgi` even existed. Well, we could try switching to it...
