### ISSUE TITLE
[Dev] Use "Gandiva" instead of "C++ - Gandiva" label

### ISSUE THREAD

**Issue by kou** [apache/arrow#44223]
### Describe the enhancement requested

We're using "C++" and "C++ - Gandiva" labels in our templates like https://github.com/apache/arrow/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml .

Do we need "C++ - " in "C++ - Gandiva"? Can we remove the "C++ - " part and use "C++" and "Gandiva" labels instead of "C++ - Gandiva" label?

### Component(s)

Developer Tools

**Comment by pitrou** [comment]
I don't mind personally.

**Comment by raulcd** [comment]
Issue resolved by pull request 44722
https://github.com/apache/arrow/pull/44722
