### ISSUE TITLE
[C#] Use new decimal.GetBits overloads to reduce allocations when serializing decimal values

### ISSUE THREAD

**Issue by georgevanburgh** [apache/arrow#44237]
### Describe the enhancement requested

Similar to #41349, .NET 6 introduced [new overloads for `decimalGetBits`](https://learn.microsoft.com/en-us/dotnet/api/system.decimal.getbits?view=net-8.0#system-decimal-getbits(system-decimal-system-span((system-int32)))) for which allow the use of a `stackalloc`'ed span, and avoiding the allocation of a fresh byte array for each value serialized. This should (slightly) reduce the allocations associated with serializing C# decimal values.

https://github.com/apache/arrow/blob/80622fa077e5232037cde10e222fca4004ad9d0c/csharp/src/Apache.Arrow/DecimalUtility.cs#L226

### Component(s)

C#

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 44238
https://github.com/apache/arrow/pull/44238
