### ISSUE TITLE
[C++] How to delete a row of data from Arrow

### ISSUE THREAD

**Issue by THUMarkLau** [apache/arrow#44243]
### Describe the usage question you have. Please include as many useful details as  possible.

I have reviewed the Arrow documentation and the API of arrow::Table, arrow::Array, and arrow::Builder, but I couldn't find any API related to deleting data. How can I delete a row of data from Arrow? 

### Component(s)

C++

**Comment by kou** [comment]
Arrow data is immutable. So you can't delete a row from existing Arrow data. You need to create a new Arrow data that doesn't have the target row.

If you want to use a compute function, we have `filter` function: https://arrow.apache.org/docs/cpp/compute.html#selections

It selects only the specified rows.
