### ISSUE TITLE
[C++] Unifying simd header includings

### ISSUE THREAD

**Issue by zanmato1984** [apache/arrow#44249]
### Describe the enhancement requested

Some of simd-related files are including concrete system headers such as:
https://github.com/apache/arrow/blob/6f64af54ea3662b7e1685b84a81429df14beace1/cpp/src/arrow/acero/bloom_filter.h#L20-L22
However I see that https://github.com/apache/arrow/blob/6f64af54ea3662b7e1685b84a81429df14beace1/cpp/src/arrow/util/simd.h seems to be a centralized header to sort out all the platform-specific checks. Besides, I think it is a good place to put universal definitions - e.g. working around certain compiler bugs like what #44116 did - to be visible to all simd source files.

Therefore I think we can unify the simd header inclusion by utilizing `simd.h`.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 44250
https://github.com/apache/arrow/pull/44250
