### ISSUE TITLE
[C++][FS][Azure] Edgecase where `GetFileInfo` incorrectly returns NotFound on flat namespace and Azurite

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#44256]
### Describe the bug, including details regarding any error messages, version, and platform.

**The problem**
Imagine in the following directory structure:

```
container-name/a/    directory
container-name/a.txt    file 
```

`fs->GetFileInfo("container-name/a/")` returns `FileType::NotFound`.

**Why it happens**
1. `fs->GetFileInfo("container-name/a/")` returns causes a list with prefix `a` and limit 1. 
2. The result is `a.txt` because `.` comes before `/` lexographically.
3. This doesn't match the requested name so return `FileType::NotFound`. 

### Component(s)

C++

**Comment by Tom-Newton** [comment]
I'm going to try fixing this. I think it will require an extra list operation but only in this edgecase.

**Comment by kou** [comment]
Issue resolved by pull request 44302
https://github.com/apache/arrow/pull/44302
