### ISSUE TITLE
[C++][FS][Azure] SAS token authentication

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#44308]
### Describe the enhancement requested

Child of https://github.com/apache/arrow/issues/38598

Add support for Azure CLI auth. Probably just accept the SAS token as an argument and use AzureSasCredential https://github.com/Azure/azure-sdk-for-cpp/blob/101f20f2bbf3dd5f6438565cd9f709a231317f77/sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/azure_sas_credential.hpp#L16C9-L16C27. This should make the implementation very similar to all the other Azure auths. 

One possible complication I'm aware of is in `CopyFile`, because this is implemented by generating a federated SAS token from whatever the original authentication was. I don't know if its possible to get a federated SAS token when using SAS token auth. 

Also I'm not sure we need to generate a federated SAS token to implement `CopyFile`. I think we should be able to use [Copy Blob](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id) instead of [Copy Blob From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url?tabs=microsoft-entra-id). I think the latter is only needed if the source is not in the same Azure blob storage account. 

### Component(s)

C++

**Comment by Tom-Newton** [comment]
take

**Comment by Tom-Newton** [comment]
I have it working to some extent, but as I feared there is a complexity with `CopyFiles` because its implemented by creating a SAS token at runtime https://github.com/apache/arrow/pull/41276. When authenticated with a SAS token already we cannot generate a new SAS token in the current way (I tested that it does work with Azure CLI auth so the problem is not just broken code that we still need to test https://github.com/apache/arrow/issues/41315).

There are 2 options:
1. Stop using SAS token inside `CopyFiles`
    1. Normally a SAS token is only needed when doing a copy from one Azure storage account to another Azure storage account. Within a single storage account we should be able to use the [Copy Blob](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id) API instead of [Copy Blob From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url?tabs=microsoft-entra-id) but I'm not sure if this is actually exposed by the C++ SDK. 
    1. I'm a bit concerned by the current implementation that generates a new SAS token for every blob. Azure tends to have tight rate limits on APIs to generate authentication tokens, so I suspect a call to `CopyFiles` on a large directory would have problems. 
    1. We can close https://github.com/apache/arrow/issues/41315
4. Use the SAS token we already have 
    1. Definitely possible.

**Comment by kou** [comment]
The option 1 is better, right? Let's try the option 1.

**Comment by Tom-Newton** [comment]
> The option 1 is better, right? Let's try the option 1.

I thought so too but, after trying it, now I'm not so sure. I checked a few of the Azure SDKs (C++, Python, and golang) and it actually looks like none of them expose the [Copy Blob](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id) API. 

I found the `SourceAuthorization` option which should allow configuring different authentication to the source when using [Copy Blob From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url?tabs=microsoft-entra-id). Plus some some [examples of how to use it in `azcopy`](https://github.com/Azure/azure-storage-azcopy/blob/ac9320275a2d5fcf590794c90489eee6a07458fd/ste/mgr-JobPartTransferMgr.go#L970-L987). There also seem to be a string of changes in `azcopy` to try to get this working correctly, because of problems like making too many token requests or using a cached token after it expired. The current implementation adds a custom http policy when creating the Azure client, which intercepts requests that include an empty `x-ms-copy-source-authorization` and populate it https://github.com/Azure/azure-storage-azcopy/blob/7f5ab059c28b09841d009d28b7510d4fcb167dc8/ste/sourceAuthPolicy.go#L47-L77.

This is all looking rather complicated and I don't think we can generate the required bearer tokens with SAS or account key auth. So I think I'll stick with generating SAS tokens, and I think I will just bump their expiry a bit as a simple mitigation for the [problem mentioned in azcopy](https://github.com/Azure/azure-storage-azcopy/pull/2513) where tokens expired during retries.

**Comment by Tom-Newton** [comment]
Ok, I think I finally worked it out `StartCopyFromUri` in the Azure C++ SDK can do copies within the same storage account any extra authentication required.
