### ISSUE TITLE
[C++][FS][Azure] 2 of the `GenericFileSystemTest`s are failing with the `AzureFileSystem` on hierarchical namespace storage accounts

### ISSUE THREAD

**Issue by Tom-Newton** [apache/arrow#44303]
### Describe the bug, including details regarding any error messages, version, and platform.

These 2 tests fail on `main` and they probably always have failed
`TestAzureHierarchicalNSGeneric.GetFileInfoSelectorWithRecursion` 
`TestAzureHierarchicalNSGeneric.Empty`

CI runs tests with azurite but if we provide the necessary connection details there are also tests that run against real Azure blob storage, including both flat and hierarchical namespace storage accounts. 

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 44307
https://github.com/apache/arrow/pull/44307
