### ISSUE TITLE
[Python][Packaging] Revert macOS deployment target to 12 for pyarrow

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44314]
### Describe the enhancement requested

We did dropped support for macOS 12 on:
- https://github.com/apache/arrow/issues/44206

For pyarrow wheels we just bumped the macosx deployment target from 10 to 12 for 18.0.0:
- https://github.com/apache/arrow/issues/41696

We probably should still use the macOS deployment target 12 at least for a release.

### Component(s)

Packaging, Python

**Comment by kou** [comment]
Issue resolved by pull request 44315
https://github.com/apache/arrow/pull/44315
