### ISSUE TITLE
[C++][FS][S3] Add support for instance level TLS related options

### ISSUE THREAD

**Issue by kou** [apache/arrow#44333]
### Describe the enhancement requested

We can set TLS related options globally by `arrow::fs::FileSystemGlobalOptions` but can't set them per instance.
If we have `arrow::fs::S3Options` has TLS related options, we can set them per instance.

See also: https://github.com/apache/arrow/pull/43601#discussion_r1778521471

### Component(s)

C++

**Comment by pitrou** [comment]
Are you talking about:
https://github.com/apache/arrow/blob/ded148c2ef5dd441a3b6ab9496d0ed0aeb940f71/cpp/src/arrow/filesystem/s3fs.h#L204-L223

**Comment by kou** [comment]
Yes. GH-43601 included this.

I close this.
