### ISSUE TITLE
[C++][FS][S3] Errors in AWS SDK are not propagated correctly

### ISSUE THREAD

**Issue by OliLay** [apache/arrow#44334]
### Describe the bug, including details regarding any error messages, version, and platform.

If the AWS SDK fails to send a request (for whatever reason), it indicates so in its `*Outcome` model classes. In the `ObjectOutputStream`, we have a bug where we do not check the outcome model that the AWS SDK returns to us correctly, hence indicating a write was successful although it was not.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 44335
https://github.com/apache/arrow/pull/44335
