### ISSUE TITLE
[C++][Packaging] Enable Azure Filesystem in official packages

### ISSUE THREAD

**Issue by tobim** [apache/arrow#44347]
### Describe the enhancement requested

The pre-built binary packages that can be downloaded from artifactory via `apt`/`dnf`/`yum` do not include support for Azure.

I hereby request to enable Azure support similar to S3 and GCS.

### Component(s)

C++

**Comment by kou** [comment]
Oh, I forgot to enable it.

**Comment by raulcd** [comment]
@kou I've seen you've pushed for this yesterday. I am going to do the feature freeze today but let me know if you close it. I am happy to add it once merged as it seems pretty isolated and I don't think it'll cause other issues.

**Comment by kou** [comment]
Thanks! I can complete this today.

**Comment by kou** [comment]
Issue resolved by pull request 44348
https://github.com/apache/arrow/pull/44348

**Comment by kou** [comment]
Done!
