### ISSUE TITLE
[CI][Packaging][Python] Free-threaded wheel build failing to in docker image install of tzdata

### ISSUE THREAD

**Issue by jorisvandenbossche** [apache/arrow#44355]
The free-threaded linux wheel builds are failing recently, see eg https://github.com/ursacomputing/crossbow/actions/runs/11146254492/job/30977772790

It seems that the installation of tzdata (does that come as dependency of python in apt?) requires some manual interaction on the cli, regardless of the `-y` being passed:

```
   #8 62.14 Configuring tzdata
  #8 62.14 ------------------
  #8 62.14 
  #8 62.14 Please select the geographic area in which you live. Subsequent configuration
  #8 62.14 questions will narrow this down by presenting a list of cities, representing
  #8 62.14 the time zones in which they are located.
  #8 62.14 
  #8 62.14   1. Africa   3. Antarctica  5. Arctic  7. Atlantic  9. Indian    11. US
  #8 62.14   2. America  4. Australia   6. Asia    8. Europe    10. Pacific  12. Etc
  Error: The operation was canceled.
```

This was not the case when we initially added those builds.

cc @raulcd @kou

**Comment by jorisvandenbossche** [comment]
Although when we added those (https://github.com/apache/arrow/pull/43965), the above output was also already present in the logs. So the fact that it is hanging here might not necessarily be caused by tzdata itself.

Looking at some more of the failures the last days, some of those are also being caused by internet / download connection issues.

**Comment by kou** [comment]
Issue resolved by pull request 44362
https://github.com/apache/arrow/pull/44362
