### ISSUE TITLE
[Python][CI] Python minimal examples fail due to dataset not being present

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44369]
### Describe the bug, including details regarding any error messages, version, and platform.

Since https://github.com/apache/arrow/pull/43740 was merge the minimal python jobs have started failing:

- [example-python-minimal-build-fedora-conda](https://github.com/ursacomputing/crossbow/actions/runs/11265233598/job/31326751164)
- [example-python-minimal-build-ubuntu-venv](https://github.com/ursacomputing/crossbow/actions/runs/11265233463/job/31326725447)

This is due to dataset not being present but parametrize using it on `python/pyarrow/tests/test_dataset.py::test_dataset_partitioning_format`  the error is:
```
 _ ERROR collecting miniconda-for-arrow/envs/pyarrow-3.10/lib/python3.10/site-packages/pyarrow/tests/test_dataset.py _
miniconda-for-arrow/envs/pyarrow-3.10/lib/python3.10/site-packages/pyarrow/tests/test_dataset.py:740: in <module>
    (ds.HivePartitioning, (r"foo=A/bar=ant%20bee", ""), ("", "")),
E   AttributeError: 'NoneType' object has no attribute 'HivePartitioning'
```

### Component(s)

Continuous Integration, Python

**Comment by kou** [comment]
Issue resolved by pull request 44370
https://github.com/apache/arrow/pull/44370
