### ISSUE TITLE
[C#][Integration] Set up integration testing of C# Flight

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#44361]
### Describe the enhancement requested

Archery includes Flight integration tests but not for C#. These would be useful for catching issues like #44360, although it appears that `DoExchange` is not currently included in the integration tests.

### Component(s)

C#, Integration

**Comment by adamreeve** [comment]
take

**Comment by CurtHagenlocher** [comment]
Issue resolved by pull request 44377
https://github.com/apache/arrow/pull/44377
