### ISSUE TITLE
[Python] Can a struct be aggregated with 'list' on a table.group_by?

### ISSUE THREAD

**Issue by robhod** [apache/arrow#44383]
### Describe the usage question you have. Please include as many useful details as  possible.

I'm trying to create a list of structs based on a grouping column. See below:
Hitting not implemented error but hash_list docs (https://arrow.apache.org/docs/cpp/compute.html#aggregations) suggest it supports any input type so wasn't sure if there was an issue in how I set this up or if I should raise a feature request/bug?

```python
import pyarrow as pa

# source data
table = pa.table(
    {
        "col1": [1, 1, 2, 2, 3],
        "struct_col": [
            {"a": 1, "b": "testa"},
            {"a": 1, "b": "testb"},
            {"a": 2, "b": "testc"},
            {"a": 2, "b": "testd"},
            {"a": 3, "b": "teste"},
        ],
    }
)

# required output
grouped_table = pa.table(
    {
        "grouped": [1, 2, 3],
        "agg_struct_col": [
            [{"a": 1, "b": "testa"}, {"a": 1, "b": "testb"}],
            [{"a": 2, "b": "testc"}, {"a": 2, "b": "testd"}],
            [{"a": 3, "b": "teste"}],
        ],
    }
)

# using group_by
grouped = table.group_by("col1").aggregate([("struct_col", "list")])


```
  File "scratch/pyarrowexample.py", line 30, in <module>
    grouped = table.group_by("col1").aggregate([("struct_col", "hash_list")])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 6359, in pyarrow.lib.TableGroupBy.aggregate
  File "l/.venv/lib/python3.11/site-packages/pyarrow/acero.py", line 403, in _group_by
    return decl.to_table(use_threads=use_threads)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_acero.pyx", line 590, in pyarrow._acero.Declaration.to_table
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Function 'hash_list' has no kernel matching input types (struct<a: int64, b: string>, uint32)

### Component(s)

Python

**Comment by amoeba** [comment]
Thanks for filing an issue. I think this isn't implemented and that the docs should be updated until it is. For comparison, `hash_count` is listed in the linked table as accepting "Any" input and is registered as:

https://github.com/apache/arrow/blob/6f424d4df218d3e99cff44def99a9eb7ea180978/cpp/src/arrow/compute/kernels/hash_aggregate.cc#L3449-L3457

Note `InputType::Any()`. Whereas `hash_list` is only registered for primitive and not nested types and isn't registered similarly:

https://github.com/apache/arrow/blob/6f424d4df218d3e99cff44def99a9eb7ea180978/cpp/src/arrow/compute/kernels/hash_aggregate.cc#L3679-L3689

I'm not sure if we have an issue to track this. cc @felipecrv to confirm

**Comment by robhod** [comment]
Thanks for the quick reply and for confirming this aggregation is not currently supported.
Do you know if there are any plans to extend support to structs for this aggregation type i can keep track of? Happy to raise request if not or if needed. 
In any case thanks again for the quick feedback, I'll look to do something in polars for now.

**Comment by felipecrv** [comment]
> Do you know if there are any plans to extend support to structs for this aggregation type i can keep track of? Happy to raise request if not or if needed.

I don't think there is an issue. Feel free to create one.

**Comment by robhod** [comment]
great thanks - created here  [44417](https://github.com/apache/arrow/issues/44417).
