### ISSUE TITLE
[GLib] Add `GArrowDecimal32DataType`

### ISSUE THREAD

**Issue by kou** [apache/arrow#44392]
### Describe the enhancement requested

It's for `arrow::type::Decimal32Type`.

See also the `GArrowDecimal128DataType` implementation:

https://github.com/apache/arrow/blob/8a7224d21fb7ac1938cb039cc6dcfd38db94519e/c_glib/arrow-glib/basic-data-type.h#L611-L630

https://github.com/apache/arrow/blob/8a7224d21fb7ac1938cb039cc6dcfd38db94519e/c_glib/arrow-glib/basic-data-type.cpp#L117

https://github.com/apache/arrow/blob/8a7224d21fb7ac1938cb039cc6dcfd38db94519e/c_glib/arrow-glib/basic-data-type.cpp#L1548-L1599

https://github.com/apache/arrow/blob/main/c_glib/test/test-decimal128-data-type.rb

### Component(s)

GLib

**Comment by kou** [comment]
Issue resolved by pull request 44580
https://github.com/apache/arrow/pull/44580

**Comment by kou** [comment]
@hiroyuki-sato Could you add "take" only comment here to assign you to this issue?

**Comment by hiroyuki-sato** [comment]
@kou I take the issue.
