### ISSUE TITLE
[Java][Dataset] Support HDFS filesystem for Read/Write using Dataset API 

### ISSUE THREAD

**Issue by suryaatul1** [apache/arrow#44419]
### Describe the bug, including details regarding any error messages, version, and platform.

I am using the Arrow Flight module to Version 17.0.0 , along with the
DataSet API to perform the read/write operations to persist the data
on the HDFS filesystem.
However I get below error message

**_Error message : "Got HDFS URI but Arrow compiled without HDFS support"_**

The per the documentation for V17.0.0 , its is mentioned HDFS support
is included Apache Arrow Java panache release

As per one of the post , I could see the Issue #37323 is never release
to any Arrow version

Please could you guide me if HDFS support is included , or I will java
to carry out any additional steps to get this working on my Hadoop
environment

Thanks
Atul S

### Component(s)

Integration, Java

**Comment by suryaatul1** [comment]
Apologies for typo
"The per the documentation for V17.0.0 , its is mentioned HDFS support
is included Apache Arrow Java package release "

**Comment by kou** [comment]
It seems that it's not implemented yet: https://github.com/apache/arrow/issues/36703
Can we close this as a duplicated?

BTW, could you share the documentation URL you referred?

**Comment by suryaatul1** [comment]
Thank you Kou for the response.

Please find below the documentation Link
https://arrow.apache.org/docs/java/dataset.html#read-data-from-hdfs

I understand this is duplicate and can be closed , just wanted to check if we see HDFS support to be enabled in upcoming release , if yes any timelines around the same ??

Appreciate your help on this 

![arrowSupport](https://github.com/user-attachments/assets/12acb7e7-61f9-4597-8823-bef7fe955554)

**Comment by kou** [comment]
Thanks. I close this as a duplicated.

It seems that it was added by GH-10333. Nobody noticed that HDFS support isn't included yet...

The upcoming release will not include HDFS support because nobody works on this. Do you want to work on this?
