### ISSUE TITLE
[Docs][C++] cpp/README.md refers docs/source/developers/cpp but it just displays a list of files

### ISSUE THREAD

**Issue by hiroyuki-sato** [apache/arrow#44416]
### Describe the enhancement requested

Hello, team.

[Apache Arrow C++](https://github.com/apache/arrow/tree/main/cpp) links to [C++ Development Documentation](https://github.com/apache/arrow/tree/main/docs/source/developers/cpp)

The linked C++ Development Documentation page does not have a README, it just displays a list of files.

<img width="994" alt="スクリーンショット 2024-10-15 17 20 04" src="https://github.com/user-attachments/assets/94d4b02e-81dc-4a01-83cf-d5a542b8e394">

Adding `README.md` like below may help for developers.

## C++ Development Documentation

* [Building Arrow C++](https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/building.rst)
* [Conventions](https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/conventions.rst)
* [Development Guidelines](https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/development.rst)
* [Cross compiling for WebAssembly with Emscripten](https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/emscripten.rst)
* [Fuzzing Arrow C++](https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/fuzzing.rst)
* [Developing on Windows](https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/windows.rst)

### Component(s)

Documentation

**Comment by kou** [comment]
How about changing the link in `cpp/README.md` to https://arrow.apache.org/docs/dev/developers/cpp/index.html from https://github.com/apache/arrow/blob/main/docs/source/developers/cpp instead of adding a `README.md` to `docs/source/developers/cpp/`?

**Comment by kou** [comment]
Issue resolved by pull request 44427
https://github.com/apache/arrow/pull/44427
