### ISSUE TITLE
[Packaging][Release] Revert uploading artifacts before testing for centos-9 on arm64 once upstream is fixed

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44439]
### Describe the bug, including details regarding any error messages, version, and platform.

This is a follow up from:
- https://github.com/apache/arrow/issues/44422

It can be reproduced locally with:
```
$ docker run --platform linux/aarch64 -it --rm quay.io/centos/centos:stream9
[root@2fec18b5cf70 /]# dnf update -y
CentOS Stream 9 - BaseOS                                                                             2.8 MB/s | 9.4 MB     00:03    
CentOS Stream 9 - AppStream                                                                          161  B/s | 4.4 kB     00:27    
Errors during downloading metadata for repository 'appstream':
  - Downloading successful, but checksum doesn't match. Calculated: ef16d195332d673efbe2fc9a316726df177a605e1caef3ca49f88a7181f973654347400cb50ee464dd7206fc9a59c34cf37d0baea158add0bde531cb7cab8039(sha512)  Expected: b2b0cdc3fdc6021ff6ddd33a4b508daa7050cc8cdfca7dd9aa6c854ed80dd39b4fd5bfa6e66db2c37e0ad25cee9f53e7b24b84d7f302f2ca07198439524d1c99(sha512) 
Error: Failed to download metadata for repo 'appstream': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

Once this is fixed upstream (hopefully) we should revert back: https://github.com/apache/arrow/commit/0577ff62828e4cde75536ce0d188c9b66889fba4
So we don't upload artifacts if tests fail.

### Component(s)

Packaging, Release

**Comment by kou** [comment]
I think that we don't need to revert it. Because it's useful for debugging when we can build deb/rpm but our tests are failed with the built deb/rpm. We can download built deb/rpm and test them on local with the change.

**Comment by raulcd** [comment]
ok, that makes sense. I was just thinking on avoiding pushing some bad packages but I guess this is more relevant to publishing failing wheels, etcetera to external nightly systems but here doesn't apply that much. I am closing this as not planned. Thanks @kou
