### ISSUE TITLE
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyarrow) on Python 3.13

### ISSUE THREAD

**Issue by cla-bit** [apache/arrow#44443]
### Describe the bug, including details regarding any error messages, version, and platform.

Before i upgraded to python 3.13, I was using python 3.11 and installing pyarrow had no issue. Now, i have upgraded to 3.13, and installed pyarrow and i got this error:

```
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
Failed to build pyarrow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyarrow)
```

How can this be solved?
Is python 3.13 compactible with pyarrow 17.0.0?

### Component(s)

Python

**Comment by raulcd** [comment]
There are not pre-built wheels for Python 3.13 for Arrow 17.0.0. You have to build pyarrow yourself.
We are in the process of releasing Arrow 18.0.0 where pyarrow wheels will be built for Python 3.13.

**Comment by cla-bit** [comment]
> There are not pre-built wheels for Python 3.13 for Arrow 17.0.0. You have to build pyarrow yourself. We are in the process of releasing Arrow 18.0.0 where pyarrow wheels will be built for Python 3.13.

thank you.

**Comment by cla-bit** [comment]
I will install python 3.11 and use arrow on it, while waiting for the pre-bult wheels support for python 3.13 and also build pyarrow to support python 3.13.

**Comment by assignUser** [comment]
Building from source isn't trivial so downgrading the python version would have been my recommendation as well!

**Comment by lacsteorra** [comment]
> There are not pre-built wheels for Python 3.13 for Arrow 17.0.0. You have to build pyarrow yourself. We are in the process of releasing Arrow 18.0.0 where pyarrow wheels will be built for Python 3.13.

thank you ,you help me
