### ISSUE TITLE
[Java][CI] Implement Flight do_exchange integration test

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#44444]
### Describe the enhancement requested

I added a new Flight integration test for testing `do_exchange` between the C++ and C# implementations: #44424

It would be useful to also have a Java implementation of this test to check compatibility of the Java implementation against C++ and C#.

### Component(s)

Continuous Integration, Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 44445
https://github.com/apache/arrow/pull/44445
