### ISSUE TITLE
[CI] Flight integration tests don't include non-target implementations as producers

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#44479]
### Describe the bug, including details regarding any error messages, version, and platform.

See https://github.com/apache/arrow/pull/44377#issuecomment-2425385449

The Archery Flight integration tests currently run the following combinations (eg. see https://github.com/apache/arrow/actions/runs/11285634070/job/31388753091):
```
Integration: Test: Flight: C++ -> C++
Integration: Test: Flight: C++ -> Java
Integration: Test: Flight: C++ -> C#
Integration: Test: Flight: C++ -> Go
Integration: Test: Flight: C++ -> Rust
Integration: Test: Flight: Java -> C++
Integration: Test: Flight: Java -> Java
Integration: Test: Flight: Java -> C#
Integration: Test: Flight: Java -> Go
Integration: Test: Flight: Java -> Rust
Integration: Test: Flight: C# -> C++
Integration: Test: Flight: C# -> Java
Integration: Test: Flight: C# -> C#
Integration: Test: Flight: C# -> Go
Integration: Test: Flight: C# -> Rust
```

This is missing running Go and Rust as producers with the three target implementations as clients.

### Component(s)

Integration

**Comment by kou** [comment]
Issue resolved by pull request 44691
https://github.com/apache/arrow/pull/44691
