### ISSUE TITLE
18.0.0 Release date?

### ISSUE THREAD

**Issue by CasperVanIersel** [apache/arrow#44499]
### Describe the usage question you have. Please include as many useful details as  possible.

When is 18.0.0 coming out, pls i need it

### Component(s)

Python

**Comment by raulcd** [comment]
We are currently validating the Release Candidate 0 for 18.0.0. You can follow the status on the mailing list: https://lists.apache.org/thread/c3t7wn32pp506925fm1bg15lrrk4jrz6
The date will depend if issues are identified and more release candidates are required.
