### ISSUE TITLE
R+arrow: using open_dataset on compressed flat files 

### ISSUE THREAD

**Issue by larry77** [apache/arrow#44514]
### Describe the enhancement requested

I would like to be able to use open_dataset on a set of *compressed* flat files (e.g. some compressed csv files). I receive compressed csv files for my work, and every time I need to decompress them to use the open_dataset interface. Any workaround for this? Thanks!

### Component(s)

R

**Comment by khwilson** [comment]
I _think_ setting `format = 'csv'` will solve your problem:

```R
library(arrow)
library(dplyr)

system('mkdir foo')
system('echo "a,b,c\n1,2,3\n" > test.csv')
system('gzip test.csv')
system('mv test.csv.gz foo')

ds <- open_dataset('foo', format = 'csv')
ds |> collect()
```

This prints:

```R
# A tibble: 1 × 3
      a     b     c
  <int> <int> <int>
1     1     2     3
```

**Comment by larry77** [comment]
Yes, you are right. I had a buggy installation on my system.
