### ISSUE TITLE
[C++] Missing joinable check for thread in AsofJoinNode Destructor

### ISSUE THREAD

**Issue by mroz45** [apache/arrow#44526]
### Describe the bug, including details regarding any error messages, version, and platform.

In the destructor of the AsofJoinNode class, no check is performed to ensure that the process_thread_ is joinable before calling the join() method. This can lead to an std::system_error exception if the thread has not been initialized, which can happen if the creation of the plan fails.

### Component(s)

C++

**Comment by raulcd** [comment]
Here the code being mentioned for context:

https://github.com/apache/arrow/blob/802a84693b21847fc48efa2b29e23e0058256eeb/cpp/src/arrow/acero/asof_join_node.cc#L1136-L1141

CC @zanmato1984 @westonpace

**Comment by zanmato1984** [comment]
Hi @mroz45 , thanks for reporting this. Are you willing to submit a fix? And I can help to review. It's OK if not, then I'll take a look soon.

**Comment by mroz45** [comment]
Hi @zanmato1984, I am working on this, and I will add a PR soon. For now, I’m trying to create a test for this case.
