### ISSUE TITLE
Arrow TS Excessively Deep Type Instantiations

### ISSUE THREAD

**Issue by treyhakanson** [apache/arrow#4452]
Using the following versions of arrow and typescript:

- `@apache-arrow/ts`: 0.13.0
- `typescript`: 3.5.1

I get a slew of errors like the following on compilation:

```
ERROR in [at-loader] ../../node_modules/@apache-arrow/ts/vector/base.ts:69:16 
    TS2589: Type instantiation is excessively deep and possibly infinite.
```

I am new to Arrow and relatively new to Typescript, so please let me know any additional information that would be helpful and I am happy to provide. Thanks!

**Comment by wesm** [comment]
@trxcllnt @TheNeuralBit 

You may want to open a JIRA issues with description how to reproduce

**Comment by trxcllnt** [comment]
@treyhakanson yeah, this was a breaking change introduced by TS 3.4 or so. I've fixed this in the JS builder branch which should get a PR here shortly.

**Comment by treyhakanson** [comment]
@trxcllnt I'll downgrade my TS version for now and keep an eye on that branch. Thanks for the info!

**Comment by treyhakanson** [comment]
Downgrading to 3.2.4 did indeed solve the problem, closing 👍
