### ISSUE TITLE
[Java][FlightSQL] Native libraries are not properly relocated

### ISSUE THREAD

**Issue by laurentgo** [apache/arrow#44564]
### Describe the bug, including details regarding any error messages, version, and platform.

The netty native libraries shipped with the FlightSQL JDBC driver are relocated to avoid a conflict with existing libraries present in the classpath, but the relocation prefix is incorrect and prevent Netty to actually load them (or possibly load different libraries than the ones shipped with the driver)

Current prefix is `oaadj` but for Netty to correctly detect relocation prefix should match the one used by Netty `NativeLibaryLoader` class (with `.` replaced with `_` as explained at https://github.com/netty/netty/blob/047bdfe4860c077f5f4318742d6427d0f84c5c3a/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L138)

### Component(s)

Java

**Comment by lidavidm** [comment]
Issue resolved by pull request 44565
https://github.com/apache/arrow/pull/44565
