### ISSUE TITLE
[Release][Packaging] Verify version

### ISSUE THREAD

**Issue by kou** [apache/arrow#44578]
### Describe the enhancement requested

18.0.0 RC0's binaries didn't use `apache-arrow-18.0.0-rc0` commit. It used wrong commit https://github.com/apache/arrow/commit/d0e7d07dfdcbf5382932292e512d7b9013b29cb6 .

We can detect this problem in verification process by checking version too.
If we use wrong commit, binaries have `X.Y.Z-SNAPSHOT` not `X.Y.Z`. So we can detect wrong commit.

### Component(s)

Packaging, Release

**Comment by raulcd** [comment]
Issue resolved by pull request 44593
https://github.com/apache/arrow/pull/44593
