### ISSUE TITLE
[C++][Statistics] How to distinct "utf8" and "binary" in `arrow::ArrayStatistics`?

### ISSUE THREAD

**Issue by kou** [apache/arrow#44579]
### Describe the enhancement requested

We can represent "utf8" and "binary" min/max values by `arrow::ArrayStatistics`:

https://github.com/apache/arrow/blob/4c36f12524752779e682959c7a000a6554fcb784/cpp/src/arrow/array/statistics.h#L29-L67

But we can't distinct them because we use `std::string` in `ValueType` for both of them.

How can we distinct them? Should we add `arrow::ArrayStatistics::{min,max}_type`?

### Component(s)

C++

**Comment by pitrou** [comment]
Why would we want to distinguish them?

**Comment by kou** [comment]
I wanted this when I create an `arrow::DataType` for `arrow::ArrayStatistics`.
But I may use associated `arrow::Array` information for it. I'll try it.

**Comment by kou** [comment]
Issue resolved by pull request 45094
https://github.com/apache/arrow/pull/45094
