### ISSUE TITLE
[JS][Release] Wrong -.tar.gz name on arrow2csv fails when publishing

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44585]
### Describe the bug, including details regarding any error messages, version, and platform.

When publishing to npm the JavaScript implementation for 18.0.0 I saw the following error on one of the packages
```
npm notice === Tarball Contents === 
npm notice 248.2kB Arrow.js    
npm notice 23.4kB  arrow2csv.js
npm notice 13.3kB  arrow2csv.ts
npm notice 20B     package.json
npm notice === Tarball Details === 
npm notice name:                                                  
npm notice version:                                               
npm notice filename:      -.tgz                                   
npm notice package size:  66.6 kB                                 
npm notice unpacked size: 285.0 kB                                
npm notice shasum:        ac29699beca57a8c8a20fef88d9c3d2b83934dce
npm notice integrity:     sha512-2vcxFjK8cZ+Q5[...]/6uMhk+7VGK8Q==
npm notice total files:   4                                       
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm ERR! code EBADSEMVER
npm ERR! invalid semver: 
```
There seems to be a bad filename generated from the log `-.tgz` but I am unsure on what happens. In order to publish I run the script:
```
dev/release/post-07-js.sh 18.0.0
```
The version seems to be published sucessfully apart from this: https://www.npmjs.com/package/apache-arrow/v/18.0.0

### Component(s)

JavaScript, Release

**Comment by raulcd** [comment]
@domoritz @trxcllnt any idea what happened there?

**Comment by domoritz** [comment]
I don't know much about the publishing process. `npm ERR! invalid semver: ` seems to indicate that there is no version detected. The command looks right and I don't see anything off in the scripts either.

**Comment by raulcd** [comment]
To me the issue seems to be related to a wrongly generated filename and it fails because the version can't be detected: The filename generated seems to be `-.tgz`

**Comment by amoeba** [comment]
@kou kindly pointed this issue to me while I was working on the 18.1.0 post-release tasks so I haven't attempted to publish 18.1.0 to NPM yet.

I did a dry-run and was able to reproduce something similar to the above:

```
11 silly logfile start cleaning logs, removing 1 files
12 verbose publish [
12 verbose publish   '/Users/bryce/src/apache/arrow/apache-arrow-18.1.0/js/targets/ts/bin'
12 verbose publish ]
13 silly logfile done cleaning log files
14 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
15 warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
16 warn publish errors corrected:
16 warn publish Missing "name" field was set to an empty string
17 notice
18 notice 📦  @
19 notice Tarball Contents
20 notice 248.2kB Arrow.js
20 notice 23.4kB arrow2csv.js
20 notice 13.3kB arrow2csv.ts
20 notice 20B package.json
21 notice Tarball Details
22 notice name: 
23 notice version: 
24 notice filename: -.tgz
25 notice package size: 66.6 kB
26 notice unpacked size: 285.0 kB
27 notice shasum: ac29699beca57a8c8a20fef88d9c3d2b83934dce
28 notice integrity: sha512-2vcxFjK8cZ+Q5[...]/6uMhk+7VGK8Q==
29 notice total files: 4
30 notice
31 verbose stack Error: Invalid tag name "@latest" of package "@latest": Tags may not have any characters that encodeURIComponent encodes.
31 verbose stack     at invalidTagName (/opt/homebrew/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:118:15)
31 verbose stack     at fromRegistry (/opt/homebrew/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:410:13)
31 verbose stack     at resolve (/opt/homebrew/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:87:12)
31 verbose stack     at npa (/opt/homebrew/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:53:10)
31 verbose stack     at #publish (/opt/homebrew/lib/node_modules/npm/lib/commands/publish.js:128:5)
31 verbose stack     at async Publish.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/publish.js:46:5)
31 verbose stack     at async Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:207:9)
31 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:74:5)
32 error code EINVALIDTAGNAME
33 error Invalid tag name "@latest" of package "@latest": Tags may not have any characters that encodeURIComponent encodes.
```

Though it's interesting that the specific error is different. I'll have a look.

**Comment by amoeba** [comment]
I found this and am not sure if it's intentional that we have what is essentially an empty package.json in the targets/ts/bin folder:

```
~/src/apache/arrow/apache-arrow-18.1.0/js main*
.venv ❯ ls -1 targets/ts/bin
Arrow.js
arrow2csv.js*
arrow2csv.ts*
package.json

~/src/apache/arrow/apache-arrow-18.1.0/js main*
.venv ❯ cat targets/ts/bin/package.json
{"type": "commonjs"}⏎
```

The current iteration of the npm-publish.sh script catches this package.json and fails to publish it which makes sense.

**Comment by amoeba** [comment]
I see the gulpfile creates the problematic package.json file in https://github.com/apache/arrow/blob/891daaab257da4414b5b88313515df869bc7cdb0/js/gulp/arrow-task.js/#L70-L71. @domoritz do you know if that file is needed? If so, is it fine if we just update the publish script to skip it?

**Comment by domoritz** [comment]
It may be needed to mark the bin scripts as commonjs while the rest of the package is esm.

**Comment by amoeba** [comment]
That sounds reasonable. I'll update the publish script to skip over the bin folder and I think we can close this issue out with just that change. Thanks.

**Comment by amoeba** [comment]
I put a PR up to fix this, please see https://github.com/apache/arrow/pull/44861.

**Comment by amoeba** [comment]
Issue resolved by pull request 44861
https://github.com/apache/arrow/pull/44861
