### ISSUE TITLE
[GLib] Fix the wrong GARROW_AVAILABLE_IN declaration in GArrowDecimal64

### ISSUE THREAD

**Issue by hiroyuki-sato** [apache/arrow#44601]
### Describe the bug, including details regarding any error messages, version, and platform.

This part should be `GARROW_AVAILABLE_IN_19_0`

Wrong
https://github.com/apache/arrow/blob/e1fa7e5fb257fa9f83ffcc531efda8a4489b2961/c_glib/arrow-glib/decimal.h#L109-L110

Correct
```
GARROW_AVAILABLE_IN_19_0
G_DECLARE_DERIVABLE_TYPE(GArrowDecimal64, garrow_decimal64, GARROW, DECIMAL64, GObject)
```

### Component(s)

GLib

**Comment by kou** [comment]
Issue resolved by pull request 44602
https://github.com/apache/arrow/pull/44602
