### ISSUE TITLE
[C++] Thrift mirrors are outdated

### ISSUE THREAD

**Issue by assignUser** [apache/arrow#44607]
Some observations:

- downloads.apache.org only has archives of Thrift 0.20.0 and 0.21.0 (current latest stable is 0.21.0)
- Apache appears to now (since 2021?) [have a CDN](https://apache.org/history/mirror-history.html): https://dlcdn.apache.org/thrift/. That also only has archives of 0.20.0 and 0.21.0.

https://apache.org/history/mirror-history.html gives more context and this sentence may explain why this list of URLs degraded over time:

> Any organization that has been hosting an Apache download mirror site, and that finds it useful for its own purposes, may continue to host the mirror site. 

So I think by continuing to use these mirror URLs we were living on borrowed time. The CDN is now the recommended way for users to download content from ASF projects.

So I think we actually need to do two things here:

- [x] Change the URL to just use the ASF CDN
- [x] Update our Thrift version in cpp/thirdparty/versions.txt to 0.20.0 or greater. Arrow C++ builds cleanly on my system when using Brew-provided Thrift 0.21.0 so it seems like this may be doable.

_Originally posted by @amoeba in https://github.com/apache/arrow/issues/44523#issuecomment-2450105564_

**Comment by amoeba** [comment]
For extra context here, we originally found this in [this CI job](https://github.com/ursacomputing/crossbow/actions/runs/11604567800/job/32313529273) as part of pre-submission testing in https://github.com/apache/arrow/pull/44523.

**Comment by amoeba** [comment]
Issue resolved by pull request 44685
https://github.com/apache/arrow/pull/44685

**Comment by amoeba** [comment]
Note for posterity: We opted not to upgrade all the way to Thrift 0.21.0 here because Thrift 0.21.0 requires an upgrade to Boost 1.86.0 and that version of Boost shipped a buggy bcp which we use in `cpp/build-support/trim-boost.sh` to repackage Boost. We can upgrade Thrift and Boost once a fixed Boost release has been published.
