### ISSUE TITLE
[Archery] Suppress pull/push progress logs

### ISSUE THREAD

**Issue by kou** [apache/arrow#44667]
### Describe the enhancement requested

They are useless and noisy in CI log.

For example: https://github.com/ursacomputing/crossbow/actions/runs/11712683518/job/32623909860#step:7:55

```text
 53  DEBUG:archery:Executing `['docker', 'compose', '--file=/home/runner/work/crossbow/crossbow/arrow/docker-compose.yml', 'pull', '--ignore-pull-failures', 'python-wheel-manylinux-2014']`
 54   python-wheel-manylinux-2014 Pulling 
 55   2d473b07cdd5 Pulling fs layer 
...
802   8e8a019736ff Extracting [==================================================>]  52.55MB/52.55MB
803   8e8a019736ff Pull complete 
804   python-wheel-manylinux-2014 Pulled 
```

### Component(s)

Archery

**Comment by assignUser** [comment]
Issue resolved by pull request 44669
https://github.com/apache/arrow/pull/44669

**Comment by pitrou** [comment]
I just noticed this change. Can this be reverted, or at least made optional? When running locally it is quite annoying to wait for minutes without being informed.

**Comment by pitrou** [comment]
By the way, Archery has a `--quiet` flag already, why not use its value?

**Comment by pitrou** [comment]
Followup PR in https://github.com/apache/arrow/pull/44850

**Comment by kou** [comment]
It's odd to me to reuse `--quiet` to suppress only progress logs. In general, `--quiet` suppresses all outputs.

**Comment by pitrou** [comment]
Would you rather a separate option, `archery docker --no-progress` perhaps?

**Comment by kou** [comment]
Yes. It's better than `--quiet`.
