### ISSUE TITLE
[R] R CMD check failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [apache/arrow#44674]
### Describe the bug, including details regarding any error messages, version, and platform.

Five arrow tests fail with the dev version of testthat:

```R
── Failure ('test-Array.R:1264:3'): concat_arrays works ────────────────────────
all(concat_int == arrow_array(1:5)) is not TRUE

`actual` is an R6 object of class <Scalar/ArrowDatum/ArrowObject>
`expected` is a logical vector (TRUE)
── Failure ('test-Array.R:1272:3'): concat_arrays works ────────────────────────
all(concat_int == arrow_array(1:5)) is not TRUE

`actual` is an R6 object of class <Scalar/ArrowDatum/ArrowObject>
`expected` is a logical vector (TRUE)
── Failure ('test-Array.R:1286:3'): concat_arrays() coerces its input to Array ──
all(concat_ints == arrow_array(c(1L, 2L))) is not TRUE

`actual` is an R6 object of class <Scalar/ArrowDatum/ArrowObject>
`expected` is a logical vector (TRUE)
── Failure ('test-extension.R:38:3'): extension types can be created ───────────
all(array$storage() == storage) is not TRUE

`actual` is an R6 object of class <Scalar/ArrowDatum/ArrowObject>
`expected` is a logical vector (TRUE)
── Failure ('test-parquet.R:458:3'): deprecated int96 timestamp unit can be specified when reading Parquet files ──
result$some_datetime == table$some_datetime is not TRUE

`actual` is an R6 object of class <ChunkedArray/ArrowDatum/ArrowObject>
`expected` is a logical vector (TRUE)
```

This is because `expect_true()` no longer coerces it's input to a vector (which was arguably  a bug in the first place).

### Component(s)

R

**Comment by amoeba** [comment]
Thanks @hadley. I put up a PR to fix this, https://github.com/apache/arrow/pull/44675, and put this issue in the [18.1.0 milestone](https://github.com/apache/arrow/milestone/67) so it'll get included in our upcoming submission to CRAN.

**Comment by hadley** [comment]
Awesome, thanks! I'm planning to submit to CRAN on Nov 11, and you'll then have three weeks to get a fix to CRAN. Is that enough time for y'all?

**Comment by amoeba** [comment]
I think so. We've already done the prep work for our next CRAN submission so, while we'll have to re-run it all once more, I think we can do it all within that timeline. Thanks for checking.

**Comment by amoeba** [comment]
Issue resolved by pull request 44675
https://github.com/apache/arrow/pull/44675
