### ISSUE TITLE
[FlightRPC][C++] Precision of `arrow.flight.Timestamp` is OS-dependent

### ISSUE THREAD

**Issue by EnricoMi** [apache/arrow#44679]
### Describe the bug, including details regarding any error messages, version, and platform.

The precision of is supposed to be nanoseconds precision:
https://github.com/apache/arrow/blob/093655c60783321c786a8e69632f185d37520f4d/cpp/src/arrow/flight/types.h#L77

Actually, the current precision of `arrow.flight.Timestamp` not nanoseconds on most operation systems:
https://github.com/apache/arrow/blob/093655c60783321c786a8e69632f185d37520f4d/cpp/src/arrow/flight/types.h#L83
The precision of `std::chrono::system_clock::time_point` is
- microseconds for macOS
- 100 nanoseconds for Windows
- nanoseconds for Linux

https://github.com/apache/arrow/blob/093655c60783321c786a8e69632f185d37520f4d/cpp/src/arrow/flight/flight_internals_test.cc#L187-L192

In order to be OS-agnostic, the timestamp resolution should be nanoseconds everywhere.

In Python, the equivalent type `TimePoint` is correctly defined with nanoseconds precision for any OS:
https://github.com/apache/arrow/blob/093655c60783321c786a8e69632f185d37520f4d/python/pyarrow/src/arrow/python/datetime.h#L88-L89

### Component(s)

C++

**Comment by lidavidm** [comment]
Issue resolved by pull request 44681
https://github.com/apache/arrow/pull/44681
