### ISSUE TITLE
Header files missing if build directory includes "internal" anywhere in the path.

### ISSUE THREAD

**Issue by pulver** [apache/arrow#4469]
The following logic incorrectly omits header files from `PUBLIC_HEADERS` if the build directory has a parent directory that includes "internal" as a substring.
```
  foreach(HEADER ${CURRENT_DIRECTORY_HEADERS})
    if(NOT ((HEADER MATCHES "internal")))
      list(APPEND PUBLIC_HEADERS ${HEADER})
    endif()
  endforeach()
```
https://github.com/apache/arrow/blob/b6123a84d1bd40ed7fbe86a474c6b1c30f7e4b0e/cpp/cmake_modules/BuildUtils.cmake#L701

For example, if the arrow package is built in a subdirectory of `project-foo-internal` then header files are missing from the build.

**Comment by wesm** [comment]
Can you please open a JIRA issue about this bug?

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-5517
