### ISSUE TITLE
[Java] maven arrow-memory Could not find

### ISSUE THREAD

**Issue by pap25** [apache/arrow#44708]
### Describe the usage question you have. Please include as many useful details as  possible.

Cannot resolve org.apache.arrow:arrow-memory:18.0.0

### Component(s)

Java

**Comment by kou** [comment]
How did you do? How to reproduce your problem?

**Comment by raulcd** [comment]
@pap25 thanks for opening the issue. Unfortunately without more details we can't do anything about it. I will close the issue, please feel free to add more details on how to reproduce and the full error log and re-open the issue if necessary.
