### ISSUE TITLE
[C++][Parquet] Remove obsolete generated files

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44700]
### Describe the enhancement requested

When bumping Thrift to v0.19.0, it seems we left two obsolete files in the repository: `src/generated/parquet_constants.h` and `src/generated/parquet_constants.cpp` (both are marked as "Autogenerated by Thrift Compiler (0.13.0)").

### Component(s)

C++, Parquet

**Comment by kou** [comment]
Issue resolved by pull request 44772
https://github.com/apache/arrow/pull/44772
