### ISSUE TITLE
[CI][MATLAB][Packaging] Update MATLAB CI and `crossbow` packaging workflows to build against MATLAB `R2024b`

### ISSUE THREAD

**Issue by kevingurney** [apache/arrow#44703]
### Describe the enhancement requested

MATLAB [R2024b](https://www.mathworks.com/products/new_products/latest_features.html) is now available for use with the [`matlab-actions/setup-matlab`](https://github.com/matlab-actions/setup-matlab) GitHub Action.

We should update the [`matlab.yml` CI workflow](https://github.com/apache/arrow/blob/aab7d81aeec1e8f106bdda953cdeb00f7f78b355/.github/workflows/matlab.yml#L126), as well as the [`crossbow` packaging workflows for the MATLAB MLTBX files](https://github.com/apache/arrow/blob/aab7d81aeec1e8f106bdda953cdeb00f7f78b355/dev/tasks/matlab/github.yml#L34) to build against `R2024b`.

### Component(s)

Continuous Integration, MATLAB, Packaging

**Comment by kou** [comment]
Issue resolved by pull request 44704
https://github.com/apache/arrow/pull/44704
