### ISSUE TITLE
[Docs][Python] Add missing canonical extension types to PyArrow arrays and datatypes docs

### ISSUE THREAD

**Issue by ianmcook** [apache/arrow#44711]
### Describe the bug, including details regarding any error messages, version, and platform.

Some of the canonical extension types which are implemented in PyArrow are missing from the PyArrow arrays and datatypes docs pages. For example, Opaque is there, but JSON, UUID, and Bool8 are missing.

The docs pages with the missing entries:
https://arrow.apache.org/docs/dev/python/api/arrays.html
https://arrow.apache.org/docs/dev/python/api/datatypes.html

The RST sources for those pages:
https://github.com/apache/arrow/blob/main/docs/source/python/api/arrays.rst
https://github.com/apache/arrow/blob/main/docs/source/python/api/datatypes.rst

You can look through the associated PXI files to check what's missing:
https://github.com/apache/arrow/blob/main/python/pyarrow/array.pxi
https://github.com/apache/arrow/blob/main/python/pyarrow/types.pxi

### Component(s)

Documentation, Python

**Comment by ianmcook** [comment]
Thanks @msebbah! Please comment here with the word "take" and the GitHub bot will assign this issue to you.

**Comment by msebbah** [comment]
take ! thanks @ianmcook

**Comment by ianmcook** [comment]
Closed by #44880
