### ISSUE TITLE
[C++][CI] arrow-c-bridge-test times out on threading-disabled CI job

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44734]
### Describe the bug, including details regarding any error messages, version, and platform.

See https://github.com/ursacomputing/crossbow/actions/runs/11840159979/job/32993317218

Also timing out on the emscripten CI job: https://github.com/ursacomputing/crossbow/actions/runs/11840159052/job/32993313329

This might be related to the Async Device Stream Interface?

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
@zeroshade Can you take a look at this?

**Comment by zeroshade** [comment]
The Async Device Stream tests absolutely rely on threading being enabled due to locks and handling. I assume we have a macro for checking whether threading is enabled so I can disable the test if threading is disabled?

**Comment by pitrou** [comment]
Yes, there's probably a macro somewhere :-) @kou knows more about it.

**Comment by pitrou** [comment]
Issue resolved by pull request 44737
https://github.com/apache/arrow/pull/44737
