### ISSUE TITLE
[C++] Upgrade ORC to 2.0.3

### ISSUE THREAD

**Issue by dongjoon-hyun** [apache/arrow#44744]
### Describe the enhancement requested

- https://orc.apache.org/news/2024/08/15/ORC-2.0.2/
  - https://github.com/apache/orc/pull/1963
  - https://github.com/apache/orc/pull/1997
  - https://github.com/apache/orc/issues/1981
- https://orc.apache.org/news/2024/11/14/ORC-2.0.3/
  - https://github.com/apache/orc/pull/2055

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 44745
https://github.com/apache/arrow/pull/44745
