### ISSUE TITLE
[C++] Float16.{ToBytes,FromBytes} fail on big-endian machines

### ISSUE THREAD

**Issue by QuLogic** [apache/arrow#44767]
### Describe the bug, including details regarding any error messages, version, and platform.

The above named tests fail in the following way:
```
[ RUN      ] Float16Test.ToBytes
/builddir/build/BUILD/libarrow-16.1.0-build/apache-arrow-16.1.0/cpp/src/arrow/util/float16_test.cc:332: Failure
Expected equality of these values:
  load()
    Which is: 7376
  0xd01c
    Which is: 53276

[  FAILED  ] Float16Test.ToBytes (0 ms)
[ RUN      ] Float16Test.FromBytes
/builddir/build/BUILD/libarrow-16.1.0-build/apache-arrow-16.1.0/cpp/src/arrow/util/float16_test.cc:361: Failure
Expected equality of these values:
  Float16::FromLittleEndian(data)
    Which is: 0.00469971
  Float16(0x1cd0)
    Which is: 7376

[  FAILED  ] Float16Test.FromBytes (0 ms)
```
The [tests themselves](https://github.com/apache/arrow/blob/4c2aef7b231f129db7b3bdb232c6da00542ba7b3/cpp/src/arrow/util/float16_test.cc#L323-L364) look suspicious to me, as they start with a "native" check, but use a fixed byte order.

### Component(s)

C++

**Comment by pitrou** [comment]
Issue resolved by pull request 44768
https://github.com/apache/arrow/pull/44768
