### ISSUE TITLE
[C++][CI] example-cpp-tutorial fails because of deprecated APIs

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44802]
### Describe the bug, including details regarding any error messages, version, and platform.

The `example-cpp-tutorial` Crossbow night build now fails because it's using some deprecated APIs.
https://github.com/ursacomputing/crossbow/actions/runs/11944262092/job/33294899404

It should certainly be easy to migrate the tested example(s) to non-deprecated APIs, and is therefore a good task for someone wanting to start on Arrow C++ development (or even perhaps general C++ development).

### Component(s)

C++, Continuous Integration

**Comment by pitrou** [comment]
@raulcd @assignUser

**Comment by malinjawi** [comment]
hey @pitrou I am new to arrow. Will try to check this issue out. Look forward to learning about this project and getting a fix in for this.

**Comment by pitrou** [comment]
@malinjawi So, if you look at the link I gave you above, you can easily reproduce the error locally if you have the Docker client installed, and run these commands:
```console
$ cd arrow/cpp/examples/tutorial_examples
$ docker compose run --rm tutorial
```

**Comment by raulcd** [comment]
@malinjawi btw this was the PR that introduced the change that has to be updated on the tutorial examples:
- https://github.com/apache/arrow/pull/44785

**Comment by kou** [comment]
Oh, sorry.

I should have updated the file too...

**Comment by kou** [comment]
Issue resolved by pull request 44807
https://github.com/apache/arrow/pull/44807
