### ISSUE TITLE
[Dev] Add top-level `.editorconfig` for C++, Python...

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44805]
### Describe the enhancement requested

See https://editorconfig.org/

Some languages such as Python, C++, bash... are used in various parts of our repository, a top-level `.editorconfig` would help maintain a consistent style at least for the basics (such as indentation).

### Component(s)

C++, Developer Tools, Python

**Comment by kou** [comment]
We should check our style by `pre-commit` even if we have `.editorconfig`.

**Comment by pitrou** [comment]
The EditorConfig spec is [extremely basic](https://spec.editorconfig.org/#supported-pairs) for now, it mostly only covers indentation and line endings. But it would help working on multiple projects with different indentation settings.

**Comment by assignUser** [comment]
It seems pretty unintrusive and useful :+1:

**Comment by pitrou** [comment]
Issue resolved by pull request 44870
https://github.com/apache/arrow/pull/44870
