### ISSUE TITLE
[R][CI] Nightly job failures with `Failed to install qpdf`

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44841]
### Describe the bug, including details regarding any error messages, version, and platform.

Some nightly jobs are failing to set up R on macOS using the ` r-lib/actions/setup-r@v2` action:
```
Error: Failed to get R release: Failed to get R 4.4.2: Failed to install qpdf: Error: The process '/opt/homebrew/bin/brew' failed with exit code 1
```
See:
- [test-r-devdocs](https://github.com/ursacomputing/crossbow/actions/runs/12001035945/job/33450983249)
- [test-r-install-local](https://github.com/ursacomputing/crossbow/actions/runs/12001035849/job/33450981253)
- [test-r-install-local-minsizerel](https://github.com/ursacomputing/crossbow/actions/runs/12001035605/job/33450980353)
- [test-r-macos-as-cran](https://github.com/ursacomputing/crossbow/actions/runs/12001035247/job/33450977546)

### Component(s)

Continuous Integration, R

**Comment by raulcd** [comment]
@jonkeane @assignUser FYI

**Comment by jonkeane** [comment]
Thanks for this! I've seen this same issue elsewhere and IIUC there's a mismatch / error in homebrew on the macos runner that's causing it. Runner image 20241119.509 has the issue, and runner image 20241022.361 fixes it. I'll take this issue on to monitor it — but I believe it will resolve itself in a few days, however long it takes for GHA runner images to percolate.

**Comment by assignUser** [comment]
Looks like they are currently deploying a new image 🤞 that you are right Jon! 
![grafik](https://github.com/user-attachments/assets/8dc5d2c8-a4c0-46f5-873d-e65ba8411321)

**Comment by assignUser** [comment]
The image is deployed and did indeed fix this issue!
