### ISSUE TITLE
[CI] pkgconfig failures on CI for nightlies

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44844]
### Describe the bug, including details regarding any error messages, version, and platform.

Same issue as in: https://github.com/apache/arrow/issues/44820

For some verification jobs:
- [verify-rc-source-cpp-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/11996300891/job/33440575768)
- [verify-rc-source-csharp-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/11996301008/job/33440576528)
- [verify-rc-source-integration-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/11996300854/job/33440575432)
- [verify-rc-source-js-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/11996300825/job/33440575254)
- [verify-rc-source-python-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/11996300945/job/33440575980)
- [verify-rc-source-ruby-macos-amd64](https://github.com/ursacomputing/crossbow/actions/runs/11996300880/job/33440575651)
- [verify-rc-source-ruby-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/11996300767/job/33440575120)

and
- [java-jars](https://github.com/ursacomputing/crossbow/actions/runs/11994603352/job/33437316110)

```
==> Pouring pkgconf--2.3.0_1.arm64_sonoma.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
  brew unlink pkg-config@0.29.2

To force the link and overwrite all conflicting files:
  brew link --overwrite pkgconf

To list all files that would be deleted:
  brew link --overwrite pkgconf --dry-run

Possible conflicting files are:
/opt/homebrew/bin/pkg-config -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/bin/pkg-config
/opt/homebrew/share/aclocal/pkg.m4 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/aclocal/pkg.m4
/opt/homebrew/share/man/man1/pkg-config.1 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/man/man1/pkg-config.1
==> Summary
```

### Component(s)

Continuous Integration

**Comment by kou** [comment]
Issue resolved by pull request 44845
https://github.com/apache/arrow/pull/44845
