### ISSUE TITLE
[Java][Docs] Remove Java documentation from this repo

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#44843]
### Describe the enhancement requested

IMO, we should move the Java documentation to arrow-java so it can follow the right release process. I would also like to submit for consideration the sphinx-javadoc bridge used by ADBC, which allows treating Javadoc as an Intersphinx mapping (so you don't have to hardcode links in the Sphinx source to reference Javadocs): https://github.com/apache/arrow-adbc/blob/main/docs/source/ext/doxygen_inventory.py

### Component(s)

Documentation, Java

**Comment by lidavidm** [comment]
@kou should I transfer this to arrow-java too? I suppose we can keep this to remove the existing docs from this repo?

**Comment by kou** [comment]
I think that the latter is better.
Let's create a new issue for preparing the Java documentation in apache/arrow-java.

**Comment by raulcd** [comment]
The `AMD64 Debian 12 Complete Documentation` job currently fails with:
```
 + rm -rf /build/java
+ cp -aL /arrow/java /build/
cp: cannot stat '/arrow/java': No such file or directory
Error: `docker compose --file=/home/runner/work/arrow/arrow/docker-compose.yml run --rm debian-docs` exited with a non-zero exit code 1, see the process log above.
```
See example: https://github.com/apache/arrow/actions/runs/12273365665/job/34243998087

**Comment by raulcd** [comment]
I've opened an issue on `arrow-java`:
- https://github.com/apache/arrow-java/issues/455

**Comment by kou** [comment]
Issue resolved by pull request 45000
https://github.com/apache/arrow/pull/45000
