### ISSUE TITLE
[Docs] "Go" link is broken in docs

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#44842]
### Describe the bug, including details regarding any error messages, version, and platform.

This:

![image](https://github.com/user-attachments/assets/09927523-a1ea-43f5-aa13-1997be14deb0)

Links to https://arrow.apache.org/go/ which is a broken link.

### Component(s)

Documentation

**Comment by kou** [comment]
Ah, we should work on this in apache/arrow-go.
I've opened an issue for this: https://github.com/apache/arrow-go/issues/202

**Comment by lidavidm** [comment]
Thanks! I'll close this
