### ISSUE TITLE
Consider shading the flatbuffers dependency (java)

### ISSUE THREAD

**Issue by alexnixon** [apache/arrow#4489]
Hi,

Just a heads up here :-

After some [discussion](https://github.com/google/flatbuffers/issues/5368) with the Flatbuffers maintainer, it appears that FB generated code is not guaranteed to be compatible with _any other_ version of the runtime library other than the exact same version of the flatc used to compile it.

This makes depending on flatbuffers in a library (like arrow) quite risky, as if an app depends on any other version of FB, either directly or transitively, it's likely the versions will clash at some point and you'll see undefined behaviour at runtime.

Shading the dependency looks to me the best way to avoid this.

**Comment by xhochy** [comment]
@alexnixon can you open a JIRA about that?

**Comment by wesm** [comment]
Can you someone from Java-side open a JIRA issue? cc @pravindra @emkornfield @siddharthteotia

**Comment by pravindra** [comment]
https://issues.apache.org/jira/browse/ARROW-5579
