### ISSUE TITLE
[C++] Compile error in arrow\cpp\src\arrow\util\utf8_internal.h with MSVC arm64 compiler

### ISSUE THREAD

**Issue by NEIL-smtg** [apache/arrow#44896]
### Describe the bug, including details regarding any error messages, version, and platform.

Recently, I encountered a few errors while building Arrow with the MSVC arm64 compiler:
```
C:\gitP\apache\arrow\cpp\src\arrow\util\utf8_internal.h(242,29): error C2039: 'make_sized_batch_t': is not a member of 'xsimd' [C:\gitP\apache\arrow\cpp\build_arm64\src\arrow\arrow_util_static.vcxproj]
         (compiling source file '../../../src/arrow/util/utf8.cc')
             C:\gitP\apache\arrow\cpp\build_arm64\xsimd_ep\src\xsimd_ep-install\include\xsimd\memory\xsimd_aligned_allocator.hpp(29,11):
             see declaration of 'xsimd'
C:\gitP\apache\arrow\cpp\src\arrow\util\utf8_internal.h(242,29): error C2061: syntax error: identifier 'make_sized_batch_t' [C:\gitP\apache\arrow\cpp\build_arm64\src\arrow\arrow_util_static.vcxproj]
         (compiling source file '../../../src/arrow/util/utf8.cc')
...
```

This issue appears to occur only when using the arm64 compiler, as the code compiles without issues with arm64ec.

Build log: [arr.txt](https://github.com/user-attachments/files/17975510/arr.txt)

Repro steps:

1. Open x64 Native tools command prompt for VS 2022
2. `set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64`
3. `git clone https://github.com/apache/arrow.git`
4. `mkdir apache\arrow\cpp\build_arm64 & cd apache\arrow\cpp\build_arm64`
5. `set _CL_=/DUSE_SOFT_INTRINSICS %_CL_%`
6. `cmake -G "Visual Studio 17 2022" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0  -DARROW_BUILD_TESTS=OFF .. 2>&1`
7. `msbuild /m /p:Platform=arm64 /p:Configuration=Release arrow.sln /t:Rebuild 2>&1`

As a workaround, I have been predefining the following flags before building the project: `/D _M_AMD64  /DUSE_SOFT_INTRINSICS /D__INTRIN_H_`

### Component(s)

C++

**Comment by assignUser** [comment]
Thanks for the report!

This seems more like an xsimd issue than an arrow issue as it happens in the xsimd external project: `C:\gitP\apache\arrow\cpp\build_arm64\xsimd_ep\src\xsimd_ep-install\include\xsimd\memory\xsimd_aligned_allocator.hpp(29,11): see declaration of 'xsimd'`

But good to hear that you have a workaround!

**Comment by kou** [comment]
Right.
You need to set some variables manually for cross-compiling.

**Comment by NEIL-smtg** [comment]
Hi guys, I have tried creating a toolchain file and setting these 2 variables, but I'm still encountering the same issue. 
```
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR arm64)
```

Build log: [arr.txt](https://github.com/user-attachments/files/17986747/arr.txt)

**Comment by cyb70289** [comment]
From below log, looks `-march=armv8-a` is appended to compiler flags, even for msvc.
Guess we need a different option for msvc cross build, [/arch:armv8.0](https://learn.microsoft.com/en-us/cpp/build/reference/arch-arm64?view=msvc-170)?
```
-- CMAKE_C_FLAGS: /DWIN32 /D_WINDOWS  /EHsc /wd5105 /bigobj /utf-8 /W3 /wd4800 /wd4996 /wd4065 -march=armv8-a 
-- CMAKE_CXX_FLAGS:  /DWIN32 /D_WINDOWS /GR /EHsc /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING  /EHsc /wd5105 /bigobj /utf-8 /W3 /wd4800 /wd4996 /wd4065 -march=armv8-a 
```

Related code at:
https://github.com/apache/arrow/blob/main/cpp/cmake_modules/SetupCxxFlags.cmake#L125-L126
https://github.com/apache/arrow/blob/main/cpp/cmake_modules/SetupCxxFlags.cmake#L543

**Comment by kou** [comment]
We can't use MSVC for Windows/ARM64 yet...: https://arrow.apache.org/docs/developers/cpp/windows.html#building-on-windows-arm64-using-ninja-and-clang

**Comment by NEIL-smtg** [comment]
Ah I see, I'll go ahead to close this issue then.
