### ISSUE TITLE
[Dev] Remove JIRA remnants

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44934]
### Describe the enhancement requested

There is still some JIRA related code present that could be removed from our codebase.
Mainly around:
- PRs and issue workflows
- Merge script
- Release scripts on archery

We should remove it.

### Component(s)

Archery, Developer Tools, Documentation

**Comment by assignUser** [comment]
Issue resolved by pull request 44936
https://github.com/apache/arrow/pull/44936
