### ISSUE TITLE
[R] Source package install not using precompiled libarrow binaries

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#44931]
### Describe the bug, including details regarding any error messages, version, and platform.

While testing the latest (18.1.0) arrow CRAN submission, I noticed the prebuilt libarrow binaries aren't being used. I'm not sure if this has been an issue for more than just this release yet.

How I can reproduce this:

```sh
git checkout maint-18.1.0-r
cd r
make build
ARROW_R_DEV=TRUE R CMD INSTALL arrow_18.1.0.tar.gz
* installing to library ‘/home/bryce/R/aarch64-unknown-linux-gnu-library/4.4’
* installing *source* package ‘arrow’ ...
** using staged installation
*** pkg-config found.
trying URL 'https://apache.jfrog.io/artifactory/arrow/r/'
downloaded 1284 bytes

*** Building on linux aarch64
*** Found local C++ source: 'tools/cpp'
*** Building libarrow from source
    For build options and troubleshooting, see the install guide:
    https://arrow.apache.org/docs/r/articles/install.html
*** Building with MAKEFLAGS=-j2
```

I think it would be good while fixing the issue to improve the print logging if we can.

cc @assignUser 

### Component(s)

R

**Comment by assignUser** [comment]
>  on linux aarch64

We don't have Linux arm64 pre-built binaries, so non could be downloaded. Also if you are on Debian it would also built from source.

**Comment by amoeba** [comment]
I think you've told me either one or both of those things in the past, sorry about that. In the R release guide, we have an instruction,

> - [ ] Check install.packages("arrow_X.X.X.tar.gz") on Ubuntu and ensure that the hosted binaries are used

Is that just a very out of date instruction?

**Comment by assignUser** [comment]
That assumes amd64, we should add that. Ubuntu is allow listed for binaries, Debian is not (because cran runs Debian).
