### ISSUE TITLE
[Dev][Archery] Remove JIRA remnants from archery

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44948]
### Describe the enhancement requested

This is a follow up from:
- https://github.com/apache/arrow/issues/44934

To remove the related JIRA code from archery.

### Component(s)

Archery, Developer Tools, Documentation

### Component(s)

Archery, Developer Tools

**Comment by kou** [comment]
Issue resolved by pull request 45091
https://github.com/apache/arrow/pull/45091
