### ISSUE TITLE
[Java] Remove java/

### ISSUE THREAD

**Issue by kou** [apache/arrow#44945]
### Describe the enhancement requested

We're moving `java/` to https://github.com/apache/arrow-java .

### Component(s)

Java

**Comment by lidavidm** [comment]
I am doing this in https://github.com/apache/arrow/pull/44932. I can try to split it out.

**Comment by kou** [comment]
I think that we need GH-44829 before this. I'll do it.

**Comment by kou** [comment]
Done. Could you work on this.

**Comment by raulcd** [comment]
:partying_face:
