### ISSUE TITLE
404 when installing apache-arrow on npm (Solved)

### ISSUE THREAD

**Issue by giovannefeitosa** [apache/arrow#44964]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi, I was working with apache arrow in node and yesterday it was working well, today I decided to start using npm workspaces so I could share my arrow schemas on different projects, however I can't install apache arrow anymore, could you please take a look?

![image](https://github.com/user-attachments/assets/197fe40d-6ba2-46b5-840f-50854cd261e0)

Error 404:

- [https://www.npmjs.com/package/apache-arrow](https://www.npmjs.com/package/apache-arrow)

---

As I was writing this issue and gathering proofs, I noticed that the response of `https://registry.npmjs.org/apache-arrow` changed from not-found (in json format) to an actual json object, so I tried installing again and it's working, the page above (screenshot) also came back to work.

![image](https://github.com/user-attachments/assets/23a64dfe-e6e3-41ac-97eb-69dc570ec799)

I guess in a Sunday afternoon we can expect something like this to happen, I'll post anyway because I found nothing about online and a post like this could have saved me some time.

Have a nice day, feel free to close this issue.

### Component(s)

JavaScript, Packaging

**Comment by raulcd** [comment]
Hi @giovannefeitosa thanks for reporting the issue. This seem like the npm website had some issues more than a specific Arrow issue.
I'll be closing this issue if you are ok with that. Thanks for notifying us of this upstream issues.
