### ISSUE TITLE
[C++] CMake fixes and improvements

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#44976]
### Describe the enhancement requested

1. Since mimalloc has [become the default allocator](https://github.com/apache/arrow/issues/43254) instead of jemalloc, mimalloc should be enabled by default, and jemalloc disabled by default.
2. compute-specific files should only be compiled when compute is enabled.

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 44951
https://github.com/apache/arrow/pull/44951
