### ISSUE TITLE
[CI][Java][Python] Integration spark jobs are failing due to missing java folder

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44980]
### Describe the bug, including details regarding any error messages, version, and platform.

The Spark integration jobs were using the Java implementation to build spark against. They are currently failing with:
```
 Removed build tracker: '/tmp/pip-build-tracker-_6u01r9l'
+ popd
+ '[' OFF == ON ']'
/
/arrow/ci/scripts/integration_spark.sh: line 36: pushd: /arrow/java: No such file or directory
```
This should be investigated and fixed. I am unsure whether this should be moved to the arrow-java implementation.

### Component(s)

Continuous Integration, Java, Python

**Comment by raulcd** [comment]
@kou it seems we removed spark being built with latest Java arrow here: https://github.com/apache/arrow/pull/44946 but we missed to remove the version retrieval.
Do we want to add a job to build spark against Arrow Java main? This job should potentially live in `arrow-java`

**Comment by kou** [comment]
Oh, sorry.
I missed this case.

I've opened an issue on apache/arrow-java: https://github.com/apache/arrow-java/issues/451
