### ISSUE TITLE
[CI] Documentation job fails due to missing java folder

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#44998]
### Describe the bug, including details regarding any error messages, version, and platform.

The `AMD64 Debian 12 Complete Documentation` job fails with:
```
 + rm -rf /build/java
+ cp -aL /arrow/java /build/
cp: cannot stat '/arrow/java': No such file or directory
Error: `docker compose --file=/home/runner/work/arrow/arrow/docker-compose.yml run --rm debian-docs` exited with a non-zero exit code 1, see the process log above.
```
See example: https://github.com/apache/arrow/actions/runs/12273365665/job/34243998087

### Component(s)

Continuous Integration

**Comment by raulcd** [comment]
Do we want to continue building java docs on this repo? We probably should move the Java reference (javadoc) to be generated on the arrow-java repository:
```
if [ "${BUILD_DOCS_JAVA}" == "ON" ]; then
  # HTTP pooling is turned of to avoid download issues https://issues.apache.org/jira/browse/ARROW-11633
  # GH-43378: Maven site plugins not compatible with multithreading
  mkdir -p ${build_dir}/docs/java/reference
  ${mvn} -Dcheckstyle.skip=true -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false clean install site
  rsync -a target/site/apidocs/ ${build_dir}/docs/java/reference
fi
```
@lidavidm @kou what are your thoughts about this?

**Comment by lidavidm** [comment]
https://github.com/apache/arrow/issues/44843

**Comment by raulcd** [comment]
Thanks, I'll close it as a duplicate but I'll add there that the current jobs are failing.
