### ISSUE TITLE
[C++] Add Fixed-Size List Support in Apache Arrow STL Conversion Traits

### ISSUE THREAD

**Issue by mroz45** [apache/arrow#45005]
### Describe the enhancement requested

Conversion of a range of std::tuple objects can be converted into Arrow Tables. However, while Arrow supports several standard C++ data types for this conversion, it lacks direct support for fixed-size lists.  At present, Arrow supports Lists via std::vector, but there is no implementation for fixed-size lists(std::array), which are often used in scenarios where size is predetermined for performance or structural reasons.

### Component(s)

C++

**Comment by zanmato1984** [comment]
Issue resolved by pull request 45008
https://github.com/apache/arrow/pull/45008
