### ISSUE TITLE
[C++] Include path in the documentation is wrong

### ISSUE THREAD

**Issue by avitase** [apache/arrow#45027]
### Describe the bug, including details regarding any error messages, version, and platform.

On my machine the include path for parquet is `parquet/arrow/...` and not `arrow/parquet/arrow/...`. This looks like a copy & paste bug from the line above:

https://github.com/apache/arrow/blob/313d11aa94c2be71142b55e3d8bb166d780c19c7/cpp/examples/arrow/parquet_read_write.cc#L29

https://github.com/apache/arrow/blob/313d11aa94c2be71142b55e3d8bb166d780c19c7/cpp/examples/arrow/parquet_read_write.cc#L47

### Component(s)

C++

**Comment by kou** [comment]
Good catch!
Could you open a PR that fixes this?

**Comment by avitase** [comment]
@kou, see https://github.com/apache/arrow/pull/45031

**Comment by kou** [comment]
Issue resolved by pull request 45031
https://github.com/apache/arrow/pull/45031
