### ISSUE TITLE
[Python][C++] pyarrow does not build without parquet

### ISSUE THREAD

**Issue by atupone** [apache/arrow#45034]
### Describe the bug, including details regarding any error messages, version, and platform.

see https://bugs.gentoo.org/944828

When building apache-arrow without parquet, the ParquetTargets.cmake file is not deployed.
But there are still trace of Parquet in ArrowDatasetConfig.cmake and ArrowAceroConfig.cmake

That causes pyarrow cmake to fail, as ParquetTargets.cmake is searched even if it not needed

This happen in version 18.1.0 and 18.0.0, on linux/gentoo amd64

### Component(s)

C++

**Comment by raulcd** [comment]
I was trying to understand if this is something that was added on 18.0.0 but it seems that this is something that wasn't possible in the past either.

**Comment by atupone** [comment]
I was able to build without Parquest commenting the Parquet line in ArrowDatasetConfig.cmake.in and ArrowAceroConfig.cmake.in. Just an hack, though.

**Comment by raulcd** [comment]
Thanks for the input there. Acero should never require parquet currently. Dataset on the other hand should require it if we've build with PARQUET enabled.

**Comment by kou** [comment]
Issue resolved by pull request 45035
https://github.com/apache/arrow/pull/45035
