### ISSUE TITLE
[CI][Python][Packaging] Test 3.12 wheels on Ubuntu 24.04

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#45047]
### Describe the enhancement requested

We already test some Python wheels on Ubuntu 20.04 or 22.04, depending on the system Python version. We should also do so with Ubuntu 24.04.

### Component(s)

Continuous Integration, Packaging, Python

**Comment by kou** [comment]
Issue resolved by pull request 45042
https://github.com/apache/arrow/pull/45042
