### ISSUE TITLE
[CI][Packaging][Python] wheel builds compile a bundled ORC

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#45041]
### Describe the bug, including details regarding any error messages, version, and platform.

It looks like our Python wheel builds do not fetch ORC from vcpkg but compile it during Arrow C++ build instead.

### Component(s)

Continuous Integration, Packaging, Python

**Comment by pitrou** [comment]
cc @raulcd

**Comment by kou** [comment]
Issue resolved by pull request 45046
https://github.com/apache/arrow/pull/45046
