### ISSUE TITLE
[R][CI] Fix r-binary-packages crossbow job. Failing with command not found.

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#45069]
### Describe the bug, including details regarding any error messages, version, and platform.

The `r-binary-packages` Crossbow job has been failing for two days, see https://github.com/ursacomputing/crossbow/actions/runs/12389231735/job/34581897456.  The error I see is:

```
2024-12-18T20:05:12.3044821Z /home/runner/work/_temp/06fe760a-c943-4688-9574-e0c09d65af8d.sh: line 4: R: command not found
2024-12-18T20:05:12.3057529Z ##[error]Process completed with exit code 127.
```

I haven't thoroughly checked yet but I think it may be related to `ubuntu-latest` migrating from Ubuntu 22.04 to 24.04. The [22.04 image includes R ](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)while [the 24.04 image does not](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md).

I think the fix here will be to let the rlib/setup-r workflow install R.

### Component(s)

Continuous Integration, R

**Comment by kou** [comment]
Issue resolved by pull request 45070
https://github.com/apache/arrow/pull/45070
