### ISSUE TITLE
[FligRPC][C++] Deprecate UCX prior to removal

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#45079]
### Describe the enhancement requested

As a first step to remove UCX:
- https://github.com/apache/arrow/issues/43296

We should deprecate it. This PR is to track the deprecation.

Some of the initial discussion can be followed here: https://github.com/apache/arrow/pull/43297#issuecomment-2550810967

### Component(s)

C++, FlightRPC

**Comment by kou** [comment]
Issue resolved by pull request 45080
https://github.com/apache/arrow/pull/45080
