### ISSUE TITLE
[CI][Packaging][Python] Simplify dev/tasks/python-wheels/github.linux.yml

### ISSUE THREAD

**Issue by kou** [apache/arrow#45076]
### Describe the enhancement requested

This is a follow-up task of #45040.

We can simplify the #45040 implementation by using GitHub Actions' standard features.

See also: https://github.com/apache/arrow/pull/45040#discussion_r1889203170

### Component(s)

Continuous Integration, Packaging, Python

**Comment by raulcd** [comment]
Issue resolved by pull request 45077
https://github.com/apache/arrow/pull/45077
