### ISSUE TITLE
[Packaging][Docs] Pyodide builds have incorrect NumPy 2.0 header location and assume `pyodide-build` to be the same version as Pyodide

### ISSUE THREAD

**Issue by agriyakhetarpal** [apache/arrow#45071]
### Describe the bug, including details regarding any error messages, version, and platform.

Hi there, we're trying to build PyArrow against NumPy v2 as a part of pyodide/pyodide#4925 and we are targeting an imminent 0.27 release soon after. I've opened this issue to put to light, that:
- the Pyodide builds are against NumPy 1.X right now, but building against 2.X has a problem because the NumPy headers were moved from `numpy/core/include` to `numpy/_core/include/`:

	https://github.com/apache/arrow/blob/b655852b260d3b8c3fe457795df0f42a2ff9c98c/python/CMakeLists.txt#L163-L177

- the documentation mentions in a few places that the version of `pyodide-build` must match the Pyodide version – this is no longer the case, since, we have [unvendored `pyodide-build` to a separate repository](https://github.com/pyodide/pyodide-build) and now [maintain a list of compatible versions against Pyodide](https://raw.githubusercontent.com/pyodide/pyodide/main/pyodide-cross-build-environments.json).
- the Pyodide and Emscripten versions are slightly out of date in a few places

I already have a pull request coming for addressing these changes, but since this was also concerning CI/packaging and not just documentation, the Contributing guide suggested that I should open an issue first before opening a pull request.

Thanks for your time!

### Component(s)

Python

**Comment by kou** [comment]
Issue resolved by pull request 45072
https://github.com/apache/arrow/pull/45072
