### ISSUE TITLE
[C++] Remove arrow/result_internal.h

### ISSUE THREAD

**Issue by wgtmac** [apache/arrow#45075]
### Describe the enhancement requested

The result_internal.h file contains only the definition of `ASSIGN_OR_RAISE` and thus can be removed because `ARROW_ASSIGN_OR_RAISE` is preferred over `ASSIGN_OR_RAISE`.

### Component(s)

C++

**Comment by kou** [comment]
Issue resolved by pull request 45066
https://github.com/apache/arrow/pull/45066
