### ISSUE TITLE
[JS] RangeError: byte length of Uint32Array should be a multiple of 4

### ISSUE THREAD

**Issue by MRYingLEE** [apache/arrow#45115]
### Describe the bug, including details regarding any error messages, version, and platform.

```javascript
import { RecordBatchJSONWriter } from 'apache-arrow';

const source = arrow_table3;// arrow_table3 is an Apache Arrow table
const writer = RecordBatchJSONWriter.writeAll(source);
const string = writer.toString();
const json = JSON.parse(string) ;
console.log(json);
```
met an error

```
status: error
ename: RangeError
evalue: byte length of Uint32Array should be a multiple of 4
traceback: RangeError: byte length of Uint32Array should be a multiple of 4
    at new Uint32Array (<anonymous>)
    at sl (https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:185468)
    at sl.next (<anonymous>)
    at nl.visitTimestamp (https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:184567)
    at nl.visit (https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:51431)
    at nl.visit (https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:183834)
    at https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:51356
    at Array.map (<anonymous>)
    at nl.visitMany (https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:51339)
    at https://cdn.jsdelivr.net/npm/apache-arrow/+esm:7:183475
```

### Component(s)

JavaScript

**Comment by kou** [comment]
Could you also provide a data that reproduces this problem?

**Comment by MRYingLEE** [comment]
Based on 
[homicides.csv](https://github.com/user-attachments/files/18273020/homicides.csv)

The arrow_table3 was generated for monthly frequency, which has the following rows:

date	count
0	2015-01-31	29
1	2015-02-28	20
2	2015-03-31	34
3	2015-04-30	36
4	2015-05-31	48
5	2015-06-30	49
6	2015-07-31	56
7	2015-08-31	54
8	2015-09-30	64
9	2015-10-31	32
10	2015-11-30	37
11	2015-12-31	33

Sorry I just couldn't reproduce the issue again for I did not store the accurate code of creating arrow_table3.
