### ISSUE TITLE
[Ruby] Building an array of hashes from Table is very slow

### ISSUE THREAD

**Issue by fpacanowski** [apache/arrow#45117]
I'm experiencing performance issues when reading Parquet files in Ruby. I've created a very simple synthetic benchmark: a table with a single `float` column and 1,000,000 rows. I want to read this data into an array of hashes. Here's my code:
```ruby
require 'arrow'
require 'parquet'
require 'benchmark'

def read_parquet
  table = Arrow::TableLoader.load('data.parquet', { format: :parquet })
  table.each_record(reuse_record: true).map(&:to_h)
end

Benchmark.bmbm do |x|
  x.report("read_parquet")  { read_parquet }
end
```
And the report:
```
$ bundle exec ruby --yjit read.rb
Rehearsal ------------------------------------------------
read_parquet  20.894371   0.129733  21.024104 ( 21.066472)
-------------------------------------- total: 21.024104sec

                   user     system      total        real
read_parquet  21.872816   0.079736  21.952552 ( 21.991875)
```

I also tested equivalent code in Python:
```python
import pyarrow.parquet as pq
import timeit

def read_parquet():
    table = pq.read_table('data.parquet')
    return table.to_pylist()

time_taken = timeit.timeit(read_parquet, number=10)  # Run 10 times
print(f"Average time: {time_taken / 10:.6f} seconds")
```
which yields:
```
$ poetry run python read.py
Average time: 0.610864 seconds
```

It seems that Ruby version is **30-40x** slower than pyarrow. Is there anything I can do to improve the performance here?

For completeness, here's a script that generates the test data (`data.parquet` file):
```ruby
require 'arrow'
require 'parquet'
require 'benchmark'

schema = Arrow::Schema.new([Arrow::Field.new("foo", :float)])

data = 1_000_000.times.map { {foo: rand} }
table = Arrow::RecordBatchBuilder.build(schema, data).to_table
table.save('data.parquet', format: :parquet, compression: :uncompressed)
```

### Component(s)

Ruby

**Comment by kou** [comment]
In general, you should not convert large data to raw Ruby objects. It's slow as you seen.

But Red Arrow provides an optimized feature that converts an Arrow array to a Ruby array. You can use it by `arrow::XXXArray#to_a`.

For example, you can get a `Hash` of `Array`s (not an `Array` of `Hash`es) with the feature:

```ruby
def read_parquet
  table = Arrow::TableLoader.load('data.parquet', { format: :parquet })
  data = {}
  table.schema.fields.each do |field|
    data[field.name] = []
  end
  table.each_record_batch do |record_batch|
    record_batch.each_column do |column|
      data[column.name].concat(column.data.to_a)
    end
  end
  data
end
```

Are you really need an `Array` of `Hash`es?

**Comment by fpacanowski** [comment]
Thank you! Based on your advice I came up with this alternative implementation:
```ruby
def read_parquet2
  table = Arrow::TableLoader.load('data.parquet', { format: :parquet })
  result = []
  table.each_record_batch do |record_batch|
    result.concat(record_batch['foo'].data.to_a.map { {foo: _1} })
  end
  result
end
```
Obviously this implementation is specialized to this particular schema. But it's orders of magnitude faster (even faster than pyarrow).
```
$ bundle exec ruby --yjit read.rb
Rehearsal -------------------------------------------------
read_parquet   17.731458   0.070106  17.801564 ( 17.830338)
read_parquet2   0.218525   0.019901   0.238426 (  0.239175)
--------------------------------------- total: 18.039990sec

                    user     system      total        real
read_parquet   21.314701   0.113192  21.427893 ( 21.462763)
read_parquet2   0.169205   0.013307   0.182512 (  0.183047)
```

> In general, you should not convert large data to raw Ruby objects. It's slow as you seen.

I'm aware there's a certain overhead to converting data to Ruby objects. But it seems to me it's not the bottleneck - certainly creating a million Hashes doesn't take ~20 seconds. When I looked at the code of `Record#to_h`, I realized calling `.to_h` on each record separately in my original implementation caused repeatedly fetching the whole column.
```ruby
# record.rb

def to_h
  attributes = {}
  @container.columns.each do |column|
    attributes[column.name] = column[@index]
  end
  attributes
end
```

> Are you really need an Array of Hashes?

In my use case I want to load data from Parquet file into a database. So I need an Array of Hashes because this is what ActiveRecord's [insert_all](https://apidock.com/rails/v7.0.0/ActiveRecord/Persistence/ClassMethods/insert_all) accepts. I think it would be nice to provide a built-in method for doing this in an optimized way. I filed a separate feature request: https://github.com/apache/arrow/issues/45122.

**Comment by kou** [comment]
For the use case, I recommend that you use ADBC: https://arrow.apache.org/adbc/

You can use Apache Arrow data to load them to a database. ADBC converts the given Apache Arrow data internally with optimized implementation.

I want to implement Active Record ADBC adapter but it's not completed yet...: https://github.com/red-data-tools/activerecord-adbc-adapter
