### ISSUE TITLE
[gandiva] Error when projector with a string field

### ISSUE THREAD

**Issue by buaasun** [apache/arrow#4544]
when I try to select a string field by `gandiva` projector, it failed with errors.

```python 
import pandas as pd
import pyarrow as pa
from pyarrow import gandiva

a = pd.DataFrame({'col1': ["asdf", "abc"]})
tb = pa.Table.from_pandas(a)
teb = gandiva.TreeExprBuilder()
col1 = tb.schema[0]
node1 = teb.make_field(col1)
exp1 = teb.make_expression(node1, col1)
gandiva.make_projector(tb.schema, [exp1], pa.default_memory_pool())

```
Run the code above, it crashs with error like this:
``
python: ../lib/IR/Instructions.cpp:1202: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
Aborted
``

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by buaasun** [comment]
@wesm see https://issues.apache.org/jira/browse/ARROW-5601

**Comment by praveenbingo** [comment]
Replied on the same.
