### ISSUE TITLE
RecordBatch with Tensors / Arrays

### ISSUE THREAD

**Issue by spott** [apache/arrow#4552]
I'm looking to serialize data that looks something like this:

```
record<n1> = { "predicted": <tensor with shape n1, m>,
                          "truth": <tensor with shape n1, m>,
                          "loss": <double>,
                          "index": <array with shape n1>}

data = [
    pa.array([record<n1>, record<n2>, record<n3>]),
    pa.array([<float>, <float>, <float>])
    pa.array([<float>, <float>, <float>])
]

batch = pa.RecordBatch.from_arrays(data, ['f0', 'f1', 'f2'])
```

But I'm not sure how to do that, or even if what I'm trying to do is the right way to do it.

What is the difference between `pa.array` and `pa.list_`?  This formulation is an array of structs, but is the struct of arrays formulation of this possible? i.e.:

```
data = [
    pa.array([ <tensor with shape n1, m>,  <tensor with shape n2, m>,  <tensor with shape n3, m>]),
    pa.array([ <tensor with shape n1, m>,  <tensor with shape n2, m>,  <tensor with shape n3, m>]),
    pa.array([<float>, <float>, <float>]),
...
]
```

Which doesn't currently work.  It seems that there is a separation between '1d arraylike' datatypes and 'pythonlike' datatypes (and 'nd arraylike' datatypes), so I can't have a struct of an array.

**Comment by wesm** [comment]
Can you write an email to dev@arrow.apache.org or user@arrow.apache.org about this?

**Comment by spott** [comment]
I sent it to user@arrow.apache.org.  Sorry for the noise.

**Comment by wesm** [comment]
Are you subscribed to that list? I don't see it yet

**Comment by spott** [comment]
I am not subscribed, do I need to be?

**Comment by wesm** [comment]
Yes, you have to subscribe in order to post

**Comment by spott** [comment]
I have subscribed and resent the email.

**Comment by spott** [comment]
This can be closed if my email made it to the users list.

**Comment by wesm** [comment]
I don't see it here https://lists.apache.org/list.html?user@arrow.apache.org. You have to e-mail user-subscribe@arrow.apache.org and then reply to the e-mail that you receive from the mail server
