### ISSUE TITLE
[JAVA] ARROW-FLIGHT CANNOT SEND listvector

### ISSUE THREAD

**Issue by liaotian1005** [apache/arrow#4620]
In a very special and simple environment, the native api can send listvector, but in the flihgt framework, it cannot be sent at all. If the listvector cannot be transmitted on the network, what does this arrow data structure mean. It does not support the list of complex types.

**Comment by wesm** [comment]
@liaotian1005 can you please open a JIRA issue and show a minimal reproduction of the issue you are seeing? Since Flight uses the Arrow IPC binary protocol, it should have no issue sending ListVector

**Comment by liaotian1005** [comment]
> @liaotian1005 can you please open a JIRA issue and show a minimal reproduction of the issue you are seeing? Since Flight uses the Arrow IPC binary protocol, it should have no issue sending ListVector

https://issues.apache.org/jira/browse/ARROW-5658 


Hello, I believe it was tested to make sure it was released without problems, but I was having problems using it, unable to send listvector packets, including using the native API, and only in the special case, only for simpler The scene can be sent, the actual scene is not so simple, I described the problems encountered, showing the relevant code, thank you!

**Comment by liaotian1005** [comment]
> @liaotian1005 can you please open a JIRA issue and show a minimal reproduction of the issue you are seeing? Since Flight uses the Arrow IPC binary protocol, it should have no issue sending ListVector

https://issues.apache.org/jira/browse/ARROW-5658

Hello, I believe it was tested to make sure it was released without problems, but I was having problems using it, unable to send listvector packets, including using the native API, and only in the special case, only for simpler The scene can be sent, the actual scene is not so simple, I described the problems encountered, showing the relevant code, thank you!
