### ISSUE TITLE
Can't import pyarrow 0.14.0 due to mismatching libcrypt

### ISSUE THREAD

**Issue by suvayu** [apache/arrow#4818]
*I have tried posting to the dev list, but my email seems to be not going through, since I'm not sure if it's something I'm doing wrong, I opened this issue instead of a JIRA.*

## Problem description

In a freshly created virtual environment, after I install pyarrow 0.14.0 (using pip), importing pyarrow from the python prompt leads to the following:

    $ python3 -m pyarrow
    Traceback (most recent call last):
      File "/usr/lib64/python3.7/runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/lib64/python3.7/runpy.py", line 142, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "/usr/lib64/python3.7/runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "/home/suvayuali/.virtualenvs/pa-0.14.0/lib/python3.7/site-packages/pyarrow/__init__.py", line 49, in <module>
        from pyarrow.lib import cpu_count, set_cpu_count
    ImportError: libcrypt.so.1: cannot open shared object file: No such file or directory

## Comments

This is surprising because I have older versions of pyarrow (up to 0.13.0) working, and libcrypt on my system (Fedora 30, Python 3.7) is libcrypt.so.2!

Am I missing something?

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by wesm** [comment]
Also, you need to be subscribed to the email list to post to it, so that may be your issue.

**Comment by suvayu** [comment]
@wesm I'm subscribed, I have posted to the list before.

I'll open a JIRA issue.

**Comment by suvayu** [comment]
Here's the issue on JIRA: https://issues.apache.org/jira/browse/ARROW-5871
