### ISSUE TITLE
Limit number of threads when converting feather of arrow table to pandas dataframe.

### ISSUE THREAD

**Issue by ghuls** [apache/arrow#4912]
It would be nice if the number of threads could be specified when converting feather of arrow table to a pandas dataframe.

Now it is only possible to pass  `use_threads=True`, or `use_threads=False` to `to_pandas()`, but not for example 4:`use_threads=4`.

On servers with 36 cores, `use_threads=True` is only twice as fast as `use_threads=False`, so I assume too many threads make things slower than using only 4 threads.

**Comment by wesm** [comment]
This is configurable globally with `pa.set_cpu_count`

https://github.com/apache/arrow/blob/74b9294bf63ff49818f2d6a72877139a1a540f60/python/pyarrow/lib.pyx#L60

**Comment by ghuls** [comment]
@wesm Is there something similar for the R package of arrow?

I can see `SetCpuThreadPoolCapacity` in https://github.com/apache/arrow/blob/master/r/src/arrowExports.cpp, but I can't figure out how to access it.
