### ISSUE TITLE
Error on Flight example

### ISSUE THREAD

**Issue by RedTailedHawk** [apache/arrow#4955]
Getting an error running the following:

`python -m grpc_tools.protoc -I./src/main/protobuf/ --python_out=./target/generated-python --grpc_python_out=./target/generated-python src/main/protobuf/flight.proto`

>>src/main/protobuf/flight.proto: No such file or directory

I can create the `protobuf` directory, but what needs to be in the `flight.proto` file?

**Comment by RedTailedHawk** [comment]
FYI, following the notes here:

https://github.com/apache/arrow/blob/master/java/flight/README.md

**Comment by wesm** [comment]
We moved the file to https://github.com/apache/arrow/blob/master/format/Flight.proto. The documentation is out of date

https://github.com/apache/arrow/blob/master/java/flight/README.md

https://issues.apache.org/jira/browse/ARROW-6050

**Comment by RedTailedHawk** [comment]
Thanks, I copied the file into `src/main/protobuf` and now I get further in Python.

```import grpc
import flight_pb2
import flight_pb2_grpc as flightrpc
channel = grpc.insecure_channel('localhost:12233')
service = flightrpc.FlightServiceStub(channel)```

But this line doesn't do anything:

`for f in service.ListFlights(flight_pb2.Criteria()): f`

**Comment by wesm** [comment]
You have to do `print(f)` in Python. I suggest we discuss further on dev@arrow.apache.org or user@arrow.apache.org
