### ISSUE TITLE
Missing artifact io.netty:netty-transport-native-unix-common:jar

### ISSUE THREAD

**Issue by RedTailedHawk** [apache/arrow#4961]
I added a dependency to my project's `pom.xml` file for arrow-flight:

    <dependency>
      <groupId>org.apache.arrow</groupId>
      <artifactId>arrow-flight</artifactId>
      <version>0.14.1</version>
    </dependency>

But I'm getting an error in my IDE (Eclipse):

`Missing artifact io.netty:netty-transport-native-unix-common:jar:${os.detected.name}-${os.detected.arch}:4.1.27.Final	pom.xml`

Is there something else I need to add?

Thanks.

**Comment by wesm** [comment]
This isn't the right place to open issues. Can you write to dev@arrow.apache.org or user@arrow.apache.org?
