### ISSUE TITLE
cant install on linux

### ISSUE THREAD

**Issue by randomgambit** [apache/arrow#5048]
Hello there! 

This R port of arrows is great news!

I am on linux and I tried to install arrow (for R).
Right now, I need to install the c++ library which I am not familiar with. Any hopes that the R package will contain all that is needed soon? That is, without the need to run some external command lines?

Thanks!

**Comment by wesm** [comment]
See http://arrow.apache.org/install/

If you are using a different Linux distribution please follow source build instructions

http://arrow.apache.org/docs/developers/cpp.html

**Comment by wesm** [comment]
If you require other assistance please write to user@arrow.apache.org
