### ISSUE TITLE
Broken Project & Product names Using "Apache Arrow" PR link ⋙

### ISSUE THREAD

**Issue by RandomFractals** [apache/arrow#5156]
on your site page: 

https://arrow.apache.org/powered_by/

Your PR suggestion links to: https://github.com/apache/arrow/edit/master/site/powered_by.md

under Projects Powered By Apache Arrow section.

What's Jira?

Thank you!

**Comment by nealrichardson** [comment]
Thanks for the report. We'll fix. 

See http://arrow.apache.org/docs/developers/contributing.html about Jira and other pointers.

**Comment by RandomFractals** [comment]
ok! you do that! thx for the pointers :)
