### ISSUE TITLE
pyarrow: Should csv_read take StringIO?

### ISSUE THREAD

**Issue by ARF1** [apache/arrow#5226]
I am trying to read an XML that was converted into an in-memory CSV into pyarrow:
```
pyarrow.csv.read_csv(
    StringIO(str(result)),
    parse_options=pyarrow.csv.ParseOptions(delimiter='|'),
)
```

The documentation suggests, a file-like object as source should be permissible. However, the code fails with:
```
SystemError                               Traceback (most recent call last)
 in 
      1 pyarrow.csv.read_csv(
      2     StringIO(str(result)),
----> 3     parse_options=pyarrow.csv.ParseOptions(delimiter='|'),
      4 )
      5 

SystemError:  returned NULL without setting an error
```

Is this a bug or am I attempting something that is not permitted?

Dumping the CSV to disk and specifying its filename works perfectly fine.

**Comment by wesm** [comment]
Can you open a JIRA issue? Looks like a bug to me

**Comment by ARF1** [comment]
@wesm Many thanks for your feedback. After investigating further I realized that I was using pyarrow version 0.11.x. With version 0.14.x this is no longer an issue. - Closing this issue.
