### ISSUE TITLE
C# Fluent API Support for Writing Nullable Primitives

### ISSUE THREAD

**Issue by abbotware** [apache/arrow#5381]
The fluent API for writing files does not support writing nulls.

The fact that **Nullable** is an option to the **Builder.Append** function is very misleading since due to the implementation, its impossible to supply a null value (except for strings / datetime since they are reference types)

The assumption that all primitives are non-nullable is a incorrect since the underlying FlatBuffers spec supports null, it should be supported from top to bottom.

I looked at the code and there are many `struct `constraints that would make this a complicated task rather than a simple minor change. It will require Bifurcating many of the `ArrayBuilder` helper methods used in the Column builder.  

However, once done it should be possible to create `Builder.AppendNullable(name, Func<NullableArrayBuilder, T>)`  where `AppendRange` would take `List<T?>` instead of `List<T>`

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by wesm** [comment]
@eerhardt @chutchinson would one of you mind opening a JIRA issue about this if you agree so we can close this? We try to keep the "Issues" tab at 0 at all times

**Comment by eerhardt** [comment]
I've opened https://issues.apache.org/jira/browse/ARROW-6603 for this. Note we also have https://issues.apache.org/jira/browse/ARROW-5708, which is for supporting `null` in BooleanArrays all together, not just in the builder classes.

It is currently possible to write `null` values with the C# API, you just have to drop lower than the Fluent API and use ArrowBuffer.Builder directly. Example that sets elements `50` and `75` to `null`:

```C#
            int arrayLength = 100;
            ArrowBuffer.Builder<int> dataBuilder = new ArrowBuffer.Builder<int>(arrayLength);
            for (int i = 0; i < arrayLength; i++)
            {
                dataBuilder.Append(i);
            }
            int numberOfBytes = arrayLength / 8;
            ArrowBuffer.Builder<byte> nullBuilder = new ArrowBuffer.Builder<byte>(numberOfBytes);
            for (int i = 0; i < numberOfBytes; i++)
            {
                nullBuilder.Append(0xff);
            }
            BitUtility.ClearBit(nullBuilder.Span, 50);
            BitUtility.ClearBit(nullBuilder.Span, 75);
            var array = new Int32Array(
                dataBuilder.Build(),
                nullBuilder.Build(),
                length: arrayLength,
                nullCount: 2,
                offset: 0);
```
