### ISSUE TITLE
JS: How to convert a negative big decimal (Uint32Array(4)) to String?

### ISSUE THREAD

**Issue by zad** [apache/arrow#5397]
https://github.com/apache/arrow/blob/d54425de19b7dbb2764a40355d76d1c785cf64ec/js/src/util/bn.ts#L99

This function does not handle negative cases If I understand correctly!

**Comment by wesm** [comment]
Can you open a JIRA issue if you can provide a reproduction of the problem?

**Comment by zad** [comment]
It is obvious to find that the function does not return "-" minus sign in any case. But I'll try to reproduce it and create a JIRA. Thanks!

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-6627
