### ISSUE TITLE
[Rust] Filtering Arrays and Request for More Examples.

### ISSUE THREAD

**Issue by rustacian** [apache/arrow#5400]
@andygrove thank you for contributing the Rust implementation. I'm currently looking over the CSV example, and it's not quite clear how to manipulate the columns that have been read. In particular, I'd like to apply a matching filter (find all values >= X). If possible, could you add examples on simple array operations?

**Comment by rustacian** [comment]
What I am thinking, is I might want to build a `BooleanArray`, and apply `arrow::compute::array_ops::filter` to the original column + the mask array.

**Comment by wesm** [comment]
Can you open a JIRA issue?

**Comment by rustacian** [comment]
Sure.

**Comment by rustacian** [comment]
@wesm Opened a JIRA ticket https://issues.apache.org/jira/browse/ARROW-6583. Please look at your convenience.

Secondly, Is JIRA an appropriate avenue for questions? I hesitated to open a ticket there initially because I did not strictly have a feature request, just a general usage question. Should I post to the mailing list instead?

**Comment by wesm** [comment]
The mailing list is more appropriate for usage questions. If you're proposing to add more documentation then this can go on JIRA since that will usually lead to a patch
