### ISSUE TITLE
[Java] Interleaving DictionaryBatch and RecordBatch messages in a stream.

### ISSUE THREAD

**Issue by randomboolean** [apache/arrow#5527]
In the IPC [specification](https://arrow.apache.org/docs/format/IPC.html), it is written that "DictionaryBatch and RecordBatch messages may be interleaved".

However, when looking at Java code, it seems to me that both [org.apache.arrow.vector.ipc.ArrowWriter](https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowWriter.java) and [org.apache.arrow.vector.ipc.ArrowReader](https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/ipc/ArrowReader.java) only allows for having DictionaryBatch messages at the beginning of the stream.

Is the Java implementation lacking this feature or do I miss something?

**Comment by emkornfield** [comment]
This is a bug in the Java implementation.  

There are also some other ambiguities that we've discussed on the mailing list [[1](https://lists.apache.org/thread.html/9734b71bc12aca16eb997388e95105bff412fdaefa4e19422f477389@%3Cdev.arrow.apache.org%3E)][[2](https://lists.apache.org/thread.html/c9031c3697f322810a7a419b7f10b2310ec5d1039c4674af933cdb83@%3Cdev.arrow.apache.org%3E)] that need clarification.

**Comment by randomboolean** [comment]
Thanks for your answer. I've found the related Jira issue [ARROW-6308](https://issues.apache.org/jira/browse/ARROW-6308?jql=project%20%3D%20ARROW%20AND%20component%20%3D%20Java%20AND%20text%20~%20%22dictionary%22).
