### ISSUE TITLE
[pyarrow]: sample for performing aggregation on arrow table using gandiva in pyarrow

### ISSUE THREAD

**Issue by joetl** [apache/arrow#5532]
Can I get a sample to perform aggregation on arrow table in pyarrow using gandiva. Like sum(x) group by y order by z

**Comment by emkornfield** [comment]
As far as I know Gandiva does provide group by or order by functionality. It is focused on expression evaluation (things that appear in the select statement)

**Comment by emkornfield** [comment]
Cc @pravindra

**Comment by pravindra** [comment]
gandiva does not support group-by/order-by functionality currently. It's limited to projection/filter use cases.

**Comment by joetl** [comment]
I am seeing cpp files for aggregate, sum, mean, aggregate in compute sub-module of arrow cop implementation.. 

https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/aggregate.cc
https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/sum.cc

**Comment by wesm** [comment]
Let's move the discussion either to JIRA or dev@arrow.apache.org. 

A number of developers are interested in implementing hash aggregations in C++ but the work is not done yet.
