### ISSUE TITLE
Building Plasma for Java

### ISSUE THREAD

**Issue by yogeshtewari** [apache/arrow#5575]
Hi,

While running test.sh from java/plasma, I am not able to resolve this error.

```
[ 99%] Linking CXX shared library ../../release/libplasma_java.so
.
.
.
/usr/bin/ld: cannot find -lflatbuffers::flatbuffers
/usr/bin/ld: cannot find -lflatbuffers::flatbuffers
collect2: error: ld returned 1 exit status
src/plasma/CMakeFiles/plasma_java.dir/build.make:98: recipe for target 'release/libplasma_java.so' failed
make[2]: *** [release/libplasma_java.so] Error 1
```

I have followed steps mentioned here (https://arrow.apache.org/install/) for my OS (Ubuntu 16.04). I have downloaded flatbuffer code and did the usual cmake builds, I have even tried `cpp/build-support/` for flatbuffer. But the am not able to link the flatbuffers libraries for plasma.

Any guidance on how to build and use plasma with java is greatly appreciated.

Cheers,
Yogesh

**Comment by emkornfield** [comment]
If you are building off of master I don't think flatbuffers is an external dependency any more so this specific problem shouldn't be an issue.  If you are still having problems please email the dev@arrow mailing list and include the exact CMake command you are running.

**Comment by wesm** [comment]
`flatbuffers::flatbuffers` is still referenced in the build. I don't think this component is build in any of our CI or nightly builds so someone will have to address that

https://issues.apache.org/jira/browse/ARROW-6799
