### ISSUE TITLE
Parquet C++ version

### ISSUE THREAD

**Issue by YucanLiu** [apache/arrow#5619]
Hi team, 

From the code, I saw the parquet cpp version is "1.5.1 snapshot". Is it the same series of version with Java parquet library version? We are facing some issues that a parquet is not able to be read into our system by using Parquet Cpp from Arrow lib. I checked the schema / metadata of those files, and found that they are build with 1.5.1+ (something like 1.10.1).

I assume that those files are exported from Spark or some other software that used higher version java parquet library, but I'm not 100% sure. Could you please confirm? If so, is there a mapping between the parquet cpp version and parquet java version? Do we have any plan to update the parquet cpp lib? Also, in the current scenario, do we have a way to read those files?

Best.

**Comment by wesm** [comment]
The version numbers for the Java and C++ libraries are not related to each other. If you are unable to read a file produced by the C++ library, or you cannot read a file produced in Java in C++, please open a JIRA issue with any information to help reproduce so we can help.
