### ISSUE TITLE
[Javascript apache-arrow] How to get a table from Json object? 

### ISSUE THREAD

**Issue by sdyalor** [apache/arrow#5637]
I couldn't find an example to how to create a table fron a Javascript object or json response. 
There is a good one from
pyarrow https://towardsdatascience.com/a-gentle-introduction-to-apache-arrow-with-apache-spark-and-pandas-bb19ffe0ddae
but is for python with pandas. 

From the example, He first creates a DataFrame Type then load that type to ArrowTable to create a Table. 

How can I achive this in Javascript cuz there is no numpy, pandas here :'c

**Comment by emkornfield** [comment]
@sdyalor I'm not sure if this functionality exists in the javascript implementation.  CC @TheNeuralBit @trxcllnt

**Comment by TheNeuralBit** [comment]
Unfortunately I don't think there's an easy button for this, but you can do it with the builders that Paul added. He put together an example of reading CSV into arrow by first converting to an array of JSON dictionary: https://github.com/trxcllnt/csv-to-arrow-js

**Comment by wesm** [comment]
It'd be useful to have some helper functions in JavaScript. I'm going to close this, but feel free to open some JIRA issues proposing new features to add
