### ISSUE TITLE
[Javascript] How to load Json to a Table?

### ISSUE THREAD

**Issue by sdyalor** [apache/arrow#5664]
Hi, everyone
I want to create a Table from an api fetch 
There is this example with python https://arrow.apache.org/docs/python/json.html
But dont know how to do in javascript since weak documentation ;'c
Maybe I can use JSONDataLoader but there is no examples or details on https://arrow.apache.org/docs/js/classes/jsondataloader.html

Need help here please

**Comment by emkornfield** [comment]
This seem identical to #5637?  If you have questions please ask on user@arrow or dev@arrow mailing for help and directions.  Some more specific questions on what you've tried that hasn't work would probably be more likely get answers.
