### ISSUE TITLE
C++ and Java Parquet Writer V2

### ISSUE THREAD

**Issue by YucanLiu** [apache/arrow#5667]
Hi, I hope this is the right place to ask. 

We are using parquet C++ library. However, we found that we have issues to load the parquet files that are written by `ParquetProperties.WriterVersion.PARQUET_2_0` from Java lib. For the same data, if we use `ParquetProperties.WriterVersion.PARQUET_1_0`, the parquet file can be loaded into our system without any issue. However, if we use `ParquetProperties.WriterVersion.PARQUET_2_0` to write the file, an error about compression will be raised, and the file is not loadable. 

We do find the [Jira](https://issues.apache.org/jira/browse/PARQUET-458) here. But can you confirm that V2 is not recommended in production by the community yet? If it's the case, is it only restricted to Parquet C++ library? The parquet v2 file can be loaded into Hive or Spark (those with Parquet Java lib) successfully. Is V2 also not recommended in Java environment? 

At last, there is an `version= '1.0' / '2.0'` option in PyArrow's `write_table` (which I assume using Parquet C++ lib). In this case, the V1 and V2 are not actually effecting the result files. The number of bytes are the same, and both file can be loaded successfully. Could you explain the difference between C++ Parquet V2 and Java Parquet V2? 

Thank you very much for your help and your time!

**Comment by emkornfield** [comment]
@YucanLiu I think the parquet mailing list is probably the best place to get an answer for this.  The core C++ reader just happens to reside in the arrow repository for developer convenience (so it is easy to build arrow readers on top of it).

**Comment by YucanLiu** [comment]
@emkornfield Thanks for your info! Could you point me to where is the parquet mailing list? 
Also, the core C++ reader is the problem right? The file that generated by Parquet writer V2 will be able to load into Java parquet lib but not C++ parquet lib.

**Comment by emkornfield** [comment]
dev@parquet.apache.org I'm not actually sure what is the problem but Imagine it is the core reader

**Comment by wesm** [comment]
V2 files are not supported in the C++ library, see PARQUET-458. We probably should raise an exception when passing `version='2.0'` in Python until this is fixed

**Comment by wesm** [comment]
I just opened https://issues.apache.org/jira/browse/ARROW-6924. I think raising an exception would be appropriate until PARQUET-458 is addressed
