### ISSUE TITLE
[RUST] Update `flatbuffers` to avoid vulnerability

### ISSUE THREAD

**Issue by emilk** [apache/arrow#5742]
[`cargo audit`](https://github.com/RustSec/cargo-audit) output:

```
ID:	 RUSTSEC-2019-0028
Crate:	 flatbuffers
Version: 0.5.0
Date:	 2019-10-20
URL:	 https://github.com/google/flatbuffers/issues/5530
Title:	 Unsound `impl Follow for bool`
```

The fix should be as simple as editing https://github.com/apache/arrow/blob/master/rust/arrow/Cargo.toml from `flatbuffers = "0.5.0"` to `flatbuffers = "0.6.0"`

A more longterm improvement is to add a call to `cargo audit` in your CI to catch these problems as early as possible

**Comment by paddyhoran** [comment]
Hi @emilk, thanks for this.  We use JIRA for issues so I created the following:
 - [add cargo audit to CI](https://issues.apache.org/jira/browse/ARROW-7005)
 - [Bump flatbuffers](https://issues.apache.org/jira/browse/ARROW-7006)
