### ISSUE TITLE
[python] Is there a way to load/dump table schema to json?

### ISSUE THREAD

**Issue by i4never** [apache/arrow#5749]
Hi, 
I'm new to this project. I saw something about the [schema json](https://github.com/apache/arrow/blob/master/integration/data/struct_example.json) used in integration test. Is there any interface in python to load & dump schema from json file like this?
If u think this is a feature request, I'll bring this to JIRA :)

**Comment by wesm** [comment]
The JSON format used in integration testing is not a public API. If you'd like to have a public API for schemas in JSON, I would suggest opening a JIRA issue and starting a thread about it on the mailing list.
