### ISSUE TITLE
[PYTHON] error with flight example 

### ISSUE THREAD

**Issue by joetl** [apache/arrow#5761]
https://github.com/apache/arrow/blob/102410ca4b738ec0560e06a26d32e10f3f472eed/python/examples/flight/server.py#L125

Getting error when trying to run the python flight example.  
ERROR MESSAGE: "FlightServer" object has no attribute "init"

**Comment by emkornfield** [comment]
Sorry about that it looks like https://github.com/apache/arrow/commit/d1848c8586409658194f5cd901c25f19ec4ab02a changed the API so that argument should be passed along through the constructor (__init__).

CC @lidavidm do you think you could update the example to get it to a working state?

**Comment by emkornfield** [comment]
or @joetl if this works for you a pull request would be welcome.  If you are still seeing issues e-mailing user@arrow.apache.org or opening a JIRA is the preferred method of support for th e project.

**Comment by martinberoiz** [comment]
Hi, I have the same issue, how is init supposed to be called?
