### ISSUE TITLE
not well supported for language  Chinese

### ISSUE THREAD

**Issue by bobowang2017** [apache/arrow#5775]
arrow.get('2019-10-20', tzinfo='local').humanize(locale='zh')

error:

ValueError: Humanization of the 'weeks' granularity is not currently translated in the 'zh' locale. Please consider making a contribution to this locale.

**Comment by wesm** [comment]
Can you please open a JIRA issue with a reproducible example?

**Comment by bobowang2017** [comment]
> Can you please open a JIRA issue with a reproducible example?

Where is the JIRA issue address?

**Comment by jorisvandenbossche** [comment]
I think you are looking for a different project with the name "arrow": https://github.com/crsmithdev/arrow (python datetime library)

**Comment by bobowang2017** [comment]
thank you
