### ISSUE TITLE
[C++] Building issues on Lnx x32/Win x32 platforms

### ISSUE THREAD

**Issue by KalyanovD** [apache/arrow#5787]
Hello! I've tried to build C++ library (0.14.0 and higher) from source with using CMake 3.7.2 on linux32  platform, but build failed whatever I tried. I didn't find any information concerning how to build Arrow on x32 architectures. Please, let me know, if there are any instructions(guidelines) concerning this question for lnx32 and win32 building from source or any information about Arrow unsupporting x32 achitectures.

**Comment by wesm** [comment]
Can you please open a JIRA issue and provide logs showing the issues you have run into?

**Comment by KalyanovD** [comment]
I don't sure that it is the "Issue" until I don't know if the Arrow supported x32 architectures, because it is not obvious to understand that from the documentation. And more than that, it is not obvious how to build it with cmake without having dependencies built. All I wanted to have was binaries for lnx32, which is not provided through any channels from installing guide.
Building failed at the building dependencies step and it may be caused by building on lnx64 with -m32 option because of having no access to x32 machine. For regret I can't attach logs because of some reasons, but there are problem with finding needed headers and I will try to fix it by my own side.
I just want to know if all my attempts are not useless, so, please, give me answers for following questions:
1) Did you tested Arrow on x32 achitectures? (Do you provide supporting on this architectures? Or where in the documentation I can find the opposite to refer to this?)
2) Did you have any channels where I can find x32 binaries built instead of building them by myself?
Thank you in advance.

**Comment by wesm** [comment]
We aren't building or testing 32-bit arch but we would like to support `-m32` builds. Can you please open a JIRA issue where we can track the project? Closing this issue for now.

**Comment by wesm** [comment]
(FWIW I was able to build Arrow on 32-bit ARM -- haven't tried x86 though -- in the last 12 months but the build might have gotten broken in the meantime)

**Comment by kou** [comment]
We have a CI task for MinGW i686: https://github.com/apache/arrow/blob/master/appveyor.yml#L81-L86
