### ISSUE TITLE
Parquet file compression

### ISSUE THREAD

**Issue by vincenzon** [apache/arrow#5818]
I am writing data to parquet files and finding the compression is very slight. I wrote 1000 files uncompressed and on average they were 200KB. With GZIP at level 9 (I think) the average file size is 170KB. If I manually gzip the files outside of arrow, the average file size is 60KB. The method I am using is at the time of writing the Table: 

```
void writeParquet(const std::string &path, const arrow::Table& table)
{
  std::shared_ptr<arrow::io::FileOutputStream> outfile;
  arrow::io::FileOutputStream::Open(path, &outfile);  
  parquet::WriterProperties::Builder builder;
  builder.compression(parquet::Compression::GZIP);
  builder.compression_level(9);
  std::shared_ptr<parquet::WriterProperties> props = builder.build();    
  parquet::arrow::WriteTable(table, arrow::default_memory_pool(), outfile, 65536, props);
}
```

The Table itself has no compression specified which I am thinking may be part of the problem. Can someone give me guidance on how to write compressed parquet files to maximize the compression ratio? Thank you in advance,

Matt

**Comment by pitrou** [comment]
What is the number of columns and the number of rows in each table, roughly?

**Comment by vincenzon** [comment]
There are 5 columns, three are short strings (3-5 char), one is doubles (random but highly auto-correlated), one is int32 (small numbers 0-100). The row count varies, the average is 30K +/- 20K. I changed the WriteTable line to use the number of rows as the chunk size but same result:

```
parquet::arrow::WriteTable(table, arrow::default_memory_pool(), outfile, table.num_rows(), props);
```

**Comment by pitrou** [comment]
When you say "If I manually gzip the files outside of arrow, the average file size is 60KB", is it by gzipping each file individually?

**Comment by vincenzon** [comment]
Yes, compressing each individually. For reference my measurement code is:

```
import os
import gzip
sizes = {}

for dir, subdir, files in os.walk('/data/'):
    if files:
        f = os.path.join(dir, files[0])
        sizes[f] = [os.path.getsize(f)]
        
        with open(f, 'rb') as f_in, gzip.open(f + '.gz', 'wb') as f_out:
            f_out.writelines(f_in)
            sizes[f].append(os.path.getsize(f + '.gz'))
            os.remove(f + '.gz')

(sum([v[0] for v in sizes.values()]) / len(sizes), 
 sum([v[1] for v in sizes.values()]) / len(sizes))
```

And the result is: `(179696.6378755365, 63077.417918454936)`

**Comment by pitrou** [comment]
`f_out.writelines(f_in)` looks weird. Also, `os.path.getsize` should be called after `f_out` is closed. Otherwise, not all data is flush to disk.

But, instead of writing the compressed file on disk, I would simply write:

```python
with open(f, 'rb') as f_in:
    sizes[f].append(len(gzip.compress(f_in.read(), 9)))
```

**Comment by vincenzon** [comment]
I'm glad I included the reference code then, but it looks pretty similar. Using the revised measurement you suggest the result is: `(179828.68401287554, 70846.4597639485)`.

```
sizes = {}

for dir, subdir, files in os.walk('/home/xbk/fileserver/data/tickdata/'):
    if files:
        f = os.path.join(dir, files[0])
        sizes[f] = [os.path.getsize(f)]
        
        with open(f, 'rb') as f_in:
            sizes[f].append(len(gzip.compress(f_in.read(), 9)))
            
(sum([v[0] for v in sizes.values()]) / len(sizes), 
 sum([v[1] for v in sizes.values()]) / len(sizes))
```

**Comment by vincenzon** [comment]
I think the problem was operator error. I had a set of files that I had created without compression earlier in the day in that filesystem it was skewing the results. I removed all the files, rewrote them and now see a result like: `(27129.290355329947, 26105.685279187815)`. 

Thanks for your help on this.
