### ISSUE TITLE
Strategy for mixing large_string and string with chunked arrays

### ISSUE THREAD

**Issue by maartenbreddels** [apache/arrow#5874]
I'm trying to see if I can move vaex to rely fully on arrow, and I have an issue with mixing string and large_string.

In vaex I can lazily concatenate dataframes without memory copy. If I want to implement this using a `pa.ChunkedArray`, users cannot concatenate dataframes that have a string column with `pa.string` type to a dataframe that has a column with `pa.large_string`.

In short, there is no arrow data structure to handle this 'mixed chunked array', but I was wondering if this could change. The only way out seems to cast them manually to a common type (although blocked by https://issues.apache.org/jira/browse/ARROW-6071).
Internally I could solve this in vaex, but feedback from building a DataFrame library with arrow might be useful. Also, it means I cannot expose the concatenated DataFrame as an arrow table.

I also wonder if having two types (large_string and string) is a good idea in the end since it makes type checking cumbersome (having to check two types each time).

PS: I guess GitHub is ok for discussions/questions, Jira has no 'Issue type' for that

**Comment by maartenbreddels** [comment]
Could an option be that there is only 1 string and list type,  and that the width of the indices/offsets can be obtained at runtime. That would also make it easy to support 16 and 8-bit offsets.

That would make arrow more flexible, and I guess it would play better with `pa.ChunkedArray`.

**Comment by jorisvandenbossche** [comment]
> In short, there is no arrow data structure to handle this 'mixed chunked array', but I was wondering if this could change.

My gut feeling is that this is not likely to change (it might open a whole box of pandora of issues if we allow mixed type in a chunked array?), but if you want to bring it up, better to send to an email to the dev mailing list (dev@arrow.apache.org) I think.

> I also wonder if having two types (large_string and string) is a good idea in the end since it makes type checking cumbersome (having to check two types each time).

The "large" types are relatively recent additions (historically, there were only the int32 offset-based types). I didn't follow those discussions, but I suppose back then it was considered how to add the "large" types and there were probably reasons to not parametrize the existing types (someone else can probably give more details on this).

If the casting issue is solved, would that also be workable for your use case? 
In general, we also need to add more type promotion / schema normalization when eg concatting tables or arrays, so string vs large_string is something that could be handled there as well.

> PS: I guess GitHub is ok for discussions/questions, Jira has no 'Issue type' for that

As mentioned above, I think the mailing list is more regularly used for this purpose (not sure if many people look at the github issues)

**Comment by maartenbreddels** [comment]
Thanks Joris, I'll post this to the mailing list.

**Comment by wesm** [comment]
In the meantime I opened https://issues.apache.org/jira/browse/ARROW-7245
