### ISSUE TITLE
Share tensor from Python to C++

### ISSUE THREAD

**Issue by doudoubobo** [apache/arrow#5878]
Hi, 
I'm doing a project where I need to store a tensor in Python code and get the stored tensor in C++ code.
Python code:
`import torch`
`import pyarrow as pa`
`import pyarrow.plasma as plasma`
`id = plasma.ObjectID(20 * b"a")`
`client = plasma.connect('/tmp/plasma')`
`x = torch.eye(2)`
 `x=x.numpy()`
`saved_tensor = pa.Tensor.from_numpy(x)`
`data_size = pa.get_tensor_size(saved_tensor)`
`buf = client.create(id, data_size)`
`stream = pa.FixedSizeBufferWriter(buf)`
`pa.write_tensor(saved_tensor, stream)`
`client.seal(id)`
C++ code:
`ObjectID object_id = ObjectID::from_binary(“aaaaaaaaaaaaaaaaaaaa”);`
`ObjectBuffer object_buffer;`
`PlasmaClient client;`
`client.Connect("/tmp/plasma");`
`ARROW_CHECK_OK(client.Get(&object_id, 1, -1, &object_buffer));`
`auto plasma_buffer = object_buffer.data;`
`arrow::io::BufferReader reader(plasma_buffer);`
`std::shared_ptr<Tensor> out;`
`ARROW_CHECK_OK(arrow::ipc::ReadTensor(&reader, &out));`

When  I run the C++ code, I get an error:

> Check failed: _s.ok() Operation failed: arrow::ipc::ReadTensor(&reader, &out)
Bad status: IOError: Cannot read a negative number of bytes from BufferReader.

So I want to know how to change the code?

Many thanks!

**Comment by emkornfield** [comment]
questions/suggestions:
1.  Remove plasma for the time being and read/write to a file to verify if it works with that. (and then verify you get the same bytes back in plasma).
2.  Are you using the the same version of Arrow CPP/ Pyarrow?  The formats changed slightly between 0.14.* and 0.15.*

if neither of these help the preferred avenue of support are the official arrow mailing list.

**Comment by doudoubobo** [comment]
> questions/suggestions:
> 
> 1. Remove plasma for the time being and read/write to a file to verify if it works with that. (and then verify you get the same bytes back in plasma).
> 2. Are you using the the same version of Arrow CPP/ Pyarrow?  The formats changed slightly between 0.14.* and 0.15.*
> 
> if neither of these help the preferred avenue of support are the official arrow mailing list.

Hi, after using the same version of Arrow CPP/ Pyarrow, this problem has been solved. Thanks!
