### ISSUE TITLE
best method to get schema of parquet object

### ISSUE THREAD

**Issue by nojohnny101** [apache/arrow#5884]
We are currently piloting using pyarrow to get schema information from parquet objects we store in AWS S3. We are currently using ParquetDataset and schema.equals to compare objects.

We have a need for saving that schema information (stored in a ParquetSchema Pyarrow object) into some other format (JSON or dict). Am I approaching this from the wrong direction? It seems this would require a custom serializer.

Thank you and I appreciate all the effort in this library.

**Comment by wesm** [comment]
This isn't the best place for this discussion. Can you write to dev@arrow.apache.org or user@arrow.apache.org (be sure to subscribe first)?

**Comment by nojohnny101** [comment]
Wes,
Sure thing. Will reply on to dev@arrow.apache.org <mailto:dev@arrow.apache.org>
