### ISSUE TITLE
How to send data to Server and then get back data

### ISSUE THREAD

**Issue by hamroune** [apache/arrow#5910]
HI every one,
 I'm playing with Flight Server and I want to send (do_put) some data table to server, then the server do some computation and after completion (for the moment just Sync operation) I want to resend back the result as a Table again to the sender. 

> client (send data) - > server (compute) - > client (get  response).

> 

What is the best approach to do that? 
I can't find in the last version the possibility to attach data into an action! 
My question is may be naive but it will en light me for the possibility to interact seamlessly with all my micro-services.
Thanks in advance

**Comment by wesm** [comment]
Sounds like you're talking about the "Bi-Directional RPC" that we are discussing on the mailing list to add to Flight. Here's a link to the mailing list thread, suggest we continue the discussion there

https://lists.apache.org/thread.html/13476a6dd895ffee3d21c6c365a79f92a0a07750391316758f4a465e@%3Cdev.arrow.apache.org%3E
