### ISSUE TITLE
ParquetDataset deadlock with different metadata_nthreads values

### ISSUE THREAD

**Issue by mrmathematica** [apache/arrow#6020]
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
output_folder = "C:\\scr\\tmp"
weather_df = pd.DataFrame({"a": [1, 1, 1, 2, 2, 2, 3, 3, 3], "b": [1, 1, 1, 1, 5, 1, 1, 1, 1], "c": ["c1", "c1", "c1", "c10", "c20", "c30", "c1", "c1", "c1"], "d": [32, 32, 32, 32, 32, 32, 32, 32, 32] })
table = pa.Table.from_pandas(weather_df)
pq.write_to_dataset(table, root_path=output_folder, partition_cols=["a", "b", "c"])
# works for 1 thread
dataset = pq.ParquetDataset(output_folder,  metadata_nthreads=1, validate_schema=False)
# stuck for 2~6 threads (but it may vary from time to time)
dataset = pq.ParquetDataset(output_folder,  metadata_nthreads=2, validate_schema=False)
dataset = pq.ParquetDataset(output_folder,  metadata_nthreads=6, validate_schema=False)
# works for 60 thread
dataset = pq.ParquetDataset(output_folder,  metadata_nthreads=60, validate_schema=False)

**Comment by bkietz** [comment]
Hi, thanks for contacting us. We use [JIRA for issue tracking](https://issues.apache.org/jira/secure/CreateIssue!default.jspa), could you open this issue there?

**Comment by mrmathematica** [comment]
https://issues.apache.org/jira/browse/ARROW-7385

**Comment by bkietz** [comment]
@mrmathematica thanks!
