### ISSUE TITLE
NULL values for Parquet data types

### ISSUE THREAD

**Issue by ankravch** [apache/arrow#6057]
What are explicit NULL value definitions for Parquet data types?

For example, here is a modified patch from arrow/cpp/examples/parquet/low-level-api/reader-writer2.cc
```
      parquet::Int32Writer* int32_writer = 
             static_cast<parquet::Int32Writer*>(rg_writer->column(col_id));
      /* ? For int32_t null value I would expect something like -2147483648 */   
      int32_t int32_value = parquet_int32_null_value_definition; 
      int32_writer2->WriteBatch(1, nullptr, nullptr, &int32_value);

```

**Comment by wesm** [comment]
Parquet nulls are represented using definition levels only -- i.e. "0" is a null, "1" is a non-null, for a simple OPTIONAL non-repeated field. If you have more questions can you write to dev@parquet.apache.org or user@parquet.apache.org?
