### ISSUE TITLE
[pyarrow] ConvertOptions Does Not Pass Through Nullability on Fields

### ISSUE THREAD

**Issue by tlantz** [apache/arrow#6243]
This may be an open a JIRA item immediately but I didn't see anything existing upon searching (possibly my bad searching as well) so I wanted to do a quick gut check first before filing a bug:

- Minor: the [docs](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ConvertOptions.html#pyarrow.csv.ConvertOptions) for `ConvertOptions.column_types` only specify that you can pass a dict but as of [this commit](https://github.com/apache/arrow/commit/df54da211448b5202aa08ed2b245eb78cfd1e50c) you can pass a `Schema` object. And I've checked that this still works. It would be a great update in the docs, and I'd be happy to submit a patch (I need to read through contribution guidelines still).
- Less minor, but I may be doing it wrong: if I supply a `Schema` for `column_types` where I've disallowed nulls on a `Field` that information seems to be lost. From what I can tell the loss happens [here](https://github.com/apache/arrow/blob/ace72c2afa6b7608bca9ba858fdd10b23e7f2dbf/python/pyarrow/_csv.pyx#L411) but I haven't read all the downstream code so I am not 100% if this is a deeper issue in the CSV reader code. I'm more than happy to submit a bug and dig a bit more to provide detail or even submit a patch (again need to read the guidelines) but this is the one I really wanted to gut check.

The problematic use case is where I have fairly well known format CSV files that I'm converting to Parquet using pyarrow (there are other choices here, but since most of my code now is in Python, this made sense for the moment). I know the data types and nullability up front so I want to specify them tight if possible, and then load the file. In this case, if I specify null is not allowed, then I end up with the following when schemas are compared when I go to write the parquet file.

```
Traceback (most recent call last):
...REDACTED...
  File "REDACTED/lib/python3.7/site-packages/pyarrow-0.15.1-py3.7-macosx-10.9-x86_64.egg/pyarrow/parquet.py", line 472, in write_table
    raise ValueError(msg)
ValueError: Table schema does not match schema used to create file: 
table:
bit: bool vs. 
file:
bit: bool not null
```

Again happy to take this to a JIRA issue if on a skim it might be a legit issue and I'm not doing something simple wrong from a usage point of view. Thank you!

**Comment by wesm** [comment]
Seems like a bug to me, can you go ahead and open a JIRA issue for this?

**Comment by nealrichardson** [comment]
Could you make a Jira please? I don't see anything that exactly matches what you're talking about on https://issues.apache.org/jira/issues/?jql=project%20%3D%20ARROW%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20in%20(%22C%2B%2B%22%2C%20%22C%2B%2B%20-%20Dataset%22%2C%20Python)%20AND%20labels%20%3D%20CSV%20order%20by%20priority%20DESC%2Cupdated%20DESC

**Comment by tlantz** [comment]
Thanks! I've filed https://issues.apache.org/jira/browse/ARROW-7655 and https://issues.apache.org/jira/browse/ARROW-7654. While demonstrating a repro case I think I might have spotted another bug in the same area but going to check that list first.

**Comment by tlantz** [comment]
I added https://issues.apache.org/jira/browse/ARROW-7656 regarding the other bug I noted as well. That is not a bug based on my read through existing CSV issues but a documentation conflict for the Python bindings.

**Comment by nealrichardson** [comment]
Excellent, many thanks!
