### ISSUE TITLE
Arrow Cpp Build prerequisites documentation has gone missing

### ISSUE THREAD

**Issue by a2un** [apache/arrow#6261]
Link to the documentation : **https://github.com/apache/arrow/blob/master/docs/source/developers/cpp.rst**

**Comment by wesm** [comment]
Where did you come across that link? This file was just separated into a few subfiles

https://github.com/apache/arrow/tree/master/docs/source/developers/cpp

**Comment by joaomlneto** [comment]
- https://github.com/apache/arrow/blob/master/cpp/README.md
- https://github.com/apache/arrow/blob/master/cpp/thirdparty/README.md

**Comment by kou** [comment]
Thanks.
I've opened https://issues.apache.org/jira/browse/ARROW-7687 and created a pull request: https://github.com/apache/arrow/pull/6288
