### ISSUE TITLE
Including locally compiled CPP headers results in compiler errors

### ISSUE THREAD

**Issue by roozmahdavian** [apache/arrow#6298]
I've built arrow + parquet cpp from source via cmake .., make, make install. #including the resulting arrow headers via <arrow/api.h> creates a ton of compiler errors in my project, the first of which is the following:

```
In file included from /usr/local/include/arrow/visitor.h:21:0,
                 from /usr/local/include/arrow/type.h:33,
                 from /usr/local/include/arrow/array.h:30,
                 from /usr/local/include/arrow/api.h:23,
                 from /home/me/test-proj/parquet.cc:5:
/usr/local/include/arrow/status.h:202:46: error: macro "NotImplemented" passed 1 arguments, but takes just 0
   static Status NotImplemented(Args&&... args) {
                                              ^
```
There are a few more, but many of them are cascading from Status failing to compile. I'm using **C++14** and compiling with the **cpp** compiler. Any ideas?

**Comment by piercefreeman** [comment]
Seen a similar issue in the past, made me fallback from compiling from source to using the homebrew packaged version.  Would love to see this solved as well.

**Comment by wesm** [comment]
Can you open a JIRA issue and provide details to reproduce? Thanks

**Comment by roozmahdavian** [comment]
Nevermind, found the root issue. Someone had defined a NotImplemented macro in a utility header deep in our frameworks that was being imported everywhere, and the compiler was trying to expand all of arrows instances of NotImplemented to this macro. Closing.
