### ISSUE TITLE
Extending the API 

### ISSUE THREAD

**Issue by achapkowski** [apache/arrow#6357]
I have some questions from the documentation on extending Apache Arrow for python and other languages.

1. The first question is if I create a custom DType for pandas, do I have to register the dtype in pyarrow for the read/write functions?

2. Is there a framework to extend the storage format to perform custom query operations like the postgis functions to arrow?  See: https://postgis.net/

**Comment by jorisvandenbossche** [comment]
> if I create a custom DType for pandas, do I have to register the dtype in pyarrow for the read/write functions?

Check the docs here: https://github.com/apache/arrow/blob/master/docs/source/python/extending_types.rst (this has a bit more content than the online released version at https://arrow.apache.org/docs/python/extending_types.html). For conversion to arrow, you can implement the `__arrow_array__` method (and for conversion back to pandas, the `__from_arrow__` on the dtype, see https://pandas.pydata.org/docs/development/extending.html#compatibility-with-apache-arrow).

If your pandas DType maps to a built-in arrow type, you don't need to create or register any custom dtype in pyarrow. But if not, and you want to preserve eg some metadata information on how to interpret the data (check eg the PeriodDtype in pandas master), then you will need to arrow extension type.

> Is there a framework to extend the storage format to perform custom query operations like the postgis functions to arrow?

Can you be more precise in what your question is? The storage format can be extended with extension types, but given your question above, I think you are already aware of that. 

---

In general, we prefer usage questions and developer discussions to be help on the mailing list, and not in github issues (dev@arrow.apache.org and user@arrow.apache.org, or JIRA for issue reports)

**Comment by achapkowski** [comment]
I want to store geospatial information into arrow, but I was looking for docs on how to create a engine capabilities so I can perform operations like intersect with another geometry on a given column of spatial data.  

`pyarrow` seems to just be a read/writer, which is very limited.  If I mistaken, can you point to the doc for this?

The python `sqlite` module has the ability to register functions and adapters: https://docs.python.org/2/library/sqlite3.html#using-adapters-to-store-additional-python-types-in-sqlite-databases

Something like this would allow for the simple creation of expanded engines.  As a suggestion.

As for the list, these all get filtered out as spam, but github messages do not.  Just something to keep in mind.

**Comment by wesm** [comment]
> these all get filtered out as spam

This is news to me. All e-mails from these mailing lists come directly to my gmail inbox. It may require you clicking "Not spam" in Gmail perhaps

There is active work on data processing tools in C++ that are exposed in pyarrow, and additionally we provide C, C++, and Cython APIs for getting access to the C++ data structures so you can use custom processing code and interoperates with pyarrow. As far as registering custom processing functions for user-defined data types, my guess is that it will happen but is simply a matter of time and developer bandwidth. 

Can we discuss this more over e-mail?

**Comment by bergkvist** [comment]
Any news on this? I'm very interested in geometry columns in Arrow. Similar to geopandas.

**Comment by jorisvandenbossche** [comment]
See also https://github.com/geopandas/geo-arrow-spec/
