### ISSUE TITLE
Decimal place getting shifted

### ISSUE THREAD

**Issue by RedTailedHawk** [apache/arrow#6428]
I used `JdbcToArrow.sqlToArrow()` to create an Arrow file from a SQL result set, and when I read the Arrow file back in PyArrow, the decimal numbers are very small.  On the order of E-10.

What's interesting is that the values are "correct", except the decimal places are shifted over.

The Arrow file is enclosed.

Please let me know if there's a bug around this.

(using 0.14.1 of Arrow)

[test_file.arrow.zip](https://github.com/apache/arrow/files/4206674/test_file.arrow.zip)

**Comment by RedTailedHawk** [comment]
FWIW, I just updated PyArrow to 0.16.0, and the Java Arrow JDBC package to 0.16.0, and now my dataframe is empty.

**Comment by emkornfield** [comment]
Could you open a JIRA and provide a example code. What database driver are you using?  My first thought is that resultsetmeta isn't returning the correct [precision/scale](https://github.com/apache/arrow/blob/master/java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcFieldInfo.java#L89)

**Comment by wesm** [comment]
@RedTailedHawk are you able to open a JIRA issue about this?

**Comment by RedTailedHawk** [comment]
Just created a JIRA.

https://issues.apache.org/jira/browse/ARROW-7875

@emkornfield The database driver is denodo-vdp-jdbcdriver.jar.

**Comment by wesm** [comment]
Thanks
