### ISSUE TITLE
Issues with installation on AWS Sagemaker notebook using R kernel..

### ISSUE THREAD

**Issue by j0bekt01** [apache/arrow#6448]
I apologize this is my first post, and I am aware of recent work done to [streamline linux installation ](https://github.com/apache/arrow/commit/5227b78300c353546041bacc6de718ad018ecb80 ) But I think that it may not be doing it for me. 
I am attempting to utilize `write_parquet `function out of the arrow package with R kernel of Sagemaker Jupyter notebook which runs on `Amazon Linux AMI 2018.03`.
So, when I run the `install.packages("arrow")` line it installs the library and allows me to load it using `library(arrow)`. However, when I attempt to utilize the write_parquet function it gives me an error 

> Error in Table__from_dots(dots, schema): Cannot call Table__from_dots(). Please use arrow::install_arrow() to install required runtime libraries.

--which I do. It takes a while but it appears as if everything installed correctly by displaying the message to restart the R console in order to use the arrow, which I do, and the package loads but again when I attempt to utilize `write_parquet `it doesn't work, it gives me the same error.

From looking at the log files, it appears that it fails to build the c++ library.

FYI, I have used `pyarrow `with the python3 kernel on the notebook instance without any issues.

Any help would be much appreciated.

**Comment by nealrichardson** [comment]
Thanks for the report. If you see logs indicating a build failure, could you please share them? Also, please include your package versions/`sessionInfo()`.

**Comment by j0bekt01** [comment]
I apologize for that, rookie mistake.
Here is the session info:

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-conda_cos6-linux-gnu (64-bit)
> Running under: Amazon Linux AMI 2018.03
> 
> Matrix products: default
> BLAS/LAPACK: /home/ec2-user/anaconda3/envs/R/lib/R/lib/libRblas.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.6.1  IRdisplay_0.7.0 pbdZMQ_0.3-3    tools_3.6.1    
>  [5] htmltools_0.3.6 base64enc_0.1-3 crayon_1.3.4    Rcpp_1.0.1     
>  [9] uuid_0.1-2      IRkernel_0.8.15 jsonlite_1.6    digest_0.6.18  
> [13] repr_0.19.2     evaluate_0.13  

and here is the notebook log when I run `arrow::install.arrow()`:


> downloaded 211 KB
> * installing *source* package ‘arrow’ ...
> ** package ‘arrow’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ++ pwd
> + : /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow
> + : /tmp/RtmpFwy14E/file585571a8c7c/cpp
> + : libarrow/build
> + : libarrow/arrow-0.16.0.2
> + : /usr/bin/cmake
> ++ cd /tmp/RtmpFwy14E/file585571a8c7c/cpp
> ++ pwd
> + SOURCE_DIR=/tmp/RtmpFwy14E/file585571a8c7c/cpp
> ++ mkdir -p libarrow/arrow-0.16.0.2
> ++ cd libarrow/arrow-0.16.0.2
> ++ pwd
> + DEST_DIR=/tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/arrow-0.16.0.2
> + '[' '' = '' ']'
> + which ninja
> + '[' '' '!=' '' ']'
> + '[' '' '!=' '' ']'
> + '[' '' = TRUE ']'
> + mkdir -p libarrow/build
> + pushd libarrow/build
> + /usr/bin/cmake -DARROW_BOOST_USE_SHARED=OFF -DARROW_BUILD_TESTS=OFF -DARROW_BUILD_SHARED=OFF -DARROW_BUILD_STATIC=ON -DARROW_COMPUTE=ON -DARROW_CSV=ON -DARROW_DATASET=ON -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_FILESYSTEM=ON -DARROW_JEMALLOC=ON -DARROW_JSON=ON -DARROW_PARQUET=ON -DARROW_WITH_BROTLI=ON -DARROW_WITH_BZ2=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_ZSTD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_PREFIX=/tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/arrow-0.16.0.2 -DOPENSSL_USE_STATIC_LIBS=ON -G 'Unix Makefiles' /tmp/RtmpFwy14E/file585571a8c7c/cpp
> Using ld linker
> Configured for RELEASE build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
> Building Apache Thrift from source
> Downloading Apache Thrift from http://apache.spinellicreations.com//thrift/0.12.0/thrift-0.12.0.tar.gz
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     OPENSSL_USE_STATIC_LIBS
> 
> + /usr/bin/cmake --build . --target install
> CMake Error at zlib_ep-stamp/zlib_ep-download-RELEASE.cmake:16 (message):
>   Command failed: 1
> 
>    '/usr/lib64/python3.6/dist-packages/cmake/data/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download-RELEASE-impl.cmake'
> 
>   See also
> 
>     /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download-*.log
> 
> make[2]: *** [CMakeFiles/zlib_ep.dir/build.make:90: zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download] Error 1
> make[1]: *** [CMakeFiles/Makefile2:660: CMakeFiles/zlib_ep.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> CMake Error at /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/bzip2_ep-prefix/src/bzip2_ep-stamp/bzip2_ep-build-RELEASE.cmake:16 (message):
>   Command failed: 2
> 
>    '/home/ec2-user/anaconda3/envs/R/bin/make' 'CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/ec2-user/anaconda3/envs/R/include -O3 -DNDEBUG -O3 -DNDEBUG -fPIC'
> 
>   See also
> 
>     /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/bzip2_ep-prefix/src/bzip2_ep-stamp/bzip2_ep-build-*.log
> 
> make[2]: *** [CMakeFiles/bzip2_ep.dir/build.make:112: bzip2_ep-prefix/src/bzip2_ep-stamp/bzip2_ep-build] Error 1
> make[1]: *** [CMakeFiles/Makefile2:551: CMakeFiles/bzip2_ep.dir/all] Error 2
> virtual memory exhausted: Cannot allocate memory
> virtual memory exhausted: Cannot allocate memory
> virtual memory exhausted: Cannot allocate memory
> make[2]: *** [src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/build.make:102: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_ipc.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> virtual memory exhausted: Cannot allocate memory
> make[2]: *** [src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/build.make:102: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_ipc.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/build.make:115: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/filter.cc.o] Error 1
> CMake Error at /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-build-RELEASE.cmake:16 (message):
>   Command failed: 2
> 
>    'make'
> 
>   See also
> 
>     /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-build-*.log
> 
> make[2]: *** [CMakeFiles/brotli_ep.dir/build.make:112: brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-build] Error 1
> CMake Error at /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-build-RELEASE.cmake:16 (message):
>   Command failed: 2
> 
>    'make'
> 
>   See also
> 
>     /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/build/brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-build-*.log
> 
> make[2]: *** [CMakeFiles/brotli_ep.dir/build.make:112: brotli_ep-prefix/src/brotli_ep-stamp/brotli_ep-build] Error 1
> make[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/brotli_ep.dir/all] Error 2
> [I 22:45:33.696 NotebookApp] Saving file at /Untitled3.ipynb
> make[1]: *** [CMakeFiles/Makefile2:1459: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/all] Error 2
> gmake: *** [all] Error 2
> + '[' 2 -ne 0 ']'
> + '[' '' '!=' '' ']'
> + xargs '-I
> {}
> ' cp -u '
> {}
> ' /tmp/Rtmpdsd6uc/R.INSTALL5764f964a92/arrow/libarrow/arrow-0.16.0.2/lib
> + find . -regex '.*/.*/lib/.*\.a$'
> + popd
> Warning message:
> In download.file(binary_url, libfile, quiet = quietly) :
>   cannot open URL 'https://dl.bintray.com/ursalabs/arrow-r/libarrow/bin/amzn-2018/arrow-0.16.0.2.zip': HTTP status was '404 Not Found'
> ** libs
> installing to /home/ec2-user/anaconda3/envs/R/lib/R/library/00LOCK-arrow/00new/arrow/libs
> installing to /home/ec2-user/anaconda3/envs/R/lib/R/library/00LOCK-arrow/00new/arrow/libs
> ** R
> ** inst
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded from temporary location
> ** checking absolute paths in shared objects and dynamic libraries
> ** testing if installed package can be loaded from temporary location
> ** checking absolute paths in shared objects and dynamic libraries
> ** testing if installed package can be loaded from final location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> ** testing if installed package keeps a record of temporary installation path
> * DONE (arrow)
> * DONE (arrow)
> The downloaded source packages are in
> 	‘/tmp/RtmpHOqaoH/downloaded_packages’

**Comment by j0bekt01** [comment]
I have also tried by installing Amazon Linux packages directly from [here](https://arrow.apache.org/install)  and then reinstalling the arrow package hoping that it would find required libraries automatically. Unfortunately, that failed as well.

**Comment by j0bekt01** [comment]
Here are the Amazon Linux libraries installed:
![image](https://user-images.githubusercontent.com/10472277/74793487-7e899180-528e-11ea-9ef2-a073e0f523c9.png)
![image](https://user-images.githubusercontent.com/10472277/74793567-b5f83e00-528e-11ea-83b4-034c9b8e21a2.png)

**Comment by nealrichardson** [comment]
Thanks. How exactly did it fail with the system packages installed?

**Comment by j0bekt01** [comment]
I got the same error message when attempting to utilize the `write_parquet` function.

> Error in Table__from_dots(dots, schema): Cannot call Table__from_dots(). Please use arrow::install_arrow() to install required runtime libraries.

**Comment by j0bekt01** [comment]
so, theoretically with the system packages being installed, one should be able to just run the `install.packages("arrow") `and it should detect c++ libraries automatically. But it seems not to do that because I get the same error message I posted previously. 
While on the same instance of the notebook using python3 kernel I am able to install and use it with  `!pip install pyarrow `.

**Comment by nealrichardson** [comment]
Since it looks like you're using conda, have you tried installing the R package from conda-forge? `conda install -c conda-forge r-arrow`

**Comment by j0bekt01** [comment]
Just did, everything installed properly, but once again, it fails when I call `write_parquet()`. Here is the output:

>  sh-4.2$ conda install -c conda-forge r-arrow
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.5.12
>   latest version: 4.8.2
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: /home/ec2-user/anaconda3/envs/JupyterSystemEnv
> 
>   added / updated specs:
>     - r-arrow
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     python-3.6.7               |    h357f687_1006        34.6 MB  conda-forge
>     r-ellipsis-0.3.0           |    r36hcdcec82_0          47 KB  conda-forge
>     tktable-2.10               |       h555a92e_3          89 KB  conda-forge
>     r-magrittr-1.5             | r36h6115d3f_1002         167 KB  conda-forge
>     boost-cpp-1.72.0           |       h8e57a91_0        21.8 MB  conda-forge
>     r-glue-1.3.1               |    r36hcdcec82_1         165 KB  conda-forge
>     glog-0.4.0                 |       he1b5a44_1         104 KB  conda-forge
>     make-4.2.1                 |    h14c3975_2004         458 KB  conda-forge
>     gflags-2.2.2               |    he1b5a44_1002         175 KB  conda-forge
>     libprotobuf-3.11.0         |       h8b12597_0         4.8 MB  conda-forge
>     libtiff-4.1.0              |       hc3755c2_3         568 KB  conda-forge
>     r-base-3.6.1               |       hba50c9b_5        23.3 MB  conda-forge
>     gcc_linux-64-7.3.0         |      h553295d_16          22 KB  conda-forge
>     _r-mutex-1.0.1             |      anacondar_1           3 KB  conda-forge
>     grpc-cpp-1.25.0            |       h213be95_2         5.1 MB  conda-forge
>     readline-8.0               |       hf8c457e_0         441 KB  conda-forge
>     thrift-cpp-0.13.0          |       h3701741_1        18.6 MB  conda-forge
>     r-bit64-0.9_7              | r36hcdcec82_1001         482 KB  conda-forge
>     bzip2-1.0.8                |       h516909a_2         396 KB  conda-forge
>     snappy-1.1.8               |       he1b5a44_1          39 KB  conda-forge
>     aws-sdk-cpp-1.7.164        |       h1f8afcc_0         1.8 MB  conda-forge
>     r-bit-1.1_15.2             |    r36hcdcec82_0         248 KB  conda-forge
>     re2-2020.01.01             |       he1b5a44_0         422 KB  conda-forge
>     gfortran_linux-64-7.3.0    |      h553295d_16          21 KB  conda-forge
>     r-r6-2.4.1                 |    r36h6115d3f_0          63 KB  conda-forge
>     r-vctrs-0.2.3              |    r36hcdcec82_0         892 KB  conda-forge
>     binutils_linux-64-2.33.1   |      h9595d00_16          21 KB  conda-forge
>     gxx_linux-64-7.3.0         |      h553295d_16          21 KB  conda-forge
>     brotli-1.0.7               |    he1b5a44_1000         1.0 MB  conda-forge
>     protobuf-3.11.0            |   py36he1b5a44_0         699 KB  conda-forge
>     r-arrow-0.16.0             |    r36he1b5a44_0         3.0 MB  conda-forge
>     gsl-2.5                    |       h294904e_1         2.7 MB  conda-forge
>     arrow-cpp-0.16.0           |   py36hf731a26_1        19.8 MB  conda-forge
>     r-digest-0.6.24            |    r36h0357c0b_0         198 KB  conda-forge
>     r-rlang-0.4.4              |    r36hcdcec82_0         1.0 MB  conda-forge
>     r-rcpp-1.0.3               |    r36h0357c0b_0         1.9 MB  conda-forge
>     libevent-2.1.10            |       h72c5cf5_0         1.3 MB  conda-forge
>     r-purrr-0.3.3              |    r36hcdcec82_0         407 KB  conda-forge
>     gfortran_impl_linux-64-7.3.0|       hdf63c60_5         9.4 MB  conda-forge
>     curl-7.68.0                |       hf8cf82a_0         137 KB  conda-forge
>     r-assertthat-0.2.1         |    r36h6115d3f_1          70 KB  conda-forge
>     bwidget-1.9.14             |                0         119 KB  conda-forge
>     r-backports-1.1.5          |    r36hcdcec82_0          68 KB  conda-forge
>     libpq-11.5                 |       hd9ab2ff_2         2.5 MB  conda-forge
>     libcurl-7.68.0             |       hda55be3_0         564 KB  conda-forge
>     r-zeallot-0.1.0            | r36h6115d3f_1001          62 KB  conda-forge
>     sed-4.7                    |    h1bed415_1000         245 KB  conda-forge
>     tk-8.6.10                  |       hed695b0_0         3.2 MB  conda-forge
>     r-tidyselect-1.0.0         |    r36h6115d3f_0         221 KB  conda-forge
>     ------------------------------------------------------------
>                                            Total:       163.4 MB
> 
> The following NEW packages will be INSTALLED:
> 
>     _r-mutex:               1.0.1-anacondar_1      conda-forge
>     arrow-cpp:              0.16.0-py36hf731a26_1  conda-forge
>     aws-sdk-cpp:            1.7.164-h1f8afcc_0     conda-forge
>     binutils_impl_linux-64: 2.33.1-he1b5a44_7      conda-forge
>     binutils_linux-64:      2.33.1-h9595d00_16     conda-forge
>     boost-cpp:              1.72.0-h8e57a91_0      conda-forge
>     brotli:                 1.0.7-he1b5a44_1000    conda-forge
>     bwidget:                1.9.14-0               conda-forge
>     bzip2:                  1.0.8-h516909a_2       conda-forge
>     c-ares:                 1.15.0-h516909a_1001   conda-forge
>     curl:                   7.68.0-hf8cf82a_0      conda-forge
>     gcc_impl_linux-64:      7.3.0-habb00fd_1
>     gcc_linux-64:           7.3.0-h553295d_16      conda-forge
>     gflags:                 2.2.2-he1b5a44_1002    conda-forge
>     gfortran_impl_linux-64: 7.3.0-hdf63c60_5       conda-forge
>     gfortran_linux-64:      7.3.0-h553295d_16      conda-forge
>     glog:                   0.4.0-he1b5a44_1       conda-forge
>     grpc-cpp:               1.25.0-h213be95_2      conda-forge
>     gsl:                    2.5-h294904e_1         conda-forge
>     gxx_impl_linux-64:      7.3.0-hdf63c60_1
>     gxx_linux-64:           7.3.0-h553295d_16      conda-forge
>     libcurl:                7.68.0-hda55be3_0      conda-forge
>     libevent:               2.1.10-h72c5cf5_0      conda-forge
>     libssh2:                1.8.2-h22169c7_2       conda-forge
>     lz4-c:                  1.8.3-he1b5a44_1001    conda-forge
>     make:                   4.2.1-h14c3975_2004    conda-forge
>     r-arrow:                0.16.0-r36he1b5a44_0   conda-forge
>     r-assertthat:           0.2.1-r36h6115d3f_1    conda-forge
>     r-backports:            1.1.5-r36hcdcec82_0    conda-forge
>     r-base:                 3.6.1-hba50c9b_5       conda-forge
>     r-bit:                  1.1_15.2-r36hcdcec82_0 conda-forge
>     r-bit64:                0.9_7-r36hcdcec82_1001 conda-forge
>     r-digest:               0.6.24-r36h0357c0b_0   conda-forge
>     r-ellipsis:             0.3.0-r36hcdcec82_0    conda-forge
>     r-glue:                 1.3.1-r36hcdcec82_1    conda-forge
>     r-magrittr:             1.5-r36h6115d3f_1002   conda-forge
>     r-purrr:                0.3.3-r36hcdcec82_0    conda-forge
>     r-r6:                   2.4.1-r36h6115d3f_0    conda-forge
>     r-rcpp:                 1.0.3-r36h0357c0b_0    conda-forge
>     r-rlang:                0.4.4-r36hcdcec82_0    conda-forge
>     r-tidyselect:           1.0.0-r36h6115d3f_0    conda-forge
>     r-vctrs:                0.2.3-r36hcdcec82_0    conda-forge
>     r-zeallot:              0.1.0-r36h6115d3f_1001 conda-forge
>     re2:                    2020.01.01-he1b5a44_0  conda-forge
>     sed:                    4.7-h1bed415_1000      conda-forge
>     snappy:                 1.1.8-he1b5a44_1       conda-forge
>     thrift-cpp:             0.13.0-h3701741_1      conda-forge
>     tktable:                2.10-h555a92e_3        conda-forge
> 
> The following packages will be UPDATED:
> 
>     libpq:                  11.2-h20c2e04_0                    --> 11.5-hd9ab2ff_2       conda-forge
>     libtiff:                4.1.0-h2733197_0                   --> 4.1.0-hc3755c2_3      conda-forge
>     readline:               7.0-h7b6447c_5                     --> 8.0-hf8c457e_0        conda-forge
>     tk:                     8.6.8-hbc83047_0                   --> 8.6.10-hed695b0_0     conda-forge
>     zstd:                   1.3.7-h0b5b093_0                   --> 1.4.4-h3b9ef0a_1      conda-forge
> 
> The following packages will be DOWNGRADED:
> 
>     libprotobuf:            3.11.3-h8b12597_0      conda-forge --> 3.11.0-h8b12597_0     conda-forge
>     protobuf:               3.11.3-py36he1b5a44_0  conda-forge --> 3.11.0-py36he1b5a44_0 conda-forge
>     python:                 3.6.10-h0371630_0                  --> 3.6.7-h357f687_1006   conda-forge
> 
> Proceed ([y]/n)? y
> 
> 
> Downloading and Extracting Packages
> python-3.6.7         | 34.6 MB   | ########################################################## | 100%
> r-ellipsis-0.3.0     | 47 KB     | ########################################################## | 100%
> tktable-2.10         | 89 KB     | ########################################################## | 100%
> r-magrittr-1.5       | 167 KB    | ########################################################## | 100%
> boost-cpp-1.72.0     | 21.8 MB   | ########################################################## | 100%
> r-glue-1.3.1         | 165 KB    | ########################################################## | 100%
> glog-0.4.0           | 104 KB    | ########################################################## | 100%
> make-4.2.1           | 458 KB    | ########################################################## | 100%
> gflags-2.2.2         | 175 KB    | ########################################################## | 100%
> libprotobuf-3.11.0   | 4.8 MB    | ########################################################## | 100%
> libtiff-4.1.0        | 568 KB    | ########################################################## | 100%
> r-base-3.6.1         | 23.3 MB   | ########################################################## | 100%
> gcc_linux-64-7.3.0   | 22 KB     | ########################################################## | 100%
> _r-mutex-1.0.1       | 3 KB      | ########################################################## | 100%
> grpc-cpp-1.25.0      | 5.1 MB    | ########################################################## | 100%
> readline-8.0         | 441 KB    | ########################################################## | 100%
> thrift-cpp-0.13.0    | 18.6 MB   | ########################################################## | 100%
> r-bit64-0.9_7        | 482 KB    | ########################################################## | 100%
> bzip2-1.0.8          | 396 KB    | ########################################################## | 100%
> snappy-1.1.8         | 39 KB     | ########################################################## | 100%
> aws-sdk-cpp-1.7.164  | 1.8 MB    | ########################################################## | 100%
> r-bit-1.1_15.2       | 248 KB    | ########################################################## | 100%
> re2-2020.01.01       | 422 KB    | ########################################################## | 100%
> gfortran_linux-64-7. | 21 KB     | ########################################################## | 100%
> r-r6-2.4.1           | 63 KB     | ########################################################## | 100%
> r-vctrs-0.2.3        | 892 KB    | ########################################################## | 100%
> binutils_linux-64-2. | 21 KB     | ########################################################## | 100%
> gxx_linux-64-7.3.0   | 21 KB     | ########################################################## | 100%
> brotli-1.0.7         | 1.0 MB    | ########################################################## | 100%
> protobuf-3.11.0      | 699 KB    | ########################################################## | 100%
> r-arrow-0.16.0       | 3.0 MB    | ########################################################## | 100%
> gsl-2.5              | 2.7 MB    | ########################################################## | 100%
> arrow-cpp-0.16.0     | 19.8 MB   | ########################################################## | 100%
> r-digest-0.6.24      | 198 KB    | ########################################################## | 100%
> r-rlang-0.4.4        | 1.0 MB    | ########################################################## | 100%
> r-rcpp-1.0.3         | 1.9 MB    | ########################################################## | 100%
> libevent-2.1.10      | 1.3 MB    | ########################################################## | 100%
> r-purrr-0.3.3        | 407 KB    | ########################################################## | 100%
> gfortran_impl_linux- | 9.4 MB    | ########################################################## | 100%
> curl-7.68.0          | 137 KB    | ########################################################## | 100%
> r-assertthat-0.2.1   | 70 KB     | ########################################################## | 100%
> bwidget-1.9.14       | 119 KB    | ########################################################## | 100%
> r-backports-1.1.5    | 68 KB     | ########################################################## | 100%
> libpq-11.5           | 2.5 MB    | ########################################################## | 100%
> libcurl-7.68.0       | 564 KB    | ########################################################## | 100%
> r-zeallot-0.1.0      | 62 KB     | ########################################################## | 100%
> sed-4.7              | 245 KB    | ########################################################## | 100%
> tk-8.6.10            | 3.2 MB    | ########################################################## | 100%
> r-tidyselect-1.0.0   | 221 KB    | ########################################################## | 100%
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done

**Comment by nealrichardson** [comment]
Hmm, I'm assuming you restarted your R session after reinstalling? Can you confirm what `arrow` package version you have in the session where it errors on write_parquet? The CRAN and conda package versions aren't identical so we'll see which one is being used. If it's the CRAN one, maybe you can uninstall.packages("arrow") and remove it, and then maybe the conda one will get picked up? Just guessing here, I'm not familiar with the Sagemaker environment so I'm not sure what else to suggest.

**Comment by j0bekt01** [comment]
So, I rebooted the instance and only ran the `conda install -c conda-forge r-arrow`. Next, I opened up the R notebook and tried loading the library but it doesn't exist. I was under the impression that I should be able to do `library(arrow)`  since it was installed via conda?

**Comment by nealrichardson** [comment]
That's my understanding of how R works in conda as well.

Are you able to specify your system setup in a Dockerfile, as a way of creating a minimal reproducible example? Our CI is easily extensible if we have docker images containing R: we can plug them into the existing build matrices (like [this one](https://github.com/ursa-labs/arrow-r-nightly/blob/master/.github/workflows/test-binary.yml#L22-L27)). If you can provide one, we have a much better chance of figuring out what's going on and ensuring that the issue is fixed.

**Comment by j0bekt01** [comment]
I think I may know whats the issue, R libraries are in **R** environment `/home/ec2-user/anaconda3/envs/R`  and when I installed the arrow package via `conda install -c conda-forge r-arrow` it got installed to **JupyterSystemEnv**   environment `/home/ec2-user/anaconda3/envs/JupyterSystemEnv` . 

![conda enviroments](https://user-images.githubusercontent.com/10472277/75068231-c5f56500-54bc-11ea-9b06-3e616fb7af33.png)

**Comment by nealrichardson** [comment]
Cool, so does it work now if you install into the right environment?

**Comment by j0bekt01** [comment]
Yep! This did the trick: `conda install --name R  -c conda-forge r-arrow` 
Thanks for all your help.

**Comment by nealrichardson** [comment]
Great! Do you think it's worth adding to the docs? Maybe some more explicit language that if you're using `conda` that `install.packages()` probably won't build successfully and you need to `conda install` instead? https://github.com/apache/arrow/blob/master/r/vignettes/install.Rmd#L26-L28 mentions conda but maybe it should be called out more.

**Comment by j0bekt01** [comment]
I think it would be a good idea.

**Comment by nealrichardson** [comment]
Would you be interested in submitting a PR? https://github.com/apache/arrow/edit/master/r/vignettes/install.Rmd

**Comment by j0bekt01** [comment]
I've never done one. is there any documentation for it?

**Comment by nealrichardson** [comment]
You can go to the edit link I shared, type your revisions, and when you save select "Create a new branch for this commit and start a pull request." The web app should handle the rest. I'll make a Jira ticket for you.

**Comment by nealrichardson** [comment]
https://issues.apache.org/jira/browse/ARROW-7918

**Comment by j0bekt01** [comment]
ok, will do.
