### ISSUE TITLE
Cythonized Sources Are Distributed as A Part of Python package

### ISSUE THREAD

**Issue by daskol** [apache/arrow#6560]
It seems that cythonized sources should not be in python package (0.16.0).

**Comment by wesm** [comment]
Can you clarify, do you mean the wheels or the .tar.gz? 

Either way, can you please open a JIRA issue? Thanks

**Comment by daskol** [comment]
I mean that if one downloads a wheel directly from PyPI and install it then anyone could find C++ source code in the package. Moreover, the C++ code is autogenerated with Cython. So, it looks like packaging bug. The following snippet describes how to 
```bash
$ pip download pyarrow==0.16.0
$ zipinfo pyarrow-0.16.0-cp38-cp38-manylinux2014_x86_64.whl | grep \.cpp
-rw-r--r--  2.0 unx   844477 b- defN 20-Feb-04 23:01 pyarrow/_fs.cpp
-rw-r--r--  2.0 unx   442817 b- defN 20-Feb-04 23:01 pyarrow/_hdfs.cpp
-rw-r--r--  2.0 unx  1541146 b- defN 20-Feb-04 23:01 pyarrow/_dataset.cpp
-rw-r--r--  2.0 unx   367887 b- defN 20-Feb-04 23:01 pyarrow/_json.cpp
-rw-r--r--  2.0 unx   613473 b- defN 20-Feb-04 23:01 pyarrow/_csv.cpp
-rw-r--r--  2.0 unx   282451 b- defN 20-Feb-04 23:01 pyarrow/_compute.cpp
-rw-r--r--  2.0 unx   849442 b- defN 20-Feb-04 23:01 pyarrow/gandiva.cpp
-rw-r--r--  2.0 unx  2718205 b- defN 20-Feb-04 23:01 pyarrow/_flight.cpp
-rw-r--r--  2.0 unx  1461292 b- defN 20-Feb-04 23:01 pyarrow/_parquet.cpp
-rw-r--r--  2.0 unx  8258722 b- defN 20-Feb-04 23:01 pyarrow/lib.cpp
-rw-r--r--  2.0 unx   787145 b- defN 20-Feb-04 23:01 pyarrow/_plasma.cpp
$ unzip pyarrow-0.16.0-cp38-cp38-manylinux2014_x86_64.whl # Inflate wheel in order to take a look inside a file
$ head -n 1 pyarrow/gandiva.cpp 
/* Generated by Cython 0.29.14 */
```
Unfortunately, I have no account in Apache's JIRA and cannot to open an issue there.

**Comment by wesm** [comment]
> Unfortunately, I have no account in Apache's JIRA and cannot to open an issue there.

This is a free JIRA server, anyone can open an account. 

I opened https://issues.apache.org/jira/browse/ARROW-8050. It would be great if you could submit a PR
