### ISSUE TITLE
Column is not a type identifier

### ISSUE THREAD

**Issue by prodipta** [apache/arrow#6601]
I am trying to build an extension last built on version 0.14.0, and having trouble.

```
cimport pyarrow.lib as pa

cdef some_fn(...):
    cdef pa.Column c # <-- issue is here
```

The compiler error message is `'Column' is not a type identifier`. I searched the code and from a code comment, it appears `Column` was removed from latest version. Also the [docs link](https://arrow.apache.org/docs/python/generated/pyarrow.Column.html#pyarrow-column) appears blank. Which is the correct type to replace this with please. Thanks vm for the help.

**Comment by wesm** [comment]
This was removed in the 0.15.0 release. You'll need to modify your code to be based on ChunkedArray instead

http://arrow.apache.org/blog/2019/10/06/0.15.0-release/
