### ISSUE TITLE
pyarrow fatal error: arrow/c/abi.h: No such file or directory

### ISSUE THREAD

**Issue by saltylamon** [apache/arrow#6652]
Debian 10 
Python 3.7

Arrow CPP libs installed from apache repo

```console
$ python3 setup.py build_ext --inplace

running build_ext
-- Running cmake for pyarrow
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3  -DPYARROW_BUILD_CUDA=on -DPYARROW_BUILD_FLIGHT=off -DPYARROW_BUILD_GANDIVA=off -DPYARROW_BUILD_DATASET=off -DPYARROW_BUILD_ORC=off -DPYARROW_BUILD_PARQUET=off -DPYARROW_BUILD_PLASMA=off -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off -DPYARROW_USE_TENSORFLOW=off -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_BOOST=off -DPYARROW_GENERATE_COVERAGE=off -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_PARQUET_USE_SHARED=on -DCMAKE_BUILD_TYPE=release /code/arrow/python
-- Arrow build warning level: PRODUCTION
Using ld linker
Configured for RELEASE build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
-- Build Type: RELEASE
-- Build output directory: /code/arrow/python/build/temp.linux-x86_64-3.7/release
-- Found Arrow: /usr/include (found version "0.16.0") 
-- Arrow version: 0.16.0 (CMake package configuration: Arrow)
-- Arrow SO and ABI version: 16
-- Arrow full SO version: 16.0.0
-- Found the Arrow core shared library: /usr/lib/x86_64-linux-gnu/libarrow.so
-- Found the Arrow core import library: 
-- Found the Arrow core static library: /usr/lib/x86_64-linux-gnu/libarrow.a
-- Could NOT find ArrowPython (missing: ArrowPython_DIR)
-- Found ArrowPython: /usr/include (found version "0.16.0") 
-- Found the Arrow Python by pkg-config: arrow-python
-- Found the Arrow Python shared library: /usr/lib/x86_64-linux-gnu/libarrow_python.so
-- Found the Arrow Python import library: 
-- Found the Arrow Python static library: /usr/lib/x86_64-linux-gnu/libarrow_python.a
-- Could NOT find ArrowCUDA (missing: ArrowCUDA_DIR)
-- Checking for module 'arrow-cuda'
--   Found arrow-cuda, version 0.16.0
-- Found ArrowCUDA: /usr/include (found version "0.16.0") 
-- Found the Arrow CUDA by pkg-config: arrow-cuda
-- Found the Arrow CUDA shared library: /usr/lib/x86_64-linux-gnu/libarrow_cuda.so
-- Found the Arrow CUDA import library: 
-- Found the Arrow CUDA static library: /usr/lib/x86_64-linux-gnu/libarrow_cuda.a
-- Configuring done
-- Generating done
-- Build files have been written to: /code/arrow/python/build/temp.linux-x86_64-3.7
-- Finished cmake for pyarrow
-- Running cmake --build for pyarrow
cmake --build . --config release --
Scanning dependencies of target _cuda_pyx
[  5%] Compiling Cython CXX source for _cuda...
[  5%] Built target _cuda_pyx
Scanning dependencies of target _cuda
[ 11%] Building CXX object CMakeFiles/_cuda.dir/_cuda.cpp.o
/code/arrow/python/build/temp.linux-x86_64-3.7/_cuda.cpp:666:10: fatal error: arrow/c/abi.h: No such file or directory
 #include "arrow/c/abi.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/_cuda.dir/build.make:63: CMakeFiles/_cuda.dir/_cuda.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:92: CMakeFiles/_cuda.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
error: command 'cmake' failed with exit status 2
```

**Comment by kou** [comment]
You didn't find Apache Arrow C++ you installed from source.

The following command line (you must replace `${ARROW_CPP_PREFIX}` with the path you specified to Apache Arrow C++ as `-DCMAKE_INSTALL_PREFIX=` when you installed from source) will fix this:

```console
$ PYARROW_CMAKE_OPTIONS="-DCMAKE_MODULE_PATH=${ARROW_CPP_PREFIX}/lib/cmake/arrow" python3 setup.py build_ext --inplace
```

**Comment by saltylamon** [comment]
I installed arrow using the instructions on their mainpage

Debian GNU/Linux and Ubuntu:

sudo apt update
sudo apt install -y -V lsb-release wget
if [ $(lsb_release --codename --short) = "stretch" ]; then
  sudo tee /etc/apt/sources.list.d/backports.list <<APT_LINE
deb http://deb.debian.org/debian $(lsb_release --codename --short)-backports main
APT_LINE
fi
wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
sudo apt install -y -V ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
sudo apt update
sudo apt install -y -V libarrow-dev # For C++
sudo apt install -y -V libarrow-glib-dev # For GLib (C)
sudo apt install -y -V libarrow-flight-dev # For Flight C++
sudo apt install -y -V libplasma-dev # For Plasma C++
sudo apt install -y -V libplasma-glib-dev # For Plasma GLib (C)
sudo apt install -y -V libgandiva-dev # For Gandiva C++
sudo apt install -y -V libgandiva-glib-dev # For Gandiva GLib (C)
sudo apt install -y -V libparquet-dev # For Apache Parquet C++
sudo apt install -y -V libparquet-glib-dev # For Apache Parquet GLib (C)

Which appears to install libraries into /usr/lib/x86_64-linux-gnu/cmake/arrow

PYARROW_CMAKE_OPTIONS="-DCMAKE_MODULE_PATH=/usr/lib/x86_64-linux-gnu/cmake/arrow" python3 setup.py build_ext --inplace

Same error

cmake --build . --config release --
Scanning dependencies of target _cuda_pyx
[  5%] Compiling Cython CXX source for _cuda...
[  5%] Built target _cuda_pyx
Scanning dependencies of target _cuda
[ 11%] Building CXX object CMakeFiles/_cuda.dir/_cuda.cpp.o
/code/arrow/python/build/temp.linux-x86_64-3.7/_cuda.cpp:666:10: fatal error: arrow/c/abi.h: No such file or directory
 #include "arrow/c/abi.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/_cuda.dir/build.make:63: CMakeFiles/_cuda.dir/_cuda.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:92: CMakeFiles/_cuda.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
error: command 'cmake' failed with exit status 2

**Comment by kou** [comment]
Ah, "Arrow CPP libs installed from apache repo" means you installed Apache Arrow C++ from our APT repository not https://github.com/apache/arrow .

You can't use pyarrow master with the released Apache Arrow C++. You need to use pyarrow master with Apache Arrow C++ master.
