### ISSUE TITLE
Start plasma store with STDOUT, STDERR arguments

### ISSUE THREAD

**Issue by tpritzker** [apache/arrow#6790]
It seems that STDOUT and STDERR are always None, and non-configurable:
https://github.com/apache/arrow/blob/b789226ccb2124285792107c758bb3b40b3d082a/python/pyarrow/plasma.py#L119

Would it be possible to add them to the API? I get many printouts, which normally I would stream to a dedicated log file or to /dev/null.

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by tpritzker** [comment]
Sure, thanks:
https://issues.apache.org/jira/browse/ARROW-8302
