### ISSUE TITLE
AttributeError: module 'pyarrow' has no attribute 'filesystem'

### ISSUE THREAD

**Issue by hendrikTpl** [apache/arrow#6841]
I was using dask-distributed computing, all the package needed have installed well including pyarrow
but I found this error on pyarrow package. I have tried to google some possible solution but it's still not working. I have installed fsspec package through conda install -c conda-forge fsspec. unistall and install again dask package. please notice that mine work under anaconda environment, pythob3.6 ubuntu 16.04. someone direct me on how to fix this issue

thanks

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-a54a0de22417> in <module>
      2 import cudf
      3 import dask
----> 4 import dask.dataframe as dd

~/anaconda3/envs/vision/lib/python3.6/site-packages/dask/dataframe/__init__.py in <module>
     11     )
     12     from .groupby import Aggregation
---> 13     from .io import (
     14         from_array,
     15         from_pandas,

~/anaconda3/envs/vision/lib/python3.6/site-packages/dask/dataframe/io/__init__.py in <module>
     11     to_records,
     12 )
---> 13 from .csv import read_csv, to_csv, read_table, read_fwf
     14 from .hdf import read_hdf, to_hdf
     15 from .sql import read_sql_table

~/anaconda3/envs/vision/lib/python3.6/site-packages/dask/dataframe/io/csv.py in <module>
     19 
     20 # this import checks for the importability of fsspec
---> 21 from ...bytes import read_bytes, open_file, open_files
     22 from ...delayed import delayed
     23 from ...utils import asciitable, parse_bytes

~/anaconda3/envs/vision/lib/python3.6/site-packages/dask/bytes/__init__.py in <module>
      2 
      3 try:
----> 4     import fsspec
      5 except ImportError as e:
      6     fsspec = None

~/anaconda3/envs/vision/lib/python3.6/site-packages/fsspec/__init__.py in <module>
      1 from ._version import get_versions
      2 
----> 3 from .spec import AbstractFileSystem
      4 from .registry import get_filesystem_class, registry, filesystem
      5 from .mapping import FSMap, get_mapper

~/anaconda3/envs/vision/lib/python3.6/site-packages/fsspec/spec.py in <module>
     66     import pyarrow as pa
     67 
---> 68     up = pa.filesystem.DaskFileSystem
     69 except ImportError:
     70     up = object

AttributeError: module 'pyarrow' has no attribute 'filesystem'

**Comment by wesm** [comment]
Can you please open a JIRA issue with a reproducible example of the problem? Try creating a fresh conda environment ensuring to use `-c conda-forge` consistently. Please also provide the installed version of pyarrow

**Comment by lmsanch** [comment]
I am experiencing the same problem. I don't know what the solution is

**Comment by wesm** [comment]
We are happy to help, but not here.
