### ISSUE TITLE
How to change default path of krb5.conf?

### ISSUE THREAD

**Issue by haleyyypurple** [apache/arrow#6880]
Is it possible to read krb4.conf which is not located in '/etc/krb5.conf' ?

What I have tried after exploring related articles from other products are

1) set KRB5_CONFIG environment variable before launching python
It did not work.
2) set KRB5_CONFIG and execute kinit command, then launch python
It did not work

It seems there is a way to set different location by using 'java.security.krb5.conf' 

Does pyarrow also support it now?

**Comment by wesm** [comment]
We use the libhdfs C API `hdfsBuilderSetKerbTicketCachePath` to set a path to the Kerberos ticket. So we respect whatever configuration / environment variables that will work for libhdfs. I'm going to close this, can you open a JIRA ticket if you identify a bug fix or if you want to make a documentation clarification?

**Comment by jchakkala18** [comment]
For libhdfs, you can override the default /etc/krb5.conf by setting env **LIBHDFS_OPTS** as in example below
LIBHDFS_OPTS=" -Djava.security.krb5.conf=/opt/myapp1/conf/krb5.conf"
