### ISSUE TITLE
mutual TLS with arrow flight

### ISSUE THREAD

**Issue by ddseapy** [apache/arrow#6885]
grpc supports connections using mutual TLS with client and server certificates (ie. using google.golang.org/grpc/credentials).  Is there an example of how to do this with arrow flight libraries, or does one need to step down to the grpc-level when making requests?

Thanks!

**Comment by wesm** [comment]
Can you ask the question on dev@arrow.apache.org? A Flight implementation for Go is not yet fully implemented (there was recently a pull request with the start of a Flight library)

**Comment by ddseapy** [comment]
sure, thanks
