### ISSUE TITLE
creation of .arrow file with dummydata in javascript

### ISSUE THREAD

**Issue by GopiNeelam1925** [apache/arrow#6893]
Is it possible to create a new .arrow file with dummy data in nodejs(without python) and I couldn't find the documentation also?

Thanks In Advance.

**Comment by wesm** [comment]
Can you ask on user@arrow.apache.org? There are examples of creating IPC files in the unit tests.

**Comment by GopiNeelam1925** [comment]
Hi, I couldn't send a mail to this user@arrow.apache.org

**Comment by wesm** [comment]
You have to subscribe first by writing to user-subscribe@arrow.apache.org
