### ISSUE TITLE
Missing `take` method in pyarrow's `Table` class

### ISSUE THREAD

**Issue by gramirezespinoza** [apache/arrow#6977]
I noticed that the method `take` is implemented for the class `RecordBatch` but not for `Table` in pyarrow. On the other hand, `Take` does exists for `RecordBatch` and `Table` on arrow's C++ code.

I'm working on a project that would benefit from `take` on pyarrow's `Table` so I wrote the code + some unit tests. 

Unless there's a design/strategic reason not to have `take` on `Table`, I'd happy to create a patch.

Thanks

**Comment by wesm** [comment]
PR would be welcome. I opened https://issues.apache.org/jira/browse/ARROW-8513, so closing this

Keep en eye out that I added `ChunkedArray.take` in https://github.com/apache/arrow/pull/6970

**Comment by gramirezespinoza** [comment]
Waiting for #6970 to be approved/merged
