### ISSUE TITLE
suggestion: why not serialize complex numbers in a Python list/dict/set

### ISSUE THREAD

**Issue by xuancong84** [apache/arrow#7017]
Dear developers, I realize that complex numbers in Numpy arrays and Pandas dataframe/series can be serialized, but complex numbers in Python structures (e.g., `[1, 2.5, 3+1.j, np.nan]`) cannot be serialized. Why not make it consistent? Or is there some other reasons to concern? Thanks!

**Comment by wesm** [comment]
Can you send an email to one of the mailing lists or open a JIRA if you want to propose a development project?
