### ISSUE TITLE
AttributeError: module 'pyarrow' has no attribute 'py_buffer'

### ISSUE THREAD

**Issue by bnicholl** [apache/arrow#7056]
I have installed pyarrow with pip and I get this error when importing pyarrow

`import pyarrow`

`AttributeError: module 'pyarrow' has no attribute 'py_buffer'`

I have also uninstalled pyarrow via pip and installed pyarrow using conda, and I get the same error

**Comment by jorisvandenbossche** [comment]
What version did you install? Can you show the output of either `pip list` or `conda list` ? And can you show the full error traceback?

**Comment by bnicholl** [comment]
Full error traceback:

```
runfile('/home/boomiuser/s3_connect.py', wdir='/home/boomiuser')
Using TensorFlow backend.
Traceback (most recent call last):

  File "/home/boomiuser/s3_connect.py", line 14, in <module>
    import pyarrow.parquet as pq

  File "/home/boomiuser/pyarrow.py", line 13, in <module>
    buf = pa.py_buffer(data)

AttributeError: module 'pyarrow' has no attribute 'py_buffer'
```

pip list gives  `pyarrow        0.17.0`

conda list gives same version

**Comment by wesm** [comment]
You have a module in your project called `pyarrow.py`. Try calling the file something else and it will work. Closing this
