### ISSUE TITLE
pyarrow 0.17 atexit handler causes a segmentation fault

### ISSUE THREAD

**Issue by hantusk** [apache/arrow#7082]
When running an ASGI webapp in python with uvicorn, I am getting the following error when shutting down. Solved by reverting back to pyarrow 0.16.0

```python
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "pyarrow/types.pxi", line 2638, in pyarrow.lib._unregister_py_extension_types
SystemError: Bad call flags in _PyMethodDef_RawFastCallDict. METH_OLDARGS is no longer supported!
[1]    23073 segmentation fault  uvicorn ba...
```

**Comment by wesm** [comment]
Can you please open a JIRA issue and provide more information about your system configuration? We saw this error inside GitHub Actions but I haven't been able to reproduce it locally

**Comment by wesm** [comment]
Please also indicate which exact version of Python you're using. From searching the internet, it seems that there was a bug fix in CPython that may affect older versions of Python 3.6 or Python 3.7

**Comment by wesm** [comment]
I'm guessing you're using macOS and at least Python 3.7.5. I just opened

https://issues.apache.org/jira/browse/ARROW-8684

If you could confirm your OS and Python version that would be helpful, closing this here. Please do comment on the JIRA issue

**Comment by hantusk** [comment]
Yes, macOS running python 3.7.5 or 3.7.7. I will try and reproduce and continue commenting in the JIRA issue.
