### ISSUE TITLE
R read_parquet don't end

### ISSUE THREAD

**Issue by masaru-tsuruta** [apache/arrow#7163]
I have tried to use `read_parquet()` function as follows:
```
write_parquet(data.table(matrix(1,1)),"test.parquet")
read_parquet("test.parquet")
```
The dataset is very small. 
However, the process never end at `read_parquet()`.
Could you please show how to fix the settings or code?

I have installed the package via cran site.
The environment is as follows:
Windows10
R 3.6.3

**Comment by wesm** [comment]
Would you mind opening a JIRA issue?

**Comment by wesm** [comment]
:pray: thank you
