### ISSUE TITLE
Rust docs don't compile for arrow 0.17.0

### ISSUE THREAD

**Issue by ritchie46** [apache/arrow#7194]
The arrow docs for Rust don't compile for version 0.17.0. 

```
[INFO] [stderr] Error: "Failed to locate format/Flight.proto in any parent directory"
```
See the build logs in https://docs.rs/crate/arrow/0.17.0/builds/242085

**Comment by paddyhoran** [comment]
Hi @ritchie46, thanks for the issue report.  

We use JIRA for issue tracking so I opened an [issue](https://issues.apache.org/jira/browse/ARROW-8819) there.
