### ISSUE TITLE
cryptic warnings during installation on ubuntu 18.

### ISSUE THREAD

**Issue by randomgambit** [apache/arrow#7235]
Hello there,

Thanks again for making `arrow` a reality in R!

I noticed this strange message when I run `install.packages('arrow', dependencies = TRUE)`

```
* installing *source* package ?arrow? ...
** package ?arrow? successfully unpacked and MD5 sums checked
** using staged installation
*** Successfully retrieved C++ source
*** Proceeding without C++ dependencies
Warning message:
In unzip(tf1, exdir = src_dir) : error 1 in extracting from zip file
./configure: line 132: cd: libarrow/arrow-0.17.1/lib: No such file or directory
------------------------- NOTE ---------------------------
After installation, please run arrow::install_arrow()
for help installing required runtime libraries
```

The install ends normally and it seems I can use the package without issues. 
According to the script, I then run `install_arrow()` and get
```

* installing *source* package ?arrow? ...
** package ?arrow? successfully unpacked and MD5 sums checked
** using staged installation
*** Successfully retrieved C++ binaries for ubuntu-18.04
Warning messages:
1: In file(file, "rt") :
  URL 'https://raw.githubusercontent.com/ursa-labs/arrow-r-nightly/master/linux/distro-map.csv': status was 'Couldn't connect to server'
2: In unzip(bin_file, exdir = dst_dir) :
  error 1 in extracting from zip file
./configure: line 132: cd: libarrow/arrow-0.17.1/lib: No such file or directory
```

Again, the install ends without other errors and the package reads parquet files just fine. Should I be concerned with this missing extraction?

Thanks!

**Comment by nealrichardson** [comment]
I wouldn't expect you to be able to read Parquet files if you're getting these messages. If this issue persists (i.e. was not a temporary network connection or mirror issue), could you please open a JIRA and provide `sessionInfo()` and any other interesting properties of your setup?

**Comment by randomgambit** [comment]
thank you so much, @nealrichardson ! I actually had to manually remove the `lock` arrow file in my package folder and then run `arrow::install_arrow()` again. I now get
```

* installing *source* package ?arrow? ...
** package ?arrow? successfully unpacked and MD5 sums checked
** using staged installation
*** Successfully retrieved C++ binaries for ubuntu-18.04
Warning messages:
1: In file(file, "rt") :
  URL 'https://raw.githubusercontent.com/ursa-labs/arrow-r-nightly/master/linux/distro-map.csv': status was 'Couldn't connect to server'
2: In unzip(bin_file, exdir = dst_dir) :
  error 1 in extracting from zip file
./configure: line 132: cd: libarrow/arrow-0.17.1/lib: No such file or directory
```

I think one the issue is that my R install lives behind a firewall (and connections to CRAN are filtered). 

Perhaps could you please suggest the best way to install the package offline? Should I simply copy the zip from github and then install the project using Rstudio?

Thank you!!! you guys rock

**Comment by nealrichardson** [comment]
Please [make a JIRA issue](https://issues.apache.org/jira/projects/ARROW/issues) and we can explore solutions there.
