### ISSUE TITLE
Can we enrich the comments of DictionaryArray::Transpose?

### ISSUE THREAD

**Issue by stephenwww** [apache/arrow#7241]
First of all, thanks for developing arrow!

I wonder if you can enrich the comments of DictionaryArray::Transpose. I read through dict_internal, array_dict_test and other files and still have a difficult in understanding what this function does. 

It would be better if we can have an example in place to demonstrate how it works. e.g. input xxx will yield yyy.

https://github.com/apache/arrow/blob/45e1f2f27d10f172c9944cd6cf7596513a420f27/cpp/src/arrow/array.h#L1365

**Comment by wesm** [comment]
Can you please open a JIRA issue about this?
