### ISSUE TITLE
march not passing correctly for docker-compose run

### ISSUE THREAD

**Issue by edk4971** [apache/arrow#7307]
Building on the new ASUS Tinker Edge T, running Mendel Linux 4.0 (Day). docker-compose build commands work fine with no errors:
DEBIAN=10 ARCH=arm64v8 docker-compose build debian-cpp && DEBIAN=10 ARCH=arm64v8 docker-compose build debian-python

DEBIAN=10 ARCH=arm64v8 docker-compose run debian-python - fails with the following:

-- Running cmake for pyarrow
cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python  -G Ninja -DPYARROW_BUILD_CUDA=off -DPYARROW_BUILD_FLIGHT=on -DPYARROW_BUILD_GANDIVA=on -DPYARROW_BUILD_DATASET=on -DPYARROW_BUILD_ORC=on -DPYARROW_BUILD_PARQUET=on -DPYARROW_BUILD_PLASMA=on -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off -DPYARROW_USE_TENSORFLOW=off -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_BOOST=off -DPYARROW_GENERATE_COVERAGE=off -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_PARQUET_USE_SHARED=on -DCMAKE_BUILD_TYPE=debug /arrow/python
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/lib/ccache/gcc
-- Check for working C compiler: /usr/lib/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/g++
-- Check for working CXX compiler: /usr/lib/ccache/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- System processor: aarch64
-- Performing Test CXX_SUPPORTS_ARMV8_ARCH
-- Performing Test CXX_SUPPORTS_ARMV8_ARCH - Failed
-- Arrow build warning level: PRODUCTION
CMake Error at cmake_modules/SetupCxxFlags.cmake:338 (message):
  Unsupported arch flag: -march=.
Call Stack (most recent call first):
  CMakeLists.txt:100 (include)

-- Configuring incomplete, errors occurred!
See also "/build/python/temp.linux-aarch64-3.7/CMakeFiles/CMakeOutput.log".
See also "/build/python/temp.linux-aarch64-3.7/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1

**Comment by wesm** [comment]
Would you mind opening a JIRA issue?

**Comment by edk4971** [comment]
Done. Thank you.
https://issues.apache.org/jira/browse/ARROW-8992
