### ISSUE TITLE
Any example for communication between multi processor?

### ISSUE THREAD

**Issue by yunfan123** [apache/arrow#7325]
I want to use it between my java processor and python processor to reduce the cost of serialization and deserialization.
The java processor will send data to python processor continuously.
In my understanding, I should create a stream batch writer in java side, and this writer will write data to a file.
In python side, I should create stream batch reader to read this file.
Or I should use arrow flight in this situation?

**Comment by wesm** [comment]
Can you send an email to one of the Arrow mailing lists instead? Thanks
