### ISSUE TITLE
read_parquet() ... cannot handle Array of type uint64

### ISSUE THREAD

**Issue by AlexStefanPopovici** [apache/arrow#7333]
# the parquet test file contains some arrays of uint64 values
require(arrow)
parquetFileName = 'C:/Data/Parquet/344_20200110.parquet'
parqDF = read_parquet(parquetFileName)

Error in Table__to_dataframe(x, use_threads = option_use_threads()) : 
  cannot handle Array of type uint64

**Comment by wesm** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-9031
