### ISSUE TITLE
[Python] DataSet uses too much memory when filtering

### ISSUE THREAD

**Issue by lnicola** [apache/arrow#7338]
I'm running this query over a 14 GB Arrow IPC file:

```python
>>> ds = dataset.dataset("foo.ipc", format="ipc")
>>> t = ds.to_table(filter=dataset.field('ID') <= 1000).to_pandas()
>>> t
[snip]
[914 rows x 617 columns]
```

If I'm reading the documentation correctly, it should scan the file collecting the results, but not load it in memory. However, the RSS grows up to about 14 GB while running it, then goes back down.

**Comment by lnicola** [comment]
I guess it doesn't say that filtering _doesn't_ load the whole file, but:

> The `pyarrow.dataset` module provides functionality to efficiently work with tabular, potentially larger than memory and multi-file datasets:

But `filter` takes an expression and it would seem possible to implement without loading the full table (e.g. using `dataset.scan`), so it's quite surprising that it works like this.

Anyway, we can close this if it's by design, or we can leave it open if it's simply something not implemented yet.

**Comment by wesm** [comment]
We're actively working toward having a complete streaming query engine and a low-level data frame API that will permit analytics on filtered, memory-mapped data without having to materialize everything in memory. It has been discussed at length on the mailing list. In the meantime to read datasets into pandas requires materializing them. So I'll close this for now and refer you to further discussions over e-mail
