### ISSUE TITLE
Memory-mapping dataframes

### ISSUE THREAD

**Issue by lnicola** [apache/arrow#7339]
I originally hoped that this would be possible, but now I think it's not. Still, it's worth asking: is it possible to `mmap` a file (in whatever format) and expose it as a dataframe without making a copy of the data?

**Comment by jorisvandenbossche** [comment]
We prefer the mailing lists for such questions. Can you send an email to one of the Arrow mailing lists instead? (see the "Community" dropdown at https://arrow.apache.org/) Thanks
