### ISSUE TITLE
put license file at module root

### ISSUE THREAD

**Issue by jba** [apache/arrow#7351]
The Go package discovery service, `https://pkg.go.dev`, looks for a redistributable license at the root of a module to determine whether it can display the README and documentation for the module.

Although there is an acceptable license file at the _repo_ root, there isn't one at the _module_ root, in the `go/arrow` directory.

Please copy the `LICENSE.txt` file from the repo root to the `go/arrow` directory.

**Comment by wesm** [comment]
Would a symlink work?

**Comment by jba** [comment]
It doesn't work at present. I filed the issue linked above.

Whatever the resolution of that issue, nothing will happen soon (Go is just beginning a 6-month release cycle), so maybe you could copy temporarily.

**Comment by jba** [comment]
golang/go#39417 was closed with an explanation of why symlinks can never happen. It suggests one alternative to making the copy, which is renaming the file at root to `LICENSE`.
