### ISSUE TITLE
module 'pyarrow.fs' has no attribute 'S3FileSystem'

### ISSUE THREAD

**Issue by szdrasiak** [apache/arrow#7443]
pyarrow version = 0.17.1

**I have latest version installed but I cant import `S3FileSystem` from `pyarrow.fs` module.**

I'm trying read parquet file from S3 using `read_table` with argument `use_legacy_dataset=False` to filter data without partitions, I tried to use file system from `s3fs` package but I'm getting ```filesystem` argument must be a FileSystem instance or a valid file system URI```. I tried pass full s3 url as source without `filesystem` parameter but I'm getting `Got S3 URI but Arrow compiled without S3 support`

Why I'm missing `S3FileSystem` and is my approach to filter data on reading good?

**Comment by wesm** [comment]
S3FileSystem is not yet available in the wheel packages from PyPI. Use conda-forge to install instead. If you run into an issue other than this please open a JIRA issue

**Comment by kkozmic** [comment]
> S3FileSystem is not yet available in the wheel packages from PyPI

Is addressing that on the roadmap? Using Conda isn't a viable option for me, so that issue is a bit of a blocker

**Comment by wesm** [comment]
See https://github.com/apache/arrow/commit/d04f54bcf6e70f3b0a46fb36f68d461ef71f764c.
