### ISSUE TITLE
Why conversion from DoubleArray with nulls to numpy needs to copy?

### ISSUE THREAD

**Issue by idmitrievsky** [apache/arrow#7540]
Hello!

There is this requirement that for `to_numpy()` conversion to be zero-copy arrow array mustn't contain any nulls. If I understand correctly Arrow doesn't specify values in slots that are marked as `null` in the corresponding bitmap.

Is it possible to write numpy-specific `nan` values in places that are `null` in arrow buffer so that upon conversion there is no copying required?

**Comment by wesm** [comment]
This came up in ARROW-3263 for R. If you'd like you can open a corresponding Python issue. On the face of it, this seems rather difficult to me to do safely
