### ISSUE TITLE
Critical - PyArrow incompatibility with apache2/Django

### ISSUE THREAD

**Issue by vagarwal77** [apache/arrow#7616]
I am using Docker based deployment on AWS EKS clusters which works fine. The moment, i had added  pyarrow==0.17.1 library into the requirement file, my service had stopped responding without showing any error. The moment, i remove pyarrow from requirements.txt, every thing works fine. I am able to consistently reproduce this issue.
My docker is using debian base along with Apache. My web server is based on Django and have attached the Docker file for reference.
Seems like, PyArrow usages Apache2 and my deployment docker also use apache2 hence, some library incompatibility....
Any Apache expert here to help?

or any other way to get parquet schema without using PyArrow?
Here is my DockerFile for reference - 

```dockerfile
FROM debian:latest

# install python3 and pip3 and apache
RUN apt-get -qq update && apt-get -qq install apt-utils -y
RUN apt-get -qq install apache2 libapache2-mod-wsgi-py3 -y
RUN apt-get -qq install python3 python3-pip -y
# RUN ln -sf /usr/bin/python3 /usr/bin/python
# RUN ln -sf /usr/bin/pip3 /usr/bin/pip

# install nodejs
RUN apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -qq install -y nodejs

# copy whole structure [preserve git versioning for debugging]
COPY . /django/phai_web

# change working dir to project dir
WORKDIR /django/phai_web

# add apache apxs workaround for mod-wsgi
RUN pip3 install mod-wsgi-httpd

# pip3 install all requirements
RUN pip3 install -r requirements.txt

# Node and Npm Configuration
RUN npm install
RUN npm run build
RUN npm audit fix

# change working dir to root
WORKDIR /

# apache specifc configrations
COPY wsgi_prod.conf /etc/apache2/conf-available/
COPY security.conf /etc/apache2/conf-available/
COPY default-ssl.conf /etc/apache2/sites-available/
COPY 000-default.conf /etc/apache2/sites-available/
COPY sslCert-_precisionhealth_ai.* /etc/ssl/certs/phai/certs/

# do apache configuration
RUN a2enmod lbmethod_byrequests
RUN a2enmod ssl
RUN a2enconf wsgi_prod
RUN a2ensite default-ssl
RUN apachectl configtest

# expose ports on docker/kubernetes
EXPOSE 80
EXPOSE 443
```

**Comment by vagarwal77** [comment]
root@c3-dev-pe-dev1-b587b5574-pmnhb:/django/phai_web# /usr/sbin/apache2 -v
Server version: Apache/2.4.38 (Debian)
Server built:   2019-10-15T19:53:42

root@c3-dev-pe-dev1-b587b5574-pmnhb:/django/phai_web# service apache2 status
[ ok ] apache2 is running.

**Comment by wesm** [comment]
Can you please open a JIRA issue or write to one of the mailing lists? Thanks
