### ISSUE TITLE
Sorting on pyarrow data structures ?

### ISSUE THREAD

**Issue by healiseu** [apache/arrow#7663]
Hi, I consider sorting a fundamental operation for any in-memory data structures, including those of PyArrow.  

It would be nice if pa.array, pa.table, etc had sorting methods but I did not find any. One has to pass sorting indices calculated from some other library, such as numpy, to sort them. Sorting indices could have been calculated directly from PyArrow. Am I missing something here ? That increases significantly complexity for the developer.

Do you have any plans on implementing such a feature in the near future ?

**Comment by wesm** [comment]
This isn't where we handle feature requests. There are some sorting-related issues in JIRA; if you do not find one that describes the APIs are you are looking for, could you open a new one? Thanks
