### ISSUE TITLE
Fail to set Java VarCharVector

### ISSUE THREAD

**Issue by miriambron** [apache/arrow#7786]
While trying to use Jave VarCharVector safe set method, 
seems that if the new value size is greater then the existing one,
the  value is overriding the next bytes in the vector.

**Comment by jacques-n** [comment]
I think you have a misunderstanding of the expected use pattern of Arrow vectors. Variable-width vectors need to be populated in order. They are randomly-readable once populated but they are not randomly-writable. 

For reference, at Dremio we did build a Arrow-vector like structure for doing what you want. You can see the code here: https://github.com/dremio/dremio-oss/blob/master/sabot/kernel/src/main/java/org/apache/arrow/vector/MutableVarcharVector.java

**Comment by miriambron** [comment]
Thanks for you answer, since I need to integrate with existing system I can't use another vector type, just to create new one.
I wonder if there is any documentation I could read this information before , since I didn't reach it

**Comment by jacques-n** [comment]
Take a look at the info here:
https://github.com/apache/arrow/blob/master/docs/source/java/vector.rst
