### ISSUE TITLE
HDFS client unable to load libjvm on Windows

### ISSUE THREAD

**Issue by mpeleshenko** [apache/arrow#7843]
I've been having trouble connecting to HDFS even with the 1.0.0 pyarrow build as I run into the below error when running:
```
pa.hdfs.connect(host="host", port=port, user="user", kerb_ticket="kerb_ticket")
```
```
  File "C:\ProgramData\Continuum\Anaconda\envs\pyarrow-test\lib\site-packages\pyarrow\hdfs.py", line 210 in connect
    extra_conf=extra_conf)
  File "C:\ProgramData\Continuum\Anaconda\envs\pyarrow-test\lib\site-packages\pyarrow\hdfs.py", line 40, in __init__
    self._connect(host, port, user, kerb_ticket, extra_conf)
  File "pyarrow\io-hdfs.pxi", line 75, in pyarrow.lib.HadoopFileSystem._connect
  File "pyarrow\error.pxi", line 99, in pyarrow.lib.check_status
OSError: Unable to load libjvm: The specified module could not be found.
```

I tried the workaround mentioned in [ARROW-5236](https://issues.apache.org/jira/browse/ARROW-5236?focusedCommentId=17106888&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17106888) and got it working by copying jvm.dll into %JAVA_HOME%\lib\server\libjvm.so. It seems the logic to find libjvm is following a Linux path for some reason.

Looking into the arrow internals, I came across this:
https://github.com/apache/arrow/blob/b0d623957db820de4f1ff0a5ebd3e888194a48f0/cpp/src/arrow/io/hdfs_internal.cc#L176-L180

This looks like the same issue observed in [ARROW-1003](https://issues.apache.org/jira/browse/ARROW-1003), except that one was for libhdfs. In my situation, libhdfs is found as expected as hdfs.dll, so Windows logic is definitely followed there.
https://github.com/apache/arrow/blob/b0d623957db820de4f1ff0a5ebd3e888194a48f0/cpp/src/arrow/io/hdfs_internal.cc#L144-L145

I suspect a similar fix is needed here to change `__WIN32` to `_WIN32`.

**Comment by wesm** [comment]
Can you please open a JIRA issue?

**Comment by mpeleshenko** [comment]
@wesm This is actually the same issue described in [ARROW-5236](https://issues.apache.org/jira/browse/ARROW-5236). Can we use that one or should I still create a new JIRA issue?

**Comment by wesm** [comment]
Alright, yes just comment there and hopefully someone can investigate it and see what needs to be fixed (I don't have access to an environment where I can do so at the moment, if someone provides instructions for configuring a Windows environment for testing that would make it easier for someone to help)
