### ISSUE TITLE
Upgrading pyarrow 0.15 -> 1.0 -- deserializing fails

### ISSUE THREAD

**Issue by jhirshman** [apache/arrow#7850]
I have pandas dataframes that were serialized using pyarrow 0.15.1.
I am now trying to upgrade to 1.0.

When trying to read the old files with 1.0, I get the following error messages:
- pyarrow.lib.ArrowInvalid: Cannot read pre-1.0.0 Union array with top-level validity bitmap
- OSError: Expected IPC message of type unknown but got unknown

Is there any chance I can modify the files to preserve compatibility?

```python
import pyarrow as pa
context = pa.default_serialization_context()
# serializing
serialized = context.serialize(df).to_buffer().to_pybytes()

# deserializing
df = context.deserialize(pa.py_buffer(serialized)
```

**Comment by wesm** [comment]
These serialization functions never contained any backward compatibility guarantees and are going to be deprecated soon. I would recommend reading the files with <= 0.17.1 and writing them in some other format (Arrow IPC files or Parquet files)
