### ISSUE TITLE
Underscores at beginning of directory names create problems for open_dataset function

### ISSUE THREAD

**Issue by JoshADHD** [apache/arrow#7857]
When attempting to source parquet files for a dataset, I've found that underscores at the beginning of directory names (which I use often for OCD purposes) cause the function to not find any files.

Examples: 
`dataset <- open_dataset(
    sources = "/data/_split_data",
    partitioning = hive_partition(year = int32(), month = string())
)`

`dataset <- open_dataset(
    sources = "/_data/split_data",
    partitioning = hive_partition(year = int32(), month = string())
)`

Both of these return `FileSystemDataset with 0 Parquet files` when queried via console. If I remove underscores from the beginning of directory names, the function returns as expected.

**Comment by nealrichardson** [comment]
Thanks. Please open a JIRA and we can discuss there.

**Comment by jorisvandenbossche** [comment]
There is already an issue about this -> https://issues.apache.org/jira/browse/ARROW-9573

**Comment by jorisvandenbossche** [comment]
Actually, this is a slightly different issue, since it is not about underscores in partition keys, but in the base path. I thought this was something we already fixed.

**Comment by jorisvandenbossche** [comment]
I suppose I remember https://issues.apache.org/jira/browse/ARROW-8427, which seems somewhat similar (about only skipping underscores in child directories, not in the base path). I suppose that case fixed it for a list of file paths, and not for a directory. Opened https://issues.apache.org/jira/browse/ARROW-9644 for this
