### ISSUE TITLE
stop plasma_store from shell script

### ISSUE THREAD

**Issue by pereverges** [apache/arrow#7864]
What command can I use to stop the plasma_store from a shell script?

And can the plasma store be started from the python code?

Thank you!

**Comment by kou** [comment]
> What command can I use to stop the plasma_store from a shell script?

```bash
kill ${PLASMA_STORE_PID}
```

> And can the plasma store be started from the python code?

```python
import pyarrow.plasma as plasma
with plasma.start_plasma_store(...):
    ....
```

See also: https://github.com/apache/arrow/blob/master/python/pyarrow/plasma.py#L82

**Comment by pereverges** [comment]
Is there a way to choose the socket when using the plasma.start_plasma_store(): in the link https://github.com/apache/arrow/blob/master/python/pyarrow/plasma.py#L82 does not seem like it.
And is there a way to stop the store when starting it from python. 

Thank you for the help

**Comment by wesm** [comment]
Doesn't appear so. If you want to suggest a feature I recommend that you open a JIRA issue

**Comment by kou** [comment]
For socket path: https://arrow.apache.org/docs/developers/contributing.html#report-bugs-and-propose-features

For stopping `plasma-store-server`,

```python
with plasma.start_plasma_store(...):
    ....
```

will stop the started `plasma-store-server` when you leave the `with` block.

You can use `proc.kill()` with `plasma_store_name, proc = plasma.start_plasma_store(...)`.
