### ISSUE TITLE
Performance difference between pc.multiply vs pd.multiply

### ISSUE THREAD

**Issue by zacqed** [apache/arrow#7882]
Wanted to report the performance difference observed between Pandas and Pyarrow. 

```
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.compute as pc

df = pd.DataFrame(np.random.randn(100000000))
%timeit -n 5 -r 5 df.multiply(df)

table = pa.Table.from_pandas(df)
%timeit -n 5 -r 5 pc.multiply(table[0],table[0])
```

Results:
```
%timeit -n 5 -r 5 df.multiply(df)
374 ms ± 15.9 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)
```

```
%timeit -n 5 -r 5 pc.multiply(table[0],table[0])
698 ms ± 297 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)
```

**Comment by emkornfield** [comment]
@zacqed thanks for the report.  We use [JIRA](https://issues.apache.org/jira/secure/Dashboard.jspa) could you report this here? Also what version of pyarrow?

**Comment by zacqed** [comment]
Sure, i will open JIRA and confirm. The pyarrow version is 1.0.0

**Comment by emkornfield** [comment]
Thanks, also if you are using prebuilt wheels, I think this could be due to the target compiler settings (I would guess numpy multiply has dynamic dispatch for more recent CPUs where this is something that we are working on implementing)

**Comment by zacqed** [comment]
https://issues.apache.org/jira/browse/ARROW-9623. Closing this.
