### ISSUE TITLE
Arrow Flight from Python to JavaScript

### ISSUE THREAD

**Issue by Alex-Monahan** [apache/arrow#8054]
I made a JIRA Wish/Issue here, but I wasn't sure if I used the correct format:
https://issues.apache.org/jira/browse/ARROW-9860

Essentially, I am looking for the fastest way to send large data sets from a Python Web Server to the browser. I have my data in a Pandas dataframe, and I believe that Arrow would be the best way to send it. Is there a way to use Arrow Flight to send this data to JS running in the browser? If not, what is the fastest way to send Arrow data to the browser today? Today I am using a BufferOutputStream.

Thanks!
-Alex

**Comment by emkornfield** [comment]
Hi Alex, The JIRA looks like a reasonable start.  Thank you for filing it.  I'll close this and tag some people who might be able to give you an answer there.
