### ISSUE TITLE
dQuote error during installation in R 3.5.1

### ISSUE THREAD

**Issue by yewero** [apache/arrow#8062]
When I install arrow using`install.packages("arrow")` in R 3.5.1, an error occurred:
```
trying URL 'https://cloud.r-project.org/src/contrib/arrow_1.0.0.tar.gz'
Content type 'application/x-gzip' length 274139 bytes (267 KB)
==================================================
downloaded 267 KB

* installing *source* package ‘arrow’ ...
** package ‘arrow’ successfully unpacked and MD5 sums checked
*** Successfully retrieved C++ source
*** Building C++ libraries
**** cmake
Error in dQuote(env_var_list, FALSE) : unused argument (FALSE)
Calls: build_libarrow -> paste
Execution halted
```
The corresponding code is here:
https://github.com/apache/arrow/blob/e934a8acef5f6586362804e005d2c398b1ab5ffc/r/tools/linuxlibs.R#L302

So I think the new arrow package is not compatible with R 3.5.1?

**Comment by yewero** [comment]
I found a solution for R 3.5.1:
Install Apache Arrow based on the following page: https://arrow.apache.org/install/.
Then, the code in `linuxlibs.R` could be skipped during `install.packages("arrow")`.

**Comment by nealrichardson** [comment]
Thanks. Could you please [open a JIRA issue](https://arrow.apache.org/docs/developers/contributing.html#report-bugs-and-propose-features)? And would you be interested in submitting a fix?

**Comment by yewero** [comment]
Here is a solution: #8070

**Comment by nealrichardson** [comment]
Fixing in #8074
