### ISSUE TITLE
Plasma contains

### ISSUE THREAD

**Issue by pereverges** [apache/arrow#8110]
I ask if there is an object in plasma using client.contains(objectID), and it returns false, then I try to save the object and it says that it is already there. I know this happens beacuse another client has added the object in there. What I do not understand is why it says that the object it iis not contained in plasma. I even print the plasma store using list, and it is not there either??

How can I check if an object is stored in plasma without attempting to store it again. Thank you

**Comment by wesm** [comment]
You can ask questions on user@arrow.apache.org. Thanks

**Comment by pereverges** [comment]
I sent an email and it block me. Could you respond at these ticket please
