### ISSUE TITLE
Add dplyr group_by, summarise and mutate support in function open_dataset R arrow package

### ISSUE THREAD

**Issue by PalGal2** [apache/arrow#8121]
Hi, 
 
The open_dataset() function in the R arrow package already includes the support for dplyr filter, select and rename functions. However, it would be a huge improvement if it also could include other functions such as group_by, summarise and mutate before calling collect(). Is there any idea or projet going on to do so ? Would be it possible to include those features ?

Many thanks for this excellent job.

**Comment by wesm** [comment]
I see you opened a JIRA
