### ISSUE TITLE
 Bind failed for pathname

### ISSUE THREAD

**Issue by RishabGoel** [apache/arrow#8137]
I was trying to use plasma with poetry in the terminal with the following command:
`poetry run plasma_store -m 6000000000 -s ~/tmp`

But I keep on getting the following error message:

`/arrow/cpp/src/plasma/store.cc:1242: Allowing the Plasma store to use up to 6GB of memory.`
`/arrow/cpp/src/plasma/store.cc:1269: Starting object store with directory /dev/shm and huge page support disabled`
`/arrow/cpp/src/plasma/io.cc:145: Bind failed for pathname /home/rishabgoel/tmp`
`/arrow/cpp/src/plasma/store.cc:1167:  Check failed: socket >= 0 `
`Aborted (core dumped)`

Is there something that I am missing here?

**Comment by emkornfield** [comment]
@RishabGoel please try using the user@ or dev@ mailing list for questions.

**Comment by lwxown** [comment]
I also met the same problem,who can solve?

**Comment by spade-zd** [comment]
how to slove this problem ?  No one meet it ?
