### ISSUE TITLE
How to transform the Arrow data column to array of array efficiently?

### ISSUE THREAD

**Issue by Zarca** [apache/arrow#8217]
Hi, all:
In my case, I'm asking if there is any efficient way that i can take to transform the arrow format table  into
the format such as Array[Array[Double]]  in java or scala?

**Comment by jorgecarleitao** [comment]
Hi @Zarca,

1. In any particular language?
2. Arrow is a columnar format. Thus, it is already formatted like you wrote. If you mean is the transpose (i.e. `array[i]` corresponds to an array on which entry is the value of a column), then AFAIK there is no way without a scan i.e. 


```
for row in rows {
    for column in table.columns() {
           value = column[row]
    }
}
```

as, like I mentioned, Arrow memory alignment is at the column level, no row level.

**Comment by wesm** [comment]
This would be best discussed further on user@arrow.apache.org
