### ISSUE TITLE
ARROW_BUILD_TESTS is confusing: the description says that it is for googletest unit tests, but it also installs shared libraries, .cmake and .pc files

### ISSUE THREAD

**Issue by yurivict** [apache/arrow#8306]
It installs:
lib/cmake/arrow/ArrowTestingConfig.cmake
lib/cmake/arrow/ArrowTestingConfigVersion.cmake
lib/cmake/arrow/ArrowTestingTargets-%%CMAKE_BUILD_TYPE%%.cmake
lib/cmake/arrow/ArrowTestingTargets.cmake
lib/cmake/arrow/FindArrowTesting.cmake
lib/libarrow_testing.so
lib/libarrow_testing.so.100
lib/libarrow_testing.so.100.1.0
libdata/pkgconfig/arrow-testing.pc
```

Could you please clarify the description of ```ARROW_BUILD_TESTS```?
Based on the current description, package builds don't need to enable and install tests, but based on the installed files - I am in doubt. Test options aren't supposed to install anything.

**Comment by wesm** [comment]
hi Yuri -- could you open a Jira issue? We should change the build system so that this library is not installed when `-DARROW_BUILD_TESTS=ON`

**Comment by yurivict** [comment]
https://issues.apache.org/jira/browse/ARROW-10139
