### ISSUE TITLE
pyarrow=1.0.1 is not even usable

### ISSUE THREAD

**Issue by impredicative** [apache/arrow#8329]
Is someone going to comment on https://issues.apache.org/jira/browse/ARROW-10152 ? As it stands, the software is not even usable, period.

**Comment by nealrichardson** [comment]
Thanks for your report. Apache Arrow is supported by volunteers, so while you wait patiently for an answer to your question, please review our [code of conduct](https://www.apache.org/foundation/policies/conduct.html) for participating in the community.

**Comment by impredicative** [comment]
> Apache Arrow is supported by volunteers

This information is intended to deceive. The fact is that [Ursa Lab has sponsors](https://ursalabs.org/blog/2020-new-sponsors/) and is [industry funded](https://ursalabs.org/about/).

**Comment by wesm** [comment]
There is no deception. Some individuals work on Apache Arrow as part of their job responsibilities, but the work that is contributed to the project is _volunteered_ by these organizations. They have their own priorities; they do not work for you.
