### ISSUE TITLE
how to test whether arrow works correctly in R?

### ISSUE THREAD

**Issue by randomgambit** [apache/arrow#8384]
Hello there!

I managed to install the great `arrow` on my linux system (with Rstudio) and it seems to be working great. However, I was wondering if a test script is available (like in Pandas) to check that the package works indeed correctly? Does that make sense?

Thanks and keep up the great work!

**Comment by wesm** [comment]
You can run the vignette examples, or the unit test suite, I think. If you wanted something more integrated with the install you could open a JIRA issue to describe exactly what you would like to implement
