### ISSUE TITLE
What is the status of 2.0?

### ISSUE THREAD

**Issue by SMillerDev** [apache/arrow#8465]
There is a tagged release, but the website says 1.0.1 is the latest version. And the changelog doesn't even mention that version. What is the latest release of apache-arrow?

**Comment by nealrichardson** [comment]
The release vote is still open: https://lists.apache.org/thread.html/r7aef4670c48c32a889a98ef445eb46f1d4a900199b308a6db788ddb5%40%3Cdev.arrow.apache.org%3E

GitHub tags are not authoritative--only the published artifacts on apache.org are official releases.

**Comment by SMillerDev** [comment]
Thanks
