### ISSUE TITLE
[R] Trouble Installing Package on Linux with S3 support

### ISSUE THREAD

**Issue by mgahan-he** [apache/arrow#8508]
When I attempt to install the newest package on Ubuntu Bionic, the code seems to be converting my environmental variable `ARROW_S3=ON` to `ARROW_S3=OFF`. 

![image](https://user-images.githubusercontent.com/45569512/96879322-c457b480-1430-11eb-8abb-06e7ba2beefd.png)

The issue seems to be with the `libcurl4-openssl-dev` package, but I already have this package installed.

![image](https://user-images.githubusercontent.com/45569512/96879558-0bde4080-1431-11eb-9163-2ff14c1ff96d.png)

I am guessing that I am making a simple error, but curious if anyone else has come upon a similar issue with the install?

Thanks for the great package,
Mike

**Comment by nealrichardson** [comment]
We use Jira for issue tracking; could you please report [there](https://issues.apache.org/jira/browse/ARROW)?

**Comment by mgahan-he** [comment]
Thanks Neal - reported here: https://issues.apache.org/jira/browse/ARROW-10371
