### ISSUE TITLE
Pyarraw V2 no release note

### ISSUE THREAD

**Issue by raphaelauv** [apache/arrow#8514]
Hello , the pypi version of pyarraw is 2.0.0 since Oct 19, 2020 ( previous was 1.0.1 )

https://pypi.org/project/pyarrow/2.0.0/#history

I could not find any release note explaining the changes and breaking changes.

Do you know where I can find it ?

Thank you

**Comment by wesm** [comment]
We'll publish a blog post today probably about the release. You can look at the changelog in the root of the git repository int he meantime.

**Comment by wesm** [comment]
Keep in mind that the major version bump does not indicate that there *are* breaking API changes but that there *may be*

**Comment by raphaelauv** [comment]
https://arrow.apache.org/release/2.0.0.html
