### ISSUE TITLE
Adding nullable columns to RecordBatch

### ISSUE THREAD

**Issue by olgacarpenter** [apache/arrow#8684]
Hello, 
I am very new to this library in C#, so forgive my ignorance.

I am trying to create an arrow file from database rows.  If I didn't have nullable properties in my model, I can accomplish this easily by following the [example](https://github.com/apache/arrow/blob/master/csharp/examples/FluentBuilderExample/Program.cs) on this repo.  However, I do have nullable columns and I've been struggling trying to make it work.

After digging a little more, i modified my code to be:
```
var memoryAllocator = new NativeMemoryAllocator(alignment: 64);
IEnumerable<Visit> visits = _context.Visit.Take(10).AsEnumerable<Visit>();
var recordBatch = new RecordBatch.Builder(memoryAllocator)
                .Append("TotalCharges", true, col => col.Float(array => visits.Select(x => x.TotalCharges != null ? array.Append((float)x.TotalCharges) : array.AppendNull())))
                .Build();
```

I don't get any errors from this but the file seems to be in invalid format.  It doesn't open.
Any ideas on what i'm doing wrong and how to fix it?  

Help is appreciated!

**Comment by jorgecarleitao** [comment]
Hey @olgacarpenter we generally do not use the github issues and instead rely on mailing lists, e.g. user@arrow.apache.org. Could you post this question over there?
