### ISSUE TITLE
Is it possible to leverage arrow to fast insert data into a data table?

### ISSUE THREAD

**Issue by dclong** [apache/arrow#8737]
The class [JdbcToArrow](https://github.com/apache/arrow/blob/master/java/adapter/jdbc/src/main/java/org/apache/arrow/adapter/jdbc/JdbcToArrow.java) is very helpful for fetch large data using JDBC (especially in Python). 
I wonder is there a similar tool for inserting large data into a data table quickly?

**Comment by wesm** [comment]
We handle user/developer questions on user@arrow.apache.org or dev@arrow.apache.org as appropriate.
