### ISSUE TITLE
Typescript Arrowjs Class 'RecordBatch<T>' incorrectly extends base class 'StructVector<T>'

### ISSUE THREAD

**Issue by vikashsingh009** [apache/arrow#8812]
I have imported arrowjs in typescript  like 

import { Table } from 'apache-arrow';

const arrow = readFileSync('simple.arrow');
const table = Table.from([arrow]);

but  when   i  am   building  the  project  getting  exception  like

ERROR in node_modules/apache-arrow/ipc/reader.d.ts:236:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'schema' must be of type 'Schema<T>', but here has type 'Schema<any>'.
    
    236     schema: Schema;
            ~~~~~~
    
      node_modules/apache-arrow/ipc/reader.d.ts:189:5
        189     schema: Schema<T>;
                ~~~~~~
        'schema' was also declared here.
![image](https://user-images.githubusercontent.com/7962189/100761756-41575000-3419-11eb-95fa-329c40afe3f7.png)

**Comment by wesm** [comment]
Would you mind opening a Jira issue? Thanks

**Comment by nevi-me** [comment]
Hi @vikashsingh009, before opening a JIRA, can you please confirm if you're using version 2.0.0 of arrow, as this issue was opened in https://issues.apache.org/jira/browse/ARROW-8394, and was fixed with PR #8216, which was released on ~22 October.

**Comment by vikashsingh009** [comment]
@nevi-me,  i  am  sure  i  am  using latest  "apache-arrow": "^2.0.0", and  typescript  version ^4.0.2,but  i  still  see  the above   error

please  suggest  if  i  can  able to open  issues

**Comment by nevi-me** [comment]
Thanks for checking. Yes, please go ahead. I'll close this as you'll open a JIRA.

**Comment by Vishwanathkinekar** [comment]
I am getting the exact same error. 
I am using
Apache-Arrow: 3.0.0
Node: 14.15.5

And Angular version is attached screenshot.
![image](https://user-images.githubusercontent.com/14130778/107930840-85320e00-6fa1-11eb-907d-ad7f7d2b57fa.png)
