### ISSUE TITLE
Are the Date Logical Type and Date Converted Type implemented?

### ISSUE THREAD

**Issue by protalis** [apache/arrow#8987]
```
parquet::schema::PrimitiveNode::Make(
                    "req1",
                    parquet::Repetition::REQUIRED,
                    parquet::DateLogicalType::Make(),
                    parquet::Type::INT32
            );
```
Fails on ```outParquetStream << int32val``` with:
 ```Column converted type mismatch.  Column 'req1' has converted type[DATE] not 'INT_32'```

I get the same error with I use the older style declaration:
```
parquet::schema::PrimitiveNode::Make(
                    "req1",
                    parquet::Repetition::REQUIRED,
                    parquet::Type::INT32
                    parquet::ConvertedType::type::DATE
            );
```
The field names match, so I know it is not a field sequencing issue.

All other code is boilerplate from the ```stream-reader-writer.cc``` example.. just the field node def changed and writing an int32.  I used this spec as a guide.  (https://github.com/apache/parquet-format/blob/master/LogicalTypes.md)

If LogicalTypes are implemented, such as the DATE example, above, can you help with whatever I am doing wrong?  Also, why doesn't the older style declaration work, either?

Thank you in advance for any help you can give.

**Comment by wesm** [comment]
Could you write to either the dev@ or user@ mailing lists? Thanks

**Comment by emkornfield** [comment]
I believe this was addressed on the mailing list.

**Comment by salqadri** [comment]
What is the answer to this? I am not on any mailing list, so could you guys please repost here @emkornfield @wesm ?
