### ISSUE TITLE
Is there a bug in flight AddWritableBuffer

### ISSUE THREAD

**Issue by kangpinghuang** [apache/arrow#8994]
https://github.com/apache/arrow/blob/9bab12f03ac486bb8270f031b83f0a0411766b3e/java/flight/flight-core/src/main/java/org/apache/arrow/flight/grpc/AddWritableBuffer.java#L94

is this line redundant？
this will copy the data from buf to OutputStream, which can not realize zero-copy.

**Comment by wesm** [comment]
Can you please open a Jira issue?

**Comment by kangpinghuang** [comment]
ok, I open a jira issue: https://issues.apache.org/jira/browse/ARROW-11066

**Comment by jorisvandenbossche** [comment]
Closing the issue here, follow-up can be done on the JIRA.
