### ISSUE TITLE
Python sdist for pyarrow 2.0.0 on PyPI

### ISSUE THREAD

**Issue by johnsushant** [apache/arrow#9003]
Python source tar.gz has not been uploaded on PyPI for pyarrow==2.0.0

I do understand that installing from sdist would require multiple other dependencies like Apache Arrow C++ binaries installed.
Many organizations have restrictions on being able to directly use binary wheels. It would be a massive help if a source distribution could also be published.

**Comment by kou** [comment]
It's uploaded:

  * https://pypi.org/project/pyarrow/#files
  * https://files.pythonhosted.org/packages/fd/b7/78115614c4b227796cc87fff907930f6ae6dd999c5000d3d6ae5c2e54582/pyarrow-2.0.0.tar.gz

But it has a problem: https://issues.apache.org/jira/browse/ARROW-10777
