### ISSUE TITLE
multiple versions of pyarrow installed?

### ISSUE THREAD

**Issue by vgoklani** [apache/arrow#9071]
Hey there,

Apologies for the beginner-level question, but it appears that pypy has somehow installed multiple versions of pyarrow on our system. We have a long list of libraries that are installed from requirements.txt, and we didn't realize that this process could install multiple versions of the same library? If that's not the case, how is it possible that we are able to uninstall two different versions? 

	root@b5d80f9670ea:~/src# pip uninstall -y pyarrow
	Found existing installation: pyarrow 2.0.0
	Uninstalling pyarrow-2.0.0:
	  Successfully uninstalled pyarrow-2.0.0
	root@b5d80f9670ea:~/src# pip uninstall -y pyarrow
	Found existing installation: pyarrow 0.15.1
	Uninstalling pyarrow-0.15.1:
	  Successfully uninstalled pyarrow-0.15.1

Unfortunately one of the other packages, transformers, is complaining that version 0.15.1 is too old, and throwing an error. It's ignoring the fact that the newer version is installed. 

Thanks! 

Happy New Year!

**Comment by xhochy** [comment]
This could just be a usage problem with the different ways to install packages with pip (in your virtualenv, via --user and systemwide). Nothing special with Arrow here. 

Note that pyarrow won't be working on PyPy, not sure how you even installed it there as it doesn't compile currently.

**Comment by pitrou** [comment]
Not a pyarrow issue, closing.
