### ISSUE TITLE
Reading Feather File from Custom Offset

### ISSUE THREAD

**Issue by pokemaster7** [apache/arrow#9104]
Is it possible to embed a feather file in another file (with known offset/length) and read the feather portion in a correct and performant way?

Here is a naive idea of what I'm trying to do, though it throws an error for some reason:

``` python
import pandas as pd
import numpy as np
import os

df = pd.DataFrame(np.random.randint(0,100,size=(15, 4)), columns=list('ABCD'))
pth = "TMP"
with open(pth, "wb") as fh:
  fh.write(b"\x01") # custom header, one byte
  df.to_feather(fh)
with open(pth, "rb") as gh:
  gh.read(1) # read header
  print(pd.read_feather(gh)) # throws 'pyarrow.lib.ArrowInvalid: Not a Feather V1 or Arrow IPC file'

**Comment by pitrou** [comment]
Feather files are accessed using seeks in the file, so I don't think that will work indeed. You can use a Arrow IPC stream, though, which should have similar performance characteristic.

**Comment by pitrou** [comment]
See https://arrow.apache.org/docs/python/api/ipc.html#inter-process-communication and especially the `new_stream` and `open_stream` functions.

**Comment by pokemaster7** [comment]
Thanks @pitrou. I am somewhat disappointment that the file read API doesn't support offsets (and that passing in a partially read file object doesn't do the intuitive thing). But that workaround does work.
