### ISSUE TITLE
Needs a handling for missing columns in parquet file

### ISSUE THREAD

**Issue by jasonkhadka** [apache/arrow#9194]
Currently there is no way to handle the error raised by missing columns in parquet file. If a column passed in `columns=[item1, item2, item3]` is missing it just raises : 
`ArrowInvalid: Field named 'item3' not found or not unique in the schema.`

There is no way to handle this. The ArrowInvalid also does not carry any information that can give out the field name so that in next try this filed can be ignored.

https://github.com/apache/arrow/blob/ec18db9dbde801781109095dc4c7198dc35bbc07/python/pyarrow/parquet.py#L1657

**Comment by jorisvandenbossche** [comment]
What kind of way to handle this are you looking for? 
Like a keyword to indicate that missing columns in this list can be ignored instead of raising an error?

> The ArrowInvalid also does not carry any information that can give out the field name so that in next try this filed can be ignored.

The name of the missing field is in the error message?

**Comment by jasonkhadka** [comment]
> Like a keyword to indicate that missing columns in this list can be ignored instead of raising an error?

Yes a `error='ignore'`  keyword would be a perfect solution. 


> The name of the missing field is in the error message?

Name of the missing field is there in the error message. But if you want to get the field name out of error so that you can use that to drop it from the list of columns and try again to read the parquet, it is difficult. 
The error only contains the message, and it would be great if the error also included the field name as property, so error handling could be built.

**Comment by westonpace** [comment]
Do you know the data type of the missing column?  If so, you can use the datasets API to read the table.  The datasets API can take in a expected schema that has all columns that might be asked for.  This allows for dataset evolution where you have a master schema for a collection of files but individual files might not have all the columns.

```
import pandas as pd
import pyarrow as pa
import pyarrow.dataset as pads

read_columns = ['a','b','X']

df = pd.DataFrame({'a': [1, 2, 3], 'b': ['foo', 'bar', 'jar']})
file_name = '/tmp/my_df.pq'
df.to_parquet(file_name)

schema = pa.schema([
    ('a', pa.int64()),
    ('b', pa.string()),
    ('X', pa.int32())
])

# df = pd.read_parquet(file_name, columns = read_columns)                                                                                                                                                  
ds = pads.dataset([file_name], schema=schema)
table = ds.to_table()
print(table)
print(table.column('X').to_pylist())
```

**Comment by jasonkhadka** [comment]
I guess this could be done, but it would be convenient if there was a simple argument to ignore the columns that are not present on the dataset. 
Also it might not be possible to get all the dtype before reading the parquet.

**Comment by westonpace** [comment]
That seems like a reasonable request.  Could you please report this feature request on Arrow's [JIRA](https://issues.apache.org/jira/browse/ARROW)?.

**Comment by emkornfield** [comment]
closing.  I think opening a feature request/bug report through JIRA is the next step.

**Comment by PoojaRavi1105** [comment]
@emkornfield Did you end up opening a feature request in JIRA for this? If so, can you please share the link here.

**Comment by emkornfield** [comment]
I did not.  If this is still needed, we can likely reopen since Github issues are now the canonical ways of tracking features.
