### ISSUE TITLE
Filter out columns in compressed IPC format

### ISSUE THREAD

**Issue by Yuhta** [apache/arrow#9239]
We have a use case in C++ to get several columns out from a compressed table (serialized in IPC streaming format) *without decompressing then compressing the data*.  I can see from the flatbuffers definition that each columns are serialized and compressed separately, so this is doable in theory.  I am wondering if there is already some code in arrow-cpp to do this, or we have to generate our flatbuffers code and manipulate on the IPC bytes ourselves?

**Comment by wesm** [comment]
You can ask user questions on user@arrow.apache.org
