### ISSUE TITLE
Error trying to build Arrow 3.0 (Java binding)

### ISSUE THREAD

**Issue by joao-parana** [apache/arrow#9250]
I'm trying to build version 3.0.0 of Arrow (Java binding) available at https://github.com/apache/arrow/archive/apache-arrow-3.0.0.zip  but the "Arrow Flight GRPC" project doesn't work.

I'm using the command below:

```bash
mvn install -DskipTests -D maven.test.skip = true -fae
```

All other artifacts are generated and installed correctly

I am using a MacOS BigSur version 11.1 and JVM 11

The error reported by Maven is: **"Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.1:analyze-only (analyze) on project flight-grpc: Dependency problems found"**

Any suggestions to solve this problem?

Tanks.

**Comment by kou** [comment]
Could you open an JIRA issue with full log?
https://issues.apache.org/jira/browse/ARROW

FYI: We have apache-arrow-3.0.0 tag but we don't release 3.0.0 yet. We're verifying RC: https://lists.apache.org/list.html?dev@arrow.apache.org
