### ISSUE TITLE
Integrate CUDA memory capacity to plasma storage

### ISSUE THREAD

**Issue by VoVAllen** [apache/arrow#9268]
Hi,

I found there's some codes inside plasma storage are for the cuda memory. Do you have any plan to provide the similar API on cuda memory as what shared memory have?

Thanks!

**Comment by VoVAllen** [comment]
Also if I want to integrate only plasma storage into my project, what's the suggested way to do so? c_glib or other way?

**Comment by kou** [comment]
I'm not sure what API do you imagine but I think that we already have it: https://github.com/apache/arrow/blob/master/cpp/src/plasma/test/client_tests.cc#L867-L1076

If your project uses C++, Apache Arrow C++ is recommended.

**Comment by VoVAllen** [comment]
Thanks. It's exactly what I'm looking for. 

I found the header files are separated in different folders, which makes it a bit hard to track all those thing. But I found it's well organized in pyarrow's package. Is there any instruction on this or how can I track those header file in my own projects?

Thanks!

**Comment by kou** [comment]
https://arrow.apache.org/docs/cpp/cmake.html
You need to use `ArrowCUDA` for CMake package name.

**Comment by VoVAllen** [comment]
Does the pip package include the cuda capacity? Also if user install pyarrow by pyenv, can `find_package(arrow)` find the corresponding package?

**Comment by kou** [comment]
It doesn't.
Conda package supports CUDA: https://anaconda.org/conda-forge/pyarrow

If you have further questions, please use `user@arrow.apache.org` mailing list: https://arrow.apache.org/community/
We don't use GitHub issue for user forum.
