### ISSUE TITLE
Appending vector to vector which had been not assigned with VectorAppender.append throw exception

### ISSUE THREAD

**Issue by ShaoxiongTang** [apache/arrow#9360]
In our project , when we attempt to append some vector to output buffer which is created by 'VectorSchemaRoot.create' method and had been not set values, we got follow error message 

![image](https://user-images.githubusercontent.com/7252486/106268144-a38bd000-6265-11eb-9cce-829aa0e19631.png)

Related code: 
![image](https://user-images.githubusercontent.com/7252486/106268220-c0280800-6265-11eb-9b8b-c7db9c3b4ac2.png)

Could we change code like this ?
``` 
int targetDataSize = targetVector.getValueCount() == 0 ?
            0 : targetVector.getOffsetBuffer().getInt((long)targetVector.getValueCount() * BaseVariableWidthVector.OFFSET_WIDTH);
```

**Comment by wesm** [comment]
This sounds like possibly a bug report, could you open a Jira issue? Thanks
