### ISSUE TITLE
DataFrame api sync send

### ISSUE THREAD

**Issue by capacman** [apache/arrow#9400]
Hi,
I am new to rust so my question can be nonsense so thank you for your patience in advance. I am trying implement a small single node query service and it will return its data over grpc(not flight). When i try to use execution context and dataframe api behind a tonic service,compiler gives error:
the trait `Sync` is not implemented for `dyn datafusion::dataframe::DataFrame`
as i understand all futures should be sync+send for tonic and currently dataframe api is not sync+send. Are there any plans to make it sync+send? Or should i look for other ways to implement it?Currently i am using this method
https://docs.rs/tokio/1.1.1/tokio/task/struct.LocalSet.html#use-inside-tokiospawn

**Comment by emkornfield** [comment]
Hi @capacman We prefer to handle discussions on the dev@ or user@ arrow mailing lists.  Would you mind asking your question there?

**Comment by capacman** [comment]
Thank you for quick response. I send the mail
