### ISSUE TITLE
Impossible to mail user@arrow.apache.org

### ISSUE THREAD

**Issue by simPod** [apache/arrow#9427]
```
Hi. This is the qmail-send program at apache.org.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<user@arrow.apache.org>:
Must be sent from an @apache.org address or a subscriber address or an address in LDAP.
```

Where to "ask questions"? Thanks

**Comment by paddyhoran** [comment]
Hi @simPod. did you subscribe?  You have to subscribe before you can send e-mail to that list.  Just send an e-mail to user-subscribe@arrow.apache.org or click the subscribe link [here](https://arrow.apache.org/community/)

**Comment by simPod** [comment]
Aight, got it. Thx!
