### ISSUE TITLE
Out-of-heap memory leaks in FlightClient.getStream

### ISSUE THREAD

**Issue by UglyLLJ** [apache/arrow#9451]
I'm trying to use Arrow and Flight in my Java project, I used FlightClient.getStream to request data from a remote node, but I found the allocator's allocated memory size grows with the request.

Java version: 8

Flight&Arrow version: 3.0.0

 

Here's a snippet of my code, I found the allocated memory of flithStream still exist after root.close:

try (FlightStream flightStream = client.getStream(ticket, CallOptions.timeout(1, TimeUnit.MILLISECONDS))) {
    VectorSchemaRoot root = flightStream.getRoot();
    root.clear();
    while (flightStream.next())

{         // transfer root to ArrowRecordBatch and execute         dispatchNext(shuffleChunk, root);         root.clear();     }
    root.close();
} catch (FlightRuntimeException fe) {
    String errorMsg = "IndexReadOperator read index fail ={}  "+indexChunkDesc.toString();
    LOGGER.error(errorMsg, fe);
    throw new NetworkException(errorMsg, fe);
} catch (Exception e)

{     LOGGER.error("IndexReadOperator read index fail!", e); throw new NetworkException("IndexReadOperator getStream fail! ", e); }
 

Is this a bug or am I using it incorrectly?

**Comment by emkornfield** [comment]
HI @UglyLLJ we generally prefer questions be asked on the user@ or dev@ mailing list as appropriate.  My guess with the limited code example is that in the code if you are transferring data to a ArrowRecordBatch so memory will persist unless the record batch is closed as well.

**Comment by emkornfield** [comment]
If this doesn't fix the issue, please try emailing one of the lists mentioned above.
