### ISSUE TITLE
pyarrow.lib.ArrowInvalid: Could not convert with type numpy.ndarray: tried to convert to int

### ISSUE THREAD

**Issue by bhavitvyamalik** [apache/arrow#9462]
Hi, 
I came to know that pyarrow has this limitation of not storing N-dimensional array. After looking into this issue, I decided to represent a N-dimensional array as a list of arrays i.e.
```
data = np.zeros((5, 3), dtype=np.uint8)
data = list(data)
```
inorder to preserve the dtype but when it comes to typecasting and writing it into array (from list) `pyarrow.array(data, type=type)` it gives the following error:

`pyarrow.lib.ArrowInvalid: Could not convert [0 0 0] with type numpy.ndarray: tried to convert to int`

Is there any way to avoid this issue? I just want to preserve the dtype from numpy array before converting it to list so that while writing it to pyarrow array format I can recognise its dtype and subsequently write it in that numpy dtype format.

**Comment by emkornfield** [comment]
Hi @bhavitvyamalik we prefer questions like this get asked through the user@arrow.apache.org mailing list.  It seems that you should also be including what type you are passing to pyarrow.array(...)

On an older version of arrow the following works for me with pyarrow3:
```
>>> pyarrow.array(list(data))
<pyarrow.lib.ListArray object at 0x11866c980>
[
  [
    0,
    0,
    0
  ],
  [
    0,
    0,
    0
  ],
  [
    0,
    0,
    0
  ],
  [
    0,
    0,
    0
  ],
  [
    0,
    0,
    0
  ]
]
>>> pyarrow.array(list(data)).type
ListType(list<item: uint8>)
```

**Comment by bhavitvyamalik** [comment]
Mail delivery to this address was failing yesterday. Do I need to subscribe to mailing list inorder to send mails to this address?

**Comment by emkornfield** [comment]
Yes you need to subscribe to the list to be able to send mail.
