### ISSUE TITLE
[Python][macOS] Using encryption with server verification disabled is unsupported.

### ISSUE THREAD

**Issue by amasend** [apache/arrow#9525]
Hi all,

I am trying to manage a connection to the `flight server` via `pyarrow` library and encountered below problem:

```python
Traceback (most recent call last):
  File "...", line 22, in <module>
    "grpc+tls://some_address:9443", disable_server_verification=True)
  File "pyarrow/_flight.pyx", line 1047, in pyarrow._flight.FlightClient.__init__
  File "pyarrow/_flight.pyx", line 1093, in pyarrow._flight.FlightClient.init
  File "pyarrow/_flight.pyx", line 80, in pyarrow._flight.check_flight_status
  File "pyarrow/error.pxi", line 105, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Using encryption with server verification disabled is unsupported. Please use a release of Arrow Flight built with gRPC 1.27 or higher.
```

I am using something similar to this:
```python
from pyarrow import flight
import pyarrow as pa

class TokenClientAuthHandler(flight.ClientAuthHandler):
    """An example implementation of authentication via handshake."""
    def __init__(self):
        super().__init__()
        self.token = bytes('Bearer ' + token, 'utf-8')
    def authenticate(self, outgoing, incoming):
        outgoing.write(self.token)
        self.token = incoming.read()
    def get_token(self):
        return self.token

read_client = flight.FlightClient(
    "grpc+tls://some_address:9443", disable_server_verification=True)
```
The same code on `Ubuntu` linux is working fine.
Here are package versions that I am using:
- `pyarrow==3.0.0`
- `grpcio==1.35.0`
- `grpc-cpp==1.35.0`
My environment is `conda`, `3.6 / 3.7`

I'v tried to change/adjust these versions somehow but with no success.
Maybe you will know what cause the problem as I cannot find anything besides this thread: https://www.mail-archive.com/dev@arrow.apache.org/msg21050.html

I will appreciate your answers!

**Comment by xhochy** [comment]
Can you open a JIRA https://issues.apache.org/jira/projects/ARROW and paste the output of `conda list` there?

**Comment by amasend** [comment]
JIRA issue: https://issues.apache.org/jira/browse/ARROW-11695#
