### ISSUE TITLE
arrow read_parquet failure in R v 3.5.1

### ISSUE THREAD

**Issue by garimagupta25** [apache/arrow#9617]
I used install.packages("arrow") in ubuntu 16.04 and am able to load the package just fine but while running read_parquet(), I get the following error -

Error in io___MemoryMappedFile__Open(path, mode) : 
  Cannot call io___MemoryMappedFile__Open(). See https://arrow.apache.org/docs/r/articles/install.html for help installing Arrow C++ libraries. 

Please help.

Detailed installation logs below -

------------------------- NOTE ---------------------------
See https://arrow.apache.org/docs/r/articles/install.html
for help installing Arrow C++ libraries
---------------------------------------------------------
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c array.cpp -o array.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c array_from_vector.cpp -o array_from_vector.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c array_to_vector.cpp -o array_to_vector.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c arraydata.cpp -o arraydata.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c arrowExports.cpp -o arrowExports.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c buffer.cpp -o buffer.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c chunkedarray.cpp -o chunkedarray.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c compression.cpp -o compression.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c compute.cpp -o compute.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c csv.cpp -o csv.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c dataset.cpp -o dataset.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c datatype.cpp -o datatype.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c expression.cpp -o expression.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c feather.cpp -o feather.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c field.cpp -o field.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c filesystem.cpp -o filesystem.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c imports.cpp -o imports.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c io.cpp -o io.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c json.cpp -o json.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c memorypool.cpp -o memorypool.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c message.cpp -o message.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c parquet.cpp -o parquet.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c py-to-r.cpp -o py-to-r.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c recordbatch.cpp -o recordbatch.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c recordbatchreader.cpp -o recordbatchreader.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c recordbatchwriter.cpp -o recordbatchwriter.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c scalar.cpp -o scalar.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c schema.cpp -o schema.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c symbols.cpp -o symbols.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c table.cpp -o table.o
g++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG  -I"/home/cdsw/R/x86_64-pc-linux-gnu-library/3.5/cpp11/include" -I/usr/local/include   -fpic  -g -O2 -c threadpool.cpp -o threadpool.o
g++ -std=gnu++11 -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o arrow.so array.o array_from_vector.o array_to_vector.o arraydata.o arrowExports.o buffer.o chunkedarray.o compression.o compute.o csv.o dataset.o datatype.o expression.o feather.o field.o filesystem.o imports.o io.o json.o memorypool.o message.o parquet.o py-to-r.o recordbatch.o recordbatchreader.o recordbatchwriter.o scalar.o schema.o symbols.o table.o threadpool.o -L/usr/local/lib/R/lib -lR

**Comment by nealrichardson** [comment]
The error message refers you to a vignette with troubleshooting information: https://arrow.apache.org/docs/r/articles/install.html#troubleshooting-1

Please check the things it suggests and if you still have trouble, open a JIRA issue with the details.
