### ISSUE TITLE
Is there an API to deserialize ListVector into double[] efficiently ?

### ISSUE THREAD

**Issue by fabiencelier** [apache/arrow#9636]
Hello,

I am receiving a `ListVector` wrapping a `Float8Vector` and I'd like to deserialize them into Java `double[]` (each array has 1000 elements).

At the moment I do the following:

```java
public static List<double[]> deserialize(ListVector listVector) {
  final Float8Vector underlying = (Float8Vector) listVector.getDataVector();
  final List<double[]> deserialized = new ArrayList<>();
  for (int index = 0; index < listVector.getValueCount(); index++) {
    final int first = listVector.getElementStartIndex(index);
    final int last = listVector.getElementEndIndex(index);
    final int size = last - first;
    final double[] data = new double[size];
    for (int i = 0; i < size; i++) {
      data[i] = underlying.get(first + i);
    }
  }
  return deserialized;
}
```

But it feels inefficient to retrieve the values one by one, is there a way to get all the values between `first` and `last` directly into a `double[]` with one call ?

**Comment by westonpace** [comment]
cc @emkornfield @liyafan82

**Comment by liyafan82** [comment]
The float8 data in the list vector and double array are both in a continuous memory region. 
So in theory, it is possible to populate the data in the `double[]` in a single copy. 

The unsafe API provides such functionality, and please note that:
1. There is some header space between the object address and the data address in the `double[]`
2. In the Arrow vector, there may be nulls in the slots, the behavior of such slots should be defined.

**Comment by emkornfield** [comment]
I agree with @liyafan82 assessment.  If there are follow-up questions, we should discuss on the user@ or dev@ mailing list.
