### ISSUE TITLE
[Python] How to append rows of a table to a memory mapped file?

### ISSUE THREAD

**Issue by mBaratta96** [apache/arrow#9679]
Hello, 
as you can see in the code below, I'm having troubles adding new rows to a Table saved in a memory mapped file.
I just want to write the file again with the new rows.
```python
    source = pa.memory_map(path, 'r')
    table = pa.ipc.RecordBatchFileReader(source).read_all()
    schema = pa.ipc.RecordBatchFileReader(source).schema
    new_table = create_arrow_table(schema.names) #new table from pydict with same schema and random new values
    updated_table = pa.concat_tables([table, new_table], promote=True)   
    source.close()
    with pa.MemoryMappedFile(path, 'w') as sink:
        with pa.RecordBatchFileWriter(sink, updated_table.schema) as writer:
           writer.write_table(table)
```
I get an Exception stating that the memory mapped file is not closed.
`ValueError: I/O operation on closed file `
Any suggestion?

**Comment by westonpace** [comment]
Do you mind closing this now that you've accepted the SO answer?  If you want to discuss resizing strategies for memory maps and maybe what you are planning at a higher level in hopes of getting suggestions I would recommend sending a message to the [user mailing list](https://arrow.apache.org/community/)
