### ISSUE TITLE
[Golang] Create ipc format for ipc Reader

### ISSUE THREAD

**Issue by hunght3101** [apache/arrow#9735]
@user 
I am a new golang in Apache Arrow.
Now i am trying serialization Apache Arrow to Flatbuffers using ipc package.
But i dont understand to create a message ipc format for input of ipc.Reader function.
Could you show me any example message ipc format ? or method for create a message ipc format?
My source:
```
import (
	"fmt"
	"github.com/apache/arrow/go/arrow"
	"github.com/apache/arrow/go/arrow/array"
	"github.com/apache/arrow/go/arrow/ipc"
	"github.com/apache/arrow/go/arrow/memory"
	"io"
	"strings"
)
func main()  {

	meta := arrow.NewMetadata([]string{"k1", "k2"}, []string{"v1", "v2"})
	mem := memory.NewGoAllocator()
	schema := arrow.NewSchema(
		[]arrow.Field{
			arrow.Field{Name: "f1-i32", Type: arrow.BinaryTypes.String},
			arrow.Field{Name: "f2-f64", Type: arrow.BinaryTypes.String},
		},
		&meta,
	)

	b := array.NewRecordBuilder(mem, schema)
	defer b.Release()

	b.Field(0).(*array.StringBuilder).AppendValues(
		[]string{"1", "2"},
		nil,
	)
	b.Field(0).(*array.StringBuilder).AppendValues(
		[]string{"1", "2","1", "2"},
		[]bool{true, true, false, true},
	)
	b.Field(1).(*array.StringBuilder).AppendValues(
		[]string{"1", "2","1", "2","1", "2","1", "2","1", "2"},
		nil,
	)

	var r io.Reader
	r = strings.NewReader("Object Apache Arrow")
	rr, err := ipc.NewReader(r, ipc.WithSchema(schema), ipc.WithAllocator(mem))
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(rr)
}
```

**Comment by emkornfield** [comment]
@hunght3101 I would recommend maybe looking at the [unit tests](https://github.com/apache/arrow/blob/master/go/arrow/ipc/stream_test.go) I still believe the problem is  `r = strings.NewReader("Object Apache Arrow")` this line is producing an reader with invalid arrow data.  If you are still having problems please send an email (not a github issue  to [user@ email list](https://arrow.apache.org/community/) you will need to subscribe first to send an e-mail.

**Comment by hunght3101** [comment]
` subscribe first to send an e-mail`
Sorry, because the first time use github. Please guide me know-how !

**Comment by hunght3101** [comment]
@emkornfield 
Excuse me, i know `r = strings.NewReader("Object Apache Arrow")` is problem. But i dont know to input right to it.
Please re-open this issues ?

**Comment by cyb70289** [comment]
> ` subscribe first to send an e-mail`
> Sorry, because the first time use github. Please guide me know-how !

@hunght3101, mail list is the preferred way for issues discussion. You can simply click the `subscribe` link at page https://arrow.apache.org/community/ to subscribe to user@ mail list. Then send email to the community about your issues.
