### ISSUE TITLE
[Golang] How i create input format for IPC Reader?

### ISSUE THREAD

**Issue by hunght3101** [apache/arrow#9737]
Sorry, i am going to subscribe

In library
```
// NewReader returns a reader that reads records from an input stream.
func NewReader(r io.Reader, opts ...Option) (*Reader, error) {
	return NewReaderFromMessageReader(NewMessageReader(r), opts...)
}
```
How i create parameter `r` right when i call NewReader function ?
Example : 
```
var r io.Reader
r = strings.NewReader(input)
rr, err := ipc.NewReader(r, ipc.WithSchema(schema), ipc.WithAllocator(mem))
	if err != nil {
		fmt.Println(err)
	}
```
How i create input ?

**Comment by zeroshade** [comment]
The input should be an IPC stream coming from either a file or from some other source. One way to do so would be to use the ipc.NewWriter to construct a writer and write `array.Record` objects to it, then use the resulting output.

**Comment by emkornfield** [comment]
Closing.  Please if there are follow-ups let's discuss on the user@ mailing list.  One nice addition might be some canonical documentation on how to use the Go API if one doesn't exist already.
