### ISSUE TITLE
Arrow C++ library not available

### ISSUE THREAD

**Issue by ticlazau** [apache/arrow#9747]
Hello,

I am installing arrow in Rstudio docker container with
`> install.packages("arrow")`
But after the installation I am getting this:

```
> library(arrow)
Attaching package: ‘arrow’
The following object is masked from ‘package:utils’:
    timestamp
> arrow_info()
Arrow package version: 3.0.0
Arrow C++ library not available**
```
My environment is:
```
> version
               _                               
platform       powerpc64le-conda_cos7-linux-gnu
arch           powerpc64le                     
os             linux-gnu                       
system         powerpc64le, linux-gnu          
status                                         
major          3                               
minor          6.3                             
year           2020                            
month          02                              
day            29                              
svn rev        77875                           
language       R                               
version.string R version 3.6.3 (2020-02-29)    
nickname       Holding the Windsock 
```

Is something I am missing? or arrow is not supported on R using the ppc64le architecture?

Rgds,
FM

**Comment by emkornfield** [comment]
CC @nealrichardson

**Comment by nealrichardson** [comment]
We don't test the R package on ppc64le so I don't know whether it builds. To find out what's going on, you'll want to try installing again with the env var `ARROW_R_DEV=true` set and then share the verbose build output--preferably on JIRA, where we track issues like these. See also https://arrow.apache.org/docs/r/articles/install.html#troubleshooting.

If you have a public docker image of this setup, we could potentially add it to our continuous integration and ensure that it passes going forward. See https://arrow.apache.org/docs/r/articles/install.html#contributing.

**Comment by ticlazau** [comment]
Hello @nealrichardson 
I am using the R Docker image from here: https://hub.docker.com/r/ppc64le/r-base
But the docker file can be found here: https://github.com/rocker-org/rocker/blob/6e6287d3c991ee7ff35e7d0c99ba70babc196cdc/r-base/4.0.4/Dockerfile

I will try to compile as indicated, however is not working in R interactive mode.
[install-arrow-on-R-ppc64le.txt](https://github.com/apache/arrow/files/6204328/install-arrow-on-R-ppc64le.txt)

See attached the full output of: install.packages("arrow") in R.

**Comment by nealrichardson** [comment]
From your logs: 

```
> ARROW_R_DEV=true
Error: object 'true' not found
```

That should be an environment variable (`Sys.setenv()` if you're doing this from R). Since you already have the limited version of `arrow` installed, you can do the same with just `arrow::install_arrow(verbose = TRUE)`. 

Since it looks like we're going to have some more back and forth to diagnose the issue, I've made a JIRA issue for this: https://issues.apache.org/jira/browse/ARROW-12085 Let's continue over there.
