### ISSUE TITLE
Reading a parquet with timestamp out of bounds in pandas

### ISSUE THREAD

**Issue by guidocioni** [apache/arrow#9781]
Hi,
I'm using `pandas` to read a parquet file which unfortunately has some timestamps in the year 2500. Of course this causes problem `Casting from timestamp[us, tz=UTC] to timestamp[ns] would result in out of bounds timestamp: 16740777600000000`. 
There should be an option in `read_table` with `safe = False` which would coerce these timestamps to be `NaT` which would be the ideal solution but unfortunately there is nothing in the official documentation. 
Right now I'm blocked as I cannot modify the original parquet file (as I cannot open it).
Is there any workaround to somehow filter out these values before reading it into pandas?

**Comment by emkornfield** [comment]
Hi @guidocioni,
You could probably read the data into an [arrow table](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.read_table.html?highlight=read_table#pyarrow.parquet.read_table) and use the `timestamp_as_object` object when calling [`to_pandas`](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html?highlight=to_pandas#pyarrow.Table.to_pandas) then do the filtering yourself.  

In general, we prefer to answer questions on the [user@](https://arrow.apache.org/docs/developers/contributing.html#join-the-mailing-lists) or if appropriate dev@ mailing list to answer questions.  So I'm going to resolve this issue for now.
