### ISSUE TITLE
[Question] How to integrate into a Flutter application?

### ISSUE THREAD

**Issue by scheung38** [apache/arrow#9829]
How to integrate into a Flutter mobile app

thanks

**Comment by emkornfield** [comment]
More details would be useful.  There aren't native dart bindings for Arrow but there are javascript ones that might be useful.  There was some interest in JIRAs on trying to make a native Dart implementation.  

We prefer to manage discussion on the user@ or dev@ [mailing lists](https://arrow.apache.org/docs/developers/contributing.html) so going to close this issue for now.
