### ISSUE TITLE
Running multiple aggregate functions on large number of parquet/feather 

### ISSUE THREAD

**Issue by svittapu** [apache/arrow#9900]
Hi .. I am trying to compute several aggregate functions on one or more columns on a large dataset which doesnt fit into memory. What is the suggested approach to doing these computations in single pass?

**Comment by emkornfield** [comment]
Hi @svittapu, 
We prefer to have conversation like this on the [user@](https://arrow.apache.org/community/) mailing list.  If you do start a thread there including what the target language is could be useful, and more specifics about the problem.  This is a very generalized/vague problem statement.

Thanks.
