### ISSUE TITLE
Read parquet via row indexes to support chunking?

### ISSUE THREAD

**Issue by aiqc** [apache/arrow#9932]
Hi there. Is there a way to selectively read a subset of a Parquet file by way of row (aka index) range? Not seeing it in `pyarrow.parquet.read_table` and there are questions about it:

- https://stackoverflow.com/questions/64050609/pyarrow-read-parquet-via-column-index-or-order
- https://stackoverflow.com/questions/62252259/pandas-read-write-parquet-data-using-column-index

Right now I just read the entire file into memory, which won't be feasible on larger datasets, and then drop the rows I don't need.
```python
df = pd.read_parquet("my_file.pq")
df = df.iloc[samples_indices]
```

I feel like I could do this with Spark, but don't want to add that dependency.

---

Ideally it would look something like:
```python
pq.parquet.read_parquet(index_start: 0, index_stop: 99, boundaries:"inclusive")
pq.parquet.read_parquet(index_start: 100, index_stop: 199, boundaries:"inclusive")
pq.parquet.read_parquet(index_start: 200, index_stop: 299, boundaries:"inclusive")
```
Or there would be a way to just read this as a generator:
```python
pq.parquet.read_generator(chunk_size:100)
```

**Comment by emkornfield** [comment]
Hi @aiqc 

As of pyarrow 3 reading as a generator should be [possible](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetFile.html#pyarrow.parquet.ParquetFile.iter_batches)

Also we try to use the appropriate mailing lists [user@ and dev@](https://arrow.apache.org/community/) to answer questions instead of github issues.

**Comment by emkornfield** [comment]
You can also use [pyarrow datasets](http://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html?highlight=parquet%20filter) to push some level of filtering down the stack.

**Comment by aiqc** [comment]
@emkornfield thank you. The 'github issue template' was a bit ambiguous about where to ask.
