### ISSUE TITLE
[Rust][DataFusion] Modulus operator

### ISSUE THREAD

**Issue by gangliao** [apache/arrow#9935]
What's the challenge of the modulus operator? SIMD?

```rust
        Operator::Modulus => {
            return Err(DataFusionError::NotImplemented(
                "Modulus operator is still not supported".to_string(),
            ))
        }
```

**Comment by emkornfield** [comment]
Hi @gangliao 

I would guess, nobody has time to do it yet.  It looks like there is an open issue to do so: https://issues.apache.org/jira/browse/ARROW-9829?jql=project%20%3D%20ARROW%20AND%20text%20~%20modulus

We prefer to handle questions on the appropriate [mailing list](https://arrow.apache.org/community) (user@ or dev@), if you have questions.  If you would like to contribute an implementation I'd suggest chiming in the on the JIRA (if you are concerned about SIMD or other issues starting a thread on the mailing list might make more sense).
